
== THE BIRTH OF THE LORD — Luke 2:1-20

=== Introduction

Although the Christmas lesson follows in order here, it probably will be studied separately, making it necessary to tell the classes that you are interrupting your regular sequence just for the Christmas lesson and that you will go back to it next Sunday. Be sure that they know what the next lesson will be. Then tell them that the Lord came into the world many hundred years later than the time about which they have been studying.

=== Doctrinal Points

The New Testament is the fulfillment of the Old.

If the Lord had not come in the fullness of time mankind would have destroyed itself.

The Lord must be born in our "Judea" (hearts), grow up in our "Galilee" (outer lives), and frequently pass through our "Samaria" (thoughts).

=== Notes for Parents

We all know that the Advent of the Lord made such a change in the world's history that eventually the calendar was changed to date from it. This alone should prove to us that Jesus was not a man like ourselves. No mere man could have accomplished what He accomplished.

Throughout the Old Testament there are prophecies that one day God Himself would come into the world. The Hebrew word Messiah, "the anointed one," was the name used by the Jews to refer to this promised savior, and the Greek word which means the same is Christ. Jesus means "Jehovah saves," and it was also said that the child was to be called Emmanuel, which means "God with us."

The Lord said that He came into the world not to condemn but to save. He took on a human nature from Mary in order that He might come in direct contact with all the temptations which we feel, and by overcoming them give us the power to overcome them in His strength as we try to follow His example. He came to show us the way to safety, happiness, and peace — the way to heaven. He came because He loves us.

Nothing was accidental about the way in which this great event took place. Every detail of the Christmas stories in Matthew and Luke has a deep meaning which the older children are studying. They are beautiful stories which we all love, and they should mean more and more to us as the years go by. We should never forget that on the first Christmas day God gave us the greatest gift of all: Himself.

=== Primary

Be sure that this class knows all the basic details of the lesson. A good plan is to ask them first what they know of the story of the shepherds, then ask them to pay close attention while you read the story from the Word, and then ask for the additional details which they did not mention at first.

Do you know whose birthday we celebrate on Christmas day?

The Lord Himself was born on that day many, many years ago.

We know, of course, that this was not the beginning of the Lord.

The Lord has lived always. He made the world and everything in it. But men needed to see Him. He had always told them about Himself and about how they must live if they wanted to be truly happy. But they had not really believed Him.

Men thought they knew enough to live without the Lord's help.

They wanted to have their own way instead of to learn from Him. So they became very selfish and very unhappy. The people who could read the Word, the scribes and Pharisees, told the others what they wanted them to do instead of what the Lord had said. So those who wanted to do right could no longer find out what really was right.

Then the Lord finally had to come into the world Himself to show people how to live.

Where was the Lord born?

What is Bethlehem called in verse 11? This is because David was born there.

Mary and Joseph were descendants of David.

Their own home was not in Bethlehem, but at this time they had traveled to Bethlehem on business.

The Holy Land had become part of the Roman Empire.

The Emperor of Rome had issued an order that everyone should be taxed, and everyone had to go to his ancestral home to be enrolled for taxation. When Mary and Joseph arrived, the city was crowded with people, and there was no room for them in the inns.

Where did they find lodging?

About how many years ago was the Lord born?

How can you remember?

The Lord came into the world to save men from evil by showing them the right way to live, making it possible for them to see and to overcome their temptations.

That is why He is called the savior.

When He was born, only a few people could be told.

This was because most people were evil and did not want to know the truth. 

What did the shepherds see?

What did the angel of the Lord tell them?

What message did the heavenly host give? 

Where did the shepherds find the Lord? 

What did they do after they found Him?

Most of the people soon forgot what they had been told by the shepherds. Who did not forget?

Sometimes at Christmas we think so much about the presents people give us that we forget the most wonderful present of all, our present from the Lord, the knowledge of our heavenly Father, which He gave us by coming into the world Himself on the first Christmas day.

The prophet Isaiah had foretold His coming long before. This is what he wrote: "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace."

=== Junior

The class will be interested to know that the Advent took place at least eleven centuries after the time of the Judges. Call attention to the fact that in the Lord's time the Holy Land had come to be divided into three parts, and on a map point out Nazareth and Bethlehem. The Juniors should remember the story of the Wise Men and also something about John the Baptist, so that a more general picture of the Advent can be discussed. They are old enough to get some idea of why the Lord came.

What great event was often prophesied in the Old Testament?

Who was born to prepare the way of the Lord?

How did he prepare it?

We celebrate Christmas because it is the birthday of the Lord Himself into the world. In Matthew 1:23 we are told that the baby was to be called Immanuel, which means "God with us." He came as a little baby and grew up as we do, so that He could feel all the weaknesses and temptations that come to us in our everyday life and show us how to recognize and overcome them. This is what makes Him our savior. We can be saved from the power of the evils that are within us if we will learn of the Lord and with His help fight against them. The name Jesus means "Jehovah saves": Christ means "the anointed one. " Anointing with olive oil pictures consecration by love. Think how much Jehovah must love mankind to have been willing to come down and live among us just to show us the way to happiness. What this has meant to the world is shown by the fact that long afterward the calendar was changed so that its years are counted backward and forward from the Lord's birth. 

Where was the Lord born?

Where was Mary's home?

Why did Mary and Joseph come to Bethlehem?

Why was the Lord born in a stable?

There are two stories about the Lord's birth which we all know well. In the second chapter of Matthew is the story of the Wise Men, who lived a long way from the Holy Land. Do you remember how they learned of the Lord's birth? They knew what the star meant because they had cherished the prophecies of the Ancient Word. They picture all people who really love to know the truth and are willing to live according to it when they find it. Some people say they love the truth, but they close their ears to any truth they do not like. The Pharisees were such people. People are really wise only when they do what truth teaches.

In our chapter for today we have the story of the shepherds. In the Word we read a great deal about shepherds, and the Lord Himself is called our shepherd. The shepherds of the Holy Land lived with their flocks, leading them from place to place to find pasture, keeping them safely in folds at night, and defending them from fierce animals even at the risk of their own lives. They knew their sheep by name and the sheep knew the voice of their own shepherd and came when he called. Sheep are gentle, harmless animals. They picture trustfulness and innocence; the word innocent comes from a Latin word meaning "not harming." People who love and cherish innocence and trust are shepherds, spiritually speaking. They may not have much knowledge of the truth, but they are close to the Lord in heart. To the shepherds in the fields of Bethlehem tending their flock on the night when the Lord was born the light which broke upon the world at His birth was not a distant star but an opening of the very heavens above them. They saw the angels and heard the glad tidings, and they did not have to go a long way to find the Lord. But we must notice that both the Wise Men and the shepherds believed at once and did go to find the Lord. This is one of the requirements of all who would be Christians: willingness to believe and readiness to act on our belief. What message did the heavenly host have for the world?

This message expresses what is in the heart of everyone in heaven and what must be in the heart of every truly good person on earth: worship of the Lord and the desire to help and serve all those around him. This is later expressed by the Lord in the two great commandments: "Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind ... And ... Thou shalt love thy neighbor as thyself." (Matthew 22:35-40) So the angels were expressing the sphere of heaven, which the Lord had come to make possible for men on earth.

What did the shepherds do after the angel message?

Where did they find the Lord?

Whom did they tell about Him?

Who remembered all they told?

=== Intermediate

The correspondence of many of the details of the story can be given, and the class should be encouraged to begin to think more deeply about the meaning of Christmas to us and to the world.

The whole of the Old Testament looks forward to the coming of the Lord into the world. The child that is promised in the prophecy in Isaiah 9:6 is to be called, among other things, "The everlasting Father." It was Jehovah Himself who was to come in the form of a child. The Jews of that day believed that this promised child, whom they called Messiah, "the anointed one," would be a mighty king who would overthrow their earthly enemies, and set up their nation as the greatest on earth.

So when He came as a lowly babe in a manger in Bethlehem, most of the people could not possibly have been made to believe that He was really their promised Messiah. Only the few simple, good people who were looking for guidance for their personal lives and the few really wise people who saw more than external meaning in the prophecies could be told of the Advent. The shepherds represent those who cherish innocence and the Wise Men those who cherish truth for the sake of life.

It was nighttime when the Lord was born (but see @AC 22).

Light is one of the representatives of truth and darkness pictures ignorance. The Lord came at a time when people were about to lose all true knowledge of Him because the religious leaders, who were the custodians of the Word, had overlaid it with their traditions. The only way in which the Lord could save men was by coming down to them in a form which they could see and touch. Moreover, the power of evil in the world had become so great that good people could no longer stand against it. Only the Lord could overcome it, and to do this He had to take on a human nature in which evil could reach and attack Him. It was because He loves us that He gave Himself to us on the first Christmas day, the most wonderful gift ever given. We should never forget, when we are thanking people for our Christmas presents, to thank the Lord for this greatest gift of all.

The fact that the Lord was born in a stable and laid in a manger pictures His coming to feed our good affections, for you remember that cattle* represent our affections for useful labor. The Lord did not come, as some of the people expected, to set them up above others, but to teach them how to serve others. Only the humble recognized Him, and only the humble really recognize Him today. With the others, whose minds are full of self, there is no room for Him, just as there was no room in the inns.

[*Although it is usual — and certainly not harmful — to associate cattle with the scene of the Lord's birth, in @AE 706[12] we read (in relation to Luke 2:12) that "a manger, as a feeding place for horses, signifies the doctrine of truth from the Word." —Editor]

The shepherds, keeping watch over their flock by night in the field near Bethlehem, represent all those simple good people who cling to kindness and goodness even when they cannot find anyone to tell them about the Lord and His truth. To such people knowledge of the savior comes as a great burst of light. They welcome it and hurry to learn more and to tell everyone else about it, just as the shepherds did. And the message of the heavenly host, "Glory to God in the highest, and on earth peace, good will toward men," expresses the very heart of heaven, love to the Lord and love to the neighbor. The Lord came into the world to teach us both by His words and by His example, that it is these two loves which make heaven both in the other world and here in this world in the heart of everyone who is willing to overcome his selfishness, learn of the Lord, and try to obey Him.

=== Basic Correspondences

manger = doctrine of truth from the Word
shepherds = those who cherish innocence
the star = guiding truth
Wise Men = those who cherish truth for the sake of life

=== Senior

The important lesson for this class is in the states of mind in us which are receptive of the Lord's entrance into our lives, as contrasted with the states which bar His entrance. The message of the heavenly host and the two kinds of people who were told of the Lord's birth gives us the picture we need.

When we realize that the Advent of the Lord, obscure as it seemed at the time, had such an effect on history that the calendar was changed to make it the central point, we wonder how anyone can imagine that He was a mere man. Yet many do so imagine.

The familiar stories of the Lord's birth picture clearly the conditions necessary to recognition of the Lord. First we must either, like the Wise Men, love and cherish truth, or we must, like the shepherds, cherish innocence and trust. In either case, we must be willing to believe and willing to act on our belief, no matter what personal sacrifices are involved.

You have perhaps heard people say, "Your belief is beautiful; I wish I could believe as you do." You might answer, "Do you really wish that? Do you wish it enough to study the grounds for our belief and, if you find them to be sound, to change your life accordingly?" This is the real test. Belief is primarily a matter of the will.

John the Baptist was sent before the Lord to prepare His way.

John the Baptist and his message picture the necessity of genuine self-searching and repentance as a preliminary to reception of the Lord. If we study the individuals to whom the announcement of the Lord's birth was made — Mary and Joseph, Zacharias and Elisabeth, the shepherds and the Wise Men, Simeon and Anna — we see that they were all looking for the Lord, open—minded to the Gospel, and ready to manifest their belief. We have to choose to believe, to be open to the reception of new truth. If instead we choose to close our minds to anything which upsets our accepted way of life, the Lord knocks at our door in vain.

Swedenborg tells us that the angels are very careful not to interfere with this freedom of ours. The message "Glory to God in the highest, and on earth peace, good will toward men" was spoken by permission and is a beautiful expression of the sphere of heaven. It makes us think of the petition in the Lord's Prayer, "Thy kingdom come, thy will be done as in heaven so upon the earth." If the Lord is truly glorified in the heart, there will be innocence and good will in the outward life. Peace is the outcome of innocence — harmlessness — and good will. The Lord is called a lamb and also the prince of peace. His spirit, received in the heart, is what leads to peace, whether in the individual life or in the life of the world. Apart from it, no external measures will bring peace.

Notice that, while the Lord was born in Bethlehem of Judea, He was brought up in Nazareth of Galilee. Here again is the same sequence, for Judea represents the plane of the will and Galilee the plane of the outer life. Between the two lay Samaria, which represents the plane of the understanding, the thought which connects will and act. We remember that during His ministry on earth most of the Lord's work was done in Galilee, but that He went up to Jerusalem periodically for the feasts, and that both going to Jerusalem and coming from it "he must needs pass through Samaria." This is a picture of what our lives should be. We begin with a desire to serve the Lord, but our good intention is not enough. We must work this intention out in active service in our outward life, and we do so by means of study and thought. What we meet in our experience in the world should lead us to go back often to a state of worship for renewal of our will to do good; and our worship, to be effective, must be the climax of a period of meditation.

The Lord came into the world on the first Christmas day in order to meet and overcome the evils which were growing so strong that even those who longed for goodness could not fight against them. He came to restore to men a true knowledge of Himself and to be our example in all things. He came as the savior of the world, but He can save each one of us only as we learn of Him and seek to follow His example, recognizing and fighting our evils in His strength. He endowed mankind with rationality and freedom of choice, which alone make us human beings instead of animals, and He cannot save any one of us against his will.

=== Adult

Discuss the necessity of the constant growth of our concept of the Lord and of our understanding and appreciation of the meaning of the details of the familiar Christmas stories. Use Isaiah 9:6 to point this up and Isaiah 9:7 to suggest the effect which this growing concept should have on our lives.

Looking back after nearly two thousand years we can see that the Lord's Advent changed the whole course of history. We all know that our calendar dates from the birth of Christ and that the Christian nations, in spite of their obvious shortcomings, are the progressive and dominant nations. The life of the Lord gave the world a new standard, a new ideal, without which spiritual life would have perished; for men, looking to themselves or to other men for wisdom, were becoming more and more confused, uncertain, and fearful. The only genuine truth in the world was in the Hebrew Scriptures, and the church of that day had so perverted these that they were no longer read with an open mind. The object of the lifelong search of Socrates was for the wise man. No man could be found who could point out the way of life.

This spiritual darkness was the night upon which the great light broke. The star which the Wise Men saw afar off and the "glory of the Lord" which shone round about the shepherds were the same light, the Lord coming into the world as the truth, "the way," "the light of the world," "a light to lighten the Gentiles," the only wise man, to whom men in all time to come could look for light and guidance. When we are little children, we love and cherish the picture of the holy babe in the manger with Mary and Joseph and the shepherds in adoration, but as we grow older every detail of this picture must be filled with deeper and deeper meaning. We begin to glimpse the tremendous significance of this seemingly obscure event which is celebrated all over the world on Christmas day, and to see that nothing less than the coming into the world of the Lord God Himself could so profoundly have affected the history of the world and the course of individual lives.

Then comes the question, "Why did so few recognize the Lord?"

This is answered for us many times in the Word. "For this people's heart is waxed gross, and their ears are dull of hearing, and their eyes they have closed" (Matthew 13:15); "And men loved darkness rather than light, because their deeds were evil" (John 3:19). Owls, which depend upon the darkness to help them surprise their prey, see in the dark and are blinded in the daytime. We can all refuse to see truths which we have not prepared ourselves to use, just as a child who has not studied his lesson or the lessons which went before it is not prepared to understand what the teacher is talking about. "God sent not his son into the world to condemn the world, but that the world through him might be saved." His light would have destroyed eyes not prepared to receive it if He had not permitted the eyes to be closed. So His Advent was accomplished in a way which represented His accommodation of Himself to men, and only those who were prepared knew of it. But the light which was at first seen by so few grew and spread and continues to grow and spread throughout the whole world.

The Lord was born in Bethlehem, the birthplace of Benjamin as well as of David. Of Himself He said, "I am the bread of life." Bethlehem means "house of bread." To each of us, when we are children or in childhood states, the Lord comes in simple instruction as to how we may be good and useful, and the beautiful story in the letter of the Word of His coming as a humble babe in the manger at Bethlehem moves our hearts. But as we pass out of our childhood states, our knowledge of the Lord and our concept of Him must grow. We are all familiar with the general correspondence of the Christmas stories: the Wise Men, those who cherish and love the truths of spiritual living; and the shepherds, the simple in heart who love what is good and innocent. These are the two classes of people who are able to recognize the Lord: those who love and cherish the knowledge of Him which they have received through the Word from their parents and teachers, as the Wise Men cherished the prophecies which they had from the Ancient Word; and those who, in the absence of knowledge of the Lord, still are humble and loving, preserving their own good innocent affections in spite of the worldliness which surrounds them, as the shepherds watched their flocks by night.

There was no room for the Lord at the inns. An inn represents a "place of instruction." The church was the only place of instruction to which men could go who wanted to learn of the Lord, but it had so perverted the precious knowledge entrusted to it that the divine truth was altogether crowded out. So the Lord was laid in a humble manger, the feeding place of horses and cattle, the few humble minds and hearts which still found some instruction for life, and He was wrapped in swaddling clothes, which represent the first simple truths which clothe our early perceptions of the Lord (@AE 706[11]).

To many it seems strange that so few people acknowledged the Lord's birth when it was accompanied by signs and wonders and when the Hebrew nation had looked forward through all its history to this very event. But we must not think that the signs and wonders were visible to everyone, though many stories based on this assumption have been written. Verses 17 and 18 of our lesson gives us a suggestion here. They make it rather evident that others knew of the shepherds' vision only as the shepherds told of it and that, while they wondered at it, only Mary really thought much about it. Belief is a matter of the will. We do not believe unless we want to. Even the Lord never forces us to believe in Him, and when He came into the world, He came in such a way that only those recognized Him who really longed for His coming and so would worship and protect the child Jesus. These few were told, each in a way that would be most assuring to him: the Wise Men, who understood something of correspondences, saw a star; the simple shepherds had in common a beautiful and awe—inspiring vision and heard the actual announcement; Mary and Joseph, Zacharias and Elisabeth were told by an angel (and the doubting Zacharias was still further impressed by being struck dumb); and Simeon and Anna were taught by a perception within their own hearts when they saw the child. Most of the people who wanted no truth which might condemn them, neither saw nor heard.

It is much the same with people today. Swedenborg tells us that the angels never try to instruct men on earth. They know that the Lord has given men the Word and leaves them in freedom to receive or reject its teaching, and that this freedom must be preserved at all costs. Only evil spirits seek to speak to men.* But at the time of the Advent the angelic host was permitted to express in one great beautiful message the very sphere of heaven: "Glory to God in the highest, and on earth, peace, good will toward men." The more accurate translation is "to men of good will." Love to God and love to the neighbor, afterward pointed out by the Lord Himself as the two great commandments, are the way to peace both for the individual and for the world. This is a message which we should ponder most deeply at Christmas time. The angel told the shepherds where to find the Lord. That is all the angels can do for us. If we are wise, we shall do as the shepherds did: go quickly to find the Lord in the manger of the letter of the Word: and we shall worship Him and tell others what we have found; and then we shall go back to our daily tasks "glorifying and praising God."

[*See, e.g., @HH 249. -Editor]

=== From the Writings of Swedenborg

@AE 706[12]: "It is said in the seventh verse of the same chapter that this was done 'because there was no place in the inn,' an 'inn' signifying a place of instruction. Because this was the state with the Jews, who were then in mere falsities, through the adulteration of the Word, this was signified by 'there was no place in the inn'; for if it had pleased the Lord He might have been born in a most splendid palace, and have been laid in a bed adorned with precious stones; but He would thus have been with such as were in no doctrine of truth, and there would have been no heavenly representation. He is also said to have been 'wrapped in swaddling clothes,' because 'swaddling clothes' signify first truths, which are truths of innocence, and which are also truths of the Divine love."

@TCR 92: "The Lord frequently says that the Father sent Him, and that He was sent by the Father ... and this He says, because 'being sent into the world' means to descend and come among men; and this was done by means of a human which He took on through the virgin Mary. Moreover, the Human is actually the Son of God, because it was conceived from Jehovah God as its Father ... He is called 'the Son of God,' 'the Son of man,' and 'the son of Mary'; 'the Son of God' meaning Jehovah God in His Human; 'the Son of man' the Lord in respect to the Word; while 'the son of Mary' means strictly the human He took on. ... In regard to the Lord, the Divine that He had was from Jehovah the Father, and the human from the mother. These two united are the Son of God. ... That the Divine Trinity — God the Father, Son, and Holy Spirit — is in the Lord, and that the Father in Him is the Divine from which, the Son the Divine Human, and the Holy Spirit the Divine going forth, will be seen in the third chapter of this work where the Divine Trinity is treated of."

=== Suggested Questions on the Lesson

Primary: What do we celebrate on Christmas day? the birth of Jesus Christ

Junior: About how many years ago was the Lord born on earth? two thousand (more or less) 

Primary: Where was He born? Bethlehem

Primary: Who was His mother? Mary

Primary: Who was her husband? Joseph

Junior: Who in a far-off country were told of His birth? Wise Men

Junior: How were they told? "We have seen his star ... "

Primary: Who were told near Bethlehem? some shepherds

Primary: Where were these shepherds and what were they doing? in the field watching their sheep

Primary: How were they told? by an angel

Primary: What did the angel tell them to do? "You will find the babe wrapped in swaddling clothes lying in a manger"

Primary: What was the message of the heavenly host? peace on earth to men of good will

Junior: Where did the shepherds find the Lord? in a stable

Junior: Whom did they tell about Him? everyone they saw

Junior: Who remembered all they said? Mary

Junior: Who was Jesus? God-with-us

Intermediate: Why did He come in to the world? to save us from our sins

Senior: What did He accomplish for us? redemption, making salvation possible for all

