ifndef::fullbook[]
= Sermons on Joshua
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 01. The Great Commission (1:1-9)

The first reading that we’ll start with is from the book of Joshua,    verses 1-9.

  And it happened after the death of Moses the servant of Jehovah,
  Jehovah spoke to Joshua the son of Nun, Moses’ minister, saying, My
  servant Moses is dead. And now rise up, cross over this Jordan, you
  and all this people, to the land which I am giving to them, to the
  sons of Israel. Every place on which the sole of your foot shall
  tread, I have given it to you, as I spoke to Moses. From the
  wilderness, and this Lebanon, even to the great river, the river
  Euphrates, all the land of the Hittites, and to the Great Sea toward
  the setting of the sun, shall be your border. No man shall be able
  to stand before you all the days of your life. As I was with Moses,
  so I will be with you. I will not fail you nor will I forsake you.
  Be strong and brave. For you shall cause this people to inherit the
  land which I swore to their fathers to give to them. Only be strong
  and very brave, so that you may take heed to do according to all the
  Law which Moses My servant commanded you. Do not turn from it to the
  right or to the left, that you may act wisely wherever you go. This
  book of the Law shall not depart out of your mouth, and you shall
  meditate on it by day and by night, so that you shall be on guard to
  do according to all that is written in it. For then you shall
  prosper your way, and then you shall act wisely. Have I not
  commanded you? Be strong and brave. Do not be afraid or discouraged,
  for Jehovah your God is with you in all places where you go.

  And coming up Jesus talked with them, saying, All authority in
  Heaven and on earth was given to Me. Then having gone, disciple all
  nations, baptising them into the name of the Father and of the Son
  and of the Holy Spirit, teaching them to observe all things,
  whatever I commanded you. And, behold, I am with you all the days
  until the completion of the age. Amen. (Matthew 28:18-20)

  ‘the land of Canaan’ represents the Lord’s kingdom in heaven and on
  earth becomes clear from many things in the Word. The reason it does
  so is that the representative Church was established in that land, a
  Church in which every single thing represented the Lord and the
  celestial and spiritual things of His kingdom. This applied not only
  to religious observances but also to everything associated with
  those observances – to both the persons who ministered and to the
  things they administered, and even to the places where the
  ministrations took place because the representative Church was
  centred there the land was consequently called ‘the Holy Land’, even
  though it was anything but holy, seeing that idolaters and profaners
  inhabited it. (Arcana Coelestia 1437)

  All the historicals of the Word, as well as its prophetical parts,
  contain a spiritual sense that treats, not of the sons of Israel and
  of nations and peoples, but of the church and its establishment and
  progress, for this is the spiritual of the Word, while the history
  is the natural that contains the spiritual…”the land of Canaan,”
  into which the sons of Israel were brought, signifies the church,
  and “Jordan” signifies the first entrance into it; and “the waters
  of Jordan” signify truths that introduce into it, which are such as
  those of the literal sense of the Word, for those are what first
  introduce. (Apocalypse Explained 700)

We begin a new series today in which we look at the book of Joshua.
This book deals with the conquest of Canaan by the Israelites, under
Joshua as their leader. After the death of Moses, Joshua is appointed
by Jehovah to lead the people of Israel to complete this task. We
should note from the outset that the name Joshua and Jesus are the
same. Je-ho-sua and Je-shua both mean “Jehovah is Salvation“. Moses had
led the sons of Israel out of Egypt from under the dominion of Pharaoh;
he received the law from Jehovah and delivered this to the Israelites.

By and large we can view the Moses period of leadership as a period of
instruction from the Word in spiritual matters. The leadership under
Joshua marks a change of state where what has been learnt under Moses
now needs to be applied to life. Spiritually, when we read of death in
the Word it indicates a movement from one state to another. So death in
the Word doesn’t actually mean death, rather, it means new life or the
coming into being of a new state of life as the old one passes away.

In the New Testament we can see a parallel of this change of state from
Moses to Joshua in the life of the Lord in relation to His disciples.
The Moses period can be seen in that period of the Lord’s life when He
was largely engaged in teaching or giving instruction to His disciples
up to His death. The Joshua period for the disciples begins after His
resurrection and this can be seen in the similarity between the
commissioning of Joshua and what has come to be called the Great
Commission given to the disciples.

Both are commands to go forth and conquer or bring all things under the
rule and authority of what the Word teaches. Therefore, in this series
that we are about to embark on, the Book of Joshua is to be viewed as
holding the detail of what the Great Commission found in the New
Testament actually involves. The Great Commission is first and foremost
a call to the path of inner spiritual growth or regeneration, through
taking the instruction we have received in spiritual things and
applying it to life. If we would do that then we would find that life
would present us with opportunities to share with others the good
things that the Lord has imparted into us in ways in which the deeper
spiritual needs of people can be truly met.

In order to respond to the Great Commission to take the Gospel out to
all nations effectively, we need to appreciate that the responsibility
that falls on the greater Church, falls onto the personal individual
level of the Church first, and that it is the quality of the work done
by individuals who make up a spiritual community that governs the
spiritual quality of that community’s efforts to reach out and impact
the lives of others around them for good.

This is a sobering thought; our personal individual effort to live from
the Word is the most important contribution any one of us can make to
the health and wellbeing of this collective spiritual community. Our
effort to read the Word, to study the doctrines for Spiritual
Christianity and apply them to life on a personal level sets the ground
for being able to contribute in a powerful way to the health and
wellbeing of the community as well as in the other communities we are
in contact with in our wider spheres of influence.

So work on ourself is important because it’s the means by which the
Lord can be more fully present in our world. It’s the means by which we
can develop spiritual sensitivity to the spiritual needs of others. It
is also the way in which real empathy and compassion for others is
developed. It’s the way by which possibilities are created to build
bridges of trust over which genuine spiritual connections can be made.
For it is through work on ourselves in response to the Word that we are
able to support others in their spiritual growth and development, and
it is in this ability to support one another that a true spiritual
community or a collective expression of the church can come into being.

The land of Canaan represents the human mind or the ground out of which
the affections and thoughts belonging to celestial and spiritual
matters arise. This is why it corresponds to the Church, because the
Church is nothing other than celestial and spiritual things, or goods
and truths made manifest in human consciousness as good affections and
true thoughts which motivate and enable a person to express themselves
in loving actions. The goal of the spiritual life on a personal level
is to become an individual church through having what is unloving and
untrue removed from our life.

Joshua represents the transition from knowing to becoming, or from
having an intellectual interest in spiritual matters to using this
knowledge as a means of examining the quality of ones life. Moses and
Joshua represent the Word at different stages of a person’s spiritual
life. There is a time for learning the stories of the Word and what the
doctrines for Spiritual Christianity teach, and this is what is meant
by Moses, but there comes a time when the Lord no longer speaks to us
through Moses, when the approach represented by Moses dies and no
longer can sustain us. At this point the emphasis shifts and the voice
of Lord is heard through Joshua or the application of the Word to life.

Our spirituality must become practical. But by practical we don’t mean
a focus on the level of life found in the external or natural world.
The practical application of spiritual truths has to do with their
application to the inner world of the life of the mind. It is the life
or quality of our affections and thoughts that form the practical
dimension of spiritual work. And it is only by attending to this level
of life that our external activities in the world can take on a
spiritual quality. All external expressions of love take their quality
from the internal quality of the mind from which they come.

This is why Spiritual Christianity directs a person’s attention to
reflection on their inner mental life and activity. This in no way
diminishes the need to attend to external matters, to act faithfully
and justly in all that we do, however this is done in order to bring a
degree of stability into the externals of life, so that the internal
things can then be attended to while being fully engaged in the
externals as well.

So we read…

  My servant Moses is dead. And now rise up, cross over this Jordan,
  you and all this people, to the land which I am giving to them, to
  the sons of Israel.

The Word that comes to us in the Joshua state brings us to a
realisation that the ways of the past are no longer able to take us on
into what lies ahead. Moses is dead. The time of external instruction
is over, and a more internal state of application of the Word is being
urged. This is seen in the instruction, “And now rise up, cross over
this Jordan…” To speak of rising up spiritually means to turn inwardly
to what is deeper. At the same time Joshua is told to “cross over“, a
phrase that speaks of a transition, of a crossing over from one state
to another, and that transition involves crossing over the Jordan
River.

The river Jordan made up one of the boundaries of the land of Canaan.
Now a boundary forms a border between what lies within and what lies
without. And because Canaan corresponds to that part of the human mind
specifically related to a person’s understanding of spiritual things
formed from goods and truths of the Word, the river Jordan must
correspond to a stream of knowledge related to the Word itself. The
river Jordan corresponds to the Word understood according to its
literal meaning. And as the literal meaning of the Word forms a
boundary, it is something that must be “crossed over” if we are to gain
access to the spiritual meaning of the Word that is able to save us
from our ego or proprium’s dominance over the life of our affections
and thoughts.

Now this crossing over or transition from a literal understanding of
the Word to a spiritual understanding of it can only occur when we are
willing to examine our internal life with a view to repentance – to
working to have our thinking and feeling structures changed. This is
what the phrase, “And now rise up, cross over this Jordan…” means. It
is the Word admonishing all people to look to the inner things of life,
an invitation to go beyond the mere surface things of religion and
begin to explore its depths in relation to what’s going on within their
own life.

The external things of religion have to do with buildings, sacraments,
rites, rituals, priests or ministers, and services etc, but none of
this forms the essence of true religion, they are merely representative
elements that keep the idea of religion alive on the most external
plane of life. The truly religious life is found in a person’s
willingness to acknowledge the Divine and to freely respond to their
understanding of truth for no other reason than that it is the right
thing to do, or the right way to live and be in life.

When this attitude is taken up then a person begins to view their
affections and thoughts to discover their quality using the Word. Self
examination by means of the Word is described by verse 3 where it says
that…

  Every place on which the sole of your foot shall tread, I have given
  it to you, as I spoke to Moses.

Joshua is the Word that saves us and the sole of its foot is the
literal sense which contains the spiritual sense. When we take hold of
the Word and look to the Lord to reveal those things that are opposed
to the spiritual life in order to have them removed, even as we are
doing as we look into the book of Joshua, then the literal sense or the
lowest or most external aspect of the Word, which is here called, “the
sole of your foot” or “the sole of Jehovah Saviour’s foot“, is brought
into contact with the states of our mind, which is the ground the Word
treads upon. Thus by means of literal sense of the Word understood in
the light of the principles of Spiritual Christianity, our states of
mind are exposed to spiritual truths by which the mind can be reclaimed
by the Lord from the dominance of self centred affections and false
perspectives of the proprium.

This is the story of Joshua. It’s the story of the regeneration of the
human mind, a story of battles and of riding into the interior land of
the mind where the things that oppose the life of heaven can be
encountered. This is the Great Commission given to all those who would
be the Lord’s disciples. And for this work the Lord says…

  Have I not commanded you? Be strong and brave. Do not be afraid or
  discouraged, for Jehovah your God is with you in all places where
  you go.

 