ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 02. Preparations For Entering The Land (1:10-18)

  Then Joshua commanded the officers of the people, saying,
  Pass through the camp and command the people, saying, Prepare food for you. For within three days you are crossing this Jordan to go in to possess the land which Jehovah your God is giving to you, to possess it. 
  And Joshua spoke to the Reubenites, and to the Gadites, and to the half tribe of Manasseh, saying,
  Remember the word which Moses the servant of Jehovah commanded you, saying, Jehovah your God has given you rest, and He has given to you this land.
  Your wives, your little ones, and your livestock shall remain in the land which Moses has given to you beyond the Jordan. But you shall cross over armed before your brothers, all the mighty warriors, and shall help them,
  until Jehovah has given rest to your brothers, as well as to you, and they, even they have possessed the land which Jehovah your God is giving to them. Then you may return to the land of your possession, and may possess it, which Moses the servant of Jehovah has given to you beyond the Jordan toward the rising of the sun.
  And they answered Joshua, saying, We will do all that you command us; and we will go everywhere you shall send us.
  According to all we heard from Moses, so we will listen to you. Surely Jehovah your God is with you, as He has been with Moses. Whoever rebels against your mouth, and will not listen to your commands in all that you say to him, he shall die. Only, be strong and brave. (Joshua 1:10-18)

  But He said to them, I have food to eat which you do not know. Then the disciples said to one another, No one brought Him food to eat? Jesus said to them, My food is that I should do the will of Him who sent Me, and that I may finish His work. (John 4:32-34)

  Joshua commanded, Pass through the middle of the camp, and command the people saying, Prepare provisions for yourselves, for within three days you will be crossing this Jordan to go and take possession of the land. 'The crossing of the Jordan' represented the introduction of the children of Israel, that is, of the regenerate, into the Lord's kingdom, 'Joshua', who led them in, representing the Lord Himself. (Arcana Coelestia 901)

  In the internal sense 'food' means, strictly speaking, those things which nourish a person's soul, that is, which nourish him when his bodily life is ended. For when this is ended his soul or spirit is living, and he no longer needs material food as he did in the world; but he does need spiritual food, which consists in everything that has a useful purpose and everything leading to this. That which leads to what has a useful purpose is knowing what goodness and truth are; and that which has such a purpose is the desire to realize these in actions. These are the things with which angels are nourished and which are therefore called spiritual and celestial foods. A person's mind -- the place within him where his will and understanding, that is, his intentions or ends in view, reside -- is nourished by no other kind of food, even while he lives in the body. Material food does not extend as far as that; it extends only to his bodily parts, which are sustained by that material food to the end that the mind may be sustained by food for the mind while the body is sustained by food for the body, that is, to the end that there may be a healthy mind in a healthy body. (Arcana Coelestia 5293)

Last time we spoke about what was spiritually represented by the change of leadership to Joshua following the death of Moses. We saw that this shift represents a shift in the state of mind of a person when they move from being led by an affection for knowledge in regard to the things of the Word, to being lead by an affection for applying its spiritual principles to their inner mental life, to their thought and feeling life . Joshua represents the understanding of the Word that arises when we look to bring it into connection with the inner activity of our minds through the work of self examination and reflection with a view to making changes in response to what is revealed.

This is an important point and should not be lost on us. The understanding of the Word that is represented by Joshua only comes into existence for us when we make a real effort to do inner spiritual work on ourselves. It's a basic spiritual law that we are given only what we need and what we need is governed by what we are prepared to do with what we already have. The Word and the doctrines for Spiritual Christianity are food, they are bread for our inner man and in order to benefit from the goodness that exists within them we have to take them into our life. This is done by reading and studying them with a view to having them govern the inner and outer dimensions of our life. They are food for the spiritual man because the spiritual man is our mind and the mind is built up through feeding on ideas and concepts that support its desires. Food of a nourishing spiritual quality is therefore ideas and concepts that support useful spiritual ends, which Spiritual Christianity identifies as love to the Lord and love to our neighbour.

So, living a spiritual life requires us to respond to the Word in order that spiritual food might be prepared for our inner life. So we read in verse 10-11 that…

  …Joshua commanded the officers of the people, saying, Pass through the camp and command the people, saying, Prepare food for you. For within three days you are crossing this Jordan to go in to possess the land which Jehovah your God is giving to you, to possess it.

This whole process which we are undertaking in seeing how the Scriptures can be understood so that they can be applied to a more internal approach to spiritual life is what it means to “Prepare food”.
Notice that this command to “prepare food” comes from Joshua and is given to “the officers” who in turn are to pass it on to “the people”.
Joshua, as we have seen, represents the Word and as such is that through which the Lord makes Himself known. How we understand the Word or interpret it depends on the spiritual teachings we hold to, or our doctrine. The term “officers” in this verse can also mean scribes, and this fits for it is our doctrine that determines how the Word is inscribed onto our understanding.

So by the Word stating that “Joshua commanded the officers” it teaches that the Word is understood according to the doctrine a person holds.
If the spiritual teachings we hold to emphasizes an inner focus and application then this is how the Word will be understood. On the other hand if it is focussed more on the literal meaning then what will be seen as important will be things that have more to do with outer life.
This is why so much of the Bible can mean different things to different people. Spiritual Christianity takes an inner focus in regard to its application of Biblical truths to life.

Some of those who take a more literal view of the book of Joshua, for example, hold to doctrines that use its contents as justification for the existence of a Jewish state in the world. Therefore they read its stories and interpret them in a way that supports this view. The doctrines for Spiritual Christianity teach that all things in the Word concern themselves solely with spiritual things and the literal text is merely a container which when spiritually understood, is seen to open up, in detail, the inner processes concerning the spiritual regeneration of the human mind.

So when we come to the book of Joshua and apply the principles of Spiritual Christianity, we find ourselves being instructed by the Word or Joshua to prepare food of a spiritual nature and quality so that we might begin this inner journey which leads to the mind, or land of Canaan, being transformed from a image of hell into an image of heaven.

The particular quality of food that needs to be prepared for this inner journey can only come into being as the officers or scribes or principles of Spiritual Christianity are able to pass through the camp or host. Now the Hebrew term 'camp' or 'host' is a term that refers to things of a military nature. In the inner world of the mind militant things have to do with the ideas that we defend our position with or the arguments which we use to attack what comes against us. So this camp or host as far as our internal man is concerned is made up of all the portions of the literal sense of the Word that contain truths that we have gathered up and are 'camped' in our memory.

Now whilst the leadership of Moses, is represented the processes of spiritual instruction whereby we have the gathering of the host into the mind or memory, the state of mind represented by Joshua, is one of having this host organized into a force able to defeat what stands against what is good and true. This requires doctrine or teachings that enable us to see how the stories of the Word can be applied to this task, and these teachings are what we find in the doctrines for Spiritual Christianity and so they offer us the means for which our mind might be reformed and ordered.

The process of ordering our mind as far as our understanding of the Word is concerned requires the officers to “pass through the camp.” In other words, we need to bring our understanding of the doctrines represented by the officers when we read the Word, in an effort to understand its more internal application for us. In its most simple internal application, the statement concerning the officers being commanded to pass through the camp is a command from the Lord as the Word to us, to use the principles of Spiritual Christianity to bring order to our understanding of the Word. And it is this inner or spiritual understanding of the Word that is able to sustain us and so serve as food for the journey into our own personal land of Canaan.

We can further confirm that this is indeed what is meant here for the word “through” in the phrase “pass through the camp” means 'the centre'
or 'the inward part' and is often used in the Word to refer to the inner faculty of a persons thoughts and affections (see Psalm 39:3; Psalm 55:4). It is also the same word used when the Lord promised to place His law in the inward parts of His people (Jeremiah 31:33; also Ezekiel 11:19; 36:26).

  Behold, the days come, says Jehovah, that I will cut a new covenant with the house of Israel and with the house of Judah, not according to the covenant that I cut with their fathers in the day I took them by the hand to bring them out of the land of Egypt (which covenant of Mine they broke, although I was a husband to them, says Jehovah). But this shall be the covenant that I will cut with the house of Israel: After those days, declares Jehovah, I will put My Law in their inward parts, and I will write it on their hearts; and I will be their God, and they shall be My people. (Jeremiah 31:31-33)

While it is the Lord who implants the law into our inner man, it is not done without our co-operation. The Lord writes His laws on our inward being as we use the Word, or Joshua and the officers or doctrines, to transform our understanding of the literal stories of the Text,
represented by the people, into a form that can support our inner spiritual growth and development and so serve as food for our minds. It is this that leads to the development of a state of mind that enables the crossing of the Jordan and entry into the land.

So the question now is what does the Jordan spiritually represent? Last time we saw that the River Jordan forms a border between what stands outside the land of Canaan and what lies within it. In general we can say that the land of Canaan represents that part of the human mind that is largely concerned with internal things of the Church, or those things of the Church that belong to the internal man. This being the case then we can see that the lands mentioned in the Word which fall outside of its border's, particularly where they hold some sort of connection with the people of Israel, must represent the things of the Church that are more external in nature, and so belong to the external man. Now by the things of the Church we don't mean those things belonging to any external organisation, rather we mean those things to do with our understanding of the Word. The Word itself is what makes up the things of the Church, and so we find the teaching in the doctrines for Spiritual Christianity that a Church is only a Church in accordance with its understanding of the Word.

The Word has an external and an internal aspect to it. The external aspect, which is its body, is accommodated to the natural understanding of people and is what we call its literal sense. The internal aspect,
its spirit or soul, lies within the external and we call this its spiritual sense. To prepare food for the crossing of the Jordan is to make the necessary preparations that can support us to move beyond the fallacies of our senses or the surface meaning that arises from reading the Word literally. To do this we need to know that this deeper meaning exists, for without knowing this we won't seek to find it. We also won't seek it if we can't see why acquiring this deeper understanding of things is important. This is where the understanding provided in the doctrines for Spiritual Christianity is vital; for these give us the ability to see that there is a deeper meaning in the Scriptures and the purpose for which it is given.

So in preparation for this crossing over into the more interior things of life we need to motivate ourselves to…

1. Read the Word

2. Learn about the principles of Spiritual Christianity

3. Use these principles to build our understanding of the Word's application to the life of our minds

4. Make an effort to use this understanding in working with the Lord to have the evils and falsities we recognise in our life removed.

If we do this, if we give spiritual things a priority in our lives, then the internal things of heaven will begin to appear more fully present in our consciousness and impact on our states of life in a real way for the good of all. This is because the internal things of heaven can only become more conscious to us as those things in our external man that are opposed to heaven are removed. The key then, to understanding the inner meaning of the Scriptures, is to work on oneself to have these things removed. We may know the Word, we may know the principles of Spiritual Christianity but unless we use them and apply them to our life, then by this knowledge can't help us. For it is in our willingness to work with them that they come together as a fighting force ready to defend what is of heaven within us. That first force of real inner change is described here as the Reubenites, the Gadites and the half tribe of Manasseh, things we will consider in more detail next time.

