ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]

---
ifdef::fullbook[]
<<<
endif::[]


== 03. Bringing Reuben, Gad And Manasseh To The Fight (1:12-18)

____
And Joshua spoke to the Reubenites, and to the Gadites, and to the half tribe of Manasseh, saying, 
Remember the word which Moses the servant of Jehovah commanded you, saying, Jehovah your God has given you rest, and He has given to you this land.
Your wives, your little ones, and your livestock shall remain in the land which Moses has given to you beyond the Jordan. But you shall cross over armed before your brothers, all the mighty warriors, and shall help them,
until Jehovah has given rest to your brothers, as well as to you, and they, even they have possessed the land which Jehovah your God is giving to them. Then you may return to the land of your possession, and may possess it, which Moses the servant of Jehovah has given to you beyond the Jordan toward the rising of the sun.
And they answered Joshua, saying, We will do all that you command us; and we will go everywhere you shall send us. According to all we heard from Moses, so we will listen to you. Surely Jehovah your God is with you, as He has been with Moses.
Whoever rebels against your mouth, and will not listen to your commands in all that you say to him, he shall die. Only, be strong and brave. (Joshua 1:12-18)
____

(see also Numbers 32:16-25)

  In general the twelve tribes meant everything constituting the doctrine of truth and good, that is, of faith and love; for these -- that is to say, truth and good, or faith and love -- constitute the Lord's kingdom, since what are essentially matters of truth or faith constitute the whole of thought there, and what are essentially matters of good or love constitute the whole of affection. And because the Jewish Church was established so as to represent the Lord's kingdom, the divisions of that people into twelve tribes therefore meant those things of His kingdom. This is an arcanum which has not previously been disclosed.
  [2] Twelve means all things in general, as shown already in 577, 2089, 2129, 2130 (end), 3272, while 'tribes' means matters of truth and good, or of faith and love, so that 'the twelve tribes' means all of these.
 (Arcana Coelestia 3858)

Last time in our look at the book of Joshua we discussed the need to make preparations in readiness to enter the land and of what this means for us so that we can be made ready for our entry into a greater sense of the spiritual dimension to our life. We saw this in the idea expressed in the story as a command that the children of Israel _prepare food_. Today we will be looking at another aspect of preparation mentioned here which involves three tribes who have already been allocated their portion of land on the eastern side, or the side that stands outside that border of the Jordan River. These tribes are the Reubenites, the Gadites and the half tribe of Manasseh.

The first thing we need to establish in regard to the details being expressed here has to do with what the tribes of Israel represent in us. What we know is that people of Israel were divided into twelve tribes, with each tribe being descended from one of the sons of Jacob, who if you recall underwent a change of name and became Israel.

Everything in the Word in its deeper meaning relates to those things that belong to the process of mental development which are associated with peoples' spiritual awareness. In the Old Testament the universal principles, processes and issues of spiritual development are illustrated and represented in the lives of the various characters and peoples we find there. Jacob's life represents a state of mind that is experienced as we struggle to make spiritual realities more real in our daily life.

He represents a stage of spiritual life when we are very much reliant on our own efforts to take hold of spiritual things and make them our own. This is one aspect of the meaning of his name, for Jacob means "_supplanter_". This is because the stage of spiritual development that he represents is one where spiritual things are more something of the head than the life. Our relationship to them is more one of the intellect than of the heart, or if you like, there is an emphasis on ideas and concepts of truth, rather than the good that comes from applying these to our life. In this phase of development, truth can be said to have supplanted good, because a person's interest and focus is on ideas that may or may not have an obvious practical application. It is a necessary phase however as knowledge of spiritual things must first be acquired in order for there to be something within us that the Lord can use to motivate us to move from that knowledge to a focus on _how_ that knowledge can be used for the benefit of others.

The growth of ideas and concepts about spiritual things, represented by the Jacob phase of our life, leads to their reworking in our minds as we think about them and draw new connections and insights. New ways of seeing things that relate to the development of our spiritual awareness are born and this is represented in the Word by the birth of sons. So the sons of Jacob represent all the various arrangements of affections and ideas about spiritual life which take form or are generated or born in people's minds as they look to develop a fuller sense of spirituality in their life.

What you find if you look at the story of Jacob's life is that his offspring were born to a number of different women, four to be exact.
Without going into too much detail now, we should note that where Jacob represents a particular stage of a persons developing spiritual consciousness, the women to which he was joined and bore him offspring represent the various affections that are active in the process of our spiritual development. We all have an internal and external part to our minds, and these are separate and independent, and so form two distinct levels of being. We call these the external or natural man and the internal or spiritual man. These aspects of our minds each have their own will and understanding with their particular quality of affections and thoughts. The affections of the external mind give rise to the desires and pleasures which form the motivation that we need to attend to the things of a more external nature, particularly those which are focused on supporting the internal dimension of our spiritual life.

For example, an interest in reading spiritual material such as is found in the Bible and the doctrines for Spiritual Christianity, or other books, being motivated to listen to lectures or sermons, or going to seminars and workshops, as well as attending church -- all belong to those affections for spiritual things that are found in the external man or mind. The affections belonging to the internal man/mind take their form in our experience as a motivation to take the things that our external man has acquired and apply these to the activity of our mind, to our thoughts and affections, so that we can be more effective in expressing the Lord's love and wisdom, and thus as be more effective vessels of use to others.

These two different quality of affections, belonging to the internal and external aspect of our minds, are represented in the story of Jacob's life as his two wives, Leah and Rachel. Jacob was married to Leah first and then to Rachel. Now, the general principle is that we begin in external things and move towards internal things and we see this principle reflected here in the fact that Leah, whom Jacob married first, represents an external affection for truth and Rachel his second wife, represents an internal affection for truth. So, it was these two women along with their hand maidens that bore Jacob his sons.

It's necessary for us to have this background because it gives us a context for understanding the spiritual representation of the various tribes of Israel in us as we move through the book of Joshua. Those tribes born to Jacob through Leah and her handmaid or slave girl represent those things to do with our spiritual development which belong to the external aspects of spiritual life, while those born of Rachel and her handmaid represent what belongs to the more internal aspects of our spiritual life.

So we now come back to the book of Joshua and can begin to unfold what is involved as regards our preparation for the spiritual work as represented by the sons of Israel preparing to enter the land of Canaan. The Reubenites were descendants of Jacob's first born son by Leah, who was named Reuben. The Gadites were descendants of Gad, who was born to Leah's handmaid, Zilpah. Manasseh on the other hand was actually Jacob's grandson being the son of Joseph who was one of Jacob's sons by Rachel.

The land that these particular tribes received was requested and given to them when Moses was Israel's leader on the condition that they would fight along with the other tribes to rid the land of their enemies. The lands given to the Reubenites, the Gadites and to the half tribe of Manasseh were on the other side of the Jordan, with the Jordan forming a boundary between the inheritance of these three tribes and the rest.
Now, because these tribes were located beyond or east of the Jordan they represent elements of the spiritual life that belong to the external man. We can see this from the following quote from the work the Apocalypse Explained 440 where it says that ...

  The land beyond or without Jordan represented and signified the [external church], which is with [men] in the [natural man]; 
  but the land on this side, or within Jordan, represented and signified the [internal church], which is with [men] in the [spiritual man].
 Apocalypse Explained 440[7]

"The land beyond, or without the Jordan, represented and signified the [_external things of spiritual life_] 
with [_people_] in the [_natural _mind_]; +
but the land on this side, or within the Jordan, represented and signified the [_internal things belonging to spiritual life_] with [_people_] in the [_spiritual mind_]."

So we see that these three tribes had in effect been established in their lands under Moses. The establishment of these tribes in their lands highlights the principle that the external things of spiritual life that belong to the external or natural man must become established in our life first, before we can enter into a deeper work of inner repentance. Reuben is mentioned first, because by Reuben is meant the first stages in the development of our understanding of spiritual ideas or concepts which are largely related to the literal sense of the Word.
Reuben then is connected to our acceptance of the basic foundational truths of the Word.

That Reuben represents this elementary understanding of spiritual ideas or concepts becomes very clear from the meaning of his name. Reuben literally means "_see a son!_". Both the word "_see_" and "_son_", spiritually relate to the things of the understanding. To "_see_" is the same as to understand, and "_son_" is used throughout the Word to signify truths. From this we see that Reuben has to do with our understanding of truths, and because his inheritance lies beyond Jordan, it is an external understanding built upon natural truths of the Word that are understood more in terms of the meaning present in its literal sense.

The Gadites, because they are mentioned second, represent what should follow on from this natural understanding of spiritual things. There are three things that make up the life of external man, the first has to do with intellectual things, the second has to do with the things related to the affections, and the third is when these things are exhibited in the actions that give them expression and life. So where _Reuben_ represents what belongs to the intellectual side of the spiritual life in the natural man, _Gad_, or the _Gadites_ here represent what is built up in a person's response in obedience to their understanding of truth, particularly when it feels difficult to stay motivated in spiritual life, and we have to compel ourselves as a matter of obedience to work. As we struggle and work from truths so _Gad_ is born ...

  …by Gad [is] described the good of life [that comes from living] according to truths from the Word
 (Apocalypse Explained 435)

And so now what follows on from Gad is Manasseh. As we live in obedience to our understanding of the Word which we have developed, a real love and delight for the things of the Word flows into the natural man/mind from the spiritual man/mind. You would have noticed that Manasseh is referred to as a half tribe. This is because the inheritance granted to the tribe of Manasseh included an allotment of land on both sides of the Jordan, leading to half of the tribe existing within the Jordan and another half without. The placement of this tribe's lands either side of the Jordan is how the Word represents the link between the spiritual and natural man represented by _Manasseh_. Of Manasseh the Apocalypse Explained 440 says that ...

  Manasseh represented ... good from a spiritual source in the natural man, therefore an inheritance was given to that tribe beyond or without the Jordan, and also on this side, or within the Jordan; to half of the tribe, beyond or without the Jordan, and to the other half, on this side, or within the Jordan
 (Apocalypse Explained 440)

Manasseh, however, at this stage of the story is only found to be established in that area of the land that represents the external mind.
From this, we are to understand that Manasseh represents the first development of a new will which is of a higher quality for spiritual things , and so we read that ...

  Manasseh means ... the delight of doing good and learning truth
 (Apocalypse Explained 440)

So when we move from our understanding of the Word (_Reuben_) affirming its truths through our response (_Gad_), we will begin to see the development of a new quality of affection for the things of the Lord and heaven (_Manasseh_).

The lesson of these three tribes is that we can never rest on just the external elements of spiritual life. Knowledge of the Word is given to serve heavenly uses and those uses belong primarily to the things of the internal man. There is always the temptation of settling down into our acquired knowledge of the Word and understanding of the spiritual principles found in the doctrines for Spiritual Christianity. There is a temptation off merely being content with the externals of a religious or spiritual life, and leaving off using what we have from the Lord to engage in the fight of having that which is opposed to the heavenly life within our minds removed. Here we see that _Reuben_, _Gad_ and _Manasseh_ in us has to be brought to the fight so that the land that is our life might be free of every selfish pattern of feeling, thought, and behavior that exalts itself against the Lord.

