ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 04. Spies Sent Forth From Shittim (2:1-6)

  And Joshua the son of Nun sent two men out of Shittim to spy
  secretly, saying, Go look over the land, and Jericho. And they went
  and came into the house of a woman, a harlot; and her name was
  Rahab. And they lay down there. And it was reported to the king of
  Jericho saying, Behold, men have come here tonight from the sons of
  Israel, to search the land. And the king of Jericho sent to Rahab,
  saying, Bring out the men who have come in to you, who have come
  into your house. For they have come in to search out all the land.
  And the woman took the two men and hid them, and said, This way the
  men came in to me, but I did not know from where they were. And it
  happened as the gate was to be shut at dark, even the men went out.
  I do not know where they have gone. You go after them, and hurry,
  for you may overtake them. But she made them go up on the roof, and
  hid them with stalks of flax, which she arranged on the roof.
  (Joshua 2:1-6)

  Of shittim wood' means out of mercy. This is clear from the meaning
  of ‘shittim wood' as the good of merit which is the Lord's alone,
  dealt with in 9472, 9486; and since the good of merit is mercy,
  ‘shittim wood' also means mercy. For out of pure love, thus out of
  pure mercy, the Lord assumed the Human, and underwent the severest
  temptations, finally the passion on the Cross, that He might save
  the human race; and therefore merit and righteousness are His. From
  all this it is evident that the good of merit consists in mercy,
  mercy being Divine Love directed towards those trapped in misery.
  (Arcana Coelestia 9528)

Today we come to this wonderful, wonderful story of Rahab which is found in the second chapter of Joshua. The children of Israel are camped outside the borders of the land of Canaan, making preparations so that they can enter the land. What now stands before them as the first challenge in their impending campaign to take the land of Canaan,
is Jericho, a Canaanite city which lies just inside the boarder near where the Israelites will cross the Jordan River.

Now, as is prudent in any campaign, Joshua selected two men as spy's to go into the land to gather information regarding the state of things in general, and in particular the state of Jericho. We read that when the spies came into Jericho they took lodgings with a woman named Rahab,
who is described as a harlot. Word then got back to the king of Jericho that these strangers were in the city and he sent for Rahab to find out where the two men were. Rahab responded, no doubt at great risk to her own life, by concealing the men on the rooftop behind some stalks of flax. Then when it was safe, she helped them make good their escape.

And so we read in verse one

  And Joshua the son of nun sent two men out of Shittim to spy,
  secretly, saying, go look over the land, and Jericho. And they went
  and they came to into the house of a woman, a harlot; and her name
  was Rahab. And they lay down there.

Reading this, we can remind ourselves that the Word has an internal sense which has nothing to do with the meaning that we find in its literal sense. This inner meaning focuses on those things that belong to the inner mental world of our minds. Knowing this means that we can come to these stories of the Word open to understanding them in terms of their application to the life of our regeneration. For the Lord has given us these stories as a map of our own inner processes so that we can have some sense of how the Word interacts with us as it creates and reforms the mind, and of the states that arise as we enter into the spiritual dimension of life.

We have already seen that Joshua represents the understanding of the Word that arises to support a person when they willingly take up the challenge to apply the principles of the Word to their inner life.
Canaan represents the human mind, which when in its proper order is populated with things good and true from the Word, those things being represented by the Israelites. However, at this stage the land is not in order but populated by Canaanites who are opposed to the Israelites and thus is a picture of the disordered state of mind which every person is in prior to being regenerated by the Lord. These enemies of Israel being in the land is how the Word represents the dominance that evils and falsities have over us in this state.

The Canaanites represent those things that are born of the loves of self and the world. No one is exempt from the activity of the selfish life of the proprium, the doctrines for Spiritual Christianity are very clear on this. The life that we are in prior to applying truths to the inner life of our mind is nothing but selfishness arising from the evils and falsities that make up the proprium. So it is that the Word and the doctrines for Spiritual Christianity continually beckon us to work with the truths and principles which they contain so that we can come to see this state of affairs. For it is not until we apply these truths that we are given to see the actual state of things internally.

So, in order to understand what is being illustrated at this point of the story we need to establish what is meant by the two men set out from Shittim, what is meant by the woman Rahab and by her being a harlot, what is meant by the king of Jericho and what is meant by the rooftop and the stalks of flax. All of these things have an interior meaning which relates to the internal realities of the Lord's interaction with us as the Word. So let's now set the backdrop by looking at the meaning of the two spy's and the spiritual connections represented by them in their coming from Shittim to Jericho.

When we look to the truths of the Word to govern our mental life the Word or Joshua then provides us with the ability to begin to see the quality of the life of our affections and thoughts. Spiritual life begins with self observation, and our ability to observe our states of mind arises from a willingness to actually look within. For it is when we are making an effort to do this inner reflection that the Word or Joshua begins to open up for us in a new way, as it provides us with truths as a light by which we can see new things. And we actually begin to see that the state of the land or our mind is filled with things that are opposed to what we understand the heavenly life to be.

These two men, the spies are sent out from Shittim, which is an area located on the outside of the borders to Canaan east of the Jordan,
where the Israelites were camped. Places in the Word correspond spiritually to states of good and truth that the mind is in, and their names provide us with insight into the quality of the place referred to. Shittim, being the place where the spies were sent out from,
spiritually represents the first truths that a person has to acknowledge in order for self examination to begin.

The area called Shittim got its name from the shittim wood presumably from the presence of the acacia trees of the middle eastern desert from which shittim wood comes. The doctrines for Spiritual Christianity teach us that shittim wood corresponds to the Lord's righteousness and merit. So, the state of mind represented by Shittim from which self examination can begin, relates to being in the acknowledgement of those truths that teach that the Lord alone is righteous and that all merit belongs to Him. Why is this acknowledgement necessary for self examination to begin? Well by righteousness and merit belonging to the Lord is meant that the Word alone is able to overcome evils and falsities, and that as far as spiritual matters are concerned human beings are absolutely powerless to effect anything. It is the Lord alone as the Word that fights for us and is able to overcome the selfish life of the proprium or ego.

When this is acknowledged by a person they then have what is needed to begin the process of self examination. Without this acknowledgement,
entering the land and all that it represents is impossible. This is because until a person acknowledges the Lord as the source of all that is good and true they are in a state where they claim merit for the good and truth that they have and attribute it to themselves, and of their own doing.

The thing to realise is, that it is with the acknowledgement of truth that creates the conditions for its opposite to come into view. By knowing truths one can know their opposite. So the first state of regeneration begins by acknowledging that the Lord alone is righteousness and merit, and when this acknowledgement is made as a matter of life and not just of the lips, then we can begin to see its opposite within us. We can see in ourselves instances of wanting to take credit for any good we do.

When we are out of touch with the truth that the Lord alone has righteousness and merit, we are unable to see that we do this. It is a state of disorder -- and its evident in every instance when we take credit, or feel offended that we are not acknowledged for what we do,
or when we feel we are not appreciated. When we are caught up in these states and the emotions involved then we are associating with spiritual influences that don't recognise that all merit is the Lord's and it translates in us as feeling that we deserve to be treated better. This is what Jericho is and this is why our arrival at this place, as the ability to observe this in ourselves, comes from the acknowledgement represented by Shittim and the two spies which are sent forth to take an inventory of what lies within. Hence we travel from Shittim to Jericho.

  And Joshua the son of Nun sent two men out of Shittim to spy
  secretly, saying, Go look over the land, and Jericho.

Self examination can only begin if we see a need to undertake it. If we can't see that there is anything out of order within us, in the land of our minds, then we won't see any need to examine ourselves or look to take up opportunities to be involved in spiritual work. It's simple really, if you don't see a problem you won't see any need to seek a solution. If, on the other hand, you see that there are enemies in the land then you will make efforts to do what the Word asks of you through stories such as this one. For when read and understood they create an opportunity for us to look to the Lord so that we can work with the Word to have what is opposed to heavenly loves removed from our life.
The spies of Shittim teach us that as we look to make an effort to observe those states within us that take credit for good, the Word or Joshua sends out truths which give us the ability to see these tendencies, to travel to Jericho.

To acknowledge the truth of what the Word and doctrines for Spiritual Christianity teach, is to engage in self examination and repentance –
that's what acknowledgement is. Acknowledgement that does not lead to active spiritual work is not real acknowledgement. So in response to this story we have an opportunity now to set ourselves a task before moving on to the next article in this series.

And that work task is -- to observe our tendencies to claim credit for the good that we do. To take account of when we feel we are not given what we think we deserve.

If we will do this, we will gain some insight into how these spies set forth from Shittim actually operate within us, how the Lord's mercy and compassion works within us. We will also get a sense of what the state of self merit, of Jericho, looks like. And it is in through doing work like this, through making the Word's truths part of our daily life –
that the way is opened for us to navigate the path forward. And we will find ourselves in a better position to see the details of what the spies find in Jericho, of what harlot woman Rahab might be in our own experience for example, which is what we will look more deeply into into next time.

