ifndef::fullbook[]
= Sermons on Joshua
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 05. The Tendency To Own Good And Claim Merit (2:1-6)

  And Joshua the son of Nun sent two men out of Shittim to spy
  secretly, saying, Go look over the land, and Jericho. And they went
  and came into the house of a woman, a harlot; and her name was
  Rahab. And they lay down there. And it was reported to the king of
  Jericho saying, Behold, men have come here tonight from the sons of
  Israel, to search the land. And the king of Jericho sent to Rahab,
  saying, Bring out the men who have come in to you, who have come
  into your house. For they have come in to search out all the land.
  And the woman took the two men and hid them, and said, This way the
  men came in to me, but I did not know from where they were. And it
  happened as the gate was to be shut at dark, even the men went out.
  I do not know where they have gone. You go after them, and hurry,
  for you may overtake them. But she made them go up on the roof, and
  hid them with stalks of flax, which she arranged on the roof.
  (Joshua 2:1-6)

  What else can people who are in ignorance know than that the good
  they do is their own, and that the truth they think is their own?
  The same applies to people who ascribe the good deeds they do to
  themselves and place merit in them, unaware of the fact that in this
  case those deeds are not good though they appear to be so, and that
  the proprium and the self-merit they place in them are evils and
  falsities that cause obscurity and darkness. And the same applies in
  many other instances. [2] What evil and falsity are like, and how
  much evil and falsity lie concealed in such deeds, cannot possibly
  be seen so clearly in the life of the body as in the next life,
  where these are presented to view altogether as in broad daylight.
  But it is different if a person acts out of ignorance that has not
  been confirmed, for in that case those evils and falsities are
  easily dispersed. But if people confirm themselves in the notion
  that they are able to do good and to withstand evil by their own
  powers, and that thus they merit salvation, such a notion remains
  attached, and causes the good to be evil, and the truth to be
  falsity. Yet for all this, order requires that a person should do
  good as though from himself, and ought not therefore to stay his
  hand and think to himself, ‘If I am unable to do anything good at
  all from myself I must wait for immediate influx’ and so remain
  inactive. This is also contrary to order. Man ought to do good as
  though from himself; but when he stops to reflect on the good he is
  doing or has done, let him think, acknowledge, and believe that the
  Lord present with him has accomplished it. (Arcana Coelestia 1712)

We continue now with the story of Rahab and her willingness to hide the
spies which were sent out by Joshua to get intelligence regarding the
city of Jericho. Last time we considered a basic principle of spiritual
development which was that when truth is received into the life it
raises our awareness in a way in which we are able to see its opposite,
the false ideas and reasonings that oppose it. The doctrines for
Spiritual Christianity state that we are able to see what is false from
what is true, but that no one is able to see what is true from what is
false. So we need the Word if we are to progress in the spiritual life.
And we saw how this principle was illustrated in our text by looking at
the relationship between what is spiritually represented by Shittim,
and what is represented by Jericho, and what the connection is between
them as highlighted by the two spies being sent forth from Shittim and
lodging in Jericho at the house of Rahab.

We saw that the two spies represent truths from the Word which provide
us with the ability to see the quality of our inner states of life.
Theses spies serve Joshua, the Word, in that they are the means by
which information can be gathered, and in this sense serve as the eyes’
of Israel, the things of good and truth, at this stage of their
campaign. For our ability to see anything within ourselves as to our
states of affection and thought, comes from the Lord, and by the Lord,
we mean that it comes from the truths of the Word for these truths are
the Lord with us.

It is interesting to note that the Hebrew word translated “spies” also
carries the meaning of “to walk about.” This teaches us that these
truths, that come out of the state represented by the spies from
Shittim, are connected with our willingness to walk or live from the
truths of the Word, for ‘to walk‘ means to be active in the application
of spiritual teachings to life. The particular kind of truths
represented by the spies are those that arise from the work of self
examination and repentance because when we speak of applying truths to
life what is meant their application to the interior life of the mind
with its thoughts and its affections and not the external life of the
body in the world. For it is through the application of truths to the
interior life that the mind gains a perception by which we can see the
quality of those things that lie within it.

Last time we looked in depth at the meaning of Shittim and the wood
that comes from it, acacia wood, otherwise known as shittim wood. We
established from the that Shittim as a place represents a state of
acknowledgement of the truth that the Lord alone is righteous and has
merit. We saw that this acknowledgement marks the beginning of being
able to enter into the spiritual work of self examination, which is
represented by the spies, or what observes, being sent by Joshua, or
the Word, from Shittim, or the acacia grove.

It is only when we acknowledge the Lord or the Word as being righteous
and deserving of all merit that we can even begin to see what is in us
that claims righteousness for itself and merit for what rightfully
belongs to the Lord and the Lord alone. So in coming back to the
principle that we mentioned right at the beginning – when we come into
a truth we are empowered to see what is within us that opposes it – in
the case of this story, what opposes the truth that the Lord alone is
righteousness and merit and therefore the Saviour, is Jericho.

Last time we also looked at setting a work task to observe the
self-merit tendencies – to take credit for things that you have done;
or to notice when you felt offended due to people not giving you the
praise you think you deserve or are owed. If you did this you would
have in fact, entered into the story in regard to your own experience.
You would have found that this tendency to take credit or merit for the
good you do is constantly raising it’s ugly head, either in attempts to
draw the attention of others to what you have done, or in feelings of
resentment when others don’t seem to acknowledge your “good” work or
give you the praise you feel you deserve.

One of the valuable things that comes out of doing a task like this is
that we very quickly come to see that what we say we believe is often
not backed up by the affections and thoughts that we entertain
inwardly. What the quality of our inner life experience shows is that
while we may acknowledge truths with our lips, in this case, that the
Lord alone is righteous and deserving of merit, our actual life or how
we are internally says the opposite. Doing a little exercise or task
like this is extremely valuable because it brings into our
consciousness awareness the inner spiritual associations which we
entertain that are constantly working at undermining our quality of
life. Claiming merit for the good that we do shuts the Lord out and
invites the hells in. But if we are prepared to work at seeing this
tendency in ourselves from the truths of the Word, from the spies of
Shittim, we will then be placed in a position where we can be empowered
to work to have such things separated from us. However, if we don’t
look with a view to working with the Word to have such things removed,
then nothing is possible.

The problem in claiming the merit for doing good to oneself is that it
is closely associated with a belief that we can save ourselves. In
other words, we live in the illusion that because we appear to be good
people externally that this somehow qualifies us for heaven. The
following quote from Heaven and Hell 495 brings a bit of clarity around
the falsity of this belief. This is a comment on the state of those
entering the spiritual world after death…

  Many of them think they will (get into heaven) because they led
  moral and civic lives in the world, not reflecting that both evil
  and good people lead similar outward lives, being similarly helpful
  to others, going to church, listening to sermons, and praying
  similarly, utterly unaware that outward behaviour and outward
  worship accomplish nothing whatever; only inner realities that give
  rise to these outer ones are effective. Scarcely one in thousands
  even knows what the inner realities are or that they are the focal
  point of heaven and the church for us. Even fewer realise that the
  quality of our outward actions is determined by the quality of our
  intentions and thoughts and the love and faith within them, from
  which our actions arise. Even when they are told, they do not grasp
  the fact that [it is the quality of their] thinking and intending
  [that] actually make[s the] difference.

This is why Spiritual Christianity takes an inner focus, for it is the
inner application of the Word that matters. The doctrines for Spiritual
Christianity give us the ability to see what’s within us. Externals, we
see here actually count for nothing if the internals are not being
attended to. The acknowledgement represented by Shittim is the
acknowledgement that in and of ourselves we are completely powerless in
regards to spiritual matters. This is the meaning of the Lord’s words,
“without me you can do nothing” (John 15:5). When this acknowledgement
is of the life and not just the lips then we are in a position to begin
to see the true nature of Jericho, and what Rahab represents.

Cities in the word correspond to the ideas and concepts that we pull
together and live from. As such they represent forms of doctrine, and
when the cities are populated by the children of Israel this represents
that they are filled with things from the Word that are good and true.
But when they are populated by Canaanites, which are the enemies of
Israel, then they represent things that are evil and false or what is
connected to the selfishness that arises from the loves of self and the
world. So depending on the context, a city can have a good or evil
correspondence.

Clearly Jericho, being populated by Canaanites, must correspond to a
belief structure that supports a life that is opposed to what is
spiritual. The spies or the truths of Shittim are truths from the Word,
Joshua, that we can use to investigate and discern the quality of the
particular form of evil and falsity represented by Jericho. For when we
truly acknowledge the Lord as the only one who is righteous and
deserving of merit then we can see within ourselves those things that
set themselves up to claim righteousness and merit as our own. We need
to be aware that the deep set beliefs that we hold, are what spirits
from the spiritual world use to gain influence in our life. The
stronger a particular belief is, the more entrenched the associated
spiritual influences will be in that area of our life.

Jericho sits inside the border of Canaan, just beyond the Jordan River.
Because of this its correspondence in a good sense relates to teaching
that is designed to introduce us into the heavenly life. The city of
Jericho has a strong association with palm trees, in fact it is called
“city of palms,” and like acacia and other trees in the Word, palm
trees also represent an acknowledgement of a form of spiritual truth.
In the case of palms it is an acknowledgement of the Lord as Saviour.
We can confirm this from the Word. You will recall that when the Lord
entered Jerusalem the people waved palm leaves, shouting,

  “Hosanna; Blessed is the King of Israel who comes in the name of the
  Lord,” (John 12:12-13)

Hosanna means “save us now,” and in the book of Revelation we also see
a connection made between palms and the Lord as Saviour where John,

  “…beheld, and, lo, a great multitude which no man could number, of
  all nations, and kindreds, and people, and tongues, stood before the
  throne, and before the Lamb, clothed with white robes, and palms of
  their hands; and cried with a loud voice, saying, salvation to our
  God, which sits upon the throne, and unto the Lamb” (Revelation
  7:9-10).

Jericho’s association with palms means that it represents knowledge of
the Lord as Saviour. But when inhabited by Canaanites, this meaning
gets changed into its opposite, which is a belief that we can somehow
save ourselves without attending to the things belonging to our inner
mental life. This belief is closely tied to the idea of merit, where
salvation is adjudged to be tied to our own sense of goodness. The
proprium or ego is confirmed in the belief that it is good, and so it
works to produce exterior forms of moral and civil good which people
place their confidence in. But as we saw from the quote from Heaven and
Hell, such confidence is misplaced.

Of course for most people who don’t not have access to truths that
teach otherwise, it is unavoidable that they end up taking credit for
good and so attributing merit to themselves. This flows from the fact
that the life we have feels as if it is our own. A foundational truth
of Spiritual Christianity is that life is not our own but that it flows
into us from the Lord. Without knowing this, however, everything done
by a person is believed by them to be done from themselves and the
result of this is that they naturally claim merit and goodness as their
own. Thankfully, no one is held accountable for falsities or evils that
arise due to an ignorance of truths.

This state of ignorance though dwells within all of us, even though of
us in spiritual work although it may be more covert. The task you were
asked to do shows that we all attribute good to ourselves and have a
strong tendency to claim merit. If you did do the task you will now be
well aware of this fact. If you didn’t get an opportunity to do it then
let me encourage you to work with it before moving on to the next post
in series, because if you do, this story will become much more real for
you.

The raw desire to do good and the delight which we feel when we do do
good is from the Lord but until the Lord is acknowledged in the state,
we remain in ignorance of truths concerning the Lord. And the good that
is done and the delight that is felt will be tainted with merit-seeking
due to the loves of self and the world being within it. But it is a
starting point and this affection in those states within us that dwell
in ignorance is something that the Lord can and does use to draw us to
Himself. In this rudimentary unclean state, this affection is
represented in our story as a harlot named Rahab. The name Rahab means
“pride” and speaks of the pride we take in our own sense of merit. This
must be purified with truths from the Word that teach that the Lord
alone is deserving of merit.

What this story shows us however, is that this desire to be
acknowledged and receive praise, to take credit and claim merit is
something that needs to be investigated through self examination so
that it can be seen for what it is – as a tendency to take what belongs
to the Lord and claim it for ourselves. The Word teaches us it is there
and that while it goes unnoticed mental cities like Jericho will remain
as an obstacle in the spiritual life. The desire to do good, and the
delight which we feel is the Lord’s gift to every person and when we
are able to free this from merit-seeking and credit-taking it is then
something truly good for it then belongs to the Lord. This can only
take place as we activate the spies of Shittim within ourselves, as we
do the work of self examination by the light of truths from the Word.

Next time we will look at some detail at how the rudimentary affection
for truth represented by Rahab, is able to be used by the Lord to
protect what is his own in us.

