ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 07. Following The Ark Of The Covenant (3:1-5)

  And Joshua rose up early in the morning. And they pulled up stakes from Shittim and came to the Jordan, he and all the sons of Israel. And they stayed there before they crossed over.
  And it happened, at the end of three days, the officers passed into the midst of the camp.
  And they commanded the people, saying, When you see the ark of the covenant of Jehovah your God, and the priests, and the Levites bearing it, then you shall pull up stakes from your place and shall go after it.
  Only, keep a distance between you and it, about two thousand cubits by measure. You shall not come near it, so that you may know the way in which you are to go. For you have not crossed over this way yesterday and the day before.
  And Joshua said to the people, Sanctify yourselves, for tomorrow Jehovah will do wonders among you. (Joshua 3:1-5)

  [The ark of the covenant is called] the ark of the covenant because it contained the law. And the law, which in a broad sense means the Word, signifies the Lord as to the Divine Truth, which is the Word, thus the Divine Truth or Word which is from the Lord, and in which the Lord is, because all Divine Truth proceeds from Him. When this is received by man, conjunction with the Lord takes place, and it is this conjunction that is signified by covenant…
  [2]…Man, from freedom, can think and will what is evil, and also think and will what is good. So far, therefore, as a man from that freedom, which belongs to his love, and thus to his life, thinks falsities and wills evils, which are contrary to the truths and goods of the Word, so far he is not conjoined to the Lord; but so far as he thinks truths and wills goods, which are from the Word, so far he is conjoined to the Lord, and the Lord causes those truths and goods to be of His love, and thus of His life. From these things it is evident that this conjunction is reciprocal, namely, of the Lord with man, and of man with the Lord; such is the conjunction meant in the Word by covenant. (Apocalypse Explained 701)

We now reach the point where the sons of Israel begin their advance towards entry to the Promised Land. It begins with Joshua rising up early in the morning, and with the children of Israel moving towards the Jordan, where they camped before they crossed over. This movement out from Shittim, as the ground from which the advance towards the Promised Land is made, is one every person who is to embark on the journey of inner spiritual growth and development must make. We have seen that Shittim represents the acknowledgement of the truth that the Lord alone is righteousness and so deserving of merit. What this means is that a person comes into a state of conviction that the truths of the Word are the only thing that have power to fight for us against the hellish influences, which keep us ego-centric in attitude and our outlook.

This acknowledgement, of course, must be one of the heart or life. A recognition from the heart or life is different from a merely intellectual acknowledgement because it comes with a sense of conviction that compels us to do something with the spiritual principles that we know. Alternatively, claiming merit arises when there is an intellectual relationship to spiritual teachings without a sense of them having implications for our life. Strictly speaking it dominates when we are more concerned about how we appear to others externally and hence don't give any real attention to the internal things of the Word and their application to our real life, which is the mental and emotional life of our minds with its beliefs, desires,
values and attitudes. Claiming that we possess some form of goodness or rightness (righteousness) is always accompanied with attitudes of self-righteousness and self conceit, and in this lurks a pride in one's own intelligence. This being the case, we should be able to see that any sense of goodness that we hold in regard to ourselves is something that flows out of the hells and as such is a form of denial that the Lord alone is righteousness and worthy of merit.

We don't actually have to look that hard to see when we are caught up in states that deny the Lord or what is the same thing, when we don't accept what the truths of the Word teach in this area. Self merit manifests in a lot of different ways. It can be seen in a sense of our own righteousness which is really an attitude or need to always be right. It can be seen in defensive behaviours and a need to constantly justify ones position. This defensiveness can either be passive or active, going silent when offended or always being on the attack. If we find ourselves constantly battling to get our own way or we respond with attitudes that are dismissive of the views of others, then this is a cue that we need to look into what is governing our responses to life.

Shittim represents the putting aside of such attitudes or at least a willingness to acknowledge and work with the Lord to have these attitudes changed or removed. Such attitudes are embodied, and so well pictured in the Pharisees of the New Testament who stood against the Lord at every turn. They represent those aspects within our proprium that continually object to the demands which truth makes on our life and so take a stand against the Divine truth in favour of what is evil and false. From this, arises a false self image that is absorbed in the loves of the self and the world.

But once the Word is acknowledged as being righteousness itself, a new state of understanding represented by Joshua arises and a new state of life begins to come to the fore. This new state is called “the morning,” and with the morning and the rising of Joshua so too the sons of Israel or the truths of the Word that have gathered and camped in our memory begin to be reorganised bringing us to the Jordan River and so to the boundary of Canaan, or to the possibility of a new life grounded in the loves of heaven.

In our story the Jordan River stands as a boundary preventing the children of Israel from advancing into the promised land. At this point, there is nothing to do but to stop and wait, and so we read that the sons of Israel lodged there before they passed over.

Verse two states that they lodged there for three days and then after the three days we are told that the officers passed into the midst of the camp. And then in verse three, that they commanded the people saying,

  …when you see the ark of the covenant of the Lord your God and the   priests and the Levites bearing the ark of the covenant then you   shall be removed from your place and go after it.

As an obstacle, the Jordan River represents what prevents the things of the Lord and the church advancing in our life. When we truly acknowledge that the Lord or the Word alone is goodness and truth, we are also in a state of acceptance that in and of ourselves we are nothing but what is evil and false. This acknowledgement opens up our ability to see the things that are an obstacle to the loves of heaven,
making their presence more fully felt in our life. The first stages of this shift are described by the sons of Israel halting at the Jordan River.

The land, like Jericho, is filled with Canaanites and the Canaanites represent the self-interest of the proprium. Now, when are working with the Word it is useful to keep in mind that the things within it have a dual application depending on their context. So, as we saw with Jericho last time, so too Jordan has a dual meaning. For when it stands opposed to the sons of Israel, preventing them entering the land, it has a negative meaning in that it represents the false perspectives and beliefs which we hold and these of course shut out the light and love of heaven from our life.

If things are to progress then the false perspectives and beliefs which we carry that are opposed to the life of heaven have to be removed. Our way of seeing things has to shift and for that to happen we have to have our minds reorganised in accordance with heavenly principles.

The sons of Israel represent the knowledge we have of the Word with its stories and prophesies. Those called “officers” represent higher principles that can direct and organise the things found in the literal sense of the Word so that they are able to be used to illustrate more internal realities. So, they bring us into a fuller sense of the internal or deeper meaning of these things and can be used as a guide to dealing with the inner things of the mind. And so it is that we see that after three days, the officers of the people are said to pass into the midst of the camp whereupon they commanded the people.

The Word is given to support us in our spiritual growth or regeneration and so the principles that we find in the doctrines for Spiritual Christianity are what are represented by the “officers.” Our knowledge of the Word is organised in accordance with our understanding of doctrine. Whatever focus we bring to the Word determines how we understand it. If our focus is on externals, our attention will be given to how we appear to others and we will fail to see the contradictions that exist within ourselves. We will see the Word as something that supports our point of view, and in those places where it highlights evils and falsities our attention will be on others and not on ourselves. Whereas if we view the principles of the doctrines for Spiritual Christianity as the basis for examining the life of our own mind, then the stories of the Word begin to be organised in a way that supports this kind of inner work. We see that the evils and falsities are within us and it is here that our attention will be directed. This shift in our understanding of the Word is critical to entering the land.

This process or shift in how we regard the Word must reach its completion before we can move on and this is represented by the “three days” passing before the officers went through the midst of the camp.
Internally by three days is not meant three days but the completion of this state of transition. The number three in Scripture always represents what is complete or what has run its full course and three days signify all the states that have to be passed through in order for our understanding of the Word to be organised so that it can support the inner work of our spiritual transformation or regeneration.

The “officers” being said to pass through the camp of the sons of Israel represents our taking hold of the principles of Spiritual Christianity and using them as the basis for building up our understanding of the Word. What they commanded the people highlights the universal truth that has to be present if we are to undergo the process of being regenerated. For the universal truth that the doctrines teach is that the spiritual life involves a commitment to following the ark of the covenant of the Jehovah our God.

The ark was a box made of shittim wood overlaid with gold. It contained the tables upon which were written the Ten Commandments and these can be summarised as all the Divine laws that pertain to loving the Lord and loving our neighbour. The term covenant means an agreement that brings two or more parties into a relationship with one another. Thus,
covenant spiritually means conjunction or joining together.

So we can ask ourselves- What is this covenant? and Who or what are the parties involved? One of the mistakes people make when they read the Word in regards to the Lord making a covenant with his people, is that they think of people naturally or as referring to individual human beings, or of a collection of people forming a nation, such as the nation of Israel. But people and nations mentioned in the Word don't refer to natural people or nations of the world; rather they refer to states of good and truth or evil and falsity in the human mind. If we saw this then we wouldn't make the error of thinking that the Lord makes his covenant with us as individuals.

The fact is -- the Lord can never be joined to us as there is nothing in what we are as finite human beings that is capable of receiving Him.
The Lord is only able to unite with what is of Himself. So when we read of the Lord setting up a covenant with the sons of Israel we are dealing with something that represents a spiritual reality. When we see that the sons of Israel are nothing other than truths of the Word, then we can see that the covenant that's established is between the Lord as goodness and the truths of the Word, the latter as represented by the sons of Israel that are in accord with this. The Word Itself is the covenant. This is given to us by the Lord and is from Him and is Him.
It is never ours although the Lord has made it so that it can be “as if” it is ours. Clearly we can take the Word into our mind and life but even though it is in us, in this sense it is never ours.

This is why the Word is so important, for it is the sole means by which a person is able to have a sense of being in the life of heaven. In fact there is a remarkable statement in Arcana Coelestia 1878 which says that the Word is in fact heaven.

…the Word is so holy in the heavens that the Word is so to speak heaven to those who are there.

It is the Word that gives us a sense of being connected to the Lord and if we have worked to have our life built on it, this sense of connection never leaves us but makes heaven within us. For when the Word is in our minds the Lord is there also and because the Lord is in the Word and the Word is in us, we then are in the Lord and so we have established within us a sense of connection with the Divine. A sense of a covenant.

To see the ark being lifted by the priests and the Levites is to see or understand that the Word contains all of heaven, which is everything of love and wisdom. Priests represent the Lord's love going forth to save what is truly human in people, while the Levites that bear the ark of the covenant are all the truths that serve the Lord's love for the salvation of the human race. Each day we are given an opportunity to prepare our minds through studying the Word and the principles of Spiritual Christianity. To open our perception that we might see how the ark is borne by love to the Lord and love towards our neighbour.

When we look to the Word to deliver us from evils we find that those things represented by the priests that carry the ark are active, and when we are building up our understanding of spiritual things so we find those things represented by the Levites are active within us. The will and the understanding when centred on the Word and its application to life is represented by both the priests and the Levites bearing the ark -- to see this is to understand spiritual principles and their operation in our life.

Our response must ever be to follow the precepts of the Word as best we can. If we do this then the Ark of the Covenant goes before us. It initiates the shifts in state and as we shall see, brings us to the Jordan River so that we may view the evils and falsities which infest our life. And it is by coming to such a place that we shall see that it is the Lord alone who saves us.

  Now as the Lord alone removes and scatters the falsities of evil that are from hell, and by His Divine truths introduces the faithful into the church and into heaven, and as the ark and the law inclosed in it represented the Lord in relation to Divine truth, it was commanded that the ark should go before the people and thus lead them. (Apocalypse Explained 700c {13})

