ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]

---
ifdef::fullbook[]
<<<
endif::[]




== 08. To The Edge Of The Jordan (3:5-17)

____
And Joshua said to the people, Sanctify yourselves, for tomorrow Jehovah will do wonders among you.
And Joshua spoke to the priests, saying, Take up the ark of the covenant and go before the people. And they took up the ark of the covenant and went before the people.
And Jehovah said to _Joshua_, This day I will begin to make you great in the eyes of all Israel, so that they shall know that as I was with Moses, I am with you.
And you shall command the priests bearing the ark of the covenant, saying, When you come to the edge of the waters of the Jordan you shall stand still in the Jordan.
And Joshua said to the sons of Israel, Come near here and hear the Words of Jehovah your God.
And Joshua said, By this you shall know that the living God is among you. And He shall certainly dispossess from before you the Canaanites, and the Hittites, and the Hivites, and the Perizzites, and the Girgashites and the Amorites, and the Jebusites.
Behold, the ark of the covenant of Jehovah of all the earth shall pass over before you into the Jordan.
And now, take for yourselves twelve men out of the tribes of Israel, one man for each tribe.
And it shall be, when the soles of the feet of the priests bearing the ark of Jehovah, Lord of all the earth, come to rest in the waters of the Jordan, the waters of the Jordan shall be cut off, the waters which come down from above. And they shall stand in one heap.
And it happened, as the people pulled up stakes from their tents to cross over the Jordan, and as the priests bore the ark of the covenant before the people,
and as those bearing the ark came into the Jordan, and the feet of the priests bearing the ark were dipped in the edge of the waters (and the Jordan was full, over all its banks all the days of harvest),
that the waters stood still, those coming down from above rose up into a heap, very far above the city Adam, which is beside Zaretan; and those going down by the sea of the Arabah, the Salt Sea, were completely cut off. And the people passed over opposite to Jericho.
And the priests bearing the ark of the covenant of Jehovah stood firm on dry ground in the middle of the Jordan. And all Israel crossed over on dry ground until all the nation had completely passed over the Jordan. (Joshua 3:5-17)
____
  The miracle [involving the parting of the Jordan] signifies the introduction of the faithful into the church, and through the church into heaven. "The sons of Israel" mean here in the spiritual sense the faithful, who after enduring temptations, which are signified by their wanderings in the wilderness, are brought into the church; for "the land of Canaan," into which the sons of Israel were brought, signifies the church, and "Jordan" signifies the first entrance into it and "the waters of Jordan" signify truths that introduce into it, which are such as those of the literal sense of the Word, for those are what first introduce. But here "Jordan" and its waters signify the falsities of evil which conduct towards hell, since the land of Canaan was then filled with idolatrous nations, which signify evils and falsities of every kind, which constitute hell; for this reason these were to be driven out, that there might be a place for establishing the church. Because "the waters of Jordan" then signified the falsities of evil, they were parted and removed, to give a passage to the sons of Israel, who were to represent the church. 
  Now as the Lord alone removes and scatters the falsities of evil that are from hell, and by His Divine truths introduces the faithful into the church and into heaven, and as the ark and the law inclosed in it represented the Lord in relation to Divine truth, it was commanded that the ark should go before the people and thus lead them. This is why it came to pass that as soon as the priests bearing the ark dipped their feet in the waters of Jordan those waters were divided and went down, and the people passed over on dry land, and after this was done the waters returned. Then these same waters signified truths that introduce; for Jordan was the first boundary of the land of Canaan, and that land, when the sons of Israel had entered into it, represented the church, and that river introduction into it.
 (Apocalypse Explained 700[12,13])

We should now be well acquainted with the idea that the whole population of Israel represents the full complex of the goods and truths that are from the Word, and as such are those things that form the basis of spiritual life and consciousness within us. The truths of the Word when understood in the light of the teachings for Spiritual Christianity are designed to give form to the spiritual mind on the level of awareness in which we find ourselves in our life in the world. Without them we are blind, deaf, mute, lame and maimed in spiritual matters. So where the people represent what populates the mind, the land upon which they stand, move and have their being, represents the ground of the human mind itself.

Lands have boundaries and divisions; and in those boundaries and divisions of lands that we find in the Word, we are able to see the boundaries and divisions that exist within the human mind. In our story today we see that there are divisions within the mind that are represented by rivers. These streams of thought move in different ways depending on the mental landscape that shapes them, even as the character of a river is formed by the physical landscape it flows through. Narrow rigid forms between hard rock surfaces create conditions for raging torrents, and this mirrors the rigid forms of thought that carry powerful flowing emotions. Wider more expansive landforms see larger more peaceful flows which mirror wide open states of love that allow for gentler movements and responses.

The natural boundary of the _Jordan River_ forms separates the land into two broad areas, the _wilderness_ on one side and _Canaan_ on the other. The things without, or beyond the _Jordan_, represents those things belonging to the more external parts of the mind, those within the boundary of the river represents what is relatively more internal. 
What is more internal, when we talk about the mind, is what is more the "real" person, being the actual states of life that we live in. 

With the _children of Israel_ outside _Canaan_, or beyond the _Jordan_, at this stage we have represented a state where the goods and truths of the Word are found in the exterior part of the mind, and reside there as something belonging to the memory. As yet they don't make up the actual internal life of a person. We can see that the more internal aspects of the state described in our story today is filled with _Canaanites_ or what is of the loves of self and the world. Our story then is the story of how goods and truths of the Word battle their way from being something external and of our memory, to becoming our very being and life.

So it is that for a long time our knowledge of spiritual things resides in the external level of the mind, in its memory, where it remains prior to moving into the more interior psychological space, as represented by _Canaan_. Here it is used to confront the enemies of the spiritual life that dwell there. We have seen that certain acknowledgements must take place in regard to truths before this shift can begin to happen. We must pass through that state called Shittim, which is the acknowledgement that the Lord alone has power to deliver us from the evils and falsities that populate our minds, or our inner land of _Canaan_.

In verse 5 we are taught that the Word continually seeks to move us forward. It instructs us on every page, in every statement,
____
To sanctify yourselves for tomorrow Jehovah will do wonders among you.
____

To sanctify ourselves is to be in the effort to receive the Lord's love and wisdom into our life. This involves taking the goods and truths of the Word, and using them to purify our emotional and intellectual life. This is an ongoing work and is the key responsibility that we need to attend to if we want to live a genuine spiritual life. Everywhere in the Word, and in the doctrines for Spiritual Christianity, the Word or Jehovah speaks, and is constantly saying to each one of us, "_sanctify yourselves_", and enter into the work which makes a life of charity its goal.

The use of the word "_tomorrow_" means that the Lord is constantly looking to take us further inward into a richer and more fulfilling experience of heaven by means of the Word. Those who are engaged in this work realise that it is indeed Jehovah Himself as the Word, that works miraculous changes in their midst. This is the "_tomorrow_" spoken of. It is not a day as such but is a state that is initiated in every moment that we affirm the place of the Lord as the Word at the centre of our life.

_Joshua_ is the understanding of the Word that comes into being when there is a desire to apply it to our inner life. When we desire to apply it to life, and are willing to face our evils and falsities, then there is awakened within us a faculty that serves in the function of the _priests_ to whom _Joshua_ is said to speak. _Joshua_ or the Word speaks to the _priests_, in other words the priestly faculty within us is that which hears what the Word is saying. We all can read the Word, but we don't always hear what it is saying. This is why the Lord often used the phrase in the gospels,
____
He who has ears to hear, let him hear. (Matthew 11:15)
____

In those times when the Word really speaks to us, in the sense that we not only hear it, but have _"ears to hear,"_ that is, we find ourselves compelled to respond to it, then in that desire and subsequent effort to respond, we are experiencing what are called _"the priests_" active within us. _Priests_, we saw last time, have to do with things of love in the spiritual life. These manifest as the desire to have all that is within us conform to the pattern of a heavenly mind as revealed in the Word and the doctrines for Spiritual Christianity.

So, the Word speaks to us when what is of "_the priests_" in us hears it. We can know when it is heard because we will be inspired to elevate the _ark of the covenant_, or have the Word take a much more central role in governing and leading us in our life. So it is that the _Ark of the Covenant_ becomes the reference point for the whole _nation of Israel_ to follow; and so when the Word is truly valued in our midst, we find that every natural truth that we have in our minds from the Word begins to become reorganized; hence bringing about a change or movement in our understanding of it, as it leads us to the edge of "sense of self", as represented by the edge of the _Jordan_ _River_.

Taken on an inward level, because the _priests_ are what hear the Word in a way which inspires us to act in regard to spiritual matters, we can perhaps see that the "_inner priests_" of our mind are closely related to the faculty of conscience. 

A genuine spiritual conscience is one that is built up through the practice of truths, from which there is a developed sensitivity to what is opposed to a genuine spiritual life.
The _priests_ are those who receive this command to take up the _ark_, and so they have to do with something connected to our new will. This new will is that which is within us which carries the Word on a personal level, and keeps us conscious of its presence and of our need to work with it, in every situation that life confronts us with.

We read in verse 7 that after the _priests_ had been commanded by _Joshua_ concerning the ark of the covenant , _Jehovah_ then said to _Joshua_,
____
This day I will begin to make you great in the eyes of all Israel, so that they shall know that, as I was with Moses, I am with you.
____

Whenever it says in the Word that "_Jehovah speaks"_ we are talking about influx into the mind that is experienced by a person as an insight, or a sense of something being required of them in response to it.
Remember, Joshua is our understanding of the Word, so Jehovah _speaking_ to _Joshua_ is what we are able to receive from the Lord through the Word. This makes complete sense when we see that the _priests_ who hear _Joshua_ represent our desire to do, and that this is activated by obeying truths. For when we obey truths, we find that insights and perceptions arise to guide and direct our life, which is what is meant by the voice of Jehovah speaking to _Joshua_, or through the Word.

There is an important principle being illustrated here, one that is repeated throughout the Word, and it is this -- we only receive further insights, as we put the truths we currently have, into practise. What this means is that we cannot see our way forward if we will not work with what truths are highlighting in our lives in the present moment.

We experience this law as a recurrence of issues and problems in our life. We are inclined to avoid facing the unpleasantness, pain and suffering that comes with letting go of the old and entering into the new, especially when it involves facing uncharitable attitudes that we hold, which go against how we like to think of ourselves. The spiritual law is straight forward. Influx flows into our effort to do what the Word asks of us. This spiritual law means that it is only as we act upon truths in accordance with the order of our life, can the Lord then implant more, and so lead and guide us further in the life of heaven.
When Jehovah says of _Joshua_ that he shall become great in the eyes of _Israel_, it means that the new phase of life which involves acting upon the understanding of truths that we have, must become the dominant aspect of our approach to spiritual life.

The next instruction, which we find is in verse eight, says,
____
the priests were to stand in the Jordan, when they came to its edge.
____

So we see that if we follow the Word, we will be brought to the edge of our inner _Jordan River_. In other words, we will be brought face to face with what is in us that prevents us from entering into the heavenly life as represented by the land opposite. 

We need to move forward sincerely in response to the Lord's Word, and because we can only do this from a very basic understanding of spiritual realities, we will have feelings of being unsure or insecure. But even a basic understanding, when sincerely responded to, has great power. The faith of a grain of mustard, the Lord tells us, can move mountains (Matthew 17:20). In the case of our story today, the _feet of the priests_ can stop the raging torrent of the falsities from evil which block our way, and thus make it clear for the truths and goods that we have acquired from the Word to become established in the more internal dimension of our life, as represented by the _sons of Israel crossing over_.

The simple desire to be obedient, is represented by the _feet of the priests_ carrying the _ark_ entering the _Jordan River_. This desire, coupled with the simplest of truths, such as those found in the Ten Commandments, is the firm footing on which the spiritual life ultimately stands. Moving from knowing to practise in the spiritual life is achieved by continually looking to the Word for guidance, for as Scripture declares, we ...
____
have not passed this way before. (v.4)
____

The life of spiritual practice is always new, inviting us ever onward and inward into areas that we have not yet been. And while we may never _"have walked this way before"_, we can certainly rest in the knowledge that the Word has gone before us, and knows every step that we need to take, and so can lead us safely on our inner journey into wholeness.
The _Ark of the Covenant_ is to go before the people, and when we are willing to be lead by the Word in this way, then it makes the way clear for us, and draws with it all the goods and truths of the Lord's Kingdom that are stored in our external man, bringing them across the _Jordan_ into our very heart and life.

