ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]

---
ifdef::fullbook[]
<<<
endif::[]




== 09. The Inner Meaning Of The Canaanites (3:9-11)

  And Joshua said to the sons of Israel, Come near here and hear the Words of Jehovah your God.
  And Joshua said, By this you shall know that the living God is among you. And He shall certainly dispossess from before your [face] the Canaanites, and the Hittites, and the Hivites, and the Perizzites, and the Girgashites and the Amorites, and the Jebusites.
  Behold, the ark of the covenant of Jehovah of all the earth shall pass over before you into the Jordan. (Joshua 3:9-11)

  Evils and falsities are meant by the nations mentioned here, evil begotten by falsity that springs from evil being meant by 'the Canaanite, falsity from which evil arises by 'the Hittite', evil and consequent falsity by 'the Amorite', that which is idolatrous but has some kind of goodness in it by 'the Hivite', and that which is idolatrous but has some kind of truth in it by 'the Jebusite'. (Arcana Coelestia 8054)

Today we going to begin to look at what the Canaanites, mentioned in the third chapter of Joshua, represent within us. To do this we will draw from a number of sources to gain a better sense of the Canaanites within the psycho-spiritual dimension of our minds. Our primary source will be the Word and the doctrines for Spiritual Christianity but we can also add what is known of these peoples historically, as to how they lived and in particular what is known concerning their religion.
Why do this? Intelligence gathering is an important undertaking in military campaigns, as we saw earlier with Joshua in preparing for the Israelite campaign by sending out the spies. It represents an essential element in the spiritual life which involves acquiring spiritual intelligence through the discipline of self examination with a view to gaining a little insight into the quality of the states of our own inner life.

The Word is given so that we can see our way forward in our spiritual life. In the Gospels we find the Lord healing the blind. For us the Lord is the Word (spiritual teaching) and it is only as we take the Word as the basis for our spiritual life that our blindness to our destructive inner states of life can be healed. Everything in the Word is given for our spiritual welfare. Nothing there is to be taken historically, God is not interested in giving us a history lesson. What He is interested in is leading us into spiritual wholeness and that requires giving us a way of reading the Word which opens our minds so that we can see what lies within. Now this knowledge is not given to us on a platter because if it was we wouldn't value it. To acquire this knowledge requires intelligence, but not the kind that is measured as IQ, this is the intelligence of the world. Spiritual intelligence is to value what is true because it is true. If a person values what is true,
that is, if they are spiritually intelligent, then they will see that the Word is vital to their life and that it must be worked with and applied to the inner life and activity of their thoughts and affections.

The Word, in giving us the names of these tribes of Canaanites that the Lord says he is going to evict from the land, provides us with what's needed to further build our spiritual intelligence. If we can get more of a handle on what these tribes represent then we will know what to look for within. However, it should not be lost on us that prior to engaging with these tribes, we must first cross the Jordan River. In fact without crossing our own psycho-spiritual Jordan, we can't come into contact with what is represented by the Canaanites.

The general teaching of the Jordan is this. The doctrines for Spiritual Christianity describe the Jordan River in this case as "falsities from evils". This is a common term used in the Text so it's important that we get a sense of what it means for us. The Jordan River as a raging torrent represents what prevents us from entering into the land and facing the enemies of the heavenly life, the inner states of genuine love. The river, as falsities that flow from evils, represents the torrent of thought that flows from the negative emotions that we entertain within our life. These lower emotions are evils because they are concerned with self and the world and when active separate us from others. But most crucially they separate us from the Lord in the sense that when negative emotions get hold of us and the torrent of thoughts that flow from them flood into our minds, we are much less able to remember the Word or principles of spiritual life. We loose touch with that side of ourselves that remembers our connection to the Lord and get carried away in the lower world of our own self centeredness.

How can we possibly see the enemies within, when our thoughts are occupied with negative thinking that flows from harbouring negative emotions? It requires discipline. And what this story of the Jordan River teaches is that it is very important that we use truths to stem the flow of negative thinking which flows from negative states of emotion -- as soon as we are aware that they are active. Here we have a task for our spiritual work, for we can set ourselves a work task to be aware of when our thoughts are flowing from negative emotions. When we see ourselves caught up in negative patterns of thinking regarding others, we can then remind ourselves of what the story of the Jordan River teaches. When we remember the story in the midst of the torrent we will find we are given power that is able to stem the flow of thoughts. We remember that what belongs to spiritual life is unable to exist in the midst of negative emotions and uncharitable thoughts.

This remembering of ourselves in connection with what the Lord teaches as the Word, is what it means to step into the waters. This is because higher and lower level thinking cannot exist together in the same psychological or perceptual space. If we are conscious of spiritual principles which remind us that negative thinking is opposed to the spiritual life and is not healthy, that we in fact have a choice and are free not to think from what is lower, we will find that our state will shift. That we will move from being in the negative torrent, and that a way is made for us to cross over and face what is usually protected by the negative streams of thought that exist as our habitual response to those things in life that tend to unsettle us.

In Joshua 3:10 we have mentioned the names of seven tribes that are in the land of Canaan that the Lord says He will evict from the land.
These are the Canaanites, the Hittites, the Hivites, the Perizzites,
the Girgashites, the Amorites, and the Jebusites. These names are general descriptions of the quality of those mental states that negative emotions and thinking, as represented by the Jordan River,
protect and keep alive within us. If we work to stem the flow of our negative thinking we then open the way for the truths of the Word, as represented by the sons of Israel, to penetrate deeper into our life to defeat these evils and falsities belonging to the loves of our proprium. We have something of their meaning described for us in the work Arcana Coelestia 10638 ...

  Behold, I am driving out from [before] your face the Amorite, and the Canaanite, and the Hittite, and the Perizzite, and the Hivite, and the Jebusite' means the moving away then of evils and the falsities arising from them. This is clear from the meaning of 'driving out from [before] the face' as moving or shifting something away from the interiors composing thought and affection (for 'driving out' means moving or shifting something away, while 'the face' means interior things, see in the places referred to in 9546; and the interiors of a human being are the things present in his understanding and will, or thought and affection, so that 'driving out from the face' means moving [evils and falsities] away from these); and from the representation of the nations in the land of Canaan as evils and falsities, ...
  [2] ... When it says that if he [Moses] observed what Jehovah commanded He would drive out those nations from [before] his face the meaning is, If they carried out the chief commands laid down by eternal truth evils and falsities would be moved or shifted away. Those commands are what come next in the internal sense, the main ones being that they should acknowledge no other God than the Lord, that He is the Source of everything good and everything true, and also that salvation and eternal life come from Him. And when people who believe these things and love the truth of them are reading the Word everything evil and false is shifted away from them, because at that time the Lord enlightens them and leads them. At that time also what they think does not originate in themselves, nor does their affection for the Word originate in themselves but in the Lord. Consequently no evil at all or falsity of evil comes in, for the Lord moves them away. These are the ones who understand the Word, have an affection for the truths derived from it, and also love to live in accord with them.

The meanings of the Canaanite tribes given here are general but more can be seen of their nature or quality as mental states from the meaning of their names. This can be done by going back to the root words in the Hebrew language and seeing their connection to other words that are related to them. The term Canaanite traces its root from a word meaning "what is low" and so we are immediately reminded that what is low spiritually equates to what is most external and belongs to the love of self. It also carries the meaning of "merchandising" or "wares that are traded", and this brings us back to the idea of the love of the world. What is also interesting about this root is that it is related to other roots that share a common meaning being that of
"domination" and the doctrines for Spiritual Christianity teach that the love of self is the love of dominating others. Other meanings related to this word are those of, extortion, force, envy and to vilify which is to defame someone, or to speak ill of them or cast dispersions on their character.

These qualities speak to the negative things in the human proprium or ego, and even the history of Canaan in the Word adds weight to these qualities. The story from Genesis chapter 9 tells us that when Noah came out of the ark with his sons after the flood, that he planted a vineyard and got drunk. His son Ham saw him lying naked and looked to expose him to ridicule him to his brothers Shem and Japheth. But Ham's brothers would have none of it and placing a garment on their shoulders, they choose to cover their father's nakedness by walking into where Noah was backwards and covering him with the garment. The actions of Ham, of exposing others, drew a curse on Canaan his son which means spiritually that this kind of behavior produces nothing but what is accursed as we've also just seen illustrated in the meaning of root word for Canaanite. For these reasons the term Canaanite carries the general meaning of evils.

Other states spring as offspring from this general condition of the proprium and these are described by the names of the other tribes which we can briefly mention now. The word from which we get Hittite is Cheth or Heth, which is the name of the father of the Hittites, Heth being a son of Canaan. This word means "to subdue" and carries the meaning of breaking up; of fear and breaking down courage, it means what is frightening and is used in the Word to describe a state of panic or anxiety. The common theme that runs across its related root words is that of piercing and we get meanings like to cut, to tear off, to frighten. We can see from this that it is closely related to states of worry that cut and tear at our courage which leads to a feeling of being broken and in fear, because such states break our connection to the Lord and remove us from a sense of His presence and hence results in the creation of states of anxiety.

The word Hivites carries within it the meaning of "walls" for protection. It is used of walled villages and means to hide or conceal.
Words related to this root carry meanings of covering over,
transgression, to confuse, scurry, to be secretive, darken and bind or restrain. This relates to ideas of defensiveness and self protection in a negative sense of hiding transgressions through being secretive and causing confusion.

Perizzite means to "open up" or "break through". The meaning it shares with related roots is one of breaking and spreading or dispersing which is what false perspectives that we carry do to truths when they dominate our thinking, particularly in regard to others. Hence we find that the Perizzite in the doctrines for Spiritual Christianity is said to mean falsities that arise from evils.

There is however very little information in the Text regarding the Girgashites. The best authorities relate this word tentatively back to a root wood which means a "scabby skin disease". This could possibly be connected to ideas of old emotional wounds that have not properly healed and are easily opened when we suffer hurt or a state of being easily offended.

In the Word, the Amorites are often mentioned in connection with the Perizzites and are the particular evils from which the falsity represented by the Perizzites flow. The Amorites were hill dwellers and represent the pride of self love and from the meaning of this root we get a sense of self righteousness. We also get a sense of all talk and no action or saying the right things but not living a life in accordance with what is being professed.

Finally we come to the Jebusites. In the Prophets, the Jebusites are described as having an Amorite as a father and a Hittite for a mother.
It would appear then in the sense that it occurs last in the series of names, to be linked to actions in which all other qualities are found.
The root means "to tread down on an object" or "trampling". It shares the meaning with other roots of to act negatively, with related words that mean, to tread down; deceive, shatter, despise and scatter. Again,
all elements pointing to the negative behaviors that issue forth from the proprium when it is self absorbed instead of centred on the things of the Lord as the Word.

So those are the seven tribes and we'll leave it there for now. But hopefully this gives you a sense of the importance of looking beyond the historical elements of the Word. And how that when we know that there is a spiritual meaning within it, and that this inner meaning relates to our inner world, that what we have in the Word, in these stories, are invaluable tools for advancing the spiritual life within us. They are tools by which we can gain spiritual intelligence. This is the intelligence that sees truths and desires to live from them. Not just to know them and know about them, but actually to travel across the Jordan River. For it is spiritually intelligent to be watchful of and look to the stem the flow of the torrent of the negative emotions and thoughts, so that we can cross over and have the Lord remove these from what is central to our loves and thinking. If we would work to do this do, then the Lord as the Word can begin to have a much more positive influence over our life.

  And Joshua said to the sons of Israel, Come near here and hear the Words of Jehovah your God. And Joshua said, By this you shall know that the living God is among you. And He shall certainly dispossess from before your [face] the Canaanites, and the Hittites, and the Hivites, and the Perizzites, and the Girgashites and the Amorites, and the Jebusites. Behold, the ark of the covenant of Jehovah of all the earth shall pass over before you into the Jordan.

