ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 10. Stones Of Remembrance (4:1-3 & 8-9)

  And it happened, when all the nation had completely crossed over the
  Jordan, Jehovah spoke to Joshua, saying, Take twelve men for you out
  of the people, one man of each tribe. And charge them, saying, Take
  twelve stones from this place, from the middle of the Jordan, from
  the place where the feet of the priests were fixed. And you shall
  carry them over with you and lay them down in the lodging place
  which you stay in it tonight… And the sons of Israel did as Joshua
  commanded, and took up twelve stones out of the middle of the
  Jordan, as Jehovah had spoken to Joshua, according to the number of
  the tribes of the sons of Israel, and crossed over with them to the
  lodging place, and laid them down there; And Joshua set up twelve
  other stones in the middle of the Jordan, in the place where the
  feet of the priests bearing the ark of the covenant stood firm. And
  they are there until this day. (Joshua 4:1-3 & 8-9)

  As the waters of Jordan signified truths that introduce they were
  commanded to take up out of the midst of it twelve stones, and carry
  them over to the first place where they passed the night, and this
  because “stones” signify truths, and “twelve stones according to the
  number of the tribes of Israel” signified the truths of the church.
  Joshua set up those stones in Gilgal to the east of Jericho, because
  Gilgal signified the doctrine of natural truth, which is serviceable
  for introduction into the church. From these few things it is clear
  what things of heaven and the church were represented by this
  miracle, also that the “ark,” because of the law in it, signified
  the Lord in relation to Divine truth, therefore it is called “the
  ark of the Covenant of the Lord of the whole earth,” as meaning
  conjunction with the Lord through Divine truth, since conjunction,
  which is signified by “covenant,” is effected through Divine truth,
  and that is what constitutes heaven and the church, which are
  signified in particular by “the whole earth;” in fact, through
  Divine truth all things were made and created, according to the
  Lord's words (John 1:1-3, 10; Ps. 33:6), “the Word” there meaning
  Divine truth. (Apocalypse Explained 14)

Today we come to that point of the Israelites journey when they have to cross the Jordan River. This represents a significant change of state in the establishment of the church within the human mind. Perhaps, we just need to remind ourselves of what is meant by the church of this context. The term “church“, really means where goods and truths are present and active. In other words, the term church means spiritual consciousness, and this can be applied to the individual, or to a collective group of individuals who look to the Word for their life.
This spiritual consciousness that the doctrines for Spiritual Christianity describes in its use of the term church, is the organisation of goods and truths that comes about through living one's life in accordance with one's understanding of truths from the Word.

All the historical aspects of the Word, including the Prophets,
contains a spiritual meaning that has nothing to do with the history of Israel as a nation, or the fortunes or misfortunes of its people. This inner level of meaning deals solely with the development of spiritual consciousness and its establishment and progress within our life. To read the Word spiritually means not to pay any attention to the historical meaning of the literal sense, but to move beyond it to what lies within. For when the literal meaning takes our attention it binds our thinking in a stream of natural associations which are tied to history and personalities of the past and in this way, prevents us from seeing the spiritual meaning within. The literal level of the text should be thought of as a body through which its spirit is able to be expressed on the material plane of consciousness and by the spirit of the Word we mean the Love and Wisdom of God.

The teachings for Spiritual Christianity concern themselves with making us aware that this deeper level of spiritual meaning exists in the Word and they instruct us how it is to be accessed. But we should be aware that the term “spiritual” when used in respect to the spiritual meaning of the Word refers to something specific. The term “spiritual” in the context of Spiritual Christianity concerns itself with love towards the neighbour. This is an important point for us because within our culture the term spiritual has such a broad spread of meaning that it's become something quite vague and for all intensive purposes, virtually meaningless. Thankfully, the doctrines for Spiritual Christianity provide us with a clear definition of this term and we see from them that it refers to those things concerning the preparation of the mind so that it can express love of wisdom from the Lord more readily in its external actions in the world. So when we talk about the spiritual meaning, we are talking about that level of meaning that has to do with the application of truths to the regeneration of the human mind, by means of which the desires or motivations of the will are purified.

So Spiritual Christianity is spiritual because its focus and life is drawn from a new understanding of the Sacred Scriptures which provides those who are willing to follow its teachings with a new level of spiritual awareness. Again the term spiritual in the phrase “spiritual awareness” refers to that inner work that makes it possible to see and love what is of the Lord in others. To love what is of the Lord in others is what it means to love the neighbour and so loving the neighbour is loving what is genuinely good and true. Our ability to do this comes from the Lord and is the Divine activity in our minds that occurs when we approach the Word with the new understanding that the principles for Spiritual Christianity gives to us. Difficult as it may be for the natural man to grasp, it is clear from the doctrines for Spiritual Christianity themselves that the Lord is indeed the Word and the Word is the Lord. And in the specific context of Logopraxis, by the Word we mean the Sacred Scriptures, these being the Old and New Testament's, and in a more general sense, we also mean the doctrines for Spiritual Christianity as these are drawn from the Word and in that sense are inseparable from it. And so it is, that in the work True Christian Religion 6(1&2) we have this remarkable statement….

  At the core of Sacred Scripture there is nothing but God or the
  divine that comes from God…This is what lies at the heart of
  Scripture. What God himself is like at the heart of the Word is
  something that cannot be seen by any created person or thing [for it
  is] where God exists [in] his own underlying reality, and his own
  essence. Although the inmost divine quality is covered over with
  elements adapted to the comprehension of both angels and people in
  the world, it nevertheless shines through like light through
  crystalline forms. Its radiance varies depending on the condition of
  that mind that we have formed for ourselves either from God or on
  our own. For all those who have formed their state of mind from God,
  Sacred Scripture is like a mirror in which they see God, though each
  in a different way. The mirror is made of truths that they learn
  from the Word and become steeped in through living the life
  according to them. A first conclusion from this is that Sacred
  Scripture is the fullness of God.

The implications of this statement and others like it in the doctrines are profound in terms of our understanding of the Lord and where He is found. They also draw a distinction between the beliefs of natural forms of Christianity whose focus is on the literal sense of the Word and Spiritual Christianity whose focus is on the internal sense of the Word. Natural Christianity, because its attention is fixed in the literal sense, defines its faith around the historical personage of Jesus Christ; Spiritual Christianity on the other hand looks to the Scriptures themselves as God with us and sees in them the Divine presence in our midst. With the gift of the doctrines for Spiritual Christianity we are provided with the means whereby our focus can be shifted away from the historical personage confined within the limitations of time and space, and onto the presence of the Lord found in the spiritual meaning within the Word. For here in the Word, is the Divine ever present with us. We need go no further than the Word in search of God, for here will we find that new church within in, which fullness of God resides.

If we could grasp this, then we would see that the Word becomes a mirror that is able to reveal the Lord to us. Now by the Lord we don't mean the historical person Jesus Christ, but rather what is of the Divine Love and Wisdom or what is good and true, for this is what the term Jesus Christ describes. Angels, the doctrines for Spiritual Christianity teach, when hearing the name of a Biblical personality have no concept of it being a person in the world. For them, a name immediately brings to mind qualities or the states of love and wisdom they represent. But when the natural man hears a name from the Bible,
for example the name Joshua, the thought is first anchored to what we know of him as a historical figure. Then if we have some idea of what he represents we can make a conscious effort in translating and thinking about the text in the light of this. Joshua we now know means Jehovah Saviour, and as the Word is the means by which the Lord saves us we understand by Joshua the Word in action within our minds as the Divine truth. This shift in perception changes everything in the story for we are then able to see that it is no longer dealing with events and figures in the natural world but with the inner realities of our mental world.

Angelic consciousness doesn't have to go through this slow process of translating and extracting meaning. It is in the light of heaven and so when it hears a name, the thoughts and perceptions that arise are immediately centred on the inner meaning that the name points to. This is because nothing of the natural world enters angelic consciousness in relation to spiritual things. It thinks in spiritual terms, which is to say that angelic consciousness thinks in terms of states of goodness and truth or love and wisdom, and their expression in uses. This has implications for when the name of Jesus Christ is heard. Given that angelic consciousness have no conception whatsoever of the natural world, when it hears the name Jesus Christ or Lord it can have no conception of a historical person in the world. Such a fixed reference point is for the man of the natural world due his natural mindedness.
Angelic or spiritual thought as a general rule just doesn't go there,
so the name Jesus Christ in the minds of angelic consciousness gives rise to thoughts concerned with the full manifestation of Divine love and wisdom which is recognised in the heavens as God's presence. It sees the Lord in everything around it for those in a state of angelic consciousness have senses which are spiritual and perceive, without a second thought, everything in terms of states of good and truth.

The holiness and sanctity of the Word lies within the literal sense in its spiritual meaning, for this is the Divine Itself and in its innermost meaning, which is beyond the comprehension of any finite creature, is God in his Being and Essence. This revelation of God in the Sacred Scripture is what the doctrines for Spiritual Christianity are all about and we are repeatedly told that the Word concerns itself solely with the things of the church, understood as spiritual consciousness, and doesn't deal with history or figures of history. As such, states of angelic consciousness are available to us through the principles of Spiritual Christianity and its teachings but we need to constantly remind ourselves of these truths when it comes to reading and studying the Word. Our struggle to get beyond the historical meaning of the Word is what the crossing of the Jordan River by the Israelites is all about. If our thinking gets caught up in the historical elements we will not see its spiritual application or meaning. In other words, we will not see its application in terms of our regeneration and it is in seeing this, that we see the Lord.

Similarly, in the New Testament, if our minds get caught up in the historical details and personalities in the stories we won't see their relevance to us now. Natural thinking in relation to spiritual things closes the mind down because the natural senses can only detect what belongs to lowest level of consciousness. Spiritual truths are needed to open the eyes of our understanding as far as spiritual matters are concerned, which is why we need the doctrines for Spiritual Christianity. These were revealed to give us the truths to open our minds to the fact that the Lord is in the Sacred Scriptures and that the Word is in fact the Lord.

Without these truths we lack what's needed to push back the natural associations triggered by the literal sense of the Word. These natural associations that see things in terms of history, forms a formidable barrier to having our perceptions shift from crossing over from the historical literal meaning of the Word and into its spiritual meaning.
This is illustrated by the Jordan River in flood, forming an obstacle to the sons of Israel being able to cross into Canaan. For it is the false perspectives drawn from the senses which latch onto the literal meaning of the Word and prevents its inner spiritual meaning from shinning forth to view. Without spiritual truths we will remain outside the border of that personal spiritual Canaan that lies within the Word.
If, as we read from True Christian Religion, the Lord is in the inmost of the Sacred Scripture then so is heaven, for heaven is nothing else than the presence of the Lord.

The ideas in the doctrines for Spiritual Christianity bring God and heaven into the very present realities of life. In other words, they make the Lord visible, not in a physical sense but in the sense that we can understand life in the light of His providence or care all around us. Heaven is not a place, heaven or true happiness is a state of life that is based on the goods and truths we have made one with our life.
These goods and truths are the Word and therefore it follows that the Word or the Sacred Scriptures is heaven. But do we see the implications of this? Or are we standing on the far side of Jordan, knowing there is a heaven but being unable to see its reality in the present because the Word remains a closed book to us?

The story of this crossing illustrates the fundamental truth that within the principles of Spiritual Christianity, the Lord has provided us with all that we need to make this crossing from a natural to a spiritual understanding of the Word and so into heaven now. In other words, the opportunity is here now -- for our crossing to begin while we are living on the natural worldly plane of existence. We don't go to heaven when we die for heaven comes to us when we are prepared to die to self and live from the Word. We have looked now at a number of principles which are necessary preconditions to making this crossing.
Ideas like we have to give up our ownership of what is good and true which was represented by Shittim. We have to be willing to be led by the Word and not by our own intelligence and prudence, represented by the sons of Israel following the Ark of the Covenant carried by the priests. We need to acknowledge that the Lord speaks through Joshua or the Word when it is applied to life, for as we have seen this is what Joshua represents. And we need to constantly remind ourselves of these principles so that they remain active and able to govern the life of our thoughts and affections.

This need is represented in our story by the command to create a memorial of twelve stones. Notice that two piles of twelve stones were put in place. One at Gilgal and the other in the midst of the river where the priests stood. What this teaches us is of the need to constantly remind ourselves that all the truths we need to live life as the Lord intends us to live it are to be found in the Word. Stones correspond to truths and twelve is a number that means what is full and complete. All doctrine or teaching relating to the spiritual life is represented by the stones set up on the dry ground. The parallel stack of stones set up in the midst of the river is there to remind us that all doctrine pertaining to the spiritual life is to be found in, and so is to be drawn from, the literal sense of the Word. That this second set of stones is built up at the point of where the feet of the priests stood in the river teaches that the internal sense of the Word is opened to all those who are in the desire and effort to understand truths and live from them. This is due to the fact that priests are charged with teaching truths that lead to the good of life and so within our own minds the term priest refers to an inner desire from the Lord to examine our life and make the changes that we need to make in the light of the truths which we are learning from the Word.

As we look to put these principles into practice so we will find that the stream of false ideas that flows when we are reading the Word and caught up in its literal meaning will be cut off. The Jordan's waters will cease to flow and we will find that we can cross over and see the power of the Lord manifesting and shining forth in the spiritual meaning of the Word. It will open up for us. When this occurs the literal meaning falls away and is no longer something that prevents us entering into spiritual realities but rather becomes something vital in support of our ongoing spiritual growth and development. This shift is seen in the placement of the stones as a memorial of the Lord's power through this miracle which enabled the Israelites to cross over. From within the boundaries of Canaan the Jordan River represents the natural truths of the Word and forms the most external border of the land. This corresponds to the written Word of the Sacred Scriptures, which when understood in the light of those truths found in the doctrines for Spiritual Christianity, opens up for us what it means to lead a genuine spiritual life and by means of that, enter into the life of heaven –
now.

  And Joshua set up twelve other stones in the middle of the Jordan,
  in the place where the feet of the priests bearing the ark of the
  covenant stood firm. And they are there until this day.

