ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]

---
ifdef::fullbook[]
<<<
endif::[]




== 11. Rolling Away The Reproach Of The Past (5)

____
And it happened, when all the kings of the Amorites beyond the Jordan, toward the sea, and all the kings of the Canaanites which were by the sea, heard how Jehovah dried up the waters of the Jordan before the sons of Israel, until they crossed over, their heart was melted. And there was not any more spirit in them before the sons of Israel. At that time Jehovah said to Joshua, Make for yourself flint knives, and again circumcise the sons of Israel, the second time. And Joshua made flint knives for himself, and circumcised the sons of Israel at the hill of the foreskins. And this is the reason Joshua circumcised: All the people who had come out of Egypt, who were males, all the men of war, had died in the wilderness, in the way, as they came out of Egypt. For all the people who had come out were circumcised. And all the people who were born in the wilderness, in the way, as they came out from Egypt, had not been circumcised. For the sons of Israel had walked forty years in the wilderness, until all the nation, the men of war who had come out of Egypt were consumed, those who did not listen to the voice of Jehovah, to whom Jehovah had sworn to them not to show them the land which Jehovah swore to their fathers, to give to us, a land flowing with milk and honey; these were consumed. And He raised their sons up in their place. Joshua circumcised them, for they had been uncircumcised; for they had not been circumcised in the way. And it happened, when all the nation had finished being circumcised, they remained in their places in the camp until they revived. And Jehovah said to Joshua, Today I have rolled the reproach of Egypt off of you. And he called the name of that place Gilgal to this day. And the sons of Israel camped in Gilgal, and prepared the Passover on the fourteenth day of the month, at evening, in the plains of Jericho. And they ate the old grain of the land on the morrow of the Passover, unleavened bread and roasted grain, in this same day. And the manna ceased on the next day after they ate of the old grain of the land. And there was no more manna to the sons of Israel, but they ate the produce of the land of Canaan in that year. And it happened, when Joshua was beside Jericho, that he lifted up his eyes and looked. And, behold! A Man stood in front of him, and His drawn sword was in His hand. And Joshua went to Him and said to Him, Are You for us, or for our foes? And He said, No, for I now come as the Commander of the army of Jehovah. And Joshua fell on his face to the earth and worshiped. And he said to Him, What does my Lord speak to His slave? And the Commander of the army of Jehovah said to Joshua, Take your shoe off your foot, for the place on which you are standing is holy. And Joshua did so. (Joshua Chapter 5:1-15)
____

  Here is a marvel: When angels in heaven conceive the idea of purification from natural things that are filthy, something akin to circumcision is represented very speedily in the world of spirits, for in the world of spirits angelic ideas come over as representatives. In the Jewish Church there were some representative religious ceremonies which had those same origins and there were others which did not. The spirits with whom that swift circumcision was represented in the world of spirits were people who wished to be allowed into heaven, but before they were allowed in this representation took place. This explains why Joshua was commanded to circumcise the people after they had crossed the Jordan and were about to enter the land of Canaan. The people's entry into the land of Canaan represented nothing else than the admission into heaven of those who have had faith.
  This is why circumcision was commanded a second time, described in Joshua as follows, 
  ----
  "Jehovah said to Joshua, Make swords of flint for yourself; circumcise the children of Israel a second time. And Joshua made swords of flint for himself, and circumcised the children of Israel on the hill of foreskins. And Jehovah said to Joshua, This day I have rolled away the reproach of Egypt from you. And he called the name of that place Gilgal (rolling away)." (Joshua 5:2,3,9).
  ----
  'Swords of flint' means the truths which they were to be provided with to enable them to correct and cut back filthy loves, for without cognitions of truth no purification is possible. That 'stone' or 'flirt' means truths has been shown already, in 643, 1298, and that 'a sword' has reference to truths by which evils may be corrected is clear from the Word.
 (Arcana Coelestia 2039 {7 & 8})

So we come today to the fifth chapter of the book of Joshua. And this chapter is a chapter of consolidation, a chapter of preparation, a chapter of purification. And it's the chapter that precedes the battle that the Israelites are going to have to engage in against the walled city of Jericho. Everything described in this chapter is needful prior to them being able to go up and follow the Lord's command in order to take Jericho. So we saw last time that the crossing of the _River Jordan_ was this state of moving beyond the literal sense of the Word into its spiritual sense, where the things of senses fall away. That our mind moves from being caught up in the things of person, place and time -- into seeing what is spiritual, what lies within the Word. It's very life. We saw that the Lord indeed is the Word and is the one who leads and guides us.

Today we will look more closely at this idea of consolidation and preparation. This occurs with the _Israelites_ who are camping at _Gilgal_ which means '_a rolling off_' so we will to see what it is that is rolled off that enables the Israelites to move on. It also speaks in the Text of the _reproach of Egypt._ being removed and in this we get this sense that _Gilgal_ then is a time to meditate on the new state of life that one is coming into, on the state of seeing the Word in a new way. A time of becoming established in these new truths that are able to support a genuine spiritual life. Also involved at this place called _Gilgal_ is purification. And this is vital to enable us to move forward,
to move into the deeper things of the Lord's Word so that the more interior things within us that need dealing with can be exposed and cut off. We see there that with this new understanding of the Word comes a host of new responsibilities, particularly in terms of the application of the Word to the life of the mind, to the realm of our thoughts and our affections.

Now this is a different state to the one the Israelites had under _Moses_ which was a state of obedience. That state was dominated by worldly and self-interest. It was a time of compliance, a time where they were fed with _manna_ in the wilderness, something that to most if not all of them, was distasteful. And just as the _Israelites_ were fighting with having to work through and follow the command of the Lord, so too this obedience is required of us in having to compel ourselves to work with the Word. To use its truths examine the quality of our thoughts and affections so that the loves of self and the world are able to be brought into order. And in fact the _Israelites_ followed _Moses_ in obedience out of fear of consequences which reflects what lies in the mix of our own initial motivations to engage in spiritual work. Fear of perhaps not being good enough to get into heaven, or of meeting the Lord's standards, or our own.

But _Joshua_ is a new state. It's a state where a love for the things of the Word has been developed within us so we can move into the land. The _manna_ is finished and we now fed from a will for what is good and true.
The Lord is able to sustain us in a new way. In this state of _Gilgal_ there is a second _circumcision_ that is to take place because the _sons of Israel_ that were born in the wilderness had not been circumcised.
And so prior to moving on further into taking the land, which as we've seen previously represents states of heaven, there is a need for purification. This is a _cutting off_ of what obscures the loves of heaven from having a much more and much stronger and deeper impact in our lives, in the experience of our life. So _circumcision_ reflects a time of a new beginning as does also the _Israelites_ moving in and eating of a _Passover_. And it is as they go through that process that _Joshua_, the commander of the host appears and he represents the new understanding of the Lord's power and providence to bring us through,
for it is the Divine Human alone that fights for us.

This chapter opens with a statement regarding the kings of the _Amorites_ and the kings of the _Canaanites_ -- that their _hearts melted_ and that there was _no spirit_ left in them because they had seen what the Lord had done in the parting of the waters so that the children or the _sons of Israel_ could cross over. Now in the book of Joshua we have at the beginning of each chapter the statement "_and it came to pass_" but in the Hebrew this can literally be read as _"and he is becoming."_ And this is a great statement regarding the Word and its operation in our life.
For in relation to us the Lord is becoming. He is becoming more real for us. As we advance in the things of the Word, in his goods and his truths, and we see their application to our life, so He is becoming.
Each step of the children of Israel through the book of Joshua is the Lord coming into being in the reality of our life and experience. It is our perception moving from being caught up in those historical elements of the literal sense of the Word and beginning to see the glory of the internal sense shining forth. And so we enter into a new state of life.
And that state of life is such that the principles of evil and falsity -- _their hearts melt and there is no spirit_, there is no life left in them. Because now this state is one of having a new will developed through the Lord's Word, for through obedience to that Word being established within our life a desire or will for what is good and what is true emerges. That is why those old states of life that have been built up from the loves of self and the world tremble and quake.
Because there is a realisation at a very deep level that the Lord is in command. That it is the Lord who fights for us and that it is the Lord who wins the victory.

The _kings of the Amorites_, as we've seen previously, represent the false ideas and perspectives that support the love of self and the world. And the loves of self and the world are represented by the _kings of the Canaanites_, as the principles that are established in our old form of life. So with this crossing of the _sons of Israel_, which represents the truths of the Lord's Word becoming more organized and gathered together, a way forward opens. And that way is a way whereby those things that once assailed us that flow out of the love of self and the love of the world, can begin to be put down and no longer exert their dominance in our life.

The _Canaanite_ is the love of self and this '_love of self_' is a common term used in the doctrines for Spiritual Christianity. It is a love of what the Lord gives us, a sense of ourselves but it's a love so strong that we begin believing that the appearance that we have life in ourselves -- is the reality. And the doctrines for Spiritual Christianity teach very clearly that our life, that our sense of self,
is but an appearance, a very real and necessary appearance but an appearance nonetheless. For the Lord alone is the only self, the Lord alone is the supreme Self. And everything that has a sense of self derives that from the Lord for He alone has life in Himself. Everything else derives their life from Him but we are born into a powerful appearance that that life is our own. And when we believe the appearance to be real we are partaking from the tree of the knowledge of good and evil because it is in believing the appearance to be real,
that all evils and falsities flow from. If we truly grasped that the self that we have is an appearance, then there would be no reason to be defensive of ourselves. It would put to rest every negative emotion that we have in our experience. We would realise that there is nothing to defend, that the Lord alone is the source of all life, and that it is to Him that we need to be connected. But when the appearance is believed to be true, then we are separated from the Lord because the Lord cannot dwell in what is false. He can use it to bring us closer to Himself, but he can't dwell within it. And so we see that "_evil_" in the Old Testament, in the Hebrew, means _to separate, to shatter, to break apart_, a disorganized mass ... disconnected.

So the Lord looks to put things back together and He does it by means of His Word. As we learn truths from the Word, the Lord begins to gather and reorganize the things within our mind that are from Him. As this happens they begin to form a mirror through which the Lord can be reflected back into our consciousness so that we can see what is good and what is true. But that mirror and that gathering together can only occur as we remove those evils and falsities that arise from the appearances of the senses. And this story of the _Israelites_ moving into the land of _Canaan_, is about that removal -- of what obscures the Lord's love, of what obscures His warmth and our connection to Him. And so the Lord give us His Word so that we may hear and see what it is that needs to be removed and what it is also that He requires of us in that.

  At that time Jehovah said to Joshua, Make for yourself flint knives, and again circumcise the sons of Israel, the second time. And Joshua made flint knives for himself, and circumcised the sons of Israel at the hill of the foreskins.

In verse 2 we see the Lord saying to Joshua to make _knives of flint_ or if you like knives of rock, truths fashioned for the purpose of cutting away what is of the flesh, to _circumcise_ the _sons of Israel_. We can look at this as the Lord asking that the rock that is the Word be fashioned into a use, into a _spiritual_ _knife of flint_. This bespeaks the idea of self-examination and reflection so that those things that obscure the Lord can be cut away and that we can enter into the reality and power of His life. But it is not enough just to acknowledge intellectually that our life is not our own because if we look we will see, if we use the Word as a _knife of flint_, that the reality of our life is one in which we operate from a belief that the self or our life is our own. Every negative emotion, every uncharitable deed, thought and affection arises from this belief and if we are willing to use the Word to reflect on our life on a daily basis, then we will see what is operating aside from what we intellectually subscribe to. And this is done so that what we know and how we live might be brought together and made into one. So the making of _flint knives_ for the circumcision has to do with taking the Word and using it in the effort to examine ourselves and to move into a life of repentance, of having our mind transformed.

Now this is a second circumcision we are told, for the _sons of Israel_ who were _born in the wilderness_ were uncircumcised and so there was a need to have them _circumcised_.

  And all the people who were born in the wilderness, in the way, as they came out from Egypt, had not been circumcised. For the sons of Israel had walked forty years in the wilderness, until all the nation, the men of war who had come out of Egypt were consumed, those who did not listen to the voice of Jehovah, to whom Jehovah had sworn to them not to show them the land which Jehovah swore to their fathers, to give to us, a land flowing with milk and honey; these were consumed. And He raised their sons up in their place. Joshua circumcised them, for they had been uncircumcised; for they had not been circumcised in the way.

In our first first phase of spiritual life, as represented by the _sons of Israel_ being under the leadership of _Moses_, there is an external compliance with truths out of a fear of consequences, a fear perhaps that if we don't comply we won't be granted entry into heaven, or meet the grade of the what the Lord asks of us or our own personal idea of what a 'good person' should be. And in that struggle and temptation represented by the _wilderness_ there are new truths born but because worldly and self-centred concerns still dominate our life, these truths in terms of their true quality as yet are unseen. We are too engrossed in our own stuff. But as we move through this process of the _wilderness_ those old truths that we used to live our life by or rather that old understanding of truth that we lived from, begins to die off. It no longer really sustains us or is able to carry us on and with the crossing over into the land of _Canaan_, a new body of ideas starts to take their rightful place.

But in order for this working _army_, this body of ideas, to become powerful there is a need for a cutting away. To use the Word to cut away elements of selfishness and worldliness so that our perception can become more attuned to the Lord's Word and to what lies within it.
Because as we are prepared to cut away what is of self in the world so in a sense the old understanding that is trapped in the literal meaning of the Word is also cut away and then the spiritual meaning begins to show itself. It comes through in the light that comes from the Lord and it shines within the mind. It is given so that we can move from external obedience and compliance in terms of our outward behavior to actually dealing with the root causes which are the affections and thoughts that underlie it and thus begin to see these things, these kings of the _Amorites_ and the _Canaanites_, cut away.

And so the truths of the Lord's Word cause their _heart to melt_, takes the _spirit_ out of them. They no longer are able to dominate our life like they once did. However, in this cutting away there is a pain that cannot be avoided and it is connected with the attachment which we have to what is of self in the world. But it's a pain that must be endured if we are to move on and see the Lord as He is in His Word. For the separation of what is evil and false from what is good and true and the giving up of the idea that our life is our own is a painful process because we have lived our lives from these things for so long. They have become so much a part of who we think we are. But here the Lord wants to make us new, to renew us and give us a new sense of self which is based on the truths of His Word. A sense of self that is grounded in the principles of a spiritual Christianity. So that we live and we follow the Lord, we follow the _Ark of the Covenant_. It is only by taking those principles and seeing how they really apply to our life that the Lord's love and wisdom can become established. And this is how a true spirit of charity is developed and grows, how we become a use fitted for the Lord's purposes in the things of the Spirit.

Now after the _sons of Israel_ who were born in the _wilderness_ had been _circumcised_, they remained in _Gilgal_ until they were _revived_.

  And it happened, when all the nation had finished being circumcised, they remained in their places in the camp until they revived. And Jehovah said to Joshua, Today I have rolled the reproach of Egypt off of you. And he called the name of that place Gilgal to this day.

This new phase of life is something truly remarkable, a miracle given our state of separation from the Lord. But the Lord is compassionate,
merciful and kind and He looks to bring us through. He never leaves us nor forsakes us no matter how painful and difficult things appear. The Lord is always fully present, He never goes anywhere and by means of reconnecting with His Word we will see that. So they wait at _Gilgal_ until they are healed and made whole. And this is described as the _reproach of Egypt_ being removed for as we saw earlier, _Gilgal_ means a rolling off and so it is that the Lord says that He _rolls off the reproach of Egypt_.

But what is it this _reproach of Egypt._ It is our vulnerability due to a lack of truths in our life. It is that early phase of life that has lasted right up until this point. Forty years through the _wilderness_ and now the _reproach of Egypt_ is being _rolled off_. Why? Because up until this point we lacked an understanding of the Lord. Of His nature,
of His Word, of its internal sense. And so while we desired the good and true things that the Lord promises we were often caught out and found ourselves powerless to see those things affected in our life. And so the _reproach of Egypt_ is where what is lower keeps dominating,
cracking through and deflating us and bringing us to points of frustration and despondency. Activating an internal thought of life that says 'You'll never make it! Why bother? Why keep going? This is the _reproach of Egypt._ And here through the revelation of the internal sense of the Word what we have is instruction and vision as to what the Lord will bring about if we persevere. Because as we move through the literal sense of the Word and become established in its internal sense,
cracking through and deflating us and bringing us to points of frustration and despondency. Activating an internal thought of life that says 'You'll never make it! Why bother? Why keep going? This is the _reproach of Egypt._ And here through the revelation of the internal sense of the Word what we have is instruction and vision as to what the Lord will bring about if we persevere. Because as we move through the literal sense of the Word and become established in its internal sense,
then and only then can that _reproach_ be _rolled off_. Because we have established principles within us that are woven into the very fabric of our thought and affection. This allows us to enter into a conscious awareness of the Lord's presence with us where we are much more secure,
peaceful and trusting that we are in a process in which the Lord is leading and guiding it every step of the way.

And so once this work of purification is affected we find an evening state described for happens afterwards is that a Passover is prepared.

  And the sons of Israel camped in Gilgal, and prepared the Passover on the fourteenth day of the month, at evening, in the plains of Jericho. And they ate the old grain of the land on the morrow of the Passover, unleavened bread and roasted grain, in this same day. And the manna ceased on the next day after they ate of the old grain of the land. And there was no more manna to the sons of Israel, but they ate the produce of the land of Canaan in that year.

So there is a shift in state. We no longer eat the food of reluctant obedience, we now have a will that is fashioned by the Lord within a new understanding which comes forth as a desire and a delight in what is good and true. A new way of being sustained. And that is the _old grain of the land that the sons of Israel are now able to partake of.
The word _old_ actually means _transition_, a shift reflecting this change of state. As this process comes near to its completion something begins to happen in terms of our perception of the word -- the _Commander_ of the _army_ appears to _Joshua_.

  And it happened, when Joshua was beside Jericho, that he lifted up his eyes and looked. And, behold! A Man stood in front of him, and His drawn sword was in His hand. And Joshua went to Him and said to Him, Are You for us, or for our foes? And He said, No, for I now come as the Commander of the army of Jehovah. And Joshua fell on his face to the earth and worshiped. And he said to Him, What does my Lord speak to His slave? And the Commander of the army of Jehovah said to Joshua, Take your shoe off your foot, for the place on which you are standing is holy. And Joshua did so.

Now _Joshua_ is our understanding of the Word as it is applicable to life. But something new is beginning to happen. The Lord is beginning to be seen as the Word, as the Divine Human itself. For here is this _Commander_ of the _army_ to whom _Joshua_ bows down and he reveals that he doesn't have an agenda in terms of taking sides for what the Lord is interested in is the salvation of all people, of bringing them all to heaven. And that is all the Lord is interested in. And so this represents a perception that arises from the Word, reinforcing and strengthening the Lord as the _Commander_. The Lord's care and providence is over all things and as this begins to be reflected in our life and in our understanding, so everything begins to change. And we are prepared for that battle where the _children of Israel_ have to go up and confront what is represented by _Jericho_. And we will explore that next time.

