ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 11. Rolling Away The Reproach Of The Past (5)

  And it happened, when all the kings of the Amorites beyond the
  Jordan, toward the sea, and all the kings of the Canaanites which
  were by the sea, heard how Jehovah dried up the waters of the Jordan
  before the sons of Israel, until they crossed over, their heart was
  melted. And there was not any more spirit in them before the sons of
  Israel. At that time Jehovah said to Joshua, Make for yourself flint
  knives, and again circumcise the sons of Israel, the second time.
  And Joshua made flint knives for himself, and circumcised the sons
  of Israel at the hill of the foreskins. And this is the reason
  Joshua circumcised: All the people who had come out of Egypt, who
  were males, all the men of war, had died in the wilderness, in the
  way, as they came out of Egypt. For all the people who had come out
  were circumcised. And all the people who were born in the
  wilderness, in the way, as they came out from Egypt, had not been
  circumcised. For the sons of Israel had walked forty years in the
  wilderness, until all the nation, the men of war who had come out of
  Egypt were consumed, those who did not listen to the voice of
  Jehovah, to whom Jehovah had sworn to them not to show them the land
  which Jehovah swore to their fathers, to give to us, a land flowing
  with milk and honey; these were consumed. And He raised their sons
  up in their place. Joshua circumcised them, for they had been
  uncircumcised; for they had not been circumcised in the way. And it
  happened, when all the nation had finished being circumcised, they
  remained in their places in the camp until they revived. And Jehovah
  said to Joshua, Today I have rolled the reproach of Egypt off of
  you. And he called the name of that place Gilgal to this day. And
  the sons of Israel camped in Gilgal, and prepared the Passover on
  the fourteenth day of the month, at evening, in the plains of
  Jericho. And they ate the old grain of the land on the morrow of the
  Passover, unleavened bread and roasted grain, in this same day. And
  the manna ceased on the next day after they ate of the old grain of
  the land. And there was no more manna to the sons of Israel, but
  they ate the produce of the land of Canaan in that year. And it
  happened, when Joshua was beside Jericho, that he lifted up his eyes
  and looked. And, behold! A Man stood in front of him, and His drawn
  sword was in His hand. And Joshua went to Him and said to Him, Are
  You for us, or for our foes? And He said, No, for I now come as the
  Commander of the army of Jehovah. And Joshua fell on his face to the
  earth and worshiped. And he said to Him, What does my Lord speak to
  His slave? And the Commander of the army of Jehovah said to Joshua,
  Take your shoe off your foot, for the place on which you are
  standing is holy. And Joshua did so. (Joshua Chapter 5:1-15)

  Here is a marvel: When angels in heaven conceive the idea of
  purification from natural things that are filthy, something akin to
  circumcision is represented very speedily in the world of spirits,
  for in the world of spirits angelic ideas come over as
  representatives. In the Jewish Church there were some representative
  religious ceremonies which had those same origins and there were
  others which did not. The spirits with whom that swift circumcision
  was represented in the world of spirits were people who wished to be
  allowed into heaven, but before they were allowed in this
  representation took place. This explains why Joshua was commanded to
  circumcise the people after they had crossed the Jordan and were
  about to enter the land of Canaan. The people's entry into the land
  of Canaan represented nothing else than the admission into heaven of
  those who have had faith.

  This is why circumcision was commanded a second time, described in
  Joshua as follows, Jehovah said to Joshua, Make swords of flint for
  yourself; circumcise the children of Israel a second time. And
  Joshua made swords of flint for himself, and circumcised the
  children of Israel on the hill of foreskins. And Jehovah said to
  Joshua, This day I have rolled away the reproach of Egypt from you.
  And he called the name of that place Gilgal (rolling away). Josh.
  5:2, 3, 9. 'Swords of flint' means the truths which they were to be
  provided with to enable them to correct and cut back filthy loves,
  for without cognitions of truth no purification is possible. That
  'stone' or 'flirt' means truths has been shown already, in 643,
  1298, and that 'a sword' has reference to truths by which evils may
  be corrected is clear from the Word. (Arcana Coelestia 2039 {7 & 8})

So we come today to the fifth chapter of the book of Joshua. And this chapter is a chapter of consolidation, a chapter of preparation, a chapter of purification. And it's the chapter that precedes the battle that the Israelites are going to have to engage in against the walled city of Jericho. Everything described in this chapter is needful prior to them being able to go up and follow the Lord's command in order to take Jericho. So we saw last time that the crossing of the River Jordan was this state of moving beyond the literal sense of the Word into its spiritual sense, where the things of senses fall away. That our mind moves from being caught up in the things of person, place and time –
into seeing what is spiritual, what lies within the Word. It's very life. We saw that the Lord indeed is the Word and is the one who leads and guides us.

Today we will look more closely at this idea of consolidation and preparation. This occurs with the Israelites who are camping at Gilgal which means 'a rolling off' so we will to see what it is that is rolled off that enables the Israelites to move on. It also speaks in the Text of the reproach of Egypt being removed and in this we get this sense that Gilgal then is a time to meditate on the new state of life that one is coming into, on the state of seeing the Word in a new way. A time of becoming established in these new truths that are able to support a genuine spiritual life. Also involved at this place called Gilgal is purification. And this is vital to enable us to move forward,
to move into the deeper things of the Lord's Word so that the more interior things within us that need dealing with can be exposed and cut off. We see there that with this new understanding of the Word comes a host of new responsibilities, particularly in terms of the application of the Word to the life of the mind, to the realm of our thoughts and our affections.

Now this is a different state to the one the Israelites had under Moses which was a state of obedience. That state was dominated by worldly and self-interest. It was a time of compliance, a time where they were fed with manna in the wilderness, something that to most if not all of them, was distasteful. And just as the Israelites were fighting with having to work through and follow the command of the Lord, so too this obedience is required of us in having to compel ourselves to work with the Word. To use its truths examine the quality of our thoughts and affections so that the loves of self and the world are able to be brought into order. And in fact the Israelites followed Moses in obedience out of fear of consequences which reflects what lies in the mix of our own initial motivations to engage in spiritual work. Fear of perhaps not being good enough to get into heaven, or of meeting the Lord's standards, or our own.

But Joshua is a new state. It's a state where a love for the things of the Word has been developed within us so we can move into the land. The manna is finished and we now fed from a will for what is good and true.
The Lord is able to sustain us in a new way. In this state of Gilgal there is a second circumcision that is to take place because the sons of Israel that were born in the wilderness had not been circumcised.
And so prior to moving on further into taking the land, which as we've seen previously represents states of heaven, there is a need for purification. This is a cutting off of what obscures the loves of heaven from having a much more and much stronger and deeper impact in our lives, in the experience of our life. So circumcision reflects a time of a new beginning as does also the Israelites moving in and eating of a Passover. And it is as they go through that process that Joshua, the commander of the host appears and he represents the new understanding of the Lord's power and providence to bring us through,
for it is the Divine Human alone that fights for us.

This chapter opens with a statement regarding the kings of the Amorites and the kings of the Canaanites -- that their hearts melted and that there was no spirit left in them because they had seen what the Lord had done in the parting of the waters so that the children or the sons of Israel could cross over. Now in the book of Joshua we have at the beginning of each chapter the statement “and it came to pass” but in the Hebrew this can literally be read as “and he is becoming.” And this is a great statement regarding the Word and its operation in our life.
For in relation to us the Lord is becoming. He is becoming more real for us. As we advance in the things of the Word, in his goods and his truths, and we see their application to our life, so He is becoming.
Each step of the children of Israel through the book of Joshua is the Lord coming into being in the reality of our life and experience. It is our perception moving from being caught up in those historical elements of the literal sense of the Word and beginning to see the glory of the internal sense shining forth. And so we enter into a new state of life.
And that state of life is such that the principles of evil and falsity
– their hearts melt and there is no spirit, there is no life left in them. Because now this state is one of having a new will developed through the Lord's Word, for through obedience to that Word being established within our life a desire or will for what is good and what is true emerges. That is why those old states of life that have been built up from the loves of self and the world tremble and quake.
Because there is a realisation at a very deep level that the Lord is in command. That it is the Lord who fights for us and that it is the Lord who wins the victory.

The kings of the Amorites, as we've seen previously, represent the false ideas and perspectives that support the love of self and the world. And the loves of self and the world are represented by the kings of the Canaanites, as the principles that are established in our old form of life. So with this crossing of the sons of Israel, which represents the truths of the Lord's Word becoming more organised and gathered together, a way forward opens. And that way is a way whereby those things that once assailed us that flow out of the love of self and the love of the world, can begin to be put down and no longer exert their dominance in our life.

The Canaanite is the love of self and this 'love of self' is a common term used in the doctrines for Spiritual Christianity. It is a love of what the Lord gives us, a sense of ourselves but it's a love so strong that we begin believing that the appearance that we have life in ourselves -- is the reality. And the doctrines for Spiritual Christianity teach very clearly that our life, that our sense of self,
is but an appearance, a very real and necessary appearance but an appearance nonetheless. For the Lord alone is the only self, the Lord alone is the supreme Self. And everything that has a sense of self derives that from the Lord for He alone has life in Himself. Everything else derives their life from Him but we are born into a powerful appearance that that life is our own. And when we believe the appearance to be real we are partaking from the tree of the knowledge of good and evil because it is in believing the appearance to be real,
that all evils and falsities flow from. If we truly grasped that the self that we have is an appearance, then there would be no reason to be defensive of ourselves. It would put to rest every negative emotion that we have in our experience. We would realise that there is nothing to defend, that the Lord alone is the source of all life, and that it is to Him that we need to be connected. But when the appearance is believed to be true, then we are separated from the Lord because the Lord cannot dwell in what is false. He can use it to bring us closer to Himself, but he can't dwell within it. And so we see that “evil” in the Old Testament, in the Hebrew, means to separate, to shatter, to break apart, a disorganised mass … disconnected.

So the Lord looks to put things back together and He does it by means of His Word. As we learn truths from the Word, the Lord begins to gather and reorganise the things within our mind that are from Him. As this happens they begin to form a mirror through which the Lord can be reflected back into our consciousness so that we can see what is good and what is true. But that mirror and that gathering together can only occur as we remove those evils and falsities that arise from the appearances of the senses. And this story of the Israelites moving into the land of Canaan, is about that removal -- of what obscures the Lord's love, of what obscures His warmth and our connection to Him. And so the Lord give us His Word so that we may hear and see what it is that needs to be removed and what it is also that He requires of us in that.

  At that time Jehovah said to Joshua, Make for yourself flint knives,
  and again circumcise the sons of Israel, the second time. And Joshua
  made flint knives for himself, and circumcised the sons of Israel at
  the hill of the foreskins.

In verse 2 we see the Lord saying to Joshua to make knives of flint or if you like knives of rock, truths fashioned for the purpose of cutting away what is of the flesh, to circumcise the sons of Israel. We can look at this as the Lord asking that the rock that is the Word be fashioned into a use, into a spiritual knife of flint. This bespeaks the idea of self-examination and reflection so that those things that obscure the Lord can be cut away and that we can enter into the reality and power of His life. But it is not enough just to acknowledge intellectually that our life is not our own because if we look we will see, if we use the Word as a knife of flint, that the reality of our life is one in which we operate from a belief that the self or our life is our own. Every negative emotion, every uncharitable deed, thought and affection arises from this belief and if we are willing to use the Word to reflect on our life on a daily basis, then we will see what is operating aside from what we intellectually subscribe to. And this is done so that what we know and how we live might be brought together and made into one. So the making of flint knives for the circumcision has to do with taking the Word and using it in the effort to examine ourselves and to move into a life of repentance, of having our mind transformed.

Now this is a second circumcision we are told, for the sons of Israel who were born in the wilderness were uncircumcised and so there was a need to have them circumcised.

  And all the people who were born in the wilderness, in the way, as
  they came out from Egypt, had not been circumcised. For the sons of
  Israel had walked forty years in the wilderness, until all the
  nation, the men of war who had come out of Egypt were consumed,
  those who did not listen to the voice of Jehovah, to whom Jehovah
  had sworn to them not to show them the land which Jehovah swore to
  their fathers, to give to us, a land flowing with milk and honey;
  these were consumed. And He raised their sons up in their place.
  Joshua circumcised them, for they had been uncircumcised; for they
  had not been circumcised in the way.

In our first first phase of spiritual life, as represented by the sons of Israel being under the leadership of Moses, there is an external compliance with truths out of a fear of consequences, a fear perhaps that if we don't comply we won't be granted entry into heaven, or meet the grade of the what the Lord asks of us or our own personal idea of what a 'good person' should be. And in that struggle and temptation represented by the wilderness there are new truths born but because worldly and self-centred concerns still dominate our life, these truths in terms of their true quality as yet are unseen. We are too engrossed in our own stuff. But as we move through this process of the wilderness those old truths that we used to live our life by or rather that old understanding of truth that we lived from, begins to die off. It no longer really sustains us or is able to carry us on and with the crossing over into the land of Canaan, a new body of ideas starts to take their rightful place.

But in order for this working army, this body of ideas, to become powerful there is a need for a cutting away. To use the Word to cut away elements of selfishness and worldliness so that our perception can become more attuned to the Lord's Word and to what lies within it.
Because as we are prepared to cut away what is of self in the world so in a sense the old understanding that is trapped in the literal meaning of the Word is also cut away and then the spiritual meaning begins to show itself. It comes through in the light that comes from the Lord and it shines within the mind. It is given so that we can move from external obedience and compliance in terms of our outward behaviour to actually dealing with the root causes which are the affections and thoughts that underlie it and thus begin to see these things, these kings of the Amorites and the Canaanites, cut away.

And so the truths of the Lord's Word cause their heart to melt, takes the spirit out of them. They no longer are able to dominate our life like they once did. However, in this cutting away there is a pain that cannot be avoided and it is connected with the attachment which we have to what is of self in the world. But it's a pain that must be endured if we are to move on and see the Lord as He is in His Word. For the separation of what is evil and false from what is good and true and the giving up of the idea that our life is our own is a painful process because we have lived our lives from these things for so long. They have become so much a part of who we think we are. But here the Lord wants to make us new, to renew us and give us a new sense of self which is based on the truths of His Word. A sense of self that is grounded in the principles of a spiritual Christianity. So that we live and we follow the Lord, we follow the Ark of the Covenant. It is only by taking those principles and seeing how they really apply to our life that the Lord's love and wisdom can become established. And this is how a true spirit of charity is developed and grows, how we become a use fitted for the Lord's purposes in the things of the Spirit.

Now after the sons of Israel who were born in the wilderness had been circumcised, they remained in Gilgal until they were revived.

  And it happened, when all the nation had finished being circumcised,
  they remained in their places in the camp until they revived. And
  Jehovah said to Joshua, Today I have rolled the reproach of Egypt
  off of you. And he called the name of that place Gilgal to this day.

This new phase of life is something truly remarkable, a miracle given our state of separation from the Lord. But the Lord is compassionate,
merciful and kind and He looks to bring us through. He never leaves us nor forsakes us no matter how painful and difficult things appear. The Lord is always fully present, He never goes anywhere and by means of reconnecting with His Word we will see that. So they wait at Gilgal until they are healed and made whole. And this is described as the reproach of Egypt being removed for as we saw earlier, Gilgal means a rolling off and so it is that the Lord says that He rolls off the reproach of Egypt.

But what is it this reproach of Egypt? It is our vulnerability due to a lack of truths in our life. It is that early phase of life that has lasted right up until this point. Fourty years through the wilderness and now the reproach of Egypt is being rolled off. Why? Because up until this point we lacked an understanding of the Lord. Of His nature,
of His Word, of its internal sense. And so while we desired the good and true things that the Lord promises we were often caught out and found ourselves powerless to see those things affected in our life. And so the reproach of Egypt is where what is lower keeps dominating,
cracking through and deflating us and bringing us to points of frustration and despondency. Activating an internal thought of life that says 'You'll never make it! Why bother? Why keep going? This is the reproach of Egypt. And here through the revelation of the internal sense of the Word what we have is instruction and vision as to what the Lord will bring about if we persevere. Because as we move through the literal sense of the Word and become established in its internal sense,
cracking through and deflating us and bringing us to points of frustration and despondency. Activating an internal thought of life that says ‘You'll never make it! Why bother? Why keep going? This is the reproach of Egypt. And here through the revelation of the internal sense of the Word what we have is instruction and vision as to what the Lord will bring about if we persevere. Because as we move through the literal sense of the Word and become established in its internal sense,
then and only then can that reproach be rolled off. Because we have established principles within us that are woven into the very fabric of our thought and affection. This allows us to enter into a conscious awareness of the Lord's presence with us where we are much more secure,
peaceful and trusting that we are in a process in which the Lord is leading and guiding it every step of the way.

And so once this work of purification is affected we find an evening state described for happens afterwards is that a Passover is prepared.

  And the sons of Israel camped in Gilgal, and prepared the Passover
  on the fourteenth day of the month, at evening, in the plains of
  Jericho. And they ate the old grain of the land on the morrow of the
  Passover, unleavened bread and roasted grain, in this same day. And
  the manna ceased on the next day after they ate of the old grain of
  the land. And there was no more manna to the sons of Israel, but
  they ate the produce of the land of Canaan in that year.

So there is a shift in state. We no longer eat the food of reluctant obedience, we now have a will that is fashioned by the Lord within a new understanding which comes forth as a desire and a delight in what is good and true. A new way of being sustained. And that is the old grain of the land that the sons of Israel are now able to partake of.
The word old actually means transition, a shift reflecting this change of state. As this process comes near to its completion something begins to happen in terms of our perception of the word -- the Commander of the army appears to Joshua.

  And it happened, when Joshua was beside Jericho, that he lifted up
  his eyes and looked. And, behold! A Man stood in front of him, and
  His drawn sword was in His hand. And Joshua went to Him and said to
  Him, Are You for us, or for our foes? And He said, No, for I now
  come as the Commander of the army of Jehovah. And Joshua fell on his
  face to the earth and worshiped. And he said to Him, What does my
  Lord speak to His slave? And the Commander of the army of Jehovah
  said to Joshua, Take your shoe off your foot, for the place on which
  you are standing is holy. And Joshua did so.

Now Joshua is our understanding of the Word as it is applicable to life. But something new is beginning to happen. The Lord is beginning to be seen as the Word, as the Divine Human itself. For here is this Commander of the army to whom Joshua bows down and he reveals that he doesn't have an agenda in terms of taking sides for what the Lord is interested in is the salvation of all people, of bringing them all to heaven. And that is all the Lord is interested in. And so this represents a perception that arises from the Word, reinforcing and strengthening the Lord as the Commander. The Lord's care and providence is over all things and as this begins to be reflected in our life and in our understanding, so everything begins to change. And we are prepared for that battle where the children of Israel have to go up and confront what is represented by Jericho. And we will explore that next time.

