ifndef::fullbook[]
= Sermons on Joshua
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 12. The Destruction Of Jericho (6)

As we continue with our walk through the book of Joshua we come now to
that well-known story of the fall of the city of Jericho, and really
everything has been building to this point. Jericho in this particular
instance represents the idea that we can save ourselves. In a positive
sense, it represents the idea that the Lord alone can save us but when
it’s populated by the idolatrous nations of the Canaanites then it
becomes the opposite. And so it carries with it this idea of ‘I can do
it’ and within that, is the attribution of what is good and and what is
true to myself, as things that belongs to me. In fact we see ourselves
really as autonomous and independent from the Lord and so everything
that we have we possess as if it is our own. But we know that
everything is from the Lord and this journey that the children of
Israel have taken is really bringing them to this place where they can
see that it is the Lord, and the Lord alone, who can save them. The
Lord is what is good and true and the Lord dwells in what is true
within us and so it’s by means of these truths that what is represented
by Jericho can be destroyed. For when see that the Lord is indeed the
Word, that He is these truths, then we will no longer attribute what is
good and true to ourselves.

This journey, if you recall, began with the spies being sent out from
Shittim. We saw that these spies are part of that initial phase of life
that involves looking into the inner world of our thoughts and
affections and so they represent the first stages of self-examination.
They went in to Jericho to gather information about the general lay of
the land and while they were there they were taken in by Rahab the
harlot who represents an affection for what is true. She is that state
with us that is able to take in and protect what is of the Lord even in
the midst of our own selfish approach to life and so the Lord uses this
affection which Rahab represents, to protect what is of Himself whilst
the city of Jericho is brought down into the dust.

And we saw also that the children of Israel were led by the ark of the
Covenant as they crossed the Jordan River. That is, they were led by
the truth that is the Lord’s Word. And so it is that we too need to be
led by truths, we have to bring ourselves into obedience to the Lord’s
Word understood in the light of the teachings of Spiritual
Christianity. Outside of Jordan, through the wilderness, they walked by
obedience through external compulsion, through a fear of God but now as
they cross over into the land of Canaan there is a shift in state. For
now there is a desire to follow the Lord. This represents our own
progression. We have to come to a place where we willingly want to
follow the Lord, to operate from self compulsion and not from external
fears.

So we read in the Arcana Coelestia 8505 that prior to regeneration a
person acts from obedience but after regeneration from an affection and
desire for what is good and true. And so we’ve seen the children of
Israel arrive at a place called Gilgal where the reproach Egypt, this
acting from obedience, is rolled away. For when we live just by mere
external obedience what we find is is that we struggle to overcome the
things within because we are not acknowledging that the Lord is truly
the one who can save us. But at Gilgal there is a circumcision where
the things of self and the world are cut off so that the deeper
heavenly loves are able to become much more established in life. And
this is where the power of religion is then to be found, through this
cutting off of the belief in self sufficiency, doing away with pride in
one’s own intelligence and in any sense of confidence in the good that
we think we possess. And with this comes the cessation of manna as the
form of food for we are then able to eat from the grains the land, we
are able to take in sustenance from being able to extract spiritual
ideas and principles from the Word. All this builds to this point now
which is this place called Jericho, the ultimate destruction of our
reliance on self. So the reading today is from Joshua chapter 6 verses
1 to 27.

  And Jericho was closed, and was shut in from the face of the sons of
  Israel; no one going out, and no one coming in. And Jehovah said to
  Joshua, See I have given Jericho and its king, mighty warriors, into
  your hand. And you shall go around the city, all the men of battle,
  going around the city once; so you shall do six days. And seven
  priests shall bear seven trumpets of rams’ horns before the ark. And
  on the seventh day you shall go around the city seven times, and the
  priests shall blow with the rams’ horns. And it shall be, when they
  make a long blast with the ram’s horn, and when you hear the sound
  of the ram’s horn, all the people shall shout with a great shout.
  And the wall of the city shall fall down flat; and the people shall
  go up, each man in front of him. And Joshua the son of Nun called
  the priests and said to them, Take up the ark of the covenant, and
  let seven priests bear seven trumpets of rams’ horns before the ark
  of Jehovah. And he said to the people, Pass on, go around the city,
  and he who is armed shall go on before the ark of Jehovah. And it
  happened, when Joshua spoke to the people, the seven priests bearing
  seven trumpets of rams’ horns before Jehovah passed on and blew with
  the rams’ horns. And the ark of the covenant of Jehovah went after
  them. And he who was armed went before the priests blowing the rams’
  horns. And the rear guard after the ark, going on and blowing with
  the rams’ horns. And Joshua had commanded the people, saying, You
  shall not shout, nor cause your voice to be heard, nor shall there
  go from your mouth a word until the day I say to you, Shout! Then
  you shall shout. And the ark of Jehovah went around the city, going
  around one time. And they came into the camp, and remained in the
  camp. And Joshua rose early in the morning, and the priests bore the
  ark of Jehovah. And seven priests bearing seven trumpets of rams’
  horns were walking before the ark of Jehovah, going on, and were
  blowing with the rams’ horns. And he who was armed went before them.
  And the rear guard went behind the ark of Jehovah, going on and
  blowing with the rams’ horns. And they circled the city on the
  second day one time, and returned to the camp. So they did six days.
  And it happened on the seventh day, they rose early, at the dawning
  of the day, and went around the city seven times in the same way.
  Only on that day they circled the city seven times. And it happened
  at the seventh time the priests blew with the rams’ horns. And
  Joshua said to the people, Shout! For Jehovah has given you the
  city. And the city shall be devoted to Jehovah, it and all that are
  in it. Only Rahab the harlot shall live, she and all who are with
  her in the house, because she hid the messengers that we sent. And
  you shall certainly keep clear of the devoted things, that you not
  become accursed by taking from the devoted things, and shall make
  the camp of Israel become accursed, and trouble it. And all the
  silver and gold, and vessels of bronze and iron, they are holy to
  Jehovah; they shall come into the treasury of Jehovah. And the
  people shouted, and blew with the ram’s horns, and it happened, when
  the people heard the sound of the ram’s horn, the people shouted a
  great shout. And the wall fell under it; and the people went up into
  the city, each man in front of him; and they captured the city. And
  they destroyed all that was in the city, from man even to woman,
  from young even to aged, and to ox, and sheep, and ass, by the mouth
  of the sword. And Joshua said to the two men who had spied out the
  land, Go into the house of the woman, the harlot, and bring the
  woman out from there, and all whom she has, as you have sworn to
  her. And the young men, the spies, went in and brought out Rahab,
  and her father, and her mother, and her brothers, and all whom she
  had; yea, they brought all her family, and set them outside the camp
  of Israel. And they burned the city with fire, and all that was in
  it. Only they gave the silver and the gold, and the vessels of
  bronze, and of iron, to the treasury of the house of Jehovah. And
  Joshua kept alive Rahab the harlot, and the house of her father, and
  all whom she had. And she lives in the midst of Israel to this day.
  For she hid the messengers whom Joshua sent to spy out Jericho. And
  at that time Joshua adjured, saying, Cursed be the man who rises up
  before the face of Jehovah and builds this city of Jericho. He shall
  lay its foundation in his first-born, and he shall set up its doors
  in his youngest son. And Jehovah was with Joshua, and his fame was
  in all the land. (Joshua Chapter 6:1-27)

  The sounding of the trumpets by the priests signified the
  proclamation of Divine truth from Divine good; the shouting and
  acclamation of the people signified consent and confirmation;
  compassing the city signified a survey of falsity and evil and their
  dispersion by the influx of Divine truth from the Lord; this influx
  was signified by carrying the ark about it. The priests were seven
  in number, and the city was compassed seven days, and seven times on
  the seventh day, to signify what is holy, and the holy proclamation
  of Divine truth, “seven” signifying holiness, and in the contrary
  sense profaneness, and as there was holiness on the one part and
  profaneness on the other, there were seven priests with seven
  trumpets, and the city was compassed seven times.

  The gold, the silver, and the vessels of brass and iron, were put
  into the treasury of the house of Jehovah, because these signified
  the knowledges of spiritual and natural truth and good, “gold and
  silver” the knowledges of spiritual truth and good, and “the vessels
  of brass and iron” knowledges of natural truth and good, which with
  those who profane are changed into direful falsities and evils; but
  as they continue to be knowledges, although applied to evils, they
  are serviceable to use with the good by application to what is good,
  and therefore these things were put into the treasury of the house
  of Jehovah. This also is what is meant by the “pounds” [minae] that
  were taken away from the evil and given to the good; likewise by the
  “unrighteous mammon;” also by “the gold, silver, and raiment,” that
  the sons of Israel took away from the Egyptians and afterwards
  devoted to the tabernacle; and also by “the gold and silver” that
  David gathered from the spoils of enemies, and left to Solomon for
  building the temple.

  (Apocalypse Explained 700d {16 &17})

The Lord wants us to be truly happy. He wants happiness for every
single member of the human race but we’re born with a whole raft of
tendencies towards what is evil and false and these are tied up in our
heredity. And so the happiness that the Lord wants to bring us into is
this land of Canaan, a land flowing with milk and honey. It is the
heavenly life, states of true joy and happiness. But that land is
occupied by these idolatrous nations. We’ve looked at some of these
already, but in general they can be called the Canaanites. They
represent our inherited tendencies towards what is evil and false,
towards selfishness, towards living for oneself. And with that comes
the greatest falsity – that we have life in and of ourselves. This is
one of the biggest things that needs to be overcome in the spiritual
life. And so what we find is that throughout this journey that the
Israelites undertook, they’re constantly being confronted with enemies.
These enemies for us, are those things that are tied into false beliefs
and particularly negative traits and emotions, they look to pull us
down and to pull others down as well. These false patterns of thinking
and feeling are structures, like strongholds within our mind and in the
Word this is what cities represent. So we can look at the city of
Jericho as a stronghold within the mind that is based upon the belief
that we can save ourselves when it is occupied by the Canaanites. Now
there are two things that need attending to in order to pull down and
dismantle this city. There is the wall of defensiveness which are those
reasonings that we put up to defend what’s within that city and then
there are the things which dwell within that city are protected by the
wall of argument, the wall of justification for how we feel, how we
think and how we behave when we act from these false beliefs and
negative states.

So what this story about Jericho is teaching us is how the Lord goes
about pulling down what is of the hells within the natural mind. We see
in the story that in terms of coming up against this city and the
destruction of its walls, that the Israelites just marched around it
according to the Lord’s command until He gave the signal that He was
going to demolish it. And so as we grow in the spiritual life and we
develop an affection for what is good and for what is true, and we
begin to really live from that, what we find is that what once roamed
the land becomes more contained. That the evils and falsities, the
desires that are of the world and of self, begin to be shut up and
closed in. Because as we gain knowledge of truths, we begin to see what
constitutes the heavenly life and so in contrast what is not of the
heavenly life or what doesn’t promote it. So those things in a sense
become bounded and until nothing can move into it or out of it and the
state of Jericho becomes a city that is shut up. And so this life that
the sons of Israel have led and the things they’ve gone through up to
this point, represents our own progression. We recognise that this
enemy that is occupying the internal landscape of our thought and
feeling life, has to fall.

This cessation of traffic has to do with a spiritual discipline. It’s
tied to self-examination and self-observation, of learning to notice
when our thoughts and feelings are not aligned with what the Lord’s
Word teaches. These things have to be brought into captivity by means
of the Lord’s Word. In fact, in 2 Corinthians we have a wonderful
statement there from Paul which says,

  For walking about in the flesh we do not war according to the flesh.

That is, we do not war or battle according to what is natural. For the
weapons of our warfare are not fleshly or natural but powerful to God
for the demolition of strongholds. For the demolishing of arguments and
of everything which lifts itself up against the knowledge of God and
for the bringing into captivity every thought to the obedience of
Christ or to the Lord’s Divine truth. So we see that it is the Word
that is the means by which this conquering takes place.

  And Jericho was closed, and was shut in from the face of the sons of
  Israel

The face represents what is internal, it gives expression to what is
within the mind. And so in the Scriptures we have this statement a lot
– before the faces. And this tells us that it’s when the interior
things of the Word begin to make themselves known, that there is power
for things to be closed down. That things that once harassed us and
harangued us can now begin to be shut down so that the Lord can deal
with them. So what does the Lord command of the children of Israel?
Well, the first thing is that they have to march around this city. And
so the first thing we see here is that there has to be the application
of truths to the examination of the things within our life. From the
application of the Word to work on ourself, that is through
self-examination, we then are given a perception or an insight into
what those false ideas we hold on to are, what these strongholds in our
life support.

As we looked at earlier, the greatest falsity that we subscribe to is
the idea that we can save ourselves, that we can claim goodness to
ourselves and that through this, that we can merit heaven. This is the
root of every evil in the human condition. For when we are troubled
internally and when we enter states of negative emotion, this can be
tracked back to just one thing – that we are claiming what is of the
Lord’s for ourselves. This is of course, far from what the Lord’s Word
teaches for it clearly states that it is the Lord alone who has merit
because He alone is holy and righteous and so we have to move away from
this self-sufficiency that dominates our life. These things have to be
put down. The thinking that exalts itself against God has to be brought
into obedience and into the captivity that the Lord provides for us
through His Word. So we see that the sons of Israel don’t attack the
walls of the city, all they do is they walk around its fortifications.
And what this process is within us is the examination of our own walled
cities in the light of what truths teach. Because when we truly see
that it is the Lord alone who is our Saviour then those walls, those
defences that we set up and justify selfishness with, can no longer
stand. Falsity or evil cannot stand before the Lord’s Word, it just
can’t do it.

However, although it is the Lord alone who brings down the defences of
the proprium, He doesn’t work apart from our understanding of truths.
And this is why it is so important that we study the Lord’s Word and
that we engage with the principles of Spiritual Christianity by
applying them to our life. This is a lifelong commitment. Our
development and growth and the things of the Lord goes to eternity, it
never ends. And so as we are engaged in that process, the Lord can work
with us but if we aren’t building our understanding of truths, and if
we aren’t taking those and living from them so that they can lead us
into good, then the Lord cannot do what He wants to for us. He cannot
bring us into the happiness and joy of the loves of heaven. The Lord
works by means of His Word within us. He doesn’t just come down and
sort it all out for us in a moment but instead He requires us to be a
part of this eternal work and so to do what He asks of us. If we would
do that, then He is empowered within our life to bring about the
heavenly ends that He desires for us. And so we see this process
communicated to us in this story which we are looking at here. The
instructions are given by the Jehovah to Joshua and then Joshua
commands the people. And the instructions are important because they
teach us how the Lord goes about doing the work of pulling down our
false strongholds.

  And Jehovah said to Joshua, See I have given Jericho and its king,
  mighty warriors, into your hand. And you shall go around the city,
  all the men of battle, going around the city once; so you shall do
  six days. And seven priests shall bear seven trumpets of rams’ horns
  before the ark. And on the seventh day you shall go around the city
  seven times, and the priests shall blow with the rams’ horns.

We see the number seven recurs time and time again. Seven priests,
seven trumpets of rams horns, around the city on the seventh day, seven
times. This number seven represents what is holy, complete and full.
And it is a number that is really a description of the Lord as He is in
His Divine Human, in His fullness of power as the Word. And the fact
that events had to take place after a six day period is also
significant for the number six represents temptation and struggle. The
temptation and struggle in letting go of our ownership over our life,
in giving it up and acknowledging the Lord as the true owner.

Now the trumpets are rams’ horns and of course lambs represent
innocence. And so here we have the full maturing of innocence formed in
the rams’ horns with the horn itself being a symbol of the power of
truth. For the blowing of the rams’ horns offers a proclamation of the
Lord’s Word in our life and it is this which brings about the
consequent destruction. The rams’ horns signify a structure of Lord’s
Word in us that has taking form through the maturing of innocence and
then given support so that these truths might be spoken into life as
signified by the breath. This is that innocence and willingness to be
led by the Word and so the rams’ horns form and provide a channel for
the Lord’s Word to be trumpeted out and heard within our life.

  And it shall be, when they make a long blast with the ram’s horn,
  and when you hear the sound of the ram’s horn, all the people shall
  shout with a great shout. And the wall of the city shall fall down
  flat; and the people shall go up, each man in front of him. And
  Joshua the son of Nun called the priests and said to them, Take up
  the ark of the covenant, and let seven priests bear seven trumpets
  of rams’ horns before the ark of Jehovah.And he said to the people,
  Pass on, go around the city, and he who is armed shall go on before
  the ark of Jehovah. And it happened, when Joshua spoke to the
  people, the seven priests bearing seven trumpets of rams’ horns
  before Jehovah passed on and blew with the rams’ horns. And the ark
  of the covenant of Jehovah went after them. And he who was armed
  went before the priests blowing the rams’ horns. And the rear guard
  after the ark, going on and blowing with the rams’ horns.

There are seven priests carrying these rams horns and spiritually
speaking priests are those states within us that are obedient and
dedicated to serving the Lord’s Word. But in front of these priests
there are the armed men ready to fight, which are like the truths that
have been fitted out for the task of self-examination and from that,
repentance. And so these all proceed forward from the Ark in this
particular order. For the Ark sits at the centre because the Ark is the
Word, the Divine Truth itself. The priests before the Ark, are our
willingness to be led by the Word so that the trumpet, as that which
proclaims the Divine truth, can be heard loud and clear in our life.
And then before the priests are the armed men so that the blast of the
trumpet that is proclaiming the truth is going on behind them as they
march forward, for it is these truths that are involved in the
examination of our thoughts and our affections so that we can see their
true quality. And what comes behind the Ark then is what is termed the
rear guard. In the Hebrew, this translates into those who gather up
which carries with it the idea of those who harvest. So it is the
application of truths that are at the forefront and those who gather up
are at the rear, like those faculties within us that can gather into
our understanding the things that may be gained from putting truths
into practice. And it is these two things, our growing understanding of
the practice of truth and our growing ability to put things into
practice, that the Lord is going to use to pull down the wall of self
love and defensiveness.

The next thing that the people were told was that they were not to make
a sound until Joshua commanded them to shout.

  And Joshua had commanded the people, saying, You shall not shout,
  nor cause your voice to be heard, nor shall there go from your mouth
  a word until the day I say to you, Shout! Then you shall shout

They were not to voice anything but were to remain silent until Joshua
gave the command. Joshua is the Word that fights for us and who shows
the level of obedience that is required. Not to make a sound here
speaks of not speaking from self, not rationalising things but only to
speak from the Lord’s Word and to think in accordance with the Word.
This is what brings down Jericho. If we try and rationalise things and
figure it all out and think that we can do it ourselves, we fall back
into self sufficiency where nothing can happen. But if we truly are
reliant on the Lord’s Word, if we are living from it, if we are in that
effort, if we are engaged in the disciplines of self-examination and
repentance – then we will hear the Lord’s Word speaking to us. The
shout will be commanded and the walls of Jericho will come down.

  And the people shouted, and blew with the ram’s horns, and it
  happened, when the people heard the sound of the ram’s horn, the
  people shouted a great shout. And the wall fell under it; and the
  people went up into the city, each man in front of him; and they
  captured the city. And they destroyed all that was in the city, from
  man even to woman, from young even to aged, and to ox, and sheep,
  and ass, by the mouth of the sword.

The children of Israel go up into the city once the walls come down.
For when the false rationalisations that we use to justify selfish
attitudes are seen for what they are, they lose their stronghold with
us and fall down. The truths then that are represented by the sons of
Israel are able to be employed and to move in to the city that has been
built up within these walls of falsity, so that they might destroy
everything within it. Man, woman, young and aged, ox, sheep, ass
everything, everything that is living in it is put to the sword. Of
course the sword is the Lord’s truth. And so every evil and false
affection that is represented by all those living, both animal and
human in that city must be put to the sword. Truths must be brought
against those affections that are not of the Lord so that they can be
examined and tested and set aside. This is the laying down of our own
life and doing away with what is selfish so that the Lord’s Word might
be promoted as what has authority in our life.

  And they burned the city with fire, and all that was in it. Only
  they gave the silver and the gold, and the vessels of bronze, and of
  iron, to the treasury of the house of Jehovah. And Joshua kept alive
  Rahab the harlot, and the house of her father, and all whom she had.
  And she lives in the midst of Israel to this day.

However, there is one delivered from this city, one household and that
is the household of Rahab. And as we saw a few articles ago, Rahab is
that affection that is trapped within our selfishness which the Lord
can use to protect truths until this day of liberation might come
about. It’s a long process but it is a process that every single person
must pass through if they are to enter into the land of Canaan. So only
Rahab is said to live and Rahab was an ancestor of the Lord. And so she
is saved that all might be saved. And so her story offers us a
beautiful picture of the Lord’s provision and providence at work.

The other thing that could be taken from the city were the things that
were of precious metal, the gold, the silver and also the brass and the
iron. These things could be taken out because even when we live a
selfish life and testify or profess a religion, we are able to draw
precious things out of the Lord’s Word into our memory. While these
remain trapped within selfishness, they are powerless really to do
anything for us but as we begin this work of self-examination and
repentance, so those things of the Lord’s Word that we have taken in
can be released and freed and put into service. So the things of gold
represent the golden things in the Lord’s Word, things that teach us
how to love the Lord and the silver things represent the things that
teach us how to love our neighbour. These things can be taken out
because now the affections have been purified, they’ve been put to the
sword. And we gain strength even at a natural level of life as
represented by the brass and iron.

And so all things are beginning to be put into order. The things that
are of the Lord are being extracted out from being bound up within that
city of Jericho and are being brought back into their rightful place.
This mirrors what the Lord is wanting to do with each and every one of
our lives. He’s wanting to put it all in order. And so we see that this
city is burnt to the ground, destroyed, for evil has its own
destruction within itself and so it is laid flat and never to be
rebuilt. Once the Lord takes us and helps us to overcome those things
that dominate our life, so then, we are not to go back. We are to hold
steadfastly to His Word. We are to continue in the effort of spiritual
life and work so that He might be fully present with us and lead us on
into what lies ahead. The power of the Word to win this victory is
affirmed in the final verse where it says,

  And Jehovah was with Joshua, and his fame was in all the land.

Jehovah was with Joshua, Jehovah, the Divine good, is with the Divine
truth for this is the Word when it is applied to our life. And when
this happens then the fame of the truth of the Lord’s Word is in all
the land, that land being ourselves when we see that it is the Lord who
win these victories for us. For this seeing and acknowldging of the
Lord as the only true source of life is His name being glorified
throughout the land of our life.

