ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 13. Defeat At Ai (7)

  And the sons of Israel sinned a sin in the accursed things. And
  Achan, the son of Carmi, the son of Zabdi, the son of Zerah, of the
  tribe of Judah took of the accursed things. And the anger of Jehovah
  glowed against the sons of Israel. And Joshua sent men from Jericho
  to Ai, which is near Beth-aven, on the east of Bethel, and spoke to
  them, saying, Go up and spy out the land. And the men went up and
  spied out Ai. And they returned to Joshua, and said to him, Do not
  let all the people go up. Let about two thousand men, or about three
  thousand men, go up, and they shall strike Ai. Do not cause all the
  people to labor there, for they are few. And about three thousand
  men of the people went up there. And they fled before the men of Ai.
  And the men of Ai struck about thirty six men of them, and pursued
  them before the gate to Shebarim. And they struck them in the
  descent. And the heart of the people was melted, and became as
  water. And Joshua tore his clothing, and fell on his face to the
  earth before the ark of Jehovah until the evening, he and the elders
  of Israel. And they threw dust on their heads. And Joshua said, Oh
  Lord Jehovah, why have You at all caused this people to cross over
  the Jordan to give us into the hands of the Amorites, to destroy us?
  And, Oh that we had been willing, and that we had dwelt beyond the
  Jordan! Oh Lord, what shall I say, after Israel has turned its back
  before its enemies? And the Canaanites, and all the ones living in
  the land shall hear, and shall come around against us, and shall cut
  off our name out of the earth. And what shall You do for Your great
  name? And Jehovah said to Joshua, Get up! Why do you fall on your
  face this way? Israel has sinned, and they also have transgressed My
  covenant which I commanded them, and have also taken of the cursed
  things, and have also stolen, and also deceived, and also put it
  among their stuff. And the sons of Israel have not been able to
  stand before their enemies; they have turned the back before their
  enemies because they have become cursed. I will not be with you
  again if you do not destroy the cursed things from among you. Rise
  up, sanctify the people, and you shall say, Sanctify yourselves for
  tomorrow. For so says Jehovah, the God of Israel, A cursed thing is
  among you, Israel; you are not able to stand before your enemies
  until you take away the cursed thing from among you. And you shall
  be brought near in the morning, by your tribes. And it shall be, the
  tribe which Jehovah takes shall draw near by families. And the
  family which Jehovah takes shall draw near by households. And the
  household which Jehovah takes shall draw near by men. And it shall
  be, he who is taken with the accursed thing shall be burned with
  fire, he and all that he has, because he has transgressed the
  covenant of Jehovah and because he has committed folly in Israel.
  And Joshua rose early in the morning, and brought Israel near by its
  tribes. And the tribe of Judah was taken. And he brought the family
  of Judah near; and he took the family of the Zerahites. And he
  brought near the family of the Zerahites by men, and Zabdi was
  taken. And he brought near his household by men, and Achan, the son
  of Carmi, the son of Zabdi, the son of Zerah, of the tribe of Judah,
  was taken. And Joshua said to Achan, My son, now give glory to
  Jehovah, the God of Israel, and give thanks to Him, and please tell
  me what you have done. Do not hide it from me. And Achan answered
  Joshua, and said, Truly I have sinned against Jehovah, the God of
  Israel, and this I have done: When I saw among the spoil a goodly
  robe of Shinar(Babylon), and two hundred shekels of silver, and a
  wedge of gold, one of fifty shekels in weight, then I lusted after
  them, and took them. And behold, they are hidden in the earth, in
  the middle of my tent, and the silver under it. And Joshua sent
  messengers, and they ran to the tent; and behold, it was hidden in
  his tent, and the silver under it. And they took them out of the
  middle of the tent, and brought them to Joshua, and to all the sons
  of Israel, and laid them out before Jehovah. And Joshua, and all
  Israel with him, took Achan the son of Zerah, and the silver, and
  the robe, and the wedge of gold, and his sons, and his daughters,
  and his oxen, and his ass, and his flock, and his tent, and all that
  he had. And they made them go up to the valley of Achor. And Joshua
  said, How you have troubled us! Jehovah shall trouble you today! And
  all Israel threw stones at him, and they burned them with fire, and
  they stoned them with stones. And they raised over him a great heap
  of stones to this day. And Jehovah turned back from the heat of His
  anger. On this account the name of that place is The Valley of Grief
  until this day. (Joshua 7:1-26)

  Profanation and hence the taking away of good and truth are
  signified in the spiritual sense by the deed of Achan, who took of
  the accursed things a mantle of Shinar(Babylon), two hundred shekels
  of silver, and a wedge of gold, and hid them in the earth in the
  midst of his tent, and who therefore was stoned, and all the things
  were burned; as is related in Joshua:

  Jehovah said unto Joshua, Israel hath sinned, they have transgressed
  My covenant which I commanded them; and they have taken of the
  accursed thing, and have stolen, lied, and have put it among their
  vessels (Josh. 7:10-11, 21, 25);

  by “accursed things” were meant falsities and evils, which were in
  no wise to be mixed up with holy things; the “mantle of
  Shinar(Babylon), shekels of silver, and wedge of gold” are in the
  spiritual sense species of falsity; “hiding them under the earth in
  the midst of the tent” signified a commixture with holy things.
  (That a “tent” denotes what is holy may be seen above, n.
  414, 1102, 1566, 2145, 2152, 3312, 4128, 4391, 4599.) These things
  were signified by Israel's “stealing, lying, and putting it among
  their vessels;” for “vessels” are holy truths (see n.
  3068, 3079, 3316, 3318)

  … a “thief” denotes the evil of merit; for he who takes away from
  the Lord what is His, and claims it for himself, is called a
  “thief.” As this evil closes the way and prevents good and truth
  from the Lord from flowing in,

  (Arcana Coelestia 5135{6&12})

  And the sons of Israel sinned a sin in the accursed things. And
  Achan, the son of Carmi, the son of Zabdi, the son of Zerah, of the
  tribe of Judah took of the accursed things. And the anger of Jehovah
  glowed against the sons of Israel.

So verse one here sets the context for what is to follow. We are given an insight into what it is that sits behind this defeat at Ai. We learn there that there is something terribly wrong in the midst of Israel.
Achan has taken of the accursed thing and this has an effect on the whole of Israel. In violation of the Lord's direct command, he took spoil out of Jericho. And of that spoil that he took, he took that which was to be set aside for the Lord, for all the metals, if you recall, were to be set aside for the tabernacle, for the worship of the Lord. And so he took what was the Lord's to himself and he hid it within his tent under the earth. Not only did he take the silver and the gold, but he took a Babylonian (Shinarian) garment and a Babylonian mantle. And we are told that he took them because he saw them and he desired them, he lusted after them. Now this desire, and in particular acting on this desire, brought danger to the whole of the Israelite nation, to the whole camp of Israel and the consequences were dire.
They were dire for the thirty six men that lost their lives as they fled from before the men of Ai who struck them down them in their descent. And of course, for Achan and his family, the consequences were clear enough.

  And Joshua, and all Israel with him, took Achan the son of Zerah,
  and the silver, and the robe, and the wedge of gold, and his sons,
  and his daughters, and his oxen, and his ass, and his flock, and his
  tent, and all that he had. And they made them go up to the valley of
  Achor. And Joshua said, How you have troubled us! Jehovah shall
  trouble you today! And all Israel threw stones at him, and they
  burned them with fire, and they stoned them with stones.

All because Achan lusted after the spoil of Jericho. Now it's interesting that the name Achan means “troubler“, so it's appropriate,
and it comes from a root Hebrew word which means “to pervert or to make crooked.” And so what he represents is a deep-seated tendency within our proprium to claim what is of the Lord for ourselves. And when we get a hold of this, then the story begins to fit together.

Achan is an Israelite, like all the other Israelites around him. He is in the midst of the sons of Israel, he doesn't stand out for all intensive purposes. He looks no different to anyone else. He blends in well as does the tendency to claim what is of the Lord for ourselves and thus like Achan, this tendency is difficult to see as it is in the midst of what the sons of Israel represent which are the truths that teach what spiritual life is all about. And so Achan as this tendency to claim what is of the Lord for ourselves, surrounds itself with what looks legitimate, belonging to the spiritual life. It goes unnoticed because it sits within our efforts to do good and to think what is true as we look to love the Lord and love our neighbour.

Now we recall that Jericho when it is filled with Canaanites,
illustrates the idea that we can save ourselves, that we are good enough and that we can merit what is of heaven. And so this city and all the beliefs that were tied to it, had to be destroyed. But still there is this desire that sits at a much deeper level that claims what is of the Lord for itself and it is much more difficult for us to detect. It's a desire that is intoxicating and it brings delight and pleasure at a certain level. The doctrines for Spiritual Christianity teach that whatever brings us delight and pleasure we call good, even when it is evil. And so we need the Lord's Word to point out and illustrate these tendencies for us for we are mostly blind to them. We need to be able to see that what feels good isn't necessarily good and that it is only through self examination by the light of truth that can illuminate where these false delights exist for us.

So Achan violated the command of the Lord and he took the gold and the silver, which was to be given over for the Lord and he also coveted a Babylonian garment. Now the garments of Babylon represent the false reasonings and justifications which we make that delude us into thinking that we're okay as we are, that we don't need to change. The garments of Babylon have to do with the love of self and the promotion of self interest. There are countless ways that we can promote our own interests and make them look, at least to those around us and perhaps to ourselves, as something legitimate. The doctrines for Spiritual Christianity state that we are engaged in this type of self deception often so if Achan is to be brought out into the open and identified,
then we need to accept that this in fact true. That what it teaches concerning the proprium is true regardless of how we might feel. Forms that this garment of Babylon might take are delight in gossip while clothing it with a false projection that we are concerned for the person's welfare, or saying something hurtful, uncharitable and justifying it by saying that we're only pointing out to the person the truth they need to hear, or lying to protect our self image and reputation in the eyes of others. These activities and behaviours are the Babylonian garment. It is a garment because it conceals the truth of what is hidden within. So all desires, thoughts and behaviours that work at justifying forms of selfishness which promote ourselves over others and promote our views over the views of others, is what is meant by the Babylonian garment.

Achan's taking of the gold and silver also represents claiming merit –
in fact claiming merit is really how this whole campaign started. Right from Shittim where the spies were sent out through to Jericho and now up to Ai, it has all been about this tendency to claim merit, to get a sense that we can save ourselves and that we don't need to do the work of self examination and repentance. The doctrines for Spiritual Christianity call this faith alone. And believing that the good which we do is from ourselves and that the truths that we think make us better, richer and more prominent or more spiritual than others -- is what is meant by spiritual theft. And what faith alone and spiritual theft lead to, at both an individual level and an organisational level,
is a tendency towards self righteousness, pride and vanity. These things needs rooting out because they dwell within our tent, they dwell within the proprium and until they are seen and dealt with, we will suffer because of them.

So how is what Achan represents rooted out? Well there has to be a willingness to work with spiritual truths in our life. So it is an ongoing process in working with what truths show us to examine the quality of our thought and feeling life. But Achan at this stage of the campaign is hidden. However, the city of Ai stands there before us and we can see that we have to go up and confront this aspect within ourselves for Ai represents worldly knowledge and false ideas, its meaning is one of an overturned heap carrying with it the idea of things which are inverted. We find this idea of inversion throughout the doctrines for Spiritual Christianity in that before we have truths and begin to work from truths, we are immersed in darkness and self love and so in this sense we are an inversion of the heavenly image and likeness. We put more emphasis and value on the things of the world than we do on what is spiritual. But Ai now stands before us as an invitation to explore these tendencies which the Word tells us that we have and and so we can follow the Lord's Word and begin to examine them.

So we need to take truths and begin to use them to assess how we think and to look at the beliefs that we are actually living from. Not what we profess with our mouths, but how we actually conduct ourselves. What beliefs do our behaviours actually find their source in? We can only make this examination from the Lord's Word, from the truths that He has given us. And so the process, if we are willing to engage with it, if we're willing to look at the Ai in our own lives, when we begin to consider that perhaps we look to worldly wisdom at times over heavenly wisdom, when we begin to do that, then this process commences. And the manifestation of Achan is pending.

Now on the surface, Ai seems of little consequence. Victory should have been a breeze in the estimation of the sons of Israel. Compared to Jericho, it's a minor obstacle. But what it teaches us is that what may appear small on the surface could well go back to something much more malignant, lying deeper underneath. So in terms of the spiritual life and our work of self examination and repentance, we shouldn't take what appears to be small evils and small false ideas lightly because they often are linked to something much bigger. We need to bring everything into the light of the Lord's Word, into the light of His truths, this is what the work of self examination is all about. And it's what moves us from a natural Christianity into a spiritual Christianity, its what moves us from faith alone into a living faith where faith is united with the good of practice.

Spiritual life involves times of being up and times of being down. And if anything, Jericho is an uptime but Ai is a downtime. We alternate between being in the things of the Lord and the things of self. And this cyclic kind of alternation is very much a feature of the spiritual life. Cycles of night and day, cycles of seasons, of segments of the day, of being in victory and being in defeat. This is the cycle of life. But the idea as far as our regeneration goes is to come into a place of peace through our work with the Word and through dealing with what these cycles bring up for us. So that we can come into a place where we are in a much more steady state, a state of inner peace,
despite what is happening around us on the outside of our life. This is what the Lord wants to bring us to, a state of constancy despite the alternations. So the fact that there are these emotional highs and lows teaches us that in all extremes of emotion, however we clothe it, there is something of self, and this is why the extremes of emotion are experienced. It's very difficult for us to give attention to what aspect of self might be present when we're on a high but it is much easier to give reflection when we're on a downer. And so we have to go through these alternating states in order for the Lord to lift us out of those things that hold us bound in those selfish desires and false beliefs. This is the aspect of self that is represented by Achan.

Now Joshua's response to the defeat is interesting in contrast with the Lord's words to him. Joshua's response was that he was down on himself and you can see here that there is a sense of self pity and real struggle, a sense of being paralyzed, a sense of not being able to do anything.

  And Joshua said, Oh Lord Jehovah, why have You at all caused this
  people to cross over the Jordan to give us into the hands of the
  Amorites, to destroy us? And, Oh that we had been willing, and that
  we had dwelt beyond the Jordan! Oh Lord, what shall I say, after
  Israel has turned its back before its enemies? And the Canaanites,
  and all the ones living in the land shall hear, and shall come
  around against us, and shall cut off our name out of the earth. And
  what shall You do for Your great name?

Joshua is wallowing in the dust. He is crying out, remonstrating before the Lord about what's going to become of them now. The Canaanites are going to hear of this and they are going to become easy prey, they will cut off our name out of the earth. Joshua's deep sorrow about what has happened mirrors our own states of defeat when we're feeling down and the sense of self pity that rises up. There is a sense of 'woe is me'
that comes about, a sense that we haven't met the expectations that the Lord has for us. We fall into states of negative self talk -- 'I'm no good. I'll never make it. Why has the Lord chosen me to lead this life?' etc. It's different for us all, but the flavour of it is the same, it's to keep us down. And all of this negative thinking and feeling is straight out of the hells. It's not from the Lord for the Lord is only ever wanting to lift us up. And so in verse 10 and 11, we read,

  And Jehovah said to Joshua, Get up! Why do you fall on your face
  this way? Israel has sinned, and they also have transgressed My
  covenant which I commanded them.

You see sorrow, if we wallow in it, is just as destructive to the spiritual life as anything else described in this chapter. What the Lord goes on to say is that Israel is on the verge of being cut off.
And so what is it that they have to do? Well, not wallow in feeling sorry -- but do something. The Lord tells us what must be done, we have to undergo a process of self examination. The tribes have to be brought before Joshua: the households, the families, man by man. They have to be looked into and investigated because this is the only way that Achan can be uncovered. There has to be a process of self examination and a willingness to do what the Lord commands in terms of dealing with it –
this is what is called repentance. And so all that belongs to Achan has to been exposed and taken and destroyed.

  And Joshua, and all Israel with him, took Achan the son of Zerah,
  and the silver, and the robe, and the wedge of gold, and his sons,
  and his daughters, and his oxen, and his ass, and his flock, and his
  tent, and all that he had. And they made them go up to the valley of
  Achor. And Joshua said, How you have troubled us! Jehovah shall
  trouble you today! And all Israel threw stones at him, and they
  burned them with fire, and they stoned them with stones.

Now often when we read the Word, we come across a story like this and to the natural man, the natural mind, there is a sense of injustice that arises. How is it that his sons, his daughters and his livestock were stoned along with Achan for it seems that what was innocent has been destroyed along with the guilty party? This is a good example of how the natural man thinks that it knows better than the Lord, that it is above the Word's judgement. For whatever we understand from the Word as far as truths go and their application to our life, we need to follow them. We need to put down our own tendencies to rationalise things, to justify our behaviour and patterns of thinking and feeling which we know aren't quite right. For anything that is born of the state of self merit which claims what is of the Lord as its own and which Achan represents, and anything that serves his livelihood, does not serve the Lord and needs to be done away with. All these things need to be set aside so that what is of the Word can be put in its place instead. So the states of the sons of Israel within us, those truths which serve the Lord and teach us about spiritual life, need need to take the foundational principles about spiritual life as represented by the stones and destroy Achan and all that belongs to him. And these stones remain in place as reminders to us each time Archan tried to rear its head again. The heap of stones act as reminder to us of how we need to be constantly remembering the Word by going to it, drawing truths from it for our life and putting them into practice by using them to self examine. They remind us that it is only the truths which the Word offers that have the power to liberate us from our suffering.

  And they raised over him a great heap of stones to this day. And
  Jehovah turned back from the heat of His anger. On this account the
  name of that place is The Valley of Grief until this day.

