ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]

---
ifdef::fullbook[]
<<<
endif::[]




== 14. Ai Overcome (8)

  Now the LORD said to Joshua: "Do not be afraid, nor be dismayed; take all the people of war with you, and arise, go up to Ai. See, I have given into your hand the king of Ai, his people, his city, and his land. "And you shall do to Ai and its king as you did to Jericho and its king. Only its spoil and its cattle you shall take as booty for yourselves. Lay an ambush for the city behind it." So Joshua arose, and all the people of war, to go up against Ai; and Joshua chose thirty thousand mighty men of valour and sent them away by night. And he commanded them, saying: "Behold, you shall lie in ambush against the city, behind the city. Do not go very far from the city, but all of you be ready. "Then I and all the people who are with me will approach the city; and it will come about, when they come out against us as at the first, that we shall flee before them. "For they will come out after us till we have drawn them from the city, for they will say, 'They are fleeing before us as at the first.' Therefore we will flee before them. "Then you shall rise from the ambush and seize the city, for the LORD your God will deliver it into your hand. "And it will be, when you have taken the city, that you shall set the city on fire. According to the commandment of the LORD you shall do. See, I have commanded you."
  ...
  Now Joshua built an altar to the LORD God of Israel in Mount Ebal, as Moses the servant of the LORD had commanded the children of Israel, as it is written in the Book of the Law of Moses: "an altar of whole stones over which no man has wielded an iron tool." And they offered on it burnt offerings to the LORD, and sacrificed peace offerings. And there, in the presence of the sons of Israel, he wrote on the stones a copy of the law of Moses, which he had written. Then all Israel, with their elders and officers and judges, stood on either side of the ark before the priests, the Levites, who bore the ark of the covenant of the LORD, the stranger as well as he who was born among them. Half of them were in front of Mount Gerizim and half of them in front of Mount Ebal, as Moses the servant of the LORD had commanded before, that they should bless the people of Israel. And afterward he read all the words of the law, the blessings and the cursings, according to all that is written in the Book of the Law. There was not a word of all that Moses had commanded which Joshua did not read before all the assembly of Israel, with the women, the little ones, and the strangers who were living among them.
 (Joshua 8:1-8 & 30-35)


  Evils cannot be removed unless they appear. This does not mean that man must do evils in order that they may appear, but that he must examine himself,-not his deeds alone but also his thoughts, and what he would do if he did not fear the laws and disrepute, especially what evils he regards in his spirit as allowable and does not account as sins; for these he still does. It is to enable man to examine himself that an understanding has been given him, and this is separated from the will to the end that he may know, understand, and acknowledge what is good and what is evil, also that he may see what his will is, that is, what he loves and what he longs for. In order that man may see this there has been given to his understanding higher and lower thought, or interior and exterior thought, to enable him to see from the higher or interior thought what the will is doing in the lower and exterior thought; this he sees as a man sees his face in a mirror; and when he sees it and knows what sin is, he is able, if he implores the Lord's help, to cease willing it, to shun it, and afterwards to act against it, if not freely, still to coerce it by combat, and finally to turn away from it and hate it; and then, and not before, he perceives and also feels that evil is evil and that good is good. This, then, is examining one's self, seeing one's evils, acknowledging them, and afterwards refraining from them. But as there are few who know that this is the Christian religion itself (because such only have charity and faith, and they alone are led by the Lord and do good from Him), so something shall be said of those who do not do this and nevertheless think that they have religion. They are these:
 (1) Those who confess themselves guilty of all sins, and do not search out any one sin in themselves.
 (2) Those who neglect the search from religious reasons.
 (3) Those who for worldly reasons think nothing about sins, and are therefore ignorant of them.
 (4) Those who favor them and in consequence are ignorant of them.
 (5) To all such sins are not apparent, and therefore cannot be removed.
 (6) Lastly, the reason, hitherto hidden, will be made evident, why evils cannot be removed unless they are sought out, discovered, acknowledged, confessed, and resisted. 
 (Divine Providence 278{2})

We move on into chapter eight today and here we find this second attack on Ai only this time the sons of Israel are victorious because that self-interest represented by Achan has been rooted out. For when self-interest is taken out of the way the Lord is able to empower us to conquer over those things in our life that are represented by Ai.

The character of Achan actually means troubler, a troubler of the sons of Israel and we all have elements of Achan within us. We all have the instinct that flows out of our lower nature to put the self first and to attribute what is good and true to ourselves. This is the nature of the ego or the proprium and it is something that needs to be uprooted and taken out. And the only way that this can actually happen is if we are willing to do the work of self examination as outlined in the quote above from Divine Providence. Because when we live from a belief that there is something intrinsically good about ourselves, we are denying the truth that the Lord alone is good. And if we live in a denial of a truth, then the Lord can't be in that. So the Lord is with us to the degree that we take truths and we live from them because the Lord makes His presence in the truths that we live from. And this is a really important point. He can only be in us to the degree that we are living in the truth that He alone is good.

So in chapter seven we saw that the sons of Israel were able to overcome the power of Jericho and as you might recall Jericho is the idea that we can save ourselves or that we deserve heaven because somehow we are better than others. Jericho was conquered through a life of obedience to the Word of the Lord and then the city of Ai was next and by comparison, it was a small city. It should have been a straightforward military venture and yet we find that the sons of Israel were defeated and suffered losses. Joshua was perplexed by this defeat, he just could not see why what had happened had happened. And we saw that the defeat was directly attributed to Achan's disobedience for by taking the things he was commanded not to take from Jericho he undermined the strength of the sons of Israel. Now the Israelites as a fighting force represent the truths and principles of the Lord's Word that we fight from and so what we see in the defeat at Ai is that when self-interest is active and credits itself with the good things that belong solely to the Lord as represented by those things that Achan took from Jericho, then the Lord can't help us because he can't be present in what is false. So when we are in states of self-interest and we justify those states then we become subject to the evils and falsities represented by Ai -- and they defeat us.

Now we know from what the doctrines for Spiritual Christianity teach that we are more often than not blinded to our own evil tendencies. And this is seen in the story in that none of the sons of Israel knew what Achan had done. They were blind to the character of this man whom they held to be one of their own and who dwelt in their very midst. And this is true of us also. We are blind to the true character of our ego or proprium for we unconsciously love the things that are associated with it. We even at times consciously seek to promote the things of that lower realm unaware of its tendency to undermine our spiritual progress and life. Such tendencies are so well hidden that the Lord is left with little option but to allow us to continue on our ways even when it means we are going to suffer some sort of mental trauma or defeat.

Now people may wonder at this. How could a loving God allow such things to happen? How could He permit us to endure these perplexities in life,
to suffer in life? Well, the Lord's love for people looks to their eternal welfare not to their temporal comfort and to allow what is destructive of the heavenly life to remain within us would not be loving behavior. It wouldn't be loving because these things will eventually destroy us. And it's unfortunate but it's true that we are more often than not oblivious to the selfish attitudes that we carry and that govern much of our behavior and so until we are willing to practice self-examination as outlined the Divine Providence quote, we won't take any action to have things changed or become different.

So these crises in our life occur because it's not until we see the effect of the evils and falsities that we are holding on to, either on ourselves or on others around us, that we begin to take stock and examine ourselves just as the defeat at Ai caused Joshua to seek the Lord in order to find out what went wrong.

Now we can get hung up about the word evil but the associations that we take from natural reasoning about evil need to be put aside. Evil is simply what separates us from the loves of heaven. Anything that separates us from love to the Lord and love to our neighbour is described by the term evil. The word evil in Hebrew means to separate,
to break a connection or to shatter. And so self-interest, promoting self, promoting the ego or proprium, all of these things are what separates us from the loves of heaven flowing in and this is why they are described as being evil. They prevent the Lord's fullness being present in our life. And so evil simply is a word that points to the need to set aside our tendencies to hang on to things that do us no good, that keep us out of the life of heaven now. The only way anyone can see what the nature of the proprium is though, is through the truths of the Lord's Word and by applying them to one's inner life, to one's thoughts and one's affections. It can't be done any other way. We need to examine our life to get a sense of the inequality of the things that we are living from but when things are going smoothly, we're not so inclined to do this.  However, when are things starting to come apart, then we become open to investigating why what is happening is happening. For the sin of Achan to be discovered, the sons of Israel had to suffer that defeat. And the principle is the same with us.
Difficulties, trauma, depressions, anxieties, all these things are related to the inner life of the mind, that is the spiritual life. And these things are given energy by false beliefs, and the evils that they stem from, which we are holding onto to protect selfish desires and delights. That's just a fact, a fact that is taught on almost every page of the doctrines for Spiritual Christianity. But when we bring our affections and thoughts before the Word, we can then have insight into what troubles us for Achan, if we remember, means troubler. To find the troubler in the midst of sons of Israel Joshua sought the Lord and so this reinforces to us that we must be constantly engaged with Divine truths in the work of self-examination and repentance. And this simply means that we need to be looking to use truths to get a sense of the false beliefs and attitudes which we are holding on to so that these can be identified and called out for what they and consequently so that the Lord as the Word might be much more present for us as something that we can live from. This kind of self-reflection is illustrated in Joshua investigating the state of the sons of Israel. When he did that investigation, he did it by tribe, by family, by household, penetrating deeper and deeper and deeper until Achan was identified, rooted out and dealt with. And then the way is open for Ai to be conquered, which brings us to the sons of Israel preparing to take a take Ai for the second time.

Ai was a city of some twelve thousand people, and it was set in an elevated position. So strategically it was an important defensive position for the Canaanites and from a spiritual perspective, what is higher corresponds to what is deeper, more internal. And so what we see in Ai in the negative sense of this principle is that in this elevated position are false reasonings that defend deeper set evils than what were found in Jericho, which is on a lower plane. So Jericho was conquered by the sons of Israel and then they moved on to Ai, moving deeper into this work of self-examination. And it was in the probing of these deeper levels of mental life as represented in the first assault on Ai, that ended in the defeat of the sons of Israel so that Achan was able to be exposed. So once our self-interest has been exposed and we have acknowledged it, then victory over what is represented by Ai is assured.

Now there's an interesting thing in the Lord's instructions to the Joshua as he says that they are allowed to take the things in Ai for themselves. They were able to take the plunder and they were able to keep it for themselves, which is a contrast to what occurred in Jericho.

  Now the LORD said to Joshua: "Do not be afraid, nor be dismayed; take all the people of war with you, and arise, go up to Ai. See, I have given into your hand the king of Ai, his people, his city, and his land. "And you shall do to Ai and its king as you did to Jericho and its king. Only its spoil and its cattle you shall take as booty for yourselves."

While it's permissible to take the things of Ai, it is not permissible to take the things of Jericho. Why this difference? What is the difference here? Well, it comes down to what these two cities represent within us. Jericho has to do with our beliefs about meriting or deserving salvation. Salvation as far as Spiritual Christianity is concerned is about being delivered from the destructive tendencies of our proprium so that we can be set free from them, and the things of heaven put in their place. Now Jericho as a Canaanite city represents beliefs tied to the idea that we can save ourselves and so that we don't need the Word as the agent of our salvation. A belief that we don't need the Word must find its expression in practical terms in a lack of interest in reading it and studying it for if we truly believe that the Word is the means of our salvation from the dominance of our proprium, then we will be taking time to value it through regularly engaging with it. Saying we believe it but not doing anything that reflects that belief is not a true belief. All true beliefs that we hold to find their expression in action. So what is able to destroy the false beliefs and evils represented by Jericho is the teaching that the Lord's Word alone is our Saviour. When this is truly acknowledged through engaging with it, that is reading it and studying it and living from it, then the walls of Jericho come down and they are rendered into dust. For any notion that we can save ourselves must be destroyed completely if we are to make any progress in the spiritual life and it can only be destroyed if we are engaging with the Word. All that happens if we are not engaged with the Word and using it for for self-examination and repentance is that we are cloaking ourselves with the Babylonian garment that Achan took. The proprium will do anything to prevent us engaging with the Word to protect its nature and self-interest. It only has interest in saving itself.

So we have to come to see that we are totally dependent on the Lord for our salvation and spiritual life and this is the continual story of the sons of Israel taking the land of Canaan. Being brought back to the realisation that the Lord alone, the Word alone, is our Saviour because of what it reveals for us -- for the Divine revelation it offers us through its Divine truths. These are the Lord present with us. The command not to take anything from Jericho is given to instruct us that we are forbidden to claim any feeling, thought or action of goodness as our own or attribute to ourselves any notion that we have the power to do anything of ourselves to live a genuine spiritual life. The power we have to do all of this is from the Lord. It is from the Word, and we are instructed that we are to do good and we are to think truthfully as if of ourselves but always acknowledging that this ability is from the Lord's Word.

Now Ai is a different proposition. The name Ai means what is overturned from a root word that interestingly means to encircle for attack or protection so it's a good description of how the proprium works. Of Ai the doctrines for Spiritual Christianity say that as a city it corresponds to a structure of thought specifically, worldly knowledge.
Such knowledge isn't bad in and of itself but depending on the state of mind and possession of it, it can be used for either good or evil. A quick illustration of this can be seen in the factual knowledge of the Word itself in the literal sense. We find scholars who are not interested in the Bible as Divine revelation but are only interested in its accuracy as a historical record. When they can't find worldly knowledge or facts to back up the historical record in the Bible or facts that seem to contradict what's in the Bible, they confirm themselves in their own belief that the Bible is nothing more than a human invention because it doesn't mirror their understanding of what the historical record should be. Yet those who acknowledge the Bible primarily a spiritual document don't see its truth lying in its historical accuracy, the truth is found instead in its ability through historical accounts to convey and illustrate the realities of the psycho-spiritual world of the human mind. So debates may rage over its historical accuracy but for those who are spiritually focused such debates are a meaningless waste of time. Its truth lies in the power of the Word to transform a person's life for good. And if it can do this then it is supremely true.

So the biblical historian and the spiritual seeker view the accuracy and the order of the facts found in the Word from very different positions. For the historian it's important that they conform to what is known of history, so these known facts are like the knowledge of Ai taken by someone who does not believe in the spiritual content of the Bible. They are seen as something that disproves the truth of the record that's found in the Bible. But for a spiritual seeker it's not important. What's important is the Bible's ability to convey things to do with the spiritual life and so historical accuracy is secondary to the spiritual objective.

So for those who hold to the spiritual doctrine that the Word teaches, it is permissible to order natural knowledge to conform to and illustrate these principles of doctrine. This means that lower things can be taken and ordered in a way that they are able to serve what is higher. And this principle is represented in our text today by it being permissible now for the sons of Israel to take the things of value from Ai which are the worldly knowledges and reorganize them according to spiritual principles instead of from the natural reasoning which the world offers. Because the world will offer those same facts in a way that looks to disprove the existence of Divine and spiritual things,
same facts, same literal text but used differently. Ai as a defensive Canaanite city is the residual knowledge and reasoning that has come from the world. The sons of Israel going in and taking what belongs to it, is the taking of that knowledge and having it reordered so that it can serve spiritual ends.

And so what about this battle plan and its execution? If Ai is worldly knowledge and Canaanites are what are opposed to heavenly or spiritual life, then Ai when occupied by Canaanites represents the organization of worldly knowledge to support and defend worldly and selfish loves rather than spiritual loves and goals. So the sons of Israel arriving at Ai to destroy it is a point in the spiritual life where we will undergo conflict by which deeper, more embedded patterns of selfish thinking and feeling can be drawn out into consciousness so that they can be dealt with. And Joshua's plan illustrates the process and shows us that if we are to understand how the spiritual life progresses then we need to get in touch with the deeper meaning of the Lord's Word.
That it is our map and compass of the interior life. And it is this kind of spiritual knowledge about what takes place within the mind that Divine revelation concerns itself with because these are things we cannot discover for ourselves. They have to be revealed to us and that is why we need Divine revelation. So where the Canaanites represent the evils and falsities that arise from the reasoning of self-interest and their cities are the defensive arguments which the mind puts up to defend the proprium, so the sons of Israel represent the truths of the Lord's Word and the principles that support a genuine spiritual life.

We all know that established patterns of thinking and feeling are resistant to change but the attack on Ai provides wonderful insights into how truths are able to work on these internal structures of our minds to set us free. For when we use truths in the work of self-examination this is like the sons of Israel taking a position around the city and just as they are under the command of Joshua, so we too need to take our lead from what the Word teaches. For Joshua represents the Lord as the Word. He represents this because he receives from Jehovah what is needed to be done and conveys it to the people.
Just as the Word has received from the Lord what is of Him and what needs to be done and is conveyed by means of the Word to us. So when these truths are brought into contact with our established patterns of false thinking from selfish desires then things begin to get stirred up and this may well be experienced by a person as rising anxiety levels or states of depression that can often occur without any apparent reason or obvious signs as to why. This is because as when we work with truths then what is opposed to them seems to become active in us although in actual fact these things have always been there present for us, it's just that now the light of truth is allowing us to see them.

In the account of Ai's defeat its inhabitants are drawn out as the sons of Israel appear to flee.

  And he commanded them, saying: "Behold, you shall lie in ambush against the city, behind the city. Do not go very far from the city, but all of you be ready. "Then I and all the people who are with me will approach the city; and it will come about, when they come out against us as at the first, that we shall flee before them. "For they will come out after us till we have drawn them from the city, for they will say, 'They are fleeing before us as at the first.' Therefore we will flee before them.

And if we reflect a little on our own experience of spiritual work, we will see that this is often how it is for us. As states of inner conflict get more pronounced, we can become confused and unsure, and doubts enter in and this is illustrated by the sons of Israel fleeing from before the people of Ai. It's like the truth that we have learnt and worked with seems at those times to be powerless to arrest those old unwanted patterns of being and we begin to be dominated by them once again.

However, if we have been faithful in our willingness to learn from the Word, to apply it to our lives, to reflect on our inner states and so seek the Lord so that we have the power to enter into a practice of repentance, then what happens is that as far as our interior lives are concerned -- a change is possible. And sometimes it may seem as though this change can occur very quickly but what we must remember is that prior to the shift there has been a long period of work that has gone on and defeats that have seemingly been suffered. But it's all leading towards the Lord delivering us and so what may appear to be a defeat in the short term, is merely a process of being strengthened and prepared for that shift to occur in the longer term.

So as the negative emotional content represented by the people of Ai pour out of the city in attempt to destroy those sons of Israel, the truths that are perceived to be their enemies, the states of Ai within us are being put in a weakened position. They're being made vulnerable,
and this is like the realisation that hits us that these negative emotions, these states of suffering that we are experiencing, really have no basis in reality. That they are conjured up things to do with false perceptions and so when this is seen, a shift begins to occur in the mind. Those truths that we have been working with leading up until this moment now appear to come out of hiding, as if they have been waiting in ambush for the city of Ai to be weakened to the point where it will not be able to stand. And so in those states we find that we become more conscious of these truths and they can begin to take a more active role. For we see that the mental fortifications and defensive justifications that we had built up are no longer able to repel what is true and this is represented by the sons of Israel now being able to enter in and destroy the city of Ai.

  "Then you shall rise from the ambush and seize the city, for the LORD your God will deliver it into your hand. "And it will be, when you have taken the city, that you shall set the city on fire. According to the commandment of the LORD you shall do. See, I have commanded you."

With the defences now exposed all that they have been employed to defend, all the people of Ai, are put to the mouth of the sword. They are destroyed utterly. And this is a symbolic representation of how truths of the Lord's Word are able to subdue every false thought and selfish intention.

  And it came to pass when Israel had made an end of slaying all the inhabitants of Ai in the field, in the wilderness where they pursued them, and when they all had fallen by the edge of the sword until they were consumed, that all the Israelites returned to Ai and struck it with the edge of the sword. ^25 So it was that all who fell that day, both men and women, were twelve thousand -- all the people of Ai. (24 & 25)

And so in the closing passage of chapter 8 we find the sons of Israel go about and they build an altar made from stones that are untouched by man by any iron tool.

  Now Joshua built an altar to the LORD God of Israel in Mount Ebal, as Moses the servant of the LORD had commanded the children of Israel, as it is written in the Book of the Law of Moses: "an altar of whole stones over which no man has wielded an iron tool."

And this captures the importance that in our worship of the Lord in living a spiritual life, we are not to fashion truths from the Word to suit ourselves but that we are to come before the Lord in humility of heart. To take His truths as they are presented even when they are hard to bear and use them so that we can engage in this battle to which our salvation is so closely tied. If we are prepared to do that then we find that there is a rereading of the law. It is affirmed. The Word is affirmed for us, and we see it in a new light and we find a renewed recommit in our faithfulness to Him.

  And they offered on it burnt offerings to the LORD, and sacrificed peace offerings. And there, in the presence of the sons of Israel, he wrote on the stones a copy of the law of Moses, which he had written ... And afterward he read all the words of the law, the blessings and the cursings, according to all that is written in the Book of the Law. There was not a word of all that Moses had commanded which Joshua did not read before all the assembly of Israel, with the women, the little ones, and the strangers who were living among them.

