ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 15. The Deception Of The Gibeonites (9)

  And it came to pass when all the kings who were on this side of the
  Jordan, in the hills and in the lowland and in all the coasts of the
  Great Sea toward Lebanon -- the Hittite, the Amorite, the Canaanite,
  the Perizzite, the Hivite, and the Jebusite -- heard about it, that
  they gathered together to fight with Joshua and Israel with one
  accord. But when the inhabitants of Gibeon heard what Joshua had
  done to Jericho and Ai, they worked craftily, and went and pretended
  to be ambassadors. And they took old sacks on their donkeys, old
  wineskins torn and mended, old and patched sandals on their feet,
  and old garments on themselves; and all the bread of their provision
  was dry and moldy. And they went to Joshua, to the camp at Gilgal,
  and said to him and to the men of Israel, “We have come from a far
  country; now therefore, make a covenant with us.” Then the men of
  Israel said to the Hivites, “Perhaps you dwell among us; so how can
  we make a covenant with you?” But they said to Joshua, “We are your
  servants.” And Joshua said to them, “Who are you, and where do you
  come from?” So they said to him: “From a very far country your
  servants have come, because of the name of the LORD your God; for we
  have heard of His fame, and all that He did in Egypt, and all that
  He did to the two kings of the Amorites who were beyond the
  Jordan -- to Sihon king of Heshbon, and Og king of Bashan, who was at
  Ashtaroth. Therefore our elders and all the inhabitants of our
  country spoke to us, saying, ‘Take provisions with you for the
  journey, and go to meet them, and say to them, “We are your
  servants; now therefore, make a covenant with us.” This bread of
  ours we took hot for our provision from our houses on the day we
  departed to come to you. But now look, it is dry and mouldy. And
  these wineskins which we filled were new, and see, they are torn;
  and these our garments and our sandals have become old because of
  the very long journey.” Then the men of Israel took some of their
  provisions; but they did not ask counsel of the LORD. So Joshua made
  peace with them, and made a covenant with them to let them live; and
  the rulers of the congregation swore to them. And it happened at the
  end of three days, after they had made a covenant with them, that
  they heard that they were their neighbours who dwelt near them. Then
  the children of Israel journeyed and came to their cities on the
  third day. Now their cities were Gibeon, Chephirah, Beeroth, and
  Kirjath Jearim. But the children of Israel did not attack them,
  because the rulers of the congregation had sworn to them by the LORD
  God of Israel. And all the congregation complained against the
  rulers. Then all the rulers said to all the congregation, “We have
  sworn to them by the LORD God of Israel; now therefore, we may not
  touch them. “This we will do to them: We will let them live, lest
  wrath be upon us because of the oath which we swore to them.” And
  the rulers said to them, “Let them live, but let them be woodcutters
  and water carriers for all the congregation, as the rulers had
  promised them.” Then Joshua called for them, and he spoke to them,
  saying, “Why have you deceived us, saying, ‘We are very far from
  you,' when you dwell near us? “Now therefore, you are cursed, and
  none of you shall be freed from being slaves -- woodcutters and water
  carriers for the house of my God.” So they answered Joshua and said,
  “Because your servants were clearly told that the LORD your God
  commanded His servant Moses to give you all the land, and to destroy
  all the inhabitants of the land from before you; therefore we were
  very much afraid for our lives because of you, and have done this
  thing. “And now, here we are, in your hands; do with us as it seems
  good and right to do to us.” So he did to them, and delivered them
  out of the hand of the children of Israel, so that they did not kill
  them. And that day Joshua made them woodcutters and water carriers
  for the congregation and for the altar of the LORD, in the place
  which He would choose, even to this day. (Joshua 9:1-27)

  The reason ‘drawing water' means instruction and also consequent
  enlightenment, as in later verses of this chapter, is that ‘water in
  the internal sense means the truths of faith, 2702. Thus ‘drawing
  water' is nothing else than receiving instruction in the truths of
  faith and so being enlightened, as is also the meaning elsewhere in
  the Word, as in Isaiah,

  With joy you will draw water from the springs of salvation, and [you
  will say] or that day, Confess Jehovah. Isa. 12:3, 4.

  ‘Drawing water' stands for receiving instruction, having
  intelligence, and being wise. In the same prophet,

  To the thirsty bring water, O inhabitants of the land of Tema. Isa.
  21:14.

  ‘Bringing water to the thirsty' stands for giving instruction. In
  the same prophet,

  The wretched and the needy are seeking water, and there is none;
  their tongue is parched with thirst. Isa. 41:17.

  ‘Those seeking water' stands for those desiring instruction in
  truths, ‘and there is none' stands for the fact that nobody had any.
  In addition ‘drawers of water' in the Jewish Church represented
  those who constantly seek to know truths but to no other end than
  just knowing them, and who consequently pay no attention to their
  purpose. Such persons were rated among the lowest of all. The
  Gibeonites mentioned in Josh. 9:21, 23, 27, represented them.

  (Arcana Coelestia 3058)

  People who have assumed that righteousness and merit lay in their
  good works and so have attributed the power of achieving salvation
  to themselves, not to the Lord and to His righteousness and merit,
  and who in thought and life have confirmed themselves in this idea,
  have their assumptions converted in the next life into delusions in
  which they seem to themselves to be cutting wood. This is exactly
  how it appears to them. I have spoken to them. When they are doing
  their work and are asked whether they are not tired out, they reply
  that they have not yet done enough work to be able to merit heaven.
  While they are cutting pieces of wood it seems as though something
  of the Lord is underneath the wood, so that the wood appears as
  merit. And the more something of the Lord seems to be in the pieces
  of wood the longer they remain in that condition. But when this
  delusion starts to fade they are getting nearer the end of
  vastation. At length they become such that they too are able to be
  admitted into good communities, though they still waver for a long
  time between truth and falsity. Because they have led a
  conscientious life the Lord takes great care of them, and is sending
  angels to them time and again. These are the people who in the
  Jewish Church were represented by ‘hewers of wood', Josh. 9:23, 27.
  (Arcana Coelestia 1100)

The spiritual man knows truths but is often not in the belief of them.
This might seem like a strange statement because we often associate belief with what we know but there is an external kind of knowing and there is an internal kind of knowing. So regardless of what we profess with our mouths, it's actually how we live that reflects what we believe, and so reflects this internal knowing or understanding.

And what we've seen in our exploration of the book of Joshua, is that there is this constant theme of falling into the belief that we have life in ourselves, and that this belief is the root of every evil and falsity within the human condition. The Word therefore has to constantly remind us that all life flows in from the Lord and that although it may feel as if it is us -- this is an appearance. So, when the doctrines for Spiritual Christianity speak of not believing appearances to be real, it has to do with not running with how things feel and instead believing what the Word teaches concerning how things are. This is something central to the tribe of Hivites called the Gibeonites which we are now going to explore in depth.

Spiritual life doesn't truly begin until we make a shift from being focused on outer life to giving attention to the inner life of our mind. The Lord is faithful and is supportive of this in that He provides countless ways for people to begin to work in conjunction with Him but the specific teachings which Spiritual Christianity offers,
allows us to go into a deeper understanding of the inner meaning of the Word and to see how it applies to the life of our own mind.

And why is this inner meaning or access to the inner meaning of the Word so important?

There are many reasons, but two of them are as follows. Firstly, the inner meaning found in the Bible is the clearest and most accurate guide to the mental processes involved in a person's spiritual development or regeneration. And even more importantly, is that the Word is from the Lord, and because the Word is from the Lord, it is the Lord.

This inner meaning, when it shines forth in a person's mind, is the Lord's very presence with them. It is the spiritual Sun which is able to fill us with the warmth of heaven's loves and delight us with eternal truths. So, where we see the Lord described as the Sun in the doctrines for Spiritual Christianity, it is referring to the Word as to its interior meanings when it is made the core and center of our life,
just as it is with the inhabitants of heaven. For the spiritual Sun is what warms and enlightens angelic consciousness.

The key to accessing the inner meaning of the Word lies in the attitude that we bring to it. If we are willing to be led by the Word, which is what it means to be led by the Lord, to examine our life so that those things that are within which prevent the loves of heaven being more prominent in our lives can be removed, then the Word is able to be opened to us. We can gain insights from it and in doing so, we are able to see that it is the Lord who lies within. And thus, that it is the Lord who enlightens our minds and lights our path.

One of the features of the story from the book of Joshua today is this need to constantly consult the Word as the guide to what is good and true. For it is the Word alone that is able to enlighten us as to what is genuinely good and true, and what is not. But that can only happen for us if we are in an attitude that is looking to live from the Word to live a genuine spiritual life.

So we come to the story of the deception of the Gibeonites. Here we see that they were motivated by a spirit of self-preservation. The story as it stands in its literal sense also reveals that a division was taking place among the Canaanites into two groups. Those who are openly opposed to the presence of the Israelites, and the Gibeonites who are of the Hivites who have assessed the situation and deemed that the best course of action was to find a way of making a covenant with Israel.
Now the doctrines for Spiritual Christianity teach that in the Word the land of Canaan, and all that is within it, is representative of the church and all its states of development towards what is good or towards what is evil depending on the context. And it's essential that when we read and speak of the church, that we don't think of churches in the natural world, of organisations, but instead keep our attention on those things which belong to the inner world of the human mind. Here in each of our minds is a vast land in which there exists whole vistas of thoughts and affections all interrelated like nations, peoples,
tribes, families, and individuals. And these various bodies of thoughts and affections are organised in our minds according to what we value or love most of all, and it is this which makes up our sense of self. The ideas and affections that fit best with who we feel we are, these are closest to us, that is, they are those things that our thoughts and our affections gravitate towards most often. Our sense of self is intimately related to the things that our thought and affections return to time and time again. Then there are also those things that grab our attention every now and again but they don't stay in our focus for long. These are not so close to our sense of self. They are more distant to the loves which rule our states. So we can know something of our inner life and the beliefs which we truly subscribe to, by getting a sense of what we invest our mental energy into as far as our thinking and affectional states are concerned.

What we see with the Israelites taking possession of the land of Canaan is a representation of how our minds are reordered by the Lord as truths represented by the sons of Israel advance in us through a willingness to live from them. All the different tribes encountered there in the land are representative of things found within our own minds where they take the form of psychological and spiritual realities that stand opposed to the heavenly life. These are structures of thought in us that are formed by the love of self and the love of the world and these can stand in defiance of the word like those tribes who gather an open opposition to the progression of Israel. And then there are structures of thought that look legitimate on the surface, but on closer examination aren't what they appear to be like the Gibeonites in this story.

So, I don't doubt that there are things that we can put our finger on in our own lives which we know are just plain selfish and are opposed to what is heavenly. And hopefully in seeing these things we can work with the Word, with the Lord, so that they can be removed to the extremities of our thinking and so changes can take place in our life which lead to more of the Lord's love and wisdom being able to be expressed. Likewise, there will be things in our lives that we recognise as being loving and wise and so from the Lord. These things are truly useful and contribute to the overall health and well-being of others.

But then there are those areas that we are just not sure about.

The story of the Gibeonites brings into focus this grey area of appearances versus what is real, or how things seem on the surface as opposed to what the Word teaches as to how things really are. The word used to describe the Gibeoniteactivity is interesting for we read that they are said to have worked craftily.

  … when the inhabitants of Gibeon heard what Joshua had done to
  Jericho and Ai, they worked craftily, and went and pretended to be
  ambassadors.

And this word craftily from the Hebrew is the same word used to describe the nature of the serpent in the garden that tempted the woman. This quality of craftiness or subtlety belongs to the lower thinking and feeling level of our minds. It's what sits close to the physical senses. It's a level where appearances are strong. So much so that without guidance from Divine revelation, we are prone to draw conclusions about life that are just plain false and the degree to which these are confirmed or believed, to that degree we are shut down from experiencing the inflow of heavenly life.

The thing with the Gibeonites is that from all appearances they looked okay. But we see in Joshua's response to them that there is this sense that all might not appear to be as it seems.

  And they went to Joshua, to the camp at Gilgal, and said to him and
  to the men of Israel, “We have come from a far country; now
  therefore, make a covenant with us.” Then the men of Israel said to
  the Hivites, “Perhaps you dwell among us; so how can we make a
  covenant with you?”

The Gibeonites appear to be something from a distance when in fact they reside right in the midst of the land as one of the Canaanite tribes that the Lord had commanded Israel to destroy. This appearance of being distant conveys the idea that what is presenting is not something that we really need worry about. There is a level of disconnection or perhaps even denial of just how close to us the evils and falsities represented by this tribe actually are.

So once again, this deception of the Gibeonites brings us back to the theme that runs throughout the book Joshua of believing what our senses tell us in preference to what the Word teaches. From the spies sent out from Shittim to the destruction of Jericho and Ai, we see illustrated the battle which we have of letting go of the belief that we have life in ourselves. This belief gives rise to claiming merit to what is of the Lord to oneself. It is the root of all evil and falsity which needs identifying and acknowledging and confessing. It is what we need to find in ourselves as we walk the spiritual path because this single belief invites hellish influences into our life. For if we truly acknowledged as a matter of our very life, and not just as a matter of the head, that all life is from the Lord alone then nothing evil or false could touch us. Yet as simple as this sounds, in practice we really do struggle to integrate this truth into our life; to be able to separate ourselves from believing the feeling that we have life in ourselves as something that is true. It is a powerful appearance, a powerful deception. So, it can be difficult to admit that for much of our daily life we actually function from this false belief. In fact, if we aren't reminding ourselves on a constant basis that all life flows in from the Lord by engaging in the work of self-examination and repentance, then we can't help but live our lives it. For without a spiritual practice which involves working consciously in an effort to live from spiritual principles, we remain oblivious to its subtle workings.

Now it's interesting that the doctrines for Spiritual Christianity describe the Gibeonites as representing a state or love of knowledge for its own sake. And what that means is that there is no interest in how to use it or how it can be applied for the benefit of others. It's knowledge for knowledge's sake. Therefore, in the spiritual life, the Gibeonites represent the subtle deception of a lower form of mental activity that manifests as a drive to gather spiritual knowledge, to investigate doctrines and spiritual teachings. But it does this without giving any thought as to how this knowledge can be applied to life. The Gibeonites in us can manifest as a love to read and study the Word and the doctrines for Spiritual Christianity, or books on spiritual subjects, or as delight in conversations about spiritual matters but the problem is, is that it doesn't take things any further. This is the deception they represent. And what we can see from this story in the Word is that this kind of activity is in fact a subtle form of evil that is very close to us all, within our very midst. Yet we cannot, or often cannot see it. Hence the appearance of it being represented as something distant, as something we don't have to worry about.

Now most people in the church, including the voices of the people in the church within us, would say that reading and studying the Word is a good thing. But if this is done without looking to use what we know to work on our life so that we are creating opportunities for the Lord to be more closely linked to us, then we are open to being deceived that this activity somehow represents a legitimate spiritual pursuit. The gathering of spiritual knowledge becomes a substitute for living a spiritual life. And this subtle deception is what the Gibbonites are.
The exterior trappings of

  old wineskins torn and mended, old and patched sandals on their
  feet, and old garments on themselves; and .. the bread of their
  provision was dry and mouldy.

These all were the signs that a long journey had been undertaken when in fact nothing of the kind had occurred. Similarly, the collection of knowledge and doctrines in the memory of being able to exhibit an understanding of spiritual things as represented by the asses on which these things were carried. These all give the appearance of someone progressing in the spiritual life, taking a spiritual journey. Yet if there has been no application of these things to the inner life of the mind, to the thoughts and affections, then nothing really spiritual is being presented at all. It's all merely external appearances.

The response of the sons of Israel in assessing the legitimacy of the Gibeonites in the literal sense is telling and it holds a critical lesson for us all. Despite their doubts about the story the Gibeonites gave of having travelled from afar, the Scripture states in verse 14 that the men of Israel checked over their provisions to see if they did indeed show signs indicating a long journey. And then it says

   the men of Israel took some of their provisions; but they did not
  ask counsel of the LORD.

And in the literal version of this it translates to:

  that they did not inquire of the mouth of the Lord.

Now the mouth of the Lord is the Word. And the lesson is that the Word alone shows us the true nature of the things within the mind because it's able to cut through the false rationalisations and justifications which preserve the life and activity of those things that support selfish states. Hence, we are constantly admonished to go back to it,
to go back to the Word. Not even relying on the knowledge in our memory but to take this knowledge and consistently go back to the Word and to examine what it is we profess to know versus what we actually know and live from.

So this lesson teaches us that no matter how far we think we have come in the spiritual life we are always, always susceptible to the deception of appearances. And so we need to keep engaged with the truths of the Lord's Word so that He can lead and guide us.

Now the Lord is well aware of our susceptibility to the appearances of the senses. And so, with our spiritual welfare in mind He allows for a covenant to be struck between the Israelites and the Gibeonites. In the end the Gibeonites are cursed to forever serve in the house of God as drawers of water and hewers of wood.

  And that day Joshua made them woodcutters and water carriers for the
  congregation and for the altar of the LORD, in the place which He
  would choose, even to this day.

Thus, they are given a use to serve for even the delight of seeking knowledge for its own sake can serve a use so long as it remains a servant in support of heavenly things. As long as it serves to support a person involving themselves in self-examination and repentance, then the knowledge drawn can be the servant to higher principles and loves.
All spiritual knowledge is given to be used to support people in their regeneration. The nature of that support though can only be opened up to us when we are in an effort to live from those truths. For it is the application of the Word to life, to the life of our minds, to the life of our thought and affections, which enables the Lord to open the Word as to its deeper meaning. And when this happens -- we see Him shining forth from within it.

