ifndef::fullbook[]
= Sermons on Joshua 
Rev. David Millar

Created and published by the Logopraxis Institute +
https://logopraxis-institute.online/joshua/

[.text-right]
Republished [with permission?] by NCBS +
{docdate}

endif::[]


---
<<<


== 16. Dealing With Adoni-Zedek (10)

  Now it came to pass when Adoni-Zedek king of Jerusalem heard how
  Joshua had taken Ai and had utterly destroyed it -- as he had done to
  Jericho and its king, so he had done to Ai and its king -- and how the
  inhabitants of Gibeon had made peace with Israel and were among
  them, that they feared greatly, because Gibeon was a great city,
  like one of the royal cities, and because it was greater than Ai,
  and all its men were mighty. Therefore Adoni-Zedek king of Jerusalem
  sent to Hoham king of Hebron, Piram king of Jarmuth, Japhia king of
  Lachish, and Debir king of Eglon, saying, “Come up to me and help
  me, that we may attack Gibeon, for it has made peace with Joshua and
  with the children of Israel.” Therefore the five kings of the
  Amorites, the king of Jerusalem, the king of Hebron, the king of
  Jarmuth, the king of Lachish, and the king of Eglon, gathered
  together and went up, they and all their armies, and camped before
  Gibeon and made war against it. And the men of Gibeon sent to Joshua
  at the camp at Gilgal, saying, “Do not forsake your servants; come
  up to us quickly, save us and help us, for all the kings of the
  Amorites who dwell in the mountains have gathered together against
  us.” So Joshua ascended from Gilgal, he and all the people of war
  with him, and all the mighty men of valor. And the LORD said to
  Joshua, “Do not fear them, for I have delivered them into your hand;
  not a man of them shall stand before you.” Joshua therefore came
  upon them suddenly, having marched all night from Gilgal. So the
  LORD routed them before Israel, killed them with a great slaughter
  at Gibeon, chased them along the road that goes to Beth Horon, and
  struck them down as far as Azekah and Makkedah. And it happened, as
  they fled before Israel and were on the descent of Beth Horon, that
  the LORD cast down large hailstones from heaven on them as far as
  Azekah, and they died. There were more who died from the hailstones
  than the children of Israel killed with the sword. (Joshua 10:1-11)

  Because the historical parts of the Word are representative, and
  contain an internal sense, equally as the prophetical parts,
  therefore this is the case also in regard to what is related of the
  five kings of the Amorites, and of the battle of the sons of Israel
  with them. For the nations that were driven out of the land of
  Canaan signified the evil who were to be cast out of the kingdom of
  the Lord, and the sons of Israel signify those to whom it is granted
  to possess the kingdom. The land of Canaan signified heaven and the
  church, and therefore the kingdom of the Lord; hence the five kings
  of the Amorites signified those who are in falsities of evil, and
  desire to destroy the truths of the good of the church. It was for
  this reason, that they were slain by hailstones from heaven, that is
  to say, they perished and were destroyed by their own falsities of
  evil; for the evil themselves perish by their own evils and
  falsities, by means of which they desire to destroy the truths and
  goods of the church. (Apocalypse Explained 503{6})

The conquest of Canaan, by Joshua and the sons of Israel under the direction of the Lord, represents the subduing of those forces that have become well established within the human psyche or spirit. And this is due to drawing conclusions about life from what appears to our senses and not being in touch with spiritual truths. From birth, we are devoid of a genuine spiritual understanding and as we advance through natural states of development through to adulthood, we gather all kinds of principles and beliefs that we look to live our lives from. In fact,
what we do is build up a philosophy for our life and this philosophy is witnessed in how we engage with others, the events and conditions of our life and in how we look at ourselves from an internal perspective.
So, we gather together a whole raft of beliefs about God, about ourselves, about others, about the mental, social and physical worlds that we experience as our own. But without genuine spiritual truths to guide us, what happens is that most of the material that makes up these worlds which we call our 'own', is constructed around fallacies concerning the true nature of life. And so it is that most spiritual traditions teach that the conditions of our natural birth result in people valuing things which have no spiritual value, and discounting those which are of an eternal nature. These traditions also teach that this inversion, where what is natural and material is valued over what is spiritual and eternal, is only reversed through the cultivation of a spiritual practice.

Now such a practice, as far as Spiritual Christianity is concerned,
revolves around us being engaged in taking truths and using them to reflect on the internal life of our minds. The reason that we are asked to do this is so that we can gain self-knowledge. This self-knowledge is a knowledge of the quality of what passes through our minds in terms of its thoughts and its affections and unless we make an effort to be aware of this, we remain unconscious to what is present. So the practice of Spiritual Christianity involves observing the quality of these things in the light of truths from the Word for it is from this that we learn to discern what is in keeping with a genuine spiritual or heavenly life, and what is opposed to it. Now the nature of this practice is found in many places within the doctrines for Spiritual Christianity and one such example we find in the work Divine Providence 83(5&6),

  So long as evils continue in the lusts of their love, and the
  consequent enjoyments, there is no faith, charity, piety or worship
  except in mere externals, which to the world seem real, and yet are
  not. These may be compared to water issuing from an impure fountain,
  which no one can drink. Man continues in the first state as long as
  he thinks from religion about heaven and about God, and yet gives no
  thought to evils as sins; but he comes into the second state, or the
  state of reformation, when he begins to think that there is such a
  thing as sin; and still more when he thinks that this or that is a
  sin, and when he examines it in himself to some extent, and refrains
  from willing it.

  Man's third state, which is a state of regeneration, takes up and
  continues the former state. It begins when man refrains from evils
  as sins, and it progresses as he shuns them, and is perfected as he
  fights against them; and as he from the Lord conquers them he is
  regenerated. With one who is regenerated the order of life is
  reversed; from being natural he becomes spiritual.

The issue for many is seeing the need to reflect in this way and then seeing the need to respond affirmatively to what truths teach. Because truths, when they reveal something, provide opportunities for us to have our sense of self extracted from the natural patterns of thought and affection that have built up over the course of our lives and that are destructive to the life of the spirit. So in the story and events of the journey of the sons of Israel from Egypt to Canaan or the Promised Land, we have a parable which when understood as to its spiritual application, offers us an incredibly detailed account of the shifts in our mental states as we pass through this process of being natural to becoming spiritual. And it has to do with learning to use the Word as a guide to building a spiritual practice.

When the Israelites were in the wilderness journeying towards Canaan,
we have a representation of what's involved in our initial experience of spiritual life. This is a state of life in which our sense of spirituality is based on the external plane of actions, speech and behaviour -- of how things appear externally to the world and to others.
This is what matters when we're in this state and it is notable that when we are in this state of external concerns of how things appear,
then our attention is not really given to the more internal things of the mind. This external level of religion and spiritual life is what is represented by the Israelites and the things that occurred outside of Canaan.

But when Joshua leads the sons of Israel across the Jordan into Canaan itself, we have represented there a significant shift in our understanding of what constitutes a genuine spiritual life. It's a time when we begin to see that giving our attention to cleaning up our outer life is only a preparation for a much deeper work. And so it is that here within the boundaries of Canaan that this new state is pictured,
where the internal things that are connected with the life of the mind begin to come into the focus of our attention or awareness. This is a time that can be very disconcerting, a time of disruption. Because until this shift of focus occurs people, more often than not, think that they're doing okay, that they have things together and have done all the things that are necessary or are doing all the things that are required of them, as far as the spiritual life is concerned. But if inner work has not been done whereby we have seen our evils,
acknowledged them as sins, and sought the Lord in order to have them removed, then remaining in the external appearance that 'everything is okay' results in a false sense of security which is based on placing our importance on natural life and those things that belong to the external or natural man.

An externally ordered life in this state only serves to cover over deeper evils and falsities that are rooted in selfishness. These things are embedded within aspects of our ego or proprium and have been developed over the course of our whole life. The movement of the Israelites into Canaan and having to confront the peoples there, is representative of our own moving into reflecting on our internal life,
the life of our mind, and seeing these evils coming into awareness.
Seeing that they are in fact enemies of the spiritual life which seek to rob us of what the Lord has for us as our rightful inheritance.

So as a parable, everything in the land and all that occurs as the Israelites are making their way through it, represent things within the sphere of our own minds as we look to the Word of God to lead and guide us. Joshua is the Word, or Divine truth that leads us in the fight against all forms of selfishness. The sons of Israel are those specific truths that we have acquired from the Word, things that the Lord is now able to call upon and gather together from within our minds to fight against every form of self-interest that opposes the advance of the kingdom of God. And our resisting of selfish motivations and orientations that have become entrenched in our patterns of feeling and thinking over the course of our lives, is appropriately illustrated by battles. For here we have what is of the Lord as represented by the Israelites, those spiritual principles and truths from the Word, coming up against that which is opposed to them -- the evils and falsities, the false perspectives, the things that separate us from others and from the Lord.  And these are represented by the Canaanite and Amorite tribes who populate the land.

The Canaanite represents heredity tendencies to evils found within every human being, which can become embedded in our character through acting on selfish impulses. And around them we have the Amorites who are those thinking structures and false perspectives that look to defend and self-justify these evils. They are the rationalisations that we make when we are feeling a particular way and act from a negative emotion, and then after move into a mode of justifying our behaviour.
So the negative emotion and impulses are like the Canaanites and the defending of it with our rationalisations are Amorites.

Now in the previous story of the Gibeonites we saw how they deceived the sons of Israel into forming a covenant with them so as to protect themselves and to avoid having them to have to face the Israelites in battle and risk being utterly destroyed, as the Israelites had done to Jericho and Ai. Now the spiritual meaning of that story rests in the idea that there are things in us that serve motives of self-interest which can be used for higher purposes. In the case of the Gibeonites we saw that this tribe represented a lower level motivation in the mind that manifests in us as an interest in spiritual knowledge and interest in spiritual knowledge and Scripture and spiritual teachings can be motivated either by self-interest or a genuine interest in living a spiritual life. And this is why the Gibeonites could be aligned either with the Canaanites or with the sons of Israel.  For an interest in spiritual knowledge doesn't necessarily make us spiritual people. We can have a natural interest in spiritual knowledge, and it goes no further, or we can have an interest in spiritual knowledge that looks to cleaning up our interior life.

So spiritual knowledge, if used properly, assists us to reflect on our lives so that we can live from what is higher, from the Word and therefore a switch of allegiance of the Gibeonites represents a shift in the way that spiritual information affects us. In their entering into a covenant with Israel we have an illustration of the use of spiritual knowledge from the Word to support a life of personal self-examination and reflection and subsequent repentance. This is in stark contrast to the use of such knowledge as represented by the Gibeonites when they were allied with the Canaanites and the Amorites.
When allied with the Canaanites we have represented a state that looks to the acquisition of spiritual knowledge so that it can be used to give merely the external appearance of spirituality when internally,
the ruling motivation remains one of it to promote one's own interests.
And so in this state we use that knowledge to convince ourselves that we are spiritual, but that we don't actually have to do any reflection and work. That's how this level of the Gibeonites works when it is aligned with the Canaanites and Amorites.

Now this is a state which can only be seen in hindsight, when we've actually journeyed beyond it to some degree because when we use truths to reflect on our life then we begin to see how this Gibeonite-Canaanite relationship stands and how it was with us. When we're in this mode of life we are completely oblivious to the quality of our motivations, we're not reflecting on them, and we feel that we are sincere in our spiritual pursuits. Thus, any challenge to the contrary results in us feeling affronted and that our integrity is being attacked -- but this is part of the process. For when the things that are operating in our life that don't quite fit with our idea of being spiritual begin to be exposed, then we feel this sense of injustice arising within us. These are powerful emotions, a deep sense of injustice, a sense of being misunderstood or of being treated unfairly. This is what begins to occur when this change of alliances for the Gibeonite's begins to happen. We actually begin to see that there are things in us that don't match the image which we carry around of ourselves and project to the world.

We need to understand that to progress in the spiritual life, this innocence of injustice which is tied to a false perspective of who we see ourselves as, has to be brought out and dealt with. This is not something that is found in some people and not in others. This tendency exists within all of us as the ego or proprium and once we start pursuing a spiritual life then we can be sure that it will make its presence known to us, or rather the Word will highlight it for us.  The question is -- What will we do when that occurs?

In our story today we are presented with five kings who form an alliance to come against the Gibeonites once they see that they have made a covenant with Israel and pose as a threat.

  Now it came to pass when Adoni-Zedek king of Jerusalem heard how
  Joshua had taken Ai and had utterly destroyed it -- as he had done to
  Jericho and its king, so he had done to Ai and its king -- and how the
  inhabitants of Gibeon had made peace with Israel and were among
  them, that they feared greatly, because Gibeon was a great city,
  like one of the royal cities, and because it was greater than Ai,
  and all its men were mighty. Therefore Adoni-Zedek king of Jerusalem
  sent to Hoham king of Hebron, Piram king of Jarmuth, Japhia king of
  Lachish, and Debir king of Eglon, saying, “Come up to me and help
  me, that we may attack Gibeon, for it has made peace with Joshua and
  with the children of Israel.”

The city of the Gibeonite sis described as a royal city and their men as mighty men. In the Amoritse and the Canaanitse this was a dire situation that needed to be put right. The rising of these five kings is the rising of five ruling principles that are raised up and connected with Adoni-Zedek who leads this. These are interrelated principles that have to do with our sense of self-righteousness. They come up to attack the Gibeonites and this illustrates the drawing out of those feelings of injustice which are grounded in the sense of our self that is based in selfishness, in the proprium or ego. As such, it is a false sense of injustice that erupts from a false perspective that sees truth, or the revealing of these things, as an enemy. And so,
there is a resistance to it. We don't want to see it. We don't want to have anything to do with it. We don't want it to damage the self-image which we carry around concerning ourselves that informs us that we are good people, that we have good in us and that that good is our own.
This good person which we see ourselves as is a construction of the ego. It takes spiritual knowledge and attributes it to itself as its own. 'I am a good and upright person who is kind and loving and wouldn't do harm to anyone'. These are the ideas that sit with Adoni-Zedek.

The fact is -- the Lord alone is good and we, apart from the Lord, are effectively nothing. The Lord is everything and all we can produce apart from the Lord is what is evil and false. And what sits beneath this projection of a false sense of self is knowledge that what the Word says we should be is good, loving, compassionate people. Now the thing to realise is that when this idea enters into the natural mind the ego or the proprium appropriates it to itself. It doesn't want to be exposed. So it takes this idea from the Word that we need to be good, loving and compassionate people and it convinces us that we are,
when we haven't done any self-reflection to actually see what the state of our inner life is.

And so, a funny thing begins to happen when we begin to use spiritual knowledge to reflect upon the quality of our thoughts and affections.
We begin to see that the image that the proprium promotes is not a true picture: we find that we may be kind and amenable to others on the outside but inside we are filled with judgments and criticisms, we feel that others don't meet our expectations, we often feel slighted, we take offense, we say what we know we shouldn't say, and the list goes on and on and on.

Without observing these things in ourselves, they remain, and the Lord can do nothing. He gives us truths so that we can reflect and see these things, and so we enter into the battle. The doctrines for Spiritual Christianity teach that the spiritual man is in constant conflict. That this is what the spiritual life is and is what we sign up for when we enter spiritual work. For when we begin to see these things, our first reaction is denial. We ignore it, we dismiss it. We look for allies to convince us that we are right, whether those are internal mental rationalisations, or we go to others to seek affirmation that we are in the right. We fashion together all kinds of justifications and excuses to blunt the contradictions that are arising and making their presence felt within our awareness. This tendency to deny what's arising for us,
to keep our self-image intact, is captured in this quote from True Christian Religion 564(3),

  The merely natural man can see good and evil in others, and also
  rebuke others; but not having looked into and examined himself, he
  does not see any evil in himself, and if any is discovered by
  another, he cloaks it by means of his rationality; as a serpent
  hides his head in the dust.

So, it's perhaps easier to see when we feel offended or unjustly treated when we're engaged with other people but if we can get some distance from these emotions, then we would see that these feelings are certainly not flowing in from a heavenly source. This is difficult though as when we are caught up in those negative emotions, we can't see it, we can't see what it is. We feel we have suffered an injustice because something has been taken from us and it needs restoring and so have every right to respond and defend our self-image's credibility.
Now whenever such feelings arise and we lash out in defence or perhaps depending on our personality, we withdraw into our hurts, and we find ourselves obsessing about what others have done and how unfair and unjust it is, then what we are feeling is Adoni-Zedek rising up within us -- and it needs to be fought against. That's what this story teaches us. It's a state where our mind begins to obsess with the injustice and the unfairness of things.

This king's name, Adoni-Zedek, means Lord of righteousness and because of his opposition to Israel, he represents the opposite of true righteousness. Therefore, he conveys the self-righteousness and feelings of indignation that come up for us when we feel that we have suffered an injustice. He is those things which arises in us with the aim 'to put things right' when our precious self-image takes a blow from being confronted with truths that call the false image that we carry of ourselves into question. Adoni-Zedek gathers to himself four other kings, and this represents how interconnected negative powers within the mind and those emotions that we feel are brought out and able to be exposed to the scrutiny of the Word.

So we see from this story that when such feelings arise an opportunity is created for real work to be done. The key is to recognise that when we feel those feelings associated with being unfairly or unjustly treated, that what is offended and what feels that offense -- are the spiritual associations that are linked into the hells. These associations and the emotions they carry attempt to seduce us, to have us buy into what they offer. And so we move out of the safety of the Lord's ground and onto the ground of the Canaanitse and Amoritse. The proprium or the ego seeks only one thing and that is to capture us in negative emotions and negative forms of thinking. The Lord seeks to deliver us from these but if we want that deliverance, then we need to reflect on the quality of what passes through our mind, and we need to do it in a military kind of way. We need to do it knowing that we've got a fight on our hands.

So the work that arises from this story is to see, from truths, when we experience that our ego or our proprium is caught up obsessing with feelings of unfairness or injustice. Because if we can do that, then we will get a good sense of the states of Adoni-Zedekis within us. And there will be many opportunities for seeing this power within our life.
For not a day passes where some aspect of this king arises from out of our proprium as it fights to keep the self at the centre and pushes the Lord out.

But if we are able to see when these emotions arise, and to get space to truly look at them from what the Lord gives us in His Word, then possibilities open up for deliverance, for overcoming. It becomes possible to move away from being in a state of denial so that truths can shine their light on the real issues for us in terms of our spiritual growth and development. We will be able to call on Joshua as the Gibeonites did for the Word to come. It will march through the night, it will seem distant, but it will arrive, and it will deliver us from the powerful forces that seek to destroy the heavenly life being present for us.

  And the LORD said to Joshua, “Do not fear them, for I have delivered
  them into your hand; not a man of them shall stand before you.”
  Joshua therefore came upon them suddenly, having marched all night
  from Gilgal.

