
== THE HOLY CITY — Revelation 21:9-27

=== INTRO

In all classes above the Primary, a few minutes should be spent reviewing the Word as a whole. Some questions may also be asked, especially in the Junior class, but the review should be kept carefully within limits so that there will be time for the lesson proper, as it is very important for all the pupils to be impressed with the picture of the New Jerusalem as the culmination of the whole Bible story.

=== Doctrinal Points

Our "holy city" is built of the heavenly principles we choose to rule our thoughts, feelings, and actions.

The New Jerusalem pictures the ideal of life toward which each of us should be striving every day.

=== Notes for Parents

The Bible is one book, although it was written through many men over a period of more than fifteen hundred years. Its author is the Lord Himself and in it He tells us the story of His dealings with men from the time when He created them, showing us how in His love He followed them down as they departed from their first state of childlike trust and obedience, never leaving them without the knowledge they needed, and even — when they were about to destroy themselves — coming into the world Himself to fight their battles and show them the way to happiness.

We have seen that the final book of the Bible, given through the apostle John after the Lord's death and resurrection, is a prophecy, the revelation of what the further course of the world would be and also of what the result will inevitably be of the kind of life each of us chooses to live while we are in this world.

The greater part of the book of Revelation is concerned with the disastrous results of choosing to close our ears to the truth the Lord speaks to us in His Word. But the book does not end on this unhappy note. The last two chapters show us the wonderful happiness which is in store for all who will overcome selfishness and follow the Lord's guidance.

In our chapter for today the final state of the good is pictured in the beautiful vision of the "holy city, new Jerusalem, coming down from God out of heaven." We all know that we have an inner life as well as an outer life, that we may be very different in our secret thoughts and feelings from what we appear to other people to be. What we do not always realize is that our inner self is the really important one, not only because that is what will appear when we pass into the other world but also because it is the quality of our inner self which makes us happy or unhappy in this world. We all naturally like to blame our troubles on other people, but we know that people who have everything the world can give are often unhappy, and that many who have poverty and hardship to bear are nevertheless happy.

The "city" our souls live in is built of the principles which we have chosen to rule our thoughts and feelings. If we have chosen to learn and obey the Lord's truth, which He has given us in His Word, we live in the beautiful heavenly city described in our lesson. Its temple is the Lord and its light comes from Him, and every one of the truths of His Word is like a precious stone, beautiful with its own special brightness and color. The golden reed with which the city is measured is the Lord's own measuring stick of pure unselfish love, and our city is found to be "foursquare," sincere and just all through, rising toward the Lord higher and higher as our knowledge of Him and our love for serving Him — its breadth and length - increase. This is why the measure of the city is called "the measure of a man, that is, of the angel." It is a picture of the ideal life toward which each of us should be striving every day.

Let us keep this beautiful city always in mind. Its gates are open.

=== Primary

Little children love the very sound of this story as it is read to them from the Word, and it makes a much deeper impression than we realize. They should be taught to think of it as a picture of heaven and the heavenly life, and also to know and love the name of our church because it is named for this heavenly city. The children can also be given an idea of what the judgment really is. It is good to put in their minds the thought that the Lord always knows what they are feeling and thinking no matter how hard they try to cover it up, and that someday we shall have to appear openly as we really are. Read to them especially Revelation 21:16 and 17 and tell them that our ideal should be to "measure up" to the dimensions of this heavenly city.

You remember that the apostle John in his vision saw some very sad things, and that these were pictures of what happens in our hearts and minds when we do not want to learn from the Lord and to live as He wants us to live.

Most of the book of Revelation is a prophecy of the judgment. Judgment is just the uncovering of what we are really like in our hearts.

This comes when we die because we leave behind us in this world everything we have "put on" for show.

But the Lord showed John also the beautiful things that happen to people who love to listen to His Word and to obey Him. Our story today is one of these beautiful pictures.

John finally saw the holy city, which is a picture of heavenly life. How many gates did it have?

What were they made of?

What were written on the gates?

What were written on the twelve foundations?

What was the wall made of?

What were the city and its street made of?

What was the shape of the city?

What was the name of the city?

What is the name of our church?

Always remember that your church is named for the beautiful heavenly city. This is because it is in the church that we learn how to live heavenly lives like the angels in the beautiful city. See if you can remember the name, and try to be good. Then you may always live in the golden city.

=== Junior

Help the children to fix in their minds as many of the details of the vision as possible, with the understanding of what the city as a whole pictures, and tell them that every detail has a meaning which they will be able to learn in later years. The thought of what the "measure of a man" really is should be a helpful one to leave with them. If there is time, tie this in with the development of a man as pictured in the Creation story.

You remember that it was the opening of the seventh seal which began the different kinds of destruction, and that this was a picture of the fact that when we come face to face with the real truth, the bad things which we have allowed to work in our hearts and minds appear, together with the destruction they have caused. So when the seventh trumpet sounded, the very worst of people's selfish desires and thoughts appeared clearly and the evil were separated from the good and went away into hell, where selfishness reigns. Then the way was cleared for the good to see and enjoy the beautiful things prepared for them.

We finish our study of the Word with the beautiful vision of the descent of the "holy city, new Jerusalem," which is the ideal toward which all the Bible has been leading us. The people of Bible days, of course, thought of Jerusalem as the city which was their capital when they were a great nation, where the temple was built and all their worship centered. That earthly city with its temple was destroyed first by Nebuchadnezzar and again by the Romans in A.D. 70. But all through the centuries it has been clear to the Christian Church that in the Word Jerusalem is a symbol of something spiritual and eternal. Jerusalem means "place of peace," and we can think of it as the state of peace and happiness in which we can live if only we will learn the Lord's truth and try to live according to it. So it is a symbol of the church which is formed of those who love and serve the Lord both on earth and in heaven, and the New Jerusalem is a beautiful and fitting name for the church founded on the deeper truths which the Lord revealed when in His Second Coming He opened the Word. In John's vision it is because the seals were opened that everything could be put in order and the "holy city, new Jerusalem" could finally appear.

It is a beautiful vision and one which you will understand more and more as you grow older. But now you must try to get some of the details into your minds and have them to remember and think about.

Where was John taken to see the holy city?

How many gates did it have?

What were the gates made of?

What were written on them?

How many foundations did the wall have?

What were written on them?

What were the city and its street made of?

What were the foundations garnished with? 

What was the temple in the city?

Where did its light come from?

Who may not enter it?

Who may enter it?

Now let us think a little about Revelation 21:16-17. What do we mean when we say that a person is "on the square" or a "square shooter"? We mean that he is sincere and just, always honest and fair to other people, a person whose word can be trusted. And we often speak of a person's "measuring up" to certain standards. So it is said of the holy city that its measure is the "measure of a man, that is, of the angel." A good man — who is an angel or messenger of the Lord — will be square, which means that he will try to learn what is right and will wish to live according to all the truth he learns. And he will also have another equal dimension: that is height, a reaching up toward the Lord for goodness and wisdom and strength of character. This is how a person comes to be "written in the Lamb's book of life" and to be one of the dwellers in the holy city, new Jerusalem.

=== Intermediate

Draw as much of the correspondence as possible from the knowledge of the young people themselves. It is an excellent lesson in which to spur them to an effort to work out the interpretation. Present the holy city as the ideal toward which each of them is working as a member of the New Church.

The opening of the seventh seal and the sounding of the first six trumpets exposed the true states of the souls of the people of the first Christian Church who had been gathered into the spiritual world from the time of the Lord's resurrection to the time of His Second Coming. These people had all believed themselves to be in heaven in the meantime because they had found themselves still alive and had been allowed to go on much as they had in the world. Swedenborg calls this state "imaginary heavens." The beginning of the breaking up of this state is described in Revelation 6:14, where we read that after the sixth seal was opened, "the heaven departed as a scroll when it is rolled together."

With the sounding of the seventh trumpet the struggle began between the evil and the powers of heaven, in which the evil were finally brought into their true places in the hells. Then the good could be raised up out of the place where they had been kept in safety by the Lord, and they could be instructed in the deeper truths revealed by the Lord in His Second Coming and formed into the true Christian heaven, with which the new Christian Church to be formed on earth would be connected.

Our lesson today is about this new heaven and new church to which we may all hope to belong if we study the deeper truth revealed in the Word and try to live according to it. It is because the giving of this deeper understanding of truth is described in Revelation by the descent to earth of the holy city, new Jerusalem, that our church is named the "Church of the New Jerusalem" and is commonly called "The New Church."

The description of the holy city given in the verses assigned for our lesson today is a beautiful picture in the letter. It is still more beautiful when we understand the spiritual meaning of the details of the vision and think of them as qualities which are possessed by the New Church in heaven and by those who are true members of the New Church on earth. You already know enough correspondences to work out some of this meaning for yourselves. You know, for instance, that a city is the symbol of doctrine; so the New Church has its form from truth. But the city was "pure gold, like unto clear glass," and you know that gold corresponds to love. So you can understand Swedenborg's own words about it: "By 'the city,' or Jerusalem, is meant the Lord's New Church as to everything of it interiorly regarded, or within the wall. By 'gold' is signified the good of love from the Lord ... and 'like unto pure glass' signifies pellucid [transparent] from the Divine wisdom." The street of the city is also said to be "pure gold, as it were transparent glass." The street, where people walk, is the symbol of the way of life. If we truly belong to the New Church, we will walk in ways of loving service, directed by truth from the Lord.

The wall which bounds and protects the city is the letter of the Word. Its twelve gates are all the truths which introduce us to the understanding of what a good life is, and its twelve foundations are the great fundamental truths of Christianity. You have learned that the twelve tribes of Israel and the twelve apostles represent all goods and truths possible to us; so you can see why their names are written on the gates and foundations. The precious stones are the various truths of the Word as we come to see them one by one in all their clearness and beauty, as the Lord gives us light to appreciate them.

There were three gates on each side of the city, and it is said that they "shall not be shut at all by day." This is a picture of the fact that although every person in the world is different from every other, starting with a different endowment and a different environment, there is no one who does not have some knowledge of truth through which it is possible for him to find his way into the holy city, provided he is in the "daytime" state; that is, if he really wants truth from the Lord because he is eager to grow better all the time. If you think that in this case everyone will certainly find his way in eventually, read John 3:19 and then the last verse of our chapter. Everyone does not want to live in the light of the holy city, because it is the light that comes from the Lord only as we overcome selfishness and worship the Lord alone. This is what is meant by Revelation 21:22-23. We have already learned what it means to have the books of our lives compared with the book of life.

Another very important verse is Revelation 21:16. All through the Word length is used as a measure of love or goodness and breadth as a measure of the understanding of truth. Height represents "good and truth together in every degree," because it is by means of learning more and more truth and loving to do it that our souls reach up toward the Lord and that His spirit can come down to us. Now you can work out this verse for yourselves, and also see why the measure of the city is said to be "the measure of a man, that is, of the angel."

You may think of all the doctrine you have learned this year as part of the foundations and walls of the holy city. Those truths which you have understood clearly and welcomed into your thought and life are the bright precious stones, and if you keep on faithfully, the whole wall will someday appear to you to be made of "jasper," beautifully translucent.

=== Basic Correspondences

the city = doctrine
the street = the way of life
the wall = the sense of the letter of the Word
length = the measure of goodness
breadth = the measure of truth
height = good and truth together in every degree
the holy city, New Jerusalem = the New Church in heaven and on earth

=== Senior

Remind the Seniors of the fact that it is the ability to know and love the Lord which really distinguishes man from the animals, and tie this in with Revelation 21:16-17. Try to make the picture of the holy city an ideal which they may hold before them always as their ultimate goal, and stress the fact that without the truths given us by the Lord in His Second Coming, there can be no holy city in the individual or in the world.

Several chapters in the book of Revelation treat of the completion of the last judgment in the spiritual world, of the struggle of those in falsities and evils to maintain control, and of their defeat by the armies of the Lord and their final withdrawal to the hells whose delights they had chosen during their life on earth. So the spiritual world was reduced to order and the way opened for the descent of the holy city.

Swedenborg begins his interpretations of our chapter in the Apocalypse Revealed with this brief summary of its meaning: "In this chapter it treats of the state of heaven and the church after the Last Judgment; that after this, through the New Heaven, the New Church will exist on earth, which will worship the Lord alone (vers. 1-8). Its conjunction with the Lord (vers. 9, 10). The description of it as to intelligence from the Word (ver. 11); as to doctrine thence (vers. 12-21); and as to all its quality (vers. 22-26)." So the New Church is identified with the "holy city, new Jerusalem." We commonly speak of our church as the New Church, but we should always have in mind its full name and the source of that name. Never hesitate to use the full name when anyone asks you to what church you belong. If your hearer looks puzzled, say: "It is named for the holy city new Jerusalem, described in the twenty-first chapter of Revelation." This is often necessary because people today unfortunately do not know their Bibles as well as they should.

We can think of this holy city as the ideal according to which we, as New Churchmen, should be shaping our lives. In the first place it is pictured as a city, and we know that a city corresponds to doctrine. You do not belong to the New Church by merely in a vague way wanting to be good. Swedenborg tells us many times that good takes its quality from truth and that love has no power except through truth. So, although the city is pure gold — pure love - it is a city with foundations and walls and gates. And although it has twelve gates, three on each side, and so may be approached from various angles, and although its gates are always open, "There shall in no wise enter into it any thing that defileth, neither whatsoever worketh abomination, or maketh a lie: but they which are written in the Lamb's book of life." We have seen that the judgment on us as individuals is no more nor less than the comparison of the books of our lives, which we have written by our daily choices in this world, with the book of life, which is the Word of God.

The city is said to be of gold and its street of gold and the reed with which the angel measured it was of gold. Love from the Lord is the quality of the life of the New Church — the Lord alone is its temple and its light — the paths in which the true New Churchman walks are paths of loving service, and everything he thinks and does must submit to the measuring stick of unselfish love.

But all the other details of the description have to do with truth.

The wall which defines the limits of the city and which also protects it is the sense of the letter of the Word, and it is said to be of jasper, which is a translucent stone, because in the New Church truth from the internal sense shines through the letter. The names of the twelve tribes are written on the gates and those of the twelve apostles on the foundations because the gates represent introductory knowledges and the twelve tribes all the truths and goods of the church, while by the foundations are meant all things of Christian doctrine, and by the twelve apostles "all things of doctrine from the Word concerning the Lord and concerning a life according to His commandments." The many and varied precious stones which adorn the foundations are the particular truths of the letter of the Word lighted up by the Lord from within as we come to see and delight in them. Different truths in the Word have special appeal for different people. We must always remember this when we talk about the church to others, and be quick and sympathetic in recognizing what each one needs most and so is looking for. And the gates of the city were twelve pearls, "every several gate was of one pearl." The pearl is "the acknowledgment and knowledge of the Lord." Read John 10:9 and then Matthew 13:45-46. No one comes into the holy city except by the way of knowledge and acknowledgment of the Lord. We cannot climb up some other way, as the Lord tells us in John 10:1.

Of the city it is said that it is "foursquare" and that "the length and the breadth and the height of it are equal." This means that we must have as much truth as goodness and as much goodness as truth, and that both must be expressed in our lives from top to bottom — in will, thought, and act. We must not keep any part of our souls to ourselves, away from the direction and cleansing of the Lord's truth as it is given us through the Word. This is the "measure of a man, that is, of the angel." Angels and men alike must strive to live up to this heavenly ideal if they wish to dwell in the holy city, new Jerusalem.

=== Adult

Our lesson is more than a beautiful picture of an intangible heavenly vision. It is a searching and challenging statement of what we of the New Church may and should be and do. The teacher of the Adult class should be well versed in the details of the vision and their spiritual meaning and should make this lesson an especially thought—provoking and inspiring one. In preparation read, if possible, all of chapter 21 in the @AR , but at least read the full five—page summary at the beginning of the chapter.

The Word in its letter begins with the account of the stages by which a truly human being is created, and it ends with a picture of the ideal form which it is possible for him to attain if he remains faithful to the Lord through all the temptations which are permitted to come to him. This form is pictured as the "holy city, new Jerusalem, coming down from God out of heaven, prepared as a bride adorned for her husband." It is a beautiful picture in the letter, one which children love to hear read for the very sound of the words, which set their imaginations to work and form a basis in their minds for the influx of the Lord's enlightening spirit. If with the years we have lost our love for this picture, there is something radically wrong in our souls, for the Lord says, "Except ye be converted, and become as little children, ye shall not enter the kingdom of heaven."

We in the New Church should love this picture above others, because under divine providence we have been brought in contact with the revelation of its meaning given to the world by the Lord in His Second Coming. Our study now is centered on the details of the description of the holy city. It is a description of our church as it should be and of the soul of each individual one of us as it should be. In his brief summary of the contents of chapter 21 in the @AR Swedenborg says: "In this chapter it treats of the state of heaven and the church after the Last Judgment; that after this, through the New Heaven, the New Church will exist on the earth, which will worship the Lord alone (vers. 1-8). Its conjunction with the Lord (vers. 9, 10). The description of it as to intelligence from the Word (ver. 11); as to doctrine thence (vers. 12-21); and as to all its quality (vers. 22-26)."

Our church organization was founded by a group of men and women who had found in the doctrines revealed by the Lord in His Second Coming the answers to their spiritual questions and the true plan of heavenly living. They named their organization the "Church of the New Jerusalem" because its purpose was to make known these doctrines, which are the holy city, new Jerusalem. Throughout the Word a city is the symbol of doctrine. "A city that is set on a hill cannot be hid." The founders set their city on a hill and the church grew. Today we ask ourselves why our organization is not growing and we run about studying the methods of other churches and trying to copy them, soft—pedaling our doctrines for fear of seeming narrow and bigoted, trying to appear as much like everyone else as possible. We say, "After all, our organization is not the New Church — the New Church is coming down everywhere." If our organization is not the New Church, it has no excuse for existence, and it is the New Church exactly to the extent that we, its members, learn, live, and proclaim its doctrines. If we try to dodge this necessity, we are like ostriches, hiding our heads in the sand of current opinion. Because of our natural inheritance it is always easier to believe that if our intentions are good, what we do will be right without any effort on our part to study the truth which the Lord has given us. We really know better. We see all about us the disastrous effects of misguided good intentions. But we persist in believing that our own are different.

True, the holy city in John's vision is made of gold and its street is of gold. The essential quality of the New Church in heaven and on earth is the good of love — but it is the good of love from the Lord, not natural goodness — and its ways are ways of loving service to the Lord and the neighbor and the city has a wall "great and high" and the wall — of jasper — is the symbol of truth from the sense of the letter of the Word "pellucid" [transparent], as Swedenborg says, from the understanding of the spiritual sense. The wall protects the city but it also imposes limits. We remember that the word religion means literally a "tying back." We cannot give free rein to our natural ideas and inclinations and dwell within the holy city.

True again, the city has twelve gates, three on each side, and they are always open. The gates represent introductory truths. People are different. Each one has a different inheritance, a different background, different problems. We need to remember this in all our missionary efforts. One may approach the city from any one of several directions and find a gate — a particular truth — which attracts him and affords access. But an angel or messenger of the Lord stands at each gate and a particular quality — expressed by the name of one of the twelve tribes — is written on the gate. The interest in the particular truth must be accompanied by a genuine recognition of the Lord and desire to be taught by Him. Though the gates of the city are always open, "there shall in no wise enter into it any thing that defileth, neither whatsoever worketh abomination, or maketh a lie: but they which are written in the Lamb's book of life." We have seen that judgment consists in the comparison of the books of our lives, as we have written them by our day-to—day choices in this world, with the book of life, which is the Word. And we cannot pattern our lives on the Word without studying what the Word teaches.

The foundations of the wall represent great basic truths, and because the new permanent heavens are Christian heavens, the names of the twelve apostles are written on the foundations. Of the jasper wall Swedenborg says, "that all the Divine truth in the sense of the letter of the Word, with the men of that church, is translucent from the Divine truth in the spiritual sense." Unless we are willing to make the effort to study the spiritual sense by means of the writings, our wall is not of jasper. And the same is true of the precious stones which garnish the wall, of which Swedenborg says that "all things of the doctrine of the New Jerusalem taken from the sense of the letter of the Word, with those who are in it, will appear in the light according to reception." Each of us knows certain particular verses from the Word which have been lighted up for us by our doctrines so that we really treasure them as precious stones. The more we study the Word in the light of the writings the more of these beautiful, varied precious stones we have.

The angel measured the city with a golden reed — the measuring stick of love from the Lord — and it was found to be foursquare:

"The length and the breadth and the height of it are equal." In the Word length is the measure of love or goodness and breadth of truth, and height is the extent to which good and truth acting together govern all three planes of our lives from our outer conduct up through our thinking to our inmost will. The only way that the Lord's spirit can come down to us is as we form all the planes of our lives according to His Word.

This is the city which is "the measure of a man, that is, of the angel." We do not build the New Church. The Lord builds it in and through us as we deny ourselves and follow Him. The holy city, new Jerusalem, can descend to earth only as those who have been called to its service by the Lord are faithful and diligent stewards of the great riches entrusted to them. He says to each one of us, "Ye have not chosen me, but I have chosen you."

"Except the Lord build the house, they labor in vain that build it: except the Lord keep the city, the watchman waketh but in vain."

=== From the Writings of Swedenborg

@AR 914: "And the foundations of the wall of the city were adorned with every precious stone, signifies that all things of the doctrine of the New Jerusalem taken from the sense of the letter of the Word, with those who are therein, will appear in light according to reception. By 'the twelve foundations' are signified all things of doctrine (n. 902). By 'the wall' is signified the Word in the sense of the letter (n. 898). By 'the holy city Jerusalem' is signified the Lord's New Church (n. 879, 880). By 'precious stone' is signified the Word in the sense of the letter, pellucid (transparent) from its spiritual sense (n. 231, 540, 726, 911). And because this is according to reception, therefore it signifies that all things of doctrine from the Word with them, will appear in light according to reception ... Interior thought is in the light of heaven, and is called perception, and exterior thought is in the light of the world; and the understanding of every man is such that it can be elevated even into the light of heaven, and also is elevated, if from any delight he wishes to see truth."

=== Suggested Questions on the Lesson

Primary: What is our lesson for today about? the holy city

Junior: Where did the city come from? God, out of heaven

Primary: What was its name? New Jerusalem

Primary: What was it made of? gold

Primary: How many gates did it have? twelve

Junior: What names were written on them? tribes of Israel

Junior: What was the wall of the city made of? jasper

Primary: How many foundations did it have? twelve

Junior: What were written on the foundations? apostles

Intermediate: What were they garnished with? jewels

Primary: What was the street of the city made of? gold

Junior: What is said about the temple in the city? the Lord is the temple

Junior: Where did its light come from? the glory of God

Junior: Who could not enter the city? evil people

Intermediate: Who could enter it? those written in Lamb's book of life

Intermediate: What does it mean to be written in the Lamb's book of life? to have lived a good life

Primary: What did the angel measure the city with? gold rod or reed

Junior: What were its proportions found to be? "four square"

Junior: Why was its measure called "the measure of a man, that is, of the angel"? good person is "four square"

Intermediate: Why should we in the New Church especially love this vision? it pictures the ideal church

Intermediate: What is pictured by the fact that the city and its street were of pure gold, like clear glass? enables one to walk in loving ways, clearly understood

Senior: What should we say when people ask to what church we belong? Church of the New Jerusalem

Senior: What should we say if they appear to be puzzled by the name? see Revelation 21-22

