
=== Summary Outline of the Appendix

No. I. Proofs of the Symbolic Character of the Writings of the
Old Testament afforded by the Revelation of John

No. II. An Attempt to discriminate between the Books of Plenary Inspiration contained in the Bible, and those written by the Inspiration generally assigned to the whole

No. III.The Great Objects and Phenomena of the Mundane
System considered, as they are referred to in the Language of Prophecy, and of the Scriptures in general

No. IV. The Signification of the Clouds, when mentioned in Scripture, further Illustrated

No. V. Illustrations of the Jewish Character; evincing its Aptitude for a Dispensation consisting chiefly in External Rites

No. VI. Critical Examination of Jephthah's Vow

No. VII. Arguments for the Literal Interpretation of the first part of Genesis considered

No, VIII. Remarks on the Recent Volume of Bampton Lectures, by the late Rev. J. J. Conybeare, M.A. ; and on the Support which it affords to the main Principle of the present Work



