
=== Lecture 2 - The True Nature Of The Scriptures Explained


Design with which the Scriptures were given, and the Nature of their Composition, stated for proof.

* I. That the title, "the Word of God", and the Plenary Inspiration which that title implies, are claimed by the Scriptures.
** 1. By Moses and the Prophets for their respective Writings.
** 2. The claim allowed them, and their absolute Infallibility asserted, by the Lord Jesus Christ.
** 3. Their Plenary Inspiration insisted on by the Apostles.
** 4. And recognised, till lately, by the majority of Biblical Critics.
* II. Proofs, from rational and philosophical grounds, that a Composition which is really "the Word of God", must contain stores of wisdom in its bosom independently of any thing that appears on the surface.
* III. That the Composition received as the Word of God, continually assures us that it is inwardly replenished with such wisdom.
** 1. This intimated by the writers of the Old Testament:
** 2. Expressly declared by the Lord Jesus Christ;
** 3. And by his Apostles:
** 4. Generally believed by the Christian Church, 
*** (1.) for many ages, from the Apostles downwards, 
*** (2.) and still recognised by the best Interpreters.
* IV. But this great truth having been abused, that endeavours
have been made, during the last two or three Centuries, to restrict the meaning of the Scriptures to their Literal Sense alone. Admitted, that all Controversies are to be decided, and Points of Faith established, by the Literal Sense; But that the objection against a further sense would fall to the ground, could it be shewn, that the Scriptures are written throughout according to an immutable Law or Rule, a knowledge of which would, in explaining them, substitute certainty for conjecture, and cut off the sources of vague interpretation.


