
=== Lecture 1 - Introductory - Infidel Objections Stated


Prevalence of Infidel sentiments, and of an increasing tendency to think meanly of the Scriptures.

Their Plenary Inspiration generally relinquished.

Design of these Lectures stated.

* I. Necessity of Revelation.

* II. The character which _must_ belong to a Composition which has God for its Author.

Inquiry proposed: Do the books called the Holy Scriptures come up to this character?

Answered in the affirmative by the Lecturer, but the Proof reserved for the subsequent Lectures.

Answered in the negative by the Deist, on the alleged grounds, that the books in question contain some Statements which are contradictory to each other, some that are at variance with Science and Reason, and some which are repugnant to Morality; and that, beside these positive Objections, the greater part of them is occupied with Indifferent and Insignificant Matters.

Examples.

General Reply: That all such Objections arise from taking a merely Superficial View of the Scriptures, and from an Ignorance of their True Nature; and that they may be retorted, so as to assist in proving what the True Nature of the Scriptures is.

* III. Appeal to the Reader, on the ill consequences of Infidelity.




