
=== Lecture 4 - Proofs And Illustrations, Evincing That The Scriptures Are Written According To The Law Or Rule Developed Tn The Last Lecture

* I. Of the Style proper to a Divine Composition. Such a Style afforded by the Relation of Analogy between Natural Things and Spiritual, as explained in the last Lecture.
* II. That if the Scriptures are written by a Plenary Divine Inspiration, they must be composed in this Style. 
** 1. The Word of God must be governed by the same General Law as his Works; and this is the Law of the above Analogy.
*** (1.) That when the Divine Speech, or the Divine Word, which is the same thing as the Divine Truth, emanates from the bosom of Deity into the circumference of Creation, or into the world of Nature, it there clothes itself with Images taken from that world, and that it cannot otherwise be presented to Mankind:
*** (2.) But it thus is presented with a fulness which no other kind of Language could afford:
** 2. Variety of Phraseology in the different Inspired Penmen, not inconsistent with Verbal Inspiration.
** 3. The difference between Plenary and Personal Inspiration;and that the former is necessarily occasional, and not permanently attendant on certain Persons.
* III. That the Holy Scriptures are the Divine Truth thus brought into a natural form; and that therefore their Interior Meaning can only be understood by an application to them of the Law which governs the Relation between Natural Objects and Spiritual and Divine Essences.
* IV. Applicability of the Rule to the Prophecies of the Divine Word. The View proposed supplies exactly what, in other Systems, was felt to be wanting.
** 1. Sentiments of Biblical Critics on the Double Sense of Prophecy. Necessity of making the System uniform.
** 2. Rule of Analogical Interpretation adopted by Sir Isaac Newton and Bishop Warburton.
** 3. Defects of their Rule, and the necessity of extending it further. 
* V. Examples of the Light which results from the application of the Rule of Analogy between Natural Things and Spiritual to the Prophecies.
** 1. Ezekiel's Prophecy of a great Sacrifice upon the mountains of Israel. (Ezek xxxix. 17 to 20.)
*** (1.) General Remarks on the Class of Prophecies which can be intended for Spiritual Fulfilment only.
*** (2.) Evidence that this Prediction belongs to that Class.
*** (3.) General Signification of Judea and the surrounding Countries.
*** (4.) The Spiritual Analogy of the relations of Place deduced.
*** (5.) The Signification of the Land of Gog and Magog as resulting from this Analogy, and of an Invasion thence of the Land of Judea.
*** (6.) The light thrown by this Prophecy upon that portion of the
Prophetic Word which treats in its Letter of particular Countries and Nations.
*** (7.) The Import, in the Language of Analogy, of the Address to the Fowls and Beasts.
** 2. The Lord's Prophecy of his Second Coming in the Clouds of heaven, (Matt. xxiv. 29, 30.)
*** (1.) The former part of this Chapter a remarkable instance of that Class of Prophecies which admits a Literal Fulfilment: yet the Spiritual Fulfilment the principal thing intended.
*** (2.) The impossibility of connecting the former part of the Prophecy with the latter by the Literal Sense alone, and the Inconsistencies incurred by Commentators in the attempt.
*** (3.) Inquiry instituted into the specific Signification of the Coming of the Son of man in the Clouds.
*** (4.) The terms must have a determinate meaning. 
*** (5.) The Import of the phrase, "Son of man", as used in Scripture.
*** (6.) The Ground of that Import in Analogy.
*** (7.) Signification of the Clouds, when mentioned in Scripture; with the Analogical Reason for it.
*** (8.) The meaning of the Prophecy thus rendered evident.
** 3. John's Vision of Spiritual Babylon, (Rev. xvii. 3 to 6.)
*** (1.) Signification of Babylon in Scripture, as discoverable from the circumstances predicated respecting it:
*** (2.) Of the circumstances predicated by Babylon personified. 
--  Conclusion: That the Prophetic Parts of Scripture are composed in the Divine Style of Writing, and that, thus far, the claims of the Scriptures to Plenary Divine Inspiration are established.

