
=== Lecture 3 - The Law Or Rule Explained According To Which The Scriptures Are Written

Preliminary Remark, on the Reasons why the Scriptures are not written in plainer Language. Short Recapitulation.

* I. A Universal Rule of Interpretation afforded in the Mutual Relation, which exists by creation, between things Natural or Material, Spiritual or Moral, and Divine. 
* II. The 
** 1. The whole Universe an Outbirth from the Deity, whence it bears, in all its parts, an immutable relation to the attributes which belong to the Divine Essence. Nature of this Relation considered.
** 2. That on all things belonging to the Moral, Intellectual, and Spiritual Worlds, the Divine Creator has thus first stamped a certain Image of himself.
** 3. And that he has done the same, though under a totally different form, on all the objects of Outward and Material Nature:
*** (1.) In the chief organs and parts of the Human Frame, and in the arrangement of Pairs observable through all Nature: 
*** (2.) In the imitation of the Human Form which reigns throughout the Animal Kingdom, and, by Analogous Parts and Functions, in the Vegetable and Mineral Kingdoms also: 
*** (3.) In what may be called the Moral Qualities of Animals: 
*** (4.) Digression on the origin of Malignant Qualities in Animals and the other productions of Nature.
*** (5.) The subject resumed, and instanced in the Essential Properties of Vegetables and Minerals.
** 4. Thus that all things in Nature, being Outward Productions from Inward Essences, are Natural, Sensible, and Material Types of Moral, Intellectual, and Spiritual Antitypes, and, finally, of their Prototypes in God.
* III. That, weie the Relation between these different orders of Existences fully understood, a Style of Writing might be constructed, in which, while none but Natural Images were used, purely Intellectual Ideas should be most fully expressed. --  
** 1. That this is in a great measure intuitively perceived by all
Mankind.
*** (1.) Hence our conclusions from the Expression of the Countenance to the Emotions of the Mind.
*** (2.) And hence the origin of many Forms of Speech in common use.
*** (3.) If such a relation of Analogy between Moral or Spiritual and Material or Natural Objects exists in a great number of cases, it must be universal.
** 2. Palpable Instances of the occurrence of such Forms of Speech in the Holy Word.
* IV. That in ancient times this constant Relation between things Natural, Moral or Spiritual, and Divine, was extensively understood.
** 1. Proved from intimations in the Historical Parts of Scripture.
** 2. Confirmatory remarks, drawn from the Mythological Fables of the Greeks and Asiatics, and the Hieroglyphics of Egypt? some of which are explained.
* V. That in this Relation, then, is to be found the Law or Rule according to which the Scriptures are written, and that a knowledge of it will afford the Key by which their "dark sayings" must be deciphered. 
--  Conclusion: That the Doctrine of Analogies is not liable to the reproach either of Fancifulness or of Novelty, and is worthy the attention of every friend of Revelation and Piety, and of Reason and Knowledge.

