
== THE ARK OF THE COVENANT — Exodus 25:1-22

=== INTRO

It is important that certain major events be mentioned briefly, because they prepared the minds of the Israelites to receive willingly the long series of instructions and laws which were given to them at Sinai. Note especially two things: they came to Sinai early in their journey — the third month — and during their eleven month stay there they were formed into an organized nation with a government which lasted them throughout their history and still to some extent persists with some Jews of the present day. Also call attention to the fact that the materials for the tabernacle and its furnishings were free offerings of all the people, and remind them of where they got those materials (Exodus 12:35-36). Some commentators have ridiculed the idea that the tabernacle was actually so fine a production, calling the Israelites a nomadic people who could not possibly have possessed the materials required or been capable of receiving so complex a system of laws. It is hard to see how they could forget that the Israelites had not been nomads for several hundred years and that Moses had been brought up as a member of the royal household, to say nothing of the plain statement as to the source of their material wealth.

=== Doctrinal Points

Worship of the Lord lies at the heart of everything we do. A study of the spiritual sense of the laws given at Sinai shows us how practical and important every detail of the letter of the Word is for us.

The plan of the tabernacle is the blueprint for a heavenly character. The commandments must be written in our hearts — not just in our minds.

=== Notes for Parents

You have read the stories of the remarkable experiences the children of Israel had during their first two months in the wilderness. Through these experiences they were shown that the Lord was really with them, and they must have begun to realize that they had a special mission to perform, since they were so miraculously protected and provided for. For various reasons, the Lord had chosen them as the nation through whom the Word could best be written in order that it might reach men in all stages of spiritual development. They were a very literal—minded people and very much interested in their own prosperity. Through fear of punishment and hope of reward they could be led to carry out all the elaborate rituals and to observe all the detailed laws which the Lord wanted recorded in His Word. In their letter these laws were for their nation, which was to be a "theocracy," a nation governed by religious laws; but every one of the directions given to them has an inner meaning which applies to the spiritual life of every one of us, even though most of the outward rules are no longer necessary to our life. Even the ten commandments, which - unlike some of the other laws — will never be out—of—date in their letter, have also deep meanings within them, and the further we go in our efforts to lead a good life the more we see and keep of this inner meaning.

The Lord gave the nation their laws while they were camped on the plain at the foot of Mount Sinai. Moses was called up into the mountain to receive them. The most important of them, aside from the ten commandments, were the directions for the construction, furnishing, and care of the tabernacle, their tent of worship. And the most important article of furniture in the tabernacle was the ark, in which the two tables of stone inscribed with the ten commandments were to be kept. Several times in the Bible we read that the commandments are to be written on our hearts. This means that if we keep them faithfully, we shall in time come to love to keep them. The state of loving to keep the commandments is heaven. We can easily see this if we think what a wonderful place the world would be if none of us ever wanted to hurt anyone else in any way. There would be no poverty, no hunger, no crime, no war. We know that the world is not like that now. What we do not always realize is that each one of us could help to bring heaven on earth by trying to feel and think and act every day in the spirit of love to the Lord and the neighbor. This is what we mean when we say in the Lord's Prayer, "Thy kingdom come, thy will be done, on earth as it is in heaven."

=== Primary

The description of the ark and its contents will make a sufficient lesson for this class. Read the story from the Word. Emphasize the importance of the commandments and their place in the tabernacle. These children can get the idea of the meaning of the ark and its position in our lives. They should be able to describe the ark in detail.

This is another story about Moses and what happened when he was leading his people from Egypt to the Holy Land. Do you remember about how the Lord spoke to Moses out of the burning bush? That was at a place near some mountains called Horeb. One of these mountains was Mount Sinai. Try to remember this name because you will hear it many times. The Lord had promised Moses at the burning bush that after they escaped from Egypt they would worship the Lord at this same place.

After three months they came to a great mountain called Mount Sinai, near the place where the Lord had talked with Moses from the burning bush. They camped in the plain at the foot of this mountain.

From the top of the mountain the Lord spoke to them the ten commandments.

You will learn these commandments someday. They are the Lord's laws, which we must obey if we want to be safe and happy.

Then He called Moses to go up into the mountain and gave him many laws to govern the people.

And He told him how to build and furnish a tabernacle in which they were to worship.

The thing of most importance in the tabernacle was the ark, a box or chest in which they were to keep the two tables of stone on which the Lord had written the commandments after He spoke them.

What was the ark to be made of?

With what was it overlaid?

How was it to be carried?

What was on top of the ark?

After the ark was finished and the two tables of stone put into it, it was placed in the inmost room of the tabernacle, which was called the Holy of Holies. After that the Lord always spoke to Moses and Aaron from between the cherubim on the ark.

=== Junior

The plan and furnishings of the tabernacle should be reviewed with this class before taking up the ark and its meaning. See if any of the children can repeat any of the commandments. This is the time to begin to memorize them, and the teacher should have this project in mind and talk over with the superintendent some plan for carrying it out — perhaps call for one commandment a week and offer a suitable reward for the final ability to repeat all ten perfectly.

In the third month the Israelites came to Sinai, and they stayed there about eleven months. The ten commandments were given by the Lord from the top of Mount Sinai. They are found in chapter 20 of Exodus. If you haven't already memorized them, you should begin now and see how soon you can learn them all, for they are our directions for a good life. We cannot break any of the commandments without suffering for it and bringing suffering on other people, too. The laws of every nation in the world are founded on the ten commandments, for they were made known to people from the very beginning of the human race. The Israelites knew them in a general way; but they, as well as everybody else, had forgotten that they were laws of God and not just man-made laws.

In addition to the commandments, the Lord gave the people many other laws about all sorts of things in their lives. There are many of them in these chapters of Exodus, and the Book of Leviticus is full of them. We should know that, although most of them in their letter applied only to the ancient Hebrews, in their inner meaning every one of them applies to us. They are a wonderful study, but we have not time to take them up in Sunday school.

Along with the laws, the Lord gave the people through Moses directions for making and furnishing their place of worship. This was a tent, or tabernacle, which could be taken down and carried with them wherever they went. When they stopped, it was immediately set up in the middle of the camp. You are old enough to understand that this means that our worship of the Lord is to be at the very center of our lives and is to be taken with us wherever we go. Later we shall study the tabernacle and its furnishings, but in this lesson we are thinking especially of its most important piece of furniture, the ark of the covenant. You remember that an ark is a box or chest made to keep something safely.

What ark have we studied about?

There is another ark in the story of Moses. What was it? The ark in our lesson today was not like either of these. Of what was the ark of the covenant made?

Acacia wood is from a thorny desert tree.

How big was the ark?

A cubit is the length from a man's elbow to the tips of his fingers, about one and a half feet.

With what was the wood of the ark overlaid? 

How was the ark to be carried?

What was to be placed on top of the ark?

The mercy seat was a covering the same length and width as the ark. The two cherubim on the mercy seat were symbolic figures, and they are usually thought of as angel figures. No one knows just what these figures on the ark were really like. How do you suppose the Israelites knew how to make them? Read Exodus 31:1-7.

What was to be kept in the ark?

The "testimony," or covenant, means the two tables of stone on which the ten commandments were written.

In verse 22 we read that the Lord promised to speak with the high priest from between the two cherubim on the mercy seat, and this happened many times afterward. Whenever Moses and Aaron were in doubt about what they should do, they consulted the Lord in front of the ark and received His answers. The ark was the only article of furniture that was in the inmost room or Holy of Holies of the tabernacle. The Holy of Holies pictures our hearts, and this means that the commandments should be "written in our hearts" or obeyed from love to the Lord and the neighbor. Read Psalm 37:31; 40:8; and Isaiah 51:7.

We should note one other point in our lesson. How was Moses told to get the materials for the tabernacle? Do you remember where the people got these things?

=== Intermediate

The correspondence of the details of the ark and the reason for its position in the tabernacle are the proper lessons for this class.

In the third month the people came to Sinai. We remember this as part of the range called Horeb near which Moses received his call at the burning bush. Sinai was a rugged mountain rising steeply from the plain. The people were told to camp in the plain and not come near the mount. Moses was called up into the mountain to receive from the Lord laws and directions which were to govern the people not only throughout their journey to the Holy Land, but always. Even today orthodox Jews observe many of them. Many of these laws (not, of course, the ten commandments) are not meant for us to obey in their letter, but in their inner meaning they apply to us and to all people at all times. When you are older, you will want to study some of them, and you will sometimes hear sermons preached on one or another of them. They go very deep into our experience and teach us a great deal.

You know, of course, that the ten commandments were given from Mount Sinai. This was not because people had never known them before. Men had been told them from the very beginning, and all people have them as the basis of their law. But people had forgotten — as people today sometimes forget — that they are laws of God and cannot be broken without causing suffering. So the giving of them from Sinai was recorded in the Word so that we might always remember their source and importance.

The commandments were first spoken by the voice of the Lord from the top of the mountain, all the people hearing them — the only time when all the people heard the Lord speak. Then Moses was called up into the top of the mountain and the Lord wrote them on two tables of stone. When Moses brought the two tables down, he found that the people had already gone back to idolatry, and he broke the tables in his anger. Then the Lord told him to cut two more tables from stone at the foot of the mount and bring them up, and the same commandments were written again. The two tables from the foot of the mount were the ones which were placed in the ark and which traveled with the Israelites wherever they went. They were the holiest thing they possessed.

Among the things which the Lord gave Moses on the mount were directions for the construction and furnishing of the tabernacle, or tent, in which they were to worship throughout their journey. It was so constructed that it could be taken down and carried with them; and very careful instructions were given for its care, including directions as to which tribes should march in front of it, and which after it, and just how the tribes were to be arranged around it when they camped. It was to be the center of their camp and the center of their marching line. It is easy to see that this means that our worship is to be the center of our life whatever we do and wherever we go.

The first and most important article of furniture to be made for the tabernacle was the ark in which the two tables of stone inscribed with the ten commandments were to be kept. The ark was to be the only article of furniture in the Holy of Holies, or inmost room of the tabernacle. Our lesson tells us that it was a chest made of acacia wood overlaid with pure gold inside and out. The three divisions of the tabernacle represent the three planes of our lives on which we should serve the Lord: our hearts or wills, our minds, and our outward lives. The Holy of Holies pictures the heart. Several times in the Word we read that the commandments should be in the heart (Psalm 37:31; 40:8, and Isaiah 51:7). This means that we should love them and cherish them as the center of our life, and the ark is a picture of the way in which we make a place for them there. Acacia wood, Swedenborg tells us, represents "the good of righteousness," which is the good which we develop in our lives when we obey the Lord because we see that all good comes from Him. The gold with which it was overlaid is pure, unselfish love. This, too, comes into our hearts from the Lord as we form the habit of obedience in a spirit of humility. The golden mercy seat, or covering, on top of the ark pictures the cleansing from sins which follows our obedience, and the golden cherubs picture the Lord's providence protecting us against taking credit to ourselves for our obedience and goodness.

The last verse of our lesson tells us that the Lord promised to meet with the children of Israel and to commune with them "from above the mercy seat, and from between the cherubims." When we have a decision to make in our lives, how do we find out what the Lord wants us to do? First we think of the commandments and ask ourselves, "Is there anything in the ways I might choose which is contrary to the commandments?" If there is, our decision is easy. But suppose all possibilities square with the commandments; then we must ask, "Which one will do the most good to others?" And when we ask this, we are led to make the right decision. If we hold the commandments in our hearts and try to live from the principle of service to the Lord and the neighbor, being grateful to the Lord for everything we can do and not proud of ourselves, we may be sure that the Lord will form in us a heavenly character.

The ark of the covenant had a long history. The Israelites carried it faithfully all through their forty years in the wilderness and set it up in the tabernacle when they reached their homes in the Holy Land. Then, because they had reached their goal and were prosperous, they neglected it. Once they even tried to use it selfishly as a sort of good—luck piece, and they lost it for a while. It was finally carried to Jerusalem by David, and when Solomon built the temple, the ark was placed in the inmost chamber there. But after the temple was destroyed and the people were carried captive to Babylon, there is no further mention of the ark. Many stories have been written about its later history, but they are purely imaginary.

=== Basic Correspondences

acacia wood = the good of righteousness
cherubim [cherubs] = the Lord's providence protecting us from profaning holy things

=== Senior

Perhaps the most important lesson for the Seniors is the fact that the ten commandments are binding upon all men for all time and are the only basis for the development of a heavenly character. There is so much attempt in the world today to compromise with the commandments that young people should be led to realize that they cannot be broken with impunity now or at any time.

It may be helpful to us to look for a moment at the wilderness journey as a whole. It lasted in all about forty years. This seems a long time for a short journey, and a later lesson will tell us why it was prolonged. But most of its outstanding events were crowded into the first year, and all but the first two months of this year were spent at Sinai. What does this picture in our lives? We have said that the wilderness journey represents the period in which we are trying to bring our outward lives into order. Most of us are brought up in orderly homes and are taught what is right and wrong, and made to form good habits. But often when we leave home for work or college, we shed some of these habits and experiment with things we have been forbidden to do at home. We want to see what it is like to "do as others do." It is not until we have seen the dangers and unhappiness of this worldly life that we break away from Egypt and start back to the Holy Land. Our journey, like that of the Israelites, follows certain stages. There is the first real temptation (crossing the Red Sea); there is the period of discouragement when we do not find immediate satisfaction in the new life (the experience at Marah); the glimpse of a new kind of happiness (the rest at Elim). Then in the Bible story follow the giving of the quails and manna (the realization that the Lord does actually give us enough goodness to meet each day as it comes, if we are faithful); the bringing of water out of the rock at Rephidim (picturing our ability, with the Lord's help, to find satisfying truth even in the hard facts of life); the battle with Amalek (the overcoming of discouragement); and finally the arrival at Sinai "in the third month." We all have these experiences when we set out to correct our lives and bring them back into order.

Up to the time of their arrival at Sinai, the people had been a mere unorganized horde under Moses' leadership, following the pillar of cloud and fire. We fumble along in the same way at first. We are on our way and it is not altogether true that we don't know where we are going, but we haven't developed any very clear plan of action. After a few experiences, however, we know that the Lord really is helping us, and we sit down to think things through and organize our life. This is just what happened to the children of Israel at Sinai. They stayed there eleven months, and in that time — through the laws and statutes given to them by the Lord from the mount, they were organized into a nation. The twelve tribes were told their proper relation to each other; leaders were chosen not only for each tribe, but for the various divisions within the tribes; rules were laid down for the conduct of all their daily affairs; punishments were named for infractions of the laws; and, above all, the commandments were given and full instructions for maintaining worship. As we read the chapters concerning this stay at Sinai, and the book of Leviticus in which most of the laws are gathered together, it may seem that they received just a long series of minute directions, some of them quite strange and some hard for us today to understand. It is not surprising that without a knowledge of the internal sense of these laws, men have often decided they were not worth reading and completely out—of—date. But we know — and it takes only a little study of the internal sense to illustrate — that each one has an important meaning and application for us and for men and women of all times, and that they all bear relation to one another and, taken together, give us a complete blueprint for orderly living. Today blueprints are very important in engineering, architecture, city planning, and many other fields. It may help us to think of these laws given at Sinai as our blueprint for a good life: we may at first see only its general outlines, but as we begin to build, we find that each little detail is very necessary to the whole.

Today we are thinking of one detail: the ark. It was a chest approximately four feet long, two feet high, and two feet wide, made of acacia wood overlaid within and without with pure gold, and with a crown or edge of gold around the top, and upon it the golden mercy seat, or cover, on which stood the two golden cherubim, usually thought of as angel figures, with their wings meeting above the ark. In the box were kept the two tables of stone on which the ten commandments had been inscribed, and it was to be the only piece of furniture in the Holy of Holies or inmost room of the tabernacle. It was thus the central point of the whole religious organization, for the tabernacle was to be set up in the midst of the camp wherever they stopped, carried at the center of their line of march, and set up in the center of the Holy Land when they arrived there. The people recognized it as the Lord's presence with them and as their most important possession.

We think of the tabernacle as embodying all our thought about worship. Swedenborg says it represents heaven and that every good man or woman is a heaven in the least form. There would be no heaven anywhere if there were not heavenly men and women. And the thing that makes a man or woman heavenly is the Lord's presence in the life. This presence is given as we put selfishness away and learn and obey the Lord's laws from the desire to serve Him. The Holy of Holies of the tabernacle represents our hearts, and that is where we should keep the commandments, obeying the Lord from love. Acacia wood represents righteousness; the gold with which it was covered, love; the mercy seat, the cleansing of our evils as we hear and receive the Lord's Word from love; and the cherubim, the Lord's providence which constantly protects us against the evil of ascribing our goodness to ourselves. We all know how easy it is to fall into that evil and how much we need this protection. Whenever we catch ourselves counting up our accomplishments and our good deeds, and thinking we are better than someone else, we know the Lord is speaking a warning to us from between the cherubim. Obedience to the commandments from love to the Lord and the neighbor is the center of a heavenly life.

=== Adult

There are many important discussion topics in this lesson: the importance of the commandments, the different motives for obedience to them, the necessity for humility, the persistence of our selfish inheritance, the way in which divine providence protects us from ourselves, the time element in the journey and its relation to our experience.

As a background for this lesson, recall the stories of the giving of quails and manna, the bringing of water out of a rock at Rephidim, and the battle with Amalek, in which Joshua led the army and Moses went up to the top of the mountain and Aaron and Hur held up his hands to the Lord. We need to have them in mind, for the experiences confirmed in the children of Israel the certainty that the Lord was able and willing to provide for them and to give them victory over their enemies. They all belong, in their spiritual sense, to the very beginning of the period of reformation, for we are told in chapter 19 that the people came to Sinai in the third month. Their first experiences were the necessary preparation for their reception of the laws and instructions to be given at Sinai.

Another preparation is found in the story of the visit of Jethro to Moses (chapter 18). Jethro the Midianite, the father-in-law of Moses, represents a simple, childlike state of worship. Yet Jethro was very wise, as good children are often wiser than grown—ups. He found Moses overburdened with the tasks he had assumed in his leadership of the people, sitting all day hearing complaints and settling differences. Are we not likely, in the early stages of our journey heavenward, to think that we must stop to look into each little thought and act, and to become bogged down in the complexities of our nature? Jethro's advice to Moses was that wise judges be chosen from the tribes to hear and decide the ordinary cases, and that only the really difficult matters should be brought to Moses. We should set up principles in our lives to govern us in the small affairs of daily life, and put our real thought upon our deeper problems.

We all know the story of the giving of the commandments from Sinai and that, in addition to the commandments, the many detailed laws recorded in Exodus and especially in Leviticus were given during the eleven months in which the people were camped on the plain at the foot of Mount Sinai. In fact, the whole system of laws by which the Israelites were to be governed throughout their history as a representative nation was given there. When they studied and obeyed these laws, they prospered; when they neglected to study them and disobeyed them, disasters came upon them. Their most pressing motive in keeping them was apparently the desire for worldly prosperity, not unlike the way a child often tries to do things he thinks will please adults without understanding any deeper reasons for his actions. In their letter the minor laws were for the people of that day, instructions by which the chosen judges might be guided in their decisions. They were abrogated — in their letter — when that era came to its end. But we know that in their inner meaning every one of them is a directive to us and can help us in setting our lives in order and keeping them in order. And the ten commandments, for which Moses himself stands in the story, are both in their letter and in their spiritual meaning divine laws for all people for all time.

Next to the commandments the instructions for making and furnishing the tabernacle and for its use are the most important. As the tabernacle was the center of the nation's worship, we think of it as representative of worship in our lives — primarily a place, but a state of life, a state so ordered that the love and wisdom of the Lord can be received. The three divisions of the tabernacle represent the three planes of our lives: will, thought, and act. The furnishings of each division picture the essential things which must be in these divisions if the life is to be heavenly.

We are concerned today with the ark. We know that each of us is kept alive from moment to moment by the influx of the Lord's life into the inmost of our being. This inmost presence of the Lord in our lives is pictured by the ark. Swedenborg says it represents the "inmost heaven." It was made of acacia wood, which pictures "the good of merit" which is in the Lord alone. It was overlaid within and without with pure gold, picturing the Lord's unselfish love. Its crown of pure gold and the golden rings by which it was carried are the encircling and support of the heavenly life by the Lord's love. The mercy seat — or, as Swedenborg renders it, the "propitiatorium" — is our cleansing from evil by the reception of that love. The golden cherubim picture divine providence protecting the good person from profaning that which he receives by attributing it to himself.

Swedenborg tells us many times that "the Divine of the Lord makes heaven." That is, no one can come into a heavenly state except as he puts self aside and so opens the way for the influx of the Lord's unselfish love. Obedience to the commandments is the essential at the heart of the heavenly life, but this heavenly life is not our first obedience through a sense of fear of consequences or the desire to be thought good; nor is it the second obedience from a sense of duty. It is obedience practiced until it has become willing and joyous, until it is so covered by our sense of the Lord's goodness and mercy that our natural self-righteousness disappears. The wood of the ark, the gold which overlaid it, and the golden crown around the top edge all picture the willing acknowledgment that all goodness and truth are the Lord's and not our own. The translation "mercy seat" was probably suggested by the fact that the Lord was to speak to Moses from between the cherubim, but it is not an accurate one. The Hebrew word is 'koppar', meaning merely a "covering," although the word "propitiatory" and the connotations of the Hebrew root indicate that it suggests the covering of our evils by divine mercy. The root is the same which comes out in "Yom Kippur," the day of atonement. We are told that even angels, when from time to time they begin to lose their lively consciousness that they have no real life except from the Lord, are "let down" into their own states briefly until they realize again what is their own and what is the Lord's in them. So the mercy seat or propitiatory pictures exactly the way in which the Lord in His mercy hides our evils from our sight and so cleanses us when we have learned to obey the commandments from love.

Cherubim are frequently mentioned in the Word. They are symbolic figures representing the care and protection which divine providence exercises over us, especially protection against "profaning" the truth and good which we have accepted. Genesis records that when Adam and Eve were driven out of the Garden of Eden, the Lord placed cherubim at the entrance to prevent their return; this means that when self-love began to occupy the human heart, the Lord closed the inner way of communication with heaven which had been open in the first people so that this "perception" should not be used for selfish ends. We are also told that whenever the Lord sees that we are no longer willing to live according to a given truth which we have previously acknowledged, He takes from us the belief that it is the truth. Swedenborg says that in this way one may gradually kill his conscience. This by no means leads toward heaven; it merely prevents one from going deeper into hell. Read here verses 23 through 31 of the thirty-seventh Psalm. These words express very beautifully the state of the "good" person, who has set up the tabernacle in the midst of his life and the ark in the Holy of Holies of the tabernacle. "The law of his God is in his heart; none of his steps shall slide."

=== From the Writings of Swedenborg

@AC 9509: "And thou shalt make two cherubs. That this signifies no admission and approach to the Lord except through the good of love, is evident from the signification of 'cherubs,' as being guard and providence lest the Lord should be approached except through the good of love.

As this was signified by the 'cherubs,' they were placed over the propitiatory* that was upon the ark, and therefore they were made of solid gold; for by the 'ark' is signified heaven where the Lord is, and by 'gold,' the good of love. That there is no approach to the Lord except through the good of love, is because love is spiritual conjunction, and all good is of love. Therefore those who are in the good of love to the Lord are brought in to Him in heaven, because they are conjoined with Him, and so are those who are in the good of love toward the neighbor."

[*translated "mercy seat" in the King James Version. (Both the Vulgate and Schmidius [Latin] use "propitiatory." The New American Version, following the Vulgate, is the only English edition I am aware of which uses "propitiatory." -Editor]

=== Suggested Questions on the Lesson

Primary: What did the Lord give all the people from the mountain top? ten commandments

Junior: What else did He tell Moses? many minor laws

Primary: What was their place of worship to be? tabernacle (tent)

Junior: What was the inmost room called? Holy of Holies

Primary: What piece of furniture was in it? ark of covenant

Primary: What was the ark to be made of? acacia wood

Primary: What was on top of the ark? cover (mercy seat, propitiatory)

Primary: What was inside of it? two stone tablets (commandments)

Junior: How did the Lord tell Moses He would use the ark? to speak to them

Intermediate: What does the ark represent? our inner being, where the Lord can speak to us

Senior: What does the "mercy seat" represent? our cleansing from evil 

Senior: What does Swedenborg call the mercy seat? propitiatory

Senior: What are pictured by the cherubim? protection of divine providence

Intermediate. Why does the ark represent heaven? heaven must be in our "hearts"

