
=== LECTURE VI. - THE WHOLE FABRIC OF INFIDEL OBJECTIONS SHEWN TO BE WITHOUT FOUNDATION

----
I. General View of the System and Arguments of the preceding Lectures; Important additional Testimony.
II. The four classes of Infidel Objections stated in the first Lecture resumed, and examined by the view which has been developed of the nature of the Holy Word, and of the means of decyphering its true signification.
1. Imputed Inconsistencies with Reason and Science considered: Style of Writing in the first part of the book of Genesis.
2. Imputed Contradictions considered: Why four Gospels were written. 
3. Imputed Violations of Morality considered: David not a pattern, but a type.
4. Imputed Insignificance considered. 
General Reply confirmed: -- That all such Objections arise from taking a merely superficial view of the Sacred Scriptures, and from an utter Ignorance of their true Nature.
III. Address to Christians, on the Necessity of taking higher ground in their Controversy with Deists.
IV. Address to Deists, on the internal causes of Scepticism.
Conclusion.
----

It has been the object of our preceding Lectures to shew, that the Holy Scriptures are written according to the laws of the Analogy or Mutual Relation established by creation between things natural and spiritual; that they thus contain a spiritual sense distinct from the literal expression, which they could not convey, in an orderly series, unless they were divinely inspired throughout; that there is ample evidence that they are thus written, and of course that they are divinely inspired; and thus that they are, what they profess to be, the Word of God.

I. The line of argument by which we arrive at this conclusion has consisted of four stages, which, now that we are about to close the whole discussion, we will state in one view.

1. We have seen, in the first place, in our first Lecture, that a
Eevelation which is indeed from God, must contain, in every part of it, the treasures of infinite Wisdom. But we have seen also,
that this wisdom does not every where appear in the Scriptures on the face of the letter; -- so far from it, that infidels have deduced from the appearances of the letter, and in ignorance of their containing any thing further, various plausible arguments for denying them to have proceeded from any superior intelligence.

But the fair inference from those appearances is, not that they are _not_ divinely inspired, but that, _if they are_, they must contain that superior wisdom which is the criterion of inspiration, in an interior sense distinct from the literal expression.
This the deistical objections appear to me decidedly to prove; -- that if the Scriptures actually do not contain any thing beyond what appears on the surface, they are not the Word of God; 
but they by no means prove the negation which they aim at, -- that they are not the Word of God; --  
they only prove, that, to be such, they must contain more than appears on the surface, -- that they must include a spiritual sense within the letter, in which all difficulties vanish, and the wisdom every way worthy of God opens to the view.

So far, then, the objections of Deists may clearly be retorted against themselves. We may say to them, "After all your industry in seeking for difficulties in the letter of Scripture; and admitting the difficulties you have brought forward to be ever so great, so long as the literal expression alone is attended to; you have not produced any thing that can convince a reflecting mind that the Scriptures are not the Word of God; you only elevate our conceptions to higher views respecting what the Word of God must really be. We find in the Scriptures numerous intimations, leading us to look for something beyond the letter: the difficulties you have started are calculated to turn attention the same way.
Let us then examine the Scriptures in this new and more exalted point of view; in which, if you will accompany us, you will probably see reason to change your opinion, and to acknowledge that your objections to the inspiration of the Scriptures have all proceeded upon a very partial and entirely inadequate view of the case."

2. This being precisely the situation in which the Christian advocate is placed by the Deistical objector, we proceeded, in the second branch of our argument, contained in our second Lecture,
Here then to examine the question thus opened for consideration.
we gave proofs, from rational and philosophical considerations,
that a composition which is really the Word of God, must not only be generally replete with divine wisdom, but must contain the chief stores of such wisdom in its interior recesses, -- in a spiritual sense included within the letter; -- just as, in all the works of God, and especially in his noblest work, man, are contained innumerable forms and wonderful organs, both corporeal and mental*, within the outward form which alone is visible to the eye.
This branch of the argument then stands thus: "A composition which has God for its Author, must contain within it stores of hidden wisdom, beyond that which appears on the surface: On the supposition, then, that the Scriptures are the Word of God,
they actually must be replete with such hidden wisdom." And thus the same conclusion is pressed upon us by considerations grounded in the very nature of things, which we before found was pointed out to us by the infidel objections.

It is true that this argument does not prove, that the Scriptures positively are the Word of God, but only, what their nature must be if they are: But as they likewise affirm the same of themselves,
and had that affirmation believed, without reserve, in the days of primitive and pure Christianity, (both which points are also proved in our second Lecture,) a full coincidence is established between what a divine revelation must be, and what the Scriptures pretend to be: and thus is raised a strong presumption, that this,
on due examination, is what they will actually be found to be.
Before then the Deist rejects them on account of some things which offend him in the letter, it behoves him to be very certain,
that the literal sense is all that is intended: and if he is assured that a further meaning is intended, (and I wish my voice or pen could carry this assurance to every one that ever saw a Bible,

whether Deist or Christian !) then ought he, as a candid inquirer,
to pause a while, and examine the evidence upon which this statement rests: and sure I am, that whoever would candidly do this,
and would take the pains to understand it, must be convinced of its truth, and must learn to prize the Scriptures as his highest treasure, -- as containing indeed the pure Word of God.

3. But to determine this point with certainty, it is necessary that we should be acquainted with the Law or Eule by which every divine composition must be composed, and by which of course it alone can be decyphered: wherefore, as the third branch of our argument, we proceeded to shew, in our third Lecture, that there must be, from the very nature of creation, an unalterable relation between natural things and spiritual, insomuch that all things in nature, being outward productions from inward essences, must be natural, sensible, and material types, of moral, intellectual, and spiritual antetypes, and finally of their prototypes in God.
I then availed myself of several testimonies in favour of this great principle: but I will here mention one which was not before the public at the time of the delivery of my former Lecture, but which is so striking and beautiful, that I am sure every lover of trut*h will be
It is contained in an glad to be put in possession of it now.
address delivered by the Eev. W. Kirby, M.A., E.K., and L.S.,
the Chairman of the Zoological Club of the Linnsean Society, at a late meeting of that body. He offers his views of the existence of fixed analogies among the various orders of being; of the im-

portance of the recognition of the principle to the higher interests of Science; and of its applicability to the construction of a highly significant language; in these terms: "When we are engaged in the study of animals, and more especially in groups of them, it is of the first importance, if we would avoid mistakes, that our attention should be kept alive to what the friend lately alluded to has said on the subject of affinity and analogy.* By his judicious observations on this subject, he has opened a new door into the temple of nature, and taught us to explore her mystic labyrinths,
guided by a safer clew than we were wont to folloio. And whoever casts even a cursory glance over her three kingdoms, will every where be struck by resemblances between objects which have no real relation to each other. He will see on one side dendritic minerals; on another, zoomorphous plants; on a third, phytomor-
<phous animals j and among animals themselves he will see number-

less instances of this simulation of affinity where the reality of it
From this part of the plan of the Creator, we may does not exist.
gather, I think, that every thing has its MEANING, as well as its USE; and that probably to the first pair the
Creation was a book op SYMBOLS, a sacred LANGUAGE;
of which they possessed THE KEY, and which it was their delight to study and decypher."j-

Here then is asserted in the most conclusive manner, and as founded on the most certain facts, the very principle which it has

* The gentleman alluded to is Mr. Macleay, who has demonstrated the existence of a remarkable analogy between insects and fungi: See our third Lecture, p. 85 and 86 (notes).

f Phil. Mag, Dec. 1823, p. 461.
been a chief object of these Lectures to establish.

Not only does this enlightened philosopher and divine, affirm the existence of a fixed analogy between the various objects of the three kingdoms of nature, but he recognises, as an unavoidable consequence, its existence between the kingdoms of nature and those of mind: and when he' concludes that it forms a sacred language, of which our first parents possessed the key, he leads by an easy step to our further conclusion, that in this language the Word of God is, and must be, written.
Little, certainly, did I think, when I first propounded the principle in this Hall, that it was being advanced,
almost at the same moment, in one of the most distinguished philosophical societies in the kingdom !
But from this and other tokens I am quite satisfied, that the advances which science is at present making in all directions, are very rapidly leading the minds of reflecting men to the same doctrine of Scripture interpretation
The final consequence will as has been offered in these Lectures.
be, that there will be no resting place to be found between absolute
Atheism, and those views of the nature of the Divine Word which we have endeavoured to develope.
These, all real science will be found more and more to confirm: and Atheism, also, will then become far more inexcusable, because the testimonies to the divinity of the Scriptures will become so palpable and so abundant.

4. Finally, we have endeavoured to shew, that the communication of a Eevelation from God to man, must follow the same general law as regulated the production of the creation; tlius that the Analogy found to exist between natural things and spiritual,
must govern the composition of writings constituting such a Eevelation; and that, in point of fact, such a regard to this Analogy is discoverable in every part of the Holy Word, and is the true key
Examples in proof of this, with for decyphering its contents.
dissertations on the true nature of divinely inspired prophecy and divinely inspired history, and on the design of the selection of the
Israelites as a peculiar people, occupied our two last and longest
Lectures: and I do trust, that some of the instances which were given of the applicability of the Doctrine of Analogies to the interpretation of the Divine Word, though very imperfectly elucidated,
must yet have been sufficiently clear to carry conviction to every accessible mind.

The presumption, then, in favour of the divinity of the Scriptures, created by the former part of our argument, now rises to certainty; for this branch of the argument stands thus: A Composition which has God for its Author must own the laws of the same
Analogy as reigns through all the divine works: This characteristic exists in the Sacred Scriptures: Wherefore they must have proceeded from the Author of nature.
If it be objected that this only proves that the Scriptures may have had such an origin, but not that they mast ,° a supplementary member may be added to the argument: As was shewn at the commencement of the fifth Lecture, No composition could, everyicliere, follow the laws of the
Analogy between natural and spiritual objects, unless dictated by a
Being to whom the properties of all natural and spiritual objects were perfectly known: As then the Scriptures do everywhere follow this Analogy, they must have proceeded from a Being of Infinite

Intelligence.

Thus have we arrived fully at the conclusion, that the Scriptures are, what they profess to be, the Word of God.

II. If then it is true, that such is the nature of the Word of
God; -- if, as has been shewn, it is not given to communicate to man natural knowledge, but spiritual, -- and if, as likewise has been evinced, to communicate spiritual things without a veil would be to injure those who are in states of confirmation against divine things, and not to benefit them; -- if, finally, it is because it follows the Law which must necessarily govern the communication of a
Divine Eevelation, that the Word of God is couched in language outwardly simple, whilst it contains divine wisdom within; which,
also, is capable of being decyphered by an application to it of the laws observable in nature: then are we furnished with a satisfactory answer to every argument that can possibly be urged
It necessarily follows, that it is the Word of God indeed: and it is immediately seen that all infidel objections proceed upon a partial view of the case, and that they fall to the ground of themselves, as soon as the true nature of the Writings against which they are raised is known, without the necessity of against it.

being separately refuted.

By way of conclusion, however, we are to shew more particularly, how the system of which we have been endeavouring to give a sketch, applies to the four classes of infidel objections noticed in our first Lecture; which impute to it many statements contradictory to each other; many that are contradictory to reason and science; many that are contradictory to just morality; and many that relate to matters of an indifferent nature, totally unworthy of the concern of an Infinite Being.

1. There will be some convenience in considering first, that class of infidel objections which imputes to the Scriptures Contradictions to Reason and Science.

Rightly to estimate the chief of these objections, it is necessary to be acquainted with the peculiarity of style belonging to that part of the Word of God in which they occur; which is, the first portion of the book of Genesis. We have endeavoured to draw the line of distinction, in our fourth Lecture*, between some of the books contained in the collection denominated the Bible, and others, and to shew, that while the greater part are written by the plenary inspiration for which we contend, and thus contain a spiritual sense within that of the letter, which is the criterion for distinguishing the proper Word of God; the remainder are the offspring of the illuminated intellect of the writers, possess no regular sense beside that of the letter, and cannot claim any higher inspiration than that lax and partial one, which is now all that is usually allowed to the whole of the Sacred Writings. But among those books which are written by the plenary and immediate inspiration, there are also some specific differences of style, though they
Thus the prophetic are all composed in the general divine style.
style is evidently different from the historical.
There also are two species of that which assumes the historical form; and which must be distinctly seen, before we can meet effectually that class of infidel objections which is founded on imputed contradictions to reason and science.

(1.) We have seen in the fifth Lecturef, that the Israelites were selected by Divine Providence, to be made the instruments of representing things of a divine and spiritual nature; hence, though the particulars of their history recorded in the Scriptures are all typical, exhibiting spiritual and divine things under symbolic actions and descriptions, they still are histories of real occurrences,
But it is easy which took place, in general, as they are related.

* Page 133; but more particularly in the Appendix, No. IL,
f PaSe228to248; &c to see, that this combination of symbolic meaning with actual facts could not exist, till the nation, thus invested by divine appoint-

ment with a representative character, existed: this species of Divine
Writing, therefore, can only commence with the origin of the
What style, then, might we expect would be
Israelitish nation.
employed in that portion of the Word of God, which relates to the affairs of the inhabitants of the earth before the birth of Abraham,
the great founder of the Israelitish nation? What could be so proper, as the style of writing which prevailed among the natives of the globe at the period it describes? And this was the style of pure allegory, in which the things meant are so entirely inde-

pendent of the things mentioned, that the latter are invented to serve merely as a vehicle for the conveyance of the former.

If such be the fact, there cannot be a greater mistake than to imagine, that the first chapter of Genesis is intended to be an exact description of the process of the Creation of the world.

It can answer to it no further, than as the real order of that creation answered to the order in which the endowments necessary for rendering man a purely intelligent and heavenly-minded being were successively implanted in him; and which was an order similar to that, in which the child now advances from the ignorance in which he comes into the world, to the understanding of a man.
All the objections then which scepticism has advanced against the divine inspiration of the Word of God, founded on the inconsistency of some of the facts related in the early part of Genesis with the known principles of reason and science, fall to the ground at once,
when it is seen, that this is not intended to be the record of a natural but of a spiritual creation; and that the events which follow to the time of Abraham, are not intended to give the history of mankind as to their outward transactions, but a history of mankind as to the state of their minds, and their reception or perversion of divine gifts and graces. To affirm, as is now the fashion,
that the narration is to be literally understood, -- that the ordinary date of human life was then about a thousand years, -- that serpents could talk, and that the woman was literally made of her husband's rib, -- is to exact of the believer a blind faith indeed.
In the early ages of Christianity, her teachers knew better: they did not thus
" bind heavy burthens, and grievous to be borne, and lay them on men's shoulders", Clemens of Alexandria, one of the most learne

14
of the early Fathers, declares, that such was the style customary in the ages to which this history belongs; observing "that all who have treated of divine subjects, whether Greeks or Barbarians, in-

dustriously involved the beginnings of things, and have delivered the truth in enigmas, signs, and symbols, in allegories and metaOrigen, when the shrewd enemy phors, and other such figures."*

of Christianity, Celsus, ridiculed the stories of the rib, the serpent,
&c, as childish fables, reproaches him for want of candour, in purposely keeping out of sight, what was so evident upon the face of the narrative, that the whole is a pure allegory, f
Indeed, so universal was this sentiment, that De la Bigue, in his Bibliotheca
Patrum, after quoting a number of testimonies to this effect, says,
" For these reasons, the Interpreters whom we have mentioned,
understanding all that is said of Paradise in a spiritual manner,
affirmed, that divers heresies had arisen, because certain persons had understood what is said of God and Paradise after a carnal manner^ :" so that although orthodoxy, as the prevailing opinion is always called, has since gone over to the other side, it is certain that, in the primitive days, the heretics were those who interpreted this part of Scripture according to the letter.

However, there is an evident prospect, that Reason and Truth will, in this respect, again resume their sway; for just sentiments in regard to the bearing of Revelation on physical science, are now frequently promulgated from high authority: Indeed, the sentiment which I have advanced, that Divine Revelation is not intended to communicate to mankind natural knowledge, but moral and spiriThus the Eev.
tual, seems likely soon to be generally admitted.
W. D. Conybeare, in his admirable Introduction to "Outlines of the Geology of England and Wales", by himself and Mr. Phillips,
delivers his views of this question thus: "Before we examine the bearings of physical science on Revelation, our ideas should first be settled as to what may reasonably be expected from Revelation in
Both its opponents and some of its defendants often seem to argue, as if it should have included the discovery ot a system of physical truth; which, it would not be difficult to shew,
gives an entirely erroneous view of its professed object; --  to treat,
namely, of the history of man, only, and that, even, but as far a9

this respect.

* Strom. 1. v. p. 658, Ed. Ox.

f Cont. Cels. 1. iv. p. 187, Ed. Sp.

J "Propter has causas", &c. torn. i. p. 270. (Par. 1589.)


affects his relations to his Creator, and the dealings of Divine Providence in regard to him."* He afterwards gives three views of the manner in which the term days may be understood in the first chapter of Genesis; the second of which, and by far the most tenable one, he states thus: "We may perhaps without real violence to the inspired writer, regard the periods of creation recorded by Moses, and expressed under the term of days, not to have designated ordinary days of twenty-four hours, but periods of definite but considerable length; such a mode of extending the signification of this term being not unexampled in the Sacred Writings.
Those who embrace this opinion, will of course assign the formation of the secondary strata, in great part at least, to these days of creation; and we have the authority of several divines in favour of this mode of interpretation. "f

Here we have the principle openly admitted, that to convey physical instruction cannot be the design of the book of God; and that even to make the statements which appear in the form of physical details harmonize with the unquestionable discoveries of true science, great latitude must be taken in the interpretation of
The same doctrine is powerfully advocated in a late the terms.
Number of the Quarterly Eeview; which I advert to, because that journal is devoted to the interests of religion, as understood in the
Church of England, -- and because the reputed author of the article alluded to is likewise a clergyman .%
part of the narrative of the beginning of Genesis, were capable, by

Supposing, however, that this

* Page 1.
% The passage is rather long; but its interest being fully commensurate
It forms part of the review of Professor with its length, it is here given.

t P- lx.

Buckland's late work, Reliquice Diluvianice.

" The more the strata which compose the crust of the earth are examined, the stronger evidence do they present of revolutions and catastrophes occurring at wide intervals of time, of slow progressive advancement to its present state,
and of the existence of varied orders of created beings which successively occupied its surface before it was finally fitted for the abode of man.
These phenomena, or rather the principles on which they are explained in the modern schools of geology, have been thought to militate against the history of the creation contained in the first chapters of Genesis.

" The usual mode of solving the difficulty has been, to interpret the six days of creation, not as natural days determined by the revolution of the earth en its axis, but as indefinite periods of time: and to this explanation Mr.
Buckland seems disposed in that [his Inaugural] Lecture to incline.

Others


this latitude of interpretation, of being reconciled with the facts as now ascertained, much difficulty would still remain to account for object to it -with great vehemence, as wholly incompatible with the institution of the Sabbath, which is manifestly set forth as the seventh day: and therefore they contend, that the other six must necessarily be regarded as days in the same sense, and of the same kind.

" Instead of presuming to decide peremptorily in this matter; our object will rather be to caution the friends of religion against a rash and possibly mischievous mode of vindicating their opinions. We beseech them to bear in mind,
that similar alarm has been taken, and similar zeal manifested, in the cause of religion, in several instances which have all terminated in establishing the points so much dreaded; and yet Christianity, so far from receiving a shock,
has only emerged from the controversy with increased vigour and lustre.
It is hardly necessary to remind them of the persecutions raised against the first
The doctrine was proteachers of the Copernican system of the universe.
nounced to be contradictory to the language of Holy "Writ, and was accordingly condemned as false and impious.
Nay, so late as the early part of the eighteenth century, when the Jesuits' edition of Newton appeared, '* was thought necessary by the Editors to prefix an advertisement, disclaiming all belief in the system thus demonstrated, because it had been declared unscriptural by the church, and setting it forth only as a series of deductions from a false hypothesis.

" Well indeed it is for us, that the cause of revelation does not depend upon questions such as these: for it is remarkable that in every instance the controversy has ended in a gradual surrender of those very points which were at one time represented as involving the vital interests of religion.
Truth, it is certain, cannot be opposed to Truth. How inconsiderate a risk do they run,
who declare that the whole cause is at issue in a single dispute, and that the substance of our faith hangs upon a thread -- upon the literal interpretation of some word or phrase against which fresh arguments are springing up from day to day

" Why, for instance, must we be compelled to understand the word efoy, in the first chapter of Genesis, precisely in the same sense it now bears, viz. the period of the earth's rotation upon its axis?
Certain it is from the narrative itself that the word does not bear the same meaning throughout the whole chapter; for the first three days were passed before the creation of the sun is
Mentioned: and yet in these, no less than in the others, the portion of time is aenoted by the words ' evening and morning:' which, according to their reLet us not, howceived import, necessarily suppose the existence of the sun.
ever, oe misunderstood. We are firmly convinced that the institution of the
Sabbath is a divine ordinance from the beginning --  that the observance of it is enjoined as commemorative of the close of the great work of creation, and that its solemn obligation is expressed by the parallel which it pleased God to draw oetween the progress of his own works, and the destined employment of that being whom he made in his own likeness.
Yet no one can believe, when it is said God rested from his works, that he really underwent fatigue and required

the existence of light for four days (and days too of this indefinitely long duration, amounting, altogether, at least to hundreds of years;

 -- to account for the existence of light all this while) before the creation of the sun, moon, and stars: -- for the hypothesis which has been so eagerly caught at by some of the Christian advocates,
that this light was what certain modern philosophers have called
" the matter of light", diffused through all space, cannot be accepted till it is shewn, that light can ever be rendered perceptible without some luminous centre to put it into activity.

"When such philo-

sophic advocates of the literal sense can introduce us into a closed room, containing neither lamp nor candle, yet fully illuminated by the universally diffused "matter of light", their explanation of
Genesis may be received: but to receive it before, is only to comBut bine the dreams of philosophers with the dreams of divines.
every difficulty would be surmounted at once, were it admitted,

that to describe the spiritual creation, -- the endowment of man the primitive times, -- in those times which the poets have designated with those gifts and graces which were so eminently conspicuous in as the golden age, and have represented by the fiction of the garden of Jupiter, and which our Scriptures depict by the happiness of man when the garden of Eden was his abode; -- were it admitted that to describe this creation is the true object of this relation in
The truth is, that the circumstances detailed agree with

Genesis.

the facts attending the physical creation, so far as the analogy between the one and the other is exact; but when it holds no longer, the inspired relation follows the course of the moral creation,

and disregards the physical altogether.

(2 .) The truth of this view will be greatly strengthened, if we stop a little to consider the genius of the inhabitants of the world in those very ancient times, according to the best idea we can form of it from the traditions and accounts handed down from ancient writers.

This is a circumstance which has much puzzled the explorers of antiquity, and which has frequently led historians immensely out of repose. The same principle of accommodation to our perceptions and modes of speaking must be admitted here as it is in a thousand other passages of Holy
Our duty cannot be mistaken, whatever interpretation we put upon
Scripture.
the disputed words; and it is this duty which it is the main purpose of that volume to declare and impress upon us."

Q. R. No. IviL p. 162 to 164.
the way; that all history is, in the beginning, involved in fable.
Trace up the records of any very ancient nation to its origin, and they are universally found to become enveloped in mystery, -- to contain relations as remote from probability as those delivered in the early part of Genesis; wherefore they are considered by all as incredible. Now the air which they thus wear of incredibility, canNever was there a not possibly arise from their antiquity alone.
more gross attempt to impose an egregious sophism upon the public, than when a celebrated infidel advanced, that all testimony
The history of diminished in credibility in the ratio of its age.
Thucydides and the commentaries of Cassar, will carry as much conviction to the mind of the reader that they were intended to be records of actual occurrences, and are in the main true, rive thousand years hence, as they do now, or ever did: whereas the fabulous history of the origin of Thebes, and of the armed men that sprung out of the earth when Cadmus had killed a dragon and sown his teeth in the ground, equally wore the character of fable when first the story was broached as at the present day: only, they who lived in the age of its invention, knew that it was to be regarded as «n allegorical and not as a real history; they knew, also,
how such allegories were to be interpreted; and did not, like many of the modern learned, suppose, that every writing wearing the historical form was meant to be understood literally, and that, if it
The was in this shape incredible, it was to be rejected altogether.
fact is, as the remains of Grecian, Egyptian, and Indian antiquity which have come down to us abundantly evince, that it was the custom in very ancient times, not only with the people who lived before the flood, but with those who flourished many ages afterwards, to couch whatever they wished to be conveyed to posterity under the form of an historical relation, but intermingled, like the history of Adam and Eve, witli circumstances so extraordinary, as
But shewed that it was not designed to be literally apprehended.
in process of time the meaning of the symbols which they used was forgotten; and then the narratives composed by their aid, being accompanied with a traditional feeling of respect which prevented their total rejection, began to be understood in their literal sense only, and mankind were lost in amazement at the marvellous
Thus the things, which they supposed their ancestors witnessed.
vulgar, in the latter ages of Greece and Kome, looked back with
admiration at the times when their heroes went to school to the centaurs, and sacred statues or holy shields fell from heaven for the of them, at least, as love the world so well they fain would never protection of favoured cities; as the vulgar of modern date, -- such leave it, -- envy the longevity of the antediluvian patriarchs, and think how happy they should be were a thousand years still the duration of human life.

But further: The people of the earliest ages of the world were of a turn of mind so devoted to exalted sentiments and sublime contemplations, that they never thought of committing to writing accounts of common occurrences: they were too indifferent to the affairs of this world, in which they knew they were but pilgrims and sojourners, to deem them worth recording: for which reason, no authentic history of political or civil events, of any very great anti-

quity, exists.

Hence the well-known remark of the learned Varro utter obscurity; that the age from the flood to the first Olympiad that the space of time before the flood was a^Xov, -- the period of was fivOiKov --  the period of fable or mystery; and that it was only with the first Olympiad that commenced the period isropiKov -- 
that of literal history. The reason why the genius of these ancients led them to describe interior subjects in the language of allegory,
was, because the illumination of their minds was such as to enable them to discern, in natural objects the images of the spiritual and divine things which are the causes of their production; because, as elegantly expressed by Mr. Kirby, "the creation was to them a book of symbols, a sacred language, of which they possessed the key, and which it was their delight to study and decypher." Hence, when they wished to communicate to others their interior perceptions, they would veil their thoughts in language borrowed from natural objects and occurrences.
Whilst, indeed, this knowledge was possessed inThe tuitively, they probably would not think of writing at all.
whole creation was to them an open book: whatever they had occasion or desire to know, they there could read: every object in it spoke to them, in the clearest terms, of the supreme objects of their regard, -- of God, and heaven, and heavenly things; and read-

ing every thing there, they had no occasion for any books beside.
But when this faculty of intuitive perception began to decline, in consequence of their beginning to turn their affections towards outward objects, instead of only using these, as before, as means for nourishing their love for heavenly things as contemplated in them; whilst yet, among the better sort, a desire for the knowledge of heavenly things remained; then, we may conclude, they would study those things as a science which they before knew by intuition.
Then books would begin to be composed, in which they would endeavour to express their meaning by analogies taken from the objects of nature, the knowledge of which they would long regard as the first of sciences, and the distinguishing mark of wisdom and learning.

Now the early chapters of Genesis treat of the people who were of this character and genius, -- both of those who had an intuitive perception of spiritual things in natural objects, and of those who enjoyed the knowledge of them by science and study; and therefore that part of the book is written in a style similar to that which those people used; that is, spiritual and interior subjects are de-

scribed in language borrowed from the appearances of nature, -- in the form of apologue and allegory, -- in a narrative that appears in
Whole classes of people, whose modes of thinking and feeling, especially the letter to relate only to natural and ordinary facts.

in regard to sacred subjects, were similar, are personified as one man, to whom an age is assigned, answering, probably, to the period during which the principles represented continued to prevail: the manner in which one class of religious sentiment and profession is propagated from another is described by family descents: and the fates among mankind of religion in general, or the vicissitudes which the church of God, under different forms, ex-

sonages.

perienced, are represented by the fortunes of these allegorical perThat such a mode of describing such subjects is agreeable to nature, is evident from the tendency to it which still occasionally shews itself; of which many examples might be given from modern compositions.

(3.) That such is the character of the Scripture history antecedent to the birth of Abraham, may also be inferred from the similarity which is observable between the events which it relates and the traditionary accounts of the ancient heathen mythologers.
This resemblance has been observed by many of the Christian advocates, from Justin and Clemens to Bryant and Faber; and lias been dwelt upon as affording a strong testimony to the authenticity
Many, however, have here run into an of the Mosaic writings.
error, which has thrown a shade of doubt and suspicion over all that they have urged upon the subject: they have assumed, that whatever exists in heathen writings which bears some similitude to facts, or apparent facts, detailed in our Scriptures, was borrowed from this source: and they who do not affirm this, consider such fables of the heathens to be mere distortions of matters
But the of fact, which are simply true as recorded in the Bible.
argument in favour of the authority of the Volume of Bevelation is much stronger, when it is admitted, as doubtless is the truth, that neither the mythological stories nor the corresponding relations in

Genesis are details of external facts, but both are allegorical records of the same facts in the moral and spiritual history of mankind,
handed down through different channels: the former being productions of men who possessed the knowledge, and wrote in the style, which was common to the learned of those ages; and the latter being also composed in the style which was common to those times, so far as this consisted in the purely allegorical character of the narration, but written by absolute inspiration, and thus possess-

ing all the fulness and truth which inspiration only can convey. This the circumstances are described.

will account for the considerable variety in the images under which
Thus, for example, we have the record in Scripture of the termination of two distinct dispensations of divine things to man; the first of which, beginning with Adam,
closes with the flood; and the other, which commenced with Noah,
began to be corrupted at the building of the tower of Babel, and was totally so by the abominations which were plunged into by the Canaanites, the Egyptians, the Assyrians, and other nations which flourished in those ages, and which originally were branches of
These events are evidently the same as are dethe Noetic Church.
scribed in the Grecian mythology, by the two wars waged against heaven by two different races of giants, the first called the Titans, and the second, simply the giants.* The first race is described in Scripture by the giants which are said to have existed before the flood,
and who are represented as having sprung from the intercourse of the sons of God with the daughters of men: and the second race,
though not denominated giants in the Scriptures, are they who undertook the gigantic enterprise of building a tower whose top should reach to heaven, -- an enterprise very similiar to that of
* See our third Lecture, p. 113 & 116.

14*
scaling heaven by a pile of mountains. By these relations, both the mythological and Scriptural, is not meant that a race of people of enormous stature then existed:
but giants, in the language of
Analogy, are they who are great in their own conceit: and such giants as are here spoken of, were they who absolutely looked upon themselves as deities, arrogating all merit, all goodness, and all wisdom to themselves, and not allowing that every thing they possessed which was really good was imparted to them by gift and perpetual derivation from the Lord alone.
In short the symbol of monstrous giants was adopted, to represent those who fell into such direful persuasions, as to imagine that the Deity had actually transfused himself into them, so as to have no existence independently of them; approximations to which sentiment are to be found in some of the doctrines of the Greek philosophers; and at this day it lies at the bottom of the religious system of the Hindoos, and has decided affiliations in that of Thibet and China: the origins of all which rise to the highest antiquity.

Ts it not then, we may now ask with confidence, in the highest degree probable, that the early part of Genesis, and the mythological tales which bear so much resemblance to it, relate to the same facts, not in the political and civil, but in the moral and spiritual history of mankind? that they equally are composed in the general style prevalent in the ages to which they refer? that neither the one narrative nor the other was ever intended to be understood according to the literal form? that both are intermixed with such stories as, in the literal sense, are in the highest degree extravagant and incredible, purposely, among their other uses, to intimate to mankind that a common record of facts was not intended? but that the mythological tales, though originally composed by men who possessed a knowledge of interior things and their analogies with natural objects, yet not being communicated by plenary inspiration, have not a spiritual sense, except as to the general circumstances, do not exist in any record which carries a spiritual idea in every expression, and are not always, perhaps,

exact representations of the things intended: whereas, in Genesis,

the same occurrences are described in language inspired through-

out, and all the representatives are infallibly exact?

We may, I trust, now repeat as a certain fact: that this early part of Genesis is written in the language of pure allegory, because it describes the moral history of a people with whom that style of writing was the only one in use; and because, further, it could not be given in the style of true but representative history, whilst the nation afterwards raised up to sustain the proper representations was not yet in existence; and because, finally, these are the only two species of narrative that can be delivered by plenary inspiration; from which source, a history of mere facts, containing no in-

ternal meaning, never can proceed.

Now what objection, carrying the smallest weight, can be raised
It solves all against this view of the subject?

I can see none.

difficulties, and is, itself absolutely unattended by any.*

Nothing part of its contents.

further, then, needs be urged to overturn from the foundation that class of Infidel Objections which rejects the Word of God for the alleged contradictions to reason and science to be found in this
The literal history was never intented to be
The understood as such;
questions, then, respecting the manner and order in which the world was created, and respecting the vicissitudes which its surface has undergone; whether all the convulsions of which symptoms are apparent in the disposition of its strata, and in the vegetable and animal remains found in its bowels, took place before it was it, therefore, can contradict nothing.

brought into a state fit for the habitation of man, or whether part of the indications have been occasioned by a general deluge which it has undergone since; are matters which may safely be left for
The Word of God decision to the unfettered progress of science.
pronounces no dictum upon such subjects: and nothing which
Science may ever bring to light respecting them, can, in the slightest degree, affect the title of the Scriptures to be received as the
Word of God. The only bearing of all real Science upon the Word of God is, to point to and confirm its true nature.

2. The class of infidel objections which we are next to consider,
is that which is drawn from apparent contradictions between the various statements made by the sacred writers.

It is undoubtedly true, as is generally urged by the advocates of

Revelation, that the greater part of these admit of a sufficient explanation when the context is fairly considered: but, as was stated
* See Appendix, No. VII.
in the second Lecture, if there are any which cannot thus be recon-

ciled, it is, because, in such cases, the letter has yielded a little to struction.*

the weight of the matters contained within; a slight turn has been given it to make it express more fully the spiritual contents,
respecting which alone it is the object of inspiration to impart inOf this an example was given, and the principle more explicitly developed, in our last Lecture, from the history of JephThough the circumstances related are thah and his daughter.
true, they may not immediately exhibit the whole truth, as far as
" Just so much is recorded as the outward history is concerned.
conveys the true spiritual sense, and no more: and Divine
Wisdom, which only regards things eternal, deems it of no moment whatever, if an impression be thus left of transient events different
Admit this principle, (and if we admit that from the true one."f a Revelation from God must primarily treat of spiritual subjects,
it will be difficult to dispute it,) and we shall find no instances of seeming contradiction which can occasion the smallest embarrassment to the candid inquirer.

(1.) In the case, for instance, of the turning of the waters of
Egypt into blood, by Moses and Aaron; when it is afterwards said that "the magicians did so with their enchantments;" upon which the Deist asks, When all the water of Egypt was changed before,
how could the magicians repeat the operation? J --  It is here well answered from the letter, that the context shews that water was still attainable for the experiment, since we read, two verses below,
that "the Egyptians digged round about the river for water to
If, however, it had been more difficult to account for the drink."
manner in which the magicians obtained their water, there still would have been a necessity, to convey the spiritual lesson in-

tended, that the narrative should be so framed as to imply in the letter, that all the waters of Egypt were changed into blood by
Moses and Aaron, and yet that the magicians performed a like
The subject here spiritually treated of is remiracle afterwards.
specting the false persuasions which adhere to those who cultivate natural science, but oppose themselves to the will of God and the truth of his Word, and respecting the judgments with which they
The waters of Egypt are all are visited to compel them to desist.
the truths possessed by such persons: blood, when considered in

* P. 27, 28.

f p - 270 > 271.

% See the first Lecture, p. 17.


any way different from its proper relation, is the symbol of truth to which violence is done by wresting it from its just application.
Moses is the type and representative of that Law or Word which was given by his instrumentality; and Aaron, as his prophet, or teaches.

spokesman, represents the true doctrine or instruction which that
The miracle, therefore, was performed by them, to indicate, that, before the wicked are finally condemned, their real
Eut "the state, as Divine Truth discovers it, is shewn to them.
magicians did so with their enchantments", to represent how the natural man finds excuses for not setting his heart to consider the divine judgments when openly displayed before him, referring them to other causes: in fact, the magicians are the proper types of that ingenious mode of reasoning from fallacies, which resolves the most express interferences »of Deity into the common operations of
The spiritual lesson, surely, is deeply interesting, and the analogies from which it results self-evident: to yield those analo-

nature.

gies is the main thing regarded in the construction of the letter and when matters so weighty are to be expressed, it surely is more important that the language of the sacred history should be such as gives the spiritual contents in all their fulness, than that it should be absolutely free from obscurity in regard to all the minutiae of the literal details !

But the difiiculties in the literal narratives of the Word of God which appear most considerable, to those who do not attend to the proper design with which all the narratives of the Word of God are constructed, are those which are presented by the frequently vary-

ing accounts of the four Evangelists.

(2.) The question, why so many as four authentic Gospels should have been written, has embarrassed not a few inquirers.
Many, even of those who have no prejudice against them on account of any part of their contents, would be glad of a plausible pretext for ejecting some of them from the Canon: thus the celebrated Michaelis, entertaining the common notions of inspiration,
regarding it as a personal and permanent endowment, and being at for a certain rule to discriminate between compositions a loss which are inspired and such as are not, would fain limit the inspiration of the New Testament to the Apostle's writings alone; and he intimates that no small advantage would result from accepting
Apostleship as the criterion of inspiration, since there would then


be but two Gospels which we should be concerned to harmonize.*
13ut if we regard the historical Scriptures as containing throughout a spiritual meaning, and conclude that, where the same general fact is variously related, it is for the sake of teaching the same general spiritual lesson, with some specific modifications; we shall have no need to wish that the number of inspired books were fewer,
or to murmur at their Divine Author for the abundance of his benefits.

The Apostle and Evangelist John concludes his gospel with observing, "There are also many other things which Jesus did,
the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written."
This would be an extravagant hyperbole indeed, if it referred to the acts of Jesus as they appeared in their, simple performance but it becomes a sober truth, if we understand by it, all that was included and involved within the outward appearances.
Only let it be acknowledged, or supposed even, that Jesus was "the Word"
or Divine Truth itself "made flesh f", thus was God Incarnate;
and it follows inevitably, that there must have been an infinity of meaning in every one both of his words and of his actions; and it may be easily conceived, that one mode of narrating them would be insufficient for their full representation.

Perhaps, also, in agreement with that unvarying constancy with which all the divine operations follow fixed laws, there may be some divine law which rendered it necessary that the Gospels should neither be fewer nor more than/ew: indeed, if inspiration be allowed to them, such must be the fact; since it were a contra-

diction in terms to affirm, that Divine Inspiration produced the exact number of four Gospels by chance.
It is somewhat remarkable, that we read respecting the "river which went out of Eden to water the garden", that "from thence it was parted, and became into four heads J:" and it seems possible that the coincidence was not unintentional, which was noticed by an ancient father; that
" there were four Evangelists, four rivers of Paradise, four corners and four rings to the ark of the covenant §:" not that the first of these circumstances was the cause of the others, nor even that the

* Introd. by Marsh, Vol. i. Ch. iii. Sec. 3; Vol. iii. Pt. i. Ch. ii. Sees, l&o;

Ch. vi. Sec. 2.

j- John i. 14.

J Gen. ii. 10.

§ Jerome, apud Lardner, vol. xii. p. 82.


others were provided to form types of the first; but that they all owed their origin to the same general principle; -- that the same law regulating the descent of divine things into nature, governed
Now, what could the rivers of the one circumstance as the others.
Paradise represent, but the streams of truth and wisdom which nourished the mind of man in his paradisiacal state? And why were there four of them, but because that number expresses fulness and abundance? for it is a number which is used in reference to the four quarters of the world, -- the east, west, north, and south,
 -- in connexion with which it is frequently mentioned in the Scrip-

tures*; and while each of these, singly, refers to some specific quality, the four together manifestly stand for the whole.

So, if the four rivers of Paradise, together, were representative of the truth and wisdom, in all their fulness and abundance, which, in the primeval ages, animated and endowed the human mind; each of them must have been the symbol of some general class of these
What this is, is discoverable from the import, in the langraces.
guage of Analogy, of the four quarters, from which the number four
The east, being considered as the draws its signification of fulness.
seat of the sun, represents much the same as the sun does, -- 

state of love, and of the illumination immediately proceeding from love, in its highest intensity; and the west is the same general state in a lower degree: so the south is expressive of a state of in-

telligence, with its attendant charity, in the highest brightness;

and the north of the same as verging towards obscurity.

Thus the east and west, and the south and north, are to each other, re-

spectively, as the internal and external of one general principle.

If the cardinal points did not bear, in the language of Analogy, which is that of the Word of God, some such meaning, would they be so frequently noticed in that Word; and this even in its prophecies and visions?! Now what if four Gospels were given, describing the history of the birth and ministry of the Lord Jesus Christ, with a reference to these four general states? to be divine streams of truth and wisdom, possessing, respectively, these general qualities?

* As when John "saw four angels standing on the four corners of the earth, holding the four winds of the earth."

Rev. vii. 1.

t See Ezekiel's vision of the New Temple, in the last nine chapters of his
For the general frequency book, and John's of the New Jerusalem: Rev. xxi.
with which the quarters are mentioned, see a Concordance.


to form the unfailing rivers of the Christian Paradise, -- the church,
 --  supplying to its inhabitants the waters of life?

I throw out this suggestion, not as a certain truth, but because, to me, it yields a probable reason for the number of the Gospels, and because it includes ideas, which, as we shall see presently, tend considerably
To me, also,
to clear up the mystery of their varying statements.
it appears quite evident, that the obviously distinct characters of the several Gospels tally remarkably with those which this view
Will not all who venerate these sacred narratives consupposes.
fess, that the Gospel of John displays the highest order of the illumination here alluded to, treating more openly of the highest sub-

jects of divine illumination, which are, the true nature and character of Him whose history it relates, and the necessity of love to his name? that the Gospel of Luke, with its sweet delineations of charity, and luminous statements of so many essential truths, ranks next in clearness? and that those of Matthew and Mark, though fully imbued with the same spirit, treat their subjects in a more external manner, or clothe them with a somewhat thicker veil, and are to the former, respectively, what the north and west are to the south and east?

(3.) Supposing there to be any truth in this view of the subject,
the reader of the Gospels would expect, that, in recording any transaction, each Evangelist would relate such of the circumstances attending it as belonged to the proper character of his Gospel, and would omit others: and if there are any cases in which the circumstances related by different Evangelists are quite incompatible with each other, he would expect further, that the narrative of the facts,
as they actually appeared to the senses of the beholders, would most probably be found in one of those Gospels, (Matthew's or
Mark's,) which treat the subjects under their most external form whilst the seemingly incongruous circumstances, if any', mentioned by the others, equally belong to the transaction, but exhibit the inward state of mind of the parties concerned, which did not manifestly appear in the words or actions actually spoken or performed,

but yet were as really present as those words or actions themselves.
This suggestion may be illustrated in a very familiar manner.
Every one knows how frequently the words and actions of persons in society greatly differ from their inward thoughts and inclinations.
To take a rather coarse, but too common example: how often do. s the greedy expectant of a profitable reversion, express with his lips k great desire for the restoration of the sick possessor's health,
while the language of his heart is, "I wish you were dead, out of
Now, if these words were actually ascribed to him by a the way !"
narrator who knew the heart, there would be no real contradiction between this account and that of another who reported the language of his tongue: they would both record different parts of the same transaction, and both records would be true, though one of them could have flowed from the pen of none but an inspired writer.
This is so obvious an idea, that I remember to have seen it very
The pleasantly illustrated in a fable for the instruction of youth.
writer imagines the existence of an edifice called the Palace of
Truth: the inmates of which are unconsciously compelled to speak and act according to their real thoughts and inclinations: the consequence is, that they are continually disgusting each other by rudeness of language and demeanour, whilst they fancy themselves to be behaving with perfect good manners, and saying the civilest things imaginable. Who doubts that the universe is, to its Architect, a Palace of Truth, in which the inmost thoughts are as audible as the outward declarations?

But not only is there frequently this palpable difference between the thoughts and inclinations and the words and actions -- a dif-

ference of which the parties themselves are sensible; but doubtless there is much more included within every single idea of thought than comes to the apprehension of him who conceives; t: and if the moving springs from which it arises, with all their complications,
were discovered to him, they would sometimes be so different from what he himself suspects, that he would hardly recogn.se himself in them, though they belonged to the very essence of his distin-

If then these unconscious thoughts and inguishing character.
clinations were actually ascribed to him by the pen of that Omniscience to which they are all known, the picture drawn of him would still be in exact accordance with the reality, though the likeness would not be discernible to a superficial observer.

We now, I apprehend, shall be in possession of the true principles for reconciling the seeming discrepancies of the divinely inspired recorders of the Gospel-history. -- When circumstances are omitted by one Evangelist which are mentioned by another, it is,
because they belong to a different specific modification of the same general spiritual lesson, and, in fact, to a different order of Divine
Truth, from those which it is within the province of that Evangelist to deliver. -- When, if ever, the circumstances are such as could not,

both, have outwardly occurred, one of them is the expression of the state of mind of the parties, within or above their outward speech and actions: it gives such developments of inward character as would have taken place had the parties been speaking or acting in the Palace of Truth; and, to carry on the allegory, it belongs,
sometimes to the lower and sometimes to the upper stones of that edifice, or is more near to, or more remote from, the actual con-

sciousness of the actors or speakers.

From theory, let us now descend to facts, and try the applica-

tion of our principles to the actual relations of the Gospels.

(4.) A remarkable example of variations, from both these causes, is, I conceive, afforded by the history, as delivered by the four Evangelists, of the treatment of the Lord Jesus Christ at his crucifixion, and of his behaviour on the cross. Matthew and Mark,

agreeably to their office of presenting things as they appeared to the outward observer, and also, as they were perceived by the parties in the lowest and most external sphere of their thoughts and feelings, are very full, especially the former, in the detail of the cruel insults which were heaped upon the Saviour in that dismal
They describe all the bitterness of his temptation thence scene.

arising, and the severity of his mental as well as bodily suffering.
They record his despairing exclamation, "My God, my God, why hast thou forsaken me* :" and these, as far as can be gathered
Luke, on from them, were the only words uttered from the cross.
the contrary, states much less of the aggravating scoffs with which the Eedeemer was assailed as he hung, and narrates nothing in his conduct which indicates that the sufferings inflicted on him engaged
According to this Gospel, when going to much of his attention.
execution, he says to the mourning women, "Daughters of Jerusalem, weep not for me, but weep for yourselves, and for your
Instead of any exclamation of despair upon the cross,
children. "f we have this effusion of imperturbable confidence: "Father, into thy hands I commend my spirit % :" and these, with the encouraging declaration to one of the thieves, and a prayer for his murderers, were, as far as can be gathered from this Evangelist,

* Matt, xxvii. 4.0, Mark xv. 34.

f Ch. xxiii. 28.

t Vcr - 46»


the only words uttered by him in that situation. How plain then it, that Luke relates the perceptions and feelings of Jesus on is this occasion, as they existed in a sphere of his mind above that,
the sensations of which are recorded by Matthew and Mark; with the words which he spoke from this different order of sentiments !
And still more is this the case with the narrative of John.
This seems to describe his feelings in a sphere of his mind to which no consciousness whatever of his indignities and sufferings reached.
It therefore does not at all notice the insults addressed to him on the cross. He is represented as occupied with no considerations
To represent his care of the whatever which regarded himself.
church, which ever dwells with those of whom "the disciple whom he loved" was a type, "he saith to his mother", in reference to that disciple, "Woman, behold thy son !" and to the disciple, who thenceforth took her to his own home, "Behold thy mother I"*
To express his ardent desire for man's salvation, and "that the
Scripture might be fulfilled", he exclaimed, "I thirst."f
And, so far from indicating any feeling bordering upon despair, he does not even express any sense of needing support: he does not, even in appearance, refer to any Divine Helper out of himself; but, ex-

periencing already a perfect consciousness of his union with Divinity,
and "knowing that all things were now accomplished" necessary to effect that union, and with it to secure the redemption of mankind,
he simply, and, with divine composure, says, "It is finished."

Now though these very different narratives, may not, regarded only as to the letter, be irreconcilable with each other; though it is probable that all the circumstances recorded by each Evangelist did actually occur; and though the very dissimilar speeches related might all actually be spoken: yet every one must see, that the different narratives and the different speeches breathe different feelings, and belong to decidedly different classes of sentiment which would have been broken and confused had they been jumbled into one continued discourse, but are preserved in all their dis-

tinctness and beauty, by. the wise provision of Providence, thatseveral Gospels shoUd be written.

(5.) Another striking example of the excellence of this arrangement, is afforded by the account of the conduct of the two thieves,
as related by Matthew and Mark, and by Luke.

* Ch. xix. 26, 27.

f Yer. 28.

J Ver. 30.



such details.

Without particularly dwelling upon the behaviour of these unhappy men, Matthew, after mentioning the taunts of the chief priests and scribes, adds, "The thieves also, which were crucified with him, cast the same in his teeth* :" Mark also says, "And they that were crucified with him reviled himf:" a circumstance deeply aggravatory of the Saviour's sufferings, when he had to endure the insults of the very outcasts of society; and therefore well suited to be introduced in the Gospels of Matthew and Mark, the nature and design of which necessarily included the insisting upon
Luke, however, who does not give so much of the scoffs of the priests and scribes, mentions the reviling of one of the thieves only, and this, chiefly, to contrast it with the becoming behaviour of the other: his words are these: "And one of the malefactors which were hanged with him, railed on him, saying,
If thou be Christ, save thyself and us. But the other rebuked him,
saying, Dost not thou fear God, seeing thou art in the same condemnation? and we indeed justly; for we receive the due reward of our deeds: but this man hath done nothing amiss. And he said unto Jesus, Lord, remember me when thou comest into thy kingdom. "X Now whether both these narratives describe things which took place in outward form, just as they are related, or not;
certain, that, spiritually, both narratives are true, and that both it is were necessary for conveying the spiritual lesson intended.

Thieves, in the Word, are types of those who deprive others of truths by infusing false and heretical opinions; as, also, of those who possess the knowledge of truth, but pervert it from its proper object, which is, to lead to a life of goodness: they likewise repreThe sent such as arrogate to themselves what belongs to the Lord.
two thieves, then, are they who act thus, either from a confirmed principle of evil in the will, or from a false principle assumed by tiic understanding; and they thus will represent the Jew and the
Both these classes of spiritual thieves, viewed as tjo
Gentile world.
their doctrinal sentiments, reviled the Son of man; both Jews and

Gentiles entertained opinions adverse to the true doctrines of the
Word of God; and this is represented by the fact as stated by
Matthew and Mark, that "the thieves, also, cast the same in his teeth:" "they that were crucified with him reviled him." But though both classes thus reviled the Lord externally, it was only with one

* Ch. xxvii. 44.

f Ch. xv. 32.

J Luke xxiii. 39 to 42.
mat the outward conduct proceeded from an internal ground: Luke,
therefore, who relates the circumstances as they exist in, or flow from, an interior sphere, ascribes determined malevolence to but one of the malefactors: the other, who is the type of those who, like the Gentiles, entertain false sentiments merely from ignorance, and of those who fall into improper conduct, because they have not had the advantage of such instruction as would teach them better, when brought, even in this extremity, into the presence ot the Son of man, -- made acquainted with the Truth Itself, -- feels all the compunction that a conviction of his error and misconduct ought to excite, and solicits the mercy of him whom he is thus brought to know: and because no one in heart can acknowledge the Lord but from some good principle, Jesus answers, "Tostate, -- "thou shalt be with me in paradise."
day", -- in this
Considered then as representative characters, -- as the types of two masses of spiritual thieves, there evidently is no contradiction whatever between the accounts of Matthew and Luke: they describe different parts of the same general facts, and parts so distinct,

being those which constitute its external form and its internal, that they could not possibly have been included in the same narrative.
And the case will be the same, if, without looking at the thieves as types of general classes, we regard them as individual transgressors of two different characters. Many a one has been led, by untutored passions, into excesses which he never deliberately purposed,
and has afterwards been awakened, by the voice of Truth, to the
The law may have been so far most sincere feelings of remorse.
violated, that the gibbet must expiate the offence: but who will affirm that the redeeming feelings in the heart of the sufferer will go for nothing in his final account, though, being beyond the eye of the human judge, they cannot change his doom here?
Every criminal act reviles the Son of man: but we cannot positively affirm, of every one who has been hurried into the commission of a
The outward conduct,
criminal act, that his heart does the same.
then, of these two characters, in which they appeared similar to each other, is described by Matthew and Mark, and their inward state, in which they were dissimilar, by Luke.

Seeing then the spiritual reason for the variation of these narra-

tives is so evident, and the spiritual lessons they inculcate are so completely satisfactory; to know, how far the facts mentioned by
Matthew and Luke appeared manifestly before the spectators of the
It may be true,
scene, becomes a matter of perfect indifference.
as some of the commentators suppose, that both the Gospels relate facts as they happened; that both the thieves at first joined in

Gospel.

blasphemous language, but that afterwards one repented, and behaved as stated by Luke: supposing it were so, the view we have offered above clearly explains why neither Evangelist states both facts: to have done this, would have confused the spiritual sense,
and would have been a deviation from the proper character of his
It may be true, again, that Luke alone relates the facts as they happened, and that the penitent thief never reviled with the other: and in this case, whether we suppose, with most of the ty, "the thieves" and critics, that Matthew and Mark, who sa
" they" loosely, and not "both the thieves", and "both of them",
emphatically, use the plural number for the singular by the grammatical figure called enallage (of which they produce several examples) ; or whether we conclude that they were really ignorant of the different circumstances recorded by Luke; we still see, as before, that there is no mistake in the matter, and that the spiritual sense of the whole transaction would have been mutilated had not both records of it been made.
Or, finally, the outwardly apparent circumstances might only have been those given by Matthew and

Mark; -- either, positively, both thieves did revile, or this might be said because one of them, though silent, gave no outward indication of dissent from the conduct of the other; and still it may be perfectly true that the language of their heart was that given by
Luke, though what this spoke, in the penitent, was only audible to him to whom all hearts are known:
if, however, such sentiments were there actually heard by Him, he did not make one Evangelist contradict another, when he caused him to give them an open
One or other of these three solutions must be the true tongue.
one; ichich, is to us of no moment whatever: and it is plain from either of them, that the Gospels are not here really at variance, but only relating different parts of the same transaction, which all be-

longed to it with equal truth.

We mentioned, in our first Lecture, two of the other seeming difficulties on which infidel writers have founded objections; and as, though solvable upon the same principles, they rather differ in kind from those just considered, it may be expected that we shall not dismiss them without specific notice.

(6.) The first of these is the circumstance, that in the history of the temptation of Jesus in the wilderness, as delivered by Matthew*
and by Lukef, there is an inversion of the order of two of the principal facts; the first Evangelist making the devil set the Saviour on a pinnacle of the temple, before he shews him, from a high mountain, all the kingdoms of the world; whereas, Luke
Eegarded as a places this latter circumstance before the other.
record of outward facts, there must here be allowed to exist a difficulty; but there will remain none at all when it is admitted,
that to communicate information respecting the same general spi-

ritual fact is the main design in both narratives; but that this general fact includes two leading branches, one of which is represented by one Evangelist, and the other by the other.

It must here be observed, that all the circumstances of this natural representatives.

temptation prove strongly the generally spiritual nature of the
Gospel-history, and evince that it treats of spiritual subjects under
Eor who can imagine that Jesus Christ,
as to his person, was thus at the disposal of the devil? was personally transported by him from the wilderness to a high mountain,
and thence to the summit of the temple in "the holy city?" or that,
to effect the temptation, Satan shewed himself in proper form, and carried it on by actual colloquy? And where could the mountain be found, so "exceeding high", that from the top of it might be seen, by any optics, "all the kingdoms of the world?"
Some of the critics would surmount this difficulty, by wishing us to believe,
that the world, here, only means the land of Judsea: but how will the phrase, "all the kingdoms of the w^orld", apply to this little
Doubtless, then, it was in spirit, and in vision, that speck of it?

these things were presented to the Saviour's perceptions; just as
Ezekiel was transported "in the visions of God to Jerusalem {,"
and as John also was "carried away in the spirit to a great
Thus the transaction, being altogether a and high mountain." §
spiritual one, must bear, in all its circumstances, a spiritual signification.

A mountain is a symbol, in the Scriptures, of an exalted state of love, either heavenly or infernal: to be incited, thence, to desire the possession of all the kingdoms of the world, is to be tempted with the lust of self-aggrandizement, either as regards the monopoly of all power, or of all wealth, or of both: to be set upon the pin-

* Ch. iv. 1 to 11.

f Ch. iv. 1 to 13,

% Ezek, viii. 3.

§ Rev. xxi. 10.
uncle of the temple, and thence incited to do a rash act that includes the persuasion of possessing divine power, is to be tempted by a still more extravagant species of the lust of power, -- what may be called the ecclesiastical thirst for dominion, -- that which aims at sovereignty over men's souls as well as their bodies.

But the ultimate end which is proposed by any passion that sways the human breast, is what determines its positive quality.
There doubtless have been Popes and Grand Lamas, who., in arrogating dominion over the souls of men, have made this pretension and lust subservient to the desire of temporal power and wealth: the latter have been their supreme objects of regard; and the former has been valued as a means to the attainment of these ends.

These then

Matthew.

have yielded to the suggestions of Satan, as they are represented by
Other occupants of the pontifical thrones of Rome and of Lassa, have unquestionably been possessed, as their ruling aim and object, with the lust of spiritual domination, and have grasped at temporal power and wealth as calculated to promote it: These as they are

This is even indi-

Thus, while it is perfectly evident that there then iiave adopted the persuasions of the devil,
arranged by Luke.
exist these two general kinds of the lust of domination, it appears no less certain, that each of them undergoes a modification, as it is made subservient, or paramount, to the other.
cated by the Evangelists in the minute distinctions of their language: thus Luke, who represents the appetite for temporal power and wealth as subservient to the ecclesiastical lust, calls the symbol of the state, simply a "high mountain;" whilst Matthew, who exhibits it as predominant, exalts its symbol into "an exceeding high mountain." Now it cannot be doubted, since the Saviour "was in all points tempted as we are*," -- was made sensible, in the human part of his constitution, of the strongest instigations to every evil that ever beset the most corrupt child of Adam; that the tempter injected the propensity to both these general evils in both
But the only way, in the lanthese states of their development.
guage of analogies, in which the two forms of them could be described, was, by placing the representatives of them before, and
To have done this in the same after, each other, respectively.
narrative would have appeared a strange tautology; neither would it have expressed the order of their manifestation or existence, the

* Heb. iv. 15.
one abiding within, or occupying a more interior sphere than the
Therefore the symbolic description of each is given in a other.
separate book: and as Matthew's Gospel treats of things in their more exterior, and Luke's in their more interior developments,
therefore, in agreement with the respective characters of the narratives, the more exterior and superficial development of these direful evils forms the subject of the temptation as described by the first Evangelist; while the latter represents them in their more interior form, and opens, in its still deeper recesses, their diabolical nature.

(7.) The only other case which we have to notice, is that in which Matthew cites a text, as from the prophet Jeremiah, which is only to be found in the book of Zechariah: he gives it thus:
" Then was fulfilled that which was spoken by Jeremy the prophet,
saying, And they took the thirty pieces of silver, the price of him that was valued, whom they of the children of Israel did value,
and gave them for the potter's field; as the Lord appointed me."*
In an ordinary writer, this certainly would argue strange negligence: but what if, occurring where it does, it affords a positive argument for the Evangelist's plenary inspiration? What if it should be absolutely impossible for a writer whose pen was irresistibly guided by the Spirit of God, to cite these words, how well soever he might know that he had read them in Zechariah, without ascribing them to Jeremiah?
Such, I apprehend, will readily appear to be the fact. And indeed, how is it possible that the change of name could have originated in mistake?
Is it credible that Matthew could know so little of the Scriptures as to be ignorant in what book the words were extant? And if so monstrous an improbability might for a moment be supposed, is it imaginable that, among those to whom he first communicated his
Gospel, there was none who possessed sufficient knowledge of the ancient Word, with which every Jew was familiar from his cradle,
to inform him of the erratum?

Eeally the difficulties of conceiv-

ing it to be an unintended error, are greater than those of supposing that it was a dictate from the Spirit of God: they indeed are such as directly point to this conclusion. And in this we shall find an easy and natural solution of the whole seeming in-

consistency.

* Matt, xxvii. 9, 10; Comp. Zech. xi. 12, 13.

15



If the Word of God be the Word of God indeed, it is a mere truism to affirm, that the Spirit which dictated it cannot possibly regard it as the work of men: consequently, that Spirit can nevei mean to ascribe any of its books to the men whose names they
Every prophet who was commissioned to deliver any portion bear.
of the Word of God, became, ipso facto, a representative type of the Word of God itself: specifically, of that portion of it which he was the instrument of writing. Now every such portion of it has a distinctive character of its own, more or less obviously discrimiSo plain is this, in some instances, as to have become pronated.
verbial: thus Isaiah is commonly called the evangelical prophet, on account of his open annunciations of the incarnation of the Lord and his advent in the flesh; and Jeremiah is popularly denominated the weeping prophet, for his pathetic lamentations over the fall and utter corruption of the Jewish Church, and its rejection and maltreatment of the Word of God, in its personal type, the prophet himself, and in its still plainer type, the roll of inspired writing which Jehoiakim committed to the flames.* When therefore a prophet is cited by name in the inspired writings, it is not that prophet, personally, that was in the mind of the Spirit of God nor even the specific book which bears his name: but his name is used as a symbol of all that portion of Scripture which is of the same character as belongs, generally, to the writings of the prophet named, whether occurring in his book or in any other.

Usually,

indeed, it cannot but happen, that the passage quoted is in the book of the prophet who stands as the type of that species of divine composition which distinguishes his own writings: but where occasion occurs for citing a passage of a different character from that which belongs, in general, to the book in which it is found,

and of the same as belongs to another principal prophet, Divine
Inspiration, which regards the intrinsic qualities of things and not merely their external circumstances, adduces the quotation in the name of the latter prophet instead of the former.
Of this, indeed,
only this one instance occurs: it cannot, therefore, be illustrated by other examples: but this one itself is admirably illustrative of the principle, and points to it with a clearness which it were difficult
The weeping prophet, Jeremiah, we have noticed to overlook.

though a real character, is a striking personification of that specier

* See Ch. xxxvi.
of Divine Truth, or of that portion of the Divine Word, which treats of the utter corruption of the Jewish Church, and its maltreatment of the Word: the latter is precisely the character of the divine declaration which is here cited as from him; it treats of the low estimation in which the Word was at this time held by the
Jews, who hoped to have purchased of Judas the power of destroying its actual personification, the Word incarnate. And whilst this passage is so decidedly of the same character as distinguishes the writings of Jeremiah, it as evidently does not at all belong to the general character of the book of Zechariah, which is mostly composed in a cheering strain, and dwells more upon the restoration of the church, and her glorious state in consequence of receiving the
Lord as the Word, than of her previous debasement and infidelity.
The two subjects are nearly connected together, since the one event follows the other; and hence the prophets seldom dwell long upon the desolation of the church and her rejection of the Lord, without some reference to her restoration and her reception of him: but the one subject constitutes the predominant topic of Jeremiah, and the other of Zechariah: wherefore the Spirit of Inspiration designates the statements which even Zechariah delivers on the former subject, by the name of its proper type, Jeremiah.

Surely I may be allowed to say, how satisfactory, and how beautiful, is this explanation !
It is a perfectly easy solution of a difficulty, which, upon every other theory, is insurmountable.*
But from our system it flows unforced; and not only so, but as a natural and necessary result. May we not then assume, that both the solution and the system must indubitably be true?

The Doctrine that the Sacred Scriptures every where contain a spiritual sense, for the sake of conveying which the letter is constructed, with a knowledge of the just mode of decyphering it by the Doctrine of Kepresentation and Analogy, will solve every other seeming contradiction in the statements of the inspired writers.

* It is affirmed by some, that Jeremiah is named instead of Zechariah,
because he anciently stood first in the copies of the prophets, and so might be taken as a name for them all: but that there is no authority for such an assertion, is sufficiently shewn in the Appendix, No. II. p. xiv.
Others consider the name of Jeremiah to be an accidental interpolation; but certainly it were such an interpolation as it could never come into the head of any scribe to make.



To examine, in this manner, all the passages in the Gospels which appear contradictory, would constitute a work of much interest but our design in the present work is, simply to lay down the principles upon which they are to be solved, and to illustrate the applicability of the theory to the facts, by such examples as might
This may now have been done.
be necessary for that purpose.
And I trust that it cannot but be seen, that varying statements,
proceeding from inspired pens, may all equally be true, and may detail circumstances which equally belong to the same transaction,

though sometimes, possibly, to such parts of it as were beyond the ken of ordinary observation, and could have been known to none
Of their inspiration, then, such circumbut inspired writers.
stances, fairly interpreted, actually become evidences. Thus in this case, as in every other, the system of interpretation which we propose, wrests the weapons of the infidel out of his hands, and makes them assist in demonstrating the divinity of the Scriptures.

3. On the Class of Objections which are drawn from the imperfect morality of some of the distinguished characters of the
Israelitish Church, little needs be added, after the view given of the design of the calling of that people, and of the nature of their his-

tory, in our last Lecture.

(1.) Admit the Israelites to have been chosen merely to represent the subjects belonging to the church; and consider all the persons distinguished among them as representative characters only;
and all difficulties arising from the questionable morality of some of them immediately disappear. We then see, how the record may be essentially the Word of God, notwithstanding the craft imputed to the immediate founder of the nation, their adherence to eastern manners in regard to the intercourse of the sexes, and the acts of violence and treachery which several of their heroes and heroines
Some of these might perhaps be allowable according to the laws of nations that prevailed in those distant scrupled not to commit.

were the subjects of a spiritual dispensation.

ages: but still they were such as could not, themselves, have been agreeable to the divine will, or have been practised by persons who
The slaughter,
noticed in our first Lecture, of Eglon by Ehud, though effected under fair pretences, and thus by treachery, was indeed no more than would have been done, and gloried in, by the most illustrious

heroes of Greece and Rome, among whom tyrannicide, by whatever means accomplished, was deemed highly meritorious: but it may be doubted whether any national opinions or customs would justify the still more insidious act of Jael. What then? Does this prove that the book in which they are recorded is not the Word of God?
Far from it.
It only proves that the Jews were not the subjects of a real church, possessing inward principles of life and grace,

but only of the type of a church, -- of a dispensation which sym-

bolized spiritual things by external acts, the performers of which might be far from any participation of spiritual feelings.

(2.) How heavenly things might be occasionally represented even by acts of violence, has been shewn at large in the last Lecture: and when this is seen, every objection which the infidel can raise against the divine origin of the Scriptures on this ground, is entirely surmounted. We also see how greatly they en*, who propose the exploits of the Jewish worthies, in their outward form, as things for the imitation of Christians; -- a principle which, at various periods, has been adopted by fanatics, who have perpetrated
The crimes of the Oldthe greatest outrages under its sanction.
Testament saints, as they are considered, have, likewise, always formed the main bulwark of Antinomianism; which hence has in-

vented the profane sentiment, 'that the saints are often permitted to fail into great sins, to convince them that salvation is by faith only,
and to make them more illustrious examples of the sovereignty of
But when David, for instance, is no longer considered as the pattern of a saint, but as the type of one, there is an end to grace.

the pretended sanction of lust and cruelty, drawn, and which I
have myself known to be drawn and openly avowed, from some of
The worst parts of his conduct will then only be his actions.
viewed as symbolizing the discovery which must be made to the highly graduated Christian, to become the ground of his humility and self-abhorrence, of the tendencies to evil which lurk iu the recesses of his heart; not as intimating that he may appropriate and practice such evils, and hope for impunity.
This will be perfectly evident, if we consider, for a moment, who that Saint or
Holy One specifically is, of whom David was eminently a type.
of the "King of saints*," -- the Lord Jesus Christ.

The king of Israel is allowed, in his highest reference, to be a type

But, he, it is

* Rev, sv. 3.


admitted by all, though "in all points tempted as we are/' yet was "without sin."*
Sin is evil appropriated in the will and thought, and brought, when convenient opportunity serves, into
Jesus was "without sin:" how then could David, in his act.
fall, be a type of him?
Because, though never was the slightest evil appropriated by the Eedeemer in will, thought, or act, but always instantly rejected with a "Get thee hence, Satanf;" yet,
in the nature taken by him from the human mother, were, before it was renewed by spiritual conflicts, the same tendencies as belong to ordinary humanity: As the Apostle declares, "In all things it behoved him to be made like unto his brethren p. "and since, in the nature taken from the mother, the likeness was so complete, "we have not a high priest who cannot be touched with the feeling of our infirmities." § Had it been otherwise, it would have been impossible for Hell to have approached him with temptations, and thus the great end of his coming would have been defeated; which,
according to the same Apostle, was, "that through death he might destroy him that had the power of death, that is, the devil; and deliver them who, through fear of death, were all their life-time subject to bondage." || The death he underwent included, not only the death of the material frame, but of every principle of his constitution which partook of human infirmity, and which presented an impediment to his returning to perfect union with his Father and this death he was undergoing through the whole period of his life: "I have a baptism to be baptized with; and how am I
The fall of David, then, restraitened till it be accomplished l"^f presented, not the falling into sin of Him who was "without sin",
but the deep temptations undergone by him, from the action of
"him that had the power of death" upon those principles of human nature appertaining to him which were susceptible of the influence: the remorse and penitence of David typified the utter rejection, by Jesus, of every thing in his nature which could be susceptible of such an excitement; and David's restoration to divine favour, the renewal of the Lord's human nature, and of every principle in it, by communication from his divine.

Now how could the perceptions andfeelings which must have been experienced by Jesus during the suffering of this inward process, be

* Heb. iv. 15.

f Matt. iv. 10.

U Ch. ii. 14, 15.

$ Heb. ii. 17.
% Luke xii. 50.

§ Ch. iv. 15.
otherwise represented, than by a detail of corresponding outward acts? And what could those outward acts which were positively sinful typify, in regard to Him who was without sin, but his experimental discovery, that the tendencies to it were inherent in that human nature of which he had become a partaker, and which in him, as in us, was to be "made perfect through sufferings?"*
For he, also,
"learned obedience by the things which he suffered; and being made perfect^ he became the Author of eternal salvation unto all them that obey him."f

What then is the doctrine taught by this part of the history of
What but this? that he has in his nature
David, to the Christian?
the seeds of the evils which in David proceeded to such flagitious acts. And what is the practical lesson taught by this part of
David's conduct, viewing him as the type of a saint, and decyphering the type by comparing it with the known Antitype, the king of saints? that it is excusable in the Christian, because he has the seeds of such evils in his nature, to adopt them in his will, or
No! but that, like the thought, or act, as was done by tlie type?
great Antitype, who alone is his pattern, he is to engage in conflict with them within; to reject them as soon as he is made sensible of their existence in his breast; and to seek from above for that renewal of the heart, which, far from favouring the least tendency to evil, delights in nothing but goodness and purity.
This is the real use which is to be made by the Christian of the history of David.
Referred to his acknowledged chief Antitype, it becomes intelligible at once. We are to study him as a type, not as an example, and are to take for our example the Antitype alone.
Accordingly, the
Lord never says to his disciples, "Follow David", but continually,
"Follow me."!

Under such views of the Word of God as these, what becomes of the blasphemous imputation of its encouraging immorality?

(4.) With regard to the charge of Insignificance, brought against great part of the Word of God, it cannot now be necessary to say a syllable. When it is seen that every part of the Sacred Records is profoundly significant, and that the most apparently trifling cere-

* Heb. ii. 10.

f Ch. v. 8, 9.

t Mat. iv. 19: viii. 22; ix. 9; xvi. 24; xix. 21; &c monies, directions, and statements, include representations of things of all others the most important to immortal beings; the imputation against them of Insignificance comes with the same weight, as would attend a decree, censuring the structure of the universe, and pronouncing the unimportance of the stars, issued by a conclave of moles.

After this view of the bearing of all Infidel objections against the
Word of God as rightly understood, may it not be assumed as certain, that all such objections arise from taking a merely super-

ficial view of the Sacred Scriptures, and from an utter ignorance of their true nature?

May I, then, now hope, that the affirmation made in the first
Lecture* will be considered as made good?
Does it not clearly appear, that to adduce from such considerations as are urged by
Deists an argument against the divine inspiration of the Scriptures,

is entirely to mistake the whole nature of the case?

Is it not evident, that the argument thence deduced falls to the ground of itself, as soon as the true nature of the Word of God is seen, and the design is regarded with which it was given to mankind?
In short, is it not a fact, that a view of the true nature of the Divine
Word overturns from the foundation the whole fabric of Infidel
Objections? that it takes the ground on which the Infidel stands in making his objections, entirely away from under his feet?

III. But although the objections of Infidels avail nothing whatever against the Word of God, as it is in itself, they are not so contemptible when urged against the views of it which commonly
They afford no argument at all when advanced to prove prevail.
that the Scriptures have no origin in Divine Authority; but they yield an irrefragable one when applied, as they only ought to be applied, to evince that the Scriptures must contain mucli more in their bosom than is extant on the surface.

On this subject, then, I fain would address an earnest appeal to all Christian advocates, and to all the portion of the Christian world in general, who adhere to the merely literal interpretation.
I would say to them, with all respect, Consider, my brethren,
whose zeal in the cause of what you believe to be the truth I

* Page 23.


venerate, and who, I doubt not, are actuated by a sincere desire to uphold the credit of the Word of God, how much you compromise that credit, when you affirm, (as we have seen is now so generally the case,) that the Scriptures are every where to be understood according to the letter alone;

that no spiritual sense is to be looked for, unless, perchance, in those passages where it is expressly referred to in the New Testament; that the inspiration by which they were written, so far from being plenary, and dictating the very words to the writers, did not even secure them from any but "material errors."
It is true, probably, that you have adopted these views of the Scriptures, from disgust at the absurdities and abominations which have formerly been advanced, drawn, as was pretended, from their spiritual sense: but are you sure, that while you thus flee from a lion, you have not been met by a bear?*
the literal sense attended with no difficulties? and is the abiding,
simply, by it, an unfailing preservative from all delusion and error?
Are not some of the greatest delusions, such as have just been noticed of the Antinomians and other fanatics, the offspring of the
Assuredly, then, even if, by embracing separated letter alone?
such ideas of the Word of God, you afforded no advantage to the enemies of religion, you deprive your own souls of great benefits,
and expose yourselves to very serious mistakes.

Is

But when, by thus binding the understanding to the letter alone,
you give so great odds to our Deistical and other adversaries, and so encumber the Christian cause with difficulties not its own, as to render it, in the eye of reason, almost untenable; how serious inThe objections, for example,
deed does the mischief become !
which are urged from the literal sense of the beginning of Genesis,

are fully demonstrative against the credibility of that sense taken alone: they thus, as we have seen, point to the real divinity of the
Word, by pointing to a spiritual sense: why then give them a direction, which, without abating an atom of their force, makes them fatal to the divinity of
The whole style of the narration in those chapters is such as might satisfy any one, that the literal sense is not that which is intended. Many the Word altogether?

(

* Amos v. 19.

The lion, when mentioned in a bad sense, is the symbol of snch false persuasions as arise from the perversion of the interiors of the Word the bear, of such as result from abiding by the letter alone, without understanding it.

15*


circumstances are introduced which are clearly designed, among their other uses, to demonstrate, that a spiritual sense only is what

In what a situation, then, is the modest inquirer is proposed.
placed, when he is told, that he must either give his faith to incredibilities which bear palpable marks that they were intended to be regarded as incredibilities, or must reject the record altogether ! Any one who believes in a God, may believe that, on occasions sufficiently important, a miracle may be performed, -- 
deviation may take place from the customary proceedings of nature;
and he will not reject a narration assuming to be divine for affirming such facts: but the marvels of the first chapters of

Genesis are not delivered as miracles, but as things in the com-

mon course of events; and the most extraordinary of them, -- the talking of the serpent, -- if it is to be taken as a miracle, was wrought, not by the hand of God, but of Satan; of whom, neverTo insist then that the theless, not a word is said in the letter.
literal sense is here to be believed; and not only so, is all that is to be believed; if it is not crucifying the Son of man afresh, is delivering him, bound, into the hands of Pilate and his soldiers, to be by them mocked, and scourged, and crucified.
The infidel,
amid his scoffs, may now quote in extenuation the divine declaration, "He that hath delivered me unto thee, hath the greater sin."*
Indeed, the literal interpreters ascribe such absurdities to the letter of the Word as are not to be found in it:
marked, the Sacred Narrative does not, with these interpreters,

for, as has been well re-

of natural fruit-tree whatever.

refer the cause of the fall to the eating of the produce of any sort
But when Condorcet ridicules
Christianity for imputing the origin of evil to Eve's eating an apple; if he were asked where he learned this, when the Sacred
Record says nothing of a tree that bore apples or any such fruit,
but calls it "the tree of the knowledge of good and evil", --  thus plainly intimating that a spiritual, not a natural tree is signified he might answer in excuse, "The orthodox told me so:" and
Voltaire might make the same apology for his jests upon Eve's tete a tete with a serpent. How much better was the chance which Christianity stood with her adversaries, when Origen could reproach Celsus with dissembling what he could not but know,
that the whole history is an allegory, and was so considered by

* John xix. 11.
those whom he was attacking!
Were this the unanimous confession of Christians now, what modern Celsus would think of again levelling the shafts of ridicule, thus deprived of their point?
Before he could find a butt to aim at, he must, like Bolingbroke,
change sides with modern Christian advocates, and prove, what they have laboured at so long, that the literal -sense is what we are here to abide by: and as the proof of this would be as impossible to him as to them, this part of the Word of God would stand for ever invulnerable to his assaults.

The difficulties under which the Christian advocate labours in defending the Scriptures, by their literal sense alone, from the charge of contradictions, are not, perhaps, quite so great; but still they are such as ought to convince him of the necessity of
I wish not to detract recurring to higher views of the subject.
from the usefulness of the harmonists; though I think that no one can ever have read what is called a Harmony of the Gospels, combining their respective narratives into one, without feeling himself in a maze of confusion, the consequence of its jumbling together things which Infinite Wisdom provided and intended should be
I acknowledge, however, the validity of some of the kept distinct.
solutions of seeming contradictions drawn out of the literal sense alone: but in general, I think, it must be allowed, that to seal that validity, and entitle it to pass without dispute, higher interpretations must be joined with them:
for though the solutions drawn from the letter alone, in many instances may be true, a still wanting why the appearance of a contradiction reason is should exist, -- why the direct literal interpretation should often be where doubt has once entered, tliey can never expel it.

It must be allowed, too, after such as to involve a contradiction.
all, that many of the solutions attempted to be drawn from the letter alone, so desperately torture it to wring them out, that,
Your very
" The violent methods", says Michaelis,
friends confess this.
" which have been used to reconcile the accounts of Mark and
Luke with those of the other Evangelists, and the insuperable difficulty which has hitherto attended the harmony of the Gospels,
have cast a dark shade on our religion, and the truth and simplicity of its history have been almost buried under the weight of explanations."* Why then, my brethren, not accept the views
* Introd. Vol. i. Ch. iii. Sec 3.
which alone can satisfactorily remove all difficulty? Why present the Scripture as a jewel of agate, carved in such a manner as is little suited for ornament, and yet insist that its value consists in its outside appearance alone; when the reasons of its peculiarity of form would immediately appear, were it known, that it was made to open, and that its singular shape arose from its exact adaptation to hold and preserve the rubies and diamonds which glow within?
Why allow the world to condemn as flaws, what are merely the junctures, designed to lead the examiner from the surface to the contents?

But again: Most certainly, none but such views as we have offered of the nature of the Israelitish dispensation, can meet the objections of the Deist on the score of the immoral conduct, and the acts of wrong and outrage, committed by those who, if we refuse to look beyond the letter, were the personal favourites of
You deny, (most of you,) a typical character to any perheaven.
sons or actions which are not expressly recognised in that capacity,
in the New Testament.
You deny then such a character to Jael and her slaughter of Sisera: then how justify or excuse them?
It is in vain to say, as some have done, that this was a transaction for which the performer alone was accountable, it not being owned by the God of the Scriptures; whereas, as noticed in our first
Lecture, it is expressly eulogized by the voice of prophecy.
With what sort of feelings do you read of a woman's killing her guest in his sleep, while you believe that it was the act itself,
and not something represented by it, which was really agreeable to him who hath said, "Thou shalt not kill?" Beautiful and impressive does the narrative become, when we read in it the manner in which wicked persons of the specific character represented by Sisera,
endeavour to escape detection, by lurking behind the assumed appearance of that species of good of which Jael is the type; and how, when they have thus filled up the measure of their iniquity by adding hypocrisy to their other vices, they sink into a merely natural state, of which sleep is the symbol, and thence pass, un-

consciously, into complete spiritual death; nailed to the earth, -- 

to earth-born feelings, -- for ever.

Jael is thus seen as the repre-

sentative of goodness of a genuine kind, which does not suffer itself to be prostituted by being made a cover to vice.
Here is something on which the divine approbation cannot but rest:

but,



without it, how vindicate the transaction?
Persons even of the best disposed minds, while they look at nothing beyond the letter,
cannot reconcile such a deed with the universal command prohibitory of murder, but by affirming, that he who gave the precept,
retains the right, when he sees fit, to remit its obligation; that the occasions for its suspension were communicated to such characters as Jael by a divine impulse; and that the slaughter which ensued
But what a then became, instead of murder, a judicial infliction.
door would be opened by this casuistry to the most horrid enor-

mities ! and not a few have actually been perpetrated under its
If a judicial infliction were all that was intended, how sanction.
much more impressively would this be exhibited by an immediate visitation, as in the cases of Ananias and Sapphira !*

Indeed,

the sentiment leads directly to the conclusion, that there is no such thing as immutable right or wrong; that He who gave the moral code could reverse it also. But what a being does this make
Does it not paint him like those of the Author of creation !
tyrants that blot the pages of history, who made their mere will the law, and whose will was guided by caprice alone?
It is true,
that the will of God is, and ever must be, the standard of morals,
and that obedience to it must always remain the test of virtue: but to imagine that his will can be mutable; that it is not unalterably determined to goodness in the abstract; and that essential good-

ness can ever be any thing else than love, or its duties any but such as love would dictate: -- surely this is to display any but a
It is, in fact, to deny to God any just idea of the Divine Nature !
unalterable attribute but that of Infinite Power: and the worshipers of mere Power, it may fairly be affirmed, would worship Satan himself, had it been possible for him to have succeeded in the enterprise which is ascribed to him, and to have seized the throne of heaven.

tures of Truth.

Consider, then, I beseech you, my Christian brethren, the consequences in which you involve yourselves, and the cause of God and of Truth, by denying a regular spiritual sense to the ScripConsider how this persuasion degrades the Word of God, and disgraces its Divine Author.
Believe it to be possible that inspiration really may be inspiration; that the Word of God may be the Word of God indeed, and that the wisdom of God may
* Acts v.




Look for it then, as you would look be actually included in it.
for God himself.
As you do not expect to find him in the scenes of nature, but in the inmost sphere of mind; so neither is it reasonable to expect to find his pure wisdom in the outward letter
Look again, I would also of his Word, but in a sphere within it.
Pretend not to meet intreat you, at the objections of the Infidels.
them in their own valley, where they can deploy their nine hundred chariots of iron; but let the array they make there convince you,
as it did Barak*, of the necessity of taking that elevated station which is your proper sphere, and of rushing down upon them from
Suffer them not to persuade you that the Scriptures are thence.
not the Word of God; but permit them to point out to you what
Thus will the weapons of the their nature must be if they are.
Infidel be wrested out of his hands, and made efficient to his discomfiture; as the sword of Goliath became an instrument of mighty
But unless you deal with efficacy when wielded by a David.f them thus, they will eventually accomplish the object at which they
Either Christians must rise to higher views of the nature of aim.

the Scriptures, and of the laws of their composition, or, I presume to affirm, the day will come, when all veneration for them as the proper Word of God, all belief of their having been dictated by any thing at all worthy of the name of Inspiration, all sanse of their inherent sanctity, and all communication by means of them with God and heaven, will cease to exist through the greater
Avert, I beseech you, the catasportion of the Christian world.

trophe, by preserving the Palladium in the centre of the Christian
Cast not the Ark of the Testimony out of the Holy Place.

Temple.
Regard the Word as possessing an internal principle within it and then, and then only, you may defy the fiercest attacks upon the outer bulwarks.

IV. But it is time to turn to the Deists: and to them I would say, Imagine not, men and brethren, should even the half of Christendom openly go over to your side, that you have obtained any victory over Christianity or over the Word of God.
yourselves that your success were the triumph of truth over error

Platter not it were nothing, be assured, but a triumph of one species of error over another, -- of simple fallacy over falsified truth.

It were not a

* Judges iv. 12, 13, 14.

f 1 Sam. xvii. 51 ,* Ch. xxi. 9.
all, that it be understood at triumph of the light of nature over the light of the Word, but over a view of the Word which extinguishes its light and that of nature
It has become the general opinion of Christians, that the together.
Divine Word is to be understood in its literal sense alone; or rather, as, when looked at merely in the letter, it often cannot is to be simply believed; you and as you look at it with these preconceived impressions;
thus find in it much that you cannot believe, and are not led to look for its time meaning in a higher sense, you reject
But what you thus reject is not so properly the Word
Itself, as a mistaken idea of it, which you have taken from those whom you regard as its proper interpreters. A very different view of the Divine Book, and to which, as we have seen, none of your objections are in the slightest degree applicable, has now been laid
As was observed to me by a gentleman, once of before you.
your sentiments, who saw, as soon as this view was presented to him, that against the Scriptures, thus interpreted, nothing which it.

he had read in the deistical writers would attach; -- your Paines and
Volneys would here have all their work to begin again. An opportunity then is now afforded you, of trying the sincerity of that love of truth which you profess so loudly: for here, I hesitate not to say, is offered you the truth itself; that is, a just view of the Word of Truth itself; and this declares, by its proper organ, the mouth of the Word Incarnate, "Every one that is of the truth heareth my words."

But, alas ! I know too well how many causes, very different from the proper love of truth, tend to swell the ranks of Infidelity, to expect that any great proportion of you will listen to this appeal.
Though perfectly satisfied that the view here offered is the truth,
I by no means expect that it will satisfy those confirmed deniers of the inspiration of the Scriptures, who, instead of being desirous to know the will of God in order that they may do it, would be better pleased to obtain demonstration that there were no God at all whose will they need consider; -- that they are free from all ob-

Of those who, from ligation of regarding any will but their own.
this ground, "hear not Moses and the prophets", Divine Truth has declared, that "neither would they be persuaded, though one rose
But to such of you as are of a different characfrom the dead."*

* Luke xvi. 31.


ter who Lave fallen into states of doubt, in consequence of having been led to fix your attention upon those parts of the Scriptures,
which, when regarded as to the literal statements alone, appear repugnant to reason, but who feel uneasiness in consequence, and would gladly see a way by which your difficulties might be removed;
the view which has been developed may certainly afford all the satisfaction which you can desire.

Since then there are two so very different origins of scepticism,
I would earnestly and affectionately exhort every one who is in such a state, or who feels a tendency towards it, dispassionately to examine his own heart, in order to ascertain the first source of his impressions. You will all, perhaps, eagerly reply, that you follow in your sentiments nothing but the unbiassed suggestions of reaI would ask in return, Are you sure of that? Every philososon.
pher knows what an extraordinary influence is exercised by the inclinations of the will over the conclusions of the understanding it has even become a proverbial remark, that whatsoever a man ardently wishes to find true, he seldom fails in the end to persuade
Let then every one, before he trusts too implicitly himself is true.
to what he deems the dictates of his reason, faithfully ascertain,
whether he inwardly wishes to find that which is offered him as a
Divine Revelation true or false: and whether, in the event of sufficient evidence of its truth being presented, he is prepared,
cheerfully and without reserve, to follow the course of duty which
It he can answer this inquiry in the affirmative, then it enjoins.
can we allow him to be an impartial inquirer after truth, all whose
Another test by which scruples we are convinced we could satisfy.
any one may judge of his own impartiality, is this: Does he find as much satisfaction, when looking over the Scriptures, in those passages which present truly exalted ideas of God, and the most pure and sublime precepts of moral duty, as when he discovers statements which, to his notions, appear extravagant and irreconcilable to reaDoes he look for and dwell upon these with satisfaction and son?
triumph? and does he feel not disposed to look attentively at the others, but to slur them over, experiencing something like mortification at finding any thing indisputably excellent in a book which he would fain regard as worthy of nothing but contempt?
If so, it is plain to which of the two classes of sceptics before described he belongs, and he will do well to relinquish his boast of impartiality,
and to allow that his rejection of the Scriptures is not the result of reason but of prejudice; -- of prejudice, the offspring of pride and self-conceit, if not of more palpably disgraceful vices.

He, on the other hand, who is really disposed to look impartially at the matter, must surely feel his heart glow with inward devotion, when he reads such a description of the Divine Majesty, as we quoted, in our first Lecture, from Isaiah; in which, as in many other instances, the great attributes of Infinity and Eternity are exhibited with a sublimity and force to which Philosophy never preAnd again: while the Scriptures so excel in describing tended.
the Divine Majesty and attributes, when did Philosophy deliver so striking and affecting a delineation of the whole duty of man, both to God and his fellow- creatures, as in the declarations of Moses,
quoted by Jesus Christ as the proper answer to an enquirer, who asked, "What was the great commandment of the law."
" The first of all the commandments", said he, "is,[ Hear, O Israel, the
Lord thy God is one Lord: and thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind,
and with all thy strength: And the second is like unto it: Thou shalt love thy neighbour as thyself:" to which he adds this emphatic declaration: "On these two commandments hang all the
Here we are plainly instructed, that to law and the prophets."*
inculcate love to God and man is the design of the whole Word of
God: if then there are any parts of that Word in which this design does not appear upon the surface, the just inference is, that there is something beneath the surface which does not shew itself on a superficial inspection.
again,
in that other beautiful and impressive summary of all moral duty: "Whatsoever ye would that men should do unto you, even so do ye unto them;" to which also the Divine Speaker adds, "for this is the law and the prophets."f
Now, surely, none who is animated by a sincere affection for truth,
and who actually loves the charity which he is so ready to eulogize, can help feeling deeply affected by such touching appeals to the heart and conscience as these; and he who thus feels their power cannot be disposed eagerly to reject, as a fable or a forgery,
the whole book in which they are found, and of which they are a part; especially, too, when these declarations affirm so positively that all the rest of the book is of the same character as themselves.

So,

* Matt. xsii. 36 to 40.

f Ch. vii. 12.



Let him then listen candidly to a system which points out how the rest of the book is of the same character as these specimens; which evinces, that there is a spiritual sense contained throughout the whole, which shines plainly through the very letter in such passages as we have just quoted, but which equally exists every where else, though veiled from immediate view by a clothing of images
In short, every one who is not taken from natural objects.
rendered inimical to the Word of God by passion, prejudice, or pride, may find abundant reason to conclude in its favour upon a candid examination of the general scope of its letter: he may there find, for himself* plain indications that it is inwardly replenished with real divine wisdom: and when he sees this proved by the views of its nature which have now been developed, he surely will take it to his bosom, and thank its Author for the invaluable boon.

I conclude with expressing a devout hope, that the Author of the Word of God will accompany this attempt at its vindication with his blessing. May the number of the sincere and devotional lovers of Truth, of all classes and of all parties, be rapidly in*
creased ! May they learn to venerate the Word of God as the
Word of God, and draw ftom its exhaustless bosom the streams of
Believing, also, the view of the nature of the genuine truth !
Scriptures of which a faint sketch has now been given, to be the truth; and feeling the powerful, the unalterable conviction of their divinity which the reception of it imparts; »I add, May mankind in general be speedily brought to do justice to a system, which sets the feet of the disciple of Eevelation on a rock of adamant, and invests him with a panoply of strength, aimed against which, the keenest shafts of Infidelity will ever fall blunted and harmless 1

END OP THE LECTURES.

== APPENDIX

