
=== LECTURE III - THE LAW OR RULE EXPLAINED ACCORDING TO WHICH THE SCRIPTURES ARE WRITTEN

----
Preliminary remark, on the Reasons why the Scriptures are not written in plainer
I. A Universal Rule of Interpretation afforded in the language --  Short Recapitulation.
Mutual Relation, which exists by creation, between things natural or material, spiritual
II. The nature of this Relation considered: -- !. The whole or moral, and divine.
Universe an out-birth from the Deity whence it bears, in all its parts, an immutable relation to the attributes which belong to the Divine Essence. -- 2. That on all things belonging to the moral, intellectual, and spiritual worlds, the Divine Creator has tl:us first stamped a certain image of himself: --  3. And that he has done the same, though under a totally different form, on all the objects of outward and material nature: -- 
4. Whence all things in Nature, being outward productions from inward essences, are natural, sensible, and material types of moral, intellectual, and spiritual antitypes, and
III. That, were the Relation between these different finally of their prototypes in God.
orders of existences fully understood, a style of writing might be constructed, in which,
while none but natural images were used, purely intellectual ideas should be most fully expressed. --  1. That this is in a great measure intuitively perceived by all mankind, and is the origin of many forms of speech in common use. --  2. Palpable instances of the occurrence of such forms of speech in the Holy Word. -- IV. That in ancient times this constant Relation between things natural, moral or spiritual, and divine, was extensively understood: --  1. Proved from intimations in the historical parts of Scripture. -- 2. Confirmatory remarks, drawn from the mythological fables of the Greeks and Asiatics, and the Hieroglyphics of Egypt. -- V. That in this Relation, then, is to be found the Law or
Rule according to which the Scriptures are written, and that a knowledge of it will afford the key by which their "dark sayings" must be decyphered.
----

We now approach a part of our inquiry of the very greatest importance; for we are now to investigate what the Law or Rule is,
by which the Holy Scriptures or Word of God are written; and this, being a subject of deep investigation, will require to be gone into with very close and serious attention.
It is not, indeed, in itself, extremely difficult of comprehension: on the contrary, I am satisfied that it is capable of being made very plain and easy; and even, if sufficient attention be given, that the arguments and instances by which it may be supported, will be found as interesting, as the subject itself is great and important: but it is usual with many, in this superficial age, to be indisposed to any inquiry
Especially on the that requires the exercise of fixed attention.
subject of religion, it is common, with great numbers, to be unwilling to regard any thing which is not obvious at first sight.
Indeed, this forms one of the objections of Deists against the
Christian Revelation in general; and will perhaps be still more positively urged against the view of it, which we are endeavouring to establish: we will therefore here meet it with a few remarks.

The Scriptures contain many things, the Deists allege, which, it is allowed on all hands, are hard to be understood; if then the belief of them is so important to man's welfare, why, they demand,
is not some standing miracle wrought to assure us of their truth?
And one of the most determined infidels has insolently suggested,
as a suitable expedient*, that God ought to cause a permanent in*
scription to appear on the face of the sun, assuring mankind,

through all countries and all ages, that the Scriptures are true.
But they who propose such expedients as these, only shew how utterly ignorant they are, both of the nature of God, and of the nature of man; and how destitute they are of any idea of the laws of infinite wisdom, by which God regulates his dealings with man.
A conviction forced upon man against his will, would not be permanent, nor really beneficial to him; but, on the contrary, it would expose him to the danger of incurring far greater guilt than he can possibly rush into while he is left to the uncontrolled exercise of his own freedom, and while the light of Divine Truth is not poured on his mind with such lustre, as absolutely to compel his assent.
It is for this reason, among others, that divine Eevelation <is always couched in language that is in a great measure parabolic and obThough capable of being easily understood, at least as scure.
to every thing essential, by those who are influenced by a sincere desire to know the will of God in order that they may do it,

according to the divine declaration of Jesus Christ -- "If any man will do his will, he shall know of the doctrine whether it be of
God f j" -- it yet is not made so plain throughout, as to aggravate the condemnation of those, who, being disposed to do his will, and only anxious to find pretences to free themselves from the obligation of doing it, would be, in fact, the more offended at any revelation,
just in proportion as they found it more difficult to devise plausible reasons for denying its authority.

the humble inquirers, -- are meant by the disciples, and the latter the pertinacious cavillers, -- by the "others", or "them that are

The former class of persons

* Paine, Age of Reason, part 3.

f J°nn v"« *7.


without", in that saying of Jesus Christ in which he developes the law of Divine Mercy and Wisdom on this subject: "To you", he says, addressing the disciples, "it is given to know the mysteries of the kingdom of heaven; but to others, in parables; that seeing they might see and not perceive, and hearing they might hear and not understand* :" by which words is not meant that an arbitrary distinction is made between one portion of mankind and the rest,
but that divine revelation is so framed, as not to force conviction on the understanding, where there is a determined resistance in the will; because, if such persons should be made to assent for a time,
their evil propensities would afterwards break out and cany them away: they would then deny the clearest demonstrations of divine truth; and even had miracles been wrought for their conviction,
they would deny these also, resolving them into some accountable
The guilt thus incurred would be that of
This state is described by Jesus Christ in the mysprofanation.
terious parable of the man out of whom the evil spirit went, but who, finding no rest in his new state, returned to his former house,
taking with him seven other spirits more wicked than the other of whom the Lord says, "And the last state of that man is worse
The first state of this man, is the state of unrethan the first." f formed man in general: the going out of the evil spirit, is his commencement of a new order of life, in consequence of opening his mind to a conviction of the truth of divine revelation and its doctrines, which banishes for a time his spirit of incredulity: his walking through dry places, seeking rest and finding none, implies,
that he finds his new state to be without enjoyment, because in contrariety to the lusts which were delightful to him, and which operations of nature.

he is still unwilling to relinquish: his returning to the house from which he came out, is a relapse into his former state of mind; but that this state is now attended with profanation, and is incomparably worse than before, because, to return to it, he is obliged to extinguish the convictions he had received, is expressed by its being said, that he took with him seven other spirits more wicked than himself, and that the last state of that man is worse than the first.
It is, then, because Divine Providence is ever watchful to prevent man from falling into so deplorable a state as this, that difficulties are allowed to appear ou the surface of the Word of God; and it

* Luke viii. 10; Mark iv. 11.

t Matt. xiL 45.


is for this, among other reasons, that it is so generally written in the language of parable.

I expect, however, that the infidel (by which term I mean the confirmed denier of revelation, -- one whose denial is grounded in a

Be it so.

wish to justify himself in the gratification of his corrupt passions,)
I would however entreat him will call this, preaching.
seriously to look at the doctrine so preached. He must, I am sure, find it agreeable to the purest reason, though such as reason,
unenlightened by revelation, might not have been able to discover.
He must also admit, that the economy of Divine Providence which the doctrine unfolds, is equally wise and beneficent, -- such as might be expected to direct the conduct of a Being of infinite wisdom and
Whether goodness, in his dealings with a frail creature, like man.

then this be preaching or philosophizing, there is assuredly a strong presumption that it is pure truth: and this should recommend it to the favourable attention of those, who affect to hold pure truth
Would mankind but view the Scriptures in so much veneration.
according to their real nature, as faintly described in our last Lecture, and understand them by the Kule which we are next to endeavour to explain, they would find them philosophizing according to the purest truth in every part, -- every where preaching the most soul-exalting lessons of heavenly wisdom 1

I have been led to make these remarks, that we might not appear to leave too long out of sight one of the objects of these Lectures,
 -- the refutation of infidel objections to divine revelation, -- while we are chiefly intent upon the other, -- the proof of the plenary inspiration the Word of God: -- though this, indeed, carries with it the former: for when once it is seen that the Word of God is actually written by a plenary divine inspiration, all objections against its being received as such, fall to the ground of course.
In our last
Lecture, then, we endeavoured to prepare the way for the establishment of this point. We shewed, first, that the Scriptures do claim for themselves the title, "the Word of God", and do affirm of themselves, that they are written by the fullest inspiration of God.
We then considered, from rational and philosophical grounds, what must be the nature of a composition which has God for its Author;
when we found that the Word of God must be exactly like his works, -- that as these contain within them wonderful parts which do not appear on their surface, so must the Word of God include a superficial inspection.

in its bosom boundless stores of wisdom beyond what appears on
In the third place, we examined whether this conclusion of reason is supported by any plain declarations of
Scripture; of which many instances were presented: indeed we found the Lord Jesus Christ directing his hearers to regard the inward spirit and life of his words, and not to suppose his meaning confined to the outward expression i we ascertained, also, that the

Apostles, in their writings, continually testify to the existence of an inward or spiritual sense throughout the Word of God; and we demonstrated, in addition, that hence this belief, in the days of primitive Christianity, was universal; that, for many ages, it was never doubted; and that it has continued to be the opinion, to a greater or less extent, of many intelligent theological writers down to the present day. We take this testimony then, joined with the inherent reason of the thing itself, to be conclusive as to the reality of the fact, -- that the Word of God does, in every part, contain a spiritual sense, treating of things in which man is interested as a spiritual being and an heir of immortality.

We are not obliged, however, be it again remembered, nor do we by any means undertake, because we conceive the fact, -- that the
Scriptures contain a meaning beyond the letter, -- to be a matter of absolute certainty, to defend all the interpretations which at various times have been offered to the world, as resulting from, or as being,
this spiritual sense: we are even ready to allow, that very idle and unfounded explications have sometims been obtruded on the public,
under the pretended sanction of this great general truth; and we are not surprised that some of the critics, disgusted with the un-

literal sense alone.

certainty which prevailed in the efforts to decypher the spiritual sense, by persons who possessed no certain rule to guide them in the attempt, have relinquished the principle altogether, and have begun to teach, that the Scriptures are to be understood in their
But we contend most decidedly, that the abuse
In of a good principle is no argument against its legitimate use.
all other cases this maxim is accepted as an axiom: if we deny it,
we must deny everything; at least we must involve ourselves in
Indeed, to argue from the cheerless gloom of universal scepticism.
the abuse of any sentiment against its use, will plunge us continually into the most palpable absurdities.
It is a truth, for instance, which all men of reason admit, that there is a God.

\\ e find this belief universal throughout the world. Now because it is unquestionably true that there is a God, it certainly by no means follows, that all the notions which all nations and religions have taught respecting him, are true likewise: but most assuredly it does not follow, because most nations and religions have erred in their notions of God, that, therefore, there is no God at all: on the contrary, the general belief, in some shape or other, in the existence of a God, however superstition and ignorance may have clouded the pure truth respecting his nature and the mode of his existence, has always been regarded as an insuperable argument in favour of the sentiment, that the existence of a Divine Being is certain, beyond dispute.

Equally strong is the argument, from the general belief of there being a spiritual sense in the Scriptures,

that there really is such a sense: and inconsistent or unfounded notions respecting the nature of that sense, no more prove that there is no such sense at all, than similar errors attending the belief in the existence of a God, can prove that there is no God.

1. Now what has been wanting to recommend the spiritual sense of the Word of God to the acceptance of the calm, reasoning mind, has been, a certain rule by which it may be decyphered.
Could such a rule be shewn to exist, the objections drawn from the tendency of the admission of a spiritual sense to introduce uncertainty and confusion into the explanation of Scripture, would,

as stated in our last, fall at once to the ground: and the existence of such a sense, which multitudes have acknowledged by a kind of intuitive perception, would then be bottomed upon the clearest rational induction; -- would indeed admit of demonstration not less convincing, though of a somewhat different kind, than that which evinces the truth of any problem in mathematics.

Such a rule, then, it is conceived, is afforded, in the Mutual
Relation which exists by creation between things natural or material, spiritual or moral, and divine; which is such that the lower order of objects answers to the higher, as certainly and immutably,

as the reflection in a mirror answers to the substances producing it.

But, alas ! though this was a subject well understood in the times of remote antiquity, it now is not only generally unknown that the Holy Scriptures are written according to this Relation,
from which, therefore, we may obtain a Universal Eule for their interpretation; but it is even far from being generally known that any such Eelation exists.
Approximations have indeed been recently made towards its re-discovery, as will be noticed in the sequel; and there is reason to expect that,

ere long, it will seriously occupy the attention of the scientific and religious public.
In the hope of promoting this desirable event; and because all that is to follow in these Lectures will refer to it as a first principle; a slight attempt shall here be made to give a general idea of its

Nature.

II. That there exists, by the laws of creation, a Mutual Eelation between things natural or material, spiritual or moral, and divine, may be concluded from the indisputable fact, that every thing in a lower sphere of existence is produced for the sake of something in a higher;

and if so, every higher thing, for the sake of which any object of a lower kind is produced, is the proximate cause, by derivation from the
First Cause, of the existence of the latter: and there must be an uninterrupted series of such causes and effects, each intermediate effect becoming, in succession, a proximate cause of existence to something beneath it, from the First Cause itself, to the lowest effects of all.

Every proximate cause, also, by the urgency, and for the sake of which, something beneath it was produced, is, likewise, the real essence, or ground of being, of such lower production, which,

on its part, is thus an outward form, manifesting the existence of
This will lead us to see, that the lower such distinct essence.
orders of objects must answer to the higher, as certainly and immutably, as the reflection in a mirror answers to the substance pro-

Thus, for example, every lower thing that exists is ducing it.
produced to serve, either more nearly or remotely, to the use of man: this being the second cause of its existence, the thing itself is actually an image, under a different form, of something that is in man: and man himself was produced to satisfy the divine love f God -- thus for the sake of God, that there might be a being in the world capable of receiving, in a conscious manner, gifts from
God, and of returning them to Him in love and adoration: and
God himself thus being to man both the proximate and First Cause of his existence, man must be, in a certain manner, an image oi
God; and the most immediately so of anv thing that the world contains. We accordingly are assured by divine Eevelation, that
And if man,
man was created in the image and likeness of God.
altogether, is, in a certain manner, an image of God, it follows evidently, that every particular thing which exists in man, (so far as he stands in the order of his creation,) is an image of something that exists in God: and, indeed, every thing in him which is not in the order of his creation, but which he has introduced by the abuse of his faculties, still has reference to something that exists in God,
In short, as God is though not as an image, but as an opposite.
the Origin and First Cause of all things, it is evident, that nothing whatever can exist which has not some sort of reference to something that is in Him; which reference is nearer or more remote, in proportion as the sphere in which it stands is nearer to the divine
Thus centre or to the extreme circumference of the universe.
things natural and material bear a secret Eelation to things moral and spiritual, and these again to things divine.

1 . This will be seen yet more evidently when it is considered,
that the proper mode of viewing the creation, is, to regard it as an Out-birth from the Deity; -- as a production essentially distinct from the Producing Cause, but necessarily bearing, through all its parts, to that Infinite Cause, and to the infinite essential properties and attributes existing in that Cause, a constant and immutable
Eelation. Among the objects of the visible creation, man, the acknowledged image of his Maker, stands in the highest degree of this Eelation, and the inert substances of the mineral kingdom in the lowest. This truth is not invalidated by the fact, that the latter
It must unquestionably be true, that, in came first into existence.
the creation of the world, the globe of earth and water, or the unorganised parts of its composition, though lowest in rank, must have been the first that were formed: but why? because their uses were indispensable to the higher orders of existence, to afford them nutriment and a basis.
Then, doubtless, the vegetable kingdom succeeded, because, without both these, animals could not exist.
Thus the higher orders of creatures must have appeared by degrees,
and last of all man himself; as he could not begin to exist till every thing necessary for his use was provided.
Still it was for the sake of man that all inferior things were produced: man was in the divine mind through the whole process: thus every thing


produced was an image of something that was to exist in him, and the spiritual and moral essences of all inferior things were concentrated iii him; as he himself was to be an image of the Creator, in whom alone exist, in their first principles and divine essences, all the powers, faculties, and virtues, which were to exist derivatively
In fact, the Deity, in the work of creation, cannot be in man.
considered as operating at random, producing things which have
To not in himself their divine prototypes or grounds of being.
produce such things, the Creator must step out of Himself, which is impossible. As the tabernacle with every thing in it, which
Moses was instructed to make, was to be made after the pattern or antitype shewn to him in the mount*, or was to be an outward so, no doubt, when God type of such things as exist in heaven;
created heaven and earth with their inhabitants, he formed every thing after the image of divine prototypes existing in himself;

after the pattern of the ineffable attributes and perfections which exist only in his own divine essence.
Thus the whole universe,
instead of being, as it is sometimes inconsiderately regarded, a production of mere caprice, little better than the offspring of blind chance, was, unquestionably, what may most expressively be called an Out-birth of the Deity: and if so, it must bear, in all its parts,

an immutable Relation to the attributes or essential properties,
which belong to the nature of that Omnipotent Being.

2.

If then the whole Universe is thus an Out-birth from the

Deity, and hence bears, in all its parts, an immutable Relation to
Him who gave it birth; this Relation must be more immediately
If, on all things perceptible in the spiritual part of the creation.
that exist, the Divine Creator has stamped, in some mode or other,
a certain image of himself, more especially must all things belonging to the moral, intellectual, and spiritual worlds, be marked with that image. We will endeavour to make this plain, by considering the two most important particulars in which the divine image is stamped on man -- the head of the visible creation: for extensive as this subject is in itself, it happily can be reduced to a few general principles; and when these are distinctly seen, the immense multitude of particulars into which it diverges, will create no confusion.

* Exod. xxv. 40; xxvi. 30.
That there are two general principles to which all the infinities which compose the divine nature have reference, and to which, in like manner, all that man possesses by derivation and gift from his
Maker have some relation, would be evident to any one who should deeply examine the subject: this, also, is pointed out by numerous
Thus in the account of the origin of the passages of Scripture.
human race, in the first chapter of Genesis, it is observable, that two terms are employed to describe the relation which man bears
It is not only said that man was proposed to be created to God.
in the image of God, but also in his likeness; evidently implying,
unless we charge the sacred text with unmeaning tautology, that there are two general things in which man was designed to resem-
" God said, Let us make man in our image, after ble his Maker.
our likeness"* What are we to suppose is intended by the divine
Word, when it manifestly points to two distinct things in which
What can be man was created a resemblance of his Creator?
intended, but an allusion to the same truth as philosophy also brings us acquainted with; -- that man is formed with distinct faculties, designed for the reception of the two leading attributes which pre-eminently characterize the Divine Nature?

It is generally acknowledged, that the two leading attributes in the nature of the Deity, are Infinite Love and Infinite Wisdom, or,
what amounts to the same, Infinite Goodness and Infinite Truth,

 -- for what is Love, essentially, but Benevolence, and what is Benevolence but Goodness? so, what is Wisdom but the possession and
That these are the two attributes judicious application of Truth?
which give the essential character to the divine nature, is so clear a truth, that it cannot be necessary to offer any proof of it; otherwise arguments in confirmation of it might easily be drawn, both from the whole field of creation and the whole Word of God.
If the Lord had not been essential Love, there never could have been any creation, since, otherwise, there could have been no motive
The Apostle capable of calling his creative energy into action.
accordingly tells us, in the plainest language, that "God is love*:"
and the Lord Jesus Christ, by a most beautiful periphrasis, affirms the same truth, when he says, "Love your enemies, and do good,
and lend, hoping for nothing again: and your reward shall be great, and ye shall be the children of the Highest; for he is kind

* Gen. i. 26.

f 1 John iv. 8, 16.


unto the unthankful and to the evil: be ye therefore merciful, as your Father also is merciful*:" -- than which, there cannot be a more decisive assertion of the unbounded benevolence of the Divine
Nature.

But Love alone, though the prime mover of all things, is not sufficient for the production of a universe. By itself, it can do
It wills, intends, and prompts: but before it can arrive nothing.

at the ends it proposes, it must seek for means in another principle and no principle is capable of supplying such means, but Wisdom.
Divine "Wisdom or Divine Truth, is what is specifically called in
Scripture, "the Word", taking that name from the instrument of its enunciation: and of this it is said, "In the beginning was the
Word, and the Word was with God, and the Word was God. -- 
All things were made by him [or it] ; and without him [or it] was not any thing made that was madef:" -- plainly teaching, that what is here called "the Word", which is easily seen to be the
Divine Wisdom or Truth, is the immediate agent by which Divine
Love acts in the production of all things.

Divine Nature.

It will then, I trust, be readily admitted, that Infinite Love and
Wisdom, in union, are the two most essential attributes of the
There are others, indeed, such as Omnipotence and Omnipresence, which, in one respect, are equally essential,
since, without them, God would be a limited Being: yet even into
Thus these, the former enter, and give them their peculiar quality.
the Divine Omnipotence, we may be certain, can never be exerted for any other object, than to give effect to the designs of Divine
Love and AVisdom; and thus the Divine Love and Wisdom are, in fact, the essence of the Divine Omnipotence: in other words, Infinite Power is nothing but the capacity of irresistible exertion, inherently belonging to Infinite Love and Wisdom. We should find all the other divine attributes as closely connected with, and equally dependent upon, these two.

Now the first being in the scale of the visible creation, -- the most exalted of the visible works of the Creator, is man: and he is

* Luke vi. 35, 36.
t John i. 1, 3.

I have added the words [or it], because if the Divine Truth be considered as a distinct attribute or essential property of the Being in whom it is, it must be considered, in English, as of the neuter gender. The original admits equally of either mode of translation.
such, because he was created iu the image and likeness of God.
That he might be capable of being such an image, he was endowed with two faculties designed for the reception of love and wisdom
These are known by the names of the will and from his Maker.

the understanding; the will being designed for the reception of the

Divine Love or Good, and the understanding for the reception of
I am aware, that although the anthe Divine Wisdom or Truth.
cient metaphysicians universally adopted this most general division of the human faculties, some of the moderns have doubted its correctness, and have been disposed to resolve the whole into intellectual powers alone: none however could deny that man was possessed of passions: and all the passions belong to the general faculty called the will: at least, however some may explain them, it is as the seat of the passions, all of which belong to some species or other of love, that we here speak of the will.
I have also been somewhat surprised, on observing that the new philosophic sect who take the name of Phrenologists, though continually at war with the metaphysicians, and rejecting with contempt the idea that all the faculties of the mind are to be resolved into intellect, still disapprove the division into understanding and will; though nothing can be plainer than that all the faculties of which the Phrenologists make the mind to consist, are only specific divisions of these two general ones: thus all those faculties which they designate as "propensities" and "sentiments", and which, they justly affirm, have nothing to do with pure intellect, belong to the province of the will; and those which they designate as "knowing" and "reflecting faculEe-

ties", as clearly belong to the province of the understanding.

specting the latter, there can be no dispute; nor yet, I should think, respecting the former, if it be considered, that all the faculties to which they give the name of propensities and sentiments,
may be resolved into some species of love. Now a man assuredly wills whatever he loves: and thus every species of love that can have an abode in his mind, may with philosophical truth be considered as belonging to a certain general faculty, which is most correctly denominated the Will. The mistake seems to have arisen,
from confounding this general faculty, by which we are only inclined to certain actions, with the determination to action, which is the result of the operations of the will and understanding together and which takes place, when man, by his understanding, sees a fit opportunity of doing the acts, to which his will perpetually inclines him.

Undoubtedly, then, the old general division of the mental powers into understanding and will, so long established by the consent of all the reflecting part of mankind, is destined to resume its authority in the schools of philosophy: because it owed its long reign there, not to the caprice of human fancy, but to its firm foundation in the unalterable nature of things.

Now the will and understanding of man are a certain image,
however faint and feeble, of the Will and Intellect Divine; and the more perfectly so, in proportion as man receives in his will the love and goodness of the Lord, and, in his understanding, the divine wisdom and truth. When man wills what the Lord wills, and when the perceptions and thoughts of his understanding flow in agreement with the divine truth; -- thus when he receives the affections of his will, and the perceptions of his understanding, without perversion, from the infinite fountain of all goodness and wisdom in

God; -- then is he an image and likeness of God indeed. And even when he entirely perverts his noble endowments: when he makes the ruling affections of his will such as are entirely opposite to the divine love and goodness, and when he adopts in his understanding a tissue of false notions quite contrary to the divine wisdom and truth; he still, in the faculties of will and understanding themselves, retains an image, though an inverted one, of his Divine
Original: and the relation is farther preserved in this respect, that the will still remains the seat of love, though it is the love of evil,
which he accounts his good, and his understanding still continues the seat of his ideas, though these are ideas of error, which he
In the way of opposition, he still bears a relaaccounts his truth.
tion to his Maker: his faculties of will and understanding, and the subjects of each respectively, still are to him, what pure love and wisdom are to God: a general image remains, however inverted and distorted.

As then it is evident, that, in the leading feature of the moral,
intellectual, and spiritual part of the head of the visible creation,
man, the Divine Creator has thus first stamped a certain image of
Himself; there can be no reasonable doubt that the same is true in regard to all the particulars of the moral, intellectual, and
The endless varieties of such things that exist,
can only be images, either in direct or in inverted order, of the spiritual worlds.
In Him, all have their infinite divine perfections that are in God.
essence or inward ground of being: To Him, they all have an immutable Eelation: So far as they are in order, they are transcripts of something that is in Him; and even when in disorder,
they point to something in Him of which they are the perversion
In all the phenomena, then, of the moral, intellectual, and spiritual worlds which come under our inspection, we might, had we capacities for such discernment, read, as in an image, the divine things to which they owe their first birth.

3. But the images of divine things that are presented to our observation, are not confined to the phsenomena of the moral, intellectual, and spiritual worlds: they descend much lower, and display themselves, though under a totally different form, on all the objects of outward and material nature: first, on the corporeal part of man himself; next, on all the inferior animals; then on the vegetable creation; and lastly, on the inert mass of earth and water which forms the lowest plane of all; not to mention the sublime exhibitions of the same which are presented in the phsenomena of the starry heavens.
It is not then, merely by a poetical figure that
David calls upon all such things to praise the Lord, but in reference to the wisdom concerning him, of which they are the silent teachers: "Praise ye hirn, sun and moon, praise him all ye stars of light: Praise him, ye heavens of heavens, and ye waters that be above the heavens: -- Praise the Lord from the earth, ye dragons and all deeps;
fire and hail, snow and vapours, stormy wind fulfilling his word; mountains and all hills, fruitful trees and all cedars; beasts and all cattle, creeping things and flying fowl."*
And I have little doubt that Paul meant to refer to the same fact when he said, "The invisible things of God, from the creation of the world are clearly seen, being understood by the things that are made; even his eternal power and Godheadf;" though I do not quote this as a proof, because the words may be understood in the merely common and popular sense.

from man.

(1.) We will again illustrate the subject by an example taken
As man has two faculties in his mind which image forth, in an eminent manner, the two greatest essential properties of his Creator; so has he also two organs in his body, which, more

* Ps. cxlviii. 3, 4, 7 to 1 0.

f R°m - ** 20.

4*
remotely, have trie same relation: answering, however, more immediately, to the two great faculties of his mind. These two bodily organs are the heart and the lungs. As it is on his will and understanding that the life of his spiritual part depends; so is it on the heart and lungs that the life of his corporeal frame depends. What the will and understanding are to the mind, the heart and lungs are to the body; they answer to them in a lower sphere: they are
It is on this account that so frequent menexact images of them.

tion is made, in Sacred Writ, of the heart and soul.
It is well known that the word "soul", in the Scriptures, especially in those of the Old Testament, where it most frequently occurs, does not,
as in English, mean the spirit which lives after death, but merely the animating principle or life, and this because its primary meaning is breath: and of breathing, the lungs are the organ. When the soul then is mentioned in conjunction with the heart, it strictly refers to the breath respired by the lungs; and the combined phrase refers, in the language of analogy, to those faculties of the mind,
of which the heart and lungs are images in the body.

But not only are there two general organs in the body, answering to the two leading faculties of the mind, but the whole body itself is made up of two principal constituent materials; which are,
the flesh and blood.
These again, then, bear a relation, though still more remote, to the two great constituents of the Divine
Nature: it is primarily because there are two of these, that there are two of those: hence also so much mention is made of flesh and blood in the Divine Word, which, we shall eventually find, constantly speaks in terms borrowed from the Relation which we are endeavouring to establish.

As, again, the human body is composed of solids and fluids, or of flesh and blood, it is necessary, for its support, that it be nourished by aliment of both kinds, or by meat and drink.
and drinks, then, have the same general relation to the great attributes of Deity, as is borne by the constituent substances of the human body, by its two vital organs, and, in the mind, by the will and understanding: but their specific reference is to the love and wisdom, or goodness and truth, which are imparted by the Divine
Author of all good to support man's spiritual life: for the human mind is nourished by the reception of goodness and truth from their origin in Him, as the body is by its appropriate food and

All meats
drink: thus natural food and drink are proper images of the spiritual.

The same analogy is continued, even till we come to the most shapeless masses of inanimate matter. Thus the terraqueous globe in general consists, in like manner, of two general parts, which are
Indeed, it would be difficult to find any thing,
earth and water.
through the whole circuit of creation, both in general and in particular, which is not composed of two principal constituent parts.
In man, for instance, and all animals, there are two sexes: and not only are they thus, in general, arranged in pairs, but all the parts of each shew an extraordinary tendency to run in pairs also. Thus,
in the face, there are two eyes, two ears, two nostrils; in the body,
two breasts, two arms and hands, two legs and feet.
So likewise the internal organs exhibit the same two-fold bias.

There are two great divisions of the brain, so distinct, that anatomists describe them by separate names: the heart is divided into its ventricles and auricles, of each of which, again, there are two: the sanguineous system dependent upon the heart has also its two marked distinctions of arteries and veins.
So there are two lobes of the lungs, two kidneys, &c. And the parts which appear as single,
consist of two portions, united by a nevertheless, in general,
common covering: and many, whose form does not admit of this,
are composed of two halves answering to each other: thus, though the mouth, all together, is a single organ, the teeth on each side form a series of pairs; and even its outward opening is not only formed by two lips, but if these be considered as divided in the middle by a perpendicular line, they each present two parts symmetrically answering to each other: and the same may be observed in the tongue.

Now since this tendency to a twofold arrangement acts so powerfully throughout creation, that we cannot turn our eyes in any direction without seeing it every where presented before them does not true philosophy lead us to refer the phsenomenon to some universally acting cause? and what canse can be adequate to the production of such continually uniform effects, but a marked duality
Admit, what of essential properties in the First Cause of all?
cannot easily be denied, that Goodnesss and Truth, in their very essence, are Deity Itself, and we cannot be surprised to find circumstances pointing to that fact through all the fields of creation;

-- to behold them exhibited more directly in the moral and spiritual productions of the divine plastic hand, as in the will and understanding of man, and imaged not less truly, though more remotely,
And if these in the objects of material and even inanimate nature.
leading traits in all existing things bear a secret Eelation to the leading characteristics of the Divine Nature, it would be unphilosophical to doubt that a similiar Relation prevails in all other respects
Most true it must be, that the Creator has stamped a certain image of Himself on his creation, both on the whole, and on every, even the minutest part.
Although this shines most plainly in man, it must be visible, to the attentive observer, in all
All must be types, of which the the inferior orders of existence.

whatever.

archetype is in God.

(2.) But that all the inferior parts of creation present a more remote but not less real image of the Divine Creator, will still more
That man himself indisputably appear from another consideration.
presents such an image, is unquestionably agreeable to the purest dictates of reason; and to the believers in Eevelation, it is placed
But beyond doubt by the authoritative declarations of Scrip ture.
if man is an image of God, most evident also, it is, that the lower orders of creation, in then respective degrees, bear the same image;

for the most cursory inspection will shew, that they all present, in a certain manner, an image of man. How strong is the tendency to the human form, for example, which is observable among all the subjects of the animal kingdom; and even, though more remotely,
among all the subjects of the vegetable kingdom likewise !
The animals which differ most in their external shape from man, have,
nevertheless, most of the organs which are found in the human body, -- especially those which are most essential to life; though

All have heads, bodies,

all display them under endless varieties.
feet: in their heads are eyes, noses, mouths, ears; and in their
As the animal debodies, hearts, lungs, and the other viscera.
scends in the scale of existence, the resemblance becomes less perfect; yet most of the species retain the principal organs; and where these cease, their place is supplied by something analogous,
which performs their office in a manner suited to the animal's nature.

So, again, the similitude between the animal and vegetable kingdoms, -- the Mutual Eelation which they bear to each other,
They melt into each other is in many respects very conspicuous.
by such imperceptible degrees, that there are animals whose sensitive powers are not much greater than those of vegetables, and there are vegetables which exhibit such an approximation to sensation, as renders the propriety of assigning them to the vegetable
But even those which most kingdom almost a matter of doubt.
decidedly belong to this province of nature, exhibit in a remarkable manner their affinity to the animal kingdom: they display, under another form, some of the most important attributes of the latter.
Not only are they, in common with animals, animated by a decided principle of life, -- are propagated from parents, grow from an obtinuance of their species, decline, and die -- sometimes from disease,

scure germ to maturity, flourish in vigour, provide for the conand sometimes by the mere agency of time; but their life is mainTrees, and indeed all tained in an exactly analogous manner.
vegetables, circulate sap, which is their blood, through vessels answering to arteries and veins, from their root, which answers to the heart: and they inhale and respire air through pores in their
And the deleaves, which perform for them the office of lungs.
velopment of their sexual system, by Linnaeus, has brought to light
The discoveries of modern science have other wonderful analogies.

even gone farther, not only establishing general analogies between all animals and all vegetables taken respectively together, but between particular classes of animals and particular classes of vegetables* ; and thus leading to the conclusion, that every individual species in the vegetable kingdom has a species answering to it in the animal kingdom; or, that certain vegetables are, in their kingdom, what certain animals are in theirs, discharging like functions in regard to the whole.

Similar observations may be made in regard to the mineral
Here, also, extraordinary analogies may be traced, and kingdom.
a tendency to offer an image of the higher orders of creation may be observed; although, owing to the inert nature of the substances of this kingdom, it is not exhibited in so palpable a manner.
It is well known, however, how many mineral productions there are,
which, when left to assume, without constraint, the forms most

* See "Remarks on the identity of certain general Laws, which have been lately observed to regulate the natural distribution of Insects and Fungi;" by
"W. S. Mac Leay, Esq , M.A., F.L.S., Linncean Transactions, Vol. xiv., Pt. 1, p. 46.


agreeable to their nature, seem to extricate themselves from their originally unplastic state, and aspire towards the kingdom immediately above them, emulating so exactly the vegetable shape, that,
judging by this test alone, it would be difficult to determine to
But look again at the which province of nature they belong.
image of the circulation of the blood, and thus of the animal creation, which is exhibited in the globe we inhabit. No one can inspect the map of an extensive country, and the plates representing the venous system of the human body in- works on Anatomy,
without being struck by the similarity of form between the rivers in the one, and the veins in the other: both rise from innumerable minute origins, wander through an infinity of small channels,
which diminish in number and increase in size as they successively coalesce, till they unite in a common trunk which carries them to
Nor is this an analogy that is only such to the eye.
their final goal.
We have before observed, that the water is to the terraqueous globe what the blood is to the body:
so, they both are circulated throughout the whole in an analogous manner, though by very difWhile the heart, by its extraordinary vicissitudes ferent means.
of contraction and expansion, performs this work for the animated frame of man and animals, distributing the blood by the arteries to nourish every part of the body, and recalling it by the veins; the mysterious economy of alternate evaporation and condensation accomplishes the same task for the insensible frame of the world
By this are the waters raised from their great storehouse, the ocean,
transported by the clouds, which execute the office of the arterial system, to the parts where their fertilizing agency is required, discharged in showers to irrigate the soil, collected again by the rivers as an immense system of veins, and so carried back to their common reservoir, to be thrown again and again, as long as time
Now, to borrow the shall endure, through the same circulation.
phraseology of an eminent scientific writer*, there is no proper affinity between man and animals, and still less between man and vegetables, minerals, and inert globes of earth and water: but who can observe these and a thousand other wonderful coincidences,
without being satisfied that a regular and certain analogy reigns between them all? Who cannot see, that all the inferior objects

* Mr. Mac Leay, in the Paper above referred to, and in his work entitled,

Horce EntomologicoB.
that exist, present an image of man, or of something that is in man,

and thus, remotely and derivatively, an image of God, or of something in him?

(3.) We have now, however, been considering the analogy between the lower objects of the creation and man, chiefly in regard to their physical organization or constitution, and have only pointed to their relation to spiritual and divine things through the analogy observable between the general constitution of the body of man,
But, doubtless, there is a more immediate and that of his mind.
analogy also: Not only may a relation be traced between the physical powers and forms of man, animals, vegetables, and minerals, which is such that the lower seems constantly to emulate the higher; but between the mind of man, what may be called the moral qualities of animals, and the essential properties of vegetables and minerals, a not less decided analogy may be observed.
Thus, all animals universally are guided by certain general appetites and instincts, not dissimilar to those which belong to the inferior part of the human constitution. And not only are the propensities which lead them to provide for their own support by food, and for the continuation of their species, similar, in a general way, to the same propensities in man, but, in regard to the latter, some of them even recede from the grossness of brutes, and shame the brutal part of the human race, by forming conjugal engagements approaching to the tenderness and purity of married love:

whilst,

with respect to attachment for their offspring, and the care with which they provide for its welfare, even the most ferocious species emulate the maternal affection of the most exemplary human
In other respects, also, there are animals which exhibit parent.

feelings so nearly approximating to moral qualities, and instincts which so accurately imitate reason, that some who would be deemed philosophers have denied there to be any essential difference, and have asserted that nothing but speech is wanting to identify their nature with that of man.

In these particulars, then, between man and animals generally,
there is evidently a common analogy; and it is equally certain,
that there is a similar analogy between every species of animal, in particular, and something that is in man.
For while all animals have certain common appetites and instincts in which they agree,
they all have particular ones in which they differ. How great is

the contrariety of character between the wolf and the lamb, the lion
Yet how easy is it to see, that the character of each and the ox !
is thus distinct, because it is formed by some specific affection, taken,
as it were, out of the human mind, and made the single governingpropensity of the animal, without being modified by the innumerable variety of other affections, with which, in that wonderful aggregate of affections, the human mind, it is combined !
That in the human mind are accumulated all the various affections, which,
when separated, give a distinct nature to so many species of animals, is evident from the cases sometimes observed, in which one such affection is, in man, so much more powerfully developed than others, as strongly to mark his character.
Thus, where pure benevolence and harmlessness pre-eminently reign, how readily do we recognize the moral features of the lamb ! where general meekness and unsuspecting honesty, not so devoid of irascibility, prevail,
we discover the temper of the ox; where a tendency to rapine and cruelty continually bursts forth, we note the characteristic of the of the lion.

wolf; and in the nature still prone to deeds of destruction, but exalted by courage and pre-eminent power, we trace a resemblance
Similitudes of this kind are familiar to every observer
Were not their truth generally perceived, poetry would of nature.
want many of its most striking beauties: and the use in poetry of images borrowed hence, could excite no sympathies in the mind of the reader, were they not founded in the fixed laws of nature.
We see clearly, that, on some animals, in regard to what may be called their moral qualities, is stamped a decided image of certain moral qualities existing in the human mind: and were we fully acquainted with the leading moral quality of every species of animal, we should see that every species of animal derives its proximate origin from that to which it thus answers in the human
Hence, also, animals are images,
mind, and bears of it the mark.
though more remotely, of those principles in the Divine Miud from which every thing that exists in the human mind is a faint transcript; only we must here recollect, what has before been remarked,

that there is a relation of opposites, as well as of direct resemblances.
Certainly, nothing evil and mischievous can bear a relation or analogy to anything in the Divine Mind, any otherwise, than as it
There are many is the perversion of something intrinsically good.
such perversions in the corrupt mind of man; and all things



noxious in nature are directly images of these, and only inversely of the opposite perfections in the Divine Nature.

(4.) But perhaps it may be asked, If the whole Universe, as advanced above, is an Out-birth from the Deity; and if every thing so produced has in Him its divine prototype and ground of being how came any thing to be created whose relation to Him is merely
It may be answered, Because, though every that of an opposite?
inferior creature has its divine prototype in God, it has, as is also stated above, its immediate antitype in man: if then man, by the abuse of the freedom of will with which he was endowed, perverted the divine gifts which he had received, and introduced evil into himself, images of such perversion and evil, by the continued action of the Divine Creative Power, would speedily appear in the lower objects of creation.

There can be no doubt, as declared in the beginning of Genesis, that all things, as they first came from the
Divine Hand, were good: and perhaps it may be questioned,
whether any thing that now exists is so purely evil, as not to be
The letter capable of being divested of its malignant properties.
of Scripture seems to affirm that it may, when it says, in reference,
to a future glorious state of the Church and its members, "The wolf shall dwell with the lamb, and the leopard shall lie down with the kid; and the calf, and the young lion, and the fatling together
And the cow and the bear shall and a little child shall lead them.
feed, their young ones shall lie down together; and the lion shall
And the sucking child shall play on the hole of the asp, and the weaned child shall put his hand on the
If we suppose that by the harmless animals eat straw, like the ox.

cockatrice' den."*

and the infants here mentioned, are typified the good, benevolent,
and innocent affections of the human mind, and by the noxious animals, such appetites and propensities, as, when not controlled by the former, are of a destructive nature; and if, by their all dwelling together, we conceive to be meant, the depriving of the latter of their pernicious tendencies by the complete preponderance of the former; we have a spiritual sense which certainly teaches a most important moral lesson, conveyed in language most striking
To dwell, however, upon this, now, would be to and impressive.
anticipate the argument to which we are to proceed by and by: I
here mention the circumstance to shew, that if there is an evident

* Is. xi 6, 7, 8.
analogy between the noxious animals, in the state in which they at present exist, and the evil propensities and passions of human nature, the Scripture, when pointing to a state in which the lower appetites and propensities of man shall be divested of their injurious nature by the preponderance of the higher sentiments, preserves the analogy between them and the same animals, by describing the latter as laying aside their destructive tendencies.

If the present species of animals all existed from the beginning, it is certain that some of them must have been greatly altered when evil established itself in the human mind.
As all evil is nothing but the perversion of the lower propensities of our nature, which by creation were good, the animals which were created as representative forms of those affections could not at first have been noxious;
but they might begin to be so when those affections in man suffered perversion.

Hence it may be true, as the poet sings, that

" Thus began

Outrage from lifeless things: but Discord first,
Daughter of Sin, among th' irrational,
Death introduced, thro' fierce antipathy.
Beast now with beast 'gan war, and fowl with fowl,
And fish with fish: to graze the herb, all leaving,
Devour'd each other; nor stood much in awe
Of man, but fled him, or, with count'nance grim,
Glared on him passing."

And if this was the origin of the noxious nature in beasts, it cannot be doubted, were mankind to return to a state such as is spiritually described in the passage just quoted from the prophet,

in which all the lower appetites and propensities were strictly subordinated to the higher, that the words of the prophet would have a literal fulfilment likewise, and all animals would again
But in any case it is certain, that could evil become innocuous.
be removed from the moral world, it would cease in the natural world also, and destructive creatures would no longer exist.
If it should be deemed unphilosophical to suppose that those now in being would change their nature, to which their physical organization is so accurately adapted, it is perfectly agreeable to the discoveries of science to conclude, that they would cease to exist altogether; since it is well ascertained, from the organic remains found in the bowels of the earth, that many species, and even whole genera, of animals and plants once common, are now no longer again before the end.

known; and, conversely, that many of those now common were strangers to the primeval ages: thus, having commenced their existence since the beginning of the world, they may relinquish it
It may then be safely concluded, since nothing noxious can have its direct prototype in God, that all such things either first acquired their noxious nature, or first began to exist, when evil established itself in the human mind; that they are properly the images of the depraved propensities which there have their seat; and that if moral evil coidd be banished from the world, these expressive images of it would either lose those qualities which make them such, or would disappear altogether.

(5.) But to return from this digression; which however was
It surely must be readily necessary to meet a seeming difficulty.
admitted, when fairly contemplated, that the analogy between what may be called, in a qualified sense, the moral qualities of animals and the affections of the human mind, is very obvious and striking;
and it cannot be difficult to discover a similiar analogy between both of these and the properties of the objects belonging to the vegetable and mineral kingdoms. How closely are the common appetites and instincts, which in animals are subservient to the preservation of the individuals and of the species, emulated in the vegetable creation !

is sustained by supplies of nourishment from without.

In these, as in those, the life of the individuals
They are provided with sets of vessels, which draw from the soil in which they grow, and from the air which surrounds them, those juices and gases which are congenial with their nature; and these they select, while they reject such as would be pernicious, with a discrimination which, though void of all consciousness, answers to,

and exactly pictures, under another form, the instinct in regard to
So, in the mode by which these objects so wonderful in animals.
the continuation of the species is provided for, there is so much that seems to rival the attachments of animals, that Poetry, with one of her usual exaggerations, has attempted to abolish the difference, by selecting as a theme, "the Loves of the Plants*," and Painting has carried on the thought, by representing the fabled Deity of the tender passion subduing the vegetable kingdom also to his sway, and levelling his arrows at the susceptible breasts of flowers.f

* By Dr. Darwin.
f See a print in Dr. Thornton's Illustrations of Linnseus's Sexual System.


And how exact an analogy of the same universal impulses is displayed through the mineral kingdom also ! By how marvellous a power, resembling the animal appetite for food, do many minerals draw from surrounding substances the materials of their accumulation ! How completely magical; how similiar to the exercise of affection and choice, is the action of chemical affinities ! How striking an image of conscious attachment is presented, when, under the influence of the mysterious principle just mentioned, we behold inanimate matters, -- substances not possessed even of vegetative life, rush into union, as if actuated by the most ardent mutual affection !

But not to dwell on these common resemblances, which assuredly tend very conclusively to establish the continual Mutual Relation, or Eelation of Analogy, between all the various orders of creation; who cannot see a similar analogy between specific moral qualities, the animals in which such qualities are imaged, and the
Between all the properties of specific vegetables and minerals?
productions of the vegetable kingdom that afford pleasant and wholesome nutriment, for example, -- the mild races of animals which are of similar use to man, and the good moral qualities of which these are the pictures, how plainly does this relation exist and, on the other hand, how close is the analogy between noxious plants, noxious animals, and the malignant moral qualities which
To descend to particulars would carry us these so aptly typify !
into too wide a field; otherwise, numerous confirmatory instances
The substances of the mineral kingmight easily be pointed out.
dom not affording food to man, their particular relation to the objects of the vegetable and animal kingdoms, and finally to moral qualities, cannot so evidently be shewn; but that every specific substance of unorganized nature has also properties peculiar to it,
which, though quite different from those of vegetables and animals,
and especially from the feelings and sentiments of the human mind,
are yet exactly analogous to them; is a truth which a little reBut Nature herself, by bringing search would easily establish.
together the aualogous objects of her different kingdoms, often calls upon us to note their mutual relation, -- to observe how, in their

Head, for instance,
respective spheres, they answer to each other.
the description of the Great Western Desart of North America,
that occupies hundreds of miles, both in length and breadth, of the


territory that lies between the great rivers Mississippi and Missouri and the Rocky Mountains, and which has lately been explored by a mission despatched for the purpose by the government of the
Of this frightful district it is related, (I quote
United States.*
from the Quarterly Review,) that "In patches where vegetation shews itself, it is mostly confined to tufts of withered grass, prickly pears, and those succulent and saline plants which can derive subsistence out of the most arid, sandy, and sterile soils. Two species of cactus are described as most formidable plants, the cactus ferox
The former is stated to reign sole and the cactus cylindricus.
monarch over myriads of acres of these desolate plains, in patches,

which neither a horse nor any other animal will venture to pass.
The latter grows singly, and forms a cluster by itself, increasing to such a size, that, seen from a distance, it is frequently mistaken for
The whole plant is so thickly beset with spines that it a bison.
forbids all approach to it, either by man or beast." f
Respecting the animated tenants of the more southern part of this horrid desart, it is stated, that "Clouds of locusts filled the air, uttering shrill and deafening cries; while the Mississippi-hawk, wheeling through their ranks, seemed to enjoy his favourite prey; rattlesnakes of various kinds, and scolopendras of enormous size, were crawling on the naked surface; and immense black, hairy spiders,
like the bird catching animal of South America (mygale avicularia),
watching for prey at the mouth of their subterranean habitations."!
Who can read this frightful account, without being struck by the homogeneity of character, so apparent between the unkindly soil and its pernicious products, both vegetable and animal?

"Who is not led unconsciously to feel, that there is a decided analogy be *
tween the characteristic nature of each and those of its accompaniments? Who does not spontaneously infer, that the barren ground,
the horrid thorns, and the venomous reptiles, mutually answer to each other? And who does not see in them all, striking emblems,
and even exact images, of the malignant passions, such as prompt to shoot the poisoned darts of calumny, and to stab with unjust reproaches? -- of a disposition, such as would pervert even the sunshine and rain of heaven into food for those passions?

* Detailed in the "Account of an Expedition from Pittsburgh to the RockyMountains, &c. r

' by E. James.

f Quarterly Review, No. lvii., p. 16.

% Ibid, p 23.
But we must not dwell any longer on these illustrations.

As we have before plainly seen, that on all things belonging to the moral, intellectual, and spiritual worlds the Divine Creator has first stamped a certain image of Himself; so enough may now have been stated to evince, that all objects of outward and even material nature, bear an image of the moral, intellectual, and spiritual world of the human mind, representing its bad as well as its excellent endowments: and thus we plainly see that on these also the divine image is impressed, though sometimes in an inverted and
Through all distorted rather than in a direct and beautiful order.

the links of creation, lower things continually answer to higher;
and the contemplation of them in this light is indeed calculated to
"lead from nature up to nature's God." Whilst, through all their varieties, minerals are seen to answer to vegetables, vegetables to animals, and animals to man; and whilst man is recognized as having been created in the image and likeness of God; we see how the attributes of the highest natures may be viewed, as in a mirror,
in the lowest: we discern how close is the tie which binds together the whole universe of being: we behold how things invisible may
The Relation of Analogy be read in the things which are seen.
thus every where existing, makes the volume of nature an instructive book indeed.
of, he who thus views the fields of creation

In a stricter sense than the poet ever dreamed

" Finds tongues in trees, books in the running brooks,
Sermons in stones, and good in every thing."

4. Concluding that it must now be pretty evident, that all things in Nature, being, as we have seen, outward productions from inward essences, are natural, sensible, and material types, of moral,

intellectual, and spiritual antitypes, and, finally, of their prototypes in God; we draw a step nearer to the important object before us,
which is, to shew that a Law or Eule of universal application is hereby afforded for the interpretation of the Word of God. We will here only remark further, that if such an analogy as we have pointed out exists at all, it must be regular and constant; that the mutual relation between natural types and spiritual antitypes must be immutable; if therefore the Scriptures are written in agreement with this analogy or mutual relation, the interpretations drawn from an adequate knowledge of it cannot be irregular or uncertain.
The doctrine of spiritual interpretation will thus be freed from the only objection by which it could be reasonably impugned.

III. Seeing then that a Eelation of Analogy so decidedly prevails among the various orders of existences in the universe, insomuch that inferior things are, universally, images of superior, and that all material things are types of immaterial; it will follow, that were this Eelation well understood, a style of writing might be constructed, in which, while none but natural images were used,
purely intellectual ideas should be most fully expressed: indeed it will be evident, that even a narrative in appearance the most simple, treating, in its literal expression, merely of the objects of nature, if framed by that Infinite Knowledge to which the proper qualities of natural objects all lie displayed, and which sees infallibly of what spiritual antitypes these are the types, might include lessons of wisdom far beyond all that philosophy ever reached.

1. Now that such a Eelation exists, and that such a truly expressive style of writing might be framed by its means, are, in a
To be satisgreat measure, intuitively perceived by all mankind.
fied of this, we need only advert to a few instances which are familiar to us all; which prove, that although the existence of an analogy immutably established by the laws of nature between natural images and spiritual essences, may seem new to us when first we hear it distinctly affirmed, this is only for want of having made it a subject of reflection; whilst we have at the same time, a natural consciousness of it, which gives birth to many of our conclusions, and is the origin of many forms of speech in common use.

(1.) In regard to the conclusions which we draw from it:
"What is better known, for example, to every human being, than that the face is, in a very great degree, an index of the mind, and that it would be most completely such, did not man often endeavour to conceal what is passing within, and thus to give an expression to his countenance which is foreign to the sentiments of his
What is more common, when we first see a stranger, than to form an opinion in regard to the dispositions of his mind from certain marks of character which we see written in his face? And though, for the reason just mentioned, we are here liable to be heart?


mistaken, this experience does not prevent us from deducing such conclusions altogether, but only from depending on them too much a person's looks invariably make some impression upon us, and we continually find ourselves apt to draw from them some prejudice or prepossession.

But although we are liable to mistake in the opinion we thus form of the general character, we can scarcely err in deciding what are the affections which at any time reign in a person's mind, when
None he is under circumstances that affect him very strongly.
but the most accomplished hypocrite can prevent us from discovering what are the feelings which agitate his breast, when they are under any very powerful excitement. Who cannot tell whether a person is angry or pleased, buoyed up by hope or weighed down by despair, melted by pity or inflamed with rage, merely by obBut these discoveries serving the lineaments of his countenance?
of the interior emotions of the mind from the exterior form of the face, would be utterly impossible, did there not exist a certain relation between things spiritual and things natural, -- between the spiritual things which exist in the mind and the natural appearances which the face assumes. It is from this origin alone that the invisible things of the mind become visible in the countenance:
the higher flows into the lower, and moulds it in an instant into a form, which, Nature teaches us all, is the image of itself.
Yet what two things can be more distinct than the mind and the face
Great disputes have divided the schools respecting the part of the system in which the mind holds her court; but none have dreamed of placing her seat in the face: yet in the face, unquestionably,
much of the mind is to be seen; and all who there read her emotions, view a branch of the analogy between the things materrial and immaterial, and testify to the fact, that of this, in many respects, man has an intuitive perception.

(2.) But to state a few of the instances in which this perception is the origin of forms of speech in common use.

What is more common with mankind, than to use such forms of expression as these: "I see what you meau: what you have observed throws a great light on the subject; it must convince all who will take a candid vieio of the question, and look at it in all its bearings." And whenever we thus express ourselves, we acknowledge the existence of a fixed relation between natural things and
spiritual; otherwise we should never talk of seeing, taking a mere,
and looking at, which are the actions of a bodily sense, and of light,

which is a natural object, in reference to the operations of the mind: but we speak in this manner, because we are inwardly sensible, that the sight of the bodily eye answers to the sight of the mental eye, which is the perception of the understanding; and that the light of the natural world answers to the light of the moral world, which is truth: thus when we say we see that a thing is so,
we mean that we understand it; and when we add that a light is thrown upon a subject, we mean that the truth respecting it is rendered evident. Again: What is more common than to speak of or, when we behold a person a warm affection, a burning desire;
Yet such forms eager in any pursuit, to say, that he is all on fire?
of speech would be quite destitute of meaning, unless there does actually exist a regular relation of analogy between things spiritual and things natural, -- between natural heat, which is that of fire,

and spiritual heat, which is that of love: thus intensity of love is what we always mean when we thus speak, metaphorically, of heat,
and (Afire; and whenever we thus express ourselves, we betray an involuntary consciousness of the reality of the above relation.
Again: How continually do we hear and use such forms of speech as these ! -- When readily assenting to a request, we frequently say.
"I wiU do it with all my heart "when speaking in commendation of a person whom we esteem, we often say, "He has a good heart:"
and when see a man extremely intent upon any object, we say,
" His whole heart is in it."
But how absurd it would be to use such expressions, if, by the heart, we meant nothing more than the organ by which the blood is impelled through the body !
It is certain that when wre thus mention the heart, we mean the will and affections: and the reason why we thus speak of one thing instead of another, is, because there is a mutual relation between them since, as has been shewn above, the heart discharges a function in respect to the body similiar to that which the will discharges in respect to the mind: and our exchanging the terms arises from a secret perception of the truth of this analogy.
So, in all ages and among all nations, it has been usual to consider the hand as an emblem of power, and to introduce the name of this important member into various phrases, when we mean, either to speak simply of power, or to express some kindred sentiment which has

5
the idea of power as its root: thus, how common it is, among politicians, to talk of strengthening the hands of government, meaning thereby, so to support the government, that it may have power to execute its designs ! -- and here, again, we refer to the sense we all have, of the fixed relation between things material and moral,
natural and spiritual.

These instances are chiefly drawn from the organs of the human body; and whoever is disposed to carry his observations of this class of analogies farther, will find, that we in like manner frequently transfer all the terms, which, in their primary signification,

describe the action of the bodily senses, to express certain operations of the mind, of which the senses are appropriate images.

they answer.

But we by no means take all our helps to expressive speech of this kind from ourselves; we as frequently borrow them from the animal creation, mentioning the names of animals when we mean to express the moral and intellectual qualites to which we perceive
Thus we often call children lambs, on account of their innocence: and to describe a pure affection between the sexes we take the suitable image of doves, calling by that name those whose mutual attachment is distinguished by its tenderness and constancy, and by the innocence which it seems to breathe. An eminent
The eagle is warrior we call a lion, on account of his prowess.
taken as an emblem of a towering intellect, on account of his mounting to such a height in his aerial excursions, and the steadias is a hawk of ness with which he can fix his gaze on the sun;
acute discernment, for his extraordinary keenness of sight. And when we behold a person indulging in flights of a soaring imagination, we borrow the appropriate figure of a winged horse, invented by the ancients, and say, "He has mounted his Pegasus."

Were we however to turn our attention to a still lower class of analogies, and endeavour to recollect the multitude of terms and phrases, borrowed from the physical properties of various common and inanimate objects, to express the qualities of the faculties,
operations, and products of the mind;- we should find ourselves in a spacious field indeed. How familiarly do we speak, and how frequently do we hear, of stabbing with reproaches, or of using cutting words; of corrosive thoughts; of bitter pangs, both of body and mind; of sharp afflictions, and acute sufferings, likewise of both kinds; of lacerated feelings; of biting sarcasms; of grinding oppres-
sion; of upright dealings; of crooked policy; of straight-forward proceeding j of melting tenderness; of hardened wickedness; of soft compassion; with a thousand other such combinations ! which are all absolutely heterogeneous, if the essentially different nature of the ideas combined be alone regarded, but which, nevertheless,
strike no one as absurd, as they would do, if not in some way founded in the very nature of things. They have such a foundation,
and therefore they do not offend us: the reason is, because, though heterogeneous in one respect, they are homogeneous in another though physical properties are applied to moral objects, and are others are in a higher.

entirely different from the properties of such objects, they answer to them by an exact analogy, and are, in a lower sphere, what the
Of this, all men have a perception; we therefore readily translate the idea of the physical property into that of the moral one; and this, often, so instantaneously, that we all which would be im»
do not advert to the physical idea at all;

possible did not Nature herself dictate the interpretation, and thus
Men, also, more particuassure us that the language is her own.
larly have recourse to such language, when they most strongly feel jl&at they say; when they speak, as it were, more immediately under the inspiration of Nature, and when their thoughts flow
Then it is that they more regularly in agreement with her laws.
have a more clear intuition of the analogy that reigns between the various provinces of her empire, and thus are better enabled to give force to a purely intellectual idea, by calling its counterpart material one to its aid: as the hero, when rising to the defence of his country, fortifies the vital parts of his frame by a clothing of armour fitted over Nature's investment of ribs and flesh, and adds the power of his sword to that of his hand.

(3.) Now, what all see to hold good in some cases, must also be admitted to hold good universally; and thus we shall find that the common perceptions of mankind irresistibly confirm the existence,
through all the kingdoms or spheres of being, of that constant analogy, which we have before endeavoured to establish from the
If there be a great number of instances in very nature of things.
which the Mutual Kelation between things moral, intellectual, and spiritual, and things material, sensible, and natural, is so evident,
that every human being intuitively perceives it; must we not necessarily conclude, that there are innumerable other instances in which a similar relation exists, although it is not so immediately
Must it not, indeed, be absoobvious to our dark apprehensions?
lutely certain, that such a relation prevails, not only in many other instances, but in all cases whatsoever?
This is a fact that appears
Tor we know that all things to be capable of demonstration.
which exist in this natural world, how much soever they may differ from each other, have, nevertheless, one common nature, and are derived from one common origin: they all are forms compacted of material substances, or are modifications of such forms, and they all have the first cause of their existence in God: If then we see,
incontrovertibly, that some of the objects which lie obvious to our senses in the natural world, have a Eelation of Analogy with certain moral and spiritual things, it follows, by inevitable consequence, that all the other objects of this natural world, by virtue of their possessing the same common nature and the same common origin, must also possess the same kind of Relation to certain other
In fact, as has in part been shewn moral or spiritual things.

above, the causes of all natural objects immediately lie in the world of spiritual existences, so that, in reality, spiritual things are,

instrumentally, the producing causes, by derivation from the First
Cause, of natural things: and hence the spiritual cause and the natural effect, must, universally, answer to each other.

This is most plainly the case with man's soul and body; in regard to which we will make this further observation.
Man's body, we know, cannot exist a moment alone, any otherwise than as a corpse; whereas, according to the Scriptures, and the truest philosophy, his soul is capable of subsisting in a separate state.

It is evident, then, that the soul is the higher subsistence of the two; and it hence becomes certain, that the soul is the immediate
Even if we suppose, with the mateproducing cause of the body.
rialist, the soul to be nothing but a certain mental life and activity,
incapable of existing separately from the body, this will not affect our argument; since it is undeniably true, that it was in order that such mental life and activity might come into existence, that the body is produced. Be the soul what it may, it is ceriai i that the body is formed merely for its sake, and for its use. Now as we have before seen that there is a Relation of Analogy between the face, with certain other organs of the body, and certain faculties of the mind, which is nearly identical with the soul; so also must it be true, that the whole of the body, taken together, answers to the whole of the soul, and every distinct organ or member of the body to some distinct faculty or principle of the soul; and this because it is derived from it, or is formed for its sake, to be its seat and instrument of action in the world of nature.

Now what is true of the human body and soul, is true likewise of all the objects in nature and of certain spiritual principles which are the proximate causes of their existence; these, again, being emanations, as it were, from their inmost essences in the perfections of

There is a Mutual Eelation or Analogy between them.

It
Deity.
is evident then, that the instances in which mankind are in the habit of speaking in phrases drawn from this Analogy, are but as a few gems taken from the entrance to an exhaustless mine; for that every object in nature, were its properties as well understood as those of the objects from whence our illustrations have been taken, would furnish other such pnrases, and the whole together,
varieties unbounded.

Here we find ourselves repeating in other words, (but now as a conclusion from the premises advanced,) the proposition stated above: That, were the Eelation of Analogy between the different orders of existences in the Universe well understood, a style of writing might be constructed, in which, while none but natural images were used, purely intellectual ideas should be most fully expressed. Such a style of language, also, would, as in the instances before noticed wherein this kind of interchange is still in use, be incomparably more forcible than that composed of abstract terms, and would, when applied to exalted subjects, embrace an infinity more of meaning, than can possibly be infused into the
But then,
best selected arrangement of metaphysical expressions.
to employ this language with all its power, we must suppose a perfect knowledge of both sides of the analogies; --  not only of the properties and intrinsic nature of all the natural objects whence images are to be taken, but of all the moral, intellectual, and spiritual things to express which the former are to be applied: and this is the wisdom of Omniscience.
While then man, from this treasury, can only borrow a few scattered jewels to set off his intellectual dress, the arrangement of them, through all their series,

into glorious forms of suns and stars, to adorn a robe of imperial splendour, demands the skill of the Owner and Author of the


whole; and they who would catch a glimpse of such a production,
must study with devotional feelings and a teachable spirit, together with just ideas of its nature, the Word of God.

2. For it is in language of such construction, that the Holy
Word is written throughout; as we hope will clearly appear in the sequel: at present we will only mention a few palpable instances of the occurrence in that book of such forms of speech as we have already noticed.

We have seen above, that the face or countenance of man is an index of his mind, insomuch that the interior emotions and thoughts of his mind are therein expressed: hence, whenever the face is spoken of in the Word of God, the interior affections and ideas or thoughts of the mind are uniformly to be understood.
Thus, mention is very frequently made of the face of the Lord; as in the form of blessing the people prescribed to Moses and Aaron: "The
Lord bless thee and keep thee; the Lord make his face shine upon thee and be gracious unto thee; the Lord lift up his countenance upon thee and give thee peace."*
Here, by the face and countenance of the Lord are meant the interior attributes or properties of the Lord, or those which constitute his essence; and these are,

generally speaking, divine love and divine wisdom, or divine goodness and divine truth; and by the Lord's making his face to shine, and lifting up his countenance, upon the objects of his blessing, is signified the communication to them of all the graces, with their accompanying felicities, of which those divine principles are the
It may also be observed that the attribute of the sun,
source.
which is, to shine, is here ascribed to the Lord's face: so we sometimes read, more explicitly, of the Lord's face being as the sunf and as from the sun flow heat and light to recreate the natural objects on which it shines, so from the Divine Sun flow love and wisdom to bless intelligent creatures. We have seen, also, that the sight of the bodily eye answers to the sight of the mental eye,

or the understanding, and that natural bght bears an exact analogy to spiritual light, which is truth: hence it is written, "The people
; "by which is that walked in darkness have seen a great light %
meant, that they who before were in ignorance, which is spiritual darkness, were brought to a knowledge of the truth: and hence also

* Numb. vi. 24, 25, 26.

f Matt. xvii. 2; Rev. i. 16.

' % Isa. ix. 2.
it is said, in a passage cited for another purpose in our last Lecture,
" Open thou mine eyes, that I may behold wondrous things out of thy law* ;" for it is certain that the interior glories of the law or
Word of God are not to be beheld by our bodily eyes, but by our mental, -- that is, they are to be perceived by the understanding.
We have seen, likewise, that natural heat, which is that of fire,
bears a recognized relation to spiritual heat, which is that of love.
Hence it is that the abode of the lost hereafter is compared to "a furnace of/ref", and is said to be a place "where the worm dieth not, and the fire is not quenched % :" for by the never-dying worm is aptly expressed the perpetual gnawing of corrosive thoughts, and by the unquenched fire the insatiate raging of evil lusts.
In this instance, fire is mentioned to express love of a wicked and infernal character; but it is frequently used to express such as is heavenly and divine: thus it is said of the Lord Jesus Christ, that "He shall
;" by which is meant,
baptize with the Holy Spirit and with fire §
that he will regenerate his disciples by his Spirit of Truth and his
Divine Love. We have seen, further, that the heart of man is inHence tuitively perceived to bear a relation of analogy to his icill.
it is said in the Holy Word, that "the heart of man is deceitful
; by which we are taught above all things and desperately wicked ||
that the icill of man is, tlirough sin, of such a quality; whence the
Lord says by the prophet, "I will take away the stony heart out of their flesh, and give them a heart of fleshy;" by which is signified,
that the icill of evil shall be removed, and the will of good implanted, with those who submit themselves to be guided by the
Lord: and it is not said that this new heart shall be a heart of flesh, merely to contrast the softness of this material with the hardness of stone, -- though this affords a poetical figure, likewise founded in a real analogy, and equally beautiful and expressive, -- but on account, also, of the less remote analogy, which, as we have seen
Finally we above, fiesh itself bears to the principle of goodness.
have noticed, how prolific a source of metaphorical phrases has been afforded by the plain analogy between the human hand and the principle of power: and of applications of this image the ScripThus how often is it said that the Lord brought tures are full.
the Israelites out of Egypt by "a mighty hand", or "by a mighty

* Ps. cxix. 18.

f Matt. v. 42.

\ Mark ix. 44, 46, 48; Isa. lxvi 24.

§ Matt. iii. 11.

\\ Jer. xvii. 9.

fl Ezek. xi. 19.



hand and a stretched ont arm !"* No one supposes that this was done by the visible putting forth of a hand and arm from the person of God; but all who believe the history allow, that it was effected
So, when it is by a wonderful exertion of Divine Omnipotence.
said of the Lord Jesus Christ, that "he was received up into heaven, and sat on the right hand of Godf", few minds can be so gross as to dare to picture to their imagination two personal divine forms sitting side by side on the throne of heaven; but all must see that the phrase is introduced to teach the same truth respecting the Lord Jesus Christ, as, in another evangelist, he declares respecting himself in plain terms: "All power is given unto me in heaven and in earth % "All power is omnipotence: to be received up and sit on the right hand of God, evidently, then, can mean nothing else, than the exaltation of that which was so received up,
which was the glorified Human Nature of the Lord Jesus Christ,
to the full possession and exercise of Divine Omnipotence, -- to be the instrument by which, thenceforth, the Divine Omnipotence was to be exerted.

It would be highly interesting, and would materially help to confirm the important result to which all the facts and examples which we have here noticed tend, could we stop to examine some instances in the Scriptures, similiar to those adduced above from common discourse, of the formation of expressive phrases by applying the names of animals, and of the qualities of inanimate objects,
to describe mental powers and properties: but we must not antiThe examples cipate too far the subject of our two next Lectures.
above adduced from common speech, and these few from Scripture,
must be sufficient to establish the fact which we have had in view in this branch of our argument; -- That were the Belation of Analogy between natural and spiritual existences well understood, a style of writing might be constructed, in which, while none but natural images were used, pm'ely intellectual ideas should be most fully conveyed: and the examples from Scripture in particular, must surely be felt to render highly probable the further conclusion,
that this is actually the style in which the Word of God is written.
On the application of the Eule of Analogy, we see how clear and beautiful a sense results from passages otherwise extremely mys-

* Deut. iv. 34; v. 15; vi. 21; vii. 8, 19; ix. 26; xi. 2; xxvi. 8; xxxiv. 12.

j Mark xvi. 19.

t Matt xxviii 18.
terious; and though a general idea of the meaning of such passages as we have now considered, might present itself to almost every reader, we see that what could otherwise be only an obscure,
shadowy, undefined idea, becomes, on the application of the Rule,

clear, distinct, and definite.
There are however, multitudes of analogies which have quite dropped out of use in common speech, but which are retained in Scripture; and in the interpretation of such passages, without a knowledge of the principle, nothing could be
This, however, will be seen more clearly offered but mere conjecture.
in the sequel; what we are here chiefly aiming at is, to establish,
beyond question, the universal existence of such a Mutual Relation between things natural, spiritual, and divine, as we have endeavoured
This is testified, we have seen, by every thing that we to explain.
know respecting all these different orders of being: the conviction comes more closely home to us, when we notice that we intuitively perceive it, and draw from it many of our every-day phrases: and it is further confirmed still, if, while we only look at the Scriptures as a collection of very ancient writings, composed in an idiom generally in use in the early ages of the world, we find them full o??
forms of speech evidently constructed on the same universal principle.

In fact, the doctrine of Analogy, and the Sacred
In the Scriptures, more
Scriptures, mutually illustrate each other.
than any where else, are afforded the means of recovering the knowledge of this Analogy; and, without arguing in a circle, we shall find in the end, that the doctrine of spiritual Analogy will afford the only key for arriving at a satisfactory interpretation of the Scriptures.

IV. Among those, however, who think that nothing which is new can possibly be true, there may be some who will be unwilling to contemplate those clear proofs of the existence of a Mutual
Relation between things natural and spiritual which Nature every where exhibits, unless to the testimony of Nature, confirmed by
Reason, be added that of human authority.
This then may be produced in abundance, provided great antiquity should not be deemed as objectionable as absolute novelty: for certain it is, that,
in the remote ages, the Relation in question was very extensively
The passages already quoted from the Scriptures understood.
evince, that, when they were written, the Relation of Analogy be-

5*
tween natural and spiritual subjects, if not necessarily known to tlie writers of the books, was present to the Divine Mind by whose inspiration they wrote them; and being thus recognized by him whose existence is from everlasting, it has the sanction of an antiquity coeval with the origin of all creation; of which fact we shall find abundantly more confirmations in the sequel.
But if there be any who can fear to give themselves up to this evidence; -- who will even distrust the voice of God, added to the dictates of Nature, till it is authenticated by the testimony of man: they need not reject it,
in this instance, for the want of such credentials.

1.

It is even unnecessary to travel out of the "Word of God itself, for testimony of this kind: for if we only take its relations as authentic history, whether dictated by divine inspiration or not,
we shall find that some of them give full proof of the fact., that the knowledge of the Eelation between things spiritual and natural,

whereby they mutually answer to each other, and whereby the natural afford proper images for the expression of the spiritual,
was in ancient times widely diffused. We might instance the case of Balaam, a native of Mesopotamia, who thrice directed Balak to build seven altars, and to offer a bullock and a ram on every altar*,
when he was desirous to obtain an "enchantment against Jacob,
and a divination against Israelf;" and who actually did, in consequence of these emblematic preparations, obtain communications from heaven, though of a contrary nature to those which he and his employer wished for: -- circumstances which evince, that there really was a connexion between the communications obtained and the ceremonies performed, and which establish tbe really typical character of the latter, and the knowledge of this possessed by

Balaam.

But we have a still more remarkable instance of the preservation of this knowledge, in the account of the events which befel the
Philistines after they had taken in battle the ark, which was the
The most holy symbol in the representative worship of the Jews.

chief circumstances were as follows.

:£

On capturing the ark, they placed it in the house of their idol
Dagon; and the consequence was, that the next morning they
They found the idol fallen with his face to the ground before it.

* Xumb. xxiii. 1, 14, 29.

f Ver. 23.

J See 1 Sam. Cos. v. and vi.


however regarded this as an accident, and set the idol up again when, the following morning, beside finding the idol thrown down afresh, they found his head and both his hands cut off, and lying
And not only did judgments thus fall upon upon the threshold.
the idol, but upon his infatuated worshipers, who died in great numbers, and those who died not were smitten with emerods: the
They then determined to send land, also, was overrun with mice.
the ark away, as the only means of obtaining deliverance from the miseries which they suffered; but on consulting their priests and diviners, these said, "If you send away the ark of the God of
Israel, send it not empty, but in any wise return him a trespass offering." Then they said, "What shall be the trespass offering?'*
The others answered, "Five golden emerods and five golden mice,
according to the number of the lords of the Philistines."
They also directed them to make a new cart, and to take two milch kine on which there had come no yoke, and tie them to the cart, and bring their calves home from them, and send away the ark: and they said, "See, if it goeth up by the way of his own coast, to
Bethshemesh", (which was the nearest Israelitish city,) "then he
(the Lord) hath done us this great evil: but if not, then we shall know that it is not his hand that smote us:
it was a chance that happened to us." All this was accordingly done: "And the kine",
the history relates, "which drew the cart, took the straight way to Bethshemesh, lowing as they went, without turning either to the right hand or to the left:" and when the people of Bethshemesh saw it, they offered up the kine for a burnt offering, cutting to pieces the cart, and making the fire with the wood. Now to what purpose could be all these ceremonies, if something were not specifically and correctly symbolized by every particular related?
"Without this, what would the whole proceedings amount to, but a piece of idle mummery? That they were not such, is evident from the effects being such as was expected: the unguided kine of their own accord, took the way to Bethshemesh, and the Philistines
The whole then must have were relieved from their sufferings.
been a series of representative images, founded in the Relation of
Analogy which exists by the constitution of nature between natural things and spiritual: and a knowledge of this Eelation must have been possessed, to some extent, by the Philistine priests and diviners: otherwise, how could they have directed such rites to be performed, as, though seemingly trifling, had the effect of turning away the plagues with which the people were afflicted?
The reason why such effects followed the use of such means, is, because,
prior to the alteration made in the state and nature of the church by the coming of the Lord Jesus Christ, all worship was carried on by representative rites significant of spiritual and heavenly things, and it was by such worship, founded in that Relation between things spiritual and natural, whereby the latter are images of the former, that, under the Economy which then prevailed, the communication was maintained between heaven and earth, between
God and man; and unless this communication be maintained by some means, neither man nor the earth could continue in existence.
Ceremonies then, which, under such an Economy, were solemnly performed according to this Relation of Analogy, sometimes produced natural effects, answering to those spiritual ones which real worship, with its accompanying graces, produces in the mind: as was often the case with the rites prescribed by divine authority to the Israelitish Church; of which we shall give an example or two in a subsequent Lecture.

We will briefly state what appears to be implied by the circumThe ark, under the Israelitish Disstances of the present history.
pensation, was a symbol of the Divine Presence, which none but the truly good can endure, and they not too near; and which causes the lusts cherished by the wicked more openly to become their
The Philistines represent those who exalt faith above tormentors.
charity, making the former every thing, and the latter of no account; which was the reason of their continual wars with the
Israelites, who represent the true church, or those who cherish faith in union with charity. The idol Dagon is the religion of those who are represented by the Philistines.
The emerods with which they were smitten, are symbols of the appetites of the natural man,
which, when separated from spiritual affections, as is done by those who do not apply their faith to the purification of their lives,
The mice, by which the land was devastated, are are unclean.
images of the lust of destroying by false interpretation the spiritual nourishment which the church derives from the Word of God, as is done by those who separate faith from charity.
The emerods of gold exhibit the natural appetites as purified and made good.
The golden mice symbolize the healing of the tendency to false inare submitted to the Lord.

terpretation effected by admitting a regard to goodness; for of this, as we shall see in the next example, gold is an emblem.
The cows are types of the natural man, in regard to such good qualities
Their lowing by the way expresses the repugas he possesses.
nance of the natural man to the process of conversion. And the offering of them up for a burnt offering, typifies that restoration of Older which takes place in the mind, when the natural affections
It would detain us too long were we to stay to offer proof of the truth of these explanations: every one may verify them for himself, by trying what sense will be drawn from other passages of Scripture, where the same emblems are used, on giving them the same interpretation; for if the signification thus obtained be every where coherent and satisfactory, the meaning assigned to the symbols must be the true one. .But whether our explanation be the true one or not, it will not affect the position for which the history is here cited: It will still be certain, that the ceremonies directed by the Philistine priests and diviners must have been intended to have some meaning: As the expected events followed, it must be true that the operations they prescribed must have had a real analogy to certain things of a spiritual nature: and of this, they must have possessed a knowledge.

But further.

That an acquaintance with the Relation which natural things bear to spiritual was in ancient times widely extended, and that it was not altogether lost sight of among the eastern nations at the period of the commencement of the Christian era, is evident from the account of the wise men of the east, who,
under the guidance of a star, came and "presented unto" the infant Saviour "gifts; gold, frankincense, and myrrh."*

Without entering into the inquiry respecting the nature of the star that appeared, the spiritual thing represented by it is obvious.

Stars,

as being luminous bodies, and thus belonging to the general analogy of light, which, we have seen, answers to truth, are apt images of knowledge or information upon spiritual subjects: hence this star,
which conducted the wise men to Jesus, was an appropriate type of that knowledge respecting the promised advent of the Lord,
which was retained, from ancient tradition, among the eastern
The gifts which they offered were emblematical of the people.

* Matt. ii. 11.
worship which the truly wise will ever be foremost in yielding to
"Him that was born King of the Jews*:" on which subject we will offer a little explanation.

By the gifts which the wise men presented, is pointed out, what the nature of all divine worship must be, if he who engages in it wishes it to be acceptable to the Lord or beneficial to himself. An offering of gold, on account of the density, ductility, indestructibility, beautiful colour, and other superior qualities of that metal,
was seen in ancient times, when the perception of such analogies was more extensive than at present, to be expressive of worship from a principle of pure love or goodness in the will, which is the deepest ground from which we can present an offering to the Lord.
It was on account of this signification of gold that so much use was made of it in the representative service of the Jewish tabernacle; most of the holy furniture of which was overlaid or otherwise ornamented with gold, if not made of it entirely: for this use of it was designed to express, that there can be no worship of the

Lord, and no religion, unless there be in the heart of the worshiper a principle of sterling goodness, -- a love towards the Lord and his neighbour.

The second offering was of frankincense, which represents worship from a principle of truth in the understanding *
that is, not from truth merely known and comprehended, for this,
nevertheless, may not form the spontaneous sentiment of a man's own mind; but from truth loved, and of course obeyed, as well as
This signification of frankincense may comprehended and known.
be gathered from its being the chief ingredient in the holy perfume or incense, which was burnt upon the golden altar in the holy placef; and from its being added as a kind of seasoning to the meat-offerings J, and spread upon the shew-bread§; for the smoke of incense is a striking symbol of the aspirations to the Lord of the heaven-directed mind, and of the thoughts of a heart that contiSo the offering of myrrh represented worship nually turns to him.
from a suitable life and conversation; and although this cannot so directly be proved, it is evident from this fact; that whatever is really in the will, and thence in the understanding, never stops there inactive, but descends, on every suitable occasion, into life
This is the reason why, in the Scriptures, so many and action.

* Matt. ii. 2.

f Exod. xxx. 34.

§ Ch. xxiv. 7.

J Lev. ii. 1, 2, 15, 1G.

instances occur, as in this passage, of a three-fold arrangement.
The particulars so enumerated are sometimes in an ascending series,
but more frequently, as here, in a descending one; and then the last in order, as the myrrh is in this instance, denotes the ultimate
Myrrh, also, was effect of the union and activity of the prior two.

one of the ingredients of the holy oil with which all the persons and vessels employed in the tabernacle-service were to be anointed*:
by which oil was signified good of all orders and degrees, beginning from the most common or lowest, represented by the myrrh,
which is therefore mentioned in the first place, (the ascending series being that which is here adopted,) and rising to the purest and most exalted, represented by the pure olive oil, which is mentioned the last. That the ointment thus compounded was intended to be a type of love and charity, with their uniting tendency and all their beneficial operations, may be gathered from the manner in which it is mentioned by David: "Behold, how good and pleasant a thingit is for brethren to dwell together in unity !
It is like the precious ointment upon the head, that ran down upon the beard, even
Aaron's beard; that went down to the skirts of his garments."!
The introduction here, by the inspired writer, of the "precious ointment", would only make a simile without resemblance, if there were not an analogy between its nature and that of the virtue whose praise he celebrates.

Now it may fairly be inferred, that the wise men would not have
"worshiped" "the young child" by these natural emblems, so exactly typifying the spiritual worship due to that Divine Nature which was assuming this mode of manifesting itself to the world,
had they not been apprized, to some extent, of the analogy between things natural and things spiritual.
Nothing but this could have dictated the performance of acts so significant and appropriate.
Without such a guide, they might, certainly, have brought presents,
in token of respect: but it must have been by a rare chance indeed that they could have fixed upon articles so exactly symbolic of the sentiments proper to the occasion.

2. But if we were to turn to the writings and other monuments yet extant of profane antiquity, we should find proofs multiplying all around us, to evince, that in very ancient times the knowledge

* Exod. xxx. 23, 24, 25.

f p s. cxxxiii. 1, 2.



of the Relation between things spiritual and things natural was very much cultivated indeed: in fact, we should see reason to conclude, that the ancients knew of no other way of expressing their conceptions respecting spiritual and heavenly subjects, but by clothWho, for ing them with images drawn from natural objects.
instance, can doubt, that the fables of their Mythology were all originally framed upon this principle? These fables have been handed down to us with many mutilations, additions, and other depravations, being now only found in the writings of authors who did not understand them, and who had received them from traditionary relaters, of whom, likewise, many were ignorant of their meaning, and frequently confounded different things together: yet many of these fables still exhibit marks which evince, that their first authors composed them by the aid of a correct knowledge of the spiritual and moral analogy of natural things, and designed them to convey lessons of interior wisdom. Thus, though some of the heathen deities might be no more than deified men,  --  persons who, while they lived, had been benefactors to their species; (in which light some of the later ancients, and many of the moderns, have chosen to consider them
;) yet how much more reasonable is the opinion of the wiser all ancients, followed likewise by many of the moderns, that the personifications of the Grecian mythology were only designed to represent the distinct attributes of the One Infinite God, and were not intended to be considered as exisiting in separate personal forms, but had such forms assigned them merely to render the contemplation of the various divine perfections more easy to the human understanding; whilst the regarding of them as so many separate gods, and the worshiping of them as such, were innovations of the ignorant vulgar, -- exactly of the same natm'e as that which has been introduced by some of the moderns, in making a
We complete separation of the persons of the Christian Trinity.
will endeavour to sketch an idea of some of the leading characters of this mythology, and of the design of a few of its principal fables.

It is a fact which will readily be admitted, that the Divine Being is regarded and worshiped, by all mankind, through the medium of the conceptions which they have formed of him in their own minds,
and that none are able to conceive an idea of him that is at all adequate to what he is in Himself, since it is impossible for a finite


being to comprehend the Infinite: hence the idea of God cannot, be exactly the same in any two minds; and in persons of very dissimiliar religious sentiments it must be very different indeed. Now it appears to have been the custom among the ancients, when a very great change took place in men's modes of conceiving of the
Deity, to assign to him a different name: the propriety of which practice seems to be recognized in the Scriptures, where we find the Lord saying to Moses, when about to communicate a new revelation different from that which had existed before, "I appeared unto Abraham, unto Isaac, and unto Jacob, by the name of
God Almighty, but by my name Jelwvali was I not known to them."*
Thus we are not to conclude that the wiser ancients regarded their supreme god, Jupiter, as a different divine being from the older supreme god, Saturn; but that under those distinct names, to each of which they assigned distinct attributes, they personified the different ideas of the Supreme Being entertained by two very different generations of mankind, -- by men of such essentially distinct genius and character as those may well be conceived to have been, who lived before, and who lived after, the Scriptural catastrophe of the flood. And as the latter race of men were descended from the former, and their idea of God sprung out of that which had been conceived by the previous generation, -- was, in fact, the offspring of it, -- they transferred this idea to the deities themselves,

and described Jupiter as the son of Saturn: for which also there was a further reason, to which we shall presently advert.

But the occasion on which Jupiter is fabled to have succeeded to the throne of heaven, was this: a war was waged against Saturn by the first race of giants,

called the Titans, -- evidently the
"Nephilim "of the Scriptures-}-, -- who, it is pretended, would have succeeded in their enterprise, had not Jupiter flown to the assistance of his father, and discomfited the enemy with his thunderbolts after which, like many other auxiliaries of distressed sovereigns, he seized the reins of government for himself. Now if we conceive
Saturn to be a personified idea of the Divine Being more in regard to that pure goodness, which, the poet assures us, prevailed under his dominion among mankind, when

* Exod. vi. 3.
t In the original of Gen vi. 4. The later races of giants are called Rephaim.
Mollia secures peragebant otia gentesi

Sine militis nsu and which procured for the Saturnia regna, in the language of analogy, the expressive synonyme of "the golden age", (though the use of that metal was then unknown j -- according to the poet, not yet itum est in viscera terra, nor yetferro nocentius aurum Prodierat) ;
 -- if we regard the Titans as the direful perversions of such a state
 -- the lust of empire and pride of self-exaltation most opposite to inoffensive benevolence; -- if we see in Jupiter a personification of the Divine Being more in regard to that other great essential property of Deity, pure Truth, which is the agent in eveiy divine work of judgment and of restoration, and of the manifestation or revelation of which, thunder, often deemed by the vulgar the voice of
God, and lightning, the sudden irradiations of which have such an awakening effect, are natural images; -- and if we conceive further,
what was clearly the fact, that the character of the people who lived after the flood was less affectionate and more intellectual than before, -- that sciences, distinct from the intuitive perceptions inherent in the love of exalted goodness, then first began to be cultivated, -- 
thus, that the altered genius of mankind led them to view the
Divine Being more in his character of pure but benignant Truth,
than of simple unmixed Goodness, -- or as a Jupiter rather than a
Saturn; -- whence, also, with the reign of Jupiter commenced the silver age, -- silver being, among metals, the symbol of pure, interior truth, as gold is that of pure, exalted goodness: --  If, I say,
we accept these views, we at least shall have a theory which well agrees with the facts, as established by higher authority, and which affords, -- may I be allowed to say? -- a beautiful solution of the circumstances of the fable.

Nor does the fiction, that it was the practice of Saturn always to devour his offspring, detract from the character here given him, as the personification of unmixed goodness: for children, in the language of analogy, viewed in relation to their father, are as the perceptions and thoughts of the intellect in relation to the love, affecEvery one who reflects tion, or desire, which gives them birth.
on the operations of his own mind, must see, that thought, the ob*
ject of which is truth, or what is esteemed to be truth, is entirely the offspring of affection.

Take away all affection, -- reduce the mind to a state of perfect apathy, -- and you will immediately cease


to think: on the contrary, when any affection is in high excitement, how active are the thoughts ! what a tumult of ideas, -- what multitudes of reasonings, crowd into the intellect, when violent
It is in agreement, then, with true passions agitate the will !

philosophy, to regard Truth as the offspring of Goodness, this being essentially Love, to some species of which all the affections belong: whence we see the further reason, alluded to above, for considering Jupiter, who was the personification of the Divine
Being in respect more to his essential attribute of Truth than of
Goodness, as the son of Saturn, who was the personification of the
Divine Being in respect more to his essential attribute of Goodness than of Truth. We are not however to suppose that the people of the golden age regarded the Divine Being as Goodness or Love alone, without Truth or Wisdom, nor that the silver age regarded him as Truth or Wisdom alone, without Goodness or Love s the former worshiped him as Divine Goodness from which proceeds
Divine Truth, and the latter as Divine Truth within which is Divine
Goodness. Now it was contrary to the peculiar genius of the people of those primeval times, to be willing to contemplate any thing of mere intellect separate from its parent affection: to do so they would have considered as an awful lapse from the perfection of the human character: they viewed all truth as inherent in its parent affection, and, though continually produced by it, conIn agreement with this sentiment,
tinually resolving itself into it.
the preservation of Jupiter and his brothers is fabled to have been effected by the artifice of his mother Rhea term used in the language of analogy, for that which, in the language of theology, is called the external man:
the external that intermediate spiritual births are produced by the internal, and it is by the suggestions of the external, or by acceding to its inclinations, that they are viewed as altogether separate.
The artifice, too, by which Saturn was deceived by Rhea, was, her giving him a stone to swallow instead of his son; -- a monstrous the earth, -- which is a it is by inclining to absurdity, if any thing like a literal history be supposed to be intended, but a beautiful combination of the analogies of different

For a orders of existences, if the involved mystery be regarded.
stone, among inanimate things of the lowest order, belongs to the same general analogies as a son does among the highest; both are types of the objects of intellect; a stone being a symbol of truth in


its lowest sphere, when clothed with appearances taken from the world of nature, and a son being a symbol of truth when living in the perceptions of the human mind. Now that, in this se?ise, strange as it may sound, stones were swallowed by the primeval inhabitants of the world, cannot be doubted, if we believe, as is highly reasonable, first, that there is such a mutual relation between natural things and spiritual, that the latter are reflected by all the objects of creation; secondly, that this analogy was intuitively apprehended by those ancients, so that, to them, every thing in nature conveyed a spiritual idea, and, by them, "the invisible things of
God were clearly seen in the things that are made;" and, lastly,
that the exalted affection for goodness in which they were principled, beholding in terrestrial objects nothing but images of heavenly ones, eagerly seized the ideas thus presented, and incorporated
Hence, as they viewed God through the medium them with itself.
of the conceptions of their own minds, so that their Supreme Deity may be considered, as noticed above in the case of the idol Dagon,
as the personified abstraction of their leading religious sentiments,

they depicted Saturn as the devourer of his children, or of stones in their stead.

And here be it observed, that such a mode of representing spiritual subjects, so long as it was understood, must have been equally delightful and instructive: but in the degenerate times that succeeded; -- to speak in their own language, -- in the copper age,
when men regarded only external goodness, cultivating merely natural affections, -- and still more in the iron age, when they took
 -- such repre-

their character from a merely external understanding, and no longer had spiritual, but only natural conceptions of truth
Then, understanding sentations became liable to great abuse.
literally this, so understood, flagitious practice of Saturn, and the similar deeds of their other divinities, they changed the whole into a system of abomination and impurity, never dreamed of by its inventors; and villainy pretended to perpetrate its crimes under the express sanction of the gods.

But to return. We have selected the above fables for illustration, as being fundamental ones, on which the whole of the Greek mythology turns: otherwise, some of the others would perhaps admit of a more familiar explanation. When, for instance, a second race of giants is fabled to have made a second insurrection, and to


have heaped mountain upon mountain to scale the walla of heaven
(, an occurrence which is described in Scripture by the parallel scheme of building "a tower whose top should reach unto heaven")* ; and when the gods are said, in fear, to have tied for refuge to Egypt, and there to have disguised themselves by taking the forms of various animals, Jupiter assuming the figure of a ram,

Juno that of a white cow, and the like; -- how aptly may we see described the desolation, through the prevalence of extravagant lusts and wild phantasies, of all that constitutes real religion, until all true knowledge of the divine nature and attributes is banished,
the graces of the truly spiritual man are no more, and nothing of them is left but some good affections (represented by the animals in which the deities lurked,) in the natural man, which in this fable, as in the Scriptures, is typified by Egypt ! On this occasion,
also, it was oracularly pronounced, that the gods must finally be vanquished, unless they called a mortal to their aid: where again we see a proof, that by their gods they did not strictly understand the Deity as he is in Himself, but as he is received, and as ideas are formed of him, in the human mind: for none could imagine that any insurrection from hell could injure the Deity Himself, though it might abolish the graces of which he is the author, from the mind of man.
The fable adds, that in compliance with the oracle,
the gods avail themselves of the assistance of Hercules, the son of
Jupiter by a human mother, by whose help they regained Olympus in which, I think, the serious Christian must discover, whatever the infidel may think of it, a knowledge among the gentiles of that genuine oracular declaration which said, that the seed of the woman should bruise the serpent's head. Indeed, the whole history of Hercules and his labours evinces, that they who constructed it, had a knowledge of the Redeemer who <was to come, and of the redemption which was to be wrought by the Incarnate God, who,
" having spoiled principalities and powersf", and "destroyed him that had the power of death"! was to be made "perfect through sufferings!," "crowned with glory and lion our
:" which truths

|J

they involved in their customary style of fable, filled with circumstances drawn from the language of spiritual analogy.

Once more.

If we were apprized that, in its spiritual reference that common Scripture-emblem, the horse, expresses the under

*Gen.xl4.

fCol.ii. 15.

J Heb. ii. 14.

§ Ver. 10.

|| Ver. 9.
standing or apprehension of Truth, -- whence four horses appeared,
in the Revelation, to proceed out of a book*, and on another was seen riding in heaven He whose "name is called The Word of
Godf", -- we shonld perceive the reason why horses were assigned

[LECT.

to Neptune, the god of the ocean, or of the waters, though they seem so little adapted to that element: -- why a chariot and horses of fire were attributed to the sun, the source of light, or of Phoebus, the god
 -- why the fountain of Hippocrene, in Mount Parnassus, the of day haunt of the nine Muses, or the sciences, who were the daughters of
Jupiter and Memory, was said to have been opened by a blow from the hoof of the winged horse, Pegasus: -- why all the principal heroes and demi-gods were represented to have received their institution in learning from the Centaurs, an imaginary raoe compounded of the man and the horse; who also were famous for their skill in medicine, and instructed in that art the god of medicine, iEsculapius himself: -- why the device, whatever it was, by which the Grecian commanders introduced a body of troops within the walls of Troy,
was symbolized by a wooden horse .- -- and why, on the founding of
Athens, that celebrated seat of science and philosophy, when Minerva and Neptune were contending for the honour of giving it a name,

Neptune, to display his power, is said to have struck the ground with his trident, when there instantly darted forth a horse; yet the disputed honour was awarded to Minerva, at whose bidding there sprung up an olive-tree;- -- a fable which beautifully represents the superiority of that wisdom figured by the goddess, which regards the conduct of life, and leads to the feeling of benevolence terminating in icorks of utility, -- *of which sentiment the olive-tree is the symbol, -- over those mere accumulations of knowledge typified by the waters of the ocean, and having a personified abstract in Neptune; these only enabling their possessor to dazzle by intellectual display, or to overwhelm by ratiocination; -- of which exercises the toar-horse is so expressive an emblem.

The brevity to which these explanations have been necessarily confined may perhaps have been such as to prevent their truth from being fully perceived: -- there is also much difficulty in conveying by abstract expressions the exact ideas intended; in which respect,
as intimated above, the language of analogy, when once understood,

has an immense superiority: -- but surely no one can doubt, that

* Ch. vi. 1, 4, 5, 8.

f Ch. xix. 11, 13.


these fables were all intended by their authors to have a specific
There is an evident uniformity in their construction.
meaning.
They are all compounded of personified abstractions, and of material images taken from actually existing objects 5 and it is plain that,
by the material images applied, material things are not intended,
but that they are used as symbols, according to some regular principle, founded in a similitude observed by the composers between the images employed and certain moral or spiritual things intended to be expressed: And what can this regular principle be, and what the similitude observed, but such a Mutual Eelation, or Eelation of Analogy, between natural things and spiritual, as renders the former expressive mediums for conveying to the mind ideas of the
Altogether, I think it certain, that no one can examine the latter?

fables of the Greek mythology, with a view to this inquiry, without being satisfied, that such an immutable Eelation between the different orders of existences does prevail, and that when those fables were composed it must have been well understood.

The same observation may be extended to the Asiatic mythologies, since the affinity between these and the Grecian is well known,
and modern researches have even discovered, on the banks of the
Ganges, some of the imaginary deities so long since banished from
Since the acquisition, by this country, of the rest of the world.

such extensive possessions in India, the attention of the learned has been much directed to the sacred books and traditions of that very ancient nation; and here, still more than in the mythological tales of the ancient Greeks, astonishment has been excited by the marvellous character of the relations which compose their records. But little certain knowledge has yet been developed by the illustrious scholars who have endeavoured to open this rich mine of science the reason is, because they have chiefly sought, in the extraordinary-

narratives which they have studied, for information on questions of ancient history, geography, and chronology j whereas, when the respecting higher subjects.

traditions of the highest antiquity appear to treat of such matters,
it is only for the sake of making them the vehicles of information
To decypher such compositions, the
As nothing but this will satisfactorily explain the mythological fables science of Analogies will be found to be the master-key.

of the Greeks; so likewise must our Orientalists avail themselves of this, before they will be able to unfold the kindred theogonies of tLe Hindoos; for it evidently was by persons skilled in this science, that these, also, were composed.

Nor is the once famous country of Egypt to be by any means excluded from this enumeration of the ancient cultivators of this study: on the contrary, could all written and traditionary learning be extirpated from the earth, Egypt would still present her imperishable monuments, silently but irrefutably proclaiming, that there,

indeed, the Relation of Analogy between the various kingdoms of nature, with their individual objects, and each other; and between all of these, again, and things moral, spiritual, and divine; wa3

once -- yea, for ages, -- well understood; that there it stamped a character upon all elevated science, and that it regulated there
What can be more evident even the first elements of knowledge.
than that her celebrated Hieroglyphics, which have so long confounded the skill of the learned, are built on this Analogy, and are expressions of it, and that, if ever they are decyphered, it must be by its means? Who could inspect that extraordinary exhibition, a year or two since open in London, respecting the tomb of an
Egyptian king, explored by Mr. Belzoni, and behold the multitude of representations of natural objects, evidently designed to convey a mystical meaning, without feeling satisfied that the arrangement of them must be governed by some Rule, and that it assumed for its basis a known Analogy? Who can escape the same impressions on viewing the Egyptian antiquities in the British Museum. To particularize only one palpable emblem, the meaning of which requires no discussion to establish it: Who can behold those monstrous fists, carved out of the hardest of rocks, without being convinced that they were designed to symbolize that irresistible power that could crush opposers into annihilation? that their meaning is similar to that of the stone mentioned in the gospel, of which it is said, that "on whomsoever it shall fall, it will grind km to powier?" *
So it is evident that in the wonderful scheme of symbolic writing contrived by this singular people, the natural objects depicted were put to convey ideas quite distinct from any thing immediately belonging to the objects themselves: they delineated one thing to express another: they evidently were guided by some
Analogy which they saw between the two: and it is much more reasonable to conclude that they followed a principle known by

* Matt. xxi. 44.
them to exist in the nature of things, than that the whole of so complicated a system was merely founded in arbitrary assumption.

From the whole of this branch of our investigation, then, these conclusions appear to be certain: That among all the celebrated nations of antiquity, the knowledge of a Mutual Relation, regarded as real, between the different orders of existences in the universe,
once was general: that it formed the peculiar learning of the priests, aud was studied by all who aspired to the distinction of erudition.

V. The final conclusion intended to be deduced by the help of what has been advanced in this Lecture, is, that in the Eelation of
Analogy between things natural and things spiritual, (which we may now, it is hoped, consider as established,) is to be found the
Law or Rule according to which the Scriptures are written, and that a knowledge of it will afford the key by which their "dark
At least, sufficient reason has persayings" must be decyphered.
haps been shewn, to make it highly probable that such is the fact,
and to entitle the application of the system of interpretation proposed, to a very attentive examination; and this probability, and claim to examination, are greatly strengthened, wheii it is considered, that the early part of the Scriptures was written, whilst this
Relation was cultivated among many nations as a science, and the latter part before the knowledge of it was every where quite extinct;
which alone affords some presumption, conjointly with the extraordinary character of their style, that they are composed accoi ding to
But to establish this conclusion by a wider induction will be it.

the object of the two next Lectures.

Now as it has, I trust, been solidly evinced, that the Relation of
Analogy between the different orders of existences is irreversibly founded in the very nature of things, and may even be considered as one of the most fundamental laws of Nature; and not only so,
but that there is a tendency to express ourselves according to it in common speech; this must shield the idea of applying it as a Rule for the interpretation of the Scriptures from the imputation of fancifulness: and as it has, I trust, appeared equally certain, from the latter part of this Lecture, that this Analogy was in ancient times

6


well understood, and that many compositions were then framed by its laws; this must vindicate the principle from the charge of
It is true that this science (, for such it may justly be novelty.
called,) has been lost sight of for many ages; that though mankind have continued to behold its phenomena, they have neglected to reflect on their cause: but it is equally true that for a still longer course of ages, prior to this interval of oblivion, -- from Adam himself through Noah and his descendants, -- it was generally understood.

Sciences of a more external kind, having natural things alone for their objects, have since been cultivated in its place: but now, when these seem to have arrived almost at their perfection,
when all the mysteries that Nature conceals in her bosom appear nearly to have been opened to our view; (as to their general branches, we mean, -- for new particulars will be discoverable to eternity;) it surely is time to turn our attention to a science which connects natural knowledge with spiritual, and sheds superior light
In the first ages, interior wisdom was cultivated, to the on both.

neglect of exterior knowledge: in later ages, exterior knowledge has been pursued, to the neglect of interior wisdom: in future
The advantages of this union
As the doctrine of Analogy is cultivated, it will no ages, doubtless, they will be united.

will be great.

longer be the reproach, as heretofore, of Science, that she has a tendency to lead her votaries to scepticism in regard to religion for natural things will then all be viewed as the outbirths of spi^
ritual essences, and so to be connected by an indissoluble tie with the Great Author of both, the Creator and Preserver of all things.

As, at the same time, religion will be cleared of its corruptions,
and the Bible, understood by the aid of this science, will no longer be represented as sanctioning doctrines which reason oondemns;
that enlargement of mind which knowledge produces will cease to
The become an obstacle in the way of the most oordial faith.
Science of Analogies, by unfolding the interior contents of the
Sacred Volume, and explaining, as we shall see in the sequel, all those appearances that seem, either trifling or contradictory, will reconcile the jarrings, so long thought irreconcilable, between
Eeason and Revelation; just as, by shewing the origin and spiritual relation of all objects in nature, it will conciliate knowledge

Every friend, then, to Revelation and to Piety, -- yea,

with piety.

every admirer of Reason and of Knowledge, is deeply interested in the restoration of this Science; and both should unite to bring on the time, when, as among the ancients, the highest wisdom shall be that which is conversant with spiritual subjects, and the first of sciences that which teaches the Relation between spiritual subjects and the appearances in nature.



