= Additamentum
By the Rev. Erik Sandstrom, Sr.
include::../template-attributes.adoc[]

"The Human Essence was only a something that was added (modo *additamentum*) to His Divine Essence that was- from eternity" - AC 1461e.

"The Lord, before His coming into the world, was indeed present with the men of the Church, but mediately through angels who represented Him; but since His coming He is present with the men of the Church immediately, for in the world He put on also the Divine Natural, in which He is present with men." - TCR 109

"There is a Divine Trinity, which is Father, Son, and Holy Spirit." - TCR 164. "This Trinity was not before the world was created, but after the world was created, when God became incarnate, it was provided for and came into existence (provisa et facta sit), and then in the Lord God the Redeemer and Saviour Jesus Christ." - TCR 170. "This Church (the Apostolic) did not acknowledge three Divine Persons, and therefore neither a Son of God from eternity, but only a Son of God born in time ... and by no means any Son of God born from eternity." - TCR 636

"It has been told me from heaven that in the Lord from eternity, who is Jehovah, before His assumption of a Human in the world, the two prior degrees existed actually, and the third degree potentially, as they do also with angels; but that after his assumption of the Human in the world He put on over these a third degree, called the natural, thereby becoming Man like a man in the world, but with the difference that in the Lord this degree, like the prior degrees, is infinite and uncreate, while in angel and in man they are all finite and created." - DLW 233.

"Abraham represented both the Divine Itself which is called the 'Father', and the Divine Human which is called the 'Son', thus he represented the Lord as to both the Divine Itself and the Divine Human, but that Divine Human which is from eternity, from which came forth and to which He reduced or brought the Human that was born in time, when He glorified it." - AC 3251e

"The Only-begotten Son ... hath set Him forth." - John 1:18

It is clear from these teachings:

1. That the *Additamentum* is the Divine Natural which the Lord put on in the world;
2. That this Divine Natural is in itself infinite and uncreate;
3. That nevertheless at a certain point in history, 1980 years ago, it was "born" in a new and special way;
4. That "the Lord from eternity", or the Divine Celestial-Spiritual-and Natural from eternity, or again "that Divine Human which is from eternity", was ever present with men, but prior to the incarnation only mediately through the angelic heaven;
5. That through the Human Essence which was born in time, and which was "only a something added," the Lord became immediately present with men;
6. That this immediate presence, coming about, as was the case, in and through the Lord's Natural, was a presence with men's natural; and
7. That this presence consisted in the Lord's Additamentum (the Divine Natural, the Only-begotten who is in the bosom of the Father) setting forth the Divine in the Human to view before the natural mind of men, that is, consisted in the Lord our God becoming the visible God.

The underlying theme in the passages quoted above is the same. We are not to think, for example, that the statement that the Divine Natural which the Lord assumed while in the world is infinite and uncreate, is in conflict with the teaching that the Son of God, i.e. this same Divine Natural, was born in time. I am sure this underlying theme can be stated in many ways. The following may be one: The Lord God from eternity revealed Himself to men and angels in a new way, when in the fulness of time it became necessary to do so in order to save them. But the points made so far, and related points, require further examination. The following propositions, therefore, will be discussed.


a. The "Divine Celestial", "Divine Spiritual", and "Divine Natural" are so named relative to the reception with men and angels.
b. Of all the five major church dispensations that have been in the world, the New Church alone is said to worship one Visible God; and this for the reason that the Lord in His Divine Natural is now visible to the natural mind of man.
c. The "Divine Human" therefore means the Lord as visible.
d. The Lord's Divine Human, thus His Divine Body, was not only conceived but also born of Jehovah; thus it was in no sense derived from Mary.
e. Nothing whatever from matter was "added" to the Lord; thus the "Additamentum" must be understood in a different context.
f. The Lord's coming into the world involved no change within the Lord Himself, i.e. in the Divine Substance.
g. The purpose in the Lord's temptation battles, therefore in His union with the Divine within Himself, or His glorification, was His conjunction with the human race.
h. There is no salvation without freedom; but freedom involves understanding, and understanding involves seeing the Lord.
i. The Lord from love by means of wisdom accommodates His operation to the states and needs of men; thus the mode and timing of His two advents were determined by those states and needs.
j. What applies to the Lord, applies to the Word.
k. Because the Lord made Himself visible in the natural, therefore His operation became visible also: the whole Trinity which is in the Lord, is now visible.
l. There is a Divine sequence or trilogy: Glorification - Revelation -
Salvation.

***

<<<

== a. The "Divine Celestial", the "Divine Spiritual", and the "Divine Natural."

We read: "The Divine Celestial and the Divine Spiritual are such in respect to those who receive the Divine of the Lord, for the Lord appears to every one according to the nature of him who receives ... as is clearly manifest from the fact that the Lord appears in one way to the celestial, but in another to the spiritual" (AC 3235:2) ...
"consequently the Divine in the one heaven is called the "Divine Celestial", and the Divine in the other heaven the "Divine Spiritual" (AC 8827). We also read: "In the Lord, and consequently from the Lord there is the Divine Celestial, the Divine Spiritual, and the Divine Natural ... Since these three are in the Lord, therefore those three are also in the angelic heaven" (AR 49); or as stated elsewhere: "From the Lord proceeds the Divine Celestial, the Divine Spiritual, and the Divine Natural. Whatever proceeds from His Divine love is called Divine Celestial, and all this is good; whatever proceeds from His Divine wisdom is called Divine Spiritual, and all this is truth; the Divine Natural is from both, and is their complex in the ultimate" (TCR 195).

We note the words, "In the Lord and consequently from the Lord." How are these degrees "in" the Lord? -"Distinctly (or distinguishably)
one", answers the Divine Love and Wisdom (cf. Nos. 14ff and 17ff), and the work adds that they are all "infinite and uncreate" (No. 230). But we get a further insight from AC 6417e: "The Lord is nothing else than Divine Good. That which proceeds from His Divine Good and flows into heaven, in His celestial kingdom is called the Divine Celestial, and in His spiritual kingdom the Divine Spiritual; thus the Divine Celestial and the Divine Spiritual are so called relatively to receptions."

Now the infinite and uncreate is one and indivisible. It is not as though the Lord was now in one degree, and then in another; nor as though He would consult within Himself as to what degree within Himself to put into action. The Lord is nothing else than Divine Good. He is pure Love. Wisdom cannot be said to be "added" to it, for infinite Love is itself infinitely wise. Love in its infinite perfection does not "consult" wisdom. Not even the celestial angels (who are likenesses of God) do; even they act spontaneously from a "yea-yea or nay-nay" wisdom that is inscribed in their love. How much more the Lord! But we, men and angels, turning to the Lord, view Him according to the nature of our spiritual eye. Thus it is that all influx from the Divine is according to the state of the receiving vessel, whatever the state of that vessel.

Yet we (from the Writings) speak of Love and Wisdom, and we do because to us, and to angels below the highest heaven, they appear as two. We as it were separate the act from the ruling love out of which it proceeds. Frequently we are even entirely oblivious of the very existence of such a love, let alone its nature. Yet every act is nothing but love acting and every word is nothing but love speaking. In either case it is love forming itself. This, if the love is genuinely good, we call wisdom. So the Divine Operation and the Divine Word are nothing but the infinite Divine Love acting and speaking -- nor can it act or speak except in such a way as to carry out precisely what it intends, thus with perfect wisdom.

Our age, however, is spiritual rather than celestial in character. We are brought to order by means of truth, not by means of good. We can see the truth, but we have no feel for what is good, not until after regeneration. And the truth with us is in the beginning harsh and argumentative, and uncomfortably convincing. To us it is something apart from good. What it actually is in itself we have to learn, because we do not perceive it. A regenerate state does perceive it. In the meantime we have to learn that in itself truth is nothing but good, that is, the very form of good.

So, therefore, when the Lord "puts on" His Celestial in the highest heaven, or "puts on" His Spiritual in the middle heaven, or "puts on"
His Natural in the New Christian Heaven and in the world, He does so by acting and speaking according to the state of the reception in each case.

It follows that the Lord's putting on the Divine Natural by coming into the world, means that His infinite love to save took to itself a new mode of accommodation. This new mode was the Word becoming Flesh and dwelling among us. And while this accommodation was a stupendous act, with stupendous and eternal consequences, yet the Word in the Flesh, or the Personified Word, called the Lord's Human Essence, "was only an Additamentum to His Divine Essence that was from eternity" (AC 1461e). After all, the infinite love that sent the Lord into the world, had foreseen all things, willed all things, from eternity. All that was now needed was to do what was ever intrinsic in the Lord's love, namely, to reach out, or down, in fulness; all that was needed was to put on Flesh.

Thus it is-that what is called "only an Additamentum" was inscribed in the Lord's Divine Essence from eternity. It follows that the Additamentum too is infinite and uncreate.

To this, however, should be added as a postscript that when the Lord was in the world (for about thirty-three years) changes took place, so that He moved from glorifying His celestial and spiritual to glorifying His natural also. He thus suffered Himself to pass through successive states. We therefore read of the Lord having "perception from the Divine Celestial", and "thought from the Divine Celestial through the Divine Spiritual" (AC 2619); also "perception from the Divine Natural" (AC 3209), etc. -- concepts which, as the Writings note, do not "fall into even the most enlightened apprehension by means of things that belong to the light of the world" (2619). These states, however, pertained to the Lord before His glorification. He came into perceptions as He overcame in temptations; and as He glorified the whole of His natural, all the three degrees of it, His perceptions descended into greater and greater fulness, as His Divine descended, infilling, further and further down towards the very sensual and corporeal of what He had inherited through Mary.

AC 2814 and surrounding numbers draw the distinction between what pertained to the Lord before and after His glorification. In the prior state He was in appearances of truth "such as the angels have", and in that state He could be tempted; but as He overcame He came into Divine Truth, which "is above appearances, nor can it possibly come to any understanding, and still less to the apprehension of man, nor even to that of angels, and thus not at all to anything of temptation." As He passed from the appearances that were in His natural before the glorification and instead took to Himself the very Divine Truth, so He would enter into fuller and fuller Divine perceptions in that Natural -- first, as I understand it, into Divine Celestial perceptions, then into perceptions that were in His Divine Spiritual and Divine Natural also; and this because His glorification progressed as His Divine by degrees descended.

I add this "postscript" in the hope of forestalling any confusion that might arise from what appears to be different sets of passages, one treating of the Lord on earth during the process of glorification, and the other telling us of the influx from the Lord's Divine Human into the three heavens which are from Him. To the latter set of teachings belongs everything that is said about the Lord's glorified Divine Natural, in which He stands forth as our God, to be seen and known by us even in our natural minds.

***

== b. The New Church alone is said to worship one Visible God.
This means that in all the four previous major church eras an invisible God was approached. Does this therefore include the Most Ancient Church? It says so. And what of the Christian Church? After all, it was at His first advent that the Lord put on His Divine Natural, and in this Divine Natural He showed Himself to His disciples after His resurrection. But again, it says so; to wit: "The Most Ancient Church, which was before the flood, worshipped an invisible God, with whom there can be no conjunction. The Ancient Church, which was after the flood, did in like manner. The Israelitish Church worshipped Jehovah, who in Himself is an invisible God (Exod. 33:18-23), but under a human form, which Jehovah God put on by means of an angel ... But the fourth Church, which was called the Christian, did indeed acknowledge one God with the mouth, but in three persons ... all invisible because existing in a similar Divine Essence before the world was; and yet, as was said above, there can be no conjunction with an invisible God." (TCR 786)

As for the Most Ancient Church, however, this is not the only thing that is said about it. The language in AE 1116:2 is just about the opposite: "In consequence of the intuition /by which spirits and men when in thought from their spirit think of God as Man/ the most ancient people worshipped a visible God under a human form more than their posterity did."

What then do these two teachings have in common? They have in common that it is only after the Lord's second advent that men will truly see and worship the Lord in their natural mind as well as in their inner minds. The Christian Church might have had at least the beginning of this full sight and full worship; but darkness fell over it at an early stage. An earlier passage in the True Christian Religion has this to say on this point: "After the coming of the Lord into the world a Church was instituted by Him which saw, or rather was able to see, Divine truths in the light" (TCR 109). In our context the significant words are, "Or rather was able to see."

What was possible in the first Christian Church is represented by the words in John, "And we beheld His glory, the glory as of the Only-begotten of the Father" (John 1:14). But what will be possible in the New Christian Church is seen in the words of Matthew: "And they shall see the Son of Man coming in the clouds of heaven with power and great glory" (Matt. 24:30). "Glory" in the first advent; "great glory" in the second: words reminiscent of the teaching in AE 948:2: "When the Lord was in the world He revealed interior Divine truths that were to be for the use of a new Church about to be established by Him, and that did serve that Church. For like reasons the Word has been opened interiorly at this day, and still more interior Divine truths have been revealed therefrom for the use of a new Church that will be called the New Jerusalem." Glory -- great glory; interior Divine truths -- still more interior Divine truths. The first was possible to the first Christian Church, but it did not respond. Will the New Christian Church be more faithful? Will it see and worship and follow the Lord as He reveals Himself in great glory?-- and also with the power that springs from the perception of the good that is within the truth?

The invitation to worship the Lord in our natural minds is of stupendous consequence. The implication is that the whole mind will worship, from inmosts to outmosts. Indeed, the words in the True Christian Religion which are offered as the reason why the New Church is to be the crown of all previous churches, may sound timid and of small moment: "... because man is natural, and thence thinks naturally, and the conjunction must be in his thought, and thus in the affection of his love" (TCR 787). One might even be confused, and think that the whole matter is one of Divine concession, the Lord revealing Himself at least to the natural mind, if man cannot receive Him in any deeper way than that. But returning again to an earlier passage we are helped to realize that the case is quite different. We find this: "From the Divine Natural the Lord enlightens not only the internal spiritual man, but also the external natural: which two, unless they are at the same time enlightened, man is as it were in the shade; but while both are at the same time enlightened, he is as it were in the day" (TCR 109:2: see also AE 759:2; SS 41).

A succinct and profoundly telling statement to the same effect is found in AC 1590: "The three heavens are images of the Lord's External Man."
Three heavens, images of the Lord's External! The reason for this is that the Lord's External or Natural is the Lord in fulness; and to reveal it, is to reveal in fulness -- the fulness of the Divine in the Human. Incidentally, the three heavens here are first of all the three discrete heavens An the New (or Christian) Heaven, for this was the heaven that was established by the revelation of the Lord's glorified Divine Natural in His second advent. The ancient heavens were affected also, indeed profoundly so, but this was because there is an inter-communication between all the heavens. It is particularly in the Apocalypse Revealed we learn about the threefold constitution of heaven that was formed from the Lord's Divine Natural. We read: "Each heaven by itself is distinguished into three heavens, an inmost or third, a middle or second, and a lowest or first; so also this New Heaven" (AR 876; but see also AE 342:3; Coro. 16, 39).

So why is it that the New Church is called "The Crown of all the Churches that have hitherto been in the world? It is not because there was no conjunction of any kind before: no conjunction at all means condemnation. After all, the Most Ancient Church in its integrity was said to "dwell alone", that is, alone with God, meaning that "they were under the Lord's guidance as celestial men, because such were no longer infested by evils, or evil spirits" (AC 139). Rather, the reason is that previously conjunction never comprised the whole man -- nor could it, seeing that it is only by virtue of the opening of the spiritual sense of the Word that the natural mind can be fully opened. It is opened from within and from without at the same time: from within by the influx of light from the Lord through the New Heaven, and from without by the setting forth of the internal Word in natural language. So when the Writings say that conjunction must be in the man's natural thought, and through this in the affection of his love, they are really saying that conjunction is full when it embraces also the lowest mind.

And conjunction is cooperation. The Lord acts, and man, from the Lord, acts as from himself. Man walks with the Lord. The Lord loves infinitely the man's neighbor, and the man loves the same neighbor in his finite way. So also the Lord provides for that neighbor with infinite wisdom, and the man serves him with the finite wisdom and discrimination that the Lord has given him through His Word. Hence the words: "... as I have loved you, that ye also love one another" (John 13:34). The True Christian Religion is explicit on this point: "The reciprocal conjunction between the Lord and man ... is effected by cooperation; for the Lord acts, and man receives action from the Lord, and operates as from himself, yea, of himself from the Lord" (TCR 371:6).

It is clear, therefore, that the as-of-self with man comes fully into its own by virtue of the Lord being visible to his natural mind. It is in our natural man we have all our conscious thoughts and all our conscious affections. These thoughts and affections, if it is well, are not from his natural mind, but from one or other of the degrees within him that belong to the spiritual world; but they are in that mind. If then he can see the Lord and understand the Lord in his natural mind, that is, if he can understand the Lord rationally, then he can truly and fully and responsibly follow. It was the Lord in His Divine Natural who said: "Follow Me."

***

== c. The Divine Human is the Lord as Visible.
If a king is always in his palace, then his people cannot know him first hand. But if he comes out from his palace, and meets with his people, and visits them in their homes, then they get to know him directly. The Lord did that by coming down among men.

But in order to come down He had to take on a body from a woman in the world. He did this by causing His own Divine to enter -- in this one case without the agency of a human father -- into a womb of a virgin. As said the angel: "Therefore also that holy thing which shall be born of thee shall be called the Son of God" (Luke 1:35)

Yet the body from Mary was not the Son of God. It was not the body from Mary, nor the mental heredity that the Lord derived through her, that did the miracles; nor did that mental heredity speak the words when He taught. But the body from Mary was necessary, in order that the Divine, descending, might have worldly hands to move and worldly lips to enunciate words of Divine wisdom. The Divine, therefore, revealed itself by means of the body from Mary. As men saw this Divine, so they saw the Lord; that is to say, so God became visible to them.

Not all did see. Some said: "Is not this Jesus, the son of Joseph, whose father and mother we know?" (John 6:42). But Peter in a moment of revealing insight said: "Thou art the Christ, the Son of the living God" (Matt. 16:16). "Christ" is Greek for the Hebrew "Messiah." But, as we so well know from the Gospels, even the disciples were slow to understand and believe. At the cross they fled, and after the crucifixion they hid themselves for fear of the Jews. Only after the resurrection, when He showed Himself to their spiritual eyes in His Divinely Human body, did they begin to see who He truly was (cf. TCR 777). We say "Begin to see", for a really rational comprehension of the wondrous things they witnessed was yet to await a later age.

But can a man really see God? Certainly, if he were to look into the Lord's Inmost Self he would be consumed. It follows that the Lord can only show Himself veiled, that is, through appearances, The spiritual sun itself, in the midst of which He is, is the very first appearance of His Divine love and wisdom, but below the sun there are the atmospheres that veil Him. It is similar when He shows Himself as a Person in heaven. Clearly He cannot appear to the angels as He is in Himself, but only as He may present Himself in a form adapted to the receptivity of each angelic society. "So it comes about", we are therefore informed, "that when the Lord shows Himself as present in any society, He appears there in accordance with the quality of good in which the society is, thus not the same in one society as in another" (HH 55). And further instruction is given in HH 121: "When the Lord appears in heaven, which often happens, He does not appear encompassed with a sun, but in Angelic form, yet distinguished from angels by the Divine shining from His face. For He is not there in Person, since the Lord in Person is always encompassed with the sun, but He is present by view (per aspectum)." (See also AC 6849; AR 465).

Obviously any accommodation has to be by means of what is finite. So it is that the finite may serve as an image that portrays the Lord: nay more, as a means through which His Divine may shine forth. We are directly exhorted to make use of our finite concepts, and not to believe that we can have access to the Lord by looking directly to the Infinite. We read: "Take as an example the societies which are in love to God, and believe that if they look to the Infinite, and worship a hidden God, they can be in love to Him; when yet they are not so, unless by some idea they make that Infinite finite, or present the hidden God as visible within themselves by finite intellectual ideas" (AC 407'5:3). Similarly in AC 3938: "Without an idea derived from finite things, and especially an idea from the things of space and time, man can comprehend nothing of Divine things, and still less of the Infinite." All this, however, applies to men on a lower degree of finition than to angels. We read: "The things which are infinite and eternal are presented before the angels in appearances which are finite, but still in such appearances as are very far above the sphere of man's comprehension" (AC 3404:2).

I would also call attention here to the necessity of that particular finite appearance which takes the form of the human shape, when angels and men think of the Lord. "Shape", of course, cannot be predicated of the Infinite itself, though "form" would be an appropriate concept, namely, the form that is infinite wisdom or the Divine Existere. Nor, therefore, do angels turn to the Infinite itself, but only to that Infinite as it is showing itself in the Divine Human. So we read: "The reason why the Divine Human is the all in heaven, is that no one there, not even an angel of the inmost or third heaven, can have any idea about the Divine itself, according to the Lord's words in John.: 'No one hath ever seen God' (1:18): 'Ye have neither heard the voice of the father At any time, nor seen His shape (speciem)' (5:37). For the angels are finite, and what is finite cannot have an idea of the Infinite; and therefore unless in heaven they had in respect to God the idea of a human shape (ideam speciei humanae) they would have no idea, or an unbecoming one." (AC 7211)

As we see there is in this last quotation a direct link between the concept of the Divine Human and the concept of the human shape. The reason for this link is that the human shape is, in the ultimate, the only full correspondent of the human itself, which is love and wisdom. The letter of Divine Revelation too, in all the three forms of the Word, is in the human form; but natural language is the ultimate of spiritual, celestial, and Divine ideas, and that ultimate is less physical than is the ultimate of flesh and bones. Hence it is that unless the concept of love and wisdom falls into the form of the human body, it has no final resting place and has no duration.

The difference between thought concerning God, with this ultimate view of Him or without it, is illustrated in the following passage: "Conjunction with the invisible God is like conjunction of the sight of the eye with the expanse of the universe, of which it sees no end; and also like the sight in the middle of the ocean, which falls into the air and into the sea and perishes.. But conjunction with a visible God is like the sight of a man in the air or on the sea, spreading out his hands and inviting to his arms." (TCR 787) The Apocalypse Explained makes the same emphatic point, though without painting a picture for the reader: "When a man shuns and turns away from evils because they are sins he not only sees from the light of heaven that there is a God and that God is one, but also that God is Man. For he wishes to see his God, and he is incapable of seeing Him otherwise than as a Man." (AE 955:4)

Sophistication might tend to reject this ultimate vision of our God in the human shape. Abstractions would seem more appealing to many. Yet abstractions without a subject have no actual existence. As noted in Divine Love and Wisdom.: "The idea of men in general about love and about wisdom is that they are like something hovering and floating in thin air or ether, or like what exhales from something of this kind. Scarcely any one believes that they are really and actually substance and form. Even those who recognize that they are substance and form still think. of the love and wisdom as outside the subject and as issuing from it ... not knowing that love and wisdom are the subject itself, and that what is perceived outside of it and as hovering and floating is nothing but an appearance of the state of the subject in itself." (DLW 40; emphasis added)

As in His second advent ("When a man shuns and turns away from evils ... he sees that God is Man"), so in His first advent the Lord appeals to the "pure in heart." "Blessed are the pure in heart: for they shall see God" (Matt. 5:8). The "pure in heart" are those with a purified heart, or those who while engaged in the struggle of shunning evil as sin in their external man are gradually receiving from the Lord an internal which He cleanses (see DP 100). These can see.

The Writings make it important that man should envision the Lord in the human shape. Take the following: "Let it be known that all who see God as Man see from the Lord, and all others see Him from self; and those who see from self do not see" (AE 1114e). "From what has been cited it follows that the Word is to be understood also according to the sense of the letter in saying that God has a face, that He has eyes and ears, and that He has hands and feet" (AE 1116e). "God is a complete Man, in face like a man and in body like a man, with no difference in respect to form but only in respect to essence, His Essence being that He is Love itself and Wisdom itself" (AE 1124, emphasis added).

In DLW 18 the same teaching is given, but there with the important point added that all the things pertaining to the Divine Body are in themselves infinite: "That in God there are infinite things, any man may convince himself who believes that God is Man; for being Man, He has a body and everything pertaining to it, that is, a face, a breast, abdomen, loins, and feet, for without these He would not be a Man."

What do all these teachings tell us? In fact, what is the whole burden of the doctrine of the Divine Human in the Writings? I think the burden is that the Infinite Divine, which is the Lord's Soul and Esse, makes itself known to men and angels by means of finite coverings, and that the Divine that shines through these coverings is the Divine Human.

Note well that this, of course, does not make the coverings to be the Divine Human, but that the Divine that shines through them, is.

Before the Incarnation this Divine Human is strictly to be called the Human Divine (see AC 2814 and surrounding numbers). At that time the Lord took on the Human by means of the heavens (meaning essentially the celestial or inmost heaven, for the middle or spiritual heaven was not fully formed until the Incarnation). The Lord, therefore, ruled mankind by means of the celestial heaven. This was a holding action, and was in preparation for His taking the rule into the hands of His Own Divine Human which He assumed in the world. The ancient prophecy spoke of this: "The scepter shall not be removed from Judah, nor a lawgiver from between his feet, even until Shiloh come" (Gen. 49:10); and the Writings explain: "This signifies that sovereignty shall not depart from the celestial kingdom . . . The case is this. Before the coming of the Lord into the world, there was influx of life with men and with spirits from Jehovah or the Lord through the celestial kingdom, that is, through the angels who were in that kingdom, and hence they then had the sovereignty. But when the Lord came into the world, and thereby made the Human in Himself Divine, He put on just that which was with the angels of the celestial kingdom, thus He put on this sovereignty." (AC 6371:2)

The Human which the Lord had before the Incarnation existed from "the transflux through that heaven" from His Divine. The passage just quoted continues: "Previously the Divine transflux through that heaven had been the Human Divine; it was also the Divine Man which was presented to view when Jehovah so appeared. But this Human Divine ceased when the Lord Himself made the Human in Himself Divine." (Ibid)* There was a distinction between the Human before and the Human after the Incarnation, and this both as to form and as to efficacy. The teaching just cited shows the distinction in efficacy; and the distinction as to form, or nature, appears in the following: "Before the coming of the Lord the Divine Human was not so completely one with the Divine Itself which is called the 'Father,' as when the Lord made it in Himself altogether one. Before this they were as it were distinct...(ref. to Gen. 19:24)." (AC 6000:7)

* The translation in the Standard Edition here deviates from the original in that it transposes the words "Human" and "Divine." See the Latin of AC 6371 and 2814.

The reason the Human before the advent "was not so completely one with the Divine Itself," was because the heavens that transmitted-the Divine were not in such absolute correspondence with the Divine Itself as was the Human that the Lord showed forth through His speech and acts while in the world and through His Resurrection Body, afterwards. Correspondence can be more or less complete. In the Lord it became totally complete. For what He set forth in the ultimate, and after His resurrection in the appearance of an ultimate before the spiritual eyes of those who saw Him (see TCR 777), was the presentation in an absolute and perfect form of His own Divine love and wisdom by means of finite forms, that is, by means of Divinely adopted appearances. Through these appearances we see the Lord, for He has made them to portray the Divine by absolute correspondence, and it is His own Divine that shines forth through them.

Remember that the Divine Natural, like the Divine Celestial and the Divine Spiritual, is so named relative to those who receive. And "the glorified Human of the Lord is the Divine Natural" (TCR 109).

I conclude, then, that the Lord's Divine Human is the setting forth, or the shining forth, of the Lord's Divine love and wisdom in power and great glory through the Natural that He assumed in the world and glorified. In other words, the Divine Human is our God visible. Moreover, the Divine Natural - being in itself infinite and uncreate-- was "only an Additamentum" ("only a something that was added") "to His Divine Essence that was from eternity." And it was "added" in the sense that now for the first time the Lord had taken to Himself the means whereby His Divine could shine forth to be seen by men in the world, having their natural minds enlightened from the light of heaven.

Unless the Lord had walked the roads of Palestine in a physical body, and unless He had afterwards shown Himself, recognizable, to some in His Resurrection Body, this could not have been. It was essential that men's minds should witness.

***

== d. "Not only conceived but also born of Jehovah."
These words occur in the following essential teaching, which, if it had not been verbatim given us, we would have had to supply as a conclusion from many other teachings. In Genesis we have: "Abraham called the name of his son that was born unto him;" and the exposition in the Arcana reads in part: "From these few words three arcana shine forth for those who are in the internal sense: - First, that the Lord's Divine Human came forth (exstiterit) from the Divine Itself... Second, that the Lord's Divine Human was not only conceived but also born of Jehovah, and hence the Lord as to His Divine Human is called the 'Son of God' and the 'Only-begotten'... Third, that the Lord's Divine Human is the 'name' of Jehovah, that is, His quality." (AC 2628)

It was during the glorification process that the Lord's Divine Human "came forth from the Divine Itself" and was "born of Jehovah." The maternal human was still there; there were organics in the brain that was born from Mary. But the Divine descended, like the fire on Elijah's sacrifice which consumed "the burnt sacrifice, and the wood, and the stones, and the dust, and licked up the water that was in the trench" (I King 18:38); and as it descended, the maternal human was replaced by the Divine Human. In the end, in the tomb, all that remained from the mother "was dissipated" (Ath. 161, 162). As I understand it, the natural organics - the "finest things of nature"-- that were the basis for the Lord's mind in the world, were gradually conditioned by His Divine as the Lord removed falsities and evils that inhered in His maternal heredity and replaced these with Divine truths and goods in the natural. But after His last temptation, which was that on the cross, and His total and final victory then, the very quality that had impinged on those organics was dispersed; and when the quality of a substance (or subject) is dispersed - in this case all the quality, then there is nothing left of that substance either.

The Arcana sheds light on the question: "From the fact that the presence of the Divine Itself is of such a nature that no angel can endure it unless he is protected by a cloud, which tempers and moderates the rays and heat/from the Lord as a sun/, it is very evident that the Lord's Human is Divine; for unless it were Divine it could never be so united to the Divine Itself which is called the 'Father,' that they may be one... For what so receives the Divine must needs be altogether Divine. What is not Divine would be utterly dissipated by such a union." (AC 6849:5).

So everything whatever from Mary was "utterly dissipated." And the Divine took the place of it. In this process there was no transmutation of material substance from the mother into a Divine substance from the Father, nor was there any commingling of the one with the other. The Writings are explicit on this point, to wit: "The Lord had a Divine Essence and a human nature: the Divine Essence from the Father, and the human nature from the mother; and hence He was equal to the Father as to the Divine, and inferior to the Father as to the human; also that He did not transmute this human nature from the other into the Divine Essence, nor did He commix it therewith." (Lord 35) This is in keeping with the oft repeated teaching that the Lord "put off" all that was from the mother, and "put on" all that was from the Father. In other words, instead of transmutation or commingling there was replacement.

All this has a direct bearing on the question of the Lord's Resurrection Body. If the Divine Human was "born of Jehovah," then clearly it was what was so born that rose from the tomb. Nothing whatever of the material could linger with the Lord. If it did, He would be partly finite. We also have this: "As His body was now no longer material, but Divine-substantial, therefore He came in to the disciples while the doors were shut" (Lord 35:9).

As Bishop Pendleton noted in his address to this Council five years ago, entitled "The Lord's Resurrection Body" (NCL 1975, pp 296-309), there is "the ultimate of life with man" (p. 306). What this was with the Lord he showed by quoting from the Apocalypse Explained: "The Lord glorified His Human even to its ultimate, which is called the natural and sensual" (AE 513:19). Then the Writings, having so spoken, go on to illustrate this point by quoting from the resurrection story in Luke: "Jesus, having appeared to the disciples, said, 'See My hands and My feet, that it is I Myself; feel Me and see; for a spirit hath not flesh and bones, as ye see Me have...'" (Ibid.; Luke 24:39). The Bishop concluded, therefore, that the Body in which the Lord showed Himself to His disciples after His resurrection "was not the material body but that body which was both conceived and born of the Father, that is, the Divine sensual" (p. 306).

The implication of this is that the Divine life descended and penetrated into the very ultimates of the mind the Lord had from the mother, and through those ultimates into the body also; for the sensual is from the soul in the body, and serves as a gateway from the material world to the soul. And can we not see that this is what the Divine life did? It could not stop short on the way. It consumed and replaced, gradually, until all was Divine, and nothing was material. The Lord's glorification did have these two aspects: He put off, and He put on.

How then could the Lord speak of "flesh and bones?" Are not flesh and bones material? Yet if it is seen that the Divine life entered in everywhere where the natural and material from the mother had been, thus descended on every plane where the things from her had been, then does it not follow that the Divine caused itself to be immediately present on the very plane of flesh and bones? Thus that the Lord in very truth took to Himself, not material flesh and bones, but Divine flesh and bones?

When the Lord showed Himself to His disciples after He had risen, He willed that they should think of Him as present with them on the same level of life that He had shared with them through all the three years of His public ministry. They did not know that they saw Him with the eyes of the spirit. Nor was it at all necessary for them at that time that they should know. He said to them, "Have ye here any food?" And when they gave Him fish and honeycomb, and "He did eat before them," they thought that He ate material things. We may now know that the material cannot enter even the spiritual, still less the Divine; but to the disciples it was enough that they should believe that

He was fully present with them, on their plane of existence, as though materially present, and that it was this He meant when He assured them saying: "And lo, I am with you alway, even unto the end of the age" (Matt. 28:20). And, indeed, He was, and is now and for ever, as though materially present.

The emphasis is on immediately so present. For formerly His ultimate presence had been only through representations in the physical world, by means of sacrifices and washings, etc. But now some had seen their God in their day to day life, for they had glimpsed something of His glory. He was where they were, He was the Immanuel-- God-with-us.

In line with the above I conclude that the Lord did not "add" anything whatever from Mary to Himself, or anything whatever from matter. His Additamentum was His reaching forth where He had formerly governed and been seen only representatively, but where now He made Himself visible and known immediately.

It was His Divine love - the infinite love of salvation - that penetrated, reached forth, and became present. Thus His love in His ultimate presence is His Body. "It is evident what is meant by the Lord's 'body,' namely, the Divine love, in like manner as by His 'flesh' (see no. 3813). Moreover, the Lord's very body when glorified, that is, made Divine, is nothing else. What else must we think about the Divine, which is infinite?" (AC 6135:3e)

***

== e. (Note: "e" was included in section "d.")

== f. The Lord's coming into the world involved no change within the Lord Himself, i.e. in the Divine Substance.
A man such as he is in himself, that is, as he is as to his ruling love, does not change, when he turns aside and does this instead of that. Nor does his outlook on life, thus his basic understanding, change. For example, if I teach a first grade class about the Divine Human, and then teach the same subject to a group of high school students, and then to the theological school, then I do not change from one time to the other, nor does my understanding of the doctrine. What is varied is only my mode of presentation, and insofar as what I say is true it is the same truth that is presented each time. The fact that I do not use the name "Divine Human" to the small children, but speak instead of the Lord as Man, makes no difference either to my worship of the Lord or my understanding of Him; nor does the fact that I do not tell the high school students everything I know, as I would try to do it in the theological school.

So the Lord does not change for appearing in different ways to the Most Ancients, the Ancients, the Jews, the first Christians, or the new Christians. What is varied is His way of accommodating Himself in causing Himself to appear, and His way of operating; and accommodation is from love according to wisdom.

There is much teaching in the Writings concerning the unchangeableness of God, and concerning variety and diversity from Him, and we select the following passages.

(From a Memorable Relation). Angels said that the Divine ESSE, which in itself is God, is THE SAME, the same not simple but infinite, that is, the same from eternity to eternity, the same everywhere, and the same with every one and in every one, but that all variety and variability are in the recipient, and arise from the state of the recipient.

But since no one can receive the Lord as He is in Himself, He appears as He is in Himself as a Sun above the angelic heavens, and that which proceeds from it as light is Himself as to wisdom, and that which proceeds as heat is Himself as to love. He Himself is not the Sun; but the Divine Love and Divine Wisdom, in their proximate emanation from Him and around Him, appear as a Sun before the angels. He Himself in the Sun is Man. He is our Lord Jesus Christ both in respect to the all-originating Divine (Divinum a Quo) and in respect to the Divine Human, inasmuch as the Very Self, which is Love Itself and Wisdom Itself, was His Soul from the Father, thus was the Divine Life that is Life in Itself. - AR 961:4, 5

That the form or state receiving induces variations may be evident from the life of infants, of children, of youths, of adults, and of old people. The same life, because the same soul, is in each one from infancy to old age; but as his state is varied according to ages and accommodations, so also life is perceived variously. - TCR 366

When the Lord shows Himself as present in any society (of heaven)...He does not appear the same in one society as in another. This diversity is not in the Lord, but in the angels who behold Him from their own good, thus in accordance with that good. - HH 55

These are the general teachings. In sum: that though the Lord does not change, He appears before finite eyes to change as He accommodates Himself to various states and needs among men and angels.

But even more striking are teachings concerning the Divine Trinity. First we have the following universal principle: "One Divine by itself is not possible, but there must be a trine. This trine is esse, existere, and procedere, for being must necessarily come forth, and when it comes forth it must so go forth as to produce. And this trine is one in essence and one in person, and is God... It may now be asked, What trine did God have before the Lord took on the Human and made it Divine in the world? God was then likewise Man, and had a Divine, a Divine Human, and a Divine going forth, that is, a Divine Esse, a Divine Existere, and a Divine Procedere, for as has been said, God without a trine is not possible. But the Divine Human was not then Divine down to outmosts. Outmosts are meant by 'flesh and bones,' and even these were made Divine by the Lord when He was in the world. This was what was added (hoc accessorium fuit), and this is the Divine Human that God now has. (AE 1111:3, 1112:3; emphasis added)

In light of the above, especially the teaching that before the Incarnation the Divine Human "was not Divine down to outmosts," we can the better understand the oft repeated doctrine that "this Trinity was not before the world was created, but after the world was created when God became incarnate, it was provided and made: and then in the Lord God the Redeemer and Savior, Jesus Christ" (TCR 170; Can. Trinity III, IV).

So far as I can see the meaning can be no other, than that the Divine Human the Lord now has is nothing but an extension of His Divine down to ultimates, so that He may now be immediately present there, and not as before only representatively. Nothing but an extension--"modo additamentum."

This modo (only), however, has no implication whatever of belittling. What is implied, I suggest, cannot be understood except by contrast. It is not only a matter of what did happen, but also of what did not. What did not take place was any addition to the Divine Substance, nor therefore any change in the Lord's Divine; but what did take place was that the Divine in the heavens, that is, the Divine Human (or Human Divine) before the incarnation, in fulness of time "bowed the heavens and came down," as says the Psalmist (Ps. 18:9): brushing aside representations, and replacing those servants of His who had represented Him in governing the Church with His own immediate presence and immediate sovereignty.

This was not a small thing. But it was "only" a change in the Divine presence and operation, not a change in the Divine Substance, nor was there any addition to it.

How else can we understand the following teachings? - "The Divine Human which was born from eternity was also born in time; and what was born in time, when glorified, is the same. Hence it is that the Lord so often said that He was going to the Father who sent Him; that is, that He was returning to the Father." (AC 2803:3) - "When that celestial Church (the Most Ancient) began to fall away, they foresaw that the infinite Coming-forth (Infinitum Existens) could no longer have influx into the minds of men, and that so the human race would perish. Therefore it was revealed to them that One should be born who would make the Human in Himself Divine, and in this way become the same infinite Coming-forth as had been before, and would at last become one with the infinite Esse as also it had been before." (AC 4687:2) - "It was the Divine Human that the Ancient Churches worshipped, and Jehovah also manifested Himself to them in the Divine Human. The Divine Human was the Divine Itself in heaven, for heaven constitutes one man which is called the Grand Man... This Divine in heaven is none other than the Divine Itself, but in heaven it is as a Divine Man. This Man is what the Lord took on, and made Divine in Him, and united it to the Divine Itself as it had been united from eternity... For it was no longer sufficient for the Divine Itself to be able, through heaven and thus through the Divine Human there, to flow into human minds; wherefore the Divine Itself willed to unite the Divine Human to itself actually by the Human taken on in the world. The one and the other is the Lord." (AC 5663:3) - "And now, O Father, glorify Thou Me with Thine Own Self, with the glory which I had with Thee before the world was" (John 17:5; emphasis added throughout).

I think any notion that there was a change in the Divine Substance, or some addition to it, would imply that the Divine is imperfect.

***

== g. The purpose of the Lord's glorification was His conjunction with the human race.
We frequently read that "the Lord came into the world to subjugate the hells and to glorify His Human" (Lord 12 et al.). But why did He do these two things? What was His ultimate purpose? We must not think that the Lord fought and triumphed for His own sake. Infinite love is not such.

But the Arcana tells us of His final purpose: "It is evident that in the union of Himself with the Father the Lord had in view the conjunction of Himself with the human race, and that He had this at heart, because it was His love... This was His end and this His love, which was such that the salvation of the human race, as beheld in the union of Himself with His Father, was to Him the inmost joy." (AC 2034:2, 3) These words occur in explanation of the Lord's words in John: (In part) "I have made known unto them Thy Name, and will make it known, that the love wherewith Thou has loved Me may be in them" (17:26); and also: "In that day ye shall know that I am in the Father, and ye in Me, and I in you" (14:20).

AC 2077 adds emphasis to the above by the words "nothing but:" "In the union of His Human with His Divine He regarded nothing but the conjunction of the Divine with the human race" (See also AC 2102:2, 2112, 2171:2).

It follows from the above, and also from everything in the Gospels that give the doctrine of "I in them, and Thou in Me" (as in John 17:23), that the subjugation of the hells and the glorification of the Human were mediate ends, and that the final end was the salvation of the human race. "This was His end, and this His love."

***

== h. No salvation without seeing God.
It is essential to bear in mind that there is no salvation without freedom. But freedom involves choice, and choice involves sight. As the final vestiges of respect for the Divine Law vanished from the Jewish Church, men lost their spiritual freedom. This was temporary, and the Lord came to restore it; but unless two alternatives are known and understood, there is no freedom. The heavenly alternative had become unknown. "Ye have made the commandment of God of none effect." All that the people knew was the giving of tribute to the temple, going to Jerusalem for the yearly sacrifice, not doing the things on the Sabbath that were forbidden by the Talmud, and giving alms for to be seen by men, and so forth.
"Cleansing the inside of the cup and platter" was unknown to them; charity and faith were unknown. There was therefore no salvation, because no freedom.

In this situation the Lord came, and declared: "Ye shall know the truth, and the truth shall make you free" (John 8:32). And how did He make the truth known? By setting forth His Divine. And what is His Divine? Divine love and wisdom. He showed them His love by His acts of healing, also of forgiveness; and His wisdom by His teachings and by His way of refuting the ensnaring questions of His enemies. "Many believed in His name, when they saw the miracles which He did" (John 2:23). "And it came to pass, when Jesus had ended these sayings, the people were astonished at His doctrine: for He taught them as One having authority, and not as the scribes" (Matt. 7:28, 29).

So it was that the Lord manifested forth His authority, so that the people began to see the alternative of living according to His doctrine. In this was their freedom.

It is important to realize that the people witnessed both the subjugation of the hells and the Lord's glorification of His Human:
remotely, of course, but enough for their salvation to be involved. Hell had its spokesmen. What did the people see, when the chief priests and the scribes sent forth spies, who with devilish subtlety asked Him: "Is it lawful for us to give tribute unto Caesar, or no?" (Luke 20:19-22) They saw hell; they glimpsed the temptations that hell launched at Him. And what did they see when the Lord said, "Show Me a penny. Whose image and superscription hath it?... Render therefore unto Caesar the things which be Caesar's, and unto God the things which be God's?" (vv. 24, 25) They saw something of His victory over hell, and His triumph; they saw, or witnessed, how the Divine spoke through the Human; the Lord's glorification was remotely visible to them.

This is what made them free, and this what made His conjunction with the human race possible, thus what made salvation possible. His very end in coming was being slowly fulfilled.

When we say that God is visible, we should think that the Lord's combats with the hells, His triumph over them, and thus the setting forth of His glory in the Human, were visible to those He came to save - but dimly visible, it is true, yet so that the marvellous things that took place were not totally hidden from their view. Unless they, and we, can see something of these things, there is no basis for faith in Him. Hence the teaching: "By His having at the same time glorified His Human, He keeps the hells subdued and subjugated to eternity" (Lord 33:2, DLW 221).

There is more to the doctrine concerning the Visible God than first meets the eye.

***

== i. Divine accommodation from love by means of wisdom.
Foresight and predetermination are different things. All things are foreseen in the Divine wisdom to eternity, but to predetermine is to void human freedom, which is to the Lord as the apple of his eye.

He, therefore, does not arbitrarily manipulate human events according to any fixed Divine timetable. In a way, it is man who sets the timing for Divine acts. For example, "had the Most Ancient Church remained in its integrity, the Lord would have had no need to be born a man" (AC 2661:2). Moreover, "as soon as this Church began to decline, the Lord foresaw that the celestial Church would wholly perish from the world; and on that account the prediction was then made concerning the Lord's coming into the world (Gen. 3:15)" (Ibid.). We note: Because of the decline, prediction was made; and had there been no decline, no prediction would have been made.

Love desires conjunction at all times. In fact, we are told that the Divine love, if it were by itself, would draw all to itself in heaven. But true love, least of all the Divine love, is never "by itself." It cannot but act according to wisdom. Hence the bending and accommodation of the Divine love in order to turn to the best whatever man in freedom - or folly - initiates.

It is thus that we may see that the Lord's coming into the world as the Word made Flesh, was precisely ordered and precisely timed according to the state and need of both men and angels. Men had had precept. It was parable that was now paramount, for by parable the understanding - a beginning understanding - is addressed. This beginning of an appeal to the understanding was the immediate next step in the Divine accommodation (after the Old Testament). He said, "Have ye understood all these things?" - "I have called you friends."

This was the first advent. Now, in His second advent He must rule by "the rod of iron, that is to say, "by truths from the literal sense of the Word, and at the same time by rational things from natural light" (AR 148). Why so? Because in our day there is nothing left with man but the rational to which to appeal. "Truths from the literal sense" are spiritual truths, based on the literal sense, and "rational things from natural light" are what might be called, in sum, the arcana of nature. We bear in mind, of course, that the rational belongs to the natural mind, but it is the highest there. So the "rod of iron" consists of arcana of two kinds, opened up and presented to the rational, so that the Lord - man being willing - may rule him in his freedom. In this way the Lord's coming as the Word in Spirit was precisely ordered and timed too.

We are speaking of the Divine operation at the first advent and at the second. Now the Divine operation is what is called "The Holy Spirit."
And since the Lord "operates of Himself from the Father" (TCR 153) it is clear that the Holy Spirit could not go forth except from the glorified Human. This, however, should be understood, and not only seen to be the doctrine. We must not lose sight of the fact that the Lord in all matters relating to man's salvation never operates except together with him. TCR 371 explains that, and so does TCR 154. So it is that the source of the Divine works with man must be seen, understood, and acknowledged by man - else the Lord cannot work salvation with him.

This is why we read that "the Holy Spirit was not yet, because that Jesus was not yet glorified" (John 7:39). Of course, the Lord's combats and victories within Himself preceded the revelation of His glory. Yet the revelation of it, and salvation following, were the purpose of His glorification. It follows that "not yet glorified" has reference both to the glorification process itself with the Lord, and to the response to it on the part of man. When the Lord said to Mary outside the sepulchre, "Touch Me not, for I am not yet ascended to My Father" (John 20:17), His glorification was complete, for He had endured His last temptation and had conquered all the hells; thus His Human had ascended into full union with His Divine. But the Church, as represented by Mary of Magdala, had not yet perceived the wonder that had taken place. To that Church He was "not yet ascended." And so with regard to the Holy Spirit: It could not operate until men saw the Lord's glory. John said,
"And we beheld His glory;" and in Matthew the prophecy reads: "And they shall see the Son of Man coming in the clouds of heaven with power and great glory."

The Holy Spirit, therefore, proceeds from the Divine Natural which the Lord put on in actuality by coming into the world; it proceeds from the Lord's Additamentum. And it operates for salvation when man sees and cooperates.

***

== j. What applies to the Lord, applies to the Word.
This is because the Lord is the Spirit and Life of the Word, that is, He is the Truth and the Good of it. Everything that is said in all the three forms of the Word is in ultimate language what the Divine Good and Truth hold in store.

This subject is not a small one: At this time, however, we will confine our consideration to the fact that each of the three presentations of the Divine Law has been given in accommodation to prevailing needs at the time they were given, and to needs following. But there is something implicit in this fact. For all the three Divine presentations have stemmed from the same Divine love and the same Divine Wisdom. It follows that interiorly, in their essence, they are the same, though in their form of accommodation they are vastly different.

What I want to suggest is that the New Testament was an "Additamentum" to the Old in a precisely similar way as the actual assumption of the Divine Natural was to the Divine Celestial and the Divine Spiritual. The Lord said that He had not come "to destroy the Law or the Prophets, but to fulfill." And to fulfill is to open up, or to reveal. That is why it is said that the things that happened to the Lord's Natural were done "in order that the Scriptures might be fulfilled." There is as it were an evolution of the Word - a two-step unfolding of the oldest form of the Word that we have. But when the Writings, the Crown of Revelations, were given, there was overturning of the law enunciated at the end of the New Testament: "If any man shall add to these things, God shall add unto him the plagues that are written in this Book" (Rev. 22:18). The Writings did not add one single truth to what was already in the New Testament. The Lord had already glorified His Human. All that the Writings did was to reveal the glory, setting it forth in heavenly light to the rational mind, so that the whole natural man, the whole man, might come to the worship of the Lord God Jesus Christ in faith and life. That was all. In a sense, the Writings are "only an Additamentum" to the former Scriptures, namely in a sense analogous to the case of the Lord's Natural being an Additamentum in Him. In neither case was there any added substance, but only an added, or new, way of presenting it to view.

If we look at the Old Testament as a whole, we see it as a Prophecy of the advent. Then the New Testament is seen as the fulfilment of that Prophecy. And finally the Writings show themselves to be an explanation of all the wondrous things that were fulfilled. Prophecy - Fulfilment -
Explanation: one Word, of one Substance, but each of the two later forms setting forth the power, shedding glory, upon what went before. Does not each form of the Word reach forth to speak to one particular degree of the natural mind? And to the sensual, the moral, and the rational, in that order?

So also the Additamentum that the Lord took to Himself by coming in the Flesh was a reaching forth to the children of men. "His arm brought salvation unto Him" (Is.59:16)-- and so did the New Testament, the Chronicle of His work; and so did the Writings, which say: "Enter with the understanding into the arcana of faith."

***

== k. The whole Trinity, which is in the Lord, is now visible.
The Lord taught that. He said: "He that hath seen Me hath seen the Father" (John 14:10); and also: "The world cannot receive the Spirit of Truth, because it seeth Him not, neither knoweth Him: but ye know Him: for He dwelleth with you, and shall be in you" (John 14:17).

The Father is visible, in that we may, from a "pure heart," perceive the Lord's love, or perceive the good that is in the truth. And the Holy Spirit is visible, in the sense that we may know the laws by which the Lord operates. I would call attention to the fact that none of the Divine operations which are enumerated in the chapter on the Holy Spirit in the True Christian Religion, can take place without man's cooperation. These Divine operations, we read, "consist in general, in reformation and regeneration; and according to these, renovation, vivification, sanctification, and justification; and according to these, purification from evils and remission of sins, and at length salvation" (TCR 142).

All these operations are especially known through the Writings. Yet they cannot be known simply by memorizing, but only if "the Spirit of Truth dwelleth in you, and is in you." The reason is that "Jesus has been glorified," and it is from Him the Holy Spirit proceeds.

The question is only if the glory of the Lord's Divine Natural, or of the Lord's Additamentum, is seen and acknowledged. If not, then with such a man "the Holy Spirit is not yet."

The above, however, is not to say that man or angel can see all of the Divine glory, or understand all of the Divine operation. What the human mind can fathom is in fact very, very little; and most of what the Lord does is for us secret. But this does not take away, but only enhances the meaning of the promise: "And they shall see His face; and His name shall be in their foreheads" (Rev. 22:4).

1. The trilogy of Glorification - Revelation - Salvation. The one follows from the other. For the Lord glorified His Divine Natural in order that He might reveal it, or make it visible; and He made it visible in order that freedom should be restored, and salvation thereby be made possible.

So the Lord changed nothing within Himself by coming into the world. But He changed His whole approach to men and angels. "The Human Essence was only an additamentum to His Divine Essence that was from eternity" (AC 1461e)--only that; yet without it no salvation, nor the survival of the human race.
