= Old Testament Introductions

All content herein was sourced from the Summaries provided for each Book, provided by the New Christian Bible Study (NCBS) project website.

== Brief Intros

=== Genesis
Genesis is the first book of the Bible. The word "genesis" means origin, birth, or beginning. It's related to the words “generate” (to cause to happen) and “genus” (family). This is appropriate; the two main themes of the book are God's creation of the world, and then, almost right away, the stories of families - Adam and Eve and their descendants, and then, after ten generations, Noah and his family, and after another ten generations, Abraham and his family.

=== Exodus
Have you ever felt oppressed? Stuck? Captive to doubts or fears? If so, it would be really surprising if the book of Exodus failed to resonate with you. It is a story of oppression followed by liberation. It's an interesting, pivotal history, and it carries a reassuring message. And, on a spiritual level, it is timeless. Like the Children of Israel, we eventually have to leave our "spiritual Egypt", and head for our "spiritual Canaan", journeying through the wilderness on the way.

=== Leviticus
The Book of Leviticus is the third book of the Old Testament. It deals with the laws that govern the offering of sacrifices, the fulfilling of priestly (Levites) functions, and the lives of ordinary people. The Hebrew title for this book translates to “And He Called”, suggesting that this book deals with the Lord's call for us to enter His kingdom.

====
_All these laws regarding external conduct and worship were to be carried out according to the letter of the law. They also represented spiritual realities and constituted the means by which knowledge of the Lord was preserved. It is this understanding that transforms the text into something eternally relevant that can be used to support the spiritual development of the human mind._
====

=== Numbers
The book of Numbers is the fourth book of the Bible. It gets its name from the two censuses of the Children of Israel mentioned in chapters 1 and 26. The original Hebrew name of the book is different; it can be translated as "In the Wilderness", and indeed the story is set in the wilderness after the Children of Israel flee Egypt, and before they arrive in Canaan.

====
_The internal meaning of the Book of Numbers concerns spiritual development: our gradual change from selfishness to love and obedience to God. The events in the book reflect the personal work we must do to improve our spiritual lives._
====

=== Deuteronomy
Deuteronomy is the fifth book of the Bible, and the last of the "five books of Moses". The events in Deuteronomy take place over roughly a two-month time span; just before the children of Israel cross over the River Jordan to enter the land of Canaan. Moses has been told by Jehovah that he will not be permitted to enter the land of Canaan himself, and - now 120 years old - he seeks to prepare his people for what lies ahead. In several speeches, he reminds the people of their past, forecasts their future, and restates the laws that they should follow, and - above all - exhorts them to follow Jehovah, and to worship no other gods.

There's tremendous depth in the whole Word - and Deuteronomy is no exception. The literal sense is powerful, sometimes clear and inspiring, and sometimes obscure or troubling. There are certainly harsh passages in Deuteronomy, and yet, it's striking, too, that there's also a sense that we should always be seeking to be led by the Lord. When the Children of Israel trust in the Lord, there is much good to be found in life. When they do whatever they want, or are led astray into worshipping other gods, hell breaks loose.


It's interesting, too, that the Israelites are commanded to fight some of the neighboring peoples, but to live peaceably with others -- the descendants of Esau and Lot. 

====
_At a deeper level, this means that there are various external forms of good and truth which can be comfortable neighbors. They're not as pure or strong as goods and truths that have become internalized, and are at the heart of our lives, but they're still in natural good. And, then, there are the people of Ammon and Bashan, who represent outright evils and falsities that we have to root out of our lives, or they will corrupt and destroy us._
====

=== Joshua
The Book of Joshua marks the beginning of a new era for the Children of Israel. Moses, who led them out of bondage Egypt, and then for 40 years in the Wilderness, has died, looking out over the promised land of Canaan from Mount Nebo. He's been buried, and duly mourned.

====
_The deeper meaning of this book is about how we need to use the Lord's Word to fight against vices within us that prevent us from living a heavenly life. Every battle that the sons of Israel fought represents various battles that we have to face in ourselves -- battles against false beliefs and selfish motivations._
====

=== Judges
The book of Judges is the seventh book of the Bible. It's set in the time between Joshua's death, after the initial conquest of the land of Canaan, and the eventual establishment of kings in Israel many years later. During this time, the tribes of Israel formed a loose, decentralized alliance, and they looked to local or regional leaders to act as judges, and often as military leaders, too. The notable stories about these leaders form the basis of this book - hence the name, "Judges".

====
_The book of Judges calls us to decide for ourselves how we are going to live. Will we bring the truth we know from the Lord down into our own lives? Or forget the Lord, and go our own way? The unconquered tribes are still out there, waiting. Confronting these requires great determination and courage._
====

=== 1 Samuel
The first book of Samuel holds some of the Old Testament's most dramatic and memorable stories. God calls Samuel, when he's still a boy, to be the next prophet in Israel. Saul is anointed the first king of Israel. He starts well, but twists into evil. David - a teen-age shepherd - arrives in Saul's war camp at a critical moment, and volunteers to do battle with Goliath, the fearsome Philistine giant. David and Jonathan, Saul's son, become fast friends.

====
_These stories aren't merely dramatic; it's possible for the careful reader to see the journey of life illustrated here. Our lives are marked by a series of turning points. Some of these are subtle, and some are more abrupt. The first book of Samuel shows us both._
====

=== 2 Samuel
The Second Book of Samuel deals with the establishment of David as the king of Israel, and his reign. The first part of the book (2 Samuel 1-5) provides an account of David's progress toward consolidating power after the death of King Saul. Having established himself, as related in the stories in 2 Samuel 6-9, he is a king in the fullness of his powers and the glory of his kingdom.

====
_The deeper, spiritual meaning of the events in 2 Samuel deal with how, when we acknowledge the authority of Divine Truth in our life, we need to bring all things that stand opposed to it under its rule. If we have evil loves and false ideas that we are not willing to deal with, they can wreak havoc and destroy the Lord's peace for us._
====

=== 1 Kings
The First Book of Kings begins with the waning days of King David's reign. There's a struggle for succession, but David chooses Solomon to be heir to the throne.

====
_The literal accounts of the lives of the kings and those around them are used to teach us one simple but hard-to-do lesson: When we do what God wants us to do, it will produce blessings. Ignoring Him leads to bad outcomes. "All" we have to do is to ask the Lord, over and over again, to help us fight our evil tendencies, to try to be good, and to accept his leadership in building a good ruling love in the core of our being._
====

=== 2 Kings
The literal accounts of the lives of the kings and those around them are used to teach how observance of God's law produces blessings while ignoring Him provokes punishment.

====
_Apart from the obvious teaching of these two books, the spiritual message demonstrates the benefits of allowing the Lord to develop a positive “Ruling Love” that serves as a moral compass within one's own journey._
====

=== Psalms
Someone once said to me that the Psalms are simply poetry with God in them but they don't tell us much! It can seem that way at first glance, but I don't agree.

====
_Teachings from the works of Emanuel Swedenborg provide insights into the Psalms. Swedenborg cites various Psalms throughout his writing, and his work The Inner Meaning of the Prophets and Psalms contains a breakdown of the spiritual meaning behind each individual psalm._
====

=== Isaiah
Isaiah's Ministry was centered in Judah and spanned from 740-680 BC. It begins near the reign of Uzziah and continues through the kingships of Jotham, Ahaz and Hezekiah. The different qualities and influences of these kings both for good and evil, have a major influence on the fortunes of Israel.

====
_In the spiritual sense, we see Jesus Himself and the battles He faced and we face as individuals on our spiritual journey. Simply put, we can see the first 39 chapters as reflecting the acts of repentance and reformation and the last 27 of our spiritual rebirth._
====

=== Jeremiah
Jeremiah was relentless in his duty as a prophet, which in turn makes his writing heavy. But the read is worth the effort. Let yourself be attracted to Jeremiah for his strong commitment to his work, for his courage, and for his great love of Judah for whom he “yearned to sound the alarm, and save them from the impending fall.”

====
_Sometimes we have to go through dark and captive states to come to understand and value the Lord's will as opposed to our own. We have to be brought down. And yet it is from that experience that a new start can - and will - be made._
====

As you think about Jeremiah, let yourself also think of the Lord; of His great love for the human race; of all the efforts He has made, “to sound the alarm, and save (His people) from the impending fall”. Think, too, of the thanklessness Jesus met while on earth, the plots to kill Him, and the way scribes and Pharisees moved so sinisterly against him. 

====
_While we are reading the Bible we think we are reading about the man Jeremiah, “but in the internal sense the Lord is meant.” (Arcana Coelestia 2838)._
====

=== Lamentations
The book of Lamentations is attributed to Jeremiah and it is the outpouring of the prophet's grief and regret that something his people had once enjoyed was now lost and devastated.

====
_Let's look at this in our lives. There are occasions when high ideals, principles, and moral values we hold are invaded and brought down by hostile forces. Examples of this include irritable displays of judgement, bouts of anger, or lustful thoughts._
====

=== Ezekiel
Ezekiel is a strange book of visions in the Bible. It begins with an amazing image of wheels within wheels and it ends with a powerful vision of the Temple of God. In between there are other visions, parables, judgments, predictions, and symbolic actions - all of which give the whole book an eerie feel to it. Yet, amid all this strangeness there is a single straightforward message from Ezekiel: the people should return to the Lord and to be faithful to their God.

====
_The best way to approach Ezekiel is to meditate on its imagery and hear the tender appeal of a loving Lord._
====

=== Daniel
The book divides neatly into two halves. Daniel 1-6 relates some of Daniel's adventures, and Daniel 7-12 his dreams and visions.

The first half recounts Daniel's exile in Babylon. Some of its more well-known stories include:

Nebuchadnezzar's dreams +
The fiery furnace +
The writing on the wall +
Daniel in the lion's den

The second half overlaps chronologically with the first half:

Daniel 7 and 8 both occur some time during the reign of Belshazzar (between Daniel 4 and 5) +
Daniel 9 and 11 during the reign of Darius (around the time as Daniel 6) +
Daniel 10 (after Daniel 6), during the reign of Cyrus

Daniel 7-12 is referenced throughout the New Testament.

* For example, the vision of four beasts and the Ancient of Days (Daniel 7) parallels John's vision of the throne room in (Revelation 4)
* and the beast from the sea in (Revelation 13).
* (Daniel 7:13) refers to the Lord: “_And behold, One like the Son of Man, Coming with the clouds of heaven!_” This is quoted directly in (Matthew 24:30) and (Revelation 14:14),
* and Jesus also refers to himself as the “Son of Man” throughout the gospels.
* Daniel 10 also contains a vision of the Lord with many parallels to John's visions in Revelation 1 and 19 - the glorious man having the likeness of the sons of men.

====
_You can see that the second half of the book of Daniel is heavily connected to subsequent parts of the Bible. That makes it worth reading, and it's certainly not something we should just ignore because it's confusing at first glance._
====

=== Hosea
Hosea lived at a time of widespread unfaithfulness among the Israelites. In order to understand the wicked behavior of his peers, Hosea was told to, “_Go, take yourself a wife of harlotry and children of harlotry, for the land has committed great harlotry by departing from the Lord._” (Hosea 1:2).

====
_It is central to the Lord's reaching out to us that here in the prophecy of Hosea, as in other parts of the Word as well, God describes His relationship with us as that of a husband and wife. The Lord reaches out to us seeking a lovely response and commitment. The relationship is emphatically reciprocal and monogamous. We receive life from the Lord and give it flesh and body. The promptings of love come to us from Him. As this marriage of love and truth takes place in our lives, the relationship grows deeper and stronger._
====

=== Joel
This little book contains a myriad of themes from the Old Testament. Additionally, key concepts from New Christian thought including repentance, reformation, and regeneration appear throughout. It will take about 20 minutes to read Joel, but make sure you allocate your time and effort in a prayerful way. You will be surprised at how helpful and fulfilling this book can be.

=== Amos
Amos lived and worked around the period of 790-750 BC. He was called by the Lord to go to the Northern Kingdom of Israel although he lived in the southern kingdom at Tekoa. He had no formal education - only a burning desire to serve the Lord. Coming from a different part of the country, he was able to look at the problems he witnessed more objectively.

=== Obadiah
Obadiah is one of the twelve “minor prophets”. In each of these twelve little books a common evil among the Israelites is pointed out. And, in us, those same evils are something we need to deal with before the Lord can become a part of our lives.

====
_The truth is there is an “Edom” in each of us, a strong inclination to contempt and superiority over others which seeks to come out — especially when others are weakened or brought low for one reason or another._
====

=== Jonah
Let's recount the story of Jonah briefly. He is commissioned to travel to Nineveh to spread the message of the Lord. Instead, Jonah runs the other way and buys a ticket to sail to Tarshish. A storm besieges his ship, and Jonah is blamed for the poor conditions and the others throw him into the sea. A fish swallows up and rescues Jonah, and when Jonah returns to dry land he finally obeys the Lord. He preached about the coming destruction of Nineveh, but Jonah becomes angry when this doesn't end up happening.

====
_The Lord's response to Jonah's anger is interesting. He prepares a gourd that springs up “overnight” (Jonah 4:10) to provide Jonah with shade from the heat of the sun. The gourd soon dies, leaving Jonah once again without shade. This, it seems, was worse than not having had any shade in the first place. The Lord makes His point one more time: the prophecy uttered through Jonah was not intended to reveal the great glory or power of God, but to secure the repentance and salvation of His lost children._
====

=== Micah
We see how people are led away from God in Micah 1-3. In Micah 4, we see a complete contrast where it talks about the mountain of the Lord's house being established. 

====
_This image represents the love and truth God places in our mind._
====

Micah 6 talks about the covenant being breached by the people of Israel. In response to this, the Lord shows them how to renew the covenant in Micah 6:8: “_what does the Lord require of you but to do justly, love mercy and walk humbly with your God_”. 

====
_All of this conveys a wonderful picture of God never leaving us. The last three verses of the book bring us back to the love and compassion of God. In many ways, this book shows us how God is always there to bring us back and lead us forward._
====

=== Nahum

====
_We can never really understand the Bible unless we recognize that its contents reflect what we experience internally. Beneath the surface, the books of the Bible are focused on the spiritual struggles we deal with as we go about our lives._
====

Most people readily accept this when it comes to the story of Moses leading the ancient people of Israel out from slavery.

====
_The progress and setbacks the Israelites face mirror our own internal battles. It is not people the Lord pits Himself against, but those very things which have the potential to devastate us spiritually._
====

=== Habakkuk

=== Zephaniah

====
_Zephaniah speaks of the destruction of the earth and land. It suggests that the subject of the book hits on the far-reaching consequences of spiritual degradation - that we see the destruction of all security, comfort and hope as we recede from the love and worship of the Lord. In spite of this, the Lord Himself protects what is valuable to Him and ultimately restores it when we ourselves see the depravity we have sunk to and rise out of it._
====

=== Haggai

Haggai is all about hope and encouragement. It's one of the shortest books in the Bible, yet relevant and full of easy-to-see teaching. It's about a time when people had lost their connection with God and were struggling to rediscover it. Haggai (whose name means “festive”) tells them to hang in there.

=== Zechariah

=== Malachi

It is thought that Malachi was the last book written in the Old Testament. It is set in the time after the end of the Babylonian captivity when the people of Israel had returned to their land with hopes of reestablishing their nation with its government and religious institutions, but they were never able to reclaim the glory of former days.

== Full Introductions

=== Introduction to Genesis
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Genesis is the first book of the Bible. The word "genesis" means origin, birth, or beginning. It's related to the words “generate” (to cause to happen) and “genus” (family). This is appropriate; the two main themes of the book are God's creation of the world, and then, almost right away, the stories of families - Adam and Eve and their descendants, and then, after ten generations, Noah and his family, and after another ten generations, Abraham and his family.

The first 3 chapters of Genesis recount the 7 days of creation, the creation of man and woman, and the fall of mankind into sin. These are fascinating stories in and of themselves, but we can look deeper, into the internal spiritual sense of these chapters, and see much more. For example, the 7 days represent the 7-stage process by which God can work within us, transforming us from having very little spiritual life to to a state of deep, useful, happy spiritual life. When Eve is tempted by the serpent to eat the forbidden fruit, it's a sad reminder of how we distort the Lord's gifts for our own selfish ends.

The next chapters of Genesis contain many familiar stories: the Garden of Eden, Noah's Ark, and the Tower of Babel. These are not accounts of actual history, but they are very ancient stories, true myths, whose literal sense contains deep inner descriptions of the spiritual development of humankind.

From Genesis 12 onward, the text contains a narrative of actual history. Abraham, a Mesopotamian shepherd who lived sometime around 2000 BC, is called to leave his home country and move westwards to the land of Canaan, in what we now call Israel. As Abraham establishes himself in his new home, we learn not only of God's provision and guidance but also of His preparation for the needs of mankind. The world at that time was sinking into spiritual darkness and ignorance, and God's plan for Abraham and his descendants was to have them preserve the Word - divine truth - through a new religion.

Abraham had two sons, Isaac and Ishmael. Ishmael's descendants became the Arab people. Isaac's descendants became the Jewish people. Isaac had twin sons, Jacob and Esau, and Jacob later had twelve sons who became the fathers of the 12 tribes of Israel. Genesis traces this story, focusing on Abraham, then Isaac, then Jacob, and then Joseph. On the surface, it's an ancient, well-preserved story of a dynastic family of wealthy herdsmen. It is full of struggles, journeys, marriages, promises and betrayals. Again, though, the literal sense contains several layers of deeper symbolic meanings, and its this depth that makes these stories important and sacred.

Towards the end of the book, the Lord changes Jacob's name to Israel, meaning "he that striveth with God". His son Joseph is sold by his brothers into slavery, but he eventually becomes the second most powerful man in Egypt. All of Jacob's extended family, fleeing famine, end up in Egypt, helped by Joseph. They settle there, in the land of Goshen, which ends up setting the stage for the next book of the Bible -- Exodus.

There's a kind of telescoping of human spiritual history in Genesis. Three “churches” are formed in this first book of the Word. Adam, whose name means “man”, represents the earliest spiritual state of human beings. Ten generations later - which could translate into many thousands of years - people have become so corrupt that they are swept away by a flood of evil. One good man, Noah, and his family, are preserved. Noah symbolizes the start of a second “church” - not a building or even necessarily an organization - but more a state of being and understanding. Swedenborg calls it the “Ancient Church”. The people of this church preserved the concept of one divine God, and knew that that the earth, and its people, plants, and animals, were part of creation. They were formed by God, driven by his love, and capable of using his wisdom. Natural things co-respond to spiritual things, and the most ancient people knew this pretty directly, or implicitly. In the Ancient Church, the knowledge was less direct, and maybe less intuitive, but it was still known. In a way, the increasing distinction between human will and human understanding protected and promoted the Lord's wish for us - that we would exercise our freedom and rationality to learn truth and to choose to love good, not evil.

For ten more generations - again, representing thousands of years - the Ancient Church, in various forms, provided a spiritual hub for the spiritual life of humankind. Gradually, though, it too became corrupt. The story of the Tower of Babel, in Genesis 11:1-9, gives evidence of this. In their pride, the people in the story believed they could build a tower to heaven, and make a name for themselves. It didn't end well; the people were scattered and confused.

From the wreckage of the Ancient Church, the Lord salvages a new church, represented by Abraham. His genealogy starts right after the Tower of Babel story, and… as the genealogy is traced out, we move from pre-history/sacred myth with traces of history, to actual historical people, starting with Eber.

This Abrahamic church that is formed doesn't have a lot of internal purity, but it does preserve external forms of religion and worship that can contain good internals. There's a monotheism that - despite recurring tendencies towards idolatry - is a essential link between the human spiritual past and its future. Jehovah is the one God. This new church also preserves the Word. The first 11 chapters of Genesis are remnants of the more Ancient Word that was given to the people of the church represented by Noah.

According to “Arcana Coelestia” (Swedenborg's commentary on Genesis and Exodus), the story of Abraham and his descendants also gives us an understanding of the way God developed and prepared Jesus Christ and His life on earth.

There are many layers of meaning in the Bible. Here, in Genesis, we have:
- the historical development of the Jewish nation,
- the development and preparation of the Jewish religion covered in the next four books after Genesis,
- the salvation of mankind through the Lord's advent, and His life on earth, foreshadowed in the inner meaning of these stories.
- The Lord's life as a model or guide for our own salvation.

All these levels in the latter half of Genesis are explored by Swedenborg in his great Latin exegesis, "Arcana Coelestia", which can be translated as "Secrets of Heaven". Using it as a study guide, we can see how this ancient story of the earliest dawn of human spirituality is still completely useful and applicable to our lives, today.

(By Rev. Martin Pennington, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Exodus
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Have you ever felt oppressed? Stuck? Captive to doubts or fears? If so, it would be really surprising if the book of Exodus failed to resonate with you. It is a story of oppression followed by liberation. It's an interesting, pivotal history, and it carries a reassuring message. And, on a spiritual level, it is timeless. Like the Children of Israel, we eventually have to leave our "spiritual Egypt", and head for our "spiritual Canaan", journeying through the wilderness on the way.

For context, here's a quick look back at the closing chapters of Genesis. Joseph, second only to Pharaoh in leading Egypt, had brought his old father Jacob (now named Israel), and his brothers, to live in Egypt. They had prospered, and for a time lived well there. But some generations had passed, and now, in the beginning of the book of Exodus, it says that “there arose a new king (Pharaoh) over Egypt who did not know Joseph” (Exodus 1:8). This new king sought to enslave the descendants of Joseph and his brothers, because they were getting to be too numerous.

Brutally, Pharaoh ordered that all male infant Hebrews (descendants of Jacob) should be killed at birth. You will perhaps know the famous story of baby Moses, in an ark made of bulrushes, rescued by Pharaoh's daughter. He was born to Hebrew parents, but brought up in the royal household. As a young man, Moses was exiled from Egypt for killing an Egyptian who was beating one of the Hebrew slaves. After a long time in the wilderness, he was (in another famous story) called by God -- from the midst of a burning bush -- to go back to Egypt, and lead his people out of bondage.

The Book of Exodus then relates the tremendous struggle between Moses and Pharaoh - who was unconvinced by the early miracles God performed. Following the death of all firstborns in Egypt, however, Pharaoh changed his mind. Moses and his people were at first allowed to leave, but then they were pursued. They crossed the Red Sea with the help of another miracle. This is "The Exodus", when the Children of Israel exit the land of Egypt, bound for the land of Canaan.

Then, though, there were highs and lows, as they journeyed through the wilderness. Moses received the Ten Commandments on Mount Sinai. The Children of Israel constructed the Tabernacle and the Ark of the Covenant. They were led by a pillar of cloud by day, and fire by night. But they strayed -- they made an idol of a golden calf, and they complained about their hardships.

It is interesting that the kind of spiritual oppression we experience from time to time is what good people endured before the birth of Jesus Christ. This is summed up in the Arcana Coelestia 7932:
“The children of Israel represented those belonging to the spiritual Church who lived in the world before the Lord's Coming, but could not be saved except by the Lord, on account of which they were preserved and held back on the lower earth, where they were in the meantime molested by the hells which were round about them. When therefore the Lord came into the world and made the human within Him Divine, He then - when He rose again - delivered those who had been preserved and held back there. And after they had undergone temptations He raised them to heaven. These matters are what the internal sense of the second book of Moses or Exodus contains.”
This passage highlights how good people are provoked and blocked by influences from hell, sending them into exasperation and despair; these curb and smother the Lord's goodness and truth in our lives.

(By Rev. Ian Arnold, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Leviticus
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The Book of Leviticus is the third book of the Old Testament. It deals with the laws that govern the offering of sacrifices, the fulfilling of priestly (Levites) functions, and the lives of ordinary people. The Hebrew title for this book translates to “And He Called”, suggesting that this book deals with the Lord's call for us to enter His kingdom.

The chapters can be broken down into the following sections:
    • Chapters 1-7 deal with laws regarding sacrifices, offerings, and the use of the altar.
    • Chapters 8-10 deal with the laws governing the functions of the Levitical Priesthood and the consecration of the head priest Aaron.
    • Chapters 11-15 deal with laws regarding how to deal with things unclean so as to avoid disease and illness. Included in this category are foods, various animals, insects, as well as procedures related to cleansing after a birth.
    • Chapter 16 covers instructions regarding ceremonies on the Day of Atonement.
    • Chapters 17-27 deal with general laws pertaining to living a holy life and cover a range of areas such as sexual conduct, idolatry, religious festivals, celebrations, the Sabbath year and the year of Jubilee.

All these laws regarding external conduct and worship were to be carried out according to the letter of the law. They also represented spiritual realities and constituted the means by which knowledge of the Lord was preserved. It is this understanding that transforms the text into something eternally relevant that can be used to support the spiritual development of the human mind.

Here's a description of how this representation works, from "Arcana Coelestia", paragraph 9990:
"To know what each kind of burnt offering or sacrifice represented one must first know that in a human being there is the external and the internal, and that in each there is that which belongs to truth and that which belongs to good. Therefore when a person is to be regenerated he must be regenerated as to the external and as to the internal, and in each as to truth and as to good. But before a person can be regenerated he must be purified from evils and from falsities, for these stand in the way. Purifications of the external man were represented by burnt offerings and sacrifices of oxen, young bulls, and he-goats, but purifications of the internal man by burnt offerings and sacrifices of rams, kids, and she-goats, and purification of the internal itself, or that which is inmost, by those of lambs. Consequently from the actual animals offered in sacrifice one may see what kind of purification or expiation was being represented."
The burnt offerings and sacrifices did not purify or expiate a person, but they served to represent purification or expiation. The "representative" nature of the Israelitish church was external, and in a way, it acted as a placeholder church until the time of the Lord's advent on the earth. The external rituals, because they contained these internal meanings, linked people to heaven, and through heaven to the Lord. (See Arcana Coelestia 2180, 9320 (near the end), and 9380).

(By Rev. David Millar, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Numbers
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The book of Numbers is the fourth book of the Bible. It gets its name from the two censuses of the Children of Israel mentioned in chapters 1 and 26. The original Hebrew name of the book is different; it can be translated as "In the Wilderness", and indeed the story is set in the wilderness after the Children of Israel flee Egypt, and before they arrive in Canaan.

The internal meaning of the Book of Numbers concerns spiritual development: our gradual change from selfishness to love and obedience to God. The events in the book reflect the personal work we must do to improve our spiritual lives.

Here's a brief overview:
The first part of the book focuses on the duties of priests and laws for common people. The main spiritual idea here is for us to have a sense of reverence for the Lord and to make space for Him in our lives.

In chapter 10, the Lord commands the people to leave Mount Sinai and to make two silver trumpets for calling the people and determining the movement of the camps.

In chapter 11, the people complain about manna being their only food, and the Lord tells Moses to appoint seventy elders to help him govern. Jehovah also instructs Moses to tell the people the the Lord will give the people meat for a whole month until it becomes loathsome to them. The Lord sends quails which plague on the people.

Next, Aaron and Miriam complain against Moses. Miriam is cursed with leprosy as punishment, but the Lord lifts the curse after seven days of her exclusion from the camp.

Next, in chapters 13 and 14, there's the “spying out the land” story. Jehovah tells Moses to send twelve men to spy out the land of Canaan. Upon their return, ten of the twelve claim that the land is inhabited by giants and cannot be taken. Two of the spies, Joshua and Caleb, say that Israel should go up and take possession of the land with Jehovah's help, but they do not convince the people.

For this lack of faith and confidence, God tells the Israelites that they will wander in the wilderness for forty years until all the adults who set out from Egypt have died - except for Joshua and Caleb - and that their children will get to go into the land. The subsequent chapters describe various events in this long wandering. The spiritual meaning of forty (40) always has to do with experiencing temptations and the time and endurance which that involves.

Then, in chapter 16, Korah and some of his friends accuse Moses and Aaron of self-aggrandizement. Moses and Aaron defer to the Lord's judgement. The Lord commands each tribe to bring a rod with a name on it into the Tabernacle overnight and for "Aaron" to be the name on the rod of Levi. The following morning, Aaron's rod was the only one to sprout leaves, signifying Jehovah's approval.

After two chapters detailing the duties of the Levites, chapter 20 relates some major events. The Children of Israel, yet again, are complaining to Moses, this time about being thirsty. Moses impatiently strikes a rock twice to get water to come from it, and takes some of the credit for the miracle. It's an un-trusting, prideful moment for him. For his lack of faith, he's told by God that he himself will not be allowed to enter the land of Canaan.

Then the Children of Israel ask the king of Edom for passage through this land, but the king refuses, and Israel is forced to turn aside as they leave Kadesh. The chapter ends with the death of Aaron.

The people again complain, and the Lord sends fiery serpents which bite many of them, and they die. The people then repent and ask for forgiveness. The Lord tells Moses to make a fiery serpent and set it up on a pole, so that whoever looks at the bronze serpent shall live.

Israel moves on, and asks Sihon the king of the Amorite for passage through his land. He refuses, and this time, Israel fights, defeating his armies and taking possession of this land.

The next three chapters - 22 to 24 - are about Balak and Balaam, with the well-known stories of Balaam's donkey seeing the angel when Balaam cannot, and then, with Balaam's beautiful prophecy of the birth of Jesus Christ.

Various chapters of ritual laws come after the second census in chapter 26. Chapter 31 describe Israel's conquest of the Midianites. Chapter 32 is about the agreed settlement of the tribes of Reuben and Gad, and half of the tribe of Manasseh on the east of the river Jordan; chapter 33 lists the camp locations from Egypt to the banks of the Jordan; chapter 34 spells out the future borders of Canaan and the leaders from each tribe who shall divide the land as an inheritance; and the final two chapters are about laws concerning judgments on murder and bloodshed and laws about marriage. At this closing point of the book, the Israelites are encamped in the plains of Moab by the river Jordan, across from the city of Jericho.

(By Rev. Julian Duckworth, of the New Church in Australia, and the New Christian Bible Study staff and volunteers.)

=== Introduction to Deuteronomy
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Deuteronomy is the fifth book of the Bible, and the last of the "five books of Moses". The events in Deuteronomy take place over roughly a two-month time span; just before the children of Israel cross over the River Jordan to enter the land of Canaan. Moses has been told by Jehovah that he will not be permitted to enter the land of Canaan himself, and - now 120 years old - he seeks to prepare his people for what lies ahead. In several speeches, he reminds the people of their past, forecasts their future, and restates the laws that they should follow, and - above all - exhorts them to follow Jehovah, and to worship no other gods.

The word "Deuteronomy" means "a repetition of this law". It's taken from a Greek word, Δευτερονόμιον, which is how the book is named in ancient Greek texts. The Hebrew name for this book is דְּבָרִים, pronounced Dəḇārīm, meaning simply "Words".

The first part of the book is a narration by Moses, reviewing the Children of Israel's long sojourn in the wilderness, and the Lord's guidance throughout that time.

In Chapter 5, there's a restatement of the Ten Commandments, and it's interesting, too, to see the details that Moses provides in Chapter 10 about the two tables of stone and the ark that contained them.

There's tremendous depth in the whole Word - and Deuteronomy is no exception. The literal sense is powerful, sometimes clear and inspiring, and sometimes obscure or troubling. There are certainly harsh passages in Deuteronomy, and yet, it's striking, too, that there's also a sense that we should always be seeking to be led by the Lord. When the Children of Israel trust in the Lord, there is much good to be found in life. When they do whatever they want, or are led astray into worshipping other gods, hell breaks loose.

It's interesting, too, that the Israelites are commanded to fight some of the neighboring peoples, but to live peaceably with others -- the descendants of Esau and Lot. At a deeper level, this means that there are various external forms of good and truth which can be comfortable neighbors. They're not as pure or strong as goods and truths that have become internalized, and are at the heart of our lives, but they're still in natural good. And, then, there are the people of Ammon and Bashan, who represent outright evils and falsities that we have to root out of our lives, or they will corrupt and destroy us.

The final chapters of Deuteronomy are quite moving. Moses is told by God to go up Mount Nebo where he is shown the whole land of Canaan laid out below. One can sense Moses's disappointment that he can't enter into Canaan himself, and, even more, his urgent sense that the Children of Israel should know and follow Jehovah. He's confident, though, that Joshua will lead them well. Moses then blesses each of the twelve tribes of Israel by name before he dies and is buried on the east side of the Jordan in an unmarked grave.

(By Rev. Julian Duckworth, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Joshua
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The Book of Joshua marks the beginning of a new era for the Children of Israel. Moses, who led them out of bondage Egypt, and then for 40 years in the Wilderness, has died, looking out over the promised land of Canaan from Mount Nebo. He's been buried, and duly mourned.

Now, the Children of Israel are given a new leader, Joshua the son of Nun. Joshua represents Divine Truth that fights for our salvation. His name means Jehovah our Saviour, and its Latinized form is "Jesus".
Before the Children of Israel lies a land "flowing with milk and honey", where their forefathers had lived, yet the land is also populated by hostile tribes who will need to be defeated before the Israelites can live there.

The Book of Joshua can be divided into three parts:
    • Chapters 1-4 deal with the miraculous events involved in the Israelites crossing into the land of Canaan through the Jordan River.
    • Chapters 5-12 deal with the conquest of the land beginning with the walled city of Jericho. The Israelites then suffered defeat at Ai and had to regroup and expunge the sins that had led to this setback. With renewed faith, they continued the conquest, moving throughout the land. Despite the Lord's desire that the Israelites possess the whole of the land, they failed to do so, preferring to rest instead. This allowed their enemies to gain strength to attack again.
    • Chapters 13-24 deal with the division of the land amongst the tribes of Israel. Some of the cities are set aside specifically for the priesthood (Levites) who, given the nature of their work, did not receive an allocation of land.

The deeper meaning of this book is about how we need to use the Lord's Word to fight against vices within us that prevent us from living a heavenly life. Every battle that the sons of Israel fought represents various battles that we have to face in ourselves -- battles against false beliefs and selfish motivations.
(By Rev. David Millar, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Judges
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The book of Judges is the seventh book of the Bible. It's set in the time between Joshua's death, after the initial conquest of the land of Canaan, and the eventual establishment of kings in Israel many years later. During this time, the tribes of Israel formed a loose, decentralized alliance, and they looked to local or regional leaders to act as judges, and often as military leaders, too. The notable stories about these leaders form the basis of this book - hence the name, "Judges".
There are twelve judges mentioned in all. The number twelve (as with the twelve tribes of Israel, the twelve disciples, and other examples in the Word), stands for all the various aspects of spirituality that we need to understand, develop, and put to use. The names of the judges give us some insights into the inner meaning of these stories. Biblical names are nearly always linked to spiritual qualities, such as 'courage', or 'one who walks with God'. (For more on this, see Swedenborg's work, Arcana Coelestia 10216).
The accounts provided in Judges are not at all proportional to the length of a judge's tenure. Some of the longest-ruling judges are written off in just a single verse! Instead, the stories that have been preserved are the ones that the Lord could use in the Bible to teach us what we need to know about how to fight evil and learn to love good.
A repeating pattern emerges in the Book of Judges:
    1. The Children of Israel fall into evil, disobeying the Lord.
    2. An enemy oppresses them.
    3. The Lord raises up a leader, who is victorious against the enemy.
    4. There is peace for a time.
    5. And then, Israel relapses, and disobeys again.

You can think of this pattern as the 4 Rs - rebellion, retribution, repentance, and rescue. The people rebel against the Lord, they're beset by an enemy, they repent, and a rescuer - a judge - is raised up to fight to bring them back into freedom and to the Lord.

The overarching spiritual theme in the Book of Judges is that this same repeating process occurs in our own regeneration. There were still parts of the land that Israel had yet to conquer. In the same way, we need to conquer the evil tendencies of our inherited human nature. (For reference, see Divine Love and Wisdom 238). During regeneration, we will discover deeper and subtler self-centered states in ourselves which need to be rooted out. Each judge raised by the Lord stands for our determination to deal with these successive states, using the Word as a guide. This brings us a period of peace, followed by the start of another personal discovery.

In the Judges stories, the enemies of the Children of Israel were of three kinds:
    1. unconquered tribes within Canaan,
    2. external enemies including the Ammonites, Midianites and Philistines,
    3. and themselves. (See Judges 9, 12, 20)
As we're pursuing our spiritual journeys, we face these kinds of enemies, too. These challenges make for memorable stories: Samson, Gideon, Ehud, and Deborah are all featured in Sunday School lessons across Christendom thousands of years later.

At the end of the book, things are degenerating again, and the stage is being set for the next act. The final stark verse of the book says, “In those days there was no king in Israel; everyone did what was right in his own eyes.” (Judges 21:25)
The book of Judges calls us to decide for ourselves how we are going to live. Will we bring the truth we know from the Lord down into our own lives? Or forget the Lord, and go our own way? The unconquered tribes are still out there, waiting. Confronting these requires great determination and courage.
(By Rev. Julian Duckworth, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to 1 Samuel
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The first book of Samuel holds some of the Old Testament's most dramatic and memorable stories. God calls Samuel, when he's still a boy, to be the next prophet in Israel. Saul is anointed the first king of Israel. He starts well, but twists into evil. David - a teen-age shepherd - arrives in Saul's war camp at a critical moment, and volunteers to do battle with Goliath, the fearsome Philistine giant. David and Jonathan, Saul's son, become fast friends.

These stories aren't merely dramatic; it's possible for the careful reader to see the journey of life illustrated here. Our lives are marked by a series of turning points. Some of these are subtle, and some are more abrupt. The first book of Samuel shows us both.
1 Samuel marks a historic turning point for the people of Israel. They had been led by a series of judges and priests who governed by direct Divine command. The trouble was that the people - and sometimes their leaders, too - did a poor job following God's hopes for them. They flagrantly disobeyed their covenant with God and, time and again, found themselves caught without His protection as a result.

The book of Judges ends with the words, “In those days there was no king in Israel; everyone did what was right in his own eyes.” 1 Samuel starts with that theme.

The book begins with a heartfelt prayer from a childless woman. When God gave Hannah the child she prayed for, He also gave Israel the last, and indeed the greatest, of its judges. Once weaned, the young child Samuel was presented to Eli the high priest so that he might remain at the tabernacle with him and serve God. Samuel's innocence was in stark contrast to the growing evil of Eli's two sons, Hophni and Phinehas, who were descending into a life of corruption and debauchery. They undermined the priestly office and, in doing so, caused God to separate their family from His service.

These were difficult times for Israel. The Philistines fought with Israel and regularly defeated them. Eli's sons were killed in one of these battles, the shock of this news caused Eli to fall off his chair and die. The Ark of the Covenant was stolen by the Philistines, though they soon began to suffer from the effects of holding this most precious religious artifact.

Under Samuel's guidance there was a twenty-year period during which there was a genuine effort to return to God's ways. The Ark was returned to Israel. Worship was restored - for a while. But the sincerity and strength of Samuel's leadership, however, was not carried on by his sons. Over time they became as bad as Eli's sons had been, repeating the pattern that had occurred with Aaron and his sons many generations earlier. This situation became part of the motivation for Israel to demand a king “like the other nations.” This marked an important emotional turning point for Israel. They were no longer prepared to accept the type of leadership that God appointed for them. Now they were calling for a leadership style of their own choosing.
A young, humble man from an insignificant family within the small tribe of Benjamin was chosen by God to be Israel's first king. Saul wasn't from a powerful family, but he was physically outstanding. He was said to have been the most handsome man in the land and he stood a head taller than anyone else. When the story turns its focus to Saul, he's out scouring the countryside for his father's missing donkeys. He had more or less determined that it was time to give up and head home when his servant appealed to him to seek advice from a wise man - Samuel - who lived in that country. God helped Samuel recognize that Saul was the man He had chosen to be the first king of Israel. Saul's head was anointed with oil as a symbol of his Divine appointment. The fulfilment of Samuel's prophecies on the journey home convinced Saul of the validity of Samuel's authority and of his own new position.

The spirit of God came upon Saul, and Israel under Saul's leadership achieved a magnificent victory over the Philistines. Most of the initial opposition to Saul's leadership melted away, and he was crowned king by the people. Tragically, though, Saul's reign went downhill from there. During another battle with the Philistines, Saul grew restless when Samuel was late to arrive. He conducted his own sacrifice to God, and in the process broke the law that stated that only priests could fill this function. Samuel was clearly angry and announced that the kingdom would be taken from Saul.

What follows next is a disjointed story that introduces David, the man who would replace Saul as king. Through God's instructions, Samuel anointed David king. This was long before David became a nationally recognized figure. As the spirit of God entered David, it was withdrawn from Saul. In its place, Saul began to be haunted by forces of evil. It was believed that music would help ease Saul's pain and his erratic temperament. David was a skilled harp player. He was called to Saul's house to serve as a musician.

What comes next seems out of sequence. We are given a scene of a battle between Israel and the Philistines. It is here that we find the much-loved story of David and Goliath. What is remarkable is that Saul seemed to have no idea who David was. David told tales of killing a lion and a bear in order to defend his father's sheep. It was with much reluctance that Saul allowed David to approach Goliath.

After David killed Goliath, and Israel celebrated this victory, Saul grew more jealous of David by the day. This led to a chase that would see Saul pursue David across much of Israel's territory. David became an outlaw. He escaped to a cave, and while he was there, many of Israel's disadvantaged and disenfranchised saw him as their only hope.

Despite Saul's actions, he was still the rightful king in David's eyes. David spares Saul's life on two occasions, the second time when he slipped into Saul's sleeping camp unnoticed. It was during this time that we hear of Samuel's death, thus closing the final chapter of Israel's former history. This is also when we meet Abigail, one of David's earliest and most influential wives.

Saul's pursuit of David was put on hold while he attempted to put down yet another Philistine incursion. This battle, as it turned out, was Saul's last. He died on the battlefield along with Jonathan, his son. While this was happening, David was avenging an Amalekite raid in another part of the land.

The friendship of David and Jonathan is one of the most uplifting aspects of this story. Amid the fury of Saul's pursuit of David, we find this unbreakable bond between two brave young men. Tragically, one of their lives ends prematurely. Before then we are presented with a scene where David was hiding from Saul:
"Then Jonathan, Saul's son, arose and went to David in the woods and strengthened his hand in God. And he said to him, 'Do not fear, for the hand of Saul my father shall not find you. You shall be king over Israel, and I shall be next to you. Even my father Saul knows that.' So, the two of them made a covenant before the LORD. And David stayed in the woods, and Jonathan went to his own house." (1 Samuel 23:16-18)
With David and Jonathan we see some of the qualities by which God could lead Israel, and indeed all of us, back to His way. They showed courage, integrity, and trust in God. If only David could have lived up to these ideals throughout his life, Israel would have had its future secured. As it would turn out, David would be haunted by an array of human failings. Yet, in spite of his shortcomings, he was able to strengthen and increase Israel's land and wealth. David faltered, but kept returning to a faith in God. This reliance on the power of God is among the reasons that David is remembered as Israel's greatest king.

(By Rev. Garry Walsh, now the pastor in Sarver, Pennsylvania, but formerly with the New Church in Australia and the New Christian Bible Study staff and volunteers.)
=== Introduction to 2 Samuel
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The Second Book of Samuel deals with the establishment of David as the king of Israel, and his reign. The first part of the book (2 Samuel 1-5) provides an account of David's progress toward consolidating power after the death of King Saul. Having established himself, as related in the stories in 2 Samuel 6-9, he is a king in the fullness of his powers and the glory of his kingdom.

As king over Israel, David on a symbolic level represents the Lord as the King of Heaven. This is not to say that David personally was without faults or human weaknesses. In the Bible, the function of kingship transcends the person who is proclaimed king. This means that a person can possess questionable qualities, and even engage in actions that are anything but holy, and still represent the Lord.

We see this phenomenon in 2 Samuel 10-20 where we find David's personal weaknesses impacting those around him and the Kingdom of Israel as a whole. Beginning with his adulterous behavior with Bathsheba and the subsequent murder of her husband to cover his sin, the book takes a tragic and sombre turn. Nathan the prophet calls David out and his sin is revealed before all.

While David does repent, he nevertheless cannot escape the consequences of his transgression. The child born to Bathsheba dies. David's life descends into sorrow as he fails to rein in the wickedness of his sons. The nation is plunged into civil war through David's son Absalom's rebellion, and David has to flee from Jerusalem for a while. Later in the war, Absalom dies in the field, much to David's sorrow.

The book closes (2 Samuel 22-23) with David's own song of praise to the Lord who has delivered him from all his enemies. But then, once again, David sins against the Lord by numbering the people of Israel without permission (2 Samuel 24), and again he repents so that the resulting plague that resulted might be removed.

The deeper, spiritual meaning of the events in 2 Samuel deal with how, when we acknowledge the authority of Divine Truth in our life, we need to bring all things that stand opposed to it under its rule. If we have evil loves and false ideas that we are not willing to deal with, they can wreak havoc and destroy the Lord's peace for us.

Concerning David... in New Christian thought, we have this teaching from the work Apocalypse Explained 205:
“David,” as being the Lord in respect to Divine truth. By “David” in the Word the Lord is meant, because by “kings” in the Word, the Lord in respect to Divine truth is represented, and by “priests” there, the Lord in respect to Divine good. The Lord is represented especially by king David, because David had much care of the matters of the church, and also wrote the Psalms. (That “kings” in the Word signify Divine truth, and “priests” Divine good, see above, n. 31; moreover, that all names of persons and places in the Word signify spiritual things, which are the things pertaining to the church and to heaven, see above, n. 19, 50, 102.)

(By Rev. Garry Walsh, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to 1 Kings
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The First Book of Kings begins with the waning days of King David's reign. There's a struggle for succession, but David chooses Solomon to be heir to the throne.

In a dream, Solomon asks God for the wisdom to be a good king. God grants him that, and, because he values wisdom more highly, wealth and honor to accompany it.

In chapter 3, there's the famous story of Solomon judging between two mothers of infant sons.

In chapters 4-9, Solomon's reign is both good and prosperous, and, with God's blessing, he launches and oversees the building of the temple in Jerusalem.

In chapter 10, there's a description of the visit by the Queen of Sheba, who had heard of Solomon's wisdom, and who brought rich gifts to him. This story is also in the Quran, and in Ethiopian tradition, too, and it's at the root of some stories of the Lost Ark. In some ways, it is the high-water mark of the Israelitish church.

But then, in Chapter 11, things turn sour quickly. Solomon strays into idolatry, influenced by his many wives and concubines. His son, Rehoboam, isn't much good. The kingdom splits into two pieces, with 10 tribes forming the Kingdom of Israel, and Judah and Benjamin forming the Kingdom of Judah.

From that point on, there's a long slide down, away from true worship. In Israel, from Jeroboam on, there's not one good king, until the Assyrians sweep the ten tribes away, out of history, several hundred years later.

In Judah, the kings are mostly bad, but every now and again there's a good one. There's a remnant of good and truth, even when the Babylonians sack Jerusalem in 586 BC, and later when the exiles return, and rebuild the temple.

In chapters 17-22, we have the stories of the great prophet Elijah, his disciple Elisha, and their opposition to the evil figures of King Ahab and Queen Jezebel.

There are famous stories throughout:

 - Elijah is fed by ravens in the wilderness (1 Kings 17:2-7)
 - Elijah vs. the prophets of Baal (1 Kings 18:19-40)
 - The still small voice (1 Kings 19:9-14)
 - Ahab covets Naboth's vineyard. (1 Kings 21)

The literal accounts of the lives of the kings and those around them are used to teach us one simple but hard-to-do lesson: When we do what God wants us to do, it will produce blessings. Ignoring Him leads to bad outcomes. "All" we have to do is to ask the Lord, over and over again, to help us fight our evil tendencies, to try to be good, and to accept his leadership in building a good ruling love in the core of our being.

“_Now if you walk before Me as your father David walked, in integrity of heart and in uprightness, to do according to all that I have commanded you, and if you keep My statutes and My judgments, then I will establish the throne of your kingdom over Israel forever, as I promised David your father, saying, 'You shall not fail to have a man on the throne of Israel'_” (1 Kings 9:4, 5)

(By Rev. Trevor Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to 2 Kings
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Reading through these the Books of Kings is an adventure. They contain many highs and lows. Examples of these are the contrasting heroic characters such, as David, approaching the end of his reign and passing the royal role to Solomon; the interaction of Elijah and Elisha set against opposite evil figures in Ahab and Jezebel.

Overall, the stories contained in these two books have stimulated the writing, production, and presentation of many motion pictures. The seduction and romance between Solomon and the mysterious Queen of Sheba, along with the intrigue surrounding their relationship, is an outstanding illustration of this point.

The literal accounts of the lives of the kings and those around them are used to teach how observance of God's law produces blessings while ignoring Him provokes punishment.
“Now if you walk before Me as your father David walked, in integrity of heart and in uprightness, to do according to all that I have commanded you, and if you keep My statutes and My judgments, then I will establish the throne of your kingdom over Israel forever, as I promised David your father, saying, 'You shall not fail to have a man on the throne of Israel'” (1 Kings 9:4, 5)
The theological thrust of the literal sense within the Books of Kings provides a prophetically oriented evaluation of the spiritual and moral causes that lead to the political and economic ruin of the two kingdoms. For example, Omri was one of Israel's most important rulers from a political point of view, but because of his moral corruption, his achievements are dismissed in a mere eight verses (see 1 Kings 16:16, 21, 22 and 23-27).
Apart from the obvious teaching of these two books, the spiritual message demonstrates the benefits of allowing the Lord to develop a positive “Ruling Love” that serves as a moral compass within one's own journey.
(By Rev. Trevor Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Psalms
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Someone once said to me that the Psalms are simply poetry with God in them but they don't tell us much! It can seem that way at first glance, but I don't agree.

Teachings from the works of Emanuel Swedenborg provide insights into the Psalms. Swedenborg cites various Psalms throughout his writing, and his work The Inner Meaning of the Prophets and Psalms contains a breakdown of the spiritual meaning behind each individual psalm.

I'm going to run through Psalm 121 and share how I break it down. I encourage you to read other psalms and admire the wisdom and teachings they offer.

I will lift up my eyes to the hills -
From whence comes my help?
My help comes from the Lord,
Who made heaven and earth.

He will not allow your foot to be moved;
He who keeps you will not slumber.

Behold, He who keeps Israel
Shall neither slumber nor sleep.

The Lord is your keeper;
The Lord is your shade at your right hand.

The sun shall not strike you by day,
Nor the moon by night.

The Lord shall preserve you from all evil;
He shall preserve your soul.

The Lord shall preserve your going out and your coming in
From this time forth, and even forevermore.

This Psalm says a lot about the Lord. In fact, apart from the opening verse, it is all about the Lord, giving us ideas about His providence over us. I get the sense that the Lord is involved with me and works to keep me safe. The word 'keep' seems important in this connection, suggesting there are things the Lord won't allow to happen. But I don't think this has to do with the physical things in life, but with more spiritual things - things to do with my trust and confidence in the Lord. Once I know and feel these things, the Lord will keep them there. The opening verse seems to be saying that I need to lift my mind a bit higher than usual in order to become aware of the Lord's real place in my life. I can't muddle around umming and ahhing about life and expect the Lord to make His presence known to me. It doesn't work like that.

(By Rev. Julian Duckworth, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Isaiah
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Isaiah's Ministry was centered in Judah and spanned from 740-680 BC. It begins near the reign of Uzziah and continues through the kingships of Jotham, Ahaz and Hezekiah. The different qualities and influences of these kings both for good and evil, have a major influence on the fortunes of Israel.

Isaiah, whose name means “Yahweh is Salvation”, came from a distinguished Jewish family. He was highly educated and had two sons. His use and grasp of language is demonstrated in the majesty and grandeur of the text, and this is part of the reason why it is my favorite book in the Old Testament.

We could say that this book is the 'Bible in miniature'. It has 66 chapters and there is a definite change in emphasis in the text from Isaiah 40 onwards. We have 39 chapters in the first part and 27 in the second, which is the same as the number of books in the Protestant Old and New Testaments.

Isaiah is the first book of the major prophets in the Word. The distinction between major and minor is defined by length of the book, and not necessarily their standing in history.

The main message of Isaiah is:
    • To warn the Jewish nation of the danger of alliances with pagan nations and idolatry
    • To describe God's judgement and our need for repentance while promising forgiveness
    • To foretell the coming of the Messiah.

Its general themes include:
    • God's complaint against Judah
    • Judah's fall and restoration
    • Judgement on Israel and other nations
    • Peace, consolation, hope, and comfort following judgement

As mentioned earlier, it is the beauty, grandeur, and power of the text that makes it stand out. It is the most quoted Old Testament book in the New Testament and is regarded as the “Romans of the Old Testament” with its focus and sweep of the Messianic prophecies.

In both its literal and spiritual meaning, the book of Isaiah foresaw man's descent into evil and the need for the birth of Jesus Christ. Isaiah is very much focussed on the central places of Judah, Jerusalem, and Zion. In New Christian thought, Jerusalem symbolizes the church in the hearts and minds of people. It enables us to focus on the way the Lord leads His people.

In the spiritual sense, we see Jesus Himself and the battles He faced and we face as individuals on our spiritual journey. Simply put, we can see the first 39 chapters as reflecting the acts of repentance and reformation and the last 27 of our spiritual rebirth.

It is interesting to note that in the last verse of chapter 39, there is a distinct change from doom, gloom and judgement to comfort, consolation and hope. In the original text found at Qumran there is no suggestion of a break. The chapter headings had been added later.
(By Rev. Chris Skinner, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Jeremiah
Jeremiah did not want to be a prophet, but the Lord had designated him to be one even before he was born. (Jeremiah 1:5). He saw himself as an inexperienced youth, unfit for the task and responsibility. It hurt Jeremiah to tell the people what God called upon him to say (Jeremiah 5:19). He was denied marriage and a family (Jeremiah 16:2) when he wanted one. He carried out the Lord's command to say unpalatable things to his people with integrity.

Jeremiah prophesied during the last 25 years of the kingdom of Judah. By this time, the northern kingdom of Israel had long since succumbed to the Assyrians and its people had been re-settled in another part of the Assyrian empire. Judah, though, pressed on and remained intact
In the meantime, Judah was mostly incapable of learning important lessons about how its neglect of religion led to its weakening and susceptibility to foreign influence. The people of Judah had a smug mindset that nothing bad could happen to them. It is this unwarranted self-certainty that Jeremiah tried desperately to get through to alert the people of the consequences ahead. Nevertheless, they aggressively dismissed Jeremiah.

The people of Judah were against reform. They welcomed false prophets who told them what they wanted to hear. As for the loathed Jeremiah, he was threatened and beaten multiple times. He would have abandoned his calling, yet he was committed to his post.

Jeremiah's devotion to obeying God's commands was amazing. He counselled his people to accept the inevitability of conquest by the Babylonians. It's astonishing to read how stubborn, self-righteous, and unwilling the people of Judah were to recognise their predicament and accept that they had brought this trouble on themselves.

Jeremiah was relentless in his duty as a prophet, which in turn makes his writing heavy. But the read is worth the effort. Let yourself be attracted to Jeremiah for his strong commitment to his work, for his courage, and for his great love of Judah for whom he “yearned to sound the alarm, and save them from the impending fall.”
Sometimes we have to go through dark and captive states to come to understand and value the Lord's will as opposed to our own. We have to be brought down. And yet it is from that experience that a new start can - and will - be made.

As you think about Jeremiah, let yourself also think of the Lord; of His great love for the human race; of all the efforts He has made, “to sound the alarm, and save (His people) from the impending fall”. Think, too, of the thanklessness Jesus met while on earth, the plots to kill Him, and the way scribes and Pharisees moved so sinisterly against him. While we are reading the Bible we think we are reading about the man Jeremiah, “but in the internal sense the Lord is meant.” (Arcana Coelestia 2838).

Here are two beautiful gems you can find in Jeremiah:

 “Thus says the Lord:
 “Stand in the ways and see,
 And ask for the old paths, where the good way is,
 And walk in it;
 Then you will find rest for your souls. ...” (Jeremiah 6:16)

And,

 “Thus says the Lord:
 'Let not the wise man glory in his wisdom,
 Let not the mighty man glory in his might,
 Nor let the rich man glory in his riches;
 But let him who glories glory in this,
 That he understands and knows Me,
 That I am the Lord, exercising loving kindness,
 judgement, and righteousness in the earth.
 For in these I delight,' says the Lord.” (Jeremiah 9:23, 24)

(By Rev. Ian Arnold, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Lamentations
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The book of Lamentations is attributed to Jeremiah and it is the outpouring of the prophet's grief and regret that something his people had once enjoyed was now lost and devastated.

In 586 BC, the Babylonians overran the kingdom of Judah. They invaded its capital, Jerusalem, and destroyed the Temple, carrying away its treasures. It was a monumental blow and loss - a loss of independence, confidence in God, faith, and identity.

But as in Jeremiah, Lamentations doesn't absolve the people of responsibility for this terrible state of affairs. To the contrary, it drives home the message that what had happened was the consequence of the people's own bad behavior in defiance of God's laws and order.

Yet, there is hope. It is not as if this small book of the Bible, just five short chapters, is all doom and gloom.

Let's look at this in our lives. There are occasions when high ideals, principles, and moral values we hold are invaded and brought down by hostile forces. Examples of this include irritable displays of judgement, bouts of anger, or lustful thoughts.

What needs to follow is sadness and regret, not just as something passingly acknowledged on the surface, but a real, deeply-felt lament. What have I lost? What has brought me to this terrible state of affairs?
What we can't do is side-step our responsibility, resolutely blaming circumstances or others. And in the midst of it all, the Lord keeps alive a flickering hope which will in time flare up and lead us forward and out of this dark state of mind.

(By Rev. Ian Arnold, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Ezekiel
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Ezekiel is a strange book of visions in the Bible. It begins with an amazing image of wheels within wheels and it ends with a powerful vision of the Temple of God. In between there are other visions, parables, judgments, predictions, and symbolic actions - all of which give the whole book an eerie feel to it. Yet, amid all this strangeness there is a single straightforward message from Ezekiel: the people should return to the Lord and to be faithful to their God.

The timing of Ezekiel is important. It was written when Jerusalem was overrun and destroyed and when the Jews were taken captive in Babylon. Ezekiel himself is in Babylon, in captivity, writing about the imminence of this coming destruction. His fellow captives persisted in believing that Jerusalem would never be taken nor the temple destroyed. Ezekiel spelled out that these events would take place and tried to explain why. Later in the book, after Jerusalem has fallen, Ezekiel's message dramatically changes and he reveals the future restoration of Israel and the coming glory of Jerusalem. The middle part of the book is a condemnation of the surrounding nations and the ways in which the Lord would eventually bring judgement on them.

It's not easy to cover everything in Ezekiel, but it will help to highlight the main sections. The first chapter features an astounding vision of God in symbolic pictures. Ezekiel keeps saying that what he sees and describes has a likeness to various images, almost as if he can't put it into words. First, he sees the likeness of a whirlwind engulfed in fire, out of which come four living creatures with four faces and four wings on each one. The living creatures move in a straight line back and forth like a flash of lightning. Then he sees wheels with rims full of eyes, and finally he sees a throne with the likeness of a man high above it. “This was the appearance of the likeness of the glory of the Lord.” (Ezekiel 1:28)
This is a vision of the powerful, all-seeing, all-knowing God. What follows is a tirade against Israel's rebellion. Passages on punishment are broken up with passages of restoration. Jerusalem is described as a prostitute and an adulteress in no uncertain terms, yet the Lord describes His love for her. Ezekiel is commanded to perform several representations, like shaving his head (Ezekiel 5) to show the terrible state of the people.

When the Lord speaks of His love for Jerusalem, it sounds like a tender voice - similar to a parent speaking to a child. Perhaps the most moving instance of this comes in Ezekiel 34. The Lord condemns the shepherds of Israel for their own indulgence and irresponsibility in leaving the people without a shepherd, followed by a description of the Lord's own desire to gather his people together and heal their wounds. The contrast is immense.

The best way to approach Ezekiel is to meditate on its imagery and hear the tender appeal of a loving Lord.
(By Rev. Julian Duckworth, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Daniel
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Daniel is the shortest book among what are known as the “major prophets”. It only has twelve chapters compared to Isaiah's sixty-six.

The book divides neatly into two halves. Daniel 1-6 relates some of Daniel's adventures, and Daniel 7-12 his dreams and visions.

The first half recounts Daniel's exile in Babylon. Some of its more well-known stories include:
----
 • Nebuchadnezzar's dreams
 • The fiery furnace
 • The writing on the wall
 • Daniel in the lion's den
----
The second half overlaps chronologically with the first half:
----
 • Daniel 7 and 8 both occur some time during the reign of Belshazzar (between Daniel 4 and 5)
 • Daniel 9 and 11 during the reign of Darius (around the time as Daniel 6)
 • Daniel 10 (after Daniel 6), during the reign of Cyrus
----

The second half is not as well-known as the first half. In many regards, however, Daniel 7-12 constitutes the more important half of the book. This is because its imagery and text is referenced throughout the New Testament. For example, the vision of four beasts and the Ancient of Days (Daniel 7) parallels John's vision of the throne room in (Revelation 4) and the beast from the sea in (Revelation 13).

The book uses the phrase, “son of man”. In Daniel 8:17, it refers to Daniel himself - mirroring its use in the prophecy of Ezekiel. However, (Daniel 7:13) contains a much more familiar image, where it refers to the Lord: “_And behold, One like the Son of Man, Coming with the clouds of heaven!_” This is quoted directly in (Matthew 24:30) and (Revelation 14:14), and Jesus also refers to himself as the “Son of Man” throughout the gospels.

Daniel 10 also contains a vision of the Lord with many parallels to John's visions in Revelation 1 and 19 - the glorious man having the likeness of the sons of men.

Two angels are named in the book of Daniel, and both play a significant role in different parts of the New Testament: Gabriel, the messenger (see Daniel 8:16, 9:21, Luke 1:19, 26) who announces the birth of the Jesus; and Michael, the warrior prince who leads the armies of heaven (see Daniel 10:13, 10:21, 12:1, Jude 9:0, Revelation 12:7). Daniel is the only Old Testament book to mention these angels.

So, you can see that the second half of the book of Daniel is heavily connected to subsequent parts of the Bible. That makes it worth reading, and it's certainly not something we should just ignore because it's confusing at first glance.

(By Rev. David A. Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Hosea
By the clergy of the New Church in Australia, New Christian Bible Study Staff

In the Old Testament, prophets had unusual and challenging experiences so that their messages would have an added edge to them.

One of these prophets was Hosea. He is the first of the twelve “minor” prophets, not in the sense of being insignificant, but “minor” in the sense that these books are so much shorter than those of the major prophets.

Hosea lived at a time of widespread unfaithfulness among the Israelites. In order to understand the wicked behavior of his peers, Hosea was told to, “_Go, take yourself a wife of harlotry and children of harlotry, for the land has committed great harlotry by departing from the Lord._” (Hosea 1:2).
Hosea obeyed these instructions. He married Gomer, a prostitute, and together they had two sons and a daughter. With each birth came a dark message of indictment and warning to the people. Gomer eventually went back to her harlotry from which Hosea redeemed her. It is a pitiful development, but having gone through this experience, Hosea understood and appreciated the message he was called to give. Even though the Israelites had a unique relationship with the Lord, they wantonly lusted after other gods.

The book of Hosea is not solely a condemnation of evil. Woven through it are memorable calls to repentance, and Hosea 11 contains one of the most magnificent statements about the enduring nature of the Lord's love.

It is central to the Lord's reaching out to us that here in the prophecy of Hosea, as in other parts of the Word as well, God describes His relationship with us as that of a husband and wife. The Lord reaches out to us seeking a lovely response and commitment. The relationship is emphatically reciprocal and monogamous. We receive life from the Lord and give it flesh and body. The promptings of love come to us from Him. As this marriage of love and truth takes place in our lives, the relationship grows deeper and stronger.

In spite of our flawed nature, the Lord is committed and patient toward us. He is our God. He is not subject to human limitations and does not have contempt towards us, but instead gently pleads for us to rediscover the nobility, beauty, and splendour of our holy relationship to Him.
“Those who dwell under his shadow shall return; they shall be revived like grain and grow like a vine. Their scent shall be like the wine of Lebanon. Ephraim shall say, 'What have I to do any more with idols?' I have heard and observed him. I am like a green cypress tree; Your fruit is found in me.” (Hosea 14:7, 8).
This is the upbeat note the prophecy finishes on; it features the words of a people who have reaffirmed their relationship with the Lord.

(By Rev. Ian Arnold, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Joel
Joel is the second of the minor prophets. In contrast to Hosea, which focuses on the Northern Kingdom of Israel, Joel's emphasis is on the Southern Kingdom of Judah. Symbolically, Israel represents understanding God's truths and Judah will obey them. Therefore, the thrust of the book focuses on the way in which we live out our understanding of the Lord.

This book depicts the stark choices the Israelites face. On a more deeper level, it illustrates the decisions we make that affect our spiritual life.

All three chapters echo themes that occur in the other prophets. As messengers of the truth, prophets try to bring about repentance among their people. The latter part of the third chapter focuses on hope and how the Lord is always ready to lead His people to a life of love and usefulness as opposed to selfishness and evil. We should also see this pattern in our own spiritual journey if we end up focusing solely on ourselves rather than God. This struggle is repeated over and over again in the book of Joel.

This little book contains a myriad of themes from the Old Testament. Additionally, key concepts from New Christian thought including repentance, reformation, and regeneration appear throughout. It will take about 20 minutes to read Joel, but make sure you allocate your time and effort in a prayerful way. You will be surprised at how helpful and fulfilling this book can be.

(By Rev. Chris Skinner, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Amos
Amos lived and worked around the period of 790-750 BC. He was called by the Lord to go to the Northern Kingdom of Israel although he lived in the southern kingdom at Tekoa. He had no formal education - only a burning desire to serve the Lord. Coming from a different part of the country, he was able to look at the problems he witnessed more objectively.

The book itself has 9 chapters, most of which outline the transgressions of the Israelites in prophecies, sermons, and visions. Very expressive examples are given of the state of the people and the way the Lord worked with them. Locusts and a plumb line appear in Amos 7, and in the first two chapters a litany of problems from the time are shown.

Amos could see the evil that prevailed due to spiritual degradation and idolatry. The message of the book is that of repentance - turning away from wickedness and turning to the Lord.

Amos 1 and 2 list places where evil is rampant. If you look at the Hebrew meaning of the names of each place, it is evident that the qualities these towns represent are only adhered to superficially. The people are focused on the external, more shallow aspects of faith because their whole lives are self-centred. I am sure we can reflect on the way our life is barren when we only think of ourselves and not of others.

At the very beginning of the book it says that the Lord roars. This means that the Lord was in great distress seeing the sorry state of His people. This is what led God to call on Amos, an uneducated man. It is an example to us that we do not necessarily have to be smartest or most credentialed to serve the Lord. The only requirements are commitment, love of God and willingness to serve.

Towards the end of the last Chapter the mood changes one of despair to hope. It discusses the eminent “Day of the Lord” to come and the changes that will bring. In our lives we have visions and aspirations. If we only think of our needs and not others, then these visions will struggle to come to fruition.

The last few verses look at the mountains and hills flowing with wine and land planted with what is provided from the Lord. These are images of what we stand to gain if evil is sifted out and we bring love and truth together into acts of use. If the seeds of our life are planted in the land given by the Lord, then it will be stable, fruitful and satisfying.

We should reflect on how much we look at life only from our own perspective. We need to see that the truth coming from the Lord can and will change us for the better.

(By Rev. Chris Skinner, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Obadiah
By the clergy of the New Church in Australia, New Christian Bible Study Staff

The little book of Obadiah, just a single chapter, targets one of ancient Israel's enemies, Edom, whose people gloated gleefully when Judah fell and Jerusalem was ransacked by the Babylonians in 586 BC. Edom and Judah were not allies. For much of their histories Edom had been a player on the international scene. So when its nemesis - Judah - was broken by the Babylonians, the Edomites couldn't help themselves from relishing in the defeat.

But how is the shortest book in the Bible relevant to us today?
Obadiah is one of the twelve “minor prophets”. In each of these twelve little books a common evil among the Israelites is pointed out. And, in us, those same evils are something we need to deal with before the Lord can become a part of our lives.

The truth is there is an “Edom” in each of us, a strong inclination to contempt and superiority over others which seeks to come out — especially when others are weakened or brought low for one reason or another.

Australians have a bit of a reputation for cutting down “tall poppies”, and enjoying the victim's humiliation and discomfort.

Clearly, humility and compassion is the far worthier alternative to gloating.

(By Rev. Ian Arnold, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Jonah
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Let's recount the story of Jonah briefly. He is commissioned to travel to Nineveh to spread the message of the Lord. Instead, Jonah runs the other way and buys a ticket to sail to Tarshish. A storm besieges his ship, and Jonah is blamed for the poor conditions and the others throw him into the sea. A fish swallows up and rescues Jonah, and when Jonah returns to dry land he finally obeys the Lord. He preached about the coming destruction of Nineveh, but Jonah becomes angry when this doesn't end up happening.

The Lord's response to Jonah's anger is interesting. He prepares a gourd that springs up “overnight” (Jonah 4:10) to provide Jonah with shade from the heat of the sun. The gourd soon dies, leaving Jonah once again without shade. This, it seems, was worse than not having had any shade in the first place. The Lord makes His point one more time: the prophecy uttered through Jonah was not intended to reveal the great glory or power of God, but to secure the repentance and salvation of His lost children.

Personally, Jonah teaches me about the folly of ”righteous anger”. Too often I point fingers or lash out, thinking I am justified in doing so only to discover there was something I missed. Even if I am “right”, am I supposed to sit back and wait for the “I told you so” moment? No! Of course not! This smacks of unforgivness, and by indulging in such things I drive a wedge between myself and those I love and I separate myself from God.

(By Rev. David A. Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Micah
Micah was a prophet of the 8th century BC - around the same time as Isaiah. He was born about 40 kilometers from Jerusalem in Moresheth, and his name means “who is like Jehovah".
While Isaiah was from the upper class, Micah came from a peasant farming background. This goes to show that the Lord uses those who he considers best fit for a particular task no matter who they are. As with most of the prophets, Micah speaks about the issues of the day as he tries to lead people back to God.

As has been said many times when looking at the prophets, they were used by the Lord at a time when Israel had fallen into idolatry and other vices. Micah, like the others, reminded Israel of God's covenant.

The seven chapters of Micah alter between warnings of judgement followed by glimmers of hope. This message of doom and gloom is particularly apparent in Micah 1-3.

The Word of God has a number of levels. It is a commentary on the times in which it is written, but it is also about God's love and our own spiritual path. Just as the Jews had turned to idolatry and selfishness, we too fall prey to temptations of the material world and our personal desires.

We see how people are led away from God in Micah 1-3. In Micah 4, we see a complete contrast where it talks about the mountain of the Lord's house being established. This image represents the love and truth God places in our mind.

Micah 6 talks about the covenant being breached by the people of Israel. In response to this, the Lord shows them how to renew the covenant in Micah 6:8: “what does the Lord require of you but to do justly, love mercy and walk humbly with your God”. All of this conveys a wonderful picture of God never leaving us. The last three verses of the book bring us back to the love and compassion of God. In many ways, this book shows us how God is always there to bring us back and lead us forward.

Each generation faces similar problems. If the covenant of God is kept, then the maladies that ail the world fade away. God is always trying to draw near to us and establish His kingdom here on earth.

(By Rev. Chris Skinner, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Nahum
By the clergy of the New Church in Australia, New Christian Bible Study Staff

We can never really understand the Bible unless we recognize that its contents reflect what we experience internally. Beneath the surface, the books of the Bible are focused on the spiritual struggles we deal with as we go about our lives.

Most people readily accept this when it comes to the story of Moses leading the ancient people of Israel out from slavery. The progress and setbacks the Israelites face mirror our own internal battles.
Ancient Israel's enemies symbolize things that attack, weaken, and imprison goodness from the Lord in our lives. Some of those enemies are fearsome, like the Assyrians and the Babylonians. They are rich, powerful, and ruthless.

Think for a moment: what are the most intimidating 'enemies' to our spiritual well-being? What things do the most damage? Babylon has long been recognized as a symbol of power and self-aggrandisement. But what about the Assyrians?
The Assyrians threatened the Israelites for more than a century. They conquered the northern kingdom of Israel in 721 BC and then stayed, threatening the southern kingdom of Judea afterwards.

What do the Assyrians symbolize in our own lives? On one famous occasion, the Assyrians showed themselves to be adept talkers and persuaders. (See 2 Kings 18)
There are those forces and influences that try to talk and persuade us, for example, that sin is fine if it remains undiscovered, or that the Ten Commandments don't matter in this day and age. If we can see this for what it is, we can recognize that such influence is capable of inflicting enormous spiritual damage on us.

Read this little, three-chapter prophecy with this in mind. It is not people the Lord pits Himself against, but those very things which have the potential to devastate us spiritually.

(By Rev. Ian Arnold, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Habakkuk
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Like the other minor prophets, Habakkuk is easily glossed over in favour of the longer books of Isaiah, Jeremiah & Ezekiel. This is unfortunate. One of the advantages of this collection of shorter books is their brevity - one can easily gain a full appreciation of the prophet's message and even read the entire book in one sitting.

Habakkuk's prophecy contains a conversation with God. Like his contemporary Jeremiah, Habakkuk complains to the Lord about the circumstances he faces. The third and final chapter contains a psalm-like prayer that the Lord will redeem His people once more. It is right at the end of the book that we find the words: “The Lord God is my strength; He will make my feet like deer's feet, And He will make me walk on my high hills.” (Habakkuk 3:19)
The central concern of the prophet is the evil he sees around him. Violence and injustice are found everywhere. Those who try to live honest lives are thwarted by the wicked. Habakkuk turns to the Lord and asks why He does not stop the suffering. The Lord answers Habakkuk with a promise to punish the wicked nation.

But I get the feeling that the cure is worse than the complaint - the Babylonians come and conquer Israel! Habakkuk is hardly comforted by this. In fact, he questions the Lord again.

In the prophet's own time, we can see the Babylonian empire invading Judah and the surrounding region. The nations who attacked and invaded Israel and Judah represented the evils which had already invaded the minds of the people (Arcana Coelestia 10481; Apocalypse Explained 817).
I wonder whether the same principle applies to the modern world. Habakkuk is certainly not alone in comparing the hostile nations of the time to the evils of his own people. His writing proclaims judgement upon every form of evil - those found outside the nation, and those found within it. We seem to lack this balance in our world. We are very good at proclaiming justice when our nation or its allies are wronged. But are we as aware of evils we cause and participate in ourselves?
Finally, however bad the circumstances around us may be, there is always a cause for hope. I find that uplifting and consoling when I consider my own poor record in regard to the virtues of love and forgiveness. I may have many reasons to give up, but the Lord calls us not to despair but to hope.

(By Rev. David A. Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Zephaniah
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Zephaniah is a small book. It is the ninth book of the minor prophets and is considered unoriginal, as it quotes images and phrases from the better known prophets with whom he was a contemporary.

It is thought that Zephaniah was descended from Hezekiah, king of Judah (see 2 Kings 18-20). Hezekiah is mentioned in the genealogy given in the opening verse possibly to add weight to the prophet's words, and the book is said to demonstrate a knowledge of the prevailing political scene and conventions of the court.

The prophecy addresses the Kingdom of Judah in the reign of Josiah (640-609 BC, see 2 Kings 22,23), one of the few good kings of Judah. Given this, it seems strange that the prophecy is one of judgement. Perhaps it was written before Josiah's reforms or before the discovery of the book of the law in the temple. The story, as it is told in the second book of kings, certainly makes it clear that the threat of destruction is only postponed and not averted.

Given its brevity, the book is easy to read in a single sitting, and the lessons it contains are important for gaining an appreciation of the Bible as a whole. Consider the second verse of chapter one: _“'I will sweep away everything from the face of the earth,' declares the LORD.”_ (Zephaniah 1:2) This outlandish statement is impossible to take literally. It points to the fact that much of this sort of language in Scripture should not be solely examined in the literal sense of the word.

“When a person has become regenerate he is no longer called the earth but the ground [or 'land'], the reason being that celestial seeds have been planted within him. Various other statements in the Word compare him to the ground and actually call him the ground. It is the external man, that is, his affection and memory, in which the seeds of good and truth are planted, … and when these are seemingly present no longer, he is in that case an external, that is, a bodily-minded person.” (Arcana Coelestia 268)
It's interesting, then, that Zephaniah speaks of the destruction of the earth and land. It suggests that the subject of the book hits on the far-reaching consequences of spiritual degradation - that we see the destruction of all security, comfort and hope as we recede from the love and worship of the Lord. In spite of this, the Lord Himself protects what is valuable to Him and ultimately restores it when we ourselves see the depravity we have sunk to and rise out of it.

(By Rev. David A. Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Haggai
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Haggai is all about hope and encouragement. It's one of the shortest books in the Bible, yet relevant and full of easy-to-see teaching. It's about a time when people had lost their connection with God and were struggling to rediscover it. Haggai (whose name means “festive”) tells them to hang in there.

Haggai was direct in saying that the people had only themselves to blame for the slow rebuilding of the temple. The Israelites were easily distracted, looking out for their own comfort and interests.

Why was the temple so important for the people of ancient Israel? Because it symbolized God's presence with them. With the first temple destroyed, they had lost their connection with God. Now they were trying to recover it.

There are times when we lose our connection to God. Negative, self-seeking forces destroy the Temple and take us captive. But the Lord calls us to rebuild and recover what has been lost. In the midst of our worst moments, He is already focusing on our spiritual revival.

There is a bigger picture here, too. Yes, this is about the presence of the Lord in our lives, but it is also about the presence of the Lord in the world and humanity's connection with Him.

This describes the world's spiritual state prior to the birth of Jesus Christ. Mankind's rich connection with God had been brought down and shattered. But after His birth, the Lord established a new and more glorious connection with the human race.

Do you remember what the name Haggai means? It means 'festival'. It can also mean 'feast of the Lord' or 'joy to the Lord'. In Haggai we have the promise of this new communing with the Lord; a feast or festival of good things.

As part of your walk with the Lord, find this little prophecy in your Bible and read it. Ten minutes is enough. Let yourself be caught up in the spiritual festivities it so beautifully, encouragingly, and reassuringly talks about.

(By Rev. Ian Arnold, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Zechariah
By the clergy of the New Church in Australia, New Christian Bible Study Staff

Reading the prophecy of Zechariah, I am struck by its many connections to other parts of scripture. If you are familiar with the Book of Revelation, you will notice similarities with some of the visions recorded by John on Patmos
    • The horsemen (Zechariah 1:8-11) and chariots (Revelation 6:1-8)
    • Horns (Zechariah 1:18)
    • The man with a measuring line (Zechariah 2:1, Revelation 21:17)
    • The woman in a basket (Zechariah 5:5-11) who is identified with Babylon in the land of Shinar as is the woman on the beast in Revelation 17
Then there are well known parallels to the gospels. Matthew is fond of quoting from the Old Testament to tell us who Jesus is and the significance of His life.

There are other connections with books of the Old Testament too, and these are particularly useful for setting Zechariah in its historical context. We find Darius (Zechariah 1:1) the ruler of Babylon who is also referenced in Daniel, Haggai, Ezra, and Nehemiah. Joshua the high priest plays a significant part in Haggai's prophecy alongside Zerubbabel. From all this we learn that Zechariah wrote when the people of Judah returned to Israel from Babylon.

If I were to choose one message from Zechariah, it would be the prophet's recollection of the punishment for past sins followed by the promise of rebirth. Judgement is prominent as well so that good may be separated and saved from evil. It is a hopeful picture: each of us must deal with the consequences of past mistakes, but at every step of the way there is a chance to turn the corner and right our wrongs. This short book reminds us of this opportunity.

(By Rev. David A. Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

=== Introduction to Malachi
The last book in the Old Testament is the prophecy of Malachi. It is relatively short (only four chapters), but important nevertheless. The Hebrew word, “Malachi” means “my messenger”.
It is thought that Malachi was the last book written in the Old Testament. It is set in the time after the end of the Babylonian captivity when the people of Israel had returned to their land with hopes of reestablishing their nation with its government and religious institutions, but they were never able to reclaim the glory of former days.

The book clearly anticipates the birth of Jesus Christ:
“Behold, I send My messenger, And he will prepare the way before Me. And the Lord, whom you seek, Will suddenly come to His temple, Even the Messenger of the covenant, In whom you delight. Behold, He is coming,” Says the LORD of hosts. (Malachi 3:1; see also Malachi 4:5)
Its position is quite appropriate as the last book of the Old Testament. As an interesting aside, have another look at Malachi 3:1 quoted above. You will notice the words “my messenger” (“Malachi”) in this context prophesize John the Baptist, whose task was to proclaim the coming of Jesus (Luke 3; John 1:6). John the Baptist's father was Zechariah (Luke 1:5), also the name of the second to last book of the Old Testament. Zechariah - John the Baptist (Malachi) - Jesus Christ: I think this progression is indicative of the anticipation associated with the Lord's coming.

One of the distinctive features of the book is a statement of the Lord followed by a question from the people. Some may think these questions are sarcastic, but I think they are genuine indications of the spiritual ignorance of the time. It seems that the Israelites of Malachi's time could not distinguish between good and evil - which introduces the other theme of the book - judgement, or how we differentiate good from evil.
(By Rev. David A. Moffat, of the New Church in Australia and the New Christian Bible Study staff and volunteers.)

