
== THE RAINBOW — Genesis 9:1-17

The review of the temptation by the serpent leads directly into the story of the decline of the Most Ancient Church and the necessity of the Lord's stepping in to save the remnant of good people from destruction. The story of the ark and the flood can be told briefly with the emphasis this time on the Lord's new promise and on the rainbow as the token of it.

=== Doctrinal Points

The will and the understanding in man.

The doctrine of reformation and regeneration.

The idea of successive dispensations as the basis of history. 

The Ancient Word.

=== Notes for Parents

Often when we are driving through new country, we come to a fork in the road. A sign—post tells us plainly which way we ought to go. If we obey it, we know we shall reach our destination. The other fork is not marked but it seems to be going in about the same direction and looks like a more pleasant road, and we take a chance; we think, "It may take us a little out of the way but it will certainly get us to the same place in time." So we go off on the wrong fork and it swings gradually away from the right road and takes us farther and farther astray. How often in our own personal lives we take this kind of chance! The Lord has marked the right road for us plainly, but we think we know better. And one wrong step leads to another. "Because wide is the gate, and broad is the way, that leadeth to destruction, and many there be which go in thereat." (Matthew 7:13)

The first people, after they listened to the serpent and chose to follow their own judgment, continued on the downward path until they had gone so far from the Lord's way that their evil passions and false ideas actually destroyed them, just as they destroy some people today. This destruction is pictured for us in the Bible story of the flood.

But there are always some who stand up in the face of temptation and refuse to follow the crowd. These good people are pictured by Noah. By obeying the Lord they are enabled to ride out the storm and begin a new and better life.

When we have had a heavy storm and the sun suddenly breaks through the clouds, we see against the darkest part of the sky a beautiful arch of colors — a rainbow. It is the same — if we are of those who try to obey the Lord — when we have passed successfully through a severe temptation. He is able to light up for us the bits of truth from His Word which we have in our minds and make them suddenly beautiful with new meaning. What a perfect symbol is the rainbow of the Lord's power to protect and bless us no matter how dark life may seem!

=== Primary

Some children may never have seen a rainbow; so the teacher may have to explain what it is and when it is usually seen. The children can be encouraged to watch for one and to think of it as a sign of the Lord's care over us. Stress the fact that the Lord takes care of us if we are good, even when life seems dark. Even the Primary children can get the idea that the sun in this world is like the Lord in our souls.

You remember how the first people disobeyed the Lord and let the serpent persuade them to eat the fruit of the tree of knowledge of good and evil. Then they had to leave the beautiful Garden of Eden and go out and earn their living by hard labor.

You know that when one child does wrong, he is very likely to lead other children who are with him to do wrong, too. So the first people, once they had started to disobey the Lord, became worse and worse. Finally most of them became so bad that the Lord could not let them live any longer. They were destroyed in a great flood.

But there were a few good people left. Noah and his family were told by the Lord how to save themselves by building a boat, called an "ark," and gathering into it a pair of every kind of bird and animal that had been created. The great rain which caused the flood lasted forty days and forty nights, and the waters rose until they covered the tops of the mountains; but the ark rode safely on top of the water. When the rain stopped and the waters began to go down, the ark rested on top of a mountain called Ararat.

When the earth was dry again, Noah and his family and all the animals came out of the ark, and a new race of people began on the earth. Did your mother ever show you something very fine and say, "See, I am going to put this up on the mantel where you can see it, and if you are good all day, you shall have it before you go to bed"? She made an agreement with you, and the thing she put on the mantel was a sign or token to you that she would keep her part of the agreement if you would keep yours. Another word for agreement is "covenant." Now let us read our story for today. [Read Genesis 9:8-17.]

Did you ever see a rainbow? Sometimes when it has been raining and the clouds are very black, the sun comes out suddenly and a beautiful bow of bright colors appears against the dark clouds. Whenever you see one, remember that it is a sign from the Lord that no matter how dark things look, the sun is still there and ready to shine again, and the Lord is taking care of you. If you are good, no trouble will last very long.

=== Junior

See how much the children already know of the story of Noah and the flood and fill in any gaps. The Juniors are old enough to be interested in the history of mankind, and it is a good thing to get into their minds the thought that man was not created evil or even a savage, but by his own selfish choice declined spiritually until the Lord had to come into the world to save the human race from destroying itself. In connection with the rainbow, if possible, show the children by means of a prism how the white light is broken up into its colors.

In the story of the Garden of Eden, by what names are the first men and women called?

What two special trees were in the garden? 

What were Adam and Eve told not to do?

Who tempted them to disobey?

What was their punishment?

When we disobey, our disobedience often leads us into doing other wrong things, and it is likely to get other people into trouble too. After the first people began to think they knew better than the Lord what they should do, they grew worse and worse. Each generation became more selfish and evil until they could not be allowed to live any longer. Their evils destroyed them. This is described in the Bible by the story of the flood. In this story Noah and his family picture the few good people who had resisted temptation and so could be saved. You are all familiar with the story of the flood. Let us see how accurately we remember it. If you do not know the answers, you may look up the Bible verses.

Who went into the ark with Noah? (Genesis 7:7)

What else did Noah take into the ark? (Genesis 7:8-9)

How long did the rain last? (Genesis 7:12)

When the flood abated, where did the ark rest? (Genesis 8:4)

The word Ararat means "high land." This is why the mountain in the story is given that name. In the previous lesson we had the story of how Noah sent out first a raven and then a dove to see if the waters were dried up from off the earth. Then, when he and his family came out of the ark, the first thing he did was to build an altar and worship the Lord. An altar is a symbol of worship; so in our churches we keep a copy of the Word on the altar. In the Bible people often built an altar to the Lord when they were grateful for something. We can build an altar in our minds by remembering always to thank the Lord for our blessings.

Now comes our lesson for today.

What did the Lord promise Noah?

What sign did He give?

When do we usually see a rainbow?

Sometimes, too, we see a rainbow in the spray of a fountain. A rainbow is formed when the sunlight strikes drops of water and is reflected back into our eyes. The white light is broken up into beautiful colors. A prism does the same thing.

You have heard that water is a symbol or picture of truth. And light is also a symbol of truth. That is why, when we suddenly understand something, we say, "I see!" Every verse from the Bible which you store away in your mind is like a drop of water, and when the Lord sees that you need to understand it, the light seems to shine into it suddenly and bring out all the beautiful things in it like the colors in the rainbow.

Of what was the rainbow to be a sign?

Just as the rainbow usually appears against the background of a dark cloud, so it is in times of trouble and temptation that we most need truth from the Lord and are most likely to ask Him for help. That is why the rainbow is the sign of the Lord's nearness to us whenever we need Him. The Lord's promise meant also that He would never again allow the human race to reach such a state of wickedness that it would be destroyed. It almost reached this state once in the course of history and then the Lord Himself came into the world and showed men the way back to safety.

=== Intermediate

The doctrine of the different churches which have been on the earth should be introduced at this age, and this lesson of the flood and the sign of the rainbow makes the best possible opportunity. Stress our need of learning the truth and making ourselves obey it, and the meaning of the rainbow with reference to our knowledge of the Word.

The story of Noah and the flood is a picture of the end of the Most Ancient Church — the first church which existed on the earth — and the beginning of the second or Ancient Church. It is also a picture of a change which takes place very early in our lives. The people of the Most Ancient Church were as innocent and trustful as little babies are, although in some ways they were much wiser than we are today because they knew that the things of nature were important only as they teach us of heavenly things. They talked with spirits and angels, and their thoughts and actions came from their hearts. They could not even think anything which they did not will. We know that a baby always shows his feelings immediately and that his little life is governed by them.

But we know that it is not long before a little child learns that what he wants is not always right, and so his mind begins to judge his feelings and to control them. This helps us to see what the change was which the Lord had to make in mankind after they began to want to go their own way instead of His. For people who had to think and do just what their hearts wanted could not be "taught better" after their hearts became bad. Their thoughts and actions became bad, too, and in the end they destroyed themselves. You may hear it said today of someone who is letting bad habits get control of him that he is "going to destruction." The flood is the Bible picture of this destruction of the people of the Most Ancient Church.

Before all the people had reached this point, however, the Lord made a change in the very nature of the few who still wanted to be good — the "remnant" — who are pictured in the story by Noah and his family. He separated their understanding from their will so that they could think the truth even when they did not want to live according to it. All people since that time have been of this nature. So they could be taught what was right and could make themselves do it until it became a habit and they learned again to like to do it. We know that this is the way we all learn. We are selfish to begin with, just as the people at the end of the Most Ancient Church had come to be, but we can learn what the Lord wants and be shown that it is best for us, and make ourselves obey Him until we come to love to obey Him. This is the process of "reformation and regeneration" about which we shall speak a good deal as our study goes on.

The story of Noah's building the ark, taking his family and all the animals into it, and riding out the flood is a picture of how the Lord protected the good remnant of the people while this great change was taking place in them. Perhaps you remember that the rain lasted forty days and forty nights. All numbers in the Word have a correspondence, and the number forty corresponds to temptation. In our own lives the flood pictures the time when the Lord is showing us by means of our own selfishness that it is better to do right than wrong, so that we may develop the habit of doing right. That is the way we all learn in the beginning: We try to do what our parents say is right, not because we want to, but because we know we shall be punished for doing wrong and rewarded for doing right.

It takes a long time for good habits to become so established in us that our hearts can be changed. Even after the rain stopped, it was a hundred and fifty days before the flood began to subside and several months after that before Noah could come out of the ark and move about freely and reestablish his life on the earth.

Read Genesis 8:20-22. An altar is always the symbol of worship, and Noah's building the altar pictures the establishment of a new church on the earth which is called the Ancient Church. The people of the Most Ancient Church had not had a Bible. The Lord had instructed them by an inner way, through their innocent and good hearts and by visions and dreams. Near the end of that church good people, realizing that selfishness was closing this inner door, had begun to write down the teachings that had been received in this way so that they should not be lost. So when the Ancient Church was established, it had a set of sacred writings — the Ancient Word. This has been lost, but we know something of what it was like because the first seven chapters of our Bible were drawn from it. It was written in the symbol language in which the people of that time spoke because they understood the spiritual correspondence of everything in nature.

The Lord made a new covenant with this new church. A covenant is an agreement. In the letter the Lord promised protection to all who would obey Him. He promised that never again would He allow a time to come when people would have to be destroyed as the people of the Most Ancient Church had been. The sign or token of this covenant was the rainbow. This does not mean that there had never been a rainbow in the natural world before, but that the Lord showed them that the rainbow had a special meaning for them. The rainbow is very beautiful. It is caused by the breaking up of the sun's rays into their colors when the rays are reflected from the raindrops. This is a perfect picture of the new state in which men were to live from that time on. As we have seen, in the time of the people called Adam — the Golden Age or Most Ancient Church — the Lord spoke directly to people in their hearts. This was like the direct light of the sun. But in the time of the people called Noah — the Silver Age or Ancient Church - men had to learn truths from the Word — the drops of water from heaven — and then the Lord could enlighten their minds to see how these truths were to be used in their daily lives; the different applications of the truth are like the beautiful colors of the rainbow. So we today learn stories and verses from the Word and the Lord enlightens us to see their meaning and how they can guide and help us.

The rainbow, which comes against the dark clouds as a storm passes away, is a beautiful symbol of the Lord's truth leading us through temptation and trouble into happiness and peace.

=== Basic Correspondences

forty = temptation
the flood = falsities destroying the life
the rainbow = truths from the Word in our mind used by the Lord to enlighten us

=== Senior

The important lesson for the Seniors is the way in which the Lord leads us to goodness by making use of our own states, and the fact that we never know truth instinctively but have to learn it from the Word.

We noted previously that once the people of the Most Ancient Church began to look to themselves and their natural senses for guidance, they declined steadily in spirituality. They became possessed by their passions and by the falsities associated with them, which grew until they swallowed up all truly human life and every spiritual aspiration. This is pictured in the Bible by the flood which destroyed all living things and covered even the mountain tops. You will remember that the preservation of Noah and his family in the ark pictures the way in which the Lord saved the "remnant" — the few people who still recognized the Lord and wished to obey Him — during this time of the final devastation of the Most Ancient Church. In our own lives it pictures the way in which the Lord, as we come out of babyhood, at first leads us by means of our very selfishness, by showing us that we get along better when we obey our parents. So we form good habits and eventually can come to love doing right.

In the Bible story the drying up of the ground is the subsiding of the monstrous falsities of the past age. When this was accomplished the good remnant could be free in the earth again. We may perhaps think of an analogy to this in the dissipation of the idea of the "super—race" in middle Europe after the close of the Second World War. Noah's first act was to build an altar to the Lord and bring sacrifices. This is the first mention in the Word of "burnt offerings" of animals, but Swedenborg tells us that the people called Noah merely presented the animals at the altar and did not kill them. They knew that to present the animals before the fire on the altar meant making their affections sacred to the service of the Lord. In later times, when knowledge of this meaning had been lost, people began to burn the animals themselves, and the Lord permitted it in order to keep them from sacrificing their children as the idolatrous nations did.

Then in the Bible story the Lord makes a covenant with Noah, promising that He will protect men henceforth from being overwhelmed by their own evils and falsities, and He gives the rainbow as a sign.

The rainbow, we know, is caused by the breaking up of the white light from the sun as it is reflected from minute drops of water. This is a perfect picture of man's new state. The light from the Lord no longer shone directly into his affections as it had in the time of Adam, but shone into the truths from the Word which he had received in his mind, and from these enlightened him according to his particular need. This application of the truth to particular states and needs is pictured in the beautiful colors, all harmonious. The rainbow always appears against the dark clouds when the storm is almost over; so it is a symbol of the Lord's protecting and enlightening presence with us in times of trouble and temptation. The Lord is actually nearer to us when we are in temptation than at any other time.

We can understand this story if we think how the verses which we have learned from the Word are brought up in our minds just when we most need them, and filled with new meaning. The more raindrops of truth we have and the darker the background of trouble or temptation, the brighter and more beautiful the rainbow.

The people pictured by Adam formed what we call the Most Ancient Church, which was an "affectional" or "celestial" church, and so came down in mythology as the "Golden Age" because among the metals gold is the symbol of love. The people called Noah formed the Ancient Church, an intellectual or "spiritual" church, termed the "Silver Age" in mythology because silver is the symbol of truth. Mythology is not an invention of the peoples of historic times to account for their origins, but old traditions handed down from the early people who talked in the language of correspondence.

=== Adult

Two main lines of discussion may be pursued: the significance of the philosophy of history found in the Arcana, and the difference between the people of the Most Ancient Church and all later people — including ourselves. We have a strong tendency to imagine that individually — if we learn the truths of the church in childhood — we arrive at a point when we no longer need to think about truth but somehow do good instinctively. There is nothing in the writings of the New Church to support such an idea.

The New Church teaching with regard to history is like a powerful searchlight bringing into clear view an area which has previously been dark and uncertain. History as we study it in school is something which has been compiled from material remains of past ages and from man-made documents, both sources necessarily fragmentary. Studied in this way, history is inevitably regarded as a process of human achievement — man's gradual conquest of his environment and the dealings of man with man. God has no part in it except as men are thought to have developed one religious concept after another and in spreading their ideas to have affected external events. But the Word teaches us that "In the beginning God created the heaven and the earth" and that God's revelation of Himself to man has governed and directed all history. And the writings of Swedenborg teach us that in every age the church has been the "heart and lungs" of the social body, the center from which the life and thought of the age has sprung.

The character of the ancient people, as these writings reveal it to us in the interpretation of the early chapters of Genesis, is very different from the theories concerning it which men have formed from the study of material remains, and is much closer to the stories of the Golden and Silver Ages handed down through mythology. Our lesson today covers the period of the flood — the transition from the Most Ancient to the Ancient Church. In @AC 605 we read: "The subject now treated of is the formation of a new church, which is called 'Noah'; and its formation is described by the ark into which living things of every kind were received. But as is wont to be the case, before that new church could arise it was necessary that the man of the church should suffer many temptations, which are described by the lifting up of the ark, its fluctuation, and its delay upon the waters of the flood. And finally, that he became a true spiritual man and was set free, is described by the cessation of the waters, and the many things that follow."

Here we have clearly stated the way in which the Lord raised up a new church — the Ancient Church — from the "remnant" who were such that they could be regenerated. We are familiar with the thought that Noah and his sons picture this remnant. The change was not sudden. It took place gradually over a long period of time. The events described in chapter 7 of Genesis treat in their internal sense of the preservation of the remnant and their preparation for the new type of life to be developed, and chapter 8 treats of the development of the new church in them.

Finally in our chapter for today the state of the regenerate man of that church is described, and this is summed up in the "token" of the new covenant, the rainbow. We should note that this covenant was to be a perpetual one. That is, although the Ancient Church was to decline and perish and its knowledges to be lost, the character of man as to his means of regeneration would not again be changed. The human race on earth will not go back to the state of the man of the Most Ancient Church, although the regeneration of any individual may, if he is faithful, progress to the celestial degree. We are told that since the period of the flood no one has been added to the heavens of the Most Ancient Church, and the hells of that church have been closed. The succeeding churches have their celestial heavens but they are not reached except by the process described by the sign of the rainbow. Each of us is born natural and must learn truths and become spiritual before he can become celestial.

Swedenborg tells us (@AC 1043) that the cloud pictures the obscurity in which our minds are as a result of the evil in our natural wills. But when we introduce truths from the Word into our minds and try to live according to them, light from the Lord shining in those truths — like the rays of the sun reflected in the drops of water against the dark cloud — can so modify our darkness as to produce beautiful appearances of truth in our minds, like the colors of the rainbow, teaching us that the Lord is always present with His love and protection however dark our surroundings may seem, and that if we are faithful to the truth, He will keep us safe and finally remove our temptations and "create in us a clean heart." This is the covenant which He makes with all the human race. Because the will with which we are born is evil, we cannot see truth directly by perception as the people of the Most Ancient Church did, but truth can be reflected from the knowledge of the letter of the Word which we have in our minds and so "reform" us that the Lord can come into our hearts and give us a new will. This is the method of regeneration with all people since the flood, and the rainbow is consequently the correspondential sign of regeneration with the "spiritual" as distinguished from the "celestial" type of man.

Swedenborg says (@AC 1042): "Spiritual angels, who have all been regenerated men of the spiritual church, when presented to sight as such in the other life, appear with as it were a rainbow about the head." He also tells us that the character of the rainbow is different with each, according to the particular way in which he has allowed the truth to modify the natural obscurity of his mind. The "white" light is broken up into colors by the absorption of some of its elements by darkness of one sort or another. All the colors of the rainbow are harmonious and all are present in the white beam. The particular content of our minds determines the colors which can be reflected there and which ones will be blotted out by persistent falsities. "Many are regenerated by the Lord in every dogma, and when they have been regenerated they do not receive any immediate revelation, but only what is insinuated into them through the Word and the preaching of the Word. But because they receive charity, the Lord works through charity upon their cloud, from which there springs light, as when the sun strikes a cloud, which then becomes more luminous and is variegated with colors. Thus also there arises in the cloud the likeness of a bow. The thinner the cloud, that is, the more numerous are the intermingled truths of faith of which it consists, the more beautiful is the bow. But the denser the cloud, that is, the fewer the truths of faith of which it consists, the less beautiful is the bow. Innocence adds much to its beauty, giving as it were a living brightness to the colors" (@AC 1043). This gives us one clear answer to the question often asked, "If people of all religions can be saved, why is one religion better than another?" We should all wish to have our cloud of falsities as thin as possible so that our characters may reflect more of the beautiful variations of the Lord's light. But we must remember that there can be no rainbow whatever if charity is not found in us. We must wish to serve the Lord and the neighbor instead of ourselves or we can have no enlightenment.

=== From the Writings of Swedenborg

@AC 1042: "I have set my bow in the cloud. This signifies the state of the regenerated spiritual man, which is like a rainbow. Anyone may wonder that the 'bow in the cloud,' or the rainbow, is taken in the Word for a token of the covenant, seeing that the rainbow is nothing but an appearance arising from the modification of the rays of sunlight in raindrops, and thus only something natural ... And that the 'bow in the cloud' represents regeneration, and signifies the state of the regenerated spiritual man, cannot be known to anyone unless it be given him to see and hence to know how the case is. Spiritual angels, who have all been regenerated men of the spiritual church, when presented to sight as such in the other life, appear with as it were a rainbow about the head. But the rainbows seen are in accordance with their state, and thus from them their quality is known in heaven and in the world of spirits. The reason that the appearance of a rainbow is seen is that their natural things corresponding to their spiritual present such an appearance. It is a modification of spiritual light from the Lord in their natural things. These angels are those who are said to be regenerated 'of water and the spirit,' but the celestial angels are said to be regenerated 'with fire.'"

=== Suggested Questions on the Lesson

Intermediate: What story teaches us about the people of the first church on earth? Eden

Intermediate: What was that church called? Most Ancient

Junior: How did evil come into the world? man's disobedience

Intermediate: What story tells about the saving of the good remnant? flood

Primary: How long did the flood last? almost a year (cf. 7:11, 8:13)

Primary: What was the first thing Noah did when he came out of the ark? built altar

Junior: What did the Lord promise? no more floods

Primary: What was the sign or token of this covenant? rainbow

Junior: How is a rainbow formed? sunlight on drops of water

Junior: When do we usually see one? end of storm

Intermediate. To what does water correspond? truth

Senior: To what do the drops of water in the cloud correspond? knowledges in mind

Intermediate: How did the Lord tell the Most Ancient people what was right? perception

Intermediate. How does He tell us? conscience

Senior: Why was the rainbow the sign of the new covenant made with Noah? to picture new state — light shines on truths in memory

