
<<<
---
== Sermon X. Judges 4:16-22 (Part 2)

"_But Barak pursued after the chariots and after the host unto Harosheth of the Gentiles: and all the host of Sisera fell upon the edge of the sword; and there was not a man left. +
Howbeit, Sisera fled away on his feet to the tent of Jael the wife of Heber the Kenite: for there was peace between Jabin the king of Hazor and the house of Heber the Kenite. +
And Jael went out to meet Sisera, and said unto him, Turn in, my lord, turn in to me; fear not. And when he had turned in unto her into the tent, she covered him with a mantle. +
And he said unto her, Give me, I pray thee, a little water to drink; for I am thirsty. And she opened a bottle of milk, and gave him drink, and covered him. +
Again he said unto her, Stand in the door of the tent, and it shall be, when any man doth come and inquire of thee, and say, Is there any man here? that thou shalt say, No. +
Then Jael Heber's wife took a nail of the tent, and took an hammer in her hand, and went softly unto him, and smote the nail into his temples, and fastened it into the ground: for he was fast asleep and weary. So he died. +
And behold, as Barak pursued Sisera, Jael came out to meet him, and said unto him, Come, and I will show thee the man whom thou seekest. And when he came into her tent, behold, Sisera lay dead, and the nail was in his temples._" (Judges 4:16-22)

In our previous discourse upon this extraordinary narrative, when we connected it with the exulting and laudatory comments upon it which follow in the song of Deborah and Barak recited in the next chapter, we chiefly confined ourselves to the endeavour to show how such narratives, terrible and even highly criminal as are the deeds related in them, yet by no means tend to invalidate, but rather to establish, the divine character of the book in which they are found, as being truly denominated the Word of God.

But to this end, some just knowledge must be possessed as to what the nature of the Word of God properly is, and the true design of the calling of the people of Israel; which was, among other reasons, in order that the Word of God, such as we have it, might be written among them. 

If, as we have seen, that people never constituted a real church, but only the representative of a church, and thus a substitute for a real church, during a period when no internal church could be raised up; 

and when the fulness of time had not arrived for the Lord's coming into the world to found the Christian church; 

and if they were made to represent the things and states relating to the church by the forms of their worship and by the circumstances of their history, for the instruction, when recorded in the Word of God, of the members of the church in all future ages, without being, themselves, interiorly grounded in the things which they thus represented; 

when, I say, these and other particulars relating to the Israelites, mentioned in our last, are known and understood, then it will be seen that no objection against the divinity of the Sacred Volume can be raised, from the circumstance, that some of the persons whose actions are related in it were far from being, in their individual character, holy or good men, and that some of their actions were, in themselves, of a criminal or flagitious nature. 

The approbation, whether expressed or implied, is not truly bestowed upon the individual person or deed, but upon the thing which was thus represented.

The individual himself might be a good man or a bad one, and his actions, as performed by him, might be morally right or morally wrong; and yet they might represent things of a most holy nature, or, when not absolutely holy, yet states of the church, and of its individual members in the course of their regenerative progress.

These alone are the things which appear in the spiritual sense of the Word, for the sake of including and conveying which, mainly, the letter is composed; and thus, though the Holy Word exists, in its spiritual sense, in heaven; yet, existing there only in its spiritual sense, nothing is there known about the persons and their actions mentioned in the letter.

Thought about these never enters the minds of the angels; consequently, it is impossible for them to be scandalized at finding wicked men or wicked deeds spoken of with seeming approbation in the Word of God; and it would be the same with its readers on earth, were they acquainted with the spiritual sense of the Word, and attended chiefly to this in its perusal.

So, also, the mention of such things in the Holy Word would be incapable of giving offence to any, if they knew and believed that it is for the sake of the spiritual sense alone, in such instances, that the letter is so constructed, even though they might not be sufficiently instructed and enlightened to see what the spiritual sense is.

What a happiness, brethren, ought we to esteem it, that, whether our information and intelligence in regard to the spiritual sense of the Holy Word be, more or less, in the knowledge which we all possess that it contains such a sense,

we are delivered from all occasions for entertaining doubts of its divine inspiration, and can never be shaken in our conviction of its essentially divine origin, by reading in it of such acts as that of Jael, with the applause bestowed upon them! 

We only conclude from such circumstances, that the narrative does, and must, contain a spiritual sense; and whether we are enabled to discern any part of that spiritual sense or not, the conviction that there is one, enables us to appropriate with more confiding certainty the instruction openly given in those passages, of which there are many, in which genuine truth is extant in the literal sense itself, and the valuable lessons conveyed on the surface of the pleasing, pathetic, and affecting narratives which in many parts occur.

Happy shall we be if we appropriate all that we can understand of the Scriptures, whether obvious in their letter or only to be seen in their spiritual sense, which tends to the establishment of our minds in true doctrine and instructs us how to conduct our life; and then, whether enabled to see much of their spiritual sense or little, they will perform for us their grand office, as justly stated by the Apostle, of making wise unto salvation.

However, at present we are to try, by such divine aids as are mercifully afforded us, if we can obtain some glimpse of the spiritual sense of the divine narrative before us, and of the encomiums [i.e. high praise -Ed.] bestowed on it in the obviously Divine song of Deborah and Barak.

We made some approaches towards this in our former discourse, in what we were enabled to ascertain, tending to throw light on the representation sustained by Jael, the actress in the tragedy, from the circumstance of her being of the family of the Kenites, and descended from Jethro the father-in-law of Moses.

Jethro, we have seen, was the author to Moses of a most important measure for the judging of the people, soon after they came out of Egypt; and at a later period, himself or his son, under the name of Hobab, was induced to remain with them by Moses, because, as Moses said to him on the occasion, he would be to them in the wilderness instead of eyes.

This evidently implies something from the Lord that guides man in his pilgrimage, and when beset with trials and difficulties, where his own understanding is insufficient, -- something that protects him, and leads him on in safety.

And as the family were not Israelites, but dwelt among the Israelites, in consequence of the connexion of their ancestor with Moses, yet always inhabiting their own tents, not residing in cities with the Israelites, but remaining, though in the midst of them, a distinct but friendly people; they, and by consequence Jael as one of them, seem to represent something that enters the mind by an immediate influx from the Lord, and operates for man's preservation and safety, without his having much or perhaps any consciousness of its operation.

It appears also to be something which operates and is present with those who do not belong to the church as well as with those who do, doing them good, so far as they are duly receptive of it, but, when they pervert and profane it, becoming the occasion of their destruction.

This, I think, may be concluded from its being said, that there was peace between Jabin the king of Hazor and the house of Heber the Kenite, whose wife Jael was; and we know that there was always peace between them and the Israelites, in whose land they dwelt as friends, -- not, like Jabin and Sisera and their Canaanites, as foes.

Sisera, we have seen on a former occasion, as Captain of the army of Jabin a Canaanitish prince, who had held Israel in bondage, and subjected them to cruel oppression for the space of twenty years, represents a ruling and primary false principle grounded in that species of evil of the external man which is always represented by the Canaanites in Scripture.

It is a principle which leads man to confide in his own strength, and, while guilty of the greatest evils, and seeking to subjugate and destroy, and make subservient to his purposes, all the genuine principles of truth and goodness constituent of the Church, represented by the Israelites, to flatter himself that the divine goodness and providence are on his side.

This is implied by Sisera's seeking refuge in the tent of Jael the wife of Heber the Kenite, and by Jael's putting on an appearance as if she favoured him according to all his wishes.

It would appear, too, that those who are grounded in such a false persuasion as Sisera represents, make no scruple to employ guile to accomplish their wicked ends.

This, indeed, is not explicitly stated in regard to Sisera, but it is involved in the guile practised towards him by Jael, who herein acted according to the law of retaliation, which was in force under the representative dispensations, and which, though prohibited by the Gospel to be made the rule of the conduct of individuals towards others, is the eternal rule of retribution according to which all are dealt with in the other world.

To represent this, Jael was led to act with guile towards Sisera, because those characters who are grounded in such a false doctrine or persuasion as Sisera, as the Captain of Jabin's host, represents, from such evil in the heart as is represented by him as being a Canaanite, habitually practise guile and deceit to accomplish their designs.

This also is in part represented by Sisera's being hidden by being covered with a mantle, and by his instructing Jael to watch against any man who should come to seek him, and to send him away by a lie.

Whatever might be Jael's individual state in acting as she did, her actions, without infringing on her freedom as to that state, were certainly so overruled as to take the form they did, to represent the operation of the law of retaliation in regard to such as are represented by Sisera at their final judgment in the other life.

All that Jael did, took the form it did, expressly for this purpose: to represent how the divine law of order called the law of retaliation eventually takes effect in regard to such as are represented by Sisera, and that, being recorded in the Word of God, it might serve for the warning of men, and the instruction on the subject of angels, for ever.

These observations may perhaps suffice to show, how it was that it is recorded that there was peace between Jabin and the house of Heber the Kenite, and how Jael was led to act with such treachery.

But we will notice a few more of the circumstances: Sisera, as soon as he was covered with a mantle and thought himself safe, said to Jael, "Give me I pray thee a little water to drink, for I am thirsty." This was, doubtless, a very natural request for a man to make, who had been in a great battle and had run a great way to save his life when he saw his army defeated; but it no doubt is recorded as representing something important and characteristic in the state of such persons as Sisera represents.

Its signification appears to be much the same as of what is related of the rich man in hell, tormented in the flame, (Luke 16), when he begged that Lazarus might be sent to dip his finger in water to cool his tongue; which, we are informed, expresses the desire of those in hell -- who are not dismissed thither until all truth has been taken away from them and they are left in mere falsities,-- to obtain truth for the purpose of falsifying it; the lust of doing which is meant by the flame in which he was tormented.

The same lust is signified by the thirst with which Sisera was tormented; and the water which he desired to drink, equally means truth that such as he represents might pervert and falsify.

The request of the rich man was refused, because on him judgment had been already passed; but the desire of Sisera was gratified, and in a superior manner to what he had asked, because his judgment was not yet performed.

Jael "opened a bottle of milk, and gave him drink." Milk denotes truth of a higher order than water, or even than wine; -- truth in fact of a celestial kind, or such as springs from and expresses the sentiments of, the most angelic love.

Such a truth, for example, is this: "That the Lord casts none into hell, but that his mercy and love are such as to desire to raise all to heaven." How would such as Sisera represents, treat this glorious truth? They would pervert and falsify it most awfully, by inferring from it, that, live as they may, they are sure of salvation. In fact, whatever truths respecting the Lord's divine love such characters are acquainted with, they are sure to pervert in their own favour.

If, as is the case with so many, they believe wrath to be a more powerful divine passion than love, and conclude that while the great bulk of the human race are objects of the wrath of God, only a very small number shall ever know his love, they are sure to monopolize all the love to themselves.

How few soever are they that shall be saved, themselves are infallibly of the number.

Such falsification of the truths relating to the Lord's divine love, is signified by Sisera's drinking the bottle of milk.

Jael's giving it to him represents that the Lord's divine love is really universal, is free to the acceptance of all, and that the truths it teaches would save even such as are here denoted, would they receive them without perversion, in a vital and practical manner; but Sisera's drinking it represents confirmation in such perversions through deliberately appropriated evil of life.

Sisera now says to Jael, "Stand in the door of the tent; and it shall be, when any man doth come and inquire of thee, and say, Is there any man here? that thou shalt say, No. 

This represents the desire and effort of those represented by Sisera, and the tendency of the false persuasion which he denotes in the sense abstracted from persons, to pervert even the good that comes immediately from the Lord, represented by Jael, to wring from it a false pretence calculated to screen from punishment the persons in question, and to conceal the nature of the false persuasion which forms the ruling principle of their understanding as derived from an evil will.

A man, in the Word of God, in a good sense, signifies the principle of intelligence, and in a bad sense, as here, self-derived intelligence.

To require then Jael to say that there was no man there, is so to pervert all good or charity, as to make it excuse the most destructive false persuasions originating in evil, by affirming that there is nothing in such persuasions of self derived intelligence; which would be the same as to say that they are harmless and good.

//<law of retaliation>
If those who desire this fail to accomplish it in others, the very desire when confirmed, effects it in themselves.

Whatever spiritual injury they thus desire to do to others, is sure to rebound upon themselves.

In this way is executed on them the law of retaliation.

Every truth they ever possessed is falsified, and every good adulterated, until at length the measure of their state is filled up, and they are divested of every principle of goodness and truth altogether.

They are immersed entirely in a merely natural state, represented by the deep sleep into which Sisera fell as soon as he had given this lesson of falsehood to Jael; and they regard themselves as in the full security which a person's spontaneously betaking himself to sleep also represents.

In a moment, they sink in total spiritual death.

Jael, Heber's wife -- the principle of good which they wished to pervert, and which they had perverted as to themselves, -- "took a nail of the tent, and took a hammer in her hand, and went softly unto him, and smote the nail into his temples, and fastened it into the ground; for he was asleep and weary. So he died."

A nail is the symbol of penetrating truth in ultimates, bringing convictions that cannot be resisted; a hammer in the hand is an emblem of great power; the temples, as inclosing that part of the brain which contains the intellectual powers, or the faculty of understanding in general, denote that faculty itself; to be fastened to the ground, is to be bound to the lowest corporeal plane and things, so as to be utterly incapable of any elevation of thought above them. To die is to perish as to all spiritual life.

Thus the import of the whole is: the influx of Divine Truth with power, in consequence of the effort of the parties represented by Sisera to pervert the good represented by Jael, Heber's wife, into the intellectual faculty in which all truth has been falsified and perverted; the effect of which is, the total destruction of the intellectual faculty as to the capacity of seeing any truth, the binding of it down to what is most grossly corporeal, and the utter privation in the party of all spiritual life for ever.

It is to be observed, that it is not the good itself which Jael represents which causes this catastrophe, as might be supposed from her being the performer of the literal action; for the good of the Lord's mercy and providence always tends to protection and salvation, and never to ruin and destruction; but it is the effort on the part of the wicked to make even this good subservient to their evil designs, and thus direfully to pervert it, which causes the total separation from heaven, and irrevocable binding to hell, which then immediately ensues.

Now as Jael signifies a principle of good immediately from the Lord, by the effort to pervert which, the destruction of the wicked is effected, and by which the protection and salvation of the good are secured, we may easily see why Jael is extolled so highly, -- why it is said, "Blessed shall Jael the wife of Heber be, blessed shall she be above women in the tent."

This is only an emphatic declaration, that nothing of man's salvation is from himself, but all of it from good immediately from the Lord; to whom, therefore, all the merit is due.

Something like this, I have no doubt, is the import, in the spiritual sense, of this divine narrative. Nothing here appears of any harsh or vindictive nature, or of any thing guileful and treacherous.

The Lord is willing to save all; but, as to them who would monopolize salvation to themselves without regard to the true divine means of obtaining it; who cherish false principles of faith grounded in the love of evil; who falsify divine truths to make them appear to favour their evils, and even endeavour to pervert the good of the Lord's love and mercy: evident it is that such must, in the other life, be divested of all the goodness and truth which they have falsified and perverted, and left to the living death of their own evils and falsities.

The effect of this also is the deliverance of the good whom they have infested with temptations, and endeavoured to destroy.

This is the law of divine order in regard to both these classes of persons; and this is what is meant by the awful imprecation [i.e. curse -Ed.] and solemn prayer with which the song of Deborah and Barak, after speaking of the death of Sisera, concludes: "_So let all thine enemies perish, O Lord: but let them that love him be as the sun when he goeth forth in his might_". This is not to be understood as a wish for the destruction even of the Lord's enemies, which means the enemies of all that is good and true; but it is a declaration of what must be the consequence of being of the number of such enemies, and never consenting to relinquish the enmity.

What can be the result of being an enemy of all that is good and true -- that is, of all that the Lord loves, and is, but the being divested of every thing good and true ourselves, and thus separated from all communion and conjunction with the Lord, and consequently, and of necessity, from all peace and happiness? Painful as is the thought, that there are many of our fellow-creatures of whom this is the fate, yet reason plainly sees, that, with all who persevere in such a course to the end of life, or of their day of probation, as our life in this world truly is, it is utterly impossible that it should be otherwise.

The declaration then, that such will, and must, assuredly be the fact, is all that is meant by the seeming imprecation, "So let all thine enemies perish, O Lord." The most ardent desire of the Lord is, that they would cease to be enemies, and so permit him to save them; but if they obstinately refuse, what can be done but to leave them to what they prefer? But if this, though obviously, in such case, unavoidable, is painful to contemplate, how delightful is the solemn prayer or benediction which is presented as the alternative: "Let them that love him be as the sun when he goeth forth in his might!" This is the declaration of a law of divine order in respect to such characters; and equally so, of the pure benevolence of the Divine Nature.

To those who love Him, the Love of the Lord can, and does, go forth in its native form, and is seen such as it is in its own intrinsic nature. He inmostly desires that all they who love him shall be as the sun when he goeth forth in his might. The sun is the grandest image and emblem in nature, of the Lord himself and his divine love. With what might, as is here expressed, does the sun go forth? Who, or what, shall stop him in his career? So glorious and certain is the blessed course of those, who truly love the Lord, -- the sun's divine prototype.

How ardent and pure should that love of the Lord be, which can claim the sun as its appropriate representation in nature! Yet as the sun rises gradually, and its light appears before it is seen itself, and, after it has risen, its full heat is not perceived until it approaches the meridian; so is it with him who is here spoken of as loving the Lord: his progress is gradual, although, where his love is genuine, it is sure.

The love of the Lord, we know, is the love of what the Lord is; and none can love what he is, without desiring, and striving, to become conformed to his will, and, as an imperfect image, assimilated to his nature; which, can only be accomplished in proportion as man keeps his commandments, in which his will is declared, and from which his nature may be inferred.

Let us, brethren, strive to do this; and then we shall assuredly realize the blessing, "Let them that love him be as the sun when he goeth forth in his might." Nothing shall prevent them from reaching the goal: rising to a station in his heavenly kingdom.




