 
<<<
---
=== Chapter XII. Judges 6:11-24.

"And there came an angel of the Lord, and sat under an oak which (was)
in Ophrah, that (pertained) unto Joash the Abi-ezrite. And his son Gideon threshed wheat by the wine press, to hide it from the Midianites. And the angel of the Lord appeared unto him, and said unto him, The Lord is with thee, thou mighty man of valour. And Gideon said unto him, O my lord, if the Lord be with us, why then is all this befallen us? and where (be) all his miracles which our fathers told us of, saying, Did not the Lord bring us up from Egypt? But now the Lord hath forsaken us, and delivered us into the hands of the Midianites. And the Lord looked upon him, and said, Go in this thy might, and thou shall save Israel from the hand of the Midianites: have not I sent thee? And he said unto Him, Oh, my Lord, wherewith shall I save Israel?
behold, my family is poor in Manasseh, and 1 am the least in my father's house. And the Lord said unto him, Surely I will be with thee, and thou shall smite the Midianites as one man, And he said unto Him, If now I have found grace in thy sight, then shew me a sign that thou talkest with me: depart not hence, I pray thee, until I come unto thee, and bring forth my present, and set it before thee. And He said, I will tarry till thou come again. And Gideon went in, and made ready a kid, and unleavened cakes of an ephah of flour: the flesh he put in a basket, and he put the broth in a pot, and brought it out unto Him under the oak, and presented if. And the angel of God said unto him, Take the flesh and the unleavened cakes, and lay them upon this rock, and pour out the broth. And he did so. Then the angel of the Lord put forth the end of the staff that was in His hand, and touched the flesh and the unleavened cakes: and there arose up fire out of the rock, and consumed the flesh and the unleavened cakes. Then the angel of the Lord departed out of his sight. And when Gideon perceived that He was an angel of the Lord, Gideon said, Alas, O Lord God! for because I have seen an angel of the Lord face to face. And the Lord said unto him, Peace be unto thee: fear not: thou shall not die. Then Gideon built an altar there unto the Lord, and called it Jehovah-shalom: unto this day it is in Ophrah of the Abi-ezrite."

In our last discourse we commenced the subject of the afflictions which the Israelites suffered in consequence of the inroads and tyranny of the Midianites: which we have seen describe, when understood in the spiritual sense and with reference to the regeneration of the individual candidate for life eternal, a state of temptation, the result of an excitement of the evil propensities of the natural man, -- a state in which external things and merely natural enjoyments are presented as objects of pre-eminent importance, and the mind is deluged, by the agency of the tempting powers, with floods of trifling thoughts, tending to extinguish all regard to matters of a serious nature. In the passage we have now read, we are presented with an account of the manner in which the internal man is invigorated to extricate itself from this thraldom, by the opening therein of a new principle of spiritual life, and the filling of it with a divine power from the Lord, which, after certain preparatory stages, and the extension of the confidence in divine aid thus originating till it fills the whole mind, finally destroys the opposing influence, and restores the whole man to a state of peace, accompanied with that sense of delight and enjoyment in heavenly things of which he appeared to be deprived.

The passage we have read is of considerable length, but we have read the whole on account of the conversation which it details between the angel and Gideon, which opens a subject of great importance to our reflection: though we only propose to offer a particular explanation of the first of the verses we have selected.

It appears then in general, that the discourse here recorded between the angel of the Lord and Gideon, describes the perceptions which are experienced in the interiors of the mind preparatory to the termination of the temptation represented by the invasions of the Midianites: and the whole of it shews to us the manner in which the immense variety of perceptions and thoughts that we all of us experience, arises within us. Every person has at various times in his life, been in situations in which he has experienced a great number of conflicting thoughts passing through his mind: and this, whatever may be the subject that occasions him solicitude. It is impossible to be much interested about any event whatever, attended with any suspense and anxiety, without experiencing something of this nature. One thought will arise that draws the mind one way, and another will present itself that sways it another. We cannot indeed weigh any thing maturely with a view to a prudent determination, but an operation of this sort must be felt. Now what can this be, but either the operation of distinct principles in the mind itself, or the action of distinct influences from without, or extraneously to what properly belongs to the man himself? These are poured into him from those spiritual associates of different classes with whom he is at all times surrounded, but some of whom are in a manner nearer to him at some times than at others. Their influence then becomes much stronger, and the thoughts winch they suggest are much more vivid and attended with more lively feelings. The man, however, usually regards them as the spontaneous births of his own mind, and seldom suspects that any beings but himself have any share in producing them. Nevertheless the thoughts of different tendencies which thus at times agitate the mind, arc so distinct from each other, and so strongly marked, that they appear to the man himself like conversations within him; although he usually believes both the distinct parties by which the thoughts are infused to be wholly himself. Hence it has even become customary to speak of particular thoughts, or trains of thought, that at times pass through the mind, as a species of discourse with oneself: and thus, when mentioning them to others, we often say, "I said to myself:" and when an opposite, or at least quite distinct train of thought has succeeded, we describe this also by saying, "But then I said to myself again." The truth is, that all this arises from there being in reality innumerable different principles in our minds; and also, from our being acted upon every moment by spiritual associates of different classes. For though there are innumerable distinct things in our own minds, yet as man in himself is not life, but merely a form receptive of life, nothing in his spiritual organization would ever be capable of the least consciousness of existence but for the continual action of life upon it flowing in from without -- that is, in all cases, primarily from the Lord, the only Source of life, but mediately through heaven or through hell, by the agency of angels and spirits from thence. The life thus presented from different mediate sources, is actually received by the man, and by every the minutest principle that has a place within him, from the one medium or from the other, according to its respective affinity of nature. The man however always has a power to turn either towards the one or the other, and thus to give the preponderance to whichever side he pleases, by virtue of a constant influx of freedom into the very inmost of his constitution, which he derives neither through heaven nor through hell, but immediately from the Lord alone. Seeing then that different currents of thought are in reality the action of different principles in the human mind, called into exercise by influences either from the heavenly or the infernal world; and that this is the case whether the alternations are of a nature opposite to each other, or they are mutually congenial, being only the distinct particulars of the same general principle; -- for this reason, when they are described in the language of correspondence, or of the mutual relation between natural things and spiritual, in which the Word is written, they are exhibited as real conversations between real persons. One of the great excellences of this spiritual language is, that it is capable of distinguishing things the most minute, such as, in any other style of writing, could not be distinctly presented to the apprehension. This shews us the true manner in which all the conversations between various persons mentioned in the Holy Word, are to be understood. However real, considered as to their natural existence, the persons were who are mentioned in the Scriptures, the conversations recorded between them are meant to represent the various trains of perceptions and thoughts that take place, on the occasions spiritually denoted, in the minds of individuals of the human race, as they are introduced by the operation of distinct influences, either from, the heavenly or the infernal world, on distinct principles in the human constitution.

Here then it may be observed, by the way, that when this law of the composition of the Sacred Scriptures is understood, we may be enabled to reconcile difficulties in the literal sense on important doctrinal points, which otherwise could not be easily explained. For instance: We know that man has innumerable distinct things in his constitution: We see that this is the case in the formation of our bodies; and all who have studied -- indeed all who have paid the slightest attention to -- the operations of their nobler part, the mind, are aware that this is still more compounded of parts innumerable. Yet we know, that as all the outward members make but one body, so all the inward feelings and perceptions make but one mind; -- yea, even the mind and body together, distinct as they are in their natures, make but one man. But on account of the perfect distinctness of the several parts of the mind and the man, the suggestions arising from the activity of each are represented, we see, in the Holy Word, by conversations between absolutely separate persons. Now this is the reason why the perceptions in the mind of the Lord Jesus Christ, while engaged in the work of glorifying His Humanity, are represented as conversations, carried on, on the one side, by prayer, and on the other by voices from heaven, and by commands declared by the Lord to have been received by Him from the Father; as when we find him saying, "Father, glorify thy name:" and, it is added, "There came a voice from heaven, saying, I both have glorified it, and will glorify it again." At other times we read of the Lord's addressing the Father, without any intimation being given of an answer received; and at others he speaks of the commands, or rather commissions, he has received from the Father, without any notice of an address on his part. These communications between the Lord and the Father, being so distinctly related, are supposed to imply that they are distinct persons. But the case is here exactly the same, as in the Scripture mode of representing the communication with each other of the distinct principles in the mind of one individual man. As the distinct principles that are in man, though represented by distinct persons in the Word, do not make him more persons than one, so neither do the distinct principles that are in the Lord, the most general of which are the Essential Divinity and the Divine Humanity, the one denominated the Father and the other the Son, make Him more persons than one. The appearance of their being so, arises from the style of correspondence and representation in which the Holy Word is written; according to which, we have seen, distinct principles are spoken of as distinct persons. Let us then (to vary the words of the Athanasian Creed) be careful, in our ideas of the meaning of the terms Father and Son, as applied to the Lord, neither to confound the principles nor to divide the person.

Here we have an important doctrinal application of the important fact, that the distinct principles in the human mind are represented in the Word by distinct persons: but from another branch of the same truth we may draw an important application of a practical nature. For if it be true that so many various things have a place in our spiritual organization; and if we are connected by them both with the heavenly and infernal kingdoms, -- and indeed with all the societies of each; -- and if, further, all the thoughts that ever pass through our minds proceed from the action upon us of spiritual associates belonging to some society of one or other of those kingdoms: then, if we were disposed faithfully and impartially to note our thoughts, reflecting upon those which we most readily recur to and dwell upon with most delight, it would not be difficult to ascertain what sort of spiritual society we prefer -- whether emissaries from the heavenly or the infernal world have most influence over us. There may indeed be thoughts which come in their origin from the heavenly kingdom, that do not immediately refer to heavenly things: and there may be some that seem to have this reference which in reality come from the infernal kingdom, but both may be known by observing the affection with which they are united. If it is so certain that both worlds are so near to us, how careful should we be to reject every thought whose tendency would be to ally us with the evil one, and to cherish those which would connect us with the heavenly one. It is true that thoughts from hell may be injected before we are aware, and in states of temptation may be presented so constantly, as we have seen in our last discourse, as to threaten to take entire possession of the mind: but this need not fill us with too gloomy apprehensions as to our state, provided we are careful not to make them our own by giving them willing entertainment. "Not that which goeth into the mouth," saith the infallible Teacher, "defileth a man, but that which cometh out of the mouth, this defileth the man:" where, by "that which goeth into the mouth" are meant evil thoughts injected by infernal agency, but not appropriated by the affection and so made our own; and by that which cometh out of the mouth are meant evil thoughts proceeding from the heart or will. On the whole, if we were duly sensible that every thought that enters our minds comes either from heaven or from hell, we perhaps should not think it of so little consequence as too many are apt to do, to be on our guard how they are engaged. By continued practice, we form our minds to the reception either of good thoughts or of bad: we bind ourselves either to the kingdom of light or to the kingdom of darkness: and whichsoever of these kingdoms we have thought from, and with, while here, we shall think from, and in, in and to eternity.

With these general remarks on the conversations recorded in Scripture, we will proceed to some observations on the appearance of the angel of the Lord to Gideon, as recorded in the first verse of our text.

It is mentioned in the verses preceding, that "Israel cried unto the Lord," (the meaning of which phrase we have spoken of on former occasions,) and that then the Lord sent to them a prophet who, after reminding them of the Lord's operations in their behalf in delivering them from Egypt, states the cause of their present calamity to be, their not having obeyed the command which prohibited them to worship the gods of the Amorites. By this statement is spiritually described, a perception communicated from the Lord through the doctrine of his Word,
(signified by a prophet,) shewing the cause of all temptation and infestation from evils to reside in our own selfhood, and the looking thereto instead of to the Lord: since, although the evil and false suggestions which may arise in temptations, may not be actually appropriated by us, it is nevertheless certain, that if there were not something in our selfhood which inclined that way, there would be no ground in us on which the infernal influence could operate. Then, it is said, "there came an angel of the Lord, and sat under an oak, which was in Ophrah, that pertained unto Joash the Abi-ezrite: and his son Gideon threshed wheat by the winepress, to hide it from the Midianites." This denotes the manifestation of the Lord as to his Divine Proceeding Influence, or Divine Truth in which is the Divine Good, in the Word, and in the things that are from the Word stored up in the human mind; and the development of a principle of genuine truth from good in the interiors of the mind, to and in which this manifestation could take place. An oak is a tree frequently mentioned in the Scriptures; and as all trees in general signify either.perceptions or knowledges of truth, according to the subject respecting which they are mentioned, so do particular trees signify some particular class of such perceptions or knowledge. An oak, for its great magnitude, its great hardness, and the tangled appearance of its crooked branches, denotes truth in its lowest and most external mode of existence, in which it is a general covering or clothing to things of an interior nature, (which perhaps is represented by the magnitude and cap-like form of the oak;) -- is to them a strong basis for their support, which is expressed by its hardness; -- and in which truth appears under a mazy and confused aspect, the fallacies of the senses which here mingle with it requiring continual unravelling; which is what is represented by its tangled appearance and the crookedness of its branches. Thus the oak is an apt emblem of the Word in the obscurer parts of its letter, a great portion of which consists of truth of this kind: and the angel of the Lord sitting under the oak, denotes the Lord Himself as to His Divine Truth in the inmost of the Word. Joash represents a principle of good from the Lord still existing in the interiors of the mind, and his son Gideon is a principle of truth proceeding from that origin. Some idea of the specific quality denoted by them may be formed, from the circumstance of their belonging to the tribe of Manasseh: for Manasseh, who was the eldest son of Joseph, denotes the will principle of the spiritual man, -- or the new will formed by regeneration in man's spiritual part by the Lord.

That Gideon had some such representation as we have stated, is evident from the employment in which the angel of the Lord found him engaged. He was threshing wheat: our translation says "by the winepress," but according to the original it is "in the winepress;" -- an extraordinary expression that has very much perplexed translators and commentators. Some have rendered it "in a little threshing floor," supposing that the winepress is mentioned, not to denote that any winepress was actually concerned, but to intimate that the threshing floor was not larger than the space occupied by a winepress; others, as the English translators, conceiving this too far fetched, have put an unusual meaning on the preposition signifying in, and have translated it by. However, we need to take no pains to reconcile the literal expressions, or to ascertain in what manner or place Gideon, as a certain man, actually managed to thresh his wheat: the spiritual sense is clearly discoverable in the mode of the expression as it stands in the original; and, no doubt, that singular mode of expression was made use of, purposely to give the spiritual sense in fulness, -- the obscurity which was thus thrown over the letter, being comparatively a thing of no consequence. To thresh wheat is to separate it from the husk preparatory to its being used for food: and a winepress is used to perform a similar operation in the preparation of, wine, it being a machine for the separation of the juice of the grapes from the skins and refuse. Wheat, as the noblest species of corn and the chief article of human food, represents that which tends most substantially to nourish the spiritual man, which is good of a celestial order appropriated in his will: and wine, which is the most generous kind of drink, denotes that which tends most directly to invigorate the spiritual part, by enabling the mind to appropriate the good on which it must primarily subsist; which is truth of a spiritual order appropriated in his understanding: for as food alone, without drink, would not nourish the body, for want of a vehicle to convey it into the system, so neither will good without truth nourish the mind: yet all the nourishment resides in the food: by drink alone, though it readily enters the system, life cannot be supported.

Thus, then, by Gideon's threshing wheat in a winepress, and this in order to hide it from the Midianites, is denoted, that notwithstanding the prevalence of such things as are represented by the Midianites in the external man, there is, nevertheless, within, a principle that is intent upon the appropriation of good, and upon the purification of it from the chaff of our own defilements: and that this is going on while there is nothing outwardly apparent hut a state of jeopardy and trial arising from the presence of opposing principles in the external: for a winepress, on account of the force used in it, represents also, a state of severe temptation, by which the quality of the truth we have received is ascertained. Thus while nothing is discoverable to the outward observer, nor perhaps to the man himself, but affliction and desolation -- though the good that is being effected is hid from the Midianites -- there nevertheless is a principle inwardly which is intent upon exploring and appropriating good, and to which the angel of the Lord -- an influence of his divine Spirit, can be manifested, and can excite it to an open development by the encouraging assurance -- the Lord is with thee, thou mighty man of valour.

We see, then, from this slight view of this part of our subject, of what infinite importance it is that we should ever preserve in our internal man, a steady determination to the love and practice of goodness, -- that we should ever cultivate in our hearts a sense of the pre-eminence of such affections as have the Lord and heaven for their objects, and which manifest themselves in harmlessness of demeanour and works of charity -- that term being understood to mean the pure love of our neighbour. If this be attended to, all external ,clouds will ere long pass away: -- sorrow may endure for a night, but joy cometh in the morning. We have also seen how much improvement may be derived from a careful watching over our thoughts -- how much our eternal state depends on our employing the freedom of will and choice, which we enjoy as a gift imparted to us from moment to moment from the Lord alone, to the purpose of making a right choice in those spiritual associations with the inhabitants of the eternal world, which, whether we know or reflect upon it or not, we are forming or strengthening every instant of our lives. Of what infinite moment must this be to us, when we must so soon become inhabitants of the eternal world ourselves! Of the certainty of this we are continually receiving warnings. At all periods of life, we are liable to be called away: let us be prepared for the call by forming our minds while here, to an association with the inhabitants of the heavenly world, by continually striving to cultivate heavenly affections in our internal man, by removing every outward obstruction, till our whole mind and life assumes the heavenly impress.




