
<<<
---
== Chapter XIII. Judges 6:11-24 (Part 2)

"_And there came an angel of the Lord, and sat under an oak which (was) in Ophrah, that (pertained) unto Joash the Abi-ezrite: And his son Gideon threshed wheat by the wine press, to hide it from the Midianites. +
And the angel of the Lord appeared unto him, and said unto him, The Lord is with thee, thou mighty man of valour. +
And Gideon said unto him, O my Lord, if the Lord be with us, why then is all this befallen us? and where (be) all his miracles which our fathers told us of, saying, Did not the Lord bring us up from Egypt? But now the Lord hath forsaken us, and delivered us into the hands of the Midianites. +
And the Lord looked upon him, and said, Go in this thy might, and thou shall save Israel from the hand of the Midianites: have not I sent thee? +
And he said unto Him, Oh, my Lord, wherewith shall I save Israel? behold, my family is poor in Manasseh, and 1 am the least in my father's house. +
And the Lord said unto him, Surely I will be with thee, and thou shall smite the Midianites as one man. +
And he said unto him, If now I have found grace in thy sight, then show me a sign that thou talkest with me. +
Depart not hence, I pray thee, until I come unto thee, and bring forth my present, and set it before thee. And he said, I will tarry until thou come again. +
And Gideon went in, and made ready a kid, and unleavened cakes of an ephah of flour: the flesh he put in a basket, and he put the broth in a pot, and brought it out unto Him under the oak, and presented if. +
And the angel of God said unto him. Take the flesh and the unleavened cakes, and lay them upon this rock, and pour out the broth. And he did so. +
Then the angel of the Lord put forth the end of the staff that was in his hand, and touched the flesh and the unleavened cakes; and there arose up fire out of the rock, and consumed the flesh and the unleavened cakes. Then the angel of the Lord departed out of his sight. +
And when Gideon perceived that He was an angel of the Lord, Gideon said, Alas, O Lord God! for because I have seen an angel of the Lord face to face. +
And the Lord said unto him, Peace be unto thee; fear not: thou shall not die. +
Then Gideon built an altar there unto the Lord, and called it Jehovah-shalom: unto this day it is yet in Ophrah of the Abi-ezrites._" (Judges 6:11-24)

In our last discourse, we took occasion, from the long dialogue which is recorded in this passage of Holy Writ, to offer some explanation of the general design of the numerous conversations which are detailed in the Scriptures, and to show, that in their application to man in the progress of his regeneration, they denote, not dialogues between distinct individuals, but distinct trains of thought, passing in the mind of one individual, and injected into him by a spiritual agency, operating either from heaven or from hell, and from the various classes of the spiritual associates who are always near him. Having thus proposed such general observations as seemed necessary to prepare us for a right apprehension of the import of the narrative, we will now, as the particulars to be considered are numerous, and will take some time to unfold even with the utmost brevity, proceed without further preface to what lies before us.

We have seen that Gideon represents a principle of truth from good in the interiors of the mind, which is intent upon the acquisition and appropriation of good, even during those states of temptation in which the exteriors seem utterly carried away by the inundation of trifling thoughts of an evil nature, tending to the confirmation of merely external delights; and that the appearance of the angel of the Lord to Gideon represents an influx of divine truth from the Lord Himself through heaven, invigorating what is thus of Himself in the interiors of the mind, and preparing it to flow into the exteriors with such power, as to dissipate whatever is infused thereinto from the kingdom of darkness, and restore the whole man to a state of heavenly peace and delight. The conversation then which is recorded between the angel and Gideon, no doubt expresses the perceptions which pass in the mind of the regenerating subject, preparatory to the conclusion of the temptation represented by the invasion of Israel by the Midianites.

The first thing stated is, that the angel of the Lord appeared unto Gideon: by which is described, the perception of light in the interiors of the mind, and of the re-opening of a communication with heaven, discovered by a sense of inward peace and elevation towards the Lord, after a long period of darkness and anxiety. For when a person, truly intent upon making sure his reception into that state of happiness, the consequence of an appropriation of a heavenly principle of life, which it is the desire of the Lord that all should attain, is not in a state of temptation, he feels an inward peace and tranquillity of mind, the consequence, though this he does not know unless he has learned it from the doctrines of his church, of the nearness of angelic associates, -- of the interiors of the mind being in fact so opened towards heaven, as to receive a communication, not indeed of the thoughts of the angels, but of somewhat of their heavenly affections which have inherent in them heavenly delight: he hence also has a ready access to the Lord in his devotions, with a sense of divine favour and acceptance, which gives a life and soul to all that he thinks, does, and is. But in states of temptation all this is intercepted, whence he cannot help coming into deep anxiety, with a sense of apprehension as to his spiritual security, a dread of being finally cut off from the heavenly kingdom, even extended to a despair of ever attaining it: for in this state his thoughts are kept continually on his own evils; and it seems to him as if he must fall into and be fixed in them for ever. This arises from the agency of the tempting spirits, who call forth such things from his memory, and from his hereditary propensities; and indeed not only excite what the man actually has possessed and appropriated, but infuse and charge upon him much more, which though altogether from them, appears to the tempted subject as if it was wholly from himself. In the present state of the world these states, probably, are not often experienced, yet we are assured in the New Church Writings, in which such subjects are laid open with a clearness never known before, that real temptations are attended with such feelings and perceptions as these, and that there is no other way by which the evils of man's nature, especially such as he has confirmed by actual life, can be removed from his mind: for the mind is a real spiritual substance and form, and whatever has been an object of the love gives a certain modification to that form, so that the removal of an evil is in fact the removal of something in the organization of the mind, and the correction of some deformity which had been occasioned by it: of course this cannot be effected by a mere thought or wish, but only by a painful course of discipline. This discipline therefore, must, at some period or other of our existence, be undergone, before we can enter the regions where no spiritual deformity can appear: if therefore it is not undergone in this life, it must after the death of the body, provided such a degree of the reception of divine things had in this life been attained, as to have given a preponderance in the interiors to good over evil: otherwise it never can be experienced at all, and thus the evils that have a place in the spiritual organization can never be removed at all, but must sink the unhappy subject of them to the regions of final misery. That some who are destined for heaven do not enter it immediately on the death of the body, is evident from many passages of the Holy Word rightly understood: sis from that where John says in the Revelation that he saw souls under the altar who said, "How long, Lord, holy and true, dost thou not avenge our blood on them that dwell on the earth;" by which is spiritually described the desire of those who are in temptations from the infestation of evil spirits in the other life, wherein they are guarded by the Lord's divine love, to be delivered and taken up into heaven. I mention these things lest it should be supposed, since many experience little or nothing of real spiritual temptations in this life, and yet they are necessary to final purification, that therefore there is room to draw unfavorable conclusions respecting their eternal state. None, it is plainly seen, pass through the world without undergoing trials of an external or natural kind; and these, when made a right use of, no doubt tend, though indirectly, to improve the spiritual state: but spiritual temptations are trials in which the objects in suspense are not earthly but heavenly ones, being real conflicts in the mind between evil and good, false persuasion and truth, and being always attended with anxieties, not about temporal things merely, but about eternal salvation: though sometimes anxieties of both kinds are combined, which are the most severe temptations of all. And we may also be assured, that the more of the temptations necessary for our purification are undergone, and thus the more of the evils inherent in our nature or acquired by habit, are removed, in the present life, the higher and more blessed will be the state to which we shall be exalted in eternity.

In the case then before us, by the angel of the Lord's appearing to Gideon is meant the restoration of the communication with heaven and the Lord, towards the conclusion of a state of temptation; and by his saying, "The Lord is with thee, thou mighty man of valour," is meant, a perception in the mind, flowing in from this source, of the divine presence, and of the impartation of strength to the truths abiding with us from the Lord, sufficient to drive away all the clouds of temptation. But when a temptation has been continued so long, that it appears as if it never could have an end, the mind is not easily raised from its despondency, but a multitude of doubts is suggested as to the possibility of deliverance; which is denoted by the numerous doubting answers and requests made by Gideon. Thus he does not at first recognize the being who spake with him to be an angel; by which is intimated that in the first breaking of light through the clouds, and the arising of the first encouraging thoughts, it is not immediately seen to be a real commencement of deliverance, but is distrusted as an illusion of deceitful hope: and the answer that he makes is that of despair; -- of a man who on such a suggestion arising, regards what it points to as impossible; having been so entirely deprived of his spiritual comforts as to doubt whether those he had experienced in former times had in them any thing real, and had not all been mere tricks of the imagination: for he says, "O my lord, if the Lord be with us, why then has all this befallen us?" -- words which imply a belief, from the severity of the temptation, that there was nothing of the Lord in the mind at all, that if there were really any thing good within, it would be impossible to seem to be so entirely deprived of it. He adds, "And where are all the miracles which our fathers told us of, saying, did not the Lord bring us up out of Egypt." These words express doubt whether former spiritual experiences had been real or not, from a supposition, that if we had really been delivered from the merely natural state represented by Egypt, we should not be liable to fall into the grievous condition which is now experienced. The miracles, or, as the word here used more properly means, the wonderful works, are the divine operations in our behalf by which we had been brought from a merely natural state, regardless altogether of spiritual things, and ignorant of them, to a state of reception and delight in them: and it is added, "which our fathers told us of," to denote that there were deliverances belonging to a former state, which indeed influence the present, but which, if real, seem now to have been of no use, as not serving to prevent our being now lost in a different manner: "for," he says, "now the Lord (whatever he may formerly have done for us) hath forsaken us, and delivered us into the hand of the Midianites:" -- every thing of the Lord once received in our minds is now become extinct, the consequence of which is that we are wholly sunk into the power of merely external things with their fallacious delights. Words cannot express a more entire state of despair: and their being urged in answer to the angel's first salute, seems to intimate that the first effect of the near presence and powerful influx of the Lord in states of temptation, is, to make us feel all the horrors of our condition. It is true, indeed, that in all temptations the Lord is inmostly present, and more immediately so than at other times: otherwise we could not be kept in a determination of resisting, but should indubitably yield, and there can be no doubt that the final sentiment of despair is the consequence of the Lord's drawing still nearer, so that the influx being stronger than our state is adequate to bear, occasions the sense of extreme humiliation and worthlessness which suggest the thought that there can be no hope for us. This however is one of the chief things which the temptation is permitted in order to produce -- not the sense of despair, if this could be separated from the other, but the conviction that in and of ourselves we have nothing that is good, that in and of ourselves we are nothing but evil; -- to feel as if the Lord had forsaken us, or cannot dwell with creatures so denied; but that we are delivered into the hands of the Midianites, -- are wholly abandoned to the possession of the evils of our nature. This state of self-abasement however is one which prepares us for a more direct reception of the Lord's mercies; which is implied by its being now said, that "the Lord looked upon him," -- to look, as having reference to the sight, denoting to communicate a clear perception. "And He said, Go in this thy might, and thou shalt save Israel from the hand of the Midianites: have not I sent thee?" It does not readily appear what is here referred to by the demonstrative pronoun this -- Go in this thy might: but if, as one would expect, it refers to what Gideon had just said, it beautifully illustrates, the doctrine contained in the Lord's saying to the apostle, "My strength shall be made perfect in weakness:" for as soon as Gideon, or the spiritual man represented by him, is brought to the heartfelt acknowledgment of his own nothingness and vileness, the Lord says, "Go in this thy might." If, however, the saying, "this thy might," refers to the vigour with which he was threshing the wheat, the meaning will be, to apply this earnestness with which the mind is intent on appropriating good and rejecting its impurities in the internal man, to the rejection of every thing opposite thereto in the external: and as both these applications of the words are in agreement with genuine doctrine, I cannot say which is specifically intended.

But we find that this improved perception of the Lord's merciful designs has the effect of carrying Gideon's humility still further; for his answer is, "O my Lord, wherewith shall I save Israel? behold, my family is poor in Manasseh, and I am the least in my father's house." As his former answer had more reference to a sense of man's being in himself nothing but evil, so this has more application to an acknowledgment of utter inability of and from himself to do any thing good. To be the least, when willingly avowed, is to be in humility, and in what is near akin to it, and cannot exist without it, in innocence: for the being innocent, in the sense in which it is referred to in the Scriptures, does not mean the being free from any hereditary corruption, or the having never fallen into any transgression, for in these senses none are innocent, nor can they possibly be made so; but it refers to a state in which the mind is thoroughly sensible of its own weakness and unworthiness, and in which it depends entirely upon the Lord alone, as a child on its parents. It is no doubt on account of this signification of being the least of a family or tribe, that it is mentioned in other instances: thus Othniel, as noticed in a former discourse, is described as being the least of his family; And when Saul was told by Samuel that he should be king over Israel, he answered, "Am not I a Benjamite, of the smallest of the tribes of Israel? and my family the least of all the families of the tribe of Benjamin?
Wherefore, then, speakest thou so to me?" So David was the least and youngest of his father's house. These instances illustrate the Lord's words, "Except ye shall receive the kingdom of God as a little child, ye shall in nowise enter therein:" instructing us that innocence, consisting in humility and the renunciation of self, is the only soil in which Christian graces can be planted so as to be fruitful. And where self is thus put out of the way, room is made for the Lord to enter: wherefore "the Lord said unto him, Surely I will be with thee, and thou shalt smite the Midianites as one man:" which denotes a further clear perception that deliverance from the infesting influence is not, as was at first supposed, impossible, but a full conviction that by the Lord's aid so full a victory over it may be obtained, that the whole mass of infesting incitements and persuasions should be swept away together.

Still, however, all that has hitherto been affected by the perceptions thus communicated, has been the intellectual part of the mind: but though this is thus convinced of the practicability of the deliverance promised, so that hope begins to succeed to despair, yet the will is not yet so inflamed and animated to the work as to exalt this hope into confidence. For a long time previously there has been an inability to raise the affections to the Lord, and to feel any sense of worship being accepted: wherefore, until this can be experienced, although the understanding is convinced that by divine aid deliverance may be obtained, yet the mind does not feel fully assured that this conviction is really from the Lord, and is positively an earnest of the attainment of such deliverance. This is intimated by Gideon's saying, "If now I have found grace in thy sight, then show me a sign that thou talkest with me," -- where the latter words properly mean, that it is thou, (that is, the Lord,) that talkest with the soul and impartest these perceptions: he adds, "Depart not hence, I pray thee, until I bring forth my present, and set it before thee. And he said, I will tarry until thou come again. And Gideon went, and made ready a kid, and unleavened cakes of an ephah of flour: the flesh he put in a basket, and he put the broth in a pot, and brought it out to Him under the oak, and presented it." All this denotes the preparing of the mind for the pure worship of the Lord, by raising to him the purest affections of innocence and charity of which it is capable, and the desire of experiencing conjunction of life with Him thereby. Then "the angel of God said unto him, Take the flesh and the unleavened cakes, and lay them upon this rock, and pour out the broth:" by which is implied, that the affections of innocence and the perceptions of truth connected therewith, must be entirely separated from self, and acknowledged to be from the Lord alone by the divine truth of His Word, which is meant by the rock: -- And when Gideon had done so, "Then the angel of the Lord put forth the end of the staff that was in his hand, and touched the flesh and the unleavened cakes, and there arose up fire out of the rock, and consumed the flesh and the unleavened cakes:" by which is meant, that when the offering of the best affections is thus made in sincerity, an influx of power flows into them from the Lord, signified by the putting forth of the staff, and they are vivified by the impartation of a pure flame of love from the Lord by the Word, denoted by the fire springing up out of the rock, and that thus our faint affections are really elevated to, accepted by, and have the effect of conjoining us with, the divine love of the Lord, signified by the offering being thus consumed. Then it is said that "the angel of the Lord departed out of his sight:" denoting the termination of the state, of the manifest nearness of the divine presence, and the return of the man into a state more of his own affection and thought, though now essentially changed and renewed: the consequence of which is, a sense of the nearness in which the divine presence had been felt, and of holy awe on account of it, attended with the extinction of the life of the previous state, and the reception of a new principle of life from the Lord. The sense of holy awe, and of the extinction of the life of the selfhood, which appears at the time as if a total extinction of all life would attend it, is implied by the exclamation of Gideon when he thus perceived what a near manifestation he had had of the divine presence, "Alas, O Lord God! for because I have seen an angel of the Lord face to face:" and the revivification of the mind in consequence of the reception of a new principle of life from the Lord, is meant by the Lord's consoling answer, "Peace be unto thee: fear not: thou shalt not die." And that the state of improved love and inward peace thus acquired is stored up in the interiors, and is attended with blessed consequences to all eternity, is meant when it is added, "And Gideon built there an altar unto the Lord, and called it Jehovah-shalom, (that is, Jehovah's peace): unto this day it is yet in Ophrah of the Abi-ezrite."

 What blessed encouragement is here afforded us to persevere steadfastly through every stage of our spiritual progress, since even the most severe, which after all endure but for a moment, procure for us blessings that never have an end. What satisfaction it must afford us to have a well-grounded confidence that an altar to the Lord is really erected in the interiors of the mind -- a principle that worships Him continually from pure love, and the name of which is Jehovah's peace, -- that is, its quality is such that a state of inmost peace, the result of the union of goodness and truth, and of conjunction of life from the Lord is inherent in it; and that this shall abide to this day -- that whatever state may ever after be present, still this shall be within. May we be faithful enough to become partakers of such mercies; to which end may we ever be intent on the purification of our heart and life, and submit in all things to the leadings of the Lord and the direction of His Word.




