
<<<
---
== Chapter XV. Judges 7:2-7

"And the Lord said unto Gideon, The people that are with thee are too many for me to give the Midianites into their hand, lest Israel vaunt themselves, saying, Mine own hand hath saved me. Now therefore go to; proclaim in the ears of the people, saying, Whosoever is fearful and afraid, let him return and depart early from mount Gilead. And there returned of the people twenty-and-two thousand; and there remained ten thousand. And the Lord said unto Gideon, The people are yet too many; bring them down unto the water, and I will try them for thee there: and it shall be, that of whom I say unto thee, This shall go with thee, the same shall go with thee; and of whomsoever I say unto thee, This shall not go with thee, the same shall not go. So he brought down the people unto the water: and the Lord said unto Gideon, Every one that lappeth the water with his tongue, as a dog lappeth, him shall thou set by himself; likewise, every one that boweth down on his knees to drink. And the number of them that lapped, putting their hand to their mouth, was three hundred men: but all the rest of the people bowed down on their knees to drink water. And the Lord said unto Gideon, By the three hundred men that lapped will I save you, and deliver the Midianites into thy hand: and let all the other people go every man unto his place."

In some discourses which I delivered a few years ago on the emancipation of the children of Israel when oppressed by the Midianites through the instrumentality of Gideon, who was divinely raised up for the purpose, I did not treat, except incidentally, and very slightly, when discoursing upon other parts of the narrative, of the very remarkable portion of it contained in the verses which I have now read. However, as the history contained in this chapter, of the rout of the Midianites by Gideon's band of only three hundred men, is one of the most singular of the narratives to be found in the historical books of the Holy Word; and as the account detailed in the verses I have now read, of the reason why Gideon's originally respectable army of thirty-two thousand, -- a force which, to all human apprehension, was quite small enough to attack a host of one hundred and thirty-five thousand men, which was the number of the Midianites, -- was reduced to a little band of three hundred, and that by so extraordinary a test as the one prescribed for the purpose, -- as this is the most singular portion of this, throughout, most wonderful narrative: I have thought it might be both acceptable and useful again to make it the subject of our meditation. The one or two notices which are taken of the passage in the writings of the New Church are extremely slight; yet perhaps they are sufficient to enable us to deduce a satisfactory and profitable explanation of the whole.

But before attempting any explanation of particulars, I cannot refrain from making an observation, which, I think, must strike every one on reading the passage. What I mean is, the utter impossibility, upon any rational principles, except such as admit the existence of a spiritual sense of the inspired record, of accounting for the extraordinary method by which the three hundred men, who, it was foreseen, would achieve the victory, were selected out of the ten thousand, of whom the force, which had already undergone a sifting which had reduced it to less than a third of its original amount, now consisted, and of which remaining ten thousand, no fewer than nine thousand seven hundred would, it appears, have been a useless incumbrance. If, for some spiritual reason which human ingenuity could never have suspected, Divine-Wisdom deemed it better to attack one hundred and thirty-five thousand with three hundred -- being one four hundred and fiftieth fraction of that number, or at an odds of 450 to one, -- rather than with ten thousand, which would have been two twenty-sevenths of the enemy, or an odds of thirteen and a half to one, -- still no one could deem, that the proper method of ascertaining who should be disbanded and who retained, could be, by trying in what manner they would drink water from a stream or lake, -- whether by kneeling down to it, and sucking it up with their mouths, or taking it up in the hollow of their hands and lapping it like a dog with their tongue. No one, I say, it is obvious, could possibly see any reason for thus distinguishing between one portion of the men who constituted the Israelitish army and the remainder, except those who know that there does exist by creation, a regular correspondence, or mutual relation, between all natural things and actions and certain spiritual ones, -- or that all natural things and actions have their properly corresponding spiritual antitypes, so that the former are representatives in nature of the latter; and that all the circumstances recorded in the Holy Word took place, and the book itself is written, according to such correspondence. I do imagine that every one who thinks deeply must see and acknowledge, that such an otherwise unaccountable circumstance, as the selecting of the three hundred men out of the whole ten thousand by so unprecedented a test, is sufficient to evince, that some spiritual reason must have been at the bottom of the transaction -- that some specific thing must have been represented by both modes of action, and thus that the narrative must contain a spiritual sense quite distinct from the sense of the letter. Let us then see if we may be enabled to discover what the spiritual sense of the whole narrative, contained in the six verses which I have read, truly is.

We have lately seen that the Midianites, when mentioned in a good sense, signify, persons of a simple and well-disposed character, who receive and apprehend the truths of the church in a simple and superficial manner, but without perversion. But when they are spoken of in a bad sense, -- as when, in this portion of the sacred history, they are described as enslaving and tyrannizing over the Israelites, as the representatives of the Lord's spiritual church, they signify such persons and principles as are of an opposite nature, -- an utter indifference to divine truths, and an attachment to falsities of the most superficial kind, the result of an immersion in pursuits and pleasures of a merely frivolous and useless description. Their oppression of the Israelites, consequently, represents temptations and desolations induced on the church, and on the member of the church, by the injection of such false and evil principles by infernal spirits of such a quality. What is signified by Gideon, and by the appearance to him of the angel of the Lord, and by the signs which were granted for his encouragement in the work to which he was called, of delivering his country, we have formerly treated of at large: at present we must confine ourselves to the portion of the divine narrative directly before us.

After Gideon, as related in the preceding chapter, had proclaimed his divine mission by casting down the altar of Baal, their profane worship of which false deity had brought on the Israelites the miseries under which they groaned, he blew a trumpet, which was first responded to by the family of Abi-ezer to which he belonged, then by all the tribe of Manasseh, to which the family of Abi-ezer belonged, and then by the neighbouring tribes of Asher, Zebulun, and Naphthali; whose warriors gathered around him to the number of more than thirty thousand men. With this army, considerable in itself, but trifling in comparison of the immense host of the Midianites, he pitched by the well of Harod, having the enemy opposite to him on the other side of the valley. The proportion of his forces to those of the enemy was as one to four and a quarter, so that every four Israelites would, on joining battle, have to engage, and, if they gained the victory, to defeat, seventeen Midianites. It is obvious, that unless assured of special divine aid, most men would deem it madness to fight against such odds. Yet "the Lord said unto Gideon, The people that are with thee are too many for me to give the Midianites into their hands, lest Israel vaunt themselves against me, saying, Mine own hand hath saved me." As just remarked, it seems improbable that any men would venture to attack so superior a force unless in the full confidence of divine assistance: yet men of an arrogant and boastful disposition, would be apt enough, on obtaining a victory under such circumstances, to forget the Divine Power to which they owed it, and claim all the merit of it as due to their own valour and military skill. In all spiritual conflicts, which these natural combats represent, such conduct would have most fatal consequences. A man who, though seeking and acknowledging divine aid at the time, should obtain the victory over any evil, or prevail in any temptation, but should afterwards ascribe it to his own strength or ability, and thus arrogate the merit of it to himself, would, by such conduct, fall into a worse evil than that which he had surmounted: the temptation would return upon him, he would no longer have strength to resist it, and the consequence of his fall would be, confirmation in evil after having attained confirmation in good, thus, a state of profanation. The care of the Lord's divine providence to guard man, in spiritual combats, from falling into such a delusion, is represented by the Lord's words to Gideon as just recited, and by the command which follows them. For the Lord proceeds to say, "Now therefore go to; proclaim in the ears of the people, saying, Whosoever is fearful and afraid, let him return, and depart early from Mount Gilead." "And," the narrative continues, "there returned of the people twenty-and-two thousand; and there remained ten thousand." They that are fearful and afraid, signify they that are without trust and real faith in the Lord; consequently, in the sense abstracted from person, such truths as man is acquainted with as yet only exist as knowledges in the memory, but are not united with their proper affection, and thus not operative in the life. In such truths, the Lord is not present, and therefore they are of no avail in temptation or spiritual conflict. This being the spiritual signification of those who are fearful and afraid, the number of them is said to be twenty-two thousand.

Twenty-two is twice eleven, and of the same signification; and eleven derives its meaning from its relation to the number twelve, just as ninety-nine does from its relation to the number a hundred. A hundred signifies what is full and complete, and consequently ninety-nine signifies what is not full and complete, but is deficient in what is chief and primary; as in the parable of the hundred sheep, of which one was gone astray. Ninety-nine, also, is a multiple of eleven, and must have the same general signification. Thus twelve -- a number so often mentioned, -- signifies all the principles of truth and goodness constituent of the church in man, considered in one aggregate Complex. Eleven signifies the same in the general, but in an imperfect state, -- thus, the principles of truth and goodness existing more in knowledge or speculation than in love and life. Twenty-two, as just mentioned, being twice eleven, has the same general signification; and its being twenty-two thousand makes no difference in the radical idea. Thus the number twenty-two thousand denotes, in the spiritual sense, the quality of those who are said to be fearful and afraid, as being such persons, or in the abstract sense such principles, as partake more of knowledge than of life, and, consequently, have not the Lord in them, and therefore are powerless and useless in temptation-conflicts. In these, nothing can prevail in which the Lord is not; and the Lord is not in any knowledges of truth, while they are not so loved as to be operative in the life. And yet, were the Lord, by other means, to give deliverance, persons whose character is chiefly formed by the possession of such inoperative truths, would be foremost in claiming the merit of the victory to themselves, and in concluding that they had obtained it by their own proper power.

However, in the case before us, the twenty-two thousand who were fearful and afraid, retired, on permission to do so being proclaimed, before the conflict. There still remained ten thousand, -- ten thousand men who stood firm and fearless, although, by the defection of the twenty-two thousand, the odds against them were increased above threefold -- from four and a quarter to one, to thirteen and a half to one; so that, in the expected battle, every two Israelites would have had to defeat twenty-seven of the enemy. Yet, it appears, they were willing to meet the foe, neither fearful nor afraid, but relying on their Divine Protector to give them a victory to which unassisted human prowess could not possibly aspire. In the spiritual sense, ten thousand is a number of good signification, denoting all, and what is perfect, in relation to truths. Under these circumstances, there could hardly be any reason to expect, that if the whole of these were allowed to act against the Midianites, and were victorious, they would claim the merit of the conquest as due to their own skill and valour, and take the honour of it from the Lord. Literally and naturally, they were too few to set up such a pretence; for how could any men, if even the bravest that ever lived, combatting at the immense odds of two to twenty-seven, ascribe the victory, when gained, to anything but the relied on and realized assistance of the Divine Hand? And, spiritually, the correspondence of the number ten thousand is too good to be applicable to any truths not in union with goodness, -- thus, to any but such as have in them the presence of the Lord, and power from him. Yet, for a reason which is not stated, though the number of the army was thus reduced by more than two-thirds, "the Lord said unto Gideon, The people are yet too many." It seems that though the quality of the truths represented by the number ten thousand was in itself good and genuine, it was not altogether such as was suited to the present emergency: wherefore the Lord commanded, saying, "Bring them down unto the water, and I will try them for thee there: and it shall be, that of whom I say unto thee, This shall go with thee, the same shall go with thee: and of whomsoever I say unto thee, This shall not go with thee, the same shall not go." "So," the narrative continues, "he brought down the people unto the water: and the Lord said unto Gideon, Every one that lappeth the water with his tongue, as a dog lappeth, him shalt thou set by himself; likewise, every one that boweth down on his knees to drink. And the number of them that lapped, putting their hand to their mouth, was three hundred men: but all the rest of the people bowed down on their knees to drink water. And the Lord said unto Gideon, By these three hundred men that lapped will I save you, and deliver the Midian-ites into thy hand; and let all the other people go every man unto his own place."

We have already remarked on the demonstration which this singular mode of testing the people, as to who were the proper men, and who were not, to be led against the Midianites, affords of the truth, that a spiritual sense is contained in the Word of God; since it is impossible to conceive any reason, other than the spiritual signification of the act, why the three hundred men who lapped the water with their tongue should be more fit instruments, though so few in number, for routing the Midianites, then the nine thousand seven hundred who stooped down upon their knees. This is to be found in the signification of the tongue, of a dog, of water, of the number three hundred, and of the Midianites, whose resistless opponents these three hundred men were found in the sequel to be.

The tongue, in the Word of God, and in consequence of the correspondence that exists between natural things and spiritual, by virtue of its being the chief organ of speech and also of taste, signifies both the confession and perception of divine truths, and the affection of good. It signifies, because it corresponds to, the perception of divine truths, and confession of the Lord from them, by virtue of its being the chief instrument of speech, or in modulating the sounds which are made by the breath in passing through the larynx into articulate words; and it signifies, because it corresponds to, the affection of good, on account of its being the principal organ of taste; for the taste corresponds to, and thence signifies, such affection.

A dog represents, by correspondence, appetite and eager desire -- in a bad sense, concupiscence. Every one may see, from all the actions and manners of the animal, that eagerness of appetite and desire, is the very life of a dog; it is modified in a great many ways, in the innumerable varieties of the species, yet it obviously constitutes the governing principle with them all. Waters, we have often shewn, signify truths, and to lap them with the tongue like a dog, signifies to appetite truths and seek them with eager desire. Thus, men who lap water out of their hand with their tongue like a dog, signify those who appetite truths, or who, from some natural affection, are eager to know truths. These then were the proper persons to be led against the Midianites, because the Midianites denote such persons as, far from having an eager desire to know truths from any natural affection, and being destitute of all spiritual affection, give themselves no concern at all about truths, care nothing for them, -- their natural affections, and thence all their thoughts, being wholly engaged with frivolous pursuits and vain amusements. And the number three hundred, though not, when applied to a band of soldiers, a number of great amount, yet signifies all the truths, in complete fulness, of the quality in question: for it arises from three multiplied by a hundred; and the number three signifies what is full and complete, and has especial reference to truths; and the number a hundred signifies fulness and completeness in the greatest degree. Three hundred men, therefore, who lap water like a dog, signify truths made active in the mind, and in the lowest principles of the life, from an eager natural affection; and such, therefore, as are proper and sufficient to dissipate that indifference to truths represented by the Midianites, and the engrossing attention to merely external, trifling, and useless things and pleasures in which such indifference has its origin.

These, brethren, certainly are arcana of so deep a nature, as not to be readily apprehended and are as difficult to be explained in a manner adequate to the apprehension of others. And perhaps some may think -- all will think who are of the Midianitish character -- who give themselves no concern about divine truths because their minds are always occupied with trifling things, -- What is the use of knowing them? It is no small use, if the advantage we derive from it is only that, of possessing a conviction that there is a spiritual sense in the Word of God, and thus being enabled to think of it, even as to its, in the letter, most seemingly unaccountable parts, with the reverence due to its most holy and essentially divine nature. But we cannot have any just idea of any portion of the spiritual sense of the Word of God, without feeling sensible that however abstract and abstruse, to our external mode of viewing things, it may appear, all that it contains, while opening to the understanding the sublimest contemplations, has an equal tendency to purify the affections and produce goodness of life. When, in the case before us, we obtain some idea of the temptation represented by the invasion of Israel by the Midianites, and of the eternal ruin that must ensue if the principles represented by them are allowed finally to prevail; and when we see that nothing can liberate the mind from the fatal unconcern about divine truths and spiritual things in general, which is hereby signified, but such an ardent appetite for truths kindled and fostered in the mind in fulness and sufficiency, as is represented by the three hundred Israelites who lapped water with their tongue like a dog, how earnest should we be to have such a desire kindled in ourselves, separated from all that would impede its operation, and made efficient to the casting out of all supreme regard to low and worldly things, all disorderly occupation of the mind, and consuming of our time in idle pursuits and pleasures. Then, giving our supreme regard to the things of eternity, we may prevail over every evil and false tendency of our nature, -- over all the snares of the world and the arts of our spiritual enemies; and, ascribing all to the power and mercy of the Lord, we shall obtain a safe and everlasting inheritance in the heavenly Canaan above.




