
<<<
---
== Chapter XVI. Judges vii. 9 -- 14

"And it came to pass the same night, that the Lord said unto him, Arise, get thee down unto the host: for I have delivered it into thy hand. But if thou fear to go down, go thou with Phurah thy servant down to the host, Mid thou shalt hear what they say; and afterwards shall thy hands be strengthened to go down unto the host. And the Midianites and the Amalekites and all the children of the east lay along in the valley like grasshoppers for multitude; and their camels were without number, as the sand by the sea-side for multitude. And when Gideon was come, behold, there was a man that told a dream unto his fellow, and said, Behold, I dreamed a dream: and lo, a cake of barley-bread tumbled into the host of Midian, and came unto a tent, and smote it, and overturned it, that the tent lay along. And his fellow answered and said, This is nothing else save the sword of Gideon the son of Joash, a man of Israel: (for) into his hand hath God delivered Midian and all the host."

It is impossible to read the holy Word with any degree of apprehension of its interior contents, as brought to light for the edification of the New Church, called the New Jerusalem, and at the same time to recollect what are the views commonly entertained respecting the most important doctrines of religion, without being struck with the widely different nature of the view which thence arises on the subject of Christian regeneration. The doctrine of the present day on this subject, as understood by those who make most profession of experimental religion, is, that regeneration is the work of a moment; that at some period or other in the life of all who are saved, -- sometimes even in childhood, and sometimes not till the bed of death, -- a work of divine grace is miraculously wrought, by which the sinner is suddenly gifted with faith in the efficacy and merits of the Saviour's death, and is enabled to believe with full persuasion that He died for him; when it is supposed that all his sins are at once blotted out, that he is instantly regarded as holy in the sight of God, and that, should he die instantly, even though this might be at the gallows, his soul would be at once received to eternal glory. This then is what is commonly understood to be regeneration. The church of England indeed, -- that is, that part of its ministers and members who do not assume to themselves exclusively the name of evangelical,- -seeing the inconsistency of this notion of regeneration, and yet not being able to form a better, get over the matter by affirming, that regeneration is nothing distinct from baptism, or if it is, that at any rate it is inseparable from baptism, and is conferred by it. Thus though the two views of the subject are as different from each other as possible, they still agree in this; that they both proceed upon the supposition, that regeneration is an instantaneous work. It is indeed true, that to account for the vicissitudes of state which even they who have been regenerated according to their plan, afterwards experience, and for the want of the fruits of holiness too often apparent in them, some have invented another process, which they call sanctification, and hold to be quite distinct from regeneration; contending, that although man is regenerated at once, and is from that moment accounted holy in the sight of God, yet he will never become so really holy in this life, but that the old man will at times be very conspicuous: however they maintain that he begins to grow holy from that moment, and the process by which he becomes so, they term sanctification.

Now it may appear, as if these two processes together amounted to much the same as what we call in one word regeneration: and if they really did so, it would not be worth while to dispute for a word, and we might as well conform to the common phraseology, and allow sanctification to be a separate thing from regeneration. But two insurmountable impediments stand in the way. The first is, that the sanctification commonly talked of, really amounts to nothing, having only been, introduced to render less perceptible the contrariety between their main doctrine of instantaneous justification and the Holy Word: for when it is contended that by the act of regeneration as understood by them, man is at once made holy in the sight of God, so completely, that though he may be suffering for the most atrocious crimes at the gibbet, he passes at once to eternal glory; it is evident that they can themselves regard their sanctification as of little value, if, where most wanted, it can so easily be dispensed with. A second obstacle to the adopting of this representation is, that nothing at all similar to the regeneration thus supposed is to be found in the real regeneration described in the doctrines of the New Church. For the false and instantaneous regeneration of which we have been speaking, is nothing but a suddenly conceived persuasion that the Saviour died for us individually, -- that the punishment of our sins, that is, the punishment due to us for the identical sins we have committed, was endured by him, and that his righteousness is imputed to us in exchange. Thus it is, that while the professing church retains the names of the great subjects which enter into the constitution of religion, she lays out of sight the things which those names imply, and, like the church of Sardis, while she retains a name to live, she is dead. Nothing whatever respecting such regeneration and such sanctification is to be found in the New Testament, either in the gospels or in the writings of. the apostles; and certainly no sanction to such views can be drawn from the Old Testament. We read indeed of those who before were in ignorance, being converted to the knowledge and acknowledgment of the Lord; but never is this called regeneration or being born again. On the contrary, the progressive nature of real regeneration is plainly indicated by the Lord when He says, Ye that have followed Me in the regeneration; implying, what in general is wholly lost sight of, that He himself underwent a process answering to regeneration, and which consisted in effecting the glorification of his Humanity, and that the regeneration of man consists in his undergoing a process similar in kind though infinitely inferior in degree, by which he from natural becomes spiritual; and that both processes are effected by gradual and successive steps.

What we have now advanced must have been amply apparent from the discourses we have been for some time engaged in delivering from this book of Judges, if the views we have offered of the spiritual import of the various transactions recorded, be allowed to be founded in the truth. We see from hence most clearly, that regeneration consists of a great number of distinct operations, not one of which even can be performed in a moment: for we see, that if the conflicts of the Israelites with the nations that oppressed them be each of them considered, as is highly reasonable, as representing distinct temptations, every one of which must mark the opening and completion of a distinct stage in the regenerate life; then each of these again is subdivided into minuter divisions, and passes through distinct steps to its termination, and thus the whole process of regeneration is a series of orderly progression. So wonderful is the order observed in all the divine operations! As in natural things, in the production of vegetables or animals, nothing arrives at maturity in a moment; so must it be in that far more important and wonderful operation, the formation of a spiritual man, as it may be called, within the natural; or the new formation of man as to his spiritual part, so that he may be qualified to live in the regions of eternal glory. How desirous ought we to be to co-operate with the Lord in this great work; -- that is, to suffer him to accomplish it in us and for us; for this is all that our cooperation amounts to. Our co-operation consists in our desisting from evils in practice, and from cherishing them in our thoughts, to which end it is necessary that we should frequently explore the state of our affections, to discover on what they are set, and what actions we should do if restraints arising from external considerations were removed. But the inward seat of our evils lies deeper than we could explore, were it not that they develop themselves by their effects in that region of the mind that comes within our inspection: the work then of purifying this inward seat of them is within the reach of divine power alone: and this the Lord does do and will do, provided we do not maintain them in their empire by refusing to check them in their outward manifestations.

These inward operations, then, of which only some part is perceived by man in an obscure and general manner, are the subjects which are described in the portion of the Holy Word which we have for some time been contemplating. This history of Gideon is particularly remarkable for the extent of detail with which it is related, and for the numerous very singular things of which the historical circumstances consist; to notice all of which would require, not four or five, but many discourses. Thus in the verses preceding our text, is described how Gideon's army was reduced from more than thirty thousand to three hundred men, to guard against the danger of their assuming the merit of their expected victory over the Midianites to themselves: the three hundred men who were allowed to remain being selected because, on going to the water, they did not go down on their knees to drink, but lapped the water out of their hands with their tongues like a dog; by which was represented the eagerness of affection for truth, which is the proper opposite to that indifference to every thing of a spiritual nature, which characterizes the trifling principle represented by the Midianites. In some former discourses we have considered the two first of the signs by which Gideon was assured of the Lord's intention of delivering Israel by his instrumentality, and which consisted in the extraordinary mode in which his offering was consumed, and in the miracle of the wet and dry fleece. In our text another sign still is afforded him; apparently to re-assure his courage after he had seen his army reduced to less than a hundredth part of the number which it consisted of at first, and when he was to attack with a band of three hundred men, a hostile army amounting one hundred and thirty-five thousand.

The general purport of the former signs which Gideon had obtained from the Lord, applied, according to their spiritual sense, to the states of mind in the regenerating subject during the state of temptation which is in general represented, was, as we have seen, to indicate the presence from the Lord of such states as to goodness and truth in the internal man, and thence in the external, as were adequate to enter into conflict with, and overcome, the evil lusts and false persuasions injected by the tempting powers into the external of the mind, represented by the Midianites and their associates. And the intention of the sign recorded in our text is, to discover what is the state of the evil influence, and to shew that having no longer the support it had in the man's own affections, it only requires to have directed upon it the sphere of divine power, resulting from the appropriation of celestial and spiritual things within, to be entirely eradicated, so as not to be able to lift up its head any more. The fact is, that the power of the evils and falsities which assault us in temptations is undermined, and in fact wholly destroyed, when that operation takes place which is represented by the throwing down of the altar of Baal, and the cutting down of the grove that was by it, and which we noticed in a former discourse: that is, when the evil that annoys us is removed from the supremacy which it exercised in the external man, so as no longer to be the chief object of regard, -- the god of our idolatry. Intermediate steps are still requisite, as all the intervening particulars of this history evince, before the power thus obtained in the interiors can be brought into contact with the evils themselves in the exteriors: but the power of these is from that moment gone, and their final removal is rendered easy and certain.

In the case before us, every thing was prepared in the interiors, by such a purification of the principles from which man was to combat, that nothing mixed itself with them but what was of the Lord alone, for the certain removal of the whole of the tempting influence: wherefore we read, "And it came to pass the same night, that the Lord said to Gideon, Arise, get thee down unto the host, for I have delivered it into thy hand:" which words imply a perception communicated from the Lord, but in obscurity, denoted by its being at night, because in the natural or external man, whose perceptions even when from the Lord, are called dreams and revelations by night, as being so much less clear than the perceptions of the internal man, which are represented by discourse with angels of the Lord by day, or open vision. It is remarkable that Gideon is first commanded to arise, and then to go down to the enemy's army; to indicate that in all conflicts with evils and falsities man is first to elevate his mind to the Lord, signified by arise, and then from this elevation to go down, with the state so acquired, into the region of the mind possessed by the opposing influence, as by this means only he can come into contact with that influence without entering into it or being affected by it. This may be illustrated by a case that may easily be conceived. Suppose a number of dissolute persons to be assembled in riotous enjoyment, indulging in the excesses to which the lowest part of our nature is prone. Let another person be introduced among them who is in the love of the same evils, but who was not in them at that moment, being attentively engaged in business or in something that otherwise occupied his thoughts: such a person, though the moment before he were acting like a sober moral man, would no sooner enter into the scene we are supposing, than his latent love for the same indulgences would discover itself, and he would immediately enter into the spirit of the dissolute party and become one of them. Just so would it be with man if he were to be admitted into temptations without being previously sufficiently fortified with principles of goodness and truth from the Lord, incapable of being influenced by the evils and falsities with which he would be brought into contact: these on the contrary would enter into him, would excite the evils of his nature, and he would presently feel himself as one with them. But if he is furnished with heavenly principles within, and keeps these in communication with their divine Source, by doing what is implied in the command Arise, he may then go down to the region of the evil influence with perfect safety: just as a man of fixed principles of religion and virtue might go without danger of contamination into a scene of dissipation, reprove the mad votaries of vice, and assist, if necessary, in bringing them before the magistrate, to be dealt with according to law.

The divine injunction proceeds to say, "But if thou fear to go down, go thou with Phurah thy servant down to the host, and thou shalt hear what they say: and afterwards shall thy hands be strengthened to go down to the host." These words shew how a perception is communicated from a lower principle in the mind to a higher -- that it is not by an influx from the lower into the higher, but by the higher descending with what is of itself into the lower, so as to become conscious of what is there passing. This is the reason that Gideon is commanded to take with him Phurah his servant, in order that he might hear the Midianites'
conversation; for servants always in the Word signify what is of the external man, which is or ought to be a servant to the internal; whence Gideon's servant Phurah denotes what is of the internal in the external, by which as a medium the internal can know what is the state of the external as to those things therein which are not of the internal. The state of the opposing influence is then described by its being said, that "the Midianites and the Amalekites and all the children of the east lay along in the valley like grasshoppers for multitude; and their camels were without number, as the sand by the sea-side for multitude:" which words are much the same as are used when the oppression by the Midianites is first mentioned, and which we briefly considered in one of our former discourses. They denote the total possession of the exterior region of the mind by thoughts of a trifling and merely external nature, originating in the delights of the merely natural man. Thus the Midianites and their associates are compared to locusts, because locusts denote the false apperceptions of the extreme of the natural principle separated from every thing interior: and their camels, which denote the common scientific principle of such false apperceptions, are compared to the sand of the sea-shore, because this denotes the most external and superficial intellectual views that can be conceived, such as tend to no sort of use, but are barren as the sand, of the sea.

"And when Gideon was come, behold there was a man that told a dream unto his fellow, and said, Behold, I dreamed a dream: and lo, a cake of barley bread tumbled into the host of Midian, and came unto a tent, and smote it that it fell, and overturned it, that the tent lay along. And his fellow answered and said, This is nothing else save the sword of Gideon the son of Joash a man of Israel; for into his hand hath God delivered Midian and all his host." These words denote the perception that is given to the evil, when the time of their influence draws to an end, and they are about to be cast into hell, that they can no longer be permitted to continue their infestations of the good, or to have any further communication with them. By a cake of barley bread, is signified a principle of truth grounded in goodness in the external man; -- or the presence therein of a real heavenly grace in such a form as is adapted to the genius and character of the external man. For as there are various principles in the human mind, which are all included in the two general divisions which, in the language of theology, first introduced by the apostle Paul, are called the inward and outward, or internal and external man; so are there divine graces communicated from the Lord adapted to replenish every faculty of man: or, in other words, the divine things of which he is the author appear under a different form according to the nature and quality of the faculty which receives them. Thus, for instance, what in the internal man is a pure love of goodness and truth, when it descends into the external man, especially into what has before been occupied by the evils of man's nature, becomes a strong zeal against all that is evil and false, -- an ardent desire and determination to cast them out. And this appears to be what is specifically meant by the cake of barley bread in our text: wherefore in the interpretation of the dream by the soldier's comrade, the cake is said to be the sword of Gideon, the son of Joash, an Israelite, which is clearly the power of a principle of truth grounded in good, flowing from the internal, wherefore it is called an Israelite combating against the evils and false sentiments of which the Midianites are representative. The operation of this principle is represented in the dream by its coming to a tent, and smiting it, so that the tent lay along, or was overthrown; which is a clear and beautiful representation of the deprival of the evils which before infested the mind, of all seat and abode therein. The Midianitish tent is clearly that in the mind which is the receptacle and dwelling place of the infesting and enslaving influence: to overthrow this, then, is to reject from within all that affords to the evil its harbour and habitation; which, when really done, the man is safe, -- not only delivered for the present, but, in consequence of the real change that has taken place within him, secured from ever being made the slave of that specific evil any more.

Again, then, we find in the circumstances of this history, matter of most beautiful as well as pleasing and animating instruction. They who are really intent upon their regeneration, shall, through divine aid, be completely delivered, though by successive steps, from the influence of every evil, be it what it may, which, by the corruption of human nature, has gained an abode in the heart. But to this end, they must co-operate with the will and efforts of the Almighty Deliverer. They must "arise;" -- elevate towards him every thing which, by the instructions of his Word and the operations of his Holy Spirit, they have received from him: They must, then, in this state of conjunction with the Lord, go down to the enemy's camp: they must apply with all the energy which is given them both to the exploration and the removal of the evils which would hold them for ever in bondage: And the consequence will be, that the evils they oppose, having no longer a root in the man's own affections, will become powerless; -- the cake of barley bread -- the sword of Gideon, will fall into the hostile camp, and smite the tent and overthrow it: -- the seat and harbour which evil had in the mind, which was in the unregenerate affections, will be entirely taken away; and instead of continuing the slave of Midian, the man will be devoted to the service of the Lord, whose service is perfect freedom, for ever.




