
<<<
---
== Chapter XVII. Judges 7:15-22

"And it was (so), when Gideon heard the telling of the dream, and the interpretation thereof, that he worshiped, and returned to the host of Israel, and said, Arise! for the Lord hath delivered into your hand the host of Midian. And he divided the three hundred men into three companies; and he put a trumpet into every man's hand, with empty pitchers, and lamps within the pitchers. And he said unto them, Look on me, and do likewise: and behold, when I come to the outside of the camp, it shall be, that as 1 do, so shall ye do. When I blow with a trumpet, I and all that are with me, then blow ye the trumpets on every side of all the camp, and say, (The sword) of the Lord, and of Gideon!
So Gideon and the hundred men that were with him came unto the outside of the camp in the beginning of the middle watch: and they had but newly set the watch: and they blew the trumpets and brake the pitchers that were in their hands. And the three companies blew the trumpets, and brake the pitchers, and held the lamps in their left hands, and the trumpets in their right hand to blow (withal): and they cried, The sword of the Lord and of Gideon! And they stood every man in his place about the camp. And all the host ran, and cried, and fled. And the three hundred blew the trumpets, and the Lord set every man's sword against his fellow, even throughout all the host. And the host fled to Beth-shittah in Zererath, and to the border of Abel-meholah, unto Tabbath."

Such is the account of the extraordinary conclusion of the oppression of Israel by the Midianites and their delivery by Gideon, every step of which is marked by such wonderful particulars. When I say, the conclusion of the history, I mean as to the decisive blow by which the deliverance was effected: for another chapter is filled with the details of the manner in which Gideon followed up his victory, which he did with such vigour and prudence as rendered the victory complete indeed, not a man of the immense multitude of the hostile forces making his escape, and the consequences being so decisive, that, as is declared towards the end of the next chapter, "Midian was subdued before the children of Israel, so that they lifted up their heads no more." The manner in which the rout of the Midianites was brought to pass, as related in the passage we have read, was equally extraordinary with the miraculous events which preceded and led to it; and the conclusion was worthy of the wonders by which it was brought about.

As we have made in our former discourses such general remarks as the occurrences of the history seemed naturally to give rise to, we will now without further preface offer a brief explanation of the principal circumstances related in the passage at present before us.

It begins with stating, that when Gideon heard the telling of the dream, and the interpretation thereof, he worshiped, and returned into the host of Israel, and said, Arise! for the Lord hath delivered into your hand the host of Midian. The dream which gave such confidence to Gideon and was that which he heard related by the Midianitish soldier, who dreamed that a cake of barley bread fell into the camp of the Midianites, and smote a tent, that it fell; which was interpreted by his comrade to be the conquering sword of Gideon. This, with the encouragement it gave to Gideon, represented the arrival of a state, in which the evil suggestions infused in states of temptation into the external of the mind, are perceived, both by the tempting spirits and the party they infect, to be without power, in consequence of their having no longer a connexion as before with man's interiors -- being no longer allied with a corrupt affection cherished by the man himself; and when also they are unable to resist the force of a directly contrary principle of goodness and truth descending from within and expelling them from their usurped establishment in the mind. It is evident from the whole of the history, that this state is brought about by the divine operations of the Lord, received and submitted to by man; and when it is produced, and not before, the actual conflict takes place, which terminates in the removal of the infesting influence. A perception in the interiors of the mind that such a state had arrived, is denoted then by its being said, "when Gideon heard the telling of the dream and the interpretation thereof:" the acknowledgment that it is the Lord's divine power and operations by which it is produced, is meant by its being said thereon, "that he worshiped:" and an elevation of state in consequence throughout the whole of the mind, implying an acknowledgment that all its power is from the Lord, with a direction of all its powers, under this acknowledgment, with full confidence, to the removal of the infesting influence, and of every thing still remaining that gives it a hold upon us, is conveyed in the words of Gideon to his forces, "Arise! for the Lord hath delivered into your hand the host of Midian."

We have observed, that the arrival of a state in which the tempting or infesting influence has lost its power, and thereby admits of being, with security, removed, is the result entirely of the divine operations of the Lord, and that, until its arrival, deliverance from the oppression of our spiritual enemies cannot be experienced: but though this is a certain fact, we should greatly pervert it if we were to draw from it any excuse for submitting or yielding to such oppression, or for being remiss in our efforts to obtain deliverance. There are many histories in the Word, beside this, which fully shew, that until a proper state is prepared, it is impossible to enter into the crisis of spiritual conflict, and that mischief results from bringing on this crisis without submitting to the preparatory states; but there is no passage which implies that it does not depend upon ourselves whether these preparatory states shall take place or not, and whether they shall be greatly protracted or not, in their succession. As before intimated, though much, and indeed the whole of our regeneration, is effected by the Lord alone, yet man's submission to, and reception of, those operations, is necessary to their taking effect. In temptations, the chief thing by which man can accelerate their happy termination, is by cultivating a disposition to search out in himself, and a willingness to part with, whatever it is that furnishes a base for the infernal influence to act upon: for Divine Omnipotence itself cannot remove any evil from man, till man becomes truly willing to let it go. In proportion then as man cultivates a sincere willingness to submit his will to the Lord's in all things, and to give up all undue attachments, whether it be to things absolutely evil, or which only are so when made the objects of too high a regard, so that the love of them holds a place which is only due to loves of a higher order; -- so far as man does this the Lord advances all the requisite states of preparation, and hastens the production of the state of which we have been speaking. The infesting influences that deprive man of the manifest perception of delight in divine things, with the infernals that inject them, being deprived of their power, are then ready to yield and depart, as soon as the sphere of the heavenly affections and truths which have been inseminated, and which have been gaining strength within, is brought to act directly upon them. The manner in which this is clone, is described in what we have now to consider.

Gideon then "divided the three hundred men into three companies; and he put a trumpet in every man's hand, with empty pitchers, and lamps (or torches) within the pitchers." We have seen in a former discourse, that the three hundred men to which Gideon's army was reduced, denote all such affections of goodness and perceptions of truth in the mind of man, as are wholly of the Lord, and which look to Him alone, undefiled by any contaminations from man's own selfhood -- all his motives, in short, and principles of action, that are altogether uninfluenced by any interested and selfish ends. These three hundred men are now divided into three companies, to denote the distinct arrangement of all heavenly graces, whether belonging to the order of goodness or of truth, according to the three degrees into which the mind of man is divided; in the third or inmost of which are all things that refer to the ends proposed by him, and which are of the will; in the second or middle are all things that refer to the means contrived by him for bringing his ends into effects, and which belong to the understanding, and in the first or lowest are all things that refer to conclusions or determinations to action, and which stand perpetually ready to embody themselves in acts whenever opportunity presents itself, and these are of the will and understanding in conjunction. There can be nothing whatever in the mind but what has relation to one or other of these three orders of principles: they include the whole that a man can be or that he can mentally possess: and on this account the number three, when mentioned in the Word, always signifies what is full and complete. It is on account of this its signification, that the number three has in all ages been supposed by many to possess some hidden charm or virtue; as it really did possess under the Jewish dispensation, when representatives of divine appointment were attended with power. This was the reason that the men by whom Gideon was to rout the Midianites, were exactly three hundred, and why these were divided into three companies. Had by any accident the number been different, or the companies otherwise divided, the miraculous effect which ensued on their blowing their trumpets and breaking their pitchers would not have occurred: for it is a great mistake to suppose that even miracles are wrought, and that by the Lord himself, at random, and without the use of any means whatever: the means He uses are, the disposal of things according to correspondences, or according to the order in which the spiritual world flows into the natural. But to explain this fully would require a discourse to itself: I only here mention it as necessary to enable us to discern the reason, why so many seemingly unimportant particulars were necessary to produce that panic in the Midianitish army, that set them upon destroying each other. Without some knowledge respecting the nature of the correspondence between spiritual things and natural, -- or at least respecting the existence of such a correspondence, all that is related respecting the mode by which Gideon's army was reduced to a small number, which number was exactly three hundred, -- the dream which Gideon heard -- the mode in which he directed his little baud to shew themselves to the Midianites, -- must appear like idle mummery, and the sincerest believer in the Scriptures, who confines his acknowledgment of them to the literal sense alone, must think in his heart that the miraculous effect which ensued might have been as easily produced in a much more summary manner. So that nothing but the views brought to light in the doctrines of the New Jerusalem Church, can satisfactorily clear up such passages as these even as to their literal sense; for no other views can furnish us with a reason why so many minute particulars were necessary to be observed, before the wall of Jericho, for instance, could be made miraculously to fall, and before the miraculous rout of the Midianites could take place.

I mention the case of the falling down of the wall of Jericho, because there was some similarity between the means employed to accomplish it, and the means resorted to by Gideon and his bands to confound the Midianites. The similarity consists in this, that there was in both instances a sounding of trumpets, and a shouting; though in the case of Jericho the trumpets were sounded only by the priests, and the shout uttered by the people was simply a shout without the use of words; whereas in the case before us all the people blew trumpets, and the shout which they uttered was the distinct cry, "The sword of the Lord and of Gideon." The sounding of trumpets was indeed directed to be used on all occasions, by one of the laws of Moses, in the conflicts between the Israelites and their enemies: the reason of course was, on account of the spiritual thing to which the sound of a trumpet corresponds, and which it therefore represents. It is, no doubt, from the same cause, that the trumpet has been appropriated to the use of war among all nations in all ages. It is true that the sound of it is extremely animating and exciting to the persons in whose behalf it is sounded, and has equally a tendency to appal and fill with dismay the ranks of the enemy; and these are the only causes commonly thought of for its use: it however is a certain fact that it derives these properties from a spiritual cause; or because it corresponds to something which has a tendency to give encouragement to the subjects of the Lord's kingdom in their conflicts with their spiritual adversaries, and to fill the latter with dread, causing them to seek refuge from its terrible effects on them in the caverns of despair. What it corresponds to then is, the revelation from the Lord through heaven of divine Truth of a celestial order, or such as is closely united with divine Good, and the influx thereof with resistless power from the interiors into the exteriors. The sphere of this has such an effect on the evil, who have nothing answering thereto in themselves, that they are filled by it with anguish and despair, -- have all the perceptions of their minds disturbed and thrown into confusion, the incoherence of their own perverted principles becoming manifest even to themselves, so that they immediately act like persons distracted, and are ready to flee 'any where to escape from its annoying presence.

But in the present case another and a more singular measure was . adopted to increase the confusion of the enemy: the Israelites carried empty pitchers in which were concealed lamps or torches: and at the same time that they sounded the trumpets, they broke the pitchers and displayed the lights to the astonished and terrified foe. The reason of this was, because pitchers, being vessels designed for the holding of water, correspond to what the New Church writings call scientifics, by which term are not meant deep attainments in what the world calls science, but merely things that are known without being much understood. Thus this history of Gideon, regarded as to its literal sense alone, is a collection of scientifics; and so in fact is the whole of the literal sense of the Word. The knowledge of such things in the memory, is denoted in the Holy Word by pitchers and all vessels for containing liquids; and thus the literal sense of the Word itself is also figured by these emblems. An empty pitcher, then, is the Word as to its merest shell or husk; or its literal sense viewed by itself, without any reference to the genuine truths it contains as brought to light by genuine doctrine, or by an acquaintance with its spiritual sense. To the Word thus closed, they who are in evils and falsities, and even infernal spirits themselves, have no objection, as there is nothing herein of sufficient power to disturb them in their falsities and evils; on the contrary, they can make the Word in this state seem to favour their views, by dwelling on those parts of it which are written according to mere appearances, and straining those parts in which genuine truths are plainly expressed in the letter, so as to make them seem to agree with the former, and thus falsifying the whole. There was nothing, then, in the mere empty pitchers capable of giving any alarm to the Midianites: to render the letter of the Word efficient for confounding those who are in evils and falsities, it must be seen in connection with its internal contents -- thus the genuine truth it contains must be brought forth and manifested, and this must be shewn to be the genuine doctrine of the letter itself. This then was represented by Gideon and his companions breaking the pitchers and displaying the lights concealed within them. That to break signifies to remove the shell of the letter and discover the genuine meaning, is evident from the manner in which the interpreting of the Midianitish soldier's dream is expressed in the original, which our translators thought so important that they have given it in the margin; according to which we find, that it is said, "when Gideon heard the telling of the dream and the breaking thereof:" -- a plain proof that, in the language of inspiration, to break a covering for the sake of disclosing what it covers, denotes to unfold the enigmatical and obscure form in which divine truth appears in the letter of the Word, and to discover the genuine truth and wisdom contained within. In the internal sense of the Word, and in the genuine doctrine of the church, which is framed indeed from the literal sense of the Word, but from the literal sense understood, -- that is, seen in connexion with the internal sense, divine truth is seen in the light; and this, as being incapable of being perverted by the evil so as to confirm their false persuasions, is seen by them as something directly contrary to them, fills them with alarm, and throws them and all their tissues of false reasonings into inextricable confusion. This, then, is what is in general meant by the lamps or torches concealed in the pitchers, and by the breaking of the pitchers to display them to the enemy.

In this circumstance, then, we have an example of the fact insisted on in the doctrines of the New Jerusalem Church, that in the conflicts of temptation man must combat by and with the truths of the Holy Word; and the reason assigned is, because, after all, it is the Lord alone that fights and conquers for man in temptations, wherefore nothing is valid to oppose the infernal influence but that in which the Lord Himself is, and the Lord is present with man in the truths of His own Word known and acknowledged by man. In these, indeed, He Himself is in all His divine fulness; wherefore, when these are connected in man's mind with the Lord, by being sincerely acknowledged and loved, and referred to the Lord their source, they possess a divine power within them which no infernal agency can long endure when brought into immediate contact with them. That combat in the concluding crisis of temptation is carried on the part of man solely by truths from the Word, seen and acknowledged in their genuine import, is plain from the account of the Lord's temptation by the devil, in which every infernal suggestion was repelled by Him by being opposed by a passage of the Holy Word. But that to be effectual for this purpose the Word must be understood -- that it must be the light of it, not the mere empty pitcher, is evident from the circumstance, that passages from the mere letter, perverted and misrepresented, were in a great measure the weapons with which the tempter carried on his assault: and the Lord's defence consisted in detecting the misapplication, and retorting the genuine sense, as conveyed in other passages, upon the would-be destroyer. This important doctrine, then, is conveyed in the circumstance, that the Israelites discomfited the Midianites by breaking their pitchers and displaying their lights within.

Another remarkable truth which the passage before us brings to light, is this; that after all it is not the Lord's divine truth that destroys the wicked, but their own evil lusts and false persuasions. All that the divine truth does when brought into immediate contact with those who are in such a state, is to discover that they are in evil lusts and false persuasions, and that therefore they cannot abide with those who are in goodness and truth; but what destroys them are these infernal principles themselves. This is expressed by its being said that on the blowing of the trumpets, the breaking of the pitchers, and the shouting by the Israelites; the Lord set every man's sword against his fellow throughout all the host; by which is specifically meant, that these doctrines and principles of life were such as destroy charity; which is the fellow or neighbour; and that whosoever is confirmed therein is in a state of spiritual death.

We see, then, brethren, from what has now been briefly and imperfectly offered, of what importance it is to be enabled to perceive the genuine light of divine truth within the outer covering of the letter of the Holy Word, and what power, for the successful prosecution of our spiritual warfare, is thus imparted to the candidate for a station in the heavenly Canaan. But it can only be exercised, and be made effectual, when Gideon possesses a band of three hundred men, of tried fidelity, who fully obey the Word of the Lord, and unhesitatingly do as he commands: that is, when a principle of genuine truth grounded in goodness is opened in the mind, accompanied with such a collection of truths and graces as are of the Lord alone, undefiled by any mixture with the selfhood of man. Such a state we must strive to attain; and the only way to attain it is, by submitting all our affections, thoughts, and actions to the government of the Lord and his Holy Word; putting away from them everything, however naturally dear to us, which He prohibits, ever turning from self and self-reliance, and learning to follow and rely on the Lord. So will the principles of truth and goodness received in our souls from Him, be purified from all selfish mixture; and being thus connected with the Divine Source, the light of divine truth concealed within the shell of the Holy Word in such histories as that before us, will shine with such splendour, and be applied with such power, that all our spiritual enemies will flee before it, and we shall be established in the Lord's kingdom, completely freed from the enthralling and infesting influence, for evermore.




