
<<<
---
== Chapter XVIII. Judges 11:30, 31

"And Jephthah vowed a vow unto the Lord, and said, If thou shalt without fail deliver the children of Amman into my hands, Then it shall be that whatsoever cometh forth of the doors of my house to meet me when I return in peace from the children of Amman, shall be the Lord's, and I will offer it up for a burnt-offering."

We have been engaged in some previous discourses, in an endeavour to give some insight into the spiritual meaning of the remarkable histories contained in the book of Judges. We have touched on the conflicts attending the final establishment of the several tribes of Israel in their respective lots, with which the book commences, and on the miseries attendant upon their disobedience to the divine commands in not utterly expelling the idolatrous nations from the country, and in imitating their idolatrous practices; particularly on the oppressions they successively suffered from the Syrians or the inhabitants of Mesopotamia, from the Moabites, from the Canaanites of Hazor, and from the Midianites, and on their deliverances by the instrumentality of Othniel, Ehud, Deborah and Barak, and Gideon. We intended in like manner to have pursued our observations through the remainder of the history of Gideon, and then to have proceeded to that of his degenerate, illegitimate son, Abimelech; whence, slightly passing over the pacific judges, Tola and Jair, to have dwelt in a few discourses on that of Jephthah; and so, again passing over the undistinguished judges, Ibzan, Elon, and Abdon, to have concluded the series with a consideration of the principal circumstances in the wonderful history of Samson. Circumstances however render it necessary to contract our course, and hasten to a conclusion. I therefore proceed at once to the history of Jephthah, as the next most interesting part of the sacred narrative; and, I have selected the most interesting circumstance in his history, usually known by the name of Jephthah's rash vow: on the literal import of which I now propose to offer some remarks, reserving its spiritual signification for another discourse.

There is no passage in the Holy Word which has been the subject of more controversy and discussion than this. Infidel writers, assuming it to be a fact that Jephthah's daughter was certainly offered as a burnt-sacrifice, have thought they have found a fail-occasion for railing against the divine Volume in which this is narrated, and for denying the divine origin either of the Jewish or of the Christian religion, as containing, among the documents on which they rest, a story so revolting to humanity. And expositors of the Scriptures have themselves been greatly divided in opinion as to the question, whether Jephthah's daughter was put to death or only devoted to a life of pious celibacy. Both of these classes of expositors have however shewn, I think quite satisfactorily, though abiding in the literal history alone, that there is here no room for the scoffs of the infidel, let the fact as to her being put to death or otherwise have been as it might. Although our chief object is to discover the spiritual instruction contained in the representative histories of the Holy Word; and though, likewise, after having examined the reasons urged by both classes of commentators for their respective opinions, I have found it difficult to arrive at a certain conclusion as to the real nature of the fact; yet on a question so celebrated it will no doubt be expected that I should offer some remarks.

It will first be necessary to detail the sequel of the history.

We find from the words which we have read as a text, that the vow of Jephthah was a conditional one: he said to the Lord, "If thou shalt without fail deliver the children of Ammon into my hands, then it shall be, that whatsoever cometh forth of the doors of my house to meet me, when I return in peace from the children of Ammon, shall surely be the Lord's, and I will offer it up for a burnt-offering." The condition, it appears, was accepted; for he defeated the Ammonites with a very great slaughter, insomuch that "they were subdued before the children of Israel." The narrative then proceeds, "And Jephthah came to Mizpeh, unto his house: and behold, his daughter came out to meet him with timbrels and with dances: and she was his only child; besides her he had neither son nor daughter. And it came to pass, when he saw her, that he rent his clothes, and said, Alas, my daughter! thou hast brought me very low, and thou art one of them that trouble me: for I have opened my mouth to the Lord, and I cannot go back. And she said unto him, My father, if thou hast opened thy mouth unto the Lord, do to me according to that which has proceeded out of thy mouth; forasmuch as the Lord hath taken vengeance for thee of thine enemies, even of the children of Ammon. And she said unto her father. Let this thing be done unto me: let me alone two months, that I may go up and down upon the mountains, and bewail my virginity, I and my fellows. And he said, Go. And he sent her away for two months. And she went with her companions, and bewailed her virginity upon the mountains. And it came to pass at the end of two months, that she returned unto her father, who did with her according to his vow which he had vowed." The relation concludes with saying, "And it was a custom in Israel, (that) the daughters of Israel went yearly to lament the daughter of Jephthah the Gileadite four days in a year."

If it were desirable to imitate the style of preaching that prevails in many fashionable places of worship, which consists in describing in a florid strain, natural objects or events, and in endeavouring to move the natural feelings, by dwelling with affected pathos on all such circumstances as will admit of such an appeal, there were ample room for it in speaking upon this story. Looking simply at the particulars of the narrative, and laying aside the consideration of its being part of the Word of God, there certainly is in it much that is calculated to interest our sympathy. What must have been the feelings of the father, returning in all the pride of triumph, saluted every where with the acclamations of his fellow-citizens, who hail him as the deliverer of his country, when, hastening to enjoy his honours in the bosom of his family, and expecting to find the sweetest reward of his labours in the ecstatic congratulations of the objects of his tenderest affection, he is at once plunged from the pinnacle of happiness to the abyss of misery, by feeling himself suddenly bereaved of the dearest of those objects; and this by his own rash act! when the over eager desire of his beloved daughter to welcome her victorious sire, makes her the first to rush into his presence; whereby she becomes the subject of that vow of sacrifice which he had inconsiderately uttered in a moment of great anxiety, little thinking who was to be its victim! Well might he utter the despair-fraught words, "Alas, my daughter! thou hast brought me very low! thou art one of them that trouble me!" Low indeed is he brought, and troubled indeed must he be: when, instead of being at liberty to enjoy the caresses of his affectionate child, to which he had just before looked forward as the consummation of his felicity, he finds himself bound to requite her tenderness with a grave! And a daughter so worthy of the fondest affection as she proves herself to be; -- so perfect a model of the purest patriotism, the most generous filial love! For how does she receive the sentence of her doom which she hears so unexpectedly pronounced? Does she fall into feminine lamentations? Does she remonstrate with her father on the injustice and cruelty of her fate? Does she use any entreaties to turn him from his purpose? Nothing of the kind. Her country is rescued from its oppressors, and her father is the honoured instrument by which the deliverance is effected. This is happiness enough for her. Having seen this, she is content to die; proud, perhaps, of being the victim whose promised sacrifice may have contributed to the desired result. She said therefore, "My father! if thou hast opened thy mouth unto the Lord, do to me according to that which hath preceded out of thy mouth; forasmuch as the Lord hath taken vengeance for thee of thine enemies, even of the children of Ammon." Certainly neither Greece nor Rome, with all their Leonidae and Decii, ever displayed an instance of sublimer self-devotion than this of Jephthah's daughter. Had it occurred among those boasting people, instead of the plain unvarnished tale of the sacred historian, we should have had it pressed on our admiration with all the pomp of eloquence. The greatest of orators and poets would have made it the theme of perpetual descant: and we should thus have learned from our school-boy days to speak of it with wonder. Nor would the steady resolution of Jephthah have passed unpraised. Indeed it cannot be doubted, had but he and his daughter been heathens, that the very men who now find in the transaction, nothing but a handle for vilifying the Scriptures, would then have extolled the whole as exhibiting the finest example of the most noble constancy, the most disinterested virtue. The mistaken views under which it could be thought that such a vow and such a fulfilment of it could be acceptable to the Divine Being, would have been spoken of as meriting our pity, not our contempt: and the immovable regard to principle, which in the father put in execution, and in the daughter cheerfully submitted to, so deplorable a catastrophe, would have been viewed as atoning for any error of judgment in forming that principle, and as exalting those who were capable of it to the highest rank among the worthies who have shed a lustre on the human race Such are some of the reflections which might naturally arise in our minds, on contemplating this history as to its literal sense alone: and certainly from this view of it alone, may be drawn a highly useful lesson for our instruction: for if a mistaken sense of duty could prompt these ancient Israelites to such a heart-rending mode of exhibiting their willingness to obey; if, under erroneous views of the nature of the Divine Being, they could persevere, in the discharge of an inconsiderate vow, to the completion of an act which must be as far from being agreeable to the Lord as to themselves: -- how ought we, who know what his beneficent nature really is, and what kind of service he requires, to render to Him this our "reasonable service," by striving daily to be more and more conformed to his will, which is the same thing as to become assimilated to his nature; and which we know, if it redounds to His glory, as the sole author of every thing good that can abide in us or proceed from us, redounds also to our own advantage, because it is the only means by which we can be qualified for the enjoyment of real happiness!

The remarks we have hitherto offered have gone chiefly upon the supposition, that Jephthah's daughter was actually put to death: upon the other hypothesis, that she was only consecrated to the service of the tabernacle and a life of celibacy, they would require some modification; though even this would be a sufficiently heavy affliction to an Israelitish parent who had no other child; nor would it be much less so to a female of that nation; amongst whom to remained unmarried, or if married to remain without children, was considered as the greatest of calamities. We are now, however, to state the grounds for these two opinions.

Certainly if we look simply at the history as it stands, we shall find it difficult to suppose that the affair had any other termination than what the terms of the vow so plainly express: and though in the conclusion, the sacrifice of the young woman is not explicitly detailed, yet this seems included in the assertion, that "her father did unto her according to his vow which he had vowed." This accordingly is the popular opinion on the subject, or of those who, without much study, draw their sentiments from our version of the Bible alone. But, as before intimated, the revilers of Revelation have eagerly laid hold of this pretence for their objections, contending that the God of Jews and Christians is thus represented as a God who is pleased with human sacrifices: and as reason clearly sees that these must be abhorrent to the nature of the true God, they infer that the true God and the God of Jews and Christians are not the same; of course, that those religions cannot be true. We shall see presently that even if we abide in the literal sense only, and give it the harshest interpretation, there still will be no room for this inference, which only argues ignorance on the part of those who make it: but it has helped to make commentators on the Scriptures very anxious to find room for understanding the relation in a different manner. Indeed the Jews themselves have led the way in giving a different interpretation; and it is after some of their Rabbies that many Christian expositors have adopted the rendering given in the margin of the English Bible; where, in the vow itself, instead of the words "whatsoever cometh forth of the doors of my house, &c., shall surely be the Lord's, and I will offer it up for a burnt-offering," we find, "whatsoever cometh forth of my house -- shall surely be the Lord's, or I will offer it up for a burnt-offering;" -- the disjunctive particle or being used instead of the copulative and: and the meaning of Jephthah is supposed to be, that whatever came out of his house, if a human being, should be consecrated to the Lord, and employed in some ministration in his tabernacle, and if a clean beast, should be sacrificed. Accordingly they conclude that the former was the fate of Jephthah's daughter; in agreement with which view, for the word lament, in the last verse, they substitute to talk with, as our version also gives in the margin; so that instead of reading "the daughters of Israel went yearly to lament the daughter of Jephthah," they would have "the daughters of Israel went yearly to talk with the daughter of Jephthah." This latter alteration, I believe, (as far as I have been able to search into it,) the Hebrew original will very well admit. It is also certain, that the Hebrew particle which generally acts as the copulative conjunction, sometimes bears a disjunctive sense, and instead of meaning and must be translated or: but I certainly do think it has been fully proved, that Jephthah's vow is not one of the passages which will properly admit of the latter signification, but that this is one of the cases in which, according to the universal rules of the language, the signification of and must be retained.

These are the chief critical points on which the advocates of the opinion that Jephthah's daughter was not put to death, found their belief; but they also support it by arguments of considerable weight of a different nature. Thus, they observe, that nothing was more strictly prohibited by the laws of Moses than the offering of human, sacrifices, either to false gods or to Jehovah, and that therefore such an abomination could never have been contemplated, much less practised by an Israelitish general who was especially assisted by Divine Providence to deliver his country: that had he nevertheless been ignorant enough to wish to do so, it was again commanded by the Levitical law that sacrifices should nowhere be offered but before the tabernacle, and by no person but the priests; and that certainly no priest could be found to offer such a sacrifice, especially at the tabernacle, where he was under the immediate inspection of the high priest, who also frequently officiated himself. And that females were employed about the tabernacle in works suited to their sex, is evident, it is urged, from the Midianitish female captives taken in war in the time of Moses, (Num. xxxi.) of whom, as of the rest of the spoil, a portion amounting to thirty-two in number, was set aside for an offering to the Lord: this also, it is stated, further appears from the last of Leviticus, where the law is given relating to the making of singular or personal vows, which mention both males and females. These are the chief considerations urged in favour of the opinion that Jephthah's daughter was not actually sacrificed: and certainly they carry so much appearance of probability, that we cannot be surprised if they were in general, and for a long time, deemed conclusive.

In support, however, of the popular notion, that this devoted female was really put to death, arguments not less strong have been urged by the most learned modern writers. We have already seen that the plain meaning of the literal account is much more consistent with this opinion than with the other. The writers alluded to found their chief argument on the fact, that it never entered into the head of any Israelite to look upon a state of single life, either in male or female, as more pleasing to the Lord than a state of marriage, and that, on the contrary, all their notions of the subject ran decidedly the other way; that men who were dedicated to the service of the Lord, or of the tabernacle, did not on that account remain single, is evident from the cases of Samson and Samuel, who were devoted in this way from their birth, and who both were married; whence it is inferred that the case would be the same with females who might be similarly devoted. That human sacrifices were strictly prohibited by the Levitical law, as also the slaying of any sacrifices by any but the priest, or any where but before the tabernacle, is indeed certain; but that many irregularities took place in all these respects is well known, and even that the Israelites often shewed a monstrous propensity to imitate the Canaanites in sacrificing their children; whence it is argued that Jephthah was more likely to adopt this course with his daughter, being a thing of which he had seen or heard of many examples, than to make her a nun, of which it is supposed he could have seen no example. It is further contended that he was just the sort of man likely, through ignorance, to fall into such errors; being, as is related at the beginning of the chapter, the son of a strange woman, and on that account driven in his youth by his relations out of the country, whence he resorted for subsistence in a foreign land, to the desperate expedient of becoming the captain of a band of freebooters; -- situations these which certainly were not likely to introduce him to a correct knowledge of the laws of Moses: and though there is no reason to suppose that he ever was an idolater, it is probable enough that he worshiped Jehovah much in the same way as the idolatrous people among whom he dwelt worshiped their deities. Besides the land of Gilead, of which Jephthah was a native, was at all times a country in which the greatest irregularities in the observance of the strict Mosaic law prevailed; it being a country situated on the other side of Jordan, at the greatest distance from the seat of the Tabernacle, the great centre of the Israelitish laws and worship. That Jephthah's knowledge of the Mosaic law was very scanty indeed, is certainly evident from his putting his vow in execution in any way whatever. If he conceived himself bound by it to put his daughter to death, he shewed himself ignorant of the laws which prescribe that only certain clean beasts and birds, and but a few kinds of them, should be offered in sacrifice, whilst, for this purpose, a human being was considered as of all things the most unclean, so to burn human bones upon an altar was a method resorted to as defiling it in such a manner, that it never could be used for a sacred purpose any more; and if he conceived himself bound by his vow, to devote his daughter to the service of the tabernacle, without being able to revoke it, as it is plain he did by his saying, "I have opened my mouth to the Lord, and I cannot go back;" he displayed equal ignorance; as there is an express statute in the last of Leviticus, empowering the person who might have made such a vow to redeem the devoted party for a sum of money.

All the circumstances, then, considered, many things might be regarded as pardonable in a man so uninformed as Jephthah, which, in a person who had better opportunities of information, would be utterly inexcusable.

But, as before intimated, even if it were certain, as it appears probable, that Jephthah did sacrifice his daughter, they who think this affords any ground of reproach against the divine origin of the Israelitish or Christian dispensations, only prove their own ignorance by the assertion. If indeed the laws of Moses gave any sanction to the practice of offering human sacrifices, and Jephthah only acted in conformity with the laws, then indeed the objection would be well-founded; but if, as already observed, the Levitical laws represented such sacrifices as in the highest degree offensive to God, and Jephthah, supposing he offered one, did it, not in obedience to those laws, but in ignorance and violation of them; then the whole case is reversed. It was to the false god Molech, principally, that children were sacrificed as burnt-offerings; on which subject we read in Lev. xviii., "Thou shalt not let any of thy seed pass through the fire to Molech, neither shalt thou profane the name of thy God." In ch. xx. the punishment of death is decreed against those who should do so: and the most awful denunciations against it are repeated over and over again: -- thus, "Whosoever he be of the children of Israel, or of the strangers that sojourn in the laud, that giveth of his seed unto Molech, he shall surely be put to death; the people of the land shall stone him with stones. And I will set my face against that man, and will cut him off from among his people; because he hath given of his seed unto Molech, to defile my sanctuary and to profane my holy name." And that they should not introduce such horrid rites into the worship of the Lord, because most hateful to him, is expressly commanded in Deuteronomy xii., "When the Lord thy God shall cut off the nations from before thee, whither thou goest to possess them, and thou succeedest them, and dwellest in their land; take heed to thyself that thou be not snared by following them, after that they be destroyed from before thee; and that thou enquire not after their gods, saying, How did these nations serve their gods? even so will I do likewise. Thou shalt not do so unto the Lord thy God: for every abomination to the Lord which He hateth, have they done unto their gods; for even their sons and their daughters they have burnt in the fire to their gods." It is impossible for language to express more strongly the divine abhorrence of such practices: If then Jephthah fell into any thing of the kind, it is evident that he did it through ignorance; and no imputation can lie against the law itself for his unwitting breach of it.

On the whole then, it appears next to impossible to decide with certainty the much agitated question, whether Jephthah's daughter was put to death or not. I incline after all to think myself that she was not, because I think it possible that although the males specially dedicated to the service of the tabernacle were allowed to marry, this might not be the case with the females: at least I think this point not fully proved. But to go into all the minutiae of this question, would be out of place in a sermon; and I have done so rather largely in a published work. [The Plenary Inspiration.]

Though I have now confined myself to the literal sense of this remarkable history, I trust the observations suggested are calculated to have their use, tending, as they have done, to vindicate the Word of God from objections, and to evince that, whatever might have been the merits or demerits of Jephthah's behavior, nothing that was wrong in it was imputable to a Divine origin, or to an alleged divine authority. But looking at the transaction as proceeding from a man little informed on divine subjects, and acting from notions universally prevalent in those times, we see much to admire, and much that, it is easy to believe, might be made the ultimate basis of truly divine instruction. At any rate, there is nothing but what is admirable in the conduct of the daughter. If patriotism is a virtue, (and the love of our country is ranked by the doctrines of the New Church, amongst the very highest forms of charity,) then, in this respect, both father and daughter exhibited virtue of the most sublime order; and, in the daughter, this was unalloyed by the slightest drawback. Such self-devotion, such disregard of every selfish feeling, is admirable in the highest degree, and worthy of being held forth as a most ennobling example: and whoever shall so far imitate it, as to be ready, on any suitable occasion, to make a corresponding sacrifice of self and of selfish inclinations for the good of others, is sure of a state of dignity in the kingdom of the Lord.




