
<<<
---
== Sermon XIX. Judges 11:30-31 (Part 2)

"And Jephthah vowed a vow unto the Lord, and said, If thou shalt without fail deliver the children of Amman into my hands, Then it shall be that whatsoever cometh forth of the doors of my house to meet me when I return in peace from the children of Amman, shall be the Lord's, and I will offer it up for a burnt-offering."

In our former discourse upon these words, we confined ourselves entirely to their literal sense, offering first such reflections as might naturally present themselves, if we look at them as containing, in connexion with the context, a simple history of an extraordinary instance of self-denial on the part of Jephthah, and of self-devotion on the part of his daughter: and in the second place, giving a view of what has been offered on both sides in the discussion of the celebrated question, Whether Jephthah's daughter was actually put to death, or whether she was consecrated to the Lord in some other way: and we finally shewed, that even upon the supposition of her being really sacrificed, they who infer from it an argument against the truth of the Scriptures and of Revealed Religion, prove by it nothing but their own ignorance; since nothing can be more decisive than the language in which the offering of human sacrifices, under any pretence whatever, is prohibited in the Mosaic law, as being the most hateful of abominations; whence, if it were even, certain that Jephthah's daughter was so sacrificed, the blame of it would lie, not on the laws of the Israelitish dispensation, but on the ignorance of Jephthah and his countrymen, of the remote part of the territory beyond Jordan which was the scene of the whole transaction.

In noticing the arguments that have been adduced in support of each side of the question respecting the reality of the sacrifice or otherwise, we found it necessary to observe, that after all the labours of the learned men who have investigated the subject, it did not appear possible to pronounce with any degree of certainty what was the case with respect to that historical fact. But although it appeared to me that they who are of opinion that Jephthah's daughter was put to death, have the strongest side of the argument; and though likewise it really seems difficult to imagine otherwise from the relation as it stands; I stated that I nevertheless inclined to think, for my own part, that her life was preserved. My reason for forming this opinion is this: that although it is very possible that Jephthah might not have a sufficient knowledge of the Mosaic law to be aware, that he was not bound by that law to perform his oath literally, when his daughter must, by adhering to the terms of his vow, be the victim, and might therefore, if left to himself, through mere ignorance, perform this dreadful immolation; yet as he allowed two months to intervene before he proceeded to put it in execution, and no doubt it must, during that time, be the subject of conversation all over the country, it seems hardly possible that this should not have afforded opportunity for his receiving better information. This indeed was time enough for the news to be carried as far as Shiloh, to the high priest himself; who, if he had heard of it, would doubtless have exerted himself to prevent its taking effect. I am aware that this may be replied to on the same ground that it has been argued, that Jephthah had not the opportunity, if he would, to send his daughter to the tabernacle to be there employed in some subordinate ministrations, because this was then at Shiloh in the tribe of Ephraim, and there was at this time a war between Jephthah and the Ephraimites, as appears from the next chapter: but this is sufficiently answered by the well-known fact, that whatever dissensions and wars there at any time existed between the several tribes of Israel, they never impeded each other in their journeys to perform the ceremonies of religion at the tabernacle or temple, where every male Israelite was required by the law to present himself three times in a year, on which occasions a truce took place and was religiously observed. It appears then that during the two months that were allowed to this generous young woman to prepare for her fate, her father must have learned, that her death was not only not required by his vow, but was in the highest degree illegal, -- that he was not only at liberty, but that it was his duty, to redeem her at the price of thirty shekels; information which, we are sure, must have been in the highest degree agreeable to him, and must have effectually prevented the human sacrifice from taking place. But if so, why is not this stated? Why, it may be asked, is the history couched in such terms, as seem at least strongly to imply that the dreadful ceremony was performed, when a statement to the contrary would be so agreeable to the feelings of every one who reads it, and would have obviated the objections which are thence urged, with some degree of plausibility at least, against its holy nature? The only satisfactory answer that can here be given is, Because the things treated of in the internal sense, for the sake of which alone the letter is written, could not have been expressed unless this appearance had been preserved.

But perhaps this answer may at first be thought to render the matter still more obscure. It may be asked again, If human sacrifices were in fact the greatest abominations that could be offered to insult the majesty of heaven, and strictly prohibited in the divine law on that account, how can it be necessary that an. appearance of one having taken place should be suffered to occur in the letter of the Word? -- especially when it is evident that it is not done to represent any thing profane and unholy, but the contrary? We answer, For the same reason as it was necessary for Abraham to believe that it was required of him by the Lord that he should sacrifice his only son, Isaac, through whom alone the promise of his becoming the father of many nations, was to be fulfilled to him, and to act under the influence of this belief so far as to "stretch forth his hand and take the knife to slay his son." It is true that in the case of Abraham, an angel was then sent to stay his hand, and a ram caught in the thicket was substituted instead of Isaac: but it proceeded far enough to show, that the offering up of a child, taken only in one point of view, has a holy signification, though taken in another it is the height of profaneness. The same may be concluded from the circumstance, that by the Levitical law, the first-born of every thing was considered as belonging to the Lord: hence, if it was a clean beast, it was to be offered in sacrifice; if an unclean beast a clean one was to be substituted for it.

One is apt at first sight to wonder how so horrible a superstition, so repugnant to some of the strongest feelings of human nature, as the sacrifice of human victims, and especially of children by their parents, could ever have been tolerated among mankind for a moment, -- much less could have been so constantly and extensively practised, among various nations of antiquity, as history assures us was the fact. Even the Greeks, so celebrated for their literary attainments, were not untainted with it: we have all heard of the sacrifice of Iphigenia the daughter of Agamemnon, the chief of the princes who went to the siege of Troy, and the commander of the whole armament, as the only effectual expedient for procuring a fair wind to waft their navy thither. We are told that it was practised, to an enormous extent among the original inhabitants of this favoured island of Britain, it being customary in the worship of the Druids to construct great idols of wicker work, and to fill them with human victims, which were all consumed together. That similar customs were common among the original inhabitants of Canaan and the surrounding nations, especially in the worship of Molech the idol of the Ammonites, is evident from numerous passages of the Holy Scriptures; and as the war in which Jephthah uttered the vow in obedience to which he is supposed to have sacrificed his daughter, was against this nation of sacrificers of their children, there can be little doubt that it was on account of the necessity that every evil must be combated from an opposite good, and that the principle of the mind in which the evil resides, is only brought into order by the introduction into it of the good suited to its nature instead of the evil removed: wherefore as the Ammonites represent those who are in the evil and false principle that is represented by the sacrifice of children to Molech, they could only be overcome by the good and truth of the same general character, represented by an apparent sacrifice of a daughter to Jehovah. At present however we are only adverting to the commonness of the practice in ancient times of sacrificing children, and to the multitude of nations by whom it was practised; and certainly the land of Canaan and surrounding countries, seems to have been the great centre from whence this horrid worship was propagated to other countries." It is known that the Canaanites were the same people as were called by the Greeks, Phoenicians; and ancient authors fully corroborate the Scripture accounts of their devotedness to the sacrificing of their children. It is known also that the Carthaginians, long the rivals of Rome, were Phoenicians or Canaanites by descent; and their addictedness to the practice is also well known. An ancient historian, speaking of their conduct at a time of national calamity, says, "They considered the wrath of their god Saturn as one cause of their misfortunes. For instead of sacrificing to him, as formerly, the sons of their most distinguished citizens, they had for some time been in the practice of buying boys privately, whom they brought up, and then sent as offerings: and now, when an inquiry was made into the matter, it was found, that some of those sacrificed had been substitutes of this description; -- that is, had not been sons of persons of distinction, but purchased slaves, represented as their children. When therefore they saw the enemy before their walls, they upbraided themselves in their hearts, for having in any measure departed from the religion of their fathers; and by way of making atonement, they sacrificed two hundred boys for the state, taking care to select those of the first quality for the purpose. Beside these, there were given up for sacrifice three hundred impeached persons, -- that is, persons accused of having shunned the sacrifice themselves, and of having allowed bought slaves to be substituted in their room. There was at Carthage a brazen image of Saturn, which let its open hands down to the ground, and threw the children that were laid upon them into a pit full of fire." I have introduced this shocking recital, in order to show, more fully even than appears in the Scripture history, to what an extent the practice of immolating their children prevailed among ancient nations. The sentiments which the contemplation of it is calculated to excite certainly are, compassion for the innocent victims, and disgust for the frightful superstition which could thus arm the hands of parents against their offspring, and overcome the strongest and best feelings of human nature; and though it is difficult not to extend our abhorrence of the practice to those who were so debased by it as to become the agents in these horrible tragedies; yet, whatever share of this feeling is justly due to the priests who introduced and enjoined it, perhaps the unhappy parents were more properly objects of pity; as it is evident that they did it in violation of those tender feelings of which they were not destitute, and in obedience to an overpowering sense of duty -- a principle that is respectable even in its errors.

But what can be the reason, that a practice which had every principle of natural feeling and common sense in such direct opposition to it, could ever, in spite of these, obtain such an extensive influence? I apprehend, because as before intimated, regarded in one point of view only, it was seen to have a holy signification; whence it got into use to the disregard of the other point of view, which ought never to be forgotten, when any thought was entertained of proceeding to the act, and in which, when actually performed, it must be seen to be in the highest degree profane. Indeed it is certain, that many of the most detestable practices that have ever prevailed among mankind, were the perversions of something intrinsically good; agreeably to that old and very true maxim, "the corruptions of the best things become the worst."

It is well known that the sacrifices directed in the Levitical law, and indeed many other of the customs introduced into that law, were not institutions given for the first time by Moses, but had long before been observed among the eastern nations; all that was done by Moses respecting them was, to limit the animals that might be offered in sacrifice, to certain species, and to prescribe exactly the manner of offering them. Now whence could this previous introduction of sacrificial worship originate? whence, but because it was perceived by the people who first introduced it, whoever they were, that hereby might be represented the pure worship of the Lord, and that this representation of pure worship might at the same time be accompanied with pure worship in him who offered it, provided he was aware of what his offerings represented. For the people of those ancient times were well skilled in what we call the science of correspondences -- that is, they knew the relation that subsists by creation between natural things and spiritual, which is such that all natural things derive their origin from certain spiritual things; for these, when exerting an influence in a sphere below that in which they are themselves, give birth to natural things which are representative of themselves, and which may indeed be considered as themselves embodied and made visible in a natural form. Thus there is between natural things and spiritual a certain constant and immutable relation, analogy, or correspondence; the natural thing answering to, and being a proper representative image of, the spiritual, as the reflection of a figure in a mirror answers to, and is an image of, the substantial object that produces it. All this was thoroughly understood in those ancient times: of course the people of those times well knew to what affections the various animals correspond: they knew that a lamb is a representative of love and innocence, a sheep of charity, an ox of good natural affections; and so on: and as they also knew that all genuine worship of the Lord essentially consists in an elevation to him of all the affections and perceptions of the heart and mind, they also knew that this might be represented by the offering of animals in sacrifice; the burning of which upon the Lord's altar, was representative of the acceptance by him of the affections from and with which man approaches him in worship.

But while the men of those times continued in the clear and full perception of what was represented by the various animals and other objects in nature, they also knew that the only real part even of representative worship, was the offering to the Lord of the inward states of mind which the animals represented, and that in the sacrifice of the animals themselves there was nothing pleasing to the Lord, but rather the contrary, as it is attended with suffering, which, even when endured by, and inflicted on, an animal, is abhorrent to the will of Infinite goodness. Whilst then the men of those times remained in their wisdom and in the undefiled worship of the Lord, they indeed talked of this worship as of sacrificing animals, because this gave them fuller ideas of the subject than they, owing to the peculiar genius of all who lived before the coming of the Lord, were capable of attaining by any other mediums. But they were content with thus offering to the Lord, as the prophet, says, the calves of their lips, that is, they offered to the Lord the affections represented by the calves and other animals used in sacrifices, in their prayers and praises, meant by the lips, without sacrificing the animals themselves. But when a generation of grosser minds afterwards arose, -- of men who were more immersed in sensual and carnal things, and who thence had not such clear perceptions of what was meant by this kind of discourse and of purely spiritual worship, they began to think it necessary to put to death the animals themselves; just as a Roman Catholic, to strengthen his conception, when in worship, of the Lord Jesus Christ, thinks it necessary to have a crucifix before his eyes: and as they who did this retained some, though an obscure idea of the spiritual things represented, the use of actual sacrifices was permitted, as necessary to keep this alive. It was from this cause that sacrifices were permitted, and apparently enjoined, to the children of Israel. Properly speaking they were not enjoined them, but only the manner and occasions of offering them directed, since they were in the practice of using them long before: and the reason why they were permitted to continue them, under certain regulations, was, because, though the Israelites never knew any thing of the spiritual things represented by them, yet the sacrifices affected them with a sense of holiness, and kept them in some kind of worship, of which otherwise they would have been incapable; at least, if not allowed in this manner to worship Jehovah, they would have plunged into all the idolatries of their neighbours. But the ultimate reason was the same as that of the calling of the Israelites altogether: that under the descriptions of representative worship thus recorded in the Divine Word a future church might, without returning to the practice of such worship, learn, by a knowledge of the spiritual things represented, how to offer to the Lord a purely spiritual worship, to consist in the consecration to Him at all times of all the faculties of the heart and mind, and in the ascription thereof to Him, at stated times, in prayers and praises, in their public assemblies. It is for the same reason that a kind of bloodless sacrifice is continued among Christians in the bread and wine of the Lord's supper; in which are represented, in one complex, all the varieties of good and truth in worship, that were denoted by all the varied symbols of the Levitical institutions.

From this view of the subject it may clearly be seen, that there may be forms of speaking and writing according to representatives and correspondences, which would be exceedingly criminal if reduced into acts. We find that even the slaughter of animals is something that, in itself, cannot enter with strict propriety, into the worship of the Lord, although to describe his genuine worship by images thence derived is highly useful and expressive. So it is, in a much stronger degree, when the subject of the sacrifice is considered to be a son or a daughter. If the animals allowed to be sacrificed were representative of certain principles in the mind of the offerer, dedicated by him to the Lord, his own children must be representative of principles in his mind still more closely connected with him, and which, to render his conjunction with the Lord complete, ought by no means to be withheld from Him. They must represent the proper affections of his own will, the proper perceptions of his own understanding, which, unless surrendered to the Lord, are the affections and perceptions of his own selfhood. It was on this account that Abraham, by whom is represented the celestial man, was tried as to his willingness to offer Isaac; and when he had complied, the reason assigned by the Lord for the blessing then pronounced upon him was, "Because thou hast not withheld thy son, thine only son, from me." Thus it is evident, that in the language of correspondences, to speak of sacrificing children to the Lord, only means to devote to him the inmost affections of the heart. In this point of view, then, and when suffered to go no farther than to words, the sacrifice of children was clearly representative of something pre-eminently holy. The reason is, because, in this point of view, the children are not regarded as having any thing, not even life, of their own, but are viewed merely as the absolute property of the parents. Hence no doubt, among the ancient people, who used to speak of sacrifices without performing them, the sacrifice of children was often mentioned: and thence their ignorant and corrupt descendants proceeded to the commission of the act. But this must necessarily be in the highest degree profane. For though for the sake of representation, children may be considered as the absolute property of the parents, yet in reality they are also human beings themselves, having a life independent of their parents, and to deprive them of which is murder of the worst kind: hence the act of sacrificing children, instead of representing the hallowing of our inmost affections to the Lord, represents the direct contrary, and denotes the privation of spiritual life in the nearest affections of the heart, and a complete enslavement to infernal bondage.

We see from the whole, that although there is a strong reason to conclude that Jephthah's daughter was not actually put to death, yet it was necessary that the literal account of the transaction should be so constructed, as to seem to indicate that such was the fact, because otherwise the holy and most important spiritual things intended to be conveyed in the internal sense, could not adequately be represented. And from the view which we have been enabled to take of what those spiritual things are, we see how indispensable it is that we should ever be ready to sacrifice our spiritual offspring to the Lord; that is, to devote to Him the very inmost affections and thoughts of our hearts and minds, -- the very inmost of our souls, -- whatever is derived from our inmost life, and is most closely and intimately identified with ourselves. Though the outward act of sacrificing children is most barbarous and profane, because they, as well as ourselves, live by a life communicated to them from the Lord as their own, and thus are not absolutely the property of their parents; yet the spiritual sacrifice, which, when only spoken of in words and not actually performed, such a sacrifice represents, is, as thus explained, a duty which we must be willing to discharge, and which will, in some stage of our regenerative progress be required of us all. May we ever be ready to dedicate all that we either are or have to the Lord, our Creator and Redeemer: so shall we be saved from all our spiritual enemies, and be permanently established in his heavenly kingdom.




