
<<<
---
== Chapter II. Judges 1:12-15

"_And Caleb said, He that smiteth Kirjath-sepher, and taketh it, to him will I give Achsah my daughter to wife. And Othniel the son of Kenaz, Caleb's younger brother, took it: and he gave him Achsah his daughter to wife. And it came to pass, when she came (to him), that she moved him to ask of her father a field. And she lighted from off her ass. And Caleb said unto her, What wilt thou? And she said unto him, Give me a blessing: for thou hast given me a south land; give me also springs of water. And Caleb gave her the upper springs and the nether springs._" (Judges 1:12-15)

We proceed in contemplating the singular history with which this Book of Judges begins -- that of the defeat of Adoni-bezek, who was afterwards made a miserable cripple, by the amputation of his thumbs and great toes. There is one part of this history, which, it has occurred to me, I scarcely touched upon in a manner sufficiently distinct; and that is, the remarkable confession which Adoni-bezek makes of the justice of the retribution which overtook him. "Threescore and ten kings," he exclaims, "having their thumbs and their great toes cut off, gathered their meat under my table: as I have done, so God hath requited me." Kings, wherever they are mentioned in the Word, denote, in the spiritual sense governing or principal truths, either genuine or perverted. Government properly belongs to Divine truth, according to the dictates of which, all kings are supposed to rule their dominions. The greatest enemies to monarchical power will admit, that the law is that by which the nation should be governed; and all law, so far as it is just, is founded in the Divine Truth. It is composed of regulations deduced from the eternal principles of order, and brought down into a form adapted to the condition of the people who are to be governed by it. Now kings, or the chief governors of nations, by whatever name they may be called, are properly the administrators of this law: and as the law is, or ought to be, founded in Divine Truth; and all its injunctions being so many particular truths; it is easy to see the propriety of mentioning kings in the literal sense of the Holy Word, as representatives of the divine truths of that Word, which are the eternal laws of divine order, designed for the guidance of the human race, both here and hereafter. The number seventy, which our translation, in the old English style of reckoning by scores, calls threescore and ten, is always used in Scripture, like the number seven, from which it is derived by multiplication, to denote what is pre-eminently holy, and particularly what has relation to the celestial and most holy principle of love to the Lord. When therefore Adoni-bezek, who represents the opposite of love to the Lord, which is the love of self, declares that he had cut off the thumbs and great toes of seventy kings, and reduced them to the slavery of depending for their subsistence on the refuse of his table, the meaning is, that so long as the love of self has the dominion in the heart, the most exalted truths of the Divine Word are deprived of their power, and are made subservient, in the mind in which this bears sway, to its low and unworthy purposes. And most truly indeed is this found to be the case where self-love has the pre-eminence, and is the governing motive of the conduct! In this state, whatever truths a man may know, they are not suffered to take their proper dignity as kings within him, but are deprived of all power, and if they are employed at all, it is only the better to carry on the object which self-love has principally in view -- that of obtaining power and influence, by enabling him to assume the appearance of a pious and upright character before the world. How happy then is the deliverance which is experienced, when Adoni-bezek himself is served as he had treated his victims, -- when the love of self is itself deprived of its influence; and the deep sense of its contrariety to every thing heavenly and divine, expressed in the acknowledgment which his sufferings wrung from him, is become the permanent conviction of every principle and power of the mind!

That the Holy Word contains in every part of it an internal or spiritual sense distinct from that of the letter, is a truth which cannot be difficult of reception by those, who believe the Sacred Scriptures to be the Word of God indeed. That such a sense should be contained in the prophets, and in all such parts as have an obscure or mystical air, can be surprising to none: but that the same should be the case with plain historical narratives, -- narratives which, though often recording very extraordinary things, yet are obviously meant to be relations of things actually transacted; -- this certainly is what few would, on first hearing the assertion, suppose. There is something inherent ia the nature of every thing presented as a narrative of facts, which chains the mind down to the facts related, and tends to prevent it from looking for any meaning beyond them. However, if the historical parts of Scripture are really the Word of God as well as the didactic and the prophetical, it is certain that the facts related, though actually transacted, cannot be all that is contained for the instruction of the pious mind: The facts themselves must be of a representative or typical character; and thus must be inwardly replete with spiritual instruction.

We have now selected for our meditation a history which is not less remarkable than the former, though the character of it is very different. No doubt all the particulars of it are also equally replete with heavenly wisdom, though it will probably not be so easy to make this apparent. The general subject is evidently respecting the union of goodness and truth, or of love and wisdom, which is effected in the mind, when evil loves and false persuasions are vanquished and removed; and respecting the increase of heavenly blessings which follows that union. But to obtain any clear views of the spiritual meaning of the relation, it is necessary first to have some acquaintance with the actors and the scene of it.

Caleb is here represented as proceeding to take possession of the inheritance allotted Mm as the reward of his fidelity, when, forty-five years before, he had visited this part of Canaan as a spy, to carry information respecting it to Moses and the Israelites in the wilderness. This we learn from the 14th and 15th chapters of Joshua. The history of the Spies and their report is recorded in the 13th and 14th chapters of the Book of Numbers; where we read that twelve spies, one selected from each tribe, were sent to explore the land then in possession of the Canaanites, of whom Caleb was selected from the tribe of Judah, and Joshua from the tribe of Ephraim. The report that they brought was, that the land was rich, but that the cities were strongly fortified, and the people of gigantic stature. When the children of Israel began to take alarm at this report, "Caleb," it is said, "stilled the people before Moses, and said, Let us go up at once, and possess it, for we are well able to overcome it." "But the men that went up with him said," (with the exception however, as the context shews, of Joshua,) "We are not able to go up against the people, for they are stronger than we." The consequence of this cowardice was, that the people were on the point of electing another leader to conduct them back into Egypt; wherefore the treacherous spies died immediately by a plague, and the people in general were sentenced to abide in the wilderness till the whole generation had died off. An exemption from these punishments was however made in favour of Caleb and Joshua. The conduct of the former, who seems to have been by far the most active in checking the madness of the people, is repeatedly mentioned with commendation. Thus the Lord says to Moses, "Because all those men which have seen my glory, and my miracles, which I did in Egypt and in the wilderness, have tempted me now these ten times, and have not hearkened to my voice; surely they shall not see the land which I sware unto their fathers; neither shall any of them that provoked me see it: but my servant Caleb, because he had another spirit with him, and hath followed me fully, him will I bring into the land whereinto he went, and his seed shall possess it." So again with respect to Joshua also, Moses was commanded to say to the rebellious Israelites, "Your carcases shall fall in this wilderness; and all that were numbered of you, according to your whole number, from twenty years old and upwards, which have murmured against me. Doubtless ye shall not come into the land, concerning which I sware to make you dwell therein, save Caleb the son of Jephunneh, and Joshua the son of Nun."

Now what can be represented by these two faithful spies, one of whom, as before observed, was of the tribe of Judah, and the other of the tribe of Ephraim? What but a principle of goodness and truth immediately and wholly from the Lord in the will and understanding of the regenerating subject? whilst the others, and all the rebellious Israelites, represent spiritual things received from the Lord in the will and understanding, but defiled by a mixture of the selfhood of man, and thus not of such a genuine nature as to be able to stand in the fiery trials of temptation. Of Caleb it is said, that he wholly followed the Lord; evidently denoting a principle of pure love received from him and undefiled by any selfish mixture. And that Joshua was equally approved, is evident from his being appointed to conduct the Israelites after the death of Moses; which clearly shews that he represents a principle of pure truth received from the Lord, and undefiled by man's self-derived intelligence. Thus they both may be regarded as representing the Lord Himself; Caleb representing him as to that Divine Goodness or Love with which he is present with man during his states of temptation; and Joshua representing Him as to that Divine Truth or Word by which He conducts man at the same critical period. That Joshua represents the Lord as to divine truth, and thence His divine truth in man's understanding, is evident from his being of the tribe of Ephraim, which always denotes the intellectual principle of the church; and that Caleb represents Him as to divine good, and thence a principle of good from Him in man's will, is evident from his being of the tribe of Judah, which represents the highest celestial principle, or that of love to the Lord, which lias its seat in the will. It is the characteristic of the celestial man to bring truths, as soon as he hears them, into the life, without first suffering them to lie inactive in the memory; and this we see represented in the promptitude of obedience, together with the ardent and fearless zeal, by which Caleb was distinguished: and this is also why he receives the high commendation of having fully followed the Lord. The Lord is never fully followed but when his whole will is obeyed without hesitation; and nothing but the celestial principle of love to Him can inspire such obedience.

From these considerations, then, it would appear that Caleb represents a principle of pure love or good, immediately from the Lord, in the inmost of the mind; but in order that it may accomplish all the blessed purposes for which it was designed, and in order, likewise, that man may enjoy all the blessedness which it is intended to impart, it is necessary that it should descend thence into the external of the mind also, and come fully into action throughout the whole man. This is what is represented by Caleb's taking possession of his inheritance in the land of Canaan, one of the cities of which was Kirjath-sepher: which, on being captured by him, through the valour of his cousin Othniel, changed its name into Debir. There are many instances of places changing their names on passing from under the power of the Canaanites to that of the Israelites; and no doubt there is always a good reason for it in the internal sense. In cases where the exact meaning of the names cannot with certainty be discovered, it will not be easy to see what is spiritually signified by the exchange: but the meaning both of Kirjath-sepher, and of Debir, is so distinct, that it is not difficult to see the reason for exchanging them. Kirjath means a city, and Sepher literally means a book; and Debir means a word or discourse. Thus the one means written and the other oral language; the one something dead, and the other something alive. All cities, in the Word, spiritually signify doctrines: by this city then, so long as it is called Kirjath-sepher, an inanimate book, is meant the doctrine of truth, such as is suited to the celestial man, so long as it remains a dead letter in the memory; but when it is called Debir -- living discourse, -- it denotes the doctrine of truth exalted into the life, so as to live within the man, as the spontaneous conclusions of his own understanding called into activity by a renewed will. And this change of name took place in this city when its wicked inhabitants were destroyed or driven out; to instruct us that our doctrines only acquire life, as the evil propensities and false persuasions, which naturally possess our hearts and understandings, are compelled to give way before the prevailing influence of heavenly affections and the genuine truths of the Lord's Word.

It would appear, too, that this takes place when, after both perceptions of truth and affections of goodness have been inseminated into the mind, they come into a strong desire for union. The stimulating cause of the taking of Kirjath-sepher is expressed by Caleb's saying, "He that smiteth Kirjath-sepher and taketh it, to him will I give Achsah my daughter to wife:" upon which declaration, "Othniel the son of Kenaz, Caleb's younger brother, took it." Here Achsah the daughter of Caleb, represents the pure affection of goodness in a lower region of the mind, derived from good that is immediately from the Lord in the higher; and Othniel the son of Kenaz, denotes truth from a celestial origin, combating with power against evils and falsities from the desire of conjunction with such affection. There is here also something remarkable in the original, that greatly adds to the beauty of the spiritual sense, which is not so perceptible in the English translation. "We might conclude, from the words of the translators, that Kenaz, whose son Othniel is said to be, was the brother of Caleb: but there are other passages which prove that he was the grandfather of Caleb. It is Othniel who is said to bo the brother of Caleb, not because he was Caleb's own brother, but because he stood in the same degree of relationship to their common ancestor, Kenaz; brother being a term which is used in Scripture not only to denote the sons of the same father, but all collateral relatives whatsoever: and the reason why it is here used is, for the sake of the spiritual sense, according to which, faith and charity, truth and goodness, love and wisdom, are called brethren to each other; wherefore, as Caleb represents a principle of celestial good, and Othniel truth from a celestial origin, he is properly denominated Caleb's brother. But what our translators have rendered younger, is properly "the least from him," namely from Kenaz, denoting not only the least in years but in importance and influence; which circumstance is mentioned to express the innocence of the principle represented by Othniel, denoting that such a principle of truth in the mind has no tendency to self-exaltation, but to humility and self-abasement, teaching him who possesses it, to regard himself as nothing, and the Lord as all. When in all our views of truth this innocent looking to the Lord is within, we shall be able, like Othniel, to overcome all opposition from self and the world, and the infernal hosts also, and to experience in the mind that union of goodness and truth in which are stored all the felicities of heaven.

And when this happy union has thus taken place, it will manifest itself in our outward man also, and will inevitably produce goodness of life as its result. This is implied by its being said, that "it came to pass, when she came (to him,) (or after the marriage,) that she moved him to ask of her father a field:" A field, as being without the city, denotes what is respectively external; and as it is ground in which seeds are to be sown, it denotes that good of life which is the proper soil for receiving the truths of faith, and becoming fruitful by their insemination. When the truth we have received from the Lord is united in the mind with a pure affection, for him, it will not always remain within the city, -- in the contemplation of doctrines, and in lifting the soul upwards in devout aspirations; but it will go abroad in oto the world in works of usefulness and benevolence, and will thus find a field for the display of such activities as a principle of truly celestial life and love in the heart, will always prompt to and inspire. It was Achsah too, the wife and daughter, that prompted the desire for this field, to shew that it is the love of goodness within that is the moving principle to works of beneficence. And Othniel, at her desire, asked it of her father -- of the Lord Himself, as the sole source of the good that can dwell within us. It will amount to much the same if we still consider Caleb as a principle of celestial good immediately received in the heart from the Lord: in which case, the asking by desire of Achsah, will denote a desire in the lower region of the mind, to be more conformed to, and replenished with, the pure love which the Lord has infused into the higher.

But now Achsah herself makes a request: and how did she proceed in doing so? She lighted from off her ass: by which is signified the separation of the mind from what is merely natural, that it may be in a state to perceive the good of the internal. Thus, to alight from the ass seems to represent something similar to the putting off of the shoe, which Moses was commanded to do when in the immediate presence of Jehovah: by which is signified the necessity of receding from a merely sensual and corporeal state, when elevating the mind to a perception of the Lord. An ass strictly signifies the intellectual principle of the natural man, which is necessary to be made use of when man is in active life, though it then must be kept in due subordination; but to alight from off an ass, is to be separated from this intellectual principle, and to come into the state of humiliation necessary for the reception of divine communications. Such communications are here represented as being consequent upon this state: for "Caleb said unto her, What wilt thou? And she said unto him, Give me a blessing; for thou hast given me a south land, give me also springs of water." The south is always mentioned in the Word to denote a state of intelligence, wherefore to have received a south laud as a gift from Caleb, denotes to be gifted with a state of intelligence from the Lord, as a consequence of possessing a principle of good immediately from him in the internal man: for nothing can impart a real principle of intelligence to the understanding, but a reception of goodness from a divine origin in the heart. Every one may have observed, that when a strong desire is felt to understand any subject from the real love of it, however intricate it may appear where there is no such desire, it then becomes easy: and there is no real love or desire for spiritual intelligence, but that which is founded in the love of practising those truths which spiritual intelligence discovers. The food however of all spiritual intelligence is truth from the Holy Word, and this is always represented in Scripture by wells or springs of water. And because in the state here represented, there is the requisite love or desire for the perception and enjoyment of these divine truths, therefore it is said that Caleb gave her the upper springs and the nether or lower springs; the upper springs are the streams of truth divine that flow from the spiritual sense of the Holy Word for the edification of the internal or spiritual man; and the lower springs are the stores of truth contained in the natural sense of the Holy Word for the edification of the external or natural man. Both are opened to those in whose minds goodness and truth are in a state of conjunction, or in whom the marriage of Othniel and Achsah has taken place. They are in continual communion with the Divine Caleb, -- with the Lord himself, -- and that good which is immediately from Him, in the inmost of their minds, and thus their souls are like a watered garden, whose waters fail not. Their minds are never destitute of themes of edifying contemplation, but in the spirit and letter of the Holy Word, they have the upper and lower springs that will cause their souls to produce new plants of paradise both here and hereafter.

Now although the circumstances related in this history are not miraculous, but, in part, of an apparently trivial nature, they certainly are such as would not have been put upon record in the Word of God, but for the sake of the spiritual things which are thereby represented. What historical interest belongs to such circumstances, as that Othniel asked for a field, and Achsah for springs of water? Yet when the signification of the field, and of the springs of water is known, how beautiful and important does the whole become! How full and complete are seen to be the divine gifts which are offered to the sincere seeker after spiritual life and blessing! Let us all, my brethren, be hereby animated to perform the part of a faithful Othniel. Under the impulse of a desire to obtain the pure affection of goodness to unite with our knowledge of truth, let us earnestly engage in the work of purification, and cast out every evil that lurks within our minds. So shall we find a field for the unrestrained exercise of a corresponding life; and the upper and the nether springs, -- the Holy Truth, internal and external, of the Divine Word, rendered living by a communication of life from the Lord, will fertilize our souls to every good product and heavenly thought, and we shall have an eternal inheritance in the heavenly Canaan.




