
<<<
---
== Chapter XX. Judges 11:30-31 (Part 3)

"And Jephthah vowed a vow unto the Lord, and said, If thou shall without fail deliver the children of Amman into my hands, Then it shall be that whatsoever Cometh forth of the doors of my house to meet me when I return in peace from the children of Amman, shall be the Lord's, and I will offer it up for a burnt-offering."

The circumstance here recorded being so much celebrated by all who have written on the history of the children of Israel, and having given rise to a question of which every one has heard, and in which all who have heard of it feel some interest; we have devoted two former discourses to a consideration of the literal facts, and of inquiries thence arising. In our first discourse we stated the arguments that have been advanced in favour of the supposition, that Jephthah's daughter was not actually put to death, and those by which this more pleasing view of the history has been replied to; when, we found, that although it is impossible to determine the matter with certainty, the particulars of the narrative, regarded solely in their literal sense, and the arguments deduced from them, give most sanction to the supposition that she was actually sacrificed. I, however, stated my own opinion to be otherwise, for which, in our last discourse, I gave my reasons; remarking also, that the reason why the letter was so framed as to favour the contrary conclusion, was, because the spiritual sense required that there should be an appearance that such was the fact, on which account the narrative is so constructed as plainly to point to this inference, although it is not expressly affirmed. For certainly, the sole design with which the Word of God was written, was, not to convey information respecting natural things but spiritual: and though the Jews were selected to represent spiritual things by their worship and the actions of their government, and of certain leading individuals, whence the occurrences related are in general strictly true, yet there certainly are some instances in which the historical narrative, though including an account of the circumstances true in some respect, is yet so partially constructed, as not to exhibit the whole truth; at least not on a superficial inspection; the spiritual sense requiring the mention of certain things, and perhaps the omission of certain others, without the knowledge of which the historical relation seems confused and obscure. And this seems likely to have been the case with this history of Jephthah and his daughter. But our last discourse was more particularly occupied with a view of the origin of sacrificial worship in general, and of human sacrifices in particular, which, though the highest abomination to the true God, were offered by many ancient nations to their idols.

It is, however, a matter of little consequence to us, beyond mere curiosity, whether Jephthah's daughter was preserved alive or not. We have before shown, that the truth of Revealed Religion is by no means dependent upon this fact, even if determined in the negative; because in this case the act was not committed under the sanction of the divine law, but in violation of it. Still Christians in general have thought, that the honour of religion was much compromised by the transaction, because Jephthah was an instrument raised up for the delivery of Israel, and was a prosperous commander and judge; and because no intimation is given of the illegality of his vow, or of any divine disapprobation in consequence of it. But if the honour of religion depended on the faultlessness of conduct of the characters distinguished in the Jewish history, it would be very difficult to maintain it indeed; as there is scarcely one of them whose conduct might be taken for the imitation of the Christian. To the best of them, many things were permitted because of the hardness of their hearts, as the Lord himself declares, which in the beginning were not so, and which he prohibits to the member of a true church, and not of the mere type of a church, which was all that the Jewish was. Many of their chief persons, even those most highly extolled in their typical character, to which alone the commendations of them are meant to apply, were guilty of acts in themselves enormously wicked: and David himself, the most distinguished of them all, in the deliberate murder of Uriah, committed a crime of premeditated wickedness, to which the cruel but not malignant or intentional error of Jephthah, even if brought into perpetration, would be comparatively innocent: for what he did proceeded from ignorance and a mistaken sense of duty; whereas David knew from the beginning that he was breaking the most imperative of the divine commandments. With what difficulties then are they embarrassed, in defending their religion, who believe the Jews ever to have been, personally, the peculiar favorites of heaven, the members of a true internal church: from which embarrassments, as we have occasionally shown, the member of the New Jerusalem Church is exempt, who believes the Jews only to have been a representative church, or even a representation or type of a church; in which case sanctity of private character was by no means necessarily implied, even in the persons who sustained the most holy representations. To us then it matters not, beyond the interest the story is calculated to excite, whether Jephthah's daughter was actually sacrificed, any more than it does whether Iphigenia, the daughter of Agamemnon, was actually sacrificed, or whether, as some authors affirm, she was at the critical moment conveyed away by Diana, to be a priestess in her temple, and a white hind miraculously substituted in her place. To us it matters not whether Jephthah was the man of enlightened piety which he is represented by some writers, or the ignorant barbarian assumed by others. But we will proceed to close our remarks on the history of Jephthah by a short view, as far as we are enabled to discover it, of the spiritual import of some of the principal circumstances recorded: only adding further to our prefatory observations, that no light is thrown upon the fact in dispute in the writings of the herald of the New Church, in which there does not occur a single quotation from any part of the history, or the slightest reference to it.

Although without more illumination than the church is at present in possession of, it may be difficult to trace the reason why the various oppressions and deliverances of the Israelites occurred in the order in which they are recorded, and why the judges who were the instruments of effecting those deliverances, succeeded each other in the progression that we find; yet one thing is so remarkable in this respect, and agrees so exactly with the information the New Church possesses respecting the meaning of the twelve tribes of Israel, that we cannot but be struck with the coincidence, and discover in it an additional proof of the truth of our doctrines upon this subject. It is this: that the judge who delivered Israel on their first affliction, from their enemies after they were settled in the land, and indeed the first of the series of governors who are properly called judges, was Othniel of the tribe of Judah; and the last of them was Samson of the tribe of Dan. Now Judah, we are informed, represents the highest principle in the church, called the celestial, and Dan the lowest, called the sensual; whence it is evident that the whole series represent a progression in order, through all the states that enter into the constitution of the church, or of the man of the church, from the highest to the lowest. Another striking coincidence or two may be mentioned: one is, that as the first judge was Othniel, of the tribe of Judah, so the second was Ehud, of the tribe of Benjamin: the reason of which no doubt is, because Benjamin is the external of the same general principle that has Judah for its internal; which also is the reason, when an entirely different state was represented under the kings, the order of which was to begin from the external and thence proceed to the internal, Saul, the first king, was of the tribe of Benjamin, and David, the second, of the tribe of Judah: and from the same cause it was that when the twelve tribes were split into two kingdoms, Benjamin alone, of them all, remained with the tribe of Judah. Another coincidence is observable in the facts, that Jephthah was the next distinguished judge that came after Gideon, and that Gideon was of that part of the tribe of Manasseh that had their inheritance within Jordan, and Jephthah was of the other half of the tribe of Manasseh that had their lot beyond Jordan: for it is said that Jephthah was a Gileadite, and Gilead was a country beyond Jordan which fell to the inheritance of one of the half-tribes of Manasseh. From this circumstance it is evident, that Jephthah must denote the external of the same general principle, as that of which Gideon is the internal. This fact, that he represents a principle that belongs entirely to the external man, will account for the want of legitimacy which is recorded of his birth, and for the disorder and violence by which, in the early part of his life, he seems to have been distinguished.

We read at the end of the preceding chapter, "Then the children of Ammon were gathered together and encamped in Gilead. And the children of Israel assembled themselves together and encamped in Mizpeh. And the people and princes of Gilead said one to another, "What man is he that will begin to fight against the children of Ammon? he shall be head over all the inhabitants of Gilead." Then begins the chapter of our text, taking up the history: "Now Jephthah the Gileadite was a mighty man of valour; and he was the son of a harlot: and Gilead begat Jephthah. And Gilead's wife bare him sons; and his wife's sons grew up, and they thrust out Jephthah, and said unto him, Thou shalt not inherit in our father's house; for thou art the son of a strange woman. Then Jephthah fled from his brethren, and dwelt in the Land of Tob: and there were gathered vain men to Jephthah, and went out with him:" -- that is, he became the captain of a band of roving freebooters, such as abound in that part of the world to this day. In this capacity he acquired such a reputation for military skill and courage, that the history proceeds to say, "And it came to pass in process of time, that the children of Ammon made war against Israel. And it was so, that when the children of Ammon made war against Israel, the elders of Gilead went to fetch Jephthah out of the land of Tob: and they said unto Jephthah, Come, and be our captain, that we may fight with the children of Ammon." Jephthah, after remonstrating with, them on their former expulsion of him from his father's house, consented to their request, on condition that, in case of success, he should be their captain and head; a solemn covenant to which effect was made before the Lord at Mizpeh. Jephthah then sent messengers to the king of the Ammonites, remonstrating with him on his unjust invasion, and desiring him to depart peaceably; and receives for answer a message from the king claiming a right to the country. To this Jephthah replies by a second embassy, shewing at length the injustice of the claim; but without any effect. "Then," it is said, "the spirit of the Lord came upon Jephthah, and he passed over Gilead and Manasseh, and passed over Mizpeh of Gilead, and from Mizpeh of Gilead he passed over unto the children of Ammon." Then he made the vow recorded in our text, attacked and defeated the Ammonites, and the other transactions took place which we noticed in our former discourses.

In all this history we find a remarkable contrast between the mode of proceeding to effect the expulsion of the Ammonites, and that which was observed to produce the defeat of the Midianites by Gideon; strongly exhibiting the difference in purity and in divine dependence, between goodness and truth of an interior kind, and such as are of an exterior kind. In the case of Gideon, the utmost caution was observed lest any thing of man should mix itself with the divine operations; in this of Jephthah, the whole seems to have been contrived almost by unassisted human prudence; except that the success appears to have been a consequence of the divine favour procured by Jephthah's vow. And his vow too was a conditional one, stipulating advantages for himself, or success in his enterprise, like that of Jacob when he said, "If God will be with me, and will keep me in this way that I go, and will give me bread to eat and raiment to put on, so that I come again to my father's house in peace; then shall the Lord be my God:" for such is interiorly the nature of all the worship of the merely natural man: he is content to serve the Lord, provided he is well rewarded for it; and he considers the happiness of heaven itself, when he elevates his mind so high, merely in the light of a reward, whence he does good not from the pure love of it, but from a motive of mere obedience, because he sees that his own welfare cannot be otherwise secured. And this motive even, low as it is, is accepted in such states by the Lord; for it is, in fact, the highest motive from which man is able to act in the commencement of his regeneration; and even when his regeneration is completed, there will always remain a principle in his constitution, though it will no longer be the highest or governing one, which finds in this motive its proper incentive to action. But the purification of this degree of the mind and life, the result of a previous opening and purification of higher principles, is represented by the whole of this history of Jephthah.

Jephthah is first described as a mighty man of valour, to denote a principle of truth in the external man that is powerful in reasoning in behalf of spiritual things, and strong in overthrowing opposing false persuasions: but he is said to be the son of a harlot, to denote that this does not originate in a pure affection, and is not the product of a legitimate conjunction of goodness and truth within. For in the beginning of his regeneration man makes himself acquainted with truths, and feels a delight in reasoning from and for them, under the influence, in a great degree, of merely natural affections, such as curiosity, the mere love of knowledge, without a supreme regard to use, and not from the genuine affection from which truth ought to be felt as delightful, which is, a love of the good to which it leads. While he is in this state, he is not a real member of the church, nor entitled to any inheritance therein; which is denoted by his brethren denying Jephthah a portion in his father's house. While in this state also he is in reality a spiritual robber; because he does not, in his heart, whatever he may do from doctrine, ascribe all his attainments to the Lord, but regards them as the proper acquisitions of his own understanding: so that he is in reality much under the influence of self-intelligence. Nevertheless, it appears that even so imperfect a principle as this, is capable of successfully resisting that principle of falsity grounded in evil, of which the children of Ammon are representative in the Holy Word: and the children of Ammon were the descendants of the brother of Moab, and therefore, denote a false principle, or a species of falsified truth, answering to the species of evil, or of adulterated good, of which the Moabites are the types. And as the Ammonites were descended from an illegitimate connexion of the most profane description, it seems that Jephthah, as the offspring of a disorderly connexion of a milder nature, and such as was tolerated by the laws of Moses, was, on that very account, and because of the representation thence resulting, the proper person to deliver the Israelites from their slavery to the children of Ammon. It is evident that he represents a principle of truth in the external man, not orderly in itself, but capable of being restored to order, and becoming a real principle of the church. This appears to be represented by Jephthah's remonstrating with the heads of his tribe, on their not Laving admitted him to an inheritance in his father's house together with his legitimately descended brethren, and stipulating that, if he succeeded in delivering his and their country, they should acknowledge him as their captain. His two embassies to the king of Ammon, in which he demonstrated the injustice of his invasion, and peaceably required the restitution of the country, evidently describe the manner in which truth clearly and calmly demonstrates the justice of its claims; and the zeal with which, on receiving a refusal to listen to such claims on the part of the king of Ammon, he collected the forces of the country and hastened to the combat, under an influence which, it is said, he experienced because the spirit of the Lord came upon him, expresses the way in which truth grounded in goodness is prepared, by an inflowing of power from above, to repel the assaults of falsity grounded in evil. That Jephthah, in his present course, represents a principle of truth grounded in goodness, is evident from the justice of the cause for which he was acting. But in order that the result may be successful, the state must be purified, and all that is disorderly be removed. We have noticed that Jephthah represents a principle of truth in the external man in which there is much of self. This must be totally done away; and its entire removal, and the devotion of all that the man has, apparently of his own, to the Lord, is, as we have seen in our last discourse, what is signified by Jephthah's vow, and by the victim of it, whether personally sacrificed or not, being his own daughter.

From this slight sketch of the general purport of the whole history viewed in its spiritual sense, we see that no degree of the knowledge of divine truth, and no power of reasoning in favour of divine things, or of refuting the principles and arguments of evil and falsity, can give any one a title to an inheritance in the Lord's church and kingdom, so long as his love and knowledge of truth are connected with, and grounded in, anything that savours of self and self-seeking, -- so long as the affections from which such attainments are cultivated, is of a spurious nature, and is not connected with a love for the good to which all genuine truth is designed to lead. Nevertheless, the power of reasoning against, and demonstrating the fallacy of, the principles and arguments by which evil and falsity defend themselves, and by which they sometimes appear to prevail against truth and goodness, is a most valuable thing, and, when properly exercised, of great importance in the spiritual warfare. But it will not be conducive to our own establishment in the Lord's Church, nor bring us to a station in his heavenly kingdom, until we are brought to ascribe all the merit of it to the Lord, and to make a full surrender to him of every good or excellence which we deemed most particularly our own. But when we are enabled to resolve that whatever cometh out of our house shall be the Lord's, and to carry the determination into effect, even though we find it involves a sacrifice immensely more painful than what we at first contemplated, the work will be accomplished, and we shall be secure of a station of bliss and honour in the Lord's kingdom for ever.

 END.




