 
<<<
---
=== Chapter III. Judges 2:1-3.

"_And an angel of the Lord came up from Gilgal to Bochim, and said, I made you to go up out of Egypt, and have brought you unto the land which I sware unto your fathers; and I said, I will never break my covenant with you; and ye shall make no league with the inhabitants of this land: ye shall throw down their altars. But ye have not obeyed my voice. Why have ye done this? Wherefore I also said, I will not drive them out from before you; but they shall be as thorns in your sides: and their gods shall be a snare unto you._" (Judges 2:1-3)

We have been engaged, in two previous discourses, in considering the spiritual instruction to be derived from some of the extraordinary circumstances related in the first chapter of this Book of Judges: on which we entered partly with a design of shewing the true nature of the historical parts of the Old Testament. To continue the same design, it is now proposed, to proceed with the consideration of some of the other remarkable histories related in this book.

All that follows is, in the literal sense, an account of the oppressions under which the children of Israel fell from idolatrous nations -- sometimes from those which dwelt beyond the limits of the land of Canaan, and sometimes from those which retained a habitation within its borders; and it includes also the detail of many surprising deliverances which they obtained, by the raising up of judges, who, supported by a divine influence, defeated their enemies and regained the liberty of their country. Our present text with the remainder of the chapter from which it is taken, gives an account of the cause which so far deprived them of the divine protection as so frequently to render them unable to cope with their enemies: The cause was this; that instead of refusing all commerce with the idolatrous inhabitants of the land, and carrying on the war against them till they were entirely expelled, they suffered them to dwell amongst them, and to exercise before them their idolatrous worship: the consequence of which was, as is stated in the thirteenth verse, that they themselves forsook the Lord, and worshiped Baal and Ashtaroth; and this was necessarily followed by misfortune and servitude.

Whoever has read with any attention the books of Moses, and that of Joshua, must have been struck with the frequency and urgency of the divine command given to the Israelites, to have no dealings with the Canaanites, but to drive them entirely out of the land. At the time of the giving of the ten commandments, at the conclusion of the precepts delivered in the three following chapters of Exodus, the Lord makes a promise to the children of Israel respecting his giving them the land of Canaan; which He finishes with these words: "I will deliver the inhabitants of the land into your hand; and thou shalt drive them out before thee. Thou shalt make no covenant with them, nor with their gods. They shall not dwell in thy land, lest they make thee sin against Me: for if thou serve their gods, it will surely be a snare unto thee." The like injunction is repeated at the time of the renewing the tables of the law: again Jehovah says to Israel, "Take heed to thyself, lest thou make a covenant with the inhabitants of the land whither thou goest; lest it be for a snare in the midst of thee: but ye shall destroy their altars, break their images, and cut down their groves." Similar commands are given over and over again through the remaining books of Moses; and they formed also one of the dying injunctions of Joshua. He had driven out or exterminated a great number of the idolatrous people: but he warns his countrymen against being satisfied with what they had already done, and making peace with the remainder, in these words: "Take good heed to yourselves that ye love the Lord your God. Else if ye do in anywise go back, and cleave unto the remnant of these nations, even these which remain among you, and shall make marriages with them, and go in unto them, and they to you; know for a certainty that the Lord your God will no more drive out any of these nations from before you; but they shall be snares and traps unto you, and scourges in your sides, and thorns in your eyes, until ye perish from off this good land which the Lord your God hath given you." Yet notwithstanding these multiplied warnings, we find that the Israelites were no sooner seated comfortably in the land, than they disobeyed them all. The first chapter of Judges contains the history of the final settlement of the several tribes in their allotments; and of every one of them it is recorded that they shared their possessions with their former inhabitants. Thus of Judah (under which name Simeon appears to be included, as Judah and Simeon made common cause in taking possession of their portions; it is said, that "the Lord was with Judah; and he drave out the inhabitants of the mountain; but could not drive out the inhabitants of the valley, because they had chariots of iron." But that this "could not" is only said in reference to the faint-heartedness with which they made the attempt, is evident from the answer of Joshua to a similar complaint of Ephraim and Manasseh, who had said to him, "The hill is not enough for us: and all the Canaanites that dwell in the land of the valley have chariots of iron:" to whom Joshua said in his reply, "The mountain shall be thine, for it is a wood, and thou shalt cut it down: and the outgoings of it shall be thine: for thou shalt drive out the Canaanites, though they have chariots of iron, and though they be strong." This is a plain declaration that the chariots of iron would not be an insuperable bar to the victories of the Israelites, if they faithfully adhered to the commandments so often given them, utterly to drive out the Canaanites, and if they confided in the divine promise, so often repeated, that nothing, whilst they continued obedient, would be able to stand before them. We find however that Judah, terrified by the chariots of iron, or chariots armed with long knives or scythes, similar to those in use among the original inhabitants of Britain, were content to leave the Canaanites in possession of the valleys or low country, and to be satisfied with the occupation of the mountain or hilly country. So it is said of the tribe of Benjamin, that they did not drive out the Jebusites that inhabited Jerusalem, but allowed them to dwell with them. It is in like manner recorded of the tribe of Manasseh, that they "did not drive out the inhabitants of Beth-shean and her towns, nor the inhabitants of Dor and her towns, nor the inhabitants of Ibleam and her towns, nor the inhabitants of Megiddo and her towns: but," it is said, "the Canaanites would dwell in that land." It is added, "that when Israel became strong, they put the Canaanites to tribute, but did not utterly drive them out:" which is equivalent to saying, that, contrary to so many divine injunctions, they made with them a covenant or treaty. Much the same is related of the tribes of Ephraim, Zebulon, Asher, Naphtali, and Dan; which, with those before named, and Issachar, of whom nothing is said, form the whole body of the Israelites whose possessions were within the river Jordan, or the country properly called the laud of Canaan. All, it appears, disobeyed the divine commandments which contained the very conditions upon which they were to be put in possession of the land: no wonder then if severe sufferings quickly followed; and if the enemies whom they endured among them occasionally became their masters.

Now it is evident that this history, even in its literal sense, conveys a lesson of great and impressive import. It is stated in. the fourteenth and fifteenth verses of the chapter of our text, that in consequence of Israel's falling away to follow the gods of the people round about them, "the anger of the Lord was hot against Israel, and he delivered them into the hand of spoilers that spoiled them, and he delivered them into the hands of their enemies round about, so that they could no longer stand before their enemies. Whithersoever they went out, the hand of the Lord was against them for evil, as the Lord had said, and as the Lord had sworn unto them; and they were greatly distressed." This effect of their disobedience so speedily followed, because with them, who were altogether external men, external rewards and punishments were the invariable consequences of their obedience or disobedience to the divine laws. Under the Christian dispensation, this immediate application, in a sensible manner, of punishment to crime and of blessing to good conduct, does not so regularly take place among either nations or individuals. Both are permitted sometimes to go on for a considerable period in a course of wickedness, without being directly pursued by divine judgments, though they are sure to encounter them, at last; -- the wicked man after the death of the body, and the corrupted nation after a longer or shorter interval of prosperity. But among the Israelites, with whom every thing was representative, and with whom also natural afflictions were the proper rewards of natural crimes, the outward sin and its visible punishment appear seldom to have been long disjoined. Such occurrences then are well calculated to impress us most strongly with a sense of the necessity of yielding a sincere obedience to the divine commandments; since we may be certain from these examples, that an habitual disregard of them throws us out of the sphere of the divine protection, exposes us to the most injurious visitations, and must, if persevered in, be attended with our final ruin.

The lesson however, will be more clearly conveyed, if we direct our view to the spiritual sense of these occurrences, instead of abiding in the literal sense alone. The idolatrous nations which the Israelites were commanded to exterminate, represent all the deep-seated evil lusts and false persuasions which lurk in the human heart: of course the command to drive them out, denotes the necessity of expelling them entirely from our bosoms, so that they should not influence our affections or conduct any more; as on the other hand, to make a league with them is to temporize with our duty, and to tolerate the existence of the principle, though we may think we will be very cautious how We suffer it to come into practice. But the example of the Israelites shews, what the experience of all mankind confirms, how dangerous it is to parley with an enemy of this nature: if we allow any thing that we know to be evil ever to tarry in our thoughts, the infallible consequence will be that it will at last ensnare us, as the Canaanites did the Jews, when they induced them to worship their gods: To worship the gods of the Canaanites; is to give that place in our affections to the corrupt inclinations of the natural man, which is due to the Lord alone, the consequence of which must be eternal ruin. It appears that when the Israelites made treaties with the Canaanites, they had no thoughts of adopting their habits: the treaties they made were such as are usually granted by a conqueror to a vanquished enemy, the terms being that they should be tributary to them; by which of course is signified, that the evils represented by the Canaanites, though not exterminated, were not to be allowed to exercise any influence, much less to assume the superiority, but were to be kept in a state of subordination; yet we find, owing to the natural bias which the corrupt heart of man has towards selfish and worldly objects, the presence of the Canaanites among the children of Israel was sufficient to lead them into their practices: This fact is replete with the most solemn warnings, typifying, as it so evidently does, the readiness with which man lapses into evil deeds and habits, if he suffers the thought or idea of such things to dwell in his mind, and does not instantly and decidedly reject it. Let us then learn wisdom from this example. Let us learn to keep our minds continually aspiring after further and further purification; and when any corrupt instigation presents itself to our senses and thoughts, instead of yielding to the allurement and appropriating the evil, let it only be the signal for its immediate renunciation. Thus will every thing of the kind be made conducive to our improvement instead of operating to our injury. For no evil inclination could ever spring up within us, either through outward allurements or the instigation of infernals, if there were not a basis of a corrupt nature inherent in our minds, to which evil inclinations and practices are agreeable. Every perception then of any evil inclination, is in fact an outward discovery of some deep-seated corruption of our selfish nature; and when the suggestion is resisted and entirely overthrown, through our forbearing to yield to it and looking to the Lord, that portion of our selfhood in which it is grounded is removed with it, and thus room is made, as it were, for a more full reception of heavenly graces and their accompanying delights. But this happy result only takes place, (be it well observed,) when the evil is rejected without being entertained and indulged: where this is done, that portion of our selfhood in which the evil is grounded, and which before existed in us in a latent state, and, being the result only of hereditary derivation and not of actual life, would not have been imputed to us as sin, is appropriated, confirmed, and made the subject of imputation: and though evils even of this nature may afterwards be removed by serious repentance, their removal will then be attended with many a bitter pang, and the state which may subsequently be attained will after all be inferior to what it might have been, had the evil suggestions been resisted on their first appearance, and had never by their adoption been made our own. How careful then ought we ever to be against making any league with the spiritual Canaanites.

Such is the general purport of the Israelitish history; but it includes likewise a more specific application, of which we will endeavour to offer a slight sketch, with a view of shewing how endless are the stores of divine instruction contained in the Word of God, and at the same time what a boundless career of improvement is open to the sincere Christian, who is willing to follow where Divine Mercy is ever desirous to lead him.

When understood in respect to the regeneration of man as an individual, the deliverance of the Israelites from Egypt and their establishment in Canaan, represents his advance to the second great stage in the regenerate life, or the attainment of that state in which if he dies, he becomes an inhabitant of the second or middle heaven. That it is the will of the Lord that man should attain the highest possible state, which is consequent upon his complete deliverance from the influence of his selfish nature, and the extirpation of all the evils with which it is contaminated, seems to be indicated by the command so often given to destroy or drive out entirely the wicked inhabitants of Canaan; the accomplishment of which command would have represented a state, in which man would be no more liable to decline into evils. But such is the depth of man's ingenerate corruptions, and his consequent infirmities, that although this would be possible to him if he would steadily look to and confide in the Lord, yet he in practice does not attain it without making a long abode in the second great stage of the spiritual life, in which further and further developments of the evils of his nature take place. This appears to be represented by the fact, that the Israelites, contrary to the divine injunction, spared their deadly foes. Their acting thus proved the cause of their suffering many calamities, which were representative of the temptations and vastations necessary to be undergone, in consequence of the depths of evil resident in the corrupt heart of man, before he can attain the perfection of the spiritual state, and be introduced into the celestial. We read in the 7th and following verses of this chapter, that "the people served the Lord all the days of Joshua, and all the days of the elders that outlived Joshua, who had seen all the great works of the Lord that he did for Israel." This appears to describe the state of ^obedience from a spiritual ground, which is maintained on the completion of man's regeneration to the second or spiritual degree, being the result of temptations and victories in them wrought for man by the Lord. His experience and acknowledgment of this are meant by its being said of that generation, that they "had seen the great works of the Lord that he did for Israel," But it is immediately added, "And Joshua the son of Nun, the servant of the Lord, died;" -- "and also all that generation were gathered to their fathers:" then it proceeds, "and there arose another generation after them which knew not the Lord, nor yet the works which he had done for Israel." These words most strikingly describe the opening of a new region of the mind, the evils belonging to which had not before been brought to light, and of consequence had not been subdued and removed by the temptations which had sufficed for the regeneration of man as to the spiritual degree. It would appear then, that all which follows in the history of the Israelites, to their being carried away to Babylon and brought back again, represents the states which the regenerating mind undergoes, before it can be raised from the spiritual degree of life to the celestial: and when, it is considered what depths of arcana must be included in this process, and what innumerable states must be passed through before all the glories belonging to the celestial state can be developed, and also that these can only be developed in proportion as greater and greater discoveries are made of the hidden corruptions of our nature; when we reflect on this, we need not wonder that the detail of them occupies so large a portion of the Holy Word. That this remarkable notice, that another generation arose which knew not the Lord, denotes the opening of a new state after the attainment of the spiritual, is strongly corroborated by this consideration, that it answers so exactly to what is related at the beginning of the sufferings of the Israelites in Egypt; on which occasion it is said,
(Ex. i. 8) that "there arose a new king over Egypt which knew not Joseph." This expresses the opening of a new state in the natural mind, not perceived to exist before, in which the contrariety of the natural man to the spiritual becomes plainly manifest: so, by parity of reason, the arising, after the time of Joshua, of a new generation which knew not the Lord, must denote the opening of a deeper state in man's selfhood, opposed to the glories of the celestial state, and to the heavenly attainments necessary to be made in advancing to it. The same phrase is not used in the Word on any other than these two occasions; the reason is, because there are no other stages in the regenerate life so strongly marked as these. These denote the openings of those degrees altogether distinct from each other which are called in the New Church Writings discrete degrees; whereas all the other changes that arc noted in the Word express different states or stages in the same general degree.

I mention these things for the satisfaction of those who wish to study, in a deeper ground than common, the Holy Word, and the sublime discoveries of heavenly arcana brought to light in the doctrines of the New Jerusalem Church: but I am aware that they are things difficult to be made intelligible to the mind which is not in possession of a good deal of previous knowledge on such subjects. Abstruse however as these things may appear, they may give rise to valuable practical reflections. It surely must tend to exalt our admiration and reverence of the Holy Word when we see the endless variety of profound mysteries which it includes within its bosom: it must also bring home to us the exclamation of the Psalmist, and convince us that we are indeed "fearfully and wonderfully made," when we learn that such a boundless store of distinct things and principles is comprised in our spiritual organization; and it must exalt our adoration of our blessed God and Father, when we see in ourselves so strong an image even of His infinity, and become more sensible of what an exhaustless exercise of divine mercies and deliverances is necessary, and is granted by Him, for our complete salvation.

We will conclude with a remark which may be necessary to secure part of what has been said from being misapplied.

We have seen that when the historical facts we have been considering are understood in their general spiritual reference, they shew how necessary it is to guard against yielding on any occasion to evil influences: and yet it might seem, from what has been said on the specific application of the circumstances, as if such influences must to a certain extent prevail. But it is to be observed that when we apply the Holy Word to the specific states of individual regeneration, all the persons ,and tilings mentioned, refer to certain principles in the mind of the individual subject, and do not any of them extend to the whole man himself. Thus in the general sense the Israelites in their states of rebellion and obstinacy represent the members of the church in its state of perversion, who yield to the allurements of evil lusts, and consequently perish, or at least suffer a great injury in their states: but in the particular sense the Israelites do not represent the member of the church himself, but certain states in his mind; and their yielding to the seductions of the Canaanites, does not imply that the real member of the church will in any state fall into the evils represented by the Canaanites, but only that he will become sensible of the existence within him of propensities inclining him to do so, and which, in states of temptation, seem to surround him so closely, that it appears to him as if he must yield to them, and so be eternally lost. That this is the manner in which the transgressions of the Israelites are to be understood in their reference to the individual subject of regeneration, is evident from the case of David, who is known to be in a particular manner a representative of the Lord. The Lord, we know, was without sin, neither was guile found in his mouth: yet David was guilty of the greatest of all possible sins -- adultery and murder, -- and this effected by the deepest guile. How then could he, in these respects, represent the Lord? The spiritual meaning is, not that the Lord fell into these evils, but that in his states of humiliation He discovered in the human nature taken from the mother, the propensities to these and all other corruptions, which afforded a ground for the infernal powers to assault Him, and to occasion deep temptations: and we know that the result in Him of all such temptations was, not any appropriation of the evils suggested, but complete victory over them. So are all the histories of the lapses of the Israelites to he understood in their reference to the regeneration of an individual: they do not mean that such a man will run into actual evils, but that he will obtain deeper and deeper discoveries of the evils that are in his nature, and will suffer temptations in consequence, but that, supported by the Lord, he will be finally victorious, and be exalted, at length, either to the state represented by the taking possession of Canaan after coming up out of Egypt, or to the still more glorious one represented by the return to Canaan after the captivity in Babylon. But all depends upon man's resisting the incitements to actual evil whenever they arise. There is no being in any real good except by the rejection of every evil. Let us then look to the Lord that we may first be enabled to discover the evils that are within us, and that we may ever abhor and shun them till we are finally established in the kingdom of heaven.




