

  __________________________________________________________________

== Chapter IV. Judges 3:5-11.

And the children of Israel dwelt among the Canaanites, and Hittites, and Amorites, and Perizzites, and Hivites, and Jebusites: and they took their daughters to be their wives, and gave their daughters to their sons, and served their gods. And the children of Israel did evil in the sight of the Lord, and for gat the Lord their God, and served Baalim and the groves. Therefore the anger of the Lord was hot against Israel, and he sold them into the hand of Chushan-rishathaim, king of Mesopotamia: and the children of Israel served Chushan-rishathaim eight years. And when the children of Israel cried unto the Lord, the Lord raised up a deliverer to the children of Israel, who delivered them, even Othniel the son of Kenaz, Caleb's younger brother. And the Spirit of the Lord came upon him, and he judged Israel, and went out to war: and the Lord delivered Chushan-rishathaim, king of Mesopotamia, into his hand; and his hand prevailed against Chushan-rishathaim. And the land had rest forty years.

It has been endeavoured in some former discourses from this book of Judges, to give a general idea of the nature of the history which it contains. We have seen, that when we regard the whole of the Divine Word as describing the progress of individual regeneration, as no doubt it does, from the first formation of the human being to his highest state of advancement; the histories of this book must have reference to those states which supervene, after man has attained the elevated situation of a truly spiritual man, represented by his establishment in the land of Canaan, and when new openings of the recesses of his nature are made to him, which are necessary to the further extension of his acquirements, and without which he could never attain the state in which are the angels of the highest heavens, and become a truly celestial being. With respect however to the more general manner in which these histories may be regarded, we have seen that they describe states of the church at large, when it suffers itself to fall away from the principle of its foundation, and inclines to the evils and false persuasions which are inherent in the mind of man, and which are called into activity by the influence of evil spirits, who, when considered in one aggregate, are called the devil, of whom an apostle declares, that he is ever going about as a roaring lion, seeking whom he may devour.

We read in this book of six great oppressions which the Israelites suffered from the idolatrous nations around them, or from those whom they permitted to dwell among them, each of which lasted for a. considerable number of years. The first is that related in our text, when the king of Mesopotamia held them in bondage for eight years, till they were delivered by the raising up of Othniel for the purpose. After his death, when the Israelites lapsed again into idolatrous practices, they were subdued by the Moabites, under whose tyranny they groaned for eighteen years, and were delivered by Ehud. After some trouble from the Philistines, who were overthrown by Shamgar, they again did evil in the sight of the Lord, (as is often remarked;) when they were oppressed by Jabin, a Canaanitish prince, and by Sisera, the captain of his forces, for the long space of twenty years; till Deborah and Barak were raised up for their deliverance. They next fell under the power of the Midianites, and were by them reduced to the greatest extremity of distress, for the period of seven years; when they were rescued by the extraordinary exploits of Gideon and his curiously selected band of three hundred men. After his days, except that they suffered from the domestic tyranny of his son Abimelech, they seem to have enjoyed a considerable interval of tranquility under two pacific judges, Tola and Jair; when they were enslaved by the Ammonites for eighteen years, and were rescued by Jephthah. He was succeeded by three judges, of whom little is recorded, when the Philistines obtained the dominion over them; and whose power, notwithstanding the great exploits of Samson, was not completely broken till the reign of David. Thus this book contains the history of the Israelitish nation under the authority of twelve Judges, and of their sufferings under six complete states of subjugation to different nations: in which, however, I have not reckoned their captivity to the Philistines in the days of Shamgar, because this seems to have been but of very partial extent. Of all these, that related in our text (except that connected with Shamgar) is passed over the most briefly. All the others are accompanied with details of considerable length, and some very singular circumstances attended all the means by which deliverance was obtained; whereas^-in that at present before us, nothing peculiarly remarkable seems to have distinguished the war which was undertaken by Othniel, further than that Chushan-rishathaim appears to have been easily vanquished. The causes, however, which led to this captivity, are detailed more at length than in most other instances, no doubt to serve as a general introduction to the whole, and to let us know what is included in the brief expression generally used on other occasions—"the children of Israel did evil in the sight of the Lord." We will note the chief circumstances stated; which will lead us briefly to explain what is meant by the several nations mentioned; what by the kind of alliances which the Israelites contracted with them; what by the anger of the Lord being kindled against Israel; what by their slavery under Chushan-rishathaim; what by their crying to the Lord; and what by their deliverance through the instrumentality of Othniel.

With respect to the first of these subjects, it is said, that the children of Israel dwelt in the midst of the Canaanites, Hittites, and Amorites, and Perizzites, and Hivites, and Jebusites; which are the same that are mentioned elsewhere as being the nations whom the Israelites were to drive out of the land, and by no moans to tolerate among them. The wicked natives of the land of Canaan represent the deep-seated evil lusts and false persuasions inherent in the human heart; and no doubt, when they are enumerated in a series, as in the present case, they denote all the corruptions, in a general complex, to which the heart of man is prone. Each one of them, we may be assured, expresses some general class of depraved affections of the will, or false suggestions of the understanding; though how to distinguish in what they differ from each other would perhaps require nicer degrees of spiritual discrimination than we at present possess. The Canaanites usually denote evil in general; but sometimes, when mentioned in connexion with others, they denote that kind of evil which is the result of a man's having previously confirmed himself in false principles of belief. Let us suppose, for instance, a man to be persuaded, as multitudes are, that faith alone is all that is requisite for salvation, and that charity and good works, though useful in society, are of no use whatever in promoting man's justification in the sight of God;—if, under the persuasion that charity or good will not save him, he should begin to think that neither will evil condemn him, and should thus become regardless of the state of his affections, and live in the practice of whatever his corrupt natural inclinations suggest:— such a man is sunk in evil grounded in falsity;—he indulges in evil in consequence of having imbibed, as a principle of doctrine, the notion that faith alone is sufficient, and that where this is possessed, sins do not appear in the sight of God. So again the Hittites represent such false persuasions in the understanding as give birth to evil indulgences; and these are such notions as just explained respecting the all-sufficiency of faith alone: and many other false notions, whose tendency is similar, exist. The doctrine, for instance, of man's being destitute of free will in spiritual things is a false persuasion that has a direct tendency to beget evil in affection and practice: for he that believes it, will readily say, "If I cannot do good or abstain from, evil without an irresistible outpouring of divine grace, and this grace is not given me, I cannot be to blame, let me do what I may:"—and so such a person will indulge in all evil propensities, while in his heart he imputes the blame of them to God. Such notions are spiritual Hittites, to contract an alliance with which is to rebel against the Lord, and to forsake his pure worship for the worship of idols. The Amorites again represent evil in general, specifically such as captivates the external man; as appears from their having their chief residence on the outside of Jordan, where, with their king Sihon, they were vanquished by Moses. The Perizzites, which are next mentioned, denote false persuasions originating in evil of heart, as all false notions originally do, although when once invented, they may be infused into other persons, who may hold them in simplicity, and thus not be sharers in the criminality which is incurred by the inventors of them. Thus, whenever a man is attached to the practice of evil of any kind whatever, though at first he may be sensible that it is very wrong, yet if he docs not on this account desist from it, he is sure by practice so to confirm it as to lose all wish to desist from it; and as in such case the thought that it is wrong becomes disagreeable and painful, he first frames for himself some excuse, and at last actually persuades himself that he has a right to do as he does: and this persuasion is truly the falsity grounded in evil—it is false in itself, and evil is its author. And such notions as these are constantly meant by the Perizzites wherever they are spoken of in the Holy Word. The other two classes mentioned—the Hivites and the Jebusites,—also denote evil inclinations and false imaginations, but such as are of a milder kind than the others, as partaking more of ignorance than of intention: but such as are nevertheless highly culpable in a man who, having the Holy Word to consult, and the means of obtaining correct ideas as to its doctrines, neglects these advantages, and following his own inclinations and blind conceptions without caring to have them set right, falls into the idolatry of regarding external things in preference to internal, thinking much of this life and little of any other.

Such then, are in general the things represented by the six nations here mentioned: of course it is easy to see how great is the wickedness described by the mode in which the Israelites contracted alliances with them, which is what we arc in the second place to notice. It is said that "they took their daughters to be their wives, and gave their daughters to their sous, and served their Gods."

Daughters, whenever they are spoken of in the Word, denote affections either of good or of evil, and sons denote perceptions of truth. As the Israelites signify the members of the church, or, specifically that which constitutes the church in man, for them to take the daughters of these wicked nations for wives, denotes the conjunction of the holy things of the Church with evil affections of all kinds; so again to give their daughters to the sous of the wicked nations, is to unite affections of a heavenly origin with false persuasions. For example; whoever, on the one part, has acquired an acquaintance with the genuine truths of the Church, knowing that there is a God, and who He is,—that there is a heaven and hell, and the numerous doctrines, that arise out of these general principles; and who does, notwithstanding, encourage affections of an evil nature in his heart, especially if he endeavours to make these heavenly things conducive to worldly and selfish ends, he does what is represented by the Israelites marrying the daughters of the Canaanites—he profanes heavenly things, by mixing them with selfish affections. On the other hand, Whoever, in consequence of being acquainted with the truths of the Church, has felt affections for them, and for the Divine realities to which they relate, springing up in his mind; if, for instance, on hearing the doctrine of the Lord unfolded, he has been struck with its reasonableness and beauty, and has felt a delight in it;—or if, on hearing of the nature of the heavenly world, he has been sensible of a desire arising in his heart to be enabled to enjoy the bliss described; —these delights and desires are daughters of Israel:—should he then afterwards embrace any of the specious but false sentiments, either of a nature directly doctrinal or not, which have their origin in the evils of the natural man; should he combine his heavenward aspirations with such notions as these, applying, for instance, his delight on hearing of the Lord and his salvation, to the notion that He is but one of three Divine persons: or seeking to gratify his longing for heaven by adopting the persuasion that heaven will be opened to him by mere faith, without regard to amendment of life; —or should he in any other way unite the affections that have been produced in his mind by a knowledge of spiritual things, with any persuasions of a false and especially of a worldly and selfish nature;
—he then does what is meant by the Israelites giving their daughters in marriage to the sons of the Canaanites. Such marriages, of both kinds, denote the combination of doctrines that are true with affections that arc evil, by which the truth becomes falsified; and the combination of affections originally good with doctrines that are false, by which the good becomes adulterated. When this is done, the transition is not great to the state represented by the serving, by the Israelites, of the Gods of the Canaanites; by which is meant, to place the worldly and selfish things represented by the idolatrous nations so high in our affections, as to allow them the station due to the Lord alone. The proper residence of the Lord with man is in the inmost of his mind: but if man's affections are set upon unworthy and evil objects, man's true spiritual internal, where the Lord resides, is not open; all that is open in such a man's mind is a region beneath; and whatever is the object of his supreme regard occupies the inmost or highest station therein; and this is to him, whether he suspects it or not, his God. Whoever, then, devotes his supreme affections to evil pursuits, worships in reality the gods of the Canaanites and the other idolatrous nations.

Now when a man has gone into this extent of transgression, he inevitably will experience what is called in the Holy Word, the anger of the Lord. It is said, "Therefore the anger of the Lord was hot against Israel;" by which is meant, not that the Lord really burns with auger, however deserving of it man may be; but that, when a man has suffered evil influences to turn him away from the Lord, so that in his heart, instead of the Lord, he worships some depraved affection, he comes into a state of such contrariety to the Lord, that everything proceeding from the Lord is perceived by him as something just the reverse of what it really is. The change is not in the Lord, but in the man. In the Lord is nothing but love and wisdom, goodness and truth; and nothing but these ever can flow from Him; but when man has averted himself from these Divine graces, and has filled his mind with their opposites, then the Lord's love will appear to him like anger, and the influx of it, instead of recreating his soul with life and enjoyment, as it does when received by the angels, fills him with horror and dismay, occasioning to him such torment as he conceives cannot be the result of any thing but anger. The case to the sinner is thus exactly the same as if the Lord were really full of auger against him, and this should ever be recollected; otherwise the doctrine that the Lord is nothing but love, would be liable to perversion and abuse. The case to the sinner and his feelings, is exactly the same as it would be if the Lord were really angry and punished him from a motive of vengeance; whereas the appearance of anger and vengeance arises from the state of the sinner alone. He has induced such a state on the spiritual organization of his mind, that pure Divine love and goodness, being things that in reality he hates, occasion to him pain by their presence: hence all in hell, when they have any thought of the Lord at all, think of Him with hatred, and believe their wretched state to proceed from anger in Him, instead of being, as it is, the inseparable consequence of their own state of evil; of their opposition and aversion to every thing that is good.

The consequence of this state, in reference to the particular subjects treated of in our text, is declared to be, that the Israelites were delivered into the hand of Chushan-rishathaim, king of Mesopotamia, who held them in bondage for eight years. Mesopotamia is that part of the ancient country of Syria which lies between the two rivers Euphrates and Tigris. Mesopotamia is its Greek name, applied to it in reference to its situation, as it denotes "in the midst of the rivers:" its name in Hebrew expressed the same thing—it was "Aram Naharaim," or "Syria of two rivers." Syria is very often mentioned in the Word, and it always denotes, in the spiritual sense, the knowledges of goodness and truth, either genuine or in a state of perversion. The truths of the Church are called knowledges, while they abide in the memory, but are not appropriated in the life, in which case they are in reality without the man and not within him; just as the country of Syria lay without and not within the land of Canaan, to which it was contiguous. To come, then, under the dominion of the king of Mesopotamia, is to come into a state in which the truths of the church, being no longer alive in us through being lived or loved, only exist as mere knowledges in the memory; and when they even are falsified, so as to be made, by wrong interpretations, to appear to confirm the falsities and evils of the natural man. In this state, the truths of the church, and whatever has been received in the mind from the Lord, are in reality made vile slaves.

This at length the children of Israel felt and deplored, which is represented by its being said, that they cried to the Lord. It is remarkable that this phrase is used on every occasion of the oppression of the Israelites recorded in this book, and in numerous other instances; as when the children of Israel were oppressed in Egypt, it is said that "they cried, and their cry came up unto God." This denotes, that when man is truly sensible of the state in which he is, and is sincerely desirous to be delivered from it, then, and not before, deliverance is afforded. As, to worship the gods of Canaan, is to give that place in the mind to evil affections, which is due only to the Lord, so to cry to the Lord is to look to him for help from the deepest recesses of the heart—to be actuated by such a desire to escape from the thraldom of our corruptions as has the Lord in reality in it, being a desire of which he is the Author and man the receiver, though a free one, and which, thus coming from him, is sure to reach to him, and then deliverance will follow. This deliverance is here described as wrought by Othniel, the son of Kenaz, Caleb's younger brother; respecting whom as the conqueror of Kirjath-Sepher, we lately delivered a discourse (p. 9). Suffice it then to state now, that by him is represented a principle of truth originating in good of an elevated order; and by his being raised up for the work by the Lord, is represented, that when such a desire for deliverance as we have already described, is excited, man is gifted in his mind with such a genuine principle of truth derived from good, and invested with such power from the Lord, as will speedily rescue his knowledges of truth from perversion, and restore his mind to order in obedience to the Lord.

Be it then our constant care to prevent our knowledges of Divine things from degenerating into mere knowledges undirected by any view to use: and if we at any time experience a tendency to such perversion, let us not be slow to cry unto the Lord, and to seek from Him such a principle of real truth from good as a governing impulse, as shall restore the state to order, and revive a genuine spiritual principle such as shall prevail through all our life and conduct, securing us for ever in our heavenly inheritance.
  __________________________________________________________________



