
<<<
---
== Chapter V. Judges 3:12-14

"_And the children of Israel did evil again in the sight of the Lord: and the Lord strengthened Eglon the king of Moab against Israel, because they had done evil in the sight of the Lord. And he gathered unto him the children of Ammon, and Amalek, and went and smote Israel, and possessed the city of palm trees. So the children of Israel served Eglon the king of Moab eighteen years._" (Judges 3:12-14)

When we endeavour to unfold in the slight degree in which we are enabled, a few of the innumerable mysteries which are involved in the regeneration of the individual member of the church, 

it may be necessary now and then to introduce a word of caution, to prevent the simple mind from concluding too hastily, that the work of regeneration is so arduous and complicated a process, that there is no hope of ever being led through what it involves.

Whilst the recondite [internal -Ed.] meaning of the Holy Word is only brought forward as matter of curious discovery, and, 

in unfolding the spiritual subjects which are contained under the covering of the letter, especially in such extraordinary histories as that of which our text is a part, 

the chief object is to defend the divinity of the Holy book, and to prove its claims to be received as divinely inspired, 

by shewing that it contains stores of wisdom within it which none but the Divine Mind could conceive, 

-- even the natural man may feel interested, and take delight, in the discussion.

Because in this case the heavenly treasures of the Holy Word appear as matters of deep yet amusing speculation; and the love of knowledge, which is a principle of the natural man, though the highest of which he is capable, is alone sufficient to make such speculations agreeable to us.

How powerful a principle the love of knowledge is, is proved by the labours of body and mind which men who make science their pursuit, will often undergo for its gratification; 

whilst the melancholy fact that some of the most distinguished of them have been enemies to the revealed will of God, fully evinces [proves -Ed.] that the love of knowledge is one of the affections of the natural man; 

though, as just observed, it is the highest of these affections, because it is eminently useful to the spiritual man, 

being a principle implanted in our nature to serve as a means of our passing from the dominion of the natural man to that of the spiritual, 

and without which this great object of our creation could not be accomplished. 

---

Now it is inherent in the love of knowledge, to be more delighted with things of a recondite and abstruse nature than with such as are common, and plain, or with knowledges of a high, than with those of a low, order. 

The more exalted the subject respecting which the means of acquiring knowledge are presented, the higher is the satisfaction with which the acquisition is made; 

and hence, where the mind is not so closed against heavenly things as to deny their reality altogether, 

knowledge respecting them is capable of affording a delight altogether similar to that experienced on making scientific attainments of an ordinary nature, 

but with many persons more exquisite, because it is seen that they relate to more noble and exalted subjects. 

Still this is a natural delight: it is the natural man, or the natural part of our frame which is affected by it; which, when it regards the profoundest arcana of the Holy Word merely in the light of curious information, feels no repugnance at hearing of it, and experiences in it a gratification similar in its nature to what it feels on hearing of new discoveries in science, or in reading the works of adventurous and intelligent travellers or of elegant historians.

---

But when, in addition to an exposition of some of the general spiritual contents of the Holy Word, an application is made of them to individual states, there is room to apprehend that some minds, even of those who have entered on the work of regeneration and are sincerely desirous to advance in it, may feel alarm at the apparent magnitude of the work; 

and some may conclude, that if the knowledge of these things is necessary to their being safely experienced, 

-- as they feel little hope of attaining any sufficient share of such knowledge, -- 

so it will be vain for them to expect the blessings consequent upon passing through the states. 

To guard against the depressing effect which such thoughts must have, it may only be necessary to be assured that they are not founded in truth. It is possible, I have no doubt, to attain a very high state in the regenerate life, without seeing distinctly the application of any great portion of the Holy Word to the states which may nevertheless have been experienced. 

The Lord declares to the Israelites, at the conclusion of their journey through the wilderness, "_I led you by a way which ye knew not_", 
//Alas, I strove and failed to discover which verse could this be accredited to
to instruct us that it is the Lord alone who regulates the steps of our progress, and that in order to arrive safely at the end of it, it is not necessary that we should have an exact knowledge of the way beforehand. 

What we have to do is to acknowledge the Lord, (looking continually to Him as the sole Author of every thing that can tend to our true welfare,) and to keep his commandments, striving without remission to recede more and more from the love and practice of whatsoever is contrary to them, and to do continually with more and more affection and diligence whatever they enjoin; and all the rest we may safely leave to the Lord to do for us.

When we have reached the desired haven, and especially when our faculties receive that improvement which is consequent upon our passing into the spiritual world, and going to our happy home in heaven, we shall be able to look back upon the road through which we have been led, and to see distinctly what spiritual associates or opponents attended us in the way; but in the mean time this is not practicable; as the Lord said, "_What I do ye know not now, but ye shall know hereafter_" (John 13:7) 

There is then, no room for discouragement, let our present state be ever so low or weak, in seeing the magnitude of the process of regeneration. Let us remember that the kingdom of heaven is like a grain of mustard seed; when once it has obtained admission into our hearts, however inconsiderable our first attainments may be, its after growth is almost a matter of course; 

that is, it will infallibly proceed to maturity, without any anxiety of ours about the result, provided we continue simply to practise what first implanted it within us, -- that is, to look to the Lord and shun evils as sins against Him. 

Besides, there are certain great resting places, as it were, in our route. Whoever enters on a spiritual course at all, and does not make shipwreck by the way, cannot, I apprehend, stop, until the contents of the greater part of the book of Genesis are fulfilled in him, -- that is, until he attains the state described by the subordination of the land of Egypt under the authority of Joseph; in which case, should he die at that time, or even before its completion, he will attain a state of happiness in the lowest or first heaven. 

If he goes beyond this, I apprehend there is no permanent abiding place for him until the contents of the remaining books of Moses, those of the book of Joshua, and of the first chapter of Judges, have been spiritually experienced by him; in which case, should he die at that time, or even before it, he will become an inhabitant of the second or spiritual heaven: 

-- for whoever departs from this world after a general stage is entered upon, but before it is finished, has it completed in the world of spirits before he is taken up into heaven. 

It is not probable that many at the present day go beyond this. To be qualified for the spiritual heaven is a very high and glorious state. But we know that it is the wish of our heavenly Father to lead us further than even this. He would, if it were possible, raise us to absolute oneness with Himself, so as to impart to us all the divine perfections which constitute His own nature, in all their infinite fulness; but as this is impossible, He ardently desires to raise us to the highest state which a finite creature can be made capable of enjoying; and it is nothing but our own fearfulness and obstinacy which prevents the designs of His boundless love from taking effect. 

Let us then, not be so unwise as to draw any matter for discouragement from the almost endless succession of states which are represented in the history of the children of Israel after their establishment in the promised land, but let us consider every new scene in which we find the Israelites engaged, not as an additional obstacle to be surmounted, and thus as a discouragement, but as a further height of glory to be obtained, and thus as a stimulus. 

Most people believe that there will be a continual increase of perfection and blessedness going on for ever in those who attain the regions of heavenly felicity; now there can be no increase in perfection in heaven but by the further and further removal of the seat of our affections from our selfish nature; and this is exactly what is to take place in us while here, and what is represented by the sufferings of the Israelites from their enemies, and their deliverances from them; 

only there is this difference, that our advancement before we enter heaven is effected by means of conflicts and temptations; whereas, when our state is so far rendered complete as to admit of our being received into heaven, it will then advance without any struggles, and our eternal state will be truly that which is represented by the sabbath of rest. 

But the basis from whence we commence this career of tranquil advancement there, will be that which is attained by our active advancement here; let us then set our minds upon the things that are before us, and from every history of the Word draw an incentive to our progress.

Our present text details the account of the enslavement of the Israelites by Eglon king of Moab; and it is followed by the description of the very singular circumstances attending the assassination of Eglon, which was the first step to the deliverance of Israel. Some of these particulars we propose to endeavour to elucidate in another discourse; at present we will offer such observations, as appear naturally to arise out of the words before us, and may tend to throw a light on the circumstances mentioned.

"The children of Israel did evil again," it is said, "in the sight of the Lord; and the Lord strengthened Eglon the king of Moab against Israel, because they had done evil in the sight of the Lord." What an important lesson do these words at the very first glance, convey. 

They plainly instruct us that when we fall into spiritual captivity, so as to lose the freedom which is felt when the mind enjoys a serene consciousness of the divine presence and favour, 

it is the result of evil done by us, or at least latent in us, and to which we inwardly incline. 

We see also, that when we are in this state we really are in spiritual captivity: for the Moabites, being a different nation from the Israelites, though descended, but by an unlawful connexion, from the same original stock, must needs represent something of the natural man separate from the spiritual, 

and, when not under the dominion of the spiritual, in opposition to it. 

With respect to the man of the church, individually, by the children of Israel's doing evil in the sight of the Lord, is not meant that the man who has advanced so far in the regenerate life, as to have attained the state represented by the taking possession of Canaan, will afterwards fall into the habitual practice of gross evils, for if he did he would be guilty of profanation; 

but by this circumstance is meant, that the man in this state makes a new discovery of some evil tendencies in his nature which he had not been aware of before, and comes into temptation by the excitement of evils to which, of himself, he inclines, although it is in opposition to the new life of heavenly affections which reign in him from the Lord. 

How far a person [who has -Ed] really advanced in the regenerate life may by any possibility be guilty of actual evils, perhaps cannot be determined; but that he should commit any of those contained in the decalogue, in their external form, I think can scarcely be supposed. 

We wish to speak with gentleness on this subject, because we should be unwilling to say any thing which might drive any one to despair; although a right apprehension of the nature of the divine laws can have no tendency to beget despair in any one, 

as we are assured that it is never altogether too late to begin a new course of life, and that repentance, when of that sincere kind, which alone is called repentance in the Word, and which consists, not merely in sorrow for our sins, but in a real desisting from and forsaking them -

- that such repentance will always avail in procuring for the sinner a lot in the heavenly kingdom. 

But we still think it may with certainty be affirmed, that none who is subject to lapses into gross evils, can have previously attained any advanced state in the regenerate life; 

wherefore if any such have fancied so, let them from the circumstance learn humility, and be content to take the lowest place, with gratitude that such a place is still left for their attainment. 

To steal, to lie, to commit adultery, and the like, are evidently crimes which belong only to those who have not entered on a religious life at all, and they must be abstained from before we can advance into the lowest degree of preparation for heaven. But there are many things which are less taken notice of, which nevertheless must be surmounted before we can attain any elevated state in that progress. 

How much is to be done and endured before our tempers, for instance, are so regulated, as never to betray any indications of dispositions contrary to charity and humility; 

and even when they are so regulated as never to exhibit the presence of improper affections, how much more is yet to be done before the mind is altogether so free from the influence of such affections, 

as to be relieved from the necessity of keeping a constant watch over the tempers, in consequence of a renewal of the will itself, so that improper influences can no longer exert a power within us. 

Thus there are innumerable things in us which at first are little noticed either by ourselves or by others, which yet, as our perception of spiritual goodness and truth becomes more acute, assume in our estimation the form of most serious evils, and are such in reality, because they are connected, as is then plainly discovered, with evil lusts that have a very deep seat in our selfish nature. 

Besides, we know that all the divine commandments have three distinct senses, a natural, a spiritual, and a celestial, and we shall find in ourselves propensities that are opposed to the two latter, long after an obedience to them in their literal sense has become habitual and easy. 

It is easy then to see how the candidate for heaven, and who is preparing for a superior station therein, will find such passages as that now before us, applicable to his state, long after he has learned to desist entirely from such outward conduct as a common observer can condemn as criminal.

With respect to the particular nature of the state represented by a captivity under the king of Moab, this may, in some measure, be apprehended by those who are acquainted with the views which we have formerly endeavoured to develop on the character of those who are represented by Moabites in the Holy Word. 

//<Moabites>
In brief, the Moabites are they, who, while they profess a general respect for the things of the church, adulterate the good of the church by separating it from its truth, considering mere natural affection, separate from an attention to the requirements of the Holy Word, as sufficient for salvation. 

It is interesting to observe here the marriage of goodness and truth which every where prevails throughout the Holy Word, by virtue of which no sooner is good the subject treated of, than something immediately follows respecting truth, and vice versa. 

Thus, as was noticed in our preceding discourse, the captivity of the Israelites under the king of Mesopotamia, denotes a state in which knowledges of truth alone are prized and sought after, but which knowledges are in reality falsified in consequence of being separated from the good and love and life with which they should be united. 

So now, the captivity under the king of Moab represents a state the counterpart of this, in which good alone is extolled as being all that is requisite to constitute the church in man, but in which, as the good is separate from truth, it is mere blind natural affection, defiled by a mixture with the evils of the selfhood. 

There is reason to believe that the state represented by Moab is one which abounds very much in the church at this day. The numerous good humoured men of the world, who trouble themselves little about matters of doctrine, but pride themselves upon being good sort of people, friendly in their general manners, and capable of feeling the more amiable affections of the natural man, may probably be in general considered as spiritual Moabites. 

And the man of the true church falls under the dominion of the Moabites, when he suffers his regard to spiritual views and ends to become quiescent, and conforms himself too far to the manners of the world.

The king of Moab however, was unable, it appears, to subdue the Israelites with his own forces alone, but he called in the assistance of the Ammonites and the Amalekites. The Ammonites, whose ancestor was brother to the ancestor of the Moabites, represent a falsification of truth corresponding with that adulteration of good which is denoted by the Moabites. 

What the specific character of the falsified truth represented by the Ammonites is, I know not that we have sufficient grounds for determining; but I have often thought that the worship of their idol, the horrid Moloch, in honour of whom his worshipers threw their children into the flames, is an apt emblem of the Deity worshiped by those who believe the doctrine of predestination, and suppose that man's eternal state is determined by an eternal decree which no efforts on his part can get revoked, and in consequence of which the greater portion of mankind are unalterably destined to eternal fire. 

//<Amalekites>
The Amalekites, again, denote a false persuasion of a very deep nature, grounded in interior evil, or in the deep-seated evil propensities of the natural man. 

The nature of this may be gathered from the first place where the Amalekites are mentioned, which is in the 17th of Exodus, where it is said that the Amalekites came and fought with Israel in Rephidim. Now this attack of the Amalekites upon the Israelites, took place immediately after the latter had undergone the temptation from the want of water at Massah and Meribah; and by the assault of the Amalekites afterwards is meant a false persuasion arising in the mind, and suggesting to the man that it is in vain for him to persevere in his spiritual course, for that it consists of nothing but trials, in some or other of which he must inevitably be lost. 

The Amalekites, however, were then conquered by the holding up of Moses' hands, to denote, that while we keep all the powers of the mind elevated to the Lord we shall be secured from every danger, and from the assaults even of despair; from being depressed by any suggestion that may present itself respecting the difficulty and danger of the path to heaven.

These united forces then came and smote the city of palm trees, which was a name given to Jericho, and which probably, after the destruction of Jericho, was a place in its vicinity. The situation of this city, at the entrance of the land of Canaan, shows it to be the principle whereby there is introduction into the church, which is by the doctrine of truth from good;

wherefore to smite this city is to deprive this doctrine of its power, and thereby to prevent any thing from flowing from the spiritual mind into the natural. 

//<Doctrine of Truth From Good>
By the doctrine of truth from good, is meant not a mere principle of doctrine by itself, but a doctrine so combined with affection for the duties which it prescribes, as to be determined forcibly into life and practice. 

The nature of this principle, however, will be more easily seen, when we come to describe, in another discourse, what is represented by Ehud, who was raised up as a deliverer on this occasion. Suffice it to say, that when the truths we know, or the doctrines we profess, have no determination to life and practice, they are of no avail whatever in promoting or maintaining our state in the spiritual life. The communication is then cut off between the internal man and the external; and such principles as are represented by the Moabites, the Ammonites, and the Amalekites sway the mind, and threaten the extinction of every spiritual attainment and heavenly hope and prospect.

From this brief view of the invasion of Eglon and its consequences, we see the importance of ever watching against the yielding in any degree, to the suggestions of the natural man in any of his allurements to evil. If the children of Israel had not done evil in the sight of the Lord, Eglon would have had no power to hurt them; but when this is done in any degree, our security against infernal influences is gone, and nothing but such a repentance as is described in the next verse, and which we shall consider in our next discourse, can save us from ruin.




