
<<<
---
== Chapter VI. Judges 3:15-21

"But when the children of Israel cried unto the Lord, the Lord raised them up a deliverer, Ehud the son of Gera, a Benjamite, a man left-handed. And by him the children of Israel sent a present unto Eglon the king of Moab. But Ehud made him a dagger which had two edges of a cubit length; and he did gird it under his raiment, upon his right thigh. And he brought the present unto Eglon king of Moab: and Eglon was a very fat man. And when he had made an end to offer the present, he sent away the people that bare the present. But he himself turned again from the quarries that were by Gilgal, and said, I have a secret errand unto thee, O king: who said, Keep silence. And all that stood by him went out from him. And Ehud came unto him: and he was sitting in a summer parlour, which he had for himself alone. And Ehud said, I have a message from God unto thee. And he arose out of (his) seat. And Ehud put forth his left hand, and took the dagger from his right thigh, and thrust it into his belly."

We have already, in our last discourse, considered the state of captivity into which the Israelites had fallen to Eglon the king of Moab, as related in the three verses which precede those just read, and the means of their deliverance from which are described in the singular history which we have now taken for our text. We have seen that, when understood in its spiritual sense, according to the relation which it bears to the advancement of an individual member of the Lord's church in the regeneration, it describes a state of temptation which is incurred, in consequence of the opening of a new depth in the corrupt part of the human mind, in which the man is infested by the predominance of merely natural ends and objects, such as are regarded by those who entertain the persuasion that natural goodness alone will suffice for their salvation, and under the influence of which he is in danger of becoming a mere man of the world. We, in the same discourse, also offered some observations with a view of guarding the inexperienced mind from concluding, that regeneration must be a state unattainable, if such a boundless variety of distinct steps are included in it; by shewing that provided we are attentive in the performance of the two conditions on which alone it depends, which are, to acknowledge and ever look to the Lord alone, and to obey His commandments, we may rely upon being led safely on, whether we have any very distinct views of the roads, and places of sojourning, or not. But it may be asked, If this is all that is absolutely necessary on our parts, what need to be prying into these deep mysteries? And if but few attain the degree of advancement internally described in the book of Judges, what use can it be to us to know any thing of its nature? Both these questions may be answered by observing, That, as it is absolutely necessary, to advance in the regeneration at all, we should learn to look to the Lord and keep his commandments, it is also necessary that all religious instruction and exhortation, especially that delivered from the pulpit, should ever keep these objects in view. But always to dwell upon them in their simplest form only, would become tedious by its sameness and by the frequent repetitions to which we must have recourse: all which are avoided by unfolding passages of the Word which have reference properly to distinct states; whilst the same end is obtained when it is shewn, as every part of the Word must shew, that the same general lesson results from them all. Surely the necessity of acknowledging the Lord and keeping His commandments, must press upon us with tenfold force, when we thus find it meeting us, as it were, at every corner. As observed on former occasions, although the states to be passed through at different periods have specific differences, yet they have general similitudes: and thus from a description of what takes place in a higher state, we may derive instruction suited to our improvement in a lower. In, the second place it may be observed, that knowledge respecting states beyond those which we may at present have attained, ought surely to be as delightful to the mind intent upon spiritual improvement, as knowledge respecting remote countries or objects is found to be to the students of natural science. To acquire information respecting the remote countries on this globe, the nature of their soil and productions, and the manners of their inhabitants, is found to be a wish so congenial to human nature, that many expeditions, attended with great danger and expense have been fitted out with this object alone. Nor is the love of knowledge, so natural to man, satisfied with learning what is to be seen and is contained in the whole of the earth we inhabit, but it has pushed its researches into other worlds, and seeks information, not only respecting the planets which belong, with our own earth, to the same solar m, but respecting the other "systems distant far, spread through the boundless skies." Numerous are the ways in which the ingenuity of man has been exerted to gratify this thirst; and the little which has thus been discovered respecting the innumerable systems of worlds and of suns which every where fill the regions of interminable space, is prized in proportion to the difficulties which lay in the way of its attainment. Now surely it should not be said, that in this respect the children of this world are wiser that the children of light. Surely some acquaintance with the more advanced states in the course of the regeneration, being what we all may, and ought to desire to attain, ought to be far more interesting to us, than the knowledge of remote countries and distant worlds, where they never can go, are found to the disciples of natural science. And if such attainments in natural science, though not conducive to any immediate use, are still highly beneficial by their tendency to enlarge the faculties of the mind, and by the light they often throw upon things of more direct utility, doubtless the study of such subjects as we have been speaking of, must improve the mind in general, and tend to throw light upon subjects connected with our immediate states, in a far higher proportion. Besides, though we have remarked that but few can have really entered into the states described in the historical relations we are at present considering, yet we cannot say but that some may have done so. Let us then endeavour to enlarge our views of spiritual subjects by the occasional contemplation of such as we have been speaking of: but let us, whatever our own state may be, endeavour to render such contemplations truly profitable to us, by appropriating the incentives which they afford to a more earnest pursuit of heavenly objects, to a more entire rejection of evil from the heart and life, a more faithful cultivation of the truly saving principles of love and charity, a more complete confidence in the Lord's mercy and assistance, and a more settled habit of keeping the mind elevated continually to Him, with that interior prayer which opens it for the reception of blessings from Him.

The subject however which is at present before us, while it shews in what manner the state in the regenerating individual represented by the captivity of the Israelites under Eglon, is terminated, also shews how judgment is performed on such persons as are represented by Eglon and the Moabites, when they have so filled up the measure of their iniquity as entirely to have separated themselves from all connection with the heavenly kingdom, and thus to be beyond the sphere of divine protection. We will therefore, by way of varying the scene, consider it chiefly in this reference, which is a very awful and impressive one; but first to continue the connection of the subject in the other point of view, we will as briefly as possible, touch upon the relation of the history to individual states.

As we have before shewn that the Moabites, in a general sense, represent those who, without much regard to the spiritual things of the church, think to be saved merely in consequence of possessing some amiable dispositions from nature, it of course follows, that when applied to the states of the regenerating member of the church, they must represent the tendency to such a persuasion existing in every human mind, -- or those principles in the constitution of the natural man, which, if allowed to obtain the decided rule within us, would make us altogether of this character ourselves. The nature of this principle, and the kind of adulteration of good which it induces, we have considered at large on former occasions. Ehud, then, by whom the deliverance of the Israelites was effected, must of course signify something directly the reverse of this -- that kind of good which is not the spurious offspring of mere nature, but such as results from bringing the truths of the Word into the life, the good actions springing from whence are not the offspring of a blind impulse, but of an enlightened apprehension of the will of the Lord; being what is sometimes called in the New Church Writings, truth in act. As this might be inferred from the character of the enemies to whom Ehud was opposed, so is it rendered certain by the information which is given respecting his family; for it is said that he was a Benjamite; of course he must represent some specific heavenly grace of the same general character, which is represented by Benjamin the founder of his tribe; and what this is, is made evident in the history of Joseph and his brethren. When Joseph was ruler over the land of Egypt, he represented the celestial internal within the natural; and his brethren, by whom he had been sold into slavery, and who had even entertained the thought of killing him, represented the truths of the church as first existing in the external man, in which though they are the offspring of the internal, they at first appear in the shape of the mere knowledges of heavenly things, and being as yet only conjoined with such affections as belong to the external man, they are unwilling to become obedient to the pure affections of the internal, represented by Joseph. At last however, this takes place, but not till a real disposition is felt to bring into life whatever is known respecting spiritual subjects from the Lord. This is the only medium by which the internal man and the external can be conjoined; and this is what is represented by Benjamin: this, then, is the reason why, notwithstanding the penitence which Joseph's brethren manifested for their former ill-treatment of him, he did not discover himself to them till they brought with them Benjamin. Thus Benjamin represents truth in act; which is a disposition and determination in the external man to bring into practice the heavenly will of the internal: and when this exists in the external, the external and internal can be in conjunction, and not before.

Now, as Benjamin denotes a principle of action in the external from the internal, we see the propriety of its being said, that Ehud, who delivered the Israelites from the oppression of the king of Moab, was a Benjamite. For the king of Moab, we have before seen, represents a principle of seeming but not genuine good that is of the natural or external man alone; and he acquires an influence in the mind by obtaining possession of the city of palm trees; by which is represented, the shutting up of the communication between the spiritual man or mind and the natural, or the internal and the external: deliverance then from a domination of this kind, must needs be effected by opening with power a principle in the mind, by which the communication between the internal and external is restored, and the natural man seeks to do good from the spiritual, and not from itself alone. This then is what is represented when it is said, that the Lord raised up for them a deliverer, Ehud the son of Gera, a Benjamite. It denotes the opening in the natural man, by a strong influx from the spiritual, and from the Lord Himself, who is inmostly present therein, of a determination to bring into practice all the divine commandments, and the fixing in the mind of a steady principle, of which this is always the tendency and object. When this is fully formed within us, the tyranny of Moab cannot last much longer. So long as light from the internal man, or what amounts to the same, from the Lord Himself through heaven, is shut out, it may be possible to imagine that the exercise of the more amiable of the natural affections, may be sufficient to qualify us for heaven, and even that the indulgence of any of the impulses which have a basis in our natural dispositions will not exclude us: but when the communication between the internal man and the external is open, in which case the rational faculty is truly enlightened, it is seen that all good, to be genuine, must have respect to eternal considerations and to the Lord Himself, and that, in reality, no good that may appear such outwardly is such inwardly, except so far as evils are resisted and held in abhorrence as sins against God. A determination inspired by the Lord, continually to act under the influence of these convictions, is what is represented by Benjamin in the Holy Word, except when he is described as being in a state of rebellion; and the specific application of this general principle to the removal of the influence of the evil represented by the Moabites, is what is denoted by his descendant Ehud. This signification of Benjamin is the reason that he is the last of the tribes mentioned as being sealed in their foreheads, in the Revelation, where, as explained in the New Church Writings, he signifies the life of truth resulting from the doctrine of good and truth that will prevail in the New Church: he also there signifies the conjunction of those who are in the ultimate heaven with the Lord, which evidently must arise from their being in a life according to such doctrine.

We see then, my brethren, of what indispensable moment it is to cherish in the mind, not merely the knowledges of truth, an acquaintance with the doctrines of the Church, but a fixed determination, living by an inward communication with the Lord, to bring such knowledges into life and activity. Without this, we shall be disposed to rest in mere doctrine alone, and shall hold the highest truths in all the harsh, unhallowed spirit of the open advocate of the doctrine of faith alone. When we hear that pure spiritual love must be exalted to the dominion within us, that a heavenly Joseph, who represents the spiritual principle in general, which is pure truth united with good and manifesting itself in the affections of charity, must take the lead within us, we shall be disposed to resist, and even to extinguish this heavenly principle altogether: nor can our knowledges of truth be conjoined with this, their proper internal, until a Benjamin is established as a medium to unite them; -- until there exists a firm determination of our truths to life. This is a state which must take place early in the regenerate life, as it belongs to the process by which man is regenerated as to the first or spiritual-natural degree. The effects of it will, however, be experienced through all the states that will succeed: for when a Benjamin is thus found to unite the internal with the external in the natural degree, an Ehud may afterwards be raised up further to extend this union, to liberate us from Moabitish domination, and to prepare the natural man for still further improvement under the influence of the genuine celestial.

With respect to the manner in which the operations are carried on in the interiors of the mind, to effect the removal thence of the corrupt principle represented by Eglon and the establishment of the heaven-derived determination to good conduct, represented by Ehud in its place, information is afforded in the remainder of our present text. To elucidate this fully, would require several discourses, which would be inconsistent with the plan at present proposed: we will, therefore, only explain some of the leading particulars in a very brief manner. And as, when brevity is an object, they admit more easily of an explanation of a general nature as referring to the divine judgments really incurred by those who are spiritually Moabites, it is in this point of view that we will consider them. It will be easy for every one to make the application to individual states, by remembering, that in this view, both Moabites and Israelites represent certain principles abiding in the mind of the regenerating subject, whereas in the general application, the Moabites represent those persons who are confirmed in the kind of adulteration of good which has been before described, and the Israelites represent those who are the true members of the church; and in this case Ehud will represent the Lord Himself as to that principle in the Divine nature, from which the faithful are rescued, and the evil of this quality are separated from heaven and left to sink into the infernal dungeons, which are the native seats of the motives and ends of life which they have made their own.

It appears then, that judgment comes upon the wicked of this description at the time of their receiving a present from the Israelites; by which is denoted their arrogant persuasion that their pretended good is the real good of the church, and that all the truths of the Word ought to be so explained as to confirm that it is so. For the Moabites to exact a present or tribute from the Israelites, is to apply the holy things of the church to confirm their ruling principle; and when this is done by the wicked, as it always is when they are confirmed in their evil state, in spirit, at least, if not in outward form, its effect is, entirely to close heaven against them, and to render them liable to the destruction which awaits all who are not protected by the reception of some degree of spiritual life through heaven from the Lord. By Ehud, who slew the king of Moab, being said to be a man left-handed, or as it is given literally in the margin, "shut of his right hand," that is, having no use of his right hand, is described the appearance to those who are in evil, as if the Lord as to His Divine Truth had no power to hurt them -- the right hand always denoting power. By Ehud's dagger with two edges, is meant the divine truth proceeding from the Lord to execute judgment upon those who are in evils and falsities, -- the two edges are expressly mentioned, to denote that the divine truth of the Word is equally opposed to both. By its being concealed under his raiment, is denoted, that divine truth in the letter of the Word does not appear to be of such a quality, since the evil can falsify it to serve their own purposes, when nevertheless it is: indeed it is in consequence of their falsifying the Word, that it becomes a sharp sword, cutting them off from all communication with the heavenly kingdom. By his bringing the present to Eglon, is meant, as before, the assumption by the wicked of supremacy over the things of the church, and their making them seem to favour their loves; and Eglon is here said to be a very fat man, to denote the deep degree of adulteration of all genuine good which is in this state incurred. By Ehud's sending away the people that were with him, is signified the Lord's care, when judgment is performed, that they who are really in truths should not be hurt, and the cutting off of communication between them and the evil to secure this object. By Ehud's returning, and coming to the king of Moab in a summer parlour which he had for himself alone, is expressed the deep exploration of the interior state of the evil at the time of judgment, when all their exteriors, in which they appeared outwardly like upright members of the church, are stripped away, and their inmost hidden quality, which is altogether wicked and profane, is detected by the piercing light of divine truth. By Ehud's then putting forth his left hand, is meant the judgment then performed as from truth alone, which, separated from its good, of which the wicked are not receptive, condemns all to hell: that nevertheless this proceeds from divine good in the Lord, is meant by his taking his dagger from his right thigh: and by his thrusting it into his [Eglon's] belly, is described the entrance of truth in this separated state, which deprives the wicked of the appearance of spiritual life which they had before assumed, and leaves them no refuge but in the abodes of death eternal.

Here then, my brethren, we see how awful is the state of those who so submit themselves to the bondage of the king of Moab as to become of the same character themselves: but we see also, that if, on discovering in our own selfish nature the tendencies to such a state, we strive to resist them, and with this view look to the Lord and live according to his commandments, he will remove from us the infernal powers by whose agency such evils are excited, and will, by the same power of his Divine Truth quickened within us, restore us to genuine liberty, and light, and life.




