 
<<<
---
=== Chapter VII: Judges 4:12-16.

"And they shewed Sisera that Barak, the son of Abinoam, was gone up to Mount Tabor. And Sisera gathered together all his chariots, even nine hundred chariots of iron, and all the people that were with him, from Harosheth of the Gentiles unto the river of Kishon. And Deborah said unto Barak, Up; for this is the day in which the Lord hath delivered Sisera into thy hand: is not the Lord gone out before thee? So Barak went down from Mount Tabor, and ten thousand men after him. And the Lord discomfited Sisera, and all his chariots, and all his host, with the edge of the sword, before Barak; so that Sisera lighted down off his chariot, and fled away on his feet. But Barak pursued after the chariots, and after the host, unto Harosheth of the Gentiles. And all the host of Sisera fell upon the edge of the sword; and there was not a man left.

Ir is a remarkable circumstance attending the relations of the oppressions and deliverances of the Israelites, recorded in this book called that of the Judges, that every distinct, narrative seems to surpass that which preceded it in the singularity of the occurrences which are detailed, and in the interest which it is consequently adapted to excite, even in the mind of the superficial reader. In our last discourse we considered the history of the deliverance of the sons of Jacob from the tyranny of the Moabites, by the bold and desperate act of Ehud, a man left-handed: in the narrative at present before us we have the account of a still more extraordinary effort for escaping from the yoke of an enemy, begun by the heaven-inspired heroism of one female champion, and completed by the subtlety and boldness of another. This is followed by the still more wonderful history of Gideon, who after being encouraged by some most extraordinary signs, to undertake the seemingly impossible task of rescuing his country from the domination of the Midianites, at length accomplished it with an army of only three hundred men, selected by the most singular of tests. Nor is the story of Jephthah and his celebrated rash vow less extraordinary: whilst this again is surpassed by the unparalleled occurrences which distinguished the life and death of Samson; whose adventures, (if such a word may be used in reference to such subjects,) which, when considered apart from the divine instruction which they contain, are more amusing perhaps than any work of mere fiction, possess, as we all, no doubt recollect, so strong a charm for youthful minds, and so greatly tend to win them to the perusal of the Scriptures. Now, Divine Mercy has provided that the historical books of Scripture should possess this entertaining character, partly with this express design; that at an age when didactic precepts would not be understood, and to minds which would be little disposed to read a merely didactic work, the Bible should be made inviting. For little as some may be disposed to believe it, the mere reading of the Bible, even when the spiritual instruction contained in it is not at all perceived, has a beneficial effect on the human mind, when done in simplicity and with some sense of its holiness. For within the letter are contained interior senses adapted to the apprehension of the angels of all the heavens, which, when the literal sense is read on earth, are perceived by the angels who communicate with the interiors of the human mind: and though, on account of their being in an interior or higher degree of life than that in which man is so long as he lives in the world, what they perceive, or their thoughts of exalted wisdom, cannot be communicated to the reader, yet the heavenly affections which, on such occasions are excited in them, do in some measure affect him or move his feelings. He thus unconsciously holds communication with heaven, and through heaven with the Lord, and is connected with the Lord and His kingdom by invisible bonds, which insensibly tend to withdraw him from a connection with the kingdom of darkness. Thus, also, states are prepared in the interiors of the mind, which at a future period may be brought to light, and tend essentially to advance his regeneration. How important then it is, since Infinite Goodness has thus accommodated itself to human infirmity, that we should not suffer it to be in vain; that parents and tutors should lead children to take pleasure in reading the Holy Word in simplicity, and that adult persons should regularly follow the same practice, endeavouring, however, to read it with some degree of understanding.

However, though it is certain that the reading of the Holy Word with simplicity, is productive of spiritual advantages, the extent of which is in proportion to the holy reverence with which it is regarded, it is equally certain that it would not have this effect were it not for the stores of divine wisdom which are included within its letter. Were it an amusing history and nothing more, the reading of it could be productive of no advantages whatsoever. Angels take no interest in mere historical relations, however gratifying they may be to the natural imagination; nor could the perusal of such compositions be effective of any consociation between the heavenly world and the mind of man. To be the Word of God, and thus to have the power of affecting the inhabitants of his immediate, kingdom, lessons of eternal wisdom must be contained within, destitute of which the reading of the exploits of Gideon and Samson would conduce no more to man's eternal benefit, than if the whole were a romance. When, also, its spiritual contents are perceived or known, all the difficulties arising from the questionable morality of some of the distinguished parties in the narration, are removed; and we see how the whole can be the Word of God, notwithstanding the deeds of an Ehud and a Jael; deeds which, though perhaps allowable according to the law of nations that prevailed in those distant ages, partake too much of treachery and deceit to be themselves agreeable to the divine will, or to have been performed by persons who were themselves interior subjects of a spiritual dispensation. The slaughter of Eglon by Ehud, which we considered in our last discourse, though effected under fair pretences, and thus by treachery, was indeed no more than would have been done and gloried in by the most illustrious heroes of Greece and Rome, amongst whom tyrannicide, by whatever means accomplished, was deemed a meritorious act; although the brighter light of the Christian dispensation shews us decidedly, that evil is not to be done that good may come; but it may be doubted whether any national opinions or customs ever existed that would justify the cruel act of Jael, whose tribe were at peace, as is expressly stated, with the Canaanitish prince, but who yet, with words of encouragement and assurances of safety, inveigled Sisera to his ruin; which, also, she completed by an act from which most persons, and especially females, would recoil with horror. Yet for the perpetration of this, in itself, dreadful deed, we find it said of her, in the song of Deborah and Barak in the next chapter, evidently uttered under inspiration, "Blessed above women shall Jael the wife of Heber the Kenite be, blessed shall she be above women in the tent." How plainly do these things prove that the Jewish was not a real church, possessing inward principles of heavenly life and grace, but only the representative of a church, the most distinguished characters of which only by their actions represented things of a spiritual nature, but might often be themselves far remote from any participation of spiritual feelings. Admit this, (and really to a mind at all open to conviction, it is not difficult to prove it) and every objection which the infidel can raise against the divine origin of the Scriptures on this score, is immediately surmounted. "We also see how greatly they err who propose the exploits of the Jewish worthies, in their outward form, as things for the imitation of Christians: a principle which at various periods has been adopted by fanatics, who have perpetrated the greatest outrages under its sanction. And we see further, how, in the darkest night of human degeneracy, when man was incapable of any direct perception of heavenly things, and wholly immersed in the carnal part of his nature, Divine Goodness, by selecting a nation which was more entirely of this character than any other, to represent those things which they were incapable of interiorly perceiving, brought divine things, as it were, into the most extreme and lowest natural form, and by causing His Word to be written at this time, and to treat in its literal sense of the transactions of this people, gave to divine things a fixity of which they otherwise would not have been susceptible among men, -- conjoined, as it were, even nature in its extreme circumference with Himself, -- and thus provided the means of extending divine aids to the most external of mankind, and for raising all from their state of degeneracy, and bringing them back to Himself and heaven.

We have shewn in former discourses upon the oppressions and deliverances of the Israelites recorded in this book of Judges, that with respect to the member of the Church individually, these occurrences represent the opening of new recesses in the human heart; -- the discovery of further defilements in our perverted nature; -- the temptations hereby induced; -- and the blessings resulting from the opening and communication of new heavenly graces, new affections of love and perceptions of wisdom, in the internal man from the Lord, opposite to the evil tendencies which are thus brought to light, and which by these means are finally cast out and deprived of all influence on the mind and life for the future. Considered in this sense, we have seen that the Israelites denote the heavenly graces which have been inseminated into the mind from the Lord, and the nations which oppressed them the various evil lusts and false persuasions which belong to the natural man. But when viewed under a more general aspect, the Israelites represent the members of the church themselves, and the other nations, all others, usually such as profess to be members of the church, who are interiorly evil.

In the present case it will be necessary to take a general view of the whole transaction.

The chapter begins with saying, And the children of Israel again did evil in the sight of the Lord when Ehud was dead; by which we are to understand, that after man has attained the state represented by the deliverance of the Israelites from the Moabites by Ehud, and has for a time been in the perception of the heavenly grace which Ehud represents, which is the constant effort and determination of the mind to bring into act the truths which the man has learned from the Word; though this state continues with him, stored up in his interiors, and will always be effectual in preventing the evil represented by the Moabites from again obtaining an ascendancy in his breast, yet he afterwards has discoveries made to him of further corruptions in his nature, which require a different heavenly grace to oppose them. This is what is meant by the children of Israel again doing evil, and by this taking place after Ehud was dead, On account of this transgression it is said, that "the Lord sold them into the hand of Jabin king of Canaan, who reigned in Hazor; the captain of whose host was Sisera, who dwelt in Harosheth of the Gentiles: Then the children of Israel cried unto the Lord: for he had nine hundred chariots of iron: and twenty years he mightily oppressed the children of Israel."

In a former discourse, in which we considered what was meant by the six nations, which it is said, were left to prove Israel -- the Canaanites, Hittites, Amorites, Perizzites, Hivites, and Jebusites, we offered some observations on the signification of the Canaanites in particular; when we observed that they signify evil in general, and specifically such as arises from a belief in false doctrines grounded in evil loves. It appears then, that they signify evil brought into act, in consequence of false persuasions embraced from evil inclinations being confirmed in the mind; and of this general class of evils, Jabin, who does not appear to have been a king of all the land of Canaan, but of a tribe of people of the Canaanitish race inhabiting the northern part of the country, must signify some particular modification. This is indeed, still but a very general explanation of the subject, but it may suffice to give us such an idea of it as may afford a general insight into the meaning of the history. This also may be observed, that the evil hereby denoted must be one of a more debased nature, and more deeply opposed to the genuine good of the church, than those represented by the former enslavers of Israel -- the Syrians and the Moabites; because these nations had their proper habitations without the limits of the land of Canaan -- whereas the Canaanites were the natives of the country itself, and of course must signify evils more directly opposed to the genuine good of the church, than the others can. Now evils are more directly opposed to the genuine good of the church, the more they ally themselves with false persuasions that enlist the literal truths of the Word in their service, by taking them out of their proper connexion, turning them from their genuine meaning, and so making them seem to support doctrines which tend to confirm man in his natural corruptions: for evil and falsehood necessarily become much more malignant, when they assume the pretence and appearance of being the genuine dictates of Religion, and when they are so covered over by an outward appearance of religion as to disguise their deformity, and render them more capable of seducing the unwary, and even the well disposed. That evil of a malignant nature has this tendency, we may learn from the history of the Lord's temptation by the devil, who, when endeavouring to ensnare the infirm humanity by the excitement of the love of self in its deepest ground, when it makes the holy things of the church its instruments, which is what is meant by the devil's placing Jesus on the pinnacle of the temple, said to him, "If thou be the Son of God, cast thyself down, for it is written, He shall give his angels charge concerning thee, and in their arms they shall bear thee up, lest at any time thou, dash thy foot against a stone" -- a passage of the Holy Word which the tempter thus applies to persuade the Lord's Humanity that it was allowable for it to appropriate the evil suggested to it. And no doubt many, in states of deep temptation, have had passages of Scripture brought to their minds by the tempting spirits, and so applied as to seem to excuse or justify them in yielding to the temptation.

Now deep persuasions of direful false sentiments, arranged into doctrines and so confirmed by the letter of the Word as to appear irrefutable, are what are meant by the nine hundred chariots of iron which Sisera is said to have had at his command. By the chariots being said to be of iron, we are not to understand that they were made altogether of that material, but that they were armed with projecting iron instruments for cutting down the ranks of the enemy when driven furiously against them: -- a mode of attack of an almost irresistible kind in a plain county, before the introduction of fire arms. Chariots are often mentioned in the Holy Word, and by them are not, in a spiritual sense, meant mere chariots, but doctrinal tenets; and when, as is often the case, chariots to be used in battle are understood, they denote doctrinal tenets so arranged, and supported by ingenious reasonings, as to be adapted to overthrow the sentiments of those of a different belief. Iron, also, always denotes that kind of truth, or of the appearance of truth, which is adapted to make a strong impression on the natural man, such as is the truth of the Holy Word in its natural or literal sense, and the reasonings which an ingenious disputant can produce from the light of nature and the apparent evidence of the senses. Now it requires a high state of illumination, the proper consequence of the reception of sacred things in an interior ground, to be able to detect the fallacies which may be couched in a false doctrine thus glossed over and supported; which is the reason why it is said in the first chapter of this book, that "Judah drove out the inhabitants of the mountain, but could not drive out the inhabitants of the valley, because they had chariots of iron;" by which is signified the purification of the interiors of the mind, which are nearer to the spiritual part of it, whilst evils with their attendant falsities still remained in its deeper recesses, which, being farther removed from the internal, required a stronger influence from thence for their extirpation than the state was yet capable of affording, and because evils of this nature, being further remote from the light of heaven, can defend themselves more by fallacious appearances, and by the application and perversion of the literal sense of the Word to their purpose.

It is evident then that the victory over Sisera with his nine hundred chariots of iron, must imply a state in the regenerate life, in which there is a much stronger influx of goodness and truth from the interiors, than is obtained at the first establishment of man in the church as to the spiritual degree; and of course that the seeming lapses of the Israelites represent in reality, in the purely spiritual sense, so many further advancements. The number nine hundred, also, represents the false persuasions and doctrinal tenets denoted by the chariots, as linked in the greatest strength and seeming coherence; for the number nine signifies conjunction, and relates in particular to what is true, or, contrariwise, to what is false; and when it is multiplied by a hundred its meaning is still further exalted: so that nine hundred must imply the strongest concatenation of such false sentiments. It seems to be on account of this signification of the chariots of Sisera, that the tribes selected to oppose them, as we learn in verse 6, were only those of Naphtali and Zebulun: for the tribe of Zebulun denotes the conjunction of goodness and truth, and the effort thereto in the regenerating mind, and Naphtali signifies temptation, and a willingness in the mind to endure whatever is necessary for its final purification. The battle is described, in our text, as taking place at Mount Tabor, where no doubt the hilliness of the ground rendered Sisera's formidable array of chariots of little use. It is first said that Barak, the Israelitish general, was gone up to Mount Tabor; and afterwards that he went down from Mount Tabor with ten thousand men after him; by which we learn that the true way of rising superior to the false suggestions that may be presented in spiritual conflicts, is, by ascending into the interiors of the mind, or in other words, keeping the thoughts elevated towards heaven, when, being above the sphere to which the fallacies of the senses can reach, their falsehood is clearly perceived; and then an influence can thence flow into the lower region of the mind -- Barak with his army will come down from Mount Tabor, and the influence of the evils and falsities which before disturbed us shall be driven away, never to annoy us any more.

Here, then, we have a lesson of general instruction, which we may in all cases apply to our real advantage, and with which therefore we will conclude our present discourse. It is only by ascending into a more elevated region of the mind, that we can rise above the influence of the suggestions of a false and pernicious nature, which our spiritual foes are always ready to present, and to clothe under such specious appearances as make them seem even worthy of entertainment. To avoid being overwhelmed on such occasions, it is necessary to elevate the mind, by looking to the Lord, and retiring inward beyond the reach of the activities of the carnal part of our nature. But a man cannot be always kept in this retired state, nor is it designed that he should be. To go out, or descend into outward things for the sake of use, since it is by our external man that the designs of the internal are brought into effect, is as necessary as to come in, or to engage in interior meditation and seek for strength in the inward man by divine communion. It is necessary therefore to clear the lower regions of the mind from whatever thoughts and affections of an uncongenial nature may therein have usurped an influence. If then we can muster ten thousand men of Naphtali and Zebulun, -- a fulness of willingness to undergo whatever trials are requisite for our purification, and of desire that the union of goodness and truth may be effected in our minds, -- we may descend therewith from the mountain of internal affection, to the plain of corresponding practice, extirpating in the way every thing that would oppose the full operation, in freedom, and liberty, of internal ends and motives, till from first to last, every principle of the internal and external man is united in the life that true religion inspires, and we possess the land without annoyance, are fully confirmed in a spiritual state, and prepared to enjoy it in the heavenly Canaan for evermore.




