
<<<
---
== Chapter VIII. Judges 5:6-8

"Then sang Deborah and Barak ..."

"_In the days of Shamgar the son of Anath, in the days of Jael, the highways were unoccupied, and the travellers walked through byways. (The inhabitants of) the villages ceased, they ceased in Israel, until that I Deborah arose, that I arose a mother in Israel. They chose new gods: then was war in the gates. Was there a shield or a spear seen among forty thousand in Israel?_" (Judges 5:6-8)

These words form part of the song, as it is called, of Deborah and Barak; in which they first describe, as in the words just read, the deplorable oppression under which the children of Israel laboured, when they were tyrannized over by their Canaanitish enemies. Afterwards the song proceeds to express their exultation in the deliverance which had been afforded them from the Lord, by inspiring Deborah and Barak to undertake the Israelitish cause, and by rousing the tribes of Zebulun and Naphthali to supply the forces requisite to oppose the cruel foe; when, after his defeat, the last stroke to crown the victory was given by Jael the wife of Heber the Kenite, who slew the fugitive chief of the Canaanitish army.

The principal circumstances of the history to which this divine song relates, and which are detailed in the preceding chapter, were briefly considered in our last. Jabin, a Canaanitish prince, whose forces were led by Sisera, who appears to have been a very formidable commander, and who had in his army nine hundred chariots of iron, (or chariots armed with iron weapons for breaking through and cutting down the ranks of the opposing forces,) reduced the Israelites to a state of subjection, in which he held them for the continued space of twenty years. The nature of the calamities under which the Israelites laboured, may be gathered from what is said respecting them in the chapter of our text, which contains, as remarked, the song of Deborah and Barak on account of their victory. It would appear from thence, that the whole of the nation was not so subdued by Jabin and Sisera, as that their authority was every where acknowledged, but as if the Canaanites were in possession of all the open country, which they laid waste, and kept the Israelites closely shut up in the fortified cities. 

For Deborah says, in our text, "The highways were unoccupied, and the travellers walked through by-ways: the villages ceased, they ceased in Israel, until that I, Deborah, arose, that I arose, a mother in Israel. They chose new gods; then was war in the gates. Was there a shield or a spear seen among forty thousand in Israel?" 

Here, by its being said that the highways were unoccupied, and the travellers walked through by-ways, is evidently meant, in the literal sense, that the enemy overran the country, so as to make the communication between distant places very difficult.

The villages ceasing, denotes the desolation resulting from the enemy's being master of the open country; 

and by war being in the gates, is implied, that the Israelites were so closely shut in by the Canaanites in the fortified towns, that they could not show themselves beyond their gates without danger of slaughter or captivity. 

That this was their condition is confirmed by what the inspired song proceeds to say of the consequences of the defeat of the Canaanites; 

on which subject the prophetess adds, "(They that are delivered) from the noise of archers in the places of drawing water, there shall they rehearse the righteous acts of the Lord, (even) the righteous acts (towards the inhabitants) of his villages in Israel: then shall the people of the Lord go down to the gates" (Judges 5:11). 

Here, the noise of archers in the places of drawing water, refers, literally, to the straitness of the siege as being so great, that they could not go to the wells without being exposed to the missile weapons of the enemy; but in consequence of the divine interposition for their deliverance, called "the righteous acts of the Lord," it is declared that "they shall go down to the gates," or no longer be compelled to remain shut up within the walls of the cities.

I mention these particulars as greatly tending to illustrate the nature of the state which the oppression of the Israelites by Jabin and Sisera denotes, when understood in the spiritual sense, wherein is described a state of the mind of man in the course of his regeneration. 

In this sense, these particulars most plainly describe a state in which, -- though there are heavenly graces of love and wisdom, goodness and truth, implanted in the internal man from the Lord, -- there is such a pouring of evil and falsity into the external man, that the graces of the internal cannot come forth, nor even renew their vigour by the perception and appropriation of divine truths drawn from the Holy Word. 

"The highways" being "unoccupied," or deserted, denotes, in the spiritual sense, the absence of those clear views of truth which lead the mind onward from state to state in the heavenward journey; the travellers walking through by-ways, or, as it is literally given in the margin, through crooked ways, implies, that they who are desirous of instruction can obtain nothing to satisfy the desire but false notions, whose tendency is not to lead man to heaven, instead of true; and by which, if heaven is reached at all, it is only after numerous wanderings and perplexities. 

The ceasing of the villages, denotes the desolation of the external man; 

cities, which are the chief places in a country, denoting what is respectively internal; and villages, which are places that lie without, denoting what is respectively external.

War being in the gates, implies that the infernal influx reached even to the rational man, or to the medium by which there is communication between the internal and the external. 

There being neither shield nor spear seen among forty thousand in Israel, denotes that the temptation became so appalling that there appeared no means of safety; 

forty, of which forty thousand is a multiple, being a number which always has reference to states of temptation, and it being generally the case that temptations are continued until despair of deliverance comes on -- until neither shield nor spear -- truths applied either to shelter us from the power of false suggestions or to detect and expose their fallacy, -- seem to remain in the mind. 

By its being said that there was the noise of archers in the places of drawing water, is meant, that no perceptions of truth could be obtained by studying the Word, without being distracted or perverted by the influx of false doctrinal sentiments; 

to draw water is to imbibe truths from the Holy Word; 

archers are they who combat from doctrine -- here from false doctrines against the truth; 

and their noise is the din and perplexity of confused reasonings proceeding from this source.

Thus it is easy to see, that these particulars represent the state of the mind when under the influence of severe temptations; when all the heavenly things which have been received within the soul, and which in other states have been attended with vivid perceptions of their presence, and with a delightful sense of their reality, are so closely shut up in the interiors, that a doubt may be entertained respecting their existence; 

whilst nothing is manifestly perceived but thoughts infused from the tempting influence, accompanied even with scandals injected against divine things, and suggestions to take refuge in despair, and to seek in the delights of the natural man with all his evil affections, for that rest which, it is suggested, it is in vain to hope for, by a perseverance in the once fair promising pursuit of heavenly acquisitions and eternal realities. 

All the open country, -- all the external of the mind, -- is occupied by the Canaanites, even to the destruction of the villages and interception of the highways -- to the seeming extirpation of whatever the external had received from a heavenly origin. 

Sisera, -- or some leading false persuasion which would justify, and recommend the adoption, as allowed by religion, of the evil represented by the Canaanites, -- is supported by nine hundred chariots of iron, or such a well-ordered array of false doctrinals, made to appear as true by reasonings from the natural man, and by seeming confirmations from the letter of the Word, that resistance seems hopeless, and it appears to the suffering soul as if he must submit to infernal domination, and relinquish all hope of the heavenly mansions.

But which way does the interior will of the party himself incline? Does he feel pleased with the suggestions and inclinations of an evil kind which arise in his natural man? Does he hail the Canaanites as friends and brothers, and wish to be persuaded that it is right to receive them as such -- to appropriate without reserve the contaminations which they bring with them, and thus, as is expressed, to choose new gods? 

No doubt there is something in his heart which inclines this way, or he would never be infested with them at all. "Israel did evil again in the sight of the Lord when Ehud was dead." The love of spiritual things in his mind is still denied by a selfish mixture; and, though not willing to relinquish the mercies of which he has been made a partaker, he would gladly mix a little of his own with them, and turn to the indulgence of some of his natural corruptions, if it could be done without forfeiting all his higher hopes. 

This it is that makes temptations unavoidable; and they are permitted, in order to make us see and feel the utter uncombinableness of good and evil, truth and false persuasion, and to render us willing to give up whatever our natural man is disposed to cling to, when we find it incompatible with the enjoyment of things which have now become dearer to us still. 

If we have no such higher attachments, the infusion of evil inclinations and false conceptions into our minds will occasion no temptation, because this only arises where there is something of an opposite kind to make resistance. 

Such things would then appear to us simply in the light of allurements, which it is a great mistake to consider, as is commonly done, as temptations. It is an abuse of language, and a corruption of the original meaning of the word, when we call an allurement a temptation, or speak of a person as being tempted when he is only enticed. 

The word temptation properly means much the same as we express by the word trial, which we always use to denote something which is accompanied with pain; which is not the case in mere allurement. 

If then there is in the mind a principle of spiritual life from the Lord, which consists in a love for Him and the things of His kingdom, there will be an internal will that turns away from the suggestions of the Canaanites, and that is anguished when their suggestions seem to be pressed with such force as to appear difficult to be resisted. 

The Canaanites therefore, in this case, may come to the gate, but they will not be able to enter the city. Their presence in the external gives to the mind real pain; because however agreeable to the natural man alone might be the principles which they represent, to the internal affections, which in this case are the ruling ones, they are altogether contrary; whence their presence deprives the internal man of all its sense of freedom and delight. 

Thus when, as is declared, there is war in the gate; -- when the suggestions and influences from the evil world come to the very entrance into the man himself, and threaten to take possession of his interiors, -- his very life appears to be at stake; indeed, that principle of life by which he must live in heaven, is at stake; and the sensations attending this, will be as distressing as those which accompany the approaching loss of natural life to natural men, when they feel the very agonies of death upon them. 

"Then," as the Psalmist says, "they cry unto the Lord in their trouble, and He delivers them out of their distresses." (Psalms 107:6,13,19,28) 

We have noticed in a former discourse, that on every occasion on which a divine interposition for the delivery of the Israelites is recorded in this book, it is introduced by the remark, that the children of Israel cried unto the Lord: and this, we have also seen, implies an inmost looking to the Lord, with an entire willingness to make every surrender that may be necessary, to permit his Divine Mercy and Truth to enter our minds with such power as to remove entirely the sphere of infernal influence, to eject the evils in ourselves which yielded it a basis, and to establish so thoroughly within us an opposite good, as to secure us against the preponderance of that particular evil for evermore.

We noticed in our last, the chief circumstances of the preliminary part of this history, -- as the nine hundred chariots of iron, -- the reason why Naphthali and Zebulun were the tribes selected for the conflict; the instruction implied in its being related that Barak with his forces first marched up to Mount Tabor, and afterwards that he went down from Mount Tabor to attack the enemy. But we have not yet noticed why Deborah, a prophetess, was the chief director of the operations of the Israelites, so that Barak, the general of the army, received from her encouragement and instructions.

It is remarkable respecting this deliverance of the Israelites from the Canaanites, that it was commenced by one woman, and finished by another. -- No doubt it is hereby intended to instruct us, that to be rescued from the power of the evil propensities and false persuasions represented by these Canaanites, a great preponderance of that principle by which the female sex is distinguished, and of which, therefore, they are representative when mentioned in the Holy Word, is necessary: and this is the principle of affection or love. 

Great disputes have been raised in the world upon the question whether there is any natural inferiority in mental power, on the part of females, as compared with men. The male part of the species are in general too apt, it must be allowed, to conclude that there is; but the female part have not wanted champions, both of their own sex and of ours, to contend for the rights of woman, and to maintain her full equality with man. But both parties have in general greatly erred in their sentiments, because both have taken, as the criterion of excellence, a standard on which it does not in reality depend. 

It is remarkable that in the present day, when faith alone is regarded in the articles of all Protestant churches, as the prime essential of salvation, even persons who do not readily admit this sentiment in religion, are yet generally inclined to allow it in philosophy, and to exalt the faculty of intellect alone as the supreme excellence of human nature. 

But as charity or love is a principle not less necessary than faith, to abide in the mind that is the seat of real religion, so must there be a faculty in the mind peculiarly appropriated to its residence; therefore, whilst our benign Creator has furnished us with the faculty of understanding to be the abode of our faith and of all the perceptions of truth, he has also given us the faculty of will to be the abode of our charity and of all the affections of goodness. 

Mental superiority therefore does not depend upon the clearness and strength of the intellectual powers alone. To form a perfect character, ardour and purity of affection are at least equally necessary.

Now as the human mind in general is constituted of will and intellect, of love and intelligence,

-- each faculty and principle being perfectly distinct from the other, and yet adapted to supply to the other what it would be extremely defective, yea, what it would be absolutely nothing, without, -- 

so that the two are capable of, and designed for, the most perfect union: -- so in like manner is the human species in general constituted of male and female human beings, designed for union of mind with each other, and to be, when so united, what the will and understanding are in one individual; and thus to render each more perfect by the union, insomuch that from two minds one may be formed, with its life and all its powers greatly exalted. 

For in such a union, all the life and respective perfections of each are communicated to the other; just as, among angelic societies, by the wonderful communion that takes place in heaven, all the perfections and enjoyments of each angel are imparted to all the others, so that each becomes a centre in which unite the perfections of the whole. 

This is a circumstance to which is owing the boundless extent of angelic felicity: and it arises out of that mutual love in which angels are principled; the essence of which consists in being willing to give, without any thought of a return, all that is its own to others; which disposition Divine Goodness rewards, (so to speak,) by returning into it all the blessedness which it is willing to bestow.

A similar, and even more intimate communication of their respective excellences undoubtedly takes place, wherever there is a perfect union of male and female minds: there is also a tendency towards it impressed on all male and female minds by creation; and therefore they are each endowed with the faculties which are requisite to enable each most effectually to heighten the perfections of the other.

Much as men of science in general may be disposed to think of the exertions of the intellect, it is a certain truth, that had they not will, with affection of some kind or other, to animate the intellect, it would be unable to conceive a single thought; it would be incapable of any exertion whatever, which would be the same thing as if it did not exist. 

The case is similar with respect to the will and its affections: if it had no understanding to think of what it inclines to, and to devise means for bringing it into manifestation, it would have no consciousness of existence, and thus would be in a state similar to that of having no existence at all. 

It is the will, then, that gives to the understanding all its activity; but it is the understanding that gives to the will its consciousness of existence. Thus the understanding, though not the most important faculty of the two, is that which most readily attracts attention, and of the presence of which, on a slight degree of reflection, a man is most sensible: and this is the reason why so many have considered the understanding as the distinguishing faculty of human nature, and have estimated the superiority of one man over another, and of one part of the species compared with the other, by this as the sole criterion. The truth, however, is, that will, as well as understanding, is necessary, to constitute a man at all; that love or affection, as well as intelligence, go to the composition of every human being. Neither man nor woman could exist as such, if they did not enjoy both.

But here comes the discrimination. It is certain that the two sexes do not enjoy both these faculties and principles in exactly the same relative proportions: if they did, their minds would be constituted exactly alike, and not suited for that intimate union which arises from the reciprocal communication of distinct but harmonious excellences; and as varieties of form arise wholly from varieties of mind, the distinction in this respect would cease also, and the world would be peopled (were that practicable) either entirely by men or entirely by women. It is well for human happiness that this is not the case, and that men and women have each marked peculiarities to distinguish them from each other. 

The predominant characteristic of the male is derived from the intellect, which in him is more active than the will; although, if he had not will also he could not be a man. And the predominating characteristic of the female is affection, which is the property of the will; although if she had not intellect also she could not be a woman. 

The aggregate amount of capacity for what is truly noble and excellent, resulting from the union of these two faculties, may be assumed to be in general equal in both; but the proportion of the ingredients which go to compose that capacity will always be different; and thus the capacity itself will be exhibited under different forms. There no doubt are instances of men who have a softness, and an affectionate character in their constitution, beyond what may be observable in some women; and there are instances of women who have a brightness and power of intellect superior to many men; thus there are instances of men who approach to the character of women, and of women who approach to the character of men: but it may be remarked, that all have an intuitive perception that the order of the sexes requires a decided distinction: each sex finds itself displeased when what it feels to be its province is too palpably invaded by the other; hence the repugnance which all men feel to the masculine character in a woman, and which all women feel to the feminine character in a man. 

But how near soever the minds of the sexes may appear in some instances to approach to identity, still there can be no doubt that by those who should have discernment enough to observe the distinctions, the male will would always be found to be something different from the female, and the female intellect to be something different from the male.

Now what conclusion should be drawn from the undeniable fact, that in the male and female will and understanding such distinctions always exist? Plainly this: that they originate in Infinite Wisdom and Goodness, in order that the two parts of the human race may be to each other mutual helps, each capable of admiring what the other possesses, instead of proud rivals, each jealous of being outshone by the other in the quality in which they considered their chief merit to consist.

Let not man then assume superiority over the woman because her distinguishing excellence is not the same as his; because, though of equal value, it is less obtrusive, and less capable of contending for pre-eminence. Nor let woman assert her just equality upon false grounds, by assuming that it consists in the same faculty as the man's. 

In proportion as genuine truth enlightens the human mind, it will come to be more clearly seen that the sexes are indeed equal, but that their respective excellences are distinct. As this is seen they will live together in more perfect harmony, and the weaker of the two, as to bodily strength, and the consequent power of asserting their prerogatives, will be restored to their due station. Of this they are uniformly deprived, among the various nations of the earth, in proportion to the remoteness of the nation from the light of Divine Truth, and from a reception of those heavenly principles, which constitute the Lord's church among mankind.

Now it would appear that this great deliverance of the Israelites by the instrumentality of females, took place, because it represented the arrival of that state in the regenerate life when good takes the priority, and man no longer acts from a principle of truth less influenced by love, as is the case in the incipient stages. It is true that, in its specific sense, these conflicts refer to the state which is experienced after man has attained the spiritual state, which he could not have attained without allowing to good the pre-eminence; but there can be no doubt that something of the same kind must be experienced in all the three great stages of the regenerative process.

That some very marked state -- some very important attainment, must be represented by the deliverance now under consideration, may be evident from its being celebrated in a divine song, sung by Deborah and Barak after their victory; for only two or three instances of the kind occur in the whole of the Divine Word. It appears then, that this refers to a state, in which good of a celestial order takes the lead in the mind of the regenerating subject; therefore, Deborah, as a prophetess, represents the perceptions of truth resulting from such good which she denotes as a female, was the first mover in the work.

In conclusion, then, let us learn from the remarkable circumstance, continually to aspire to the attainment of a state in which goodness, in its genuine character of kindness and love, shall assume the superiority in our minds; -- in which goodness and truth shall be perfectly united, and the latter shall chiefly be valued because it leads to the former, and directs us how to bring into operation its benevolent behests. 

To this end, how obvious it is that we must acquire a state of humility, and cease from assuming any superiority for mere acquisitions of science or intelligence. This is pointed at by Deborah, when, in the preceding chapter she says to Barak, who represents the intellectual principle in this state, "Notwithstanding, the journey which thou takest shall not be for thine honour; for the Lord shall sell Sisera into the hand of a woman." 

Let us be willing that this shall be spiritually the case: let us relinquish all desire to be distinguished for mere intellectual acquirements, and, whatever we may possess of these, cease to pretend to honour on account of them, that we may become subjects of the honour which cometh from God only, and which depends upon the degree in which we receive, and exercise, affections of charity. Thus will our external man be conjoined to the internal, and we shall (according to the signification of the name of Barak) attain the blessing of the marriage which the king made for his son, and which results from the union in the soul of truth with goodness, or of faith with charity.




