
<<<
---
== Chapter IX. Judges 4:16-22 (Part 1)

"_But Barak pursued after the chariots and after the host unto Harosheth of the Gentiles: and all the host of Sisera fell upon the edge of the sword; and there was not a man left. +
Howbeit, Sisera fled away on his feet to the tent of Jael the wife of Heber the Kenite: for there was peace between Jabin the king of Hazor and the house of Heber the Kenite. +
And Jael went out to meet Sisera, and said unto him, Turn in, my lord, turn in to me; fear not. And when he had turned in unto her into the tent, she covered him with a mantle. +
And he said unto her, Give me, I pray thee, a little water to drink; for I am thirsty. And she opened a bottle of milk, and gave him drink, and covered him. +
Again he said unto her, Stand in the door of the tent, and it shall be, when any man doth come and inquire of thee, and say, Is there any man here? that thou shalt say, No. +
Then Jael Heber's wife took a nail of the tent, and took an hammer in her hand, and went softly unto him, and smote the nail into his temples, and fastened it into the ground: for he was fast asleep and weary. So he died. +
And behold, as Barak pursued Sisera, Jael came out to meet him, and said unto him, Come, and I will show thee the man whom thou seekest. And when he came into her tent, behold, Sisera lay dead, and the nail was in his temples._" (Judges 4:16-22)

In my work on "The Plenary Inspiration of the Scriptures", I have recited this passage as one of those which is used by Deists and Infidels as incompatible with the belief, that the book in which it is contained can really be of Divine origin, and have any right to the title of the Word of God; whereas, when any just notion is possessed of what the Word of God must necessarily be, it is rather one of the passages which prove it to be such.

Certainly, if we are to believe that all the persons whose actions are recorded in the Scriptures with expressions of approval, are to be concluded to be holy characters, and their actions to be such as truly receive the divine approbation, there would be no small difficulty in regarding as divine, the book which thus records the deeds of such a heroine as Jael. To invite the discomfited captain of the Canaanitish army into her tent, in the confidence of the peace which existed between her tribe and king Jabin his master, -- to assure him that there was nothing to fear, -- to perform for him the rites of hospitality, by giving him refreshment and covering him with a mantle to hide him while he slept; and then, as soon as, believing himself safe from his pursuers and from every danger, he yielded to slumber, to drive a great nail or tent-pin through his temples with a mallet: -- here was a combination of treachery and cruelty, of which assuredly, few women, and not many men, in any age, have been capable; and which, in most times and countries, would be rewarded, not with exalted praise, but with deep execration.

One would suppose that Barak himself, when invited to behold his massacred enemy, could hardly feel any other emotions than horror and disgust; and that Deborah, who, though a woman, filled the office of judge in Israel, and instigated Barak to the expedition against Sisera, would feel all that was feminine in her nature revolt at such a deed, and would view its perpetration as a disgrace to her sex. But it is certain that her feelings were not of this kind. In her song on the occasion, which fills the whole of the following chapter, she speaks of the deed with the extreme of exultation, and of its performer with the highest encomiums. "_Blessed above women shall Jael the wife of Heber the Kenite be, blessed shall she be above women in the tent!_" (Judges 5:24)

Such are the praises bestowed upon the actress in the tragedy. The reasons are given in the honourable mention, which follows, of her act. "_He asked water, and she gave him milk; she brought forth butter in a lordly dish. She put her hand to the nail, and her right hand to the workman's hammer; and with the hammer she smote Sisera, she smote off his head, when she had pierced and stricken through his temples_." (Judges 5:25-26)

Afterwards a taunting description is given of the great and blighted expectations of his mother, agonized at the delayed return of her murdered son: "_The mother of Sisera looked out at a window, and cried through the lattice, Why is his chariot so long in coming? why tarry the wheels of his chariots? Her wise ladies answered her, yea, she returned answer to herself, Have they not sped? have they not divided the prey; to every man a damsel or two; to Sisera a prey of divers colours, a prey of divers colours of needlework, of divers colours of needlework on both sides, meet for the necks of them that take the spoil?_" And the whole concludes with the devout ejaculation, "_So let all thine enemies perish, O Lord: but let them that love him be as the sun when he goeth forth in his might._" (Judges 5:28-31)

I have shown repeatedly and largely on former occasions, that the Jewish, though called a representative church, was never truly a real church, but was nothing more than the representative of a church, designed to fill up the interval between the utter decline of the ancient church, or that founded with Noah and his posterity, and the arrival of the fulness of time, in which it was possible, and requisite, that the Lord should be born into the world, to provide the means for maintaining a true church in the world for evermore; and thus for opening, through all ages, the effectual way of salvation for all the human race.

This is what Paul means in his Epistle to the Galatians, when he says, that the Law, meaning the Jewish dispensation, was a school-master to bring us to Christ; and that it was appointed because of transgressions; where, by a school-master, he does not mean an instructor, but a governor of children, whose office is to rule and keep them in order until they come of age.

Thus the Law was given while the human race, after the extinction of those generations who had been members of the true churches named after Adam and Noah, was in a state of nonage, and incapable of being governed by any thing better, until they could be brought to such a state of maturity as again to have a true Church established among them, first as the Primitive Christian Church, and afterwards, and permanently, as the New Jerusalem.

The Law was thus the Pedagogue, -- the Master of Children, as that word, being the word used in the original, literally implies, -- conducting the human race onward, after the consummation of the Ancient Church, until the coming of the Lord into the world, -- filling up the interval, in which, otherwise, no resemblance even of a true Church could have been preserved, 

to perform for the whole human race, considered as one great human being, the functions which the heart and lungs discharge in the individual man, 

thus preserving the race in existence by keeping open its communication with heaven, which, if once totally cut off for a single moment, all must perish.

Thus did the Law bring us, -- that is the human race generally, -- to Christ, -- keeping open that communication with heaven, without which, direct or indirect, none could be sustained in life, -- until the states of mankind, and the arrangements of Divine Order, could permit that he should come into the world.

This communication was kept open in and through the Jewish Church, by the Divinely appointed ordinances of their worship, quite independently of the character of the persons by whom it was performed.

Thereby, and by all the particulars of their history recorded in the Word of God, the Israelites and Jews represented the spiritual things and states belonging or relating to the true spiritual Church, without being members of such a Church themselves.

At the same time, the means were thus provided that the Word of God should be written, and should be brought into a more ultimate form, and thus into greater fulness, by thus having real historical facts, not merely allegorical or parabolical relations, as its basis. This was the real design of the calling of the Israelites: in this, and in no other sense, were they the elect people of God. For such a purpose, the more external the character of the people, the better qualified were they to fulfil their mission; they merely represented, and were driven by miracles and punishments, on the one hand, and by the allurement of the promise of worldly rewards on the other, accurately to represent the spiritual things and states belonging to the true spiritual Church, and thus, as a nation, to constitute the representative of a Church, as long as, in the counsels of the Divine Wisdom, such an economy was needful.

Of course, such of them as discharged their duties with sincerity and willing obedience, according to the form of Divine Truth with which they were made acquainted, acquired a capacity for, and were made partakers of, eternal salvation. But it is evident that the sincerity and willing obedience of the parties, were by no means indispensable to their maintaining the representation for which they were selected. Nothing was required for this but the performance of the external representative acts themselves; and a wicked man was quite as capable of sustaining even the most holy representation as a good man; since acts which are in themselves even of a wicked nature, and the commission of which would be very criminal in any but the most external, carnal-minded, unenlightened of the human race, may nevertheless sometimes bear a most holy representation, and correspond to things of a most internal and sacred nature.

Such then is the character of the dreadful action of Jael recorded in our text, and commented upon in the truly divine song of Deborah, on the occasion; -- a song, which is one of the most obviously divine, and divinely sublime effusions, in the whole Word of God. Who can suppose that an ignorant woman, such as, though she filled the office of judge in Israel, it is evident that every woman, and man too, in the whole nation, in that dark period of its history, most certainly was, could, from her own unassisted intellect, have expressed her feelings in such a burst of the most elevated poetry as this song undeniably is? 

How natural is the conclusion, that she was possessed at the time by a divine afflatus, -- that the angel of the Lord, full of the divine sphere, absolutely spoke through her, taking indeed the natural words and images as they lay in her mind, but arranging them in heavenly order, so as to become the properly corresponding expression of truly divine and heavenly sentiments and subjects! 

In the Divine Mind, from which the words were in this manner spoken, there assuredly was no reference to the person Jael, or to her deed, themselves, but to certain divine and spiritual principles and operations which in her and her exploit, found a properly corresponding and truly representative expression; and which found that expression, whatever was the state of mind of Jael in committing the act, or the moral quality of the act as committed by her; both which circumstances, in regard to the representation designed, were of no account whatever.

In any Christian, doubtless, such an act would be most direfully criminal; judged by Christian principles, it must be condemned as most atrociously wicked; but in a person of so barbarous a tribe as, at this time, the race of wandering shepherds was to which Jael belonged, it might not be so utterly inexcusable, as, judged by principles of pure divine truth, it most certainly is. She, -- the individual woman, -- has received her award, in the other life, at the hands of the Omniscient Judge, according to the state of her mind at the time, and her means of possessing any just knowledge of religious and moral duty; or rather, according to her internal state as formed through the whole course of her life, of which this tremendous action is the only one which has made her name known to posterity; and we have no means whatever of knowing, what her state in the other life, in consequence, is.

The blessing pronounced upon her in Deborah's song, is by no means intended to assure us that she is among the blessed in heaven. The history of her act is related, and the particulars of it commented upon in Deborah's inspired poetry, purely in reference to what is represented by it, and to the representative character which Jael bore in performing it. And this is the same, whatever might be the real character of herself as an individual; whether, a penitent for all her sins, she is now a saint in heaven, or, dying in them, she is amongst the lost in hell.

Leaving then Jael, as a private individual, I propose, in another discourse, to inquire into the spiritual representation, and consequent signification, of some of the particulars recorded of her. At present, I will only advert to what is signified by her nation and family.

We are expressly informed, that she was the wife of Heber the Kenite. The Kenites were a tribe of the nation of the Midianites: and the Midianites were derived from the same stock as the Israelites themselves, being descended from Midian, who was one of the sons of Abraham by his second wife Keturah.

All the sons of Abraham not descended from his first wife Sarah, seem to have formed part of that numerous people known under the general name of Arabs, amongst whom 
// the false prophet [-Ed. removed]
Muhammad was born, and who, under the first caliphs and other
// Mussulman [-Ed. replaced]
Moslem conquerors, have formerly made so great a figure in the world. In the latter portion of the history of Midian or the Midianites, as related in Scripture, and when they acted as enemies of the Israelites, they bear a bad signification. But in their earlier times it was otherwise; and they then represent, we are informed, those who are grounded in the truths of simple good; which definition appears to mean, persons of simple but well-disposed minds, who hold the truths of the church in a manner agreeable to their simple state of mind; which preserves them from being injured by false doctrines, when these become generally prevalent.

Thus, it was to the land of Midian that Moses fled when Pharaoh sought his life; and he married a daughter of Jethro, a priest, as is related, of Midian. It was, also, to Midianitish merchants that Joseph was sold by his brethren, who, if they had not found this way of disposing of him, would have killed him. Jethro likewise came to see Moses when at the head of the people in the wilderness, when he acknowledged and worshiped Jehovah, and was the author of a most important measure, which Moses adopted, for the government of the people.

At a later period, either the same person, but who is then called Hobab, or his son of that name (for it is not certain which is meant), came to Moses, and was prevailed upon to stay with them, under the promise that whatever goodness the Lord should show to the Israelites, they would show to him. Accordingly we find that his descendants, under the name of Kenites, always dwelt among the children of Israel. Jonadab and the Rechabites, mentioned with such high commendation by Jeremiah, were of this family.

Now we find that Heber the husband of Jael was descended from this Hobab, the brother-in-law, or father-in-law, of Moses; for we read in the chapter of our text, "Now Heber the Kenite, which was of the children of Hobab the father-in-law of Moses, had severed himself from the Kenites, and pitched his tent unto the plain of Zaanaim, which is by Kedesh" (Judges 4:11). From all which it is indubitable, that the Kenites, and especially that portion of them who dwelt among the Israelites in the land of Canaan, and were descended from the father-in-law of Moses, who was a Midianite according to its best signification, must be representative of some principle of goodness or truth, connected with, and exercising an important influence upon, the states of the church.

Jethro was the author to Moses of an important rule for his government of the people; and Hobab, whether the son of Jethro or himself under another name, was induced by Moses to attach himself to the Israelites, upon the consideration, urged to him by Moses, that he would be to them in the wilderness "instead of eyes" (Numbers 10:31). The eyes, we know, always signify the understanding; if Hobab, then, was to be to the Israelites instead of eyes, it is evident that he must represent some principle from the Lord that guides the traveller to Canaan when his own understanding fails him, or can be of no use, -- a principle of providential guidance, which conducts him in safety, in situations and states, in which, otherwise, he might be totally lost.

What can this be, but something of goodness and truth from the Lord, which flows into him by an internal way, above the region of his own consciousness, and operates for his protection and safety, without his having any distinct perception of what is taking place.

This harmonizes with what, we are informed, is the signification of Jethro as father-in-law to Moses; for as Moses represents the Divine Law, and thus the Divine Truth, his wife's father must represent Divine Good -- that Inmost Good from which the good that is conjoined with the Divine Truth, of which Moses is the representative, is derived.

//<Divine Providence><Providence>
It was on account of this high representation of Jethro, that he was enabled to give such salutary counsel to Moses in relation to his judging the people; and when it is stated on the occasion, that he saw how Moses proceeded in that work, and said that it was not good, he represents also the Lord's Divine Providence, which takes cognizance of all things, and operates to bring into order whatever is not so.

From this ascertained signification of Jethro, then, we may be certain that something of the same general nature must be signified by his descendants; and thus that Jael, as being one of them, must be representative of a principle of Divine Good from the Lord, and of his Divine Providence, operating for the removal of evil, and of evil-doers, when their state is fully made up, so as to prevent them from any longer infesting the good; and this without any consciousness of those who suffer the divine judgment as to how it is effected, signified by Sisera's being asleep when he was killed; or any activity for the purpose on the part of those who are delivered; signified by the blow being struck by a hand which was not of the nation of the Israelites.

These, brethren, are the observations, which it has occurred to me to make, at present, on the extraordinary narrative of the slaying of Sisera by Jael. If what I have imperfectly offered be understood, it will be seen that such narratives afford no argument against the divinity of the Holy Book in which they are recorded, but tend to establish its divinity by throwing light upon its true nature, and upon the nature also of the Israelitish dispensation; as well as upon the true character of that people, the reason why they were taken for a time to be the representative of a Church, and to afford means by which the Word, in all fulness, might be given from the Lord.

And the slaying of Sisera by Jael, whatever the moral character of the act as performed by her, was certainly a most obviously providential interference for the complete deliverance of the children of Israel from their cruel oppressors; and when we see that while it literally was such, it also represents the Lord's providential influence, operating from his Divine Good, for the deliverance of his people, or the protection and salvation of the true members of his Church, we may draw no small encouragement from it for ourselves.

If we are truly members of his Church, we may be assured that the Lord's goodness and providence will be put forth for our protection and deliverance, whenever our states require it; and what by our own arm we are unable to accomplish, will be effectually accomplished by the arm of the Lord; that is, by the hand of his instruments, who are led, by the imperceptible influences of his providence, to the execution of his purposes, all which, whatever form the acts so brought about may take, are purposes of Mercy.




