
<<<
---
=== Prefatory Explanation.

The delivery of the "Sermons on Judges," now first printed, was commenced by the Author in July, 1822, at the place of worship, which the Cross Street Society then occupied, in Lisle Street, London, and was concluded in February, 1823. They formed, originally, a continued series from chapter I. to chapter XI.; but a portion only of the first sermon has been found, which -- is here introduced in the form of Preliminary Observations, and not a vestige of the second; so that the present volume commences with what was really the third sermon of the series. The sixth and seventh verses of the first chapter of Judges, relating to the capture, punishment, and death of Adoni-bezek, formed the subject of the first three sermons, but the text to the third (now the first) had been re-transcribed by the Author, and embraces, as printed, from the first to the seventh verses inclusive. In sermon xviii,, the Author intimates that it had been his intention to carry on the series to the end of the history of Samson. The circumstances that prevented it are thus stated, -- "We have but two Sundays more to continue in our present place of worship, and it will not be expedient, on opening the chapel in Hanover Street, where we must invite the public in general to come and hear us, to begin with the latter part of a series of discourses."

Some of these discourses were delivered on more than one occasion, and alterations were marked in pencil to render them, principally by omissions, suitable for the special purpose; it has been considered desirable however to restore them to their original state as far as possible. Some of them were entirely re-written by the Author: thus of sermon ix. (and x.), relating to the death of Sisera, which he preached in Cross Street Church, September 13, 1846, he says, "About three years since, in a series of discourses on parts of this book of Judges, I delivered one on the war of the Israelites with Jabin, a Canaanitish prince, who reigned in Hazor, an Israelitish city; as related in the preceding part of this chapter; but I did not then offer any explanation of the extraordinary termination of the conflict, by the dreadful act of a woman; as related in the verses I have now read. Twenty-four years ago, indeed, I delivered a discourse upon these verses, and considered the circumstances of the awful narrative at large; but the manuscript of that sermon having been lost by friends, by whom it was borrowed, I have never taken up the subject again, and have not now the smallest recollection of the manner in which I treated it. However, it being so very extraordinary a part of the Word of God, and constituting so important a link in the chain of subjects contained in the present and subsequent chapters, which. I have not so very long since considered, I have thought it might not be unacceptable, or unprofitable, if I make it the subject of our meditations afresh."

Sermon XV was also entirely re-written in 1846, and preached in Cross Street Church. The Author says that above twenty years before, when he originally preached from the Book of Judges, he had fully treated the remarkable circumstances relating to Gideon, contained in chapter vii. verses 2-7, "but that sermon," he adds, "was lost -- lost at least to me; as I never could recover it from a gentleman (not a member of the New Church) who borrowed it, though I often applied for it, and he always assured me it was safe." Thus three sermons were re-written by the Author more than twenty years after the original delivery, in order to make the series complete to a certain point.

All the original discourses appear to have been delivered at Norwich in the year 1828, as the name of that city is written upon the covers. In all probability they were lent to the Society for the use of the leader for the time being. They could not have been delivered there by Mr. Noble, as they were preached on consecutive Sundays through several months, and while he was necessarily engaged in his ministerial duties in London.

Some of the subjects touched upon in this volume are treated more extensively in the Author's celebrated Work, -- to which the reader is referred, -- entitled The Plenary Inspiration of the Scriptures asserted, originally published in 1825, but of which a new and cheaper edition has recently appeared.

In preparing these Sermons for the press, the utmost care has been taken faithfully to preserve the original matter intact -- nothing has been omitted, added, or altered; some evidently clerical oversights only, having been corrected. That the work may be blessed to the good intended by the Author, and tend to the enlightenment and edification of the reader, is the sincere hope of those who have been active in its publication.




