
<<<
---
=== Preliminary Observations.

It is generally admitted by Christians, that the journey of the Israelites from Egypt to the wilderness, is representative of the progress of man from a natural state to a spiritual one: though I believe their ideas even when thus spiritualizing, as they term it, the Scriptures, are so external, that they consider the wilderness merely as an emblem of this world, and Canaan as an emblem of heaven. It is true that Canaan represents heaven when it is considered as peaceably possessed by the children of Israel; it is also true that the Christian is really, as to his internal man, introduced into heaven when he arrives at the state represented by the passing over Jordan; but that he cannot be actually in heaven at this time, is evident from this, that he then has to wage a war of extermination with the inhabitants of Canaan; and certainly his warfares must all be ended before he actually goes into heaven. We find however, not only that all the period during which the Israelites were conducted by Joshua, was a period of war, but that a fresh series of conflicts began immediately after his death; the first of which was that which led to the extraordinary occurrence mentioned in the 1st chapter of Judges respecting Adoni-bezek. Here then it is evident that something distinct from the admission of man after death into heaven, must be meant by the introduction of the Israelites into Canaan. As however the nature of the Israelitish history is a very curious and important subject, and a right understanding of which will greatly assist us in obtaining correct ideas of the nature of the Holy Word in general, I will make some general remarks respecting it. And as this whole book of Judges abounds with singular histories, more than any other book of the Word, we probably may afterwards continue our remarks in a series of discourses on the whole; at present, then, we will confine ourselves to some preliminary observations.

The numerous singular occurrences which distinguish the affairs of the children of Israel, as recorded in the historical parts of the Old Testament, are calculated to excite very different impressions in those who read them, according to the general bias and prevailing inclinations by which they are influenced. The simple and well disposed but un-enquiring mind, beholding in so many instances such extraordinary interferences on the part of a Divine Power, will read with simple devotion, and will gladly appropriate the general lesson, apparent throughout the whole, -- of the blessings which are ever consequent upon a faithful obedience to the divine commandments, and the judgments which ever await disobedience and rebellion. They, on the other hand, who, while they pride themselves upon their superior discernment and powers of ratiocination, are too well satisfied with the pleasures and pursuits that the world sets before them, to be willing to think much about a state of future existence, infer from the extraordinary nature of much of the Israelitish history, that more is related than is really true; and as no such instances of immediate interposition from heaven occur at the present time, they conclude that every pretension of the kind, in any age, must be unfounded. They also endeavour to find inconsistencies in the sacred narrative, and where they see any thing that wears the appearance of being such, they assume it as a decisive proof that none of the context could have proceeded from divine inspiration.

Whilst, however, it is a most certain fact, that all denial of the divine inspiration of the Scriptures, and all reasonings against them, originated in human pride, and in a disinclination towards the admission of any thing of a truly spiritual nature, we nevertheless would by no means affirm that all who ever entertained any doubts on these subjects, or who find any difficulties in the Holy Word, which they are at a loss how to reconcile with a belief in its divine origin, are persons of reprobate minds, whose doubts and difficulties are to be treated with contempt. We believe the Holy Word is the great medium of conjunction between heaven and earth, -- the primary vehicle by which divine influences, including all inclinations and thoughts that are really good and true, are conveyed into the hearts and understandings of mankind. If there were no Church existing on the earth, composed of persons whose minds are enlightened by the Holy Word, and who, instructed thence, frame their lives according to its requirements, there could be no communication whatever between the Lord and man, the consequence of which would be that the human race must perish; whereas, whilst there is such a medium for preserving the connexion between the Author of life and the recipients, it is conveyed through all the nations, however uncivilized, that inhabit the globe, who all are kept, by means of it, in a state capable of being saved. For in the eye of the Lord, the whole human race compose, in a manner, one human form, of which the church which reads the Word, constitutes the heart and lungs, whilst the other tribes form the less noble organs and members; and as no single human body could live without a heart and lungs, into which life first flows from the soul, and is thence circulated with the blood throughout the whole of the system: so the body universal of mankind, could not subsist without a church enlightened by the Word to be to it as a heart and lungs, in which spiritual life is first received from the Lord, and is thence distributed through the whole of the mass. Viewing, then, a belief in the Holy Word as being of such great importance, we must needs consider the denial and rejection of it, by any who live where it is known, as a most awful calamity to themselves; and as taking its primary cause, not from any superiority of intellect, as they themselves would fain have us believe, but from a hidden principle of evil in the heart, which exerts an influence upon their understanding, in a manner they do not suspect, and leads them to prefer views which leave them at liberty to act, as far as outward circumstances will permit, according to every impulse which perverted nature may cause to spring up in their minds. This it is that makes them sharp-sighted in detecting what they conceive to be inconsistencies in the writings of which Divine Revelation is composed, and which has given birth to the numerous publications, distinguished sometimes by subtlety and sometimes by railing, in which attempts are made to overthrow the Christian religion, and, as an important step thereto, to destroy their credibility.

These remarks may tend to prove the duty of making the reading of the Word, both by young and old, a matter of daily practice. The mere reading, even where nothing is understood beyond what the letter expresses, may have the effect of bringing around us a heavenly influence, and of storing in our interiors, affections for divine things and delights in which angels themselves participate. But to have this effect, be it understood, it must be read either by innocent children, or by adult persons who are in the devout acknowledgment of its divine and holy nature. Where it is read with carelessness, as it does not then penetrate into the mind of the reader, it is productive of no communication with heavenly societies; whilst, if read by a person who is not merely ignorant of the true import of what he reads, but who endeavours to apply it to the confirmation of any false doctrine, especially any that tends to sanction an evil life, it not only produces no good effect, but is in reality attended with a bad one; as the Word, when thus falsified in the mind, is exceedingly offensive to angels and good spirits, who immediately avert themselves from the person, and thus heaven, instead of being opened to him, is more firmly closed against him. But the Word is not falsified when any part of it is applied to confirm a doctrine or sentiment that is true in itself, although that doctrine or sentiment may not in reality be taught in the passage applied to it. Be it then our care, and let us esteem it our privilege, often to impress our minds with the lessons of divine wisdom contained in the sacred Volume. Let us, where we understand nothing beyond the mere letter, ever read it with holy reverence and devotion. Let us too be careful to impress upon our hearts the practical precepts which are every where interspersed through it; and let us remember, that to regulate our affections and practice by such precepts, is the only effectual way to acquire any permanent knowledge of the sacred contents that lie within the letter: since whatever is learned in the memory only, without entering the life, never becomes our own, and will finally be taken from us. How beautiful on this subject are the experimental declarations of the Psalmist! "Through thy precepts I get understanding; therefore I hate every false way." -- Again; "I have more understanding than all my teachers; for thy testimonies are my meditation." And since the Word is thus, as to its essence, the Very Divine Truth Itself, the eternal truth of God from everlasting to everlasting, how true is the Psalmist's declaration respecting it: "Thy word is true from the beginning; and every one of thy righteous judgments endureth for ever."



