
== THE SCRIBES AND PHARISEES — Luke 11

=== INTRO

With the younger classes we have chosen the latter part of the chapter for emphasis because it is less familiar than the portion on prayer, but with the older classes both parts should be taken up. Verse 33 may be used to bind the two parts together, for it is only as we turn to the Lord as our Father and seek His guidance and help that we can keep the eye of our soul "single" or clear. The scribes and Pharisees are the classic example of what not to do with our religion.

=== Doctrinal Points

The Lord's deeds showed the divine within Him.

The Lord constantly used passages from the Old Testament. 

Faith comes through knowledge of the Word.

It is the heart which most needs cleansing.

=== Notes for Parents

We know that the Lord, when He was in the world, gave us a wonderful example of love and self-sacrifice and daily service. We know that He healed people of many diseases and raised the dead. We think of Him as tender and gentle, loving and forgiving. But there were two groups of people whom the Lord condemned in no uncertain terms. They were the scribes and Pharisees, the people who were learned in the law of Moses and made a great show of religion, while at heart they were proud and selfish and hard, expecting everyone to admire and serve them. He called them hypocrites.

Perhaps you have heard of the "unforgivable sin." According to Matthew 12:31 it is blasphemy against the Holy Spirit. People have sometimes worried a good deal about it because they did not know just what it meant and were afraid they might commit the unforgivable sin without knowing it. The Holy Spirit is the spirit of truth proceeding from the Lord to enlighten us and show us what is right and wrong. To blaspheme against the Holy Spirit is to know what the truth is and refuse to try to do it. The scribes and Pharisees really knew they should accept the Lord, but they would not acknowledge it because they did not want to change themselves. They could not deny the Lord's power, for they saw His miracles; so they said His power came from "Beelzebub the chief of the devils." They wanted to appear good, but they did not want to be good.

This sin is unforgivable not because the Lord is unforgiving, but because the person who acts this way will not let the Lord's forgiving spirit enter his heart. This is why we pray, "Forgive us our debts as we forgive our debtors." If we refuse to listen to the truth or to acknowledge it as truth when we do hear it, the truth cannot reach us to purify our hearts and minds and lead us to the Lord. To His disciples, who believed and obeyed Him, the Lord said, "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you." The hypocrite closes the door of his heart and mind against the Lord. It was the scribes and Pharisees who finally crucified the Lord.

If you will read this chapter thoughtfully, you will find that each part of it — and it can be divided into several apparently separate parts — has something to contribute to the general teaching that if we would be good people, we must keep our hearts and minds constantly in a state of willing reception of the Lord's truth. It is not enough to do the outward good deeds which make us popular with our neighbors. Goodness is something within us which can come only from the Lord. The Lord speaks to us today in His Word just as really as He spoke to the people in Palestine nearly two thousand years ago. Are we among those who hear Him gladly, or do we close our minds to His teachings in the Word because it might say something we did not want to hear? The chapter speaks to us all.

=== Primary

The children should be told who the scribes and Pharisees were and led to see the meaning of verses 33 and 34. The teacher might read as an illustration the story of the Pharisee and the publican from Luke 18:9-14.

When the Lord was on earth, the good people welcomed Him and listened eagerly to all He had to tell them about the right way to live, because they wanted to do right.

You know that when you are feeling like being good, you ask your parents all kinds of questions and listen to what they tell you and understand it; and if you will think back a little, you will realize that those are the times when you are happiest. Isn't it too bad that we are not always like that?

But you know that there are times when you don't like to hear what your parents say to you and don't want to understand it. These are times when you are feeling like having your own way and doing something you want to do whether it is right or not.

So when the Lord was on earth, there were many people who did not want to listen to Him and who refused to try to understand what He told them, because they were used to having their own way and did not want to change it. These people even said that the Lord's power came from Beelzebub, which is another name for the devil. If they had admitted that it was the power of God, they would have had to believe Him because they had always pretended to be especially religious.

The scribes were men who spent their lives studying and copying the Old Testament and teaching people the law.

And the Pharisees were a sect who pretended to be very strict keepers of the law.

Both these groups knew all the prophecies about the coming of the Messiah. You would think they would have been the first to welcome the Lord when he came.

But they had become used to having everybody look up to them, and they could not bear to have the people turning to anyone else for instruction.

So they tried in every way to prove that Jesus was not the Messiah.

They said His power came from the devil instead of from God.

They knew the Scriptures, but they covered up their real meaning with their own ideas.

They were like a person who covers up a candle so that it can give no light. 

What complaint was made by the Pharisee who invited the Lord to dinner? What did the Lord tell nim ?

The Pharisees were very careful to pay their tithes or dues to the temple. What did the Lord say they had overlooked?

Of what did He accuse the lawyers?

We should always listen when our parents are trying to tell us what is right, and be willing to see and understand what is true instead of just seeing what we want to see. Then the eyes of our souls will be "single" — which means pure — instead of evil. The truth which the Lord gives us is like a light by which we see how to live. We should not want to cover it up as the scribes and Pharisees did. This is what verse 33 is saying to us.

Then let us read the verse which follows it in the Bible. [Read Luke 11:34.] You know that we all say "I see" when we mean "I understand."

The verse means that if we keep our understanding clear and pure, our minds will have light.

But if we let selfishness cloud the eye of our minds, we cannot see what is right.

=== Junior

The Juniors should learn well who the scribes and Pharisees were, why they refused to recognize the Lord, and why the Lord condemned them. They should also learn the word hypocrite and what it means. The Bible references in their notes should be looked up.

Our chapter for today begins with the story of how the Lord gave us the Lord's Prayer. The form in Luke is not so familiar to us as that in Matthew, but there are two things about it which we should especially notice. One is that the last sentence in verse 2 gives the order "as in heaven, so in earth," which is actually the order in the original Greek in both Matthew and Luke.* If we are to do the Lord's will on earth — in our outward lives — we must first write His will in the heavens within — our minds and hearts. The second is the use of the word sins instead of debts. As you may know, in many churches the form used is, "Forgive us our trespasses, as we forgive those who trespass against us." This is not the form given in either Gospel, although Matthew introduces it in the Lord's explanation of the prayer. We often do need to pray for forgiveness of our sins or trespasses, but we always need to pray, "Forgive us our debts," for we are in debt to the Lord for everything we have.

[*This phrase, however, occurs only in Codex Vaticanus in the Luke version. Later versions omit "Thy will be done ..." cf. @AC 2009[2], where it is cited as above, although the explanation then renders it "on earth as in the heavens." @AE 1217[2] also quotes the Matthew version as "on earth as in the heavens," but then states that "the Lord always rules both heaven and earth." -Editor]

Read verses 5 to 10 and then read Matthew 6:7-8, which are the verses just before the Lord's Prayer in that Gospel. These seem to say different things, don't they? Now read Matthew 7:21-23. You see, when the Lord is speaking to His disciples, He is speaking to those who are trying to learn from Him and to obey Him. When we are His true disciples, He is always ready to hear and answer our prayers, even though sometimes for our good the answer has to be, "No," just as it does when we ask our parents for things which they know would do us harm. In the Gospel of Matthew the passage about the Lord's Prayer is part of the sermon on the mount, which was preached to a great crowd of people, who were in various states of life.

Most of our chapter today is about the Lord and the scribes and Pharisees. The scribes or "lawyers" were those who were educated in the law of Moses. They spent their lives reading and copying the books of the Old Testament, and they were the ones who told the people what the law said. Read Matthew 2:3-6. The Pharisees were a sect who claimed to be more religious than any others and who made a great show of their religion and expected to be looked up to by everyone because of it. See what is said of them in Matthew 23:5-7. These two groups had added a great many laws and regulations of their own to the laws of Moses so as to keep people under their own control, and the people — most of whom could not read — had no idea what was really the law of the Lord. The scribes and Pharisees of course knew all the prophecies of the coming of the Messiah, and they should have recognized and welcomed the Lord but, like Herod, they did not really want any ruler in the land instead of themselves.

Where did they say the Lord's power came from? 

What did the Lord tell them?

In verse 16 what did His enemies ask for? 

What sign did He say they would have?

In Matthew 12:39-40 you will find what He meant by the "sign of Jonas the prophet." He was referring to His own coming crucifixion and His resurrection on the third day. Jonas is a Greek form of Jonah. The story of Jonah and the people of Nineveh is found in the third chapter of the book of Jonah. The "queen of the south" means the queen of Sheba. If you do not remember that story, read it in 1 Kings 10:1-10. You see that if we are to understand what the Lord says to us in the Gospels, we need to study the Old Testament.

When in verse 33 the Lord says that a candle should not be lit and then covered up so that the light cannot be seen, He is referring to the way in which the scribes and Pharisees had covered up the truths of the Word so that the people could not see them. In this verse, the translation should be lamp and lampstand instead of candle and candlestick. They did not have candles in those days. Their lamps were dishes formed like a very shallow pitcher with a handle. They burned oil in them, which came up to the spout in a wick so that the flame was at the spout. We should also know that the word single in verse 34 is an old word for clear or pure. The Lord's teaching here is that it is selfishness which prevents our seeing the truth. We should remember this when we are refusing to recognize what we ought to do because we want to have our own way instead. We are all sometimes like the scribes and Pharisees.

The Pharisees saw that the people believed in the Lord. So they often pretended to listen to Him, but it was only in the hope that they could find something in His words or actions which they could tell the people was wrong. So in our chapter one of the Pharisees invited the Lord to dinner.

What did the Lord do which he objected to?

What did the Lord tell him?

What did He say about tithes?

The tithe was the tenth of their produce of every kind, which they were supposed to give to the service of the Lord. The Pharisees made a great show of paying their tithes.

What did the Lord call the scribes and Pharisees?

A hypocrite is a person who pretends to be what he really is not, so that people will praise and respect him. We should try to be good all through — in our thoughts and feelings as well as in our acts. The Lord sees our hearts and minds just as He saw those of the scribes and Pharisees.

=== Intermediate

Center the lesson on the correspondence of verses 33 and 34, using the disciples of the first part of the chapter as an illustration of those whose eye is "single" and the scribes and Pharisees as an illustration of those whose eye is "evil."

From our lesson in Malachi you may remember that the coming of the Lord into the world would be to the wicked like a consuming fire which would burn them up. In our lesson today we find how this prophecy worked out. The scribes and Pharisees in the Gospel story typify that element which at heart hated all the things the Lord came to teach, although outwardly they posed as the most strictly religious of all the people. The scribes — also called lawyers — were the learned men who studied the Old Testament and were regarded as authorities in the law of Moses. The Pharisees were a sect who prided themselves on their strict observance of the law. But both these groups loved the power they had over the people, and they had added many regulations of their own to the law in order to keep the people in subjection to themselves. As long as the people looked to them for instruction, their position was secure, but when first John the Baptist and then the Lord Himself appeared, and the people began to listen to them, the scribes and Pharisees felt their hold on the people weakening, and they "burned" with anger and with hatred of the Lord. They knew the prophecies and should have recognized Him as the Messiah, but, like all of us at times, they believed what they wanted to believe.

This is what is meant by verses 33 and 34 of our chapter. Light is one of the principal symbols of truth. A candle or lamp by whose means light is given forth represents doctrine. "Thy word is a lamp unto my feet, and a light unto my path." Do you remember how the Lord, when He appeared in Revelation to the apostle John, was seen in the midst of seven candlesticks? In Revelation 1:20 we read: "The seven candlesticks which you saw are the seven churches." It is the church which is supposed to teach true doctrine so that its people will be able to walk in the light instead of stumbling in the darkness of ignorance. The scribes and Pharisees, who considered themselves to be the church, covered up true doctrine instead of teaching it. Their own self-love had closed their minds to the truth even when it came to them in the person of the Lord Himself.

The eye, you remember, corresponds to the understanding.

When the understanding is not clouded with selfish thoughts, the eye is "single," that is, pure or clear. But when selfishness governs the understanding, the light of truth cannot penetrate. You know how this is from your own experience. When you are trying to have your own way about something, your mind is so busy finding reasons why you should be allowed to do what you want that you will not listen to the simple truth. The scribes and Pharisees had to admit the Lord's power to work miracles, but in order that they might not have to admit that He really was the Messiah they claimed that His power came from the devil (verse 15). We should remember this verse, because it shows us how far one can go when he is trying to have his own way, and also it shows us that miracles do not produce faith.

The Lord's description in our chapter of the character of the scribes and Pharisees is summed up in the word hypocrites in verse 44. The same charges are made in more detail in the twenty-third chapter of Matthew. In both Gospels there are two charges which most of us remember better than the others. One is that they are careful to pay their tithes but forget to practice the virtues that the tithes stand for — "judgment and the love of God." The other is that they cleanse the outside of the cup and platter, but leave the inside full of wickedness. The cup, which held wine, pictures the knowledges we have in our minds which are capable of containing spiritual truth. The platter, which held food, pictures things in the mind which should contain goodness. So you see how exactly this verse describes the hypocrisy of the scribes and Pharisees. They had all the necessary knowledges from the Scriptures, but they had let their selfish desires and reasonings fill them up so that there was no place for truth or goodness.

There are many other interesting things in this chapter. It gives us, for one thing, our second version of the Lord's Prayer. You will notice that it differs slightly from the version in Matthew. The translation "as in heaven, so in earth" is a more accurate rendering of the Greek than "on earth as it is in heaven" (see footnote to Junior notes). Swedenborg tells us that unless it is the desire of the heart and mind — the heavens of the soul — to do the Lord's will, our outward doing of it — the earth — is not sincere. So this, too, is related to the general subject of our chapter. The parable of the householder and the promise in verses 9 and 10 are addressed to true disciples of the Lord.

The "sign of Jonas the prophet" mentioned in verse 29 means, as we learn from Matthew 12:40, the Lord's resurrection on the third day after the crucifixion. Jonas is a Greek form of Jonah. We remember that Jonah, after three days in the belly of the great fish, was cast up alive on the shore, and now we see that this was one of the prophecies of the Lord's life on earth. The story of Jonah and the Ninevites is told in chapter 3 of the book of Jonah. In verse 31 the "queen of the south" means the queen of Sheba. The story of her visit to Solomon is told in 1 Kings 10:1-10.

=== Basic Correspondences

a candle or lamp = doctrine 
a lampstand = the church
a cup = a containant for spiritual truth 
a platter = a containant for goodness
the eye = the understanding

=== Senior

The lessons of sincerity and humility are important for your young people. They are often tempted to pretend to feel and think as the rest of their "crowd" does. Hypocrisy may be an expression of cowardice in that case. If they can be led to see it as a danger signal in themselves, they will be led to do independent thinking and will gain in spiritual strength.

When the Lord was in the world, His severest condemnations were addressed to the scribes and Pharisees, the two religious groups who held the position of highest honor among the laity. Both groups were outwardly devoted to the study and keeping of the law of Moses. The Lord charged them with hypocrisy, and their attitude toward Him proved them to be hypocrites. For they knew all the prophecies concerning the Messiah and pretended to be looking forward to His coming, and yet when one appeared who fulfilled all the prophecies, they were unwilling even to consider whether He might be the Messiah because His presence and teaching were a threat to their own power over the people. They even said His ability to work miracles — which they could not deny — came from the devil.

We all dislike hypocrisy when it is uncovered. But we do not always stop to think what it really is or to ask whether we ourselves may be guilty of it. In @TCR 147 Swedenborg says: "It is as yet scarcely known in the church that in all of man's will and thought and his consequent action and speech, there is an internal and an external, and that from infancy man is carefully taught to speak from the external, however the internal may dissent; and that this is the origin of simulation, flattery, and hypocrisy; and thus man becomes double—minded. But he alone is single—minded whose external thinks and speaks and wills and acts from the internal; and such are meant by the 'simple (single)' in the Word (as in Luke 8:15; 11:34, and elsewhere). Nevertheless these are wiser than those who are double—minded." This does not mean that we should always be in the attitude of "calling a spade a spade," as some rather disagreeable people enjoy doing. We remember that our first step toward regeneration is reformation of the outward conduct, even against our natural inclinations, and that the Lord makes use of our natural desire to be liked and praised to help us in the beginning of this reformation. You recall the story of the quails and manna in the wilderness, and that the quails represented natural satisfaction from doing right. But this is only the beginning, and there is nothing genuine about our outward goodness until we reach the point where it comes from the heart. This is why in the original Greek in Matthew as well as in Luke the petition in the Lord's Prayer reads, "Thy will be done as in heaven so in earth" (see footnote to Junior notes), just as it is translated in verse 2 of our chapter [KJV]. This is the true order of doing good and the state of mind and life for which we should pray.

The first part of our chapter emphasized the Lord's unselfish love, His willingness to give all good things to those who look to Him for goodness. This is pointed up by the miracle — told in a single verse — of the dumb man who was able to speak when the Lord had cast out the devil who possessed him. You remember from the story of Zacharias that dumbness represents inability to "confess" the Lord. The scribes and Pharisees saw this miracle. They could not deny the fact. It should have led them to acknowledge the Lord themselves. But their minds were so clouded by thoughts of self-interest that they said the Lord's power came from Beelzebub. Their inner state is described by the Lord in the story of the house that is swept and garnished only that it may become the abode of seven devils instead of one.

All through the chapter the Lord points out to us by one means after another that it is our will — our free choice — which determines whether we acknowledge the truth or not. The men of Nineveh and the queen of Sheba were Gentiles. They did not have the direct knowledge of the Lord in the Scriptures which the scribes and Pharisees had. Yet they recognized wisdom when they heard it because they were humble—minded before the Lord while the scribes and Pharisees did not recognize the Lord Himself.

In verse 33 the Lord is referring to the treatment His truth had received at the hands of the church. A candlestick — or lampstand, as it should be translated — is a symbol of the church, whose office is to hold the truth high so that men will receive its light. And the next verses sum up the lesson in parable form. Then follow the Lord's specific complaints against the Pharisees and the scribes or lawyers — which are familiar to us. They are given in more detail in the twenty-third chapter of Matthew.

Young people just starting out in life need to take this lesson very much to heart. Suppose we put it in this way: Whenever I catch myself behaving toward other people in a way which is contrary to the way in which I feel, it is time to take stock of my feelings and try to straighten myself out inside — to give the inside of the cup and platter a thorough cleansing.

=== Adult

The whole subject of hypocrisy is an interesting discussion topic. We all condemn hypocrisy, and we should recognize that we are all hypocrites to some extent. The quotations from True Christian Religion and Apocalypse Explained given in the notes below help us to think this problem through and to meet it in ourselves. The question of the limits we should set upon our judgment of others is also important.

Our chapter begins with the giving of the Lord's Prayer. We are more familiar with the somewhat different form given in Matthew, where it is recorded as part of the sermon on the mount. For the New Churchman such differences of form and context create no problem, because we know that the incidents were recalled to the minds of the different evangelists in each case in a providential order, and that the words were providentially directed each time to serve the needs of the internal sense. We should remember, however, that the Gospel was written in Greek and that, whenever any difficulty arises over differences in form in connection with the same incident, it becomes important to know what the Greek says. In the Lord's Prayer, for example, the order "as in heaven, so in earth" is the order in the Greek both in Matthew and Luke (but see the footnote at the Junior level). This order has an evident bearing upon the lesson of the rest of our chapter for today.

In the first thirteen verses of the chapter we are given the picture of what our true relation to the Lord is. We are children of our heavenly Father, dependent upon Him for guidance and help in every phase of our daily life, just as little children depend upon their earthly parents: and if we acknowledge and accept this relationship, we may look to Him with confidence for the supplying of our every spiritual need.

Against this background we are given the picture of the scribes and Pharisees who, while professing to know and keep the law of Moses above all others, rejected the promised Messiah when He appeared among them, because at heart they wanted no rule but their own will. As Isaiah wrote of them, they honored God with their lips, but their heart was far from Him. Read Isaiah 29:13-19 as an exact description of the conditions presented in our chapter.

We may take verses 33 and 34 as a summary of the teaching of the chapter. The scribes and Pharisees had done just what is pictured by putting the candle in a secret place or under a bushel instead of on a candlestick. They had covered up the light of truth in the word of the Old Testament with their own false interpretations and additions, instead of lifting it up where it might give light to the people around them. They posed as the special spokesmen of the church. We recall words of the Lord to John in Revelation 1:20: "The seven candlesticks which thou sawest are the seven churches." The primary function of any church is to teach truth from the Word so that people may walk in the light. When a church covers over this light with reasonings which spring from the exaltation of human intelligence above revelation, it is false to its high calling.

Verse 34 goes to the root of this evil. "The light of the body is the eye." The eye is a symbol of the understanding. The eye has to be "single." Swedenborg renders this word "simple."* The Greek work [and its Latin counterpart], according to the dictionary, means "single, simple, candid, ingenuous, frank, sincere." In our verse this is contrasted with "evil." The Greek word means "wicked, perverse, malignant, evil." So the emphasis is on the state of the heart as influencing the understanding. And in the two words used, the contrast is between an inner state of humility and one of self-will. If we follow this thought through a study of the charges which the Lord makes against the scribes and Pharisees, the picture becomes very clear. We should also read the more detailed record of this condemnation in Matthew 23. The teaching is that we believe what we at heart want to believe, however our outward life may appear.

[*In @AE 526[13], e.g., he has "oculum purum" seu "simplicem" ("clear or simple" [honest] eye).] 

In @TCR 147 we read: "It is as yet scarcely known in the church that in all of man's will and thought and his consequent action and speech, there is an internal and an external, and that from infancy man is carefully taught to speak from the external, however the internal may dissent; and that this is the origin of simulation, flattery, and hypocrisy; and thus man becomes double-minded. But he alone is single-minded whose external thinks and speaks and wills and acts from the internal; and such are meant by the 'simple (single)' in the Word (as in Luke 8:15; 11:34; and elsewhere). Nevertheless these are wiser than those who are double-minded." The rest of this number elaborates and illustrates this thought. Does this mean that we should always say exactly what we think? We have all known individuals who prided themselves on this practice, and they are likely to have been very disagreeable people. Does it mean that we should always do just what we feel like doing? Does it mean that we should not teach our children to observe good manners whether they feel like being polite and considerate or not? The answer to all these questions is, "No." We are taught in our doctrines that reformation of our outward conduct must precede regeneration. But the motive in the effort must be the motive of obedience to the Lord, not the motive of being socially acceptable. When we find that our pleasant words and kindly deeds are not sincere expressions of our inner thought and feeling, our duty is not to change our words and deeds but to set to work to change our thoughts and feelings. For we read in @AE 394[3]:

"When a man does and speaks what is good, true, sincere, and just, for the sake of self and the world he does and speaks them from self, because from the external man without the internal; and such deeds or works are all evil, and if heaven is regarded in them they are meritorious [i.e., self-righteous], and all such are iniquitous." But Swedenborg adds: "In this world no one can determine whether works are from the Lord or from man, since in external form the two kinds appear alike, but they can be distinguished by the Lord alone, and after man's life in the world their origin is disclosed."

The Lord saw the hearts and minds of the scribes and Pharisees.

He had the right to utter the condemnation. We have the right to judge the outward acts of other people but not their motives. And as to our own, we can only strive to keep ourselves in a state sensitive to searching and correction by the Lord's truth as it comes to us in the Word. So we pray that the Lord's will may be done in the heavens of our souls and thence in the earth of our outward lives. This is the ideal we set up as our goal.

=== From the Writings of Swedenborg

@AE 794[3]: "Man has two minds, one spiritual, the other natural. The spiritual mind is what is called the internal and the spiritual man, and the natural mind is what is called the external and the natural man. And as man has an internal spiritual and an external natural, and the internal is conjoined with heaven and the external with the world, it follows that whatever man does from that internal through the external he does from heaven, that is, through heaven from the Lord; but anything that a man does by the external without the internal, this he does from self. This is meant by the Lord's words in Luke ... (Luke 11:39-41). It is said, 'the outside of the cup and of the platter,' and 'the inside' of them, because the 'cup' has a similar meaning as 'wine,' and the 'platter' a similar meaning as 'food'; and 'wine' signifies truth, and 'food' signifies good. It is said also 'give alms,' and this signifies love and charity."

=== Suggested Questions on the Lesson

Junior: How does the form of the Lord's Prayer in Luke differ from that in Matthew? [see Junior notes]

Junior: Who were the scribes? men who copied the Scriptures

Junior: Who were the Pharisees? a strict sect who took pride in knowing the law

Junior: What law did the scribes study? Scriptures

Primary: Where did they say the Lord's power to work miracles came from? Beelzebub (devil)

Junior: What did the Lord tell them? a house divided against itself falls

Junior: What sign did the Lord say would be given to the Jews? that of Jonah

Junior: To what two stories of the Old Testament did He refer? Jonah, queen of Sheba

Primary: What did the Lord say about a lamp? put it on a stand

Primary: What does this mean? it is foolish to light lamp and then hide it

Junior: What is meant by the eye's being single? clear or pure

Junior: What is meant by the eye's being evil? blinded by evil

Primary: With what great fault did the Lord charge the scribes and Pharisees? hypocrisy

Junior: What is a hypocrite? one who only pretends to be good

Intermediate: What were some of the ways in which the scribes and Pharisees were hypocrites? prayed to be seen of men, acted very pious, judged others

Senior: Why did the scribes and Pharisees not want to recognize the Lord as the Messiah? His presence and teachings threatened their power

