
== BELSHAZZAR'S FEAST — Daniel 5

=== INTRO

[In the original four-year series, this lesson was a general lesson on the Major Prophets with a considerable amount of information on the Prophets in general, but also including detailed study of Daniel 5. Thus we have placed it here in this edition. -Editor]

=== Doctrinal Points

The Lord inspired all the Prophets.

The book of Daniel is part of the inspired Word. 

Confidence in self is the opposite of faith in the Lord. 

Humility is essential to goodness.

=== Notes for Parents

The whole Word is really prophecy, because its instruction is meant for people of all time, and even what seems to be merely the history of the ancient Jews tells us things about our own lives, our weaknesses and temptations and how to meet them, and about the Lord as the only source of security and happiness today as always. So the whole Word is our prophet.

But there are also many individuals in the Bible story who are spoken of as prophets. They were chosen and prepared to speak for the Lord to the people. Some of them are not even called by name. Some of those who are named — like Nathan, Elijah, and Elisha — did not give their names to books in the Bible. But at the end of the Old Testament there are sixteen* books which we call "the Prophets." The first four of these are called the Major Prophets because their books are long as compared with the other twelve.

[*A seventeenth book, Lamentations, is included in this group. -Editor] 

The Major Prophets are Isaiah, Jeremiah, Ezekiel, and Daniel.

Isaiah lived in the time of king Hezekiah of Judah. Jeremiah, as we have learned, was a prophet in Judah at the time Babylon conquered it. Ezekiel and Daniel were also from Judah. Ezekiel was a priest and Daniel one of the royal family. But they were both taken away to Babylon with the captives, and their prophecies were given and written there.

Daniel's story is quite a bit like Joseph's, for in his captivity he was faithful to the Lord and the Lord protected him and gave him power to interpret dreams, which brought him to the attention of king Nebuchadnezzar and led to his being made a ruler in the kingdom.

The story of Babylon is the story of how pride and the desire to be greatest and to rule over others inevitably leads to one's own destruction. "Pride goeth before destruction" is one of the proverbs of Solomon which is very true. Chapter 5 of Daniel tells of the defeat of Babylon, which was the result of the final profaning of the holy vessels of the temple of Jerusalem by Belshazzar, the son and successor of Nebuchadnezzar.

When we watch someone going ahead stubbornly in a course which we are sure will end in disaster, we may say, "Can't he read the writing on the wall?" The strange words which Daniel interpreted are from the Chaldean language, which was spoken in Babylon, and which was much like the Hebrew. Belshazzar was frightened by the sudden appearance of the hand which wrote on the wall, but he did not think of repenting. Something from the Word about judgment, heard suddenly, may startle a selfish man, but it does not change him. Our characters are built up day by day by our free choices, and they cannot be changed in a moment.

=== Primary

With this class try to see that the children know what a prophet is and why the prophets were sent; remind them who the Major Prophets were and why they were called "Major." Then spend the rest of the lesson time on the story. Try to teach the children the names of the four Major Prophets.

Do you remember what a prophet is? It is a person who speaks for the Lord. You have heard about some of the Lord's prophets: Samuel, Nathan, Elijah and Elisha, and Jeremiah. Whenever the people were doing wrong, the Lord sent a prophet to rebuke and warn them, because the Lord loves us all and is always trying to keep us from doing what will hurt us, and to show us the way to be really happy.

Some of the prophets, like Nathan and Elijah and Elisha, only spoke the Lord's words, but others were commanded by the Lord not only to speak them but to write them down, because their messages were meant for everyone — even for us today.

At the end of the Old Testament you will find four long books by prophets followed by twelve short ones.

There is another short one, which is called Lamentations, but this really belongs to the book of Jeremiah.

The four prophets through whom the four long books were written are called the "Major" Prophets.

The prophets through whom the twelve short books were written are called the "Minor" Prophets.

This is just because of the difference in length of the books. See if you can learn the names of the four Major Prophets. 

Isaiah lived in the day of king Hezekiah of Judah.

When did Jeremiah live?

Ezekiel and Daniel were both among the people carried off by the king of Babylon, and they prophesied in captivity in Babylon.

But Daniel became a very great man in the land of Babylon.

This was because he always obeyed the Lord and the Lord could protect and enlighten him.

Who was king of Babylon at the time of our lesson?

What did he do that was wrong?

What happened which frightened him?

To whom did he first go to find out what the writing meant?

Why was Daniel called in?

What did he say the writing meant? His prophecy came true immediately.

Do you know why the Lord does not send prophets to us today? It is because He has given us the Word, in which we can read all the things He wants us to know.

=== Junior

The Juniors have been told something about the difference between the Jewish canon of Scripture and the New Church canon, and this knowledge can here be carried a step further. They should also remember something about both Isaiah and Jeremiah. They may even have some recollection of Ezekiel's vision. Always get as much as you can from their own memories. The character of Daniel will be stressed more in our next lesson; so Belshazzar's sin and the interpretation of the writing should be the main lesson this time.

What is a prophet?

Why did the Lord send prophets?

What do we have to speak to us for the Lord?

We have learned that the part of the Jewish Bible called "The Prophets" contains the "Former Prophets," the books from Joshua through 2 Kings (except Ruth), and the "Latter Prophets," the books from Isaiah through Malachi (except Lamentations, which really belongs with the book of Jeremiah). We usually think of the first group as historical books, and of the second group as "The Prophets." These in common thought are again divided into the Major Prophets and the Minor Prophets. This is only because the first four are "full—length" books, whereas the last twelve are very short books. "Books" in Old Testament times were really parchment scrolls. Each of the four Major Prophets required a whole scroll, while the twelve Minor Prophets were all written on the same single scroll.

Who were the four Major Prophets?

When did Isaiah live?

When did Jeremiah live?

Where did Jeremiah die?

Jeremiah wrote the Lamentations after he was carried away to Egypt. The other two Major Prophets — Ezekiel and Daniel — also wrote in captivity, but Ezekiel had been a priest, and perhaps a prophet, before he was carried away to Babylon, and this is probably one reason why his book was included among the books of the prophets. Another reason may be that Ezekiel was more than once carried "in the spirit" back to Jerusalem to receive his visions. It was felt that it was very doubtful that a prophet could be inspired outside of the Holy Land. This is why Lamentations and also the book of Daniel are not in the Hebrew "canon" of Scripture. A "canon" is an ecclesiastical ruling or decision.

Daniel prophesied in Babylon. He was one of the young men of the royal household of Judah who were among the first to be carried away when Nebuchadnezzar conquered Judah. Read Daniel 1:1-7 to learn the beginning of Daniel's history, and then read the next few verses of that chapter to see how Daniel became a prophet. We have had the story of Nebuchadnezzar's image, and you will remember that when all the wise men and astrologers of Babylon could not tell Nebuchadnezzar what he had dreamed and what his dream meant, Daniel came and told him, and so he made Daniel one of the rulers of his kingdom. Chapter 4 tells of another dream of Nebuchadnezzar which Daniel interpreted, and how his interpretation came true. This is the story to which Daniel refers in verses 18 to 21 of our chapter for today. The king in our story is the son of Nebuchadnezzar, and he has forgotten his father's experience and has forgotten Daniel as well.

Who is this king?

What wrong thing did he do?

What happened which frightened him?

Whom did he first call in to tell him what the writing meant?

Could the wise men of Babylon help him?

Who reminded him of Daniel?

What did he promise Daniel if he could interpret the writing?

What did Daniel say about this promise?

What were the words of the writing?

What did Daniel say they meant?

What happened to Belshazzar?

What happened to his kingdom?

So the Medes took over the kingdom immediately, just as Daniel had prophesied. Their next king after Darius was Cyrus the Persian (Daniel 6:28).

Perhaps you have noticed that when Daniel interprets the writing on the wall, he uses the word Peres instead of Upharsin; so you need to know that this is just a different form of the same word. The U in Upharsin means "and" in the Chaldean and Hebrew languages, and putting this sound before a word often changes the sound of the first letter of the word; here it makes the difference in sound that there is between "p" and "ph." The changes in the last part of the word are also easily understood if one has studied the language. The Chaldean language, which the people of Babylon used, was almost the same as Hebrew.

=== Intermediate

Do more in this class with the Prophets as a whole. Make connection with previous lessons through Isaiah and Jeremiah and later through Nebuchadnezzar. More will be done in the next lesson with Daniel as an individual; so the major part of the lesson time may be given to a discussion of the story in our chapter and its meaning — the final result of the love of dominion.

We divide the books of the Prophets into the "Major" and the "Minor" Prophets solely on the basis of the length of the books, those of the twelve Minor Prophets being very short. There were many prophets besides those who gave their names to books in the Bible. We have heard of some of them in our lessons: Nathan, Elijah, and Elisha. There were many others. Samuel — who was himself a prophet — established schools for the training of young men to be suitable for prophets, and we hear of these groups several times in the Bible story, especially in the time of Elijah and Elisha. Read 2 Kings 2:5-7, 15-18. These young men studied the law of the Lord and forms of worship, and followed certain orderly and temperate ways of life which would make them such that the Lord, if He chose, could use them as instruments when He wanted to speak to the people. We read in the Word also of false prophets who deceived the people by pretending to speak for the Lord when He had not spoken to them. But through the true prophets the Lord spoke many things which were for the times only and therefore not recorded in the Word. Those prophecies which He commanded to be written were for all men of all times. So the whole Word is our prophet, for in it are all the messages which the Lord wishes us to hear, and in His Second Coming the Lord has given us the means of understanding these messages as we come to need them. The books of the Prophets especially are mysteries to us without this help which the Lord has given the world through Emanuel Swedenborg.

There are four Major Prophets: Isaiah, Jeremiah, Ezekiel, and Daniel. Isaiah, we remember, lived in the time of king Hezekiah of Judah, and Jeremiah in the last days of Judah. The book of Lamentations, which follows Jeremiah in our Bible, was given through Jeremiah after he was carried away into Egypt. Ezekiel and Daniel prophesied in captivity. Ezekiel was a priest as well as a prophet.

To know about Daniel we should read Daniel 1:1-7. He and his three special companions were evidently young men of royal blood in Judah and were distinguished from the rest not only by their intellectual ability but also by their absolute faithfulness to the teachings in which they had been brought up before they were carried off to Babylon. Because of their faithfulness they could be completely protected by the Lord, and Daniel was given the power of interpreting dreams and also prophetic power. This was recognized by the kings of Babylon and resulted in the advancement of all four young men to high position in the kingdom.

Our story for today is a striking one, and is one of the well-known parts of the Bible. You may sometimes hear people say of a person who is persisting stubbornly in an obviously wrong course, "Can't he see the writing on the wall?" Belshazzar was the son of Nebuchadnezzar. He had apparently reorganized his father's kingdom under new lords who were his own favorites, and Daniel had been forgotten. Nebuchadnezzar had been a proud king. You remember that Babylon represents the love of dominion. The story to which Daniel refers in verses 18 to 21 of our chapter for today is told in chapter 4. But Nebuchadnezzar was willing to learn from his experience, and after he was restored to sanity he humbled himself before the God of Daniel, who had told him through Daniel what was to happen to him.

Belshazzar was not the wise man his father had been. Nebuchadnezzar had carried away to Babylon all the golden and silver vessels of the temple (2 Kings 24:13), but he had kept them with his treasures in the house of his own god. Now Belshazzar brought them out and profaned them by using them at his feast to add to his own importance and glory. The vessels of the temple represent knowledges of good and truth from the Word which contain the "wine" of spiritual truth and are given to enable us to worship and serve the Lord truly. When these knowledges are used selfishly — to "set us up" above others — we profane them. Swedenborg tells us a good deal about profanation, which is defined as knowing and acknowledging the truth and refusing to live according to it. We all do this to some extent, and there are different kinds and degrees of profanation. Belshazzar's act represents one of the most serious forms of profanation, which destroys spiritual life.

The handwriting on the wall presents a vivid picture in the letter.

The sudden appearance of the "fingers of a hand" and the strange words stay in our memories. It represents the plain condemnation from the Word of such profanation as Belshazzar's. It frightened Belshazzar because of its supernatural character, and his fear led to the reappearance of Daniel. Belshazzar rewarded Daniel for his ability to interpret the writing. But once the writing was interpreted, there is no record that Belshazzar tried to undo what he had done. And the appeal to Daniel and the reward given him did not save Belshazzar or his kingdom. There is an important lesson in this. No one is saved by what he does in a state of fear, because when we are frightened, we are not acting freely. After the fear is past, we fall back into the state which we have developed in ourselves by our free daily choices of right or wrong. We are in the end what we make ourselves by our whole life, and we cannot be changed in a moment.

We may know that afterward the vessels of the temple were put back among the royal treasures because later, in the first year of the reign of Cyrus the Persian, when the captives were allowed to return to the Holy Land, Cyrus gave them back the vessels of the temple. You may read this story in the first chapter of the book of Ezra, which is not one of the books with an inner sense but is very valuable for our knowledge of the return.

=== Basic Correspondences

vessels of the temple = knowledges from the Word which enable us to worship
wine = spiritual truth
the writing on the wall = judgment from the Word

=== Senior

Draw as much as possible upon the knowledge which the pupils themselves have of the general facts concerning the Major Prophets. It is good for the young people to find out how much or how little they know about the Bible. The chapter assigned is a valuable one for them, and the lesson can be easily brought out by contrasting Belshazzar with Nebuchadnezzar. The teacher should read all the pupils' notes from the Junior level up for an adequate background.

The four Major Prophets are Isaiah, Jeremiah, Ezekiel, and Daniel. We call them "Major" only because their books are longer than those of the twelve Minor Prophets which follow them in our Bible. All the prophets were equally inspired by the Lord, but some prophesied over longer periods than others. Not all the prophets were commanded to write down and preserve their prophecies, although in some cases — such as those of Nathan, Elijah, and Elisha — many of their words were recorded in the course of the story. Many of the prophets are not known to us at all by name. In fact, all of the Word — whether or not we know through whom it was given — is prophecy because it is for all men of all time, and so we may think of the whole Word as our prophet, who instructs us and blesses or warns or condemns us, according to our daily choices.

In the letter, the books of the Prophets are often obscure and in places apparently meaningless to us. Yet with the assistance of the writings of the Second Coming we can find in them much instruction and help, and Swedenborg tells us that we should read all of them regularly because even those passages which are beyond our present experience bring us some light and help, for the angels who are with us as we read are understanding their spiritual meaning [see @AC 6333].

We have some personal knowledge of Isaiah and Jeremiah from our study of the latter part of the history of Judah. Ezekiel and Daniel were also from Judah, but their prophecies were written in Babylon. Ezekiel was a priest, already a grown man when he was carried away, but Daniel was one of the young men of the royal family who were selected, at Nebuchadnezzar's command, and brought to Babylon sometime before the final captivity to be trained in the language and learning of the Chaldeans, the language of Babylon. Incidentally, this language was very much like the Hebrew. The words written on the wall in our story for today are Chaldean, and we might note that the word Peres which Daniel translates is just the basic word of which Upharsin is a grammatical form, the U merely meaning "and."

All the young princes of Judah received their instruction from the priests; so Daniel, even as a boy, was well versed in the religion of his own people, and he was one of those who chose to be faithful to it and who were not led away into idolatry after they went to Babylon. All the stories in the book of Daniel teach us this fact. His faithfulness to the Lord made it possible for the Lord to protect him and to give him the power to interpret dreams and to foretell the future.

We have had the story of Nebuchadnezzar's dream of the great image. You will remember that because Daniel was able to tell the dream and to interpret it, Nebuchadnezzar not only made Daniel ruler over the province of Babylon and governor over all his wise men, but he also recognized Daniel's God as a "God of gods, and a Lord of kings." The story about Nebuchadnezzar to which Daniel refers in verses 18 to 21 of our chapter for today is found in chapter 4. You remember that Babylon represents the love of dominion. Nebuchadnezzar was a great and, in general, a very wise king, but he also had the pride and hastiness which come with the love which his nation represents, and these for a time got the better of him. However, when he came to himself and was restored to his royal dignity, he was wise enough to accept the lesson which had been taught him, and his last statement in the Bible story (Daniel 4:37) is: "Now I Nebuchadnezzar praise and extol and honor the King of heaven, all whose works are truth, and his ways judgment: and those that walk in pride he is able to abase."

The last words of this statement are a fitting introduction to our story for today. For Belshazzar, Nebuchadnezzar's son, did walk in pride. Nebuchadnezzar was a great enough man to be capable of humility before the Lord, but Belshazzar's pride did not hesitate to use the vessels of the temple of the Lord to minister to his own vanity. It is not hard to see what this act pictures. When we form too high an opinion of ourselves, we become anxious to prove that our word is law, and we may even become so filled with the idea of our own importance that we use our knowledge of the Word and of spiritual things — which is what the vessels of the temple represent — to make other people admire and flatter us. When we do this, the Lord cannot reach us by means of His Word and save us. Our spiritual death has become certain.

The sudden appearance of the disembodied hand which wrote upon the wall frightened Belshazzar, but neither he nor his wise men could interpret the writing. Then his wife — who represents such affection for truth as remained to him — remembered Daniel. But, although the king recognized that Daniel had told him the truth and gave Daniel the promised reward, he could not save himself. Daniel's prophecy was fulfilled that very night. Belshazzar was slain and Darius the Mede* took over his kingdom.

[*There is no historical record of a king called Darius the Mede (Daniel 5:31 [H.B. 6:1]) — also called "the son of Ahasuerus" (Daniel 9:1). -Editor] 

This illustrates a point which Swedenborg makes more than once — that no one is regenerated in a state of fear or compulsion. We may be frightened or forced into checking an evil course of action, but our desire to pursue it is not at the same time changed. And when we come into the other world, if our ruling love is selfish, we shall choose to live in hell. Belshazzar committed profanation. Read carefully the quotation from Divine Providence which follows the Adult notes.

=== Adult

It might be well to call for questions on the chapter immediately after your brief introduction on the Major Prophets in general. The questions will show the particular phase of the lesson which will be of most interest and value to the class. The teacher should be thoroughly prepared.

As we all know, the four Major Prophets are called "Major" only because of the length of their books as compared with those of the twelve Minor Prophets. The length of the books also gives us more knowledge about the men themselves than we should otherwise have. We know when and where and approximately how long each one prophesied. The first one, Isaiah, appears also in the second book of Kings in connection with the account of the reign of Hezekiah in Judah. In our lesson on the fall of Judah we had occasion to speak of Jeremiah, who was the Lord's prophet in Judah at that time. Jeremiah was spared by the king of Babylon because he had advised the people to submit and pay tribute and remain in their homes, but afterward some of those who were left in the land fled to Egypt, taking Jeremiah with them against his will. The Lamentations of Jeremiah were written in Egypt and were for this reason classed by the ancient Jews among the Tehillim or Writings instead of with the Prophets — where they belong.

Ezekiel and Daniel were among the captives carried away to Babylon. Ezekiel was a priest and Daniel one of those of royal blood who were selected at Nebuchadnezzar's command at the time of his first victory in Judah and brought to Babylon along with part of the treasure of the temple. In Daniel 1:4 we have a description of Daniel and his companions: "Children in whom was no blemish, but well favored, and skilful in all wisdom, and cunning in knowledge, and understanding science, and such as had ability in them to stand in the king's palace, and whom they might teach the learning and the tongue of the Chaldeans." The book of Daniel contains several chapters of consecutive narrative which afford striking stories to teach to children, and in the letter the book is easier to follow and to understand than most of the strictly prophetical books of the Word.

Earlier we have compared Joseph's character and his rise to power in Egypt with the story of Daniel in Babylon. They are strikingly similar. Like Joseph, Daniel became a captive as a very young man but, because he was absolutely faithful to his own God, he was protected by the Lord and given the power to interpret dreams which eventually brought him to the notice of the king and led to his becoming a ruler in the land of his captivity. Daniel's contemporary fame is attested by two references to him in Ezekiel 14:14, 28:3. The last few chapters of the book of Daniel are accounts of his own visions, which in the spiritual sense are prophetic of the whole history of the church from his own time to the Second Coming and the Last Judgment, and in the last chapter he is ordered to "seal the book, even to the time of the end." This connects with the opening of the seals in the fifth chapter of Revelation.

We recall that Babylon represents the love of dominion and that Swedenborg usually interprets it as applying to a particular church in which from love of dominion holy things have been made to serve the ambitions of men and so have been profaned. Nebuchadnezzar's dream of the great image, the subject of our lesson from Daniel last year, pictured the gradual vastation of that church. The history of the spiritual Babylon is very clearly described in @AE 1029. In paragraph 10 of this number a part of our chapter for today is quoted, and we are told that "the church of the Lord (in which the love of dominion rules) successively becomes Babylon; and that as it becomes Babylon so it is devastated as to all the good of love and all the truth of faith; and that this is its end, that is, it is no longer a church; and when it is no longer a church it is reckoned among the idolatrous nations, except those in it who worship the Lord, regard the Word as holy, and admit instruction from it."

Daniel had said, in interpreting the dream of the image, that Nebuchadnezzar was the head of gold. Nebuchadnezzar's dealings with Judah and in particular with Daniel show him to have been in general a wise king, but he had the pride and love of dominion which characterized his nation. They led him astray more than once, as in the story of Shadrach, Meshach, and Abednego in chapter 3 and again more seriously in the events of chapter 4, to which verses 18 to 21 of our chapter for today refer. Nevertheless each time Nebuchadnezzar accepted his lesson, recognized his fault, and humbled himself before the God of Daniel. He was the head of gold of the image.

Belshazzar, the son of Nebuchadnezzar, had all his father's pride and love of dominion but none of his wisdom. Nebuchadnezzar had kept the treasures of the temple which he had brought from Jerusalem laid up with his own treasures in the house of his god. Belshazzar brought them out and profaned them. His act is referred to in @DP 231 (see below), which is a study of various kinds of profanation. There Swedenborg lists seven kinds of profanation of varying degrees of seriousness. Belshazzar's is the fifth kind, which is committed by those "who attribute to themselves what is Divine." It is one of the depths to which the love of dominion in a person may lead, one which brings about the destruction of the church of everything spiritual — in him. Belshazzar could be frightened by the appearance of the strange hand and by the writing which he could not understand, but they did not change him. We are told in the writings that no one is regenerated in a state of fear.* It is by our daily free choices that we gradually form the character which will be ours to eternity. Our most subtle and deadly foe is arrogance and the love of rule.

[*See, e.g., @DP 139, 282, @AE 1155[3]. But cf. @AC 8925. -Editor]

The most striking part of our chapter is, of course, the writing on the wall. In @AR 313 we read: "By 'drinking from the gold and silver vessels of the temple of Jerusalem,' and at the same time worshiping other gods, signifies the profanation of good and truth; as also by 'Babylon.' By 'Mene,' or to number, is signified to know his quality as to truth; by 'Thekel,' or to weigh, is signified to disperse." The words in verse 25 are in Chaldee, the language of Babylon, which is a language very similar to the Hebrew. The word Peres, which Daniel appears to substitute for the word Upharsin, is merely the simple form of the same word. The U in Upharsin means "and," and the other changes in the word are phonetic and grammatical. The International Bible Dictionary suggests that the change to Peres may have been made "to suggest the empire of the 'Persians,' whose empire was to supersede that of Babylon." The king who followed Darius on the throne was Cyrus the Persian.

Daniel the prophet of course represents the Word of God; and we may think of the whole story of Daniel as a picture of how the Word of God is protected, manifests its power, and actually dominates the affairs of the world even among those who profess to be independent of it or to reject it altogether.

=== From the Writings of Swedenborg

@DP 231: "As profanation of what is holy means profanation by those who know the truths of faith and the goods of charity from the Word, and who in some measure acknowledge them, and does not mean those who are ignorant of these, nor those who from impiety wholly reject them, so what now follows is said of the first class, and not of the others. Of the profanation of such there are several kinds, some lighter and some more grievous; but they may be referred to these seven. The first kind of profanation is committed by those who make jests from the Word and about the Word, or from the Divine things of the church and about them. ... The second kind of profanation is committed by those who understand and acknowledge Divine truths, and still live contrary to them. ... The third kind of profanation is committed by those who adapt the sense of the letter of the Word to the confirmation of evil loves and false principles. ... A fourth kind of profanation is committed by those who say with the lips pious and holy things, and counterfeit the affections of love for these in tone and in gesture, and yet in heart do not believe and love them. ... The fifth kind of profanation is committed by those who attribute to themselves what is Divine. ... Babylon and Chaldea are mentioned in many places in the Word, 'Babylon' meaning the profanation of good, and 'Chaldea' the profanation of truth; both of these in such as attribute to themselves what is Divine. ... The sixth kind of profanation is committed by those who acknowledge the Word and yet deny the Divinity [Divinum] of the Lord. ... The seventh kind of profanation is committed by those who first acknowledge Divine truths and live according to them, but afterwards recede and deny them. This is the worst kind of profanation ... "

=== Suggested Questions on the Lesson

Primary: What is a prophet? one who speaks for the Lord

Junior: Why did the Lord send prophets to the people of Israel and Judah? rebuke, warn

Primary: What prophets do you remember who did not write books of the Word? Nathan, Elijah, Elisha, Ahijah

Primary: What is the difference between (1) "Major," and (2) "Minor" Prophets? (1) longer, (2) shorter

Primary: Who were the four Major Prophets? Isaiah, Jeremiah, Ezekiel, Daniel

Junior: When and where did Isaiah live? Judah, Hezekiah's time

Junior: When and where did Jeremiah live? Judah, time of Babylonian captivity

Junior: Where did Jeremiah die? probably in Egypt

Junior: Who wrote the book of Lamentations? probably Jeremiah

Junior: Where was it written? Egypt

Primary: Where did Ezekiel and Daniel prophesy? in captivity

Junior: What was Ezekiel's occupation? priest

Junior: Where was he sometimes taken in vision? Jerusalem

Junior: What power did the Lord give Daniel? to interpret dreams

Primary: Why was He able to give Daniel this ability? he was faithful to the Lord

Junior: Who was king of Babylon when Daniel was first brought there? Nebuchadnezzar

Junior: How did he happen to make Daniel a ruler in the kingdom? interpreted dreams

Junior: Of what other well-known person in the Bible story does this remind us? Joseph

Junior: Who followed Nebuchadnezzar on the throne of Babylon? Belshazzar

Primary: What great sin did he commit? profaned temple vessels

Primary: What happened that frightened him? hand writing on wall

Junior: What were the words written on the wall? MENE, MENE, TEKEL, UPHARSIN 

Junior: What did Daniel tell him they meant? measured, weighed, divided

Primary: When was Daniel's prophecy fulfilled? same night

Intermediate: What does Belshazzar's act represent? selfish use of spiritual knowledge 

Senior: What does the writing on the wall represent? judgment from the Word

