
<<<
---
=== 13 - Solomon's Cities: Tadmor in the Wilderness

1 Kings 9:16.

In chapter v, we read that Solomon made a levy out of all Israel, and the levy was thirty thousand men. And Solomon had seventy thousand that bare burdens, and eighty thousand hewers in the mountains: besides the chief officers who were over the work, three thousand and three hundred, who ruled over the people that worked in the work. It appears however from chapter 9that those who performed the servile labour were the children of the nations of Canaan whom the Israelites had been unable to subdue. On these Solomon levied a tribute of bond-service; but of the children of Israel Solomon made no bondmen, but they were men of war, and his servants, and his princes, and his captains, and rulers of his chariots, and his horsemen. These were the chief officers that were over Solomon's work, five hundred and fifty. This was the usual fate, in olden times, of conquered nations. In the case of the Israelites it represented the natural in subjection to the spiritual, and the service which the lower was made to render to the higher. The Israelites themselves had been bondmen, and had been made to render bond-service, to the Egyptians, and all their service was with rigour; but this represented that inversion of order, the spiritual in bondage, and compelled to render bondservice, to the natural. Besides the house of the Lord, and his own house, Solomon built Millo, and the wall of Jerusalem, as well as a number of cities. Millo, as the name expresses, was a rampart or mound, which had been built by David (2 Sam. 5:9), but was so extended by Solomon, as to entitle him to be considered the builder of the new structure. This and the wall of Jerusalem were for the protection of the city, which now contained the glory of Israel, the house dedicated to the Lord as the true God, to which the nations might look and from which they might learn. The wall, great and high, which encloses and defends the holy city New Jerusalem, shows that the wall of the earthly city had a representative meaning. Walls and ramparts signify the doctrines of the literal sense of the Word; for the literal sense of the Word defends its spiritual sense, as walls defend a city. But as doctrines introduce those who are friendly, as well as exclude those who are hostile, to the Church, the walls of the holy city had gates on all sides.

Solomon built several cities in Canaan itself, which represented internal doctrines of the Church. Hazor was in Naphtali, Megiddo was in Manasseh, Gezer was in Ephraim, Beth-horon the nether was in Benjamin, and Baalath was in Dan. It would be interesting to consider these cities singly as well as collectively, but as this would occupy too much space, it must suffice to notice one or two. Hazor, the first mentioned, and whose name indicates a place of great strength, had formerly been the head of all the Canaanitish kingdoms. This is evident from the account given by Joshua of the conduct of Jabin king of Hazor, when he heard of the defeat of the five kings on the memorable day when the sun stood still. He sent to the kings of the Canaanites east and west, south and north, and they went out, they and their hosts with them, much people, even as the sand that is upon the sea-shore for multitude, with horses and chariots very many. Encouraged by the Lord, Joshua led Israel against this mighty host, and they smote them until they left them none remaining. "And Joshua at that time turned back, and took Hazor, and smote the king thereof: for Hazor before time was at the head of all these kingdoms'' (Joshua 11:1-10). This head of all the Canaanitish kingdoms, which had been destroyed by Joshua, was built by Solomon. "There is a time to break down, and a time to build up "(Ecclesiastes 3:3). Solomon's reign was the time for building up. The reign of goodness is the time for building up habitations of peace where habitations of violence had been, and which the power of truth had destroyed. In the place where the head of all these evil kingdoms had been, Solomon planted a new city in the possessions of that tribe to which Hazor had been assigned, those of the tribe of Naphtali, because that tribe represented those who, by temptation-conflicts, come into a state of liberty, and into the marriage: of goodness and truth.

In the "Adversaria" the city of Hazor, in Joshua 11, is explained to mean the Roman religion, which is expressed by various names. As the leading characteristic of that religion is the love of dominion, which is the desire to rule over all, this is well represented by Hazor being the head of all the kingdoms of Canaan, and by their kings obeying the call of Jabin to come up and fight against Israel. But as the love of dominion is not confined to any one form of religion, nor to any one class of men, we are to look for it and fight against it in ourselves. And when we have overcome that great evil, we are to build up that which is its opposite in character and use. The cities which Solomon built or rebuilt in Canaan occupied the same sites and bore the same names as those they superseded. An evil is but a good perverted. The evils of the Canaanites were the perverted goodnesses of the Ancient Church; and the places in Canaan had their representative character from that earlier dispensation. The Israelites did not originate, they only restored, the symbolisms of the Ancient Church, even in rebuilding the cities which they themselves had thrown down. This city is the first mentioned of those which Solomon built, because the principle it represented is the first in importance of all which these restored cities of Canaan represented.

Gezer is mentioned with this peculiarity, that "Pharaoh king of Egypt had gone up, and taken it, and burnt it with fire, and slain the Canaanites that dwelt in the city, and given it for a present to his daughter, Solomon's wife." Why Pharaoh had gone up against Gezer, which was in Solomon's dominions, it is difficult to conjecture, and impossible, in the absence of any explanation, to understand. We find that when Horam king of Gezer came up to help Lachish, Joshua smote him and his people, until he had left none remaining (Joshua 10:33). The children of Ephraim, who obtained this city as part of their inheritance,
"drove not out the Canaanites that dwelt in Gezer: but the Canaanites dwell among the Ephraimites to this day, and serve under tribute" (Joshua 16:10). This condition of things was not peculiar to the sons of Ephraim and the inhabitants of Gezer, for several of the tribes failed to drive out the original inhabitants of the cities they took, and continued to live together with their vanquished enemies. But Pharaoh, in this instance, accomplished what the sons of Ephraim had been unable to effect. It would seem, indeed, that not only had the children of Ephraim failed to drive out the Canaanites, but that the Canaanites had driven out the children of Ephraim; otherwise Pharaoh would not have burnt the city -- unless we are to suppose that at the time he went up against Gezer he was not on friendly relations with Israel. But whatever may have been the circumstances, the facts recorded are all we have to guide us to their spiritual meaning.

Gezer, as part of the possession of Ephraim, partook of the representative character of the tribe. Ephraim represented the intellectual principle of the Church, or the new understanding, as Manasseh, his elder brother, represented the new will, born and existing in the natural mind. But there is something connected with Ephraim and Manasseh which does not apply to the fathers of the other tribes. They were the sons of an Israelitish father but of an Egyptian mother, for Joseph was married to Asenath, daughter of Poti-pherah, the priest of On, and being born and educated in Egypt, they had something of the Egyptian character as well as nature in them. Asenath was not, like Hagar, a handmaid and concubine, but the daughter of a priest and a wife. She represented, not the affection of science, but the affection of good, but of good having a scientific origin, and therefore having a scientific character. Here we find Gezer, a city of Ephraim, a tribe descended from the son of an Egyptian mother, taken by an Egyptian king, and restored to Solomon, as king of Israel, through an Egyptian wife; for Gezer was part of the dower which Pharaoh's daughter brought to Solomon. Gezer must therefore represent the doctrine of the Church, as built up in the intellect grounded in the affection and perception of science, the science not of material but of spiritual things. For it is to be remembered that Gezer, as it came to Solomon, was but the ruins of the Canaanitish town. Pharaoh took it, and burnt it with fire, and slew the Canaanites; it was Solomon who built or restored it.

There is one other city that Solomon built that demands special notice. Tadmor in the wilderness has acquired celebrity from its having risen, after Solomon's time, from a simple town, for the rest and refreshment of merchants in passing through the Syrian desert, into a city of extraordinary magnificence. To the general reader of history it is better known as Palmyra. Both names have the same meaning, and designate it as the city of palms. The description of this city as given by Jones, in his work on the proper names of the Bible, is the most concise we can present: -- 

" Solomon built this city on a fertile spot, on what is usually called an oasis in the desert; for here were fountains of water to refresh the thirsty traveller, and shady trees to screen him from the sun. It is remarkable that he should have chosen such a spot to found a city, surrounded as it was with an extensive and inhospitable waste -- a wilderness of barrenness and desolation; but when we consider that it was a place abounding with palms and fountains of water, and that all caravans with the produce of Eastern Asia from the Persian Gulf and the banks of the Euphrates to Phoenicia, Syria, and the various mercantile cities of the Mediterranean, must necessarily pass that way, we see at once the good policy of the Jewish monarch in founding a city there. His wisdom in the selection is proved from the fact that it became the greatest mercantile city of the ancient Eastern world, and was the emporium of all the luxuries of India. Nothing is recorded in Scripture about it except that Solomon built it. It was first destroyed by Nebuchadnezzar, according to an ancient historian; and afterwards it submitted to the Persians, the Greeks, and the Romans; but it was only under the last of these that it attained the summit of its glory. In the time of Aurelian, the governor, Odentos, styled himself emperor of Palmyra and the east, and he bid fair to maintain the dignity he had assumed; but sudden death arrested him in his career. His queen, however, followed in his steps; but the emperor Aurelian marched a large army against her, and, after one battle, compelled her to retire within the walls of Palmyra. He laid siege to it, and, after an obstinate resistance, subdued it, consigning the city to the rapacity of his soldiers; it was afterwards however repaired.

"The queen of the Eastern world is now a ruin, and the abode of a small tribe of Arabs, whose wretched hovels are established in the peristyle court of the great temple. The ruins of this city are the most magnificent in the world, if one may so term such an evident token of human frailty. Here are thousands of Corinthian columns, some of which are forty feet high, erecting their heads towards the sky. Before Bruce penetrated into Abyssinia, he visited this place; and he says that when he arrived on the top of one of the hills on the west or northwest, he beheld the most stupendous and astonishing sight. The extensive plain below was covered so thick with magnificent buildings,. that one seemed to touch the other; all of fine proportion, all of agreeable form, and all of white stone; and in the distance the magnificent Temple of the Sun reared its lofty head, to the honour of which the Palmyrenians dedicated their city. For ten miles in circumference there are remains of this ancient city, though the principal ruins may be contracted to three. In this space travellers find the courts and halls of once proud palaces; here a temple with its peristyle half thrown down; and there a noble piazza, half a mile in length and forty feet in breadth, with two rows of marble columns; now we see a triumphal arch, or a violated tomb. Wherever the traveller turns his head, the earth is strewn with chiselled stones half buried, with broken entablatures, with damaged capitals, mutilated friezes, disfigured relics, effaced sculptures, and ruined altars." It may be remarked that more recent travellers have made, by closer observation, some deduction from the grandeur of this description, especially as to the purity of the style of architecture and the finish of the work; but after all allowance is made for the glow of first and general impressions, there can be no doubt that the ruins of Palmyra are something marvelous.

But our chief concern is with the beginning of this magnificent place as Tadmor in the wilderness. If we view this city, erected by Solomon in the desert, as a resting-place for pilgrims, in connection with the city-less desert through which Israel passed in their way to Canaan, we can hardly fail to see in it the sign and emblem of a change of state, such as that not infrequently predicted in the prophets, when "the wilderness and the solitary place shall be glad for them; and the desert shall rejoice, and blossom as the rose. And an highway shall be there, and it shall be called The way of holiness; the unclean shall not pass over it; but it shall be for those: the wayfaring men, though fools, shall not err therein. No lion shall be there, nor any ravenous beast shall go up thereon, it shall not be found there; but the redeemed [of the Lord] shall walk there: and the ransomed of the Lord shall return, and come to Zion with songs and everlasting joy upon their heads: they shall obtain joy and gladness, and sorrow and sighing shall flee away" (Isaiah 35). All this cannot be drawn from the circumstance of Solomon building a city in the desert, but it points in this direction. The Psalmist, speaking of the redeemed of the Lord, whom He redeemed from the hand of the enemy, describes their destitute and tried condition by saying, "They wandered in the wilderness in a solitary way; they found no city to dwell in." Yet the Lord "led them forth by the right way, that they might go to a city of habitation" (Psalms 107). Now the circumstances were changed. The traveller and the pilgrim were now provided with a city in the desert, where they might avoid the ills which the Psalmist laments his forefathers had suffered, when "hungry and thirsty, their soul fainted in them" (ibid.). And so with the Christian. He too has to wander in the wilderness. But when he is in some degree perfected by suffering, and has prospered, and the kingdom is established in him, he can and will build a Tadmor in the desert, that it may serve to refresh those who bring their treasures to enrich and delight his soul. May we not say with the sweet singer of Israel in the same inspired composition,
"O give thanks to the Lord, for He is good: for His mercy endures for ever"?


