
<<<
---
=== 17 - Solomon's Army

1 Kings 10

David was a man of war, and his soldiers formed an army of warriors; and we have in the annals of his reign a long list of his mighty men, some of whom performed prodigies of valour (2 Samuel 23). But Solomon was a man of peace; and although, as we shall see, his reign was not altogether undisturbed by foreign aggression, his army seems to have been intended, and to have served, for the display of his regal magnificence more than for the defence of his kingdom. The "host," of which we read in the time of Solomon, was that which had existed in the time of David. Soon after his accession to the throne he put Benaiah, whom he sent to slay Joab at the altar, in his room over the host (1 Kings 2:35, 44). The appointment of Benaiah to be over the host in the place of Joab, was in accordance with the higher representative character of the kingdom under Solomon. Joab was of the family of Jesse and nephew of David, and was thus near to the throne; but Benaiah was the son of Jehoiada the high priest, and was thus near to the altar; so that he represented truth derived from goodness of that holiest character which was represented by the priesthood. But besides the host which had come to him from his father David, "Solomon gathered together chariots and horsemen: and he had a thousand and four hundred chariots, and twelve thousand horsemen, whom he bestowed in the cities for chariots, and with the king at Jerusalem " (1 Kings 10:26). The number of horses is not here mentioned, but many years before the time to which this relates," Solomon had forty thousand stalls of horses for his chariots," the number of horsemen being then, as at the later period, twelve thousand (1 Kings 4:4). Solomon, therefore, added to his host an army of horsemen with war-chariots, which do not appear to have formed any part of the host of Israel under either Saul or David. This no doubt indicates a great advance of the kingdom in wealth and civilization. But it indicates something more. It symbolizes a higher representative character of the kingdom under Solomon than it sustained under David. Horses and chariots represent understanding and doctrine, and horsemen, those who are intelligent, and guide the understanding. This meaning of the horse and his rider is well exemplified in the Book of Revelation. When the Lamb had prevailed to open the book that was sealed with seven seals, which none in heaven or on earth could open, or even look upon, there came out one after another four horses, each with a rider. These horses represented the understanding of the Holy Word in the successive ages of the Church, and the colour of the horse and the character of the horseman represented what the quality of the understanding of the Word in the several ages of the Church had been. The first horse, which was white, and whose rider had a bow, and who went forth conquering and to conquer, represented the understanding of the Word in the first age of the Church. His whiteness is emblematical of the intellectual purity and freeness from error which characterised the Church of the earliest times, when, in consequence, they were able to conquer, as the apostles and early Christians did, the opposition of the heathen world and everywhere win souls to Christ. The red horse, to whose rider it was given to take peace from the earth, and that they should kill one another, and to whom was given a great sword, describes the beginning of sorrows to the Church itself, when opinions became divided and contentions arose, and love, which is life, began to grow cold, and death as well as unpeace began to invade the sanctuary, where love gave peace and unity gave power. The black horse represents the understanding of the Word in the Church darkened, the light of truth having given place to the darkness of error, in consequence of which the principles of goodness and truth, that support the spiritual life of the soul, are lightly esteemed, a measure of wheat being offered for a penny and three measures of barley for a penny. The pale horse, which came last, expressively symbolizes the understanding of the Word in the Church at the time of its end, when the life of love as well as the light of truth is extinguished. His rider is death, and hell follows with him; and power is given to them over the fourth part of men, to kill with sword, and with hunger, and with death, and with the beasts of the earth.

The same subject is treated of by the same symbolism by the prophet Zechariah; but the four chariots, with their red, black, white, and grisled and bay, or rather strong, horses, that came out from between two mountains of brass (1
Kings 6), represent the doctrine and understanding of the Word, not in a falling but in a rising Church; for here the rebuilding of Jerusalem and the temple, or the restoration of the Church, is spoken of. They are the four spirits of the heavens, which go forth from standing before the Lord of all the earth. The black horses are here followed by the white, and go forth into the north country, and the grisled go forth toward the south, while the strong horses walk to and fro through the earth. The whole prophecy evidently relates to the coming of the Lord, the man whose name is the BRANCH; and the going forth of these chariots and horses figuratively describe the diffusion of the Gospel with its light and power.

But the spiritual meaning of the horse and his rider is perhaps still more obviously brought out in the Revelation 19, where John "saw heaven opened, and beheld a white horse; and He that sat upon him was called Faithful and True, and in righteousness He does judge and make war. His eyes were as a flame of fire, and on His head were many crowns; and He had a name written, that no man knew but He Himself: and He was clothed with a clothing dipped in blood: and His name is called The Word of God." The white horse, the understanding of the Word as it had been in the primitive Christian Church, is here again restored; for the restoration of the Church is treated of by the descent of the New Jerusalem; but it is restored in more than its former power and glory, for He who sits on this white horse is the very Word of God, who has gone forth to judge between right and wrong, and to make war against ignorance, error, and evil. From this stale of intellectual purity in the last Church there is no predicted departure. The clothing of Him who sits upon the white horse -- the outer garment of the letter of the Word -- is, indeed, crimsoned with the blood of its martyred truths; but the white horse of the Word is followed by no others bearing the marks of degeneracy. On the contrary, He who sits upon the white horse is followed by the armies of heaven, riding also upon white horses, and are clothed in fine linen white and clean.

Admitting the spirituality of the Scriptures and the representative character of Solomon, it is almost obvious from the Scriptures themselves what the meaning of the king's numerous horses and chariots with their horsemen must be. If natural war against the enemies of Israel is typical of spiritual war against the enemies of the Church, then, as the weapons of the Church are not carnal but spiritual, the chariots and horses must be intellectual and not physical; and in relation to the Lord, as Solomon's antitype, must mean what the prophet, addressing the Divine Being, calls His horses and His chariots of salvation, upon which He rode, when He went forth for the salvation of His people, even for the salvation of His anointed (Habakkuk 3:8, 13).

Solomon's forty thousand stalls for horses, his fourteen hundred chariots, and his twelve thousand horsemen, are expressive not only of the abundance but of the quality of the spiritual instruments and agents which they represent. Whatever is numbered by thousands is expressive of qualities or things that are grounded in goodness, the number of thousands expressing other elements that enter into and modify them. Forty generally indicates something of temptation and its combats, fourteen, like seven, of what is holy, and twelve of what is true, or the truths of faith in plenitude and power.

There are two particulars connected with Solomon's army of horsemen that might seem to deprive it of any merit or of any good significance. Moses, speaking to the people of the time when they would desire a king, laid it down as a rule for his observance, that he should not multiply horses to himself, neither should he cause the people to return to Egypt to the end that he should multiply horses
(Deuteronomy 17:16). Yet this wisest of their kings multiplied horses, and if he did not send his own people to Egypt to procure them, he had them brought from there; for "Solomon had horses brought out of Egypt... And a chariot came up and went out of Egypt for six hundred shekels of silver, and an horse for an hundred and fifty." That which is wrong in the letter cannot represent that which is absolutely right in the spirit, but it can represent that which is relatively right. There are things which are the result of evil that are not themselves evil. Reasoning comes of evil, and yet in itself it is not evil. Our Lord says,
"Let your communication be, Yea, yea; Nay, nay: for whatever is more than these comes of evil." If men had never fallen from their original state, they would have perceived the truth, and seen the difference between what was true and not true without reasoning. But now that the power of perception is lost, men require to reason in order to discover whether a thing be so or not. Reason is indirect and imperfect perception. It comes of evil, but it is the means of overcoming the evil from which it comes. The law itself comes of evil. The law of love was originally inscribed upon the mind. Its being written on tables of stone was a necessity produced by its having been effaced from the table of the heart; and yet "the law is holy, and the commandment holy, and just, and good"
(Romans 7:12). The injunction that the king was not to multiply horses to himself, nor cause the people to return to Egypt to the end that he should multiply horses, was grounded in a law of order and necessity. Egypt represented science; and the horses of Egypt represented the understanding reasoning from science respecting religion, or seeking to enter through natural science into spiritual truth, which is as impossible as for a camel to go through the eye of a needle. But although one cannot enter through natural science into spiritual truth, it is possible to confirm and illustrate spiritual truth by natural science, when a spiritual state has once been attained. This state was represented by the reign and kingdom of Solomon; therefore it was allowable for him to multiply horses, and to go down to Egypt for horses and for chariots. When the mind is established in the truth of religion, the understanding and the doctrines of science may be made the means of defending as well as of confirming the truth.

So far as the history of Solomon's reign affords the means of judging, his army was never engaged in offensive warfare, but, if employed at all, as there is reason to believe it was, against the enemies of Israel, it was only for the purpose of defence. It is indeed remarkable that there is nothing said of Solomon making any but defensive implements of war. "King Solomon made two hundred targets of beaten gold: and he made three hundred shields of beaten gold;" but we do not read of his making either swords or spears. The higher state of spiritual warfare is purely defensive. So long as the Christian is progressing from truth to goodness, he attacks as well as defends. The true principle of spiritual warfare is defence; and this is the true principle of natural warfare also. But the principle of self-defence sometimes requires offensive operations. True principle, either spiritual or natural, never seeks occasion of war, or enters on a war of aggression. But in the war of the religious life the spiritual and the celestial man, or the man of faith and the man of love, act differently. The warfare of the celestial man is more purely defensive in its character than that of the spiritual man. Love employs the shield more than the sword, faith employs the sword more than the shield. The man of true faith uses the sword of truth, indeed, under the influence of love. The Israelitish warriors anointed their swords and shields with oil, to represent that even the spiritual man must have his sword of truth anointed with the oil of love. But the celestial man fights, so far as his defensive warfare can be called a combat, from love itself. Solomon's targets and shields were made of beaten gold, the emblem of love. The Lord, even when He fought with the whole infernal host, never entered into conflict with the enemies of Himself and His people, except when He was assailed by them. Nor does He in the minds of the faithful. Whatever in their conflicts is more than this is from their own selfhood. The promise to the faithful is, " His truth shall be your shield and buckler" (Psalms 91:4). But His truth is the form, His love is the substance. It is the shield and the buckler of beaten gold.

The Christian life is a warfare as well as a pilgrimage; and in passing through it we have to fight under the banner of Saul and David as well as of Solomon. In all our conflicts the Lord is our Leader, and He has trod the thorny path and fought the good light before us. But He appears to every one according to his state. The same in Himself and in all His operations, He appears to all men according to the nature and measure of their reception of His love and truth. Those who receive more of His truth than of His love see Him as a Man of war; and those who receive more of His love than of His truth, see Him as a Man of peace. Those who fight from truth, apparent and real, are led by Him as Saul or David; those who resist from love are led by Him as Solomon. He leads all who are earnestly pursuing their way to His kingdom of love and wisdom, of righteousness and peace; but He desires to lead them through their necessary conflicts with self, the world, and the flesh, in the spirit and in the state in which He can protect them from evil and enrich them with good, and enable them to sit every man under his vine and under his fig-tree, and none shall make them afraid.


