
<<<
---
=== 11 - Nations out of Canaan Conquered and Made Tributary

2 Samuel 8

The rest which the Lord had given David from all his enemies round about he did not long enjoy. About two years after he had taken Jerusalem we find him engaged in war with several different nations. The first of these are the irrepressible Philistines, whom David subdues, and from whom he takes Metheg-ammah, an important town in Gath, which, from its commanding position, was called the bridle of the mother city. A blow was thus struck at the metropolis of Philistia. Like one of the heads of the Apocalyptic beast, it was wounded to death, but like it also its death-wound was healed; for although subdued, the Philistines were not yet wholly vanquished.

After recording this subjugation of the Philistines, the chapter is occupied in relating the wars which David carried into some of the nations beyond the borders of Canaan, which he not only conquered but made tributary. And this leads us to consider a distinction which the Israelites were commanded to make between the Canaanitish nations and those whose countries bordered upon Canaan, but were separate from it.

The seven nations inhabiting Canaan were to be utterly destroyed, but the nations beyond Canaan, unless they resisted, were only to be subdued and made tributary. In Deuteronomy 20this is clearly stated: "When you come near to a city to fight against it, then proclaim peace to it. And it shall be, if it make you answer of peace, and open to you, then it shall be, that all the people that is found therein shall be tributaries to you, and they shall serve you.... Thus shall you do to all the cities which are very far off from you, which are not of the cities of these nations. But of the cities of these people, which the Lord your God does give you for an inheritance, you shall save alive nothing that breathes."

The nations of Canaan represented evil loves and false persuasions that are essentially opposed to everything good and true, and which can neither be reconciled nor made subservient to right principles. But the nations out of Canaan represented affections and persuasions that are indeed remote from goodness and truth, but are not essentially opposed to them, and can therefore be made tributary to them, and serve them. On this interesting and important subject the Writings throw a clear light, as the following quotation will show. Though the author's remarks refer directly to another subject, they are quite applicable to this.

" Evils with man are of various kinds; there are evils with which good cannot be mixed, and there are evils with which good can be mixed; the case is the same with falsities; and unless it was so, it would be impossible for any man to be regenerated. The evils and falsities with which goods and truths cannot be mixed, are such as are contrary to love to God and to love towards our neighbour. For example; if any one loves himself in preference to others, and under the influence of that love studies to excel others in moral and civil life, in scientifics and doctrinals, and to be exalted to dignities and likewise to opulence above others, and yet acknowledges and adores God, performs from his heart duties towards his neighbour, and does from conscience what is just and equitable, the evil of that self-love is such as to admit good and truth to be mixed with it; for it is, the evil which is proper to man, and is hereditarily born with him; and suddenly to take it away from him would be to extinguish the fire of his first life. But if any one love himself in preference to others, and under the influence of that love despises others in comparison with himself, hates those who do not honour, and, as it were, adore him, and therefore feels the delight of hatred in revenge and cruelty, the evil of his love is such as not to admit of good and truth being mixed with it, for they are contraries. Again: if any one believe himself to be pure from sins, and cleansed like a person cleansed of filth by washing in water, when he has once done the work of repentance, and discharged the duties which he has imposed upon himself by repentance, or after confession has been told by his confessor that he is so cleansed, or after he has been a partaker of the Holy Supper; in case such a one lives a new life, in the affection of what is good and true, this false principle is such as to admit of good being mixed with it; but in case he lives a worldly and carnal life, as heretofore, the false is then such as not to admit of good being mixed with it. So again; he who believes that man is saved by virtue of believing what is good, and not by virtue of willing what is good, and nevertheless wills what is good, and in consequence thereof does what is good, this false principle is such as to admit of good and truth being adjoined to it
; but not so in case he does not will and thence do what is good. Again, if any one be ignorant that man rises again after death, and in consequence thereof does not believe in the resurrection, or if he be acquainted with the resurrection, and still doubts and almost denies it, and yet lives in truth and good, this false principle also is such as to be accepting of good and truth being mixed with it; but if such a person lives in what is false and evil, the false in this case is accepting of no such mixture, because of contrariety, and the false destroys the true, and the evil the good. Further, pretence and cunning, which have good for their end, whether it be the good of the neighbour, or of a man's country, or of the Church, are prudence, and the evils thereto admixed may be mixed with good from and for the sake of the end proposed; but pretence and cunning, which have evil for their end, are not prudence, but are artifice and deceit, with which good can in no wise be conjoined, for deceit, which has evil for its end, induces an infernal principle in all things in man, and places evil in the midst, and rejects good to the circumference, which order is essentially infernal. The case is similar in numberless other instances. That there are evils and falsities, to which goods and truths can be adjoined, may appear from the fact, that there are so many diverse dogmas and doctrinals, several of which are altogether heretical, and yet in every one of them salvation is attainable; and also from this, that among the Gentiles who are out of the Church, there is likewise a Church of the Lord, and that although they are in false persuasions, still such as live a life of charity are saved, which could not possibly be the case, unless there were evils which can be mixed with goods, and falsities which can be mixed with truths. Evils which are mixed with goods, and falsities with truths, are wonderfully arranged in order by the Lord, for they are not conjoined, still less are they united, but they are adjoined and applied, and this in such a sort, that goods with truths are in the midst, as in a centre, whilst such evils and falsities are by gradations as the circuits or circumferences, in consequence of which the latter are illustrated by the former, and are variegated like black and white by the light proceeding from the midst or centre. This is heavenly order."

The nations whom David subdued at this time were the Moabites, the Syrians, and the Edomites. David garrisoned their cities, and they became his servants. Two of them are mentioned as having brought gifts, but the other was no doubt also made tributary. Besides these gifts, which were compulsory, the king of Hamath sent him vessels of gold and silver and brass. These did David "dedicate to the Lord, with the silver and gold that he had dedicated of all nations which he subdued; of Syria, and of Moab, and of the children of Ammon, and of the Philistines, and of Amalek, and of the spoil of Hadadezer, son of Rehob, king of Zobah." The reduction of these nations to a state of vassalage, is a type of the subjection of the natural man to the authority of the spiritual; and the dedication of their gifts or their spoil to the Lord, is representative of the sanctification of the possessions of the natural man, by devoting to spiritual uses and eternal ends what had hitherto been employed for natural uses and temporal ends. As the silver and gold, of which the Israelites spoiled the Egyptians, came to be dedicated to the Lord in the construction and adorning of the tabernacle, the treasures which David obtained from the nations helped to adorn and enrich the temple. But as both the tabernacle and the temple represented, not only the Lord's Humanity, but His Church, and not the general Church only, but the Church as built up and established in the individual mind, we learn from this turning of the spoils and gifts of the nations from profane to sacred uses, the duty of turning all our natural acquisitions, whether they be intellectual or material, into means for promoting the glory of God. This does not imply that they are to be devoted to what are commonly called religious purposes, but that they are to be brought under the government of religious principles, and so employed as to promote the glory of God, by ministering to the best interests of ourselves, and of our neighbour. That which is made to serve the love and truth of God in us, is, in the best sense, dedicated to the Lord, for it is applied to uses that build us up into temples of His presence. The gifts themselves are various; but they are spoken of, in the present case, as consisting of gold, silver, and brass; and these, as sent by the king of Hamath, were in the form of vessels. We have had occasion, more than once, to speak of these receptacles as symbols of what we have called scientifics, that is to say, facts, as distinguished from the conclusions we draw from them, or the wisdom they teach us. Every one recognises the difference between knowledge and wisdom. But we have a better instance in the difference between science and religion. Nor do we need to confine ourselves in this case to natural science. A man may be eminent in religious science and yet have no religion. In regard to natural science, we know that it can be a means of confirming men either in the belief or in the denial of a creative Intelligence. By the believer "the invisible things of Him from the creation of the world are clearly seen, being understood by the things that are made, even His eternal power and Godhead" (Romans 1:20). To the unbeliever, invisible things are assumed to have no existence, and the visible are considered to account for their own existence, and to show that they are able to take care of themselves. It is essential that men should not be forced to believe, therefore God does not reveal himself to sense, but to reason. It is a less evil to disbelieve from choice than it would be to believe from compulsion. Natural science, therefore, leaves men free. But it does not leave them blameless. That is to say, scientific denial is deeper and more deadly than simple negation. Science creates neither belief nor unbelief, but it confirms the mind more deeply in either. The more deeply the natural man penetrates into the secrets of nature the nearer he believes he is to the origin of life. What he calls the origin of life the spiritual man calls its beginning, the origin of which is in Him who is Life itself, from whom all things are and live. Scientifics, in fact, are vessels, which men may replenish either from the true vine or from the vine of Sodom and the clusters of Gomorrah, and out of which they may drink either to the true God or to idols -- the molten images of their self-love or the graven images of their self-intelligence.

But, on this subject, we must let the light of Revelation in upon ourselves. There, if we have entered on the regenerate life, we shall see what is here described representatively in the history of the Israelites. We shall see the spiritual mind and the natural mind in their true character. In the natural mind we shall find evils that are in their very nature opposed to spiritual truth and goodness; while there are others, some of which may be called infirmities, which can be brought under subjection to spiritual principles, and be made to serve some useful spiritual purpose, the acquirements of the natural man contributing to the perfection of the spiritual. Let us see, then, what these different nations represent.

Moab, the first of these nations that David subdued, was descended from Lot's son by his eldest daughter. In treating of the Ammonites, the descendants of the son of Lot's younger daughter, who were the first to feel Saul's kingly power, we have seen that Moab and Ammon represented the profanation of goodness and truth. Yet they did not represent that degree of profanation which is unpardonable, because unremovable. A Moabite or an Ammonite was not absolutely excluded from the congregation of Israel, but was not allowed to enter until the tenth generation (Deuteronomy 23:3), which implies that the profanation they represented did not necessarily destroy all remains of goodness and truth, but might leave a rudiment, from which a new and spiritual state could be commenced. David's treatment of the Moabites on this occasion teaches something of the same kind. They were subdued and severely treated, but not exterminated. "He smote Moab, and measured them with a line, casting them down to the ground; even with two lines measured he to put to death, and with one full line to keep alive." Dreadful work! And yet apologists tell us, and no doubt tell us truly, that the treatment of the Moabites, as compared with that of conquered nations in those times, was humane. By the law of nations, and even by the law of Moses, the whole of the Moabites had forfeited their lives by their opposition or resistance; and David showed his clemency by saving some. It reminds us of the Calvinistic vindication of the character of God in the decree of election. The whole race by their sins had incurred the sentence of eternal damnation, and God showed His mercy by saving a few. The truth is, the Jews were a barbarous race, and enjoyed the delight of all barbarous nations in shedding blood. They were not chosen because they were better than other nations, but because they were better adapted to perform a use which concerned the welfare of the human race. Their great use in the Divine economy was to receive and preserve the oracles of God, and to keep alive, however imperfectly, the faith and worship of the one true God. Their barbarism made them fit instruments for rooting out hopelessly corrupt nations, and their facile piety made them the means of keeping the embers of religion from altogether dying out. They served therefore to preserve the spiritual connection between heaven and earth, on which the salvation and even the preservation of the human race depends; and they could perform acts which represented higher things than they either thought or intended.

Regarding David's treatment of the Moabites, there is some difficulty in understanding the nature of the operation by which the fate of the vanquished was decided. German critics make the text to mean, that David subdued Moab, and then made the whole people lie down on the ground, and measured them with a measuring-line, destining two measures to death, and one measure to life. In other words, instead of exterminating the whole brood, he decimated them, as it were, by a kind of lot, and left it to apparent chance whether any given Moabites were to be slain, or spared. Josephus, however (Jewish Wars 7:5), has not so taken it; possibly he was willing to spare David's humanity. Just as the Chronicles omit this incident. On the other hand J. D. Michaelis, in his treatise on the Mosaic Law, declares that David was much more merciful than the Mosaic Law if he only killed two-thirds of them.

Whatever the precise nature of the operation may have been, the general conclusion seems to be, that two-thirds were in this way devoted to death, and one-third kept alive. Whatever obscurity there may be respecting the application of the measuring-line and its results, the terms are sufficiently precise to enable us to see the spiritual lesson intended to be conveyed by the circumstances. To measure is to ascertain or estimate the quality of a thing. A mystic man with a measuring-line measured the temple (Ezekiel 40), and also Jerusalem (Zechariah 2:2), and John was commanded to measure the temple of God and them that worship therein (Revelation 11:1); in all which cases, to measure evidently means to discover, or rather to show, the quality or state of the Church. The measuring-line applied to the spiritual Moabites is not, therefore, a measure merely to decide their fate, but a measure to ascertain or express their character. With two lines David measured to put to death, and with one full line, literally, with the fullness of the line, to keep alive. All the Moabites were cast down upon the ground, to represent, that those who live profanely are all equally natural and earthly; but they were measured with different lines, to show that they are not all equally guilty; that even with them "there is a sin to death, and there is a sin not to death" (1 John 5:16, 17). Those who were measured with two lines typified those who live profanely from the will with the full consent of the understanding; while those who were measured with one line represented those who live profanely from one of these two active powers of the mind, but not from both. This subject may be illustrated by one of the laws of Moses. One of the rules of evidence laid clown in the Mosaic code was this: "At the mouth of two witnesses, or three witnesses, shall he that is worthy of death be put to death; but at the mouth of one witness he shall not be put to death"
(Deuteronomy 17:6). This law, spiritually interpreted, teaches this important, and at the same time hopeful truth. When the will and the understanding, or when the will, the understanding, and the outward life, bear united witness against us; at the mouth of these two or three witnesses, we bring upon ourselves the sentence of eternal death. But when one of these only witnesses against us, we, of the Divine mercy, are kept alive. Some sin from natural depravity, hardly knowing what sin is and what are its consequences; some sin from education and habit, as those who have been brought up to crime, as skilled workmen in a not dishonourable but rather dangerous trade. It is not to be supposed that either of these is in a state of innocence. But they come within this saving condition: Natural depravity of the will may not have deeply corrupted the understanding, and misdirection of the understanding may not have deeply corrupted the will. Indeed, we can hardly speak of will and understanding with respect to such persons; for will is nothing without understanding, and understanding is nothing without will. Such persons form a kind of fictitious will and understanding in a lower region of the mind, leaving the true faculties to a great extent undeveloped, and the capacity of being reformed and regenerated, though seriously injured, yet not un-destroyed. This is not, of course, the case with all even of the criminal class; but it is no doubt true of some. Indeed, the Moabite, in the better aspect of his character, represents one possessed of some natural goodness, which makes him the easy dupe of the designing, to whom he has not the courage to say no.

There are, however, others besides such characters, to whom, as spiritual Moabites, these lines may be applied. The law which required at least two witnesses to put to death, was delivered with immediate reference to the man or the woman who "has gone and served other gods, and worshiped them, either the sun, or moon, or any of the host of heaven." Scripture does not say that Moab worshiped the heavenly bodies, unless the Moabitish god Chemosh, who is said to have been worshiped under the form of a black star, may be considered to belong to the host of heaven; but the Mosaic law included all kinds of idolatry. And the worship of God was an exalted virtue and idolatry a deep crime, because the idea of God enters into all our worship, which comprehensively means all our religion. In profane worship there may be the concurrence of the will and the understanding; or one may be involved without the other. A gross idolater may be sincerely devout. While his understanding is corrupted, his heart may be sound. He will be measured by one full line to be kept alive. When the heart is idolatrous as well as the understanding, then will the false worshiper be measured by two lines to be put to death. But there is an inward as well as an outward idolatry. Yet even here the line of life may be found to apply. Only when the concurrent testimony of the two inward witnesses is against the idolater, will he be measured with two lines to be put to death. A hopeful doctrine this when we apply it to others; a solemn one when we apply it to ourselves.

After Moab, David "smote Hadadezer, the son of Rehob, king of Zobah, as he went to recover his border at the river Euphrates." From him David took many thousand chariots, and horsemen, and footmen. And when the Syrians of Damascus came to succour Hadadezer, David slew of the Syrians twenty-two thousand. Zobah was in Syria, so that here was one and the principal of the Syrian princes supporting another. Syria, in its best days, when the second ancient or Hebrew Church was there, signified the knowledge of good, as Syria of rivers signified the knowledge of truth. In the time of Abraham, when he was called out of Ur of the Chaldees, which was in Syria, it had sunk into idolatry, and had therefore corrupted the truth which it once possessed. Syria is thus the intellectual principle, answering to Moab, which has relation to the will. The intellectual character of the Syrians is indicated by their chariots and horsemen, which are symbols of doctrine and intelligence, false it may be.

When David had subdued and made tributary the Syrians of Zobah and Damascus, a third Syrian king, Toi, sent his son to bless David, because he had fought against Hadadezer, and smitten him, because that Hadadezer had wars with Toi. Wars take place in the rational mind itself, which Syria, under one view, signifies, as when one intellectual nation conflicts with another. We have seen that one evil may serve to hold another in check, but cannot remove it. Neither the rational nor the natural mind has the power to reform itself. This can only be clone by the spiritual mind. So David ended the wars between the two Syrian kings; and, while he forced one into submission, led the other to send a friendly message with rich gifts.

One other nation David subdued. "He put garrisons in Edom; throughout all Edom put he garrisons, and all they of Edom became his servants." The Edomites, the descendants of Esau, had, like the other nations, degenerated. Therefore, from representing the good of the natural mind, they had come to represent the natural mind under the influence of self-love, which rejects all truth. In putting garrisons throughout all Edom, and making all Edom become his servants, David represented the power and operation of the spiritual mind in placing under the control of spiritual truth all the natural affections that powerfully influence the mind in favour of self as a ruling principle. For those garrisons of the king's forces in the conquered nations around Canaan symbolize the presence of the spiritual mind in the natural by means of truths, which exercise a controlling power over those thoughts and feelings which are inimical to, but not destructive of, the life of love and truth in the soul. Yet this is not a permanent state. The thoughts and feelings which at first are restrained must finally be brought into a friendly relation with the ruling principle of the mind, or be removed. And so we find in the prophets predictions of the ultimate renewal or destruction of the nations generally that David conquered. Here, at least, we have, in the conquests of David, a representative history of a Divine work that is constantly going on in the minds of those who are being regenerated, and a promise of the time when all nations shall serve the Lord, and bring their gifts and offerings to Him as the King of kings and Lord of lords.


