
<<<
---
=== 24 - David's Song of Thanksgiving

2 Samuel 22

After the life of tribulation and conflict which David had passed through, with its perils and deliverances, it is only what might be expected from the piety of his character that he should pour out his soul to God in a song of thanksgiving. We have had occasion to notice some of these beautiful compositions, in which he expresses his trust in the Lord in times of trial, and His gratitude to Him for deliverance from trouble. This song is more general in its character than any of the others; and is one of the noblest and sweetest of the numerous effusions of his pious spirit, influenced as it was by the Spirit of the Lord.

This song bears some resemblance to that which Moses sang after the deliverance from Egypt; and we may preface the explanation by what our great commentator has said on the subject of sacred songs in treating of that which was sung by that other representative man on the borders of the Red Sea. "To sing a song signifies to glorify; and thus a song signifies glorification. In the ancient Church, and afterwards in the Jewish, songs were prophetic, and treated of the Lord, especially of His coming into the world, and destroying the diabolical crew, and delivering the faithful from their assaults. And as the prophetics of songs contained such things in the internal sense, they hence signified the glorification of the Lord, that is, the celebration of Him from gladness of heart; for gladness of heart is especially expressed by a song, since in a song gladness breaks forth as it were spontaneously into sound. Hence it is that Jehovah, that is, the Lord, in song is called a Hero, a Man of War, the God of Armies, the Conqueror, Strength, a Defence, a Shield, Salvation. And the diabolical crew which was destroyed is called the enemy which was smitten, swallowed up, overwhelmed, cast into hell. Those who knew nothing of the internal sense formerly believed that such worldly things were meant as worldly enemies, combats, victories, overthrows, and overwhelmings, of which the songs in the external sense treat. But those who knew that those proprieties involved heavenly and Divine things, and that the heavenly and Divine were represented in the worldly, knew that these prophetics treated of the condemnation of the unbelieving, and the salvation of the believing, by the Lord when He should come into the world. And those who knew this to be the case, and reflected on it, and were influenced by it, were affected with internal gladness; but the former only with external gladness. The angels also who were attendant on man were at the same time, on such occasions, in the glorification of the Lord. Hence those who sang and those who heard the songs experienced heavenly gladness from the holy and blessed principles which flowed in from heaven, in which gladness they seemed to themselves as if taken up into heaven. Such an effect had the songs of the Church among the ancients. Such an effect might they have also at this day; for the spiritual angels are especially affected by songs that relate to the Lord, to His kingdom, and to the Church. That the songs of the Church had such an effect was not only in consequence of their giving activity to gladness of heart, and its breaking forth from the interior even to the extreme fibres of the body, and exciting them with a glad and at the same time a holy tremor, but also because the glorification of the Lord in the heavens is effected by numerous choirs singing in concert. Hence also angelic speech is harmonious, falling into numbers. Hence the glorification of the Lord among the ancients who belonged to the Church was performed by songs, and psalms, and musical instruments of various kinds; for the ancients who belonged to the Church derived surpassing joy from the recollection of the Lord's coming, and of the salvation of the human race by Him."

With a few slight differences this song is the same as the eighteenth Psalm. It might have been sufficient to refer the reader to Clowes and Hiller on the Psalms, where the explanatory passages scattered throughout the Writings are brought together. But as David's spirit was refreshed after his many and severe trials by raising his thoughts and affections to God, so may the reader who has followed with us the course of David's history, and has seen so much of war and bloodshed, feel his spirit tranquillized by joining David in his pious aspirations.

In his fragmentary notes known as "Adversaria," our author, after leaving twenty chapters of the Second Book of Samuel unnoticed, enters into a minute explanation of David's song; minute, we mean, not in explaining every word, but in taking every verse, and saying something in the way of explanation upon it. The explanation itself is, to use the artist's phrase, rather a study than a finished work. Yet as the studies of the great masters are highly prized, as enabling us to trace the development of their ideas, this study of our great Master Expositor may be interesting and not a little instructive. We therefore offer a translation of this sacred song. In some instances the explanation is supplemented by remarks, or by extracts from the author's published works, which are distinguished from the words of the "Adversaria "by a dash. Some few of the renderings may be considered partly as conjectural readings, the original being elliptical even to obscurity, and one is omitted as being founded on an accidental misreading of, we suppose, Schmidius' Latin version of the Hebrew.

(1.) The song of David when he was delivered out of the hand of his enemies.

That David uttered this word inspired by the Spirit of God-Messiah is clear: thus the Spirit speaks, not David, as also appears from 2 Sam 23:2. And because the Spirit speaks, it is not David who is understood, but in the more internal sense the faithful, and in the inmost sense those who trust and love God-Messiah, and in the supreme sense God-Messiah Himself. Such is the intention of the Holy Spirit wherever He speaks through David. Of this anyone may be assured, particularly from vers. 21-27, where he treats of justice, cleanness of hands, integrity, holiness; although he says elsewhere that in himself no one is pure, but altogether profane and unjust.

" The Lord is my rock, and my fortress, and my deliverer; the God of my rock; in Him will I trust: He is my shield, and the horn of my salvation, my high tower, and my refuge, my Saviour; You save me from violence" (vers. 2, 3). These are names which all signify God-Messiah, for He is everywhere called a mountain, and stone, and rock, and bulwark -- for He alone fights  -- as well as holy, and the horn of salvation. -- The Lord is a rock, as the omnipotent; a fortress, a high tower, a shield, as a protector; a horn of salvation, a Saviour, as He who saves from the violence of Satan and sin.

" I will call on the Lord, who is worthy to be praised: so shall I be saved from mine enemies "(ver. 4). Spiritual enemies are understood; the Spirit means no other.

" When the waves of death compassed me, the floods of ungodly men made me afraid; the sorrows of hell compassed me about; the snares of death prevented me" (vers. 5, 6). The horde of the devil, who is the enemy, is likened to the waves of death and the floods of Belial (ungodly men), because they are spirits, who in like manner rush in in troops. Hence come temptations, for they rush in in an inexpressible manner, by persuading, reviling; hence they are called the sorrows of hell and the snares of death; continually they persuade him whom they assault, craftily, most cunningly, nay, they are suffered in temptations to affect man, but they are snares or cords of death.

" In my distress I called upon the Lord, and cried to my God: and He did hear my voice out of His temple, and my cry did enter into His ears" (ver. 7). Spiritual distress is here described. But in God-Messiah is the only refuge; out of His temple, that is, out of heaven, through the angels, comes a supplication (or cry), which, the more intense it is, is the more compared to a cry, for a cry is an effect, as is known, in accordance with the degree of intensity of the spirit.

" Then the earth shook and trembled; the foundations of heaven moved and shook, because He was angry "(ver. 8). Here is described vengeance upon the enemies, which is not inflicted by God-Messiah, although it is ascribed to Him, but is given to others, who rush in. Anger is described, that it will descend in order to the ultimate. Thus all that is above is moved, as is the case in man whilst the mind is in anger; whatever is below, too, and the ultimates in the body, are moved; there they act together. Here it is said, the earth trembled, the foundations of the heavens shook and were moved. Evil spirits are in the lowest parts, namely, in the place where the body is, and the natural mind respectively to the higher mind; wherefore they tremble.

" There went up a smoke out of His nostrils, and fire out of His mouth devoured: coals were kindled by it" (ver. 9). Anger is likened to smoke, and fire, thus to live coals, as in mount Sinai and elsewhere.  -- It is not meant that smoke and devouring fire come out from the Lord, because He has no anger; but it is so said, because the Lord appears such to those who are in the falsity of evil. Smoke denotes falsity, and the flame of it anger; for the falsity of evil in the intellect is as smoke, and anger is the flame of kindled smoke.

" He bowed the heavens also, and came down; and darkness was under His feet"
(ver. 10). In like manner darkness, for it is as a very dark cloud, because it is then night to the evil. -- Jehovah bowing the heavens and coming clown signifies the visitation which precedes the last judgement; darkness under His feet signifies falsities of evil in lower things; by this is effected an exploration of the quality of spirits, and also a separation of the good from the evil. The Lord also bowed the heavens and came down at the time of the Incarnation when the heavens co-operated with Him, and darkness was under His feet, when He assumed our fallen humanity. Darkness also is the literal sense of the Word.

"And He rode upon a cherub, and did fly: and He was seen upon the wings of the wind" (ver. 11). Upon a cherub; because cherubs are those who descend, and who execute commands. On the wings of the wind is the same, for angels are called wings of the wind. -- The Lord's riding upon a cherub signifies His Divine Providence, and His flying signifies His Omnipresence in the spiritual world, and His being seen upon the wings of the wind signifies His Omnipresence in the natural world.

"And He made darkness pavilions round about Him, dark waters, and thick clouds of the skies "(ver. 12). Darkness is as pavilions round about Him. Also binding of waters, and clouds, which amounts to the same, but with some difference of meaning. -- This treats of the coming and presence of the Lord in the Word. Darkness and clouds are the literal sense. Still Divine truth such as it is in heaven is within the literal sense, therefore darkness is called a pavilion round about Him.

"Through the brightness before Him were coals of fire kindled" (ver. 13). There is brightness, which is the truth; thence coals are kindled; for [the spirits] chastise by means of the truth. -- The darkness mentioned in the previous verse meaning the literal sense of the Word, the brightness here is the spiritual sense. In relation to the righteous, the darkness of the letter comes before the brightness of the spirit; and they know the Lord after the flesh before they know Him according to the spirit. The affections are kindled by the fire of the Lord's love.

" The Lord thundered from heaven, and the Most High uttered His voice" (ver. 14). He thundered out of heaven. Thunders are thus the effects of anger; they follow in the clouds; thence [He] is called the Thunderer, from terror. -- In respect to the Lord Himself His thunder is His Divine love and His lightning is His Divine truth, which affect the good and the evil in opposite ways, as explained in the next verse.

" And He sent out arrows, and scattered them; lightning, and discomfited them"
(ver. 15). These are spiritual weapons, namely, truths and goodnesses; they are weapons of torment because they wounded the innocent one. Lightning is that light which thus comes, by which they are confounded. -- Thunders are here expressed by thundering out of heaven and by giving forth a voice, and lightnings by arrows; and both these signify Divine truths, and the flash their light; which truths, as they vivify and enlighten the good, terrify and blind the evil, which is understood by sending forth arrows and scattering them, and lightning and discomfiting them, for the wicked cannot endure Divine truths or any light from heaven, wherefore at their presence they flee away.

" And the channels of the sea appeared, the foundations of the world were discovered, at the rebuking of the Lord, at the blast of the breath of His nostrils "(ver. 16). That these will strike to the lowest hell, thus to the ultimate, is here described, the channels of the sea and the foundations of the earth being the lowest hell; for of hell there are degrees, on account of the rebuking, namely, the voice, or what that here signifies, the lightning, the thunder, of the truth. From the blast of the breath of His nostrils, the blast of the breath of the nostrils is life, which penetrates thus with that glow to the lowest parts.

" He sent from above, He took me; He drew me out of many waters" (ver. 17). Here is described, that man, nay, spirits are drawn forth out of hell, and this by God-Messiah, who draws man out from the damnation of many sins, that is, from many waters; He took him out of the deep, because from hell; man is rescued from the enemy, or the devil, who is too strong for him, thus from them that hate him, for the impious horde regard with deadly hatred the sons of God-Messiah, who are here represented by David.

" They prevented me in the day of my calamity; but the Lord was my stay" (ver. 19). They prevented me in the day of my calamity, namely, they desired to destroy me, but God-Messiah was my stay, as above, vers. 2, 3. -- The day of calamity is a weak state as to the faith of truth; the Lord being a stay signifies ability in such case.

" He brought me forth also into a large place: He delivered me, because He delighted in me "(ver. 20). He brought me forth into a large [broad] place, into a heavenly plain, from the pit, from hell, because He delighted in me, that is, God-Messiah delighted in His sons. Here those things which are God-Messiah's are applied to those things in heaven and earth which are in God-Messiah. These
[expressions] can in no wise be applicable to David, according to his own confession and various acts of his life, for he was exceedingly unrighteous. Because now those things which are in God-Messiah are applied or imputed, these words treat concerning Him alone, namely, that Jehovah delights in His Son alone, as was said in the mount, when He was glorified: these in like manner; for God-Messiah alone is Righteousness and clean.

" For I have kept the ways of the Lord, and have not wickedly departed from my God" (ver. 22). He alone kept the ways of Jehovah, that is, the Law in its complex; for He fulfilled all the law, internal and external, as well as all that the law involves, namely, what is involved by the sacrifices, and worship, etc. etc.: thus He alone became Righteousness, and yet He prayed for those that hated Him, which David was never wont to do.

" For all His judgements were before me: and as for His statutes, I did not depart from them" (ver. 23). This is now confirmed by these words. -- Judgements are Divine truths, according to which men ought to live. Statutes are the external things of the Word, such as rituals; and those things which are representative and significative of the internal sense are the laws of worship.

" I was also upright before Him, and have kept myself from mine iniquity" (ver. 24). In like manner, [as in the previous verse.] Mine iniquity is man's iniquity, but it reads, "he took care that he should not act wickedly," as the other translator renders it. In Him was no iniquity.

" Therefore the Lord has recompensed me according to my righteousness; according to my cleanness in His eyesight" (ver. 25). These words in like manner as before, but with a difference. -- By fulfilling the whole law in all its degrees the Lord became Righteousness itself; and He alone had merit in His righteousness, because He fulfilled the law by His own power, whereas all the power which men have of doing good is derived from the Lord alone, and to Him all the merit of human righteousness is due.

"With the merciful You will show Thyself merciful, and with the upright man You will show Thyself upright" (ver. 26). That imputation of righteousness or holiness is understood, is manifest from these words, namely, with the holy You are holy, with the perfect You are perfect. Only God-Messiah is holy and perfect.

" With the pure You will show Thyself pure; and with the forward You will show Thyself unsavoury "(ver. 27). With the pure, pure, in like manner. That righteousness may be imputed there must be a conflict, wherefore it is said, With the perverse You contend. --  This and the previous verse teach a most important truth. The Lord appears to every one according to his state. Mercy itself and purity itself, the perfect One appears to imperfect men, and especially to evil spirits, as He is reflected in their own states of heart and mind. For however men may think of the Lord doctrinally, they necessarily think of Him practically from their own states.

" And the afflicted people You will save: but Yours eyes are upon the haughty, that You may bring them down " (ver. 28). Thus, You save the afflicted, namely, in the conflicts. But the haughty You cast down; the lowly only He raises up: thus the lofty one is opposed to the afflicted, or the lowly, who lies in the dust.

" For You are my lamp, O Lord: and the Lord will lighten my darkness "(ver. 29). Thus He enlightens the understanding, for the understanding is never enlightened but after a conflict; thus is dispersed the darkness, or the falsities. But the darkness clings to the mind because cupidities and guilt do so; these continually induce falsities, which God dispels.

" For by You I have run through a troop: by my God have I leaped over a wall"
(ver. 30). Thus he shall conquer, which is to run through a troop, and he will go over a wall, which they attack, as above, for within or without amounts to the same: for the impious think they stand in their fortified city.

" As for God, His way is perfect; the word of the Lord is tried: He is a buckler to all them that trust in Him "(ver. 31). After man has been justified, this now follows, for God-Messiah then defends man and spirit, wherefore it is here now said, "as for God," that is, God-Messiah. He is called the way, integrity, the tried word of Jehovah, which clearly signifies God-Messiah, who is the Word of Jehovah, and tried, as is well known. A buckler to all who have faith, that is, who trust in Him.

" For who is God, save the Lord? and who is a rock, save our God?" (ver. 32.)
That Jehovah alone is God: thus God-Messiah, in whom is the fullness of the Godhead; for through Him, that is, by Him, all things are made, who alone is a rock, as above.

" God is my strength and power: and He makes my way perfect" (ver. 33). In like manner a refuge, and power, as above. He will make man's way perfect, will lead man in the way of truth, which is the perfect way, which He will prepare.

" He makes my feet like hinds' feet: and sets me upon my high places "(ver. 34). Swiftness is here treated of, that He will speedily prepare the way. Feet are the way in which they walk. Upon my high places, namely, upon the sphere in me, which is above the rational mind, which is the high place in man, when it gives him understanding of the true and the good.

"He teaches my hands to war; so that a bow of steel [brass] is broken by mine arms "(ver. 35). He teaches to war, how he shall smite his enemies, or overcome them. He submits the brazen bow to my arms, that is, gives me to understand the natural truths which are the brazen bow. Arms are the powers of understanding; these are the strength of a man, and are called arms.

" You have also given me the shield of Your salvation: and Your gentleness has made me great" (ver. 36). The shield of salvation is saving faith. Your afflicting makes me great, namely, affliction makes those who have faith great -- thus to afflict is also said of the Messiah, that He makes man great.

" You have enlarged my steps under me; so that my feet [ankles] did not slip
"(ver. 37). -- To enlarge, literally, to make broad, the steps is to bring the life, meant by the feet, into conformity with the truth, which is meant by breadth. The ankles, like the feet, correspond to the natural and sensual part of the mind; hence the ankles not slipping signifies that the natural mind is supported.

" I have pursued mine enemies, and destroyed them: and turned not again until I had consumed them. And I have consumed them, and wounded them, that they could not arise: yea, they are fallen under my feet" (vers. 38, 39). These things follow when man has acquired faith; then he pursues his enemies until he has consumed them. -- The Lord pursued His enemies when, in His conflicts with the powers of darkness, He continued to resist and fight against them until they were overcome. The powers of darkness are in the continual effort to rise up and acquire dominion over heaven, yea, over the Lord Himself; but the Lord so completely subdued them under His power that His foes were made His footstool. In relation to man the Lord's foes are the thoughts and affections of the natural mind, which are in the continual endeavour to rise against the thoughts and affections of the spiritual mind, until the Lord has brought them into subordination to the power of His Divine truth and goodness.

" For You have girded me with strength to battle: them that rose up against me have You subdued under me. You have also given me the necks of mine enemies, that I might destroy them that hate me" (vers. 40, 41). The like, for strength here is faith, with which he is girded, and with which he lays low, i.e. subdues his spiritual enemies.

" They looked, but there was none to save; even to the Lord, but He answered them not. Then did I beat them as small as the dust of the earth, I did stamp them as the mire of the street, and did spread them abroad" (vers. 42, 43). How his enemies are treated of, how they are subdued, namely, that none shall save them, that they shall be as the dust, which is trodden as the mire, etc. -- It may seem singular that, the enemies of the Messiah or of man should cry to the Lord for help; but we find in the Gospel evil spirits both acknowledging the Lord's power and praying Him to grant them what they knew He only was able to give them. When about to be cast out of one possessed, the spirits prayed Jesus that He would not send them forth into the deep.

" You also have delivered me from the strivings of my people, You have kept me to be head of the heathen: a people which I knew not shall serve me "(ver. 44). Because it is faith that effects all this, here those things are set forth in which there is no faith, but there is doubt. Thus He shall deliver me from the strivings of my people, from the doubts which bring forth strivings and heresies. "You shall keep me to be head of the heathen." Thus it is faith which he will keep; in the inner, the inmost, and the supreme sense the head of the heathen is God-Messiah. The people whom he knew not, is all that which confirms faith, which are things intellectual, etc., these shall serve and consent.

" Strangers shall submit themselves to me: as soon as they hear, they shall be obedient to me" (ver. 45). These words in like manner, for they are called sons of the stranger which shall fawn upon me, for they consent and obey; for those things are servile, in comparison with faith.

" Strangers shall fade away, and they shall be afraid out of their close places"
(ver. 46). Here are other sons of the stranger, namely those who possess truths without applying them; they guard their treasures without enjoying them; these shall quake, for from them they shall see spiritual celestial truths: this now is "out of their close places," where they guard those things.

"The Lord lives; and blessed be my rock; and exalted be the God of the rock of my salvation "(ver. 47). Now again he calls upon God-Messiah, as in the beginning so in the end, because of the first and the last, as is usual in Divine songs, just as in our Lord's Prayer. "The Lord lives" is a solemn expression, implying that Jehovah-God alone is Life. God-Messiah alone is a Rock, as above. And God is the rock of salvation, i.e. of faith. He is the rock of salvation.

" It is God that avenges me, and that brings down the people under me "(ver. 48). He alone it is who defends man from injuries, and punishes the evil, [whom He prostrates] for He alone it is who does this; faith indeed [effects this] but He alone gives faith.

" And that brings me forth from mine enemies: You also have lifted me up on high above them that rose up against me: You have delivered me from the violent man"
(ver. 49). The things which were stated in the beginning are here taken up again, as is customary in songs. At length the deliverance is set forth. The enemies are, as above, the devil's horde. The man of violence is the devil.

" Therefore I will give thanks to You, O Lord, among the heathen, and I will sing praises to Your name" (ver. 50). Hence now confession or thanksgiving. That it shall be among the heathen, signifies various things, which see elsewhere; for Your name shall be sung among the heathen, those who confess.

" He is the tower of salvation for His king: and shows mercy to His anointed, to David, and to his seed for ever more" (ver. 51). Who magnifies the salvation of His King; namely, Jehovah the Father, who praises His King's, i.e., His Son's, righteousness and merits. And shows mercy to His anointed, to David, i.e. to God-Messiah, for when He suffered He cried out concerning the mercy of Jehovah the Father, that He had forsaken Him. The Son Himself is the Anointed of Jehovah; and is King David. And His seed is all who have faith in Him. Furthermore, by king, anointed, and David are understood those who are called the sons of the King, thus kings. Seed is applied to them, when God-Messiah is understood by David. But seed is applied to faith and to those things which belong to faith, when the King's sons [are meant] by David; but when [seed] is applied proximately to David, it is those who will reign after him. These [will endure] for an age, i.e. for a time, as is manifest from the signification of an age wherever it occurs. But in the inner sense [and] the inmost, an age signifies eternity, as also elsewhere. That the kingdom will be everlasting, of David, see above, 2 Sam. 7:13, 16, where those words also are explained.


