
<<<
---
=== 7 - David is Anointed King over Israel, and goes up against Jerusalem

2 Samuel 5:1-5.

ISH-BOSHETH reigned two years; but it was not until five years after his death that David was anointed king over Israel. What government prevailed among the eleven tribes between the death of Saul's son and the commencement of David's reign, we do not learn. It would probably resemble that which existed during the time of the judges, when there was no king in Israel, and every man did that which was right in his own eyes. The tribes had no doubt come to feel the necessity of a more stringent rule. They came to David of their own accord. It is indeed remarkable that David seems to have taken no measures to bring the eleven tribes under his dominion. It was no doubt right that they should come and offer him their voluntary homage. The Lord came to establish a kingdom, but He never employed force to bring men into it. He requires the free reciprocation of His love; for only in freedom can men be ruled to their advantage.

When the tribes of Israel came to David they said, "Behold, we are your bone and your flesh. Also in time past, when Saul was king over us, you were he that led out and brought in Israel: and the Lord said to you, You shall feed My people Israel, and you shall be a captain over Israel. So all the elders of Israel came to the king to Hebron; and king David made a league with them in Hebron before the Lord: and they anointed David king over Israel." This is an accurate description of the Lord Jesus. He is our bone and our flesh, in being clothed with humanity, which, though glorified in Him, is not less akin to us. Nay, it is nearer to us than it was when yet unglorified. For that humanity in which all the fullness of the Godhead dwells, is life itself, and enters as a living principle into all that is human in us: nay, it is the origin of all that is truly human in human minds; for no one is truly man but he in whom is an image of the Divine man. It is no less accurate a description of David's Lord that He feeds His people, and is a captain over them. He leads them to the green pastures and beside the still waters, and defends them against, and even prepares a table before them in the presence of, their enemies.

The league which the Lord makes with His people is the agreement which rests upon conditions -- conditions of support and protection on His part, and of fidelity and obedience on theirs. This league is made before Jehovah, when the Church acknowledges the Divinity of the Lord in His Humanity. And the Church anoints the Lord King over Israel, when the love she has received from the Lord is returned to Him again, and there is reciprocal conjunction between the Lord and His people.

When all Israel had thus voluntarily placed themselves under the rule of David, and formed one united kingdom under one king, a new, capital was to be provided by the king more suitable to his enlarged dominions.

Jerusalem was inhabited by the Jebusites, one of the seven nations of Canaan that were devoted to the sword. In the division of the land it fell to the lot of Benjamin (Joshua 18:28). The king of Jerusalem was one of the five kings who fought against Joshua on that memorable day when the sun stood still (Joshua 10:5). So powerful were the Jebusites, the inhabitants of Jerusalem, aided no doubt by the strength of the place, that neither the children of Judah nor the children of Benjamin could drive them out, but the Jebusites dwelt with them "to this day" (Joshua 15:63; Judges 1:21). The reduction of the stronghold of the Jebusites was reserved for David, nor did he attempt it until backed by the whole force of Israel. And when the king went up against Jerusalem, the Jebusites, as we shall see, felt so perfectly secure, that they mocked at the very idea of his seriously attempting to force his way into their impregnable fortress. In all this there is of course a higher meaning. It is, in one of its applications, part of a large and comprehensive subject, and one of the mysteries of the kingdom that could only have been known by what may be called a revelation.

The whole history of the Israelites, from the time of Moses to the reign of Solomon, is, in the internal sense, a history of the Lord's work of redemption, in regard to its effects in the spiritual world. There, we know, judgement is effected, and a new heaven is formed, preparatory to the establishment of a new Church upon earth. The plagues of Egypt, by which the Israelites were separated from the Egyptians, describe the process and progress of judgement, by which the good were severed from the evil in the world of spirits. The Red Sea signifies that hell into which the wicked, who were represented by the Egyptians, were cast, and through which the righteous, represented by the Israelites, passed in safety. The forty years' journey through the wilderness describes the temptations through which the redeemed passed before they could enter heaven. And this reveals a most important fact relating to those who had lived in the world from the fall of the celestial Church to the time of the Lord's Advent. It is the common belief of Christians, that there was no salvation for the fallen race of man but through Jesus Christ; and that His atonement included past sins as well as future offences. But the important question is, How was this effected? We know the common opinion. Christ, it is held, suffered for the sins of all men from the time of the Fall; and those "who died in faith, not having received the promises, but having seen them afar off," were saved, "being justified freely by His grace through the redemption that is in Christ Jesus: whom God has set forth to be a propitiation through faith in His blood, to declare His righteousness for the remission of sins that are past" (Romans 3:24, 25). We share in the common belief in the efficacy of our Lord's redemption. We believe, however, that sins can only be remitted by being removed. And it is a vital question, how the sins committed before the Lord's coming could be removed by what the Lord did and suffered in the flesh.

The work of salvation consists of two parts, reformation and regeneration. All who are reformed in the world are ultimately saved; for those who in the natural world have shunned evils as sins can be imbued with good in the spiritual world. Before the Lord's coming men could be reformed in the world, but they could not be regenerated. Regeneration cannot be effected without temptation. And until the Lord had conquered hell and glorified His humanity, no one could undergo temptation; therefore none were admitted into a trial in which none could have stood. Yet without regeneration there is no salvation, therefore no heaven. How then was the salvation of those who died in faith provided for? All who had passed through the first stage of the new life, and were thus capable of passing through the second, were reserved in the intermediate state, or world of spirits, until the Lord's coming. And when the Lord had overcome hell and glorified His humanity, then could the faithful in the world of spirits pass through the corresponding process, and be regenerated as He had been glorified. He being perfected through suffering could succour them that were tempted (Hebrews 3:18). The temptations which the faithful underwent in the middle state, were represented by the trials which the children of Israel endured in the middle region between Egypt and Canaan, the waste and howling wilderness. And by this means they realized the promise, and had remission of sins that were past. They had been carried in the womb; now they were born -- born from above although with trouble and anguish. For the Church, as the mother of the faithful, had been in that state described by the prophet: "The children are come to the birth, and there is not strength to bring forth" (Isaiah 37:3). The faithful, new-born, were prepared to enter into heaven, as the Israelites, after their weary pilgrimage, were to enter into the Promised Land.

Regarding Canaan as the type of heaven, the eternal home of the faithful, there is one important circumstance connected with it, which seems to make it anything but an image of that place where the wicked cease from troubling and the weary are at rest. It is inhabited by wicked nations, which have to be driven out before Israel can find it a quiet habitation. But this otherwise inexplicable circumstance is explained in the Writings, and in such a way as to make the whole history of Israel a consistent and continuous history of the great work of human redemption. "Before the Lord's coming into the world, that region of heaven to which the spiritual were afterwards raised, was occupied by evil spirits and genii; for before the Lord's coming, a great part of them roamed at large, and infested the good, especially the spiritual, who were in the lower earth; but after the Lord's coming they were all thrust down into their hells, and that region was delivered, and given for an inheritance to those of the spiritual Church." These were like the imaginary heavens spoken of in connection with the Lord's Second Advent, and which were abolished by the judgement which then took place.

When we know that the evil spirits and genii who occupied that region of heaven which was afterwards given as an eternal inheritance to the spiritual, were represented by the nations of Canaan, we can see the reason why none of them were completely conquered by Joshua, by the Judges, or even by Saul, but that their final and complete overthrow or subjugation should be reserved for David, who especially represented the Lord as Divine truth, and who, as such, conquered death and hell, and went and preached to the spirits in prison, delivering men on earth and the faithful in Hades from the captivity in which they had for ages been held by the powers of darkness.

David is now leading Israel, as the Lord led the faithful, to take the kingdom of heaven by force. But the account of this we reserve for another chapter.


