= Last Judgment
By Hugo Lj. Odhner
include::../../template-attributes.adoc[]

////
The outline (if it is) needs help
////


A compilation of the teachings concerning the last judgment in the Spiritual World in the year 1757

By Hugo Lj. Odhner Bryn Athyn, Pennsylvania

== THE LAST JUDGMENT

=== I. THE WORLD OF SPIRITS, AND THE SCENE OF THE JUDGMENT

Many teachings in the Writings aim to show that the Last Judgment was not a destruction of the material world and did not involve the ceasing of the procreation of the human race.

The present part will be devoted to the subject of the world in which the Judgment actually took place, the World of Spirits.

1.{empty} A spiritual judgment can only take place in a spiritual world. Natural judgments occur here on earth in manifold ways; mistakes, errors and evils result in natural punishments and losses.

The common idea that sins are a definite set of acts, and that intentions and the spirit behind the act play a very small part in the sin, is reflected in much literature of the present day: The hero of a story, for example, is calmly intending a crime or revenge, but before he actually perpetrates his act, the villain falls to the bullet of some other foe, and the hero is whitewashed and wins the love of the heroine. His intentions, the character of spirit, the novelist forgets to deplore. Well, the act is the wrong, but the spirit alone commits the sin, and this whether circumstances prevent the act or not.

When the Writings speak of Judgment it is the judging of the spirit that they refer to: the body is mere obedience.

A final judgment upon a man can be made only in the spiritual world; where his spirit is in a spiritual body, the body of his own choice and impress, the body of his mind, his purpose and intention.

2.{empty} What does this judgment consist in? Everyone is, without being aware of it, bound to same society in heaven or in hell. The judgment consists essentially in his going to the society of his ruling love and ruling delight, to work out his life in the way of his choice.

(If man was absolutely sincere in good, and so single-minded that there was in him nothing contrary to his ruling love--no other ties, no other, lesser affections, no distracting thoughts; then he would go to that heavenly society at once on death.)

On the other hand, if he was so brazen in his evil, that no other things withheld him from it and no external bonds or self-restraints held him, then he would and will go to join his society or his like in hell practically immediately after resurrection.

But relatively very few are in either of these states. Having lived in the body and in the world, their natural and external minds are fashioned to some extent, usually to a great extent, by their heredity on the one hand, and their environment, education and associates, on the other.

Heredity: Inborn natural affections, both good and evil, are ingrained in the sensual degree which is the last to regenerate. Natural good with the evil is apt to modify the expression of their intention, and especially restrain them from certain cruelties or certain particular forms of evil. Like, good animals, they will love certain kinds of people or virtues, instinctively.

Environment: Prudential restraints are created by discipline and experience: adjustment to environment is advantageous. (Mass opinion is unconsciously accepted; identity of self with Society; the tendency to go in droves; protection in numbers etc., etc. Thou shalt not follow a multitude to do evil.)

3.{empty} The World of Spirits is a state of gradual weaning from the states of the natural mind. There are societies of natural affections in the world of spirits. (Examples: Societies from cities, and from nations; societies of interior friendship, of exterior friendship, of dissenters; societies from religious sects, from racial groups, etc.)

(Normal progress or the judgment: the three states of the World of Spirits: (a) State of exteriors; (b) State of interiors; (c) State of instruction (or of insertion into hell).)

Abnormal Progress. This is necessary when the World of Spirits does not function. Normally diseases are thrown off by a healthy body, but if the body, for some reason, does not react against the disease, it accumulates into a fever, or a crisis. The equilibrium of the body, with its organs and functions, is then disturbed and a judgment comes.
(Judgment in the Greek is krisis, separation, ordering, from krino, to separate; hence the Latin crimen, which means accusation or crime).

4.{empty} (How the world of spirits is affected by the decline of the church on earth.) The Church is the seminary of heaven. (The World of Spirits may be likened to the alimentary canal in man; for Heaven is a like a Grand Man, and novitiate spirits are like the food. The stomach normally absorbs the food and puts it to use, in some organ of the body, or some cell tissue. Any disturbance in the process of digestion will affect the state of the stomach and indeed all the viscera and organs of man; there might be a poisoning of the system, with various results.

This would happen especially if an accumulation of indigestible food came to infest the stomach.

It is the same with the world of spirits when the church is at an end in the world, and more evil than good spirits accumulate in the world of spirits.

Read LJ 33, 34, 38, as to the reason for a last judgment.

A last judgment is nothing else than the end of the church with one nation and its beginning with another. (AC 3353, ill. 1850)

Last judgments, or general judgments, have occurred whenever a church or dispensation has come into a state of consummation.

There have been three most universal judgments, the first signified in the Word by the Flood of Noah (end of Most Ancient Church), the second occurring at the Lords first advent (and of the Ancient Church) and the third in 1757 (end of First Christian Church). (LJ 46)

There have been four general judgments, when the Church of Israel is considered as a church distinct from the Ancient Church. (See Coronis, especially n. 36.) (AC 2118)

There have been five judgments, when the Hebrew Church is distinguished as a Second Ancient Church and the Israelitish is considered as the Third Ancient Church. (See AC 1850) The judgment on the First Ancient Church is then represented in the dispersion after the confusion of tongues at Babel, or in the destruction of Pharaohs army in the Red Sea. The end of the Hebrew Church would then coincide with the call of Abram or the conquest of Canaan.

5.{empty} A Witness to the Judgment. To the New Church has been given not only the general principles of the last Judgment,--the laws of judgment, and the truths of charity on which it is based; but the Seer Emanuel Swedenborg actually witnessed every step of the judgment which Spiritual World. Through his eyes we also can see it, can follow each stage of it. He even mentions the fate of this or that historical personage, names what happened to a number of his personal friends, and tells how the face of the world of spirits was changed and reformed.

At once we must mention that these changes seem, especially at first, very complex and confused. Perhaps that is the reason why no history has ever been written of the last Judgment. But there must be some profound reason why the revelator spent so much time noting every event
(however trivial it may seem on paper) and describing so minutely the fantastic appearances connected with the destruction of the old order there. (The Spiritual Diary has nearly a volume full of details.)

Several reasons for this may be noted:

(1) This day by day description confirms the actuality of Swedenborgs visions.

(2) It is essential to have an imaginative basis for our thought about this event and about the Spiritual World.

(3) Illustrations are thus provided of the working of spiritual laws.

(4) History can be interpreted in the light of what is there said about the fate of persons, institutions, nations and churches.

(5) The bald description of such spiritual events serves to prevent the acceptance of the Writings by any that are not ready for it; it is a protection against profanation of the doctrine itself.

In our philosophisings about the spiritual world as a living realm of non-spatial substance, we are apt to forget to meditate on the reality of its life. It is of course a form of spiritual timidity to accept the Spiritual World as a fact-yet be unwilling to study its structure or its appearance. One of Swedenborgs friends wanted to accept Swedenborgs claim to inspiration and to accept his doctrine, yet expressed his regret that Swedenborg had ever published the Memorabilia! There was a reluctance to picture the life of the Spiritual World for fear of materializing it! Even Swedenborg himself went through a state, where he experienced a shock at finding the Spiritual World so substantially complete, so complicated, so confusingly like the natural world. So many perplexing appearances and apparent contradictions! Space, yet no space; nature there, yet no nature!

The memorabilia and other recorded experience of Swedenborg in the Spiritual World, constitute, in a manner, a letter, a literal sense, for the doctrine; as a historical, symbolic covering and containant for the precious spiritual laws of life which are the essential Word itself to the New Church.

We shall therefore attempt to present certain generalizations about the changing appearances of the World of Spirits, and study the reasons why sometimes fantastic and surprising events occur there.

6.{empty} Place in the Spiritual World: The Spiritual World is the kingdom of the Divine Proceeding, or of Divine Truth. All things there are as they appear: there is no appearance without its definite significance or actuality; and this significance is sensed in the appearance, by angels and intelligent spirits.

What fixes place in the World of Spirits, therefore, is the Divine Truth; or ... the reception of the Divine Truth (D 5363-64). Those who are without certainty, are seen to wander about (D 5373) and have no fixed place.

The source of all permanency is the Lord. His Divine love never alters, neither do the gifts of His love. There are certain constants--such as the atmospheres from the spiritual sun; they are His ever-living hands, and are a permanent and underlying basis of substance in the Spiritual World. Angelic societies are also permanent and do not alter except by a continuous growth,. The reason is that ruling loves once confirmed, are constant; heaven and hell are therefore constant. (TCR 78)

(But the World of Spirits is changing; it contains elements in flux, opposites, and mixed states, like the natural minds of men.)

7.{empty} The World of Spirits is only the Intermediate between heaven and hell. It is also the source and beginning of every heaven or hell. These grow out of the World of Spirits.

In the Most Ancient Church there was probably a time when there was only a heaven in the spiritual world. With the development of evil, this heaven deteriorated, and at the time or the s. c. Flood there was a division between the good and the evil, and thus a formation of a heaven and a hell. Afterwards-between these two--a World of Spirits was formed. At length the good from the Ancient Church formed societies there, yet had no power to purify these from evil of the subtler sort. Hence it was not until the Lords time that a complete judgment was made, and a spiritual heaven and a middle hell were organized permanently. Early Christians formed societies in the World of Spirits, but these also became defiled by admixture of evil spirits. Not until the time of Swedenborg could there be a permanent separation of the good and the evil and the formation of a natural heaven and an opposite hell.

Most ancient heaven

/ Heaven of Ancient Church

/ / New Christian heaven

/ / /

- - - W O R L D O F S P I R I T S - - - - - - -

/ / /

/ / New hells of Christian era

/ Hells of Ancient churches

Antediluvian hells

8.{empty} The elevation of the good to form a heaven is invariably presented in the world of spirits under a spatial appearance, as a lifting up or as a new world above the world of spirits.

For all states are presented in apparently geographical relations in the world of spirits and even in the heavens and hells. The World of Spirits therefore has the coherent features of an entire world!

9.{empty} Geographical Appearance in the World of Spirits:

a) The world of spirits appears a vast place (TCR 475): is compared to a forum (AR 791:2); is compared to a city (LJ 27).

b) The world of spirits is seen as a valley (HH 429, cp. 58j) in the low parts of the Spiritual World (HH 583), immediately below the heavens (AR 552). The Heavens then appear as mountains rising over the valley of the world of spirits and Hell like cavernous entrances in the earth below. This appearance is induced when a connection is required between the heavens and the world of spirits, or the hells. But, from different states and points of view the world of spirits appears wider and more inclusive, or different in appearance and relation to the heavens. The law in this respect is that all things are visible to each other in the spiritual world but only so much appears as the Lord permits: that is, as is pertinent to the state or use of an angel or spirit. The same law governs the mind: only that is present to the thought which is pertinent or belongs to the active affection or state.

c) The world of spirits also appears as a complete world: (TCR 475). in this case the heavens are conceived of as above and the hells as below.
(5 Mem. 10; CL 461; HH 422). The heavens then are not ordinarily apparent (HH 583) except as clouds or sky. The hells--a continuous hell--is hallowed out under the heavens and the world of spirits (HH
583), a hell being beneath every society of heaven.

d) The latter conception shows the heavens as three expenses, appearing over the mountains of the world of spirits, and then like atmospheric expenses (AC 702:2; AR 260, 876, etc.). The lower expanses appear wider in extension than the higher, and the lowest heaven as if under the earth (AR 260). The ancient heavens form the higher expanses, the new heavens the lowest (HD 4). The hells also form expanses below, so that there are in all six expanses. (AE 1133:6)

e) The next point to notice is that the world of spirits is also an expanse between the heavens and the hells. (LJ post. 126e, AE 1133:6, SD 5240e, 5244). That world and all the superior expanses, are complete worlds, and are not plane, but concentric globes, one within the other.

This appearance is not merely a memory survival from earth, but is the representation of a spiritual coherence of states, a certain mutual relation which can only thus be described. (The appearance of the heavens as higher and wider circuits or spheres about an inner globe is reminiscent of the Ptolemaic idea of the earth as the center of the universe, and of the old Hellenistic conception of the seven spheres-each ruled by some God or Damon. There was a spiritual truth underlying that old idea; it came from the Ancient Church, from a corresponding spiritual reality. The concept of Hades as an underworld is paralleled in the fact that below the surface of the World of Spirits some souls are preserved in the lower earths, which are dispersed at a last judgment.)

From the point of view which shows our relations to the Lord, the universe centers in Him as the Divine Sun. This is the physical truth of each solar system-its center is the sun. But from the view-point of the relations of spiritual beings to each other, the human race, on earth, and thus the world of spirits form as it were a stationary plane upon which the heavens seem to be resting. This is the appearance in the spiritual world.

f) The world of spirits, being a globe, has its zones-relatively frigid and tropic and temperate (TCR 185; SD 5144-7, 4383). It also has its quarters, E. W. N. and S., but oriented from the East, (which is the fixed point). The earth there does not revolve: the Sun is really omnipresent, and those to when it appears at all, see it at an angle of 45 degrees. The quarters are fixed with reference to each angels body. The East is in the front of the angel, the North at his left, the South at the right and the West behind him.

g) There is a physical or geographical parallel. The continents there correspond somewhat to those on earth, but are not in the same physical proportions. The uninhabited parts do not seem to occupy any area, to judge from Swedenborgs diagram of Africa. (SD 4946) It is the human not the physical relation that is shown: racial and cultural similarities make for spiritual proximity.

The cities of this world are duplicated in the other life. Yet some, like Hamburg, did not exist there, lacking a distinct character. Others, like certain Swedish cities, are grouped in a cluster with no distance between them. National characteristics govern all to a certain extent. Yet nations which are dominated by a common church or a religion such as the Roman Catholic, Mohammedan, or Jewish, remain separate in the other life according to religions, not according to distinct national boundaries. These therefore are called nations.

h) Arrangement of the Nations in the World of Spirits. The center of the world of spirits is where the greatest light is. In the beginning of the Christian Church, the Greek Churches were the most enlightened, but later the Roman Church may have taken the lead, although learning existed only in the monasteries. At the reformation a re-orientation began, because the Word was then read in Northern Europe. The first country where the Gospel was widely preached was in England. (Note the work of Wychliffe and his Lollards and, later, of the British and Foreign Bible Society.) Hence at the time just before the last Judgment, the nations in the world of spirits had the following arrangements:

QUARTERS AND TRACTS IN THE WORLD OF SPIRITS

E A S T

Pagans

Mohammedans

Papists

N O R T H

Pagans

Mohammedans

Papists

W E S T

Papists

Mohammedans

Pagans

S O U T H

Papists

Mohammedans

Pagans

Arrangement of Reformed Nations in central space:

E - English

D - Danes

G - Germans

H - Dutch

S Swedes

10.{empty} Representations of spiritual relationships. The geographical arrangements of the nations and the ordering of the heaven into expanses, each like a globe, are necessary for a perfect representation of the mutual contacts which all bear to each other in the spiritual world. For nothing else would fulfill this requirement of an actual relation between all spirits. (AR 260, 876; AE 702:2; CL 42)

The added teaching is given that the hells, in the view of heaven and thus actually (in spiritual state and idea), are in a reversed relation to the angels: their position is upside down, and thus they are on lands which are under the world of spirits, but they walk head down and feet on their subterranean land as if they lived in the antipodes, and face West. (AC 2641; HH 151; AE 1143:4; SD 3428; AC 5116:3, 9128e, 5013:2, 5746e, 6468:3)

Each single heaven is divided into similar expenses (AR 876), and the World of Spirits is no exception. For the expanses are the spiritual representations of a state that is utterly superior or something as yet unattainable-discretely higher: something which does not enter ones ordinary life, yet is acknowledged as a governing factor.

This may be seen reflected in a larger community on earth which is normally divided into group-life, based on race, heredity, and social standing. Certain uses are leading uses, and tend to impress and govern the rest. Similarity of uses and interests makes for special bonds, and naturally such as are in common uses flock together. This is normal and desirable. But greater education, greater wealth, greater power or at least ambition cause certain people to form a class, and we speak of class distinctions (in an invidious sense) as arising from a gradual segregation of those who have these more exalted uses or who at least can intelligently follow and support such uses sympathetically, from those whose uses are lowly and must follow the leadership of others somewhat blindly. There must be two elements to cause this separation. One is a relegation of responsibility to the governing classes, which means that the simpler among the people will admire and trust leaders of thought and captains of industry, and this largely because they regard them as having succeeded where they themselves have failed. It is usually a matter of hero-worship, however grudgingly this be admitted. The leaders will thus have a great power, and will, on the whole, truly people, like priest. An instructed people means a wise clergy. A people will thus readily make an upper or governing class of those whom they look up to, and follow, and perhaps imitate. A people will reward and exalt and give privileges to those who perform the uses which they need at the time.

In the other world, spiritual class distinctions lead to the formation of certain social layers and strata within the world of spirits, which also becomes distinguished as three expanses.

11.{empty} Swedenborg does not give a clear description of the various expanses and quarters of the World of Spirits until he had seen their relationships after much experience. Gradually he finds proper names for the various levels and degrees. At first, in the early Diary, he makes only general observations. (Cf. SD 636-637) His acquaintance had to grow, first with individual spirits, then with societies. The vastness and apparent confusion of that world impressed him, and also the imminence of a judgment.

In the last days of 1756 the last, judgment commenced. Many preparatory judgments had gone on before. (Cf. SD 1316, 2122) But now the connections of states in the spiritual world were being made clear.

The judgment may have been precipitated by the completion of the serial treatments of the Doctrine of Charity and Faith, which closes with a statement of the doctrine concerning the Lord, in the last volume of the Arcana Coelestia (nos. 10815-10831). After the last judgment had occurred, Swedenborg was able to describe the social connections of the World of Spirits with greater preciseness. (Then, not before, he tells of the arrangement which was made among the nations of Christendom, and begins to tell of the more definite geography of the World of Spirits.)

12.{empty} Descriptions of the Last Judgment of 1757 in the Writings.

The main treatments on the last judgment are to be found in the work The Last Judgment (publ. 1758) in entries in the Spiritual Diary, from n. 4925 to ca. N. 6022, the works on the Last Judgment (posthumous, written c. 1760), Continuation concerning the Last Judgment (1763), and incidentally in The Apocalypse Explained (1759) and The Apocalypse Revealed (1766). See also Argument concerning the Judgment (Diarii p. VII Appendix).

(The Diary contains a running account of the last judgment, beginning about n. 4925. For dates, note especially nos. 5239, 5336 and 5762. But the events were happening so fast that Swedenborg did not have time to write down everything that he observed. Hence later entries give further details of what happened in the earlier stages of the judgment.)

Similarly, Swedenborgs brief account in The Last Judgment and Babylon Destroyed, published in 1758, mainly stresses the judgment on the Catholic communities, and it was not until 1763 that a description of the judgment on the Protestant spirits was published, as A Continuation of the Last Judgment.

The manuscripts known as The Last Judgment (Posthumous) is a part of codex 12" in the library of the Royal Academy of Sciences at Stockholm. It was used as a rough draft of material to be used in the published work-A Continuation of the Last Judgment. The MS was-according to Hyde-partly written after SD 5947 (compare with LJ post. 122), perhaps early in 1762.

== THE APOCALYPSE

== PART ONE: Preparation for the Judgment

Introduction (i. 1-9)

=== I. The Son of Man and the letters to the Seven Churches (i-iii)

=== II. The Throne in heaven, and the Opening of the Seven Seals of the Book (iv-viii. l)

The four horsemen. The souls under the altar.

The dread of the judgment. The sealing of the servants of God (144,000)

=== III. The Seven Trumpets sound. (Viii. 2-xi. 19)

Woes on the earth. John eats the little book. The temple measured.

The two witnesses are killed end rise again. The temple seen in heaven.

PART TWO: A prophecy of the assaults of the devil and his agents on the Church. Their final destruction. The Coming of the Lord. The universal judgment. The descent of New Jerusalem.

=== IV. Star-crowned Woman (xii) The Dragon in heaven.

The male Child born and caught up to God. The Woman flees to wilderness.

The Dragon flees to wilderness. The Dragon, cast on earth, persecutes the Woman.

=== V. Two Beasts. (xiii) The beast from the sea overcomes the saints.

The beast from the earth, 666.

=== VI. The Lamb on Mt. Sion and the 144,000 redeemed (xiv).

The Angel with the Everlasting Gospel. Doom foretold.

=== VII. The Seven last Plagues (xv, xvi)

The victors on the sea of glass. The temple opened in heaven. The angels

pour out the vials of wrath. The temple filled with the smoke of glory.

The seven plagues poured out. The evil gather at Armageddon.

=== VIII. The Judgment on Babylon (xvii, xviii). The scarlet woman on the seven-

headed beast of blasphemy. Her mystery explained. The city destroyed,

her fall bemoaned.

=== XI. The Rider on the White Horse (xix). Glorification for the coming marriage supper of the Lamb. The heavens open.

The white horse with the secret name (The Word of God). The rider conquers the beast and false prophet.

The Dragon sealed in a pit for 1000 years, the saints enthroned, in the first resurrection. After 1000 years the Satan is also cast into the lake of fire.

=== X. The Great White Throne (xx. 11-15). Opening of the books of life.

The universal judgment of all the dead.

=== XI. The New Jerusalem (xxi-xxii. 5). A new heaven and a new earth are seen.

Holy City descends out of heaven. All things are made new.

The golden city measured and described. The river of life and the trees of life. Evil absent, darkness gone.

=== XII. The Imminence of the Lords Coming (xxii. 6-21). The angel speaks in the name of Jesus, promising the coming of the Lord.

The Church, as the Bride, responds. Benediction.

== THE APOCALYPSE

(Series of the Spiritual Sense)

=== I. The Lord as to the Divine Truth of revealed Doctrine.

His reception in all possible states.

=== II. Ordering for Judgment. The Word as to its internal sense seen by the Lord alone.

Exploration of states for judgment. A new heaven and a new church to be formed.

=== III. Exploration of the Reformed churches. Preparation of the spiritual heavens and their influx with the Reformed.

Preliminary judgments. Influx effects no repentance.

The doctrine (two essentials) rejected. Future state of New Church announced from heaven.

=== IV. The New Church in the spiritual world. Faith alone assails the Church.

The Church among a few.

The Heavenly Doctrine (male child) received and protected.

=== V. The doctrine of faith alone with the laity and the clergy within Christendom (Reformed).

=== VI. Heaven from the Reformed: the Heavenly Doctrine in heaven.

Exhortations against faith alone and love of dominion.

=== VII. The new heavens from Reformed in confession and preparation to inflow spirits to disclose evils and falsities. Consequent vastations and judgments.

=== VIII. Judgment on Babylonish tract in World of Spirits. Judgment on those in love of dominion through spiritual things-as in Roman Catholicism.

=== IX. Second Advent of the Lord. The future conjunction of the Lord in His Divine Human with the Church.

The Lord makes His advent as the WORD in its spiritual sense.

The final judgment of those of the Reformed churches and on the dogma of Faith alone.

Formation of the new heavens from the redeemed.

=== X. Universal judgment on all states in the world of spirits, including those of gentiles, etc.

=== XI. The New Church and the new heaven. The New Church as to Doctrine and Life. The Doctrine makes all things new. Genuine truths out of literal sense are the foundations of the Heavenly Doctrine. The conjunction of the New Church with the Lord who alone is worshiped. The quality of the New Church.

=== XII. Conjunction of the Lord and the Church.

The Apocalypse to be revealed in its time. The Lord to make His second advent. The things revealed are to be kept. The Church is thus conjoined with the Lord.

== GENERAL ORDER OF THE LAST JUDGMENT OF 1757

=== I.

a. Ordering of heavens and preparation Internal Sense of the Word of world of sprits. Disclosed through the Arcana Coelestia.

b. Explorations and preparatory judgments.

c. Visitations on Former Heavens: Dragon begins to assault. Eastern Papists re-ordered.

=== II.

a. Judgment on Babylonish tracts. Extraction of Doctrine from Completed Jan. 6, 1757 The spiritual sense as Revealed in Arcana Coelestia.

b. Judgment on Mohammedan circuit.

c. Judgment on Gentiles.

d. Judgment on the Reformed nations:
Commenced about Jan. 7, 1757. Nearly Completed about the middle of April, 1757, although the judgments were continuing throughout the year (?).

=== III.

a. Release of those in the Lower Earth, Formal organization of the began especially towards the end of Doctrine of the New Church, April, 1757. and its reception among spirits and men.

b. Their elevation into the New Heavens. First phase lasted into the month of May. Formation of new heavens and new hells.

c. Strengthening of New Jerusalem in the Comp. CLJ 11, 12. World of spirits.

d. Beginning of New Church on earth: reception of the Heavenly Doctrine.

e. Sending out of the Gospel of the Second Advent in the Spiritual World, June 19, 1770.

f. Gradual establishment of the New church on earth, in proportion to its increase in the world of spirits.

DIAGRAM OF THE BABYLONISH TRACT

The main feature of the district occupied by the Papists in the Spiritual World before the Last Judgment, as described in Last Judgment, n. 58.

The convention in the sides of the North Watch (B) Central tract of the Reformed or the Mount of Assembly Nations (A)

Area of various religions, including some of the Reformed (H) Subterranean great city Babylon (EDF) in mountains
(C)

Great city of blind faith (G)

Papal city and under-city (J)

Underground city of the ancients (I) The black sea in the West (L)

Seven Mountains (D)

Characteristics of the Quarters:
East: Those who had greatest delight in ruling and were in something of natural lumen.

South: Those who had more powerful abilities and were more confirmed in their religion.

West: Underground in anterior part looking towards the North, were the men of the Dark Ages. Posteriorly towards the West, the most wicked of the Babylonians, who forced the vulgar to blind obedience. These were informal profession but in interior denial of the Lord.

North: Those in less powerful abilities, less confirmed and in blind faith, not as numerous as in the South.

=== II. THE LAST JUDGMENT UPON BABYLONIA.

1.{empty} Babylonia before the Last Judgment.

In the Arcana Coelestia, published in 1756, Swedenborg tells of those who are meant by Babylonia, namely those who aim by the things of religion to raise themselves above others and arrogate to themselves the power of the Lord, setting themselves up in the spiritual world on mountains, and proclaiming somebody from their own rank as a god. While they are engaged in this profane worship, the mountain opens into a cleft, and they are swallowed up into hell. (AC 10412)

Those of the Papal religion appeared before the last Judgment in a region stretching around the middle or the spiritual world where the Reformed were. For is the center are those who are in the light of truth from the Word. Such light is propagated from the center to the circumferences. (LJ 58)

For the general features of the Babylonish tract, see Diagram. Most of the papists dwelt, in the South and in the West. In the South dwelt those who were talented, and many of nobility and wealth; but for fear of robbers they lived under the earth. Near the Reformed a great city extended almost from East to West, a city full of temples and monasteries, where ecclesiastics hid their precious things in subterranean Labyrinths. Jesuits there consorted with the wealthy. And a council met in a place called Rome in that quarter towards the East, consulting how to keep the people in blind obedience. (LJ 58, cp. 56)

In the North were those less able and less confirmed in their religion. Most were in a great city stretching from the angle of the East to the West and somewhat into the West. At its outer side near the East were some from the Reformed and many from various religions. (LJ 58)

In the East were those in the delight of ruling, who were also in something of natural light. They appeared on mountains, but only in the quarter which faced North. On top of a mountain in the angle of East and North, an insane spirit was placed when they claimed to be the God of heaven and by secret arts inspired to give out their commands. This mountain is referred to in Isa. 41:13. Some appeared there as building a tower that would reach heaven (cp. Gen. 11:1-10); but this only in phantasy. (LJ 58)

In the West, in front, dwelt those from the dark ages, mostly underground, one posterity beneath another. The tract in front, towards the North was excavated and filled with monasteries. (See also page 18)
Beyond that tract, to the West, were many mountains (Rev. 17:9) where the most wicked were. (See HH 580) There are in a profane love of ruling. (LJ 58)

The reason why these spirits were tolerated until the last judgment are noted in LJ 59, 70.

The first of the main preparatory judgments on Babylonian spirits from the Catholic religion is noted in a long account in SD 4913-18, 4953-4988. The region which is here treated of seems to be in the Eastern Quarter of the Babylonian tract, but the directions given are simply right and left, which leaves a certain amount of uncertainty as to its relations. In the Eastern Quarter dwelt those who were in the greatest delight or ruling and also were in some natural lumen. (LJ 58)

A - Tower on the Mount of Assembly: first position.

B - Opposite Tower: NE

C - Communications (SD 4969).

D, D - Benches on Mount of Assembly.

F - Mountain range, E to W, in the south

G - Above of vast multitudes.

[Drawing]

Bishops and prelates, aided by Jesuits, appeared on a mountain to the right of the place where the Lord appears as a Sun. On this mountain they had a great city and a Consistory, but no Pope was permitted. (SD
4957) They had organized their authority over the whole region, inspiring the multitudes with the chimerical faith that the things they say are from the Lord and that the Lord is with them with His own presence. (SD 4956) Inspectors were everywhere, and spies. An immense multitude occupied the mountain.

In the midst of the mountain was an eminent height, which Swedenborg calls the MOUNT OF ASSEMBLY. This was is the side of the North. Its height was the same as the height of the Sun. (See Isa. xiv)

A Watch Tower stood above the mount, indeed many on and below the mount, from which signs and signals were given. The whole mountain was surrounded with benches, filled with spirits--row after row--who ruled all things below as far as eye could see. This rule was from a diabolic love. (SD 4965ff)

A communication appeared between the mountain to the right and another toward the left. This was produced by an interception of the light of the Sun by such as took away love. (SD 4969) The mountains there obscured the Sun; a vast multitude was in that place of communication, possibly descended from the Mount of Assembly. (see SD 4969, 4968)

A corresponding Watch Tower then appeared on the opposite side (SD
4969:2).

Presently, the Mount of Assembly, end the surrounding mountains, sank down from its altitude even to the plane of the horizon. But as this was happening, the Mount of Assembly was-with a great number of spirits transferred to the left, around, to quite a distance, where it sank down. They feared their destruction. (SD 4975ff)

The immediate occasion for this judgment was that Swedenborg read Isaiah ch. xiv, concerning Lucifer, the King of Babel, and the angels turned their eyes upon the spirits on the Mount. (SD 4970 et seq.)

Afterwards there appeared a Babylonian Tower of doctrine, being built up on the left side by a council which deliberated below. They sent out these dogmas to establish the worship of the Vicar of Christ. (SD
4979ff) They raised the tower above the clouds. Ib. Some of them devised how to receive and adulterate the Heavenly Doctrine (printed in Arcana Coelestia), but were detected and punished by being unable ever to recover their intellectual power. (SD 4988)

The mountains further off however resigned. The Judgment was not yet started, only a visitation. (SD 5004ff)

[Drawing]

Later site of Mount Assembly First site of Mount of Assembly

A - Second Babylonish Tower (SD 4969-1/2)

B - Mountain of the Phantastic Sun

Those in greater dignity, and thus to the right side, were first removed, (SD 4954, 4977). A movement to the North indicates an increase of ignorance and phantasy.

In their attempts to make the simple hold their confidence in them, evil spirits (Jacob Benzelius, etc.) resorted to magical miracles. They produced--by phantasy--a Sun, but they could not make it shine! So they put a man in this lightless sun of phantasy and made him give verdicts in their favor. They hailed him as God the Father, and when he was judged, a successor was continually appointed. (SD 5044ff, 5207, 5082f. LJ 58) He authorized their crimes, and assented to the doctrine of Purgatory. (SD 5005f)

NOTE: The mountain on which this devil sat, may be identical with the Mount of Assembly after its transfer to the left and its subsidence.
(See SD 5082)

The man in the sun: received the applause of Jesuits, sad sirens and some of his worshipers or disciples said that they are Christs. (Cp. SD
5080ff, compare 5208, 5209)

2.{empty} The Beginning of the Last Judgment on Babylon.

After these preparations had been made in the Eastern Quarter, Babylonia, as to its three sides, was completely devastated and utterly destroyed. This judgment commenced at the end of the year 1756, and on the 5th and 6th of January 1757, it had been accomplished. (SD 5336)

It occurred in the following order: 1. Southern side; 2. Northern side; 3. West, toward North;

3.{empty} A summary description of the progress of the Judgment is found in LJ
61, 63. The features of the Babylonish tracts are outlined in LJ 58.

The general stages of the Judgment were:

(1) Earthquakes in diverse places: spirits tremble and flee in all directions.

(2) SOUTH: In the great city, a flight to the cellars and caves with their treasures. An earthquake and ebullition from below overturn city and region. The East Wind carries all into the Black Sea. (Jer. Ix, 11, x. 22, xlix. 33. Mal. i. 3. Apoc. Xviii. 21.)

(3) WEST and NORTH: Earthquakes (Matt. xxiv 7, Lu. Xxi. 11. Apoc. Vi. 12, viii. 5, xi. 13, xvi. 18, and in Old Testament). An East Wind, through the South, demolishes the front part of the West quarter (dark ages) the Great City, from West to North to East, is laid bare. There is no fire or flood, but the places are overturned and blown away into smoke.

[Drawing]

EAST

NE Chasm

GC - College for Cath. Hells of the gentiles Gulf in South toward North

Gulf in angle between North and West Gulf in West and South

Gulf in West, to North

(4) EAST: The mountains subside into the deep. The god set up for their worship is cast into hell with the worshipers. The monks declared him God and themselves Christs.

(5) Remote WEST: The Seven Mountains (Apoc. xvii. 9) yawned open into spiral gulfs or turned upside down. The plains were deluged and the spirits cast into gulfs.

(6) Four gulfs or chasms were seen, others not seen. The Black Sea was covered up by an encrustation of black dust.

(7) Good Catholics were brought to a district inside the Middle Space for instruction.

4.{empty} Swedenborgs visit to the Spiritual Rome, or Babylon.

In a wakeful vision Swedenborg visited a certain senator in a place called Rome, in the Southern quarter, in a house, which resembled a palace on the Capitoline hill. This spirit, with some others, had been trying to form a doctrine of life. (SD 5210ff) They accepted some things which Swedenborg told them, but remained in the extravagances of the Catholic religion. The Senator seemed to receive something of the doctrine concerning the Lord. This caused many prelates and cardinals to conspire and form a mob which broke in through the windows. They thought to kill him and tried in vain to drag his dead body away. (SD
5211)

The conspiracy involved multitudes on surrounding hills. Swedenborg was besieged, but protected by being put to sleep until the conspirators were overthrown and cast the fourth gloomy gulf (mentioned in SD 5206, 5220), and the riot quieted. (SD 5212)

The gulfs (hiatus) are described in SD 5204 as being at great depths in the extremes of each world, or interstitial. About fifty cardinals are cast into the third gulf--the lake of sulphur. (SD 5213, 5204) See LJ
61 for the position of the gulfs.

5.{empty} A papal Consistory at in the Southern quarter (SD 5221, 5229), and further towards the south former cardinals who ruled the conclave. Popes are not allowed to show themselves. (SD 5215, 5229) The Consistory, whose membership changed daily, governed the whole Babylonian tract by their gaze. When they deny the Divine, influx from heaven is denied them and they fell down as if dead. (SD 5229)

6.{empty} The Southern Chasm and the New Hell. Events now increase in importance. After half a day of tranquility, Swedenborg finds that more than ten thousand eminent monks and higher Roman clergy have gathered to scheme to usurp the Lords power. Some of their followers dissented.
(SD 5230)

A large mountain in the southern quarter opened into a frightful, dark chasm running deeper and deeper to the south. (SD 5231) Many spirits were engulfed. The peaks of all the mountains of the Babylonian tract flowed together into a continuous chain, and from all--in the West, North, and East--a multitude of spirits who had magnified themselves from self-love were carried into the deep chasm. (SD 5232, 5235, cp. 5313)

NOTE: The formation of a continuous plane out of the summits of the mountains suggests the defensive action of the hierarchy. (Cp. SD
5765f) But these leaders, whether ignorant or learned, outwardly good or evil, were judged together, for their pride. (SD 5233)

The order in which they were borne into the chasm was, (1) those from the South, (2) those from the North, (3) those from the East, (4) those from the West. (SD 5233f) The mountain of the cardinals was then split open and, with some of the popes, cast into the chasm. (SD 5234)

There was rejoicing among those Catholics who had lived in mutual charity according to their religion (SD 5236).

The chasm was enlarged below into a vast subterranean hell, in an orderly arrangement according to quarters. Angels are sent to arrange it into order. (SD 5237) This hell is new, and is kept closed beneath but open above; and is for those of such character who had lived since the beginning of Christianity, and is still open. (SD 5338)

This happened in the last days of the year 1755. (SD 5239)

INTERPRETATION OF SPIR. DIARY, 5231 et seq.

Confer SD 5206, 5212.

[Drawing]

7.{empty} Judgment on the Mohammedans. A this point, the last judgment an the Mohammedan tract seem to have begun. This judgment took less time, but went on coincidentally with the progressive judgments in the more central tracts. (SD 5240-5248, 5258-5262). See Part III.

8.{empty} The Mountain of Multitudes. Investigating an infestation from the northern quarter towards the West*, Swedenborg was conducted to a mountain consisting of cities one below another, inhabited by immense multitudes from various ages of Christendom. A winding shaft connected the highest city with the lower where those of greater distinction dwelt. Monks find others from the first origin of Babel were there, some also of the ancients who were idolaters. These lived separate from the moderns. (SD 5249f) A great part do not appear to each other when they turn to different quarters, being of different opinions (which in the spiritual world causes them to vanish or be invisible). Similarly their houses disappear with them. (SD 5251f)

* Compare LJ 58 and 61 as to situation-in the West, in front.

THE MOUNTAIN OF MULTITUDES-SD 5249

Swedenborgs Diagram and an interpretation

A--A precipice. BC--The highest city. BD--A city below it. DE--A city still lower. FG--A communicating shaft or winding stairway. IK--The lowest habitations, where dwelt those of greatest distinction from ancient times.

[Drawing]

A visitation by means of angels occurred. (Gen. 19) The governors of the innumerable monasteries were cast out into a gulf which opened lengthwise in the mountain, or into the mountain gulf. The monks were a lazy crew who subjugated others by sacred things, by magic, by phantasies, or violence. The monasteries were now emptied. (SD 5253f)

Those who sat in the windings of the shaft as agents of oppression were cast down, mingled with pagan idolaters, into lakes and marshes toward the West. Those in the lowest city, who ruled the rest, were cast into the southern chasm. The whole mountain was dispersed like smoke. (SD
5255-5257)

9.{empty} Judgment on the Gentiles. Gentiles, at this juncture, were being brought from their districts by a way on high above the northern level of the Christians and to the East and South beyond the Mohammedans. (LJ
51, SD 5263-5267) See Part IV.

[Drawing]

INTERPRETATION: (See SD 5279)

[Drawing]

The Papal City (A) was on the surface of the mountain; the monastic city was below, under the ground, inside the mountain.

A - Mountain with small papal City. K-Entrance to the great city underneath. GEF-Northerly extension. I-Outreach into the East. BD-Extension of city to West and South. C-South. EI-Region of various religions. UZYX-Region of villas and fields under the control of the monasteries.

[Drawing]

INTERPRETATION:

A - Mountains within which the wealthy dwell

BCD - Mountain of the Rich City

CE - Spiral shaft to city

FG - The great city, G-West, F-East

HI - Shaft to treasure chambers

KSM - Labyrinth to NN, where the most precious things were stored

10.{empty} The Papal City in the West. Behind the city in the Mount of Multitudes (SD 5249ff) towards the West was a vast mountain country. On top of one mountain was a small city ruled by a Pope who lived in a palace like that on Monte Cavallo at Rome. (SD 5269f) in Northern quarter, LJ post 102) Catholics coming into the other life have always a Pontiff set over them who takes over the name and function. But seldom is any Pope from the world so appointed. (LJ post. 102, CLJ 59, Docu. 247) Yet one who was Pope twenty years before Swedenborgs writing CLJ 59 was placed over the Papists because he believed in heart that the Word is more holy than is believed and that the Lord ought to be worshiped.

NOTE: Clement XII was Pope 1730-1740, when he died at the age of 88. He was austere in personal life, rigid in discipline, a reformer and a patron of language studies. Swedenborg notes: It was perceived that in the life in the world, he had been blind. Whether, perchance, he use saved. (SD 5272, cf. 5845)

When a visitation came, Swedenborg was brought there, and saw a golden image of Mary carried out and next the Pope, before any harm could come to him. (SD 5272, LJ post. 102, SD 5845)

11.{empty} The Metropolis in the Mountain. Inside the mountain on which the Papal city stood, was another city, very wide, which extended to the eastern quarter and through the Western as far as the southern. There was no other city below it. It contained multitudes of various religions, but was a Catholic city. (SD 5270) It was wholly monastic, except for small sections. The monks lived off the people and were hypocrites. Swedenborg writes, I found some acquaintances in that city.
(SD 5271)

The great city heaved up and sank down, and roads opened from it. All in the monasteries were compelled to go out by a Divine force. The well behaved were allowed to remain, under judges and priests. The evil were cast into the marsh (of the gentiles) in the North, where the mountain of multitudes had been, or into the southern chasm (SD 5231), and the worst into a gloomy cavern beside the marshy valley. (SD 5273-5278)

NOTE: The judgment on the Seven Mountains in the West occurred later. See section 21.

12.{empty} The Rich City between West and South. A city-Great Babylon--extended underground from West to South (as far as the mountain of the southern chasm), where ingenuity and invention were esteemed, and they excelled in the light of nature. SD 5280ff.

An immense tract, under the mountains, as under their dominion. The city was entered through a shaft from above. It was principally for the wealthy and is ruled by Jesuits and monks who gathered riches--gold, silver, and precious stones--concealed in dark vaults lit by candles
(Rev. 18:23) (SD 5282-5293)

[Drawing]

A - the very great underground city

B - the very rich city Babylon

K - the western sea

S - district subject to the rich city

T - district subject to city A

M - northern hells (swamps)

N - southern hells

H - the hill in the Middle

SWEDENBORGS DIAGRAM OF THE BABYLONIAN TRACT, SD 5302

The diagram was made in order to have an idea of the situation, which is somewhat confused from turning to a quarter opposite from those who are above me.

They performed masses in a foreign tongue that is not understood by the people. (SD 5289) This is against the law of the spiritual world. (Cp. SD 4931, 6049)

They began to commune with the magical hells under the southern quarter. (SD 5293) The dust they that thought to be gold was placed in inner cells, but the ground beneath began to bubble up and an earthquake caused some to be engulfed in nearby hells. Panic followed and the vast crowds of Jesuits and monks poured out from the shafts to the level of the mountain and the monasteries were deserted. Some tried to rescue their golden images but in vain. (SD 5293-5295)

The mountain was then borne away, exposing the city with its magnificent temples, monasteries, and palaces. But the city was carried away by an east wind (cp. AE 419:11), as smoke, and cast into the western sea. (SD 5296) Other judgments are noted, lasting for same time. Some of the wicked were cast into pagan hells (SD 5264) on the West at the sides of the Mohammedan heaven. (SD 5297) A flood seemed to be let loose over the whole region. The Jesuits were lined up along that shore of the western sea which faces the South, and then cast in.
(SD 5297-5300)

Thus perished great Babylon (Rev. 18); and a monstrous dragon flew over its place. (SD 5301-5303)

13.{empty} The Western Tract. Under the mountains behind the Papal city (SD
5269, 5270ff) were many monasteries, monks going about at night to intimidate souls by miracles, masses in an unknown tongue, and keeping them from reading the Word. The monks were sinful and gluttonous. An earthquake frightened them out and they were cast into the northern swamp, the murky cavern, or a certain gulf. (SD 5305ff)

In the north-west angle, women who had lived in almshouses infested Swedenborg who finds that they had lived indolent lives, loved gossip, eating and sleeping, and going to church without desire for instruction. They infest others by means of thought. Most of them were cast out from their hidden cells into the fifth gulf near their dwellings. Here they are compelled to remain and to think only of what they see. (SD 5308-5312)

Beggars or hoboes who acted as if they stuck together, were cast into a gulf towards the North (SD 5313)

14.{empty} Monasteries from various Ages. In the western quarter, beneath the earth, there were twenty times as many monasteries as on earth, but on top only a few to observe the state of things. New monasteries were formed of the same order in each age and the older ones then let themselves down on a lower level. In one place, in the center, there was a hill where they at times could ascend to those above. Those of the Dark Ages dwelt below those of the time of the Reformation, and were not so wicked. (Cp. 35 58, SD 5323) There canoe appeared se gods, some like robbers. None know any doctrine. (SD 5315-5317)

The rich men of the Dark Ages and later, live similarly in strata. They are idolatrous and turn their back to the Lord as a Sun, and live in illusory light. They claim to be destitute but secretly cherish treasures in phantasy. (5318-5320)

Some of their dwellings were laid open, and from fright they crowded up the spiral stairs with their possessions. (SD 5321)

[Drawing]

SWEDENBORGS DIAGRAM-SD 5317-to illustrate the arrangement of the levels in the underground city of monasteries from the Dark Ages.

The point marked A in the middle was the only exit but this was usually closed up.

On the surface dwelt those who lived after the Reformation.

15.{empty} Total Destruction of Babylon. The article so headed (SD 5322-5328)
seems first to summarize the judgments of the western tract of Babylonia, giving some additional details. Later paragraphs show (SD
5329-5336) the conclusion of the judgment on the western tract.

After the east-wind had carried off the mountain-roof of the Monastery region in the West, a stronger east wind, going and returning, exposed the two lower strata, where the monks and a rabble of slaves existed. The evil were brought to the north shore of the western sea and cast in, while the monasteries vanished like smoke, and the region became a desert. (SD 5329-5332) Their magical instruments were reduced to powder floating like scum on the western sea. (SD 5502). Merchants who were wont to trade with the rich there, found nothing at all. (Rev. 18;15, cp. SD 5344, Expl. AR 783ff) They went away sad, some trying to fish out the gold and silver from the bottom, perhaps of the western sea. A
sulphurous fume filled the place. Some spirits nearby were seen with millstones over their shoulders-because they had confirmed execrable dogmas from the Word. (Rev. 18:21, SD 5333-5335)

Thus was Babylon devastated and utterly destroyed on three sides, the southern, the western, and the northern; this commenced at the end of the year 1756, and in the beginning of the year 1757, yesterday and today, these three tracts, today (being) the 6th day of January, 1757.
(SD 5336)

16.{empty} Babylon on the Eastern Quarter.

In the East, there were also Catholics, both monasteries and common people (vulgus) subject (to them). But these were pious and upright, and devoted to many uses. These had been released from the judged quarters and taken into the East where they kept up their religion. They sought by influx to restrain those in the South and West, but without success. (SD 5337, cp. 5501ff)

The vast multitude of spirits who had made the phantastic sun were cast into the North, beyond the desert there, being led around by the NE
diagonal. (SD 5340) Those in the SE angle were led out of their monasteries across the South into the West or across the North to the NW angle to where those who lived in almshouses had dwelt, or still farther away. These had remnants of hypocrisy and love of rule, but an inner sanctity. (SD 5339)

Lastly, three strata of monasteries in the NE angle were visited and dispersed. Here were nuns and virgins in immense numbers. Those in an evil life, in harlotry, etc., were brought out to the front of the boundary of the angle and cast into a deep chasm. The rest, those not idle, were led to form a society, but few stayed, for they longed from their monastic life; and many were distributed amongst Catholics to learn to work. Women who from religion served dutifully in domestic uses were brought to the South West, to be instructed in a society outside the region of the church where there were no infestations from men. (SD 5341-5343; LJ post. 109) Monks and merchants returning to the abandoned districts, lamented. (SD 5344)

17.{empty} The Judgment on the Reformed.

The last judgment on those in the central space now commenced. (CLJ 14, et seq., SD 5347 et seq., passive) See Part V.

18.{empty} Societies of Good Catholics.

In the western quarter, in front, towards the North, pious and good Catholics with an affection of truth were given fertile habitations where they are instructed by priests From the Reformed as in a school, and then accepted in heaven. (LJ 63, SD 5405, 5504f, cf. 5515f; LJ
post. 112, 111) Various types of simple good Catholics were preserved in places under the earth. (SD 5503)

Those transferred to the West seemed to go by a direct way, borrowing silver and garments from the Reformed, as the sons of Israel did from the Egyptians. (Expl. LJ post. 110, SD 5406, 5412)

The new colonists of the West inherited much treasurer left underground by the monks; because they were in an affection of truth. (SD 5412-1/2)

Those simple good Catholics who had lived scattered underground in the west among the monks, concealed from contagion of idolatry, were given places formerly occupied by the evil in the South, East, and North. Those adhering strongly to Catholic traditions remained hidden near the western see, an the shore facing North. (SD 5503)

19.{empty} Residue of the Catholic Community.

Because of the need for spirits to serve the Catholic communion on earth, there remains, after the judgment, sufficient Catholic spirits in the world of spirits.

Swedenborg saw remaining a city of Rome in the south-west within the Babylonish tract, having all the streets, but no Monte Cavallo or church of St. Peter. Some monasteries remain for the present. (SD 5408)

A new orderly arrangement was made around the Babylonish tract--that is, to provide for the hells descending at its outer borders, and for the disposal of the good Catholics, so described above. (SD 5501 et seq.)

20.{empty} Attempts to re-establish Papal Dominion.

Continued attempts were made by Papists to retain dominion by magical use of symbols to persuade that they worship the Lord. The cross was used by some (SD 5409). In the West near the North, thousands of Jesuits were discovered living in a city who employed magicians. They had a miraculous lamp, a shining banner floating in the air, a man flying like an angel, and pious women praying for them. The lamp was taken away, their treasures turned to dust. It was shown that the ever-burning lamp was caused by their casting the heavenly doctrine into a crucible, and that the banner also was made from a pretended acceptance of the doctrine. (Descr.) The earth finally opened to receive these spirits. (SD 5413-5420) (Compare SD 5737-5739) (Cp. SD
4838, written before the judgment.)

21.{empty} The Judgment on the Seven Mountains

The Spiritual Diary gives several accounts of judgments on special sections of the Babylonian tract in the West. (SD 5567ff, 5630ff, 5648ff). Whether these were later judgments or are identical with the events less fully described in n. 15 of our Notes, seem uncertain.

In the West, on a low mountain in the midst, certain spirits dwelt who sake simple spirits their subjects and force them to cause temptations in men. Other more cunning spirits; nearer the North, deflected the influx of heaven by possessing the province of the ear (where the influx of heaven has its axis) and so possess other spirits. (SD
5567-5569) But these crews are cast into a hell as soon as they assemble. (Cf. SD 5568e)

Certain crafty Italian spirits claiming that they possessed the power belonging to the Lords human nature, dwelt in a mountain in the West behind a wood. They try in vain to practice the methods of the Inquisition. They are cast into a desert near a bridge from the mountain, crossing a swamp. They lose their understanding and the worst enter a long tunnel underground leading to a second bridge and the farther they go the more stupid they become, and lie like corpses. (SD
5630-5635) At length the whole mountain sank in the midst, and waters from the western sea overwhelmed them, while other neighboring spirits are cast into certain gulfs. (SD 5636-5637)

In the West, behind the cities already judged (See nos. 13, 14, 15), are about twenty mountains, called the Seven Mountains in the Apocalypse (Rev. 17:9), because seven signifies what is profane. Moat of those there are Italians, but some are evil renegades from the Reformed. On one (possibly the Papal city, see n. 10) the Romans live who are in the lust of ruling the rest. To the North are the worst, from Naples and Sicily, who are in subtleties of falsity. On the middle mountains are those from Tuscany, Genoa, Venice, Milan, and the Transalpine provinces. (SD 5648-5649)

After visitation made on three of the mountains, it was next made on the Romans. They invited their last judgment when external bonds were cast aside and they proclaimed themselves as gods. They were taken from two mountains in a moment, and cast into gulfs (enu.). The middle mountain sank down in the center, and a black smoke rose. (SD 5650)

Next, those from the North (lower Italy) were judged because of open idolatry. An earthquake like a billowing sea came upon some, then the towns were scattered with their palaces. The mountains around were rolled back to and fro, and they were carried to an unknown destination. These were inquisitors (SD 5651, 5556, cp. 5633)

The mountains nearest to the North, where Neapolitans and Sicilians are, maintained a devil cult but besides worshiped the Divine to keep a protective communication with simple good spirits who well in a heaven on a mountainous region that rises up thence towards the middle space
(where Christians dwell).

These from Naples and Sicily are most malignant, yet sharp-sighted and keen, placing wisdom in wickedness. The worst become most stupid when vastated, and are confined under the NW angle. (SD 5652-5654, descr. 5655ff)

The upright spirits from whom they had their acuteness having been removed, they became insane and rushed into black caverns. Their town fell into a heap. (SD 5658)

[Drawing]

INTERPRETATIVE DIAGRAM OF THE WESTERN MOUNTAINS

This, or a similar judgment is described in SD 5812. The final stage of their doom took the form of a flock. Some who were in higher places retreated to the North, but the flood recurred and some were cast into the hells of the Nephilim. (SD 5812f) These antediluvian hells are to the left, in front, at the extreme outskirts of this universe. (SD
4453)

22.{empty} Babylon after the Judgment.

The cities and districts of the Babylonian snow lie deserted and leveled, barren and mostly uninhabitable. Yet since new spirits of like character continue to arrive from earth, similar things recur, new monasteries appear, etc. But thought several hundred thousand roam at large in the world of spirits, they are successively vastated and by alternations their places are destroyed. (SD 5599, 5598; TCR 818)

The great wealthy city of the Jesuits in the southern quarter is still a desert land though explored by wandering monks. (LJ post 106)

The Papal city seems still to be in the western quarter, with all the streets and monasteries, but without St. Peters cathedral and the Monte Cavallo palace. (SD 5408, 5410 des.) A good Pope is there maintained.
(SD 6022e) The Babylonians gather as before on the mountains where their love is and seek to make for themselves new heavens. When more than about; two hundred (or a few thousand) are gathered they are judged, and cannot remain on the earth there, when good spirits have taken possession. (LJ post 105; cp. SD 5598, 6012) Evil spirits who aspire to return to such societies are removed in the very ascent. (SD
5966) False new heavens are however formed again and again, but collapse of themselves through the proximity of good spirits. (A
Catholic heaven which dissolved is described, SD 6012) Seven methods of purifying societies after the Last Judgment are listed in SD 6020.

The monks still persist in sending out emissaries to seduce the Reformed. But they are constantly investigated and punished if they use cunning. (TCR 817; LJ post 107; AE 1107) For Babylonish spirits have now no intercourse with other spirits. (LJ 64; AR 812:3) But all spirits go to their places soon after death. (Cf TCR 818)

NOTE: The rise of nationalism has to some extent an influence in the world of spirits which is organized on the basis of natural affections. Even Catholics are likely to seek national associations in the other life. Babylonia has perished.

Many and great heavenly societies are formed from Catholics. (LJ post 112, etc.)

In February, 1762, Swedenborg records that a Catholic Council is held in the western quarter toward the North. (SD 6022, cf 5833, 5229)
Another council is permitted in the South towards the East. (TCR 819)
On a higher place in the West, good Catholics meet under an appointed Pope who acknowledges that all power is the Lords. Schools are there established conducted by converted monks. (SD 6022-3; TCR 820) In the southern quarter to the West, there is an imaginary heaven for Catholics. (TCR 819)

A general description of the papists in the other life is given in TCR
317-827.

The arrangement of the Babylonian hells is noted in SD 5895. In general, the bells of the Reformed stretch obliquely downwards beneath the Babylonian tract, the hells of the Catholics beneath the Mohammedan tract, etc.

The Catholic hells nearest the Middle Space are apparently milder, those of the more wicked being farther away and deeper. But for the sake of equilibrium, the hells beyond these are less atrocious, until you reach the tract of Mohammedans and gentiles. (SD 5895)

23.{empty} The Roman Catholic Church after the Judgment.

As regards Babylon in the natural world or on our earth, those meant by Babylon there are not in the same state as those in the spiritual world, and yet the exhortation (Rev. 18:4) is also for them, that they may take heed to themselves. (AE 1107; cp 880)

Come out of her, O My people, that ye be not partakers of her sins and that ye receive not of her plagues, for her sins have reached unto heaven and God hath remembered her iniquities. (Rev. 18:4, 5)

Regarding the end of Babylon: Not that the idolatrous worship of such in the world will be destroyed and themselves with it, for this will remain, but not as the worship of any church but as the worship of paganism; consequently such after death will come among pagans, and be no longer among Christians. But from those who have adored the Lord, and not the pope or saints or graven images, a New Church will be gathered up by the Lord. (AE 1029:8, cf 1029:4, 10)

The Reformed or Evangelical churches are included in the expression the Christian world, but not the Papists, because where the church exists the Lord is adored and the Word is read..., (HD 8.) instead the Catholic church is called Christian gentilism. (AE 955:5) The perversions of Papacy are described, LJ 55 and context, AR 784, etc.

24.{empty} Posthumous Biographies of Popes.

Sixtus V, Pope 1585-1490. A son or a vine-dresser, who by resolute ambition and assumed humility rose to Pope. Known for reforms and cold-blooded justice, magnificent public works and passion for order. Inspired the Catholic league and the invasion of England by the Spanish Armada. Amassed large public treasures in the vaults of St. Angelo.

Swedenborg (SD 5529) mentions Sixtus V first in connection with spirits who are not yet vastated, being in alternating states for as long as fifty years. If cast into hell, they keep on returning to the world of spirits. But if vastated they do not return, except by permission. Because Pope Benedict XIV wanted to speak to him, Sixtus V was taken out of a nearby hell. Scarcely speaking, he came into torture and wished to return. He was recognized only by his portrait. (SD 5529, 5833) Sixtus is sometimes set over his own hell to keep the impious in order, but is punished if he exceeds the law. (SD 5833, LJ post 103)

Later (AR 152) Swedenborg was erected to speak to Sixtus V. He was then chief governor of a Catholic society which excelled the rest in judgment and industry. He confessed that he had for the last half year of his life realized that the vicarship was an invention, that the Lord alone is to be worshiped, and that the Word was more holy than the papal edicts. He led a very active life, conversed about the treasure in St. Angelo, and sent a message to other Catholic societies and to men on earth.

Clement XII, Pope 1730-1740. See note under n. 10.

Benedict XIV. Pope 1740-1758. Died May 3, 1758. Known for his tolerance, for discouraging persecutions and restraining the abuse of ecclesiastical power. A cultured man, wise and zealous in propagating Romanism. His pontificate was unique as one of peace, plenty, and prosperity. When he died, he was preparing to suppress the Jesuit order.

Swedenborg spoke to him, May 21-25, 1758. (SD 5529, 5833, 5841-5847; AE
114e; LJ post. 103)

Seen in the West, near Worth. Shown impiety of Babylonians. Astonished that even inferior monks made themselves Christs, which he alone should claim. Saw Sixtus V. (SD 5529, 5833) His character was shown as cunning, at first civil, then very sharp-sighted. (LJ post. 103)

He spoke to Swedenborg politely and as if from a borrowed affection of truth. (SD 5843), listening attentively and confessing that the Word has a spiritual sense end that no edict should contradict it. (SD 5841)
But when left alone the destruction of the Reformed, thinking he plotted himself immune from punishment. He was then cast into a cavern and then taken West. (SD 5843)

His false claims and pretensions as Pope are listed, SD 5844, LJ post 103. He is said to have loved the Jesuits (secretly?) more than others
(Ibid.) He associated with sorceran and Jesuits, and the Neapolitan spirits in the West, and finally plunged himself into the western sea at its farthest extremity. (SD 5846f) This happened only a few days after he met Swedenborg. (Cp AE 114e; SD 5841, 5843; LJ post 103)

25.{empty} Russian Communities.

The Russian nation (belonging to the Greek Orthodox Church, called Greek Catholic), after the last judgment, dwelt in the SE angle, under the earth, in greater darkness than the rear. Many secretly deliberated about political liberty, but feared the Czar as omnipresent. (SD 5452)
They do not care for religion, are more inwardly wicked and operated by phantasies. (SD 5454f) Russians, Italians and Swedes are the worst nations in Europe. (SD 5043)

Swedenborg was also carried down to other Russians who were better. These worked continually. The better type was carried down towards the North, near the NE angle, beyond the deserted Babylonia, into a plain and a forest in which also there are same who are like wild beasts. They live underground. (SD 5453, 5456)

Good Russians are described in SD 5963 as not so wicked as the rest in Christendom, but as averting the influx of the evils of the Christian world from Swedenborg. They live in greatest subordination to their officers, believing that all they have belongs to God as formerly to the Czar. They are modest and obedient, not at all intellectual. They purge their society of evil persons so that they can remain in their place. They have no ambition.

Czar Peter was seen in a dream, and afterwards was seen among the Russians. He claimed possession of all the property of his subjects. These revered him almost as their god. They were free from the love of self but were of thievish disposition, willing to risk and do everything to obtain money. (SD 5949)

The Word is but little read in Russia. (De Ver. 16)

SITUATION OF THE MOHAMMEDANS IN THE SPIRITUAL WORLD

EAST

A - Christian Middle Space-Situation of Reformed nations

B - Babylonian city of Blind Faith

C - Whirlpool

D - Forests, marshes, and ponds, North of Mohammedan desert

E - Mountain of the Moguls, which sank and became desert

F - District where Mohammedans are brought who acknowledge the Lord as the Son of God

G - Site of the Black Sea or Western Sea

H - Babylonian ethereal spirits conspiring with Moslems

I - Gulf into which ethereal spirits were cast

K, L - Chasms or pagan hells on both sides of Mohammedan heavens

AM - Place of the false Mohammed while instructing coverts to Christianity

N - Many mountains where false Mohammed was worshiped

Q - Gathering place of novitiate spirits from Moslem world

P - Great northern chasm, for Pagans and idolatrous Moslems and Catholics

=== IV. THE LAST JUDGMENT ON THE MOHAMMEDANS

General articles on the Mohammedans:
TCR 828-834; CLJ 68-72; SD 5240-5248; LJ post. 69-101.

1.{empty} Situation of the Mohammedans in the Spiritual World.

From natural affections centering about their religious loyalties, the nations of the Moslem faith are arranged in a circuit or tract outside and around that of the Papists. (LJ post. 126; LJ 48; CLJ 68; SD 5258, 5240; TCR 828) They appeared distinguished according to their countries, all in the West near the South. (LJ 48, 50; TCR 828)

The position of nations in the spiritual world was, about the time of the judgment, determined by the light of truth from good. there according to their confession of the Lord or of one God. (LJ post. 126, cp 176, 178; LJ 48, SS 117, TCR 828)

The Koran alone is the sacred book of Islam. In it there is something accommodated to the genius of the orientals, something from the Old Testament and something from the New. (CL 342; SS 117e; AE 1217:3) The religion was raised up in Divine providence to destroy the idolatries of many nations. (CL 342; TCR 833; CLJ 71; SS 117e; and DP 255:2-5, fully expl.) From the Koran a Muslim sees certain saving truths: that God is one, that the Lord is the Son of God and a great prophet, that all good is from God, that there is a heaven and a hell, and a life after death, that the evils of the decalogue are to be shunned, etc.
(AE 1180:2; cp CL 341) Some pages of the Koran are written by correspondences and by reason of the correspondences there is some light from it in the (Mohammedan) heavens. (SD 5809:8; cf LJ post 93)

NOTE: Compare the statement in the Koran that in it there are some verses clearly to be understood; they are the foundation of the book; but others are parabolic. (Chap. iii a)

2.{empty} Mohammed and his Impersonators.

The Mohammed who wrote the Koran, after his death, at first presided over his followers. He had his seat under the Papists, But because of his love of ruling as a god he was sent down to the right side near the South. (CLJ 70; TCR 829, 830) He was a gross, swarthy, corporeal and idiotic spirit. (SD 5666a)

Because Mohammedan spirits usually seek for Mohammed, some impersonating spirit is always provided. (LJ 58; CLJ 69; TCR 829; CL
344; LJ post 82) Such a spirit is appointed who has acceded to the Christian religion, and he therefore appears among Christians, but beneath the Christian middle, a little to the right, towards the NE
quarter, but is later removed to the western quarter. (SD 5243, 5260-1/2, cp to the left in LJ 50)

Two Mohammeds are specially mentioned as functioning prior to the judgment. (LJ 50; LJ post. 69, 77, 79; SD 5260 1-2) These sometimes refused adoration and worshipped the Lord shown in glory, and visited heaven for instruction. Their followers were inaugurated into choirs.
(LJ post. 69-77, 83)

One Mohammed, born in Saxony, had been captured by Algerians and had adopted the religion of Islam. He then became a ships captain, was captured by the Genoise and received Christianity. (SD 5667; LJ post. 79; LJ 69; TCR 829) He was a clever man and led by love of rule impersonated Mohammed after death. He held his court; at the left under the plane of the sole. (LJ post 79, 81; SD 5268) A certain fiery light--invisible to non-Moslems--marked his place which enjoyed an unclean heat as from polygamy. (LJ post 81; LJ 69; SD 5268; TCR 829)
When he at last arrogated power to himself, he became openly angry when multitudes of good spirits deserted him and were transferred to the East; (cp SD 345). He was then exposed and chained in the lover regions. (SD 5663a, 5260-1/2, 5261)

Those who wanted to worship Mohammed as a god remained outside the Christian middle and labored to release their judged Mohamned. (SD
5664a) Failing this, they appointed a successor from their own number; this also failed and they then elected some one on a mountain above Christendom as their supreme head. On his advice they invaded Christendom and secretly sought to injure Swedenborg and others. (SD
5664a, 5665a; LJ post. 96; TCR 829)

To quell this crew, the Mohammed who wrote the Koran-a black and terrible spirit--was raised up and appeared above to the left of Swedenborgs head. He confessed, I am your Mohammed, and sank down again. (SD 5666a; TCR 830; LJ post. 78; CLJ 70)

After this, the Mohammed in chains--from Saxony--was led forth so as to be identified who he was on earth. (SD 5667a, and above)

Another Mohammed was a Christian from Greece had a place behind the former, became able assistant, double, and successor. He was acknowledged by those who in the world had thought of many Mohammeds.*
(SD 5667a; LJ post. 80) He may have been the second Mohammed who was cast into a gulf. (SD 5261, compare, however, SD 5667a with 5663a)

* This may refer to the question of the Caliphate which has often troubled the Moslems.

3.{empty} The Last Judgment on the Mohammedans.

The judgment on the Mohammedans started in the first few days of January, 1757, after the dispersal of the Mount of Multitudes in the northern tract of Babylonia. (See SD 5239, 5258, cp 5336; LJ 47)

The Mohammedans were led from their places in the South West, by a way around the Christians, to the East as far as the southern boundary. They went through the deserts and bogs behind the great Babylon and the city of Multitudes, and past the great northern gulf and the whirlpool of wide extent. (SD 5258; LJ post. 93, 99) On the way, the good were separated from the evil, the latter being cast into marshes and lakes, many also scattered in a far-off desert. (LJ 50; post. 93; SD
5258-5262)

NOTE: In the other life, all past states or spiritual contacts are repeated. This often takes the aspect of travel or of communication with different quarters or classes of spirits. Through such successions of states judgment is effected.

The remnant went on toward the East and colonized a vast district of mountains and valleys in the East, behind the place of instruction for Christians, but quite far from the Christian circle. (LJ post. 93; SD
5258)

The best were led on further, to the South, with communication with the Christian heavens; and if receptive, they obtained heavens behind the Christians there. (LJ post 93) Others were brought first to the East, then to the North, ascending higher and higher to the West, and those who confirmed themselves in the Divinity of the Lord appeared to ascend toward the South. (LJ post 31; SD 5246) This was an inner circuit. (Cf SD 5260, 5262.)

Pagan hells lie on each side of the Mohammedan heavens, but deeply below. (SD 5264f)

Some Moslems who accepted Christianity from craftiness, were detected and cast into the desert or into the adjacent chasms, or dispersed. (LJ
post. 94)

In the western quarter there gathered a great many of the faithful, and these wanted to restore a Mohammed who had already been judged and enchained and whom they worshiped as a god. (SD 5663f; see above)

These Moslems, some of whom lived in palatial abodes, then elected a new Mohammed and infested the Christian region; and associated themselves with etherial spirits from the Babylonians so as to render themselves inconspicuous (See above; LJ post. 36; SD 5664a, 5856ff)
These Mohammedans were destroyed by the earth surface rolling over them and they ended in a fiery hell. (Ibid.)

Swedenborg sometimes refers to the wealth and magnificence of the Mogul emperors or the Mongols (Mogolenses). (AR 655:7; TCR 245:2)

Their judgment occurred in due course. They were proud, loved rule and riches, and were hostile to Christians. In the spiritual world they, dwelt at the southern side, beyond Christendom. The mountains were cast down or subsided, and those who from love of self thought of Mohammed instead of God were cast into deserts or into hells. (SD 5729)

NOTE: Originating with the conquests of Genghis Khan and Tamurlane, the Mogul empire at Delhi began to decline in the 18th century.

4.{empty} Mohammedan Heavens.

Mohammedan spirits told Swedenborg that they had believed that they would live after death in happy marriage, drink wine, etc., and that they would shed the material body as exuvise. (LJ post 90) They perceive that there is a resurrection immediately after death. (SD
5244)

Their abodes, as spirits, are variously described. Swedenborg saw two mountains on which they lived more harmoniously than Christians do. On one they lived well in willing submission to their magistrate, and had a better understanding than most Christians. On the other mountain were spirits perceptive of spiritual truths. They recognized the justice of monogamy, but could not yet recede from polygamy, which in the world had been conceded by religion due to their passionate oriental nature which would otherwise break out into adulteries. (LJ post 84f; SD
5060f)

Certain Janizaries (Christian born) said they were, some still Christian at heart, some intermediate, some Mohammedans. When their city was infested by the evil, it sank down and was protected by a mountain wall. (SD 5064; LJ post 88)

The mountains cannot usually be reached by Christians, but if these intrude they are imprisoned, maltreated and sent away.

Those on one of the mountains gave holy attention to the doctrine about the glorification of the Lords entire body, that He took all things of the body with Him, differently from men, because His soul was infinite.
(LJ post 87; SD 5063) The same was explained fully by angels to certain gentiles beyond the Mohammedans to the East. (LJ post 129; SD 5244)

These mountains were, presumably, initiatory heavens. All the good Moslems live at first with many wives if they did on earth, but afterwards with only one woman who is of like mind. (De Conj. 48)

Moslem spirits are first instructed by teachers of their own religion who have been converted to Christianity. (HH 515; LJ 50) When some wished to go and join the heavenly Christian Church they were advised to remain in their own religion, or in their doctrine of the Koran about the Lord as the greatest prophet and as the Son of God. For their spiritual good is formed in part from such things as had been of their faith, which cannot suddenly be extinguished. (LJ post. 97; SD 5669a; cp HH 516)

Those who on earth had believed in the above belief and lived a moral spiritual life are instructed, and most of them receive the belief that the Lord is one with the Father; and these have a heaven in which all things are happy and live in a spiritual marriage of good and truth from the Lord. (LJ 50; LJ post. 101)

They are docile and obedient (SD 403ff, 480, 512), so that Christian angels were moved with shame (SD 344). Their infants are taken into heaven immediately, but not so immediately their boys and girls (SD
347, expl.).

NOTE: The places of instruction are described in HH 513 et seq.

Many of the Mohammedans are sent among Christian angels and become Christians. (De Conj. 49; SD 5246) The general teaching is that the Mohammedan heavens must remain distinct from, and outside of, the Christian heavens. (CL 352, 342; De Conj. 48; LJ 50; cp. D. Wis. vii. 2:3) But communication is granted them with the Christian heaven by influx from the Lord. (LJ 50)

The Mohammedan heavens are distinguished into three: (DP 255:5)

3.{empty} The highest heaven, of those who acknowledge the Lord as the Only God, one with the Father.

2.{empty} The second heaven, of those who renounce polygamy.

1.{empty} The ultimate heaven, of those who are being initiated.

They may also be grouped into two heavens, a higher and a lower. (CL
342, 343) The higher heaven includes all who renounce polygamy, and is thus the only permanent heaven. (Cp De Conj. 48, their heaven; descr. 46-48)

=== IV. THE LAST JUDGMENT ON THE GENTILES

General articles: LJ post. 125-133, 115-124, TCR 835-840, CLJ 73-78, LJ
47-51.

1.{empty} Situation of the Gentiles in the spiritual world. The gentiles are in two circuits: the Africans are just outside the Mohammedan circuit, and those from Asia and the Indies on the outside fringe. Round about is the bordering Great Sea--which appears as a boundary to those from our earth. Certain gulfs also appear which surround the area of our world of spirits. (SD 5240-5248, 5263, 5065; AC 9583; LJ 48; LJ Post 126-128; SS 105e; De Conj. 96) These circuits are arranged in a globe, as Swedenborg perceived when he could reach the Gentile region only by descending as by a declivity. (LJ post. 126; SD 5244)

Among themselves, the gentiles dwell distinct according to races or genius, ordered according to the quarters, in correspondence with their lumen and love. (SD 5240-5248)

When Africa is mentioned, the angels think of the East. (AE 21)

2.{empty} Before the last judgment, a New Church was being prepared for among gentiles in the spiritual world.

After noting the great number of men within the church on earth who are atheists--three millions and more (SD 4769f)--Swedenborg reports that it had been announced in the spiritual world that somewhere amongst the nations there begins to take place a revelation from heaven; that is, that spirits and angels speak with them and teach the heavenly doctrine, especially about the Lord; and that those there embrace it, and that thus a New Church from heaven is rising up.... (SD 4770) This appeared to the left in front, as if somewhere in Asia near Africa (SD
4771).

Many spirits from this place spoke with angels concerning the heavenly doctrine, intending to communicate these things to their people. (SD
4772)

Certain spirits communicating with men not far from the Indian Sea
(descr.) had long had revelation from heaven, were expecting a revelation concerning Christ, and an angel came to instruct them. (SD
4774, 4775; cp LJ post. 117, cp 119 and SD 5516)

Swedenborg was next led towards the right, where it was told that they were expecting revelations of the unblemished doctrine of heaven, and would also receive a Bible, but a new Bible, from the Lord. They spoke with perception about the Lords revealing Himself in human form even to the sight of the eye. They were in the entrance to Africa. (SD 4775f; LJ post 117; cp TCR 838, et al.)

Prophecy as to how the Heavenly Doctrine would advance in Africa:

It was shown in an obscure vision that it would advance, from the entrance to the interiors of Africa, but not to the middle; then it would bend towards interior Africa nearer to the Mediterranean Sea and thus go on for a long distance but not to the coasts. After a time it would bend back through an interior tract as far as Egypt, also from there to some in Turkish Asia and in Asia round about.

The angels rejoiced that the Lords Advent was now at hand, and that the church now perishing in Europe should be renewed in Africa; and this by the Lord through revelations and not by Christian missionaries. Therefore the heavenly doctrine was not divulged to those near the coasts. (SD 4777, 4783; LJ post. 116, 118; TCR 840. Compare Diagram in SD 5946.) Swedenborg was brought back by another way (SD 4778f)

From those nations at least the heavenly doctrine should be propagated to other spirits from our earth and other planets. (SD 4780; cp 4781; EU 121, 118; AC 9357)

3.{empty} The last judgment on the gentiles, like that on the Mohammedans, was very speedily accomplished, since there were with them few knowledges from the Word to rearrange, but only the need of letting then into their own love and its faith. (LJ 51) Their judgment commenced shortly after the mountain of multitudes in the north-west of the Babylonian tract had been destroyed, and the Mohammedans had been judged. (SD 5263
in context)

[Drawing]

The gentiles were led from the East, (West?) where most of them lived, and brought not in a circuit, but on high above the northern level of the Christians without communicating with them. They were then allotted places around the Mohammedans, at the East and in the South. (SD 5263)

According to LJ post 127 and LJ 51f, those in the western quarter were led away only a short; way in the West and then towards the East, above the Christian middle. Those gentiles who in the world worshiped God under a human form, were conjoined with Christians in heaven. (Compare Luke 13:29, They shall come from east and west...) The most intelligent come from Africa.

Yet in SD 5515f Swedenborg records a visit to good African spirits who dwelt in the far West near the northern angle, and these were visited by a vast number from the college in the middle heaven or Reformed area--a place of Christian instruction (SD 5505)--who had been sent forth to these distant nations. (Cp. LJ post. 119)

During the transfer of the gentiles to their quarters the evil were cast into various gulfs, two of these being openings on both sides of the Mohammedan heavens (LJ post. 127f; SD 5279, 5265ff), the other two stretching obliquely downwards in the West. (LJ 51)

4.{empty} The Africans are the best of the Gentiles, and more interior (TCR
835, 837; CLJ 73; SD 5518-1/2), most intelligent (LJ 51; cp CL 114), have an interior judgment (TCR 837), are most loved (AC 2604; HH 326), are meekest (SD 460). They are of a genius like those of the celestial kingdom. (SD 5518, 4783; LJ post. 118) They are more receptive of the heavenly doctrine than others. (SD 4783; LJ post. 118f; cp. SD 5946)
They think interiorly and receive truths. (SD 5518) They live according to their religion and laws which they love. (SD 5518-1/2) Described, SD
6095.

They easily perceive the doctrine of the Lords body. (SD 5809; LJ post. 129; CLJ 75). They discoursed with Swedenborg on various profound subjects. (TCR 837-839, et al.)

5.{empty} Swedenborgs visit to the Africans. (SD 5946)

Swedenborg was once brought in a southerly direction to Africana of a wise sort, who perceptively knew all that was in his mind, and more.
(SD 5946ff) They could also speak truths. But they were deficient in the knowledge of correspondences (probably because they were not much affected by the Ancient Church), but were delighted to see their value.

The best were at the side towards the Sea, more than half the region, with almost this form:

[Drawing]

SWEDENBORGS DIAGRAM OF THE SPIRITUAL AFRICA

CORRESPONDING FEATURES OF TERRESTRIAL AFRICA

The best of them are in the entire tract (DE), but the worse are towards the Mediterranean Sea (H) and at the Cape of Good Hope (F); so that the kingdoms of the best are DE; but those who are toward DB, that is, towards Asia, are not wise, and are infested by those who come thence, because these speak things which they do not perceive. It is like this almost to C; and those who are still worse are towards A, where Egypt is.

They stated that in the great tract DE all worship the Lord and are taught by many who communicate with the angels of heaven; that the communication is not through speech by the angels, but through an interior perception; and that these are their instructors, whom they perfectly discriminate from all others... (SD 5946, compare LJ post 124) The European and papists are sent away by a road at B and are sold to Asia or become their servants. (Ibid.)

These Africans next received the Word and, reading it, they perceives its holiness and gave it to their instructors who admitted that they already had it. (Ibid.)

NOTE: Compare LJ post. 123: When the Word was presented to African spirits they understood its spiritual sense and carried it to their elders who said that they had the Word with them, and that it is most; holy.

The instructors stated that they dictated (the Word) to the men in Africa with whom they had communication, as the Lord guided: whence it is plain that there is now a revelation-Afterwards, they were also given the work on Heaven and Hell, which they received and preserved; similarly also The Last Judgment, and Earths in the Universe and also the White Horse, lastly, The Doctrine of the New Jerusalem, that they might pick out (eligant) those things which they saw useful.-Tranquility prevails there, because (they were) in order....
(SD 5946)

In other descriptions of this visit, is stated: They said that at this day some speak with Africans in the world and instruct them orally; and that their speech falls especially into their interior perception; and that they perceive the influx, and so receive the revelation with enlightenment; and that such speech is with their instructors, in whom they have confidence. (LJ post. 124)

Such being the character of Africans even in the world, there is today a revelation with them, which, commencing at the center, is communicated around, but does not reach the seas... I have heard the angels rejoicing over their revelation, because, by means of it, a communication is opened for them with the human rational, hitherto closed up by the blindness which has been drawn over the things of faith. It was told me from heaven, that the truths now published is the Doctrine of the New Jerusalem concerning the Lord, Concerning the Word, and in The Doctrine of Life for the New Jerusalem, are orally dictated by angelic spirits to the inhabitants of that country. (CLJ 76)

...There is at this day a revelation made to (the Africans), which, having commenced, goes from its region around, but not yet to the seas... There is hope of the propagation of this new Gospel into certain regions over which Augustine of Hippo presides. (TCR 840)
Compare SD 4777.

A New Church is now being instituted by the Lord ... to which the things published by at the present day will be of service; it is also being instituted elsewhere. (Preface to Historical Parts of the Word, PP)

The angels have small hope of the men of the Christian Church, but much of a nation far distant from the Christian world ... which is such as to be capable of receiving spiritual light and of being made a celestial spiritual man; and they said that at this day interior Divine truths are received ... in life and heart. (LJ 74; cp SD 4770, 4775ff)

The Lord has betaken Himself to the gentiles. (Heading, SD 5807ff) The various kinds of faith which gentiles have is described in SD 5809.

6.{empty} Various gentile nations.

In Abyssinia in the natural world, certain psalms, composed by a pious man, were written in a style similar to that of the Word. The singing of these on earth touched the spirits from that country deeply. (SD
5947; SS 108)

In a certain region of Africa some wise gentiles had from ancient times a Book which is their Word; but it is not like ours. It is written in like manner, by correspondences. It was written through enlightened men. (SD 5809; LJ post. 121)

Spirits from Lesser Tartary who dwelt outside of the Chinese wall, possessed the psalms of David. They were peace-loving, and related to the Chinese. (These may have been from a Jewish or Christian sect in Manchuria). (LJ post 133; SD 6077)

The Ancient Word is still preserved among the peoples who life in Great Tartary. The Chinese emperor is from their country, which is extremely populous. The angels and spirits from Great Tartary appear in the southern quarter, on the East side, and dwell separately from Christians, in a higher expanse. (Expl., TCR 279; AR 11e)

Certain Indo-Chinese are described as of a spiritual celestial genius.
(LJ post. 132; SD 6067)

Certain spirits from isolated islands (somewhere about West Africa)
appeared at first as sphinxes or apes or dogs with human faces because they had known nothing about God. (SD 5822; LJ post. 130; SS 116; cp. SD 393) Others, from the West Indies, who had no religion had lived in civil friendship and were easily instructed. (LJ post. 131)

[Drawing]

Illustrating the appearance of various expanses or levels in the spiritual world immediately preceding the Last Judgment in 1757. The Diagram shows a cross-section of the Middle Space. See SD 5347, 5485, 5781, 5816; AC 7090, etc., and the text of the Notes.

A - The New Jerusalem: those in genuine faith and good of life

B - Central mountain of the pretended Christians

C - Outer mountains of the same

D - Expanse of the Pietists (SD 5377)

E, F - Chasms at the borders of the Protestant region

G - Opening of the Pit of the Profane

H - Inverted mountains in which are the hells (LJ 61)

=== V. THE LAST JUDGMENT ON THE REFORMED

General articles: CLJ 14-21; LJ post. 134-179; SD from n. 5347 on, passim.

1.{empty} The Christian heavens formed after the Lords advent had successively declined.

In the beginning, in heaven, all were picked out who had lived well, thus in the acknowledgment of the Lord and in a good life for the sake of Him and the Divine precepts. But because they were few, and the heavens immense, therefore many others were admitted, and finally all who had lived a moral life. And to these also were given happiness and all things in abundance, so that nothing was lacking. And finally they commenced to admit others from mere piety if only they could simulate pious (behavior), and also such as only appeared in externals as proper or pious although in internals they were most malicious. Angels also were sent to them by the Lord who manifested such things to them; but in vain. Therefore, no such a multitude increased, so their interiors were first opened, and they yielded themselves to them. But all the good (spirits) were taken out thence and hidden in various places. These afterwards composed the new heaven. (SD 5745; cp. LJ post. 169)

In a word, the heavens which were collected after the Lords advent from the Christian world, successively declined, as is the way on earth. At first they procured heaven in themselves, and worshipped the Lord, and thus also had heaven outside of themselves, as is the proper order. But successively the heaven that was in them began to be overshadowed and at length dispersed; and then they wanted to have the heaven which they knew outside or themselves, and this they called heaven, and then there was no more any internal. It was also permitted them to have heaven outside themselves, which consisted in stupendous magnificence, which is ineffable; in palaces, in porticos, in decorations, in paradises, as well as in dignities and like things, and then in the magnificence of many servants, thus in dignity alone, and in external worship of self, on account of these things. At length, when they could not have such things from the Lord, because they regarded themselves and not the Lord from which these things came, they provided them for themselves through phantasies, and arts unknown in the world, which are innumerable. Thus they went on continually. Not that those who were or the first resurrection were such, but those who came afterwards. For as the latter came into heaven the Lord removed the former or concealed, them there so that they, of Divine providence, would not appear. Therefore, when they placed all things in nothing but external splendor and pleasures, then at last came this judgment.... (SD 5749, referring to Rev. 12; cp. LJ post. 169, 141)

By the (first) heaven which passed away (Rev. 21:1) is meant a heaven, formed from all the human race who had lived since the commencement of the Christian Church; but they were in it were not angels, but spirits of various religions. (LJ 2, cp. 66 et seq.; CLJ 18, 19)

2.{empty} State of the ultimate heaven before the Last Judgment.

Evil spirits bad occupied places in heaven. (WE 2382; SD 218, 220, 223, etc.; SD 5070, 5185, 5377, 5532, 5742, 5746, 5749, etc., etc. Reasons why the evil were tolerated there, LJ 69, 70, et al.)

The world of spirits at this day is full of genii and evil spirits, mostly from the Christian world, among whom their reigns nothing but hatreds... Nor is this the case only with the world of spirits ... but also with the interior sphere of that world, where those are who have been interiorly evil as to intentions and ends.... (AC 2121)

At the time of the first advent of the Lord, the hells had grown up to such a height that they filled all the world of spirits ... and thus not only confused the heaven which is called the ultimate or lowest, but also assaulted the middle heaven.... (TCR 121; cp. BE 57; Lord 33; AE 806) The like else at this day.... The difference is that at His first advent the hells had grown to such a degree from the multitude of idolaters, magicians, and falsifiers of the Word; but, at this second advent, from Christians so called, both such as are imbued with naturalism, and also such as have falsified the Word, by confirmations of their fabulous faith concerning three Divine persons from eternity and concerning the passion of the Lord that it was redemption itself...
(TCR 121)

The angels could not have subsisted in a state of integrity unless the Lord had performed a redemption. For the Grand Man ...would have been destroyed, as to the feet and loins, by the church on earth seceding; as to the gastric region, by the seceding of the lowest heaven, as to the breast, by the seceding, or the second heaven; and then the head, having no correspondence with the body, would fall into a swoon. (TCR
119)

3.{empty} The Order or the Judgment.

The Reformed were last to be judged (LJ 47) for various reasons. Inasmuch as they had communication with the heavens through the Word, there was also communication from them with the nations, or gentiles, round about, for light is diffused from the Word. (SD 5948, 5937, 5947:2; CLJ 14; LJ post. 122ff) This caused a delay in their final judgment, and also protracted their judgment for a long time. (SD 5948; LJ 72) It had to be effected by successive changes. (LJ 72)

For summary descriptions of the last judgment on the Reformed, see CLJ
14-31; LJ 72; LJ post. 134-179.

4.{empty} Who were judged?

The last judgment on the Reformed affected all in the spiritual world from this earth. But it was effected only on those who had professed religion and had acted as if from religion but only hypocritically; (LJ
post. 141) or those whose external morality ... gave them the outward appearance of Christians while inwardly they.... The destitute of spiritual life. (CLJ 22, cp. 16) See AE 624:2, 497.

Those who had led a life of charity, which may also be called a life of faith, had all been carried up into heaven long before the universal judgment: and all who in heart denied heaven and led an evil life had been cast by turns into hell as they came from the world. (LJ post. 141) All unbelievers were cast into hell without waiting for the judgment. (CLJ 17)

All the Protestants or Reformed of whom there was still some hope or who had led lives of charity and its faith, were collected in the middle region, where they were arranged according to their kingdoms in the world. Surrounding them are those ... who made seeming heavens for themselves. Thus the judgment was effected not upon those in the center
(meditullio) but upon those who were round about it. (LJ post. 142; CLJ
20, 22, 14) These seeming heavens were occupied by those in externals without true internals, and appeared situated mainly on mountains and rocks on all sides of the middle of the Reformed area. (Confer SD 5347, etc.)

5.{empty} Arrangement of the Reformed before the Judgment into Nations and Quarters.

For the general arrangement of the World of Spirits, see Part I. The general relation of the Reformed area to these of the papists, Moslem, and gentiles, see especially SD 5314, 5395; LJ 118, 58; CLJ 14, 20, 22; LJ post. 2, 126, 127, 178.

When the last judgment was being executed, the Protestants were then led into the middle...(LJ post. 2, 126, 142; LJ 48; CLJ 14, 20; SD
5838f) The nations appear in their quarters according to their genius as regards religion, or according to each nations common faculty for receiving Divine truths. (SD 5395; LJ 48, et al.)

Judgments are effected in the spiritual world by spirits being turned towards the quarters. The heart of a spirit is where he turns himself.
(AC 10396:2; ill. SD 5068, 5742) All turn their eyes to those whom they love. (Expl. AC 10131:4; ill. SD 5761, 5763, 5831) Quarters in the spiritual world are not fixed as in the world, but determined by aspect
(facies). (HH 123) Swedenborg also states that spirits were seen by him in a constant situation relative to his body wherever he turned himself. This appearance testified to their situation in the Grand Man or to their quality. (SD 2334)

Evil spirits are explored by being let into the general state of their life. They then turn themselves to the West; and if they turn to the East they still spring back to face the West like a spring when it recoils. Some turn to the East briefly when they think about heaven.
(Cp. SD 5535-1/2)

The evil are separated in the second state of the world of spirits, by being taken around to the good societies there with which they had any connection. They are led in a wide circuit. Good spirits turn away from them, and the evil turn their faces to their own quarter. (HH 511) When the good are separated from the evil, they are turned to the Lord and thus became invisible to the evil. The evil then do not see the good, but the good can see the evil. (AE 426:4; cp. SD 5252; HD 583)

Note: The order in which all societies were disposed according to nations, seemingly become more perfect and admirable after the Last Judgment. (LJ post. 176. Compare SD 5357; TCR 800f, 807, 816.)

The abrupt and world shattering changes which are described as occurring in the world of spirits, especially during the judgment, do not occur in the heavens or the hells. See LJ post. 12: This in the world of spirits; it is otherwise in heaven, and otherwise in hell.
(Cp. TCR 78)

That spirits appeared to Swedenborg in places and situations fixed relative to his body, was a general rule. (SD 2334, 1699; AC 3639, etc.) But after the Last Judgment had occurred, no such appearances are recorded, except; in HH 332 and in a few passages extracted from the Arcana Coelestia.

6.{empty} Situations of the Reformed Nations.

A.{empty} The English. General art., CLJ 39-47; LJ post. 1-12; TCR 806f.

Situation: A little forward, to the right, higher up, in a plane above the head. (SD 5369) They were led into the middle when the last judgment impended and occupied the center of the Protestant middle space. (LJ post. 1, 2; SD 5369)

Character: The light with them is more interior, and they enjoy freedom of thought. Many of them will receive the heavenly doctrine. (LJ post. 1, 3, 5; SD 5577. Compared with the Dutch, ibid., CLJ 48; SD 5629, 5577, et al.)

London: SD 5712ff., 5092, 5360; LJ post. 268ff 328. Two Londons, CLJ
42f; TCR 809-811; LJ post. 12; SD 5012, 5016. The good Londoners dwell in a London situated on a rock in the Christian middle. It differs as to houses but has similar streets and districts, such as the Exchange, Cheapside, Temple, and East Side. The other London is on the same pattern but is not in the middle of the Christian region but at a distance, to the north, in a plane on the level of the foot, a little to the right. Here the evil dwell, and the city sometimes sinks down in the middle to deliver the worst to hell.

Moravians sometimes pose in London as Anglicans, but mostly they are separated in a society of interior friendship. (LJ post. 282, 280, cp. 294ff) The Jews in London dwell under the earth on the north were Tower hill is. (LJ post. 284)

London in the last judgment, is described in SD 5360, 5712f, 5718.

B.{empty} The Dutch. General articles: CLJ 48ff; TCR 800ff; SD 3500, 5017; LJ post. 13ff., 28.

The situation of the Dutch was towards the East and South, the same both before and after the last judgment. (LJ 48; CLJ 20, 48) It was at the right, in front, in the middle space of the Protestants, chiefly in the plane of the arm. (SD 5367) Their situation is according to quarters, South to East. (SD 5367, 5395; LJ post. 15; and above)

Character: They keep spiritual light conjoined with natural light more than others. Trade is their final love, while money is a subservient one. They hold stubbornly to their religious principle even if convinced that they are wrong. They excel in knowing phantasy from reality. Some are of secretive nature. They have an inherent prudence in concealing their designs. (CLJ 48, 49, 51; TCR 800ff; SD 5826, 5029; LJ post. 13-17, 20; SD 3498 compared with AC 5573, 4630; SD 3498, 3513f, 5358, 5368, 5629, 5826, et al. CP WE 2947. Many become genii. SD
5577)

Dutch cities are guarded, and roofed over to prevent inspections. (CLJ
51; LJ post. 19; SD 5367) Described, CLJ 53; TCR 805; LJ post. 19, 21; SD 5019, 6099:14, Amsterdam, SD 5092.) In the world of spirits there are cities in three levels connected by stairs. (LJ post. 19)

Domineering wives are made to dwell on one side of the city, CLJ 51; TCR 805; SD 4745, 5021; De Conj. 59.

The last judgment on the evil in the Dutch cities began on January 9, 1757. (CLJ 53; SD 5633; LJ post. 18)

C.{empty} The Swedes.

Their situation in general is in the West (LJ 48), in the West and North (CLJ 20), within the middle region. (SD 5395; LJ post. 2)

Character: The Swedes are among the wicked nations. (Why, SD 5042, 5037). They are the worst in Europe except for Italy and Russia. (SD
5037ff, 5043 descr.) They think inwardly in themselves more than others. (SD 5037, 5043f) Dalekarlians are especially bad, being sincere outwardly from hereditary disposition for integrity (SD 5042f.), and the nobility because of their feeling of superiority (SD 5461ff). The Swedes think more interiorly in themselves than others, and can assume an external sincerity to deceive. They harbor hatred against those who do not favor them and have no respect for honesty, etc. (SD 5037, 5043)
In order to be kept in some interior fear of law and reputation they live in cities after death, even if they had been from the country. (SD
5034f.)

Swedish cities: SD 5034-5042, 5052f, 5396. The Swedish cities are many but are all near one another, yet separated as if by walls and by a sense of distance; thus making a metropolis. The civil cities are centered around Stockholm, Falun being to the East, Boras to the North, etc.

The good Swedes are associated in another city resembling Gothenburg, where the best are in the midst. Stockholm does not have a smaller city within it for the upright, as the evil London has on its Eastside. (SD
5036, 5713)

The last judgment caused the evil metropolis of the Swedes to subside in the center, and later they began to rebuild the city, in a new order, with the worst in the center. (SD 5039) The Falun part sank deeper still. (SD 5042) The good associate themselves is towns on the outskirts (SD 5041). The vastation of a part of Stockholm is described in SD 5721. Among districts mentioned in the spiritual Stockholm, are:
Stora Nygatan, Lilla Nygatan, the Apothecary, the Market place, the Bridge, Sodermalm, and Swedenborgs own house. Going through these districts, Swedenborg found hardly any spirits who were spiritually living. (SD 5711, 5721.)

A crowd of Swedish spirits were cast down into a chasm, in the plane of the left foot. (SD 5046) Other judgments are described, SD 5051ff.

D.{empty} The Danes

The situation of the Danes at the last judgment was in the West. (LJ
48; CLJ 20; SD 5395) The character of some is mentioned in SD 579-1/2
as hypocritical, preferring to rule than to work. The ideas of some Danish spirits about marriage are told in CL 111. A visitation on Danes and other Protestants is noted in SD 5396; those who cared little about religion were cast out first.

E.{empty} The Germans. General article: TCR 813ff.

Their situation is towards the North in the region of the Reformed. (LJ
48; SD 5395; LJ post. 2; CLJ 20) Those belonging to the Catholic religion are supposedly not here meant.

Character: TCR 813-815. This noble nation devotes itself little to matters of judgment but much to those of memory and the history of letters, trusting in reputation and learning. (TCR 814f) They keep spiritual things inscribed on their memory and seldom elevate their thought. (SD 5791a) They want to remain in their own doctrines. (SD
5358a) Their freedom of thought is limited. (TCR 814)

Because of Germany being divided into many separate governments, and religion being divided there, the common quality of the Germans was less discernible in the spiritual world. (TCR 813)

Cities: Among the German cities, Hamburg is not represented by a city in the other life. Its inhabitants are scattered among other Germans.
(Why, TCR 816)

F.{empty} The Jews. General articles: CLJ 79ff; TCR 841ff; LJ post. 251ff.

There are many spirits belonging to no special national districts. Among these are the Jews, who dwelt within the Christian world because they had the Old Testament. They lived a little to the left, is a parallel with the sole of the foot and below (SD 5619), thus under the middle space. (LJ post. 251; SD 5421, 5227)

They lived in a valley, at the left side of the middle space, before the last judgment. Two great cities existed in that quarter which they called Jerusalems. (CLJ 79; LJ post. 258; TCR 841) But after the last judgment the name was changed. (Ibid.)

The hell of the avaricious contains, to the left of Gehenna, one Jewish city, miry and fetid, called the filthy Jerusalem. Another city, on the right of the Gehenna and between it and the lake, is inhabited by a better sort of Jews, but the city changes according to their phantasies. A third city is called the Judgment of Gehenna. (AC 94ff; cp. SD 3042, 3409, 3851, 748-754)

The Jews were tolerated under the Christian middle because they had the Word in the Hebrew and this gives communication with some of the heavens. (De Verbo 16; LJ post. 293:2, 254, 261; SD 5619, 5421) Except for this reason, that whole nation would have perished, because it is perverted. (LJ post. 254)

The worst spirits in the ultimate heaven before the judgment were Christians and next tot hem the Jews. (SD 480)

Sometimes an angel known to them as Moses appears to them to rebuke them. (SD 5619; LJ post. 252, 293; CLJ 80; AC 2604) Moses (himself?)
Was later below in his own place among the ancients, in a quiet state. He was serious, and had with him his five books and also the Ancient Word. (SD 6107, Dec. 3, 1764) Swedenborg discoursed with Abraham also, SD 2873. The character of the Jews, see SD 2260f, 2873, 2881f, etc., etc. Few are saved. (AE 119:2; cp. SD 2881f et al. Cp. AC 3479:4, 4847:3; CL 202:2; TCR 103.)

A little before Babylon was destroyed the Jews from the middle space were dispersed and their synagogues destroyed. They now wander about without worship. Many of the evil come into the desert of robbers, and into the northern quarter. Descr., SD 5421, 5619; LJ post. 251.

After the judgment Jews come into certain filthy cities of newcomers, and are explored. Those looking for a Messiah are taken to synagogues for instruction. (CLJ 80; LJ post. 251, 257) They still trade in precious stones. (Why, LJ post. 254f; AE 717:4; CLJ 81) They are unwilling to know that they are in the spiritual world. (CLJ 82, et al.)

G.{empty} The Moravians.

The Moravians or Herrenhuters, followers of Zinzendorf, are at first referred to as similar to the Primitive Church. (SD 3488 heading, 3492)
But before and during the judgment their secret doctrine and practices were disclosed, along with their love of the Lords person which joined them with simple spirits in the ultimate heaven. (SD 4785, 4791-4817, 5886f, 5988-5990, 6017, 6043, 6081, 6102; SD min. 4763ff, 4791-4810; LJ
post. 282-284, 294-304, 45-57, 278-280; CLJ 86-90)

They first appeared in a valley not far from the Jews, but were then explored and conveyed into uninhabited places. (CLJ 86) Their situation was at first to the right in the plane of the sole of the foot. (SD
4791, 4799) later they are reported a little in front, in a like plane.
(SD 5988) Some Moravians appear also overhead. These were cast into the North to form a society remote from the Christian world. (SD 5886f, cp. 6081)

Those who were ignorant or not confirmed in their dogmas were separated. (SD 5989) Their peculiar societies of interior friendship, based on doctrinal brotherhood and conviction that they alone are saved, are described in detail. (SD min. 4763, 4806; LJ post. 366; SD
4795f, et al.)

H.{empty} The Quakers

No society is formed from Quakers in the other life because they have rejected the sacraments, speak from the obsession of enthusiastic spirits, and commingle the Word with profane ideas; nor have they any fixed doctrinals of faith except what the spirits inspire into them.
(CLJ 85; SD 3735)

From the first they have gone from bad to worse, and finally into nefarious things which their founder and William Penn disowned. The early Quakers had ecstatic convulsions but these seized after the first type of enthusiastic spirits were removed from them. (CLJ 84, 83; SD
5767) If Christians knew the quality of their worship the Quakers would be expelled from society. (SD 3765, et seq.)

Quaker spirits wander about alone in the spiritual world and are later collected into a desert where caves are their temple. (CLJ 85, 83)

General articles: CLJ 83ff; SD 3732ff, 3762ff, 3784ff, 3793ff, 6076; LJ
post. 58.

7.{empty} General Arrangement of Spirits in Planes and Levels.

Note: Owing the complexity of the evidence the interpretation here given is only tentative.

A.{empty} The worst among Christian spirits in the other life seek high places and try to establish themselves on rocks and mountains. (SD 5077) Five kinds of such spirits are described. (SD 5070) On a mountain above the central hill in the middle space, and also on the mountains around it, are such as have been external men, without internals. (SD 5347) The central hill, however, is occupied by those in genuine faith and the good of life. These latter thus seem to live on a lower level or a lower earth, and were mostly unaware of the evil. Yet in the angelic view, these good spirits were living on the mountains now occupied by the evil! The evil were actually, or in body, below the good, but by phantasy in the mountains. (See SD 5816)

This reversal of position by phantasy is a mental and spiritual appearance. But every one in the other life, no matter where he appears, is yet in that place where this ruling love is and they who are on the heights are notwithstanding in the lowest place. (SD
5789-1/2)

A great number of cities are situated on the mountains above the earth. And both good and evil spirits appear there. (SD 5485)

In the early Diary this general plane is referred to as the interior heaven, the heaven of spirits, the more interior heaven and the third heaven, where evil spirits lodged. (SD 562, 152, 228:2, 458, 1141, 1177ff, cp. 1330.) Later it is described as a degree within the world of spirits; for the world of spirits is separated from heaven. (SD
1610f; AC 978) It is on the plane of the natural mind. (SD 2157) After the last judgment the ultimate heaven was established in these mountains.

B.{empty} At the foot of these mountains is a general level where spirits live on top of the earth (supra terram, supra diem). At the time of the judgment all the spirits on this ground-level were evil, and were allocated according to the quarters. (SD 5481-5485)

This is seemingly the earth level of the World of Spirits. In the early Diary it is named the heaven of spirits(SD 1141, 1080, 1296). Later this is called the spiritual world (SD 1577). And finally it is permanently referred to as The World of Spirits.

C.{empty} Below this earth, concealed from the two upper levels, is the lower earth, which also contains various levels. Here dwell both good and evil spirits (SD 5485), arranged as it were in strata, so that the good may always rule or control the evil (SD 5781), even as public opinion restrains evil in the world, and as involuntary fibres rule the voluntary fibres in the body. The Form or order there is incomprehensible (SD 5781).

Thus, in the lower earth, good spirits live encompassed by the hells round about, yet; well separated. (AC 7090, 10810:2) In general, they who are there are in falsities about heavenly life, and in a state of vastation and preparation. They are protected against infestors, yet are sometimes reduced to despair and torment in order that corporeal and worldly things may be removed. In the Scriptures, this state is called the Lower earth, the earth of lower things, the pit, Sheol
(AV-hell), captivity, souls under the altar, the grave, the sepulchres, and hades.

Before the last judgment, the lover earth is referred to by Swedenborg as below the feet, in consonance with his custom to describe the situation of spirits in their relation to the human form. Some of the nations are so referred to. (See above, re. English, Dutch, Jews)

With some difference, the cities of the Reformed are represented on this general level of the lower earth before the judgment. Some, however, extended below and above, as in the case of double or triple cities. The evil tend to positions distant from the center.

D.{empty} Above the mountains on which the pretending Christians dwelt in their false heavens, another expanse appeared, inhabited by several kinds of pietists such as had an external holiness. This expanse was invisible to Swedenborg until the judgment was imminent. (SD 5377, cp. 5814ff) Cp. LJ post. 142, below.

E.{empty} When the last judgment came (LJ post. 2, 426) All the Protestants of whom there was still some hope were collected in the middle, arranged according to nationalities and consequent diversities of disposition and affection. In this middle region were those who were in the good of faith and charity. (LJ post. 142) Above them (see C and D, above) and around them were such as had read the Bible and frequented churches but made nothing of evil and who loved self and the world. (Ibid.)
Surrounding the middle space, dark caverns stretched obliquely into hells which extended beneath the heaven of spirits. (Ibid.) The hells of the evil Protestants are open, round about, to the North, West, and South, under the Babylonian district. (SD 5362)

8.{empty} Preliminary Judgments on the Reformed.

Before the last judgment, which was general, many preparatory or less general judgments occurred. (LJ post. 134, 135, 140, descr. 134ff)

Societies who had made semblances or heavens for themselves, were purged and destroyed. Some had been in faith without charity and in the lust of rule, and occupied cities on a rock. The rock sank down as in a vortex but the borders of the hill were left with some who were in charity. Another rock was carried to a distance and then sank. (LJ
post. 135, 137f.) Before such judgments, visitations take place by angels who exert the evil spirits to desist and separate the good. The angels are attacked as at Sodom. (CLJ 26, LJ post. 135, 136) A plain, where cunning spirits used arts to act invisibly from behind others, was overturned and good spirits, formerly concealed beneath the earth, took their place, like the Israelites dispossessing the inhabitants of Canaan. (LJ post. 139) Some of these judgments seem to have preceded the judgment on Babylonia. (See SD 4925ff, 4944) A purification of the Swedish cities is described. (SD 5034-5058) Charles XII declares war on God. (SD 4884, 4873) Fermentations in the Reformed region went on both before and after the last judgment. (SD 5838, 5839)

Signs of the coming judgment. Certain spirits skilled in exciting evils of interior thought conspired a spreading rebellion, wishing to destroy the faithful. A storm cloud or misty sphere then spread over their mountains and rocks, bearing them away. This was due to a Divine sphere in the heavens above them, which laid bare their interiors. The higher heavens were thus brought closer to the seeming heavens. (CLJ 23; LJ
post. 140; AE 401:10.) See Apoc. xii, xiii, xix. 20, xx. 10, re passing of the first heaven. How the approaching advent of the Lord was represented in the heavens, is described in 5 Mem. 16ff.

The order among the evil spirits was inverted into that of a hell while their interiors were being disclosed. The more powerful spirits rushed to the center and assumed dominion while these less powerful in reasonings against religion receded to the sides, acknowledging the ones in the center as their tutor-angels. Earthquakes and signs (such as in Matthew 24, Luke 21, Mark 13) occurred. (CLJ 24, 25)

9.{empty} Beginning of the Last Judgment on the Reformed.

A.{empty} The proper beginning of the last judgment on the Reformed came after the 6th of January 1757, at the same time that the Papists of the eastern quarter were brought down beyond the northern tract. (See SD
5340) (SD 5336, 5348; LJ post. 143; cp. CLJ 53) All who were interiorly evil were led down from every quarter into four main gulfs and chasms which were at the boundary of the middle space with the Babylonian circuit. Those at the south were first led down, then these at the west, lastly those at the east. (SD 5347ff; LJ post. 142, 143)

These were mostly of those outside the cities. (SD 5350, cp. 5714)
Those in love of self and dominion and in faith alone were cast into the eastern gulf; those versed in doctrinals into the southern gulf; those in love of the world into the western gulf; those without understanding into the northern gulf. (LJ post. 142)

B.{empty} Next, immense numbers, both learned and unlearned, who had laughed faith alone and said they should be saved above others, were led to West, South, and even East, divided, scattered to the North, and thus explored. (LJ post. 145; SD 5351) In the South they were joined by a multitude from early times (LJ post. 146; SD 5352)

From the cities, those were led out who had lived morally not from conscience but from fear, and after being explored in the South and West, were rejected. (LJ post. 147; SD 5353)

Those versed in doctrinals, and morals for the sake of reputation, were cast out of the mountain region.

All these were arranged into classes, deprived of doctrine, and scattered in desert places outside of the region of the church, never to return. (LJ post. 146-150; SD 5354ff)

10.{empty} Cleansing of the Cities.

The clearing away of cities and suburbs from the middle space afterwards proceeded. All who had lived irreligiously were cast into deserts or chasms (N, W, S). (SD 5359) In one city one fourth of the spirits, being of dissimilar affection and genius, were given quarters under the city. In London and elsewhere this occurred. The evil enter through a small hill, and some return. (SD 5360)

In the suburbs, especially, are novitiate spirits, both good and wicked, who have arrived from the world within ten or twenty years. These are not judged, but serve men for communication with the heaven or the hells. These are properly in the world of spirits, and serve as subjects, being vastated in the meanwhile. (SD 5361)

On the 9th of January, the Dutch cities suffered their last judgment.
(SD 5366, LJ post. 18) All regard for reputation was removed and the evil rushed into robberies and every wickedness outside of the cities, and were cast into chasms obliquely extending under the eastern and southern tracts. Those with a religious conscience remained. (Ibid., cf. SD 5356; LJ post. 151; CLJ 53)

11.{empty} The Dragon cast down.

Those meant by the Dragon (SD 5370, desc.) Were collected and sent into a southern abyss, where they are bound. (SD 5372, cp. Rev. 12:9, 20:3; LJ post. 161, 162)

A.{empty} The tail of the Dragon consists of literalistic pietists who have no doctrine. These were cast down from heaven to earth at the West toward the North. Some were left to wander in the eastern quarter. (SD 5373ff)
This was represented in actual appearance as a dragon, after the Lord had been seen in a bright cloud with angels and a trumpet sound. (CLJ
28, et al.)

B.{empty} An immense number ofpietists from the still higher expanse (which was invisible) were let down, because angels complained that their thoughts disturbed them. They were led around (N, W, S) and to the level earth and to plains which appeared in gloom, and to distant forests. (SD 5377-5380) See 7 D. Cp. SD 5768.

Other groups of idle pietists, who in heaven had dwelt to one side because they made the angels melancholy, were carried down to the northern plain. (SD 5392ff) Among them were women who had placed salvation in mere piety.

Merely external men from among Germans, Swedes, and Danes were first cast out. (SD 5396)

A multitude from quite a high mountain district had practiced contrition before the Communion but no self exploration of sins. They were otherwise worldly as to life and thought about the Lord as another man. Their mountain sank to the level ground, and the worst were cast into a northern hell. (SD 5396ff)

In the mountain in the western quarter a multitude in self-made heavens, many in the pride of self-intelligence, were leagued with the simple upright in the ultimate heaven; for they sounded sincere to subjugate the simple. They obstructed the Divine influx. They were cast into a hell in front beneath the western tract. (LJ post. 166; SD 5398)

Spirits devoid of real charity were explored as to whether they wished well to the public good and thus to the Lords kingdom. They were scattered, mostly into chasms and deserts. (SD 5399) A vast number who cared nothing for the truths of the Church and led the simple into a slavery of thought were also cast out. (SD 5400)

At the boundary on the West, harlots who infested every one were cast into a marshy lake in the remote West. (SD 5401) Others who had practiced whoredom secretly were led to a pond in the West and cast into a yawning cavern there. Some of the nobility who had secretly been harlots, and others who have been as external as to retain the language used in the world, were cast into a marshy pond in the South. (SD
5402f)

In the meanwhile, a multitude reserved from early Christian times (Rev. 20:4-12) under the Papal tract in the West, were elevated into the place of the false pietists mentioned above. (SD 5389; LJ post. 165)
These were also the souls under the altar of Rev. 6:9.

Jews who had dwelt below the middle space were also dispersed and their synagogues destroyed. See above section 6 F. (SD 5421)

C.{empty} The Dragon means those who justify all people in their evil loves and principles to obtain their good-will, confirming those things by the letter of the Word apart from a desire for doctrine. (SD 5370ff)
They especially cater to the powerful and rich. They are sensual men holding the spiritual sense in aversion. They waver and wander among all heresies, and can become Jews, Socinians, or papists. (SD 5422)

Such gathered beneath the heels, at the left; others in certain other quarters. Most were presbyters (i. e., elders or priests), and appeared representatively like black dragons with tails, But those in the heavens who were in outward sanctity without any affection of truth communicated with these dragons and conspired against the heavenly doctrine. The dragons were exposed and cast far into the SE angle. And the pietists then fell down from the heavens like stars-a Milky Way-(Rev. 12:4) to the surface of the earth. (SD 5423ff)

In their place ascended those in affection of truth who had been reserved by the Lord to this time, in the lower earth. The dragons were tormented by even looking at those who were in the heavenly doctrine. For the latter are the Michael of Rev. 12:7, and the blood of the Lamb is there meant the Divine truth. (SD 5427-1/2ff)

(At this time Swedenborg was conveyed to the abodes of the Russians. See SD 5452ff, and page 27f. Above.)

D.{empty} The profane of both sexes from various religions were collected into one in the NE angle and cast into a very deep pit which opened in the midst of the middle space. (SD 5457ff) In the midst of the West nearly within Babylonia, there appeared a sunken place which stank of putrefied flesh. Here were certain of the profane who had been in sacred worship yet cherished revenge and cruelty. This profane lake was covered over with dust from its southern shore. (SD 5459) The pit of the profane is beneath hell. (AE 1158:8)

E.{empty} A lawless lot of infestors who were cunning in reducing others into their proprium and so leading them, were seen by Swedenborg wandering in the forests and in a desert place in the East.

Those who by phantasies and magic (cp. n. 5463f) led others into these wild districts, were then judged and cast into a deep cavern which opened in the middle space. Some more evasive spirits of like type appeared on a higher place at the end of the forest and were also cast into this cavern. (SD 5465) Other spirits, still craftier, dwelt under the earth in a long row, right in the extension of the SW angle. See Diagram, SD 5466.

[Drawing] QUARTERS BELOW THE EARTH

SWEDENBORGS DIAGRAM AND INTERPRETATION
Spir. Diary 5471

All states are concentrated around the New Jerusalem SD 5471 See opposite page for key.

KEY to the DIAGRAM on the opposite page, from descriptions in SD 5471
to 5491

A - The New Jerusalem (SD 5471)

ab - Extension of South East angle

op - Extension of North East angle

mn - Extension of North West angle

gh - Extension of South West angle

c - Long chasm for male adulterers

d - Chasm for harlots

cd - The bottomless abyss of the Dragon (Rev. 20:3)

ef - Great plain of spiritual whoredom and unsettled faith

i - Abyss for those who knew of God

k - Abyss for male procurers (SE 5466)

ik - Gloomy chasms (SD 5467)

l - Sulphurous lake of the harlots

mn - Location of chasms for gross spirits, once clever, now idiotic. The front one is for men, the one behind for women

O - Lake of female sirens (SD 5487)

- Shaft in mountain, for female liars (SD 5476)

P - Underground site of male sirens (SD 5477f)

Q - Mountain of the sirens (SD 5487)

q - Hell of female liars, etc. (SD 5476)

r - Dark chasm in plain, for male deceivers, etc. (SD 5477f)

x - Smoky chasm for clergy who adulterated the Word

z - Mountains in the East (SD 5473)

After visitation and judgment, these spirits were cast into hells located crosswise over the extension line. Sec Diagram, explained in 5467f.

The spirits who incited these spirits were then sought out and found on a mountain above the middle space toward the West, and thus in knowledges of religion. They stole men and women into adulteries, and led them into a cavern in the West not far from the middle. The inciting spirits were now assigned to bells in the South West, and later to others. (SD 5466, 5469f)

12.{empty} General Situation of the Evil in the outskirts of the Middle Space.

To clarify the groupings of the evil, Swedenborg gives certain sketchy diagrams of various levels at various periods.

A.{empty} Quarters below the earth.

This grouping is described in detailed treatments, SD 5466-5469, 5471-5479, 5487-5431. The center of reference is the truly Christian middle, here identified with an incipient New Jerusalem, four square
(SD 5471) All things in the other life must be considered in relation to such a site! (Ibid.) See Diagram on opposite sheet.

The evil were brought down from mountains everywhere to their various hells below the level called below the earth and outside the middle space.

A broad plain below the ground with caves at the side (near e f) at the SE angle became the precarious abode of those, priests or laity, who had not any settled faith, having only cared fro the literal sense. They are not badly off since they have not lived very evilly. But their states and houses are impermanent. Those cast out thither do not go out any more. (SD 5474)

When the evil spirits had been cast into their hells, the good spirits, concealed by the Lord in the lower earth, were released and raised up from the western region towards the South. (SD 5480, cp. 5427-1/2)

B.{empty} Dwellings according to Quarters above the earth (supra diem)

Spirits in this level are uniformly evil, while those who are in the mountains and rocks above the earth, and those below the earth at various levels, are differently from the former, both good and evil.
(SD 5485)

In the western quarter, towards the South, dwell the cunning, and wicked. In the northern, towards the West there, are the dull and towards the East there, those who ingratiated themselves to seduce and lead others. In the eastern, quarter, to the North, are liars who are in no religion, and to the South those who are not in say doctrine, but vacillate in belief and incline to domineer. In the southern quarter, towards the East are those who are in high offices but know nothing for certain, and to the West, some who are crafty through affections, like sirens. (SD 5481-5484)

[Drawing]

QUARTERS ABOVE THE EARTH

SD 5481 et seq. Liars who cunningly deceive and seduce Spirits who vacillate and have no doctrine. Some domineer. Those in high employment: Domineering spirits with no settled faith.

SOUTH
Sirens and others who use affections with craftiness Cunning and wicked spirits wanting to lead others towards the North Cunning spirits who ingratiate themselves and so lead others

NORTH
Dull spirits without talent for injuring or deceiving.

[Drawing]

QUARTERS BELOW THE EARTH
SD 5467f Swedenborgs Diagram (turned) with Interpretation d e - Extension of the angle between West and South a e - Sulphurous pond for harlots b - Abyss for male adulterers c - Lascivious spirits who knew about the Divine

C.{empty} Releases from the Lower Earth.

The states of those in the lower earths are described in SD 1771; AC
699, 4728, 4943-4948, 5392, 6854:2, 6928, 7090; AR 325, 845; AE 899:2; CL 231ff; etc. (They are in states of vastation and arrested development, held back by natural delights or worldly loves, and from the result of evils of imprudence. Yet they have led good moral lives from something of charity and, although sometimes infested, are protected, and sometimes instructed by angels. They live cheerfully together there, and worship the Lord; nor do they know anything about hell, although there are hells around them. They are subject to phantasies and are in various falsities.)

In the West, toward the South, had been reserved great numbers who in childhood had been instructed in doctrinals with a pride of reputation but later put off their pride. These were concealed and removed from the contagion of evil and initiated in spiritual life. After the last judgment they were brought up and led into the mountains of the East.
(SD 5480, cp. 5427-1/2)

Swedenborg then witnessed the release of Catholic spirits from their lower earths in the West, and mountains that Protestant teachers established a school or college to teach them. (SD 5503-5505, 5515), and to provide teachers to nations far away, who proved to be Africans
(SD 5516; LJ post. 119).

13.{empty} Separation of the good from evil.

A general separation of the evil from the middle space continued. (SD
5532-5535) The evil were sent out mostly towards the West where they wander in deserts or dwell in huts under severe magistrates. Spiritual adulterers are sent into deserts (cp. SD 5475), but actual adulterers are sent into hells. (SD 5538f)

Some who accepted the Heavenly Doctrine theoretically, but with sadness that it was meant to be lived, were cast out of heaven into lower places towards the North where there was but slight communication with heaven. Crowds of Lutherans, etc., had lived ill and were cast into hells at the North East. The body and head of the Dragon were those who had confirmed themselves in opposition to the heavenly doctrine. These induce a nausea against the affection of truth. (SD 5540-5542-1/2)

For a whole night spirits let down out of heaven were separated and arranged into order. The evil were cast into deserts and hells. The good found mansions according to the degree of their good. (SD 5543f)

East - Those in clearness of good

South - Those in clearness of truth

West - Those in obscure good

North - Those in obscure truth

The best are in the middle.

But vastations by which the good are liberated from gross externals and corporal pleasures so that they can be elevated to heaven, may last form one to fifty years. (SD 5693f)

On March 30, 1757, spirits who were in light as to spiritual things, but not in any celestial heat or charity, were judged. The mountains which they had occupied, partly in the middle, partly in the western quarter, now swallowed them up, and they and their subjects, now rendered powerless, were cast into various hells, some on plains, others in mountains. (SD 5696-5699)

14.{empty} Final judgment on the Solifidians.

Swedenborg by interior sight looked into certain streets of Stockholm-Stora Nygatan and Lilla Nygatan-and saw many walking about. But afterwards he was led through by angels who shuddered because all in the surrounding houses were spiritually dead, with few exceptions. Only dark holes appeared for windows. Other quarters in the city were also examined. (SD 5711) Swedenborg witnessed the vastation of a part of Stockholm, the left side of Nygatan and parts of the South side of the city nearly up to his own house being entirely destroyed. (SD 5721)
See above; SD 5034-5042, 5052f, 5396.

In the London which is above (quod supra) there is a little city on the East side wherein the upright dwell. The vile appear to the West and the seized by agony if they intrude. Swedenborg also visited the districts of the Exchange, Cheapside, and Temple, but few there were living. The West part of London was destroyed. (SD 5712f, 5715, 5718)
See also SD 5092, 5360, 5012, 5016; LJ post. 12, 268ff, 328; CLJ 42f; TCR 809-811.

The main judgments on the Dragonists are then described. Certain Solifidian robber priests, Erik Benzelius, Sr., among them, were cast into their lake at the South East. (SD 5722f, 5828f) later the Solifidian abyss there was extended or removed far into the South. (SD
5751; Docu. 245 V., p. 370, dated in 1770)

The head of the Dragon is made up of those who believe the Word as to the letter only and are in the loves of self and the world, the Word serving them as a means to honor only. The tail is constituted of those to whom the Word only serves for preaching, not for life. (SD
5722-1/2f; CLJ 28e)

Note: At this point the judgment on the Moguls is related.

In the meanwhile, Solifidians gathered by the myriads into a rebellion to destroy the heavenly doctrine. They acted not from zeal for their doctrine but from a delight of evil and dominion. They came in groups of ten to fifty from all quarters except the East, but were discovered and hurled down into hells. Certain of the leaders became black as devils. These he-goats had led an eternal moral life in the mountains.
(SD 5731-1/2-5736, cp. 5758; LJ post. 167)

After many days a hand appeared extended by the Lord over the heavens, and the combat of Michael and the Dragon began in earnest! (Rev. 12; SD
5742-5750; cp. LJ post. 168) In the western quarter towards the North, there appeared a large back of a dragon, raised above the middle space towards heaven.

The dragonists then we spoke their real thoughts concerning the Lord and faith alone, and all turned towards them to hear what they would say. The angels answered them, but in vain. This explanation proceeded through and the heaven which had been gathered since the Lords advent, and the dragonists were sentenced to leave every place they had occupied. The refused, claiming prior rights. (SD 5742; LJ post. 168)
Swedenborg felt this collision of truth and falsity as a grievous temptation. For all the heavens collected since the Advent were thrown into a state of temptation even to despair-the Lord holding them in truth, the devil in falsity. (SD 5742f; LJ post. 168)

Then the Lord was seen to descend out of the Sun in a bright cloud to the heights, gathering the good by a sound of a trumpet. He gave judgment and with drew into the Sun, after which the Solifidians were separated and alienated, and by turns were cast down. (Ibid., CLJ 28)

The whole western quarter fro North to South, was filled with these evil spirits, but the earth opened itself and a cloud covered them so that they could not rise up any more. From South to West the dragonists had been seen in a curved line a dragons tail. (LJ post. 168e; SD 5744, 5748; CLJ 28)

Thus perished the old (vatus) heaven and the old earth; and all those were cast into hell who had not lived the life of faith which is charity. They are also called the he-goats who were on the left hand, who none of them gave anything from internal charity but only for external reasons. These things continued from the 31st of March even to the 11th of April, when the feast of the Passover fell, in 1757. (SD
5746; cp. LJ post. 168e; cp. SD 5762)

Note: Those called Michael were those who fought for the Lords Divinity and the life of charity. These were chiefly from the ancient heavens who all remained steadfast, and from those who were among these from the gentiles, and from infants everywhere, then adults. (SD 5747; cp. AR 548 and AE 735, expounding Rev. 12, and AE 564)

A general review of the progress on judgment seems to be given in SD
5758-5769, 5786-5792-1/2, and other places in which reflections of the past events are not easily distinguished from the current experiences by Swedenborg. See SD 5812-5821, 5831, etc.

15.{empty} Continuation of the Judgment on the Reformed.

The climax of the last judgment on the Protestants was evidently reached on April 11, 1757 But for a long time, et per annum tempus Swedenborg was shown how all the Reformed were purified according to their nations. This was done by fermentations, through the presence of the evil. When these went outside of their societies they came into the freedom of their interiors, and attached themselves to evil spirits beneath. Such, while in societies were bound to the evil spirits below and visited the society until driven out. (Explained, SD 5838)

Numerous spirits who loved ease more than use and collected evils in their spirits were sometimes premised to move up to the place of former heavens. They were skilled into looking into the heads of those below them, but were afterwards sought out and arranged by the Lord and compelled to walk the path to their society without deviating whenever departed from his road was sent to his hell. Such purifications went on for a long time among the Reformed. (SD 5839; LJ post. 176f)

Such purifications of long duration affected (1) those who utterly despised erudition and knowledge; (2) those who feel delight in the sufferings of others or inject despair and wariness of life; (3) those who wish to enlarge their dominion; (4) those who looked down, caring for only worldly things, and were therefore sent down to the plains or lower parts where were their eyes and minds, and if evil, to hell. (SD
5759-5761) Spirits who did not look down, but had solicitude only for their own homes, and trusted in the Lord, were not brought down. (SD
5765-1/2, 5761, 5831) (5) Pietists, on a high rock in the middle, invisible to the rest, had lived in piety without charity. Some were in falsities about merit, etc.; another kind despised others for lack of similar piety and wanted to rule, claiming that they were angels because they lived on high. (Cp. SD 5789ff) They inflicted sadness on the angels. (SD 5764, 5767) These were also brought down in the course of the purifications.

Other types of spirits had elevated themselves on high to exercise rule, and appeared there by means of phantasy, although they were not there in the body, but beneath, on the ground level. They wore hidden in the cloud of their own phantasy. In the sight of the angels some were in the hells, deep below. (SD 5816 cp. 5789-1/2, 5968) They were usually hypocrites. (SD 5791) many of these spirits are from Germany, Sweden, Denmark, etc., but few from England, where they care for their own household and business affairs. (SD 5791-1/2)

Some of those who are cast down are social pests who hunt for enjoyments and visit others so that they disturb the uses and peace of homes. (Descr. SD 5791-1/4-5792-1/5)

How the evil spirits ascend the mountains and how they are cast out, in described in SD 5786-5792-1/4, 5966-5969.

Certain foolish spirits who had been in external devotions and emotional religion, but not in any affection of truth were cast down from the mountains and told that they might serve for ultimates in the Lords kingdom, corresponding to the heels of the foot. (SD 5814) Since they had trusted in authoritarian leaders, they were allotted a region under the earth because they had before served as a fulcrum tot he infernal crew. They were concealed under the earth so that those of them who do anything from the heart could serve for the ultimates of heaven. These were content to dwell with the good and find joy in devotions. (SD 5815)

Those who were joined with devils and came up on the mountains and displaced the good there (descr.) Are called those of the second resurrection. (SD 5203, 5761, 5763; LJ 59:4)

Note: This evidently is used as a contrast to those of the first resurrection (Rev. 20:6) See translators note on SD 5761.

Those who lived not on the rocks but scattered below, yet in similar evils, fled amazed to papists, Mohammedans or pagans and adopted their religions; but they were eventually driven to the hells of their former confederates. (CLJ 29)

Among those who ascend the mountains there are also good spirits looking for heaven. (SD 5820; cp. 5889)

Those who remain on the mountains after judgment are collected into a one and appear as one Man, because in charity. (SD 5760) This assumption of the human form is one means of purification. (LJ post. 176) Other means by which societies are purified are recounted in SD
6020.

The arranging of the Reformed after the judgment lasted a lone time, for the reason that the Lord is with them and the Lord is known, and they are therefore in the middle; and the greatest light is there, which passes from that middle to the peripheries where the gentiles are... (LJ post. 178; SD 5948, 5937; descr. LJ 72)

16.{empty} Disposal of Societies after the Last Judgment.

After the judgment, all societies were disposed according to nations, in an admirable order ... according to affections in the heavens and according to cupidities in the hells.... After the judgment it is not permitted to thus ascend into heaven and be cast down thence, but each one is determined in such direction that he may go the way that leads to his society. (LJ post. 176, descr. 177) Afterwards, societies were formed most distinctly according to all the genera and species of the affections of good and truth; and else corresponding infernal societies.

After the last judgment many of the he-goats and dragons were seen scattered in the West, and in various places. They were then collected into one; and since their consultation inflamed them to evil, they were, forced to the boundaries of the Christian world, behind which are rocky deserts, where they dwell solitary with some harlot and are given mostly breed and water. (LJ post. 219, 182)

=== VI. THE STATE AFTER THE LAST JUDGMENT

Note: See also above, pages 22f (re Catholics), 33f (re Moslems), 37-39
(re Africans), and 59 (re Reformed)

1.{empty} Formation of the New Heaven

A.{empty} Constitution of the Hew Heaven. See our Notes on The Heavens, pages 34 to 36, for references.

New heavens were formed from those of all religions after the last judgment had cleared away the seeming heavens. The New Heaven was formed only from those who had died since the Lords time, but consisted of both Christians and gentiles as well as of all the infants who had died as such. It is distinct from the ancient heavens and forms an expanse below them.

In a general sense the entire New Heaven is a New Christian Heaven, since it contains only those born since the time of the Lord, whether Christian or gentile (HD 2) and is based on faith in the Lords Divine Human and on the knowledge of His advent.

The infants of Christians are introduced into the Christian heaven by means of their baptism. But infants and children born out of the Christian Church are introduced by other means than by baptism into the heaven designated for their religion, after reception of faith in the Lord; but they are not mixed with those who are in the Christian heaven. (TCR 729)

That among the new heavens there are specific societies called the Christian Heaven, which serve as the heart and lungs to the entire Heaven, is evident from AR 876: A New Heaven was formed from Christians
... in which heaven also are all the infants of Christians. (Rev. 21:1; cp AR 486) It is from this New Christian Heaven that the New Church on earth is to come down. (Cp. AR 546f, etc.) The doctrine of this New Christian Heaven is now revealed to men in the True Christian Religion containing the Universal Theology of the New Heaven and the New Church.
(Title above TCR 1)

See Notes on The Heavens, pp. 34ff.

The New Heaven is distinguished into three heavens. (AR 876:2; Coro. 16, 17). Similarly the new hells.

B.{empty} The gradual formation of the New Heaven began some time before the last judgment. (AR 878)

Before this, the good spirits who had been separated from those on the mountains had been kept in concealment and protected by the Lord in many different places, in order not to be seduced. (SD 5762f, cp. 5480
descr. 5503-5505) Among these were also all who had died as children and had been educated in the other life. These there form a new heaven and a new earth. (SD 5763)

Note: The places in which good spirits are concealed are various, and their real presence may be in some heaven while their seeming situation is in the lower earth. (cp SD 5816) Otter good spirits are preserved in heaven and may never have lingered in a lower earth. (SD 5819)

The elevation of multitudes of good spirits from the lower earths took place first from the Babylonish tract as soon as its judgment had come.
(SD 5393) From the Protestant tract the release of spirits from the lower earth was slower and of longer duration. The judgment went on from the beginning of the year 1757; and the elevation of the good to constitute the new heaven, took place from the end of the month of April into the month of May. (SD 5762; cp TCR 115)

Those who had taken delight in uses and reserved by the Lord were those of whom is the New Jerusalem. (SD 5792-1/4)

C.{empty} The completion of the New Heaven was not immediate.

The internal heaven of Christians was not fully formed by the Lord till a little before the last judgment and also after it... because it would have been hazardous. (AR 878) Those who had been taken up into heaven before the last judgment are meant by the 144,000 who were sealed and by those of the first resurrection. (AE 430:17; Rev. 7:4, 14:1-4; 20:4-6.)

The New Heaven is not formed immediately, but is waiting for sufficient numbers. (AE 397)

The New Church will grow slowly. One reason for this is that a New Heaven must first be formed. (AR 547:2) The New Church on earth grows according to its increase in the world of spirits.... Only those spirits receive the doctrine who have been in a spiritual affection of truth... The number of these in the spiritual world now increases daily.... (AE 732:3; cp SD 5749f, 5882; AE 670)

The New Heaven of Christians out of which the New Jerusalem, will descend from the Lord (Rev. 21:1, 2) is not yet fully established...
(Docu. 230, dated Sept, 25, 1766)

The Lord is at this time preparing a New Heaven of those who believe in Him, acknowledge Him as the true God of heaven and earth, and look to Him in their lives, which means to shun evil and do good; for from that heaven the New Jerusalem is to come down (see Rev. 21:2.). I daily see spirits and angels, from ten to twenty thousand, descending and ascending and being set in order. By degrees, as that heaven is being formed, the New Church likewise begins and increases. The universities in Christendom are now first being instructed, whence will come new ministers; for the new heaven has no influence over the old (clergy)
who deem themselves, too learned in the doctrine of justification by faith alone, (Docu. 234, II., dated Stockholm, February 1767.)

The spheres of spiritual truths are as yet few, being only in the new heavens. (TCR 619:6, written in 1770)

The New Heaven will very soon be completed. (Docu. 245BB, dated April 30, 1771.)

2.{empty} State of the World of Spirits after the Last Judgment.

General articles: SD 5871-5876; LJ post. 176-179; LJ 73f; CLJ 8-13.

Even after the judgment, lower earths are formed, and also heavens of the joys of the imagination, for the sake of protection and vastation. There are also constant attempts of cast-down spirits to ascend back into former heavens, but these are foiled in the ascent. (SD
5966-5969). There are also new heavens which perish. (SD 6012.)

The normal processes of judgment obtain in the world of spirits since the judgment. (See LJ post, 176-17, et al.; SD 6020, 6022, 6103.)

The equilibrium between heaven and hell, which wee on the point of perishing, is now restored, (LJ 33, 34; Canons Redn., ii, v.; cp HH 589
art., 593; SD 2466, 3528, 4285, 6006, etc.)

After the judgment the state of the spiritual world has been completely changed.... Every one is now borne to heaven or hell according to his life. (AE 754:3) Even the angels will have a renovation of state. (AE
911:6; Coro. 19e; cp SD 5610)

After the last judgment was accomplished there was then joy in heaven and also light in the world of spirits such as there was not before ... because infernal societies had been interposed like clouds which darken the earth. A similar light also then arose with men in the world, from which there is a new enlightenment with them. (CLJ 30; AE 351:2, 1179)
Spiritual light does not pass through spaces but through the affections and perceptions of truth... (CLJ 14)

After the last judgment and not sooner, revelations were made for the New Church. (CLJ 12, 11; Cp Coro. 20, 12; AE 260, 670, 955-957, 974, 1217, 1094; BE 94; AR 804; TCR 102; LJ post. 134; Lord 65; DP 264)

The communication between heaven and the world, or between the Lord and the Church, has been restored. (CLJ 11) The state of the world and the church is hence like morning after night. (CLJ 13)

The prayers of Solifidians and of those who do not go immediately to the Lord alone, are no longer heard. (AE 277:9; TCR 108)

By the new revelation, which takes place in both worlds, a New Church is established and a separation takes place between the good and the evil. (Cp AE 641:3)

3.{empty} The State of the world and of the Church hereafter.

The state of the world will be altogether similar as to external form, with peace, wars, treaties, and social and civil affairs. The state of the church will be similar as to external appearance, with divided churches, different doctrines and the same gentile religions. But as to internals, the man of the church will be in a more free state of thinking on matters of faith, thus on spiritual things. (Expl., LJ 73)
Man is led, in a freer and more spontaneous spirit, to discard falsities and to receive truths. (Coro. 20)

The angels do not know the future, but know that the man of the church can now, from restored freedom, better perceive interior truths if he wills to perceive them.... (LJ 74; cp Coro. 20) But they have slender hope of the men of the Christian world, but much of some nation far distant from the Christian world... and they say that at this day interior truths are revealed in that nation.... (LJ 74; compare page 39
above, and AC 9407:7, 9256:5, 2910e, 2986, 3898:3)

Indications as to when the New Church could be expected, are discussed by Swedenborg in Docu. 234, 230, 240, 245.

On being asked fur a sign of his Divine call, Swedenborg, wrote to Oetinger, Nov, 11, 1766: The sign given at this day will be enlightenment, and thence an acknowledgment and a reception of the truths of the New Church; with some also there will be an illustratio loquens, which is more than a sign, But some sign will perhaps still be given (Docu. 232 in P. T. W. vol. i, p. 571)

I am certain of this: that after the appearance of (the Universal Theology of the New Heaven and the New Church) the Lord our Savior will labor both mediately and immediately towards the establishment throughout the whole of Christendom of a New Church based upon this Theology. The New Heaven, out of which the New Jerusalem will descend, will very soon be completed. (Docu. 245BB, April 30, 1771.)

The Lord derives and produces the New Church on earth by means of a revelation of truths from His mouth, or from His Word, and by inspiration.... (Coro. 18, 20)

This New Church, truly Christian,... will endure to eternity. It was foreseen from the creation of the world, and will be the crown of the four antecedent churches.... (Coro. lii)

APPENDIX: CITIES IN THE SPIRITUAL WORLD

1.{empty} The existence of cities in the spiritual world does not fall into sensual ideas, but only into rational ideas enlightened by spiritual light.... For the spiritual appears before a spirit as the material does before a man. All the things which exist in the spiritual world are from a spiritual origin,... in like manner the houses of a city, which are not built as in the world, but rise up in a moment created by the Lord.... (LJ post. 12)

The abodes of the angels are altogether like houses on earth, and where many live together the houses are arranged in the form of cities.
(Descr., HH 184f, et al.; AC 1626ff)

Cities correspond to the doctrinal things of the church, and to the interiors of man where truths are conjoined with good. (AC 5297; HD 1, references)

The angels are completely ignorant what a city is, and can never have any idea of a city but only perceive what it signifies when mentioned in the Word. (AC 402)

When angels converse about doctrinal things, there sometimes appears in the lower sphere, where there is a corresponding society of spirits, the idea of a city... (AC 3216)

Each city and mountain in the spiritual world corresponds with some part of the human body. (SD 5058)

2.{empty} Cities appear in the other life, because spirits used to live in cities in the natural world; because they associate with the men of the same earthly cities and possess the interiors of men and thus their entire memory. (Expl., SD 5092, 5716; LJ post. 12.)

The cities in the other life are not similar so to the houses, but as to certain of the streets and districts. (LJ post. 12; SD 5711 et seq.)
See above as in Stockholm and London, pages 44 to 46.

After the last judgment, the societies in the spiritual world are disposed according to nations, in an admirable order--in the heavens according to affections, in the hells according to cupidities. (LJ
post. 176)

The correspondence of the cities there to the material cities is close and material, according to the ideas of the thoughts of men in the world. But now, in this last time of the church, another arrangement takes place, and another correspondence: thus through correspondences not so direct and close, but more remote. (SD 5716)

3.{empty} The good and the evil do not dwell promiscuously. (LJ post. 12) In good cities the best are in the center, (SD 4987, 5057, LJ post. 200)
In evil cities, the worst are in the center, (SD 4986, 5039) Those in evils are at the right, those in falsity at the left, etc, (SD 4986f)

In the cities law always reigns. (SD 5714) While in the city, the evil can live morally, but not when removed from the city. (SD 4930) Spirits therefore do not dare to go outside of these cities for fear of robbers. (SD 5714, 5711) Sometimes robbers from the environs are admitted into the streets of a city; but not into the houses, unless the inmates are no longer able to remain, They have no power in the streets. (SD 5714)

Only those in the same state appear together in a city. When states are changed the houses as well as the spirits disappear. (SD 5252, 5531)

Those who have come into the spiritual world within the last ten or twenty years, and are of service to men, are usually in the regions outside of the cities, although sometimes within them. These serve as subjects, and are in the meantime in process of vastation. (SD 5361)

4.{empty} Cities are first formed by the good, on rocks and mountains, but are later usurped by the evil. (SD 4930) These usurpers learn a forbidden language of natural ideas, and abuse correspondences. (SD 4931)

For references to the cities of the Babylonian tract, see above, pages 10 to 25. Cities of the Reformed and of the Jews are referred to on pages 44 to 47. Jewish cities in hell are described in AC 940ff, and certain cities reading for judgment, in SD 4925 to 4932. Cities of phantasy are described in SD 843ff. (Note SD 851 especially.)

The cities in the World of Spirits which underwent judgment are variously described. These cities were sometimes double of triple (LJ
post, 12, 19), one city beneath another. (SD 5249-5251) In the lower or subterranean city dwelt sometimes those from ancient times who are there more secure from change. (SD 5249, 5255) The lower city was often connected with the higher by shafts or winding stairs. (LJ post. 19; SD
5782 et al.)

Just as cities are often double, so also are mountains. Most mountains are double, higher and lower, one within the other. If the good are in the middle, the evil are at the sides; and vice versa. Those on the upper mountain govern and excite those on the lower. (SD 5454ff)

When the evil are cast out from a mountain and its city, the mountain is sometimes seen to be inhabited by good spirits and angels, who actually belonged there although they were not seen there while the evil occupied it. The good are concealed by the Lord from the sight of evil. (SD 5185)

5.{empty} Cities in course of purification or judgment are changed or laid waste in various ways, mostly described in LJ 61.

a. Subsidence. (SD 4944f, 5057: ill. SD 5089, 5042, 5053)

b. Translation or transference in a circuit, as if it were a cloud, and then subsidence. (SD 4945, 4977, 5202f.)

c. Mountain tops carried away to expose subterranean cities below. (SD
5296, etc.)

d. Earthquakes, causing spirits to flee in panic. (SD 5655, 5294, 5306, 5651; LJ 61; CLJ 25; AE 499, Expl.)

e. Place dried up by an East wind, gardens perish, garments change, houses blow away like smoke, etc. (SD 5296, 5078, etc.)

f. A city may suddenly fall down into the hells where the spirits actually were dwelling. (SD 5077)

g. A flood may inundate the region. (SD 5298; LJ 61; CLJ 29)

h. Conflagrations may destroy the city, as Sodom, etc. (LJ 61; cp. HH
586, etc.)

i. The evil may be exiled. (Ill. SD 5274ff) and scattered (SD 5066, 5185e), while the upright remain. (SD 5073)

6.{empty} In the spiritual world certain cities are called New Jerusalem or Jerusalemite cities. (AR 655:4; TCR 483:4) The New Jerusalem appeared as a square city in the center of the middle space. (SD 5471, cp. 5543, 5577, 5792e)

Among heavenly cities visited by Swedenborg are the Eagle Society (CL
11ff), Athens (CL 156a and 207), a tent-city of the Golden Age (CL 75), a city of the Silver Age (CL 76), and one from the Copper Age (CL 77).
