#!/bin/bash

## this process is far from perfect;
## several different circumstances, or combinations thereof, can cause peculiar results
## this is inherent in the taking one specific search string, and applying it to the entire target file,
## without bothering to attempt locating the appropriate single target string --- 
## The primary problem however is likely the short strings in the '/tmp/italics' file
## and secondarily it is likely when an _italicized string_ crosses a linebreak
## search italicized file for 'doubled' underbars.

fromfile=./fromfile
#tofile='../../Joshua-Millar/07-Following\ The\ Ark\ Of\ The\ Covenant\ \(3\:1-5\).adoc'
#tofile="$(realpath "$tofile")"
tofile=$(realpath "./tofile")


[[ -f "$fromfile" ]] || (echo "error! file not found: $fromfile"; exit)
[[ -f "$tofile" ]] || (echo "error! file not found: $tofile"; exit)


#grep -P '[ \"\n(]?_[^_]+_[ \"\n;.,)]?' "$fromfile" |sed '1d' >/tmp/italics
# below accommodation for italicization across line breaks; by grep (two_)|(one_)
grep -P '([ \"\n(]?_[^_]+_[ \"\n;.,)]?)|(^[^_]*_[^_]*$)' "$fromfile" |sed '1d' >/tmp/italics

lines=$(wc -l /tmp/italics); echo "$lines lines"

seq 1 ${lines% *} |
	while read line
		do istr=$(sed -n ''"$line"'p' /tmp/italics)	#; echo "istr: $istr"
			fstr=$(echo $istr |tr -d "_")	#; echo "fstr: $fstr"
			sed -i 's/'"$fstr"'/'"$istr"'/' "$tofile" || echo "Sed Fail at line:$line"
#echo 
	done

exit

