
== NEW CHURCH DAY — Revelation 21:1-10

=== Introduction

(@TCR 791, 846-847)

This lesson is an additional special lesson to be used following the regular season, on June 19, or the nearest Sunday to that date. It is based on Swedenborg's statement in @TCR 791 that "after this work [the book @TCR ] was completed, the Lord called together His twelve disciples who followed Him in the world; and the next day He sent them all forth throughout the whole spiritual world to preach the Gospel that the Lord God Jesus Christ reigns ... This took place on the nineteenth of June, 1770 ... "

=== Primary

Tell the children that when the Lord had finished revealing the teachings for a New Church, He sent His disciples all over heaven to tell this good news. Stress the term, "New Church Day." Look in some detail at the event described in @TCR 791. Then follow the notes as a guide.

You know what fun it is to have something brand—new — a new dress or pair of shoes, or a new toy. It is even more fun when it is a surprise. You are delighted and jump for joy. Remember on your last birthday when you got some nice new things? You probably received something that you had never had before, something that was brand—new.

Have you ever wondered why you like new things? It is partly because you can always learn something from them. They may help you discover something that you didn't know anything about before. When you first learned how to ride a tricycle you discovered a new thing — it made it possible for you to go faster and more easily to more places. You learned to do something new.

This week is the birthday of something new in the world, something that the Lord has given to be enjoyed by everyone in the whole world. But not only enjoyed. It is intended to help us all learn things we never knew before and do good things that the Lord wants us to know how to do. What is this new thing? We call it the New Church. And June 19 is called New Church Day, for that was the day long ago when the Lord sent His disciples out to tell everyone in heaven the good news that the teachings of His New Church had been made known to men on earth.

When the Lord was on earth at the time of His first coming, He taught His disciples many new and wonderful things about Himself, and about the way people should live if they want to come at last into heaven and be happy forever. Before Jesus left His disciples, He told them to go and "make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all things that I have commanded you." (Matthew 28:19-20)

Those who believed these teachings and were baptized were called Christians, from the Lord's name Christ. They became like one large family, with the Lord as the Father, and so they were called the "church," meaning the Lord's family.

Many hundreds of years later, the Lord in his wisdom saw that the time had come to give to men a new understanding of His truth. Many of the teachings He had given before were being taught wrongly, and people did not know that what the church was teaching was often not what the Lord wanted at all.

For this reason the Lord made known to His children a new understanding of His teachings, which He called the doctrines of a New Church. When all of these teachings had been given, and written down in books, the Lord called together in the spiritual world all the disciples who had been with Him in the world and sent them out to tell everyone in heaven the good news that now men on earth knew that the Lord God Jesus Christ reigns.

=== Junior

Explain simply the spiritual meaning of Revelation 21:1-10. ("It treats of the state of heaven and the church after the Last Judgment ... after [which] ... the New Church will exist on earth [and] will worship the Lord." (@AR 875).) Then connect this meaning with the event described in @TCR 791.

Today we are celebrating the anniversary of something new in the world: something that the Lord has given for the benefit of all mankind. It was so important the Lord also told all the men and women and children in heaven about it.

What is this new thing that He gave us?

On what day did the Lord send out His disciples to tell everyone in heaven about this new thing?

What were they told to preach?

Our New Church teachings tell us that this was to fulfill a prophecy that was made in the Gospel. Look up Matthew 24:31 to see what that prophecy was.

Let us see if we can remember some of the new teachings which the Lord gave to the world to be used in His New Church:

1. He revealed that His Word has an inner spiritual meaning.

2. As we learn this spiritual meaning here in Sunday School and as we study at home, we find that the Bible really tells us all about heaven, all about the Lord, and all about the life that leads to heaven.

3. Although people had believed in a general way that there was a life after death, the Lord revealed through Swedenborg just what kind of life it would be. He described in full detail the way people live in heaven, and also in hell.

4. Another wonderful thing that the Lord revealed is that there is a new kind of love that is possible between a husband and wife if they truly love the Lord. He called this love conjugial love.

5. Many false ideas about what God wants of us were corrected.

One very important doctrine the New Church teaches is that the Lord Jesus Christ alone is to be prayed to and worshiped, for there is no other God besides Him, and He alone has power to save us from our sins.

We celebrate New Church Day on or near June nineteenth, the anniversary of the day the Lord sent His disciples out to tell the good news.

=== Intermediate

Follow the same general outline as for the Juniors, but look in more detail at the summary of news given in @TCR 846-847. If time permits, discuss part of chapter 14 of @TCR 768 et seq.

In Swedenborg's work, @TCR 791, which is at the end of the last regular chapter in the book, it says that when this last great summary work of the doctrines of the New Church had been completed, "the Lord called together His twelve disciples who followed Him in the world; and the next day He sent them all forth throughout the whole spiritual world to preach the Gospel that the LORD GOD JESUS CHRIST reigns, whose kingdom shall be for ages and ages, according to the prediction in Daniel 7:13-14 and Revelation 11:15. ... This took place on the nineteenth of June, 1770."

Throughout the history of the organized New Church, this date has been celebrated as New Church Day. It is a day to remind ourselves of how much we have to be grateful for, in that the Lord has permitted us to know about the revelation He made as the basis of a New Church in the world.

In the supplement to @TCR 846-847, Swedenborg records a remarkable conversation he had with some angels. It began when these angels asked him, "What is the news from the earth?" Here is an outline of his reply.

He said that the Lord had revealed many mysteries or secrets that had not been known before. Some of them are:

1. That in each and all things of the Word there is a spiritual sense corresponding to the natural sense; that by means of that sense the Word conjoins men of the Church with the Lord.

2. That the correspondences of which the spiritual sense consists have been disclosed.

3. That the Lord had made a new revelation about life after death.

a. About the nature of heaven and hell.
b. About the sun of the spiritual world.
c. That there are three degrees of life, and consequently three heavens.

4. That many other things had been revealed: regarding the Last Judgment, the Lord as being the God of heaven and earth, God as being one in person and in essence in whom is a divine trinity, a New Church to be established by Him, the doctrines of that church, the holiness of the @DSS, that the Apocalypse (book of Revelation) had been unfolded, and many more things.

If you would like to learn how this revelation constitutes the Lord's Second Coming, read in @TCR 768-790.

=== Senior

After discussing the significance of the event which led to naming June 19 as "New Church Day," and relating it to the first ten verses of Revelation 21, review briefly the new doctrines outlined in @TCR 846-847. If any time remains, interesting details of the spiritual meaning of Revelation 21:1-10 will be found in @AR 875, beginning at the subheading "THE CONTENTS OF EACH VERSE."

In Swedenborg's last great summary work, @TCR 791, which is the last paragraph at the end of the last regular chapter in the book, it says that when this work, this summary of the doctrines of the New Church, had been completed, "The Lord called together His twelve disciples who followed Him in the world; and the next day He sent them all forth throughout the whole spiritual world to preach the Gospel that the LORD GOD JESUS CHRIST reigns, whose kingdom shall be for ages and ages, according to the prediction in Daniel 7:13-14 and Revelation 11:15. ... This took place on the nineteenth day of June, 1770."

This announcement heralded the descent of the Holy City from God out of heaven, described in Revelation 21:1-10. A summary of the spiritual meaning of these verses will be found in @AR 875, beginning at the subheading "THE CONTENTS OF EACH VERSE."

Throughout the history of the organized New Church, June 19 has been celebrated as New Church Day. It is a day to remind ourselves of how much we have to be grateful for, in that the Lord has permitted us to know about the revelation He has made as the basis of a New Church in the world.

Following the last chapter, in a supplement to @TCR 846-847, Swedenborg records a conversation he had with some angels, who had asked him, "What news from the earth?" Here is an outline of his reply.

He said that the Lord had revealed many mysteries or secrets of heaven that had not been known on earth before. Some of them are:

That in each and all things of the Word there is a spiritual sense corresponding to the natural sense; that by means of that sense the Word conjoins men of the Church with the Lord.

That the correspondences of which the spiritual sense consists have been disclosed.

That the Lord had made a new revelation about life after death:

About the nature of heaven and hell; About the sun of the spiritual world;

That there are three degrees of life and consequently three heavens.

That many other things had been revealed: regarding the Last Judgment, the Lord as being the God of heaven and earth, God as being one in person and in essence in whom is a divine trinity, a New Church to be established by Him, the doctrines of that church, the holiness of the @DSS, that the Apocalypse (book of Revelation) had been unfolded, and many more things. If you would like to learn how this revelation constitutes the Lord's Second Coming, read in @TCR 768-790.

=== Adult

