
== INDEX--CONTENTS--SUMMARIES

=== LECTURE I. Introductory - Infidel Objections Stated

Prevalence of Infidel sentiments, and of an increasing tendency to think meanly of the Scriptures. 
Their Plenary Inspiration generally relinquished.
Design of these Lectures stated.
I. Necessity of Revelation.
II. The character which _must_ belong to a Composition which has God for its Author.
Inquiry proposed: Do the books called the Holy Scriptures come up to this character?
Answered in the affirmative by the Lecturer, but the Proof reserved for the subsequent Lectures.
Answered in the negative by the Deist, on the alleged grounds, that the books in question contain some Statements which are contradictory to each other, some that are at variance with
Science and Reason, and some which are repugnant to Morality; and that,
beside these positive Objections, the greater part of them is occupied with Indifferent and Insignificant Matters.
Examples.
General Reply: That all such Objections arise from taking a merely Superficial View of the Scriptures, and from an Ignorance of their True Nature; and that they may be retorted, so as to assist in proving what the True Nature of the Scriptures is.
III. Appeal to the Reader, on the ill consequences of Infidelity.


=== Lecture II. - The True Nature Of The Scriptures Explained

Design with which the Scriptures were given, and the Nature of their Composition, stated for proof.
I. That the title, "the Word of God", and the 
Plenary Inspiration which that title implies, are claimed by the Scriptures.
1. By Moses and the Prophets for their respective Writings.
2. The claim allowed them, and their absolute Infallibility asserted, by the Lord Jesus Christ.
3. Their Plenary Inspiration insisted on by the Apostles.
4. And recognised, till lately, by the majority of Biblical Critics.
II. Proofs, from rational and philosophical grounds, that a Composition which is really "the Word of God", must contain stores of wisdom in its bosom independently of any thing that appears on the surface.
III. That the Composition received as the Word of God, continually assures us that it is inwardly replenished with such wisdom.
1. This intimated by the writers of the Old Testament:
2. Expressly declared by the Lord Jesus Christ;
3. And by his Apostles:
4. Generally believed by the Christian Church, 
(1.) for many ages, from the Apostles downwards, 
(2.) and still recognised by the best Interpreters.
IV. But this great truth having been abused, that endeavours
have been made, during the last two or three Centuries, to restrict the meaning of the Scriptures to their Literal Sense alone. Admitted, that all Controversies are to be decided, and Points of Faith established, by the Literal Sense; But that the objection against a further sense would fall to the ground, could it be shewn, that the Scriptures are written throughout according to an immutable Law or Rule, a knowledge of which would, in explaining them, substitute certainty for conjecture, and cut off the sources of vague interpretation.

=== LECTURE III. - The Law Or Rule Explained According To Which The Scriptures Are Written

Preliminary Remark, on the Reasons why the Scriptures are not written in plainer Language. Short Recapitulation.
I. A Universal Rule of Interpretation afforded in the Mutual Relation, which exists by creation, between things Natural or Material, Spiritual or Moral, and Divine. 
II. The 
1. The whole Universe an Outbirth from the Deity, whence it bears, in all its parts, an immutable relation to the attributes which belong to the Divine Essence. Nature of this Relation considered.
2. That on all things belonging to the Moral, Intellectual, and Spiritual Worlds, the Divine Creator has thus first stamped a certain Image of himself.
3. And that he has done the same, though under a totally different form, on all the objects of Outward and Material Nature:
(1.) In the chief organs and parts of the Human Frame, and in the arrangement of Pairs observable through all Nature: 
(2.) In the imitation of the Human Form which reigns throughout the Animal Kingdom, and, by Analogous Parts and Functions, in the Vegetable and Mineral Kingdoms also: 
(3.) In what may be called the Moral Qualities of Animals: 
(4.) Digression on the origin of Malignant Qualities in Animals and the other productions of Nature.
(5.) The subject resumed, and instanced in the Essential Properties of Vegetables and Minerals.
4. Thus that all things in Nature, being Outward Productions from Inward Essences, are Natural, Sensible, and Material Types of Moral, Intellectual, and Spiritual Antitypes, and, finally, of their Prototypes in God.
III. That, weie the Relation between these different orders of Existences fully understood, a Style of Writing might be constructed, in which, while none but Natural Images were used, purely Intellectual Ideas should be most fully expressed. --  
1. That this is in a great measure intuitively perceived by all
Mankind.
(1.) Hence our conclusions from the Expression of the Countenance to the Emotions of the Mind.
(2 ) And hence the origin of many Forms of Speech in common use.
(3.) If such a relation of Analogy between Moral or Spiritual and Material or Natural Objects exists in a great number of cases, it must be universal.
2. Palpable Instances of the occurrence of such Forms of Speech in the Holy Word.
IV. That in ancient times this constant Relation between things Natural, Moral or Spiritual, and Divine, was extensively understood.
1. Proved from intimations in the Historical Parts of Scripture.
2. Confirmatory remarks, drawn from the Mythological Fables of the Greeks and Asiatics, and the Hieroglyphics of Egypt? some of which are explained.
V. That in this Relation, then, is to be found the Law or Rule according to which the Scriptures are written, and that a knowledge of it will afford the Key by which their "dark sayings" must be deciphered. 
--  Conclusion: That the Doctrine of Analogies is not liable to the reproach either of Fancifulness or of Novelty, and is worthy the attention of every friend of Revelation and Piety, and of Reason and Knowledge.

=== LECTURE IV. - Proofs And Illustrations, Evincing That The Scriptures Are Written According To The Law Or Rule Developed Tn The Last Lecture

I. Of the Style proper to a Divine Composition. Such a Style afforded by the Relation of Analogy between Natural Things and Spiritual, as explained in the last Lecture.
II. That if the Scriptures are written by a Plenary Divine Inspiration, they must be composed in this Style. 
1. The Word of God must be governed by the same General Law as his Works; and this is the Law of the above Analogy.
(1.) That when the Divine Speech, or the Divine Word, which is the same thing as the Divine Truth, emanates from the bosom of Deity into the circumference of Creation, or into the world of Nature, it there clothes itself with Images taken from that world, and that it cannot otherwise be presented to Mankind:
(2.) But it thus is presented with a fulness which no other kind of Language could afford:
2. Variety of Phraseology in the different Inspired Penmen, not inconsistent with Verbal Inspiration.
3. The difference between Plenary and Personal Inspiration;and that the former is necessarily occasional, and not permanently attendant on certain Persons.
III. That the Holy Scriptures are the Divine Truth thus brought into a natural form; and that therefore their Interior Meaning can only be understood by an application to them of the Law which governs the Relation between Natural Objects and Spiritual and Divine Essences.
IV. Applicability of the Rule to the Prophecies of the Divine Word. The View proposed supplies exactly what, in other Systems, was felt to be wanting.
1. Sentiments of Biblical Critics on the Double Sense of Prophecy. Necessity of making the System uniform.
2. Rule of Analogical Interpretation adopted by Sir Isaac Newton and Bishop Warburton.
3. Defects of their Rule, and the necessity of extending it further. 
V. Examples of the Light which results from the application of the Rule of Analogy between Natural Things and Spiritual to the Prophecies.
1. Ezekiel's Prophecy of a great Sacrifice upon the mountains of Israel. (Ezek xxxix. 17 to 20.)
(1.) General Remarks on the Class of Prophecies which can be intended for Spiritual Fulfilment only.
(2.) Evidence that this Prediction belongs to that Class.
(3.) General Signification of Judea and the surrounding Countries.
(4.) The Spiritual Analogy of the relations of Place deduced.
(5.) The Signification of the Land of Gog and Magog as resulting from this Analogy, and of an Invasion thence of the Land of Judea.
(6.) The light thrown by this Prophecy upon that portion of the
Prophetic Word which treats in its Letter of particular Countries and Nations.
(7.) The Import, in the Language of Analogy, of the Address to the Fowls and Beasts.
2. The Lord's Prophecy of his Second Coming in the Clouds of heaven, (Matt. xxiv. 29, 30.)
(1.) The former part of this Chapter a remarkable instance of that Class of Prophecies which admits a Literal Fulfilment: yet the Spiritual Fulfilment the principal thing intended.
(2.) The impossibility of connecting the former part of the Prophecy with the latter by the Literal Sense alone, and the Inconsistencies incurred by Commentators in the attempt.
(3.) Inquiry instituted into the specific Signification of the Coming of the Son of man in the Clouds.
(4.) The terms must have a determinate meaning. 
(5.) The Import of the phrase, "Son of man", as used in Scripture.
(6.) The Ground of that Import in Analogy.
(7.) Signification of the Clouds, when mentioned in Scripture; with the Analogical Reason for it.
(8.) The meaning of the Prophecy thus rendered evident.
3. John's Vision of Spiritual Babylon, (Rev. xvii. 3 to 6.)
(1.) Signification of Babylon in Scripture, as discoverable from the circumstances predicated respecting it:
(2.) Of the circumstances predicated by Babylon personified. 
--  Conclusion: That the Prophetic Parts of Scripture are composed in the Divine Style of Writing, and that, thus far, the claims of the Scriptures to Plenary Divine Inspiration are established.

=== LECTURE V. - Proofs And Illustrations Continued

2. Necessity of making the System uniform.

The Argument, respecting the proof of the Plenary Inspiration of the Scriptures by their Style, more distinctly stated.
I. Applicability of the Law which governs the Relation between Natural Objects and Spiritual and Divine Essences, or of the Science of Analogies, as a Rule for the Interpretation of the Historical Parts of the Divine Word.
1. Sentiments of Biblical Critics, and admissions of Expositors, on the Typical Nature of the Scripture History: 
(1.) In regard to the Miracles; 
(2.) And other Circumstances.
II. Just Ideas of the nature and uses of the Israelitish Dispensation necessary to the right apprehension of the Israelitish History.
1. The selection of the Israelites as a peculiar people, not intended so much for their own benefit as for the general benefit of mankind. 
2. It promoted this object; 
(1.) By their filling a station indispensable in the Divine Economy, during a period in which a higher or more extensive Dispensation could not have been received, and in supplying the Preparation without which such superior Dispensation could never be given at all: 
(2.) By furnishing the means by which the Holy Word might be written: which they did by representing divine things under External Symbols and Natural Occurrences; for which office they were peculiarly suited by their distinguishing Temper and Genius.
III. Examples of the Light which results from the application of the Rule of Analogy between Natural things and Spiritual to the Scripture Histories.
1. The Miraculous Capture of Jericho: (Josh, vi.)
(1.) The Acts of Violence performed by the Israelites, and some of the Enactments of the Law, merely permitted to them "because of the hardness of their hearts", and because they could be so overruled as to afford exact Symbolic Representations of the Spiritual and Heavenly things which are the real objects of all
the Divine Commandments. 
(2.) The Spiritual Import of the Command to destroy the Canaanites; 
(3.) of the circumstances attending the Capture of Jericho.
2. Jephthah and his vow: (Judges xi.) Remarks on the literal history.
(1.) Necessity for an appearance, on the face of the Narrative, as if the Sacrifice took place.
(2.) The Origin of Human Sacrifices: 
(3.) And of Sacrificial Worship in general; with its Ground in, and Signification by, the Science of Analogies.
(4.) The Signification of an _apparent_, and of the _actual_ Sacrifice of a Child.
(5.) The principles applied to the case of Jephthah's Vow, and shewn to explain, most satisfactorily, the statements of the Narrative.
3. The combat of David and Goliath, (1 Sam. xvii.)
4. The circumstances attending the Crucifixion of Jesus Christ.
IV. Examples of the Light which results from the application of the Rule to the Ceremonial Precepts of the Divine Word.
1. The Sacrifices in general
2. The Prohibition of various kinds of meats: (Lev. xi.)
3. The Law of the Nazarite: (Numb, vi.)
4. Baptism and the Lord's Supper; which were instituted under the Christian Dispensation as an Epitome of the whole Ceremonial Law. --  Inference from the whole.
V. Additional Argument,
1 . Proposed and Illustrated: A false Rule of Interpretation could not draw from the Scriptures a coherent sense throughout: But the Doctrine of Analogies does this: Wherefore it must be the True Rule of Interpretation, and the Scriptures must be written according to it.
2. The argument afforded by the fact, That a number of Writers, living at distant periods, produced Compositions all uniformly following this Law. --  Inference repeated, -- That the Style in which the Scriptures are composed is the truly Divine Style of Writing; and that nothing short of Plenary Divine Inspiration could be adequate to their production.
Thus they are truly denominated the Word of God.

=== LECTURE VI. - The Whole Fabric Of Infidel Objections Shewn To Be Without Foundation

I. General View of the System and Arguments of the preceding Lectures:
1. The first stage of the Argument: 
2. The second: 
3. The third: Important additional Testimony: 
4. The last.
II. The four Classes of Infidel
Objections stated in the first Lecture resumed, and examined by the View which has been developed of the nature of the Holy Word, and of the means of deciphering its true Signification.
1. Imputed Inconsistencies with Reason and Science considered: 
(1.) Style of Writing in the first part of the book of Genesis.
(2.) Genius of Mankind in the Primeval Ages.
(3.) Coincidences between the Narratives of this part of Scripture and ancient Traditions. 
--  Conclusion: That the Word of God pronounces no dictum upon the questions agitated by Science.
2. Imputed Contradictions considered.
(1.) The case of the water turned into blood by the Magicians of Egypt.
(2.) Why were four Gospels written?
(3.) Theory of their variations proposed.
(4.) Illustrated by the different accounts of the treatment and behaviour of the Lord Jesus Christ at the Crucifixion
(5.) By the two modes of representing the conduct of the Thieves.
(6.) The two accounts of the Temptation in the Wilderness.
(7.) Matthew's naming Jeremiah instead of Zechariah a necessary result of his Inspiration. 
-- Conclusion: That the varying statements of the Sacred Writers, fairly interpreted, actually become evidences of their Inspiration.
3. Imputed Violations of Morality considered.
(1.) That they only evince the Representative Character of the Israelitish Dispensation. 
(2.) David not the Pattern of a saint, but the Type of one.
4. Imputed Insignificance considered. General Reply confirmed; -- That all such objections arise from taking a merely superficial view of the Sacred Scriptures, and from an utter Ignorance of their true Nature.
III. Address to Christians on the Necessity of taking higher ground in their Controversy with Deists.
IV. Address to Deists, on the internal causes of Scepticism.

Conclusion.

=== APPENDIX

No. I. Proofs of the Symbolic Character of the Writings of the
Old Testament afforded by the Revelation of John

No. II. An Attempt to discriminate between the Books of Plenary Inspiration contained in the Bible, and those written by the Inspiration generally assigned to the whole

No. III.The Great Objects and Phenomena of the Mundane
System considered, as they are referred to in the Language of Prophecy, and of the Scriptures in general

No. IV. The Signification of the Clouds, when mentioned in Scripture, further Illustrated

No. V. Illustrations of the Jewish Character; evincing its Aptitude for a Dispensation consisting chiefly in External Rites

No. VI. Critical Examination of Jephthah's Vow

No. VII. Arguments for the Literal Interpretation of the first part of Genesis considered

No, VIII. Remarks on the Recent Volume of Bampton Lectures, by the late Rev. J. J. Conybeare, M.A. ; and on the Support which it affords to the main Principle of the present Work


