
== PREFACE

// === PREFACE

So numerous are the works which have been produced in vindication of the divine authority of the Scriptures and of the truth of the Christian Religion, so high the reputation of many of them, and so unquestionably great their merit, that it might almost appear like presumption in any one again to handle this argument.
Certainly, however, while fresh attacks upon the foundations of the Christian Religion are continually being made, it is necessary that fresh works should be composed in its defence; even though they added no more that is new to the vindication of Revelation, than the renewed ranks of its assailants produce against it.

But laudable and useful as the production of works of this class is, he who now solicits the attention of the Public would never have appeared as an Author, merely to add to their number. He has long been impressed with a serious conviction, that fully to meet the difficulties which infidel writers have raised, it were necessary to put the controversy on a different ground from that which has been taken by the most popular of the Christian advocates. 
He is of opinion, that the ablest of their works are more adapted to silence, than to satisfy, even an ingenuous inquirer. 

The former effect is or ought to be produced, when such circumstances and considerations are alleged as cannot be accounted for upon any other hypothesis than that which supposes the truth of the religion. 

But to accomplish the latter object, the circumstances in the documents of the religion, which, as the Sceptic thinks, are incompatible with the belief of their divine origin, must, also, be satisfactorily explained.

This is what few of the modern advocates of Revelation attempt; and they who have attempted it have seldom satisfied even their own friends: indeed it is now usual to admit, that some of the difficulties are such, as, in the present state of knowledge upon the subject, or by any principles which have yet been applied to it, are inexplicable. 

With this drawback, the success with which they have handled the other part of the argument too often fails to produce any deep conviction; notwithstanding they have proved, with a completeness which leaves little room for fair denial, that Christianity, in general, may, -- nay, must be true, whether all the seeming difficulties in its records can be explained or not.

The perpetual theme of modern defenders of Christianity, is, Miracles; which, they shew, were certainly performed by Jesus Christ and the apostles, and which they extol as the proper evidences of a Divine Revelation.

So far as relates to the latter assertion, the Deist is ready enough to take them at their word; he admits that miracles are proper evidences, and desires, therefore, to see some performed.
With the express terms of this request, the Christian advocate declines to comply; but he undertakes to prove, instead of it, that the sceptics of former ages might, if they pleased, have had that satisfaction.

But do not both parties here somewhat mistake the matter?

If the evidence of miracles were so convincing as the Deistical writers usually suppose, how come some of their acutest reasoners to object to Christianity on that very ground, -- because it records them among its documents?

If, on the other hand, that evidence were so essential as the Christian advocates admit, how can we account for their having ceased; and ceased, not only in countries where the profession of Christianity is established, but even where attempts are made to sow in new soils the seed of the gospel? 

Ought not this palpable fact to make the Christian hesitate about affirming so confidently, that miracles are so highly important as evidences of the truth of Revelation? 

Ought it not to lead us to conclude, that, either separate from, or in addition to, this use of miracles, some other cause was required to their exhibition; 
and that, this ceasing to operate, they ceased also?

Thus may we not infer, that they were performed under the Jewish dispensation, because they were suited to the nature of that dispensation, and to the Jewish character; that they were performed also at the commencement of Christianity, on account of its original connexion with Judaism; 
because, likewise, the Jewish dispensation was not finally terminated till the destruction of Jerusalem, which put a total end to the types and shadows of the ceremonial law;
and because, in general, they were suited to the state of the human mind at that time? 
but that the cause of their entirely ceasing soon afterwards* 
----
*Footnote: What was the exact period of their cessation, -- whether, with some, we suppose the power of performing them to have died with the Apostles; or, with others, to have continued for one, two, or three centuries afterwards: or even, with the Roman Catholics, to exist still; is of little consequence; since few will contend that, after the Apostles, it was constantly enjoyed by the teachers of Christianity, or was so exercised as to add much effect to their preaching. The phenomena which may have sometimes attended private acts of faith, or, as most will prefer to say, (in regard, at least, to modern cases,) of imagination, belong to a different order.
----
was, because they were not suited to the nature of the
Christian dispensation, nor to the state of the human mind which was introduced with, or produced by, that dispensation?

It is certain that, with the introduction of Christianity, the human mind received a capacity of being enlightened by the substance of those things of which the Jewish law, with the miracles wrought to confirm it, and those also wrought among the Jews by the Founder of Christianity, were types: and this new state of the mind required evidences more congenial to its own nature.

Now this view of the subject does more for the support of Christianity, by nullifying the demand of the Deist for present miracles, than would be effected in its behalf by miracles themselves, could they still be produced. 
For certain it is that miracles would not have that convincing effect which both parties ascribe to them.
Accordingly, when they were wrought by the first teachers of Christianity, the conversion of opposers does not appear to have been their chief intention; 
on the contrary, where opposition prevailed, it is said of the Saviour himself, that he could not do many mighty works, because of their unbelief (Mark 6:5; Matt. 13:58.); and never did he perform one when defied to it.

Still, because no one, in those days, doubted the possibility of such performances, the fame of them spread abroad. But we well know what excuses the Jews readily framed, for refusing to believe the Revelation thus authenticated to them; and are we sure that even all of those, who now are loudest in condemning the folly, in this respect, of the Jews, and who take most pains to prove the infallibility of miracles as evidences to a Divine Revelation, would accept any doctrine which they now reject as contrary to their reason, could its advocates work a miracle for their satisfaction? 

Would they not presently evince as much ingenuity as the Jews, in evading the force of the miraculous proof, and justifying their adherence to their former opinion? 
We may infer the result from the example of a celebrated controversialist, and a strenuous advocate for the efficacy of miraculous proof; who yet scrupled not to affirm in one of his publications, that were an angel from heaven to announce to him a certain doctrine, which many think they plainly read in the Scriptures, he would tell him in reply, that he was a lying spirit. 
If then a celestial visitor would have been so rudely treated by this mighty polemic, who also was an eminent philosopher, what would be the fate of a human teacher of any obnoxious doctrine who should pretend to confirm it by miracles?
Would he not be reviled as a juggler and a cheat? 
would not the philosophic science of his antagonists be put in requisition to devise for the phenomena some plausible solution from natural causes? 
and would not some secret method of putting these causes into action be the utmost that would be allowed to the operator? 
The only difference between the philosophic and the Jewish opponent would be this; that while the one allowed a positive miracle to have been wrought, but assigned the cause of it to Satanic energy, the other would deny any miracle at all, and would ascribe the whole to the energies of Nature.

Let us suppose, however, the Deist to be somewhat more candid,
and to be capable of being satisfied, at the time, that a miracle had been performed. 

Imagine him then to appeal to a modern inheritor of the Apostolic gifts, (if any such existed,) enumerating the difficulties with which, to him, the documents of Revelation seem to be attended,
affirming that certain statements in the Sacred Records appear to him repugnant to reason and replete with contradictions, and begging to be informed how the difficulties may be reconciled, and the record containing them viewed as altogether worthy of a divine origin; 

And suppose the Christian teacher to answer, "I will presently convince you that the Record _is_ from God; but as for the difficulties in it, you must reconcile them yourself in the best manner you can;" and were immediately to perform some notable miracle. 
How would the Deist be affected by it? Would the wonder displayed before his eyes remove all darkness from his mind? When thus certified that the Revelation came from God, would he understand it any better? If he before thought it unworthy of God, would he now see the ground of his error?
If it before appeared to him to include contradictions, would these immediately vanish?
In short, though silenced, would he be satisfied?

Now this appears nearly to resemble the situation, in which the inquirer, whose attention has been directed to the difficulties which have been raised by Infidel Objectors, is placed by the defences of Christianity most in esteem, when they insist so much upon the miracles wrought at its origin. 
A compulsory conviction, (compulsory as far as it goes,) is produced, that the religion thus evidenced must be true; but the question as to how it can be true, is left just where it was before; 
and yet till this also be seen; till the question of reason be as satisfactorily answered as the question of fact; no conviction can penetrate very deep. 

The miracles wrought by the first promulgators of Christianity, are certainly brought again, by the labours of modern advocates, almost before our senses; but, happily, not quite; 
for if they were, the effect would be, to deprive the mind of that superior freedom which Christianity, among its other benefits, was introduced to restore, and not to open the understanding, but to close it. 
A sceptic thus convinced that the Scriptures have the sanction of divine authority, would be placed in the situation of an Englishman and a Protestant in such a country as Spain; in his heart he might think the government a tyranny and the religion priestcraft; but being quite satisfied of their power, the fear of the Inquisition might compel him to hold his tongue.

It is not congenial to the nature of the human mind to acquiesce in implicit faith contrary to the dictates of its own understanding; and if this is not congenial to the nature of the human mind in general, assuredly it is peculiarly repugnant to it at the present day, when so astonishing a spirit of inquiry has so universally gone abroad.


The sceptic will now ask, "While the phenomena of nature are in every direction becoming intelligible, and we are admitted to see the _rationale_ -- the philosophy, -- of every other science, is Theology for ever to present nothing but dogmas, for which faith is demanded while understanding is denied? Will she, alone, never answer the request for her reasons, but by alleging her miracles?"

Let not, however, these remarks be misunderstood.
Nothing is further from the intention of the writer, than to depreciate the merit, or undervalue the utility, of the vindications of Revelation here alluded to; all that is meant to be insinuated is, that they require something in addition to render them fully efficient to their object.
If, while the Deist is convinced by them that miracles were actually wrought at the commencement of Christianity, and that Revealed Religion had a divine origin, he is induced, in consequence, to suspect that the circumstances in its documents which he regards as revolting to reason only appear so because they are not understood; 
the conviction wrought in him may be lasting, and may finally be exalted into an enlightened faith. 
But to secure this result, it surely is necessary to lead him, as well as to drive him; -- to resolve his doubts and remove his difficulties, as well as to assure him, that the religion is true in spite of them all.

It has long, then, been the conviction of the writer of these pages, that such a view of the Volume of Revelation might be presented, as should be adequate to this object; 
but he little thought that ever he should venture to attempt it himself. 
____
The present work is entirely the product of circumstances, and its publication is what they who do not acknowledge a Providence in every thing, would call purely accidental.

The public mind having for some time past had the question respecting the divinity of the Christian Oracles thrust before it in every possible shape, it occurred to the Author, during the last winter, that some benefit might be communicated, at least to a few, by the delivery of some Lectures, in a public Lecture-room, upon the subject.
The thought and its execution were equally sudden; so much so, that the chief part of each Lecture was composed, amid other engagements, and, at first, without the most remote view to any other mode of publication, in the week which preceded its delivery. 

The approbation with which the effort was received, by a numerous and respectable auditory, far exceeded the Author's most sanguine expectations. From the commencement, urgent solicitations were made to him to allow the Lectures to be printed; and when, towards the conclusion, he announced his determination to comply with the request, it was received with the strongest expressions of satisfaction.
____
This statement is made simply from a sentiment of gratitude, and to account for the appearance and form of the work; but without any idea on the part of the Author, that the decision of his auditory will in the slightest degree influence, or even that it can afford any means for anticipating, the decision of the public at large, before whose tribunal he has thus been encouraged to venture.

It is also necessary to state, further, that when he consented to publish the Lectures, he really was not aware of what he had undertaken. 
So hastily had they been prepared, that, when he had finished reading them, he hardly knew of what they consisted. 
He was well apprised that much revision would be necessary, and that many important things had been cursorily passed over, which must be more distinctly treated; 
but he fully expected that the whole would have been comprised in less than three hundred pages. 
The work was put immediately to the press, and the first Lecture was printed without any very considerable alterations from the original copy; the five others, however, have been enlarged,
upon an average, to three times their original extent; and a copious Appendix has also been added.*
----
*Footnote: To the last Article of the Appendix, --  the Remarks upon the late excellent Bampton Lectures by the late Rev. Mr. Conybeare, -- no reference occurs in the Work itself, the Author not having read them till that part of his Work was printed in which the notice of them would properly have come; He takes the opportunity, therefore, of making the reference here.
----

Altogether, the book has assumed dimensions much beyond what was wished; but for this it is hoped, the importance of the subject will be a sufficient apology. As neither the whole of the work, nor any large portion of it, was ever under the Author's eye together, till it was irrevocably fixed in print, he is aware that it may afford abundant occasion for the severity of criticism: he would wish therefore that it might be judged by its matter and design, rather than its manner and execution.

If the former merit condemnation, let condemnation be awarded; but for the latter he craves some indulgence.
The mode of its origin necessarily threw the work into a popular form, which it still retains, especially in the first Lecture; 
but the Author has endeavoured to render it not unworthy the attention of the lover of studious inquiry and of biblical literature,
while he has mainly endeavoured to assist the pursuit of the earnest investigator of revealed truth. The question respecting the divinity of the professed Oracles of Revelation, is equally momentous to the simple and to the sage; and this, he hopes, will be accepted as an apology by the learned, for his having treated it in a _concio ad populum_.



