= Bible Study Notes &#8212; Lesson 110
By Anita S. Dole



== Palm Sunday

*Bible References:* Matthew 21:1-27

_This is a lesson excerpted from The Dole Bible Study Notes. There are more than 150 of these lessons, covering many of the great stories in the Bible. They were designed for use in Sunday Schools, but they're good for all ages — for self-study, for parents to use in home devotions, and for pastors and teachers. Here's a link to more information about them._

---
.*Contents:*
----
1. Introduction
2. Doctrinal Points
3. Basic Correspondences
4. Notes for Parents
5. For Young Children
6. For Older Children
7. For Young Teens
8. For Older Teens
9. For Adults
10. From Swedenborg's Writings
11. Suggested Questions
----

---

<<<


=== Introduction

There is no need of making a connection between this lesson and the last one. Special days can be treated as special, rather than in a series. In all classes it is enough to start by asking the pupils if they know what special day this is. The story itself is simple and striking and is easy to tell.

---

<<<


=== Doctrinal Points
----
• The principle which rules our thought and conduct is our "king. " We "cast our garments before the Lord" when we willingly give up ideas that are contrary to His teachings.
• Only the Lord can cleanse the inner "temple " of our souls, driving out our false thoughts and selfish desires.
----

---

<<<


=== Basic Correspondences
----
• donkey = natural reason
• palm tree = principle that the Lord alone can save
• garment = ideas which "clothe" our affections
----

---

<<<


=== Notes for Parents

Palm Sunday commemorates the entry of the Lord into Jerusalem at the beginning of the last week of His life on earth. We know that throughout the three years of His public ministry the Lord had been going about through Palestine and the country beyond Jordan teaching, preaching, and healing. Although His power to heal drew crowds of people to follow Him, there is no record that He ever tried to attract the crowds or even that He was pleased to have them. In fact, He told them plainly that many of them were following Him merely for the loaves and fishes. He said without hesitation many things which He knew would drive many of them away, and it is often recorded that He withdrew from them and sought to be alone with His close disciples. If we take the Lord as our example, we shall do our Christian work quietly and without worrying about appealing to crowds. The Lord said, "Where two or three are gathered together in my name, there am I in the midst of them."

The entry into Jerusalem on Palm Sunday was the only time when the Lord purposely displayed the tokens of His real position, and this was in fulfillment of the prophecy spoken through the prophet Zechariah (Zechariah 9:9), for the Lord came, as He said, to "fulfill the law and the prophets." It was the custom of kings and judges to ride on donkeys, and the multitude hailed the Lord as king. The Lord knew that within the week which was beginning they would turn against Him and put Him to death. He was teaching them and us a lesson which every one of us needs.

A king is the accepted ruler of a nation. In our lives the principle which we have accepted to rule our thought and conduct is our "king." Each one of us, as you may remember from our lesson about Elijah, is given the choice of accepting the Lord or Baal — divine truth, or the principle of worldliness and self-interest — as our ruler. But we cannot divide our allegiance: as the Lord Himself tells us, "ye cannot serve God and mammon." When we try to serve both, it is our spiritual principles which are sacrificed, as the events of the last week of the Lord's earthly life show.

When the people welcomed the Lord into Jerusalem as king, they cast their garments and branches from the palm trees before Him. This is a picture of the willingness we should have to give up our own ideas — the garments in which we have clothed our souls - and to recognize that divine truth should rule us and that all power to bring happiness and peace to us and to the world is in the Lord alone.

But what all too often happens? The Lord's first act on entering Jerusalem was to drive out from the temple those who were using their religion for selfish gain. The temple symbolizes our character in its spiritual aspects. To cleanse the temple is to "search the soul" and expose and reject all its deep-seated selfishness. It was the cleansing of the temple which started the conflict that ended in the Lord's death on the cross.

---

<<<


=== For Younger Children

[.underline]#*Teacher Notes:*# 
Talk about the Lord, the donkey, the garments on the donkey, and the palm branches.

---
Dwell on the joy of the people, especially of the children, in welcoming the Lord. The lesson should end with at least a statement of the fact that within a few days the very people who welcomed the Lord on Palm Sunday turned against Him and put Him to death. The children can also understand that when they are good, they are welcoming the Lord into their hearts as king, and that whenever they are naughty, they are turning against Him.

This week is called "Holy Week," and today is Palm Sunday.

Can you tell why this is called Palm Sunday? (see John 12:13)

It was the beginning of the Lord's last week on earth.

On the first day of that week the Lord came to Jerusalem.

What did he tell two of His disciples to do?

How did He enter Jerusalem?

It was the custom of kings and judges to ride upon donkeys.

And it had been prophesied that the Messiah would come riding on a donkey. Suppose we read this prophecy in Zechariah 9:9.

The people welcomed the Lord gladly, and especially the little children.

The chief priests and scribes did not like to hear Jesus praised.

But He told them that the little children who sang hosannas were wiser than they.

The priests, however, were very powerful, and the people listened to them. They very soon turned against the Lord.

What did the Lord find in the temple?

Many of the people were making money for themselves out of the gifts that were brought to the temple for the Lord. They were really stealing from Him.

Before the week was over, they put Him to death.

The Lord knew they were going to do this, but He went to Jerusalem just the same.

If we love the Lord, we shall accept Him as our king and try to learn what He tells us is right.

And we shall try to be strong and brave enough to do right even when it is hard.

---

<<<


=== For Older Children

[.underline]#*Teacher Notes:*# 
These children can get a good deal of the correspondence of this lesson, especially of the donkey, the palm branches, and the garments. They should look up the various references in the Old Testament and see how many prophecies were fulfilled literally. And the general lesson for their own lives should be impressed upon them. Children of this age are usually eager to learn and quick to receive, but equally quick to forget in the face of their daily environment. The surprise they will feel at the fickleness of the crowd can be made helpful to them if they were led to see how the same thing is true of themselves.

---
Today we commemorate the first day of the last week of the Lord's life on earth, and the events of that day.

Why is today called Palm Sunday?

What city was the Lord coming into?

What did He ride on?

It was the custom for kings and judges to ride upon donkeys. The donkey, you know, is very sure—footed but also very stubborn and unwilling to be directed by his master. The donkey is a picture of our natural reason, our "common sense," which always looks at the ground and never up to heaven. It leads us along very well in worldly matters, but there are many things it does not see. For instance, it is sometimes very hard for us to admit that unselfishness is really better and wiser than selfishness. Our common sense says, "unselfishness doesn't get you anywhere." This is the donkey speaking. The colt on which the Lord entered Jerusalem was one "whereon yet never man sat" (Luke 19:30). That is, the Lord was the first one ever to bring this power of the natural reason wholly under subjection to higher principles. Look up Zechariah 9:9 to see how the Lord was fulfilling prophecy.

When the Lord rode into Jerusalem on Palm Sunday, His disciples hailed Him as king, casting their own garments and branches of the palm trees in His path for Him to ride over. This is a picture of what we should do. Our "garments" are the thoughts in which our feelings are dressed, and the palm branches are symbols of our belief in the Lord as our savior. All our own ideas should be submitted to the judgment of the Lord's truth, if we really recognize Him as our God and king.

What did the Lord do in the temple?

Doves were used as sacrifices. The law said that all the animals and birds used as sacrifices had to be perfect. Many people bought their doves to sacrifice after they reached the temple, but even when they brought their own, it was not hard to find some small flaw and make them buy others. The temple offering had to be made in the "shekel of the sanctuary," and this was not a common coin. The money changers charged a fee for the exchange. The passage the Lord quoted is found in Isaiah 56:7 (cf. also Jeremiah 7:11).

The chief priests and scribes did not like to hear anyone praised but themselves, and they were afraid of the Lord's popularity. So the Lord again quoted Scripture to them. Read Psalm 8:2.

Where did the Lord go to lodge overnight?

The Lord had friends there. Look up John 11:1-5 and Luke 10:38-39. What happened to the fig tree because the Lord found no fruit?

This is a picture of what happens to the soul of anyone whose religion does not bear the fruit of good deeds. The church of that day was in this state. When the Lord came to Jerusalem on Palm Sunday, He knew that He would be put to death. He could have saved Himself as He had many times before, but He knew that His death on the cross was necessary to the finishing of His work and to our salvation.

---

<<<


=== For Younger Teens

[.underline]#*Teacher Notes:*# 
The best point to discuss with this age group is perhaps the correspondence of the donkey and the necessity of submitting our natural reason — which judges according to appearances — to the rule of the Lord's truth. Remind them of our study of Saul.

---
In thinking of what Holy Week should mean to us, we should ask ourselves if we are like those people long ago who welcomed the Lord as king on Palm Sunday and put Him to death the following Friday.

Palm Sunday was the first day of the last week of the Lord's life on earth. He and His Apostles were coming to Jerusalem to celebrate the Passover. The Lord had told them that He was to be put to death, and they had tried to persuade Him not to go. But the Lord rebuked them. He came to His death willingly, as a part of the work He had come into the world to do. So we should think of the cross as the symbol of victory over self, which the Lord won and which He gives us the power to win if we are faithful to His teachings.

The Lord rode into Jerusalem on a donkey, after the fashion of kings and judges. The donkey is the symbol of the natural reason, the thing we call common sense. Do you remember our lesson about Saul? Often the "common—sense" thing, the thing which seems to promise most immediate practical returns for ourselves or even for others, is not at all the thing which is wisest in the Lord's sight and so in the long run. Sometimes when we are being urged to do the right thing instead of the easiest thing and are tempted to say, "What's the sense of going to all that trouble?" it may help if we say to ourselves, "There speaks the donkey." The Lord was the only one who ever really mastered this donkey — that is, who ever brought the natural reason wholly under the control of divine truth.

What does it mean to accept the Lord as our king? First, it means that we really acknowledge that He is the one who is ruler of our life and that His laws are the laws to be obeyed. This is to cast palm branches before Him, for the palm tree is the symbol of the principle that the Lord alone can save us. Then we should determine that whenever we find that our ideas are not in accordance with the truth He gives us in His Word, we will give up our ideas. This is pictured by the people's casting their garments before the Lord. Our garments are the ideas in which our affections clothe themselves.

But the first act of the Lord after His triumphal entry was to drive the money—changers and vendors of doves out of the temple. What does this mean? The money—changers and vendors of doves symbolize all the selfish thoughts and feelings which have crept into our minds and hearts and are interfering with our true worship of the Lord. Can we stand having these driven out? The priests and scribes could not stand it, and they did not like to hear the innocent children crying "Hosanna" to the Lord. They did not want their rule interfered with. And the people, in spite of the miracles of healing which the Lord also wrought in the temple, listened to the priests. The incident of the fig tree on which the Lord found no fruit is added here because it pictures the condition of the church, which carried on what looked like worship but which produced no fruits of good character and good works. Are we like the people of that time? Do we go to church and Sunday school and learn to know the Lord and His laws and then in our everyday life let our selfishness rule us and lead us to put the Lord and His truth out of our minds?

---

<<<


=== For Older Teens

[.underline]#*Teacher Notes:*# 
This class needs especially the reminder of the fickleness of the people and its result. Most young people "mean well" and are easily inspired to good resolutions, but many are as easily persuaded to break them when their everyday environment is worldly. Emphasis should be put on the story of the cleansing of the temple and its meaning.

---
We are all so familiar with the story of the Lord's entry into Jerusalem at the beginning of the last week of His life on earth that we need only review its meaning. Jerusalem stands for the place we have made for the Lord in our minds. He reigns there as king just so far as we actually accept the rule of divine truth. He enters riding upon a donkey when we submit worldly reasonings to the control of spiritual principles. We cast our garments before Him when we are willing to give up our own ideas if we find that they are contrary to His teaching, and palm branches when we acknowledge His saving power. Then He can cleanse the inner temple of our souls, driving out false thoughts and selfish desires. And it is the "little children" in us, the innocent and trustful states, which are to be listened to.

The triumphal entry into Jerusalem on Palm Sunday was, as the Lord knew, really the beginning of the end. But the temporary support of the multitude gave Him an opportunity to cleanse the temple and to teach there, as He did during the first two days of the week, denouncing the scribes and Pharisees openly and prophesying the end of the age, which was necessary to the establishment of a new, genuine church. The fig tree which bore no fruit is a picture of the condition of the church in His time. In much the same way, there are moments in our lives when the sense of the Lord's kingship and power is so strong that we can see our own sins and hypocrisies in clear light and condemn them. Unfortunately, also like Jesus' contemporaries, we soon lose this fervor amid the temptations of our daily environment, but its effect persists and strengthens our small beginnings of regenerate life.

We think of the Palm Sunday lesson as a joyful one, and yet it is always shadowed by the thought of the dark events to come. The Lord's triumphal entry into Jerusalem actually took place "in the shadow of the cross." It should be a warning to us to examine ourselves carefully, to be steadfast in temptation, to let no selfish ambitions or fears rob us of our high purposes and lead us to crucify our king. Holy Week should be a time of humble self-examination, when we expose the scribes and Pharisees in our own minds and hearts and restore the states of innocence and trust and love which will enable us to partake worthily of the Holy Supper and to rejoice in the assurance of the risen Lord.

---

<<<


=== Adult

[.underline]#*Teacher Notes:*# 
The special discussion topic for the Adults should be what it means in our individual life really to accept the Lord as our king, remembering that a king represents truth. It is not enough to have good intentions or even to do outward good works. We must study the Word regularly in the light of the writings of the Second Coming. The conflict which followed the Lord's entry into Jerusalem on Palm Sunday and its result show us clearly where the temptation is and how and why we all too often yield to it.

---
We remember the correspondence of the three parts of the Holy Land: Galilee, the outer life; Samaria, the thought life; Judea, the life of the will. Whenever the Lord enters Judea, it is a picture of His desire to be present in our wills and to make them pure and holy. His final coming into Judea and His work there during the last week of His earthly life picture the searching of our inmost will to see whether it will receive or reject Him. Our lesson today shows that many of the people received Him gladly, recognizing Him as their king and savior; but we know that the political power in Jerusalem was still in the hands of His enemies and that they finally persuaded the people to reject and crucify Him. On the Sunday before the resurrection the Lord entered Jerusalem riding upon a donkey, as kings and judges had done in Old Testament times, and acclaimed as the "son of David," the Messiah, multitudes casting their garments in His path and waving branches of palms, the recognized symbol of victory. The multitudes acclaimed Him because they had seen His wonderful works of healing and resurrection. They thought they were ready to accept Him as their king. In much the same way, when we have recognized the power of the Lord to make over the external life, to restore the faculties men have allowed to become sick and even to die through neglect or abuse, we think we are ready to welcome Him into our minds and hearts as king.

A king is one who rules, whose laws his people accept and obey, who is looked to as the final authority. If we really accept the Lord as our king, we will obey His laws and recognize Him as our final authority — we will not merely call upon Him to save us from the consequences of our follies and misdeeds. Are we ready to do this? The final test for us is pictured in the results of the Lord's entry into Jerusalem. The Lord's rule is not always what we want it to be. He does not support our selfish desires and ambitions. His law often cuts directly across the path we wish to follow, and says "Stop!" In our hearts and minds are "priests and Pharisees," selfish feelings and thoughts which do not wish to submit to the Lord's rule, as well as a few loving "disciples" who wish to see Him on the throne. The "multitudes" are all our everyday thoughts and affections, which are swayed this way and that according to the deep currents of our souls. Our final test as Christians is whether or not we allow ourselves to be persuaded by our hereditary selfishness. For if we do, we shall finally reject the Lord's rule, even though we have seen it to be right and best. A great many of us see that the Christian life is the right and happy life and are willing to correct our ordinary conduct according to Christian principles and to learn to live an outwardly orderly life for the sake of the obvious benefits which result from such conduct. We are anxious to call ourselves Christians, to acclaim the Lord as king, because we see what Christianity has done for the world and for individuals. But when we really try to open our hearts and minds and submit them to the Lord's cleansing control, we find the chief priests and Pharisees too strong for us and yield to their insistence that we free Barabbas and crucify the Lord.

In Zechariah 9:9 it is prophesied that the Lord would enter Jerusalem "riding upon a donkey, and upon a colt the foal of a donkey." We learn from the writings (@AC 2781) that the donkey (properly translated "she—donkey") and colt picture the natural man as to good and truth, and that the Lord's riding upon them not only shows that He claimed the prerogatives of king and judge but also represents the fact that He subordinated the natural planes of mind and heart to the divine. In Mark 11:2, and also in Luke 19:30, the colt is said to be one "whereon never man sat." The Lord alone completely reduced the natural plane to order and made it serve its true use. In the statement that the disciples placed their clothes on the donkey for the Lord to ride upon we see pictured the attitude of the true disciple who submits his own ideas to the Lord's government and correction. The same thing is represented by the fact that the multitudes "spread their garments in the way." Palm trees picture "spiritual good, or the good of truth" (@AC 8369). The palm branches which the people carried and strewed in the way of the Lord thus represent genuine affection for divine truth, through which alone the Lord can be victorious in anyone's life and reign there as king. For this reason the ancient Hebrews were commanded to bring palm branches at the feast of the ingathering (Leviticus 23:40), palm trees were carved upon the walls and doors of Solomon's temple (1 Kings 6:29, 32), and the multitude who stood before the throne in John's vision had palms in their hands (Revelation 7:9). It is also said of the righteous, those who practice the truth and so are in the good of truth, that they "shall flourish like the palm tree" (Psalm 92:12).

This was one of the first fruits of the Lord's entry into Jerusalem — He went into the temple and drove out the money—changers and overthrew the seats of those who sold doves, those who were profaning the temple by turning its worship to their own selfish advantage. The temple, the Lord's house, is the symbol of the church in each one of us. It is meant to be a "house of prayer." That is, the purpose of worship is to open the mind and heart to the Lord, acknowledging our weakness and need, and seeking instruction and help. But the temple had, both literally and figuratively, become a den of thieves. The sale of animals for sacrifice and the changing of ordinary money into the shekel of the sanctuary had come to be carried on for profit within the very court of the temple itself. And the scribes and Pharisees had come to use their outward piety to win reputation and power for themselves. The money—changers picture the use of the Scriptures for selfish ends, and the vendors of doves trading on pretended piety to win reputation and honor. Therefore the cleansing of the temple was one of the first things the Lord did after He entered Jerusalem as king. When the Lord is received into our inner lives as king, the selfish motives which have previously been in our religious life are exposed. Why have we called ourselves Christians? Has it always been from a genuine desire to learn of the Lord, to see our own faults, and to obtain the Lord's help in overcoming them? How often do we go to church to be seen of men? How often do we give because we are ashamed not to instead of because we really want to? How often do we sit in church and think how the sermon applies to someone else? The genuine recognition of the Lord leads us to recognize these attitudes of mind for what they are and to try with all our might to drive them out.

It is significant that the Lord did not spend the night in Jerusalem, but lodged with his friends Mary and Martha and Lazarus in Bethany. It is in our daytime states, when we are able to see clearly, that we make progress against our evils. And in the morning we have the incident of the fig tree. In the triad of olive, vine, and fig, the fig represents outward conduct, good in the outward life. And as the church of that day was a wholly external church, the fig tree was its special symbol. So the Lord's finding no fruit on the fig tree is symbolic of the fact that that church no longer bore its proper fruit and had come to its end as the representative of the Lord's church in the world. So the fig tree withered away. This little incident was a divinely appointed herald also of what the people were about to do to the Lord, destroying their own life by rejecting Him. We, too, die spiritually when we do not "practice what we preach."

---

<<<


=== From the Writings of Swedenborg

@AC 2781: "To 'ride upon a donkey' was a sign that the natural was made subordinate; and to 'ride upon a colt, the son of a she—donkey' was the sign that the rational was made subordinate ... From this their signification, and because it belonged to the highest judge and to a king to ride upon them, and at the same time that the representatives of the church might be fulfilled, it pleased the Lord to do this. ... From all this it is now evident that all and everything in the church of that period was representative of the Lord, and therefore of the celestial and spiritual things that are in His kingdom — even to the she—donkey and the colt of a she—donkey, by which the natural man as to good and truth was represented. The reason of the representation was that the natural man ought to serve the rational, and this the spiritual, this the celestial, and this the Lord: such is the order of subordination."

---

<<<


=== Suggested Questions on the Lesson

*Q:* (Younger Children): What is today called? +
*A:* Palm Sunday

*Q:* (Older Children): What does the day commemorate? +
*A:* the Lord's triumphal entry into Jerusalem

*Q:* (Younger Children): What did the Lord ride when He entered Jerusalem? +
*A:* a donkey

*Q:* (Younger Children): What did the disciples put on the donkey? +
*A:* their garments

*Q:* (Younger Children): What did the people strew before the Lord as He rode? +
*A:* palm branches and garments

*Q:* (Younger Children): What did the multitude cry? +
*A:* Hosanna!

*Q:* (Older Children): Where did the Lord go when He entered Jerusalem? +
*A:* the temple

*Q:* (Older Children): What did He do there? +
*A:* drove out money—changers and dove—sellers

*Q:* (Older Children): What did He say about the temple? +
*A:* it was to be a house of prayer

*Q:* (Older Children): What else did He do in the temple? +
*A:* healed the blind and the lame

*Q:* (Older Children): Where did He go to spend the night? +
*A:* Bethany

*Q:* (Older Children): Who lived there? +
*A:* Mary, Martha, and Lazarus

*Q:* (Younger Teens): What is pictured by the Lord's riding into Jerusalem on a donkey? +
*A:* that He alone had brought His natural reason under divine control

*Q:* (Younger Teens): What do the palm branches picture? +
*A:* that the Lord alone can save

*Q:* (Older Teens): What does it mean in our lives to accept the Lord as king? +
*A:* to acknowledge that His laws rule our lives and are to be obeyed


