= Bible Study Notes &#8212; Lesson 20
By Anita S. Dole



== Isaac and Abimelech

*Bible References:* Genesis 26:1-33

_This is a lesson excerpted from The Dole Bible Study Notes. There are more than 150 of these lessons, covering many of the great stories in the Bible. They were designed for use in Sunday Schools, but they're good for all ages — for self-study, for parents to use in home devotions, and for pastors and teachers. Here's a link to more information about them._

---
.*Contents:*
----
1. Introduction
2. Doctrinal Points
3. Basic Correspondences
4. Notes for Parents
5. For Young Children
6. For Older Children
7. For Young Teens
8. For Older Teens
9. For Adults
10. From Swedenborg's Writings
11. Suggested Questions
----

---

<<<


=== Introduction

We have already studied the best—known stories about Isaac.

For the two youngest classes the teacher should be prepared to retell very briefly the story of the birth of Isaac and of his marriage to Rebekah, and should then tell today's story as an example of his dealings with the people of the land. With the older classes, also, the life of Isaac should be reviewed briefly as an introduction.

---

<<<


=== Doctrinal Points
----
• The Abraham story teaches the way in which the Lord developed as a child, and this is continued in the stories of Isaac and Jacob.
• Nothing in the Word is accidental or unnecessary.
• We should not try to force our doctrines on those who do not want them.
• True rationality is based on the desire to learn and obey the truths of the Word.
----

---

<<<


=== Basic Correspondences
----
• Egypt = the plane of memory-knowledge
• the land of the Philistines = the knowledge of doctrinal things
----

---

<<<


=== Notes for Parents

The son born to Abraham and Sarah was Isaac, and we remember that Ishmael, who was fourteen years old when Isaac was born, mocked at the baby and as a consequence was sent away with his mother Hagar into the wilderness. This may at first seem to us a harsh punishment for a thoughtless act, but we can understand it if we realize the lesson it is given to teach us. We all have an "Ishmael" in us in our natural disposition to judge according to appearances and to discount the deep spiritual causes and principles. Our teenagers do this when they are so sure that they know better than their parents. We can see the folly of it in them, but do we always realize that it is exactly the same folly in us which makes us imagine that we know better than the Lord what is good for us?

Isaac, who was to be Abraham's heir, represents our maturer judgment, which develops late and grows up slowly under the Lord's guidance, and is steady and obedient. Our story today is a picture of how this higher judgment can direct our lives wisely even after the simple trust and obedience of childhood, represented by Abraham, is gone.

If you will read the Lord's words to the woman of Samaria in John 4:5-14, you will see that the Lord's truth in the Bible is the well to which we must go for spiritual cleansing and refreshment, the only water with which our thirst can be permanently satisfied. The stories of the Bible which we learned in early childhood are the wells dug by Abraham. We, like the Philistines, often fill these wells up with earth when, as we grow older, we let worldly ideas and desires discourage and destroy our belief in the Bible. Isaac, our more mature judgment, has to re-dig these wells. As he did this, the Lord could prosper him until even the king of the Philistines, who had at first tried to drive him out of the country, decided that it was to his interest to make peace with him. The people to whom we go for advice and help in our times of doubt and need are not those whose lives are controlled by selfish and worldly ambition, but those whose judgments are based on the deep and sure foundation of the Lord's precepts.

---

<<<


=== For Younger Children

[.underline]#*Teacher Notes:*# 
Teach the children the name Isaac and what it means. Tell the story of Isaac and then read the story for the day, explaining the importance of the wells and emphasizing the name Beersheba.

---
Where was Abraham's first home?

What did the Lord tell him to do?

Where did Abraham finally settle in the land of Canaan?

What was the one thing Abraham and Sarah wanted which they did not have?

Who came to Abraham with a message from the Lord?

What was the message?

Less than a year later Abraham and Sarah did have a son. They named him Isaac, which means "laughter." Abraham and Sarah were old when Isaac was born.

After Isaac grew up, his father sent one of his trusted servants on a long journey to the place called Haran where Abraham's brother Nahor had settled, to bring back a wife for Isaac from among his own relatives, because the people of Canaan did not worship the Lord, and Abraham wanted his son to have a wife who would not lead him away from the true worship. The servant brought back Rebekah, the granddaughter of Nahor, and Isaac loved her very much. Isaac and Rebekah had twin sons, Esau and Jacob. We shall hear more about them in our next lesson.

After Abraham died, Isaac became the head of the family, and the people of Canaan soon had to recognize that he was a great man just as his father had been.

Into whose country did he go in a time of famine?

Abimelech, king of the Philistines, was afraid of him and asked him to leave.

What did Isaac do in order to get water for his flocks and cattle?

Who had dug the wells in the first place?

What had the Philistines done to them?

Over how many wells did the herdsmen of the land quarrel with Isaac's herdsmen?

What did Isaac call the third well? Rehoboth means "room."

You see Isaac chose to let the Philistines have the first two wells rather than quarrel over them.

Then Abimelech came and asked Isaac to make peace with him, and they made a treaty and swore not to do each other any harm.

You see Isaac did not let his herdsmen keep on quarreling with the herdsmen of the land. He went on until he found a well which the others did not want. Then Abimelech realized that Isaac was not his enemy, and came and asked Isaac to make peace with him. You know that if you keep on quarreling with another child, someone always gets hurt in the end, and everyone is unhappy. But if one of you refuses to go on quarreling and just walks away and does something else, the one who is left is likely to want to make up. So when a quarrel begins, try to remember that it is always the one who has the most sense who stops first.

---

<<<


=== For Older Children

[.underline]#*Teacher Notes:*# 
The general story of Isaac up to the beginning of our lesson should be reviewed briefly. If the children ask why Isaac lied about his wife, call their attention to the two similar stories about Abraham (Genesis 12:10-20; 20:1-11) and tell them that the explanation is in the spiritual sense, which they will study when they are older. The story of the wells is the important part of the lesson for the Older Children, and an attempt should be made to fix Beersheba in their minds.

---
Abraham had been recognized by all the people of the land as a great man. He had made agreements with the kings among whom he lived and had found plenty of pasture and water for his flocks and herds. Isaac was now head of the family, but the people of the land did not know him as they had known Abraham and they thought that they might safely take advantage of him. You remember that when Abraham first came into the land there was a famine and he had to go down into Egypt for a time. Now there is another famine, but the Lord tells Isaac not to go to Egypt.

Where did Isaac go?

What was the king of the Philistines called?

What did Isaac tell the people about Rebekah?

How did Abimelech find out that she was Isaac's wife?

Did Isaac prosper in the Philistine country?

What had happened to the wells which Abraham had dug there?

Why did Abimelech want to send Isaac away?

Why could Isaac not use the first two wells which his servants dug?

What happened when they found the third?

What agreement did Isaac and Abimelech make?

What did Isaac call the place where it was made?

Now read Genesis 21:22-32. It is thought that the word Abimelech, which means "father of a king," was not the name of one person but of a whole line of kings of the Philistines. Abraham had made an agreement with the Abimelech of his day just as Isaac did now. Shebah or Sheba means "oath" and Beer means "well"; so Beersheba means "the well of the oath." Look on a map and find the Philistine country along the shore of the Mediterranean Sea. We shall hear a great deal about the Philistines. Now find Beersheba. We may think of it as the southernmost city of the Holy Land. The northernmost city was Dan. So the expression "from Dan to Beersheba," which we find several times in the Bible, means the whole length of the land. Isaac's agreement with Abimelech at Beersheba established him with the people of the land as a great man, just as his father had been.

---

<<<


=== For Younger Teens

[.underline]#*Teacher Notes:*# 
The teacher should review very briefly the story of Isaac from his birth to the time of our lesson. The principal emphasis of this lesson should be placed on the meaning of Isaac in our lives, on why Isaac prospered in the Philistine country more than the Philistines themselves, and on the meaning of the wells and what happened to them. The teacher should be familiar with the interpretation of the incident concerning Rebekah as found in the Older Teen and Adult notes, and should be prepared to touch upon it if the young people are curious to understand more than is given in their own notes.

---
Abraham represents our spiritual state in infancy and early childhood. It is a beautiful state, and yet we know that we all expect and want little children to grow up. If they are to take their true places in the world, they must learn to think and act for themselves. The period of learning to think and reason is pictured in the Word by the stories of Abraham's sons, Ishmael and Isaac.

Ishmael, you remember, was not Sarah's son. His mother was Sarah's Egyptian bondwoman Hagar. There is a great deal in the Bible about the land of Egypt. Egypt, because of the river Nile, did not depend on rainfall for its fertility, and so there was always grain in Egypt even when other countries were suffering from drought and famine. Egypt represents the plane of memory-knowledge. We can store our minds with facts even when we are not able to understand and use them. Ishmael, born of an Egyptian mother, represents the beginning of our thinking and reasoning power, when we judge by what we see and hear in the natural world without understanding the causes that are within and above what we see.

But after a while we begin to find that things are not always just what they seem to be. Our senses sometimes deceive us. Our plans do not turn out as we expected. There are spiritual laws which must be learned and obeyed. When we see this, Isaac is born. In our lesson for today there is a famine in the land of Canaan, just as there had been in the time of Abraham; but the Lord tells Isaac not to go down into Egypt as his father had done. Our higher reason must not depend on the kind of knowledge which concerns this world only. We must learn doctrine concerning the Lord and spiritual life. This kind of knowledge is represented by the land of the Philistines.

Now notice in our story the difference between the Philistines and Isaac. Isaac prospered so greatly in the Philistine country that the Philistines envied him and wanted him to leave their land. The Philistines picture the kind of people who like to know what the Bible teaches and to talk and reason about it but do not try to live according to its teachings. Isaac pictures those who try to learn and understand the same things, but for the sake of living as the Lord wants them to live. So Isaac prospered and became rich in the Philistine country.

Another thing in our lesson which shows the difference between the Philistines and Abraham and Isaac is the statement that the Philistines filled up with earth the wells which Abraham's servants had dug. Water, you know, represents truth. In the Word, a well represents the truth as we find it in the Bible. The wells which Abraham and Isaac dug picture the Bible when it is studied as the Word of the Lord for the sake of life. To fill these wells up with earth is to stop the truth from appearing in the Word by preferring our own opinions to the Lord's guidance. And you notice that the Philistines claimed two of the wells as their own. When people think that the Word was made up by men instead of inspired by the Lord, they cannot find its truth. All they see is their own ideas. We all have this tendency, which comes from our natural self-love. You know that when you start to argue with someone, you seldom really listen to what he is saying: you think only about making him agree with you.

Isaac's apparent deceit in telling Abimelech that Rebekah was his sister is something you will understand better when you are older. But you should know that this is the third time such a thing has happened in the Bible story. Abraham earlier told Abimelech that Sarah was his sister, and still earlier in Egypt he told Pharoah the same thing. We find these two stories in Genesis 20:2-7 and 12:11-20. Swedenborg points out that the fact that this incident is repeated three times in the Word shows that it has a very deep and important meaning. You will see that this is an illustration of what we were saying just now — that things are not always what they seem.

This is also the second time that an agreement has been made at Beersheba. Read Genesis 21:22-31. Beer means "well," and Sheba means "oath," and so Beersheba means "the well of the oath." It was the southernmost city in the Holy Land.

Those who think that the Word is the product of men sometimes argue that these repetitions are mistakes — something put in by the scribes who copied the Scriptures. This is one of the ways in which the well of truth is stopped up with earth. The Lord makes no mistakes.

---

<<<


=== For Older Teens

[.underline]#*Teacher Notes:*# 
The development from Abraham through Ishmael to Isaac should be explained clearly as a preparation for understanding the meaning of Isaac's dealings with the Philistines. The important lesson is the difference between an intellectual interest in the Word and going to the Word and studying it to find out how to live.

---
Our true spiritual progress comes through Isaac, our spiritual rational faculty. If we are developing properly, Abraham gives all that he has to Isaac and dies, as we are told in Genesis 25:5-9, and Ishmael and Isaac bury him. It is after this that Isaac and Rebekah have their twin sons, Esau and Jacob.

Then comes our story for today. There is a famine in the land, just as there had been when Abraham first came there. Abram had gone down into Egypt, and we remember that this pictured our need in early childhood for acquiring all kinds of natural know]edges. But Isaac is told by the Lord not to go to Egypt, and instead he goes to the land of the Philistines. This is because natural knowledges are not the basis of spiritual reasoning. The land of the Philistines represents knowledges of doctrine.

We find that Abraham had in his time made a treaty with Abimelech, king of the Philistines, and had dug wells in the Philistine country; but after the death of Abraham the Philistines had stopped these wells and filled them with earth. The Philistines themselves represent those who like to learn doctrine but make no attempt to live according to it. When we are little children in the Abraham state, we learn — among other natural knowledges — stories from the Word and the lessons drawn from them by our elders. These are Abraham's wells. But often, as we begin to assert our own wills, these wells are stopped up with the earth of our own worldly and selfish ideals. We rebel against going to Sunday school and church. We stop saying our prayers. We think we know enough to take care of ourselves without the Lord.

When Isaac develops in us, we have to go down again into the Philistine country and re-dig the wells. Some of them we cannot reclaim because the Philistine hold on them is too strong, but eventually, if we persist, we find one we can develop, and then Isaac can renew the oath made between his father and Abimelech. Beersheba means "the well of the oath." In the Word, a well is frequently used as a symbol of the Bible, because we draw truth from the Bible just as one draws water from a well. If we are to become regenerate, we must keep on searching until we find a doctrine which enables us to understand the Bible and to see the Lord's truth in it.

One part of our chapter often puzzles people. Isaac in the beginning deceives Abimelech by saying that Rebekah is his sister. Abraham had said the same to Pharaoh about Sarah and repeated it later to Abimelech (Genesis 12:11-20; 20:2-7). Critics of the Bible have sometimes thought that these repetitions were mistakes of the scribes who copied the Scriptures, but this is a case of the Philistines' filling a well with earth. Swedenborg says: "As the same thing occurred three times, and is three times repeated in the Word, it is evident that there is in it an arcanum of the greatest moment, which can never be known to anyone except from the internal sense" (@AC 3386). In the internal sense a sister pictures rational truth, but a wife pictures truth united to good. People in the Philistine state are interested in learning rational truth; but because they have no desire to apply rational truth to their own conduct, they would destroy the same truth if it were presented to them as something they ought to do. This meaning is not so hard to understand as you might think. We all enjoy learning new things, but do we always welcome good advice?

---

<<<


=== Adult

[.underline]#*Teacher Notes:*# 
We should be able to take it for granted that the adults know the general story of Isaac, and so the teacher may concentrate on the specific lesson, which is an important one often overlooked.

---
All adults who have brought up children or who have observed the development of any child from infancy through the early "teens" should be able to draw upon their experience for help in understanding our lesson for today and its background. The keynote of the lesson is to be found in the wells. Throughout the Bible a well is the symbol of the Word. We dig wells when we go to the Word for truth. Without the Word our lives are barren.

Abraham had dug wells in the Philistine country. In early childhood we learn the stories of the Word and are given instruction from them. But as we develop out of the innocent childhood states, as we learn more about the world and its standards and begin to reason from appearances — the Ishmael state — the Philistines stop up these wells of truth and fill them with earth. The Philistines lived in the Holy Land along the coast. Their part of the country pictures knowledge of doctrine, but the Philistines themselves represent "the memory-knowledge of knowledges," the knowledge of spiritual truths held in the memory but not used in life. We all have the Philistines in us, for we all know more truth than we are willing to use. Whenever we know what we ought to do but reason ourselves out of doing it because it is not convenient, the Philistines in us are stopping up Abraham's wells and filling them with earth.

In @AC 2083 Swedenborg shows us very clearly the nature of the progression from Abraham through Jacob in the Lord's own experience, which is our pattern: "Abraham, as said in various places before, represents the Lord's internal man, but Isaac His rational man, and Jacob His natural man. The Lord's internal man was Jehovah Himself. His rational man, because conceived of the influx of His internal man into the affection of memory-knowledges in the external man, was from the Divine thus conjoined with the Human. Hence the first rational, represented by Ishmael, was human; but it was made Divine by the Lord, and then it is represented by Isaac." So in our lives our first reasoning, although a faculty given us by the Lord, is exercised on the basis of natural knowledges and must later be corrected as we learn by experience that appearances are often deceiving and that spiritual causes and principles are the only true basis of rational thought. Wise parents recognize the "difficult" years in their children as merely a necessary step in their growing up, and draw a breath of relief when they see the first signs of maturer judgment.

It is interesting to note that Sarah dies some time before Abraham. Sarah, Abraham's true wife, represents the genuine affection for truths received in the simplicity of childhood. The child outgrows this affection when he begins to want to do his own thinking, but the good intention of childhood persists, joining itself to a different type of affection for truth — comparatively obscure — which is represented by Keturah, whom Abraham married after Sarah's death. Modern psychiatry, which delves into the inner experiences of the childhood of an individual, might well study the six sons of Abraham and Keturah and their descendants. They appear from time to time throughout the Old Testament story, usually as enemies of the descendants of Isaac, but we note in Genesis 25:5 that "Abraham gave all that he had unto Isaac." All our spiritual progress depends upon the development of the true rational whose judgments are based without equivocation upon the truths of the Word.

Abraham and Isaac both swore a covenant of peace with Abimelech, king of the Philistines, who represents "the doctrine of faith that looks to rational things." The truly spiritual man has no quarrel with interest in doctrine and reasonings about it. It was the Lord who sent Isaac down into the Philistine country in time of famine — to knowledges of doctrine, not to the mere natural knowledges represented by Egypt — and prospered him there. Isaac was even led to repeat the ruse twice practiced by Abraham (Genesis 12:11-20; 20:2-7) and to represent Rebekah at first as his sister. The difference between Rebekah as a sister and Rebekah as a wife is the difference between the affection for spiritual truth as an intellectual exercise and affection for the same truth for the purpose of directing the life. Swedenborg points out that with those who do not wish to change their ways of life, spiritual truth will be rejected if it is presented first as an exhortation to good, whereas in its merely intellectual aspects they may find it interesting and pleasing, and after it is accepted intellectually it may gradually affect the life. We should remember this in our missionary efforts.

Beersheba — "the well of the oath" — became Isaac's home. It is the southernmost city of the Holy Land, and we recall that the north and south direction is the measure of the extent of enlightenment, the north representing ignorance and the south enlightenment; so it is clear that Isaac's settling in Beersheba, digging a well and building an altar there after his covenant with Abimelech, gives us the true pattern of spiritual enlightenment which is the necessary basis for a good life, both external and internal.

---

<<<


=== From the Writings of Swedenborg

@AC 3464: "As regards the doctrinal things that are from the literal sense of the Word, the case is this: When a man is in them, and at the same time in a life according to them, he has a correspondence in himself; for the angels who are with him are in interior truths, while he is in exterior ones, and thus through the doctrinal things he has communication with heaven, but according to the good of his life. As, for example, when in the Holy Supper he thinks in simplicity of the Lord from the words then used — 'This is My body, and this is My blood' — the angels with him are in the idea of love to the Lord and charity toward the neighbor; for love to the Lord corresponds to the Lord's body, and to bread; and charity toward the neighbor corresponds to the blood, and the wine ... and because there is such a correspondence, there flows an affection out of heaven through the angels into that holy state in which the man then is, which affection he receives in accordance with the good of his life. For the angels dwell with everyone in his life's affection, thus in the affection of the doctrinal things according to which he lives; but in no case if his life disagrees therewith; for if the life disagrees, as for instance if he is in the affection of gaining honors and riches by means of doctrinal things, then the angels retire, and infernals dwell in this affection, who either infuse into him confirmations of the doctrinal things for the sake of self and the world, thus a persuasive faith — which is such that it is regardless whether a thing is true or false provided it captivates the minds of others - or else they take away all faith, and then the doctrine of his lips is only a sound excited and modified by the fire of these loves."

---

<<<


=== Suggested Questions on the Lesson

*Q:* (Younger Children): Who was the son of Abraham and Sarah? +
*A:* Isaac

*Q:* (Younger Children): Who was Isaac's wife? +
*A:* Rebekah

*Q:* (Younger Children): What place did she come from? +
*A:* Haran

*Q:* (Younger Teens): What children did Isaac and Rebekah have? +
*A:* Esau and Jacob

*Q:* (Older Children): In time of famine where did the Lord forbid Isaac to go? +
*A:* Egypt

*Q:* (Older Children): Where did Isaac go instead? +
*A:* Philistia

*Q:* (Older Children): What was the king of the Philistines called? +
*A:* Abimelech

*Q:* (Younger Children): Did he welcome Isaac? +
*A:* yes, but later feared him

*Q:* (Younger Children): Who had previously dug wells in the Philistine country? +
*A:* Abraham

*Q:* (Younger Children): What had the Philistines done to these wells? +
*A:* filled them in

*Q:* (Younger Children): How many wells did they prevent Isaac from opening? +
*A:* two

*Q:* (Younger Children): Did Isaac quarrel with them? +
*A:* no

*Q:* (Older Children): What agreement did Abimelech finally make with Isaac? +
*A:* oath of peace

*Q:* (Older Children): What did they name the place where the agreement was made? +
*A:* Beersheba

*Q:* (Older Children): What does Beersheba mean? +
*A:* well of oath

*Q:* (Younger Teens): What does Isaac represent? +
*A:* our ability to reason spiritually

*Q:* (Younger Teens): What does a well represent? +
*A:* the Word

*Q:* (Older Teens): What do the Philistines picture? +
*A:* desire to know truth, but no desire to live it

*Q:* (Older Teens): What is pictured by their filling up Abraham's wells with earth? +
*A:* preferring one's own opinion to the Lord's guidance


