= Bible Study Notes &#8212; Lesson 26
By Anita S. Dole



== Joseph in Prison

*Bible References:* Genesis 39; 40

_This is a lesson excerpted from The Dole Bible Study Notes. There are more than 150 of these lessons, covering many of the great stories in the Bible. They were designed for use in Sunday Schools, but they're good for all ages — for self-study, for parents to use in home devotions, and for pastors and teachers. Here's a link to more information about them._

---
.*Contents:*
----
1. Introduction
2. Doctrinal Points
3. Basic Correspondences
4. Notes for Parents
5. For Young Children
6. For Older Children
7. For Young Teens
8. For Older Teens
9. For Adults
10. From Swedenborg's Writings
11. Suggested Questions
----

---

<<<


=== Introduction

A short review of the last lesson will lead easily into the story of Joseph. For the background of today's lesson the important points to bring out are the length of time Jacob stayed in Haran, the number of sons born to him there, the fact that Joseph was Rachel's son, and the reasons why his older brothers hated him. In all the older classes mention the meaning of the series Abraham, Isaac, and Jacob, and recall the meaning of Egypt which they learned in connection with the story of Abram and Lot. All the classes above the Younger Children should be fairly familiar with the general outline of the Joseph story. It is a long and interesting one, and the events are so closely connected that it is hard to pass over any of it. If the teacher prefers, he may tell the whole story very briefly before concentrating on the events of these two chapters.

---

<<<


=== Doctrinal Points
----
• The Lord preserves and strengthens our spiritual affections even when we try to forget that we have them.
• The story of Joseph has a close relationship to the life of the Lord.
• So it helps us to see how closely the Old and the New Testaments are bound together.
• Truth is necessary to protect good.
• Obedience to the Lord enables one to receive understanding.
----

---

<<<


=== Basic Correspondences
----
• bread = goodness
• wine = truth
----

---

<<<


=== Notes for Parents

Most people are familiar with the beautiful story of Joseph.

He is an example of a man who remained faithful and upright in the face of the severest trials, and the lesson is one from which we can all profit. The Lord can be with us only as we look to Him for help and keep His commandments. When we do wrong, there are always consequences which cannot be averted. Joseph went through some hard experiences, but his brothers were much worse off because they had guilty consciences to bother them. As we read the rest of the story, in chapters 41 to the end of Genesis, we find that Joseph, because of his character, is in a position of control in every situation. The brothers, on the other hand, are afraid at every unexpected turn of events. Read chapter 42, verses 21 to 24, and see the difference between them.

Joseph represents something in the life of every one of us — the voice deep within us which tells us that the most important thing in the world is to do right in the sight of God, whatever may happen to us. We sometimes try to silence that voice and think we have succeeded, but it is there just the same. The brothers were never really happy until they found Joseph again and realized that he had forgiven them and wanted to take care of them. The Lord takes care of us if we let Him.

---

<<<


=== For Younger Children

[.underline]#*Teacher Notes:*# 
The Younger Children class needs to know that Joseph was Jacob's favorite son and the reason why his brothers were jealous of him. Then read them verses 8 through 23 of chapter 40. You will probably have to explain what a butler is. More of the beginning of the Joseph story should then be given. Stress the fact that the Lord was with Joseph so that he prospered in spite of everything that was done by his enemies. Tell the class also the end of his story and how he forgave his brothers and took care of his whole family.

---
Today we have a story about Joseph, Jacob's favorite son. Joseph had ten older brothers and they hated him, partly because his father loved him best and partly because he was brighter and more unselfish than they were, and the Lord gave him some wonderful dreams which showed that he was to be greater than his brothers and even greater than his father and mother. The Lord also gave him power to interpret dreams — that is, to tell what dreams meant.

One day, when his brothers were all tending their flocks away from home, the older brothers decided to get rid of Joseph. First they thought they would kill him, but then they decided it would be better to sell him. They sold him to a caravan of Ishmaelites, who were on their way to Egypt. In Egypt Joseph was sold to a man named Potiphar, who was captain of the king's guard. The king of Egypt was always called Pharaoh.

Joseph was always faithful to the Lord and honest in everything he did, and the Lord always took care of him. Potiphar made him ruler over his household, but Potiphar's wife became angry with Joseph and told her husband lies about him, and Potiphar believed his wife and put Joseph in prison.

Even in prison Joseph made such a good impression on his keepers that they put him in charge of all the other prisoners.

Two of Pharaoh's servants were in prison at the same time.

Who were these two servants?

Why did they come to Joseph one day?

What did Joseph tell them about the interpretation of dreams?

What was the chief butler's dream?

What did Joseph tell him it meant?

What was the chief baker's dream?

What was Joseph's interpretation of it?

How did the interpretations come true?

What did Joseph ask the butler to do for him?

Did the butler remember?

Although the butler forgot Joseph as soon as he was free, later - when Pharaoh himself had a strange dream which none of his wise men could interpret — the butler remembered Joseph and told Pharaoh about him. Joseph was taken out of prison and was able to interpret Pharaoh's dream; so Pharaoh decided this was a very wise man, and he made him ruler — under himself — of all Egypt. So some time afterward, when there was a great famine in the Holy Land, Joseph was able to save his father and his brothers and their families, and Pharaoh invited them to come to Egypt to live during the famine, and gave them the best part of the land to live in.

---

<<<


=== For Older Children

[.underline]#*Teacher Notes:*# 
Discuss especially the reasons why Joseph was disliked by his brothers and point out how liable we are to belittle people who seem to be different from ourselves. Joseph's uprightness and desire to serve the Lord should be cited as the reason why the Lord could take care of him and why he always rose to positions of trust and authority. Try to cover the whole story of Joseph, getting as much as possible from what the class themselves remember from former years.

---
Of all his sons Jacob loved Joseph best and this made the older sons jealous. Also Joseph was different from the others. The Lord was with him especially and he had dreams which showed him that he was to be greater than his brothers or even his father and mother. The brothers hated him for this, also. They stripped him, threw him in a pit and plotted to kill him, but finally decided to sell him instead. While they were making their plans, caravans of Ishmaelites and Midianites, on their way to Egypt, came to the pit and drew Joseph up out of the pit, and took him to Egypt with them. Our lesson today begins with the selling of Joseph to Potiphar, captain of the king's guard in Egypt.

The Lord was with Joseph. Read Genesis 45:4-8, which tells of his reunion with his brothers many years later and his forgiveness of them. Wherever Joseph went, the Lord was with him no matter how hard his outward condition might be. We can see this in our story today. Joseph's ability and honesty at first led Potiphar to advance him until he was ruler over all Potiphar's household. But again someone plotted against him.

Who was it this time?

Potiphar believed his wife's story. What did he do with Joseph?

Yet you see that even in the prison Joseph's ability and honesty attracted attention and led the keeper of the prison to put him over the other prisoners. Even today men who have really committed crimes, if they show a disposition to obey the prison authorities and to improve, are made "trusties" and given certain privileges. Joseph had done no wrong.

Which servants of Pharaoh were in the prison at the same time?

Pharaoh is the name by which all the kings of Egypt were called, just as we call the head of our government President, no matter what his own name is.

What led the chief butler and the chief baker to come to Joseph for help?

What did Joseph tell them about the interpretation of dreams?

You see the real difference between Joseph and other people was that Joseph knew that all goodness and wisdom and power were in the Lord and not in himself, and he looked to the Lord for guidance and tried to serve Him. So the Lord could show Joseph what was true and right.

What was the chief butler's dream about? What did Joseph tell him it meant?

What was the chief baker's dream about? What did Joseph tell him?

Did the dreams come true?

There is something in the literal story which may show us the difference between these two men. The butler was willing to tell Joseph his dream as soon as Joseph said that interpretations belonged to God, but the baker waited until he found that the interpretation of the butler's dream was good before he told his dream. That is, the baker was willing to let God into the picture only when he thought it would be profitable to him. We are sometimes like the baker: we like to hear good things about ourselves, but we don't want to be told when we have not been good.

What did Joseph ask of the butler?

Did the butler remember?

Sometimes we promise things when we are in trouble and want help, and then forget all about our promises after the trouble is over.

But the butler did remember later. Pharaoh had a dream which no one could interpret, and that reminded the butler; and, because he was really a good man, he was sorry he had forgotten his promise. Read Genesis 41:9-13. Pharaoh sent for Joseph, and because Joseph could interpret his dream, he made him ruler under himself over the whole land of Egypt. Later, when famine came, Joseph was able to invite his father and his brothers and all their families to come and live in Egypt until the famine was over. So he saved their lives, and helped them to settle in the best part of Egypt - the land of Goshen. The hard things which had happened to Joseph enabled him to be of great service to the others. But this would not have been true if Joseph had not wanted to serve the Lord and the neighbor. If we have this good desire, everything that happens to us can be turned by the Lord into a means of making us better and stronger men and women, and more useful to the world.

---

<<<


=== For Younger Teens

[.underline]#*Teacher Notes:*# 
This class can understand the meaning of Joseph as distinct from his brothers. They all have Joseph in them and if they can see what is meant by trying to get rid of him and by putting him in prison, it may help them to meet some of the temptations to selfishness and worldliness which come with the modern environment.

---
Jacob's twelve sons picture all of our faculties and affections through which we may serve the Lord. The highest of these faculties develop last, because we have to learn to live in this world before our minds are free to think deeply of spiritual things. This does not mean that we do not need to know what is right and try to do it all along, but it is easier to do right in our outward life than it is to think and to feel right.

Joseph was different from his brothers and had dreams which told him that he was to be greater than they; this caused his older brothers to be jealous of him and to try to kill him. Joseph pictures a desire to be truly good in the Lord's sight. It does not come to us until we have had a good deal of experience in trying to lead successful lives. When it does come, we are ready to go back to the Holy Land; but all the faculties and affections which we have developed before it, which are centered on the things of this world, resist being governed by it. The Lord protects our "Joseph" as He protected the Joseph of the Bible story, and does not let it be killed. But for a long time we may put it away in the back of our minds and go on living as if it were dead. This is the time in our lives when Joseph is in prison in Egypt. Egypt in the Word is the land of "memory-knowledge": that is, all the body of facts stored up in our memories.

Even in this land of memory-knowledge, Joseph easily became a great man. I wonder if we can see how this is. When once we have felt the desire to be truly good, we can never again think of the world around us as something just created for our benefit. We know that there are higher things than having good food and clothes and money to spend, and even though we don't yet really want to be unselfish, we know that unselfishness is best and we can see and appreciate it in other people. We can see the use which trouble and temptation and hard work and disappointments serve, and things in life fall into their true order in our minds. So Joseph was able, even while he was a servant in Egypt, to rise to a position of control over the household of the master. Then came the effort of Potiphar's wife to make him do what he knew to be wrong. The desire to be good cannot be used in this way, and our selfish desires try to shut it up so that it won't bother us. Joseph is cast into prison.

The butler and the baker were servants of Pharaoh, king of Egypt. They represent our senses, which serve us while we are in this world. The Lord, when He instituted the Holy Supper, said that the bread was His body and the wine His blood. Bread pictures goodness and wine truth, and the Lord's body and blood are the divine goodness and truth which nourish us if we accept them from Him. When the butler and the baker came to Joseph for the interpretation of their dreams, he told them that interpretations belonged to God; that is, that only a knowledge of the Lord's truth could show them the meaning of what happened to them. In the butler's dream he was making the wine perform its proper use, pouring it into his master's cup; but in the baker's dream the birds were carrying off the bread from his basket before it reached his master's table. So the dreams meant that the butler would be restored to his proper place but the baker would have to die. This is a very important lesson for us. When our senses perform their true use of bringing truth into our minds so that we can serve the Lord more intelligently, all will be well with us. But when we let false ideas, like the thieving birds, take away our goodness, our senses are no longer true servants and what they tell us is destructive to our spiritual life. An example of this is found in the kind of books we choose to read. If we choose good, wholesome books which give us a picture of life as it ought to be, our minds remain clean and healthy; but when we read bad books, we take into our minds ideas which steal away our good affections and destroy our souls. Our Joseph — our honest desire to be good in the Lord's sight — tells us truly what will happen to us. This is proved many times in our experience. Sometimes, when everything is going well with us, we — like the butler after he had been restored to favor — forget all about Joseph down in his prison. But the time comes again, as it did later in the Bible story, when something reminds us, and then we are sorry for our forgetfulness, and Joseph is brought out of prison and set over our whole life.

The story of Joseph is a beautiful story and one which will mean more and more to you as your experience grows. You need to know it well and to read it often. You will find also that it is a picture of the Lord's life when He was on earth, and that many of the things that happened to Joseph are very similar to things that happened to the Lord. Joseph is one of the people in the Bible who most clearly picture the Lord.

---

<<<


=== For Older Teens

[.underline]#*Teacher Notes:*# 
A good lesson for the Older Teens is found in the power of Joseph to interpret dreams. Only our recognition of the Lord and of His power in the life can give us an understanding of the experiences we have and enable us to be of real help to other people. People who persist in keeping Joseph shut up in the back of their minds are left to their own imaginations, and one man's guess is then as good as another's as to the meaning and purpose of life. Young people should be led to feel that it is a sad thing for people to be in spiritual darkness.

---
Swedenborg explains the meaning of Joseph in various ways.

Perhaps the simplest is in @AC 3969, where he says that Joseph represents "the good from which is truth." We may think of this as the deep desire to be good in the Lord's sight rather than merely in the sight of men. It is this desire which leads us to read and study the Word and to accept correction from it in our own feelings and thoughts as well as in our outward lives. You remember that when Joseph's older brothers saw him coming, they said, "Behold, this dreamer cometh." (Genesis 37:19) This was because Joseph had had dreams which showed him that he was to be greater than any of his brothers and even than his father and mother. Our spiritual affections are greater than our natural affections, but the natural affections resist the thought and try to put it out of sight "in the back of the mind." The brothers first put Joseph in a pit and then he was sold into Egypt. Egypt is the land of "memory-knowledges," as we remember from the story of Abram. We need memory—knowledges, but we should not be bound by our knowledge of natural science so that we reject spiritual truths.

Joseph had the power to interpret dreams; that is, to see the true meaning and effect of the experiences that come to us. This power comes to us from the genuine desire to do right in the Lord's sight. Sometimes, perhaps for a long time, it makes us uncomfortable and we try to shut it up. It is so much easier and more pleasant to forget about right and wrong and go on getting what we can of fun and satisfaction for ourselves without looking at our spiritual future at all. But the Lord protected Joseph in Egypt. First he rose to favor in the house of Potiphar, captain of the king's guard. Even in our time of most complete devotion to worldly pursuits we can see that it is to our advantage to go to church and to associate ourselves with churchgoing people. Eventually, however, this association with religion comes into conflict with our selfish affection — pictured by Potiphar's wife — which is trying to use religion selfishly and wants to control our higher impulses. Then we put away our religious feeling still more deeply. Joseph is cast into prison.

Pharaoh's chief butler and chief baker were also in prison. Pharaoh represents the principle which is at the moment ruling over the things in our memories — sometimes the Pharaoh is a good ruler and sometimes an evil one. His servants are the bodily senses which bring into the mind facts necessary to maintain it. In the Holy Supper the bread represents goodness and the wine truth. The butler represents those senses which bring in things which affect the intellect, while the baker represents those senses which primarily move the will. Our senses are orderly servants when their ministrations lead us to truth and good, disorderly when they deceive us and lead us to evil. It is significant that when Joseph said, "Do not interpretations belong to God?" the butler did not hesitate to tell his dream, but the baker waited until he found that the interpretation of the butler's dream was good. The butler in his dream was pouring wine into Pharaoh's cup, performing his proper use; but in the baker's dream birds were stealing the bread before it reached Pharaoh. We may think here of the parable of the Sower and the wayside, or hard—trodden path, which offered no soil for the seeds so that the birds of the air carried them off. These are birds in a bad sense, or falsities which destroy goodness before it is taken into the life.

The whole story of Joseph is especially important for young people just starting out in life. The temptation is to become so absorbed in the life of the world, in the occupation or studies chosen, that the thought of religion is put away into the memory instead of being kept in the forefront of the daily life. But Joseph was to be the savior of his people; in time of famine they were to come to him for food and protection. Sooner or later in life come troubles which cannot be met except in the light and strength of faith in the Lord. The Lord preserves our "Joseph," however we may try to get rid of him, until the time when we seek him out and put ourselves under his protection.

---

<<<


=== Adult

[.underline]#*Teacher Notes:*# 
The meaning of Joseph's imprisonment in Egypt and of the dreams of the butler and baker should be discussed in their application to our own states of temptations in the present materialistic age. The teacher will find excellent discussion material in @AC 5077-5078.

---
The stories of Joseph are among the best—loved in the Bible.

This is partly, no doubt, because of their variety and dramatic qualities, and partly because our sense of justice is satisfied by the triumph of right in spite of scheming and persecution. We know, however, that the real power in them comes from the fact that they picture states through which the Lord passed during His life on earth, and states through which we all pass in our youth, as well as repeatedly throughout our lives as we feel the temptation to stifle our spiritual promptings in the face of the pressure of our worldly environment.

We recall that Joseph was the eleventh son of Jacob and the first son of Rachel, the last of Jacob's sons to be born in Haran before they returned to the Holy Land. Jacob and his sons represent development of the church on the natural or external plane. His two wives, Leah and Rachel, represent affection for exterior truth and affection for interior truth. Jacob loved Rachel first but was given Leah instead, and he had six sons by Leah before he had any by Rachel; and, although Jacob at first was angry at Laban's deception, we find (Genesis 30:2) that after he had had four sons by Leah, he was angry with Rachel because she complained of her childlessness. So the natural man catches a first vision of a higher spiritual state, but readily settles down into satisfaction with external accomplishment. The sons of Jacob represent the gradual development of orderly living on the natural plane until, with Joseph, there is a beginning of true spiritual feeling, which is followed by the birth of Benjamin — its complementary truth — after the return to the Holy Land. Benjamin was born near Bethlehem and Rachel died at his birth. Jacob settled down with Leah and eventually they were both buried in the cave of Machpelah with Abraham and Sarah, Isaac and Rebekah. This would indicate that Jacob's glimpse of something higher than the external order did not take very deep root in his life, and that Leah was actually his true wife. Nevertheless, Joseph remained his favorite son. Do we not see this illustrated in the case of many people who live orderly external lives? The external life satisfies them and they do not really wish to think more deeply: yet they like to remind themselves of a higher possibility within them which they recognized in their youth.

The representation of Joseph is described by Swedenborg in several phrasings: "the Lord's spiritual kingdom," "the spiritual man," "the celestial spiritual man," "the charity from which is faith, or the good from which is truth." In the Lord's life Joseph represents the "Divine Spiritual." In our lives we can perhaps best think of him as our inner desire to be good in the Lord's sight rather than just in the sight of our neighbors. Joseph is the "dreamer" who was disliked by his brothers because his dreams showed that he was their superior. We really know that this higher urge is the true ruler of our lives, but we rebel against the thought. Joseph also had the power to interpret dreams. That inner voice which brings the Lord before our minds is able to point out the true meaning of life and all its experiences. The Lord sees to it that each of us has his "Joseph," and that it is preserved no matter how hard we try to stifle or even destroy it. And if we come to the realization of our need, as Jacob and his sons did in the time of famine, we are enabled by the Lord to dig down into our memories and find our "Joseph" not only still alive but in a position to save and protect us.

Our lesson today finds Joseph a slave in Egypt. Egypt, we remember, is the land of memory-knowledge. How often we relegate our Joseph to the land of memory-knowledge! Joseph was first sold to Potiphar, captain of the guard of Pharaoh. Because the Lord was with Joseph, under him Potiphar's affairs prospered and Potiphar advanced Joseph to charge over his household. The very fact that we have deep within us the recognition of our duty to the Lord serves to bring a type of order into our external lives, even though we do not understand the source of our outward success. But Potiphar's wife, who represents the affection which belongs to natural truth, is not satisfied. She wants to own Joseph. We see this temptation in the effort of the natural mind to explain away spiritual causes and to reduce everything in life to the level of the finite human rationality. Joseph resists and leaves the house, but his garment is left in the hand of Potiphar's wife and she uses it as evidence against Joseph. Garments represent outmost truths; Joseph's garment — like the Lord's nearly two thousand years later — represents "the ultimate of spiritual truth," the letter of the Word. Think how at times the letter of the Word is used to discredit religion! So Potiphar puts Joseph in prison. We put Joseph further and further out of sight.

Still, Joseph cannot be kept down. In prison he rises to be given charge of all the other prisoners. When we are bent on leading worldly lives, we keep many things in ourselves in prison: some good things because they would bring to our minds truths which would rebuke and correct us, and some evil things because they would lead us to acts which would lower our reputation in the world. The chief butler of Pharaoh and his chief baker represent these two kinds of prisoner. We are familiar with the thought that in the Holy Supper the wine represents truth and the bread good. In the butler's dream he is performing his proper office, pouring the wine into the cup of his master. But in the baker's dream the bread which he is carrying to his master is being stolen from his basket by the birds of the air.

Swedenborg says (@AC 5077-5078) that the butler represents the external sensual which is subject to the intellectual part of the internal man, and the baker represents the external sensual which is subject to the voluntary part of the internal man. This is why the chief butler was restored to his place and the chief baker was hanged. Our intellectual capacity often is able and willing to receive memory—knowledges of truth, but at the same time reject knowledges of good because we did not want to live according to them. In short, we often are eager to learn things but unwilling to put them into practice. Even in the letter there is a difference between the butler and the baker. When they told Joseph that they had been troubled by their dreams and Joseph said, "Do not interpretations belong to God? tell me them, I pray you," the butler had no hesitation in telling his dream immediately. But it is said of the baker, "When the chief baker saw that the interpretation was good," he proceeded to tell his own dream to Joseph. That is, the butler was willing to submit himself to the Lord's judgment, but the baker waited to see if the judgment was likely to be favorable to him. Still another indication is found in Swedenborg's translation of Genesis 40:16. The King James Version says the baker had "three white baskets" on his head, and the Revised Standard Version says "three cake baskets." The latter version gives no indication of any other possible translation, but the center column in the Oxford teacher's edition (King James) gives as an alternate translation, "baskets full of holes." [Two recent versions, the New American Bible and the Anchor Bible, have "three wicker baskets."] Swedenborg says "three baskets with holes in them" [canistra perforata], and explains the verse as meaning that the baskets represent the planes of the mind and their having holes in them means that the "interiors were without termination anywhere in the middle." Read here @AC 5145. Compare this with Haggai's rebuke to those who returned from exile (Haggai 1:4-6).

---

<<<


=== From the Writings of Swedenborg

@AC 5149: "There is falsity from two origins — falsity of doctrine, and falsity of evil. Falsity of doctrine does not consume goods, for a man may be in falsity of doctrine, and yet in good, and therefore men of every doctrine, even Gentiles, are saved; but the falsity of evil is that which consumes goods. Evil in itself is opposite to good, yet by itself it does not consume goods, but by means of falsity, for falsity attacks the truths which belong to good, because truths are as it were outworks that encompass good. These outworks are assaulted by means of falsity, and when these are assaulted, good is given to destruction."

---

<<<


=== Suggested Questions on the Lesson

*Q:* (Younger Children): Why did Joseph's older brothers dislike him? +
*A:* favorite, dreams

*Q:* (Younger Children): Where was he taken by the Ishmaelite caravan? +
*A:* Egypt

*Q:* (Older Children): How did he come to be put in prison? +
*A:* Potiphar's wife's lies

*Q:* (Younger Children): Who else were in prison with him? +
*A:* Pharaoh's butler and baker

*Q:* (Younger Children): What did he do for them? +
*A:* interpreted dreams

*Q:* (Older Children): What was the butler's dream? +
*A:* wine into cup

*Q:* (Younger Children): What was the baker's dream? +
*A:* birds eating bread

*Q:* (Older Children): What happened to the butler and the baker? +
*A:* butler restored, baker hanged

*Q:* (Younger Children): Did the butler remember Joseph? +
*A:* no

*Q:* (Younger Teens): What is Joseph in our lives? +
*A:* desire to be good

*Q:* (Older Teens): How do we sometimes "put him in prison in Egypt"? +
*A:* try to forget him when we have selfish desires

*Q:* (Older Teens): What is meant by his being able to interpret dreams? +
*A:* to understand our experiences

*Q:* (Younger Teens): Why could the Lord always take care of Joseph? +
*A:* wanted to do right


