= Bible Study Notes &#8212; Lesson 97
By Anita S. Dole



== The Prophet Micah

*Bible References:* Micah 6

_This is a lesson excerpted from The Dole Bible Study Notes. There are more than 150 of these lessons, covering many of the great stories in the Bible. They were designed for use in Sunday Schools, but they're good for all ages — for self-study, for parents to use in home devotions, and for pastors and teachers. Here's a link to more information about them._

---
.*Contents:*
----
1. Introduction
2. Doctrinal Points
3. Basic Correspondences
4. Notes for Parents
5. For Young Children
6. For Older Children
7. For Young Teens
8. For Older Teens
9. For Adults
10. From Swedenborg's Writings
11. Suggested Questions
----

---

<<<


=== Introduction

This again is one of the survey lessons. Be sure all the children learn what is meant by the "Minor Prophets," and why they were called "Minor." Read Micah 6:8 and comment on its meaning with all classes.

---

<<<


=== Doctrinal Points
----
• Charity is the essential of a good life, but outward good works are only the first step toward charity. Outward good works are not charity.
----

---

<<<


=== Basic Correspondences
----
• Bethlehem = truth conjoined with good
• burnt offerings = representatives of internal worship
• sacrifices = representative worship from derivative faith
----

---

<<<


=== Notes for Parents

The last twelve books of the old Testament are called the Minor Prophets. They are so much shorter than the other books that all twelve used to be written on one scroll. In Old Testament times books were not like our books, but were long pieces of parchment which could be rolled up on round pieces of wood. Jews today still keep the Torah, or Law, on such a scroll in their synagogues in a shallow, curtained chamber which they call the "ark." The chamber occupies the same place which the altar and Bible occupy in our churches, as the focus of vision for the congregation.

The books of the Minor Prophets in our Bible are not in exact historical order. Jonah is thought to have been the earliest. Hosea, Amos, and Jonah prophesied in Israel. The last three, Haggai, Zechariah, and Malachi, prophesied after the return from captivity. The others were all prophets of Judah. Some of them tell us in what period they prophesied; a few do not, and their dates cannot be certainly placed.

Many people are not very familiar with the books of the Minor Prophets. While everyone feels in them the same strange power which is felt throughout the Word because it is really the Lord who is speaking to us in it, there is little narrative in them to fix them in our minds, and they often seem disconnected and obscure. But we should read them just the same, for the Lord knows what we need better than we do, and we are told that as we read any part of the Word, guardian angels are present with us as we read, sensing the inner meaning, and so the Lord can help us through even the parts we do not understand at all. And often, as in our chapter for today, we come upon a verse which has a clear, direct meaning for every one of us.

The prophet Micah tells us (Micah 1:1) that he lived in Judah in the time of three of its kings, the best known of whom was Hezekiah. Like all the prophets, he was sent by the Lord to point out to the people the sins they were committing, to warn them what the result would inevitably be if they continued in the same ways, and to show them the path the Lord wanted them to follow. The prophets were not popular. In our chapter Micah points out clearly the injustice, violence, and deceit of the people, and begs them to return to obedience to their God, who has done so much for them. He tells them that they cannot make up for the evil of their deeds by sacrifices and offerings to the Lord, no matter how great these may be. There have been men in our own country who have thought that they could be as hard and unjust in their dealings as they liked in order to make money, provided that after they made it they gave part of it to the church or to some great charity.

Micah is speaking to us as well as to the people of his day when he says that it is our daily dealings with our fellow men which count in the Lord's sight and our daily attitude toward the Lord and His teachings by which we are finally judged. The verse which we should ask the children to learn is one which we should all know and say to ourselves often: "He hath shewed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God."

---

<<<


=== For Younger Children

[.underline]#*Teacher Notes:*# 
Try to teach Micah 6:8 to the children and explain simply what it means, especially by illustrating its opposite from their own experience. Do they ever try to claim credit to themselves for what someone else has done or put the blame for their own naughtiness on someone else? Do they ever get angry with others and try to make them suffer? Do they ever want their own way even when they know it is wrong? These children should also hear again the names of the twelve Minor Prophets and learn where to find them in the Bible. The learning and explanation of the three rules should be the basis for most of the lesson.

---
At the end of the Old Testament there are twelve short books called the Minor Prophets.

Let us open our Bibles and read their names.

Some of these Minor Prophets lived in Judah and some in Israel. The last three prophesied after the people returned from captivity.

Each has his special message, but they all rebuked the people for their sins.

The ancient Hebrews did not have the kind of books we have.

Their books were all written by hand on very long pieces of parchment or skin. A round stick was fastened to each end. Then, as it was read, the "book" was unrolled from one stick and rolled up on the other. The twelve books of the Minor Prophets were so short that they could all be written on one scroll.

Our lesson for today is from the book of the prophet Micah. He lived in the kingdom of Judah and prophesied during the reigns of three kings, the greatest of whom was Hezekiah. The Lord always sent His prophets to tell the people when they were doing wrong and to warn them of what would happen if they went on doing it, and to urge them to change their ways and do right. The Lord had done many wonderful things for the people and He had a right to expect them to obey Him. When your parents find fault with you for being naughty, you should remember how much they are doing for you all the time and that you owe them loving obedience.

Let us read Micah 6:1-12. As we read, see if you can pick out some of the good things the Lord had done for the people and some of the bad things they were doing.

Through Micah the Lord is speaking to us also.

Are we ever really happy when we are doing what we know is wrong?

"To do justly" means always to be fair and honest in little things as well as in big ones. "To love mercy" means always to be kind and forgiving and helpful and never to want to hurt anyone.

"To walk humbly with thy God" means to read our Bibles regularly, to go to church and Sunday school, and to try always to do what will please the Lord rather than just what will please ourselves.

---

<<<


=== For Older Children

[.underline]#*Teacher Notes:*# 
The historical background can be taken up in this class and the various Bible references studied. Have the children memorize verse 8, and discuss each of the three rules separately. Point out how much happier the world would be if everyone obeyed them.

---
For our lesson today we have chosen the prophet Micah, because in our chapter he gives us in one verse which we can easily learn by heart a clear and simple statement of the requirements of a good life. Micah, as he tells us in the first verse of his book, lived in Judah in the days of the kings Jotham, Ahaz, and Hezekiah. This was the same time in which Isaiah lived. Micah points out some of the particular sins of the people of that time.

What ones can you find mentioned in our chapter?

What does Micah say will be the punishment for these sins?

Now read verses 6 to 8. People today do not actually sacrifice animals or bring meal and oil to the church as offerings, or sacrifice their children to obtain salvation for themselves. Yet we are not so different after all from the people of Micah's time. We do like to do as we please most of the time and then imagine we make up for it by going to church on Sunday and putting something in the collection plate and perhaps giving something to charity once in a while and being very generous to someone now and then.

The Lord tells us through Micah that the good life does not consist in doing something spectacular occasionally, but in a certain quality of daily living. As in everything else, there are three planes of our lives concerned in goodness. They are will, thought, and act. In our acts we must "do justly." That is, we must be honest and fair in little things as well as in big ones. We must not be always trying to get the better of someone else or to get something for nothing. Then in our thoughts we must "love mercy." That is, we must be kind and forgiving, not holding grudges or trying to pay people back when they injure us, but always ready to help others. Finally, and most important of all, in our hearts we must "walk humbly" with God. That is, we must recognize that we are often wrong and weak and that we need to learn all we can about the Lord and what He teaches us in the Word, and to make the Lord's ways our ways, instead of trying to prove that what we happen to want to do is what ought to be done.

More than seven hundred years after the time of Micah the Lord found the same faults with the scribes and Pharisees which Micah had found in their ancestors. And the Lord gave them the same rules for a good life. Read Matthew 23:23.

One more thing we must learn about the book of Micah. Read Micah 5:2. Does this sound familiar? Now read Matthew 2:1-6. The Old Testament and the New Testament are bound together even in the letter by so many such prophecies and fulfillments that they cannot be understood apart from each other. And in its internal meaning the Old Testament is really a life of the Lord. He came to "fulfill" the Law and the Prophets. You will understand this better when you are older.

---

<<<


=== For Younger Teens

[.underline]#*Teacher Notes:*# 
The Younger Teens are old enough to realize that the thought and feeling must be right as well as the conduct, although they are still in the stage when conduct is rightly their chief concern. Remind them that all the prophets are speaking to us, and that a single verse like Micah 6:8 really taken to heart can do a great deal to mold the right kind of character. The people they really respect are those they feel to be sincere. They themselves are quick to detect and condemn any goodness which is "put on."

---
All of the prophets are not arranged in historical order in the Bible. Bible students have given much time and study to the attempt to place the Minor Prophets from "internal evidence"; that is, things that are said and language forms that are used in the books themselves. The prophet Micah tells us his own place in history in the first verse of the first chapter of the book. He was a contemporary of Isaiah and lived in Judah. Amos and Hosea were a little earlier and Jonah is thought to have been the earliest of all. Zephaniah prophesied in the reign of Josiah of Judah, Habakkuk in the last days of the kingdom and the beginning of the captivity, and Haggai, Zechariah, and Malachi in the time of the return. The periods of Joel, Obadiah, and Nahum are uncertain. The message of the Minor Prophets is principally applicable to older people, but there are things in all of them which we can all understand.

In Micah there are two passages of special note. One is the prophecy in 5:2 which was the source of the direction given to the Wise Men in Matthew 2:1-6. The other is verse 8 of our chapter, one of the most beautiful and well known summaries in the Scriptures, a verse everyone should know by heart and think of often, for it gives in simple terms the requirements for a good life by which we may judge ourselves. A life, to be really good, must be right on all three planes, beginning with the lowest, the plane of external conduct, and ascending through love to the neighbor, which is the spiritual plane, to love to the Lord, which is the inmost or celestial plane. The Lord stated this same teaching in Matthew 23:23. It is easy to see the necessity of this when we remember that at death the inner life is opened and we take our places according to the quality of that inner life. In heaven, love to the Lord and the neighbor rule, and if we have not developed these loves, we cannot possibly be happy there.

No one attains inner goodness all at once. We have to begin by making our conduct right, then progress to cleansing our thoughts, and finally, if we persevere, the Lord will give us a "new heart" to replace our natural selfish inclinations. This is the process of reformation and regeneration, the "second birth" of which the Lord spoke to Nicodemus. Our part in it is to learn and do the Lord's will from day to day in little things as well as in big ones.

Micah, like all the prophets, called attention to the actual sins which the people were committing. We need to examine ourselves from time to time and single out our "besetting" sins in order that we may fight them. As it is not enough just to do external good works, it is also not enough merely to confess that we are sinners in general. We must recognize and overcome particular faults one at a time.

Each of the Minor Prophets has a particular message for us.

We should study them more as we grow older and have more life experience to draw on for understanding them. But we can all understand the rules for life which Micah gives us and use them from day to day as standards and guides.

---

<<<


=== For Older Teens

[.underline]#*Teacher Notes:*# 
The position and value of the Minor Prophets should be stressed. All the Word of God is given "for our good always." The Older Teens are drawing close to independent adult life and should be helped to realize the importance of choosing a proper pattern not only for their conduct but for their inner life as well. It is what they are which will actually count wherever they go and whatever they do in their lives, and not only in this world but in the life to come.

---
The twelve books which conclude the Old Testament are called the Minor Prophets. This is because they are short, not because they are less important than the others. When we look through Swedenborg's summary explanation of these books in his work Prophets and Psalms, we find that in the inner meaning they have to do with the complete "vastation" of the ancient Jewish Church through its accumulated evils and with the establishment of a new church of a more internal and therefore more genuine character. All twelve prophecies were spoken after the division of Solomon's kingdom into the two separate kingdoms of Israel and Judah. From the time of that division the decline of the nation was rapid. Jonah is thought to have been the earliest of the Minor Prophets, but he was probably partly contemporary with Hosea and Amos, who place themselves in the reign of Jeroboam 2 of Israel and Amaziah and Uzziah of Judah, thus after the time of Asa and before that of Hezekiah. Micah, from whose book our lesson is taken, was a contemporary of the Major Prophet Isaiah, placing himself (Micah 1:1) in the time of Jotham, Ahaz, and Hezekiah, kings of Judah. The fall and captivity of Israel took place while Hezekiah was king in Judah; so the rest of the Minor Prophets belong to Judah after it was deprived of the protection of Israel. The three last, Haggai, Zechariah, and Malachi, prophesied after the people of Judah returned from their own captivity in Babylon. We can, therefore, think of all the Minor Prophets as the voice of the Lord coming to us when our understanding has been undermined and taken captive by worldly reasonings and when our good intentions are either in the last throes of the struggle to hold out against selfishness or have actually been swept away by it. So the detailed study of the Minor Prophets is for older people rather than for Sunday school children. Nevertheless there are passages which are clear and helpful for anyone.

We have such a passage today in Micah 6:8, in which we are given in very simple terms the rules for a good life. Compare this verse with the Lord's words to the scribes and Pharisees in Matthew 23:23. Outward acts of worship are necessary for us, but they should be done not as an end in themselves, but as an external expression of something genuine within. They are not a substitute for genuine day—to—day goodness. Three planes of requirement are described: justice in the outward acts, kindness and gentleness in the thoughts, and humility before the Lord in the heart. All these demand the overcoming of selfishness. We cannot be just in our outward acts if we put our own needs and interests first. We cannot be kind and gentle in thought if we believe others should always agree with us and defer to our opinions. We cannot be humble before the Lord if we do not seek always to learn of Him and to do His will rather than our own. See how verses 10 to 12 of our chapter single out the particular evils which the people of Judah were committing in violation of the three rules. So we must examine ourselves in the light of the three rules and recognize the particular things in us — the particular actions and thoughts and feelings - which are standing in the way of our regeneration. And we must fight these failings one by one. No one can do this work for us. If we learn the three rules and accept them as our own yardstick from day to day, we shall grow better and happier all the time.

---

<<<


=== Adult

[.underline]#*Teacher Notes:*# 
There are two important lessons here for Adults. One is that we need to read regularly all the Word — not just the parts which particularly appeal to us. The other is the simple outline of the good life found in Micah 6:8 in contrast to the many conflicting superficial ideas in the world around us. This verse provides endless food for thought and discussion.

---
We should all be familiar with the names of the twelve Minor Prophets, and for practical purposes it is best to know them in the order in which the books are found in our Bible, although this is not their exact chronological order. Little is known of their lives except from occasional statements in the books themselves, but they all claim direct divine inspiration and were included in the Judaic canon. Most of them state specifically the period in which they prophesied, but the periods of Joel, Obadiah, and Nahum are uncertain. Jonah is considered the earliest, the first great prophet after Elisha, and his book, unlike the others, contains considerable personal narrative. Hosea and Amos follow next after Jonah in time and were contemporaries. Micah was a contemporary of Isaiah. Zephaniah prophesied in the time of Josiah of Judah and Habakkuk in the time of Jehoiakim. Haggai, Zechariah, and Malachi were all prophets who lived during the restoration. Hosea, Amos, and Jonah prophesied in Israel and the others in Judah. These books are all so short that the ancient Hebrews wrote all twelve of them on one manuscript or scroll.

Even in the letter the books of the Prophets are often obscure and difficult. It is impossible to make a study of each of the twelve Minor Prophets within the limits of a Sunday school course. In their letter they deal with the corrupt state of the Church, with the ruin which will inevitably follow upon such perversion of the divine gifts, and with the preservation of the good remnant and the coming of the Messiah. Many of them contain strange visions and commands which can be interpreted only by the law of correspondence. Only the book of Jonah contains narrative of the type which children can readily grasp. Yet all twelve, like the four Major Prophets, had a message which was essential to the people of their day and which, in its inner meaning, is essential to people of all time, to point out and condemn particular evil states and to give hope to those who are in despair. Even if much of the contents of the Minor Prophets seems incomprehensible to us, these books should be read reverently and attentively, in order that the letter may make its impression on the mind and be there for the Lord to use. We know that the reading of every part of the inspired Word connects us with particular societies in the heavens and serves them as well as helping us by new conjunctions. We shall also find many familiar prophecies in them which will help us to connect the Old and the New Testaments, and scattered through all twelve books there will be passages such as the one chosen for our reading today which are so direct and clear that they will come to serve us as constant guides to thought and conduct.

As we read any part of the Word, we should realize that it speaks to us. In our lesson the Lord, through the prophet Micah, calls upon the mountains to witness His dealings with His people. The mountains, picturing our states of nearness to the Lord when we look down upon our lives as from a height, do bear witness to the Lord's constant mercy and protection and to the blessings which He gives us freely. They also bear witness to our ingratitude and forgetfulness, and to our proneness to follow self-interest and worldly ways — to walk according to the statutes of Omri and the works of the house of Ahab. Yet the Lord's way is not hard or burdensome. He does not require us to give up anything that is really good or that will really make us happy. And He does not leave us in the dark as to what the good life is: "He hath shewed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?"

This is a verse which everyone of us should know by heart and repeat often. The three requirements of a good life belong to the three planes, beginning with the outmost. "To do justly" is to be honest and upright and faithful in our outward conduct. This is the first step toward heaven, literal obedience to the commandments, reformation, the baptism with water. Many think it is enough, as the rich young man did. But the Lord tells us that we must also "love mercy." This is to love the neighbor. Abstract justice would permit us to punish those who injure us, to love only those who love us, but mercy requires that we love our enemies, bless those who curse us, and do good to those who despitefully use us and persecute us. This is the baptism with the Holy Spirit. Many stop here. They say, "If we are honest and faithful in our conduct and kind to our neighbors, what more can anyone ask?" The Lord does ask more. There is still the inmost plane, the most important of all since it determines the quality of all our thoughts and acts. On this inmost plane we are told to "walk humbly with thy God." The Lord said to the rich young man, "Sell whatsoever thou hast ... and come, take up the cross, and follow me." Put most simply, this means that we must give up our own way whenever it is contrary to the Lord's. This is the essence of walking humbly with God, to recognize that all goodness, wisdom, and power are the Lord's, to study His Word, and to submit ourselves humbly to its guidance. This is to love the Lord, the baptism with fire. People can live outwardly correct lives and be kind to their neighbors and still within cherish pride and self-satisfaction and shut the Lord out of their hearts altogether. Heaven is where the Lord is. We cannot be in heaven either here or hereafter if the Lord is not in our hearts. "Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment."

---

<<<


=== From the Writings of Swedenborg

@AC 10143: "By sacrifices and burnt—offerings was specifically signified purification from evils and falsities, and the implantation then of good and truth, and the conjunction of both, thus regeneration. The man who is in these is in genuine worship, for purification from evils and falsities consists in desisting from them, and in shunning and turning away from them; and the implantation of good and truth consists in thinking and willing what is good and true, and in speaking and doing them; and the conjunction of both consists in living from them; for when good and truth have been conjoined with a man, he then has a new will and a new understanding, consequently a new life. When a man is of this character, there is Divine worship in every work he does, for he then looks to the Divine in everything; he venerates it, and he loves it; consequently he worships it. That this is genuine Divine worship is unknown to those who make worship consist in adoration and prayers, thus in such things as are of the mouth and thought, and not in such as are of work from the good of love and the good of faith; when yet the Lord regards nothing else in the man who is in adoration and in prayers than his heart, that is, his interiors, such as they are in respect to love and the consequent faith. If therefore these interiors of man are not inwardly in adoration and prayers, there is no soul and life in them, but only an external such as is that of flatterers and pretenders, and that these are not pleasing to a wise man in the world is well known. In a word, to do according to the precepts of the Lord is truly to worship Him."

---

<<<


=== Suggested Questions on the Lesson

*Q:* (Younger Children): From what book is our lesson today? +
*A:* Micah

*Q:* (Younger Teens): In which division of the divided kingdom did Micah prophesy? +
*A:* Judah

*Q:* (Younger Teens): Do you remember the name of one of the three kings in whose reigns he prophesied? +
*A:* Jotham, Ahaz, Hezekiah

*Q:* (Younger Children): Why did the Lord send prophets? +
*A:* to warn people about their wrongdoing

*Q:* (Younger Children): What were some of the bad things the people were doing in Micah's time? +
*A:* cheating, lying, violence

*Q:* (Younger Teens): What kind of worship did the people think would please the Lord? +
*A:* sacrifice

*Q:* (Younger Children): What did Micah tell them would please the Lord? +
*A:* to do justly, love mercy, walk humbly

*Q:* (Younger Teens): What does "to do justly" mean? +
*A:* be fair and honest

*Q:* (Younger Children): What does "to love mercy" mean? +
*A:* be kind, helpful, forgiving

*Q:* (Younger Children): What does "to walk humbly with thy God" mean? +
*A:* read Word, attend worship, try to do the Lord's will

*Q:* (Younger Teens): To what three planes of our lives do these three requirements of the good life apply? +
*A:* conduct, thought, will

*Q:* (Older Teens): Why are they given in this order in Micah's prophecy? +
*A:* must begin by making our conduct right, progress to cleansing our thoughts, and finally receive a new will from the Lord


