= Style Guide for NCBS Collateral Literature
a work *in progress* ........   {docdatetime}
include::../template-attributes.adoc[]

.Note
NOTE: This document is quite raw at this stage of development. 

== {empty}
//empty levels here enable smaller heading fonts with next level
=== {empty}


For reviewing this in VSCode, + 
open the source file using the Explorer, + 
and preview it on the right. + 
(instructions elsewhere, eventually)

##[.underline]#Comments:###

`//` two slashes start a comment line.
intenchionally mizpelled werds
////
comment block bounded by ////
ok
////

WARNING: When the comments should also be displayed on the output files, such as this from Spiritual_World-Odhner :
WARNING: Tremendous! quantity of footnotes is posing a problem here

==== ##[.underline]#References to Bible verses:###

(Genesis 1, 3:1-4,8; Exodus 2:6,9) + 
 wrapped in parentheses (optional) + 
; semi-colon separates Verses from new Chapters, and Books + 
, comma separates verses, and chapters + 
- hyphenate a range of chapters or verses + 
: colon separates chapter:verse + 
all numerals Arabic, not Roman + 

Code or searches should consider commas *_optionally_* followed by a space.

(1 Chronicles|1 Corinthians|1 Esdras|1 John|1 Kings|1 Maccabees|1 Peter|1 Samuel|1 Thessalonians|1 Timothy|2 Chronicles|2 Corinthians|2 Esdras|2 John|2 Kings|2 Peter|2 Samuel|2 Thessalonians|2 Timothy|3 John|Acts|Amos|Colossians|Daniel|Deuteronomy|Ecclesiastes|Ecclesiasticus|Ephesians|Esther|Exodus|Ezekiel|Ezra|Galatians|Genesis|Habakkuk|Haggai|Hebrews|Hosea|Isaiah|James|Jeremiah|Job|Joel|John|Jonah|Joshua|Jude|Judges|Judith|Lamentations|Leviticus|Luke|Malachi|Mark|Matthew|Micah|Nahum|Nehemiah|Numbers|Obadiah|Odes|Philemon|Philippians|Proverbs|Psalms?|Revelation|Romans|Ruth|Song of Solomon|Titus|Zechariah|Zephaniah)


==== ##[.underline]#References to the Writings of Swedenborg:###

(@AC 123-125, 1234[5]; @DP 3) + 
wrapped in parentheses unless inappropriate + 
Titles are abbreviated, without trailing period + 
space between title and number; period following number is discouraged
leading @ + 
, comma separates numbers in same book + 
; semi-colon separates books + 
  spaces around punctuation are possible and optional + 
- ranges acceptable +
[] sections, including comma separated, and hyphenated ranges, in brackets +
Ranges should be fully numbers, e.g. @AC 123-125 is acceptable, but @AC 123-5 is not

@(5M|9Q|AC|AE|AngIdea|AR|Ath|BE|CL|CanonsNC|Char|ConvAng|Coro|DFaith|DLW|DLife|DLord|DLove|DMin|DP|DSS|DWis|DeConj|DeConsum|DeDeoSalv|DeDomino|DeInfluxus|DeJust|DeMiraculis|DeVerbo|Dicta Probantia|Docu|EU|EccHist|HH|HistCrea|ISB|Inv|LJCont|LJPost|LJ|Letters|NJHD|PP|SE|SciaDoc|TCR|Adversaria|WHApp|WH)

See this sheet for more information: + 
https://github.com/New-Christian-Bible-Study/swedenborg-concordance/blob/main/docs/swedenborg-works-info.csv

"Spiritual Diary" is now "Spiritual Experiences" @SE + 
"Marriage Love" is still "Conjugial Love" @CL + 
"Heavenly Secrets" is still "Arcana Coelestia" @AC


==== ##[.underline]#Line Breaks:###

You'll readily note that two separated
but adjacent 
lines will be joined into a seamless flowed paragraph. + 
_here again, compare the source with the preview_ + 
For separating short lines, + 
without a blank line between them + 
append the spaceplusspace sequence  ` + `

==== ##[.underline]#Thematic Breaks:###

Several titles use a visible paragraph separator to indicate a thematic break. For our project, these should be converted to three dashes.

---


==== ##[.underline]#Page Breaks:###

following a blank line, a new line starting with three '<' characters:

<<<

Note that this kind of markup only works for document types which understand pages. The default document type (:doctype:) is html. + 
Changing the doctype happens in the header section at the top of the file. + 
_See there for this._


==== ##[.underline]#Footnotes:###

In accommodation of many of our source files, the asterisk(*) is adopted for footnotes. 

(*)But since it conflicts with the markup's uses, we enclose it in parens, below the insertion block, separated by a blank line, as shown here and below.

In some cases(*1), there is a need for multiple footnotes(*2) in the same line.

(*1). the source would use multiple asterisks

(*2). I couldn't get that to work in AsciiDoc

There have also been numbered footnotes (23) in documents prepared for maybe an endnotes section.

(23). They came with wrapping parentheses.

In order to match the footnote insertion with the footnote explanation, the regex format is `\([*0-9.]+\)`

//Steve's note: In NCBS, we restart footnote numbering for each passage, and we replace all asterisks with an Arabic numeral, like this `fff1`, `fff2`. Then in the notes section below the passage, we use `nnn1`, `nnn2` etc. to match the footnote number to the note.

a horizontal line separator, generated with three dashes following a blank line, as below:

---
Many source files used a multiple of asterisks, some with alternate spaces, for this use. Again, incompatible conflict with AsciiDoc's need for asterisks.

==== ##[.underline]#Ordered Lists:###

This has been a pretty big headache. Read about it here:

Escaping the List marker : insert '{empty}' before the period + 
https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/#escaping-the-list-marker


See our file "Application_of_Doctrine-DeCharms" for having worked this out. The entire file is nested ordered lists.

==== ##[.underline]#Tagging Concepts and Verses:###

by example, use this markup where and as you see fit, until we develop more definitive instruction ...

```
=== What is Man?
//<soul><spirit>
```

Also for use with Bible Verses, prepended to the adoc line to be used as descriptive. First example:

```
"I am the First, and I am the Last: yea, my hand hath founded the earth, and my right hand hath spanned the heavens. I call them together; they stand together." (Isaiah 48:12-13).

//<Isaiah 48:12-13>
The doctrine of the text is that the first, by lasts, builds intermediates and holds them in form, connection, and order; ...
```
(the full descriptive content is not included in this example; + 
the source is NDPendleton's "Glorification")


==== ##[.underline]#Inconclusive Editing:###

Sometimes a word or phrase just can't be resolved at the time of encounter while proofreading. These can be designated by enclosing the mystery, or a comment, within `[?...?]` ; 
as `not [?set?] by` and thereby easy to find by subsequent search, and to convey the uncertainty in the printed output. + 
An alternative may refer to an entire sentence or paragraph: + 
`//[? the last sentence isn't clear ?]` + 
Use the double slashes to remove what follows from being output, as you'll see in the preview pane.

Sometimes the editor may have a clear idea of what word should be used, but it differs greatly from what is given. This can be annotated as .... `the [?which?evil?] gain power` .... where 'evil' fits the phrase or sentence, and 'which' definitely does not; yet the exchange does not resemble a scan/ocr error of processing; and a simple replacement feels a possible disservice to the original author intent.


NOTE:
Editors with access to authoritative sources are encouraged to seek and resolve these mysteries within the entire collection.

---
'''
== References:

This page catalogs all the built-in (i.e., reserved) document attributes in AsciiDoc:
https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/

Text justification and things like underlining are known to asciidoc as 'roles' .... shown here:
https://docs.asciidoctor.org/pdf-converter/latest/roles/
