== Style Guide for NCBS Collateral Literature
a work *in progress* ........   {docdatetime}
//:doctype: book

=== {empty}

.Note
NOTE: This document is quite raw at this stage of development. 

For reviewing this in VSCode, + 
open the source file using the Explorer, + 
and preview it on the right. + 
(instructions elsewhere, eventually)

##[.underline]#Comments:###

`//` two slashes start a comment line.

WARNING: When the comments should also be displayed on the output files, such as this from Spiritual_World-Odhner :
WARNING: Tremendous! quantity of footnotes is posing a problem here

==== ##[.underline]#References to Bible verses:###

(Genesis 1, 3:1-4,8; Exodus 2:6,9) + 
 wrapped in parentheses (optional) + 
; semi-colon separates Chapters, and Books + 
, comma separates verses, and chapters + 
- for a range of chapters or verses + 
: colon separates chapter:verse + 
all numerals Arabic, not Roman

Code or searches should consider commas *_optionally_* followed by a space.

(1 Chronicles|1 Corinthians|1 Esdras|1 John|1 Kings|1 Maccabees|1 Peter|1 Samuel|1 Thessalonians|1 Timothy|2 Chronicles|2 Corinthians|2 Esdras|2 John|2 Kings|2 Peter|2 Samuel|2 Thessalonians|2 Timothy|3 John|Acts|Amos|Colossians|Daniel|Deuteronomy|Ecclesiastes|Ecclesiasticus|Ephesians|Esther|Exodus|Ezekiel|Ezra|Galatians|Genesis|Habakkuk|Haggai|Hebrews|Hosea|Isaiah|James|Jeremiah|Job|Joel|John|Jonah|Joshua|Jude|Judges|Judith|Lamentations|Leviticus|Luke|Malachi|Mark|Matthew|Micah|Nahum|Nehemiah|Numbers|Obadiah|Odes|Philemon|Philippians|Proverbs|Psalms|Revelation|Romans|Ruth|Song of Solomon|Titus|Zechariah|Zephaniah)


==== ##[.underline]#References to the Writings of Swedenborg:###

(@AC 123-125, 1234[5]; @DP 3) + 
wrapped in parentheses unless inappropriate + 
Titles are abbreviated, without trailing period + 
space between title and number
leading @ + 
, comma separates numbers in same book
; semi-colon separates books + 
  spaces around punctuation are possible and optional + 
- ranges acceptable + 
[] sections, including comma separated, and hyphenated ranges, in brackets


@(5M|9Q|AC|AE|AngIdea|AR|Ath|BE|CL|CanonsNC|Char|ConvAng|Coro|DFaith|DLW|DLife|DLord|DLove|DMin|DP|DSS|DWis|DeConj|DeConsum|DeDeoSalv|DeDomino|DeInfluxus|DeJust|DeMiraculis|DeVerbo|Dicta Probantia|Docu|EU|EccHist|HH|HistCrea|ISB|Inv|LJCont|LJPost|LJ|Letters|NJHD|PP|SE|SciaDoc|TCR|Adversaria|WHApp|WH)

See this sheet for more information: + 
https://github.com/New-Christian-Bible-Study/swedenborg-concordance/blob/main/docs/swedenborg-works-info.csv

"Spiritual Diary" is now "Spiritual Experiences" @SE + 
"Marriage Love" is still "Conjugial Love" @CL + 
"Heavenly Secrets" is still "Arcana Coelestia" @AC



==== ##[.underline]#Line Breaks:###

You'll readily note that two separated
but adjacent 
lines will be joined into a seamless flowed paragraph. + 
_here again, compare the source with the preview_ + 
For separating short lines, + 
without a blank line between them + 
append the spaceplusspace sequence  ` + `

==== ##[.underline]#Thematic Breaks:###

Several titles use a visible paragraph separator to indicate a thematic break. For our project, these should be converted to three dashes.

---


==== ##[.underline]#Page Breaks:###

following a blank line, a new line starting with three '<' characters:

<<<

Note that this kind of markup only works for document types which understand pages. The default document type (:doctype:) is html. + 
Changing the doctype happens in the header section at the top of the file. + 
_See there for this._


==== ##[.underline]#Footnotes:###

In accommodation of many of our source files, the asterisk(*) is adopted for footnotes. 

(*)But since it conflicts with the markup's uses, we enclose it in parens, below the insertion block, separated by a blank line, as shown here and below.

In some cases(*1), there is a need for multiple footnotes(*2) in the same line.

(*1). the source would use multiple asterisks

(*2). I couldn't get that to work in AsciiDoc

There have also been numbered footnotes (23) in documents prepared for maybe an endnotes section.

(23). They came with wrapping parentheses.

In order to match the footnote insertion with the footnote explanation, the regex format is `\([*0-9.]+\)`



a horizontal line separator, generated with three dashes following a blank line, as below:

---
Many source files used a multiple of asterisks, some with alternate spaces, for this use. Again, incompatible conflict with AsciiDoc's need for asterisks.

==== ##[.underline]#Ordered Lists:###

This has been a pretty big headache. Read about it here:

Escaping the List marker : insert '{empty}' before the period + 
https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/#escaping-the-list-marker


---
'''
==== References:

This page catalogs all the built-in (i.e., reserved) document attributes in AsciiDoc:
https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/


