==== The Importance of the Collateral Work of The New Church


{empty}

---

The spiritual marriage (so often referred to in the Writings) is not a conjunction of natural good and natural truth, but is that *_state_* in which natural good is purified and lifted up by a love of spiritual truth, *[.underline]#and the study#* of natural truth is entered into from a spiritual love, or from the good of charity (@AC 3952). -Hugo Odhner, "The Divine Allegory"

---

"This is the Aaron and Moses" (Ex. 6:26) ... "the doctrine of the spiritual church is not that of truth Divine itself, because those who are of the spiritual church have no perception of truth Divine, as have those who are of the celestial church; but instead of this perception they have conscience, which is formed from the truth and good which they have acknowledged within their own church, of whatever kind these may be.
 + 
... + 
Hence it is that everyone within the spiritual church acknowledges as the truth of faith that which its founders have dictated
 + 
... + 

[width=95%]
[frame=none]
[grid=none]
[cols="1,>6"]
|===
|
|_nor do they search further from the Word whether it be the very truth; and moreover if they did search they would not find it unless they had been regenerated and at the same time enlightened in an especial manner; and this for the reason that their intellectual can indeed be enlightened, but the new will cannot be affected with any other good than that which has been formed by means of conjunction with the truth received within the church._
|===

{empty}
 ... + 
For their own will has been destroyed, and a new will has been formed in the intellectual part
{empty}
... + 
[width=95%]
[frame=none]
[grid=none]
[cols="1,>6"]
|===
|
|_doctrinal things being from the Word does not make them Divine truths, for from the sense of the letter of the Word any doctrinal thing whatever can be hatched, and that which favors the concupiscences can be readily learned; thus also what is false can be taken for what is true_
|===

{empty} 
... + 
but not so if doctrine is formed from the internal sense. The internal sense is not only that sense which lies concealed in the external sense, as has heretofore been shown, but is also ...

that which results from a number of passages of the sense of the letter rightly collated, and which is discerned by those who are enlightened by the Lord in respect to their intellectual. For the enlightened intellectual discriminates between apparent truths and real truths, especially between falsities and truths, although it does not judge about real truths in themselves. But the intellectual cannot be enlightened unless it is believed that love to the Lord and charity toward the neighbor are the principal and essential things of the church. He who proceeds from the acknowledgment of these, provided he himself is in them, sees innumerable truths; nay, he sees very many secrets disclosed to him, and this from interior acknowledgment, according to the degree of the enlightenment from the Lord." @AC 7233

