
<<<
---
=== 17 - David Spares Saul and Cuts Off the Skirt of his Robe

1 Samuel 24

Hitherto we have seen David only as a fugitive fleeing before Saul, and we can have no doubt what his fate would have been, had he fallen into the hands of his merciless pursuer. We are now to see some of the circumstances connected with them reversed. David is still a fugitive, fleeing and hiding from his adversary, but Saul is providentially brought completely within David's power; and we shall see how differently he acts towards the king from the manner in which the king, if the case had been reversed, would have acted towards him.

No sooner had Saul left following the Philistines than he returned to renew with undiminished ardour his pursuit of David. Learning that the object of his search was now in the wilderness of Engedi, "he took three thousand chosen men out of all Israel, and went to seek David and his men upon the rocks of the wild goats. And he came to the sheepfold by the way where was a cave; and Saul went in to cover his feet: and David and his men remained in the sides of the cave." David's men urged him to kill his enemy, whom God had delivered into his hand; but David only cut off the skirt of Saul's robe, and his heart smote him for doing even that, which seemed to him an impious deed. When Saul went out of the cave David followed him, and cried after him. Saul looked back; and David, addressing him, said, "Behold, this day your eyes have seen how that the Lord had delivered you today into mine hand in the cave: and some bade me kill you: but mine eye spared you; and I said, I will not put forth mine hand against my lord; for he is the Lord's anointed. Moreover, my father, see, yea, see the skirt of your robe in my hand: for in that I cut off the skirt of your robe, and killed you not, know you and see that there is neither evil nor transgression in mine hand; and I have not sinned against you; yet you huntest my soul to take it." Saul would have been worse than wicked if he had not been melted and disarmed by this practical appeal to the better instincts of his nature. He made the fullest acknowledgement of David being more righteous than himself. Recognising the fact, which he had so laboured to prevent, that David would surely be king, and that the kingdom of Israel would be established in his hand, he only asks David to swear to him by the Lord that he will not cut off Saul's seed after him, nor destroy his name out of his father's house.

In the conduct of David towards Saul there is something so noble and generous, that it cannot fail to command our admiration. His sentiments are not, however, those of the natural disposition merely. They are inspired by piety to God, and are extended to Saul, not as a frail and erring human being, but as the anointed of the Lord.

There is a wide difference between the manifested character of many men when they act under the immediate influence of religious feeling, and when they act from the promptings of their own frail nature. Few men, perhaps, have exhibited more strikingly these two opposite characters than David, in whose history we find strongly marked instances of generosity and vindictiveness, mercy and cruelty, chastity and impurity.

No man is entirely exempt, in the sight of God and His angels, from the same charge, because no man is entirely free from the infirmities of sinful flesh.

There is, however, a wide difference, both in nature and degree, between the truly spiritual and the merely pious man.

Piety, as distinguished from spirituality, is a feeling of reverence for what is pure and holy, as distinguished from a state of actual purity and holiness. Those who are pious without being spiritual -- who have reverence without holiness -- are for the most part very susceptible of tender emotions; but these being excited from without, are impressions rather than states, and may last only so long as the outward producing cause is present. Acting from feelings excited by external circumstances, rather than inspired and regulated by inward principles, such persons are capable of emotions and actions widely different and even opposite in their character. Their corrupt nature, not having been subdued by religious self-denial, is likely to come forth in all its malignity when a sufficiently powerful appeal is made to the passions.

Whenever the life of man is marked by strikingly opposite or even widely different characteristics, there is reason to fear that spirituality has been too little cultivated, however piety may have been cherished. Those who are spiritually minded are not, indeed, exempt from all the feelings and actions that originate in human infirmity. They will, however, be so in the degree that the spiritual in them has obtained the dominion over the natural. Those who are born again receive a new nature; and it is impossible for any who have thus become new creatures, deliberately to commit deeds that are characteristic of the old man, of the world and the flesh.

Yet David committed such deeds; and David is said to have been a man after God's own heart. It is against the conclusion sometimes drawn from the combined testimony of these two facts that we require to be guarded. That conclusion is, that evil does not condemn him whom God has justified -- that a man may be an eminent saint and yet fall into grievous sins.

In regard to David and the characters of the Old Testament, as compared with those of the New, we are to reflect on the entirely different characters of the two dispensations. The one was the shadow and the type, the other was the substance and the reality, of a true Church. The eminent men of the Jewish Church were not necessarily more than the types of saints -- the eminent men of the Christian Church were saints in reality. David was a man after God's own heart in a Jewish, not in a Christian sense -- in his official and representative rather than in his personal and spiritual character. The Apostle John was the beloved of Jesus, not only representatively but actually, because he had the love of Jesus eminently in him.

We could not imagine any one of David's stamp being an apostle of the Lord Jesus Christ. Yet David himself is not to be judged by a Christian but by a Jewish standard. So Christians are not to be judged by a Jewish but by a Christian standard: and except their righteousness exceed the righteousness, not only of the straitest sect, but even of some of the most eminent men, of the Jewish religion, they cannot enter into the kingdom of God.

While it is necessary for us to be guarded against casting the mantle of David's piety over some of his actions, we are nevertheless to honour him for the good and generous deeds he performed; and not least for those noble instances of clemency and forbearance which he manifested towards Saul, when he could have rid himself at once of a malevolent enemy and a powerful rival. From such actions as these we may learn some of the highest lessons of Christian virtue; for what is more forcibly inculcated by our Lord than love towards our enemies, and forgiveness to those who sin against us? "Bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you; that you may be the children of your Father which is in heaven: for He makes His sun to rise on the evil and on the good, and sends rain on the just and on the unjust." An enlightened Christian charity may act in some cases and in some respects differently from the manner in which love to the neighbour acted under the Jewish dispensation; but the charity we exercise should not be less, but ought to be still more, tender and forgiving. If under a dispensation in which men were allowed to hate their enemies, such instances of love as this of David were exhibited, how much more should we be disposed to forgive men their trespasses; knowing also that unless we forgive men their trespasses neither will our heavenly Father forgive us.

The history before us shows also the effect which the practice of love and forbearance may have on those to whom they are manifested. Saul, notwithstanding the unreasonable and unnatural cruelty of his disposition and conduct towards David, was yet overcome with tenderness at the discovery of his clemency. When David held up the skirt of Saul's robe, and told him how he might, and, had he yielded to persuasion, would have cut off his life instead, the hard heart of the king was melted into tenderness, and he was penetrated with a sense of shame. "He lifted up his voice, and wept. And he said to David, You are more righteous than I: for you have rewarded me good, whereas I have rewarded you evil." He desired that the Lord might reward David good for what he had done to him; and bowed in submission to the Divine decree that David should be king of Israel. This better frame of mind was indeed of but short duration. And in this case we find a striking exemplification of the truth we have already alluded to, that when our better feelings are active only when they are excited from without, the impression lasts no longer than the presence of the cause that produced them. Saul soon returned to his former frame of mind; and so will every repentant relapse into his former condition, or into one still worse, if he has no inward principle to sustain and guide him. But it is now time to pass on to the contemplation of the spiritual meaning of the circumstance on which we are now engaged.

As representative of the state of the kingdom of Israel, as itself representing the state of the Israelitish Church, the cutting off of the skirt of Saul's robe by David, and his retaining it in his hand, represented the transfer of the kingdom from Saul to David; Saul himself recognised this symbolical meaning in the fact. "Now, behold, I know," said the humbled monarch, "that you shall surely be king, and that the kingdom of Israel shall be established in your hand."

Looking at the circumstances before us in a higher sense, as relating to the kingdom of the Lord in ourselves, and regarding Saul and David as representing the natural and the spiritual mind, the particulars related will be found to describe some state of experience, and to contain some lesson of Christian instruction.

Regarding David as representing the inner man or spiritual mind, and Saul as representing the outer man or natural mind, the present circumstance presents another striking and beautiful illustration of the truth, which we have had occasion more than once to state, that the natural mind in its yet unregenerated state is at enmity with the spiritual, while the spiritual, on the other hand, has no enmity against the natural, but is in the constant desire of reconciling and uniting it to itself. This is evident from the general temper and conduct of David and Saul to each other, but it is described in particular in the act and in the words of David.

As the wilderness is the symbol of temptation, the character of the temptation is indicated by the wilderness which represents it. What is represented by the wilderness of Engedi may be known from the spiritual meaning of Engedi itself, which occurs in a part of the Scriptures which has an obviously spiritual meaning. In the 47th of Ezekiel Engedi is mentioned in connection with the new or mystical temple, and as sharing largely in the blessings diffused by the river of the water of life issuing from under the threshold of the temple eastward. Of these waters it is said at the 8th verse: "These waters go down into the desert, and go into the sea, whose waters shall be healed. And it shall come to pass, that every thing that lives, which moves, whithersoever the rivers shall come, shall live: and there shall be a very great multitude of fish, because these waters shall come thither.... And it shall come to pass, that the fishers shall stand upon it from Engedi even to En-eglaim; they shall be a place to spread forth nets; their fish shall be according to their kinds, as the fish of the great sea, exceeding many. But the miry places thereof and the marshes thereof shall not be healed; they shall be given to salt."

That to which the living waters flowed was the desert of Judea, that into which it flowed was the Dead Sea. This desert was that in which, under the name of the wilderness of Judea, John the Baptist appeared, and first preached the Gospel of glad tidings to the world; and in that instance the vision of the living waters may be considered to have received an external representative fulfillment. But spiritually understood, the desert and the sea, restored to life and fruitfulness by the river of living waters, are expressive emblems of the will and understanding of the natural mind, in themselves desert and dead, restored by the reception of Divine truth to life and fruitfulness.

This great desert of Judea was the wilderness of Engedi, and in it, near the banks of the Dead Sea, stood the town of Engedi, En-eglaim occupying a site on the other side of Jordan, in the land of Moab, inhabited by the tribe of Reuben. The two places thus connected the inheritance of the tribes in Canaan with that of the tribes beyond the river Jordan. So abundant are the fish in the healed waters of the Dead Sea, that fishers occupy its banks from Engedi to En-eglaim: the fish denoting living truths, and fishing the acquirement of such truths for the purposes of the spiritual life, the fishers denoting the rational faculty itself by which truth is sought and acquired.

From Engedi to En-eglaim is from the inmost to the outermost of the natural mind; which is in some measure evident from the names themselves; for Engedi means the fountain of the kid, and En-eglaim the fountain of the two calves, both signifying the good of innocence in the external man, the kid that which is interior, the calf that which is exterior.

The wilderness of Engedi, into which the living waters of the sanctuary flowed, is thus a symbol of the natural mind in its yet unregenerate state, but of that mind considered in its relation to the highest affection of the spiritual mind, represented by Judah, rendered still more specific by being here called, not the wilderness of Judah, but of Engedi.

A temptation represented by the wilderness of Engedi is, therefore, one that assaults the innocence that resides in the interior of the natural mind -- that innocence which is stored up therein by the providence of the Lord during infancy and childhood, and to which additions have been made in the course of the regenerate life, while acting from disinterested love and charity. For whenever we act from an affection of love to God and the neighbour, with a childlike forgetfulness of self, the divinely treasured-up innocence of our early life is increased and exalted. But no state is improved and confirmed without trial. The pure silver is not separated from the dross of our corrupt nature without passing through some fiery ordeals; and such trials are represented by those which David so often endured and was now subjected to.

The cave in which David and Saul were brought into such close connection with each other, and where David was tempted, so far as the persuasion of his followers and every consideration of self-interest and feeling of self-love could tempt him, to destroy Saul, is a fit symbol of that obscure state into which the mind is so often brought during times of trial. How blessed when, amidst the gloom which temporal or spiritual affliction casts over the mind, there is a principle in the soul that remains faithful to the law of mercy and truth, however great the temptation may be to violate it.

Saul, though personally corrupt, was still the Lord's anointed. He was the representative of truth Divine, not to be destroyed by Divine truth, but to be sifted by Satan, who may burn the chaff, but has no power to destroy the wheat. It is not the purpose of the Lord's saving operation in the human mind that any principle which has good in it should be destroyed, but that the good should be separated from the evil, and preserved. The contest between the inner and the outer man is to determine which shall have dominion; and it is the Divine purpose that this contest, which originates with the natural or outer man, shall end in the establishment of the dominion of the inner man, for this is the order of heavenly government. The natural mind, prone to the earth, cannot be raised at once above its own hereditary and even acquired condition, and brought willingly to acquiesce in the supremacy of that principle to which it was intended to be subordinate and subservient. But even when the natural man is still rebellious and unwilling to yield submission to the rule of the spiritual, there may be partial, if there is not entire, control acquired over him. If the spiritual man cannot bring the whole of the natural man under his power, he may at least lay hold on his mantle, or retain the skirt of it in his hand. When the afflicted woman but touched the skirt of the Lord's garment, she was made whole of her disease. And this miracle was performed to teach us that whoever lays hold of the Word of eternal truth and life, even of its lowest truths, will obtain the virtue that flows from the Lord's saving love and wisdom. So David, by taking and retaining the skirt of Saul's mantle, represented that he who lays hold of the ultimate of truth of the natural mind, has obtained the power which will enable him finally to acquire dominion over and possession of the whole. One great object of spiritual trial, besides confirming the inner man in the love of goodness and the faith of truth, is to bring the outer man to see and acknowledge the rightful claim and inevitable destiny of the inner man to be king, and to have the kingdom established in his hand. This has been effected, for the time at least, in the case of Saul, or of him whom Saul represented. But this transfer of power is not to be effected at once, nor even acquiesced in by one peaceful conquest of the spiritual mind over the natural. Our Lord was engaged in spiritual conflict to the end of His life. His state of destitution was like that of David. "The foxes have holes, and the birds of the air have nests; but the Son of Man has not where to lay His head." Like David with Saul, He returned good for evil to His persecutors; and when pressed by His disciples to bring down fire from heaven to consume His enemies, He, like David, when advised to slay Saul, told them they knew not what manner of spirit they were of. If David, in his merciful conduct to Saul, was a faithful type of the Lord Jesus, so was he also of what the Lord's disciple should be.

There is a distinction, however, to be made between Saul as David's enemy, and those who were the enemies both of David and of Saul, those who cared not for the transfer of the kingdom from Saul to David, but desired its destruction. These are the enemies of all true order; and, like the nations who invaded the land of Israel, and like the mercenary dealers who desecrated the temple, they are to be driven out. The natural mind itself, however, like Lot when made captive by the kings, must be preserved and delivered from captivity, and restored to a state of freedom (Genesis 14). And even when there is a difference between the thoughts and affections of the natural mind and the spiritual, as there was a contention between the herdsmen of Abram and the herdsmen of Lot, our language should be that of Abram on the occasion, "Let there be no strife, I pray you, between me and you, and between my herdsmen and your herdsmen; for we be brethren."


