
<<<
---
=== 18 - The Threatened Effects of Nasal's Churlishness are Averted by Abigail's
                                   Prudence.

1 Samuel 25

SAMUEL died, and he received the tribute due to a great prophet, for all the Israelites were gathered together and lamented him, and buried him in his house in Ramah, his own native town. Natural death and burial are, to the righteous, spiritual life and resurrection; and Samuel's death at this time may indicate not only life and immortality to himself, but the beginning of a new and higher life to the kingdom, and greater stability to the throne and the altar, which he had been he means of doing so much to establish.

We can hardly suppose that David would venture to appear among the assembled Israelites when they mourned for Samuel; but it is stated immediately after, that he arose, and went down to the wilderness of Paran. Paran was out of the land of Canaan. The wilderness of Paran was the home of Ishmael (Genesis 21:21), one of the resting-places of the Israelites in their journey (Numbers 10:2), and the place from which the men were sent to spy the land (Numbers 13:3). The meaning of the wilderness may be known from the meaning of the mount, as spoken of by Moses and by Habakkuk. Moses says, "The Lord came from Sinai, and rose up from Seir to them; He shined forth from mount Paran, and He came with ten thousands of saints: from His right hand went forth a fiery law for them" (Deuteronomy 33:2); and Habakkuk says, "God came from Teman, and the Holy One from mount Paran. His glory covered the heavens, and the earth was full of His praise" (Habakkuk 3:3). Seir and Teman have relation to celestial love, and mount Paran to spiritual love. The wilderness of Paran, considered as a place of refuge in states of trial, signifies temptation in regard to spiritual love; as a dwelling-place, it means the life of the spiritual man as to good. Paran itself spiritually means illumination from the Lord's Divine humanity. Regarding David as a type of the Lord, his going down to the wilderness of Paran describes the Lord's humbling Himself, to endure, for our sakes, some of the deepest of the temptations by which He made His humanity Divine, so that His glory might cover the heavens and the earth be full of His praise, and from the right hand of His power might go forth the fiery law of His love. For it is to the Lord Jesus that the words of Moses and Habakkuk relate. And for what was it that the Lord came from mount Paran, with the ten thousands of His saints, but that He first went down to the wilderness of Paran, as He here does in the person of His representative, with the small band of His humble followers? "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom." "Ought not Christ to have suffered these things, and to enter into His glory?"

We have entered thus minutely into this particular, principally because of its connection with what now follows.

The sacred writer relates that "there was a man in Maon whose possessions were in Carmel; and the man was very great, and he had three thousand sheep, and a thousand goats: and he was shearing his sheep in Carmel. Now the name of the man was Nabal; and the name of his wife was Abigail: and she was a woman of good understanding, and of a beautiful countenance: but the man was churlish and evil in his doings; and he was of the house of Caleb." The inspired historian goes on to relate that David, hearing that Nabal was shearing his sheep in Carmel, sent ten of his young men to him, saying, "Give, I pray you, whatever comes to your hand to your servants, and to your son David." This was asked on the ground that David and his men had been guardians of his possessions and protectors of his shepherds. The respectful request Nabal insultingly refused. On receiving his answer, David, with four hundred men, went up with hostile intent to go to Carmel. But Abigail learning how matters stood, went, with abundance of provisions, to meet the insulted and incensed leader of this determined band. The result was that David was propitiated, and Abigail was sent away in peace. On her return she found Nabal holding a feast like the feast of a king, and she was prudently silent; but in the morning she told him, when his heart became as a stone, and in ten days the Lord smote him that he died. When David heard of the death of Nabal, he sent and communed with Abigail, and she became his wife.

This is the meagre outline of a narrative which occupies the whole of a long chapter. No explanation of it appears in our author's published writings; but in what may be regarded as his first essay as an expositor, in a commentary which he laid aside to write his first and greatest work, "Arcana Coelestia," he enters minutely into the subject, and explains it according to what he himself has called the internal historical sense, so far as he then perceived it.

The Messiah is represented by David; the Jewish people by Nabal; the representative Church, which, according to order, was instituted very much like the ancient Church, by Abigail, whom afterwards the Messiah, understood by David, married, and delivered from those who are signified by Nabal. It may be necessary here to say that, while dispensations change, the Church remains ever the same. The Church itself consists of the immutable principles of love to God and charity to men; but these have a different quality according to the truth to which they are united or adjoined. The Church, as it has existed under its several dispensations, is like a woman who has been married successively to several husbands. The womanly character of her love remains essentially the same in all her unions, but it is modified in each according to the wisdom of the husband. Love to God and man were different, because they were differently understood, under the Israelitish dispensation from what they had been under the ancient, and from what they became under the Christian dispensation. Yet the Israelitish dispensation, as it existed according to Divine order, although a lower, was not a distorted, form of the ancient Church. It could not have been a representative Church, nor even the representative of a Church, if its institutions had not been according to Divine order. The dispensation, however, degenerated, and when the Lord came into the world the Jewish people had become as Nabal; they reviled and refused to admit the claims of Him whom David represented, although He had been the Shepherd of their shepherds and Guardian of their flocks.

Nabal is described as very great, having three thousand sheep and a thousand goats. The Jewish people, to whom the representative Church, as a wife, was adjoined, were great and rich in spiritual things, compared with the nations around them. Yet the charity and faith which they possessed in abundance, and which are meant by Nabal's thousands of sheep and goats, were rather of the letter than of the spirit. The character of the people, in regard to their possessions, may be indicated by what is added to the description of Nabal's wealth, that he was shearing his sheep in Carmel. For although sheep-shearing has its favourable meaning, it has also its unfavorable side, since there are shepherds who care more for the fleece than for the flock. These are the evil shepherds, against whom a woe is pronounced, because they cat the fat and clothe themselves with the wool (Ezekiel 34:2). Nor does this apply to those only, who are usually meant by pastors; but is to be understood of all whose care for religion is not for its own sake, but for the sake of honour and gain.

Nabal was shearing his sheep in Carmel. This is not the Carmel so celebrated in Scripture for its richness and beauty, and which, from its vineyards, signifies the spiritual Church; but seems to have been a place rich in pasture, and has therefore a lower though similar meaning. Yet although Nabal was shearing his sheep in Carmel, that was not his native place. He is indeed called a Carmelite (1 Samuel 30:5; 2 Samuel 2:2) from his residing in Carmel, but he is described as a man of Maon, whose possessions were in Carmel, and which he may have acquired through Abigail, who was in all probability a native Carmelitess, as she is called (1 Samuel 27:5). The Jewish people, to whom the representative Church was adjoined, were like the man of Maon united to a woman of Carmen and the affections of charity and the perceptions of faith which they possessed, and which were represented by Nabal's flocks, took their character from Carmel, in whose pastures Nabal fed his flocks, rather than from the wilderness of Maon, where his native town was, thus from Abigail rather than from Nabal. The Jews were rather the custodians than the possessors of the spiritual principles of the Church, which they preserved in representatives until the coming of the Lord, who removed the veil and brought all hidden things to light.

Abigail is described as a woman of good understanding and of a beautiful countenance, but Nabal as churlish and evil in his doings. The Church described by Abigail, like the primitive, was of good understanding, which consisted in understanding what was represented by types and other things of a like nature; and was of a beautiful countenance, beauty in the interior sense denoting goodness and in the inmost sense holiness. The churlishness and evil-doing of her husband describes the disposition and character of the Jewish people, to whom the Church represented by Abigail was as a wife.

David sending to Nabal with a salutation of peace, and asking that the young men may find favour in his eyes, and receive of his hand some beneficence for themselves and for his son David, represents what the Lord Himself describes in His parables, the lord sending his servants to receive from the husbandmen of the fruits of the vineyard. But the Jewish people treated the Lord's servants as Nabal treated David's young men. As Nabal refused to acknowledge David, and reviled him, so the people refused to acknowledge the Messiah, and inveighed against Him continuously, just as the husbandmen of the parable shamefully treated their lord's servants, and not only sent them away empty, but killed the son, who was the heir, when he at last came to them, as they had killed some of his servants, that the inheritance might be their own.

David's going up with his armed men with the intention of slaying Nabal and his household, is also expressed in the same parable by what the Lord's hearers said, in answer to His question, "When the lord therefore of the vineyard comes, what will he do to those husbandmen? They say to Him, He will miserably destroy those wicked men, and will let out his vineyard to other husbandmen, who shall render him the fruits in their seasons." This, however, was what the Jews deserved at the Lord's hand, not what He inflicted upon them. The vineyard was indeed taken from them, and given to others, but the Jews destroyed themselves as did Nabal, and as did afterwards Judas, by both of whom the Jews were represented.

In the crisis which affairs had now reached by Nabal's churlish conduct, a young man told Abigail how David had sent messengers out of the wilderness, and his master had railed on them, although the men had been very good to Nabal's shepherds, and they were not hurt, neither missed anything, as long as they were conversant with them, when in the fields; and the young man entreated his mistress to consider what she would do, for evil was determined against the master and his household. In this is narrated, respecting the Jewish Church, that she had been preserved by the Messiah, that she had not suffered dishonour, and had been often delivered from her enemies; that she missed or wanted nothing during all the time He dwelt with them, for He dwelt with them when they called upon the Lord, that is, when they were in the field, and when they fed their flocks. Wherefore the Church, as the wife, is admonished by her pastors and others that evil is determined. But Nabal is a son of Belial.

Abigail, when warned by the servant, "made haste, and took two hundred loaves, and two bottles of wine, and five sheep ready dressed, and five measures of parched corn, and an hundred clusters of raisins, and two hundred cakes of figs, and laid them on asses." That is, the Church, represented by Abigail, with the eager earnestness signified by haste, took spiritual good and truth, meant by bread and wine; and rational good and truth, meant by the dressed sheep and the raisins; and natural good, meant by figs, and disposed them in the scientifics or knowledges of good and truth, meant by asses. Abigail, having sent on her servants before her, went forth to meet David, "and it was so, as she rode on the ass, that she came down by the covert of the hill, and, behold, David and his men came down against her; and she met them. And when Abigail saw David, she lighted off the ass, and fell before David on her face, and bowed herself to the ground, and fell at his feet." This Oriental mode of salutation is very expressive of that profound humiliation and self-abasement which the Church owes to the Lord, and which Abigail's prostration represents. The wife of Nabal, by her address to David, shows herself to be a woman of good understanding. "Upon me, my lord," she exclaims, "upon me let this iniquity be," and she proceeds to plead her cause with words of more than human eloquence; for the words Abigail now speaks, she speaks, our author says, by the Spirit of the Lord, for they contain within them things Divine. First she throws herself at his feet, which expresses adoration. She confesses iniquity in herself, saying, "Upon me let this iniquity be." She describes the people by her husband, calling him foolish, as his name imports; like the people, he was foolish, nay, might be considered insane; so that to punish the foolish for their insanity would be contrary to justice. She implores only for grace. Abigail pleads that she had not seen David's young men, when they came to and were repelled by her husband, which signifies the representative Church, which was pure like the primitive. So the Church Brings gifts, which are spiritual things, such as burnt-offerings and sacrifices, meat-offerings and drink-offerings, sin-offerings and peace-offerings, which constituted the externals of worship in the representative Church, and which were expressed by the gifts now offered by Abigail to David -- by the Church to the Messiah. Abigail prays David to forgive the trespass of his handmaid; for the Lord would certainly make him a sure house: because he fights the battles of the Lord, and evil had not been found in him all his days. This is truly descriptive of the Messiah, and of Him only. He it is who forgives sin, by removing it; for He fought the battles of the Lord in His conflicts with the powers of darkness, and His victories over them; and which He still does in opposing and overcoming the evils of the human heart, wherein, as well as in His general Church, the Lord makes for Him a sure house, because they are built on the foundation of truth and righteousness. He and He alone it is in whom evil has not been found all His days; for He alone of all men lived without sin.

"Yet a man," she says, "has risen to pursue you, and to seek your soul." Saul is here distinguished from the enemies of the Lord against whom David fought; for although Saul fought against David, David did not fight against him. Nay, while both fought the battles of the Lord, David had to endure this separate and internal conflict. This, we have seen, and will have occasion further to show, is entirely consistent with the view of the antagonism of the letter to the spirit, or rather of the apparent truths of the letter, through which temptations come, to the spirit, against which they are directed; whereas the
"enemies "are the evil spirits themselves that tempt, like that by which Saul was possessed. "But," Abigail continues, "the soul of my lord shall be bound in the bundle of life with the Lord your God; and the souls of your enemies, them shall he sling out, as out of the middle of a sling. And it shall come to pass, when the Lord shall have done to my lord according to all the good that He has spoken concerning you, and shall have appointed you ruler over Israel; that this shall be no grief to you, nor offence of heart to my lord, either that you have shed blood causeless, or that my lord has avenged himself: but when the Lord shall have dealt well with my lord, then remember your handmaid." This, according to our author, clearly treats of the life after death, and the last judgement.

The souls of the righteous shall be bound up in the bundle of life with the Lord God, and the wicked, who are meant by Hi enemies, shall be cast out, as from the middle of a sling; and Jehovah, when He shall have done or accomplished all the good that He has spoken concerning Him, shall He make ruler over' Israel. The supplication of Abigail for the house of Nabal, like that of Abraham for the inhabitants of Sodom, is a prayer of the Church for her people, her children, that in the judgement the innocent may not perish with the guilty. Abigail's final petition, "when the Lord shall have dealt well with my lord, then remember your hand-maid," is, spiritually, a prayer that the sin of the people may not bring ruin upon the Church which has been united or adjoined to them -- that though the dispensation should perish, the Church may remain.

David listens to Abigail's prayer. He blesses the Lord God of Israel for having sent her to meet him, and blesses her for having, by her blessed advice, kept him from shedding blood, and avenging himself with his own hand, since, except she had come, he would, by the morning light, have left no male alive. He receives the present she had brought him, and desires her to go up in peace to her house. Thus it repented him; for he had hearkened to her voice, and accepted her person. This, understood of the Lord and His Church, presents the subject of the relation that exists between them, and of the influence they have upon each other, as we find it represented in Scripture. According to the letter of the Word, the Lord is determined to take vengeance on the people for their sins, but by the penitence and entreaty, either of themselves or of one who takes their place, He is turned from the fierceness of His anger to clemency and mercy. Yet we know there is no anger in God, no shadow of turning from His infinite love and mercy. Still the appearance of God's anger against sinners, and His taking vengeance on them for their sins, expresses a terrible reality. It expresses nothing less than the absolute opposition and irreconcilable hostility between holiness and sinfulness -- holiness in God and sinfulness in man; while the seeming case with which the Lord is propitiated, and His vengeance gives place to mercy, expresses the encouraging truth, that penitence never fails to remove hostility and effect reconciliation, since it removes sin, which is the only cause of hostile separation. David had threatened that by the morning light he would have left none of Nabal's household alive. The morning is a time for judgement. "O house of David, thus says the Lord; Execute judgement in the morning, and deliver him that is spoiled out of the hand of the oppressor, lest My fury go out like fire, and burn that none can quench it, because of the evil of your doings" (Jeremiah 21:12). Yet David's vengeance was to have been executed before the morning light, so that the dawn of a new day would have found his house desolate. In accordance with the view, that the subject of this chapter is the end of the Jewish and the beginning of the Christian dispensation, the words of David imply that, but for the interposition of the representative Church amongst them, the Jewish people would have been unable to endure the Lord's presence among them, even when veiled in humanity. Had not John the Baptist, by preaching and baptizing, prepared the way of the Lord, His presence would have smitten the earth with a curse, the Church would have perished with the dispensation, and the morning light would have shone on impenetrable darkness and gloom.

But that which David was dissuaded from doing to the whole house of Nabal, the foolish man did to himself. On Abigail's return she found her husband feasting, and Nabal's heart was merry within him, for he was very drunken. Spiritually understood, this feast, which was like that of a king, is the profanation of goodness and truth, which is meant by eating and drinking to excess. So we find the consummation of the age described. The days of the Son of Man, when He was to come to judgement, were to be like the days of Noah, when they did eat and drink, until the Flood came; and like the days of Lot, when they also ate and drank, and fire and brimstone were rained from heaven, and destroyed them all, except the remnant that, in both cases, were saved. When Abigail told Nabal, his heart died within him, and he became as a stone. And it came to pass about ten days after, that the Lord smote Nabal, that he died. The heart dies when all love, which is the life of the will, is extinguished; and man himself becomes a stone -- not merely as a stone -- when nothing remains of religion but a hard and lifeless faith. Nabal becoming a stone, like Lot's wife becoming a pillar of salt, is representative, not only of the extinction of the life of truth, which is charity, but the perversion of the truth itself.

When David heard of Nabal's death, he sent and communed with Abigail, to take her to him to wife. The description of Abigail's coming to David, with her five damsels, like the five wise virgins that went in with the bridegroom to the marriage, is a spiritual description of the marriage of the Lord with the Church, her five damsels representing the spiritual affections and graces which belong to the Church, and are attendant upon her. Thus the Church which had been joined to the Jewish people, became, at the end of the Jewish dispensation, in the true sense the Lord's bride and wife, for He having become Man, was in the full sense the bridegroom and husband of His Church. But by the Incarnation, the Lord not only united to Himself the Church as it existed among the Jews, but also as it existed among the Gentiles. This Church was represented by Ahinoam the Jezreelitess, whom also David took to wife; and Abigail and Ahinoam were both of them his wives. "But Saul had given Michal his daughter, David's wife, to Phalti, the son of Laish, which was of Gallim." We have already seen that Michal, the daughter of Saul, represented a natural affection, and we shall have further opportunities of seeing this exemplified. Saul intended her to be a snare to David; and when she no longer served that purpose, she was given to another. According to the custom of the times, when women were considered the property of their parents, and might be disposed of at their pleasure, Michal, like Samson's wife, was given to another man, without the consent of her husband, or even without consulting him. Saul may have had the same seeming justification that the parents of Samson's wife pleaded. Michal did not share David's fortunes during his fugitive life; and Saul may have considered that he was justified in annulling David's claim to her as his wife. From a higher point of view, the history of Michal shows her to have represented the Church more as the daughter of Saul than as the spouse of David, partaking more of the merely human than of the purely Divine element, more of the affection of truth Divine than of Divine truth, yet capable of being joined now to one and now to the other; like Adonis living alternately in the upper and in the lower world, and serving in some measure to connect them with each other. Michal is now away from David and joined to Phalti, who, we shall see, has to render her up to David again.


