
<<<
---
=== 22 - Preparation for Battle. The Amalekites Spoil Ziklag. David recovers all

1 Samuel 29-30

The cloud that has hung over Saul, and darkened his mind and his prospects, now rapidly becomes more dense and threatening. The Philistines, who had been collecting their forces in Shunem, now gather together all their armies in Aphek; and the Israelites pitch by a fountain which is in Jezreel. Had Saul been wise enough to retain David in his service, he would have had a tower of strength in him whom his enemies feared and his subjects loved; and we can hardly suppose that the king did not now secretly lament the folly, at least, of his own suicidal conduct. But he had not only deprived himself of David's powerful assistance, he had thrown him into the arms of the very enemy who had made war against him, the dread of whose hosts had driven him, when heaven was shut against him, to knock at the gate of Sheol, and ask counsel of the dead.

The Philistine armies set out on their march to Jezreel, where the Israelites were encamped; "and the lords of the Philistines passed on by hundreds, and by thousands: but David and his men passed on in the rearward with Achish." David would thus appear to have joined his forces to those of the enemy, to war against his country. Whether he would have fought in the enemy's ranks cannot perhaps be determined. The trial was prevented by the Philistines themselves; and it is not improbable that, had he actually engaged in the conflict, the result would have verified the suspicion of the Philistine nobles, which they urged upon Achish, as the ground of their demand that David should return to Ziklag, "lest in the battle he be an adversary to us: for with which should he reconcile himself to his master? should it not be with the heads of these men?" And that they believed he would be a formidable adversary is evident from their repeating the triumphal song of the women, when David was returning from the slaughter of Goliath, "Saul slew his thousands, and David his ten thousands." David must either have been in bitter earnest or have cleverly dissembled; for when Achish, reluctantly yielding to the remonstrance of his nobles, urged David's return, "David said to Achish, But what have I done? and what have you found in your servant so long as I have been with you to this day, that I may not go fight against the enemies of my lord the king? "The king's confidence in David seems to have remained unshaken. "I know," he says, "that you are good in my sight, as an angel of God: notwithstanding the princes of the Philistines have said, He shall not go up with us to the battle. Wherefore now rise up early in the morning with your master's servants that are come with you: and as soon as you be up early in the morning, and have light, depart. So David and his men rose up early to depart in the morning, to return into the land of the Philistines. And the Philistines went up to Jezreel." David's answer is consistent with either supposition. But there is no reason to believe that he who so completely deceived Achish on a former occasion would of necessity be faithful to him now.

These personal considerations are interesting to us chiefly for the lessons we may derive from them, not merely by moral reflection, but by spiritual interpretation. If David is a type of the spiritual man, and even of the Lord Himself as Divine truth, that must hold good in this instance, as well as in others in which he manifests true nobleness of character; always understanding that the acts of representative men do but show forth tenderness in those they represent. There are, besides, different aspects and appearances of character, answering to the states of those towards whom representative men act. The Lord appears to every man according to his state. "With the pure You will show Thyself pure; and with the forward You will show Thyself forward" (Psalms 18:26). These words were uttered by the Psalmist in reference to the circumstances of the present history. "David spoke to the Lord the words of this song in the day that the Lord delivered him from the hand of all his enemies, and from the hand of Saul." The psalm, in its inmost sense, is prophetic of the Lord, whose experience was typified by that of David. So must the history be.

We have seen that David's raid against the Amalekites was represented to Achish as having been an attack upon Judah; and that this false representation symbolized the false conception which those who are in the doctrine of faith alone form of the teaching of Divine truth, that it is hostile to what they call self-righteousness, but not to what is rightly called self-love. David's position now is different in one respect from what it was then. On that occasion he was believed to have fought of his own accord and with his own men against Israel; on this occasion he is to fight, not only against Israel, but with Philistia. The cases are different. The weakening of an enemy or an opponent may strengthen our own position, but only when it is done by ourselves, or by others in concert with us. One may be a foe to our enemy, and yet not a friend to us. David might have been supposed desirous to inflict injury on his own people, and yet be unwilling to assist another nation to conquer them. The lords of the Philistines were not only of this opinion, but believed he intended to turn against them in the day of battle. Achish seems to have still regarded David as his friend, and as honestly disposed to fight with him against his enemies, and thus against Saul, who was the enemy of David. The circumstances here recorded respecting David and the lords of the Philistines again remind us of those related of Abraham and Isaac with respect to the Philistines among whom they dwelt. We have seen that these patriarchs deceived king Abimelech, by each representing that his wife was his sister. Yet we know that this has a high and holy signification, which is this, that rational truth is permitted to those who are not capable of receiving Divine truth. Rational truth is related to good as a sister to a brother; Divine truth is related to good as a wife to a husband.

But the circumstance now related of David resembles that which happened to Abraham and Isaac when the Philistines discovered that Sarah and Rebecca were the wives of Abraham and Isaac. They were dismissed; and in the case of Isaac, at least, for a reason similar to that which led the lords of the Philistines to demand the dismissal of David. "Abimelech said to Isaac, Go from us; for you are much mightier than we "(Genesis 26:16). In the case of the patriarchs there was the discovery, in David's case there was only the suspicion, of deceit; but that suspicion amounted to and had the effect of certainty. When, in intellectual warfare, men suspect or believe that a truth on which they have relied for support is likely, not only to fail them but to turn against them in the hour of conflict, if they are wise in their generation they will reject it. In dialectics a bad argument turns against him who employs it. In religious polemics men are driven, in extreme cases, to deny the genuineness of a text, or the authenticity of a history, if they certainly know or strongly suspect it will prove false to their cause. Those who believe in the mere humanity of Jesus deny the genuineness of that part of the New Testament which gives an account of His miraculous conception. Some deny the genuineness of the Lord's miracles, some the fact of His resurrection. But it is characteristic of those whom the Philistines, even in their best state, represented, that they receive not the real but the apparent truths of the Word. They must see God, if not altogether such an one as themselves, yet as having some considerable resemblance to them in character. Indeed many of the false ideas men form of the Divine character, and of His dealings with His creatures, are to a great extent a reflection of their own character and of their dealings with each other.

When David and his men returned to Ziklag on the third day they found that "the Amalekites had invaded the south, and Ziklag, and smitten Ziklag, and burned it with fire; and had taken the women captives, that were therein: they slew not any, either great or small, but carried them away, and went on their way." Here was a calamity that David had brought upon himself and all his company, by following the Philistine army. It represents one of those trials that come upon us when our attention and our energies are turned to some new enterprise, and we leave some important interest unprotected. The Amalekites, true to their character, had invaded the south and attacked Ziklag, when they knew that their defenders were gone, and they could make an easy conquest. Falsity grounded in interior evil is ready to rush in when truth grounded in interior goodness recedes from the light, as David departed from the south when he went to join Achish and when he followed the Philistine army. And, indeed, the condition of the mind, when truth comes down from the perceptive to the reasoning faculty, is favourable to the insinuation of those false suggestions that try our inward faith, which is that of the heart rather than that of the understanding; and which, for the time, deprives the perceptions of truth of the affections of goodness, as the Amalekites made captives the wives and sons and daughters of David and his men. When the affections are held captive, which they are in temptation, which is spiritual captivity, all the delight of life is taken away; as "David and the people that were with him lifted up their voice and wept, until they had no more power to weep." But "David was greatly distressed; for the people spoke of stoning him, because the soul of all the people was grieved, every man for his sons and for his daughters." The people in the wilderness threatened to stone Moses, when they thirsted, and there was no water for them to drink (Exodus 17:4). In states of severe trial the mind, in bitterness of spirit, is brought, in extreme cases, to the verge of desperation, in which it is tempted to extinguish in itself all the truth of faith and all faith in the truth. This is the threat of the people to stone Moses, and also that of the people to stone David. This threatened violence led David, as it had led Moses, to seek strength where only it can be found. "David encouraged himself in the Lord his God." Truth draws its strength from love; and the true effect, as it is the real purpose of trial, is to strengthen the bond of union between truth and love, first in the inner, next in the outer man.

But the inner man seeks the direction of wisdom as well as the strength of love. David called on Ahimelech the priest to bring the ephod; "and he inquired at the Lord, saying, Shall I pursue after this troop? shall I overtake them? And He answered him, Pursue: for you shall surely overtake them, and without fail recover all." This Divine answer inspired David's despairing followers with hope. "So David went, he and the six hundred men that were with him, and came to the brook Besor, where those that were left behind stayed. But David pursued, he and four hundred men: for two hundred abode behind, which were so faint that they could not go over the brook Besor." It would be straining resemblances to compare David's expedition to that of Gideon against the Midianites, and Amalekites, and children of the east, recorded in Judges 7; but there are two particulars that have some similarity to it. It may be reasonably supposed that six hundred men were not too many to attack a host that had invaded the south and Ziklag, and had taken great spoil out of the land of the Philistines, and out of the land of Judah; yet the number is reduced to four hundred. Two hundred remained behind, indeed, because they were so faint that they were not able to pass over the brook; but the four hundred were no doubt more suitable for the work than the six hundred. The number four, like two, is expressive of the conjunction of goodness and truth; and the purpose of the present expedition, spiritually interpreted, is to restore that conjunction. For the Amalekites had carried away the wives of David and his men; thus representing the severance of the spiritual marriage, which it was the chief purpose of David and his men representatively to restore. It is not said, as it was of Gideon's army, that David's men were too many, or that the number was ultimately reduced by the manner in which the men drank of the water. David's men were faint, not, like some of Gideon's men, faint-hearted; they were weary, no doubt with their previous toil; they were willing but not able; their progress was arrested by the brook, which they were not able to pass over. Brooks and rivers are emblematical of truth; but passing through them is a symbol of passing through trial and temptation. This was represented by the Israelites passing through the Jordan. And the Lord promises to the redeemed," When you passest through the waters, I will be with you; and through the rivers, they shall not overflow you"
(Isaiah 43:2). Those of David's men who had not sufficient strength to cross the brook, were those who had goodness, but not truth corresponding to it, and were unable to pass through the trial that was before them. Goodness alone and truth alone are equally powerless. Truth has all its power from goodness, and goodness ever uses all its power by truth. Yet those who have goodness without truth, though unable, in that state, to pass through some of the trials and engage in some of the conflicts of the spiritual life, are privileged to share in the spoil which others acquire; which we shall see exemplified in the case of David's men and others, who went not with him against the Amalekites.

When the Israelites were in pursuit of the enemy, "they found an Egyptian in the field, and brought him to David." Servant to an Amalekite, his master had left him when he fell sick, and he had eaten and drunk nothing for three days and nights. When he received nourishment, his spirit came again; and, besides telling where the Amalekites had been, he engaged to conduct David to where they now were. Science, which serves the evil, can also serve the good. Knowledge is an instrument that can be employed in the service both of error and of truth. Without knowledge there can be neither truth nor error; for that of which nothing is known can neither be affirmed nor denied. Knowledges are of facts; truth or error is the conclusion we draw from them, or the principle they serve to confirm. Science helps the believer to confirm the truths of revealed religion, and the unbeliever to deny them. Science is a receptacle that may be filled with what is true and good or with what is false and evil, as the young Egyptian could be nourished either by an Amalekite or by an Israelite. It may also be sickly or healthy, and may be abandoned by a master whom it is no longer able to serve. Science becomes sick to the evil when they become weary of science, which they do when, having served its end, they despise and reject it as a means. When men become openly wicked, they no longer try to make others believe they are righteous. When a scientific is emptied of falsity and evil, and is filled with goodness and truth, spiritual and natural, as the Egyptian after three days' fasting, was fed with bread and water, figs and raisins; and is devoted to the service of truth, and thus secured against destruction and profanation, as David swore by God to the young man that he would neither kill him nor deliver him to his master; then may it become instrumental in guiding the mind to the discovery of the falsity of evil which it desires to overtake and overcome.

Led by the Egyptian, David came upon the Amalekites, who "were spread abroad upon all the earth, eating and drinking, and dancing, because of all the great spoil that they had taken out of the land of the Philistines, and out of the land of Judah." The whole natural mind given up to sensual pleasure, and the higher faculties spoiled of their possessions to feast and gratify the lower appetites, the camp of Amalek presents a true image of the carnal mind and of the carnal man. But like the natural man when he abandons himself to sensual enjoyment, the Amalekites had thought themselves secure and had neglected to watch, and at an hour that they thought not the judgement of truth had come upon them. Like all judgement, this came upon the Amalekites in the night; for "David smote them from the twilight even to the evening of the next day: and there escaped not a man of them, save four hundred young men, which rode upon camels, and fled." The twilight is the dawn of a new state, when spiritual light is let in upon the mind, to reveal its character, and bring it under the operation of the Divine truth that judges, the completeness of the judgement being indicated by the continuance of the slaughter, from the twilight of one day to the evening of another. The four hundred young men that escaped may give us some idea of the entire number of the host. But the singular circumstance of these alone escaping, and their fleeing upon camels, has a meaning more than historical. The four hundred young men of the Amalekites are those who are not confirmed in the principles which Amalek represented, but have some general knowledge of, and some affection for, what is good and true, their knowledges being symbolized by the camels. It is a no less singular circumstance that the Divine promise that David would recover all should be so literally fulfilled: for "David recovered all that the Amalekites had carried away: and David rescued his two wives. And there was nothing lacking to them, neither small nor great, neither sons nor daughters, neither spoil, nor any thing that they had taken to them: David recovered all." This, both in fact and meaning, is like the complete recovery by Abram of all that the rebel kings had carried away. "And he brought back all the goods, and also brought again his brother Lot, and his goods, and the women also, and the people" (Genesis 14:16). In Abram's case, too, the Amalekites were concerned: for Chedorlaomer and his confederate kings smote, besides others, all the country of the Amalekites. Complete liberation from the dominion, or attempted dominion, of the natural man over the spiritual, was represented by David's, as by Abram's recovery of all that had been carried away, both captives and spoil.

On his return with the spoils of victory, consisting, besides what he recovered, of all the flocks and herds of his enemies, David met the two hundred men who had been left behind. Those who had gone with him objected to these receiving any part of the spoil, except every man his wife and children. But David decided that they should not do so with that which the Lord had given into their hand, but "as his part is that goes down to the battle, so shall his part be that tarries by the stuff: they shall part alike. And it was so from that day forward, that he made it a statute and an ordinance for Israel to this day." We have seen that the men who stayed behind, being too weary to pass through the brook, represented those who, though principled in good, are not yet possessed of truth sufficient to enable them to engage, with a reasonable prospect of success, in the active conflicts of the spiritual life. Truth, we have also seen, has no power but from good, and good has no power but by truth. There is no direct conflict between good and evil. Good fights by truth, evil by falsity. And as every evil defends itself by its own particular falsity, so does every good defend itself by its own particular truth. He only is able to fight against an evil who has the truth as well as the good that is opposed to it. But he that goes not down to the battle can tarry by the stuff. This "stuff" was no doubt the baggage, the impedimenta, of David's little army. But we have seen, in speaking of the stuff among which Saul hid himself (1 Samuel 10:22), that it literally means vessels. And vessels, we have also seen, signify scientifics or knowledges, which are not truths, but the vessels that receive and contain them. Truths that we know are knowledges; knowledges that we understand are truths. Knowledge comes before understanding. We must know a truth before we can understand it, and we must understand a truth before we can rightly use it. Those only who understand a truth can enter into conflict with its opposite falsity. But those who only know a truth, though they cannot fight, can guard and keep that which supplies others, and which some day will supply themselves, with the means of vindicating truth against falsity, and thus good against evil. And the ordinance for spiritual Israel is, that all who are actuated by the same good end, and combine their efforts, though in different ways, to attain it, shall share alike in the spoil with the more active, who directly acquire it. A wife who tarries by the stuff at home shares alike with her husband in the spoil he acquires by his more active duties in the world. So those who perform more of the woman's part in the business of the spiritual life, by watching while others toil, share equally with them in the results. In the Church of God there is diversity of gifts but the same Spirit; and all who are influenced by the same spirit of love, whatever their several gifts may be, share alike in the benefits of a general acquisition.

In the "Adversaria "this equal division of the spoil is said to teach the same truth as the parable of the labourers in the vineyard; those who worked one hour being made equal to those who had borne the burden and heat of the day. In the Writings themselves the different hours at which the labourers were hired are explained to mean different states of life. Those hired at the third, the sixth, and the ninth hour signify those who are in states of truth; and those hired at the eleventh hour signify those who are in a state of good though not yet of truth, but who are in a receptive state, such as well-disposed young people, whose faculty of understanding is not yet matured. These last are they who tarry by the stuff. They know but do not yet understand the truth, and therefore do not go down to the battle.

Besides giving equal shares to his men, when he came to Ziklag David sent a present -- a blessing -- of the spoil of the enemies of the Lord to the elders of various cities, chiefly in Judah, and to all the places where David and his men were wont to haunt. It is said of Him whom David represented, that He spoiled principalities and powers (Col 2:15); and that He shall divide the spoil with the strong (Isaiah 53:12). Wherever the Redeemer has been received in His humiliation, there will His blessing descend in His exaltation. In the spoil He acquired by His victory over the powers of darkness and the glorification of His humanity, all the faithful share. This is emphatically "David's spoil." In delivering those whom the Amalekites had made captive, David representatively performed that Divine deliverance which he himself prophetically celebrated.
"You have ascended on high, You have led captivity captive: You have received gifts for men; yea, for the rebellious also, that the Lord God might dwell among them "(Psalms 68:18).


