
<<<
---
=== 23 - The Defeat of Israel and the Death of Saul

1 Samuel 31

the sacred writer, as the historian of the kingdom of Israel, gives a prominent place to whatever relates to its rulers and people, and only introduces the nations around them, as their history is connected with the main subject of his narrative. The kingdom of God, or the government of the Divine love and wisdom in the minds and affairs of men, is the grand theme of the inspired record; other principles and forces being introduced only as they aid or hinder its prosperity. As it is in the Word, so should it be in us. The Lord's kingdom should be the primary object of our attention and esteem, and all other things regarded only as they affect its stability and progress. With two short statements, that the Philistines and the Israelites had gathered their armies together for war, we have two long narratives, one of Saul with the witch of Endor, and the other of David with Achish and against Amalek. After these brief statements of preparation for war, we read, "Now the Philistines fought against Israel: and the men of Israel fled from before the Philistines, and fell down slain in mount Gilboa." Brief but pregnant announcement! War and defeat recorded in one short sentence. Yet this was no ordinary conflict either in itself or in its consequences. It did not, indeed, involve the fate of the kingdom of Israel, but it decided the fate of its first king. It disclosed, at the same time, the state and condition both of the king and the people in their relation to the Lord. The war itself might be no cause of reproach to Israel, but defeat was a sign of their moral degradation. No numerical inferiority could have made it necessary for the men of Israel to flee before the Philistines. If Saul had trusted in the strength of Israel, no power of the enemy could have overcome him. But he had sought to them that have familiar spirits; and now he saw the result of his moral weakness and practical infidelity. So is it when men substitute superstition for religion, or seek "for the living to the dead." When they have no living faith in God, they are punished by those who are in dead faith. Unfaithful Israel flee before the faith-alone Philistines. "Evil shall slay the wicked." But evil and unfaithfulness may seem only to be in Saul. Why should the people suffer on account of his sin? Children suffer for the sins of their parents, subjects for the errors of their rulers, soldiers for the incompetence of their generals. Yet the Israelitish people themselves were not blameless. They participated in Saul's persecution of David, whom they must have known as a national benefactor, and whose powerful aid some of them had received in their utmost need. The men of Keilah, whom he had so valiantly aided, were willing to betray him into the hand of Saul; and the Zephites both counselled and guided Saul in his pursuit of David. As they had joined Saul in his crime, they not unnaturally or unjustly shared in his punishment. But besides the operation of natural and moral law, there was, in the case of Israel, the operation of a spiritual law, by which the principal and the instrumental act and suffer together. This is the law which governs our mental and spiritual life. When we err in first principles, every subsequent step leads us further away from the right path, and from the true goal. When our ends are evil, our means are deceits, and our actions sins. The ruling love enters into all the lower affections, and gives them a character and determination agreeable to its own nature; it even overrules those whose character is inherently different from its own.

In accordance with this principle the main object of the history is to tell us of the fate of Saul. When the men of Israel fled before the Philistines, their pursuers aimed at something besides and higher than merely beating down the panic-stricken army. "The Philistines followed hard upon Saul and upon his sons; and the Philistines slew Jonathan, and Abinadab, and Melchi-shua, Saul's sons. And the battle went sore against Saul, and the archers hit him; and he was sore wounded of the archers. Then said Saul to his armour-bearer, Draw your sword, and thrust me through therewith; lest these uncircumcised come and thrust me through, and abuse me. But his armour-bearer would not; for he was sore afraid. Therefore Saul took a sword, and fell upon it. And when his armour-bearer saw that Saul was dead, he fell likewise upon his sword, and died with him. So Saul died, and his three sons, and his armour-bearer, and all his men, that same day together." No catastrophe so great as this had ever happened to Israel, no ruin of theirs was ever so complete. The nearest approach to it, and one which much resembles it, was that in which the ark of God was taken, and the two sons of Eli were slain, and Eli himself was killed by falling from his seat on receiving the news. But on that occasion the army, though defeated, was not annihilated. The two cases present other parallels. The sin of Eli was the cause of the one catastrophe, as the sin of Saul was of the other. And in each case a successor was divinely appointed in the lifetime of the legitimate but unworthy ruler, and was partly nurtured by the ruler himself. Samuel was to Eli what David was to Saul. Both circumstances teach the same general lesson, differing only as the representative character of the judge differs from that of the king.

In considering the subject for the purpose of learning its spiritual meaning and practical lessons, we need not dwell at any length on this catastrophe in relation to Saul himself. There may be something to admire in the desperate courage of the king, in engaging in this, which he no doubt believed would be his last and fatal conflict with the enemies of his God, his people, and himself. And this is all that can be said in favour of the king in this encounter with the Philistines. Saul was not wanting in courage, but in fidelity. To be faithful is more difficult, as it is more important, than to be courageous. Self-love or self-interest is sufficient to inspire courage where it does not naturally exist; fidelity often requires the surrender of both. Faithfulness to our duties and obligations sometimes demands the denial of even our best natural affections. Saul, in the early part of his reign at least, when he still was little in his own sight, showed himself capable of noble actions; and even in sparing Agag he may have been actuated by a generous impulse, but it was against the voice of God and reason. In his conduct towards David he manifested the character of the natural man) whose favour and dislike are not grounded in principle but in caprice, and whose tenderness and security are measured to others, not according to what they are in themselves, but according to what they are in relation to him. "If you love them which love you, what reward have you? do not even the publicans so?" Judged by the standard of religious morality, his conduct during the later part of his reign indicates a character almost diabolical. The nature of self-love, as the parent of all cruel and degrading passions, is fearfully exhibited in his conduct towards David; and his character is rendered more odious by its contrast with David's conduct towards him, of which we know not a nobler instance of patient endurance and magnanimous forbearance and forgiveness. But Saul, as we have formerly hinted, is not to be judged by the ordinary standard. We cannot regard him as of a perfectly sound mind. He was the subject of spiritual possession, not perhaps always, but during much of his official career. Yet under this view, his conduct affords us a most impressive lesson. It exhibits, more perfectly than could otherwise have been done, the intrinsic character of the natural man, and of the natural mind in every man. In Saul's experience, too, we see the misery and wretchedness which sin brings with it. And in his end we behold the consequence of forsaking God, and seeking what our diseased imagination desires to know by personal exchange with departed spirits.

But while it is profitable for us to reflect on Saul's personal conduct, it is far more agreeable and still more useful to consider his representative character, in the present case in reference to the last conflict and the closing scene of his life.

Nay, it shows what was the quality of the natural mind which the Lord in His marvelous condescension assumed from His fallen mother. Saul's character thus holds up to us a mirror in which we may see our own reflected, supposing we were to become subject to the same spiritual influence.

In considering the spiritual lesson which these events and circumstances teach, it is the representative character of the man and his doings that we are chiefly, and in some respects exclusively, to regard. The function itself with which he was invested was holy, and representatively Divine and spiritual. The function is adjoined to the person, but is not identified with him. Saul could, therefore, as the Lord's anointed, represent the regenerate man, and even the Lord in the flesh, and yet have nothing in his personal character answering to either. David clearly made this distinction in regard to him. As his persecutor, David held him guilty of sin; as the Lord's anointed, he held his person sacred. The Philistines and others who opposed Saul fought against him, and he fought against them, not in his private but in his official character, as the king whose kingdom they wished to subdue, and which he wished to defend. Their wars, therefore, represented spiritual wars, wars for and against the Lord and His kingdom. Yet the spiritual wars which those waged against the king of Israel represented are not to be understood as waged against the Lord personally. Personal warfare could only be carried on against Him once. Only when manifested in the flesh could the Lord be assaulted in person; and even then chiefly by the enemies of Himself and His kingdom, the spirits of darkness, called the devil and Satan. In all these conflicts the Lord was conqueror. How then could any of His conflicts be represented by those in which, like this last battle of Saul with the Philistines, Israel was defeated and Saul himself was slain, or slew himself? In temptation - conflicts there always is an appearance of defeat on the part of those who conquer. Our Lord's last and severest temptation, the passion of the Cross, presented this appearance. His death seemed to the spirits of darkness as the triumph of their power: they had overcome Him at last. But when on the resurrection morning He burst the bands of death, and rose in a glorified humanity having all power, their seeming victory was turned into overwhelming defeat, and they themselves were thrust down, to be held in everlasting subjection. Although visible in this one instance, all temptations have the same appearance and the same reality. The extremity of every temptation is attended with despair. And what is despair to the tempted, is triumph and seeming victory to the tempter. Every temptation is also attended by a death and a resurrection. Something of the old man dies, and something of the new man lives. The death of the old man is effected by evil spirits, and this is their seeming victory; and the resurrection of the new man is effected by angels, or by the Lord through angels, and this is their actual defeat. Evil spirits are thus the permitted agents of effecting the death of the old man, both generally as to his ruling love, and particularly as to his affections and lusts; they are also the dead that bury their dead, while the new man obeys the Divine command,
"Follow you Me."

The death of Saul, therefore, and of his sons, and the defeat of the armies of Israel, do not, cither when understood as referring to the glorification of the Lord or to the regeneration of man, mean the defeat and death of the spirit but of the flesh, or in reference to us, to what the apostle calls the putting off the sins of the flesh, dying with Christ that we may live with Him.

There is one particular relating to Saul's death that may seem to break through this analogy. Saul did not allow himself to be slain by the enemy; he took his own life. Yet in this he may, with all reverence, be considered to have represented the Lord, in regard to a truth which He declared respecting His own death. He said, "I lay down My life for the sheep. No man takes it from Me, but I lay it down of Myself. I have power to lay it down, and I have power to take it again. This commandment have I received of My Father" (John 10:15, 18). As
"the Word in its inmost sense treats solely of the Lord, and in that sense are described all the states of the glorification of His humanity, or of its union with the Divinity; and likewise all the states involved in the subjugation of the hells, and in reducing to order all things therein, as well as all things in the heavens;" it is evident that not only the annihilation of the Israelitish army, and the death of Saul's sons, but the death of Saul himself, must in the inmost sense have reference to the Lord in His conflicts with the powers of darkness and His victories over them, and to the glorification of His humanity. There is something similar to the flight of Saul's army and the death of Saul himself in the history of the Lord's life, immediately before His last great trial. When Jesus was seized by the officers of the chief priests, all His disciples forsook Him and fled. That flight of the Lord's little flock was far more momentous than the flight of Saul's great army; and the evil angels who were then exerting all their power to prevent their own subjugation, no doubt rejoiced at their own success. When on that memorable occasion the Lord's disciples fled, the Lord Himself sought no way of escape, and offered no resistance, but yielded Himself up into the hands of His enemies. If He who could have saved His life yet voluntarily laid it down by giving Himself to what He knew was certain death, was not this self-immolation? And might it not be typified, in the history of a representative people, by the last act of one who, however imperfect as a man, was yet, as the Lord's anointed, a type of the Anointed One, the Messiah?

We are to remember, too, that it was truth Divine in the Lord's humanity that was tempted and that died. It is truth Divine that is meant by the Son of Man. This is Divine truth finited and accommodated to the apprehension of angels and men, truth clothed with the appearances that bring it down to their states of thinking and even of feeling respecting things spiritual and Divine. Therefore, wherever, in the New Testament, the Lord speaks of His personal sufferings and death, He always speaks of Himself as the Son of Man, not as the Son of God. By this name the Lord also speaks of Himself as the Word. And now, when the Lord cannot be tempted and put to death personally, all that was done to Him and suffered by Him in the days of His flesh, can only be done to and suffered by Him in His Word, the Scriptures of truth, and in His Church and people. There is also a correspondence between the Lord as the Eternal Word, clothed in human nature, and the Lord as the Revealed Word, clothed in human language. The human nature which the Lord assumed had all man's hereditary imperfections; and the language which the Revealed Word assumed in coming down to men, expresses the truth according to fallen man's power of apprehension. It is possible, therefore, for Christians to treat the Lord's Word as the Jews treated the Lord Himself. Christians can deny and oppose the truth, as the Jews denied and opposed the Lord; they can even destroy the truth, as the Jews destroyed the Lord; for they can crucify to themselves the Son of God afresh, and put Him to an open shame (Hebrews 6:6). On this ground it is, that wherever in the Scriptures we read of the treatment which the Lord received, either in those who represented Him, as recorded in the Old Testament, or in His own person, as recorded in the New, we are to understand it as being descriptive of the treatment which the Word receives at the hands of those who are opposed to the principles of goodness and truth which it teaches, and are in the evil and false principles which it condemns.

This correspondence extends still further. Whatever relates to the Lord and His Word relates also to the Church; for the Church is the Lord's mystical body, the image of His own glorious body, and is formed from and upheld by the truths of His Word. But the Church is not to be regarded only as consisting of the general body of the faithful. It consists essentially of the principles of goodness and truth, which the faithful individually believe as well as collectively acknowledge. Thus the chain of analogy and connection descends from the Lord, through His Word, to His Church, both in heaven and on earth, thus from the Lord to the least of His disciples. What relates to one, therefore, relates to all, differing in regard to each according to the place it occupies in the descending scale, from its first cause to its last effect.

The literal sense of the Word consists, to a great extent, of appearances of truth, such as belong to the natural world. And these appearances have within themselves the means of their own correction. Apparent truths can be proved to be appearances by their own inherent contrariety to real truth, both in the works and in the Word of God, when the real truth has, in any instance, been discovered or revealed. The apparent truths of the Word have indeed a spiritual sense; but this spiritual sense is the soul or life which they contain, and which survives the sense of the letter, when this has perished. Let us be careful, however, to note that this is not to be understood of the whole letter of Scripture, but of its apparent truths only. For the literal sense of Scripture consists of real as well as of apparent truths. Real truths are true both in the letter and in the spirit, and are therefore immutable and eternal; apparent truths are true in the spirit but not in the letter, and are therefore mutable and transitory. It is true both in the letter and in the spirit, that the Lord is good to all, and His tender mercies are over all His works. It is true in the spirit but not in the letter, that the Lord is angry with the wicked every day. The spirit in this instance is opposite to the letter; for the spiritual sense is, that the mercy of the Lord is extended even to the wicked, in every state of their life, although, from their state of contrariety to the Lord's nature, His love appears to them as anger and even as hatred. The literal sense must therefore die that the spiritual may live. Indeed, when the spiritual sense, which is the only real truth which the words contain, is discovered or revealed, the literal dies as it were by its own hand. The sword of the Spirit, which is the Word of God in its genuine and spiritual sense, is that on which apparent truth falls. This is the case generally and particularly, in the whole Word and in every part. When the genuine and spiritual sense of any portion of Scripture becomes known its apparent truth perishes not naturally but by violence. Apparent truths, indeed, still remain in Scripture, as they remain in nature, but they are no longer regarded as real truths: they are not made the foundation of doctrine or the guide of life. Moreover, the Philistines cannot abuse them, at least to the destruction of the faith of others. They may seize the lifeless body and subject it to indignity, but the spirit they cannot insult and abuse.

This general view of the subject will enable us to enter more readily into the particulars of the history, which we will now consider.

When the men of Israel fled before the Philistines, they fell down slain in mount Gilboa. Gilboa means, and was, a fountain. It was near the valley of Jezreel, and gave its name to the town where the Israelitish army assembled, and to the mount where the men of Israel fell down wounded, where Saul's sons were slain, and where Saul himself died by his own hand. Emblematic of spiritual love, which is spiritual and eternal life, mount Gilboa becomes, for the time at least, emblematic of natural love, which, when it rules, is spiritual and eternal death. As the best things become by perversion the worst; so things that have the best, come by the law of opposites to have the worst, signification. Zion was commanded to get up into a high mountain to proclaim the coming of the Saviour (Isaiah 40:9); and when He came, the devil took Him up into a high mountain to tempt Him (Luke 4:5). The law was promulgated on mount Sinai, and was desecrated on mount Calvary. In these instances a mountain is emblematic of the holy principle of love to God, and of the unholy principle of the love of self. So we find in other parts of the Word. "Our persecutors are swifter than the eagles of the heaven: they pursued us upon the mountains "(Lam 4:19). "I will lay your flesh upon the mountains, and fill the valleys with your height "(Ezekiel 32:5). "Your people is scattered upon the mountains, and no man gathers them
"(Nahum 3:18). When, as represented in the history before us, the truths of the Church flee before the errors of the world, or when true views and principles of religion recede before those which are false, the termination is in that which has relation to life; the true terminates in good, the false in evil.

When the Philistines had put the Israelitish army to flight, they pursued Saul and his sons, and soon overtook them. The three sons they slew, and Saul would have perished by the sword of the Philistines had he not fallen upon his own. In Saul, his sons, and the men of Israel we have represented the three component parts of every whole; the ruling principle itself, the leading principles by which it governs, and the common principles which are governed. The common principles form the basis on which the higher rest, and by which they are supported; and when these give way, all the others perish. In regard to the Word, the common truths of the letter form the basis of all its highest truths, and in them Divine truth is in its fullness and power. In regard to the Church, its common principles of life and worship form the basis of its higher principles of faith and love. In regard to man, his words and actions form the basis of his thoughts and affections. In all these that which is the basis is also the support of the higher principles; and when that gives way the others must fall. The men of Israel flee, Saul's sons are slain, and Saul himself perishes. Thus we see the force and significance of the inspired record, which expresses at once a literal fact and a spiritual truth. "So Saul died, and his three sons, and his armour-bearer, and all his men, that same day together. The battle went sore against Saul, and the archers hit him; and he was sore wounded of the archers." This is with one important difference like Jacob's prophetic blessing on his son Joseph. "The archers have sorely grieved him, and shot at him, and hated him: but his bow abode in strength, and the arms of his hands were made strong by the hands of the mighty God of Jacob; (from there is the shepherd, the stone of Israel)" (Genesis 49:23, 24). This is prophetic, as that respecting Saul was representative, of the Lord; but Joseph represented the spiritual, as Saul represented the natural part of the Lord's humanity. So of the regenerate man. The archers who shot at Joseph denote those who are opposed to the members of the spiritual Church; for an archer denotes the spiritual man; a bow signifies doctrine, and arrows the things that belong to doctrine, thus the truths of doctrine with those who are in truths, and the falsities of doctrine with those who are in falsities. Both Joseph and Saul were shot at and sorely grieved by the archers. But there is this difference between them: Joseph's bow abode in his strength, for his hands were made strong by the hands of the mighty God of Jacob; but Saul's bow abode not in his strength, for his hands were not strengthened by the hands of the mighty One of Jacob. Not from him, therefore, but from David, came the shepherd, the stone of Israel. Nor from the Lord's pre-incarnate humanity in heaven but from His incarnate humanity on earth. Not from truth Divine but from Divine truth, came the shepherd of the sheep and the foundation and chief corner-stone of the temple. The maternal and finite were put off, and the paternal or infinite was put on.

There is one mentioned among the distinguished victims of this disastrous battle who must not be left unnoticed. Saul's armour-bearer refuses to thrust his master through, but follows his example, and dies with him. The armour-bearer is to the warrior what a servant is to his master or a minister to his lord. The only peculiarity in his case is, that he serves and ministers in respect to the implements of war. The armour-bearer is, therefore, related to his master as truth is related to goodness, or as the external is related to the internal. Truth serves goodness, and the external serves and ministers to the internal. As Saul represents the natural mind, he and his armour-bearer answer to the internal and the external of that mind. The internal of the natural mind is the seat of our motives, the external is the seat of our means; the one is principal, the other is instrumental. When the internal and the external are in perfect accord they act as one. When they are not, the external does not always or at once obey the behests of the internal. Saul's armour-bearer did not obey the command of his lord to thrust him through. And the reason given is, that he was sore afraid, not for his master but for himself. But when Saul had fallen upon his sword, his armour-bearer also fell upon his sword, and died with him. When the internal falls, the external falls also; when the internal dies, the external dies with it.

The issue of the battle had another disastrous effect. "When the men of Israel that were on the other side of the valley, and they that were on the other side Jordan, saw that the men of Israel fled, and that Saul and his sons were dead, they forsook the cities, and fled; and the Philistines came and dwelt in them." The inhabited cities of Israel represented doctrines of the Church filled with living truths. These cities, forsaken by the men of Israel, and inhabited by the Philistines represented doctrines of the Church emptied of their truths, and occupied by falsities. If it be asked what this means, we may answer by a few examples. The doctrine of the Trinity is occupied by truths when it teaches that in God there are three Divine Essentials; it is filled with falsities when it teaches that in God there are three Divine Persons. The doctrine of the Atonement contains truths when it teaches that God was in Christ reconciling the world to Himself; it contains falsities when it teaches that the Son of God was in Christ reconciling God the Father to the world. The doctrine of the Resurrection is occupied by truths when it teaches that man rises in a spiritual body at the end of his life; it is possessed by falsities when it teaches that he is to rise in a natural body at the end of the world. The doctrine of Faith contains the truth when it teaches that the faith of love saves; it is possessed by falsities when it teaches that faith alone saves. Thus it is that the doctrines of the Church may in name remain while their essential nature is entirely changed. And thus it is that the Philistines come and dwell in the cities from which the men of Israel have fled.

What Saul feared the Philistines would do to him if he should fall into their hands they did to him after he was dead. "On the morrow [after the battle], when the Philistines came to strip the slain, they found Saul and his three sons fallen in mount Gilboa. And they cut off his head, and stripped off his armour, and sent into the land of the Philistines round about, to publish it in the house of their idols, and among the people. And they put his armour in the house of Ashtar-oth: and they fastened his body to the wall of Beth-shan." The indignities which they offered to the body of Saul -- decapitation and a kind of crucifixion -- are expressive of indignities offered to the truth by the spiritual Philistines, whether they be among the Jews or among the Christians, and whether offered to the Lord as the Truth in person or to His Word as the Truth revealed. They cut off the head of the Lord's anointed, when they destroy the connection between the internal and external of His Word, which is the result of having destroyed the connection of the internal with the external of religion in themselves; they strip off his armour, when they divest the Word of the truth which is for the defence of goodness against the assaults of evil; and they publish it in the house of their idols and among the people, when the triumph of the false principle over the true enters into all their worship and life. The Philistines putting Saul's armour in the house of Ashtaroth is very significant. There is good reason to believe that the idol goddess Ashtaroth represented the moon. In Scripture the moon is an emblem of faith, and in regard to the Philistines, of faith alone, the idolatry of which was represented by the worship of Ashtaroth. Saul's armour is placed in the house of Ashtaroth, when truths that should defend goodness are devoted to a faith that claims the power to save without goodness, and which the impure rites of the worship of Ashtaroth too plainly represented.

Beth-shan, to the wall of which the Philistines fastened the body of Saul, was part of the inheritance of Manasseh, but the men of that tribe were unable to drive out the Canaanites, whom, however, when their strength increased, they made tributary (Joshua 17:11-13; Judges 1:27). Beth-shan signifies a house of rest. The faithful find their house of rest in the good they have acquired by obedience to the truth; but the unfaithful find their house of rest in the evil, which they call good, into which they have settled by making the truth obedient to them. The body of Saul is fastened to the wall of Beth-shan, when the good, which has been stripped of its truth and deprived of its power, is exposed, for derisive mockery, on what, as a city of Manasseh, would have represented truth defending goodness, but as a city of the Philistines, represents falsity defending evil, if not in life at least in doctrine. There are two kinds of Solifidians. Both teach that good does not justify, but only one teaches that evil does not condemn. This is the secret if not the open belief of those who are in evil, and if it does not manifest itself in this life it will in the life to come. There also the truth will be seen by those who desire to see it. "When you come out of natural light into spiritual light, as you will after death, inquire what faith is and what charity is; and you will clearly see that faith is charity in form, therefore that charity is the all of faith, consequently that it is the soul, life, and essence of faith, just as affection is of thought, and as sound is of speech; and if you desire it, you will see the formation of faith from charity, like the formation of speech from sound, because they correspond."

But though fastened to the wall of Beth-shan, the body of Saul was not allowed to remain there. "When the inhabitants of Jabesh-gilead heard of that which the Philistines had done to Saul; all the valiant men arose, and went all night, and took the body of Saul and the bodies of his sons from the wall of Beth-shan, and came to Jabesh, and burnt them there. And they took their bones, and buried them under a tree at Jabesh, and fasted seven days." Jabesh-gilead was the place where Saul first displayed his martial courage and kingly power, when that city was besieged by the Ammonites; and it is highly appropriate that the men of Jabesh, for whom Saul had worked so signal a deliverance, should rescue his mangled body and those of his sons from the wall of their enemies, and give them, what was so much esteemed in those times, an honourable burial with befitting obsequies. There is another fact which makes this act of the men of Jabesh appropriate and significant. Jabesh belonged to the half-tribe of Manasseh on the other side Jordan, as Beth-shan belonged to the half-tribe of Manasseh on this side Jordan, thus signifying the external and the internal of the same principle of spiritual goodness, which the tribe that sprung from the eldest son of Joseph represented. The truth which was desecrated by the Philistines in the one city was restored by the men of Jabesh in the other. The men of Jabesh acted very differently towards Saul to what the men of Keilah did towards David; no doubt for the spiritual reason that David's trials were still in progress, but Saul's trials were now ended. To complete the representative history of the first king of Israel, it was necessary that he should be buried; for burial signifies resurrection. And by whose instrumentality could his burial be more appropriately effected than by the men of Jabesh-gilead? and where could his ashes find a more suitable resting-place than in Jabesh-gilead itself? The noble act of the valiant men of Jabesh exemplifies the Divine law of life that no good deed sincerely performed is ever lost, and that the first-implanted good is realized as the last. Between Saul's first kingly act of heroism to the men of Jabesh, and their last act of heroism to him, many dark days and nights have intervened. But regarding Saul in his typical character, and his persecution of David as representative of the enmity of the natural mind against the spiritual, we can see that when the natural dies and is put off, it becomes like a seed sown in the ground, from which a new tree springs forth. "Except a corn of wheat fall into the ground and die, it abides alone: but if it die, it brings forth much fruit." But there are some, as the apostle says, who "shall be saved; yet so as by fire" (1 Corinthians 3:15). The Lord says by Zechariah, in a prophecy of the Incarnation, "Two parts therein shall be cut off and die.... And I will bring the third part through the fire, and will refine them as silver is refined, and will try them as gold is tried" (Zechariah 13:8, 9). And Malachi says that "the Lord is like a refiner's fire, and like launderers' soap: and He shall sit as a refiner and purifier of silver "(Mal 3:2, 3). The burning of the bodies of Saul and his sons indicates this kind of purification. It does not appear that cremation was a Jewish custom. And even if it be supposed that there might be special reasons for burning in this case, the spiritual meaning of the act is no less clear, as well as highly instructive. Nor is it to be understood of the regenerate only, but also of Him who passed through all the fiery ordeals of human experience.

When the men of Jabesh had burned the bodies, they buried the bones under a tree and fasted seven days. Two acts of this kind are mentioned in the Old Testament. When Deborah, Rebekah's nurse, died, they buried her under an oak-tree, which was called the oak of weeping (Genesis 35:8); and when Joseph went up to bury his father, they made a mourning for him seven clays (Genesis 50:10). In the apparently simple incidents of Deborah's death and burial an important truth relating to the Lord and to the regenerate man are contained. Deborah, the nurse, signifies that which the Lord received from His mother and by which He was nourished from infancy; this was the hereditary nature, in itself frail and evil, against which the Lord fought, and which He expelled, so that at length He ceased to be the son of Mary. The rejection of hereditary evil out of the natural mind entirely and for ever is meant by Deborah being buried under an oak. Such is the meaning, generally, of the bones of Saul and his sons being buried under a tree in Jabesh. But why, it may be thought, should burial signify both rejection and resurrection? Because the rejection of the old implies the resurrection of the new. This was the case with the Lord Himself. He laid down the life of His human mother that He might take up the life of His Divine Father.

" For when the son of Mary died the Son of God arose."

The seven days' fast which the men of Jabesh observed, when they buried the bones of Saul, while expressive of their own grief on account of the loss of their king, is expressive also of mourning over the defeat or the loss of truth and goodness, which is one of the meanings of fasting. There is sometimes resemblance where there is no correspondence; but may there not be both a resemblance and a correspondence between the case of Saul, as the Lord's anointed, and that of the Lord Himself? Both were crucified by their enemies and buried by their friends. The disciples of the one and the subjects of the other mourned and wept over their loss; and both sorrowed over the blighted hope that it was he who should have redeemed Israel. He on whom had been "all the desire of Israel," to lead out their armies, and fight their battles, and deliver them from the oppression of the Philistines, had been conquered by the very power he should have broken. Saul and his sons and his army were no more. The panic-stricken Israelites on both sides of the Jordan were fleeing from their cities, which their pursuing enemies entered and occupied. Philistia was jubilant. Her gods, to whom her sons offered the most precious trophies of their victory, were held to have triumphed over Jehovah. To despairing Israel all seemed to be lost. A brighter day is soon to dawn upon them. But for the time fasting is the most suitable expression of their state. So with spiritual Israel, "The days will come, when the bridegroom shall be taken away from them, and then shall they fast in those days."
