
<<<
---
=== 3 - Saul Anointed King, With Signs Following

1 Samuel 10

when Saul stood still, "then Samuel took a vial of oil, and poured it upon his head, and kissed him, and said, Is it not because the Lord has anointed you to be captain over His inheritance?" As a ceremonial, anointing was a sign of the inauguration of a person into a particular office, or the dedication of a thing to a particular purpose. Not only were priests and kings anointed, but even the particular instruments of their service -- the vessels of the temple and the instruments of war. This general unction was designed to teach us an important truth. Oil is in Scripture the symbol of love. A very striking and obvious illustration of this meaning of oil is afforded in the parable of the Ten Virgins, when they went out to meet the bridegroom. The five wise virgins took oil in their vessels with their lamps; but the foolish took their lamps, indeed, but they took no oil; so that when, at midnight, the cry arose, "Behold the bridegroom comes, go you out to meet him," the wise, whose lamps were burning, went in with him to the marriage, while the foolish, whose lamps were gone out, being unable to follow, were shut out. Love is the life of faith, as oil is of the flame; but when there is no love there is not even faith; for the light of the foolish virgins had gone out, and they were left with the empty lamp of mere knowledge. Anointing in the Israelitish Church represented that persons enter actually into a holy state, and are devoted to a holy use, when they receive into their hearts the love of God and act under its influence.

But all the anointings that took place in the shadowy dispensation of the Jews, especially of priests and kings, were representative of the anointing of the Lord Jesus Christ Himself, as the Priest and King, of whom all their priests and kings were types. As a typical act this ceremonial had, in reference to our Lord, the highest and the holiest significance; and it gave Him the title of the Messiah and the Christ, which signify the Anointed. In His case, however, anointing was a purely Divine act. He was anointed with the oil of Divine love. The Lord was manifested in the world as Divine truth; He was the Word made flesh. Divine truth was the Son; Divine love was the Father. The glorification of the Lord, by which He became the Anointed, consisted in His uniting Divine love with Divine truth in His humanity, so that His humanity became the. infinite form of Divine love and Divine wisdom; and He, in His own Divine Person, became, and now is, both Father and Son; all the fullness of the Godhead dwelling bodily in Him.

The Lord's glorification is the pattern or archetype of human regeneration. As He made His humanity Divine by uniting Divine love and Divine truth in Himself, He makes His disciples spiritual by conjoining love and truth in their minds and lives. Truth they acquire from revelation, thus from without; love they can only acquire by inspiration, thus from within, or from above. It is love that makes us the children of God. Truth is indeed necessary, because without truth we could not know what love is, nor who and what we ought to love; but truth must be anointed and sanctified with the holy oil of love before it can become holy in the mind of him who has acquired it, or be employed in the actual performance of holy uses. In the inauguration of one who was to be the ruler of the Lord's heritage, the ceremonial of anointing was the more necessary, because it was expressive of the law of Divine order, that the truth which governs in the Church and in the minds of its members must be grounded in love. The first reception of love in truth is the actual commencement of spiritual life in the soul, for love is life; it is that which enkindles in our hearts a real desire to do the Lord's will, and affects it with true joy and delight in doing it. When truth, which we have acquired from the written Word, has become joined to love, which we have received from the glorified incarnate Word, then is fulfilled that prophetic saying of the inspired Psalmist, "Truth shall spring out of the earth; and righteousness shall look down from heaven;" and that declaration is also realized, "Mercy and truth are met together: righteousness and peace have kissed each other" (Psalms 85:10, 11). The kiss, which is the Scripture symbol of conjunction by love, and in the best sense the conjunction of truth and love, is that which Samuel bestowed upon Saul when he had poured the vial of oil upon his head: for Samuel, as the anointing priest, and Saul, as the anointed king, now represented, more perfectly than before, the two kindred principles of love and truth, of charity and faith. Had this union ever afterwards continued and increased, both the king and the kingdom would have been more prosperous and happy, and the aged prophet would have escaped much bitterness of spirit. Yet those unhappy changes that passed over the spirit and disfigured the reign of Saul, are but too faithful symbols of vicissitudes in the Christian life, and even of trials and temptations of the Lord Himself as truth Divine, thus as the Son of Man during that early experience, when His visage was so marred more than any man, when He had no form nor comeliness, and there was no beauty that we should desire Him. But it is carefully to be observed that, while the typical characters who represented the Lord committed sins, and in some instances grievous sins, their sins only represented His temptations, not temptations to commit the sins themselves which they committed, but the evils too deep to be seen by the human eye, and even too mysterious to be comprehended by the finite mind, in which the sins of men originate. The Lord's temptations had therefore a depth and intensity of which we can have no adequate conception.

Before Samuel had sent away Saul he told him of three signs that were to follow in confirmation of the Lord's having chosen and anointed him to be captain over His inheritance. These are still among the signs that follow them that believe, and to these we must now turn our attention.

When Saul was departed he was to find two men by Rachel's sepulchre, who should tell him that the asses which he sought were found. This was appropriate in the case of Saul, but it is as significant in relation to those whom Saul represented. Rachel was the mother of Benjamin, the father of the tribe to which Saul belonged. She was the first and best beloved, though not the first obtained, of Jacob's two wives. She represented the spiritual affection of truth, Leah her elder sister representing the natural affection. Rachel died in giving birth to Benjamin while Jacob was journeying from Padan-aram to Canaan. Bethlehem-Ephratah, the scene of this affecting and significant event, is distinguished in sacred prophecy and history as the birthplace of the Lord Jesus Christ, the Sovereign and Saviour of the world. And on the massacre of the innocents by Herod, in the hope of destroying Him who was said to be born King of the Jews, Rachel is represented as weeping for her children, and refusing to be comforted, because they were not, the prophet thus describing the despairing grief of the Church over its innocence destroyed, except in Him and by whom it was to be restored. The death and burial of Rachel at the birthplace of Benjamin did not represent the extinction and rejection of that affection of which she was the type, but its resurrection into newness of life. For as, when the body dies and is buried, the soul enters on a new and higher state of existence, death and burial signify resurrection; and spiritual resurrection is regeneration, which is entrance into life. Saul's first sign occurring at Rachel's sepulchre is a sign to us that regeneration enters on its first stage of development, when the spiritual affection of truth first puts off the old man and puts on the new. This state is further described by this first sign taking place when Saul came to Rachel's sepulchre on the border of Benjamin at Zelzah. The land of Benjamin, like Benjamin himself, represented the good of truth, or truth in act; for when man in the progress of vital religion enters practically on the life of truth from love, he enters into the new or heavenly state. Of Zelzah we know nothing besides its situation but the name. Its verbal meaning, a shade from the heat of the sun, shows it to be expressive of a state continuous with that, the commencement of which was represented by the dawn of the day, when Samuel called Saul to the housetop to send him away, but a state rather of love than of light, or one in which good has been added to truth. The sign itself which was here given him was a double proof of Samuel's character as a seer; but it is expressive of a spiritual truth relating to the stage of spiritual progress now represented. Saul was to find two men who should say to him, "The asses which you went to seek are found: and, lo, your father has left the care of the asses, and sorrows for you, saying, What shall I do for my son?" Saul's searching for asses and finding a kingdom presents a striking natural antithesis; but the former announcement, that what he had lost was found, is the point we are to observe, and in connection with it the father's sorrowing for his son. We have already said that in the highest sense Saul's search for the lost asses represents the Lord's coming to seek that which was lost; and in seeking for the lost He also found a kingdom. Yet Saul himself did not recover the asses; so that the analogy between his seeking and the Saviour's may seem not to hold good, nor are we told by whom they were restored, and this is a matter of important significance. There is a profound as well as a superficial correspondence between the type and the antitype in the Holy Word. There is an internal and invisible as well as an external and visible finding. The faithful were internally restored and conjoined to the Father before they were fully and finally redeemed by the Son. The Lord glorified His humanity in the same order in which He regenerates man. His internal man was, therefore, glorified before His external. These were distinct or discreted acts. Reference is made to them in the Father's answer to the Son's prayer, "Father, glorify Your name. Then came there a voice from heaven, saying, I have both glorified it, and will glorify it again" (John 12:28). Simultaneous with the internal glorification of the Lord's humanity was the internal redemption of the human race, and of the angelic heaven, and more immediately of the faithful in the middle state, who were thereby internally conjoined to the Father, or to the Lord's internal man; for the Father dwelt within Him. Jesus therefore speaks of His people being already in His Father's possession and in His own before the work of redemption was accomplished. "I give to them eternal life; and they shall never perish, neither shall any man pluck them out of My hand. My Father, which gave them Me, is greater than all; and no man is able to pluck them out of My Father's hand. I and My Father are one" (John 10:28-30). This oneness of the Father and the Son was as yet only internal. Like Kish and Saul at this juncture, they were internally united, but externally apart. The complete union of the Father and the Son, or the Divinity and Humanity, was yet to be effected by direful temptations, the last of which was the passion of the cross; and it was in these that the Father sorrowed for His Son. Jesus was a Man of Sorrows. We do not read of the Father sorrowing; nay, we do not read of the Son of God sorrowing, but only of the Son of Man. Only Patripassians supposed the Divinity to suffer. Such images only express representatively the sympathy of the Divinity with the Humanity, or of the Father with the Son in His sufferings.

In reference to the regeneration of man, the asses signify the lowest truths, which belong to the memory, while Saul represents the higher truth, that belongs to the understanding. The wandering of the asses from the fields of Kish is expressive of the separation of these lowest truths from connection with the good to which they belong, of which Saul's father is the type; and the finding of the asses is expressive of their restoration and reunion with the good to which they belong and are serviceable.

The second sign given to Saul was that he should meet three men going up to Bethel, one carrying three kids, another three loaves, and a third a bottle of wine; and after being saluted, he was to receive two loaves of their hands. These three men going up to Bethel describe the progression of the regenerating man as to will, understanding, and life from truth to the good of truth. The men were no doubt going up to worship at Bethel, where was the ark of God, and, it is supposed, the tabernacle also; and the kids, the bread, and the wine were their offering, the kids signifying faith in which is innocence, bread spiritual good, and wine spiritual truth. Saul was to receive from them two loaves; which, though not precisely similar to David receiving the shewbread from the priest in the tabernacle, was yet something of the same nature and representation; for this was bread intended for the temple service, and was therefore in a measure sacred, as being Corban, devoted to God. The gift of this sacred, though not sanctified bread, which Saul received at the hand of these worshipers, was a sign of his being recognised as possessing something of the priestly character, and exercising something of the priestly function, and of being sustained by the sacred bread which was designed for the priest. In respect to the regenerate man, this bread is the spiritual good, the good of charity and the good of love, which supports the life of love in the heart.

The third sign was that of the company of prophets which Saul was to meet after coming to the hill of God, where there was a garrison of the Philistines. What hill this was is not accurately determined; but its name implies, in the spiritual sense, a state of mind in which the love of truth, which is meant by the hill of God, is the ruling principle, but which has not yet overcome and removed the opposite false principle, meant by the garrison of the Philistines. Saul is here brought into the presence of one of the evils for the conquest of which the regal office was permitted in Israel. And the Christian is instructed or reminded, that the love of truth in the inner man is opposed, either tacitly or openly, by the love of falsity in the outer man, in other words, that faith in God is opposed by faith in self, which is the essential ground of faith alone.

The company of the prophets which Saul met, after seeing this memento of the enslaved condition of his country, was the opposite of the garrison of the Philistines; for prophets were the types of the genuine truths of religion, truths that teach the faith of charity and lead to a life of goodness. And whereas the previous company were going up to Bethel, these were coming down from the high place, where they had no doubt been engaged in the worship of God, whose praises had been sounded on the wind and string instruments which they carried with them, and which represented what the sweet sounds they gave out were designed to express -- the affections of goodness and truth, of love and faith. Ascent and descent are expressive of that alternation of state, and of the progression which it effects, which goes on in the minds of those who have earnestly entered on and are consistently pursuing the regenerate life, and which is so strikingly described in the dream of Jacob on the spot to which, from that circumstance, he gave the name of Bethel -- the House of God. And well did it deserve that name, for there he beheld the mystic ladder which, resting on earth, reached up to heaven, and on which the angels of God were seen ascending and descending, connecting man with God, and God with man. In every human mind that is sincerely directed heavenward there is such an ascent and descent. The affections and thoughts are directed upwards to God in adoration and prayer, and descend again sanctified and invigorated for the performance of the duties of life. When the company of prophets, coming down from the high place, prophesied, and thus exercised their function and discharged their peculiar duty, the Spirit of the Lord came upon Saul, and he prophesied among them. The prophetic gift did not consist exclusively, or even principally, in the ability to predict future events. It made those who enjoyed it seers and revelators, and raised them into an ecstatic condition, in which they spoke and acted above the sphere of ordinary life. Whatever else may have been included in the prophetic gift, Saul acquired it when he was met by a company of the prophets; the Spirit of the Lord came upon him, and he prophesied among them. But what is the Spirit and gift of prophecy in relation to others? It is the Spirit of truth which God gives to those to whom He has given another heart. When the will is made new the understanding is enlightened to see new and higher truths. These are not merely intellectual truths, but are truths of the heart, because they regard good as an end. They raise the mind which receives them above the ordinary condition of knowing and believing, into that of seeing and loving the truth, and so far realize the devout wish of Moses, "Would God that all the Lord's people were prophets, and that the Lord would put His Spirit upon them!" (Numbers 11:29.) So great is the change of state, and in some cases so obvious is the improvement of character, which the reception of the Spirit of truth produces, that those who knew such a one beforetime, when they see him prophesying among the prophets, say one to another, "What is this that has come to the son of Kish? Is Saul also among the prophets?" But such a one is no longer, as a prophet, the son of Kish. It was therefore well answered by one of the same place, "But who is their father? "Spiritually such a one is a son of God. "He is born, not of blood, nor of the will of the flesh, nor of the will of man, but of God" (John 1:13). God is his Father. And that which became a proverb is a proverb still: "Is Saul also among the prophets?" It is like the question of Nathanael respecting Jesus, "Can any good thing come out of Nazareth?" We are all too apt to think that a prophet must come Of the prophetic line; that a great man must come of a distinguished family or belong to an important place. Yet we are constantly taught in Bible history and in Bible doctrine, that Divine Providence chooses the lowly, and accomplishes great works by seemingly inadequate means.

When Saul had made an end of prophesying he came to the high place from which the prophets had come down. Thus he ended his eventful progress by ascending to the high place, as the symbol of a high state, to worship the Lord, who had led him to greatness as the means of usefulness.

On Saul's return we do not hear of his father, but of his uncle, inquiring of him respecting his eventful journey, and what Samuel had said to him; and Saul answered that Samuel had told him plainly the asses were found, but of the matter of the kingdom he said nothing. An uncle represents good of the same kind as that represented by a father, but connected with the truth, represented by a son, not by relationship, but by affinity, and therefore can enter into the scientifics or knowledges of that truth, but not into its governing power.

Samuel, having anointed Saul, called the people together to the Lord to Mizpeh. This is not the place where Laban and Jacob entered into a covenant not to pass over to one another, and which was therefore named Mizpah, a watch-tower; for Laban said, "The Lord watch between me and you when we are absent one from another." That Mizpah was in Gilead, on the other side Jordan; this was in the land of Benjamin. Yet the two places, having the same name, must have the same general signification. Mizpah spiritually means the presence of the Lord's Divine natural represented by Jacob, in the Gentile good represented by Laban. But here, instead of Jacob and Laban, we have Samuel and Saul. Samuel, as a prophet and judge, represented the Lord as the Word; and Saul, as king, represented truth from the Lord as the Word. To express it otherwise, Samuel represented Divine truth, and Saul represented truth Divine. Here, then, Mizpeh signifies the presence of the Lord's Divine spiritual in the Divine natural principle of His humanity, thus the presence of Divine truth in truth Divine.

When the people were assembled together, Samuel does not tell them that the Lord had appointed one whom he had already anointed as their king, and that he had assembled the tribes for the purpose of announcing what to them must have been good tidings. Without saying anything to them of the already divinely-appointed sovereign. he proceeds to choose a king from among the tribes by lot, confident that of the many ten thousands of Israel it would fall upon the right person. The lot was acknowledged among the Israelites as a direct appeal to the Deity, so that the decision should rest with the Lord Himself. "Now therefore," said Samuel, "present yourselves before the Lord by your tribes, and by your thousands." The principles of the Church, which the people represented, were to be arranged under the two great divisions of the principles of truth and of goodness, which are meant by tribes and thousands. Of these a successive subdivision is to be made, until the lot falls upon the man whom the Lord shall thus mark as the object of His choice. "When Samuel had caused all the tribes of Israel to come near, the tribe of Benjamin was taken; and when he had caused the tribe of Benjamin to come near by their families, the family of Matri was taken, and Saul the son of Kish was taken." Here we have evidently a further division into general, particular, and singular. The general principle which the tribe of Benjamin represented is, as we have seen, the ultimate form or state of truth, which is truth in act. The particular truths arranged under one head, and growing out of one good as their parent stem, are meant by the family of Matri, and the one singular or single truth, in which all the others are ultimated, and by which they are represented, is meant by Saul. This, then, is the truth Divine in heaven which is to be manifested upon earth, but which is to pass through so many changes, and these changes to be effected through so much suffering, before it can be perfected, and become the perfect Ruler of a kingdom established in righteousness.

But there is another mysterious circumstance connected with the newly-chosen king. When the lot fell upon Saul the son of Kish, they sought him, but he could not be found. " Therefore they inquired of the Lord further, if the man should yet come thither. And the Lord answered, Behold, he has hid himself among the stuff. And they ran and fetched him hence." Saul's hiding himself bespeaks a becoming modesty on his part, but the circumstance contains a deeper meaning and a more instructive lesson. The truth which Saul represented could not be found by the Church, which was represented by the people. It had hid itself among scientifics. What is here rendered "stuff" would be more correctly translated vessels; and vessels are the expressive symbols of scientifics, which are the receptacles of truth. At the time when the Lord came into the world the truth could not be found, even by those who sought it. It lay concealed among scientifics, that is, among religious scientifics, and only by inquiring of God, and by Divine guidance, could the truth be found. This same circumstance is taught in another fact in the history of the representative people. When Abraham offered up his son Isaac, and his hand, when raised to slay the intended victim, was arrested by a voice from heaven, he looked and saw behind him a ram caught in a thicket by the horns, and he offered him up instead of his son Isaac. The ram caught in the thicket has the same general meaning as Saul hid among the vessels. The ram is the symbol of truth, and the thicket in which he was caught by his horns is the symbol of scientifics, in which the truth was entangled and held captive until delivered by the Lord. In the internal historical sense, in which the events connected with the work of redemption are treated of, the ram represents the spiritual, who were in captivity in the middle state until the Lord delivered them after He had glorified His humanity, represented by the potential sacrifice of Isaac; but that which in the historical sense relates to persons, in the spiritual sense relates to principles; in fact, it was because the spiritual principle in the minds of the spiritual was entangled in scientifics that they themselves were held captive, but still were prisoners of hope, whom the Lord delivered.

Brought forth from his hiding-place, Saul stands among the people, towering above them all; and when Samuel says to all the people, "See you him whom the Lord has chosen, that there is none like him among all the people?" all the people shouted, and said, "God save the king!" "Live the king" is the correct and more significant form of acclamation, this being expressive of a wish that the truth may have in it the love from which it lives; for love is life, and only that truth lives, and secures life to those who in faith receive it, which is animated by love.

The two elections of Saul, one by direct appointment and the other by lot, thus by the Lord, evidently represent a double election -- that of the internal and that of the external man. This was not, however, the final settlement of the king and the kingdom. Another is recorded in the next chapter.

When the king had been accepted by acclamation, Samuel told the people the manner of the kingdom, and wrote it in a book, and laid it up before the Lord.

When the Divine Wisdom, to which all the future is present, saw that the children of Israel would desire a king, instructions were given in the law of Moses as to the manner of the king they should choose: "When you are come to the land which the Lord your God gives you, and shall possess it, and live therein, and shall say, I will set a king over me, like as the nations that are about me: you shall in any wise set him king over you whom the Lord your God shall choose: one from among your brethren shall you set king over you: you may not set a stranger over you, who is not your brother "(Deuteronomy 17:14, 15). When the state of the Church is such that truth, and not love, has the supreme control, it is above all things necessary that the truth which rules should be genuine and not spurious, and that it should be derived from the Word and not from any foreign source. It is further necessary that this truth should have relation to goodness, in order that the faith of the Church should be derived from charity. This is what is taught in the command to take their king from among their brethren, a brother signifying the grace of charity, for charity is the bond of brotherhood.

It was further commanded that the king should not multiply horses to himself, nor cause the people to return to Egypt, to the end that he should multiply horses.... Neither should he multiply wives to himself, that his heart turn not away: neither should he greatly multiply to himself gold and silver (Deuteronomy 17:17). This teaches that truth should not be corrupted by reasonings and scientifics, meant by the horses of Egypt, nor by natural affections, meant by wives, nor by the knowledges of natural things, meant by gold and silver. Truth itself resides in the spiritual mind, but science, and the affections and knowledges connected with it, belong to the natural mind, which mind itself is Egypt. It was therefore commanded that the king should not cause the people to return to Egypt, to the end that he should multiply horses; for that would represent a return of the mind to the state from which it has been delivered, a state in which the spiritual was in subjection to the natural, and thus truth to science. This state is well described by the Apostle where he says to the Galatians, "But now, after that you have known God, or rather are known of God, how turn you again to the weak and beggarly elements, whereunto you desire again to be in bondage?" (Gal 4:9.)

Besides telling the people the manner of the kingdom, Samuel wrote it in a book and laid it up before the Lord in the tabernacle, where the Lord's presence was. The regenerate mind is a tabernacle and temple of the living God, and the manner of the kingdom -- the principles of the Lord's kingdom, are written and placed therein, when they are inscribed in the heart, and thus placed in the Divine presence. Although the writing of these laws was no doubt a future act, yet there is a spiritual connection between the recorded events; for when the laws of the kingdom are inscribed on the inner man, all the truths which form the kingdom go forth and enter each into its own good; as Samuel, after the election and acceptance of the king, sent the people away, every man to his house. It is especially mentioned that Saul also went home to Gibeah. There were two places of this name, one in the land of Judah, and this in the land of Benjamin. That in Judah is famous as the place where the ark so long remained, and from which it started on its upward progress to Jerusalem in the time of David. As the progress of the ark represented the progression of the Church in man from its ultimate to its inmost, as from one heaven into another, even to the highest, Gibeah, from which the progress of the ark commenced, signifies the ultimate of the Church, which is its natural principle. Gibeah, we may infer, has a similar meaning here; only, there it is the lowest from which an ascending state begins, here it is the lowest in which a descending state closes. This meaning is also in unison with all that is related of Saul, as representing truth in the ultimate degree. Gibeah literally signifies a hill, and is so rendered in several instances, as in the 10th verse of this chapter; and as a hill signifies good, ultimate good is that which is the home of ultimate truth, which Saul represented. When Saul went to Gibeah there went with him a band of men, whose hearts God had touched. This does not express the force of the original. The term rendered men means mighty men, and is so rendered in other instances, as mighty men of valour, mighty men of wealth. Here it would seem to mean valiant rather than wealthy men. Such would be the more needful and suitable companions in the present circumstances. The band, therefore, who accompanied Saul to his house in Gibeah, when every man was sent to his home, are those who are zealous for the truth, and ready to fight for it against opposing falsities; and who engage in the warfare of the spiritual life strong, not only in the belief but in the love of truth, whose faith is not only of the intellect but of the heart, which God has touched with the fire of His love. In the abstract sense these men denote truths themselves, which were added to the truth which now began to reign in the Church and in the minds of the faithful.

But when truth begins to act powerfully in the mind, one of its effects is to excite the evils that naturally belong to it. So we find that while this band adhered to Saul, the sons of Belial said, "How shall this man save us? And they despised him, and brought him no presents." The Lord's representative was, in this respect, like the Lord Himself when in the world. His disciples, whose hearts God had touched, followed Him, while the Jews, and especially the priesthood, said, Can this Man save us? And they despised Him, and brought Him no presents. But the Lord, like Saul, "held His peace; "or, as rightly expressed, was as though He were deaf. For Jehovah has said by the prophet, "Who is blind, but My servant? or deaf, as My messenger that I sent?... Seeing many things, but You observes! not; opening the ears, but He hears not" (Isaiah 42:19, 20). The Lord's ear was open to the cry of His children, but closed against their imprecations. "If You, LORD, should mark iniquities, O Lord, who shall stand? But there is forgiveness with You, that You may be feared "(Psalms 130:3, 4). A highly fitting conclusion this of the account of the election of the first king of Israel, the first representative of the Lord, as a king who was to rule by truth and righteousness in the hearts of his people.


