= Application of Doctrine
By George De Charms
include::../template-attributes.adoc[]


////
I converted ~900 ' or ' words to ' of ' words.
EPUB converter isn't handling this many levels well. PDF and HTML do.
////


.Original outline structure:
....
I. Roman numeral
  A...
    1...
      a...
        -x...
          +s...
....

.Here using:
....
I.{empty} upperroman
[upperalpha]
. A
[arabic]
.. 1
[loweralpha]
... a
[lowerroman]
.... i
..... * bullet
....

////
I found no way to avoid having to put these [annotations] *everywhere*. The second sequential of a level was not necessary, but easier to accomplish.

Before adding [them], the line was just a blank, and Asciidoctor applied its own numeration sequence, which was functional.

This tip isn't meaningful for me yet:
"Custom numeration styles can be implemented using a custom role. Define a new class selector (e.g., .custom) in your stylesheet that sets the list-style-type property to the value of your choice. Then, assign the name of that class as a role on any list to which you want that numeration applied."


Note how the output processors for pdf and epub handled the outlining entirely differently (and both independently)
PDF resolved all 6 levels
EPUB could only distinguish 3, and then reused lower_romans for the rest, still indented however.

There may be a way to block the lists and designate a sequence
the asciidoc context is 'olist'

See https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/#styles

and https://docs.asciidoctor.org/pdf-converter/latest/theme/custom-role/

////

== I. Introduction.
January 9, 1953 + 
February 23, 1971

`I` The faith of the New Church is based on the conviction that in the Theological Writings of Emanuel Swedenborg the Lord Jesus Christ has fulfilled His promise to come again that He may be visibly present with men to teach them and to lead them in paths of true happiness and lasting peace.
[upperalpha]
. The purpose of His coming is to establish His Kingdom on the earth as well as in the heavens.
[arabic]
.. The Church is the Kingdom of the Lord on earth, and in the Heavenly Doctrine the Lord Himself has set forth the plans and specifications of a true Christian Church, one that is designed to be altogether distinct from the former Christianity.
[arabic]
.. The teachings of the Writings differ from traditional Christian doctrine not merely superficially, as to matters of ritual, or church government, or social custom, but as to the most basic and fundamental concepts of religion.
[loweralpha]
... Although they reaffirm the truth of the Old and New Testaments, and restore our faith in their Divine infallibility, they completely revolutionize our understanding of what the Bible teaches, and of how its teachings are to be applied.
[loweralpha]
... They present a radically new idea of God, of Jesus Christ and His Divine work of redemption; they offer an entirely new concept of heaven and the life of man after death; and they give a new interpretation of what is meant by a truly religious life.
[arabic]
.. These teachings are set forth in plain terms, in rational language, with marvelous logic and consistency.
[loweralpha]
... They are brought within the grasp of any normally intelligent person who approaches them with an open mind.
[loweralpha]
... And the whole world is invited to receive these doctrines in heart and faith, and to join in the task of building that spiritual city of God which is called in the Apocalypse the New Jerusalem.
[upperalpha]
. It is not so difficult for any one to acknowledge intellectually the general teachings of the Writings.
[arabic]
.. For the most part they appeal at once to common sense.
[loweralpha]
... Unless the mind is deeply imbued with traditional doctrines, and literal interpretation of the Bible, many of the teachings of the Writings are spontaneously recognized as true.
[lowerroman]
.... Indeed, many, on people hearing them for the first time, will often say, Yes, that is what I have always believed, although they could not possibly have formulated the idea for themselves or have expressed it in words.
[lowerroman]
.... They recognize it as true, but they do not see how greatly it differs from what they had previously been taught.
[loweralpha]
... Sometimes the difference is clearly seen, and then people have been known to exclaim: What a beautiful idea, if only I could believe it!
[lowerroman]
.... It strikes them as something wonderful, but visionary and impractical, out of harmony with the hard realities of life.
[lowerroman]
.... It affects them no more deeply nor permanently than a tale that is told.
[arabic]
.. It is obvious that if the New Church is actually to be built in the minds and hearts of men according to the new Divine specifications given in the Writings, more than this is necessary.
[loweralpha]
... The doctrines must be clearly understood.
[loweralpha]
... The way in which they differ from the established tenets of the former Christian Church must be clearly seen.
[loweralpha]
... And finally, their practical application to the problems or are must be not only understood, but brought into practice.
//mess above
[loweralpha]
... As the Writings plainly state: All religion is of life, and the life of religion is to do what is good (@DLife 1).
[lowerroman]
.... Divine teaching is given not merely that it may be known and stored in the memory; nor even that it may be understood and intellectually admired.
[lowerroman]
.... It is given in order that it may guide man's life, and mould his character.
[lowerroman]
.... The most important thing of all is the application of doctrine, for by this alone is man regenerated and prepared for entrance into the Lord's Kingdom, both on earth and in heaven.

* There is no teaching in all the Sacred Scripture, nor in the many volumes of the Writings, that does not have a direct and vital bearing on human life; and by this we mean on men's life here and now in the material world.

* The New Church comes into being only so far as this application is actually made.
[arabic]
.. Let us not suppose that the difficulty of realizing the difference between the teaching of the Writings and the generally accepted religious ideas of the day, and thus the difficulty of understanding how those teachings are intended to be applied, is limited to those who come into contact with the Heavenly Doctrine for the first time.
[loweralpha]
... Those of us who have been brought up in the New Church, and have been familiar with the Writings from earliest childhood, are all too aware of this difficulty.
[lowerroman]
.... Much of what we know of the doctrine is retained in the memory as abstract knowledge, accepted and believed without deep understanding, merely because we are convinced that everything in the Writings is true. And this applies to the most learned of the clergy as well as to the least learned of the laity.
[lowerroman]
.... A relatively few things - more of course with some than with others - have been rationally confirmed by individual study and reflection, so that they have become matters of deep conviction.
[lowerroman]
.... And still fewer are those doctrines which have been understood so fully as to have become a motivating force in the formation of our character.
[loweralpha]
... As members of the New Church, therefore, there is nothing more important for us to consider than the all-pervading question of how doctrine is to be applied to life.
[lowerroman]
.... We would propose therefore to present a few reflections on this subject in an effort to understand more clearly what the Writings really mean by the life of religion.
[lowerroman]
.... To this end we would examine a few specific teachings, contrast them with parallel ideas prevalent in the Christian world, and analyze just what their impact upon our actual life is intended to produce.

`II`. As a general introduction to the subject we would ask ourselves this evening, what do the Writings really mean when they say, "All religion is of life and the life of religion is to do that which is good"?
[upperalpha]
. Surely this is something that we spontaneously recognize as true.
[arabic]
.. It must be obvious to every one that the end and purpose of religion of the good life.
[arabic]
.. That the good life consists in keeping the Commandments of God is the universal testimony of the Word.
[loweralpha]
... As we read in the Law of Moses: Thou shalt hearken to the voice of the Lord thy God, to keep all His commandments which I command thee this day, to do that which is right in the eyes of the Lord thy God (Deuteronomy 13:18).
[loweralpha]
... Again: Keep therefore the words of this covenant, and do them, that ye may prosper in all that ye do (Deuteronomy 29:9).
[loweralpha]
... And again: When a righteous man turneth away from his righteousness and committeth iniquity, and dieth in them; for his iniquity that he hath done shall he die. Again when a wicked man turneth away from his wickedness that he hath committed, and doeth that which is lawful and right, he shall save his soul alive. ... Therefore, I will judge you, O
house of Israel, every one according to his ways, saith the Lord God (Ezekiel 18:24, 26, 27, 30).
[loweralpha]
... And in the New Testament: He that; hath my commandments and keepeth them, he it is that loveth me (John 14:21).
[loweralpha]
... And again: If ye keep my commandments ye shall abide in my love, even as I have kept my Fathers commandments and abide in his love (John 15:10). And in many other places.
[arabic]
.. But what then is new about the teaching that religion is of life, and the life of religion is to do that which is good?
[loweralpha]
... Does not every religion, both Christian and non-Christian, teach the same thing?
[lowerroman]
.... Every religion in fact claims to teach the law of God.
[lowerroman]
.... Every religion teaches obedience to that law.
[lowerroman]
.... Every religion therefore professes to have the secret of the good life, and of salvation by means of it.
[loweralpha]
... Yet that one religion proclaims as good, another condemns as evil.
[lowerroman]
.... What then really is the good life in the sight of God?
[upperalpha]
. Of course the New Church differs from all other religions primarily in this: that the Writings of Emanuel Swedenborg are proclaimed to be a Divine Revelation from God.
[arabic]
.. The teachings found therein consequently replace in our thought and understanding the theological doctrines that have been traditionally acknowledged in the sects of Christendom.
[loweralpha]
... We hold therefore that these teachings are the true law of God, in keeping which there is great reward.
[loweralpha]
... Yet in professing this belief we are doing no more for the doctrine of our own church than others are doing for their particular creeds and dogmas.
[loweralpha]
... It is quite possible to profess this faith, and at the same time to be carried along in the stream of life that swirls about us.
[lowerroman]
.... We may to all intents and purposes continue to feel, and speak, and act very much as before.
[lowerroman]
.... And in this case our faith will not greatly change the deeper currents of our life.
[arabic]
.. It is not by our intellectual faith, but by practical application of our religious beliefs to life, that our religion becomes really new and different.
[loweralpha]
... But what do we mean by application?
[lowerroman]
.... Is it the adoption of a different form of ritual and mode of worship?
[lowerroman]
.... Does it consist in formulating a new mode of church organization and government, based on the teaching of the Writings?
[lowerroman]
.... Does it imply a new system of education, a new code of moral conduct, now social customs, and forms of family life?
[loweralpha]
... Certainly the establishment of the New Church involves all of these things.
[lowerroman]
.... For the Lord promised at His coming, saying, Behold I make all things new.
[loweralpha]
... Yet all of these things could be done without attaining what the Writings really mean by the application of doctrine to life.
[lowerroman]
.... There is nothing distinctive about this kind of application, for the same thing is done by every church and every religion in the world.
[loweralpha]
... In order that a really new religion may be born, and come to life, something more than this is needed, something deeper, more subtle, and much harder to achieve.
[lowerroman]
.... For all these things have to do with the life of the body.
[lowerroman]
.... But when the Writings say that all religion is of life, they refer primarily not to the life of the body, but above all to the life of the inner mind and spirit of man.
[upperalpha]
. The essence of life is love, Whatever a man loves supremely - loves so deeply that he will sacrifice everything else to attain it, and to protect it - this is his God. And the activity of this love - whatever he thinks, speaks, and does under the impulse of this love - this constitutes his real religion.
[arabic]
.. It is well known that this supreme love lies deeply concealed from the sight of others. Often it may remain hidden from the man himself.
[loweralpha]
... The faith a men professes may not be the outward expression of his inmost love.
[lowerroman]
.... He may cling to it from mere habit, or out of deference to those among whom he lives, or because by means of it he gains the respect, the approbation, and the assistance of his associates.
[loweralpha]
... His accustomed forms of worship, his moral conduct, his outward way of life, may not at all accurately reflect his inmost purpose or objective.
[lowerroman]
.... They may be bent to serve the ends of many divergent loves.
[lowerroman]
.... One brought up in the New Church may follow its established customs as a matter of course, because to do so is the easiest path, taking them for granted without serious thought.
[lowerroman]
.... One may come into the New Church and adopt these external observances without in the least realizing why they have been established, or what they are intended to mean in terms of spiritual life.
[loweralpha]
... For this reason the acceptance of a new creed, the adoption of a new ritual, or a new mode of social behavior is not necessarily a reliable sign that one has acquired a new religion.
[lowerroman]
.... All these things can be done while the inmost love, the motivating force, the essence and qualifying soul of a man's religion remains unchanged.
[arabic]
.. The purpose for which the Heavenly Doctrine has been given is that it may change the inmost loves of men, and thus make new not merely the outward forms of religion, but especially its vital soul and essence.
[loweralpha]
... This change can be effected only by the application of doctrine to life; and it is for the sake of effecting this change that doctrine must be so applied.
[lowerroman]
.... We cannot be satisfied with any external conformity to the truths of revelation.
[lowerroman]
.... The Lord has said: My words are spirit and they are life, and only as this spirit and life are received in mind and heart can we become true disciples and followers of the Lord.
[loweralpha]
... This is what is meant when it is said in Heaven and Hell no. 351:
True intelligence and wisdom is seeing and perceiving what is true and good, and thereby what is false and evil, and clearly distinguishing between them; and this from an interior intuition and perception.
[lowerroman]
.... Such intuition and perception are possible only so far us the spiritual or internal mind is opened and formed.
[lowerroman]
.... Man's internal mind can be formed only in one way, namely by man's looking to the Divine and to heaven, and by an inmost willingness to be led by the Divine.
[lowerroman]
.... When man looks to the Divine and is willing from the heart to be led by the Divine, everything he learns and applies to life causes him to grow in intelligence and wisdom, because then the interior sight belonging to his understanding, and the interior affection belonging to his will are perfected.
[loweralpha]
... This, however, is no easy task. The loves into which we are born are those of self and the world; and the loves into which the Lord's teaching is intended to lead us are those of heaven and eternal life.
[lowerroman]
.... Creeds, doctrines, rituals, moral precepts, all are but necessary means whereby this essential change of love may be effected.
[lowerroman]
.... Only so far as it is effected will these outer garments of religion serve their true purpose.
[lowerroman]
.... This change of love is what is really meant by the application of doctrine to life, the only kind of application that can actually establish a New Church, a new religion in the hearts of men.
[loweralpha]
... That which makes the church new is not anything of the body, but is a new state or attitude of mind that is born of love to the Lord.
[arabic]
.. Many of the teachings found in the Heavenly Doctrine, many of the goals of life, or the ideals to which those teachings point, appear superficially to be altogether similar to the ideals acknowledged in other religions, both Christian and pagan.
[loweralpha]
... For this reason it is not easy to see wherein their newness really lies.
[loweralpha]
... If we are to discover it we must probe deeply beyond the outward form or appearance, to lay bare the love from which they spring, the love that gives them their distinctive quality.
[loweralpha]
... In attempting to apply to life these ideals, it is this inner content of love that we must seek above all else.
[arabic]
.. In order to demonstrate this truth we have undertaken the difficult task of defining the real differences that distinguish a few of the well-known doctrines of the New Church from similar teachings of other religions.
[loweralpha]
... The first or most essential requirement of true religion is an attitude of internal humility.
[lowerroman]
.... The reason for this is obvious.
[lowerroman]
.... The truth of the statement appeals at once to common sense.
[lowerroman]
.... In some form it is acknowledged in every religion.
[loweralpha]
... But what the Writings mean by an attitude of internal humility is something new and different from that which is understood by it in other churches.
[loweralpha]
... We shall endeavor at our next class to show, at least to some degree, just what that difference is.

Readings: @HH 351. + 
Music: Doxology 17-398 + 
Hymn 22-442 (Verse 1, 3)

<<<

== II. The Spirit Of Humility.
January 16, 1953 + 
March 8, 1971


`I`. The Writings plainly teach that the very first requirement of religion is a spirit of humility.
[upperalpha]
. On reflection, every one spontaneously recognizes that this is true.
[arabic]
.. That alone which can turn the mind toward the worship of God is a deep sense of one's own weakness and inadequacy, on acknowledgment of Gods omnipotent power, and a realization of one's constant need for Divine aid.
[loweralpha]
... To one who is complacent, confident that he can achieve for himself whatever he may desire, religion can have but little meaning.
[upperalpha]
. This is so obvious that every religion in the world, at least theoretically, teaches the importance of humility.
[arabic]
.. Yet ideas as to what genuine humility really is, why it is demanded of us, and how it is to be expressed, are extremely various.
[loweralpha]
... It is in regard to these concepts that the teaching of the Writings is altogether new and distinct from anything to be found in the doctrines of other churches.
[loweralpha]
... If we are rightly to apply the New Church doctrine of humility to our lives, we must clearly understand just wherein it is new and different.

`II`. While every religion has its own particular idea of what is involved in humility, from the standpoint of both doctrine and ritual, we note three distinct attitudes toward a religious life that markedly qualify the concept. These are exemplified in the Jewish Church, in the medieval Christian Church, and in many sects of modern Christianity, respectively.
[upperalpha]
. In the Jewish Church the life of religion was almost completely identified with traditional customs, and with the meticulous observance of ritualistic forms.
[arabic]
.. It was recognized, of course, that humiliation was an affection of the heart.
[loweralpha]
... Yet this affection was associated almost exclusively with external worship.
[loweralpha]
... Between this and the affairs of every day life there was hardly any connection.
[arabic]
.. It was thought that the purpose of humiliation was to appease the wrath of Jehovah, to turn aside Divine punishment or retribution, and to secure the Lord's protection and blessing.
[loweralpha]
... A conscientious observance of the prescribed sacrifices and burnt offerings, according to the Law of Moses, was regarded as a sign of humble allegiance to Jehovah.
[loweralpha]
... But in times of special danger, distress, or fear, it was thought efficacious to express the spirit of humility by prostration before the altar, or sitting in sackcloth and ashes, or beating the breast, rending the clothing, and loudly proclaiming one's guilt and unworthiness.
[loweralpha]
... Such outward forms of humility, even though sincerely expressed at the time, could nevertheless be a cloak for a deep sense of pride, and a feeling of self-merit combined with contempt for others who were not so careful to observe the minutiae of the law.
[loweralpha]
... Among the Jews this pride was born of the conviction that they were the chosen people of God; and it was openly displayed in their attitude toward other nations whom they despised and treated with cruel intolerance.
[loweralpha]
... It is revealed also in their love of ostentation, wherefore the Lord Himself said concerning them: All their works they do for to be seen of men: they make broad their phylacteries, and enlarge the borders of their garments, and love the uppermost rooms at feasts, and the chief seats in the synagogues, and greetings in the marketplace, and to be called of men, Rabbi, Rabbi (Matthew 23:5-7).
[upperalpha]
. In the medieval Christian Church the life of religion was considered to be a matter not so much of ritual as of doctrine. And basic to all also was the doctrine of original sin.
[arabic]
.. It was believed that the entire race had bean condemned because of the sin of Adam, and that therefore every man from birth was irretrievably wicked.
[loweralpha]
... This will was thought to be utterly depraved, insomuch that it had to be completely broken or destroyed if he were to be saved.
[loweralpha]
... Genuine humility was said to be the heart-felt acknowledgment of this depravity, and the repudiation of every spontaneous impulse toward natural enjoyment or pleasure.
[arabic]
.. This idea gave rise to many religious orders devoted to a life of austerity, poverty, to fasting, and the frequent practice of self-inflicted punishment.
[loweralpha]
... By the castigation of the flesh men hoped to destroy all self-esteem, pride, and conceit, and thus to prove their complete devotion to the spiritual life, a life of prayer, and praise, and adoration of God.
[arabic]
.. Out of this concept of inborn wickedness there arose also a cruel and repressive form of education, the sole purpose of which was to chastise the native will, and thus to exorcise the devil who was supposed to dwell in the child.
[loweralpha]
... As a result there was impressed upon the child at a very early age a deep sense of guilt, and a powerful fear - the fear of hell-fire and of eternal punishment.
[loweralpha]
... Such teaching tended strongly to discourage any spirit, or imitative, to produce a feeling of inferiority, and to inculcate an attitude of unquestioning submission to authority, and of obsequious obedience.
[arabic]
.. Although this Christian concept probed much deeper into the heart and the life than did the religion of the Jews, it tended to rouse a spirit of rebellion because it ran counter to the instinctive love of freedom which is perhaps the deepest and most powerful of all man's affections.
[loweralpha]
... The Lord wills that man should be free in order that he may enjoy the sense of achievement and of possession that can be given only with the exercise of judgment and responsibility.
[lowerroman]
.... And for this reason a longing for freedom and independence is implanted in the human soul from creation.
[loweralpha]
... When this is threatened, man's whole being is stirred to rebellion, and because of this, the doctrine of man's utter depravity failed to remove the inmost cause of pride.
[lowerroman]
.... Back of every profession of humility the way still remained open for the cultivation of a spirit of merit, self-righteousness, and a whole train of evils that flow from this.
[lowerroman]
.... This hidden spirit manifested itself in the sadistic cruelty of the inquisition directed against so-called heretics, in the ruthless treatment of non-Christian peoples who were regarded with contempt, and as worthy of no consideration; and also in the bigotry that has led to such bitter sectarian strife among Christians of divergent faiths.
[upperalpha]
. In modern times this whole idea of humility has been largely repudiated. The doctrines so authoritatively proclaimed by ecclesiastical councils have been called into question; and the foundation of religious faith has been shifted from creeds to human reason and the testimony of science.
[arabic]
.. The theory of evolution has replaced the belief in the fall of the race, with the contrary idea, namely, that from the beginning there has been a steady though gradual development of mankind out of ignorance and barbarism into over greater intelligence and wisdom.
[loweralpha]
... It is now declared that so far from being innately corrupt and defiled, man is inherently good, with unlimited possibilities of future progress in the perception of moral and spiritual truth.
[arabic]
.. Furthermore, scientific psychology has demonstrated that deep-seated fears implanted in early childhood are the hidden cause of many abnormal mental states.
[loweralpha]
... Even in their milder forms, such fears engender diffidence, hesitation and uncertainty in moments of stress, when decisive action is essential to success.
[loweralpha]
... If deeply impressed on the mind, a guilt complex can produce states of morbid introspection that seriously interfere with normal reactions to life.
[loweralpha]
... In extreme cases this fear and sense of guilt can lead to manic depression, and various forms of melancholia and insanity.
[arabic]
.. As a result of these scientific findings, which have been amply confirmed by experiments, and which can readily be demonstrated in everyday experience, the whole teaching of the medieval Church concerning humility has been very widely abrogated by modern thinkers.
[loweralpha]
... Present day philosophy demands that any idea of inborn evil must be removed.
[lowerroman]
.... On the contrary, everything possible must be done to bolster a man's self-assurance, to banish fears, to encourage confidence in one's own intelligence and ability.
[lowerroman]
.... This is regarded as essential if one is to be prepared with any hope of success to meet the stress and strain of business or professional competition in our highly organized society.
[loweralpha]
... This philosophy has profoundly affected religious thinking.
[lowerroman]
.... It lies at the root of nearly all the more modern sectarian movements in the Christian world such as New Thought, Theosophy, Christian Science, Unity, and many others.
[lowerroman]
.... They all agree in seeking escape from the traditional doctrine of original sin by denying either the existence of the inherent power of evil, and emphasizing the innate goodness of human nature, the spark of Divinity in every man.
//help above
[lowerroman]
.... We see the same idea exemplified in the widespread insistence upon the dignity and worth of the individual, the profound respect due to his personality, and to his inalienable human rights.

* And under its impulse the whole theory and practice of education has been reversed from one of repression to one that encourage self-expression, initiative, the pride of achievement, and sublime confidence in one's intelligence, strength of will, and ability to succeed.
[arabic]
.. The idea of the need for humility before God remains as an abstract theory.
[loweralpha]
... Especially in the Catholic Church its ritualistic expression is required; and it is preserved in milder form in Protestant sects also.
[loweralpha]
... But increasingly it is a humility toward a God who is identified with man's inmost self.
[loweralpha]
... The scientific attitude of mind does indeed imply a lack of trust in one's own untried theories, and a humble recognition of the supreme authority of nature's laws.
[loweralpha]
... In addition there is constant teaching of the importance of acknowledging the superior judgment of great thinkers, learned men, and geniuses in every field.
[loweralpha]
... But aside from this, humility has largely ceased to be regarded as a virtue to be prized and cultivated.

`III`. Superficially viewed, the teaching of the Writings can easily be mistaken for a throwback to the thought of the Middle Ages; but further examination will show that this is by no means the case. That teaching differs radically from both the medieval and the modern concepts of humility.
[upperalpha]
. The Writings state that man is indeed born into evils of every kind, and that his native will is irredeemably corrupt.
//'state' above for 'seats'
[arabic]
.. But this appearance of similarity with the traditional Christian doctrine is profoundly modified by the further teaching:
[loweralpha]
... That the evils into which man is born are not imputed to him because of the sin of Adam, but are derived by heredity from parents and ancestors.
[loweralpha]
... Further, they are not sins, but are merely tendencies to evil for which man is in no way responsible, because they have been imposed upon him through no choice, and therefore through no fault of his own.
[loweralpha]
... God therefore does not condemn him on account of them unless, or until, he, of his own free choice, confirms them in faith and life.
[arabic]
.. It is true that man cannot liberate himself from these tendencies to evil by any will or power of his own; but he is entirely dependant upon the Divine Providence, and mercy of the Lord for deliverance.
[loweralpha]
... True humility is an acknowledgment from the heart that this is so, and such an acknowledgment is a prime essential of man's salvation.
[loweralpha]
... The reason is that the Lord cannot force man to resist these hereditary tendencies to evil, but must lead him gently, in full freedom, in the way to heaven.
[loweralpha]
... And this is why, in both the Old and the New Testaments, the Lord requires of man a spirit of humility, as in the following places:
[lowerroman]
.... The sacrifices of God are a broken spirit: a broken and a contrite heart, O God, thou wilt not despise (Psalms 51:17).
[lowerroman]
.... To this man will I look, even to him that is poor and of a contrite spirit, and trembleth at my word (Isaiah 66:2).
[lowerroman]
.... Verily I say unto you, Except ye be converted and become as little children, ye shall not enter into the kingdom of heaven. Whosoever therefore shall humble himself as this little child, the same is the greatest in the kingdom of heaven (Matthew 18:3, 4).
[loweralpha]
... Wherefore the Lord says: Behold I stand at the door and knock. If any man hear my voice and open the door, I will come in to him and will sup with him, and he with me (Revelation 3:20).
[lowerroman]
.... Pride and self-conceit keep the door closed, and leave the knock unheeded.
[lowerroman]
.... Nothing but a spirit of humility, a profound recognition of the need for Divine guidance, a willingness to be taught and led, can open the way for the Lord to enter the mind and heart of man.
[upperalpha]
. At the same time the Writings fully recognize the truth of the findings set forth by scientific psychologists concerning the injurious effects of fear and a sense of guilt when deeply instilled in early childhood.
[arabic]
.. Fear does indeed tend to inhibit action, to paralyze both mind and body.
[loweralpha]
... It produces vacillation, indecision, and uncertainty.
[loweralpha]
... It holds the mind captive in such a way as to prevent calm judgment.
[loweralpha]
... Hidden fears may profoundly distort the mind, and destroy all sanity.
[arabic]
.. Furthermore, a guilt complex invites influx from the hells, because evil spirits delight in accusing and condemning others.
[loweralpha]
... They seize therefore upon an admission of guilt to insinuate despair, to break down resistance through a sense of the inevitable, which at the same time relieves one of responsibility, and makes the evil excusable.
[loweralpha]
... They encourage man therefore in self-condemnation and morbid introspection, seeking thereby to weaken his resistance and increase the power of evil to imprison his will and his thought.
[upperalpha]
. All this is true, but the cure for these ills of the spirit - the antidote to the poison of fear and guilt - does not lie in the denial that evil exists, nor in the false assertion that man is inherently good.
[arabic]
.. It does not lie in a false confidence that he has life, power, intelligence, and ability in himself.
[loweralpha]
... Such a delusive faith will indeed tend to banish fear, and will encourage quick and bold decision.
[loweralpha]
... It will do so temporarily, or so long as one is successful, or has hope of succeeding.
[loweralpha]
... But if and when one is opposed by circumstances that are unchangeable, or by irresistible force - if and when one is brought face to face with disaster and the inevitable loss of what one most deeply desires -  the illusion of self-power is destroyed, and man is left altogether helpless, the victim of utter despair.
[arabic]
.. The cure lies solely in the acknowledgment of the truth that man is born into a tendency to evils of every kind; that he has no power, nor will in himself whereby these tendencies may be overcome, and therefore that he is in need of constant Divine help.
[loweralpha]
... But it lies at the same time in the recognition that these tendencies to evil are not himself; that he is not under Divine condemnation because of them; that he need not make himself guilty of them.
[loweralpha]
... It lies in a recognition of the fact that the Lord has secretly insinuated into his mind and heart a counter tendency to feel delight in what is good, and heavenly, and of Divine order. This also is not himself, but is a gift of Divine mercy for which he can claim no iota of merit.
[loweralpha]
... It lies in the realization that the Lord endows him with life and power to resist the evil tendencies, and to choose instead those that are good.
[lowerroman]
.... It lies in the acknowledgment that he is required to make this choice on his own initiative, altogether as if his life were his own, even while in his heart he knows and acknowledges that the power to do so is not his own, but comes from the Lord alone.
[lowerroman]
.... It lies in the realization that while he, as of himself, is consciously endeavoring to overcome one evil, the Lord is secretly protecting him from the overpowering influence of hell, constantly maintaining a balance between the forces of good and evil, and thus protecting his freedom to choose the one and reject the other, and this by a thousand unseen operations of His Providence, without which man would be completely helpless.
[arabic]
.. In this way the teaching of the Writings presents an ideal of humility that avoids the pitfall of fear and a guilt complex on the one hand, and the pitfall of any claim to self-power and self-merit on the other.
[loweralpha]
... It is an ideal that is by no means confined to states of external worship of formalism, but seeks to instill humility as an affection of the heart that underlies all our thought and all our life, opening the door of the mind constantly to the Lord, and inviting Him to enter to direct and govern, and to instruct us in our way.
[loweralpha]
... It is an ideal of humility that overcomes fear not by any delusion of our own goodness or power, but by a profound confidence in the ever-present power and the mercy of the Lord.
[loweralpha]
... But as to the distinctive nature of this confidence as revealed for us in the Heavenly Doctrine, we would speak at the next class.

Reading: @AC 8271, 7550; @DP 320. + 
Music: Hymn 64-489 (verse 1 to open), (verse 2 to close)

TRUE CONFIDENCE.

(@TCR 137[5]): ... (An angel said to Swedenborg) Our faith (the faith of heaven) ... is, was, and forever will be, a faith in the Lord God the Savior, whose Human is Divine, and whose Divine is Human. Thus it is adapted to reception, and by it the Divine spiritual is united to the natural of man and a spiritual faith is formed in the natural, and from the spiritual light in which our faith is, the natural becomes as it were transparent. The truths of which our faith consists are as many as the verses in the sacred volume. These truths are like stars, which by their light make the faith manifest, and give it form. Man acquires this faith from the Word by means of his natural light, in which light it is knowledge, thought, and persuasion; but the Lord causes it, in those who believe in Him, to become conviction, trust, and confidence. Thus faith becomes spiritual-natural, and by means of charity becomes living.

(@AC 5963): ... (The states of those in the other life) are according to the perception of good and truth with those who are there, thus according to their perception of the Lord's presence. According to this perception they have tranquillity; for they who are in the perception of the Lord's presence are in the perception that each and all things which befall them tend to their good, and that evils do not reach them; hence they are in tranquillity. Without such faith or confidence in the Lord no one can possibly come to the tranquillity of peace.

@TCR 344: The esse of the faith of the New Church is: confidence in the Lord God the Savior Jesus Christ; a trust that he who lives well and believes aright is saved by Him.

The essence of the faith of the New Church is truth from the Word.

And the existence of the faith of the New Church is spiritual sight, in accordance with truths, conviction, acknowledgment inscribed on the mind.

<<<

== III. Confidence In The Lord.
January 23, 1953 + 
March 23, 1971

`I`. We have said that an attitude of internal humility is the very first essential of a truly religious life. But the Writings teach that genuine humility must be accompanied by a deep sense of confidence in the Lord, and by an abiding trust in the dispensations of His Providence.
[upperalpha]
. The one indeed is the complement of the other.
[arabic]
.. Humiliation is but a source of weakness that is born of fear, unless it is balanced by confidence in some power outside of one's self that can give a sense of security and assurance.
[arabic]
.. For this reason, just as every religion teaches humility, so every religion also teaches that we must have faith in God, and confidence in His power to protect and save.
[upperalpha]
. Yet the nature of this confidence varies greatly according to one's idea of God, or what God requires of man in order that he may be saved, and thus according to one's idea of a religious life.
[arabic]
.. Here again the teaching of the Writings differs markedly from that of every other religion in the world, because it offers a new idea of God, a new idea of heaven and the life after death, a new idea of what constitutes a genuine life of religion.
[loweralpha]
... Because of this, there is given in the Writings a new doctrine concerning trust and confidence in the Lord.
[loweralpha]
... And it is by the true application of this doctrine that the New Church is actually established in our minds and hearts.
[upperalpha]
. In general there are two kinds confidence: one that is based a blind faith, and one that is based on a seeing faith.
[arabic]
.. By a blind faith we mean faith in something that is purely imaginary - something that does not really exist.
[loweralpha]
... A man may have faith in the discovery of oil, or gold, or buried treasure where there is none; and by misplaced confidence he may lose his fortune or his life in a vain search for it.
[loweralpha]
... A research scientist may have faith in a mistaken theory or cure for a disease; or he may have a wrong idea as to how to solve some mechanical problem; and in consequence he may spend months or years in a fruitless attempt to demonstrate his theory.
[loweralpha]
... It is equally true that a man may incline throughout life to a faith in a false god - in a god who does not exist - or in an imaginary heaven that has no reality, or in a kind of religious life that is not saving.
//'incline' was a fix of 'dine'
[lowerroman]
.... He may of course be utterly sincere.
[lowerroman]
.... If he is sincere he will not be condemned for errors of ignorance.
[lowerroman]
.... Either in this world or after death, he will, in Providence, be led to discover his error, and will be given full opportunity to embrace the truth.

* But only then can he begin to journey in the right direction that he may at last come into heaven.
[arabic]
.. By a seeing faith, on the other hand, we mean faith in what is really true - something that is not conjured up in man's imagination, but that really exists in God, and in the universe of Gods creation.
[loweralpha]
... He who knows the laws of physics, or of chemistry, can use those laws successfully. His confidence in them will be rewarded.
[loweralpha]
... So also, just to the degree that the nature of God, and the Divinely ordained laws of spiritual life, are rightly known and understood, a life according to those laws will lead to the blessings of regeneration and eternal happiness.

`II`. The religions of the world are founded upon a blind faith in an invisible god.
[upperalpha]
. Primitive peoples identify God with the forces of nature, which to them are invisible, and utterly mysterious.
[arabic]
.. To these they ascribe human attributes, supposing them to exert an influence upon the lives of men, either benevolent or malevolent.
[loweralpha]
... They put confidence in the efficacy of magical practices, incantations, or rituals to placate the forces of evil, and to insure the protection of benevolent spirits.
[loweralpha]
... Their religious life may be sincere and innocent; yet it is childish and irrational, governed by fear and superstition.
[upperalpha]
. The religions of the ancient East, on the contrary, are the product of highly developed philosophies; yet they also are founded upon the worship of invisible and mysterious forces.
[arabic]
.. They all teach that we must have trust end confidence in God. But by this each one means something very different.
[loweralpha]
... Vishnu, the supreme deity of the Hindus, is thought of as demanding a life of contemplation, or non-resistance, of withdrawal from the outer world.
[loweralpha]
... Allah, the God of the Mohammedans, encourages an active life of conquest, and the full enjoyment of sensual pleasures.
[loweralpha]
... Both cannot be a reliable guide to the kind of religious life that is truly in accord with the Divine law.
[arabic]
.. Because wherever God is unseen, men can picture Him only according to the limited powers of their own imagination, they can think of Him only in terms of what they know, what they feel, what takes form out of their own experience. For this reason they cannot help ascribing to Him the weaknesses, the imperfections, and the limitations of mortal man.
[lowerroman]
.... They picture Him as being angry, as feeling jealousy, as seeking vengeance upon His enemies.
[lowerroman]
.... They think of Him as a finite ruler who needs emissaries, ambassadors, and intermediaries to keep Him informed of what is happening in His vast kingdom.
[lowerroman]
.... They think of Him as subject to persuasion by prayer, and especially by the supplications of those who are wiser and more powerful, and thus nearer to Him.

* This ascription of human limitations to the Deity is what is meant by an anthropomorphic idea of God.
[upperalpha]
. Many of these imperfect concepts of God are inherent even in traditional Christianity.
[arabic]
.. Christian worship also is addressed to an invisible God; that is, to God the Father, of whom it is said that He is without body, parts, or passions.
[loweralpha]
... This God is pictured as being angry with the whole human race because of the sin of Adam, and as demanding retribution in the form of eternal punishment.
[loweralpha]
... Divine justice is supposed to have been satisfied by the vicarious sacrifice of Jesus Christ, His Son, for whose sake He is willing to forgive those who confess their faith in the redeeming blood of the cross.
[loweralpha]
... By Catholics He is regarded as requiring a vicar of Christ on earth in the person of the Pope, to whom He has given the wisdom to interpret His Word for all men, and also the power to remit sins, the power over the keys of hell and of death.
[loweralpha]
... Furthermore, He is pictured as being moved to pity by the penitence of the faithful, and by the prayers of the saints, and thus persuaded to deliver departed souls from the sufferings of purgatory.
[upperalpha]
. If God is really Infinite; if He is everywhere present in the whole of creation; if He knows all things, even the most minute; if His laws are immutable from eternity to eternity; if His Love is boundless, and His mercy is unceasing; then Christians, as well as pagans, worship an imaginary Deity who does not exist.
[arabic]
.. Philosophic thinkers everywhere recognize that this is true, and they strive by human reason to divest the idea of God of all finite and imperfect attributes.
[loweralpha]
... But in doing so they become lost in mere abstractions.
[loweralpha]
... Regarding everything human as limited and imperfect, they tend to deny that God is human.
[loweralpha]
... They postulate a formless force, mechanical, utterly impersonal, devoid of purpose, producing the wonders of nature by accident, or by chance.
[loweralpha]
... Such a God is altogether unapproachable, unresponsive, incapable of loving or of being loved; and the mind reverts to atheism, with nothing in which to place confidence except self-will and self-intelligence.
[loweralpha]
... It cannot be otherwise because no finite mind can possibly even imagine the Infinite.

`III`. What then is a seeing faith? How can we know who God really is, and what are His Divine qualities and attributes? How can we know the laws of His Providence, whereby He guards man, protects his spiritual life, forms his mind and his heart for heaven? How can we know these things in such a way as to have trust and confidence in what is actually true, in what really exists?
[upperalpha]
. Because the Infinite transcends all finite comprehension, no man can possibly discover God for himself.
[arabic]
.. Yet man is so created that he can see God; not indeed as He is in Himself, but in a human form, within which, and through which, the true qualities of God may appear, even to man's limited vision.
[loweralpha]
... This was the simple faith of the primitive Christians and the ground of their firm belief in the Divinity of Jesus Christ.
[loweralpha]
... In His miracles they saw limitless power openly displayed.
[loweralpha]
... In His deeds of mercy and complete self-sacrifice they beheld a vision of boundless love.
[loweralpha]
... And in His teachings they dimly perceived the wonders of unfathomable wisdom.
[loweralpha]
... When the Lord appeared to the disciples after His resurrection, they knew that although the body had died on the cross, the love, the wisdom, and the power that had been made manifest through it had by no means been destroyed.
[loweralpha]
... Although in thought they could not remove the limitations of the body, still, in the Glorified Lord they beheld and worshiped the Infinite God of heaven and earth.
[upperalpha]
. This is the Christian faith that has now been almost completely lost.
[arabic]
.. Some remnant of it remains with children, and with the simple in heart.
[loweralpha]
... But Biblical criticism has cast serious doubt upon the Gospel accounts of the Lord's birth, of His purported miracles, and of His resurrection.
[loweralpha]
... Ever-increasing reliance is placed upon the testimony of science as the only source of truth.
[loweralpha]
... By an ever-widening circle of thinkers, Jesus Christ is regarded as no more than a man of outstanding moral wisdom and insight, and God is conceived as an invisible and formless force, devoid of all human attributes.
[arabic]
.. At best, the hope of Christianity lies in the belief that at some future day Jesus Christ will fulfill His promise to cone again.
[loweralpha]
... The church has not solved the problems of society; it has not brought the Kingdom of God to earth; it has not overcome the powers of selfishness, and greed, and the lust for dominion, that inflict such widespread suffering upon mankind.
[loweralpha]
... Yet there remains the faith with many, that all this will be accomplished in the Day of Judgment, when Jesus Christ shall return to dwell forever on the earth.
[upperalpha]
. In sharp contrast to this Christian confidence in a vague hope that lies in the distant future, the confidence of the New Church is founded on the vision of the Lord already come.
[arabic]
.. Think of the difference between the faith of the Jews in the promise of a Messiah, and the confidence of the early Christians in the Lord whom they had seen and known, and whose teachings were deeply impressed upon their minds.
[loweralpha]
... His Advent was utterly different from anything that had been anticipated; yet it was objective, it was real, it was living, and it exerted a power beyond all imagination.
[arabic]
.. Such also is the great difference between Christian faith that some day Jesus Christ will appear in the clouds of heaven with power and great Glory, and the realization that He has so appeared, and that He is here now, visibly present, in complete fulfillment of His promise.
[arabic]
.. Consider for a moment: suppose that Jesus Christ should again come to earth in His physical body. How would men know Him?
[loweralpha]
... Would it be because they would recognize His face from the portraits the great artists have painted of Him?
[loweralpha]
... Would it be because He was surrounded by a halo, or because His face did shine as the sun, and His raiment was white as the light as He appeared on the mount of transfiguration?
[lowerroman]
.... These outward signs would not help us to know Him truly.
[loweralpha]
... Would it not rather be because what He said would open the mind to a new and wonderful vision of spiritual truth, and give renewed insight into the qualities of Divine love and wisdom?
[arabic]
.. Suppose now, that without again imposing upon our minds the limitations of a physical body, the Lord should speak to us through the medium of a human servant; should speak these same words of surpassing love and wisdom that carry with them the stamp of Divinity; should speak truths that no finite mind could possibly imagine - shall we not by means of them come to know the Lord as He was never known before?
[loweralpha]
... Will He not be brought near and present to us even more effectively than could be the case if our minds were distracted from the inner truth by the vision of a material body?
[loweralpha]
... What we come to see in the truth of the Writings is the very mind of Jesus Christ, the infinite mind of God made manifest in terms of human language adapted to our finite understanding.
[arabic]
.. For us then to have confidence in the Lord, is to have confidence not in any figment of our imagination, but in what the Lord says, what He reveals clearly, openly, and objectively before our eyes.
[loweralpha]
... We have confidence in this because we plainly see in it a truth that the mind at once recognizes as indisputable, as self-evident as axiomatic, and within this we vaguely perceive unfathomable depths of meaning that beckon us on with the promise of untold wonders to be discovered.
[loweralpha]
... How do we know that this is the Lord speaking? How did the disciples know that Jesus Christ was indeed the Son of God?
[loweralpha]
... They knew because they recognized the truth of what He said. Their hearts burned within them, as He who walked with them to Emmaus opened unto them in all the Scriptures the things concerning Himself.
[loweralpha]
... He gave them an idea of the Old Testament teachings that was altogether new, and strange, and at variance with the wisdom of the Rabbis. But it was an idea that confirmed the truth of Scripture, removed obscurities, and difficulties, and opened before their minds a marvelous vista of spiritual perception.
[loweralpha]
... No ordinary man could possibly have conceived what He set forth in clear and simple terms. This is the reason they knew that He was a Divine Being.
[arabic]
.. This is exactly what the Writings do for us, not only for the Old Testament but also for the Gospels and the Apocalypse.
[loweralpha]
... Only they delt now in terms adapted to the minds of men stored with scientific knowledge, and trained in philosophic thinking.
[loweralpha]
... They do it in rational language and with a fullness, logic, and consistency hitherto undreamed.
[loweralpha]
... They fully confirm the truth of all the Scriptures; and yet they open before us a deeper spiritual meaning long buried within them and undiscovered; indeed, undiscoverable by any finite mind unaided.
[loweralpha]
... Here is the Lord speaking, revealing by His words the infinity of His love, the immensity of His power, the eternity and the incalculable wisdom of His law and of His Providence.
[loweralpha]
... The Divinely Human God who here appears, is not the product of any man's imagination. He has none of the weaknesses nor the limitations of mortal beings. He is a Man, indeed loving and wise, compassionate and just, but infinitely perfect.
[arabic]
.. Why, we are asked, if this be so, does not every one recognize Him, acknowledge the truth of the Writings, and gladly become His disciples?
//need help with the above; I changed 'Why, us are' to WE.
[loweralpha]
... It is for the same reason that many among the Jews did not recognize the Lord at His first advent.
[loweralpha]
... It is true today, as it was then, that there is no room in the inn; that is, in the active minds of men, where the infant Lord may be born.
[loweralpha]
... Two things are necessary if the Lord is to be truly seen and known:
He must come by an accommodation, an adaptation of His infinite truth to human comprehension; and men must freely seek Him from a love of truth that opens their minds to the understanding and perception of His Word.
[loweralpha]
... When men are absorbed in the things of earth; when their minds are fully occupied with the problems of natural life; when their whole thought and energy is taken up with the attainment of worldly objectives and ambitions - because these things are regarded as all-important, and essential to human happiness - there is no desire for spiritual understanding.
[loweralpha]
... Only slowly, by gentle Divine leading, by the inscrutable operations of His Providence can the Lord awaken the love of spiritual truth in the minds of men completely devoted to external things.
[loweralpha]
... And only so far as that love is awakened can men freely turn to the Lord, enquire of His Word with minds affirmative, prepared to hear what God the Lord doth speak.
[loweralpha]
... Only such as respond to His teaching in this spirit can recognize Him, and perceiving the marvelous truth of His Word, can realize His near presence, and know that confidence, that sense of inner assurance which is born of a seeing faith, that they may be moved to exclaim from the heart, My Lord, and my God.

What this love of spiritual truth is, and how it may be cultivated in our own minds, and in the minds of our children, will be the subject of our next class.

Reading: @TCR 137, 344; @AC 5963 + 
Music: Doxology 1-382 + 
Hymn: 54-478 (verses 1, 4)

Used: New York, N.Y., June 4, 1961 + 
Pittsburgh, Pa., September 27, 1963

(@AE 759[2]): ...It is granted to the men of the New Church, that is called the Holy Jerusalem, to behold the truths that are in the Word, not sensually, that is, according to appearances, but spiritually, that is, according to their essences; for this reason the internal sense of the Word, which is spiritual and is solely for those who will be of that Church, has been disclosed. ... All who are of that Church have the understanding enlightened, and from this they are able to see truth from the light of truth, that is, whether a thing be true or not true. Because they see truth in this say they acknowledge it, and receive it with the affection which is of the will. By this the truths they have are made spiritual; and in consequence, the spiritual mind which is above the natural mind, is opened with them, and when this is opened it receives angelic sight, which is the sight of truth itself from its own light.

<<<

== IV. The Love Of Spiritual Truth.
April 20, 1971

`I`. We have pointed out that if the Lord is to be truly seen and known, loved and worshiped, two things are necessary: He must come to man by means of a Divine revelation, and man must freely come to Him seeking instruction and guidance.
[upperalpha]
. However fully and plainly Divine truth is set forth in human language, it will not bring the Lord present unless man responds with an eager desire to learn and understand what the Lord says.
[arabic]
.. Man must approach the Lord by reading the Word with an open mind, and by reflecting upon its meaning from a love of spiritual truth.
[arabic]
.. This is well illustrated by the parable of the sower, wherein the truth of the Word is compared to the seed, and the mind of man is compared to the ground on which the seed falls.
[loweralpha]
... Whether or not the seed can spring up and bring forth fruit depends upon the love that is active in the mind of the reader.
[loweralpha]
... If the reading is casual because the interest is centered elsewhere, there will be no real understanding of the Divine message.
[lowerroman]
.... The seed will but fall by the wayside and the fowls will devour it.
[lowerroman]
.... That is, wandering thoughts, preconceived ideas, false appearances will be allowed to distract the mind, and the truth will be lost.
[loweralpha]
... If the reading is inspired by mere curiosity, the truth may be intellectually seen and acknowledged. But the application to life for which it is intended will not be seen; or if it is seen, it will be neglected as a thing of small importance.
[lowerroman]
.... When the sun of selfish or worldly ambitions waxes strong, the truth will be forgotten.
[lowerroman]
.... The tender plant of spiritual affection, having no root, will wither away.
[loweralpha]
... If the truth is sought merely for the sake of appearances, its meaning will be deliberately distorted by false reasonings in support of evil loves.
[lowerroman]
.... Then it is said that the seed falls among thorns, which spring up and choke the young plants.
[loweralpha]
... Only if the mind is inspired by a sincere love of spiritual truth for the sake of amendment of life, will the seed fall into good ground, that it may bring forth fruit some an hundred-fold same sixty-fold, and some thirty-fold.
[arabic]
.. It is by means of this love of spiritual truth, and by this alone, that man draws near to the Lord, and opens his mind to the genuine understanding of the Word.
[upperalpha]
. But what is really meant by a love of spiritual truth? Does it mean that we must love the teachings of the Writings, and accord to them our loyal allegiance? If so, what do we more than others?
[arabic]
.. The adherents of every religion in the world profess to love whatever they may regard as a Divine revelation.
[loweralpha]
... Christians love the Bible, and look to it for Divine instruction.
[loweralpha]
... The Jews cling with unswerving devotion to the Old Testament, and seek therefrom the guidance of Jehovah.
[loweralpha]
... Mohammedans love the teachings of the Koran, and those of every Eastern religion cherish the wisdom of their own sacred books.
[arabic]
.. In doing so, many are utterly sincere, so sincere indeed that they are willing to fight, and if need be to die, in defense of their faith.
[loweralpha]
... History bears testimony to the fact that no persecution, however severe, can stamp out this love of one's religion.
[loweralpha]
... In every age, the blood of the martyrs has proved to be the seed of the church, as is being demonstrated even today in Russia, and in China.
[arabic]
.. Ideas of religion that have been acquired in early childhood rouse the deepest of all affections.
[loweralpha]
... Because these ideas, as implanted in a state of innocence, they are accepted with complete confidence as true.
[loweralpha]
... They are inextricably bound up with that love of truth which is insinuated by celestial angels even in infancy.
[loweralpha]
... Unless this love were insinuated as a balance to the hereditary tendency to love self and the world, no man could possibly be saved.
[loweralpha]
... For this reason the Lord not only implants this love in the mind of every little child, but He protects it with infinite care, even though it may be clothed in religious ideas, rituals and customs that are far from true.
[upperalpha]
. This being the case it follows that to love what one has been taught to regard as a Divine revelation, and thence to love the teachings of one's own church, is not at all the same thing as to love spiritual truth.
[arabic]
.. Children readily, almost inevitably, learn to love the religion in which they are brought up.
[loweralpha]
... They accept it as true because of confidence in the wisdom of their parents and teachers, and because they know nothing else, rather than because they really understand it.
[loweralpha]
... Their acceptance is emotional rather than intellectual. It is indiscriminating, and has little to do with the question as to whether the doctrine is true or false.
[arabic]
.. Indeed it is very commonly supposed that spiritual truth, the truth concerning things supernatural, is beyond human understanding.
[loweralpha]
... Faith therefore is defined as belief in something that cannot be understood.
[lowerroman]
.... It is said that those things which we can understand we do not need to accept on faith.
[loweralpha]
... In accord with this idea, Christian faith is regarded as nothing more than confidence in what has been authoritatively proclaimed, and traditionally accepted as true by the church.
[lowerroman]
.... Catholic faith is based on confidence in the pronouncements of the church councils, the ex-cathedra proclamations of the popes, and the interpretations of bishops and parish priests. Indeed no other understanding of the Bible is permitted.
[lowerroman]
.... Protestant faith is founded upon a belief in the Old and New Testaments as expounded by the great leaders of Christian thought who arose at the time of the Reformation, or as their concepts may have been modified by the ideas of modern science.
[lowerroman]
.... In neither case are the people expected to understand profound theological doctrines for themselves, but merely to accept them, and believe in them, without critical analysis.

* As a result, many people, impelled by the innocent affections of childhood, and by a deep sense of loyalty to what they regard as Divinely true, cling throughout life to the faith of their fathers, closing their minds against everything that seems to oppose it.
[arabic]
.. In modern times even this traditional faith has become, with many, more a matter of form and of habit than of deep conviction.
[loweralpha]
... In every church the traditional dogmas of religion have been called increasingly into doubt.
[loweralpha]
... In consequence, while the established tenets are still held officially, less and less emphasis is placed upon them.
[loweralpha]
... Basic questions as to the nature of God, as to the life after death, and man's eternal destiny, or as to the end and purpose of human life on earth, have been well-nigh abandoned as insoluble.
[loweralpha]
... The Christian Church has widely embraced what it calls the Social Gospel as its chief mission, and the clergy has concerned itself almost exclusively with the task of improving the moral, political, and economic welfare of earthly society.
[loweralpha]
... As a result, the eyes of men have been turned away from the contemplation of spiritual truth.
[lowerroman]
.... It is the love of natural truth, and of the things that can be acquired by scientific application of that truth, that dominates modern thought, both religious and secular, in the Christian world.
[lowerroman]
.... From that love, men look to the Bible seeking therein for the answer to their worldly aspirations.
[lowerroman]
.... In the light of that love they become blind to the spiritual truth that lies concealed within the letter of the Scriptures.
[upperalpha]
. That, therefore, which the Heavenly Doctrine demands of those who would become members of the New Church, is not merely a transfer of loyalty from one ecclesiastical organization to another.
[arabic]
.. They are not asked merely to substitute a new creed, a new Bible, a new set of doctrines for those that have been accepted in the past.
[arabic]
.. Nor is it intended that those who do belong to the New Church should, by education and training, so impress this new faith upon the tender and responsive minds of their children that they may continue, throughout life, faithfully to abide by the religious beliefs and practices of the parents.
[loweralpha]
... This would do no more than bring a new sect into the world, to add its dissenting voice to the Babel of conflicting claims that already have split the Christian Church into an untold number of warring factions.
[arabic]
.. On the contrary, the purpose of the Lord at His Second Coming is to rescue mankind from the web of error and ignorance in regard to spiritual things in which they have become almost inextricably entangled.
[loweralpha]
... He has come to lift men's eyes once more above the things of earth, toward the mountain of His holiness.
[loweralpha]
... He has come to inspire men with a love of spiritual truth that will lead them to seek that truth as the pearl of great price, and to persist through all their life in their search for it.
[arabic]
.. The Writings openly proclaim the truth concerning God, creation, Divine Providence, and concerning man, his spiritual nature, the mode of his regeneration, the supreme purpose for which he has been created, and how the Lord would have him live that he may attain his Divinely intended destiny.
[loweralpha]
... They proclaim this spiritual truth - not in dark sayings, nor in cryptic utterances, to be accepted on trust without understanding - but in rational terms that shed a new and wonderful light upon the mind of each one, enabling him to see for himself these inner verities with the sane clarity, the same certainty and assurance as men have come to associate with the discoveries of science.
[loweralpha]
... This is the truth that is to be loved and sought in the New Church.
[loweralpha]
... By this love, and this search, the New Church is to be distinguished from all other religions.

`II`. In the common thought of the day, spiritual truth is regarded as a sort of abstract theology, an esoteric philosophy concerning God and the future existence of man beyond the grave, the pursuit of which is possible only to a special class of people who unaccountably have a flair for it. It is conceived to have little or no bearing upon earthly things, nor upon the pressing practical problems of everyday life.
[upperalpha]
. Modern Christian thinkers look back with contempt upon the other-worldly philosophy of the middle ages, when men were so absorbed in religious speculations that they neglected almost entirely the demands of the body and the world.
[arabic]
.. Hardly any attempt was made at that time to investigate the laws of nature, or to study how those laws might be utilized to reduce human suffering, and to increase the well-being of society.
[loweralpha]
... Diseases, plagues, famines, floods; long hours of hard labor, serfdom, and slavery - all these things were taken for granted as inescapable, and little or nothing was done to relieve them.
[arabic]
.. Only when men turned aside from fruitless theological speculations, and began to devote themselves wholeheartedly to the task of discovering and applying scientific laws to the needs of mankind, was there any real progress in the development of our civilization.
[loweralpha]
... But as soon as men accepted this responsibility, and persistently exercised their intelligence upon the solution of immediate and practical problems, improvements began to multiply at a most astonishing rate.
[arabic]
.. As a result there has arisen a strong tendency to resist any suggestion that men should return to the study of spiritual philosophy, lest the obvious gains of modern scientific genius be retarded or lost, and the world be plunged once more into the dark ages from which we have happily emerged.
[loweralpha]
... The modern attitude is one of supreme confidence that if we continue to discover the secrets of nature, we need have no concern about those deeper questions of human life which remain unanswered.
[lowerroman]
.... There has been complete assurance that these things will take care of themselves.
[loweralpha]
... Yet in spite of the unbelievable progress in the discovery and application of natural laws, it has become increasingly apparent that something is vitally wrong with our civilization.
[lowerroman]
.... There has been no corresponding progress in spiritual understanding.
[lowerroman]
.... Modern society, with all its wonders, exists under the impending threat of total destruction.
[lowerroman]
.... Inventive and mechanical genius has put lethal power into the hands of those who would reduce all men to slavery, and under the ruthless tyranny of a godless political, and economic machine.

* Selfishness, greed, cruelty, cunning, having cast aside all bonds of honesty, truthfulness, and integrity, seek to trample under foot all the treasured rights of man.
[loweralpha]
... The existence of these deeply imbedded evils is taken for granted as something inevitable and inescapable.
[lowerroman]
.... They are regarded as inherent in human nature, and it is supposed that to ignore them, or to think and act as if they did not exist, or as if men were not necessarily subject to them, is inexcusably visionary, sentimental, and impractical.
[lowerroman]
.... In fact, the modern attitude toward these basic evils is just as fatalistic as was the medieval attitude toward natural ills.
[lowerroman]
.... Religions seek to escape these evils by denying their existence, or by cultivating a belief in some magical formula whereby they may be instantaneously dissipated, or rendered powerless.

* The one is represented by Christian Science, and the other by the doctrine of salvation by faith alone.

* But no one has the faintest idea how they may actually be overcome and removed. Nor is it believed that this knowledge can be discovered.
[loweralpha]
... This is the reason why there has been no measurable advance toward a solution of the deeper problems of human society.
[lowerroman]
.... It is the reason why, at the very height of scientific development, we have seen the resurgence of global war on a scale unprecedented in the past.
[lowerroman]
.... It is the reason why we are faced today with a tremendous increase of tyranny, slavery, and ruthless cruelty of man to his fellow man, together with a growing disregard of all moral and spiritual obligations.
[upperalpha]
. There can be no progress in the realm of moral and spiritual life so long as men retain the confirmed opinion that the truth concerning spiritual things cannot be known with certainty or assurance.
[arabic]
.. The established belief of our day is that while scientific truth can be tested and proved, ideas concerning religion are purely imaginary, and therefore are matters of personal opinion for which there is no criterion.
[loweralpha]
... It is supposed that although nature operates according to fixed, discoverable, and understandable laws, God operates in the realm of the spirit altogether government is in accord with law, it is above all human comprehension, and therefore in the sight of man, wholly miraculous.
//this sentence needs help
[arabic]
.. On the contrary, the Writings teach that God operates in both worlds in accord with definite laws, and that the human mind is created to see and understand not only the laws of nature, but spiritual laws as well.
[loweralpha]
... The Lord can makes those laws known in such a way that man can see and understand them quite as clearly as he can understand the laws of nature.
[lowerroman]
.... The mind, we are told, can see spiritual things, just as the eye sees natural things.
[arabic]
.. The laws of the spiritual world, and of man's spirit here on earth, are all involved in the teaching of the Old and New Testaments; and what is there concealed under parables and dark sayings, is now set forth plainly in the rational language of the Writings.
[loweralpha]
... Not that men can see it there suddenly, and in fullness; but merely that the possibility of a gradual discovery of those laws, and of their application to the practical concerns of human life, is now opened to men as never before in the history of the world.
[lowerroman]
.... This because the race has advanced to the point where such rational understanding is now possible for the first time.
[lowerroman]
.... This is the meaning of the statement that now it is permitted to enter intellectually into the mysteries of faith.
[loweralpha]
... The laws of nature were present in all of creation from the beginning. But only in modern times were men awakened to the fact that they could be discovered and used for the benefit of mankind.
[lowerroman]
.... Only when this became evident, and men turned their minds systematically to the investigation of those laws, did natural progress result.
[loweralpha]
... So also the laws of spiritual life have been present in the Word from the beginning; but only as a result of the Lord's Second Advent have men begun to awaken to the fact that these also can be discovered and brought to bear, in practical ways, upon the problems of spiritual life.
[lowerroman]
.... The truth of the Writings makes it plain for the first time that the evils of man's heredity, that bring so much suffering into the world, are not inevitable.
[lowerroman]
.... They can be met and overcome by learning, and by applying the true laws of spiritual life now made available to us in the Heavenly Doctrine.
[loweralpha]
... However, if this is to take place, men must love spiritual truth. They must search it out with unceasing persistence. They must cherish it, and abide by it, with the same determination, the same devotion, the same willingness to set aside preconceived ideas, as men have demonstrated in their successful search for natural truth.
[lowerroman]
.... This is the kind of love for spiritual truth that must characterize the New Church, and distinguish it from all other religious bodies.
[lowerroman]
.... It is a far cry from any blind devotion to traditional dogmas, or from any approach to revelation in search of political, economic, or moral answers to the ills of human society.

.... This love of spiritual truth is not to be confined to the clergy. Its application to life is, of necessity, an individual matter.
[lowerroman]
.... No one can make such application for another. Nor can the Church organization make it for its members.

* Each one must seek enlightenment and guidance immediately from the Lord, by means of the Word; for the Lord alone knows the heart of man, and He alone can teach man how to remove the love of evil at its source.
[arabic]
.. That the Lord will grant an understanding of spiritual truth to all who love that truth, and who seek it with a pure heart, is the sure promise of the Writings. For we read:
[loweralpha]
... It is granted to those who belong to the New Church that is called the New Jerusalem, to behold the Divine truths that are in the Word, not sensually, that is, according to appearances, but spiritually, that is, according to their essences; ... They and no others receive spiritual light which is continually flowing in from the Lord with all who read the Word (@AE 759).

Reading: @AE 759[2] + 
Music: Hymns 72-502; 27-446 (1, 4)

THE DECALOGUE

(@TCR 282): There is not a nation in the whole world which does not know that it is wicked to murder, to commit adultery, to steal, and to bear false witness; and that kingdoms, republics and every form of organized society would be at an end unless these evils were guarded against by laws. Who then can suppose that the Israelitish nation was so stupid beyond all others as not to know that these are evils? Any one therefore may wonder that laws so universally known in the world should have been promulgated from Mt. Sinai by Jehovah Himself in so miraculous a way. But listen: they were promulgated in so miraculous a way to make known that those laws are not only civil and moral laws, but also Divine laws; and that acting contrary to them is not only doing evil to the neighbor, that is, to a fellow citizen and society, but is also sinning against God. Wherefore these laws, by their promulgation by Jehovah on Mt. Sinai, were made also laws of religion....

(@TCR 289): In the spiritual and celestial senses the Decalogue contains universally all the precepts of doctrine and life, thus all things of faith and charity, because the Word in each and all things of the sense of the letter, or in general and in every part of it, conceals two interior senses, one called the spiritual sense, and the other the celestial; ... And because the Word in general and in every part of it is so constituted, the Ten Commandments of the Decalogue must needs be explained according to these three senses, called the natural, the spiritual, and the celestial.

<<<

== V. The Removal Of Evil. (1)
April 4, 1971 + 
February 20, 1953

`I`. We have said that the New Church is to be distinguished from all other religions by a love of spiritual truth.
[upperalpha]
. This is the truth that has hitherto lain concealed beneath the dark sayings, the historic narratives, and the parables of the Old and New Testaments.
[arabic]
.. But at His Second Coming the Lord has made it possible for men to penetrate the literal meaning of the Scriptures, and to discover therein the Divine laws of spiritual life.
[loweralpha]
... These laws are openly stated in the Writings, but their practical application to life can be learned only by slow degrees.
[lowerroman]
.... The minds of men can be prepared to understand them only gradually, as long established ideas, appearances, and fallacies are discredited and discarded.
[lowerroman]
.... This can come to pass only as men read, study, and reflect upon the teaching of the Writings from an acknowledgment of their Divinity, and from an inmost desire and willingness to be taught by the Lord.
[loweralpha]
... This task of careful study and investigation must be undertaken, not merely that we may understand what the Lord teaches, but in order that we may live according to it.
[lowerroman]
.... The sole purpose for which the laws of spiritual life are revealed, is that by the right application of those laws to the circumstances and conditions of our lives, the love of evil, which has become so deeply rooted in human nature, may be overcome, and permanently removed from the hearts of men.
[lowerroman]
.... There is no other means by which this end can be accomplished.

`II`. Of course the professed purpose of every religion is to combat and overcome evil, and thus to redeem mankind from the bondage of sin. But religions differ widely in their concept of what evil is, and of how it is to be removed. In regard to these two things the teaching of the Writings is in marked contrast to that round in other religious faiths.
[upperalpha]
. In general it may be said that those things are commonly regarded as evil which are thought to be in any way injurious to the welfare of human society.
[arabic]
.. The goals men seek are peace, security, and freedom of opportunity; health, success, and prosperity; mutual respect, charity, and good will among men.
[loweralpha]
... Whatever is deemed to promote these objectives is regarded as good; and whatever is opposed to them is condemned as evil.
[arabic]
.. Because conditions of life differ greatly in various parts of the world, and because they continually change with the times, human judgment as to what is good, and what is evil, is correspondingly divergent.
[loweralpha]
... Things that are regarded as evil in one country are sanctioned as good in another.
[loweralpha]
... Practices condemned by one generation may be accepted as right in the next.
[loweralpha]
... Things arbitrarily proclaimed to be sinful by one religious group, are either ignored or definitely approved by others.
[loweralpha]
... And for this reason there is a strong appearance that there is nothing either good or evil in itself, but that ideas of right and wrong, or justice, and honor, and morality, are altogether relative, varying according to circumstances that arise out of existing needs.
[arabic]
.. Every religion claims that its concept of what is good, and what is evil, is the true one that it is derived by revelation or by inspiration from God, and that all men must live by it if they are to be saved.
[loweralpha]
... Yet in many respects they are mutually contradictory. Indeed in many respects they are applicable only within a restricted area of time, or of space.
[upperalpha]
. This becomes clearly evident at once by comparison of various religions.
[arabic]
.. Among the Jews, the laws of Moses, literally understood, apply very largely to conditions that have long since passed away.
[loweralpha]
... Some of them were designed to meet the circumstances in which the Israelites found themselves during their wanderings in the wilderness, but had no application to their life after they had conquered the Holy Land.
[loweralpha]
... Others had to do with the period of the judges, and still others with the time of the kings, but had no practical application during the Babylonian captivity, nor even after the restoration, when they were subject to Persia, Greece, or Rome.
[loweralpha]
... Because of this, the Mosaic code was subject to constant and repeated interpretation by the Scribes, the Pharisees, and the Rabbis.
[lowerroman]
.... In the course of generations a tremendous accumulation of meticulous regulations arose many of which were quite contrary to the original intent of the law.
[lowerroman]
.... Against these the Lord warned His disciples saying, Ye have heard that it hath been said by them of old time ... but I say unto you.
[lowerroman]
.... And He inveighed against the cruel demands of the Jewish rulers, saying, They bind heavy burdens, and grievous to be borne, and lay them on men's shoulders.
[arabic]
.. These obsolete legal restrictions were all abrogated by the Christians, though not without a long struggle. But having done so, the Christian Church proceeded to accumulate traditional restrictions of its own. Indeed every sect adopted its own set of prohibitions and requirements.
[loweralpha]
... Some established specific requirements for the keeping of the Lord's Day.
[loweralpha]
... Many condemned as sins the practice of card playing, smoking, drinking, going to the theater, and various forms of gambling.
[loweralpha]
... Others proclaimed it a sin to shave the beard, or to wear buttoned garments, or to use mechanical appliances.
[loweralpha]
... These are but a few random illustrations of the kinds of things that at various times, and by various religious organizations were proclaimed to be sins, and made matters of conscience.
[arabic]
.. Are all these things sinful? Does our salvation depend upon our careful observance of them? If not, what is evil? How can we know? Is there nothing that is so evidently detrimental to the welfare of society everywhere, that it may be universally recognized as evil?
[upperalpha]
. I think it may safely be said that all religions, whether Christian or pagan, recognize as sins those things which are forbidden by the Decalogue.
[arabic]
.. Every one knows that it is wicked to murder, to commit adultery, to steal, to bear false witness.
[loweralpha]
... And everyone knows that the evil in these things lies not merely in the outward act, but also in the desire and intention of the heart - in ill-will toward the neighbor, in jealousy, covetousness, hatred, malicious cunning, and the lust for revenge.
[arabic]
.. Surely these are Divine laws, having universal application to all men, in every age.
[loweralpha]
... The Writings indeed tell us that they include every possible evil into which mankind can fall.
[loweralpha]
... Yet, in accepting this teaching, we still have not discovered wherein evil really lies.
[lowerroman]
.... For in application these laws also vary greatly, according to the circumstances and conditions of life.
[lowerroman]
.... Although they are evil, in their outward form these things are not always sins.
[loweralpha]
... Religions differ widely in their understanding as to when it is not a sin to kill; under what conditions it is allowable to abrogate the marriage convent; when it is not only allowable, but right to deprive others of their goods; and when it is wise and just to withhold the truth from those who would use it to injure or destroy the innocent.
[lowerroman]
.... For this reason we find outward infractions of the Ten Commandments that are sanctioned by some religions and condemned by others.
[lowerroman]
.... Where does the evil really lie? Surely not in the outward form, but in violating the inner essence of these Commandments.

`III`. The Writings teach that the Divine Providence, in all that it does, has regard primarily to what is eternal, and to temporal things only so far as they contribute to eternal ends. This, because that which is eternal IS, and that which passes away in time, relatively IS
NOT.
[upperalpha]
. Good, in its very essence, is that which is in accord with the will of God, and which thus promotes the final end and purpose of His Providence, and evil, in its very essence, is that which is contrary to the Divine will, and which opposes and interferes with His Providence.
[arabic]
.. The end of all creation, we are told, is the formation and the perfection of a heaven from the human race.
[loweralpha]
... Whatever runs counter to this Divine end is evil.
[loweralpha]
... And because the end is one, and eternally unchanging, evil is universal and ever the same, when regarded as to its inmost essence.
[arabic]
.. Furthermore, because it is man's eternal life and happiness that the Lord has in view, it is not that which affects the body, but solely that which injures or threatens to destroy the spirit of man, that can truly be called evil.
[loweralpha]
... Wherefore the Lord said: Fear not them which kill the body, but are not able to kill the soul; but rather fear him which is able to destroy both soul and body in hell (Matthew 10:28).
[arabic]
.. If therefore we would discover the inner essence, the true quality of evil, we must know what is injurious or destructive of man's spiritual life.
[loweralpha]
... We must know something of the mode whereby the Lord imparts spiritual life to man, and something of the Divine laws whereby in Providence He protects that life.
[loweralpha]
... So far as these laws are known and understood, we can judge wisely as to what is truly good, and what is really evil.
[lowerroman]
.... Such understanding gives us the ability to use these laws for the spiritual and lasting benefit of mankind, just as a right understanding of the laws of nature gives men the power to utilize them to promote the external welfare of human society.
[upperalpha]
. The Writings are given for the specific purpose of making known these Divine laws in terms adapted to our limited understanding.
[arabic]
.. They teach us not only the universal laws of Divine Providence, but also how those laws may be applied, in practical ways, to the task of removing evils, not merely as to their outward form and manifestation, but as to their inner cause and essence.
[loweralpha]
... They teach us what the Ten Commandments really mean in their relation to spiritual life.
[lowerroman]
.... Thus not only their moral application to the preservation of earthly society, but how they will continue to apply in the spiritual world, where earthly conditions will no longer obtain.
[lowerroman]
.... And because the life of men's spirit here on earth is governed by those same laws, they teach us how those Commandments are intended to promote man's eternal welfare.
[lowerroman]
.... How by their application to life man's spirit may be formed for heaven, and how the true spirit of heaven may actuate his every thought, word, and deed.
[arabic]
.. When we learn the internal sense of the Ten Commandments, as now revealed in the Writings, we are given an altogether new and different concept of what evil really is.
[loweralpha]
... There we are told that to kill is to destroy spiritual life; that is, to destroy all love to the Lord, and all charity toward the neighbor, and thus to deprive one of the life, the use and the happiness of heaven.
[loweralpha]
... We are told that adultery, in its essence, is that which destroys the conjugial which is in heaven, the conjunction of the Lord and the Church, the marriage of good and truth in the mind and heart of man.
[loweralpha]
... We are told that to steal is to claim for ourselves that which belongs to God alone, to confirm the appearance that we have life in ourselves, to be used to satisfy our own ambitions, without regard to the will of God, nor to the welfare of others.
[loweralpha]
... And we are told that to bear false witness against the neighbor is to distort and falsify the teaching of the Word. To do this is to deceive men, and close their minds against the reception of spiritual truth and good.
[arabic]
.. These are the real sins against God and the neighbor that must be removed from the inner spirit of man, if he is to enter into heaven after death, or if he is truly to enter into the church, the kingdom of heaven on earth.
[loweralpha]
... And while they appear very simple, as stated in the Word and in the Writings, their application is rendered extremely complex by the very complexity of human life.
[loweralpha]
... This is the reason why the Ten Commandments, by themselves, are not sufficient.
[lowerroman]
.... To help men understand how they are to be applied, the entire Sacred Scripture is needed.
[lowerroman]
.... To this end the Writings explain the spiritual meaning of all the Mosaic Laws, showing, that while in their outward form they are obsolete, and adapted solely to the times and conditions of ancient Jewish life, when spiritually understood they may be seen to have universal application, and are just as vital to men today as they were in the lifetime of Moses.
[lowerroman]
.... More than this, not only the laws of the Pentateuch, but the historic events recounted in other books of the Old Testament, and the cryptic sayings of the prophets, all are intended to illustrate the application of the Ten Commandments to man's spiritual life.

* So also are the teachings and parables of the Lord, and the account of His journeys and His miracles, as related in the New Testament, as well as the prophetic imagery of the Apocalypse.
[loweralpha]
... From beginning to end, as to every chapter and verse, the Divine purpose of the Word is to teach man how to live in accord with the spiritual and eternal laws of life.
[lowerroman]
.... It is evident therefore that the wise application of spiritual truth is not something that can be learned in a moment.
[lowerroman]
.... In this respect spiritual truth, to be sought out by a study of Divine revelation, is not unlike the scientific truth that must be investigated and discovered in nature.
[lowerroman]
.... Only by persistent effort on the part of many minds, and extending over many generations, can men discover the laws of nature, and how they may successfully be applied to the cure of disease, to the relief of poverty and want, or to the increase of freedom, and the greater satisfaction of human desires.

* So also, only by the same slow process of devoted research can the spiritual truth now brought within man's grasp by the Writings, be successfully applied to promote the spiritual welfare of mankind, and to remove internal evils.
[upperalpha]
. Let it be clearly understood that evil, as to its real essence and its spiritual cause can be removed only by the Lord.
[arabic]
.. What the Writings are intended to teach us is not how we can remove them, but what by Divine law we are required to do in order that the Lord may remove them.
[loweralpha]
... And this brings us to consider the question, how may evils be removed?
[loweralpha]
... In regard to this also, the teaching of the Heavenly Doctrine differs radically from that to be found in any other religion in the world.
[loweralpha]
... This then will be the subject of our final class.

Reading: @TCR 288, 289; @AE 1024[2] + 
Music: Hymns 42-464 verses 1, 3;  41-463

(@AC 9938): ...The gifts that were offered in the Jewish Church, and which were chiefly burnt offerings, sacrifices, and meat offerings, were also called expiations from sins, because they were offered for the sake of forgiveness from them, that is, removals from them. Those who belonged to that church also believed that their sins were accordingly forgiven, nay, that they were entirely taken away; for it is said after they had offered those things that they were forgiven. But they did not know that these offerings represented interior things, thus such things as are done by man from the love and faith that are from the Lord; and that these are the things which expiate, that is, remove sins, and that after they have been removed they appear as if they were quite taken away.

(@AC 9452): The Lord regenerates man from Divine mercy. This is done from his infancy down to the last of his life in the world, and afterward to eternity. Thus it is from Divine mercy that the Lord withdraws man from evils and falsities, and leads him to the truths of faith and goods of love, and afterwards keeps him in these. And after this, in Divine mercy He raises him to Himself in heaven, and makes him happy. All this is what is meant by the forgiveness of sins from mercy. They who believe that sins are forgiven in any other way are quite mistaken....

<<<

== VI. The Removal Of Evil (2)
Delivered: Bryn Athyn, Pa., February 27, 1953 + 
New York, N. Y., April 14, 1957 + 
Rockford, Ill., October 7, 1958 + 
February 27, 1953. May 4, 1971 + 


`I`. At our last class we stressed the teaching of the Writings as to what evil really is, or what makes an evil to be a sin against God and by comparison we showed how greatly this teaching differs from that to be found in other religions. And this evening we would consider the question as to how evils of sin may be overcome end removed.
[upperalpha]
. The idea that this can be accomplished by some form of ritual observance is common to all religions, and its origin may be traced to the very dawn of history.
[arabic]
.. Sir James G. Frazer, in The Golden Bough cites many instances of such practices as found not only among primitive races, but also among highly cultured nations in many parts of the world.
[loweralpha]
... In general the idea of primitive man seems to have been not so much to remove the sin, as to escape the punishment of sin by appeasing the wrath of the gods.
[lowerroman]
.... External evils, such as disease, famine, drought, flood, fire, or any catastrophe were supposed to be instruments of Divine punishment.
[lowerroman]
.... It was thought that they were caused by evil spirits whose influence must be counteracted.
[loweralpha]
... The means employed to drive away such evil spirits varied greatly in different countries, and with regard to different evils.
[lowerroman]
.... Some were preventative, as the charms hung at the door of a house to protect its inmates.
[lowerroman]
.... Others were to beg forgiveness for some sin, either recognized or unknown, which was supposed to be the cause of Divine displeasure. Such were prayers and votive offerings to the Deity in times of trouble.
[lowerroman]
.... In other cases, without appealing to the gods, direct measures were taken against the evil spirits, as when the men of a village would gather with sticks and other weapons, and go through all the houses, one after the other, beating the floor, the walls, the furniture, and loudly calling upon the evil one's to depart.

* Sometimes, in case of illness, an image of the sick person moulded in clay, or made of other material, would be rubbed against the patient, and then, with imprecations it would be burned, or crushed, or buried deep, either in water or in the ground, the idea being that it would carry the disease away with it.

* When a nation or tribe was suffering from any general disaster, means of a more sinister nature were often employed. An animal, or even a person, having been declared the bearer of the evil, would either be driven away or put to death, in the belief that in this way the evil would be stamped out.
[arabic]
.. Such methods of removing evil would seem to have been given Divine sanction in the Old Testament.
[loweralpha]
... Among the Jews it was believed that men could make atonement for their sins by means of burnt offerings, sacrifices, and meat offerings.
[lowerroman]
.... In fact a specific sacrifice was prescribed for each kind of offence, and minute directions were given, both to the priests and the people, as to how these were to be offered.
[lowerroman]
.... Under the direction of the priests and Levites, a lamb, a kid, a bullock, turtledoves or pigeons, were to be sacrificed at the altar in the court of the Tabernacle, or later in the Temple, for every one who came confessing some sin.
[loweralpha]
... A sacrifice was offered for the whole congregation every morning and every evening; and once a year, on the great day of atonement the high priest would enter the Holy of Holies, to sprinkle the blood of the sacrificial bullock, and he-goat, upon the mercy seat above the ark of the covenant, thereby to remove the sins of all the people.
[lowerroman]
.... Afterward, he was to take a live he-goat, and laying his hands upon its head, confess over it all the iniquities of the children of Israel
... and send it away by the hand of a fit man into the wilderness.
[lowerroman]
.... Thus it was believed that the scapegoat would carry away into the wilderness the sins of the whole congregation.
[arabic]
.. The idea that sins could be removed by transferring the guilt, and at the same time the punishment, to another, has been carried over into the Christian Church.
[loweralpha]
... Indeed, the doctrine that Jesus Christ, the Son of God, by His death upon the cross, made a vicarious atonement for the sins of all mankind, is a direct descendant of that ancient concept.
[lowerroman]
.... The Jewish sacrifices are understood to be a prophetic foreshadowing of the crucifixion.
[lowerroman]
.... And John the Baptist said of the Lord: Behold the Lamb of God, which taketh away the sin of the world (John 2:29).
[loweralpha]
... In the Catholic Church it is believed that a person may be granted absolution from sin by doing whatever penance may be prescribed by the priest.
[lowerroman]
.... This is effected by offering prayers, by burning candles, by paying money, or by making some personal sacrifice.
[lowerroman]
.... Moreover, it is taught that by similar means, through the intervention of the saints, one may take upon one's self the guilt and punishment of another, and thus obtain release for one's family or friends from the tortures of purgatory.
[loweralpha]
... In general, Protestants, following the doctrinal teaching of Martin Luther, deny the efficacy of any such works of the law, and hold that man is released from the bondage of sin solely by faith in Jesus Christ.
[lowerroman]
.... This, it is believed, brings a free and instantaneous gift of Divine forgiveness, and with it the sure promise of salvation.
[lowerroman]
.... While a good moral life is thought to contribute nothing to salvation, it is regarded as the fruit of faith, and the spontaneous result of belief in Jesus Christ.
[loweralpha]
... Other Protestants, however, consider that the guilt of sin is removed by a careful observance of the moral code, or by abstaining from whatever, in conscience, is hold to be evil.
[lowerroman]
.... Some add to this the power of prayer, the efficacy of regular worship, and a devout partaking of the Holy Supper.
[lowerroman]
.... While others make light of these formalities, and place sole reliance upon honesty, fair dealing, and a spirit of charity, and good will, as the means of removing evils.
[lowerroman]
.... Often these suppose that they can make amends for sin by acts of kindness, benevolence, and mercy, which as it were balance or cancel out one's misdeeds.

`II`. In striking contrast to those ideas is the teaching of the Writings as to how evils may be removed, and sins forgiven.
[upperalpha]
. In the first place, we are taught that there is no such thing as a vicarious atonement.
[arabic]
.. Guilt cannot be transferred from one person to another.
[loweralpha]
... A tendency to evil can indeed be transmitted from generation to generation by parental heredity; but for this no man is held responsible.
[loweralpha]
... The evil of sin is solely that which one does by deliberate choice, and of his own free will. For this alone he is culpable.
[loweralpha]
... That which a person has made his own by free choice can be removed only by his own free consent.
[arabic]
.. The idea that the guilt of sin may be transferred to another had its origin in the representatives of the Ancient Church.
[loweralpha]
... The ritual of the scapegoat, which in later times took on many perverted forms, was originally intended to represent the truth that the Lord alone can remove evils from the human heart.
[lowerroman]
.... It represented the fact that the Lord removes evils by means of the truth of the Word.
[lowerroman]
.... Also, that He can do this so far as man freely cooperates by striving to understand that truth, and by living according to it. To live according to the truth is to resist every impulse to will, think, or act contrary to it.
[lowerroman]
.... Finally, it represented the fact that man is able to resist evil in this way only if he acknowledges that the impulse to evil, ever present in his hereditary nature, is not himself, but is imposed upon him by an influx from the hells; thus that he is under no compulsion to obey it, but has power from the Lord to reject its influence over him.
[loweralpha]
... All this is pictured representatively in the ritual of the scapegoat as prescribed in the sixteenth chapter of Leviticus. There, as we are told in the Writings:
[lowerroman]
.... Aaron represents the Lord, by whom alone evils can be removed.
[lowerroman]
.... The goat called asasel, represents the natural man, or the external mind, in which are all hereditary tendencies to evil.
[lowerroman]
.... Aaron placing his hands upon the head of the goat and confessing the sins of the congregation, represents the acknowledgment that the source of hereditary evil is from hell; thus that man is not guilty of it unless he makes it his own by willful act.

* Sending the goat out into the wilderness, the land or cutting off, represents the shunning of the evil, conscious resistance to it on the part of man, whereby he practices actual repentance.

* When man does this in regard to one evil, or to a few evils that he sees and acknowledges from the heart, the Lord removes many interconnected impulses to evil of which the man is not conscious; and thus protects him against the overpowering attack of the hells.
[arabic]
.. Further, we are taught that by the passion of the cross the Lord did not make a vicarious atonement for the sins of the human race.
[loweralpha]
... Instead, by a long series of temptations extending throughout His life on earth, and culminating in the passion of the cross, the Lord conquered the hells, reduced them to order, and restored man's spiritual freedom by re-establishing a balance of equilibrium between heaven and hell.
[lowerroman]
.... Without this Divine work no man could have been saved, because no man could have been given the power or the ability, in freedom, to choose the Good and resist the evil.
[lowerroman]
.... All would have been swept into a maelstrom of evil passions, against which they would have been completely helpless.
[lowerroman]
.... But when the Lord overcame the hells, He unmasked the falsities that had held the minds of men in bondage, and revealed the inner truth of His Word, that men might know the truth, and that the truth might make them free.

* By this Divine work all men have been redeemed; but only those who freely accept the Divine truth, and by their own determined effort strive to live according to it, are saved.

* This every individual must do for himself. It is a responsibility that no one else can take for him.

* And man can in this way cooperate with the Lord, just so far as he knows, understands, and loves the spiritual truth of the Word, which alone can teach him what are the evils that are to be resisted, and how he can effectively fight against them.
[arabic]
.. This knowledge is involved in all the minute particulars recounted concerning the sacrifices, burnt offerings, and meat offerings in the Books of Moses.
[loweralpha]
... Burnt offerings, and sacrifices in general, we read, represented purification from evils and falsities (@AC 10022).
[loweralpha]
... What was represented in particular is evident from the various species of animals which were sacrificed (ibid).
[lowerroman]
.... Each animal represented some specific truth of the Word, or some specific affection whereby a corresponding evil might be resisted and overcome.
[lowerroman]
.... A study of the internal sense of this portion of the Old Testament, as now explained in the Writings, will lead to increasing understanding of how evils are to be removed.
[lowerroman]
.... This can be accomplished only by a slow process, because at present these concepts are so abstract to us, and as have so little knowledge of these spiritual things.

* But as the Church grows, the ability to derive from the Writings intelligence and wisdom in the understanding and application of these spiritual laws of life, should steadily increase.
[upperalpha]
. The Lord alone can remove evils from man's heart, and this He does continually, in a thousand and a thousand ways. But the Lord can do this only so far as man, as of himself, shuns evils as sins against God.
[arabic]
.. To shun evils is, of course, to refrain from them in intention, in thought, and in act. But this may be done for many reasons.
[loweralpha]
... The first deterrent to evil, with every one, is the fear of punishment and the hope of reward.
[lowerroman]
.... This begins with every little child at his mothers knee, by learning to refrain from what she has forbidden.
[lowerroman]
.... As the child grows he learns progressively why certain things are evil, and why they must be shunned; namely, because they are injurious to himself, and to others.
[lowerroman]
.... But the most important lesson of all is that evils are to be shunned because they are against the teaching of the Word, and thus against the will of the Lord.

* This also can be done solely to avoid punishment, or to gain favor with others.

* In fact it cannot be done for any other reason during childhood.
[loweralpha]
... As the rational mind is gradually formed and opened in youth, abstract ideals of justice, uprightness, honesty, and other moral virtues begin to modify the concept of what evil is, and of why it should be shunned.
[lowerroman]
.... Yet ideas of right and wrong will be determined by the moral code of one's family, one's teachers, one's church, and the prevailing standards of morality in the society in which one is brought up.
[lowerroman]
.... All these things will be accepted as true because of confidence in others.
[lowerroman]
.... It cannot be otherwise before adult age is reached, and one has acquired the ability to think and judge for one's self.

* In this regard, those who are educated in the New Church are no different from those who are brought up in other religions.

* Many people remain in this state throughout life, and this is possible also to those who are raised in the New Church.
[loweralpha]
... The Writings describe an easier mode of shunning evil, which in the merciful Providence of the Lord is open to all men, of every religion.
[lowerroman]
.... Every one who believes in God, and in a Divine law that must be obeyed because it is the will of God, can do what he thinks is right, and avoid what he believes to be wrong.
[lowerroman]
.... When he is tempted to take an action that is contrary to his religious conscience, he has power to say within himself, I will not do this because it is forbidden by God.
[lowerroman]
.... This mode of shunning evil preserves a state of innocence, that is, a willingness to be taught and led by God; and one who is faithful to it during his life on earth, can after death learn what is really good, and what is truly evil; and as be learns this he can freely be led to live according to it.
[loweralpha]
... But no one can fight against what is really evil unless he knows what it is, and what he must do in order to overcome it.
[lowerroman]
.... This knowledge can be received only from the Word, and only so far as the spiritual sense of the Word is revealed and opened to our understanding.
[arabic]
.. So long as men rely solely upon a literal understanding of the Bible; so long as their minds are clouded by false interpretations of the Bible; so long as they take the attitude that nothing can be known about the life after death, and that if we live what we personally regard as a good moral life in this world, the future life will take care of itself, to this extent they will not seek a deeper understanding of the Word, and of the life of religion.
[loweralpha]
... It follows that they will remain ignorant of what evil really is, in the sight of God; and they will remain ignorant of those spiritual laws of human life by which alone those deeper evils nay be removed by the Lord.
[loweralpha]
... This is what the Lord has now revealed at His Second Coming. And by means of this spiritual truth, He has made it possible for men to learn progressively how to combat those evils of the human heart which the religions of the world have been unable to remove - the evils of self-love, greed, the love of dominion, and of personal power, which combine to perpetuate wars, dissentions, injustices, with all their accompany sufferings; and to pose a constant threat to the very existence of human society, in spite of great progress in scientific knowledge and skill.
[loweralpha]
... This is the truth which those who belong to the New Church are to search out from the Writings, and the former Scriptures.
[loweralpha]
... And these are the evils against which those who belong to the New Church are to give battle, by resolutely striving to live according to that spiritual truth.
[loweralpha]
... And as this is done, we have the Divine promise that the Lord, in a thousand miraculous ways, will deliver mankind from the power of evil, and will establish His heavenly kingdom in the hearts of men, that they may come at last into the peace, security, and happiness of genuine charity and mutual love.
[loweralpha]
... Then indeed will the prophecy be fulfilled: Behold, the tabernacle of God is with men and He will dwell with them, and they shall be His people, and God Himself shall be with them, and be their God (Revelation 21:3).

Reading: @AC 9938, 9452. + 
Music: Hymns 70-499; 47-469 (verses 1 and 4)
