= Chapel Talks on Vital Subjects
By Reverend Ormond de Charms Odhner
// include::../template-attributes.adoc[]

PREFACE

To

CHAPEL TALKS ON VITAL SUBJECTS

By Reverend Ormond de Charms Odhner

There has been a great demand on the part of those New Church people who do not live in situations where they have regular pastoral ministrations for material suitable for family worship and Sunday Services with their children. It is with the hope that this little volume of fifty-one talks by the Reverend Ormond Odhner will in some measure fulfill this need.

The talks here presented were given originally to the boys and girls of the Secondary Schools of the Academy of the New Church at their regular morning worship services. The talks are remarkable in that few of them are more than five minutes long, yet they cover the subject with virility and clearness.
// ?'virility'? //

Another work, endeavoring to do the same thing, is now available. It is a similar booklet by the editor containing ten talks on the prophet Elijah, twenty-six talks on the prophet Daniel, and fourteen talks on Easter. Yet another book by him, in process or completion, will contain fifty talks to children on the Creed, and other selected subjects.

Rev. Karl R. Alden, Editor

////
TABLE OF CONTENTS

Preface I Prayer I 1

Prayer II 2

Prayer III: Why Pray? 3

Prayer IV: For What is it Right to Pray? 4

Prayer V: Praying for Others 5

Prayer VI: Particulars Concerning Prayer 6

II Selected Subjects

Worship 7

Ritual I 8

Ritual II 9

With or Against I 10

With or Against II 11

Greatness of Service I 12

Greatness of Service II: Ambition 13

III Knowledges and Uses

Knowledge of God 14

Knowledge of the Means of Salvation 15

Knowledge of the Life After Death 16

Knowledge of the Purpose of Creation 17

Knowledge of Conjugial Love 18

Uses are the Lord with Man 19

Use and Pleasure 20

Sincerely, Justly, and Faithfully 21

Use and Youth 22

IV The Book of Judges

I 23

II 24

Story of Gideon I 25

Story of Gideon II 26

Story of Gideon III 27

Story of Gideon IV 28

Abimelech 29

Jephtha I 30

Jephtha II 31

Shibboleth 32

Hair 33

Samson's Instability 34

Philistines 35

Samson 36

Samson and Delilah 37

V The Book or Jonah

I 38

II 39

III 40

IV 41

V 42

VI The Christmas Story

Advent I: Prophecies 43

Advent II 44

Virgin Birth 45

Reformation and Regeneration 46

Preparation by John 47

And He Called His Name Jesus 48

The Incarnation 49

Thoughts Revealed 50

The Christmas Star 51

Out of Egypt 52

The Incarnate Word 53
////

== CHAPTER I

=== PRAYER -- I

Psalm 66

This morning we have begun a series of chapel services dealing with the subject of prayer - first, prayer in general; next, the Lord's Prayer in particular.

Almost from infancy we have indulged in prayer. Today, with all of us prayer is habitual, and anything that becomes a habit tends to lose meaning. Occasionally, therefore, it is well to pause and give serious consideration to the subject. What is prayer? What should it be? How does it work? For what is it right to pray?

Perhaps the most general definition or prayer given in the Writings is found in the Arcana (2535) where it is taught that prayer is talk with God together with some internal view or the subject of the prayer.

Talk with God - that conceivably could be mere idle prattling. But, it is added, together with an internal view or the subject. That makes prayer serious and also helps to teach what it is right to pray for. You might want a candy bar; you could hardly have any internal view on the subject, though, and you therefore would not pray for it.

Prayer should be serious, done with real thought. Yet there is probably not a person here who has not frequently experienced a certain common embarrassment. We begin to say the Lord's Prayer; all of a sudden we find ourselves at the Amen, with no memory at all of what went before. Is that wrong? Is it evil? Would it be better not to pray?

It is not wrong, if such prayer is said from a sense or duty. Swedenborg wrote, I perceived that prayers to the Lord, if made from conscience, as a duty, are they good. (@SE 3126) Nor is such prayer evil if it is done from habit, provided, and that is important:
Provided - that a sense of duty inspires that habit.

But prayer - prayer without thought, or prayer with thought - is evil if it is done for show. As the Lord taught in the. Sermon on the Mount, prayer is evil if it is done to be seen or men.

Evil prayer? In the Psalms it is written, I cried unto God with my mouth. If I had regarded iniquity in my heart, the Lord would not have heard. Yes, prayer can be evil, for, as the Writings teach again and again, mens prayers are such as the men themselves are in their hearts.

Thus we read, Prayers are not from the mouth, but from the heart by the mouth. Mens prayers are such as they themselves are in respect to life. (@AE 225 2-3) Again, The Lord regards nothing else in a man who is in adoration and prayers than his heart, that is, his interiors, such as they are in respect to love and the consequent faith. If, therefore, these interiors of man are not inwardly in adoration and prayers, there is no spiritual life in them. (@AC 10143) Again, What is the prayer of the mouth, if the mind be not in it but babbling? (@AC 1094) And again, Prayers if something is obtained or merited, are not good, yea, are evil. (@SE 3126)

It is the heart, then, (the will and the consequent faith) which determines the nature of every prayer. Prayers can be evil. It is evil if the heart is evil. But it is not necessarily evil to pray without thought, and, as we shall see at another time, the Lord actually makes great use of such prayers. But it is better and of far greater use to pray with thought - true thought of what the prayer really means - for prayer is talk with God together with some internal view of the subject of the prayer.

=== PRAYER II

I Kings 18:21-29

When the Lord was on earth and was teaching men how to pray, He said, When ye pray, use not vain repetitions as the heathen do, for they think that they shall be heard for their much speaking. Be not ye, therefore, like unto them; for your Father knoweth what things ye have need of, before ye ask Him.

A striking instance or the much - speaking of the heathen was told or in the above reading: From morning to evening the prophets of Baal called to their god to send fire from heaven to light their sacrifice. They howled and yelled; they leaped upon Baals altar; they cut themselves with knives, after their manner, until the blood rushed out. But there was neither voice, nor any answer, nor any that had regard. The prophets could not get Baal to answer them, for all their much speaking.

Now, Baal, of course, was no god and could not answer. But in regard to the true God, our heavenly Father, the Lord also taught, Think not that ye shall be heard for your much speaking. Your Father knoweth what things ye have need of, before ye ask Him.

Our prayers, the Writings show, cannot change Gods will or mind or purpose, for God simply cannot change at all. He is infinite. Infinite means without any limits whatsoever. The infinite, therefore, cannot change. God, from eternity to eternity, is always the same. Nothing we say or do can change Gods mind concerning us.

It is not, however, that God ignores our prayers or does not hear them. It is not even that He does not answer them, though frequently the answer is and must be, No. It is simply that our heavenly Father knows, and has always known, what things we really need, what things are necessary to promote our salvation. And since He is interested in our eternal salvation, and in our present lives only in so far as they will affect our eternal salvation, He refuses to answer affirmatively any prayer for a thing which would hurt our salvation. Nothing we say or pray can make Him give us anything else.

We might want riches and pray for them. In His omniscience He might see that riches would lead us to hell. He provides that we shall remain poor, no matter what our prayers to the contrary. We might pray for a certain victory. He might see that victory would make us conceited. He provides that we shall lose. Our prayers cannot change God.

Indeed, it is frequently said in the Writings that any prayers that man concocts from himself - from his own proprial loves and interests - are never heard and received by the Lord. at all. For a prayer to be heard and received and answered affirmatively, it must be from the Lord Himself with man, (A. 10299) In other words, He answers our prayers affirmatively only when we pray for what He wants, only when our desires are His desires, only when the abject for which we pray furthers the end and purpose He has far us.

This, in fact, is the meaning of the words, Anything ye shall ask in My name, believing, that ye shall receive. The name of the Lord is not merely the letters L - O - R - D. It is all we know about Him; it is His quality. When we ask Him for something that is in accord with what we know of Him; when we ask Him in prayer for something that accords with His quality; then our prayer is heard and answered affirmatively.

Think not that ye shall be heard for your much speaking. Your Father knoweth what things ye have need of, before you ask Him. Our prayers cannot change God. Yet it is vitally important that we pray, nevertheless, and the use of prayer we shall consider at another time.

=== PRAYER -- III: WHY PRAY?

Luke 18:18

Our prayers effect no change in God, The Lord has in mind for each of us our eternal welfare. Eternity, to Him, is present and He sees today how far into heaven, or toward it, He can lead us in freedom. This is His purpose in our lives, and nothing can dissuade Him from it. He sees our eternal destiny; he knows what we need to attain it; He provides that for us. Our Father knoweth what things we have need of, before we ask Him. No prayer can make Him give us anything save what will serve His eternal purposes.

Why, then pray? It seems almost useless, perhaps. Yet the Old Testament teaches the duty of prayer. The New Testament teaches it: Men ought always to pray. And the Writings teach it constantly. Frequently, indeed, we cannot help but pray. But why? If our prayers cannot change God, what can they do?

At the baptism of a child the parents are instructed to teach the child the Lord s Prayer in order that he may be introduced into the worship of the Lord as his heavenly Father. That use of prayer continues throughout life. Prayer introduces us into the sphere of worship as we humbly bow ourselves before our God.

More than that, prayer is an acknowledgment that what is good comes from God. It is a useful reminder that if we want what is good - what is genuinely good - we must turn to Him from whom all lasting blessings flow.

But even more important, prayer is necessary that we may appropriate, or make our own, the things the Lord wills to give us. We read in the Apocalypse Revealed, It is usual in all Divine worship that man should first will, desire, and pray., and the Lord then answer, inform, and do; otherwise man does not receive anything Divine. (R 376) In other words, our Father knows what things we need and is ever trying; to give us those things. But that, by itself, is not enough to make us take them. We are beings possessed of rationality and free will, and those two faculties must be consciously turned upward to the Lord before we can receive from the Lord and make our own the Divine things He is seeking to give us.

He wants to give us honesty, let us say. But He cannot make us honest against our wills. If, however, He can lead us to see that hone sty is a good thing; if He can inspire us to desire honesty, to seek it, to pray for it, to work for it, then, when He gives us honesty, we like it and make it our own.

It is for this purpose especially that prayer has been instituted. It prepares us to receive what comes form the Lord. It desires; it makes us anxious and willing; to accept what the Lord wants to give us - those eternal blessings which the Lord cannot give us, unless we turn to Him, ask for them in prayer, and work for them.

Our prayers do not change God. They change us, making us come to want what the Lord wants. That is why it sometimes even seems as if our prayers did change the Lord's will concerning us as when, after much prayer, we finally receive the thing for which we prayed. The Lord did not change. We did. Prayer finally changed us so much, that at last it was good for us to receive the thing for which we prayed - that thing which it would not have been good for us to receive before prayer.

Our prayers do not change God. They change us, for in prayer we can learn to make the Lord's will our own.

=== PRAYER -- IV: FOR WHAT IS IT RIGHT TO PRAY?

Arcana Coelestia 8179

For what is it right to pray? We have seen that the Writings define prayer as talk with God, together with some internal view of the subject of the prayer. Prayer, therefore, must be serious; it cannot be for light and foolish things. We have seen also that our prayers cannot change God, for He is unchangeable, from eternity to eternity the same. He has one purpose in mind for each of us to get us as far into heaven or toward heaven as we in our freedom will permit Him to take us. Nothing we say or pray can swerve Him from the purpose, and He will give us nothing save what will further that purpose. Praying, it follows, is of use primarily to change us so that we will desire what the Lord wills for us. For what, then, is it right to pray? It is right to pray for what the Lord wills. Thy will be done.

But what is the Lord's will? Let us say that we are standing for election to a certain office. Invariably, if we consider the office really important, we will end up praying for victory. Is that right? Yes, for surely we would not be running for office unless we thought it a good thing that we should be elected unless, in other words, we thought it was in accord with the Lord's will that we should win.

Take as another example, a father and a mother whose tiny child lies sick and at the point of death. Every moment the child lives a prayer that the child will recover would fill their hearts. Indeed, they will fall on their knees and with tears will beseech the Lord to spare their child's life. They cannot do otherwise, and it is not wrong, for they cannot but believe that it is the Lord's will that the child should live.

It is right to pray for anything sincerely believed to be the Lord's will, sincerely believed to be good. But all of us are finite human beings, and no finite mind can know with infinite certainty what the Lord's will really is. We run for office and believe that our victory will be in accord with the will of the Lord. The Lord, however, might see that power would eternally corrupt us, or that the victory of our opponent would serve a greater use. Our victory, then, would not be the will of the Lord. We were mistaken in our understanding of His will, as parents, we pray for the life of our child. The Lord, it is conceivable, might see that only if the child grew up in heaven could he be saved. Our child's death would then be the will of the Lord. Again we were mistaken.

It is our duty to try to determine the Lord's will. It is our duty to pray for what we believe to be in accord with His will. But it is also our duty to remember, always, that we can be mistaken. We would not want victory at the cost of eternity in hell. We would not want our child's recovery, if that meant he could not go to heaven. And hence it is that the Writings teach that whenever we pray for what we sincerely believe to be right, we must submit the hearing of our prayer to the Lord, and add to our supplication the further phrase, Nevertheless, not my will, but Thine, O Lord, be done.

=== PRAYER V: PRAYING FOR OTHERS

I Samuel 1:7:1-11

The question is frequently asked, Is it of any use to pray for other people - to pray for their safety, to pray for their success, to pray for their salvation? A fast answer would be, No; a slow answer, thoughtfully considered, would not be, No.

We have seen that it is always right to pray for what is sincerely believed to be good, for what is sincerely believed to be in accord with the Lord's will. If, then, you pray for something for another which you sincerely believe to be good, it is just as right as if you prayed for such a thing for yourself.

But the question remains, Does it do any good?

During the last war many tales were told of how a mothers prayers brought her son home from battle safe and sound. Pretty stories; utterly fallacious. No prayers effect anything by magic, and no mothers prayers ever kept a bullet from hitting her son. Actually, indeed, such stories belittle the Divine majesty of the Lord. What they imply is that the Lord only takes care of those soldiers whose mothers pray for them or takes more and greater care of them than of others, or has to be reminded that He should take care of them. Such prayers have no magical effects at all, though it still is not wrong to make such prayers, hoping they accord with the Lord's will.

It is remotely possible that our prayers for another may have some effect upon the association with him of good spirits and angels, to inspire him with a love of good, and understanding of truth. Yet the reception of that inspiration must always depend upon the mans own free choice, Nothing we can do can destroy or interfere with another's freedom. The Lord, it is said, guards mans freedom; as the apple of His eye. He will not save a man against his freedom, in spite of our prayers. We cannot pray our evil friends and relatives into heaven. Nor will our prayers cause either the Lord or the angels to exert a greater effort in another's behalf. They both always do all they can.

And yet, prayer for another can be efficacious if he knows that he is being prayed for, for he then may think of his well - wishers desires and act accordingly, though that, too, is up to him.

Probably, therefore, the greatest use of prayer for another is one with the use of all prayer: It changes us. If we consider another persons plight seriously enough to pray for him, that prayer may move us to do some actual work for his good. And even beyond. that, in prayer, thinking of the other person, our minds will be opened upward to the Lord, so that He may give us a deeper understanding or what the other person really needs in life, and may inspire us with a better concept of how his eternal good may be achieved.

Tomorrow we shall conclude our talks on prayer with a consideration of a few of the lesser teachings on the subject given in the Writings.

=== PRAYER -- VI: PARTICULARS CONCERNING PRAYER

This morning we conclude our series of talks on prayer with a consideration of certain lesser teachings of the Writings concerning it - the God to whom to pray, and, finally, consideration or prayer without thought.

We pray, of course, to our heavenly Father, the Lord Jesus Christ. One of the great purposes in the incarnation was to show men forever that God is in the human form - to make the Divine Human God visible. During prayer, therefore, it is right to hold in the mind a picture of a human figure - an image of the Lord as a Man. There is, of course, no actual picture or portrait of the Lord. We thus do not need to have in our mind a picture of Him based on any portrait we have seen. But we should, nevertheless, each have in our minds our own individual picture of Him, and it should be the picture of a Man, for that alone is the correspondential image of what He really is - a Divine Human God, because a God of love and wisdom.

And now, finally, a few words concerning prayer without thought. Frequent repetition of the Lord's Prayer almost invariably brings with it a lack of attention to the words of the Prayer, and the Writings have much to say about that. First, they teach that the words of Scripture--(and this includes the Prayer)--the words of Scripture, when present in a mans conscious mind, are actually the basis from which the angels of heaven draw their wisdom and intelligence. In other words, when we read, hear, or recite the words of Scripture, the angels of heaven gain wisdom therefrom. This is especially the case with the repetition of the Lord's Prayer.

But several remarkable statements are made concerning this, namely, that when little children repeat the Lord's Prayer, the angels get more wisdom from it than when it is said by adults; that when adults repeat the Prayer without thought, the angels get more out of it than when it is said by adults with thought; but also that when Swedenborg himself repeated it, the angels got the most of all out or it.

A deeper study of these teachings, however, reveals the following things. 1. When little children say the Prayer, without understanding, but in innocence and aware of its holiness, the angels gain wisdom from it - more wisdom than they can gain when adults say it who misunderstand its meaning. 2. When adults say it without thought - without thinking of their misinterpretation of its meaning - angels gain more wisdom from it than when adults say it, consciously thinking of its misinterpretation. But, 3. When Swedenborg said it, consciously thinking of the true meaning of it that he had learned from heaven, than the angels got he most of all out of it.

It is of use, then, to say the Prayer without thought - not of much use to us, but of use to the angels of heaven. It is better to do that than to think of it and put the wrong meaning into it. But of the greatest use or all is its repetition with conscious thought of its true meaning as that is now revealed in the Writings.

== CHAPTER II

=== WORSHIP

Luke 4:16-22

When the Lord was on earth He said that He had given us an example of what we, too, should do. One of the things He did one of the things it was His custom to do - was to enter into the synagogue and worship. Worship, then, is a thing Divinely commanded, as, indeed, all three parts of the Word - the Old Testament, the New Testament, and the Writings - frequently state.

It is our intention to devote our morning chapel services this week to a consideration of the subject or our morning, worship the place where we worship, the form of our ritual, and the purpose and use of this daily service.

From now on when you enter this room the curtains will already be opened. When the curtains are shut this room is simply an auditorium, and it is proper to use it for any purpose at all. But when the curtains are parted, it becomes our chapel, a house of the Lord, a church, and our conduct here must then be regulated accordingly. In the house of the Lord we do not talk, slouch, push, or pass notes, but rather comport ourselves with dignity and reverence, as we would in the presence of the Lord Himself, shutting from our minds all thoughts of worldly and personal matters, that we may turn our whole heart and mind to the praise and contemplation of our God.

On the valance above the curtains you see the Latin words, _Nunc licet intellectualiter in arcana fidel_ - the words which Swedenborg saw inscribed above the door of a heavenly temple which represented the New Church - Now it is permitted to enter intellectually, into the mysteries of faith. And that is one of the chief uses of all New Church worship - to help us comprehend with the understanding the meaning or the worship of our lives.

In the East, in the very center of the chancel, raised above all else, is the altar on which rests a copy of the Word. All worship, to be genuine, is founded upon the Word, the teachings of the Lord. The Word, then, is the very center of our worship, and is higher, more important, than anything else. And on our chancels the Word is placed in the East, for in heaven the spiritual East, the origin and arising of all things, is the Lord.

But it is the open Word that is the center of our worship, and this is truly significative. The Lord's teachings kept shut up on a bookshelf have never done anyone any good at all. The Word must be opened, studied, understood, applied to life. That is real worship. And even more than this is signified by the opening of the Word in our services. It is an interesting historical fact that at the very first Mew Church service of worship ever held, the leader, Robert Hindmarsh, spontaneously opened the Word at the beginning of the service. The practice has remained with us ever since - the one distinctive ritual of New Church worship. It is most appropriate, for the whole purpose of the revelation the Lord gave at His second advent was to open up the Word in order to show the genuine Divine power and glory within its stories.

Flanking the lord, therefore, is a complete set of the Writings; arranged in chronological order, for it is in the Writings that the Lord has now revealed Himself, and on each volume of the Writings here there is inscribed, in a facsimile or Swedenborg's handwriting, the words which Swedenborg himself wrote upon two copies of the Writings in Holland: Hic Liber est adventus Domini - This book is the advent; of the Lord. (One of those copies has been found, and is now in the British Museum.) Swedenborg said that he wrote the same words on all copies of the Writings in heaven.

Now, it is a peculiar thing that when the Lord was crucified, Pilate, the governor, placed above His cross a sign on which the words, Jesus or Nazareth, the King of the Jews, were written in Hebrew, Greek, and Latin. Jesus the King; Hebrew, Greek, and Latin, The whole of revelation proclaims that the Lord Jesus Christ is our God and King. But that revelation was written in three parts - the Old Testament in Hebrew, the New Testament in Greek, and the Writings in Latin.

In recognition of this certain other features have been incorporated into the decoration of our chancel. On the wall to the North, in Hebrew, we see the Ten Commandments, the very center or the worship or the Jews, and the fundamental rules of life for us today. It is significant that they are on the North, for the Jews were in little spiritual light; and it is significant also that they are commandments, for religion, to the Jew consisted in a rather blind following of Jehovah's commands. On the wall to the South, in Greek, are the words or the Lord's Prayer that prayer which contains the very heart of the religion the Lord revealed on earth, when the real warmth and fire of Divine Love was again made known to mankind. And on the very center of the wall, raised above all else, there is written in Latin those words which the Lord's disciples proclaimed in the spiritual world on the 19th or June in 1770, when the revelation or the Second Advent had been completed - those words of truth toward which all our worship looks; those words of truth which we individually must work to make true in ourselves, The Lord God Jesus Christ doth reign, whose Kingdom shall be for ages of ages.

=== RITUAL -- I

Luke 1:5, 17

Today and tomorrow in our chapel services we shall consider the form or ritual of our worship. Ritual is the external of worship, and the Writings teach that in the New Church there is to be nothing external unless there be an internal within it. Each part of our ritual, therefore, has been incorporated into our services only because it has an internal, a meaning - only because it is significative or something:
of internal worship. But external ritual still has no internal for us, individually, unless we know something of the meaning, the significance, of each act.

In order to be of any eternal value to you, your worship each morning must begin even before you enter this chapel. As with anything important, there must be preparation. You have to prepare yourself for heaven, in order to live a useful and happy life there. You have to prepare yourself for marriage, or you enter it unfit to be a husband or wife, a father or mother. You have to prepare for your job in life. So, too, if your morning worship is going to mean anything, you have to prepare yourself for it.

How? Real preparation for worship comes in your daily life in looking to the Lord for guidance, in shunning your own evils as things against His will, and in being of use and service to others. If you do that, your worship will really mean something to you, and will also be pleasing to the Lord.

But a bit of more formal preparation is also extremely useful. It is impossible to jump all at once from frolicking or fighting to formal worship. Here in school a bell announces the approach of worship. If each of us then turned his thought to preparation for this service - even if only on the way downstairs - our worship would have more meaning. There would be an internal in this external. And the best preparation possible is to practice a bit of self - examination, to see if, in our hearts, we have been harboring aught of distrust of the Divine Providence or ill - will toward our neighbor, for as David the Psalmist truly wrote, If I regard iniquity in my heart, the Lord will not hear me.

The second thing I would speak of in connection with ritual is not used here in chapel, but is rather a feature of our services on Sundays. It is the voluntary or free - will offering. This should always be considered an act of worship - the first formal act of worship each or us makes.

But, you may say, what has money got to do with worship? My pennies and dimes just go to support some minister or other. Yes, it is true that the priesthood is primarily supported by your voluntary offerings. But in the Writings it is taught that the Lord wants a priesthood to exist in order to provide that Divine things may be present with men. Anything you do to carry out the Lord's will is worship in the truest sense. Therefore when you provide that there may be a priesthood to carry out its uses, you are actually engaging in worship. Your free - will offering, then, is an act or worship and should be so regarded. It is not a gift to any man or men. It is the support of a use. It is an offering to the Lord.

=== RITUAL -- II

Psalms 27:1-14

Yesterday we spoke or the preparation that should precede worship a few thoughts, at least, of self - examination and also or the voluntary offering made on Sundays an offering to the Lord. Today we will briefly review the order of our chapel services.

Our worship begins with the singing of an introit - a doxology of praise to the God we have come to worship. The word introit means an entering within. During the introit the congregation and minister together enter with reverence within the sphere of worship.

There follows the opening of the Word - one of the high points or our service. The opened Word gives spiritual enlightenment, and the Lord in His Second Coming opened the Word to our understanding, even as He said, Nunc licet.--Now it is permitted to enter intellectually into the mysteries of faith. ...When the Word is opened you come, more closely, as it were, into the presence or the Lord as now revealed. It is a solemn moment, to be observed with reverence. Some people choose to recognize it by bowing the head, others, by standing at strict attention. Whichever you choose, observe it.

Following a sentence of Scripture, there comes the invitation to prayer. The Lord invites man, never compels him, to conjunction with Himself. Man accepts of his own free will, guided by his rationality.

Then, before the prayer, certain responsives are read by the minister and the congregation, again signifying the mutual action and reaction between the Lord and man.

=== WITH OR AGAINST -- I

Mark 9:40

He that is not against us is on our part.

The Writings teach that anyone in any religion will be saved, if only he live according to what he believes to be true, for the sake of his God or his neighbor. Salvation the right to be happy in heaven to eternity - is not confined to the pitifully few who today make up the Lord's New Church. Heaven would be an awfully lonely, empty place, if that were the case.

Anyone in any religion will be saved, if only he lives according to what he believes to be true for the sake of his God or his neighbor. A
boy might be brought up in such ghastly mental slums that he never realized it was wrong to cheat and swear and lie. He might commit all those evils and more, all his life. But he might also have been taught that it was evil to kill his neighbor, evil even to inflict physical harm upon him. Then if, throughout his life, he refrained from killing, refrained from injuring his neighbor; and if he did this for the sake of whatever god he believed in, or because he loved his neighbor; eventually he would be saved and go to heaven. Oh, he would have a hard time in the world of spirits getting over his evil habits the longer you practice an evil habit, the harder it is to break it but he would be willing to do just that, and at last would conquer them. Why? Because on earth he had loved what he knew to be true, and after death, when he finally learned what really is true, he would love that, too, and would pattern his life according to it. His basic character would not be changed after death, you see: He already loved truth; he would only be perfected in that love.

He that is not against us is on our part. You will often hear it said that the Old Church is dead. That does not mean that every single person in the Old Church is going to hell. Only a little child would believe that. The Old Church is dead, because as churches they do not teach their people the real truth about the Lord, the life after death, the means of regeneration. But inside the Old Churches there are thousands millions, probably ministers and laymen both who are trying to do what is right. From a love of good they live what they believe to be true. All or them will be saved. They are building up within themselves a love or truth, and when they hear the real truth after death, they will accept it, and be regenerated by it, and then they too will enter into heaven. They are not against the truth that the Lord now teaches in the Writings. They have not knowingly rejected it. They are not hateful enemies of the Lord's New Church. Salvation can come to them as well as to us, for he that is not against us is on our part.

=== WITH OR AGAINST -- II

Matthew 12:30

He that is not with Me is against Me.

Yesterday we considered the Lord's words, He that is not against us is on our part, and saw that within them is the teaching that anyone in any religion can be saved, if only he lives according to what he believes to be true, for the sake of his god or his neighbor. Today we would consider another saying of the Lord's, almost the opposite, He that is not with Me is against Me.

Why the difference? Yesterdays reading from the Word told how the disciples had seen a man casting out devils in the Lord's name. He was not one of the disciples. They had Forbidden him to do so. No, the Lord said. Let him. He that is not against us is on our part. He might not have belonged to the Lord's true church; but he was trying to do what was right; he had not knowingly and willfully rejected the Lord. He that is not against us is on our part.

Todays Scripture told a different Story. The Lord Himself was now casting out devils. The Pharisees sneered at Him, said He was a devil Himself. The Pharisees the best educated men in the Jewish Church. They knew who the Lord was, knew what He claimed to be; and knowing this, they rejected Him. It was to them that the Lord replied, He that is not with Me is against Me.

Anyone in any religion can be saved, yes. But anyone in any religion can be condemned, too; and he will be condemned to an eternity in hell if, when he hears the truth and understands it, he turns his back on it. When truth is made the issue, rejection of the truth condemns.

Millions in the Old Church today will never hear the genuine truths now revealed in the Writings until after they die. But all of them will hear it then. They will hear it, too, from teachers better able than yours to explain it clearly and to adapt it to each mans needs. (After all, those angel - teachers have been in that job a few thousand years!)

And what will happen? Some will sneer at it as falsity. Some will be bored. Some will think other things more important. And eventually all of them will wander off - and off - and down - and down - to hell. He that is not with Me is against Me.

But the others-- those who, no matter what their church, had built up within themselves a love of truth? They will stay around and listen to their teachers. They have come to love truth, and now they hear and understand the real truth the same truth you can learn on earth. And because they love truth, they'll pattern their lives according to it, and at last, as genuine Christians, will enter heaven. He that is not against us is on our part.

What, then, is the difference between them and the New Church men and women you can be, here on earth? First, its easier for you than for them. You can learn the truth here and can start now to conquer your evils; they have to wait, and their evils get more deeply embedded. Second, and more important, because you can learn the truth here, you can start out in regeneration early and get well along the way. You, therefore, can be of greater spiritual service to all your fellow men.

The love or truth. It is that alone which saves New Church men or Old. The love or truth. It is. that above everything else which your teachers and ministers here hope to enkindle in your hearts, so that you, as New Church men and women will seek the Lord for yourselves where now He may be found, in the Heavenly Doctrines of the New Jerusalem.

=== THE GREATNESS OF SERVICE

Mark 10:35-45

Several times when He was on earth the Lord told His disciples what they had to do in order to be great, Whosoever will be great among you, let him be your minister, and whosoever will be chief among you, let him be your servant.... He that shall humble himself shall be exalted.... Whosoever of you will be the chiefest, shall be servant or all... He that is least among you all, the same shall be great.

Probably there is not a teenager on earth who does not dream, secretly at least, or his own future, personal greatness. It is right that everyone should. Greatness is much to be desired. How, then, achieve it? The Lord gave the answer: Whosoever will be chief among you, let him be your servant.

But what did the Lord mean? The apostle Paul, the greatest Christian missionary of history, thought he knew the answer. Endless and unstinted labor in the Lord's vineyard would bring him the reward of greatness after death. For years on end he worked, worked hard, in the church, and according to legend, he died in the persecution under Nero. Yes, he thought he knew the answer, and toward the end of his life he wrote to a friend, I have fought a good fight, I have finished my course, I have kept the faith; henceforth there is laid up for me a crown or righteousness, which the Lord, the just judge, shall give me.

Paul wanted greatness; to achieve it, he became servant unto all. But the Writings, unfortunately, leave very little doubt as to Pauls eternal lot. He is not great; he is nothing, He did not even achieve the very lowest reaches of heaven. He put entirely the wrong interpretation on those words of the Lord. Whosoever will be great among you, let him be your servant. And each and every one of us, before regeneration is complete, is prone to do the same: Well work, well serve, well humble ourselves; but boy, wed better get something out of it, and if not here, then hereafter. What? What Paul got?

No, that ifs not what the Lord meant. In fact, He was not then even speaking of how to achieve greatness, but was simply telling His disciples what real greatness is. He was giving definition of greatness. Listen to them. Whosoever will be great among you, let him be your minister and whosoever will be chief among you, let him be your servant.

Greatness is service, the Lord was saying - a life of usefulness to other people, working for them, helping them, doing whatever has to be done in order to help them get along. That's greatnessservice. And therefore, even when we have served others, served them all our lives, we can take no pride in having done it. Rather we must be like those servants of whom the Lord spoke in one or His parables. All day long they had labored in the fields, and when they came in to dinner, what happened? Their master told them to wash up, get his dinner ready, and serve him. More work. That's greatness. That's what the Lord created us for. And at the end of that parable the Lord said, So likewise ye, when ye have done all those things which are commanded you, say, we are unprofitable servants; we have done that which was our duty to do.

Work, service, self - abasement - greatness. The same greatness exactly that the Lord Himself had. The Lord, the only really great Person there is, who has given us an example, that we should do even as He has done. The Lord, the God of heaven and earth, the Son of Man - He came, not to be ministered unto, but to minister and to give His life a ransom for many.

=== THE GREATNESS OF SERVICE B II: AMBITION

Luke 17:7-10; @SE 2796

The Lord's teachings that he who would be great must humble himself, have, over the ages, led many Christians into several kinds of false humility. Many have consciously tried to be servants unto all, in order to achieve great personal glory after death. Others, literally trying to follow a misinterpretation of the Lord's meaning, have piously rested content with the lowest and most menial of all jobs, thinking that God admires the poor and lowly in station, and despises the important and powerful.

Such is not the case. The Lord Himself indicated otherwise when He defined greatness as a life of service to others: Whosoever will be great among you, shall be your minister, and whosoever of you will be the chiefest, shall be servant unto all.

Greatness is service, yes - a life of usefulness to others. But the more people you serve, the more people to whom you are useful, the greater is the greatness, and he who performs a use to all men, the same is the greatest, the chiefest, of all.

The Writings only once use the word ambition, and as we heard in the lesson this morning, they term it an evil thing. It is evil, for it is the desire to do great things to get ahead - for the sake of ones own personal glory, reputation, or wealth. The emphasis in ambition is always on what you can get out of doing great things, rather than what greatness can do. The emphasis is on the doer, rather than on the deed.

But notice exactly what the Writings say about ambition. It is an evil love exciting men to do great things, but the Lord allows it today as a substitute for a good love, the love of the neighbor. It is love to the neighbor which should excite man to do good to others, but where that is absent, the Lord allows ambition to take its place.

And if you still should ask, does the Lord wish man to seek to be important, to seek important work rather than low and mean jobs, the answer is, yes. Whosoever of you will be the chiefest, shall be servant of all. The Lord wishes us to be truly great.

The Writings put it another way, speaking of mans duty of seeking to extend the sphere of his use. He must seek, that is, to be useful to as many people as he can possibly serve, and he must seek to serve them in ways as important as he can possibly manage. It would be ridiculous for a person gifted with great talents in music to shut himself up in a lonely sound - proof cave. It would be ridiculous for a person capable of teaching others a genuine understanding of law to spend his life polishing other peoples shoes. It would be wrong for a man capable of contributing to other peoples eternal welfare to concern himself exclusively with their bodily entertainment.

The truly great man will not consider himself above any job that comes his way in the line of duty. Born to serve, he will cheerfully do whatever has to be done, no matter how low or mean. Should necessity ever really demand it, a truly great President would gladly scrub the White House floors. That is greatness. But it would be insanity and evil for a man really capable of being President purposely to seek to spend his life at menial tasks.

Each of us is born to be of use to others. That is the greatness that is our destiny, Each of us is told of our duty of seeking to extend the sphere of our use, so as to serve as many people as possible in the most important ways open to us. That takes two things, self - searching and determination self - searching to discover our abilities (as well as our limitations), and determination to use our abilities to the greatest possible extent. Only thus can we fulfill the Lord's injunction, whosoever will be great among you, let him be your minister, and whosoever of you be the chiefest, shall be servant of all.

== CHAPTER III

=== KNOWLEDGES AND USES - I: THE KNOWLEDGE OF GOD

Exodus 6:1-15

A persons god is that which he loves more than anything else. A girls god might be her own good looks; a boys his reputation in athletics - two gods that die in a very few years and leave an awful emptiness behind. A mans god might be money - and if money is what he really loves above all else, hell resort to anything to get it, and will try to crush anyone who stands in his way. And many a person has himself for his god - he loves himself, and therefore he loves his evils, too; he cant be, wont be, regenerated.

Its obvious that such gods as these are not enough. Whats needed is genuine understanding of who and what God really is. If we have that knowledge, then we can know exactly what we should love above everything else. We can make that true God our ideal, and strive to live according to His will. And its only that which is going to bring lasting personal happiness, good will among men, and angelic life after death.

Now, there are millions of people on earth, fundamentally good, who want the knowledge of the genuine nature or God. They want to know what God really is like, so they can make that their ideal in life. But in spite of that, there are only a pitifully few thousand who do know what God really is - only a few thousand who even can know while they live here on earth. And of those few thousands, more than a hundred are here in this room - you.

Who are the gods of the worlds one hundred and twenty million people who still believe in primitive religions? Mysterious spirits who rule wind and storm and vegetation - spirits to be feared, fawned at, propitiated with sacrifice. What are the gods of the hundred and fifty million Buddhists? Gods if they can even be so - called - who demand renunciation of every bodily pleasure and or all desire for individuality. Who are the gods of the three hundred million followers of Confucius? Hardly gods at all, for Confucius centered his whole interest in the world - in good government and polite society. Who are the myriad gods of the three hundred and twenty million Hindus? Almost anything and everything, and at the top an unknown infinity into which the just shall be absorbed and first lose their individuality. Who is Allah, god of the four hundred and twenty million Moslems? All - powerful, power unlimited, arbitrarily predestining mans every move and breath, and so far removed from man and mans comprehension that man cannot ever try to understand him.

Who is Jehovah, God of the Jews? Something like our God - a heavenly Father, but a father who plays favorites with His arbitrarily chosen people, and who judges the acts, rather than the hearts, of men. Who is the God of the worlds six hundred million Catholics? At best, a split personality, damning the world, yet loving it; allowing it to be redeemed by the suffering of His infinite Son; allowing His Son to give the power of salvation to mortal priests; allowing human beings to buy their places in heaven with mortal good works. And who is the God of the worlds two hundred million Protestants? That is the saddest of all. They don't know. Something to do with Jesus. Something to do with damning humanity. Something to do with instantaneous salvation. Listen to their prayers on the radio. They pray for anything, for they know not the nature of the God who answers prayers. And Ive even heard some of their leaders say that it is wrong to call God He that makes Him too much like a man. Ive heard their leaders, trying to solve the problem of evil, say that there must be something evil in God Himself - an evil He cant always control.

A few thousand people know, or even can know, who and what God really is. You are part of them. For today it is only in the Writings that the nature of God is revealed in a manner suited to the modern mind. Its only there that God is shown clearly to be a Divine Human Being - a God of infinite love expressing itself in infinite wisdom. Its only there that the Lord Jesus Christ is shown to be the one and only God of heaven and earth, and only there that we can see the inner working of the mind that Jesus Christ built up and glorified on earth - the reasons He did what He did end said what He said - the infinite love and wisdom behind it all. And yet, with all, theres there revealed a God into whose image were created, and in whose pathway we can follow.

To know thee, the one true God, and Jesus Christ whom Thou hast sent - that is lift, life eternal.

=== KNOWLEDGES AND USES - II: KNOWLEDGE OF THE MEANS OF SALVATION

Matthew 16-22

If the purpose of creation is a heaven from the human race, and if heaven is a desirable state of life, it is of obvious importance that we know how to get there, We need a knowledge of the :means of salvation; we need an answer to that question the rich young man asked the Lord, Good Master, what good thing shall I do that I may have eternal life?

Christianity has given two different answers to that question the one Catholic, the other Protestant and both of them are equally wrong and spiritually dangerous.

Throughout the centuries the belief grew up in Catholicism that man, entirely on his own, could do good works, in return for which God would reward him with a place in heaven. Meritorious good works, they were called - a pride paid for salvation.

The great trouble with this doctrine was that it contained the potential for tremendous evil. You do this and you do that, and you have the right to demand something from God. As though God could be bargained with! But worse yet, you do this and you do that, and you're pretty good, aren't you? All by yourself you can do something good enough to get yourself to heaven. Nothing could more effectively build up conceit, the love of self.

The Lord did tell the young man to do something in order to have eternal life, but what did He say before that? There is none good but one, that is, God. That was a truth which Luther saw, and from which he started the Reformation. Only God is good. Man from himself can do nothing at all that is genuinely good. Man can merit nothing by his works.

But then Luther went off into a doctrine of salvation even worse than the Catholics! You can do nothing to save yourself, for nothing you do is good. God must do the whole thing. You cannot even cooperate, for even your cooperation would be evil. Salvation does not come by doing. How, then? Luther ignored all the Lord taught about doing His commandment, and dwelt instead on all the Bible teaches about believing, about faith. Man is saved by faith, and Luther made it read, by faith alone. But note carefully what he meant. Not a faith that comes because of anything you do; that would be doing, again. No, a faith suddenly given you by God, for no reason at all except that God decided to give it to you. It does not matter what kind of life you are leading; God, at His own decision, suddenly breaks through into your life, and gives you a faith that Christ died for your sins. And in that very moment you are saved. Instantaneous salvation by faith alone the doctrine of salvation taught by every Protestant Church there is. It should be obvious what evils and falsities that doctrine can lead to.

The means of salvation revealed in the Writings are entirely different, and ignore neither the teaching that only God is good nor the fact that the Lord everywhere commands the doing of His commandments. Only God is good; man, from himself, is nothing but evils, and from himself cannot do one good thing. But the Lord has provided that something which really is His can be implanted in man in such a way that man feels it to be his, and therefore can act from it as if he acted from himself. From birth onward there are stored up in man things that are really the Lord's - good loves, true ideas; remains, the Writings call them - but so intimately fashioned into mans very life that he feels them as his own and so acts from them just as if he acted from himself.

Each one of you has some love of something good. As far as you are concerned, its a part of your life. You feel it to be your own. But there is none good but one, that is, God. Every good love you have not only is from the Lord in you, but is the Lord's in you. Yet you feel it to be yours, and you act from it as though you acted on your own and from yourself. And that is the means of your salvation to act from the Lord, from the Lord's loves in you, just as if you acted from yourself. You can do it. You do do it, every time you act from any good love at all. And all you need do further to be saved is to acknowledge to yourselves that those good loves are the Lord's and not your own that's so you wont get spiritually conceited and from those good loves then fight against the evils that are in you fight against them in act, in thought, and in intention. The Lord's loves then will grow in you until they push all evil out. The Lord's loves will grow in you until they fill the whole of your being with regenerate life, and you will be saved.

=== KNOWLEDGES AND USES - III: KNOWLEDGE OF LIFE AFTER DEATH

John 14:1-14

In a few weeks we celebrate the one hundred and eighty-eighth anniversary of the establishment or the Lord's New Church. In preparation for that I. am treating in our chapel services this week of various distinctive things about our doctrines for which, I feel, New Churchmen should be especially thankful. You might choose a list different from mine; possibly no two people would ever choose exactly the same things. I have chosen to treat of the knowledge of God, the knowledge of the life after death, the knowledge of the Divine purpose in creation, the knowledge of the means of salvation, and the knowledge of conjugial love.

Death is a thing usually pretty far removed from the minds of young people, so its perhaps hard for you to realize just how fortunate you are to know what you do about the other world. You are so pre - occupied with the joy of living, with the fun of growing up, that you don't spend much or your time thinking about heaven. That's all right.

But there will be times in your lives when death will suddenly be very present. Some one you love very much will suddenly be gone from this earth forever. Most of you here will probably live through the deaths of your fathers and mothers. Some of your best friends will be killed in accidents or in war. Death will suddenly loom on your horizons. And then, possibly more than at any other specific times in your lives, you'll be glad you're New Churchmen.

Or course, its never pleasant to lose a loved one. You can hardly ever be really glad that the Lord has taken some one you love. Death is always hard to face. It hurts, hurts very, very deeply. The bravest of men weep uncontrollably when death hits home. But the attitude of New Churchmen toward death always inwardly, usually outwardly is tremendously different from the attitude of those outside the church, and its different because of our certain knowledge of what life after death is like.

Old Churchmen, when they think from doctrine, either believe in a future earthly life following some distant resurrection or the body, or hold that God intends men on earth to remain in ignorance of the other world. And when Old Churchmen think apart from doctrine, then, even when they guess the truth, they can be certain of absolutely none of their beliefs.

Is there a life after death at all? What is it like? What do you do there? Is it any fun? Do you have to work? Are men still men, and women still women? Many of todays thoughtful Christians have made some pretty shrewd guesses at the answers to those questions, but even when they hit the truth, its still only theory with them, not certain fact. They have no revelation which tells them what the other world is really like. And so, when death hits them, it leaves them not only saddened, but also bewildered. They know not what to think. Its a wonder to me that they can ever face up to death, recover from its shock, and continue to put their trust in God.

For you as New Churchmen the death, even of those you love the most, will be, instead, a thing that builds up your trust and belief in the Lord. Death will hurt when it strikes home at you. But always, inside, you will rest content in your knowledge that death is only the gateway to life, that the parting of death is but that of a few short years, and that the life beyond the grave is beautiful, happy, useful, and truly human. That is your heritage, for you possess a detailed description of the daily life of heaven, written for you by a man who spent twenty-seven years observing it.

=== KNOWLEDGES AND USES - IV: KNOWLEDGE OF THE PURPOSE IN CREATION

Divine Providence 27

Why was I born? That question is more then the cry of a frustrated, selfish brat. Every man who has ever indulged in any philosophical thought at all has asked that question seriously. Why was I born? What is the purpose in existence?

Atheists (men who deny God) and agnostics (those who doubt His existence) have their answers. There is no why; there is no purpose in existence. Existence just happened by chance. No purpose in life; no meaning. What then? One of two choices. Either get as much enjoyment out of life as you possibly can (and who cares how?); or else, live, so as to make worldly society as happy as possible, since that gives you a sense of accomplishment and actually increases Your own happiness, too. Not bad, that latter, except, of course, that man thus puts himself in the place of God, the only source of genuine and eternal happiness.

Roman Catholicism has another answer. God created men so that men could glorify God. That answer tends to promote righteous living: If God wants me to glorify Him, then Id better do what He commands. Or else. That's the rub. That answers promotes fear. But the whole thing is absolutely wrong. What possible glory could God get from men? He is infinite; man is finite. All men put together are still as nothing in comparison with God. He could find no more vain satisfaction from worship offered Him by man than you could find from worship, offered you by an ant.

Protestants, for the most part, have not tried to answer the question, What is the purpose in creation? It is too big a question for their theology. But about eleven years ago a bishop of the Swedish Lutheran Church, Gustave Aulen, gained tremendous fame in church circles when he came up with a partial answer. Its been known from the beginning of Christianity that God is love. The apostle John said that. Bishop Aulen went a bit further. If God is love, then His love could not be satisfied unless it had some one on whom to lavish that love. Bishop Aulen spoke of an inner necessity in God which caused Him to create us.

One hundred and eighty - sight years ago the same thing was written in the True Christian Religion. God is love, and love must have an object; therefore God created us. But TCR went further: Gods love wants our love in return, freely given. And still further: God wants our love only in order that He can make us truly and eternally happy. That is His final purpose in creating us - to make us happy. Or, as it is put in the work on Divine Providence, the purpose in creation is a heaven from the human race.

That's why we were born - so that God could build up a heaven out of the human race. Think of that a bit. A heaven from the human race. A human heaven. A human society in which men figure out for themselves how to be happy by being useful to each other, how to be happy by being good. It has to be that way. Heaven cant be a place where the Lord personally tells you every move you should make. No one would feel like an adult human being in a life like that; no one would be happy. It has to be a lift in which men figure things out for themselves, and so it is. But its not a life without Divine guidance, for then there could be no happiness at all,

And so it, is that the Lord gives men certain very general rules and teachings, and lets them decide for themselves how to apply them to life, lets them decide for themselves, from His teachings, what kind of a heaven they want.

That, then, is why we are born - born to find happiness from the Lord by going to His Word, studying it, and figuring out from it how we can best be useful to our fellow men, and thus build up, both on earth and in the other world, a perfect life.

=== KNOWLEDGES AND USES - V: KNOWLEDGE OF CONJUGIAL LOVE

Matthew 19:1-9

If there is one doctrine for which, above all else, New Church men and women should be thankful, it surely is that which the Lord has revealed in the Writings concerning marriage. Marriage means so much in life. marriage so intimately affects each one of us, even if we remain single; marriage is so definitely the institution in which we personally live out our religion - or our lack or it - that it is truly wonderful that we should have Divine guidance in the subject.

When the Lord was here on earth He could teach but little concerning marriage. Mens ideas of marriage were then so low that He could not even tell them that there was marriage in heaven.

Indeed, there is no marriage in heaven of the nature of their marriages, and they could understand no other kind. but He did lay down strict laws of morality for marriage; He spoke of marriage as a Divine institution; and He compared Himself to a Bridegroom and a Husband - the bridegroom and Husband of the Church.

In spite of such teachings, however, the Catholic Church very soon began to look down on the institution of marriage as definitely inferior to celibacy (celibacy: the unmarried state). Basing its doctrine primarily on the sayings of Paul, Catholicism taught that marriage is a thing the Lord permits to the weak or will, a thing which in itself tends to turn man away from the Lord and make him more selfish. Celibacy was held up as a better way of life, spiritually preferable. Priests and monks and nuns shunned marriage as a thing of evil, end laymen were told that if they married they must pay for it with the bearing of children. What a horrible doctrine! Indeed, in only one thing concerning marriage was Catholicism correct. It insisted that those who married must lead strictly moral lives, and that helped to raise the concept of marriage above what it had been with the Jews.

When Luther started the Reformation he broke entirely from the Roman doctrine or marriage. He went back to those truths that marriage is a Divine institution, those sayings of the Lord in which He compared Himself to the Bridegroom and Husband of the Church. If the Lord had done that, Luther saw, marriage must be essentially a good thing, rather than a thing of evil. It must be of Divine will, rather than or Divine permission. There must, in fact, be something holy about it, even if, as Luther and his Protestants saw it, marriage ended with bodily death. Something holy in the Divine institution of marriage that made possible the revelation of the doctrine of conjugial love.

He who made them at the beginning made them male and female, and said, For this cause shall a man cleave unto his wife. Man and woman each made incomplete, so that each, looking for completion, would look out from himself to someone else. The source of every love we have. Man and woman together, the perfect unit of both earthly and heavenly society. Husband and wife, blessed with the first blessing recorded in the Word:
Be fruitful, and multiply, and replenish the earth, and the heavens. Husband and wife, helping each other toward regeneration, raised up out of themselves by a love of something higher than themselves, raised up out of the word of selfishness that separates their propriums into a perfect and eternal union in the Lord. One in mind, one in life, and one - in body; united in thought and will, in truth and in good; and blessed with all the delights of life, even to the inmost - eternal blessedness. And for those who do not marry on this earth, but to regenerate and hold fast to the true ideals of marriage, the eternal blessedness of conjugial love awaits them after death.

The Lord is good to all, and His tender mercies are over all His works, but we in the New Church have been blessed beyond all measure with the revelation given in the Writings - a revelation of truth that is ours to hold, to study, and to apply to life; pure from all evil and falsity until that day when this knowledge of the Lord and of His ways shall cover the whole earth, even as the waters cover the sea.

=== KNOWLEDGES AND USES - VI: USES ARE THE LORD WITH MAN

Divine Love XIII:1

In the election read from the Writings this morning there is the teaching that uses - the uses men perform for each other - not only are Divine, but actually are the Lord Himself with man. That is a remarkable statement: Uses are the Lord Himself with man. When you perform a use for someone else, the Lord Himself is in your life, working through you to benefit that other person.

The Writings frequently teach that the very being or essence of God is love - infinite and unlimited love. The Lord is love, seeking with all its force and wisdom to make men happy, seeking to serve men in a myriad different ways, so that they will find heavenly and eternal happiness for themselves. That, in fact, is all the Lord is; He is nothing else; infinite love seeking to serve men and make them truly happy.

But God also is omnipotent; He has all power. Theoretically speaking, it would be possible for the Lord to create us in such a way that we would never have to work. Be Himself could feed us, create houses for us create clothes for us and put them on our backs, He Himself could teach us or could create us knowing all we need to know.

Then why didn't He do it? Because His only desire is to make men happy, and only when He can do that can He know any satisfaction or happiness or delight. Only when He is being of use to men can He have happiness, and His only delight is in being of use.

But He wants to make men happy. He wants to give them delight. Well, can you give a person something you yourself do not possess? He wants to give us happiness. The only delight He has is in being or use and service to men. That, therefore, is the only happiness He can give to us - the happiness that comes from being useful to others.

That is why the Lord gives us work to do, uses to perform. It is said in the Arcana that the Lord does good to men through other men through their uses - not because He needs their help - He could do all things by Himself - but in order that men might have something to do and might find happiness in doing it.

In the last analysis, therefore, we do not really perform uses to each other from ourselves; in the last analysis, it is really the Lord who helps others through us. In spite of how hard we may have to figure out how to be of real service to someone; in spite of how much brawn or brains we may put into our work; still, it is the Lord who is working through us. It is He who created our brawn and our brains. It is He who teaches us how to be of use to others. It is He who inspires us with the desire to be useful; or if we are evil, who drives us to work for others, so that we may make money or build up our own reputations. He, through us, performs our uses; He merely lets us cooperate with Him in their performance.

Uses - the uses and services we perform to each other - are the Lord with us. Let us regard them as such.

=== KNOWLEDGES AND USES - VII: USE AND PLEASURE

Heaven and Hell 402

The Lord is use itself, and everything He created was designed to serve some use, some purpose. To discover the Divinely appointed use of a thing is to discover the Lord's will in regard to our use of that thing. To use a thing for the purpose for which the Lord created it is to serve the Lord in our daily lives. It is love to the Lord in the highest sense.

Everything the Lord does is done for use. For example, He gave us our fine bodily senses because of the use that each performs. The sense of taste enables us to feed our bodies and keep them healthy. The sense of sight enables us to develop minds.

But the Lord not only gave us our five senses. To each of our five senses He attached pleasure and delight - great or little according to the use it performs.

Here on earth the eating of food is extremely important and useful. The Lord therefore made the sense of taste extremely delightful. It is wonderful to sit down to a good steak, to eat a delightful dessert, to quaff a cool drink. The sense of taste gives us tremendous delight, and it is right that it should. The Lord made taste delightful because of its use.

But we all now that what is called gluttony is evil. It is evil to eat simply and only for the sake of pleasure with no regard to use. It is evil to eat, as we say, like a pig; or to eat as did the old Romans who gorged themselves on exotic concoctions of peacock tongues - gorged themselves till they made themselves sick, and then came back for more.

That is evil. Anyone knows that. But why is it evil? It is evil because the pleasure of a thing is sought without regard for the use for which the Lord gave that pleasure. And that, in all of life, is the very essence of evil. It ignores or destroys the Lord's purpose in creation.

Consider this in regard to parties. They're fun, and they're supposed to be fun, because they're useful in helping man to relax so that he can do his work better afterwards. That's why the Lord made social life delightful. But to ignore or destroy that purpose brings in the essence of evil. To become nothing but a party boy; to work only so that you can enjoy parties; that is evil.

The Lord also attached great delight to the sense of touch. It is most delightful to kiss and make love to the person you are in love with. The Lord made it delightful because of the use it performs in bringing man and woman into an eternal marriage of love truly conjugial. But again the essence of evil and sin enters when the pleasures of the sense of touch are sought just for their own sake, and not for their Divinely appointed use.

As New Churchmen it is our privilege to see the Lord's purposes in all things of life - to see the Divine use in them. As New Churchmen it is both our privilege and our duty to devote ourselves to that use and to behave accordingly. And when we do that - when we use and enjoy a thing for the purpose for which the Lord created it - then, in our daily lives as men and women, boys and girls, we serve the Lord.

=== KNOWLEDGES AND USES - VIII: SINCERELY, JUSTLY, AND FAITHFULLY

Matthew 25:14-30

Use is the Lord with man. When man becomes regenerated - or, as the Writings also put it, when he is in the Lord and the Lord is in him - he is said to become a form of use. To become a form of use, then, must be the ideal of every New Churchman.

How to attain that ideal. It is not so hard. The Writings say that three things are necessary. First, man must look to the Lord for spiritual guidance. Second, he must shun evils as sins against God - must discover what is evil in himself and then must turn away from that in both mind and body as a thing that is against the will of God. And third, he must perform the duties of his occupation or calling, and must act in all his dealings with others, sincerely, justly and faithfully.

It is about that word sincerely that I wish to speak today. We must perform the duties of our callings, and must act in all our dealings with others, sincerely, justly, and faithfully. (Justly means according to the laws of justice; without cheating; things like that. Faithfully means to the best of your abilities day by day.)

Sincerely. How do we do our work and act with others sincerely? The Writings say that a doctor does his work sincerely if he does it out of regard for the health of the physical body, and that he does it insincerely if he does it for the sake of money or his own reputation. They say a minister does his work sincerely if he does it out of regard for the eternal salvation of mens souls, but that he does it insincerely if for the sake of money or reputation.

In other words, any man does his work sincerely, if he does it for the sake of the use that it performs to other people; he does it insincerely, if he does it only or primarily for the sake of any external advantages it can bring him.

You as students do your studies sincerely if you do them out of regard for the usefulness to others toward which your studies are training you; you do them insincerely if you work at them only for marks, or to appear brighter than another, or just because you have to. You as students are sincere in whats now called student work (and used to be called scholarship) if you set you minds on the good that work does for the school to keep it going, and do your work for that reason, rather than just because you have to, or because its an easy way to pay for your education. You as students in your clubs, in your parties, on your dates and in all your contacts with your fellows can act sincerely if you figure out the real use of what; you're doing, and do it for that reason. And to act sincerely is to do the will of the Lord in your daily lives.

And that is just the point I am trying to make. You, even as students, can live the life that leads to heaven by looking to the Lord for guidance, by shunning your own evils as sins, and by performing the duties of your calling, and acting in all your dealings with others, sincerely, justly, and faithfully.

=== KNOWLEDGES AND USES - IX: USE AND YOUTH

C 129-129

Man is born that he may perform use, and the life of use is the life that leads to heaven. What, then, is use?

First, and most important, it is the sincere, just and faithful performance of the duties of ones employment or occupation.

But speaking more broadly, use may be identified with influence - the influence for good one man has upon another. A womans work might be doing dishes, cooking, making beds, doing the wash. But her influence may be more than all menial tasks put together. She is the greatest inspiration there is in her husbands life. She is the first and most important influence for good in the lives of her children. Active in society, she may be useful in many different feminine ways.

Use, in this latter sense, is more than just work, although it can never be completely separated from work. Always, on earth, the sincere, just and faithful performance of work is the very essential of use.

Then what about you - you students? Infants and children, as long as they are under nurses and masters, do not do the goods of Use. (C 129)
(The Latin word _puer_, here translated children, always included adolescents and youth.) You, as students, are not yet useful and productive members of human society.

Are you, then, denied the right to live the life that leads to heaven? Of course not.

In some ways you are directly of use already. In your life at home you can be of use - dishes, lawn - raking, baby - watching. In any job you may have outside school you are directly of use to society. In your contacts with others - family, friends, mere acquaintances - you can be of tremendous use as a good influence - cheerful, brave, generous, temperate, clean - minded.

But it is primarily in your studies that you too can live the life that leads to heaven. You may not yet be able to do the goods of use, but you can learn to do them, and thus have usefulness to others as the end and purpose motivating your studies. And you are judged according to the motives from which you act. If you study that you may learn to be of use, then, in the Lord's eyes, you are as much a form of use as if you were out in society working. And in Providence this is so, for at your age the human mind is capable of learning much more easily than it can in later years.

To do your studies sincerely - to do them out of regard for the usefulness to society for which they are preparing you; to do them justly - honestly, fairly; to do them faithfully - to the best of your abilities, day by day; that is your use at present. It is in that that regeneration can begin.

== CHAPTER IV

=== THE BOOK OF JUDGES - I

Judges 1:1-7, 9, 17, 19, 21.

For the next few weeks in morning worship we shall be rending selections from the Book of Judges, and, for the most part, passages from the Writings bearing on the material read. Occasionally, however, there will be addresses or talks. Today and tomorrow I shall speak on the Book of Judges in general.

The book contains some wonderful stories - tales of heroes who rose up to deliver Israel from her enemies. We call it one of the historical books or the Word, and are likely to think of it as a mere history of the Jews from the period following Joshua's conquest of Canaan up to the establishment of the kingdom by Saul. To the Jew it was more than that to him it was a prophecy. The Jew celled the books of Joshua, Judges, Samuel, and Kings the former prophets.

The word prophesy really does not mean to forecast the future. Actually it means to speak on behalf of, to speak for - to speak on behalf of God. The prophets of Israel spoke on behalf of God to the people. Once in a while they spoke on behalf of God about the future, and hence the meaning we usually attach to the term. But with this in mind, let us see why the Jews called Joshua, Judges, Samuel, and Kings the former prophets, when we call them the historical books of the Word.

They are history a history of the Jewish people from about 1200 to 600
B. C. But the ancient Jew was not the least bit interested in plain ordinary history as such. He wrote the story of his people, yes, but he did so with a very definite purpose in mind. He wanted to show their history was actually a message from their God, Jehovah. When they obeyed Jehovah, they had peace and prosperity; when they disobeyed Him, they got into trouble and their enemies conquered them.

Over and over again you will hear that theme in the book of Judges. Israel sinned; an enemy conquered them; they repented and called to the Lord for help; the Lord raised up a judge, a great leader, to overthrow the oppressor.

That is why they called their history prophecy. It was a message from their God; it spoke for or on behalf of Jehovah. And they called these particular books of their history the former prophets, because much later in their story there arose a remarkable series of men who laid claim to speak for Jehovah in a very particular was Elijah, Amos, Isaiah, Daniel, Malachi, etc. These were the latter prophets, Joshua, Judges, Samuel, and Kings were the former prophets the former message from their God.

In the introductory lesson read from Judges this morning we heard how, after the death of their leader, Joshua, the tribes of Israel completed their conquest of Canaan. One tribe helped the other conquer one enemy after another - Canaanites, Perizites, Zidonians, etc. But one horribly important thing should be observed - either because they were plain, ordinary tired of fighting, or because they were not strong enough to win, all the tribes of Israel allowed remnants of their enemies to, survive in the land. That would mean trouble - trouble just as certain as if you decided to stop telling lies, except on one particular day or each week.

=== THE BOOK OF JUDGES - II

Judges 2:7-23

In the days of Moses and of his successor, Joshua, the Lord performed so many manifest miracles that even the stiff - necked Israelites were convinced that Jehovah was a God of power, whose word they had better obey. The plagues in Egypt, the crossing of the Red Sea, the daily manna the water out of the rock, the Ark parting the River Jordan, the fall of the walls of Jericho - these and many more were enough to make Israel believe that Jehovah was really an unusual Being. They were enough to inspire Israel to conquer Canaan in His name. Ruthlessly the Israelites slaughtered almost every enemy they came across. Almost all - but not all. Here and there throughout the - land they left remnants or the enemies of the Lord - remnants who would increase and multiply and cause them trouble.

The tribes of Israel had fought together, close - knit, as they conquered Canaan, but now a new phase of their life was beginning, and it is this which is described in the Book of Judges. They were comparatively small tribes, and the land was comparatively large. Tribe separated from tribe. They wandered away from each other, and there was little communication between them as they began to settle in their new homes, planting their farms and building their cities. There was no feeling or national unity at all. On occasions there was even civil war between the tribes.

It is important to know this if we would understand the Book of Judges. Almost none of its stories concerns the nation as a whole. Rather is judges a collection of various unrelated tales, dealing now with this tribe, now with that. In one section of the land trouble descended upon the Israelites - an enemy conquered them. A judge, a leader, arose and liberated them. And then the book moves on, years later, to another section of the land. The stories, we say, are unrelated, and so they are, but the writer of the book unifies them all with that ever - recurring theme: Israel sinned by turning away from the worship of the Lord; the Lord allowed an enemy to conquer them; in trouble, Israel repented and called to the Lord for help; the Lord raised up a judge, so celled, to help them; worship of the Lord continued pure for a while thereafter.

It was a wonderful, but a very wild land that Israel had conquered. Before the centuries saw it stripped or its trees, it was rich and fertile, a land flowing with milk and honey. But native to the land when Israel got there were some of the most perverted forms of worship that have ever existed. Human sacrifice was practiced near the village or Jerusalem babies were thrown into a fire that burned in the belly of a brazen bull, tended by profane priestesses. And all throughout the land were many other Baals gods each claiming his local devotees. Usually their worship was connected with the cycle of winter and summer, but almost always their worship involved the grossest immoralities. And without fail such worship exerted a peculiar, apparently irresistible attraction upon the Jews.

If there is any single moral lesson that the Book of Judges has for us it is probably this. When you are trying to conquer your evils, the enemies that would keep you from your promised land, heaven, DO IT. Be ruthless with your evils. Slaughter them. Don't toy with them; don't temporize; don't think you can keep them under control. You cant. They'll get the best of you. They'll grow in you - grow and multiply - and as surely as night follows day, you will be the loser.

=== THE BOOK OF JUDGES - III: THE STORY OF GIDEON (1)

Judges 6:25-32

In the period of history recounted in the Book of Judges covering, roughly, the one hundred and fifty years from 1200 to 1050 B, C.--there was practically no monotheism anywhere on the earth. (Monotheism is the belief that there is one, and only one, God.)

Mans original religion had been monotheistic. The men of the Most Ancient Church, represented by Adam, had known front revelation that there was but one God, and that He was Divinely Human - Jehovah. As those first men became more worldly, however, they began to make images and pictures of the different things they knew about Jehovah - a statue of a man with wings on his feet, to remind them that God could be everywhere at once; a statue or a strong; young man, to remind them of Gods power, His omnipotence. And, later, as men became evil, they began to worship these things as different gods in themselves. Polytheism - the belief that there are many gods - arose.

It was necessary, then, for the Lord to start men back on the road to true religion, so that when God Himself should be born on earth, they could understand that it was not one god of many, but the one and only God who had all power in heaven and on earth. To do this, He began to raise up a special church among the Jews.

For centuries the Jews had been slaves in Egypt and had absorbed Egypt's polytheism. At last, out or a burning bush, Jehovah spoke to Moses and proclaimed Himself to be the god worshiped by the ancient Jews. Moses got his people to accept that teaching, and behind the banner of Jehovah, as it were, they marched out of Egypt. Yet two things should be noted. First, they knew that they were supposed to worship the Lord, Jehovah, a god powerful enough to do great miracles. Second, it apparently never even dawned on them that Jehovah was anything but their special god, one god among many, many others.

That was their belief in the days of the Judges. It would be another three centuries before one of their prophets, Amos, could first reveal that Jehovah was the god or other nations than their own. And it would be another three centuries after that before they would understand that they could worship the Lord outside the Land of Canaan, and that their god, in fact, was the only God of ail the earth.

The Jews came into Canaan worshiping Jehovah. But the people they met up with all had gods of their own - a god who ruled this valley, a god who ruled that hill. Baals, these people called their gods gods, they said, who brought them prosperity. So, said the Jews, all right, Jehovah brought us up from Egypt, led us through the desert, conquered this land for us. We will go on worshiping Him. But just to be an the safe side, why not also worship the gods of the land where we are growing our wheat and grapes? They did - and usually the worship or Jehovah was forgotten in the process.

So it was in the days of Gideon. His father, Joash, worshiped the local Baal. He also worshiped some other god whose name we do not know - some god worshiped in a grove of trees. Gideon, at the Lord's command, broke down his fathers altar to Baal one night, cut down the grove dedicated to the other god, and built instead an altar to the Lord and offered sacrifice thereon. Next morning the men of the city, discovering what Gideon had done, said to Joash, Bring out thy son, that he may die. But Joash stood up for his son, who had thus reinstituted the worship or the Lord. Baal? he asked. Does he need men to plead for him? Does he need men to save him? If he is really a god, why does he not do something to save himself? Let Baal plead his own cause. But the Baal did nothing, Baal, after all, was not much of a god.

=== THE BOOK OF JUDGES - IV: THE STORY OF GIDEON (2)

Judges 6:33-40

Gideon had broken down his fathers altar to Baal and had destroyed the grove that stood by it. Infuriated, the local worshipers of Baal had demanded Gideon's life. But Joash, his father, stood up for his son and said, Does Baal need men: to plead for him? Let Baal plead for himself. And from that day on, Gideon was nicknamed Jerubbaal, a Hebrew name meaning Let Baal plead.

Frequently, to arrive at the genuine internal sense or the Word, its stories must be inverted, the Writings say. An evil must be understood as representing something good. Thus Solomon's sin in marrying a thousand wives represents the Lord's Divine love going forth to the many different churches and peoples of the earth. Similarly, in the story just referred to, we must invert it to derive any moral teaching from it. Let Baal plead for himself. Baal, the false god, inverted, represents the truth. Let the truth plead for itself.

Occasionally, both in youth and in adult life, each or us gets a new idea of what is true or right, a new idea or how something ought to be done. We tell it to others. No one accepts it. Our idea, they say, is completely and totally wrong. We are utterly certain it is correct. What then? Shall we keep on pushing it, until everybody is tired of hearing it and is afraid to see us come around? No. Let the truth speak for itself. If what we have said is wrong, we would not really want other people to accept it. And if what we have said is true, but other people are not yet ready to see it, we need not worry. We have stated the truth. From then on the truth will plead for itself. Eventually, even if not right now, the Lord will be able to get others to see it.

Gideon had received divine command to lead Israel to victory over the Midianites. At the Lord's command he had cast down the altar of Baal, and Baal had not defended himself. And now war was immediately ahead of him. He was afraid - afraid to go out without divine help. And as yet he did not know much about the Lord. Was He really a god powerful enough to give him victory? Gideon wanted a sign. And the Lord gave him two signs dew on a piece of fleece, but not on the ground around it; dew on the ground, but not on the fleece upon it. Gideon went off to war.

A sign that the Lord has power. A sign that the Lord exists. The Israelites often sought such signs, and often the Lord gave them. But when the Lord Himself was born on earth and was raising men further up the road to truth, He refused to give unbelievers any sign at all. A
wicked and adulterous generation seeketh after a signs. He said,

A sign that God exists, A sign that the Lord has power. What sign do you need, in order to believe? What sign is there? Is there any? Christians have argued these questions for centuries. One sign they have come up with is the argument that everything has to have a cause. Any rational man will agree with that. Well, some thing, some one had to cause creation God, Again they point to the wonderful order so evident everywhere in nature and in the human body. Who but a god of wisdom could be responsible for that? And who but a god or kindness and or love could give us beauty and the ability to appreciate it? These, and other such things, are their signs today. They are good signs, too,

But think a bit. Good as these signs are, they do not really prove anything at all. An atheist knows all these arguments, and simply denies them, so that he can deny God, too. Really, there is no proof of God at all, and no good man needs any proof. It is a wicked and adulterous generation that demands a proof. But in the inmost heart of every good man there is that which is sufficient to make him see that God exists the desire to believe, a love which asks no proof and needs none, is and finds its own proof, and sees the truth because it wants to.

=== THE BOOK OF JUDGES - V: THE STORY OF GIDEON (3)

Judges 7:1-8

Sure, now, that the Lord would help him in battle Gideon - Jerubbaal - set off to fight the Midianites. An army of thirty-two thousand men marched with him. Too many, the Lord told him. If an army that big conquers Midian, they will think they won without divine help. Send home any who are afraid. Twenty - two thousand men went home.

The people are yet too many, the Lord told him. Bring them down to this water and there divide them into two groups. Gideon marched his soldiers to the water. All were thirsty, all wanted to drink. Some - the great majority - got down on their hands and knees to drink. But a few others, it is said, lapped of the water with the tongue, as a dog lappeth, putting the hand to the mouth.

The merely natural meaning here is at first obscure. The soldiers who got down on their hands and knees and sucked up the water with their mouths were not the ones who lapped like dogs. The ones who scooped up water with their hands and put their hands to their mouths were the ones who lapped like dogs.

Only a hunter could immediately understand this. When a hunting dog is following a scent, he stops for nothing. If he comes to a little stream and is thirsty, he drinks, but he does not stop to do it. He drinks, still on the run, lapping up the water as he goes.

This is the meaning here. Gideon's men were off to battle. They came to a stream and were thirsty. For most, the battle could await their personal satisfaction. But a few of them, just three hundred exactly wanted to join the battle at once to conquer Midian. They thirsted too, a, they came to the stream, but they did not stop to drink. Like thirsty dogs, they drank on the run. They waded into the stream and scooped up handfuls of water as they crossed.

Three hundred men. This was all the Lord, allowed Gideon for an army. With these three hundred he must attack the Midianites, who lay along the valley, as grasshoppers for multitude. And with these three hundred, Gideon went off. They had victuals with them, and each of them had a trumpet, and, we find later, some sort of a jug. They would not need much else,

Those who lapped of the water like dogs on the run would deliver Israel from her enemies. Water represents truth. Eagerly lapping of it like a dog signifies eagerness to learn truth for the sake of the uses of life, And it is only men who have such eagerness, such an appetite, who can strengthen the church. It is only those who have such appetite who will succeed in conquering their own evils, their spiritual enemies. For others, the battles of spiritual life can await their personal satisfaction.

But such appetite for truth, the Writings say, is not inborn in anyone. It is an acquired taste, an acquired thing, and it is acquired in exactly the same way that a taste for a bodily food is acquired. We do not like a certain food, but know that it is very healthful. We force ourselves to eat it. At length it no longer tastes quite so bad. Then it begins to taste good. At last we like it a lot.

So it is with a taste, an appetite, for truth. It can be acquired, though it takes time, patience, and perseverance. And only he who thirsts for truth as a panting dog thirsts for water will save the church at large or the church in himself, from her spiritual enemies.

=== THE BOOK OF JUDGES - VI: THE STORY OF GIDEON (4)

Judges 8:22-35

Gideon had conquered Israels oppressors, the Midianites, and in gratitude the Israelites had offered him and his family kingship over them. But Gideon refused: I will not rule over you, neither shall my son rule over you: the Lord shall rule over you.

But so low was the state of religion in Israel at that time that not even Gideon knew what those words implied, even though with his own eyes he had seen miracles wrought by the Lord. I will not rule over you, he said, but give me the golden earrings you have taken from the slaughtered Midianites. About seventy pounds of gold was laid at his feet, and out or it Gideon made some sort of a statue or image to some unnamed god, and set it up in his city. He worshiped it himself, and many others in Israel came and worshiped it also, adding this too to their worship of the Lord.

Polytheism again, the worship of many gods. For centuries still to come, polytheism would attract Israel almost as irresistibly as a flame attracts a moth.

We today look back at ancient polytheists and say, What fools! Who but a fool could think that there was one god of love, another of wisdom; one god of the mountains, another of the sea? We today know that God is infinite and therefore cannot be divided. God is one. We would never worship many gods.

Or would we? In fact, do we? Polytheism, unfortunately, is just as attractive to us as it was to the ancient Israelites, and we frequently indulge in its worship, even though we do not use images and statuses in it.

God is one, the Writings say, for God is infinite, totally unbounded, and the infinite cannot be divided. But God is absolutely one, and in Him all tings are absolutely one, even if we in our speech distinguish between the things in God as though they were actually different one from another. We have to do that in order to think of them or talk of them at all.

God is love, and God is also wisdom. God is mercy, but God is also justice. We speak like that, and what we speak is true. But Gods love and His wisdom are actually exactly the same thing. They are a one. Gods mercy and Gods justice are also a one, and, in fact, the same one. There is no love in God which is not also wisdom; there is no wisdom in God which is not also love. There is no divine mercy which is not justice; there is no divine mercy which is not justice; there is no divine justice which is not also mercy. Gods divine love is so great that by itself it would give the greatest happiness of heaven to everyone. But Gods divine wisdom sees that this simply would be more than most people could bear. So God in His mercy justly provides that each person shall receive as much of true happiness as he can freely take.

And now, where does todays polytheism come in? It enters when we pray for one thing we know to be in God and ignore the fact that it is one with all others. Caught in an evil, we pray for mercy, ignoring the fact that there is no mercy which is not also justice, for we would escape the just consequences of our evil act. Seeing an evil habit in ourselves and knowing that that habit can lead us to hell, we weakly appeal to Gods mercy to take our love of that habit out of us overnight, as it were; and we ignore the fact that Gods wisdom has given us the means to remove that habit from ourselves in the one way that it can be removed.

That is todays polytheism - to appeal to one distinct thing in God as though it were the only thing in God or as though it were a god in itself. Polytheism it is. It needs no images or statues. Without them it constantly attracts us today, even as when it had its images and idols and led Gideon and Israel away from the genuine worship of the Lord.

=== THE BOOK OF JUDGES - VII: ABIMELECH

Judges 9:1-57

The ninth chapter of the Book of Judges recounts the treachery of Abimelech, son of Gideon. Gideon had many wives and seventy legitimate sons. The wives were Israelites, as was Gideon himself, for the Lord had forbidden the Israelites to marry outside their church.

But still living in the land in the days of the Judges were remnants or the heathen Canaanites, and one of their strongholds was the city of Shechem in west - central Palestine. Gideon had taken to himself a woman from that city to be, not his wife that was impossible, for she was heathen but his concubine, and to them also was born a son, Abimelech.

After Gideon had defeated the Midianites, the Jews, in gratitude, offered to make him their king him, and his sons after him, Gideon refused, saying, The Lord shall rule over you.

There the matter should have ended. But after Gideon's death, Abimelech, half - breed that he was and of lowly birth, kept thinking of that offer of royalty and began to plot to establish himself as king. He went to Shechem, his mothers city, and spoke to his Canaanitish relatives there. Look, he said, do you want to be ruled over by Gideon's seventy sons Jews, foreigners, your conquerors? Would it not be better to have just one man be your king, a man of your own flesh and blood?

It worked. The men of Shechem took money from the temple of their Baal and gave it to Abimelech, and with it Abimelech hired a band of villains to follow him. In Ophrah they seized Gideon's seventy sons and killed them - all but one, Jotham, who had managed to hide. And Abimelech was now crowned king, at least or the cities of Shechem and Millo.

If there is any moral lesson to be learned from this mornings reading, it is in connection with Abimelech's words to the men or Shechem, would you rather be ruled over by Gideon's seventy sons, or by one who is your brother? Nowhere is there any indication at all that Gideon's other. sons wanted the kingship, any more than Gideon himself had wanted it. But Abimelech coveted the rule, and a man of evil loves suspects all others of having the same evil loves. The covetous Abimelech suspected his brothers of being covetous, too.

As the jaundiced eye sees all things yellow, the evil eye sees all men evil. All too often when we suspect other peoples motives, we do so because our own motives are open to suspicion. The good man consciously looks for what is good in others. He takes it for granted that others are good and trustworthy, and if he is forced to see an evil in another, he tries to excuse it and to put a good interpretation on it. Not so the evil, He delights in discovering and publishing the evils of others, and where no evil is apparent he makes it up, accusing others of the same evil motives which he has himself. It is a sorry lot, the lot of hell.

=== THE BOOK OF JUDGES - VIII: JEPHTHA (1)

Judges 11:1-11

Today we read from the Book of Judges the introduction to what is undoubtedly the saddest story in the whole of the Word the story of Jephtha, a man who make a promise that he did not understand, but who kept his promise because he had made it to the Lord.

The story of Jephtha, however, brings up a whole host of serious moral problems, mainly but not exclusively - having to do with the nature of a promise. This week, as the story builds up to its horrifying conclusion, it would be well if you seriously considered the making of a promise. What is a promise? Should you ever make any promise at all? Should you promise something you don't realize the full implications of? Is a promise so important that you have to keep it, even though keeping it means that you must do something wrong?

Those are the chief moral problems raised by the story of Jephtha, but there is a lot else that is provocative of thought in the story, too. Can you bargain with God, for example? Can you say, Ill do this, if Thou, O God, will do that? That is what Jephtha tried to do - and the misery it brought him was more than a normal human being could endure. What was still the state of religion with the Jews at this time? And how can we Americans justify our seizure of this country from the Indians? And why did every Jewish wife want a large family?

But most important of all, perhaps, is the subject treated of in our reading from the Word today. The Jews had sinned, and they knew it. They had left the worship of Jehovah for the worship of the local Baals of Canaan. Their divine protection, therefore, had vanished, and once again they had been conquered by their enemies. They prayed for help from Jehovah. First He refused their plea; eventually He would heed it.

Forgiveness is what they wanted - forgiveness for their sins. And what does each of us want? The same thing - forgiveness. But what do the Writings teach about forgiveness? The Lord not only is always willing to forgive, but is anxious to. Forgiveness, on the Lord's part, means sending back to hell the devils who inspire us with our evil loves. Do we really want that? Do we really want the Lord to remove from us all our loves that are selfish and worldly and bodily and impure? If the Lord really forgave our sins, we wouldn't love any of those things any more. Is that what we really mean?--for that is what the Lord was warning when He told Israel to go back and worship her other gods. Is that what we really mean when we say, each day, Forgive us our debts?

It can be.

=== THE BOOK OF JUDGES - IX: JEPHTHA (2)

Judges 11:12-28

The lesson read from Judges this morning consists chiefly of a long historical statement whereby Jephtha sought to justify Israels conquest of Canaan, and thus to forestall war between his nation and the invading Ammonites. His appeal fell on deaf ears, even as appeals for peace usually do where a nation is determined on war.

Down in Egypt Moses had been commanded by the Lord to lead the Hebrew people out of their slavery and up into Canaan, there to establish their church. He and his army approached the southern borders of Canaan on the far side of the River Jordan from here what the Old Testament calls the other side Jordan. They did not want this land for themselves - this side Jordan was their promised land. They asked the king of this land Edom, it was - for permission to cross his territory toward their ultimate destination. He refused, so they circumnavigated his land and came to the next kingdom to the North - the land of the Amorites - whence they could push straight west to Jordan.

They asked the king of the Amorites for permission to cross his territory. He not only also refused, he came out with an army and fought against Israel. Israel won, claimed his land by right or conquest, and said that the Lord had given it into their hands. They took the land, some of them settled there, and the rest crossed over to this side Jordan, and under Joshua conquered it, too.

And now, three hundred years later, the Ammonites, descendants of the Amorites, came with their armies to take back the land of their ancestors. Why did you not speak years and years ago? Jephtha asked. For three centuries no one said anything. Now you suddenly appear, demanding redress for the wrong you think you suffer. (Even if justice had been on the side of the Ammonites, where could the Jews go now? Where would we go now should we give this land back to its original inhabitants? We have no other home.)

And then Jephtha appealed to Divine intervention as justification for Israels possession of the land of the Amorite - Ammonites. We did not seek war. Your ancestors forced war upon us. Our God, Jehovah, gave us the victory, gave us this land. Why do you not rest content in the land which your god, Chemosh, gave to you? (Was there a hint of polytheism here?--probably.) But Jephtha's plea was ignored. Battle was about to be joined.

There are at least three moral lessons to be learned from this story.

First, when a nation thinks its god is favor of its conquests, war is practically inevitable.

Second, there are some wrongs which can never be righted. However much it must have been a permission of Providence, allowed for the sake of the greater ultimate good, that the white man could dispossess the Indian from his lands; however much that may have been a wrong far wars of aggression cannot be justified - still it is a thing which cannot be righted. We cannot return to any mythical homeland; this is our homeland, now. Some wrongs can never be righted; they can only be atoned for, to the best of our abilities. (And so it is with many of our own private evils and sins.)

And thirdly and most, important to an understanding of the long, historical sweep of religion it should be remembered that many of the things told of in connection with the Israelites were applicable only to that people in that day. The Lord did want the Jews to possess the Land of Canaan, so that they could there set up a church whose ritual would be representative of true religion. The Lord did command the Jews to conquer Canaan. But the morality which apparently was Divinely sanctioned with the Jews is not. to constitute morality with us. Our faith and our morality is to be based upon the Writings.

=== THE BOOK OF JUDGES: - X: SHIBBOLETH

Judges 12:1-7, E 102:2

After the battle was over the people of Ephraim - one of the tribes of Israel - came and threatened Jephtha's life because he had beaten the Ammonites without their help. Now that the battle was won, they wanted to share in the glory.

It was a ridiculous threat. Jephtha had called all Israel to help him. The cowardly Ephraimites had stayed home as long as there was danger facing them.

Jephtha lost his patience. He and his army turned on the Ephraimites, fought them, and beat them, and then, to prevent any escaping alive, he took the fords of Jordan, which the Ephraimites had to dress to gel; home, and barricaded them. To anyone who came to cross the fords or Jordan a simple demand was put. Say the password-- the first record of a password in history. Say Shibboleth. Most people could, but the Ephraimites could not. The Ephraimite tried to say. Shibboleth, and said Sibboleth instead. His speech betrayed him. Jephtha took him and slew him.

Their speech betrayed them, and even hereon earth our speech sometimes betrays us; it reveals our character. Observe another's conversation ford while. What does he apparently like to talk about?--himself, light and silly things, things that are evil and wrong? His speech betrays him. What do you yourself like to talk about? Often on earth - but not infallibly - your speech betrays you.

But after death this is absolutely the case. In the other world no names of earthly language are ever spoken. Not even the names Jesus Christ, are used to designate God, but each man has his own name for God, exactly corresponding to his own individual beliefs concerning God and revealing what he thinks of God. He can say no other name. Who is the God of this kingdom you would enter? You may be asked same years from now. What will the answer be? Say Shibboleth - Sibboleth.

=== THE BOOK OF JUDGES - XI: HAIR

Judges 13:1-8

We began to read today the last story we shall read from the Book of Judges the wonderful tale of Samson and his one - man crusade against Israels newest enemy, the Philistines - sea - rovers from the islands of the Aegean Sea who began to push east into Palestine some time around 1100 B.C.

Two things read from the story so far should be noted. Manoah's wife saw and heard an angel, but had no idea at all that it was an angel. Manoah's child was to be a Nazarite, and therefore was never to cut - his hair.

Protestant theologians unanimously conclude that the reason Manoah's wife did not know she saw an angel was that the angel had put on a disguise. The same was the case, they say, with Abraham and Gideon. We, of course, know differently. Angels are men, and therefore they look like men - not like spooks and ghosts. The men of the Most Ancient Church talked with angels constantly, and only knew it was not men on earth they spoke with if the angels suddenly disappeared, or some such thing.

And now for Samson's being a Nazarite, the sign of which was that he was never to cut his hair. (Such was also the case with John the Baptist.)
We all know well the story of how Samson's strength was in his hair. When his hair was long, he was strong. When his hair was cut off, he was easily captured. When his hair grew back he grew strong again. But why? What is the significance, the spiritual meaning, of hair? Why is hair so frequently mentioned in the Word, and why are such strange stories told about it? (Some children, for example, once called Elisha the prophet a baldhead. Elisha cursed them, and immediately forty-two of the children were devoured by bears.) Why?

Hair, very obviously, is part of the living human body. It is classified as bone, and our bones have to do with the structure and form of our bodies. And hair, though alive, is not very, very much alive it has very little life in it in its use as the very outermost covering of the body.

It is on those facts that the spiritual significance of hair is based. Alive, but not very much alive. Bone and therefore having to do with structure and form. An outermost covering. Hair, therefore, is said to signify such literal truth as is found in the stories, in the plain, simple teachings of revelation. Hair, the Writings frequently state, signifies ultimate truth.

Why, now, was Samson strong when he had hair, weak when his hair was shorn? To illustrate this, take the fifth commandment, Thou shalt not kill. In its inmost or celestial sense, this means that we may not hate the Lord. In its internal or spiritual sense it means that we may not destroy another's faith, another's religion. In its literal, ultimate sense it means we may not kill another human being, injure him, hate him, or destroy his reputation.

Let us pretend, now, that we decide to obey this commandment as to its internal meanings only. We will not go around hating the Lord. We will not destroy another mans religion. But hate our neighbor? Why, of course; hate him. We will revel in hating him. We will injure him when possible, and would gladly kill him, if we could be away with it. And as for destroying his reputation - what could be more delightful?

It is as clear as day that in such case the fifth commandment has no real strength with us at all. The internal may indeed be the most important thing. The external may be only its covering, comparatively lifeless as far as religion goes (for an utterly irreligious person may also abstain from murder and slander.) But unless we obey the teachings of the Word in their ultimate form, their ultimate form, their literal meaning, nothing in the Word has any real power in us at all.

The hair signifies such ultimate, literal truth. Hence it was that Samson, who typified the power of the Word, was strong when his hair was long, powerless when his hair was shorn off.

=== THE BOOK OF JUDGES - XII: Samson's INSTABILITY

Judges 14:10-20

The wonderful story of Samson paints a picture of a very strange and inconsistent character. He was a man of terrific strength. With his bare hands he killed a lion. He walked off with a weavers beam braided into his hair. He tore the gates off a city's walls and carried them away into the hills. But he was also obdurate, stubborn, at times completely foolish, and was always getting himself into trouble. Against the will of his parents and the laws of his Church, he married a woman of the Philistines. Constantly he got into trouble with women, and even when he plainly saw that he woman Delilah was out to have him killed, he could not resist her physical charms and came back to her again and again.

So far in the story we have read how, on one of his early visits to the Philistine woman, he had killed the lion, and how, some time later, he had found bees and honey in the lions carcass. He kept that a secret. Today we read the story of his marriage feast - a marriage which was never consummated. Interesting marriage customs are revealed here. The bridegroom, even then, had a best man. For seven days he put on a marriage feast and at the end of seven days he took the woman home to be his wife. Only Samson never did. She had betrayed his riddle. He had lost his bet. He killed enough Philistines to pay his debt and then went home in anger. His bride was at once married off to the friend who had served as best man.

A mighty hero - and a very foolish man. But it should be carefully noted in the story that Samson was the hero when the spirit of the Lord came upon him; foolish, when he acted on his own, without Divine instruction. This is most important to an understanding of the spiritual sense. For Samson, we are told, represents the Word in its letter the Word such as we have it in the stories of the Old and New Testament. It is here that there is strength and power against evil that, we have already seen. That is why Samson was strong. But Samson did what was right only when under Divine guidance; he did what was wrong when he acted on his own. And the stories of the letter of the Word give us spiritual strength when we are led to a proper understanding of them by the Lord; they can get us into serious trouble when we try to interpret them on our own, without the guidance of the spiritual sense.

What, for example, does the letter teach about the Divinity of Jesus Christ? If you just stuck to the letter and tried to interpret it on your own, you might come up with this answer - millions of people have - that it teaches that Christ is the Son of God, that He said prayers to God the Father, and asked Him to send the Holy Spirit. Three separate Gods - foolishness, trouble. But under the Divine guidance given in the revelation of the spiritual sense, you discover that such passages are written according to the appearance and must be interpreted in the light of other passages, in which the spiritual sense is clear I and the Father are one; he that hath seen Me hath seen the Father; the Son of God who would be born would be God Himself, the Father from eternity.

In the letter of revelation there is spiritual strength when it is interpreted and understood according to Divine guidance. To the New Church such guidance has been given in the Writings.

=== THE BOOK OF JUDGES - XIII: THE PHILISTINES

Judges 15:9-20

One of the most common temptations to come upon New Churchmen as they grow up and enter more deeply into the mysteries of faith, is to believe that the whole of religion consists in knowing and understanding the tenets or their faith. If you can give a rational explanation of the Trinity, showing that the whole of it exists in Jesus Christ; if you can explain how an eternal, conjugial marriage is effected by the union of the will of the wife and the understanding of the husband; if you can show that the Lord's purpose in creation is a heaven from the human race;--well, then you are really New Church, intelligently and rationally New Church.

Or so we are tempted to think, making religion to consist solely of doctrine, separating it from life. But what good is it to be able to explain the Trinity, but not live the explanation?--and a person who allows himself to be guided by teachings other than those or the Lord Jesus Christ is not living the doctrine of the Trinity, for, above everything else, this doctrine teaches that the human words spoken by Christ are the words of God Himself, and that there is no Divinity elsewhere. And what good is it for a boy to be able to prate beautifully of marriage and conjugial love, if, as a boy, he is not preparing himself for that love by purity of word and thought? And what good is it to speak of an eternal purpose in creation, if one lives as though all that mattered in life is the present here and now?

Religion is not merely what you say you believe. Religion is the way you live according to your belief. Yet, as we mature, we are constantly tempted to make the whole of religion consist only of knowledge and doctrine.

Each of the nations who conquered the Israelites as they were settling:
in their promised land signified not only the particular evil into which Israel had fallen, but also one of the various evils that attacks the Church in each or us. The Philistines, the Writings say, signify the evil of which we have just spoken, the evil of making religion to consist merely in doctrine and knowledge, while ignoring application to life.

It was Samson, strong and mighty Samson, who, on a one - man crusade, began to lead Israel to deliverance from the Philistines. Samson, we have already seen, represents the literal sense of the Word, the plain meaning of the literal teachings of the Old and New Testaments and the Writings, And it is the literal sense of the Word which alone can deliver us when, tempted by spiritual Philistines, we would make the whole of religion to consist of mere knowledges and doctrine. It is in the letter of the Word that we will find the strength of Samson, if only we will turn to it again and again when in such temptation.

We can explain the Trinity, can we? (Not every one that saith unto Me, Lord, Lord, shall enter the kingdom of heaven but he that hath My words and keepeth them.) We believe in the eternity and holiness of marriage, do we? (For everyone who from early youth loves and desires and asks of the Lord a legitimate and lovely companionship with one, and who spurns and detests wandering lusts, a conjugial marriage is provided.) We believe in an eternal purpose in creation, do we? (Lay not up for yourselves treasures upon earth, for where your treasure is, there will your heart be also.)

The letter of the Word - its plain and simple, homely teachings. In intellectual conceit we are tempted to despise it as a lowly weapon for the battles of life. But in it is the strength of Samson, who could take the moist jawbone of an ass and with it slay a thousand Philistines heaps upon heaps

=== THE BOOK OF JUDGES - XIV: SAMSON

Judges 16:1-5

The few verses read today from the story of Samson tell one full incident of his life and the beginning or another - the last. One of the most remarkable features of the letter of the Word, incidentally, is the brevity of its stories. Probably forever there will remain in your minds a picture of Samson ripping off the huge gates of the city of Gaza, and carrying them off into the hills. It took exactly three verses of Scripture to tell that whole story and to describe the incidents that led up to it.

The story of Samson, the Writings say, is literally true, and is to be accepted as such. It is not what the Writings call made - up history, such as we find in the first few chapters of Genesis - stories made up for the sake of their internal meaning - the flood of water, for example, to describe the flood of evil and falsity that practically destroyed the human race at the end of the Most Ancient Church. Nor is the story of Samson mere legend or fable, such as we find in the ancient Greek tales or Hercules. The story of Samson is literally true. There was a man named Samson. He was strong - almost unbelievably strong. And - note this most carefully - his strength actually lay in his hair. Literally, when his hair was long he had strength; when his hair was shorn he was powerless.

To us today, this seems almost impossible. We accept it only because revelation tells us that we must. And yet, the Writings give some indications of how such things could be, and, to some extent, so does common experience. There seem to be on record authenticated cases wherein men, under great emotional stress, have performed almost superhuman feats of strength. The most common examples of this which we usually hear tell how two or three men will carry some such thing as a huge piano out of a burning building, and then, once outside, are unable to lift it. Whether these particular tales are factual or not is unimportant. What is important is that they illustrate the general truth that under emotional stress men can sometimes do that which they are incapable of under ordinary circumstances.

Where does such strength come from? Not the body by itself - that remains unchanged. No, it is rather that something from the mind has entered the body and has given it unusual strength. And it is along this line that the Writings speak when they explain how Samson's strength literally lay in his hair. The mind into the body. But, the Writings say, first something special into his mind, and then the mind into the body.

For when the Lord set up the Jewish Church and commanded it to go through its representations and rituals, He associated the angels of heaven with those rituals and representatives in a very peculiar way. Today, with us there may indeed be angels present in our repetition of the Lord's Prayer. There will be, if we are shunning evils as sins and otherwise living the Lord's commands. But if our hearts are evil, there will be no angelic spirits at all associated with our saying of the Prayer. With the ancient Jews the case was otherwise.

It did not matter what the spiritual state of the Jew was. As long as he stuck to the representatives commanded by the Lord, the heavens were associated with him, and he could use their power as his own. Hence his superhuman strength. But when his hair was shorn there was no representative left in him with which the heavens could be associated, and he became as any other man.

And at the end of the reading today we rind Samson about to be thus bereft of his strength, betrayed by that woman he loved in the valley of Sorek - betrayed by Delilah for a bribe of about four thousand dollars.

=== THE BOOK OF JUDGES - XV: SAMSON AND DELILAH

Judges 16:6-31

Samson, mightiest of the heroes of Israel, now has fallen, fallen because of the nagging, of the woman he loved, but could not trust. Shorn of his hair, he was powerless before the Philistines. They took him captive, gouged out his eyes, and set him to work grinding wheat in their prison. Only one more act remained for him - to die the death wherein he would kill more Philistines than he had killed in the whole of his life.

He had fallen in love with a woman in the valley of Sorek. There is no indication at all that she loved him in return. Quite to the contrary, she at once agreed to the plot of the Philistine lords, in which, for a sum of about four thousand dollars - almost a fortune for that day - she would discover the secret of his strength, and would reveal it to his enemies.

She started to plead with him for his secret. He toyed with her, told her to bind him with seven new bowstrings. She did and then called the Philistine ambush lying in wait in her house, Samson snapped the cords as though they had been tallow.

He must have known she was out to betray him. Nothing could have been more obvious. But back he came for more. She nagged. Again he lied - unused ropes. Again the Philistine ambush. Again he freed himself. And came back for more. And now he began to weaken. Not the whole secret yet, but close to it. Bind my hair with a weavers beam. Once again he walked away free - and came back for more. She nagged again. Vexed to death, he at last told her his secret: Shave my head and I shall be as any other man. He sat at her feet; she stroked his head; he fell asleep at her knees. The dead was done, and he was captured, for when he rose to escape, though he knew it not, the Lord had departed from him.

Three things are very evident here. One: It is dangerous to throw oneself into temptation, or, as we say colloquially, to play with fire. Two: No male can withstand the constant nagging of a female, find three: Man can do that which will cause the Lord to depart from him, as it were.

As foolish as it may sound, there has been many a person who purposely has let himself be tempted, just up to a certain point, so that he may feel pride and glory in resisting evil. Nothing could be more lethally dangerous. No man can ever resist evil from himself. His power to do so comes from the Lord alone, and it comes only when he keeps himself in a state of order. It is hardly orderly to put oneself into temptation. The Lord tells us to ask Him not to lead us into temptation. Why should we lead ourselves there? The outcome is inevitable, and if anyone has ever escaped it, it was by blind luck, and not because of his own power - much less because of his own intelligence.

The Writings teach that the male acts primarily from intelligence; the female, primarily from the will. The understanding is inconstant, vacillating; the will is forever persistent. Hence the Writings teach that, in any marriage wherein one partner sets out to dominate the other, it is always, invariably, the woman who wins, even as the weak Delilah conquered the mighty Samson.

And Samson wist not that the Lord had departed from him. Actually, the Lord never departs from anyone. He is infinite, eternal, and unending love. But for the Lord's love to do man any good, there must be in man something to receive it. What? A knowledge, a living knowledge, of the plain teachings of His Word. Cast these away from yourself, and nothing in heaven or earth can save you from hell. To all intents and purposes, the Lord will have departed from you. The hair of the head represents these knowledges. Samson's hair had now been shorn. The Philistines took him, blinded him, and threw him into prison.

== CHAPTER V

=== THE BOOK OF JONAH - I

Jonah 1:1-10

If you were to ask the average member of a church what he knew about Jonah, he would probably tell you that Jonah was a man in the Bible who got swallowed by a whale and after a few days was spat out alive. Insofar as that answer goes, it is partially correct; there is no mention of a whale, but only of a great fish. Yet the incident of Jonah and the fish is but one tiny fraction of the story of Jonah. The rest concerns the attitude the Jews, Gods chosen people, toward the Gentiles around them.

Jonah, an Israelite, received command from the Lord to go to the great Assyrian city of Nineveh, far to the North, and call it to repentance. Jonah refused - he had no desire to save any non - Jew from damnation. He ran away, took shipping for the western Mediterranean. Perhaps there was the old thought here. Outside Canaan Jehovah has no power. Jehovah, however, pursued Jonah, sending a great storm into the Mediterranean that almost sank the ship. The heathen sailors, terrified, prayed to their gods, threw the wares out of the ship to lighten it. Smugly self - assured, Jonah slept through it all.

The sailors woke Jonah, told him to pray to his God, too, and then, by casting lots, discovered that it was Jonahs sin which was bringing Divine wrath upon them. Jonah now confessed all, and in his one unselfish act in the whole story, told the sailors how to achieve safety - throw him overboard and the storm would cease, Horrified, the heathen refused, instead tried everything else to get the ship to land. The storm increased. At last, after prayers for forgiveness, the sailors threw Jonah into the sea. The storm stopped at once.

Now, the Lord had appointed a great fish to swallow up Jonah, and Jonah was in the belly of the fish three days and three nights. Out of the fish's belly he prayed to the Lord, acknowledged his sin, vowed repentance and the fulfillment of his vows. The Lord caused the fish to vomit out Jonah on the dry land.

Again came the word of the Lord to Jonah: Go to Nineveh and call it to repentance. This time he went, prophesied the destruction of the city for its sins. A mass conversion swept the populace. From king to lowliest servant, the whole city repented, fasting, covering themselves with sackcloth, praying to God for mercy.

The Lord averted the threatened destruction, Jonah was simply furious. He railed at the Lord. This was just what he had been afraid of right along - the Lord, the gracious God, merciful slow to anger, infinitely kind, would spare Ninevah if Jonahs preaching crusade stirred her to repentance. But, still hoping against hope, Jonah went off to the East of the city and built himself a little shack in which he might sit and watch. Perhaps, in spite of everything, the city would still be destroyed,

Overnight the Lord caused a wonder - plant to spring up to give shade to Jonah. This was more to Jonahs liking - God was taking, proper care of His chosen people again. Jonah was exceeding glad of the plant. That night the Lord caused a worm to gnaw through its root. It died, This was simply more than Jonah could bear. He was so furious that he prayed to die.

The Lord said to him, You are very sorry about that plant, which came up in a night and went the next night. You feel badly about it, though you did not create it, nor make it grow. Should not I spare Nineveh, that great city of more than a million persons who do not know right from wrong?

And there the story ends abruptly, without another word, its moral all too clear for our comfort. We talk and prate of Gods mercy and kindness, His love and His wisdom, His desire that we should live a lire or usefulness to others. But we do not do much about it; we do not put much heart in it. But let any little bit or personal good luck or fortune be taken from us, and our emotions are aroused at once to a burning intensity. Life is no longer worth living. We want to die.

=== THE BOOK OF JONAH - II

Jonah 1:8-16

In the portion or Jonah read today we came across two things: Jonahs one unselfish act; the kindness of the very heathen whom Jonah so thoroughly despised.

Jonah admitted his guilt, but in a very peculiar manner. I am an Hebrew, he began, and I fear the Lord, the God of heaven, which hath made the sea and the dry land. I fear the Lord. Indeed! To fear the Lord meant to obey Him, and Jonah had disobeyed the Lord s command to preach salvation to the Gentiles. For this reason the storm was upon them. Yet Jonah now admitted his guilt, and his words imply an admission that the punishment the Lord was bringing upon him was absolutely justified. Throw me overboard, and the sea shall be calm unto you.

The heathen sailors would not do it. Not even to save their own lives would they cast a man to certain death, even if he was the person whose continued existence endangered them. Not, at least, until everything else had first been tried. They labored and strove to bring the ship to land. They could not the storm only grew worse. Finally, accepting the sacrifice of Jonah as the will of Jonahs God, they threw him into the sea. At once the storm ceased. In fear, the mariners offered a sacrifice to Jonah s God, Jehovah.

Jonah, the Jew, unwilling even to call Gentiles to repentance, lest his preaching succeed and they be saved from destruction; the heathen sailors, risking even their lives to save the very man who hated the heathen en masse.

Mass hatred - it is a diabolical thing, yet very common. The ancient Jew, believing his race Gods chosen people, hated all Gentiles at once. Today, many among us so - called Gentiles return that mass hatred, hating every Jew all Jews, simply because they are Jews; despising all Negroes simply because they are Negroes. We condemn whole groups, either without any knowledge at all, or because of our personal contacts with a very few members of the groups. We are unwilling to admit that any, save those of our own class or race, our own color or church, may be good.

The Writings condemn this attitude in their teachings concerning societies of friendship, groups with no real point to their existence, save friendly intercourse, yet closely knit into cliques, unwilling to admit that the good done by others than themselves is really good. Such, the Writings say, are not in heaven.

Perhaps more than any other people in history, New Church men are in danger or making our church a society of friendship, of adopting the attitude of Jonah. The Writings teach flatly that the Old Church is dead. It is. As New Church parents we teach our children that our church is better than others. It is, and children should know this. Yet here lies the danger.

The Old Church is dead. That means only that as a church, as a body capable of teaching the genuine truths of heaven, the Old Church is dead, Our church is better than others. That means only that our doctrines are infinitely superior to the teachings of any other church. Not a word is said concerning the people of these churches.

If only Swedenborgians go to heaven, heaven will be a very lonely place. There are millions of good people in the Christian churches, even if those churches are dead as teachers of truth, and after death those millions will accept the genuine truths of heaven and will become angels. New Churchmen have more truths than others, and therefore can be better, than others they should be - but it does not follow that they are. Church membership is no ticket to heaven. Jonah, the Jew, despised the ignorant heathen; the heathen sailors risked even their lives to save the man who hated them.

=== THE BOOK OF JONAH - III

Jonah 1:17, 2:10

Merely in introducing; a few remarks concerning the prayer of Jonah from the fish's belly, we would note that the Writings never list this event among what they call the made - up histories of the Word - stories such as Adam and Eve, Noah and the Flood, apparently historical, but really made up for the sake of a spiritual meaning. Indeed, the last time Swedenborg treats of the subject - several years after his spiritual eyes had been opened, but before he had been commissioned by the Lord as a revelator he says that the event actually happened even as did also the miracles in Egypt. (@SE 1391) When the Lord was on earth, He referred to the story of Jonah several times, and in one instance said that as Jonah was in the whales belly three days and nights, so would the Son of man be three nights in the heart of the earth.

At first hearing this would seem to refer to the time between the Lord's death on the cross and the time, on the third day thereafter, when He was seen resurrected from the dead. The Writings, however, explain it otherwise, teaching that it refers to the duration of the direful temptations the Lord underwent during His whole lifetime on earth, when, just as the floods encompassed Jonah about, and all the billows and the waves of the sea passed over him, so all the powers of the hells encompassed the Lord and buffeted Him about. All of hell at once attacked Him. He overcame them all, and now salvation is of the Lord.

Mans temptations, it is said, are a finite image of the temptations endured by the Lord, and sometimes mans plight in temptations seems as hopeless as Jonahs plight must have seemed to him. Yet Jonah, we would note, did not give up hope: the earth with her bars was about me forever, yet thou hast brought up my life from the pit. My prayer came in unto thee, into thy holy temple. It will sacrifice unto thee with thanksgiving, I will pay that I have vowed.

Now, the Lord never leads us into temptation. Like Jonah, we Bring trouble upon ourselves. Knowingly or not, we do something evil and get to like it. Then we repent of it and try to overcome what has now grown with us into an evil habit. That is where temptation begins, for the hells then seek to keep their grip upon us, confirming us in the love of evil.

Such temptation not only is hard to endure, it is horrible, in every respect. No matter how hard we try, it seems we cannot really break our evil habits, our love of evil. The thing is too strong for us. All the billows and waves are - spiritually deformed and hideous - and cry out with David the Psalmist, I am a worm, and not a man?

What shall se do then? Give up the fight? Give in to evil and confirm it? We are tempted in only one evil at a time; the Lord was tempted by all the hells at once. His temptations lasted a lifetime: can we expect victory overnight, or even in a year?

No. Nor may we give in. No matter how hopeless our struggle may seem, we yet must look again to the Lord's holy temple, and pray to Him the vows that we have made. Salvation is of the Lord. In His own good time, when He sees that our eternal good will thereby be served, He will deliver our soul from hell.

=== THE BOOK OF JONAH - IV

Jonah 3:1-10

Jonah, chastened into obedience but not yet converted in his heart, complied with the Lord's second command to go to the Assyrian city of Nineveh and call it to repentance. He Prophesied destruction of the city within forty days. The people of Nineveh repented one and all, sackcloth and ashes, fasting, and prayer to God to spare the metropolis. And God saw their works, and repented of the evil that He had said He would do unto, them, and did it not.

Once again, here, we see that very ancient concept which still endures with us today. God will damn us for our evils, condemn us to eternity in hell. It is an idea as hard to get rid of as is the opposite belief:
God will give us heaven as a reward for being good.

The life of heaven, however, is not a thing the Lord gives man, as it were, in a package. Indeed, it is not even given in a book of specific instructions, a rule book, as it were, telling each resident what to do at ten o'clock and what to do at three, what to do on Tuesdays and what to do on Sundays, what to do when visitors come to call and how to bring up children. Much less is heavenly life personally directed by the Lord speaking to the angels. Heaven is not like that. Heavenly life is simply the way of life that decent people have figured out for themselves - decent people who study the Word and decide for themselves its applications to life. That is all that heaven is - not any kind of present or reward for good deeds done.

Nor is hell a divinely inflicted punishment for evil. Hell is simply the association of evil and selfish men who would far rather live together than side by side with angels. And the life of hell, for the most part, is simply the way of life that the people there impose upon each other. But that is what makes it hellish. No one there wants to work, get society cannot go on without work, and so, since nothing else avails, strict laws are set up under which frightful punishment comes upon anyone who shirks at his job. No one there wants to obey the law, yet society cannot go on without law, and so ghastly punishments are inflicted on anyone who commits an evil that hurts his neighbors body.

Hell is not a divinely inflicted punishment. The Lord could not condemn anyone; for He is nought but love and mercy. He may, indeed, warn you that if you continue in such and such a course you will be punished in hell. That is true. He sees the inevitable outcome of your present state of life. And if you then repent and change your way of lire, the threatened disaster will not transpire.

But neither the punishment nor its retention comes from Him by personal decision., His mercy is infinite, and goes forth universally and eternally to all. We can, if we insist, shut ourselves off from the happiness He would give us. We do, when we head ourselves toward the destruction of hell. But if we turn once more toward heaven, the threatened disaster is averted, and, once again in the stream of Providence, we are carried upward to eternal joy.

=== THE BOOK OF JONAH - V

Jonah 3:10, 4:11

Forgive us our debts, we pray the Lord - and much of the time are afraid that He will. To forgive sins in us means to take out of us the love that caused us to sin. With the love gone, no enjoyment of the evil would any longer be possible. A familiar and pleasant delight would be taken forever from us. Do we really want to undergo such a change as that? A lot of people do not. They want to keep on enjoying their evils. They know the Lord is forgiving, and they fear that He will forgive them personally. Like Jonah, they deny the very God they worship. I knew that Thou art a gracious God, merciful and forgiving; now Thou hast forgiven Nineveh; I would rather die than live.

Many of the things we know about the Lord we deny in our lives. The Lord is justice itself, but do wt want Him to judge us justly - to give us our just deserts? Other people, yes; but we want mercy for ourselves, or a blind ignoring of the facts. The Lord is mercy itself, but do we want Him to be merciful? To us, surely; but what about others? If we do, then why are we not merciful to others ourselves? We know that the Lord alone can do what is good. Our conceit denies it.

Like Jonah, we deny the God we worship. We do not want Him to be what we know He is. We do not want to take what He has to give. Jonahs story, indeed, is the story of each and every one of us. Fortunately, however, our stories need not end as Jonahs did, with Jonah still rebellious against his God. There is another ending possible, and millions who began no better than Jonah have achieved it.

To make ourselves want God to be what He is; to make ourselves want what is His to give -- that is the struggle. How gain the victory?

The first step is to know what God really is and what He wants for us. This is every man s personal duty. It is not enough to rely on a minister for this knowledge. Every man must gain it for himself from Divine Revelation the Old Testament, the New Testament, and, for us today, the Writings especially.

The second thing is to compare ourselves with what we learn concerning the Lord and His desires for men the things we do, the things we say, the things we think when all alone, the things we would like to be able to do. This is self - examination. It gradually reveals wherein our will differs from the Lord's.

Having discovered our evils, we must then pick out one or two of them and determine to shun them as sins - determine to turn away from them, not only in word and act, but also in thought and intention.

What comes next is not easy. Temptations follow. Temptations to go on with the evil we have determined to shun, temptations as hard as was the plight or Jonah in the fish. But temptations which the Lord will always give us strength to endure to the end. And the end will come. If we persist in our determination to cease from doing and thinking the evil, then, in the Lord's good time, the end will come, and we will find our love of the evil entirely gone. Our sin will have been forgiven. New loves will take the place of the old. We will truly be glad that the Lord is what He is, and we will eagerly want that which He seeks to give us, for His desires will have become our own.

== CHAPTER VI

=== THE ADVENT -  I: PROPHECIES

Genesis 3:1-15

In order to be saved it is absolutely necessary to believe that God is a Divine Man. No other belief about God makes religious sense, for no other belief teaches what man must do to serve his neighbor.

The men and women of the Most Ancient Church (signified by Adam) knew perceptively that God is a Divine Man. Wherever they looked in nature, they saw evidences of the Lord's Divine love, evidences of His Divine wisdom; and love and wisdom, they perceived, are Man.

When the Most Ancient Church fell, the birth or the Lord on earth was at once inevitable. Faith in the Divine humanity of God, it was foreseen, would otherwise parish, God would eventually have to be born on earth, both to show forever that God is Man, and to show what Man is and should be.

Yet not immediately could the incarnation take place. The seeds of all imaginable evils had been implanted in mens hearts at the Fall, but it would be .... before they all grew and flowered and bore their hideous fruits. The Lord could not be born until the spiritual state or man had sunk to the depths. Were He to come earlier, men would at first have accepted Him and then would have utterly rejected Him, for evil was still growing within them unseen and unrecognized. Their last state would have been far worse than their first.

Faith in the Lord's Divine humanity, then, had to be kept alive. But the Lord Himself could not yet be born on earth. Prophecy, however, could keep that faith alive - prophecy that God would be born as Man - and faith in the Lord to come was, for the ancients, saving faith.

The first prophecy was given as soon as the Fall took place. It is told of in the curse upon the serpent: I will put enmity between thee and the woman, and between thy seed and her seed; He shall trample thy head, and thou shall bruise His heel.

Very general this prophecy is, but the whole or truth is contained within it. The seed of woman: not the seed of man, but one born of a virgin. The enemy of evil. The power of evil would hurt Him, bruise His heel, crucify His body. But He would trample the head. of the Serpent, break the power or evil, conquer all the hells.

For the Most Ancients this was enough. It told the whole story. For their descendants, however, an increase in prophecy would be necessary, ever bolstering the central truth that God is Man, actually to be born on earth. Judah would have dominion until He came whose name was Peace. A star shall rise out of Jacob. Jehovah will raise up a prophet like unto me; Him shall ye obey. Behold, a virgin shall conceive, and bring forth a Son, Wonderful, God, Father of Eternity, Prince or Peace. Thou Bethlehem, out of thee shall come a Governor that shall rule my people, Israel. The dromedaries of Midian shall come; they shall bring gold and incense, and shall show forth the praises of the Lord. The voice of one crying in the wilderness. Prepare ye the way of the Lord. The glory of the Lord shall be revealed, and all flesh shall see it together. And the Word was made flesh and dwelt among us full of grace and truth.

=== THE ADVENT -  II

Luke 1:5, 7-13, 15-22

The greatest fact in human history is the Lord's love for the human race. More than anything else, it has shaped and guided the course of human events, as it sought continually to draw man upward toward conjunction with his God.

If the entire human race on any earth were to turn to evil, then, the Writings say, that race would have to be destroyed, for its connection with the heavens, and through the heavens with the Lord, would be broken. No man could receive anything divine, when yet it is only from the Lord that we live and move and have our being.

Somewhere on earth, therefore, there must always be a church; there must always be some men who receive divine truth from the Lord and live it. So far, the Lord has always been able to provide that there be such a church to keep open the connection between heaven and earth, but once two thousand years ago, that connection was at the very point of being broken. In the spiritual world the hells had swept out of bounds, had swarmed over the world of spirits, and had begun to infest heaven itself. Devils could seize the very bodies of men on earth, the bodies even of good men, seize them against mens will. On earth, all genuine understanding of truth was gone. Even the few who tried to be good did not know how, knew not what the truths they still had meant. Mary would see in the promised Child only some one to free Israel from her Roman conquerors.

For ages the Jewish Church, through special and unusual means, had served to keep open the path between heaven and the human race, but now the Jewish Church was almost at its end. Prophecy had perished from Israel. For four hundred years no vision had come; for four hundred years no one had spoken to the nation the Word of its God. Formal ritual had become the whole of religion.

A few in that church, however, still clung desperately to one of its teachings its promise that some day a Messiah would be born who would somehow make everything turn out all right. Such were Zacharias and Elizabeth, righteous before God, but, like the rest of the race, well stricken in years and spiritually barren. Zacharias the priest. There were so many priests in Israel, and there was only one temple for their ministry, that their work was divided into courses. For two weeks a year, a week at a time, Zacharias worked as a priest, and even then his work was almost nothing. At this particular time there had fallen to him by lot the privilege of entering the sanctuary to light the morning - incense. It was then his duty to come out and bless the praying multitude.

An angel appeared to him - but no angel had appeared to Israel for centuries, and vision of an angel used to mean death. Fear not, said the angel. Zacharias and Elizabeth, even in their old age, would have a son they were to name him John who would go before the Lord to Prepare His way. Zacharias, doubting, was stricken dumb. When he finally emerged from the sanctuary the waiting people thus perceived that he had seen a vision. A vision! Something strange, something new, was in the air. Fear fell upon them, and they were filled with awe.

But it was not something new. The Lord's love for mankind has never changed. It always has been, it is, and it always will be, the greatest fact in human history. Mankind had brought upon itself the complete blackness of spiritual night. Only one thing could redeem it. The Lord God Himself was now ready to bow the heavens and come down to take upon Himself our fallen nature; to purify it from every evil and falsity; to conquer for us all the hells at once, so that we today would have the power to conquer the little bit of hell that creeps into each of us; to unite His Human nature to His Divine and to rise in divine majesty and glory as our Savior, the one and only God.

=== THE ADVENT -  III: THE VIRGIN BIRTH

Luke 1:26-38

The Holy Spirit shall come upon thee, and the power of the Highest shall overshadow thee: therefore also that holy thing which shall be born of thee shall be called the Son of God.

Everything born receives its soul from its father, and becomes such a being as its father. An animal receives its animal soul from its father, and becomes an animal. A human being receives a human soul from his father, and becomes a man. The Lord, when born on earth of the Virgin Mary, had no human father, else He too would have been a mortal man as we all. It was God Himself who thus assumed the human through the Virgin birth. His soul was Divine, and He therefore made the whole of His Human Divine. It was God Himself who thus became Emanuel, God - with - us, God on earth in human form.

The doctrine that each thing born receives its soul from its father is a doctrine absolutely distinctive to the New Church, today. It is not among the facts of science. It is not even known science. It is a matter of revelation - the revelation of the Writings - and it is the eternal reason why we, as a church, will always uphold belief in the Virgin Birth or Christ. It is the very cornerstone of our faith that the Lord Jesus Christ is the one and only God.

Had Joseph been the father of the Lord, the Lord could never have become a being different from Joseph. He could never have been more than a man, a good man. Through the Virgin Birth, however, He could be, and He was, our God on earth.

Six months after Zacharias and Elizabeth, in fulfillment of the angelic promise, had discovered that they were at last to have a son, the angel Gabriel was sent to Elizabeth's cousin, Mary, a virgin of Nazareth, betrothed, but not yet married to Joseph. Jewish wedding customs differed from ours. Among them, when a boy and a girl announced their engagement, a priest was present at the announcement, and pronounced the Lord's blessing upon them. They were then said to be betrothed or espoused, and were spoken of as being husband and wife. Twelve months later the man put on a wedding feast, to which he bade his friends, and at the end of that, he took his bride home to be his wife. There was no formal wedding.

It was during this period of betrothal between Joseph and Mary that the angel appeared to Mary to tell her that she, blessed among women, was to be the mother of the Lord. How shall this be? Mary asked I am not yet married. And the angel answered, the Holy Spirit shall come upon thee, and the power of the Highest shall overshadow thee; therefore that holy thing which shall be born of thee shall be called the Son of God. And Mary replied, Behold, the handmaid of the Lord; be it unto me according to thy word.

The greatest miracle of all history had begun. Jehovah Himself had begun to assume the visible human form a God who would conquer evil for us and who would hold hell in eternal subjection; a God who would teach us truth in clear and intelligible language; a God whom we can see with the eyes of our minds, and thus can understand and worship and adore.

=== THE ADVENT - IV: REFORMATION AND REGENERATION

Luke 1:39-47; 54-56

Mary and Elizabeth were cousins Mary, the mother of the Lord, and Elizabeth, mother of John the Baptist, who would go before the Lord to prepare His way. But the Lord had no human father, while John the Baptist had the priest Zacharias.

Now, even the Christmas stories of the Word have an internal sense, which treats, not of the Lord, but of the individuals reformation and regeneration, and in this sense the facts just mentioned are of great importance the relationship of Mary and Elizabeth, the Virgin birth of Christ and the human birth of John.

The birth of the Lord on earth is said to signify mans regeneration; the work or John the Baptist, that which the Writings call reformation. Reformation and regeneration what are they, and what is the difference between them?

Regeneration - spiritual rebirth - consists of the removal or evil loves from the heart and the establishment of good loves in their place. There is not a one of us who does not have some love of evil and who does not actually find enjoyment in that evil. Yet, when we become regenerate, every single evil love will be taken from us; we will love only what is good; and evil will simply horrify quite a difference from now. Truly, we will be reborn into entirely new people.

Let us picture a man strong, intelligent, handsome, powerful - and horribly conceited. He gets lots of compliments in life, and every single one or them fills him with a glow of pride. He considers himself pretty neat. He revels in his sense of personal power. Yet if he becomes regenerate, all his enjoyment of such selfish loves will be gone.

So let us suppose that he discovers that his loves are evil. He wants to be regenerated. He asks the Lord to take his evil loves from him. What would happen if the Lord immediately did what he asked?--if the Lord then and there regenerated him?

The man would be lost. All his enjoyment in life would be gone, and he would have nothing to take its place. He wouldn't even know himself.

The birth of the Lord represents mans regeneration. Something else has to come first - the birth of John, who represents reformation. Reformation consists of discovering your own evils, asking the Lord's forgiveness for them, and then fighting against them with all your might through all your life, until you come to hate them. That is something you yourself can do with the life the Lord gives you, and that is why John the Baptist could have, and had to have, a human father.

Until you do all that that is meant by reformation, you would hate regeneration if it came to you. The birth of the Lord in you would only strike you as a curse.

Regeneration - the removal of evil loves from the heart. That is a thing which only the Lord can do for you. You can fight your evils; only He can remove them. And that is why, even for the sake of the spiritual sense, the Lord was born of a virgin.

Reformation and regeneration - the two are closely related. One is fathered by man; the other is not. And reformation (John) must come first, to prepare the way for regeneration (the birth of the Lord in the human heart).

=== THE ADVENT - V: PREPARATION BY JOHN

Luke:1:57-64, 68-71, 76-80

For any important event, much preparation is needed. A person needs training, before he can begin most any job; without training, the job would ruin the man and the man would ruin the work. Before the exalted use of marriage can properly be entered into, intense preparation is needed - education, physical growth, social experience, and finally engagement or betrothal. The tremendous preparation of reformation must precede regeneration.

Almost infinite preparation to precede that supremely important event of history, the Lord's First Advent. Something vital had to prepare His way, and that preparation was both personified and represented in John the Baptist, who made ready a people prepared for the Lord. Without his preparatory work, the coming of the Lord could only have smitten - humanity with a curse.

The Writings say some strange things about the importance of John the Baptist. Without Johns work, it is said, the Lord's revelation of Himself among the Jews in Palestine would literally have caused that whole people to perish at once in eternal death. Johns work saved that people from itself.

But what was it he did which was of such tremendous effect?

First of all, the sense or mystery surrounding his birth caused many in Israel to think once again concerning Jehovah a practice all but forgotten by myriads. Knowledge of Zacharias vision and of his miraculous dumbness spread throughout the land. And then, at the naming or the child, the fathers tongue was loosed, and he prophesied wondrous things concerning his son.

Fear came on all that dwelt round about ... and these sayings were noised abroad.

John spent his childhood and youth in the desert. It is popular today to believe he grew up in the Essence monastery at Qumran, where the Dead Sea Scrolls recently were discovered. (It is not impossible.) And then, a while before the Lord began to preach, John again appeared in civilization.

He roamed the streets or the cities, a strange man, indeed his hair uncut, his clothes rough leather and camels hair, his only food grasshoppers and wild honey. Repent ye, he cried. Be baptized unto the remission of sins. Flee from the wrath to come! He frightened the people. Myriads came out to his baptism. What shall we do? they asked. He gave them good moral advice: Show charity to the neighbor ... fairness ... mercy ... contentment. On express command, he baptized the Lord, He whose shoes I am not worthy to unloose. And finally his path crossed that of Herod the king, He condemned the king for murder and adultery. The king imprisoned him, and at last, to satisfy his lust, beheaded him and gave his head to his stepdaughter to dance with.

This was John the Baptist, who prepared the way of the Lord. It was his baptizing. that was important. Today, in the sacrament or baptism, angels are associated with the one baptized. The Jews of that day were a lowly and evil people, and evil cannot stand in the presence of the Lord. But Johns baptism associated with the Jews certain angels of heaven - lowly angels - and their angelic sphere would protect the Jews from the all - consuming assault or hell, which otherwise would have destroyed them as God on earth revealed Himself among them.

=== THE ADVENT - VI: AND HE CALLED HIS NAME JESUS.

Matthew 1:18-25

Ancient Jewish wedding customs, we have seen, differed from ours. At the announcement of the engagement, a priest was present and administered a blessing upon the couple. They were then said to be betrothed or espoused, and thereafter were properly called husband and wife. From that moment on, only a legal divorce could separate them.

Yet by law, a whole year was supposed to elapse before the man put on a wedding feast and then took the woman home to be his wife - a whole year, in which they were not allowed to see each other, and communicated only through a chosen representative called the friend of the bridegroom.

It was during this interim period that Joseph discovered that Mary, his betrothed, was with child. He knew not that the Child was conceived of the Holy Spirit. Two courses were open to him. He could divorce Mary openly in court. (In that case she would be stoned to death.) Or, in the presence of two witnesses, he could hand her a formal bill of divorcement, and there the matter would end.

A just man, Joseph chose the latter course. But while he was still thinking over this decision, the angel of the Lord appeared to him in a dream, and told him that Mary's child was of Divine conception. She shall bring forth a Son, the angel said, and thou shalt call His name Jesus.

Matthew, in telling this story, points back, now, to the prophecy of Isaiah, some seven hundred years previously, Behold, a virgin shall be with child, and shall bring forth a Son, and they shall call His name, Emanuel.

Emanuel - the name means, God - with - us. In the Lord Jesus Christ, God was with us men on earth. And in the Lord Jesus Christ God still is with us here on earth - not only present with us in our hearts and minds, but also with us in the sense of being on our side. The Lord is on the side of every one of us who seeks salvation - fighting for us against the forces of hell, teaching us, guiding us, comforting us, and at last giving us eternal peace. Emanuel - God - with - us.

And Joseph, waking from sleep, took Mary to himself to protect her, till she had brought forth her Firstborn Son, and then he called the name of the new - born Child, Jesus.

Jesus - the word means, Savior. The Lord was born on earth for one purpose only: To save the human race. The love of humanity's salvation was the one and only love that ever motivated Him in life. And he did save mankind - saved them from the clutches of hell which then wee fastening themselves on man with death - dealing grip. He made salvation possible again. And today it is still He who saves each one of us who permits himself to be saved.

Jesus - salvation. That Child, whose birth on earth we celebrate at Christmas; that Child, then weak in infancy - it is not really His birth that we celebrate, but rather, what He became: Jesus, our Savior, our confidence, and our joy, He who broke the power of Satan over us and now can give us peace eternal.

=== THE ADVENT -  VII: THE INCARNATION

Luke 2:1-17

In the days of Caesar Augustus. Rome, the latest conqueror of Israel, was a hated overlord, but she did bring one thing into the world - law and order. And it is only when mans daily, external life is kept in a state of order that the Lord can be born in his heart,

A decree went out that all the world should be enrolled. A census taking. Each man had to stand and be counted in his own city. In the state of reformation that must precede regeneration, man must take account of each and every thought and affection in his mind. Is it good or evil, true or false? Is the city of its birth heaven, or is it hell?

From Nazareth of Galilee to Bethlehem of Judea, because he was of the lineage of David, and Bethlehem was Davids royal city. Prophecy long had foretold the Messiahs birth in Bethlehem, long had said that the Messiah would be of Davidic stock. Yet it was mere chance - Caesars census - that combined events to bring about the Lord's birth in Bethlehem, (Chance?--or Providence?)

Bethlehem. The name means house of bread, the source of spiritual food, the Word of God. If ever we allow the Lord to be born in our hearts - if ever we acknowledge Him as our personal Creator, Redeemer, and Savior - it will be because there is within us a Bethlehem, a knowledge of the teachings of His Word.

And laid Him in a manager. A food box for horses; yet it served as a crib for our Lord. But a horse signifies the intellect, the thinking - power of the mind, for the intellect does for the mind what the horse then did for men. It gets you places, it is the beast of work. And the proper food box for the intellect?--again, the Word. When the Lord is born in us, He can find rest only in what we know of the teachings of His Word,

Because there was no room in the inn. The inn signifies the church - a place to turn aside into for spiritual refreshment and there certainly was no room then for the birth of the Lord in the Jewish Church. .... But the word the Writings here use for inn is the same word they use for social life. Then, is there no room for the Lord in our private and social activities into which we turn aside for relaxation from our work?

To simple shepherds keeping watch over their flocks by night, the Lord's birth was first announced, and it is with simple, faithful states in our lives - not in proud and proprially exalted delusions of personal grandeur - that our regeneration can begin.

Their spiritual eyes were opened still further, and they saw, not just one angel, but a whole society of angels it often happens that way in heaven praising God, and saying, Glory to God in the highest, and on earth peace, among men of good will. Peace on earth! How men have longed for it through the centuries - twenty centuries which have hardly known one year when there was not bloody, hateful warfare somewhere on earth. Peace on earth! How men long for it today, and live in constant fear that todays uneasy peace shall suddenly perish in nuclear destruction. Peace on earth! Is its promise a sham? Why does it never come? Because Peace on earth was not all the angels sang: Something else came first and ever must come first: Glory to God in the highest.

And the shepherds said ... Let us now go even unto Bethlehem.... And they came with haste, and found Mary, and Joseph, and the Babe lying in a manger. The greatest single event in human history at last had taken place: God was born on earth.

=== THE ADVENT - VIII: THOUGHTS REVEALED

Luke 2:22-35

Forty days after the Lord's birth on earth, Joseph and Mary, devout Jews that they were, undertook the short journey from Bethlehem to Jerusalem, in fulfillment of ancient custom. Their purpose was two - fold: First, to offer a sacrifice of thanksgiving to Jehovah for the first - born Son; and second, to present the Child in the temple, apparently in memory of the presentation of the child Samuel to Eli the priest. For this sacrifice the rich offered a lamb; the poor, a pair of turtle doves or two young pigeons. Mary and Joseph, it seems, were poor, for theirs was the latter offering.

It must have been before the visit of the Wise Men that this occurred, for after that event, with Herod on the lookout for the new - born King, it would have been too perilous a risk to take the Child to the very seat of Herods iniquitous rule. Really, then, neither this story nor the story of the Wise Men belongs to Christmas, but in spite of that, we carry on the very ancient tradition of the Church.

In Jerusalem at this time lived a man named Simeon, just and devout, and to him it had been revealed that he would not die before he saw the Lord's Christ - the Messiah, that is. And now, under the guidance of the Holy Spirit, he came into the temple, just as Joseph and Mary arrived. At once he took the young Child in his arms. His life - long --ambition had been achieved. He was an old man; he knew he faced imminent death; but now he faced death in perfect peace: Mine eyes have seen Thy salvation.... A light to lighten the Gentiles, and the glory of Thy people Israel.... A sign which shall be spoken against, that the thoughts of many hearts may be revealed. The glory of Thy people Israel.

If the Jews had had their way - the good Jews who believed in the Lord, that is - Christianity would have remained a sect confined within the Jewish Church. The Messiah was going to be their King, making them the ruling nation of the earth. But it was not to be thus. The Lord loves all men equally, not just Jews, nor even New Churchmen. His truth is for all men, of all nations, in all times, and from all earths, even as it is destined to penetrate to the darkest corners or the minds of each of us. The salvation of .all men was and is the Lord's only love.

But Simeon also said of the Lord that He was a Sign which should be spoken against, that the thoughts of many hearts might be revealed. How literally true was his prophecy! Evil men did speak against the Lord, and good men spoke in His favor. In His presence the thoughts of many hearts were revealed. It is ever so. The Lord does not come to judge man and condemn. He comes only to save. But the first effect of the Lord's Advent to man is always judgment. Man, in His presence, judges himself. When any one of us - youth or adult - hears and understands a teaching of the Lord, the first effect is always a judgment. He who would follow the Lord in the service of his neighbor, accepts the truth, and changes his life according to it. He who insists upon having his own way in life, no matter what the truth, rejects it, and thereby condemns himself.

As we approach this Christmas celebration - this nineteen hundred and sixty - second anniversary of the birth of the Lord on earth - let us pray that ours may be the former course.

=== THE ADVENT - IX: THE CHRISTMAS STAR

Matthew 2:1-12

We have seen His star in the East, and are come to worship Him. Among certain wise men of Syria, the worship of Jehovah persisted long after it had died out elsewhere. Magi, these men were called, and they were well - versed in the knowledge of correspondences. They knew too the ancient prophecies that some day God Himself would be born on earth, to save men from their sins.

Somehow, when the Lord at last was born, they were given a revelation or that fact. Perhaps they saw a spiritual light. It is popular to believe that they saw light from the society of angels which spoke to the shepherds. (Certainly it was not a natural light. If it had been, even Herod would have followed it in his hideous hunt for Him born King.) Perhaps they were given a verbal revelation that mankind's Savior had been born, and they then spoke of this new knowledge as a star. This would have been enough to bring them to Jerusalem, for the prophecy that the Lord would be born among the Jews was very ancient, while the prophecy of His birth in Bethlehem was comparatively recent.

A star to follow! Every man has some star that he follows, some goal shining before him which guides him on the way he wants to go in life. But it was His star that the Magi followed. A star: Light ... high up. A most exalted truth, a star thus signifies; and His star is the most exalted truth there is. It is knowledge or the Divine Humanity of God.

What more could any man ask than this - to know His God? To know the nature or the God who created him; to know why God created him and what the purpose in his creation is; to know what Gods will is and thus to know how to achieve Gods purpose in his creation. This is His star - knowledge or the Divine Human nature in God.

But when first we begin to see it, it does not lead us directly to the Lord. It leads, instead, to Jerusalem, which signifies the church. It leads us to see that if we are going to rind the Lord, each one of us for himself, we must go first to the church to receive instructions Only after that can we as individuals each rind the Lord for himself in Bethlehem, the Word, and enter into His house and offer Him that worship which is signified by gold, frankincense, and myrrh. Gold it was then the most precious thing there was, and it signifies love to the Lord, frankincense mans love or his neighbor ascends to the Lord as a grateful incense. And myrrh - an ointment for the body, a bodily thing: the uses we perform for one another.

We have seen His star in the East, and are come to worship Him. The Lord also had His star, a star He followed all His life, and that is why He is the God we worship. His guiding star was His infinite desire to make possible the salvation and eternal happiness of every man who will freely take salvation. No greater love hath any man than that; indeed, no love so great.

Born on earth as a man with His consciousness then residing in His human mind, He found for us a pathway which we could freely follow into heaven. With infinite tenderness, He forced that path on no one. He lays it out before us; He asks us to follow it; He offers us His help along the way. His only desire is that we shall follow it, for that way alone brings eternal happiness. He is God. He has all power. But He forces Himself on no one. He respects our free dom. He humbles Himself, and asks us (as though we were really worth it) to follow Him into heaven. For this, He is our God.

We, too, like the Magi, now have seen this, His guiding star, and it is for this that we are come to worship Him.

=== THE ADVENT - X: OUT OF EGYPT

Matthew 2:13-23

It is more than mere coincidence that several people mentioned in the Word spent some time in Egypt before coming to live in the Promised Land. Each had a glimpse or the Holy Land, as it were and then went to Egypt. Abraham was the first; he went down into Egypt and there received riches from Pharaoh before going back to live in Canaan. The whole nation of Israel, in fact, was in Egypt for centuries before the Lord called them out under Moses to occupy Canaan as His chosen people. And now the Lord Himself spent His early childhood in Egypt, before returning to the Holy Land to grow up in the city of Nazareth.

Matthew saw significance in this. He saw it as fulfillment of the ancient prophecy of Hosea, Out of Egypt have I called My Son. But Matthew never saw what the real significance or it was.

Egypt. Why did Abraham grow rich there? Why did Israel go there for relief from famine, become enslaved there, and finally escape, after robbing the Egyptians of their jewels and their gold? Why was it the Lord was in Egypt as a Child? And why must we all spend time in Egypt before we can attain our destiny in our promised land?

Egypt, in ancient times, was the land of worldly learning. Astronomy, mathematics, engineering, and other sciences then flourished there. As such, in the story of the Word, Egypt signifies science or worldly learning.

Canaan, on the other hand, (the Promised Land, it was called), obviously signifies heaven; or, putting it another way, mans heavenly destiny, which is regeneration. This, of course, in reference to Abraham's and Israels return to Canaan. In reference to the Lord, Canaan signifies even more His glorification or the making Divine of His assumed human mind and character.

It is easy to see, then., that a residence in Egypt, preparatory to life in Canaan, signifies the necessity or gaining worldly learning; before we can undertake the adult uses of regenerate life. We must know how to live in the world and be or use in the world, before we can successfully serve the Lord in usefulness to our fellow man.

And with the Lord, residence in Egypt signified even more. As a Man on earth, He, too, had to receive a worldly education before He could begin His Divine use of teaching men the way to heaven. In His conscious natural mind, He had to learn what men knew, so that He could penetrate their knowledges to the genuine truth within them and then teach that to men.

That is why Egypt, in the Word, was so often the source of riches. It was with the jewels and gold borrowed from the Egyptians that Israel built her tabernacle in which to worship the Lord. And it is with the learning and science we can take from the world that we can build up our minds into fit dwelling - places in which to serve the Lord in a lire of use to others.

But Egypt can be too captivating a thing at times, Israel was enslaved there for hundreds of years. Worldly learning and science can become so attractive that we forget that in themselves they are not our destiny. They are not, Canaan, the Promised Land, the life or regeneration, is. Out or Egypt have I called My Son.

=== THE ADVENT - XI: THE INCARNATE WORD

John 1:1-14

The historical details of the Christmas story are found only in the Gospels of Matthew and Luke. Yet John also tells the story or Christmas, though without mentioning a single event connected with it. He tells it in a philosophical presentation of the really important thing that then took piece: The Word ... the Divine Truth ... which from eternity was with God and was God; this Divine Truth by which all things were made and which was both the light and life of man; this was made flesh and dwelt among us, and we beheld His glory.

This is the real meaning of Christmas, and it is why we celebrate the day. Without this, Christmas would be naught but commercialized gift - giving, cheap sentiment, and gaudy tinsel.

The Word was made flesh and dwelt among us. The Lord's whole life is the love of humanity's salvation. But this, the Writings show, means more then just giving us salvation, as though it were a wrapped - up gift. It means leading men to find eternal happiness for themselves. That, then, is the Lord's whole purpose: to lead each of us to find eternal happiness for himself. Now, how can that be done? In one way only. First, He must give us a picture of what real happiness is, to serve as our ideal. How does He do that? By teaching; us the truth concerning it. Then He must teach us how to attain that happiness. Again He must teach us truth - truth which will show us what things within us prevent us from having that happiness now; truths by which we can overcome those evils within ourselves; truths which can serve us as a pattern of heavenly life, so that we may live accordingly, until we come to love that way of life and find salvation in it. Only through the teaching of truth can the Lord lead men to find happiness for themselves.

And before the Advent, genuine spiritual truth was utterly unknown on earth. The Jews were the last remnant of the Lord's church on earth, and Mary, who became the Lord's mother, must have been among the best of her race. But what did she then know or truth? She praised and magnified the Lord,--but why? Because all future generations would call her blessed, and because now, she thought, had come the day of Israels release from her hated Roman captors.

Truth was lost before the Advent. The Jews knew Gods command against murder. But the Lord's words were almost unintelligible to them that anger against ones brother was also a sin. They worshiped God; and thought that God sat in the sky, drinking in with delight the stench of their burning sacrifices.

Truth was lost before the Advent, and yet without truth there can be no salvation. It was for this reason that the Word was made flesh. In Jesus Christ, Divine Truth became Incarnate, and that truth He taught to men, so that we might behold and be moved by His glory. In very simple terms, He taught that truth while He lived on earth - simple terms, but terms pregnant with meaning, to start men out on the path toward understanding. And now, at His Second Advent, He has revealed the inner meaning of all that He then said and did - the love that motivated His words and now, at the infinite wisdom concealed within them.

The Word was, indeed, made flesh, that He might behold His glory. And it is for this, O Lord, that we would thank Thee at this Christmas season. It is for this that we would praise Thee, and acknowledge Thee to be our God.
