= Crown of Revelations - A doctrinal study
By Alfred Acton, M.A., D.Th.  1934
// include::../template-attributes.adoc[]


by Alfred Acton, M.A., D.Th. Dean of the Theological School of the Academy of the New Church

1934

To + 
E. C. A. + 
A Lover of the Writings

////
I. THE HISTORY OF THE DOCTRINE CONCERNING THE WRITINGS

II. THE WRITINGS ARE THE WORD FOR THE NEW CHURCH

Do the Writings refer to themselves as the Word?

The Writings and Correspondences

Conjunction with Heaven by the Writings

Holiness to be Predicated also of the Writings

III. THE APPLICATION TO THE WRITINGS OF THE TEACHINGS CONCERNING THE
WORD

The Word is Divine Truth

The Word Contains a Spiritual Sense hitherto unknown

The Sense of the Letter is the Basis, Containant and Firmament of the Interior Senses

In it Divine Truth is in its Fullness, Holiness and Power

From it is to be Drawn the Doctrine of the Church

Genuine Truth does not Appear in it save to those in Enlightenment.

By it there is Conjunction with the Lord and Consociation with angels.

The Word is in the Heavens. The Church is from the Word and according to the understanding thereof.

Everything in the Word is the Marriage of the Lord and the Church.

Heresies may be taken from the Sense of the Letter.

The Lord Fulfilled the Word. There was a Word that is lost. By the Word those also have Light who have not the Word.

Without the Word there would be no Knowledge of God, of Heaven and Hell, etc.

IV. CONCLUSION
////

<<<

THE CROWN OF REVELATIONS

This (the disclosing of the spiritual sense of the Word by the Lord through me) is more excellent than all the revelations that have hitherto been made since the creation of the world (Invitation 44).

The New Church is the Crown of all the churches that have hitherto existed on earth (@TCR 786, Invitation 53).

== I - THE HISTORY OF THE DOCTRINE CONCERNING THE WRITINGS

Some day, I suppose, there will be written for the New Church a history of Doctrine. Many such histories have been written for the first Christian Church, but naturally they deal with the interpretation of the New Testament, and of the Old Testament in the light of the New; that is to say, with doctrines drawn from those Testaments; such doctrines, for instance, as the Trinity, the Atonement, Faith and Charity, Baptism and the Holy Supper, etc. The genuine doctrine of the Old and New Testaments with respect to these subjects has been set forth in the Writings so clearly and unmistakably that there is no dispute concerning them among any who accept those Writings as a Divine Revelation. New Churchmen of every school of thought are wholly at one in seeing that there is one God only; that there are not three Divine Persons but that the Trinity is in the Lord Jesus Christ; that faith does not save without charity; that all men are predestined to heaven, etc., etc.

It was similar in the beginning of the Christian Church; Christians were in general agreement in accepting the genuine doctrine of the Old Testament as plainly unfolded in the New. Divisions arose not on this point but in respect to the true interpretation of their own revelation. Hence those disputes and schisms which have culminated in the countless sects of modern Christendom, and which differ from each other solely in their interpretation of the New Testament.

So in the New Church questions have arisen concerning the genuine interpretation of the Writings given to that Church, and many different views have been put forth during the years that have elapsed since its establishment. Indeed, few as these years are, the literature of the New Church dealing with the interpretation of the teachings of the Writings is rich in abundance and will afford a fertile field for the researches of the future historian of the development of doctrine.

Foremost among the questions which will be dealt with in such a history will undoubtedly be the doctrine concerning the Writings themselves, which is the question which I propose more particularly to discuss in the present study. In the absence of a history of that doctrine, let me commence with a brief outline of its development.

In the years 1771-1772, even when Swedenborg was still living, the Reverend Sven Schmidt, a clergyman of the Skara Diocese of the Lutheran Church in Sweden, openly proclaimed that the Writings are a new Gospel revealed by God, even as Matthew, Mark, Luke, and John had been revealed, and the claim was consistently maintained by Mr. Schmidt throughout the series of investigations to which he was subjected by the Bishop of Skara and his Consistory. (A typescript copy of the Minutes of these investigations may be consulted in the Library of the Academy of the New Church.) It may be added that Mr. Schmidt seems to have stood entirely alone; for there is no evidence that he held any communication with other receivers of the Writings.

Some years later, in 1776, Doctor Beyer, in a letter to Nordenskiold (Printed in New Church Life, 1930, p. 324 seq.), expressed his views concerning the Writings at some length. Of the portions of those Writings where the spiritual sense is expounded he says: "This sense is the Word itself and is the holy in the Word. The same has been dictated to the Assessor from heaven (@AC 6597) equally as the Word in the letter was dictated to the Prophets. It is not a new Divine Word but an unveiling in the Word we have had, which is the crown of all heavenly revelations." As to the doctrinal portions, "the Apostle did not receive the least thing thereof from any angel but from the Lord alone (@TCR 779; @DP 135; AR Pref.). The Doctrine is thus divine as to all its contents, and effects immediate communication with the new Christian heaven." Of the descriptions of the spiritual world, Doctor Beyer says that Swedenborg's preparation "gives full assurance of inerrant truth"; and in this connection he refers to the Writings as "holy books." Of their philosophy and science he says that "illumined by light from the other world . . . they become true and infallible."

With the establishment of the Church in England, where in 1788 a new Priesthood was inaugurated "under the auspices of the Lord," there gradually developed two conflicting views of Swedenborg's Writings. By some those Writings were held to be "the Word of the Lord as positively as the writings of any of the four Evangelists"; others, however, while allowing that Swedenborg "was highly illuminated by the Lord, and that his Writings are highly useful in opening the spiritual sense of the Word," could not allow that they were "upon an equal footing with the Word itself; for none can be the Word but the Lord alone."

These two views were set forth in a letter printed in the Aurora (a New Church monthly) for September, 1799. In their comments, "the editors (of that journal) and several of their respectable correspondents conceive that E. S. as to his theological writings is no more an author than Matthew, Mark, Luke or John, but a scribe of the Lord. . . . We do not pretend to say that the whole of his theological writings are the Word of the Lord. We say that what he hath written is strictly true - his relations real facts - that there is no error or mistake in them - that he was under the peculiar direction of the Lord, and that his Arcana in particular is no other than the Lord's own Word opened and exhibited in its internal sense, and therefore is infallible truth."

These remarks called forth from the Manchester Society a protest which appeared in the Aurora for December, 1799. There it was held that the difference between the Word and the Writings is, that while the former "contains infinite treasures of Divine Wisdom which neither man nor angel can comprehend," the latter are "mere explications of the hidden wisdom of the Holy Book adapted and brought down to the capacity of man, but not containing anything above that capacity." They therefore "bear witness to the internal sense of the Holy Word and teach in part what that sense is." This proves that they themselves are not the Word just as the fact that John the Baptist bore witness to the Light proves that he was not the Light itself. The Writings are to be considered not as the Word but "as doctrines derived from the Word and instrumental to the opening of the internal spiritual sense."

In the same number of the Aurora appeared a letter from John Augustus Tulk in which he quoted numerous passages from the Writings, from which "it appears that the revelation contained in the above writings is an opening of the spiritual or internal sense of the Word, together with the genuine doctrine of the Word, and that by this revelation is understood the second coming of the Lord"; that Swedenborg disclaims taking anything from any other source than "from the Lord alone whilst he was reading the Word," and consequently that he is in no sense to be regarded personally in the revelation any more "than are the prophets or apostles"; that what is revealed through him is "the soul of the Word," the literal sense being its body. Both "are holy and divine as proceeding solely from the Lord through the instrumentality of men, and can in no wise be separated. Of the Word in the letter it may be said, Here is the Divine Word veiled; of its spiritual sense and of its genuine doctrine it may be said, Here is the same Divine Word in its power and great glory."

Mr. Tulk's letter was followed by a communication signed by fifteen members of the Kingston-upon-Hull New Church Society wherein they specifically identify themselves with those "who esteem the Writings really as the Word of the Lord itself, particularly his Arcana."

The subject was further discussed in the Aurora for January, 1800. There one correspondent asks, "Can any one suppose for a moment that the Word in its glory is less Jehovah because E. S. was its vehicle?"
And later he adds: "As the doctrines from the internal sense of the Word will establish a church that will be the crown of all churches, so the internal sense of the Word itself is the crown of all dispensations." The Manchester position is again presented in a communication declaring that while the Writings "contain a real revelation from the Lord," yet they are not the Word because they do not contain the supreme or inmost sense of the Word but only the internal sense. Moreover, in the Word all things are infinite and incomprehensible to men or angels, while in the Writings they are finite and comprehensible; and furthermore, the Word has an internal sense, while the Writings have no other sense than what is opened in the letter.

In the same number of the Aurora, the members of the Kingston-upon-Hull Society controvert the views of the Manchester School. But while holding that the Writings are the Word because written under the direction of the Lord, they yet add that they "ought not to be called the Word independent of or separate from the Sacred Scriptures, but the spiritual sense of the Word revealed by the Lord through the Sacred Scriptures."

The discussion is closed by an anonymous writer who points out in opposition to the Manchester School that the Writings are an "immediate" revelation from the Lord. But the particular interest of his letter consists in the notice he gives of a third view that had been put forth in the Church, namely, that the Writings are merely human writings like the Epistles. His adverse comments on this view indicate that he considered it to be essentially the same as that of the Manchester School.

There was no further public discussion of the status of the Writings until 1802 when an anonymous author published a pamphlet entitled "Two Discourses on the Internal Word of the Lord as opened in the Writings of Emanuel Swedenborg." Here the writer shows that the essential Word is the internal sense of the Word and not the Letter;" therefore, as in the Writings we have that internal sense or meaning dictated by the Lord himself, surely that which constitutes its sanctity which the Lord himself dictates or speaks, and which approaches nearest to its essential must be as much the Word of divinity and origin, the speaker as that which is the most remote from its essence and is only deemed holy because it contains such divinity." It "does not cease to be divine because of its natural clothing. It cannot be less the Word of God, less the internal sense thereof, because the Lord has delivered it by means of an enlightened and inspired mind in natural language." The Lord has not given a new Word, but by means of Swedenborg He has opened the interiors of that same Word which was given in ultimates by the Prophets, and has brought down heavenly truths to the capacity of the rational mind. It is the internal sense and not the letter which is the Word of the Lord in the heavens, and by this internal sense now opened to the New Church "we may have communication with heaven, with angels, and with the Lord." The writer therefore has no hesitation in declaring that Swedenborg "was as much illuminated and inspired to understand and open the internal sense of the Word of God, as any of the prophets and evangelists were to speak and write the letter or ultimate thereof"; that "they were really dictated from the Lord," and consequently "are as much the Word with respect to its spiritual sense as the writings of the Evangelists are with respect to its literal sense; for it appears that the Lord dictated to their mind or brought to their remembrance all things whatsoever he had said unto them. And whatsoever the Lord dictates whether to the spiritual or rational mind, is His Word."

The author's reasoning, which is fortified throughout by an abundance of quotations from the Writings, concludes with an appeal to the members of the New Church: "Let us who have this Word acknowledge it as the Word and use our utmost endeavors to propagate the glad tidings of salvation therein contained! Let us boldly own the Lord in his second coming. . . . 'He that hath a dream, let him tell a dream'; but we who have the Lord's Word, let us speak this Word faithfully."

The reading of the discussion here reviewed leaves one with the impression that the belief that the Writings are the Word found many adherents among New Churchmen in England. Yet the event shows that it was the Manchester School of thought that finally prevailed; for after 1802 nothing more is said of the question and the New Church both in England and America contented itself with the general acknowledgment that the Writings are a Divine Revelation of the internal sense of the Word.

This position of affairs continued until the early sixties when, owing to the activities of Mr. Benade and his associates, the status of the Writings became a very active question in the Church. Mr. Benade and his group of sympathizers stood for the Divine Authority of the Revelation. Indeed, Mr. Benade went further. In 1861, he openly stated to the Pennsylvania Association that the Writings are the Lord's Word to the New Church; and in 1873, the statement was repeated before a meeting of Convention ministers in Cincinnati.

With the establishment of the Academy in 1876 and the appearance of its journal, Words for the New Church, the question of the status of the Writings became more than ever a subject of active debate in the Church. The Academy, however, did not specifically claim that the Writings are the Word. Its position was rather that they are an immediate Divine Revelation and so are the sole authority for the guidance of the Church. Yet the logical conclusion that the Writings are the Word was not ignored, and in private correspondence, conducted in the early 1880's, one of the leaders of the Academy expressed the opinion that the Writings should be openly proclaimed as the Word. Publicly, however, except in the New Church Tidings of which we shall speak presently, emphasis was not laid on the Writings as the Word but on their Divine Authority - which essentially amounts to the same thing. This continued until the establishment of the General Church of the New Jerusalem. The latter body, almost from its inception, has steadily preached the doctrine that the Writings are the Word for the New Church, preaching it as the one and only logical consequence of the doctrine of the Divine Authority of the Writings.

Meanwhile, Conference and Convention continued in their general acknowledgment of the Writings as a Divine Revelation. With the rise of the Academy, however, they naturally could not remain static in this position. If the Writings are acknowledged as a Divine Revelation, and yet are not the Word, something must be said in explanation of what appeared to be two contradictory positions. Therefore, in 1902, the Reverend James Reed, acting on behalf of a committee appointed by the ministers of the Convention, propounded the doctrine that the Writings are a Revelation not of all the internal sense of the Word but only of some part, being that part which is understood in the natural heavens; and that, being thus limited, they are inferior to the Word though superior to all other books. This position was tacitly though not formally accepted as the position of the Convention. What has subsequently come up in the Convention with regard to this question has all tended in the direction pointed out by Mr. Reed and his committee; and at the present time, while some in the Convention hold that the Writings are of Divine Authority, yet the leading position seems to be that they merely give us the method of drawing out the internal sense of the Word, and that, with this before us, it devolves upon us to go to the Word for ourselves, and there to discover further arcana.

Going backward a few years, we find that in the early 1890's, the Reverend E. S. Hyatt, writing in the New Church Tidings, of which he was the editor, taught not only that the Writings are the Lord's Word to the New Church, but that, being the Word, we must apply to them all that they themselves teach concerning the Word. Mr. Hyatt judiciously added that this application must be made with due reserve, his meaning being that in certain passages the term " Word " is evidently used only of some specific revelation. But although Mr. Hyatt's position was set forth and illustrated in a number of articles appearing in the Tidings, it is a curious fact that practically no notice was taken of this position by the journals of the Church, including New Church Life. The silence of the latter is probably due to the fact that the Tidings and the Life were engaged in a common cause, the upholding of the absolute Divine Authority of the Writings, as against opponents in the Convention. Mr. Hyatt's position was tacitly accepted as being the logical development of the Academy position and implicit in that position. It was probably for this reason that the editors of the Life did not make any note of it. I myself remember both reading Mr. Hyatt's articles and discussing them with him; I remember also that his position came to me not as something strikingly new but as a natural extension of the doctrine that had long been familiar to me.

It was this same position that I maintained in 1920 in an address delivered in Colchester, England, and I remember that in writing this address I had no thought that it contained anything fundamentally new.

Previous to 1920, the Life had occasionally discussed the implications of the doctrine that the Writings are the Word, and had shown that they must therefore be considered as having been written by correspondences and as having an internal sense - not, however, in the same way as the Old and New Testaments. Their correspondences were the correspondences between natural and philosophical truths on the one hand, and spiritual truths on the other; and their internal sense was to be sought not in the interpretation of symbolic language but in the deeper meanings and implication of the truths plainly revealed.

In recent years, a new position has been taken, a position which its proponents hold to be the orderly development of the doctrine of the Academy and the General Church. It is also claimed that this new position is closely related to the position taken by Mr. Hyatt in the New Church Tidings. But this claim fails to note a vital distinction between the two positions. While Mr. Hyatt held that what the Writings said concerning the Word must be applied to themselves, but with due reserve, the new position abolishes every reservation. According to the new position, the Writings are a revelation written in the language of correspondences in the same way as the Old and New Testaments; they are a dense veiling of the Divine Truth; and the veil can be pierced only by expounding the language of the Writings in the same way and according to the same laws that are necessary for the expounding of the Old and New Testaments; only thus, says the new position, can we possibly arrive at the spiritual truths which are to characterize the New Church.

To some, this position may seem to be the logical consequence which must follow if the Writings are indeed the Word; and we can well imagine that there are not wanting those who, when they see that this new development is opposed by ministers of the General Church, experience a sense of humor at what they regard as the reductio ad absurdum of a position to which they themselves have been steadily opposed.

My object in the present study has been to ascertain, in the light of the Writings, what truly is involved in the doctrine that the Writings themselves are the Word. For this purpose I have deemed it to be sufficient to review the predicates of "the Word" as given in the Doctrine of the Sacred Scripture. This I shall do under the principle of interpretation that when the term "the Word" is used as meaning Divine Revelation, what is said of it is applicable to all forms of Divine Revelation; but not so when it is used specifically of some particular revelation. This is the "reserve" to which I have already referred as having been maintained by Mr. Hyatt. Before entering on this examination, however, I should like to make some general observations, first on the relation of the Writings to former revelations, and second, on the term "the Word" as applied to the Writings.

== II - THE WRITINGS ARE THE WORD FOR THE NEW CHURCH

That the Writings are a Divine Revelation, and consequently are the Lord's Word to the New Church in the same sense that the Ancient Word and the Old and New Testaments were the Word to the churches which were instituted by their means, must seem indisputable to any one who believes the New Church to be a New Church established by the Lord in his Second Coming. But to argue from this, that what is said of one Word is necessarily true of all, is to fail in the observance of rational discrimination. As well might we argue that the form of instruction given to adults is the same as that given to children. The Ancient Church, the Jewish Church, and the Christian were essentially different, and their differences are due solely to the differences in the nature of their Word.

Thus the Ancient and Jewish Churches were representative churches because the revelations on which they were based were written in the language of representations and types. The revelation to the Christian Church, on the other hand, is not characteristically a revelation veiled in the language of types. In the New Testament the Lord Jesus Christ himself is the Teacher, and his teachings are clear and open, even though couched in simple and parabolic language. Hence the Christian Church was not a representative church. Indeed, with the exception of Baptism and the Holy Supper, representatives were abolished and the church was characterized not by ritualistic and typical worship but by the preaching of the Gospels, and the exposition of the truths there openly revealed. This is plainly indicated by the Lord himself in the New Testament when he declares: "Ye have heard that it was said by them of old time . . . but I say unto you" -that is to say, in the New Testament the Lord speaks in clear and open language.

In this connection, I am reminded of something I have read in The Word Explained and which may aptly be quoted here: "In the primitive church, things yet to come lay inmostly concealed in every object, and inmostly in the lives of the patriarchs. Later these things were encompassed with types as with coverings, even to the temple of Jerusalem. When the Messiah came, he drew off the outmost coverings; for he taught by similitudes. By his apostles, interior coverings were drawn away; and finally, at the end of days [that is, in the Second Coming], the more interior and inmost things will come to view" (WE 1196).

"At the present day, the Messiah does not deal with men without persuasion, as he did in times of old when he gave commands without any interpretation of their causes. Then all things were in types, but now it is a different matter. When man is able to understand causes, and the Messiah has unveiled mysteries, then He tells the causes; but previously this was not the case. It is like as with a father leading his sons. During their infancy he leads them as infants; afterwards he instructs and educates them as boys and young men, and finally as adults. This is the cause of the many changes in the Church, and the reason why the Messiah does not deal with men in the same way at this day as of old; that is to say, why He speaks, not in veiled words, but in words unveiled and explained; not by miracles, but by intellectual persuasions" (n. 1108).

To one who acknowledges the Writings to be a Divine Revelation, it is quite obvious that they are "the Word" if by this term is meant a specific revelation by the Lord which constitutes the Divine Authority from which the Church is to derive its distinctive doctrine and quality. But some there are in the New Church who while acknowledging the Writings to be an immediate Divine Revelation are yet more or less unwilling to call them the Word, and this for one or more of the following reasons: 

(1) The Writings when speaking of "the Word" clearly refer to former revelations; they do not call themselves the Word.

(2) By "the Word" is meant the Word written in the language of correspondences; the Writings are not so written.

(3) The Word is the uniting medium between heaven and earth, since when man reads the letter the angels perceive the internal things which are correspondentially contained therein; this is not the case with the Writings.

(4) The Writings do not have the holiness which characterizes the Old and New Testaments.

Let me briefly examine these reasons:

=== DO THE WRITINGS REFER TO THEMSELVES AS THE WORD?

(1) That the Writings, when speaking of the written Word, usually refer immediately and directly to the Ancient Word or the Old and New Testaments may be granted. It may not perhaps be so readily granted that the Writings never call themselves the Word, for there are several statements in those Writings which can fairly be interpreted as meaning that they do so call themselves. (In The Testimony of the Writings Concerning Themselves, Bryn Athyn, 1920, these statements are gathered together under the headings: "That the Writings are the internal sense of the Word." "That the internal sense of the Writings is the Word," and "that therefore the Writings are the Word.") These statements, however, have received different interpretations, and by many are not regarded as conclusive. We shall therefore assume that the Writings do not specifically refer to themselves as the Word; certainly they do not so refer to themselves in language so unmistakable as to force conviction even on the reluctant or unwilling. Not only do we grant this but we go further and assert that such reticence is an integral part of a revelation made for the establishment of a genuine spiritual church.

In the case of the Old Testament, and especially of the Pentateuch and the Prophets, it is quite easy to show that this Testament is a Divine Word revealed by God, and that it is to be obeyed as such. This is the case because the church to be established by the Old Testament was not a genuine church but the representative of a church. As a consequence, the external revelation made for the establishment and preservation of this church must necessarily have been a revelation which compelled acceptance; for which reason also that revelation was accompanied by compelling miracles.

In the case of the New Testament, on the other hand, it would not be so easy to show from its own statements that this Testament is the Word of God. Of the twenty-three direct references made in the New Testament to "the Scriptures," to say nothing of the many indirect references, there is not a single one which does not directly and exclusively refer to the Old Testament. Nor in the whole of the New Testament can there be found a single statement that proves beyond cavil that that Testament is also "Scripture." The Lord does indeed say "the words that I speak unto you are spirit and are life" (John 6: 63); and in the Apocalypse, John is indeed commanded by God to write what he had seen (Revelation 1:11, 19) but of these and similar statements the same can be said as was said above with respect to certain passages in the Writings, namely, that while they might strengthen and confirm the believer, they cannot be regarded as being so clear as to compel belief. The reason is obvious. The Christian Church was to be a church founded on the genuine acknowledgment of the Lord and his Word, and such acknowledgment must come from perception of the truth and not from external persuasion.

How much more then is this the case with the Writings which are given for the establishment of a spiritual-rational church! No rational church could possibly be established by a revelation which compelled belief. The Writings do indeed come to us as a Divine Revelation, yet in such a form that many find it easy to read and totally reject them; others find much that is good in them but reject the idea that they are a Divine Revelation; while others accept them as in some sense a Divine Revelation, but will not for a moment entertain the idea that they are "the Word" or are even comparable with the Word. That the Writings are a Divine Revelation is openly declared in those Writings themselves, and this is generally acknowledged by New Churchmen. But beyond this the Writings declare nothing that is externally compelling. Consequently men find it possible to accept them as a Divine Revelation, and yet to regard them not as the Lord's Word but as some kind of auxiliary revelation designed to open the Word and make it of service to men. They are free to do so, so far as any externally compelling passage in the Writings is concerned; free to think that the Word is a sealed book, which can be unsealed and so can be made available for the use of man, only by means of a revelation which is inferior to "the Word."

Most Christians regard the Old and New Testaments as the Holy Bible or Word. In great part this is the result of training, and of an inherited tradition that is so strong as almost to amount to instinct. If we reflect, we can perceive something of this in ourselves; for we find that to acknowledge the divinity of "the Word," "the Sacred Scriptures," "Holy Writ," "the Bible," is so natural as almost to be spontaneous; so harmonious with our habits of thought that we feel a shock if we hear anything said that is openly disparaging to the Scriptures, or that tends in any way to modify our conception of them as the only Word, unique in divinity and unique in holiness. It is for this reason that many New Churchmen, and perhaps most, feel somewhat of a shock when first they hear that the Writings are also the Word. "The Holy Word! Yes, I can believe in that (so runs their thought), it is God's own Word to us. But to say the Writings are the Word! They were written by Swedenborg; he quotes passages from the Word to confirm what he says; he uses rational arguments." They may add, "I believe, of course, that what Swedenborg writes was revealed to him by the Lord, and consequently that his writings are a Divine Revelation. But to say they are the Word!" Such is the common reaction with those who from childhood have cherished the idea that the Old and New Testaments are alone the Word, when first they hear the Writings proclaimed as being also the Word. And those who have come to see that the Writings are the Word may feel something of the same reaction when first they contemplate all that is involved in that acknowledgment.

This, I take it, is a protection to the New Church; for in this way men are guarded against acknowledging the Writings as the Word except as they truly see them to be the Lord's teaching, and acknowledge that teaching to be the sole rule and guide of their life and faith. The acknowledgment is to come, not from tradition or upbringing but from internal conviction; from that "self-evidencing reason of love" which alone can establish a genuine spiritual church (Canons, Prologue).

=== THE WRITINGS AND CORRESPONDENCES

(2) Another objection to calling the Writings "the Word" entertained by those who yet believe they are a Divine Revelation, is that by "the Word" they understand a book or books written in correspondential imagery, or symbolic language; written that is to say, in the prophetic style, or in the form of a narrative describing earthly things or earthly events, which while corresponding to spiritual things, are in themselves more or less remote from spiritual things. If this truly describes the essential properties of "the Word," then the Writings are most certainly not the Word, as can be seen at once from a cursory reading of them. That the Word is written in correspondences must be admitted; for it is a revelation of spiritual things, and these cannot come to man unless they are clothed in corresponding natural language. But is the language of symbols the only form whereby spiritual truth can be presented in corresponding natural garb?

The Writings teach that the Word was written throughout by mere correspondences (@DSS 20). It is easy enough to see this in the story of the Garden of Eden and of the Tower of Babel, in the lives of the Patriarchs, the statutes of the Israelitish Church, the chronicles of the Kings, etc. But what, shall we say of those parts of the Word where the spiritual sense shines through? Take, for instance, the following:
"He hath showed thee, 0 man, what is good, and what doth the Lord require of thee, but to do justly, to love mercy, and to walk humbly before thy God" (Micah 6:8); "Thou shalt love thy neighbor as thyself"
(Leviticus 19:18); or the Lord's words: "But I say unto you, Whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart" (Matthew 5:28). I might quote innumerable passages of the same kind, but they are so well known that there is no need of further citation. Are these passages also written by correspondences? Seeing that the Word "is written throughout by mere correspondences," I answer unhesitatingly, Yes, and in this I suppose all New Churchmen will agree with me. But reflection upon the answer must bring to us the conviction that the idea of correspondences cannot be limited to physical objects or historical events, and still less to such objects and events when they convey meanings remote from the spiritual sense, and even opposite thereto.

Because certain portions of the Old and New Testaments are so written that the spiritual sense shines forth in the sense of the letter, it does not follow that these portions are not written in the language of correspondences. As well might we argue that the mild and gentle expression of a good man does not correspond to the spiritual charity that rules in his heart. Everything in the world and everything in man's speech and actions and in his natural thought and affection has its correspondence in spiritual things, and these it represents or sets forth to the view whether in clear language or obscure.

If we examine the correspondences used in the Word, we shall find that they are in general of two kinds, namely, those which consist of physical objects, plants, animals, etc., and those which consist of human thought and will, and speech and action. And each of these may again be divided into natural correspondences and permissive correspondences (By this term I wish to express correspondences or representatives which have been adopted from the Jewish Church as representing the things of heaven but which in themselves are not correspondences of things heavenly - as, for instance, animal sacrifices, the command to kill women and children, to hough horses, etc. These are what are referred to in that teaching of the Writings which shows that the Word would have been written differently had it been written among another people. They are also involved in the fact that a second writing of the Decalogue was substituted for the first which Moses in his anger had broken. See @AC 10453, 10461, particularly 10603.). In those that are natural, whether physical or human, the spiritual sense shines through more or less clearly, and something of it is at once perceived; or, to put the matter in another way, the correspondential language is such that it is the natural and spontaneous expression of the spiritual truths within. Thus in the passages, "The Lord is a sun and a shield" (Psalms 84), "He maketh his sun to arise on the evil and on the good" (Matthew 5:45), the correspondences are self-explanatory, and the general spiritual sense is at once apparent. So in the passages, "Wash you, make you clean, put away the evil of your doings from before mine eyes; cease to do evil, learn to do well" (Isaiah 6:16, 17); "Thou shalt love thy neighbor as thyself."
This will become clearer when we come to speak of "the sense of the letter of the Word."

Now these and many other like passages that might be quoted are just as much written in correspondences as are those portions of the Word where the spiritual sense is not apparent but is thickly veiled. In both cases, the Divine Truth is clothed in the language of correspondences; but in the one case the correspondential clothing is in the form of natural correspondential objects, or of corresponding natural ideas and moral truths, while in the other case the clothing is taken from the events of history, or from the Jewish mind with its debased ideas and its characteristic cruelty and idolatry. In the one case the veiling is transparent so that all who will can see something of the spiritual truth within; in the other case, the veiling is so dense and thick that in the mere letter, it sometimes presents what is even opposed to the spiritual truth within, and that spiritual truth can be seen only by entirely removing, as it were, the letter.

There is a difference also in the method of interpretation of these two classes of passages; for in the one case the natural truth presented, or the natural image, is simply unfolded and opened up, the natural truth or image still remaining but gloriously infilled. In the other case, the opening of the spiritual sense will abolish, as it were, the sense of the letter. Thus if we see the spiritual sense of Solomon's dedication of the temple, or of the cruel wars of the Israelites, then the bloody sacrifice of ten thousand animals, and the savagery of the Jews disappears from our sight, and we fix our gaze on spiritual things which are far removed therefrom. How different is the case when we see the spiritual sense of the words "The Lord is a sun and a shield." As soon as the Christian hears these words, he at once sees that the Lord is the source of that heat and light which bring comfort to the mind of man, and that He guards against all evils. However natural the idea that comes to him, yet, if he reads the Word holily there is something spiritual within that idea, and his further progress depends on his penetrating more deeply into this something, as the Lord gives him more clearly to see it. So in the words, "Thou shalt love thy neighbor as thyself." The idea of the neighbor may be a merely natural one, yet to the devout Christian the spiritual idea is involved in the love of that neighbor; and however deeply he may enter into the arcana contained in the words, those words will still remain as the true and correspondential clothing of those arcana. And here we may note in passing that the four Gospels are much more characterized by a letter in which the spiritual sense thus shines forth than are the books of the Old Testament.

It is clear, therefore, that the Writings cannot be differentiated from "the Word" on the ground of the one being written by correspondences and the other not. Spiritual truth can be revealed in no other way than in corresponding natural language and so in the language of correspondences. "The sense of the letter of the Word (we read) is the basis into which the spiritual ideas of the angels terminate; nearly in the same manner as words are the basis into which the sense of the thought flows and is communicated to another" (@AE 356 fin.). But the words, that is to say, the correspondences, may or may not be "remote" from the internal sense (@DSS 102).

The difference between the Old and the New Testaments and the Writings is not in their being written by correspondences but in the nature of the correspondences. In the Old Testament, the correspondential clothing is, for the most part, a Jewish one. Therefore we are told that "in the sense of the letter of the Old Testament interiors rarely stand forth" (@AC 3373). In that Testament it is only here and there that the spiritual truth appears clothed in its own shining garments. In the New Testament, excepting the Apocalypse, the clothing consists for the most part of spiritual-moral truths learned by the disciples from the Lord's own mouth; and to that extent it openly presents more or less of the spiritual sense within. In the Writings the clothing is a rational one, gathered by Swedenborg under the Divine guidance by the reading of the Old and New Testaments and by the study of nature in the light of a genuine philosophy. This clothing sets forth the Divine Truth in its glory. Yet it is a clothing; and men may read it and see nothing of the spiritual truths within, seeing merely an intellectual system of philosophy or theology wherein, for them, the spiritual truth lies concealed; or they may read it and see the Divine Love and Wisdom enlightening them in interior arcana such as have never before been given to the world. It is for this reason that the revelation made in the Writings is said "to be more excellent than all the revelations that have hitherto been made since the creation of the world"
(Invitation 44)

The difference between the various revelations is reflected in the nature of the churches instituted by those revelations. The Jewish Church was in representatives and its worship consisted in ritual. In the Christian Church purely ritualistic worship was abolished and the open preaching of the Gospels took its place; for its revelation was an open one. In the New Church also purely ritualistic worship is abolished, but in that church it is spiritual truths that are to be preached, and being seen rationally, these truths will reveal the presence of God Man even in nature and its science and philosophy.

The three revelations have each their letter. The letter of the one may be compared to a coarse garment, the letter of the other to a more seemly and beautiful garment, and the letter of the Writings to a magnificent garment, and this despite the fact that when seen merely as a garment those Writings may appear simple and unadorned. Paul's words to the. Corinthians, "The letter killeth but the spirit giveth life," apply equally to all three revelations; for no revelation is living with a man or a church unless the Lord himself is seen therein. Without this, the letter gives not life but death.

While on this subject, I should like to add some reflections on the letter of the Gospels and that of the Apocalypse. As already stated, the letter of the Gospels consists for the most part of spiritual-moral truths which, provided they be read as coming from the Lord, reflect the spiritual truth within. Still the Gospels contain also obscure passages which, like the majority of passages in the Old Testament, seem thickly to veil the truth. The reason seems to be that at the commencement of the Christian Church it was only to a limited extent that genuine truths could be revealed. The Church had to progress from the former state of mere representatives and rituals to the perception of genuine truths, and this could be done only in time. Therefore in the Gospels, while for the most part truths are openly set forth in general but genuine form, yet the merely representative style of the Old Testament could not be altogether abolished.

As to the Apocalypse, this was a book prophetical of the New Church, and its contents were sealed because, though it was necessary that they be presented on earth as the basis for angelic thought and for the hopes and aspirations of the good on earth, yet men could not then enter into them.

=== CONJUNCTION WITH HEAVEN BY THE WRITINGS

(3) A third objection which New Churchmen have entertained against thinking of the Writings as "the Word" is that they understand it to be the peculiar prerogative of the Old and New Testaments to serve as a medium conjoining angels and men, this conjunction being effected when men read the letter; for angels are then in the spiritual sense of what is read. This they suppose cannot be the case with the Writings since the Writings are themselves the spiritual sense.

A little reflection will show that such a position involves that the Word serves as a medium between heaven and earth only when man is in ignorance of its spiritual contents, or that it is the letter that conjoins and not the spiritual sense within the letter. But if such were really the case, what shall we say of those parts of the Word where the spiritual sense shines forth? Is not the conjunction of angels and men effected by those parts also? nay, and a closer conjunction?

There are indeed passages in the Writings which teach that the conjunction of heaven and earth when man reads the Word is effected when the man reads it without an understanding of its spiritual contents, provided only he reads it with an acknowledgment of its holiness; and consequently, that such conjunction is more frequently effected when children read the Word than when adults read it. But to take such passages to mean that man's entering into the spiritual sense detracts from or weakens this consociation, is to reduce the teaching to absurdity. I shall again refer to this matter a little later.

Here I would ask for a more particular attention to what is involved in the teaching that if the Word is to conjoin man with heaven, it must be read with an acknowledgment of its holiness. Clearly it is this acknowledgment that effects the association with angels; without it there could be no such association. It was because of this that the Israelites, when engaged in their rituals, were induced - for the most part by compelling external means - into a state of awe and reverence, that is to say, into a state of apparent holy acknowledgment. Only then could their rituals serve as the medium between heaven and earth; for otherwise the spheres of their evil loves would have been sensated in the spiritual world and would have repelled all association with good spirits and so with the angels who are associated with such spirits. With the Israelites, the mere reading of the Word, or the mere enactment of the rites there laid down, could not have brought even the presence of good spirits; there was also required a state of awe and fear whereby the evils of the Israelites were temporarily concealed and so could not affect good spirits, and prevent communication with the angels of heaven. It was for this reason that Balaam was hindered from cursing the sons of Israel, that so their evils might not be laid bare to the gaze of good spirits (@SD 1778, 2354).

It is, therefore, not the mere reading or enactment of the Word that effects the consociation of angels and men, but the sphere engendered when the Word is read holily. When the Word is thus read, good spirits and angels are present with the man and perceive the spiritual things that are concealed within the sensory images in the man's mind. Thus heaven and earth are conjoined by means of the Word only when read by men who acknowledge its holiness, and who thus tacitly acknowledge that within its bosom lie truths ineffable.

And now I again ask, Shall we say that this conjunction of man with angels is weakened if the man sees something of the spiritual sense of the words that he reads? Shall we say that he is more closely conjoined with heaven when, with holiness, he reads those portions of the Word where the spiritual sense is thickly veiled, than when he reads those portions where the spiritual sense shines out and moves his thoughts and affections? that he is closer to the angels when he reads the statutes of the Israelites and their cruel wars, than when he reads the Sermon on the Mount?

There are indeed passages in the Writings which imply that the consociation of men and angels is more assured when men read the letter of the Word without entering into its hidden meaning, but such passages clearly have reference to an entering into the interiors of the Word from the man's own intelligence; otherwise why should we now be taught that there is a spiritual sense in the Word? why should that sense be revealed? and why should we be exhorted to think from the spiritual sense of the Word and not from its mere letter? Is not the revelation given that man may be more closely conjoined with heaven than ever before was possible?

The reading of the Word holily does indeed bring man into communion with angels, but if, when reading, he also has spiritual ideas like those of the angels, then not only is he conjoined with them but he is actually associated with them and, is it were, thinks and wills as one of them.

It can safely be said that the consociation with heaven enjoyed by true Christians when reading the Word was more intimate than that enjoyed by faithful Jews when reading the Hebrew Scriptures - for we cannot lose sight of the fact that even in the Israelitish Church it was possible for men to see something of the spiritual sense in the Hebrew Word. Shall we then deny the operation of the same law in the reading of the Writings? If those Writings are read in a spirit of holiness, with the acknowledgment that it is the Lord who is there teaching, do not they also bring consociation with the angels? and this even though the reader may not enter deeply with his understanding into the spiritual arcana involved? The Writings are a revelation of Divine Truth clothed in a letter which aptly and beautifully presents that Divine Truth under the garb of language perceptible to the bodily senses and comprehensible to the natural mind; and surely it cannot be denied that when a man reads them holily and with a view to his spiritual edification, he is thereby brought into Consociation with heaven. Can it be denied then, that if haply his mind is enlightened, and he enters interiorly into the meaning of what he reads, his consociation is still more close? To me it seems indisputable that when man reads the Word in the letter, whether it be the Old Testament, the New Testament, or the Writings, with an acknowledgment of its holiness, he is by that very fact conjoined with angels who perceive the interiors of what he reads; and that if he also can see those interiors, he is not only conjoined with angels but actually makes one with them in thought and in love.

That there may be no doubt concerning this office of the Writings in consociating man with heaven, let me adduce the specific teaching of the Writings as given in the Invitation to the New Church, n. 44. There, after stating that the revelation now given is more excellent than all the revelations which have hitherto been made, the passage continues: "By this revelation the communication of men with the angels of heaven is opened and the conjunction of the two worlds is effected; for when man is in the natural sense angels are in the spiritual sense."

In general it can justly be said that, granting that the reading is done with holiness, the reading of the Old Testament brings the presence of angels; the reading of the New Testament brings not only this presence but also some kindredship of thought and affection which is reflected in the perception of spiritual-moral truths; and the reading of the Writings enables man to think with the angels and as an angel.

And here I should like to add some observations with respect to the thoughts of the angels. It is often assumed that angelic thought is so far removed from human thought as to be ineffable. In a sense this is true - in the sense namely, that interior thought can be set forth in human language only inadequately; indeed, when we essay to express in writing our deepest thoughts and affections, it is a matter of common experience to find, when reading the writing, how inadequate are our words; how greatly we are forced to rely on the perception of our reader for the grasping of the many things which we would express but can express only feebly. But it is not true that angelic thought is ineffable, if by this is meant that man cannot think with the angels and as the angels. Man is a spirit, and he can become an angel even while on earth. True it is, that during life on earth, the things of time and space obtrude to obscure his thoughts, and that after death he is freed from these hindrances. But it is also true that at times, even on earth, he can elevate his thought and think with and as the angels. When the ministers of the Church teach the Word, what other end do they have in view than that men may think spiritually? Moreover, the fact that man can think spiritually even while on earth, is abundantly pointed out in the Writings of the Church, which while teaching that the letter of the Word is for men, and the spiritual sense for angels, also teach, and this again and again, that the spiritual sense is also for men who will think spiritually, that is to say, who will think as do the angels. Of what use otherwise are the Writings? the revelation of spiritual truths? of angelic wisdom? It is true that when we read in the letter the words "Abraham," "bread," "rain," "shield," etc., the angels have no idea of the natural images which these words present; but it is also true that the spiritual man, when reading these words, also fixes his mind and thought not on the words but on the spiritual ideas which they present. While on earth, the words also are before his sight, but this does not prevent him from seeing and delighting in the spiritual ideas contained in those words, and this to such an extent, that the words may disappear, as it were, from his view. Whether he thinks of them spiritually or celestially can be known to the Lord alone. It is enough for us to know that if we will, we can think as the angels think. Indeed it is possible for some men to think more wisely, more interiorly than some angels - a fact which is testified to by the teaching of the Writings that after death some men are at once elevated into an interior heaven.

When we die, we do not come into an alien world, an alien thought and speech. Death is but the continuation of life, and those who have thought spiritually and wisely on earth will continue so to think after death; nor will they notice any essential difference in the nature of their thought. Though this thought will then be unchecked by the hindrances of time and space, and of worldly cares and anxieties, yet essentially the thought will be the same. Why otherwise has the Lord made himself manifest in interior light? why otherwise do we pray daily that the kingdom of God may be established on earth as it is in heaven?

It is this entering into spiritual and angelic thought that is meant by the suggestion sometimes given in the Writings, that in the New Church intercourse with the spiritual world will be renewed somewhat as it was in the Most Ancient Church. Certainly men will never again consort with spirits as did the men of the Most Ancient Church; for in the New Church instruction is to be received not from any angel or spirit but from the Lord alone in his Word. But this quasi-renewed consociation of men with spirits will consist in the establishment of spiritual thought among men on earth; in the possibility, now given by the Writings, that man can think with the angels and as angels, even while clothed with a material body.

Before leaving this subject of the communication with heaven effected by means of the Word, I would note the teaching that every verse of the Word communicates with some society of heaven. "When I read the Word through, from the first chapter of Isaiah to the last of Malachi, and the Psalms of David (says the Revelator) it was given me clearly to perceive that every verse communicated with some society of heaven, and thus the whole Word with the universal heaven" (@DSS 113).

It has been supposed that a communication of this sort, that is to say, a communication with the societies of heaven in orderly series, could not be effected by the Writings. Reflection, however, will, I think, show that this supposition is not well founded. Certainly it cannot apply to the Arcana Celestia and the explanations of the Apocalypse where the Word is unfolded in series. Nor does it hold good as regards the other books of the Writings. It is not the mere letter of the Word that effects communication with societies of heaven, but the truths that are contained in that letter. This is obvious; moreover, it is clearly indicated by some words which were added to the passage last quoted, when that passage was inserted in the True Christian Religion. There it is said that Swedenborg perceived the communication with the societies of heaven when he read the Word from Isaiah on, "and held the thought in their spiritual sense" (@TCR 272).

When now we consider that every book of the Writings is an orderly presentation of the Heavenly Doctrine in series (see @TCR 351) the conclusion must inevitably follow, that the truths there presented, effect communication with the societies of heaven also in series. The Writings are a revelation of the Heavenly Doctrine in divine order, and so present the image of the universal heaven, that is to say, of the Grand Man.

Indeed the communication with societies of heaven by means of the Word, is of wide extension. It is true that any given verse of the Word, or any given aspect of truth as disclosed in Divine Revelation, effects communication with some society of heaven; but it is also true that the more interior the entrance into that truth, the more extended and universal is the communication; for inmostly in every verse of Scripture, in every truth of revelation, the Lord Himself is present, and thus the whole of heaven. Indeed the Writings are the Lord Himself revealed in human form as the Divine Man, and they must needs effect conjunction with the whole of heaven and with every society thereof.

The fact of such communication is moreover vividly presented to us by the Revelator, who tells us that "when the Brief Exposition was published the angelic heaven from east to west, and from south to north, appeared of a deep scarlet color with the most beautiful flowers" (Eccliast. Hist. 7); and elsewhere he adds that "this was a sign of the assent and joy of the New Heaven" (Documents 2: 281). It is also involved in the fact that when the True Christian Religion was finished the Lord called together His twelve disciples and sent them forth into the whole spiritual world (@TCR 791). Both these events indicate that the writing of the works referred to, established a communication with the societies of heaven whereby the angels were inmostly affected.

=== HOLINESS TO BE PREDICATED ALSO OF THE WRITINGS

(4) It is thought by many that it would be improper to call the Writings the Word because they are the internal sense of the. Word and so are not ultimate containants of the whole of the Divine Truth, whereas the Old and New Testaments, being a most ultimate revelation, contain in their bosom all spiritual and celestial truths, and so are holy. I shall speak more fully concerning this point later on in the present study. Here, however, it may be observed that so far as being ultimate is concerned, there is no difference between the Writings and other written revelations. Not only do they all come down to actual writing, but all are clothed in human natural ideas and words. That there is a difference in the nature of the ultimates has already been set forth; but this does not make the one more ultimate than the other. Whether I teach a child or an adult, I must speak in ultimate language based on ultimate natural images. True, in teaching the child, I may clothe my lesson in the garb of a story, and may illustrate it with a picture, but I must use words equally ultimate in teaching an adult, and even though the words may express abstract ideas, they still rest on ultimate images.

The eye is no less ultimate than the hand, or the muscles of the face than those of the arms and legs. The difference between them is not in respect to their being ultimate but in respect to their being ultimates which can more openly or less openly reveal the thoughts and affections of the mind. So in the case of the Old Testament, the Gospels, and the Writings. They are all equally ultimate, being all expressed in words of human language resting on ideas derived from the senses. The difference between them is seen in the nature and arrangement of the ultimate, it being this that determines whether the spiritual ideas within shine forth clearly or obscurely, or are entirely concealed.

Here we must not forget that these revelations, even though parts of them are especially adapted for children and the simple, are all addressed to adult minds; that they are so written that it would have been possible for such minds to have derived from them a true doctrine. In the Old Testament, historical narratives predominate - narratives which seem connected with the revelation of Divine Truth only in a general way. In the New Testament it is spiritual-moral truth that predominates, though here also we find historical narrative. In the Writings, the Divine Truth is clothed with the garb of natural-rational language; but here also we find stories, illustrations, allegories (I refer to the Memorable Relations and to the many comparisons and illustrations that are used in the Writings, particularly in the True Christian Religion.), all of which are given for no other purpose than to present the truths of heaven.

It may readily be granted that some ultimates are more objective than others, but holiness resides not only in objects but also in all ultimate expressions of things divine. If we take the grossness of the ultimate to be the ground of the holiness, then we must say that the Old Testament is more holy than the New, and even that the obscure portions of the Old Testament are more holy than those portions where the spiritual sense shines forth. In the Old Testament, moreover, there is a correspondence even in the curves of the Hebrew letters. This is certainly not true of the Greek Testament; yet surely no Christian will believe that for this reason, the Old Testament is holier than the New! or that the Lord who alone is holy, is more nearly present there!

The holiness of the Word rests indeed in ultimates, but it comes from internals. The Lord alone is Holy, and the more He is revealed the more fully is holiness present. To say that when the letter of the Word deeply veils and conceals the spiritual sense, that is to say, the presence of the Lord, it is more holy than when it openly presents the Divine Love and Wisdom for man's contemplation and for his instruction and elevation, is to ascribe holiness to the letter. But of this I shall speak later.

== III - THE APPLICATION TO THE WRITINGS OF THE TEACHINGS CONCERNING THE WORD

In what has preceded I have sought to show what is involved in the belief that the Writings are the Word - the Word for the New Church. I shall now endeavor to show that what the Writings say concerning the Word applies also to themselves - which must certainly be the case if the Writings are indeed the Word. Yet, to the rational mind, it is clear that in this inquiry, discrimination must be made, the faculty of discriminating being one of the supreme traits of the rational mind. I have shown that there are different kinds of correspondences, different kinds of ultimate clothing which may be taken on by the Divine Truth. It is with these differences in mind that, in approaching this new field of study, I observe a certain discrimination and reserve in applying to the Writings their own teachings concerning the Word. Where those teachings concern the Word in general as Divine Revelation, as the Lord's message to the human race, they must be applied to the Writings. But not so when the teaching is concerned specifically and only with the Ancient, the Jewish, or the Christian Word.

For the purpose of my inquiry, I shall take the chapter headings set forth in the Doctrine of the Sacred Scripture, having in view also what is said in the earlier work De Verbo, and in the later work, the True Christian Religion. (The chapter on the Sacred Scripture in TCR is transcribed with slight alterations from the Doctrine of the Sacred Scripture. De Verbo is a first sketch of the latter work.)

=== THE SACRED SCRIPTURE OR THE WORD IS DIVINE TRUTH ITSELF (@DSS 1-4)

Here the direct meaning of "Sacred Scripture or the Word" is undoubtedly the Old and New Testaments. This cannot be disputed any more than it can be disputed that by "Scripture" in the Gospels is meant the Old Testament. It is not, however, a question of what is the direct meaning, but of what is involved. The whole Christian Church has come to see that while the New Testament quotes "Scripture" as its authority, yet what is true of that Scripture, as for instance, when the Lord says "Search the Scriptures," is equally true of the New Testament itself. Therefore all Christians acknowledge that the New Testament also is "Scripture." So with the Writings. When they speak of "the Word" or "Sacred Scripture," the direct and immediate meaning is undoubtedly the Old and New Testaments; but this does not exclude the idea that they themselves are also the Scripture or the Word of the Lord. They are certainly a Divine Revelation equally as are the Old and New Testaments; indeed, they are a more excellent revelation inasmuch as they are the fulfillment of the Lord's words to his disciples: "I
have many things to say unto you but ye cannot bear them now; howbeit, when he, the spirit of truth, is come, he will guide you into all truth" (John 16: 12, 13).

It may be objected that the Christians were able to see that the New Testament is the Word of God because its authority rests not only on the testimony of the "Scriptures," that is, of the Old Testament, but on the direct teachings of the Lord himself who "taught them as one having authority and not as the scribes" (Matthew 7: 29). But is not the same also true, and even more evidently true, of the Writings? The Writings do indeed quote an abundance of confirmatory passages from the Old and New Testaments, for without these there would be no means whereby the Christian could judge the Writings whether they be of God; yet this is not the essential source of their authority. So the New Testament appeals to the Old to bear witness that "this day is this Scripture fulfilled in your ears" (Luke 4: 21). Yet the real authority of the New Testament is that it was revealed by God. Therefore when once this was acknowledged the Christian looked to this Testament as his own peculiar Word, the source of his faith and doctrine. So with the Writings. The real source of their authority is the fact that they are a Divine Revelation.

While Swedenborg quotes abundantly from the Old and New Testaments, yet, unlike Christian commentators, he does not appeal to those Testaments as the authority for his writings. His authority is the Lord alone. "The Lord alone has taught me," is his declaration (@DP 133); the works "are not my works but the Lord's" (@SD 6102). The Old and New Testaments do indeed confirm the doctrines, and necessarily so since they also are the Word. But could any man have drawn from those Testaments the truths now revealed? Manifestly not. "The Apocalypse (says Swedenborg) could never be explained save by the Lord alone" (AR Pref.; see also SS 25).

The Writings rest on no other authority than the fact that they are an "immediate Revelation" from the Lord (@HH 1). On what other basis can the New Church rest? on what other authority can it justify a new baptism? a new holy supper? a new priesthood? What proof do we need that the Writings are the Word other than the fact that the Lord has revealed them? To be sure they were revealed through Swedenborg, but this does not detract from their being the Word of God; the Old and New Testaments also were revealed through men.

And now in the light of the above, let me quote from the Doctrine of the Sacred Scripture in confirmation of the thesis that the Sacred Scripture or the Word is the Divine Truth itself. "Jehovah spoke the Word through Moses and the Prophets, and that which Jehovah himself speaks can be nothing else (than Divine Truth). The Lord who is the same as Jehovah spake the Word written by the Evangelists, many things from his own mouth and the rest from the spirit of his mouth which is the Holy Spirit. It is for this reason that He says that in His words there is life, and that He himself is the light which enlightens" (n. 2). So must all New Churchmen say that it is the Lord himself who spoke the Divine Truth now revealed through Swedenborg.

In further comment, the Doctrine of the Sacred Scripture adds: "The Word conjoins man with the Lord and opens heaven; therefore it fills the man who reads it from the Lord, and not from himself alone, with the good of love and the truths of wisdom. Hence man has life through the Word" (n. 3). Is not this eminently true of the Writings? Therefore, the passage continues, "Lest man should be in doubt whether the Word is such, its internal sense has been revealed to me by the Lord. That sense is the spirit which gives life to the letter."

=== IN THE WORD THERE IS A SPIRITUAL SENSE HITHERTO UNKNOWN (n. 5-26)

The word "hitherto" in this heading shows plainly that by "the Word" here is meant solely the Old and New Testaments. Two things, however, may be noted in the treatment of this heading.

First: That for the most part, the passages from the Word that are here adduced as illustrations, are passages which, apart from the spiritual sense, have little or no meaning, and certainly no meaning that could serve for forming a genuine doctrine; passages in which the spiritual sense in no way appears in the sense of the letter (@DSS 13, 15, 16) and which could not be unfolded except by Divine Revelation (@DSS 25).

Second: That in the explanation of this heading, an indication is given that the Writings also have an internal sense. I refer to the statement "that hereafter the spiritual sense of the Word will not be given to any one who is not in genuine truths from the Lord," and this "because no one can see the spiritual sense except from the Lord alone and unless he is in genuine truths from Him" (n. 26). The Writings again and again declare themselves to be the revelation of the spiritual or internal sense of the Word; but clearly they are not the naked spiritual sense, otherwise it would not be said that hereafter this sense will be given only to those who are in genuine truths from the Lord. Clearly the Writings are a revelation clothed in a letter consisting of natural language and natural ideas; a revelation in which the Divine Truth itself is seen as Divine Truth in the natural. This revelation, however, differs from former revelations, in that, while in former revelations the Divine Truth was more or less veiled and could not be seen by the men of the church save here and there when it appeared in the sense of the letter, the revelation now given is written in language where the spiritual sense, that is, the interior truths of heaven, is everywhere apparent in the sense of the letter; yet not apparent save to those who are in genuine truths from the Lord, that is to say, who are in the love of truth for its own sake. I shall revert to this matter later in connection with what is taught in the Doctrine of the Sacred Scripture n. 57. For the present I wish merely to show that the Writings are couched in an ultimate letter, as must necessarily be the case with all revelation; and that the difference between them and the New Testament, like the difference between the New Testament and the Old, consists in the nature of that letter.

=== THE SENSE OF THE LETTER OF THE WORD IS THE BASIS, THE CONTAINANT, AND THE FIRMAMENT OF THE SPIRITUAL AND CELESTIAL SENSES (n. 27-36)

We note here that it is not said that the Letter of the Word is the basis, etc., of the spiritual and celestial senses, but "the sense of the Letter." What is meant by this term will perhaps become clearer if for "sense" we read "meaning," this being the exact English equivalent for the Latin word sensus. By "the meaning of the Letter" is meant its real meaning; not a meaning twisted or perverted to favor men's desires, but the meaning that was intended for the leading of men to the acknowledgment and worship of God. This is indicated in n. 31 of the Doctrine of the Sacred Scripture, where, speaking of the three senses of the Word, it is said: "Its ultimate sense which is natural and is the sense of the letter of the Word, is the container." What is here referred to by the "sense of the Letter of the Word" is therefore not the merely historical sense, or the poetic and literary sense, but the Divine Truth as it appears to the natural man in the sense or meaning of the written words. "The interior things of the Word (we read) are those which are contained in its internal or spiritual sense and which are genuine truths; to these correspond the exterior truths of the Word which are those in the external or natural sense called the sense of the letter" (@AE 618). Essentially this sense of the letter is the genuine sense of the letter, but it includes also all appearances of truth such as the statement, in the Old Testament, that the Lord is angry, or, in the New Testament, that He leads into temptation. Every Christian who reads these words holily perceives in them something of the genuine sense of the letter; and it is this genuine sense and this alone that is the basis, the containant, and the firmament of spiritual and celestial truths; it is this alone wherein the Divine Truth is in its fullness, its holiness, and its power. If the reader sees nothing in the Word save mere historical narrative; if like the Scribes he sees only vain traditions, or, like many of the critics, nothing but grammatical forms and material ideas; then with him, the internal sense has no basis, no containant, and no firmament or support.

That this is what is meant by the "Sense of the Letter of the Word," is clearly involved in the teaching of the Doctrine of the Sacred Scripture, n. 6. There we read: "The Divine which descends from the Lord to human beings descends through these three degrees, and when it has descended, it contains those three degrees within itself. Such is the case with everything Divine. Therefore, when it is in its ultimate degree it is in its fullness. Such is the Word. In its ultimate sense this is natural, in its interior sense it is spiritual, in the inmost, it is celestial, and in every sense it is Divine."

That this "ultimate degree" or "ultimate sense wherein Divine Truth is in its fullness, and which is itself Divine, being the Divine Word in lasts, is the same as "the Sense of the Letter" which is the basis, containant, and firmament of the spiritual and celestial senses, is specifically stated in the chapter we are considering (n. 31) where, after referring the reader to n. 6 just cited, it is said that "its ultimate sense which is natural, is the sense of the letter of the Word." Clearly this ultimate sense or meaning which is "Divine," and which, moreover, is called "divine doctrine" (@AC 3712), cannot be the merely historical, Jewish, grammatical or literary meaning; these are not divine. Nor can it be the mere meaning of the letter, except where that letter plainly expresses spiritual-moral truths. The reading of the letter of the Word with nothing else in view save the history and laws of the Jews, or the increase of one's learning and fame, will not in itself bring the presence of the Lord in ultimates, that is to say, His presence as Divine Truth in the natural; for while the "Letter of the Word" is indeed read, yet there is no entering into the "sense" or meaning for the imparting of which that Letter was given, and which alone is the basis, containant, and firmament of Divine Truth. In itself (we read) the Letter is dead, "the holiness of the Word is in its sense of the Letter" (De Verbo 15).

It is for this reason that we are so often told, that in order that there may be communication with heaven, that is to say, in order that the Lord may be present with man, the Word must be read "holily." It must be read as the Word of God given for man's spiritual guidance and reformation. When man so reads it, he is truly in the sense of the letter, in that Divine natural sense which is the basis, containant, and firmament of the interior senses. Even when reading parts that are obscure to him, he is yet brought into the sphere of angelic spirits, and something of the love of God and the love of obedience is insinuated into his mind. Even if in his simplicity he interprets what he reads in a sense apparently contrary to the truth, as that God is angry and persecutes the wicked, etc., yet these ultimate appearances are the actual appearances of the Divine Truth in ultimates and are the Lord's presence with him; and so something of the genuine truth is insinuated.

By means of the correspondences of spiritual things with natural (we are told) "the man who reads the Word holily is closely conjoined with heaven and by heaven with the Lord, even though the man is only in thought concerning such things in the Word as are in its sense of the letter. The holiness which is then with the man is from the influx of the celestial and spiritual thoughts and affections which are such with the angels" (@AC 3735). And again we read: "The internal of the Word flows in and is conjoined with good, when man reads the Word holily; and he holds it holy when he is in good" (ibid. 6789).

It is not my intention to assert that whenever the Writings use the term "Sense of the Letter" they mean the genuine sense of the letter. (It may here be noted that in many of the English translations of the Writings, sensus literae (sense of the letter) is frequently translated literal sense.) The term may be used in various senses, and its meaning must be determined by the context. What I wish to establish is that this is the meaning of the term when that term is used to signify the basis, containant, and firmament of Divine Truth.

This is fully confirmed by a multitude of passages, of which the following may be adduced:

"Ultimate truths are the truths of the sense of the letter of the Word, within which are the internal senses, and on which these rest as columns on their bases" (@AC 9163).

"The Word in the ultimate or natural sense which is the sense of its letter, is signified by the wall of the holy Jerusalem, the structure of which was jasper, and by the foundations of the wall which were precious stones" (@DSS 36). What is here meant by "the sense of the letter" is expressly stated later, where we read that it is "the truths of the, sense of the letter of the Word that are meant by the foundations of the wall of the New Jerusalem and also by various precious stones" (ibid. 43, 45); and it is added that "the truths and goods of the sense of the letter of the Word are what are meant by the Urim and Thummim" (ibid. 44).

"The Word in ultimates is like a man clothed in a garment, who is bare as to his face and hands . . . and therefore the doctrine of genuine good and truth can be seen from the sense of the letter by those who are enlightened by the Lord, and can be confirmed by those not enlightened. The Word is such in the sense of the letter that it may be a basis for the spiritual sense. . . . Divine Truths in the sense of the letter are mostly appearances of truth" (@AE 778).

"Divine Truth on earth is such as is the Word in the sense of the letter, wherein are few genuine truths such as are in heaven, but wherein are appearances of truth" (@AE 950).

It is true, of course, that the whole of the Word is the ultimate on which heaven rests. But that portion where the heavy veiling of Jewish garments conceals the Divine Truth was not and could not be the basis, containant, and support of the Divine Truth for the establishment of a genuine church on earth, any more than the Apocalypse could be such a basis for the establishment of the Christian Church. These dark portions of the Word were the means of establishing a representative of a church; like the Apocalypse, they also provided an ultimate on earth wherein angels could see the future coming of the Lord and his work of redemption. But it is by the sense of the letter of the Word that the Divine Truth is actually present on earth for the establishment of a genuine church. In itself the letter of the Word is dead, but this is not true of the sense of the letter (De Verbo 15; see SS 77).

This is clearly indicated in a noteworthy passage in De Verbo. There we learn that without the sense of the letter the spiritual sense would be like a body without its skins whereby communication with its interiors is maintained; or like wine without a containing vessel. The passage goes on to say that the same would be true of the heaven of angels and of their wisdom, without the human race and the church there "and its intelligence from the sense of the letter. It is the sense of the letter of the Word with man that makes this connection and conjunction. This, moreover, was the reason why the Lord came into the world; for every sense [or meaning] of the letter had been so falsified by the Jews that there was no longer an ultimate in man. Wherefore the Lord came into the world and put on the human that He might become the Word also in the sense of the letter, that is, the Divine Truth in ultimates" (De Verbo 54).

It is the "sense of the letter of the Word" that establishes a church on earth and effects consociation with heaven. Therefore by His coming on earth, the Lord "became the Word also in the sense of the letter," that is to say, He revealed himself in the spoken and written Word, as Divine Truth in the natural, whereby was established a genuine church. A genuine church might have been established even among the Jews had they not by vain traditions falsified "the sense of the letter" of their Word. Among Christians the Divine Truth in the sense of the letter of the New Testament was so revealed that by it they were able to see the genuine sense of the letter of the Old Testament also.

Clearly the same reasoning applies to the Lord in his Second Coming. True He has come to reveal the interiors of the Word, but this was also the Divine end in the First Coming. Then, however, there were few or no vessels to receive save those moral truths which are the face and presentation of interior truths. But in Swedenborg, by means of his study of the sense of the letter of the Word, and also by means of his study of nature as the theatre of Divine Love and Wisdom, there was provided a body of rational truths whereby the Divine could clothe itself to be seen in the glory of His Second Coming.

It is frequently said that the Writings are the spiritual sense of the Word. This is true, but only in the sense that essentially, the same statement is true also of those portions of the Old and New Testaments which are compared to the bare face and hands, and in which consequently the spiritual sense shines forth. That sense shone forth here and there in the Old Testament; it shone forth almost everywhere in the Gospels, so much so indeed that the Christian Church might have been a genuine church advancing in the knowledge and perception of spiritual truths; in the Writings it shines forth everywhere in clear light. In all these revelations the spiritual sense "shines forth"; it does not and cannot appear without a body or clothing through which it can shine forth. It cannot appear as bare spiritual truth without a natural clothing. This is taught in so many places in the Writings that it would be superfluous to quote. However, I shall adduce a single passage: "That the Word may be Divine and at the same time may be the Word for heaven and the Church, it must be wholly natural in the letter; for unless it were natural in the letter there would be no conjunction of heaven with the Church by its means, for it would be as a house without a foundation, and as a soul without a body, since ultimates enclose all things interior and are their foundations. Man also is in ultimates, and upon the Church with him is founded heaven. Hence then it is that the style in the Word is of such a nature. Wherefore when man thinks spiritually from things natural which are in the sense of the letter of the Word, he is conjoined with heaven with which he could not otherwise be conjoined" (@AE 71 fin.).

This and similar teachings have usually been assumed as referring solely to the Old and New Testaments, and there can be no doubt that this is the immediate reference, just as the Old Testament was the immediate reference when the Lord said "Search the Scriptures." But it is manifest that there is here no limitation of the term the Word to the Old and New Testaments. The New Church also is in ultimates, and it is for this New Church that the Writings are revealed. Can it be doubted then that "the Word" here also includes the Writings? This, moreover, is confirmed by the words: "Man is in ultimates and heaven has its foundations upon the church in him . . . wherefore, when he thinks spiritually from things natural which are in the sense of the letter of the Word, he is conjoined with heaven, which could not otherwise have been the case." Where is man afforded so full an opportunity of thinking spiritually, as in "the natural things which are in the sense of the letter" of the Writings? that is to say, which are the genuine meaning of what is there written. What is it that conjoins him so closely to heaven as the genuine sense or meaning of those Writings? It is not the mere reading of the letter that conjoins to heaven but the seeing of the spiritual things there set forth. Shall we say that the sincere Christian is more closely conjoined to heaven when he reads, for instance, in the Old Testament the laws concerning leprosy, than when he reads in that same Testament the words "Thou shalt love thy neighbor as thyself"? Or that he is more closely associated with angels when he reads these words in the Old Testament, or, the words in the New Testament, "If ye love me keep my commandments," than when he reads the words of the Writings with a mind opened to perceive their genuine meaning?

Yet so accustomed is the Christian to think of the Old and New Testaments as alone being the letter of the Word, so firmly has this been impressed on the mind for almost two thousand years, that the New Churchman finds it hard to extend his idea of the Word beyond the limits of the past; hard to include in that term even a revelation which is more excellent than all previous revelations (Inv. 44). May he not profitably ask himself whether this clinging to the Old and New Testaments as the sole letter of revelation has its origin in a genuine perception of the holiness of the Word, or in a traditional and hisorical faith; whether his love and affection attaches itself to the mere form of revelation, rather than to the Divine Truth which speaks by means of the form.

How can revelation, even of the most sublime arcana, be given to man save in a letter? I do not refer merely to alphabetic letters, nor to mere words. The letter to which I refer is the letter of natural ideas, ideas which, however abstracted, rest more or less consciously on what has been derived from the world through the senses. Unless clothed in such ideas, Divine Truth cannot come to man (@AC 2553); and, this being the case, it necessarily follows that men can read the letter, can see the clothing, and yet see nothing of its genuine meaning, still less of the spiritual arcana more deeply involved therein.

The reader may ask, Are then the Writings written in correspondences? I answer that, being in the language of natural ideas, they must necessarily be written in correspondences. But this word correspondence must not be confined to correspondences such as are found in the historical events, the Israelitish statutes, the dark utterances of the Prophets as recorded in the Old Testament. I have already dealt with this subject, but wish now to add somewhat to what has gone before.

Correspondence is the relation between spiritual cause and natural effect. Hence the whole of nature is a theatre in which are set forth in correspondential forms the Divine Love and Wisdom of the Creator. Indeed, if we could read this book of Nature, as did the Most Ancients, then Nature herself would be to us a letter of the Word revealing internal arcana. But we are not thus able. Therefore it devolves upon us to study nature, and learn her laws, that these laws may form a body or letter in our mind with which spiritual causes can be clothed. It was such a study that engaged Swedenborg during his years of preparation, - essentially a study of correspondences, an effort to behold nature as the theatre of higher forces. The study of nature, and also the accumulation of experience in human relationships, forms in our mind a great body of natural ideas - ideas of government, ideas of cause and effect, and so forth; and this body of ideas is the source of the rich language which distinguishes civilized peoples. Now, just as nature can speak to us only through the senses; just as we can convey ideas to a child only through sensual images; so the Divine can teach us spiritual arcana only by clothing them in natural words and natural ideas, words and ideas drawn from the theatre of nature and therefore fitted aptly to clothe in correspondential form the arcana of the spiritual causes of nature. Thus the spiritual idea of God as a Man, is presented in the natural idea of a man; the doctrine of the Grand Man in the uses of the organs of the human body; the government of heaven and the laws of association both among the angels, and between angels and men, is presented to us clothed in our ideas concerning human government and human relationships; the spiritual idea of love comes to us clothed in natural and moral ideas concerning our duty to our fellow men; and the heavenly truths concerning Conjugial Love in moral truths concerning the duties of husband and wife; and so in other cases.

That the relation here is one of correspondences is specifically declared in the Writings. There we read: "Man is aware of his evils and falses by means of the truths of faith in the natural, that is, in the external man, but not in the internal. The reason is, because the ideas of thought in the internal man are spiritual, and spiritual ideas, being intellectual ideas which are without objects such as are in the material world, cannot be comprehended in the natural. Still these spiritual ideas, which are proper to the intellectual man, flow into natural ideas which are proper to the external man, and produce and make them-which is done by means of correspondences" (@AC 10237).

Such is the correspondential language which occurs here and there in the Old Testament, more frequently in the Gospels, and everywhere in the Writings of the New Church. And, therefore, as I have already observed, men can read those Writings and yet see nothing spiritual within them; see merely natural ideas, sometimes clear and rational, sometimes obscure. So men can read those parts of the Old and New Testaments where the spiritual sense shines through, and while seeing much that is admirable therein, see nothing Divine. They read the letter and more or less comprehend the natural or rational ideas, but are blind to the real sense or meaning of that letter as the ultimate appearance of the Divine Truth.

There is a universal reason why revelation can come to man only in a letter of correspondential natural ideas. This reason is indicated in the following passage: "Naked goods and truths cannot flow in, for these are not received, but truths clothed, as they are in the sense of the letter of the Word; moreover, the Lord always operates from inmosts through ultimates, that is to say, in fullness" (@AR 672).

We shall refer to this law later. Suffice it for the present to see that the Writings in their letter, in their natural and rational presentations, are the basis, the containant, and the support of the spiritual and celestial arcana contained more deeply within; for they are an ultimate Divine Revelation to man, and it every Divine work in the ultimate is complete and perfect. Moreover, that which is in the ultimate is the all, because in it are at the same time things prior" (@TCR 210; SS 28).

=== THE DIVINE TRUTH IN THE SENSE OF THE LETTER OF THE WORD IS IN ITS FULLNESS, IN ITS HOLINESS, AND IN ITS POWER (@DSS 37-49)

Two things should be noted in this doctrinal statement: (1) That Divine Truth is in its fullness, holiness, and power not in the letter of the Word but in the sense of the letter. (2) That the fullness, holiness, and power do not come from the sense of the letter but reside in it.

As to the first point, I need add nothing to what I have already written. It is the second point that I would now discuss. It is an important point, and is emphasized in the Doctrine of the Sacred Scripture in the very beginning of the comment on the above heading.
"The Word in its sense of the letter is in its fullness, holiness, and power because the two prior or interior senses . . . are together in the natural sense which is the sense of the letter" (@DSS 37). I suppose that all New Churchmen would at once assent to this as a self-evident truth. Yet there are abundant indications that many, while acknowledging the truth, fail to see its implications. Much that has been written in the Church concerning the Letter of the Word, meaning the Old and New Testaments, really implies that the holiness and power are from the letter itself. Though the Writings are given to us as an ultimate Divine Revelation teaching the truths of heaven, yet, because this ultimate is not like the ultimate of the Old and New Testaments, they are too often regarded as inferior to "the Word itself." Sometimes this view is held in a clear and definite way and is plainly the result of a disbelief in the Divinity of the Writings save in a more or less restricted sense. But there are some who, while accepting the Divinity of the Writings, while acknowledging them as the Lord's teaching to the New Church, yet are reluctant to acknowledge them as the Word. Some also there are who, while acknowledging that the Writings are the Word, yet hesitate to ascribe to them the full properties of "the Word," feeling almost instinctively that the Word, meaning the Old and New Testaments, is in some way more holy, more Divine, more effective in conjoining man to heaven. This hesitation is a fact which cannot be ignored; nor can we be surprised at it, for it is fortified by the belief of generations of Christians for two thousand years back. Yet if the Writings are not so holy as the Old and New Testaments, if they are not so effective in conjoining man to heaven, or in bringing to him the power of Divine Truth, then they are not the most excellent of all revelations.

Let us then examine what it is that makes the Old Testament the Word, and also the New Testament; what it is that makes the essential characteristic of "the Word."

It cannot be the Hebrew language, for the New Testament is written in Greek. It cannot be the ritual of the Israelitish people, for this is entirely absent from the New Testament, and also from parts of the Old. It cannot be obscurity of language such as we find in many portions of the Prophets and in the Apocalypse, for then we would exclude not only most of the Gospels but also many parts of the Old Testament. It cannot be its suitability for children, and the simple, for this would exclude many parts of the Old and New Testaments. It cannot be that it is written in the form of story or historical narrative; for this would exclude the Psalms and many portions of the Prophets. We have but one characteristic left, namely, because it is Divine Revelation. The Word is "the Word" because it is Divine teaching given in ultimate form for the instruction of man; for the opening of his mind to the influx of heaven; for the conjoining of man to the Lord.

It is this and this alone that makes "the Word of God," whether it be clothed in Hebrew letters, or in Greek or in Latin; whether it put on the language of Jewish history, of Hebrew poetry, of dark sayings, of moral truths, of spiritual relations, or of rational thought. The Writings then are clearly the Word, and being ultimate they are the Word in ultimates. Indeed, in the Writings the Lord appears in greater glory, and teaches in clearer language than in former revelations, this being in accordance with His statement to the disciples, that He had many things to teach men which they could not then bear, and that therefore He would send them the Spirit of Truth which would guide them into all truth (John, 16: 7-14). At the same time, the Writings are so written as to be adapted to the comprehension of all manner of men, young and old, simple and wise. And lastly they are so clothed that they convey nothing of the Divine save to one who reads them as a Divine Revelation; reads them not for fame and glory, not for the procuring of arguments wherewith to refute opponents; but for the edification of his spiritual life; in a word, who reads them holily. When man thus reads the Word, whether it be the Old Testament, the New Testament, or the Writings, the Lord is present in his fullness, his holiness, and his power. Yet it must be acknowledged that this presence is more clearly evident in the Gospels than in the Old Testament, and in the Writings than in the Gospels; not that the one is less the Word than the other, but the clothing is more suitable for the appearing of the truth within. The matter can be illustrated in the human body. The whole of the soul is present in fullness and power in the hands equally as in the eye. Yet, in the eye its affections and thoughts are more clearly discernible.

The clothing in which Divine Truth reveals itself is frequently expressed in the Word, and particularly in the New Testament, by "clouds," and "clouds of heaven." Indeed, every form of the revealed Word is a cloud. The Writings, however, are a translucent cloud in which the Lord appears "in power and great glory." The Writings cannot be that glory itself any more than the actions and speech of the body can be the soul, howsoever fully they may reveal the soul. In the Writings, the Lord comes in the clouds of heaven; in translucent clouds drawn not from the minds of Jewish scribes or of simple disciples, but from the mind of a man prepared from his youth by the study of natural philosophy to become the medium for the revelation of spiritual philosophy (Influx 20). Where else does the Lord appear "with power and great glory" if not in the Revelation now given to the New Church?

That the Writings in their external form are the clouds of heaven appears moreover to be indicated in the Doctrine of the Sacred Scripture. There we read: "The Word in its glory was represented by the Lord when he was transfigured . . . when His face shone like the sun; and His raiment became as the light; and Moses and Elias were seen talking with Him; and a bright cloud overshadowed the disciples; and a voice was heard out of the cloud saying, This is my beloved Son, hear ye him. I have been instructed (the passage continues) that the Lord then represented the Word. By his face which shone like the sun was represented his Divine Good; by his raiment which became like the light, his Divine Truth; . . . by Moses . . . the historical Word in general, and by Elias, all the prophetical Word; by the bright cloud which overshadowed the disciples, the Word in the sense of the letter; wherefore from it a voice was heard saying, This is my beloved Son, hear ye him; for no enunciations and answers from heaven are ever made except by ultimates, such as are in the sense of the letter of the Word, for they are made by the Lord in fullness" (@DSS 48).

By the "historical and prophetical Word "in this passage is clearly meant the Old and New Testaments, for the latter also is historical and prophetical. By "the Word in the sense of the letter" is meant the Divine Truth shining forth in and as the sense of the letter. This eminently includes the Writings; for it is in the Writings alone that the Son of Man appears with power and great glory.

The Lord's coming in clouds is frequently explained in the Writings, where it is shown that by clouds is meant "the Divine Truth in ultimates such as is the Word in the sense of the letter" (@AE 906, @AR 24, etc.). New Churchmen have invariably understood that by these clouds is meant solely the Old and New Testaments. Yet a little reflection will show that if this were the case then the Lord himself has not come, but has merely used Swedenborg to point out where alone He is to be seen, namely, in the Old and New Testaments; that it is to these we must go if we would approach the Lord, and be enlightened in spiritual truth, and not to the Writings. Such a position is manifestly absurd. It is the Lord himself who has come; and He has come as "the Divine Truth in ultimates such as is the Word in the sense of the letter."

That the Writings themselves are a cloud, bright and luminous to those who are enlightened by the Lord, and dark to others, is clearly indicated in the little work entitled Sketch of an Ecclesiastical History. There we read: "The books are to be enumerated which were written from the beginning to the present day by the Lord through me. The writing there is such that it shines brightly before those who believe in the Lord and in the new revelation; but it appears dark and of no consequence to those who deny them, and who are not in favor of them on account of various external reasons" (n. 3-4).

Many have felt that the power of the Divine Truth is peculiarly present in the Old and New Testaments, comforting and sustaining; and that this is not the case in the Writings. I am not aware that any such distinction has ever been made between the Old Testament and the New; yet if the power of Divine Truth in ultimates is dependent on the obscurity of the ultimates, then logically, special emphasis ought to be laid on the Old Testament as the revelation where Divine Truth is in its greatest power to comfort and sustain man. Yet if anything, the opposite is generally the case in the Christian world. And naturally so, since the power is not in the letter of the Word but in the sense of the letter, that is to say, in the Divine Truth thus appearing; and this Divine Truth appears or shines forth only in parts of the Old Testament, while in the Gospels it is apparent almost everywhere.

Any one can readily confirm this from his own experience. Let him ask himself what are the passages in the Word that give him heavenly strength and comfort, and he will see that they are not the dark and obscure passages of the Word, the Jewish statutes, the tables of genealogies, but passages where the spiritual sense shines forth, passages where the Lord's presence is felt as the Teacher, the Comforter, the Sustainer.

Can we then deny this power to the Writings, where the Lord more interiorly presents himself? Men come into different states and are affected by the Word in different ways. Thus states of despair may overcome a man, in which his greatest strength and comfort is found in the contemplation of such words as "The Lord is my shepherd, I shall not want." In other states he finds his refuge in the stern command "Thou shalt not"; in others again in the Lord's words "come unto me all ye that labor"; and so in other cases. But when it becomes a question of more nearly beholding the Lord, of receiving strength to combat and overcome the assaults of doubts inspired by sensual and materialistic spheres, it is in the Writings of the New Church that the Lord gives of his power, and imparts interior strength and comfort; it is there that the Divine Truth is in its fullness, its holiness, and its power to combat the evils and falses that have destroyed the Christian Church, and, despite the low state into which men have sunk, to lift them up and establish a New Church as the kingdom of heaven on earth.

The teaching that in the sense of the letter of the Word, Divine Truth is in its fullness, its holiness, and its power, is but a phase of a universal law applicable to all Revelation; the law namely, that the Lord never operates on man from within unless at the same time from without. This law is revealed to us as "an arcanum of angelic wisdom," and it is shown that it was from this law that the Lord came into the world that He might be in firsts and in ultimates at the same time (@DP 124). The reason is because only in ultimates is man free to cooperate with the Lord. He would not have this freedom were truth poured in through the soul. Hence all revelation is made in ultimates. "Nothing is ever wrought by the Lord except in fullness (we read), and the Word is in its fullness in the sense of the letter; hence doctrine is to be drawn from the sense of the letter" (@DSS 53). "The Lord does not speak with man except in fullness, and the Word in the sense of the letter is Divine Truth in fullness" (@DSS 97). Moreover, the sense of the letter is a guard for the genuine truths which are latent within, and this to the end "that the Lord, heaven, and Divine Truth, such as it is interiorly in the Word, may not be approached immediately but mediately through ultimates" (ibid.). We further read that "the power of Divine Truth is in the sense of the letter, nay, the Lord's omnipotence in saving man; for when the Lord operates, He does not operate from primes through mediates into ultimates, but from primes through ultimates and thus into intermediates" (@AE 1086-7).

So universal is this law that it applies also to the spiritual world. The devils are held in order by the Lord operating in ultimates, the angels are enlightened by means of the Word on earth. In a word, it is by means of the Divine Truth in ultimates with man that the Lord exercises his omnipotence. New Church students are familiar with the teaching as to the dependence of the angelic heaven on the Church on earth (@LJ 9; Cor. 19); and that unless the Lord had come on earth, the heavens themselves could not have remained in a state of integrity (@TCR 118-19); but let me quote a single passage which applies this universal teaching to the written Word. We read: "The sense of the letter of our Word is the basis, support, and firmament of the wisdom of the angels of heaven. For the heavens subsist upon the human race as a house upon its foundations. Hence the wisdom of the angels of heaven, in like manner, subsists upon the knowledge, intelligence, and wisdom of men from the sense of the letter of the Word, for through the sense of the letter of the Word is effected communication and conjunction with the heavens" (@AE 1085). Let the reader ask himself the question, Whence is to come "the knowledge, intelligence and wisdom" of the men of the New Church?

=== THE DOCTRINE OF THE CHURCH IS TO BE DRAWN FROM THE SENSE OF THE LETTER OF THE WORD AND TO BE CONFIRMED BY IT (@DSS 50-61)
(In the treatment of this heading it is further said that "the doctrine of genuine truth may be fully drawn from the literal sense of the Word" (n. 55).)

Here again we note the use of the term "sense of the letter of the Word." It is from this that the doctrine of the Church is to be drawn, and not from the letter of the Word. That is to say, it is to be drawn from the Word not by any correspondential interpretation but from the sense of its letter, from the genuine meaning of that letter.

This is so clear a consequence of the oft-repeated teaching as to the source of doctrine, that it seems unnecessary to adduce any specific confirmation from the Writings in its support. At any rate, I will content myself with a single passage:

There are many things in the sense of the letter which cannot serve for any doctrine of the church at this day, and many which can be applied to various and diverse principles, whence arise heresies; but still, many things are intermingled, from which doctrine can be gathered and formed, especially the doctrine of life. But he who reads the Word from doctrine sees there all things that confirm and also many that lie concealed before the eyes of others. Nor does he suffer himself to be drawn away into strange doctrines by those things there which do not appear to agree and which he does not understand; for to him all things of the doctrine which he does see there, are in clearness, and all else in obscurity (@AE 356).

The manifest reason for this law as to the source of doctrine is that man may be taught not by men but by the Lord, that is to say, by the ultimate form of revelation wherein alone the Lord instructs man, and wherein alone Divine Truth is in its fullness and its power to save.
"To be taught from the Word (we read) is to be taught by the Lord. This is an arcanum of arcana of angelic wisdom" (@DP 172).

It is manifest that in every dispensation man can be taught by the Lord from the Word only from the sense of the letter of that Word, that is to say, from those things "intermingled" in the letter which are the clear face of the Divine Truth, and "from which a genuine doctrine can be gathered and formed." To be taught in any other way would be to be taught by man and not by the Lord.

In the Jewish Church the most pious and enlightened of men could not have seen any Divine Truth save what is declared in the sense of the letter of the Old Testament. By studying the sense of that letter in the spirit of obedience to God, they might by the light thus received have been able to perceive something of the true meaning of many passages theretofore obscure. Thus they might have seen that the sense of the letter of their Word teaches that the neighbor who is to be loved includes the gentile also; that the Lord's mercy is extended to all alike; consequently, that the promised Messiah would come to save all who would receive Him; and so, that His kingdom was to be a spiritual and not an earthly kingdom, a kingdom of love and not a kingdom of despotic rule. All this is clearly taught in the sense of the letter of the Hebrew Scriptures, or is clearly deducible from that sense. This genuine sense of the letter of their Word was, however, the limit beyond which the Jews could not have gone. To have taught or believed anything not clearly expressed or involved in the sense of the letter of the Old Testament would have been to teach and believe not God's Word but the imagination of men. Such teaching could have none but human authority.

By the sense of the letter of their Word, the Jews might have been introduced into many heavenly truths, bringing enlightenment and wide extension of thought. But by no possibility could they have penetrated to the interiors of their Word by means of correspondences, except indeed as regards those natural correspondences to which we have previously referred; as, for instance, where it is said that the Lord is a sun and a shield; that true circumcision consists in the circumcision of the heart; that man is to wash and cleanse himself; and so on. They could not have learned the spiritual arcana which lay within their statutes and rites, the history of the patriarchs, or the dark sayings of the prophets. To do this would have required a knowledge of doctrines which were beyond their reach because not taught in the sense of the letter of their Word.

So in the Christian Church. By a faithful study of the sense of the letter of the New Testament, Christians might have been introduced by the Lord into the seeing of many spiritual truths which were beyond the reach of the Jewish Church even had that church been a genuine church. Thus they might have seen that the Lord's kingdom is a spiritual kingdom, and consequently that His second coming would not be a coming to destroy the visible heaven and earth and create a new one, but would be a revelation of truths enabling men to enter more interiorly into the kingdom of heaven. They might also have gathered from the Word some knowledge of correspondences, and so might have seen something of the spiritual significance of some of the more obscure portions of the Word, as for instance, of the twenty-fourth chapter of Matthew, the promise of the land of Canaan to Abraham, the raising up of the brazen serpent, etc. Indeed, in its early days the Christian Church did make a beginning in this direction, and had that church continued in its integrity its knowledge of genuine doctrine must have been widely extended.

But by no possibility could they have entered into the more interior arcana now revealed in the Writings, as for instance, the Glorification of the Lord as taught in the story of the patriarchs, the degrees of the human mind, the nature of the spiritual world, etc. Nor could they have unfolded the correspondences of the Apocalypse or of the dark sayings of the Prophets. "The Apocalypse (we read) can by no means be explained save by the Lord alone" (AR Pref.), and this by means of a man "to whom it has been granted to have consort with angels and to speak spiritually with them" (@LJ 42); "and therefore (we further read), lest what is written therein should be hidden to men, and hereafter be disregarded because not understood, its contents have been disclosed to me" (ibid.).

That the internal sense of the Old and New Testaments, save as to those portions thereof where that sense shines forth from the sense of the letter, can be disclosed only by a new Divine Revelation, is aptly illustrated in the case of the Apocalypse. Many men have put forth expositions of this book, but because what they taught was not drawn from the sense of the letter of the Word (to cite one reason only), these expositions have brought no light and have had no power and no authority among men. "Unless gathered from the sense of the letter of the Word and confirmed thereby (we read), the doctrine of the church is of no avail [has no power (De Verbo 57)] because it does not effect communication, but only doctrine from the sense of the letter and together with that sense" (De Verbo 15). How can aught but the Divine Truth have power and authority? and how else can Divine Truth be given to man except in the "sense of the letter" of Divine Revelation? There alone does that Truth appear in ultimates, and there alone has it power to instruct man and elevate him into the light of heaven.

"Doctrine from any other source than the Word [that is, doctrine from any other source than the sense of the letter of the Word] is not doctrine wherein is anything of the church, still less anything of heaven. Doctrine must be gathered from the Word, and while it is being gathered, the man must be in enlightenment from the Lord; and he is in enlightenment when he is in the love of truth for the sake of truth and not for the sake of self and the world. Such men are enlightened in the Word when they read it, and see truth and make for themselves doctrine therefrom" (@AC 9424). "Doctrine is not only to be drawn from the sense of the letter of the Word but is also to be confirmed by it; for if not confirmed by it, a truth of doctrine appears as if only the intelligence of man were in the doctrine and not the Lord's Divine Wisdom" (@DSS 54).

Some of my readers may feel that I have dwelt at unnecessary length on a matter which, after all, should be obvious to every intelligent man on slight reflection. I have done this purposely because of the importance of this obvious truth when considered in its whole extent. For broadly stated the law is that the Lord teaches man solely from ultimate Divine Revelation, and that the doctrine of the church is to be drawn from the sense of the letter of that Divine Revelation, and from no other source.

New Churchmen have usually limited this law to the Old and New Testaments. A limitation of the same sort must have been made by many in the early days of the Christian Church, especially by Jewish converts. "The Scripture" was then the Old Testament, and it was to that Testament that the Apostles constantly appealed in support of the truth which they preached - as seen in their Epistles. But gradually, as the Gospels became recognized as being themselves a Divine Revelation, there came a change, and the writings of Christian teachers
- except when addressed specifically to the conversion of the Jews - no longer laid the emphasis on the Old Testament. Satisfied that the New Testament is in truth the fulfillment of the prophecy of the Old, it was to the New Testament that they then turned for deeper instruction, and it was from the sense of the letter of that New Testament that they drew the doctrine of their church; and in the light of this doctrine they then read both the Old Testament and the New. Both Testaments were indeed seen to be the Word of the Lord; but the New Testament was seen to be the Word given for the establishment of the new and Christian Church, and as the source from which the doctrine of that church is to be drawn. "When the end of the Jewish Church was at hand (we read), the Lord himself came into the world and opened the interiors of the Word.
. . . Those truths, therefore, were interior truths and in themselves spiritual, which afterwards served the new church for doctrine and life. But still those truths were not immediately received" (@AE 670).

We see something of the same kind in the early history of the New Church. And naturally so; for a clear parallel is drawn by the Writings between the revelation given in the Gospels and that which is now given to the New Church. Thus we read:

"When the end of the Jewish Church was at hand, the Lord himself opened and taught the interior things of the Word, and especially did He reveal those things in the Word which were foretold of Himself. . . . The case is the same at this day; for it has now pleased the Lord to reveal many arcana of heaven, especially the internal or spiritual sense of the Word which has hitherto been entirely unknown; and with it He has taught the genuine truths of doctrine" (@AE 641). Again we read:"
The like is to be done now as was done at the end of the Jewish Church; for at its end, which was when the Lord came into the world, the Word was interiorly opened; for by the Lord when he was in the world were revealed interior Divine Truths which were to serve the new church about to be established by Him, and which also did so serve. At this day, also because of similar reasons, the Word is interiorly opened and thence are revealed Divine Truths still more interior which are to serve the New Church which shall be called the New Jerusalem" (@AE 948).

In the beginning, New Church teachers were mainly engaged in the work of making converts. Consequently, their writings abound in quotations from the Old and New Testaments showing the truth and authority of the claims of the enlightened Swedenborg. By abundant quotations from these Testaments they set forth their genuine doctrine, namely, that the Divine Trinity is in the one Person of our Lord; that faith alone is not saving; and so forth. By the same means they also demonstrated that the Last judgment and the Second Coming of the Lord are the fulfillment of prophecy. But as the church grew, and more and more men came to recognize the Writings themselves as Divine Revelation, a change came upon the character of the literature of the Church. Men began to devote their studies to learning the deeper meaning of the Writings, and to the drawing of doctrine from the sense or meaning of the letter of the Writings themselves; not those doctrines, such as the Unity of God, the necessity of the life of charity, etc., which, in the Writings, are so plainly stated as to be unmistakable; but doctrines peculiar to the New Church itself; as, for instance, the Glorification of the Lord; the nature of the Second Coming; the Authority of the Writings; the nature of the Spiritual World, etc., etc. In this way there has come into being, a body of doctrines distinctively belonging to the New Church. It was then confirmations from the Writings, and not so much from the Old and New Testaments that were brought forward; that is to say, for the showing and the confirming of what men considered to be the true teaching of the Writings, it was the sense or meaning of the letter of those Writings that was the final court of appeal.

In the Christian Church, teachers of opposing creeds all appealed to the sense of the letter of the New Testament as their authority; but in the New Church, the proponents of varying or opposing doctrines appeal solely to the sense of the letter of the Writings. Even those in the New Church who deny to the Writings Divine Authority in any real sense, yet cite the letter of those Writings as their supreme authority. This must necessarily be the case. For were the New Church to confine its teaching to what can be drawn out of the sense of the letter of the Old and New Testaments, it could advance not one step beyond the possibilities opened to the first Christian Church.

And yet, as I have said, many New Churchmen interpret the general teaching that doctrine must be drawn from the sense of the letter of the Word as referring exclusively to the Old and New Testaments; and they refuse it any wider interpretation when applied to the drawing of doctrine by the New Church. There is manifest confusion and contradiction here. Thus it is a doctrine of the New Church that only those books of the Old and New Testaments are the Word which have an internal sense, and these books are enumerated. I will not dwell on the obvious question, How can we draw this doctrine from the sense of the letter of the Old and New Testaments; but I will ask whether it is reasonable to imagine for a moment that the lower can thus dictate the status of the higher?

Furthermore, it is obvious that the only doctrines that we can draw from the sense of the letter of the Old and New Testaments are those which are already so abundantly set forth in the Writings, and on which there is no disagreement within the borders of the New Church. I have never heard of any genuine doctrine being drawn from the Old and New Testaments that has not already been drawn therefrom and openly set forth in the very letter of the Writings; indeed, the genuine doctrines of these two Testaments, form a large part of that letter.

But as I have already observed, in addition to these doctrines, doctrines which were within the reach of the first Christian Church, the men of the New Church have gathered from the words of the Writings, that is, from the sense or meaning of those words, a host of doctrines peculiar to the New Church and which it would not be possible to draw from the sense of the letter of the Old and New Testaments. If you say that in the light of the Writings we can see them in those Testaments when unfolded, I will not object. But that is not drawing the doctrine from those Testaments. We have first drawn it from the Writings. But why belabor the obvious? It cannot justly be denied that the doctrines distinctive of the New Church -those doctrines which make it the crown of churches - are to be drawn from the Writings, that is, from the genuine meaning of their letter.

The teaching that the doctrine of the church must be drawn from the sense of the letter of the Word, is a general teaching applicable to all churches founded on the Divine Word. And since there have been several churches founded on different revelations, therefore in the specific application of the teaching, the term "the Word" must be understood in accordance with what is meant by "the Church." Applied to the Ancient Church, the teaching would be that the doctrine of that Church is to be drawn from the sense of the letter of the Ancient Word; applied to the Jewish Church, that its doctrine is to be drawn from the sense of the letter of the Old Testament. Applied to the Christian Church, that the doctrine of that church is to be drawn from the sense of the letter of the New Testament; and applied to the New Church, that the doctrine of the New Church is to be drawn from the sense of the letter of the Writings; in a word, that each church must draw its doctrine from the sense of the letter of the revelation given to that church. By the sense of the letter, as I have already said, I mean the genuine meaning of the letter when read as a Divine Revelation and with a view to receiving instruction from the Lord.

Naturally the Writings also are the letter of the Word. Why should this startle us? Those Writings are certainly a Divine Revelation; it is equally certain that they are written in words or letters, and that in these words the Lord teaches us only so far as we see their sense or meaning.

We read that "the doctrinals of the church must first be learned, and then exploration must be made from the Word as to whether they are true. For they are not true because the leaders of the church have so stated and their followers confirm it. . . . When this is done from the affection of truth, the man is then enlightened by the Lord, so that, without knowing whence, he sees what is true and is confirmed therein according to the good in which he is" (@AC 6047; SS 59).

Here again we have a general statement applicable to all churches, which must be understood according to the rule of interpretation previously referred to. Applied to the New Church, the teaching obviously means that the doctrinals taught by the leaders in that church must first be learned, and then exploration must be made from the Writings as to whether they are true. Manifestly it cannot be doubted that those who are able should themselves test the truth of what the leaders of the New Church preach as the genuine doctrine drawn from the Writings; for that doctrine is not true because the leaders of the church so declare it, and their followers confirm. It is equally manifest that the test can be made only by going to the Writings themselves as the final court of appeal. As to the truths taught by those Writings themselves, it is clear that when one acknowledges those Writings as a Divine Revelation, it would be superfluous, not to say presumptuous, to test their teachings by an examination of the Old and New Testaments. Such a test is called for only when the purpose is to ascertain whether the Writings are truly a revelation from God.

Here we may add by way of parenthesis that a distinction must be made between the doctrine of the church as drawn from the sense of the letter of the revelation to that church, and the revelation itself. The latter is the Word, and this is the Doctrine of Divine Truth (@AE 612), and, in the case of the Writings, the Heavenly Doctrine revealed out of heaven (@NJHD 7). The former, the doctrine of the church, is man's finite perception of the sense of the letter of revelation; and being finite it is variable; it may even be false, and at best it is always subject to improvement, clarification, development. Every distinctive body of the New Church has drawn from the Writings the doctrine which distinguishes it. This is a plain fact and is quite independent of whether or not the doctrine so drawn is justly drawn, or even of whether the Writings are acknowledged as a Divine Revelation in any real sense of the term.

And now I will quote a passage which to my mind leaves no doubt that by the sense of the letter from which the doctrine of the New Church is to be drawn is meant the clear and genuine meaning of the words of the Writings. This passage is one of a series wherein is expounded the Apocalyptic description of the New Jerusalem. It reads: "Having a wall great and high signifies the Word in the sense of the letter from which is the doctrine of the New Church; for this sense protects the spiritual sense which lies within, as a wall protects a city and its inhabitants. . . . The doctrine of the church is to be drawn from the sense of the letter of the Word and to be confirmed by it. . . . That the Word in the sense of the letter is signified by a wall, is clearly manifest from what follows in this chapter which treats much of the wall, its gates, foundations and measures. The reason is because the doctrine of the New Church which is signified by the city is solely from the sense of the letter of the Word. . . . By the twelve foundations of the wall are signified all things of the doctrine of the
[New] Church, by foundations being signified doctrinals, and by twelve all. . . . And he measured the wall of it a hundred and forty-four cubits signifies that it was shown what the quality of the Word is in that church, that from it are all her truths and goods. . . . By the wall is signified the Word in the sense of the letter. . . . And the building of the wall of it was jasper signifies that all the Divine Truth of the Word in the sense of the letter with the men of that church is translucent from the Divine Truth in the spiritual sense" (@AR 898, 902, 909, 911).

In reading this teaching, three things should specially be borne in mind:

First: That the doctrine of the New Church, as distinct from the Heavenly Doctrine or the Word itself, can be drawn not from the Old and New Testaments but solely from the sense of the letter of the Writings. We have already dwelt on this obvious truth.

Second: That the Apocalypse "from beginning to end treats of the last state of the Church . . . then of the Last Judgment and after this of the New Church which is the New Jerusalem. The New Church is the end of this work" (A R. Pref.). Therefore the New Church is described 'not only by the New Jerusalem itself but also by its wall and the foundations thereof. It is the Writings that are the wall of the New Church, and not the Old and New Testaments, except in a general sense which includes also the Writings. Therefore this wall is described as being of jasper, with gates of pearl, and its foundations as being garnished with precious Stones (Apoc. 21: 18, 19, 21).

Third: That by the foundations of the wall, that is, of the sense of the letter of the Word, are meant all things of the doctrine or doctrinals of the New Church, by foundations here being meant that upon which the wall, that is, the sense of the letter, rests. Now it cannot be said that the sense of the letter of the Old and New Testaments rests on the doctrines or doctrinals of the New Church. Not so in the case of the Writings, for their letter is founded on the doctrinals drawn from the Old and New Testaments for the use of the New Church. The very warp and woof of that letter consists of those genuine doctrines which the Jewish and Christian Churches might have learned. Moreover, "doctrine from the literal sense of the Word" or "the doctrinals of that church from the sense of the letter of the Word are specifically said to be the wall of the New Jerusalem (@DSS 10; @TCR 197)
as well as the foundations of the wall. This wall is said "to protect the spiritual sense which lies within" (@AR 898); that is to say, the letter of the Writings is a protection for the spiritual arcana which lie within; I shall speak further of this matter in connection with nos. 91-97 of the Doctrine of the Sacred Scripture on the subject of the origin of heresies in the church.

I should like now to add some further observations as to the necessity of drawing the doctrine of the New Church from the sense of the letter of the Writings.

The Old Testament, and to a less degree the New, were written partly in language which so deeply concealed the spiritual sense within, that it could not be penetrated by the men of the church, and partly in language from the sense of which, when read holily, the truths of heaven could be seen. In contrast with this, the Writings are written in language the sense or meaning whereof everywhere reflects the spiritual arcana within, and reveals them to man so far as he approaches the Lord from the love of truth for its own sake. Here are no cryptic utterances, no impenetrable veils, no dark sayings. True, we find in the Writings apparent contradictions, passages the import of which we may but faintly comprehend; all these, however, are but the different facets of the one truth, and when, by further study of the sense of the letter of the Writings, we see this truth, they not only become clear but, and this should well be noted, these apparently contradictory or obscure statements are then seen as necessary elements to the full comprehension of the truth. I suppose most New Church students have experienced this in their own studies, have pondered over seeming obscurities and contradictions, and then when light has come to them, have seen that the obscurities were merely the effect of their lack of understanding, and that the contradictions were not contradictions but statements necessary for the presentation of the complete truth.

The same thing is true of the sense of the letter of all revelation; I mean the sense of the letter from which the church to which the revelation is given can draw its doctrine. The reason is, because Divine Truth is presented in a form adapted to all manner of states, and so is necessarily presented in many appearances. Take, for instance, the statements in the Old Testament, that God is angry with the wicked every day, and that He is slow to anger. One who sees the truth which is thus presented in the sense of the letter does not reject either of these statements, for he sees that both are necessary for the full comprehension of that truth, and that when the truth is seen both statements remain.

This is not the case with those portions of the Old Testament where the letter deeply conceals the truth within. Thus if we read of the wars of the Jews and are told that they represent the combats of the Lord with the hells, then if we are to contemplate the truths which are thus concealed under the description of these wars, sometimes with cruel details, we must dismiss the picture of the wars; it does not remain as a facet of the truth, but like a garment which is no longer of use, must be dismissed when the truth is seen. The letter must die that the spirit may live.

How different is it in the Writings. The letter of the Writings is made up of doctrinals drawn from the sense of the letter of the Old and New Testaments, of rational arguments, of illustrations taken from nature and the sciences, of relations concerning the spiritual world, and here and there of statements where the deeper arcana of heaven are set forth to plain view. And every statement, every expression, every argument, is a necessary part in the setting forth of Divine Truth to be seen in the sense of the letter. There should be no difficulty in seeing this; for the language of the Writings is manifestly designed to explain the truths of heaven, not to hide them; to make them clear to the rational mind, not to present a cryptic veil.

It is because of this that the Revelation now given to the New Church is the crown of revelations and the final one. The whole of the Heavenly Doctrine is now revealed; it remains for men to draw it forth from the sense of the letter of that revelation, according as the Lord gives them enlightenment. They are to draw from an everlasting fountain; and the more they draw, the more clearly will they see the Divine truth in the sense of that letter which constitutes the Revelation to the New Church.

It should not be a matter of wonder that the doctrines of the New Church are to be drawn solely from the sense of the letter of the Writings; for the men of the New Church must be taught by the Lord alone, and the Lord teaches only in the sense of the letter of His revelation. "it is most important for man to study the Word in the sense of the letter (say the Writings); thence only is doctrine given"
(@DSS 56). If there Is other teaching than what is plainly set forth in the sense of the letter of revelation, then either it will be the product of human imagination, and so have no power and no authority; or it will be a new Divine Revelation; for, as we have already noted, when truth is deeply veiled and concealed in the language of correspondences, it is the Lord alone who can reveal it.

Here we have the reason why the nature of the Writings is such that those Writings everywhere set forth the Divine Truth in the sense of their letter; that they are written in no other language of correspondences than that natural correspondence which clearly reflects the Divine Truth in the sense of their letter; that it is from the sense of their letter that doctrine is to be drawn, and not from correspondential interpretation. It is because of this their nature that it is said of the Writings that they are a revelation which "surpasses all the revelations that have hitherto been made since the creation of the world" (Inv. 44).

And now I would touch on a phase of this subject to which I have already adverted and which is dealt with in the Doctrine of the Sacred Scripture when developing the teaching that doctrine is to be drawn from the sense of the letter of the Word. I refer to the statement that:

=== GENUINE TRUTH, WHICH WILL BE OF DOCTRINE, DOES NOT APPEAR IN THE SENSE OF THE LETTER OF THE WORD TO ANY BUT THOSE WHO ARE IN ENLIGHTENMENT FROM THE LORD (@DSS 57).

This statement involves that the Writings are not the naked spiritual truth or internal sense of the Word, but that they are written in human language so adapted that the sense of its letter contains the genuine truth of heaven. Any intelligent man can see the sense of the letter of the Writings, but only those who are in the genuine love of truth can see the spiritual truth within. Whether a man belongs to the one class or the other can be known only to the Lord; we cannot distinguish between them.

The Writings are written in the language of rational thought, with illustrations and confirmations such as pertain to rational thought. Any man can see the truth of their statements and can see the ramifications and extensions of that truth, provided he has the necessary education and intelligence, and provided also he lifts his understanding above the light of the world and sees in the light of heaven. Indeed, in such case, those who are endowed with keen mental vision can see more clearly than others, and if gifted also with the art of expression, can set forth what they see so that it may be the means of instruction and of progress in the church. Yet unless such a man has the love of spiritual truth, he sees nothing more than the rational forms with which, in the Writings, such truth is clothed; he is blind to the truth itself which lies within the rational ideas that he so clearly sees and so eloquently presents to the view of others; and these others may see and be affected by the spiritual truth within, of which the teacher himself has no perception, and by which he is not affected. For while the preacher may set forth the Word, it is the Lord alone who causes man to see the truth (@DP 172).

As an illustration of this, I might point to the ability possessed by all men, when thinking above the light of the world, to see the truths concerning life delivered by the Lord in the Gospels. The more intelligent of such men can also proclaim these truths with clearness, force, and eloquence. And yet it is possible that they have no sight of the truths themselves. Other illustrations might be given. Thus, an evil statesman, if he is also intelligent, may clearly see and eloquently set forth the truth that the love of country demands that a man shall be willing to lay down his life for the sake of his country; and yet the statesman himself may be in the love of his own glory, without any perception of the spiritual truth which lies within the words which he so convincingly pours forth.

The indication of what it is that a man really sees is to be found in the manner in which it affects him. If a keen judge of the beauty of poetic imagery admires the language of Isaiah but is blind to the spiritual truths which here and there shine out therein, it is a sign that he sees merely poetic form and the beauty of natural truths. So if a man of keen perception reads the Writings and admires the rational form of the truths there set forth, but is unaffected by the Divine Truths which thus present themselves that they may lead to love to the Lord and charity toward the neighbor, it is a sign that he sees, and it may be, can eloquently present, the sense or meaning of the letter of the Writings, but is blind to the spiritual truths there revealed. He sees the meaning of the Writings merely because it is rational, but not because it is heavenly.

Here let me note that no one can see the rational truths set forth in the Writings unless his mind is elevated into the light of heaven. This is true whether the man does or does not see, that is, is or is not affected by, the spiritual truths which lie within the rational statements. A man can see natural facts, their order and sequence, and the natural law of cause and effect, merely from worldly light, and this by virtue of the gift of rationality which is the human birthright. But to see, that is to say, to understand, the rational forms of spiritual truth, even if be sees no more than the forms, he must elevate his sight into the light of heaven. In the light of the world no one can see that God is a Man; for in that light man can think only of a corporeal man and in space. But if he elevates his mind above the light of the world, he can see that God is a man apart from space; and he can see this as a rational truth, even though be has no love of God.

It is a well-known teaching of the Writings that man can elevate his understanding into the light in which the angels are; and this teaching has been frequently interpreted as meaning that man can see spiritual truths as the angels see them. There is, however, one passage (@TCR 588)
and perhaps more than one, which states that he "can elevate his understanding almost into the light in which the angels of heaven are."
The word almost has its significance here, and should not be ignored. In effect it means that man cannot elevate his understanding into the light in which the angels are, but that he can appear to do so, the appearance being so strong that he almost does so in fact. This "almost" becomes clear when we consider that an evil man can so elevate his mind as to see in the light of heaven the rational forms of truth wherein the Divine reveals itself, and this even to confession; yet without any perception of the Divine Truth thus revealed. He may for a time even see the latter, and thereby be moved to a sort of repentance, but if be does not shun evils as sins, this is merely the effect of angelic spheres acting upon his external mind. It is no interior seeing. The reason is that the seeing of truth depends on the influx of the light of heaven into the mind, but so long as the mind does not receive the heat of heaven, there is no reception of the interior activity or determination which makes the form of truth. Consequently, the essential truth, which in itself is the determining activity of good, is not seen and the man is not affected by it. He sees truth separate from good, and such truth is a mere form without its soul.

The seeing of the rational forms of truth is a real seeing by the understanding, and so long as that understanding is elevated, the seeing continues, even though the man may be in evils. This is well known; for a man can condemn himself even while he is in the will and actual intention of committing evils.

This ability to elevate the mind almost into the light of the angels of heaven, is possible not only because of the God-given gift of rationality but by virtue of the fact that in the sense of the letter of the Word, the forms of Divine Truth are set forth. The evil can see these forms from the rational which is open to every man. But the good see and are affected by them not merely as rational forms, but as truth proceeding, from good, that is, as truth proceeding from the Lord for the salvation of man.

This, as it seems to me, Is what is meant by a striking teaching given in the Arcana Coelestia nos. 2496 seq., to the effect that the doctrine of charity and faith "is a spiritual doctrine from a celestial origin, and not from the rational."

The doctrine of charity and faith revealed by the Lord in his Word must be acknowledged not because it is seen to be rational but because it is seen to be true - to be the law of God; and it is so seen by all who read the Word holily to the end that they may be instructed by the Lord. Men who thus read the Word are affected by the spiritual and celestial truth within the sense of the letter, and so are enlightened by the Lord. Yet, being human, their sight is limited; it must be enlarged by confirmations drawn from the sense of the letter, and, it may be, by rational considerations. Their faith, however, is based not on rational arguments but on the perception of the genuine truth which appears in the sense of the letter of the Word. Thus their doctrine is a spiritual doctrine from a celestial origin but not from the rational. Yet to make it possible for men so to see the Divine Doctrine, the latter is always set forth "in a rational manner adapted to the comprehension of man" (@AC 2533), and so can be confirmed by the rational.

On the other hand, if the truths of the Word are seen merely because they are rational, that is to say, if the forms of truth are seen without any perception of the Lord within them, then those truths are not "spiritual doctrine from a celestial origin," and do not conjoin man with the Lord. They may afford a palliative remedy and may hold the man in a state in which he may afterwards be led to the Lord; but they cannot themselves effect any real cure.

"Doctrine is to be procured only from the Word (says our revelation), and by no others save those who are in enlightenment from the Lord . .
. that is, who love truths because they are true. All things belonging to doctrine are to be confirmed by the sense of the letter of the Word
. . . because in the sense of the letter, Divine Truth is in its fullness; for that is the ultimate sense and in it is the spiritual sense. Therefore, when doctrine is thence confirmed, the doctrine of the church is also the doctrine of heaven, and conjunction is effected by correspondences" (@AE 356 fin.).

=== BY THE SENSE OF THE LETTER OF THE WORD THERE IS CONJUNCTION WITH THE LORD AND CONSOCIATION WITH THE ANGELS (S.S. 62-9)

It is frequently supposed that the conjunction and consociation here referred to is effected by man reading the Old or New Testament holily without regard to whether or not he enters into the meaning of what he reads. I have already treated very fully of this matter and need not here repeat. I would, however, again emphasize the fact that what conjoins and consociates is not the letter of the Word but the sense of the letter and the reception of that sense. The mere reading of the letter is not enough. It may bring presence but not conjunction. Thus we are told that "the Lord is present with a man by the reading of the Word; but He is conjoined with him by the understanding of truth from the Word" (@DSS 78); and furthermore, "All the wisdom of the angels is given by the mediation of the Word . . . when this is read by man, and when there is thought from it" (@SD 5187).

Therefore consociation with angels, and conjunction with the Lord can be brought about only when a man reads the Word with some acknowledgment from the heart that it is the Lord's teaching. This acknowledgment causes him to see the presence of the Lord in ultimates, and it is this perception that constitutes the reciprocal act which effects conjunction with the Lord and so consociation with angels.

This is involved in the very first of the passages which deal with the heading now under consideration. "That by the Word there is conjunction with the Lord (we read) is because He is the Word, that is, the Divine Truth and Divine Good therein. That the conjunction is by means of the sense of the letter, is because in that sense the Word is in its fullness, in its holiness, and in its power. This conjunction does not appear to the man, but it lies in the affection of truth and in the perception thereof" (@DSS 62). The sense of the letter of the Word is then defined by a reference to a previous passage (n. 6 - which we have already quoted), where it is said that "in its ultimate sense the Word is natural, in its interior sense spiritual, and in its inmost celestial; and in every sense it is Divine." Thus when man reads the Word, and, from the affection of truth, understands the sense of the letter which is the divine natural sense, the angels are in the spiritual or celestial senses. This is then illustrated by passages from the Word, and the very nature of these passages clearly indicates that what conjoins man with the Lord is not the letter but his understanding and perception of the genuine sense of the letter. For whereas in a former chapter (nos. 5-26) showing that there is a spiritual sense in the Word, the examples taken from the Word are all passages where the spiritual sense is deeply veiled, in the present case where the subject is conjunction with the Lord by means of the sense of the letter, the illustrating passages taken from the Word are without exception passages in which the spiritual sense shines out in the sense of the letter, namely, Honor thy father and thy mother; thou shalt not steal; thou shalt not commit adultery; thou shalt not bear false witness.

I have already spoken of the universal law which underlies the teaching that conjunction with the Lord is by means of the sense of the letter of the Word, namely, that the Lord reveals himself to man in ultimates, where alone man is in the free choice of reception. It is by means of ultimates that the Lord teaches man, enlightens the angelic heaven, and holds the universe in order. Therefore the Lord came on earth that He might be in firsts and at the same in lasts, and so might exercise all power in heaven and on earth. "Conjunction with heaven and by heaven with the Lord (we read) is not given by the spiritual sense but by the sense of the letter; for divine influx of the Lord is through the Word from firsts through ultimates" (De Verbo 15). And further: "It is the sense of the letter of the Word from which and by which communication with the heavens is effected; likewise from which and by which man has conjunction with the heavens. . . . Without that basis, the wisdom of the angels would be like a house in the air. . . . It is the sense of the letter of the Word by which man is enlightened by the Lord, and by which he receives answers, when he wills to be enlightened; it is the sense of the letter of the Word from which everything of doctrine in the earth is to be confirmed" (@AE 1066). Thus the conjunction is not effected by the mere letter but only by the sense of the letter, that is to say, only when man sees the Lord appearing in the sense of the letter. Therefore we are told that "there is no communication (of man with heaven by means of the Word) if the Word is comprehended merely according to the letter and not at the same time according to some doctrinal of the church which is the internal of the Word" (@AC 9410). In other words, there are no means by which man can be conjoined to the Lord, save by the sense of the letter of the Word, whether of the Old Testament, the New Testament, or the Writings; for it is only from the sense of the letter, that the doctrinals of the church can be formed.

In the Writings the Lord himself appears. There He speaks to man from Divine Love and Divine Wisdom clothed in a letter which constitutes a body of rational truth. There, if man will, that is, if he read the Writings from the love of truth, he can be conjoined to Him, and consociated with the angels of heaven.

But the Writings have something more; they not only are the means by which man may be conjoined with the Lord and consociated with the angels, but, they are also the means by which man can himself enter into the interior spiritual arcana of the Word; can think with the angels and as an angel, even while on earth. It is this that characterizes those Writings as the crown and fullness of Divine Revelation.

=== THE WORD IS IN ALL THE HEAVENS, AND ANGELIC WISDOM IS FROM IT (@DSS 70-75).

=== THE CHURCH IS FROM THE WORD AND IS SUCH AS IS THE UNDERSTANDING OF THE WORD (@DSS 76-79)

These points need no comment since they do not immediately concern the question under consideration.

As to the first, however, we may note that the Word which appears in heaven is not the same in external form as the Word as we know it. In the words of the Writings, "it is written in a spiritual style which is wholly different from the natural style" (@DSS 71). It is the same Divine Truth which with us is presented as the written Word, but it appears in a form which differs in the different heavens. Moreover, this form, though verimost reality, is yet dependent on the ultimate existence of the Word among men. For the Lord instructs both angels and men only by means of ultimates. "All the wisdom of the angels (we read) is given by the mediation of the Word, because in its internal and inmost sense is Divine Wisdom, and this is communicated to angels by means of the Word when the latter is read by man, and when there is thought from it" (@SD 5187).

We note also that the Writings were seen in the spiritual world. Thus the Arcana Celestia and the Divine Love and Wisdom were seen there on a cedar table (@TCR 461; @AE 875). There were also in the spiritual world copies of the Brief Exposition, on all of which was written the inscription, "This book is the Advent of the Lord" (Eccles. Hist. 8). So Heaven and Hell and the Last Judgment were seen in the spiritual world, and were twice read by a certain spirit from Holland (@SD 5908); and Heaven and Hell, the Last Judgment, the Earths in the Universe, the White Horse, and the New Jerusalem and its Heavenly Doctrine were given to certain Africans in the spiritual world (@SD 5946).

As to the second point, to quote from the Writings, "that the church is from the Word is not a matter of doubt" (@DSS 76). That the quality of the church is according to its understanding of the Word, follows from all that has thus far been said. Again to quote from the Writings: "The Word is spirit and life, according to the understanding of it; for the letter without the understanding of it is dead" (@DSS 77). Apply this to the New Church, and it is obvious that the quality of the New Church depends not on its possession of the Writings but on its understanding thereof. "Since a man has truth and life according to his understanding of the Word [and with the New Churchman, according to his understanding of the Writings], he also has faith and love according to it. . . . And since the church has its being by means of faith and love and according to them, it follows that the church is a church by means of its understanding of the Word; a noble church if it is in genuine truths, ignoble if not in genuine truths, and destroyed if in truths falsified" (@DSS 77).

=== IN EVERYTHING IN THE WORD IS THE MARRIAGE OF THE LORD AND THE CHURCH, AND THENCE THE MARRIAGE OF GOOD AND TRUTH (@DSS 70-90)

This teaching has sometimes been understood as meaning that in the Word there are dual expressions or dual words, one signifying good and the other truth; and doubtless the thought has occurred to many that since this ultimate representation of the marriage of good and truth is characteristic of the Word, therefore the Writings cannot be the Word, seeing that they are in no way characterized by the use of such dual expressions. This, however, is mistaking an effect for the cause. It is as though I should say that the marriage of good and truth does not exist in the human internal, since that human internal does not have two eyes, or two ears, etc.

The dual expressions in the Old Testament, and to a much less extent in the New, are not themselves the marriage of good and truth, they are merely the most ultimate representation of that marriage. The marriage itself is present everywhere in the Word, but it is represented by dual expressions only here and there. Therefore we read: "Because this marriage is in everything of the Word, therefore there are very often two expressions in the Word which appear like repetitions of the same thing" (@DSS 81). In the Old and New Testaments the spiritual marriage is also, and perhaps more frequently, represented by the marriages of men and women. But these also are merely the occasional representations of that heavenly marriage which exists everywhere in all Divine Revelation.

What that marriage itself is, is thus described in the Doctrine of the Sacred Scripture: "When the man of the church is in truths, then the Lord flows into his truths with good, and vivifies them; or what is the same thing, when the man of the church is in intelligence by means of truth, the Lord then flows into his intelligence by means of the good of love and charity, and thus infuses life into it" (@DSS 82).

In all Divine Revelation, what is revealed, is the Divine Wisdom from Divine Love, or Divine Truth from Divine Good. Hence all revelation is a revelation of truth that it may prepare man for the reception of good to the end that he may bring forth the fruits of heaven. In the deeply veiled portions of the Old Testament and the Apocalypse, this marriage is represented sometimes by a duality of expressions which has been noticed by Biblical critics, and been imitated by poets; and sometimes by stories of human marriages and their offspring. But in those portions of the Old and New Testaments where the spiritual sense is set forth in the sense of the letter, these representations are less in evidence, and what necessarily predominates is the note of exhortation to a life of obedience to the Divine precepts. This is a more open and living manifestation of the marriage of good and truth which exists everywhere in the Divine Word; consequently it is a manifestation more potent for the actual establishment of that marriage with men, and so for the formation of a genuine church.

This difference in the external characteristics of different parts of the Old and New Testaments as regards the marriage of good and truth or of the Lord and the Church is plainly indicated in the implications of a passage in the Writings which I have already quoted, but from which I shall again quote a few lines as follows: "There are many things in the sense of the letter of the Word which cannot serve for any doctrine of the church at this day; . . . but still there are intermingled many things from which doctrine can be collected and formed, especially the doctrine of life" (@AE 356), that is to say, the doctrine which exhorts man to the good of life, or to the marriage of good and truth.

Now this exhortation which so manifestly characterizes certain portions of the Old Testament, and which is seen in the Gospels to a far greater degree; this divine exhortation to men in the sense of the letter of the Word, to the end that a church may be established which shall be the Bride of the Lord; this, I say, is pre-eminently the characteristic of the Lord's Revelation to the New Church in the very sense of its letter; not its characteristic here and there as in the Old Testament; not even its predominant characteristic as in the New Testament; but its all pervading characteristic. On every page, in every word, the Writings breathe nothing but the marriage of good and truth. They exhort to this marriage not in the obscure though poetic imagery of dualism; not in the deliverance of spiritual truths dimly perceived; but in rational language whereby the Divine Truth of the Divine Good openly instructs man, gives him strength to fight against the forces of hell if he will, and is ever urgent for the establishment of a church which shall be a genuine spiritual church, the Bride of the Lord.

It is no fanciful picture that I am describing. Every one who has read the Writings with any desire to learn the Lord's will for the guidance of his life will recognize its truth, knowing that when the Writings are thus read they are at once perceived as a perpetual exhortation to genuine repentance and to the living of that spiritual life which is the fruit of the marriage of good and truth.

We have also the literal testimony of the Writings themselves. In a passage in the Arcana, the theme of which is the showing that there would be no doctrine of faith if the rational were consulted, we read:
"And, what is an arcanum, every doctrinal is from the Divine Good and the Divine Truth, and has in itself the heavenly marriage. The doctrinal which does not have within it this marriage, is not a genuine doctrinal of faith. Hence it is, that in the single things of the Word which is the source of doctrine, there is an image of marriage" (@AC 2516).

=== HERESIES MAY BE TAKEN FROM THE SENSE OF THE LETTER OF THE WORD, BUT IT IS HURTFUL TO CONFIRM THEM (@DSS 91-97)

Here as in a previous heading we have a general statement applicable to all churches; for in every church, heresies are taken from the sense of the letter of the revelation to that church. In the Ancient Church they arose because men falsified the Ancient Word by teaching that the names of God designated separate gods - whence arose idolatry. The Jewish Church was destroyed, or rather was prevented from being a genuine church, by its interpretation of the Hebrew Scriptures as promising an earthly kingdom to themselves, and by its traditions whereby the commandments of God were made of none effect. So heresies arose in the Christian Church from wrong interpretations of the New Testament. The application of the same law to the New Church and the Writings is obvious. Indeed, without this application the present heading would be void of meaning for the New Church; it would be merely a statement of what may take place in the Jewish or Christian Churches.

No heresy can possibly arise in a church, save from the falsification of the sense of the letter of the Word given to that church. It would be impossible to imagine a heresy in the Christian Church as having its source in a falsification of any other revelation than the New Testament. Nor can any one conceive of a heresy in the New Church arising from any other source than a falsification of the Writings. The history of the Church is eloquent testimony to this.

With regard to the origin of heresies in general, I would again note that all Divine Revelation is in ultimates; and it is a limitation inherent in ultimates that they can express truth only by presenting it separately in its various facets or phases. This involves that the truth is presented in different appearances even to the point of contradiction. Fastening their attention on the one appearance or the other, that is to say, on one apparent truth, or another, men may therefore come to different opinions as to what the Word teaches. This is the origin of diverse doctrines in the church, and also of heresies.

As already stated, this law as to the origin of heresies applies also to the New Church. But what I wish now to call particular attention to, is that this application is clearly involved, as it seems to me, in that vision of the New Church which was seen by Swedenborg in the spiritual world. I refer to the description in the True Christian Religion of that magnificent temple on whose portal were written the words NUNC LICET. We read: "In the midst of the temple was a shrine, in front of which was a veil, but now uplifted, where stood a cherub of gold with a sword in his hand waving this way and that . . . . The temple signified the New Church; . . . the shrine in the midst of the temple, the conjunction of that Church with the angelic heaven; the cherub of gold therein, the Word in the sense of the letter. The sword waving in its hand signified that this sense can be turned this way and that, provided this be done in application to some truth. That the veil before the cherub was uplifted signified that how the Word is laid open" (@TCR 508).

It is commonly supposed that by "the sense of the letter" here, is meant the Old and New Testament. If such be truly the case, then this part of the representation seen by Swedenborg can mean nothing more than that the letter of the Old and New Testament can be interpreted in various ways provided this be done to confirm some truth taught in the Writings - for naturally no one in the New Church would use the Word for any other purpose. This of course is true, but it can hardly be said to be a guard against undue entry into the interiors of the Word - and that a cherub signifies such a guard is evident.

In the supreme sense, a cherub represents the Lord's providence preventing man from entering into the interiors of the Word from himself and his own proprium (@AC 308, 2761). "By cherubs (we read) is signified a guard, that the Lord, heaven, and the Divine Truth as it is interiorly in the Word, be approached, not immediately but mediately by means of ultimates" (@DSS 97).

This guard is provided by the fact that all revelation is made in ultimates. Here man stands at the threshold of heaven. While he can see and understand the truth of the statements in the ultimate words of revelation, he cannot see the spiritual truths within, that is, cannot be affected by them, unless he approaches the Lord in that revelation with the desire to learn from Him the way to heaven. This, as I have already observed, makes sure to man his freedom of choice; it is also a guard lest he enter into the truths of wisdom save so far as he can be held in them to the end of life (@DP 232).

"The sense of the letter of the Word (we read) is a guard for the genuine truths that lie within, lest they be injured; and the guard consists in the fact that this sense can be turned this way and that, and can be explained according to one's apprehension, and yet its internal not be injured or violated. For it is not harmful that the sense of the letter is understood by one person differently than by another; but it is harmful if man brings in falses that are contrary to Divine Truths, - which is done solely by those who have confirmed themselves in falses. By these, violence is done to the Word. The sense of the letter guards against this, and it so guards with those who are in falses from religion but do not confirm its falses" (@TCR 260; SS 97).

This guard was shown to Swedenborg in the spiritual world by a representation wherein he saw great open purses filled with silver, but guarded by angels. The purses of silver signified cognitions of truth, and "their being opened and yet guarded by angels, signified that every one could take therefrom cognitions of truth, but that care is taken lest any one shall violate the spiritual sense within, wherein are unmixed truths" (@DSS 26).

This guarding of spiritual truths by the sense of the letter which both clothes and presents them, is characteristic of all revelation - and this of the Divine Providence for the preservation of man's freedom, and the prevention of profanation. And so I can entertain no doubt but that by the cherub with the waving sword in his hand whom Swedenborg saw standing in front of the uplifted curtain which revealed the shrine, that is to say, revealed the conjunction of the New Church with the angelic heaven, was signified the sense of the letter of the Writings. It is this sense that is the threshold before the uplifted veil revealing the Lord; the threshold from which man can behold the Lord and be conjoined with the angelic heaven; the threshold where for a time some are detained because of obscurity arising from appearances, which yet in some way confirm with them the acknowledgment of God and the life of charity; the threshold in which others are held imprisoned lest they seize on heaven as the servant of their evil loves, and be destroyed in the seizing.

Being written in the language of natural ideas, the Writings present spiritual and celestial truth in natural appearances. True, these appearances are not of the simple character found in the Old and New Testaments, but that they are appearances is sufficiently testified to by the fact that in respect to various subjects New Churchmen differ in their views as to what is the genuine teaching of the Writings. Thus, on the basis of what they read in those Writings, some hold that the body which the Lord had in the world, was dissipated, while others, on the same basis, hold that it was changed to a divine substantial body; some hold that the Writings are the Word, while others hold that they are not the Word but the internal sense of the Word; some hold that open communication with angels will again be restored as it was in the Most Ancient Church, while others hold that such communication will never be restored; and so forth. As the men of the church progress in enlightenment, they will come to see the true relation of these differing views, and that both are necessary to a fuller understanding of the truth.

Meanwhile to hold to the one of these views or the other is not harmful provided the man does not thereby confirm himself in the loves of self and the world. Based on appearances in the Writings, heresies may spring up which in themselves are destructive of spiritual truth; yet even the belief in these does not condemn a man provided he believes them in simplicity because he thinks the Lord so teaches in the Writings, and provided also he lives the life of religion. They are destructive of spiritual life only with those who confirm them from evil loves and who thereby blind their eyes to the teaching of the Lord; but as to who these are, this is known to the Lord alone. It is to guard against such heresies that we are admonished to go to the Lord in his Word and there to receive enlightenment. There is no other guard.

=== THE LORD CAME INTO THE WORLD TO FULFILL ALL THINGS OF THE WORD, AND THEREBY TO BECOME THE DIVINE TRUTH, OR THE WORD, IN ULTIMATES ALSO (@DSS 98-100)

=== BEFORE THE WORD WHICH IS IN THE WORLD AT THIS DAY, THERE WAS A WORD WHICH IS LOST (@DSS 101-104)

=== BY MEANS OF THE WORD, THOSE ALSO HAVE LIGHT WHO ARE OUTSIDE THE CHURCH AND HAVE NOT THE WORD (@DSS 104-113)

As connected with the subject of the present study, little need be said with respect to these three headings. The first two are historical statements. The third must necessarily apply to the Writings if the Writings are the Word, but it does not itself determine that question, the immediate reference, as is so frequently the case throughout the Writings, being to the Old and New Testaments, or, more specifically, to the Word which is in the church of the Reformed (@DSS 110).

With regard to the first heading, however, I would note that the teaching that the Lord came into the world to become the Word in ultimates, involves that He also came as the Word in His second coming. In the Gospels He reveals himself as a Divine Man fulfilling the Word; in the Writings He reveals himself as the Divine Human Glorified. Note here a statement made in the text. It reads: "Few understand how the Lord is the Word; for they think that the Lord can enlighten and teach men by the Word, and yet cannot from this be called the Word. But let them know that every man is his own love, and thus his own good and his own truth. A man is not man from anything else. . . . But the Lord is the Divine Good itself and the Divine Truth itself, and thus is THE MAN
from whom every man is a man" (@DSS 100; see also @DP 172).

The evident import of this teaching is to show that in thinking of the Lord as the Word, we are not to think of the mere letters; that is to say, in the case of the First Coming, of the letters and words of the Greek Gospels. These are taken from the minds of men, and in themselves are a mere body. The Lord as the Word is the Lord appearing as Love and Wisdom in the sense of the letter of the Gospels. To the man who reads the latter with the desire to learn of the Lord, it is the Lord Jesus Christ whom he sees appearing in the sense of the letter. There the Lord reveals himself, unfolding the Scriptures and giving instruction in a manner adapted to the comprehension of his hearers and of the church they were to be the means of establishing.

In the Second Coming, the Lord appears with power and great glory, that is to say, He reveals himself openly as the Divine Man glorified. It is not the Latin letters and words of the Writings that are the Lord as the glorified Word, for these were taken from Swedenborg's mind and in themselves are dead. It is in the sense of their letter that the Lord appears. There, it is He who is the Word, He who speaks, He who instructs, He who enlightens. Yet the letter and the sense of the letter, being natural, serve as a guard lest those should behold the Lord who would profane. For man can see the letter, he can also see the sense of the letter, and yet not see the Divine Love and Wisdom of God Man. Only those see this who are in the love of truth for the sake of truth.

=== IF THERE WERE NOT A WORD, NO ONE WOULD HAVE A KNOWLEDGE OF GOD, OF HEAVEN AND HELL, OF THE LIFE AFTER DEATH, AND STILL LESS OF THE LORD (@DSS 114-118)

This heading constitutes the last chapter in the Doctrine of the Sacred Scripture. Specifically the chapter is directed to showing the impossibility of natural theology, that is, of a theology not drawn from Revelation. It declares that there can be no knowledge of God, or of the Lord, or of the Spiritual World, except by means of the revealed Word; and the declaration clearly identifies as the Word all revelations which impart these knowledges to man. In the Old Testament, God reveals himself as the doctrine of faith and charity; in the New Testament, he reveals himself as a Man, teaching more interior truths, and leading to closer conjunction with himself. In neither of these revelations, however, do we learn anything concerning heaven and hell, except that they are the final abodes of men according to their life on earth. They do not teach any of those interior arcana which are so fully disclosed in the Writings, arcana which "if there were not a Word" would remain unknown. They can now be known for the first time by means of the Word delivered to the New Church.

Let me here quote a striking passage from the Spiritual Diary n. 1464, which is peculiarly significant in this connection:

"I spoke concerning those in the world who will say no other than that they have the Word, and that there is no need of revelation, thus rejecting these things, which come forth and descend out of heaven; when yet what is here treated of is the genuine meaning (sensus) and understanding of the Word, and the nature of faith, and, in addition, many things specifically concerning the state of those who are in the other life; for, in its ultimate or literal sense , the Word simply mentions heaven and hell, with damnation in hell and felicity in the heavens; and yet there are things indefinite in both. Therefore the objection that they have such things solely from the things [already] revealed, is of no avail."

== IV CONCLUSION

I have now finished my self-imposed task of running through the Doctrine of the Sacred Scripture to show that what is there said concerning the Word applies to the Writings also, though with discrimination. The reader may perhaps have noticed that, nevertheless, I have generally referred to the Revelation to the New Church not as "the Word" but as "the Writings." I have done this purposely, though, as surely it is unnecessary to explain, not with any idea of detracting from their status as the Lord's Word. The term "the Writings" is equally exclusive as the term "The Word," or "The Scriptures," and seeing that it has become established in the Church, and has a well-defined meaning, there seems no good reason why it should now be discarded for the term "the Word," unless indeed in literature whose special purpose is to demonstrate that the Writings are in truth the Word.

To me there is also another and positive reason why the term "the Writings" should be used rather than "the Word," namely, that the Revelation now given surpasses all other revelations. In previous revelations, the Divine Truth has been more or less veiled; in this revelation the Lord comes "with power and great glory." It seems appropriate, therefore, that this vital difference shall receive an ultimate expression in a difference of terms.

Moreover, the use of the term "the Writings" to designate our Revelation, rather than "the Word" avoids possible confusion of thought; for by a usage of almost two thousand years, "the Word" has come to mean the Old and New Testaments. The continual use of this term to designate the Writings, might therefore tend to turn the mind away from the distinction between previous revelations and this final revelation which surpasses them all in excellence.

I have no desire to lay this down as a point of doctrine; it is merely an expression of my view of what is the most suitable term with which to designate the Crown of Revelations on which the New Church is founded.

My primary endeavor in these pages has been not so much to show that the Writings are the Word, as to show that, granting this, to them must be attributed, though with rational discrimination, the characteristics which they themselves ascribe to the Word. Surrounded by the spheres of Christian thought, and accustomed to a use of words which has come from that thought, we are naturally apt to conceive of "the Word" as being the Word and Holy, not because it is Divine Revelation, but because it is Revelation couched in the form to which we have grown accustomed - the story of the Patriarchs, the poetry of the Psalms, the awful utterances of the Prophets, the simple truths of the Gospels, the visions of the Apocalypse. Nay, with many this attachment to the form of Divine Revelation is almost inseparable from a deeply rooted reverence for the King James' Version.

It is far from my wish in any way to weaken devout reverence for the Word of God. The Old and New Testaments remain the Word as before. Nothing is detracted from them by the revelation of the Writings, just as nothing was detracted from the Old Testament by the revelation of the New. Nay, rather is the opposite the case.

I would, however, waken in the minds of my readers, some reflection as to the nature of their reverence for "the Word." It is a fact, that those also may have reverence for "Holy Writ" with whom such reverence is mere tradition; and the reverence may remain even when He who revealed the Word is at heart denied. Therefore it may well behoove us, who have access to a revelation wherein is taught the source of the holiness of the Word - it may well behoove us, I say, to reflect as to whether possibly some tinge of idolatry, or something of merely historical faith may enter into our reverence for "the Word."

To the New Church it is given to know what the Word is and wherein is its holiness; to know that all Divine Revelation is the Word, whatsoever the form in which it is given; and that its holiness consists not in the form but in the fact that the Lord there speaks to men in ultimates, making manifest his Divine Love and Wisdom, that He may be present in lasts as in firsts for the accomplishment of the end of creation.

Seeing this, there will be no loss in true reverence for the Old Testament or the New; but there will be a more genuine reverence for that Crowning Revelation in which the Lord appears with power and great glory; and there will also be humble adoration of Him from a grateful heart, because He has been pleased thus to manifest himself and to reveal the hidden mysteries of eternal life.
