= Effects of the Last Judgement 
A Series of Doctrinal Classes
by the Rev. Hugo Odhner
include::../template-attributes.adoc[]

{empty}

////
INDEX
Class Number Subject of Class 
I THE HEAVENS THAT PERISHED. 
II THE NEW CHRISTIAN HEAVEN. 
III WHO CONSTITUTE THE NEW HEAVEN? 
IV (Part I) THE SACRAMENTS RENEWED. 
IV (Part II) THE EFFECTS OF THE LAST JUDGMENT ON THE SPIRITUAL WORLD
////

== Class I - THE HEAVENS THAT PERISHED

Reading: Revelation 20:11-15, 21:1-5

The most startling news proclaimed in the Theological Writings of Emanuel Swedenborg is that the last judgment foretold in the New Testament has taken place and that the Lord has made His second advent to establish a new heaven and a New Church; by which the imperceptible communication of heaven with mankind has again been restored and the spiritual world has been ordered so that the spirits of men may, if they are well disposed, find their way to heaven shortly after death.

This announcement involves many new concepts about the Word, the Lord, and the spiritual world, and also raises a number of questions about the relation of the New Church to the former Christian Church, and about the effects of the last judgment upon the world. It prompts us to inquire into the nature of the new heaven and ask of whom it is composed, and how its influence is to be communicated.

Much depends upon the answers given to these questions. For whatever answers we adopt will determine what we mean by the New Church and what our responsibilities are as New Church men and women, and also what uses the New Church should undertake; and thus will deeply affect our conscience and our conceptions of charity toward those within and without the church. And since marked differences may be observed, among those who profess the faith of the New Church, as to these matters, it seems important to examine what answers the Writings themselves furnish on the subject, and to reflect on their meaning.

---

The general doctrine is that there must always be a specific Church on earth where the Lord is known and the Word is read, and by which there can be a communication of mankind with heaven. (@AC 10765, 10500, @HH 305, 308, refs.) In the past, when one such church has perished and become vastated of spiritual life, it has been succeeded by another which is usually established among peoples that before had been gentiles. The four churches on this earth, since the time of creation, have been the Adamic, the Noatic, the Israelitish, and the Christian. At the end of each dispensation, the Lord appeared and executed a judgment in the spiritual world upon the man (that is, the spirits) of the consummated church, forming a new heaven of the good and a new hell of the evil. Then from the new heaven, the Lord derived and produced a new church on earth, which took place by means of a revelation from His mouth or from His Word, and thus by inspiration. (Coro. i-iii.)

It is notable that a new Church cannot be established until after the Lord has performed a redemption in the spiritual world and formed a new heaven. This order is amply illustrated in the Apocalypse, where the judgment upon the corrupted Christian Church is first prophetically described and then the appearance to John of a new heaven and a new earth, and finally, the descent of the new Jerusalem from God out of heaven.

Heaven is onefor it is the Lords kingdom. It is called a Homo Maximus, a greatest human form, a grand man of uses. It is composed from spirits derived from all the earths in the universe. And specifically, the spirits of all the men who have been saved from our own planet since creation, also compose a human form, a Grand man, although no doubt incomplete in itself. It was formed by stages and degrees, from the successive churches and their contemporary gentiles. In this Grand Man, these churches have contributed to various heavenly functions corresponding to those of various bodily organs. But in actual appearance the ancient and most ancient heavens constitute higher expanses or levels in the spiritual world. Each expanse, or dispensational heaven, contains three degrees, or three constituent heavens (Coro. 16, 17). The reason why these expanses appear thus aloof and separate is that the way of life and thought in those heavens is utterly different from that of the men and angels of the centuries following the Lords coming. The angels of the ancient churches thus belong to a different world, and communicate consciously with the lower expanse only when special intermediations are provided. Otherwise the communication is solely by influx. (@HD 4, @AR 876, and Preface.)

In the highest expanse dwell the celestial angels, many of whom were of the Most Ancient Church. These celestial heavens were finally organized after the judgment signified by the flood of Noah. Below them is the expanse for the heavens of the spiritual angels, most of whom are from the Ancient Church which existed before the Lords Coming. These heavens were at first adjoined as an external of the celestial kingdom or the expanse above, but were made into a distinct kingdom when the lord had fulfilled the prophecies by glorifying His Human. (@AC 6372). It is of importance to note this. For the heavens are not finally organized in their first formation. Throughout the vast ages of the Ancient Church regenerating men found their way to heaven, forming societies where charity and intelligence abode. But these societies had their basis in prophecyrested on the hope of the Lords eventual coming. They were in representatives, by which they sought both to imitate the life of the celestial church which had perished and also to look forward to the Redeemer who was to come. And prophecy is never fully understood until its fulfillment comes. These heavens did not subsist on their own basis until the Lord had, by His life on earth, shown the real meaning of His advent.

The Hebrew and the Israelitish Churches were only external reformations within the declining Ancient Church, and their heavens were thus comprised within the second expanse. When the Christian Church arose, it was founded on an entirely new concept of God - on the faith in the Lord born, the Divine Natural. But the Christian heavens, formed from the apostles and early converts, were still in states kindred to that or the Ancients, and they may have depended greatly on the influx of the ancient spiritual heavens. From principle we conclude that the Christian Church may be said to have descended from the new heaven formed by the Lord at His advent from those of the Ancient Churches. The primitive Christian Church was characterized by great simplicity. Even the apostles could not rid themselves of the belief that they were to sit on twelve thrones to judge the tribes of Israel, and that they were to rise from death with their earthly bodies. The simple worship of the Lord Jesus Christ - the central message of the Apostles - was soon neglected, and the early faith was rent asunder by so many heresies that scarcely any doctrine of faith could appear in its own light (Coro. xxxii, @TCR 378). Faith became spurious, mixed with falsities and, with some, hypocritical. And from the beginning there had been no real knowledge or the Lord except as to person, or as the only begotten Son of God; and no knowledge of what was meant by the Divine trinity; and no knowledge of Redemption, for it was thought that this was effected merely by the Lords passion on the cross.

What happened to the spirits of these early Christians when they entered the spiritual world? The Lord had wrought redemption and ordered the spiritual world, restoring the equilibrium necessary for maintaining men in spiritual freedom. Butt He was not able, then, to form a new heaven of Christians, and from that a new church, because as yet there were no Christians except a little nucleus of disciples. (Coro. xxxi). And when, through the preachings and writings of the apostles, converts were made, heretical ideas were already at work to confuse the true faith. We are therefore shown that the heavens formed from Christians were not permanent; even as we read of Peter, on whose bold confession of the Divinity of Christ the Lords Church was to be built, that when he was old, another would gird him and lead him where he would not wish to go (John 21; 18, cf. Matthew 16:18).

In a word, the heavens which were collected from the Christian world after the Lords advent, successively declined - suffering the same fate as the Christian Church on earth. (@SD 5749). In the beginning only those were selected for heaven who had lived well, confessed the Lord, and obeyed the commandments for His sake; thus such, as had heaven in themselves and thus also had heavenly blessedness given them and corresponding externals in abundance. But compared to the immensity of heaven, and of the uses that needed to be done, such spirits were but few. And thus gradually they began to admit others - and at length all who had lived morally well if they appeared pious and upright in externals. Angels were then sent to them by the Lord to show them that external morality sometimes contained internal wickedness. Those angels were apparently chiefly those from the ancient heavens who were called Michael. But the simple Christians did not listen to their warnings, and the multitude of external spirits increased and gained control. Gradually, the state of that heaven deteriorated. They sought blessedness not in virtue and sincerity, but in the amazing magnificence and beauty which the heavens provide - in palaces and paradises, in dignities and grandeur from multitudes of servants. When this could not be provided from the Lord, they at last procured it for themselves by the strange arts of magic or phantasy which are unknown in this world; and they could do this so long as they were held in an externally moral life. There were continual purifications occurring in such societies, however. Those blatantly evil - the atheist and the adulterer, the thief or manifest evil doer - were not admitted. And if the veneer of morality wore through, and someone was unable to hide his wicked interiors, he was cast out of these societies.

In the meantime, as those one-time heavens were being more and more usurped by external spirits - most of whose leaders were either Roman prelates or Protestants who became champions of the principle of faith alone - the Lord quietly removed all the original inhabitants, the good Christians, and concealed them in various places. where they could neither be seen nor harmed. (@SD 5744-5740, 5758.) Where such places of refuge are, in the spiritual world, is only partly indicated. For simple spirits are frequently confined in the world of spirits in what is called the lower earth, where they are sometimes infested by the evil, yet on the whole lead happy lives while they await a final redemption. Even spirits who, in the beginning of a church, had become accepted as angels, surfer in various ways when that church degenerates. The world of spirits then becomes filled with evil, spirits professing religion, and these cannot; be expelled if the Church has came into falsities and evils which obscure the light of the Word. Such angels themselves then come into a spiritual drowsiness and even fall down into such states as were theirs while on earth - that is, they come into the states of their former natural thought and affection. It seems as if the foundations of heaven are as it were removed. It may be likened to a disease of the body which. affects the life of the mind (@TCR 121, 118, 119, Coro. 19).

It is therefore said that the Lord comes to redeem the angels as well as the men and spirits of the Church. And this can be illustrated by what is said about the apostles of the Lord. For - as we infer from descriptions in the early part of the Spiritual Diary (nos. 1321-1332)--the apostles did indeed become angels and progressed in spiritual understanding. They forsook worldly ideas and came to perceive the Word spiritually. They were only in a lower heaven, however, and there were myriads more worthy than they. Yet they were in an angelic state, until in the course of time their heaven became confused and some of them became subjects to literalistic spirits, and fell back into such ideas as they had held in the life of the body. Then they felt indignation that they could not judge others, as was promised them. They were unwilling to admit into heaven others who had never suffered martyrdom as they had themselves. So they had to be instructed anew, as to the spiritual meaning of those - the poor, the persecuted, and the miserable - whom the Lord spoke of as the salvable.

Generally speaking an angelic spirit who is brought back into his corporeal life and its thought - and this is done occasionally to enable him to allay his former affectionshas then no remembrance that he ever was an angle, and no memory of what had happened in heaven. But when Swedenborg had been introduced into the spiritual world, angels and spirits could as it were compare states by both conversing through Swedenborgs memory; and in the case of these apostles, their memory of their former life in heaven was thus restored, so that the contrast might be seen. (@SD 1391). But besides this, we are told that; while Swedenborg was writing the draft of the True Christian Religion, the twelve apostles of the Lord attended him. This was twenty-two years later, thirteen years after the last judgment; and the purpose was undoubtedly that the apostles should be instructed in the theology of the Heavenly Doctrine before they were sent out to proclaim the Lords second coming.

---

The heavens once occupied by the primitive Christians was - as we see - usurped by evil spirits, and became false heavens, or fictitious heavens. What a tremendous variety of such heavens there can be, is obvious when we consider all the schemes and systems that men have advocated to achieve happiness - and all in the name of the Christian religion. First we note simple Jewish or pagan converts, spell bound over the miracles of the apostles, and persuaded that the end of the world was at hand. Then - the later Christians, courting the martyrs crown, poverty, and abstinences. After thatidolatrous-minded worshipers of relics and saints, who relinquished all spiritual power to a priestly hierarchy. And finallycrowds of literalists who made salvation a pure gift of God to a select few, and blind faith the only mean. Each group - and all were prisoners of hope - established a heaven of their own, thinking it alone the effective method to earn eternal bliss; and each fell under the tyranny of leaders that demanded obedience and perhaps worship, in subtle or brutal ways.

Because of these fictitious heavens, the simple good were by degrees removed elsewhere - partly at least in the lower earths where they dwelt in a state of arrested development. But it seems indicated that those who had, from an affection of truth and good, attained a more interior heaven, were less disturbed by the degeneration of the first heavens or Christians, and maintained societies where they perceived the Word in its spiritual sense and lived according to its Divine. Doctrine (Cf. Lord 65). In this they were sustained by the influx of the ancient heavens; for it must be recalled that the internals of the Ancient Church are the same as these of the Christian (@AC 4489, 3478, 47?2, 1083). But weight should also be placed on the statement in the work on the Last Judgment, that while a heaven had been collected since the time of the Lord from all the human race, those who were there were not angles, but spirits of various religions (@LJ 2). This refers to Christians and gentiles alike, and indicates that the inhabitants of these heavens had (none of them) undergone their final preparation for heaven, but that this had been arrested, awaiting the second advent of the Lord.

---

At the time of the Lord, evil spirits had so far upset the equilibrium of the spiritual world that the hells filled the whole of the world of spirits ... and thus not only confused the heaven which is called the ultimate or lowest, but also assaulted the middle heaven which they infested in a thousand ways and which would have gone to destruction unless the Lord had protected it (@TCR 121). A similar situation came about at the end or the Christian Church, although there is no teaching to suggest that the ancient spiritual heavens, established at the first advent of the Lord, were infested.

Swedenborg observed that as the last judgment approached, the center of the world or spirits was occupied by spirits from the Reformed Christian world, arranged according to their nations, those in the center having greater clarity in the things of the Word. For that reason, the districts of the papal religion and of the Moslems and pagans, were further away from this canter. Those occupying the surface of the world of spirits were generally evil. But underneath the surface were abodes for spirits of internal character, and the best of these were centralized on a hill where certain societies came to be known afterwards as New Jerusalemite cities. In the lower earth, good spirits and evil ones were dwelling as in strata or layers - which was explained to be done so that the good might exert a restraining influence on the wicked.

Around the center of the world of sprits there were many entrances to the hells, which also surrounded the lower earth. Below the lower earth were the hells - in threefold degrees of depravity and horror. And in the canter was a passage leading to the pit of the profane which is below the deepest hell, because the profane are not tolerated even by the devils.

It may seam strange that Swedenborg could, as it were, give the geography of these various spiritual districts, since their appearance is only representative or the mutual relations of the states of the spirits. Yet to spirits, the locations were more real than actual spaces are to us. Men, too, live on varying levels both as to social and mental life, and are keenly aware of it.

The same appearance held above the world of spirits. For around the central plain there rose mountains of varying heights, on which were the false heavens, where ambitious external men had established and ruled those below. And above these, again, there was an expanse which to others was invisible, and there, strange to say, lived the pietists who were in the fantasy of a spiritual superiority.

It is of some moment that we visualize this situation, for it was owing to the superior position of the evil spirits who were thus above the world of spirits, that they could stave off the judgment for so longyea, for many, many centuries. Much of their power depended on the fact that they were able to retain the support or the simple good. For the interiors of the good spirits from the Christian Church had been closed, to prevent them being injured by the evil (@AE 699). And it is also stated that the reason why the evil were so long tolerated upon high places, and the good so long detained below heaven, was ... that there might be a sufficient number of the good to form a new heaven, and also, that the evil might sink down of themselves into hell; for the Lord casts no one down into hell... (@AE 397).

Any heavenly society requires numbers for the performance of its uses. Where good spirits are lacking, evil spirits have an opportunity to infiltrate and take over. Before the good Christians could muster sufficient souls to replace the evil, it would be hazardous to attempt it. Those who were interiorly wicked could of course not perform spiritual uses of an interior type. But they could teach and maintain civil and moral good, and thus judge the more blatant evils. At the same time they would obscure and dim out all perception of spiritual truth - and would evade the acknowledgment of the Lords Divinity and the need for a life of charity or love.

The judgment by which the evil spirits would be cast down from their position or privilege and power and be reduced to the level of other spirits, came only in the Lords good time; but when it came it came quickly. And note that it was occasioned by events in the natural world. For the Lord effects all things from inmosts through ultimates. Indeed, all power of Divine truth lodges in the sense of the letter of the Word. The word that I have spoken, the same shall judge him in the last day, said the Lord.

But the truth does not judge until it becomes apparent. In the Christian church the literal sense of the Word had been twisted out of its real meaning, and was no longer understood. This was the reason why the Christian heavens could not be purged. The Lord - when the field was ripe for the harvest of judgment - prepared and raised up His Servant Emanuel Swedenborg and by particular enlightenment and thus revelation, as well as by introduction into open intercourse with the angels, instructed him in the doctrine of genuine truth from the literal sense of Scripture; and by this doctrine opened its spiritual sense.

It is notable that this opening of the internal sense to disclose the doctrine of the Lord and the doctrine of charity, was the purpose of the writing of the Arcana Coelestia, which occupied Swedenborg from 1748 to 1756. He reveals therein that while a man reads the literal sense of the Word, the angels in heaven perceive the spiritual and celestial senses of it. He also notes certain premonitions of a coming general judgment in the spiritual world; but while the Arcana shows how the false heavens of the ancient Church had been judged at the time of the Lord, and indicates that a similar thing - and the raising up of a new church - must soon occur again to bring back order into the spirit-world, he notes these things without any fore-knowledge of the future. It is also of interest that while the Arcana outlines the main doctrines, in brief treatment between the chapters, they are headed The Doctrine of Charity, and not either the Heavenly Doctrine or The Doctrine of the New Church. Thus they are presented simply as the doctrines implied in the internal sense of the Word, and as the genuine Christian doctrine which the angels perceived as taught in the Word.

The question naturally arises, What angels? For the later teaching shows that the first heaven of the Christian era was not composed of angels but of spirits from various religions (@LJ 2). Or we may put the question another way: Was the doctrine taught in the Writings already existent in heaven, since it was indeed given before in the Word? (Lord 65). And, if so, in what heaven? And what is meant by the statements that only after the last judgment had been performed, and not before, were revelations made for the New Church, because the congregations of evil spirits in the false heavens intercepted much of the communication between the Lord and the Church? (CJ 12, 11, @AR 804, @DP 264[4]) For certainly the Arcana was revealed before the last judgment in 1757.

Several other uncertainties suggest themselves. The New Jerusalem, which was to descend after the last judgment was first shown to John as to all its details in the third heaven, where are these who are in love to the Lord and in the genuine doctrine of truth from Him. Was it thence that the Heavenly Doctrine descended? Was it true of the Writings, as of other forms of the Word, that in its descent from God it was written and so made the Word in each heaven, before it was written down in a natural form on. earth?

These querieswhich may be more than we can answer - must be viewed from the general question, when and how was the New Heaven formed? Did the formation of that heaven commence before the last judgment, or was it wholly the result or the judgment?

I believe the answer to the question is given in the general sequence of the internal sense of the Apocalypse, which is expounded in the Apocalypse Revealed. (To this we hope to give some consideration in our next class.)

== Class II - THE NEW CHRISTIAN HEAVEN

Reading: Matthew 13:36-43

The general teaching or the New Church is that the heaven formed from Christians after the Lords time deteriorated owing to the introduction of external spirits, and that eventually those who had been interiorly good were no longer tolerated but were persecuted so that, they withdrew, leaving these placeson mountains, rocks, and hills above the world of spiritsoccupied mainly by the evil, who were in moral good devoid of any spiritual internal.

The spirits of these false heavens, by their holy externals, by their outward sincerity and apparent justice, were able to be conjoined with the simple good in the ultimate heaven and in the world of spirits. And heaven would have suffered in its ultimates if a judgment had separated them before the time was ripe (@LJ 66-70).

The Christian Church was - by virtue of its knowledge of the Word and the Lord - in a central place in the spiritual world. Normally, the heavens of Christendom should be the vanguard of spiritual progress and the source of light and instruction for the spirits from other religions. But since these heavens had become externalized and corrupted, the spiritual development of the human race as a whole in the after life was arrested, it is therefore stated that a heaven was formed from all the human race who had lived since the commencement of the Christian church; but they who were there were not angels, but spirits of various religions (@LJ 2). This first heaven or prior, former heaven, existed not merely from Christians but also from Mohammedans and Gentiles who had all formed for themselves such heavens in their own places, and lived in delights similar to natural delights, devoid of anything angelic (@LJ 69, 66).

But how can this teaching be reconciled with other statements to the effect that these factitious or artificial heavens were preserved for so many centuries because they were conjoined with simple spirits of the ultimate heaven? (@LJ 70). What heaven was that? A closer scrutiny of the doctrines seem to give the answer. For after describing the false heavens, one passage makes this remarkable addition: But it is to he known that all who were interiorly good, thus who were spiritual, were separated from them and elevated into heaven, and that all who were exteriorly as well as interiorly evil, were also separated from them and cast into hell; and thus from the time immediately following the Lords advent, down to the last time, when the judgment was; and that those only were left to form societies among themselves, who constituted the first heaven... (@LJ 60). By this first heaven is not meant the heaven formed of those who have become angels from the first creation of this world up to the present time; for that heaven, the doctrine assures us, is abiding, and endures to eternity; for all who enter heaven are under the Lords protection, and he who has once been received by the Lord can never be plucked away from Him (@LJ 66). In other words, those who are interiorly good ... are by turns sent, before the judgment, to places of instruction, and are taken up thence into Heaven (@LJ 59[6], cf. @AE 413).

A new picture of the post-advent heavens thus emerges. All those men who had the faith of charity and whose spiritual minds had been opened by regeneration, were after death admitted into heaven, and if they had been in the heaven which deteriorated into a false heaven they were withdrawn thence; for upon such the evil with their seductive externals would have no power. Such regenerate men would thus form interior heavens - albeit within the expense below the ancient heavens. This lowest expense was threefold - for, like each of the ancient expenses, it contains a celestial degree, a spiritual degree, and a natural degree. The higher degrees, or the higher heavens, are for the regenerate, whose spiritual minds have been opened. But the lowest or natural heaven is for the simple, or those who are only reformed by obedience to the doctrine of their church.

It is the natural, or those who are in the ultimate heaven, that can be deceived into a close association or conjunction with the spirits of the false heavens. They are usually not called angels, but good spirits; although after the judgment they become natural angels. Before the judgment, they are in states or varying degrees of confusion and obscurity, and it is mainly their trust and support which makes it possible for the spirits of the false heavens to maintain themselves in power (@LJ 56).

The higher heavens collected from Christians from the time of the Lord on were from those only who had acknowledged the Lord alone as the God of heaven and earth and had shunned evils as sins against Him. These heavens are below the ancient heavens and receive influx from them (@AR 612). Even as the heavens of the ancient church before the Lords first advent formed an external or an adjunct to the celestial heavens of the most ancient church, so these Christian heavens were not organized before the Lords second advent, but must have formed an adjunct to the ancient heavens. And it is to be understood that the ancient heavens all acknowledge the Lord alone as the God of heaven and earth.

We know of no conclusive teachings as to the exact spiritual position of the societies of these superior Christian heavens except that they were secreted from the evil and that their influx into the false heavens was restrained. Sometimes they seam to be included among those good spirits who were concealed from the hells in places like the lower earths, where they would occupy a central situation and be in states of spiritual peace and happiness, quite unconscious of the hells; while the natural, or the simple good, are often mentioned as suffering infestation from the evil spirits of the false heavens and even from surrounding hells.

Yet in the Apocalypse, the internal sense of which treats of the state just before the judgment and after it, these higher heavens or Christians are more clearly depicted. They now come out of the states of concealment and protection and assume an active role, and appear as a nucleus for the New Heaven to be organized alter the judgment.

Here it is well to observe the order in which preparations for a last judgment are made. First of all, the Lord makes His advent, in Divine truth. Secondly, He prepares for judgment by an ordination of the heavens, and by a general disclosure of the states of the Church in the spiritual world, both states of possible reception of the future New Church and states as to the understanding of the Word. After this exploration, which causes certain preliminary judgments, the establishment of the internal of the New Heaven commences, and the birth and crystallization of the Heavenly commences, and the birth and crystallization of the Heavenly Doctrines occurs in heaven, while yet the world of spirits and the church on earth are utterly unable to receive it.

All this is told in the Apocalypse Revealed, in explanation of the early part of the Apocalypse: the revelation of the Lord as the Son of Man amidst the seven golden candle-sticks, the letters to the seven churches, the sight of the heavenly throne about which are ordered the four beasts and the twenty-four elders (significant of the higher heavens), the Lamb opening the seven-sealed book, and many other wonders. And then is described the heavenly Woman crowned with twelve stare, who gave birth to a male child wholest the dragon devour him - was snatched up to heaven for a time.

Whence came this Heavenly Doctrine into existence in the New Heaven, before it could be received in the world of spirits or on earth?

As we know, the angels have their wisdom from the Word, and indeed read the Word and draw doctrine from it. It is when the men of the Church read the Word in the sense of its letter, that the angels perceive its spiritual sense. But when the meaning of the Word is perverted by falsities of evil in the church, the angels associated with them fall into something of obscurity, for the Word can then no longer serve to check and purify their perceptions and ideas.

The Lord must then Himself come and reveal its truth, or restore its meaning and use. And this was done when Swedenborg was prepared and inspired to see the internal sense and its doctrine of genuine truth. The Lord acts from primes through ultimates to order intermediates (@AE 1086[5]). For this reason He came at His first advent; by assuming an ultimate Human by birth in the world. For the same reason His second advent was a coming in the ultimates of the Word - in the sense of the letter - where He is present in fullness and holiness. Yet His continual presence there is by means of the spiritual sense (@TCR 780), and by means of the doctrine of genuine truth.

Now it is clear from the sequence of events that the disclosure of the spiritual sense of the Word, in the Arcana Coelestia preceded the last judgment. This seems utterly opposed to the general law laid down in the later Writings that not until after the last judgment was the spiritual sense of the Word revealed (@AR 804), because the congregations of the false heavens from the Protestant and the Babylonish religiosities were like a dark cloud which was interposed under heaven and cut off all spiritual light, so that the man of the church could not be enlightened. If anything had been revealed by the Lord (before), either it would not have been understood or, if understood, still it would not have been received, or, if received, yet it would afterwards have been suffocated. (CJ 11)

That revelations for the New Church were made only after the last judgment and not before, is reiterated again and again (CJ 12, @AR 804, @AE 955-957, 774, 1094, 1217, BE 94, @TCR 182, Coro. 12, @DP 264). In a most general sense, it might of course be said that the judgment commenced by preliminary separations of evil spirits throughout the Arcana period. But this seems to me to be a specious and evasive explanation. What is meant by the teaching is rather that before the judgment there could be no real or interior reception of the truth among spirits and men. On the other hand, nothing that men or spirits can do can prevent the Lord from revealing truth by direct inspiration. The Lord became incarnate at a time when mankind was entirely estranged from heaven: He - as the Word - assumed flesh, put on the ultimates of nature, by-passing the false heavens or that time. And similarly at the end of the Christian Church He - as the Holy Spirit of Divine truth - descended and dictated the internal sense of the Word into the thought of Emanuel Swedenborg; thus creating, in the Arcana Coelestia, a new pathway whereby the Word in its literal sense could be made to yield its spiritual doctrine.

Yet the Arcana Coelestia was not directly addressed to the New Church, and we have no evidence that any man except Swedenborg received or understood its teachings.((*)) The effects of its publication in the spiritual world, is another matter. Swedenborg was intermitted into heaven in order to perceive the spiritual sense in its own light, and the interiors of his mind were thus raised above the realm of the false heavens. We may therefore be permitted to surmise that the angels of the higher Christian heavens came, through him, into a contact with the Word apart from the falsities of the Christian churches. The angels are in wisdom from the Word, but pay no attention whatsoever to those things which are in the sense of the letter, nor to those things which are in the thought of a man at the time when he reads it, but to the interiors of the Word from man.... The natural thought of man is a plane in which all things of angelic wisdom close: it is a foundation like that of a house.... And as are the ultimates, so are the primaries.... Indeed, angels told Swedenborg that the wisdom of their thought falls into mens minds as into a plane, and are therefore in lucidity or obscurity according to what this plane furnishes; and when they turned to those things which were in Swedenborgs thought from the heavenly doctrine they were in greater clearness than in any other case (@SD 5807-5610).

((*)) That it was read by some, as for instance by Stephen Penny, is conceded.

Now it was apparently while Swedenborg was writing the Arcana that the internal heavens of Christians, that is, the higher heavens, were being formed, as a nucleus of the New Heaven. For we read, The internal heaven of Christians was not fully formed by the Lord till a little before the last judgment and also after it.... For it was hazardous to collect them sooner into a heaven (@AR 878).

It is also taught that before the judgment on the false heavens could commence, the heavens had to be ordinated or arranged. This is described by the four beasts and the twenty-four elders being gathered about the throne of God, while the Lamb opens the book sealed with seven seals that no man in heaven or earth or under the earth could open (@AR 299).

There is a church in heaven as well as on earth. In heaven there is the Word, and there is doctrine from the Word.... This doctrine is the same as the spiritual sense of the Word, and is called the Heavenly Doctrine; and this was revealed to Swedenborg out of heaven (@HD 7). It is also signified in the Apocalypse by the male child to which the heavenly star-crowned woman - clothed with the sun - gave birth. For this woman signifies the New Heaven - that is, the Lords New Church in the heavens before the judgment. The New Heaven was then an internal without an external, for the external heaven of Christians was as yet conjoined with the false heavens; and the New Church on earth was as yet to come. Therefore the new-born man-child, or the Heavenly Doctrine, was caught up unto God and His throne; that is, it could be received only in the internal of heaven. And the woman herself was miraculously protected. The nucleus or first beginning of the New Church in heaven and later on earth had to remain in seclusion among a relatively few as long as the dragon of faith alone prevailed.

In the Arcana Coelestia we observe the gestation of the Heavenly Doctrine - its formation out of the truths of the spiritual sense or the Word. In the last few volumes of the Arcana we see its complete outlines. But it is not called - as yet - the Heavenly Doctrine. It is headed, The Doctrine of Charity; for this is the burden of the internals sense. When the Arcana was completedthe last volume being published in 1756 - the storms of judgment were let loose in the spiritual world. In the fall of 1756 Swedenborg began to collect doctrinal extracts from the Arcana Coelestia with the view or publishing some smaller works - among them Heaven and Hell, The White Horse, and The New Jerusalem and its Heavenly Doctrine. And towards the end of the year, Swedenborg tells, he was, in vision, present in a spiritual city called Rome, visiting a senator who, with some others, had been seeking to form a doctrine of life, and he spoke with him about the doctrine of the Lord. The senator acceptance of what Swedenborg told him inflamed the papist leaders to direct the terrors of the Inquisition both upon the Senator and upon Swedenborg. Both wars protected; but the event marked the beginning of the universal judgment an the Babylonish tract - those false heavens which were occupied; by the Catholics and were dominated by the Roman hierarchy. The entirely world of spirits was soon engulfed in the judgment - the Mohammedan regions, the gentile tracts, and finally the region or the Reformed.

The immediate occasion of the judgment. was an increased influx of the Lord through the New Heaven - an influx of the Divine sphere which was intended to protect the good. The higher heavens thus drew near to the false heavens in the world of spirits, in an endeavor to prevent harm to the simple-minded who were there (@AR 340, 342, 343, 761). By this influx of Divine truth the good are separated from the evil: for it brings an opening of the interiors of the wicked spirits, and thus these case into open evil and blatant falsity, in a last endeavor to maintain their power. Angels also made visitations among the societies of these usurpers, and explored their states, until the evil spirits could no longer stand the light or truth.

It is not our purpose to seek to describe these judgments as they presented themselves in the other world - as successive earthquakes and inundations, destroying cities and engulfing whole mountain chains - which was quickly done, since these things were built up by phantasies and had no 'reality when once exposed to the searching, light of truth. The last judgment continued throughout the year 1757, but was mainly accomplished by the middle by April. By that time the mountains or the false heavens had been leveled or replaced. The evil spirits had been cast into hells or at least been reduced to undergo the ordinary processes of vastation in the world of spirits.

And now began the release of myriads of spirits from the lower earths. Seemingly unending streams or themboth Christians and gentiles - crossed the world of spirits in varying ways, being instructed in several places as they went. Some of this instruction seemed to have been gained through spirits in the world of spirits who were in faith alone, but who, before their full vastation, as it were lent their religions knowledge to the simple good spirits who were emerging from a state of ignorance. This was in fulfillment of the law. To him that hath shall be given, and from him that hath not shall be taken away even that which he seemeth to have.

But it is clear that those raised up from the lower earth were destined for places of instruction where angels or angelic spirits communicated to them a knowledge of the Heavenly Doctrine. This doctrine - which had been treated of in the Arcana Coeleatia - was apparently present in the world of spirits. For on the very eve of the impending judgment, certain spirits who were ambitious to use religion as a means to power over the common people, not caring what the religion was, sought to pervert and subtly change the Heavenly Doctrine to suit their purposes. They were soon detected and punished by loss of all their intellectual power, so that they were reduced to stupidity (@SD 4838, 4988).

Yet it was not until after the judgment had been fully accomplished, and the New Heaven was increasing and the world of spirits was reduced to its normal state, that the Heavenly Doctrine could descend from God out of the New Heaven as the holy city New Jerusalem, and be received by spirits and men. Swedenborg could and did write the Arcana before the judgment, and through it the Word was restored, the angels of the higher Christian heavens were prepared for their part in the judgment, and the way was laid open for the birth of the Heavenly Doctrine - that is for the rational formulation of the contents of the spiritual sense in the form of a doctrine for the New Church which was now about to commence in the world of spirits and on earth.

During the year 1757, Swedenborg not only witnessed the judgment and made various records or its momentous incidents, but he also began to prepare several works for publication. The next year five of his books issued from the press - among them one entitled The New Jerusalem and its Heavenly Doctrine - from what has bean heard from Heaven. This work is the first which is stated to be for the New Church (@HD 7). It announces that the Christian Church has been consummated and judged and that a New Church is being established by the Lord (@HD 5). Most of the Writings which followed were also similarly titled and proclaimed as doctrine for the New Church. And the True Christian Religion is subtitled, The Universal Theology of the New Heaven and the New Church.


== Class III - WHO CONSTITUTES THE NEW HEAVEN

Reading: Revelation 21:22-27; 22:1-5

Since it is from or through the New Heaven that the Lord successively initiates and insaturates the New Church on earth or derives and produces the New Church, which thus comes down from and is formed through that heaven, it is of importance to know as exactly as possible who constitute this New Heaven (@AR 879, Coro. iii, 18). That it is distinct from the ancient heavens, or the two superior expanses, has already been mentioned. That it constitutes a third or lowest expanse, which contains three degrees or heavens, is also clear (@HD 4, @AR 612, 876, Coro. 16, 17). We have also learned that the external or natural degree of this lowest expanse was gradually occupied predominantly by evil spirits living moral or pious lives, and that these could not be dislodged until the last judgment. Further it was indicated that those spirits who were regenerate or spiritual or interiorly good were in the meantime reserved or secreted by the Lord, in various places in the spiritual world; that some of them formed higher heavens while others were consigned to the lower earths; but that the internal of the heaven from Christians was not fully formed until some time before the last judgment and also after it. And the external of that New Heaven was organized as a result of the judgment, from spirits who were then raised up from the lower earths.

It is to be noted that not only Christians, as their church decayed, but also all gentile religions, formed false heavens which were dissolved by the judgment (@LJ 69). And similarly, in a broad sense, the New Heavens formed before and after the judgment, was composed of both Christians and gentiles; but as to the greatest part of the infants of all in the universal world who had died (in infancy) since the time of the Lord; for all infants had been instructed by angels and reserved to swell the numbers of the New Heaven.(*) This heaven was formed of all those who, from the time of the first advent up to this time had lived the life of faith and charity; which makes its quality altogether unanimous (@HD 2, 3).

(*) A third of heaven is said to consist of infants (@HH 4); and these amount to a fourth or fifth part of the human race on earth (@HH 416).

In general, the New Heaven is distinct from the superior expenses, because it is characterized by the good of faith, or a life according to the doctrine of ones church. (@HD 4). This does not mean that there are not spiritual and celestial angels in the New Heaven, but that the good of faith is the starting point for the regeneration of a man of this epoch (Coro. 16). The ancient heavens are above the New Heaven because the Ancient and Most Ancient Churches had spiritual and celestial love as their characteristics.

The New Heaven is said to be constituted from gentiles as well as from Christians. We must not infer that all the children who are born outside of the Christian church and who die in childhood, are commingled with Christian infants who by baptism were associated with Christian heavens. After death, gentile children are introduced by other means into the heaven designated for their religion, after the reception or faith in the Lord (@TCR 729). For all in heaven, from whatever religion, acknowledge the Lord. It is also stated that while the heavens of the Mohammedans, the gentiles, and the Christians, receive a common influx from the Lord, they do not communicate with each other. This is especially noted in reference to the lower Mohammedan heavens where even polygamy is tolerated, because it is from their religion (@CL 348, 352). How permanent such heavens can be, is not indicated. Certainly it cannot be imagined that they are proper parts of the New Heaven whence the New Church is to descend! We are even told of monks and. nuns who have lived in celibacy from religious motives and are assigned places at the sides of heaven, lest their sphere infest the angels (@CL 54).

The heavens which are thus separated consist of those whose conscience has been formed from the doctrine of the church or religiosity, rather than from a real understanding of the truth or from the Word. It must be permitted that separate societies be formed from souls out of every religious affiliation, so far as their conscience is bound to its peculiar concepts. And thus it is only those who are in a real love of truth for the salts of life that can be lifted into the light of the truth itself, and thus brought out of the various false religiosities and pager faiths, into the sphere of the Word and its internal sense end so be affected by the Heavenly Doctrine.

The New Heaven - in the broadest sense of that term - consists of all who are saved since the time of the Lord. But it is clear from the Writings that the heart and the lungs of this grand man is the Christian Heaven - where the Word is an the Lord is known. It is therefore shown that it is specifically from the New Christian Heaven that the New Jerusalem descends (@AR 612, 876). This is composed of good Christians, not only of the internal who were received before the last judgment, but also of the more external, such as those who were later collected from the lower earths; and besides this, of all the infants of Christians who were educated by the angels in the two essentials of the Church (Ibid., @SD 5762, 5763).

The teaching is that it is by means of the Word that those have light who are out of the Church and have not the Word (SS chap. xiii). Although the church consists of comparatively few, yet by the Word the Lord is present in the whole world and by it heaven is conjoined with the human race. Thus the Christian heaven is the center from which there is a communication or propagation of enlightenment to all nations and peoples in the spiritual world, and this is felt by the spirits as light or as the perception of truth. It spreads from the region of the Reformed Christians to the papists, and further to the Moslems, the Africans, and the peoples of Asia and the Indies.

This was the providential reason why the North European nations especially were permitted to establish universal commerce throughout the world whereby the knowledge of the Word was spread to distant races (@DSS 108). But the real communication takes place in the spiritual world. And the source of it is in the New Christian Heaven. Many gentile spirits show an aversion to the teachings of missionaries from the old Christian churchesperceiving not only the falsity of their doctrines but also their evils of life. But as the New Heaven was being formed, those gentiles who were not confirmed in false doctrines and in conceit of self-intelligence, were told by angels that a revelation was beginning to take place from heaven (@SD 4770). Angels indeed began to teach their chiefs from the heavenly doctrines, especially concerning the Lord (@SD 4771, 4772, 4774). They were promised unblemished doctrine of the Church out of heaven, and also that they would receive a Bible, but a new Bible, from the Lord (@SD 4775). Presumably this meant the old Bible, but, as this is written in the heavens, where the literal sense is not seen. Swedenborg was then shown in an obscure vision, how the Heavenly Doctrine would advance among these spirits from Africa and Asia, and from those nations even to other spirits and then to spirits of other earths (@SD 4777, 4780).

Hence the angels rejoiced that the Coming of the Lord was now at hand, and that the Church which is now perishing in Europe, should be renewed in Africa; and that this is done by the Lord alone, by means of revelations, and not by missionaries from the Christians (@SD 4777, LJ post. 116).

Swedenborg later visited some of the wiser Africans and perceived that they knew the truths of the Church in themselves. They ran through the things Swedenborg knew and stated that they knew all these things, and more, and could discuss them; but had no knowledge of correspondences. He found that they are taught by instructors who received communication from heaven, yet not through angels speaking, but through interior perception (@SD 5946, J. post. 124)

These spirits received the Word, and read it, with an increasing sense of its holiness, understanding it as to the internal spiritual sense. Their instructors admitted that they had it and that they dictated it into the interior perception or Africans in the world, who thus receive a revelation with enlightenment (LJ post. 124, @SD 5946). Swedenborg gave them five of his works, published in 1758, including the New Jerusalem and its Heavenly Doctrine, which they accepted so as to take thence what they might find useful (@SD 5946). And Swedenborg was told from heaven that the truths published in those works were being orally dictated by angelic spirits to the inhabitants of that country (@LJCont 76).

In speaking of the New Church to which Swedenborg writes the things that are being published by me at the present day will be of service, he adds: It is also being instituted elsewhere (Hist. Parts of Word, Preface). But at the end of the work on the Last Judgment he writes:
The angels ... have slender hope of the men of the Christian Church, but much of some nation far distant from the Christian world ... which nation is such that it is capable of receiving spiritual light and of being made a celestial-spiritual man; and they said that at this day interior Divine truths are revealed in that nation ... and are received in spiritual faith... (@LJ 74).

Although there is a strong appearance that a revelation somewhere in the natural world is hinted at; and despite the fact that many New Church people have taken this as a fact, so that the first public meeting of New Church men in the worldin Norrkoping, Sweden, in 1779actually planed an expedition to Timbuktu to verify it; we believe that the revelation referred to was an enlightenment from the Christian Heaven to the heaven of the Africans and from their instructions to Africans in the world of spirits below that heaven. For in the Spiritual Diary Swedenborg occasionally refers to the world of spirits as the world, in contrast to heaven. The world of spirits, he explains, is not perceived by those there as an extend plane but as a globe, where the various nationalities and races occupy their own segmentsin accordance with the relationship of natural affections. Its spiritual geography is reminiscent of earth; and Swedenborg actually drew a map of the spiritual Africa, a map which only vaguely resembles the continent with which we are familiar.

If we study the statements about the revelations to the Africans, we may notice that while mention is made of an oral instruction and dictation, it is also said that the communication was not through speech by the angels but through interior perception and was perceived as an influx or as an influx or as enlightenment (@SD 5946, LJ post. 124).

If there had been an actual dictation of doctrinal truth by spirits or angels to men still living on earth, we would have to regard this as an exception to the general laws of influx and revelation. Because of mans evil heredity, it has been provided by the Lord that nothing of truth flows in through mans internal, but only through his external (@AC 2557). Thought is not introduced with man through spirits, but only affection... (@HH 298). Spiritual things inflow by means of instruction (@AC 1832). Man is not led and taught immediately by any dictate, or by an influx into his spiritual delight, from which he has perception according to the truths of which his understanding consists (@AE 825[3]). In order that spiritual perception may come forth, there must be spiritual cognitions with man in his natural (@AC 9103[3]). For this reason there is no natural theology. Without the Word no one would have spiritual intelligence or any religious ideas. These have all been derived from previous revelations. Even the wise pagans, such as Aristotle and Seneca, had their ideas of immorality and of God from traditions stemming from the ancient church. (SS chap. xiv) Religion cannot exist except by some revelation and by its propagation from nation to nation (Coro. 39). Moreover, no leave is granted to any spirit or even angel, to instruct any man on this earth in Divine truths.... And spiritsif they are permitted to speak to mancannot inflow from their own memory and derivative thoughts, but must speak to man in his own ideas, and can thus only confirm all the things which he has made a part of his religion. (De Verbo xiii, cf. @HH 298) Swedenborg explains that he was allowed to take nothing from spirits or angels, but from the mouth of the Lord alone, while reading the Word (Ibid., @DP 135, @TCR 779). The nature of the revelation to the Israelites was determined by the religious knowledge that they already had from other sources. Always, influx is according to the receptive forms. What, then, would be the nature of a revelation dictated to natives of central Africanatives isolated from both Christian and ancient-church sources, and possessed only of very primitive and gross ideas?

Whatever may have been the case in the most ancient church, at this day revelation is given on our earth only through the Word, and not by immediate intercourse, as on other earths. (@AC 10355, 10384) But oral revelation of truth Divine such as takes place on other earths is given only within families and is either perverted or perishes unless new revelations are constantly provided (@AC 9358). They are not directed for the establishment of a permanent church, but take the form of warnings and signs, and often of open intercourse with spirits. This is not the type of revelation that seems to be described as taking place among the Africans.

About the Africans themselves it is said that they are more receptive of the Heavenly Doctrine than any others from this earth. The doctrine was spoken or by the angels as a new advent of the Lord to establish a New Church, among these people whom the Lord Himself teaches through the angels (@SD 4783). From the joy of the angels of the Christian heaven it was manifest that there was a communication of the whole of heaven from the Christian heaven where the Word is; and thus that it is the Word from which wisdom and interior joy come. The communication is like that of light, and like the communication or all the viscera in the human body from the heart and the lungs (@SD 5947). In the True Christian Religion it is added that Augustine, once bishop of Hippo in North Africa, was present with them (presumably as an angel instructor)
and was hoping for the propagation of the new gospel into neighboring regions (@TCR 840).

---

From the scattered statements on this subject it would appear that the heavenly teaching is propagated from the New Christian Heaven in many ways, and not only in the form of the Writings of Swedenborg. The evidence indicates that the teachings were received by gentiles in partial fashion, yet that some - like the Africans - seemed to know the truths contained in the Writings, but were cautious about accepting the published works when Swedenborg offered them. We conclude from this that the heavenly doctrine which they had been taught was derived from the internal sense seen in the New Heaven, and presented so far as it was applicable to their state. And it may be pertinent to note that when the Word of our earth is read and preached, the contents of the internal sense - so far as it can be receivedis presented to angels in heaven from whatever earth they come (@AC 9357). For in heaven there is communication between all (@AC 9356).

But on earth the Heavenly Doctrine can spread only in one way: namely, by the reading of the Writings. Only through the Writings can the internal sense or the Word come to light or be disclosed. That the Writings of Swedenborg actually were the Heavenly Doctrine or the doctrine which was as it were born in the New Heaven, is shown in the Apocalypse Revealed, no. 543. The woman clothed with the sun, seen by John, signified the Lords New Church in the heavens, thus the New Heaven. The male child which she brought forth, signified the doctrine of the New Church. And it is said: The doctrine here meant is The Doctrine of the New Jerusalem, published in London, 1758; as also The Doctrine Concerning the Lord, concerning The Sacred Scripture, and concerning Life according to the Commandments of the Decalogue, published in Amsterdam; for by doctrine all the truths of doctrine are meant, because doctrine is the complex of them. When these doctrines were written, the dragonists stood around me, and endeavored with all their fury to devour, that is, to extinguish them... (@AR 543).

It is obvious that the Writings were written, if not actually in the spiritual world, yet in full view of spirits and angels. The books of the Writings existed in both worlds. They were cited by Swedenborg before the angels, and were presented to various spirits. And even as the heavenly doctrine orally taught by the angels of the New Heaven, was called a new advent or the Lord, so Swedenborg, when the Brief Exposition had been published, witnessed a marvelous glorification of the angelic sky: and there appeared, on all the copies in the spiritual world this inscriptionThe Advent of the Lord. And he was commanded to write the same on two copies of the book in Holland.

The Writings evidently then were that holy city, New Jerusalem, which in Johns vision had been foretold as descending from God out of heaven. They were the rational formulation and ultimation of the spiritual sense in the form of doctrine for the New Church.

Yet this was not accomplished until after the judgment. In the Arcana the Word had been unfolded preparatory for the judgment. The heavenly doctrine thug was seen in the Scriptures. It was born, like the man-child, in heaven, but could not be received. It was after the judgment that the same heavenly doctrine was organized and descended as a city of truth - ultimated in the doctrinal texts published by Swedenborg

---

The formation or the New Heaven went on throughout the rest of Swedenborgs life. Ancient Christendom had been judged. The world of spirits had been reduced into order, and into an equilibrium which guaranteed spiritual liberty to spirits and men. But in 1766
Swedenborg. writes that the New Heaven was not yet fully established (Docu. 230). In 1770 he shows that the New Church on earth will come down from the New Heaven and this only as this New Heaven increases; which is not done in a moment but is done so far as the falses of the old church are removed. And falses will first be eradicated among the clergy and thus among the laity (@TCR 784). That the time was still far off seemed indicated by the fact that, thirteen years after the last judgment, the spheres which poured forth from modern Christendomfrom spirits newly come from the earth (where, it was said, the dragon had been cast down)were invading the minds of spirits and men so that the angels complained. For these spheres of thought and cupidity confused faith or destroyed it, and opposed the conjunction of faith and charity. And Swedenborg adds, The spheres of spiritual truths there are as yet few, being only in the new heaven and with those under heaven who are separated from the spirits of the dragon; which is the reason why those truths are invisible to men in the world... (@TCR 619).

How soon, then, could a New Church be expected? To this question, asked by Dr. Beyer in 1767, Swedenborg answers by testifying that he saw daily tens of thousands of spirits and angels being set in order for the formation and increase or the new heaven. As that heaven is being formed, the New Church likewise begins and grows. But the new heaven has no power over the old clergy who are confirmed. in faith alone; and the universities of Christendom are now first being instructed, whence will come new ministers (Docu. 234).

A few months before the True Christian Religion came off the press, Swedenborg writes Beyer: I am certain of this, that after the appearance of this book the Lord our Savior will operate both mediately and immediately towards the establishment throughout the whole of Christendom of a New Church based upon this Theology. The New Heaven, out of which the New Jerusalem will descend, will very soon be completed... (Docu. 245BB).

From these statements it becomes clear that the New Church could in no wise arise by any secret influx of the new heaven into mens minds, but by the direct agency or the Writings. For only by the truths revealed in the Writings taken as a whole could falsities be judged. And only after falses were removed, under the leadership of a new clergy, could the New Church be established. The Lord acts immediately from the Writings, and mediately by men, and especially by the clergy. But always, the New Church which the Lord in His second advent Cad in view, is based upon the Universal Theology of the New Heaven and the New Church, the theology that is taught not only in the True Christian Religion but in all the Writings, including or course the Arcana Coelestia. The arcana of heaven and the church have now been revealed by the Lord, to serve as the doctrine of life and faith for the New Church... (@AE 670[4]). Truths can come only from a Divine revelation, without truths, there is no theology, and where there is not this, there is no church (@TCR 619).

---

One hundred and eighty-years have passed since the Universal Theology was published. A New Church based on this has be established or at least gained a foothold in various quarters of the earth and among several races. The slow growth of the New Church can be traced to many causes, and was predicted in the Writings themselves. But the Writings connect this with the slow growth of the new heaven.

Three reasons are given why the New Church must begin with a few, afterwards be with more, and finally reach fulnessthat is, reach its appointed state. 1. Only those who are interiorly affected by truths can acknowledge its doctrine of love to the Lord and charity towards the neighbor. And only those can see truths who have cultivated their intellectual faculty and have not destroyed it by selfish and worldly delights. 2, The doctrine cannot be received by any who are confirmed in the doctrine and life of faith alone. 3. The New Church on earth grows according to its increase in the world of spirits (@AE 73, cf. 670, @AR 547).

Good spirits after death retain the faith they had professed on earth and are unable to sever themselves from its fallacious teachings unless they have a spiritual affection of truth. They therefore congregate among the spirits of their own religion, and are instructed in whatever of truth does not conflict with their spurious conscience. They may indeed form heavens, but not the New Christian Heaven from which the New Church on earth can be inspired. Only those among them who have a spiritual love of truths, can receive the heavenly doctrinethe doctrine of the new heaven and the New Churchand become members of the specific church in heaven. For this New Church is the Christian Church itself (Ath. Cr. 147).

Thus the heaven which is to be conjoined with the New Church is from spirits of all religions but only such spirits as receive the doctrine in its essential fulness, from a spiritual affection.

And it is upon the conjunction of men with the angels of this New Christian Heaven that the growth of the New Church depends. Not that any truth can percolate down to us from that heaven. The Writings alone give us access to the truth. And indeed the Writings did descendas revelationthrough that heaven. But what the influx of the New Heaven provides is (firstly) the affection which is needed for the perception of the truths of the Writings, and (secondly) the enlightenment in those truths.

It is often stressed in the Church that life is all one and is varied by reception. But reception occurs on all planes of creation and hence influx is varied indefinitely. There are untold different influxes originating in the heavens and hells. Each society of heaven represents a distinct affection, and that affection is what inflows into men and arouses a love and an interest in the particular use of that society and in the field of truths which implement and serve that use. Even in this world, interest in a use or in a field of knowledge or doctrine depends on the sphere of a sustaining society, where the thought is varied and enriched and encouraged by many minds. But a society or church in this world would be altogether helpless unless it invited the influx of corresponding societies in the other world. For while thought is stimulated from other men and from the Word and doctrine propagated by them, affection inflows only from the spiritual worldwhence all our life comes.

Hence the New Church depends for its growth and vigor on the societies of the New Heaven; and these serve as its soul. The affection of spiritual truth therefore introduces mans spirit into an affirmative attitude and into a state of enlightenment. Enlightenment or spiritual illustration is actually the introduction of a mans spirit among these angels who are more than others in heavenly light from the Lord (@DLW 150). But such illustration cannot take place except when man reads the Word, which provides the objects or the truths which he can see. Without objects to behold, light is of little use. Nor can illustration become effective where falsities are taken for truths or where truths are confused and disordered.

This is the reason why a New Heaven has no power to give illustration to those who read the Scripture in the light of false doctrines. For the establishment of the New Church it was thus necessary that a new Divine revelation be given to men. And this is done in the inspired Writings of Swedenborg.

== Class IV - Part I - THE SACRAMENTS RENEWED

The New heaven with which the New Church on earth is to be conjoined is composed of spirits from various religions, but only of such as have received the heavenly doctrine from a spiritual affection of truth, in essential fulness.

The Word and the two sacraments of Baptism and the Holy Supper are the means by which this conjunction of heaven and the church can be effected. The Writings show that the sacraments, in the former church, were observed from piety or from custom or from a belief that sins are thus removed; but that Christianity itself is now first beginning to dawn and a New Church is being established which can enter into the real use of the sacraments, which is done when man understands the spiritual meaning and the holiness of Baptism and the Holy Supper, and applies this to himself by the Lire of regeneration (@TCR 700).

The question is thus raised as to what is effected by the sacraments administered in the denominations of the old Christian Church which is now at its end. The general doctrine is that by baptism a man is introduced into the Christian Church and his spirit is at the same time associated with angels of the Christian Heaven (@TCR 677). But the more specific teaching is also given that he is inserted among societies and congregations there according to the Christianity in him or around (extra) him (@TCR 680[e]). The general effect of the last judgment was to establish a greater spiritual order. And order requires distinctions, not only in the whole but in all parts. Indeed it is stated that on the distinct arrangement in the spiritual world the preservation of the whole universe depends. And since distinctions cannot be made without signs by which it is know to what religious assembly each man belongs, baptism was instituted by the Lord for Christians instead of circumcision which had introduced into the Jewish Church. Yet there can be many kinds of baptism: the baptism of John had the efficacy of enrolling the penitent Jew among those in the other life who in heart expected and desired the Messiah (@TCR 689, 691). The baptism of John represented a cleanings of the external man, and those baptized by him, when they received faith in Christ and became internal men, ... were baptized in the name of Jesus. This requirement of a second baptism is spoken of in the Acts of the Apostles, xxi. 3 to 6 (@TCR 690).

It follows from this that a baptism into the First Christian Church does not introduce either into the New Christian Church or into the New Christian Heaven, but into congregations of the old church on earth and into societies of spirits who remain in the faith of the old church. Such societies of spirits are continually formed in the world of spirits, but the inhabitants are only temporary sojourners on their way to heaven or hell (@SD 5871-5876, LJ 64). The Lord at this day is forming a new angelic heaven, the Writings testify; and it is formed of those who believe in the Lord God the Savior and go immediately to Him:
and the rest are rejected. The heavens can no longer be approached through the worship and prayers of those in faith alone (@AE 277[e]). Hereafter prayers to a divided Trinity are driven back from heaven like smoke (@TCR 108).

Yet if a mans heart is sincere and upright, he will be saved whether he be pagan, Jew, or Moslem, Catholic or Protestant! If he is animated by a spiritual love of truth, he can be taught in the other life and introduced into the New Christian Heaven. But if his affection of truth has only been natural, and his perception limited by the prejudices of family pride or personal loyalties, so that he sees doctrine only in the borrowed light of others rather than from the Word, it will be impossible for him to remove from his mind the falsities that he had accepted in the world. Such are saved, if they have been in charity according to their religion; and they then acknowledge God and refrain from evils because He forbids them; and, in varying degrees they acknowledge the Lord as the God of heaven. But they remain natural. Their spiritual minds have not been opened.

Such spirits take for truth all manner of false teachings if only there seems to be some good in the falsities! They incline to look to merit and reputation. It is said of these that they abide in certain heavens which are under the Lord (@AE 708, 527). For the Grand Man of heaven is distinguished not only into two kingdoms, and into three heavens; but also in respect to the manner in which the light of intelligence is received from the Lord. Those who think rationally about their faith, from a spiritual affection, see the Lord as a Sun. But those who have intelligence only from a reflected lightor from other men, so that they think not from an open rational but from memoryare under the Lord as a Moon! There are three such heavens, and all there are natural, and can see nothing in real solar light; although to them the reflected light seems quite bright enough.

It would seem that these lunar heavens are very many, formed of good spirits from every religion in which falsities predominate, the heaven of each religion being quite separate from every other. And it is our understanding that by various signs and initiations and rites, and further by doctrinal training, earthly children of each religion are more and more introduced into an association with the lunar heaven of their own faith, so far as they do not confirm falsities with an evil life, but yet adhere to falsities to which good can be adjoined.

From this it would follow that old church baptisms introduce into the society of the denomination in the world of spirits andif the child, as he grows up, undergoes repentance and something of reformationinto the lunar heaven of his church. Such baptism cannot introduce into the New Christian Heaven itself; unless, after death, he is found to have a spiritual love of truth which surmounts denominational prejudices and preconceptions and opens his mind to instruction in the heavenly doctrine. Children who die in their tender infancy, before they are infected by the falsities of their religion, are however all taken up at once into the New Heaven where they are taught first of all by celestial angels (@SD 347, 345). And these infants remain utterly ignorant of the falsities of their parents (@LJCont 58).

The religion of the heavens under the Lord as a Moon, which remain in relative obscurity, to the New Christian Heaven, is suggested in Johns vision of the celestial woman crowned with twelve stars and clothed with the Sun (Apoc. xxii). For it is said that the Moon was under her feet; which signified that the faith of Christendom at the present day was such that there could be no conjunction of the New Christian Heaven with it (@AE 708, @AR 533).

It may indeed be that there are lunar heavens formed of those New Church people who are attached to the external life and traditional doctrine of our Church only from natural affection and thus from historical faith. Yet the heaven with which the New Church on earth is to be conjoined, from which it is to receive its enlightenment, and where its people are meant to find their eternal home, is under the Lord as a Sun!

And in this New Christian Heaven, those who were conversant with the Writings, the Heavenly Doctrine of the New Jerusalem, while on earth, must have certain functions that are quite unique and that others cannot perform, not even the twelve apostles who on the Nineteenth day of June, 1770, were charged with the mission of Spreadingthroughout the spiritual worldthe new gospel that the Lord Jesus Christ had come again in His kingdom.

Foralthough New Church angels cannot claim to be more regenerate than othersyet those who on earth, by their rational understanding perceived Divine arcana naturally from an affection of truth, can, when they become spirits, use their knowledge as a vessel to convey the wine of spiritual truth, in a way that others cannot (De Verbo 6). This function may carry them far and wide in the spiritual world; but it will doubtless also bring New Church spirits together to consort in groups and societies, not only in the world of spirits, but in the New Heaven.

== Class IV - Part II - THE EFFECTS OF THE LAST JUDGMENT ON THE NATURAL WORLD

Reading: Revelation 12.

The last judgment was performed in the spiritual world. There its effects were a complete ordering of the influxes from heaven, and a restoral of freedom for all noviate spirits so that they could be more speedily judged hereafter. No longer could false heavens be established by evil spirits and maintained for many centuries. Such imaginary heavens as are still permitted are temporary and are periodically judgedat least within twenty years (@AR 866). Every society in the spiritual world is purged of evil spirits continually. The evil still abound in the world of spirits, but are held under restraints. Spirits from the earth are now able to remain in the world of spirits only for twenty or thirty years at most. Their first state, when they retain the externals of life which they were in the world, lasts rarely with any one more than a year (@HH 426, 498, @AR 866).

Thus the equilibrium between heaven and hell is now restored, and since the spirits or minds of men are unconsciously in the word of spirits and are continually acted upon by both good and evil spirits. Men are now in a kind of freedom as to the interiors of their minds in which they were not before. Always, men have had spiritual choice. But the choice has been confused, since the spiritual issues have not been clear, and when this is so, only a moral decision is involved in their choice; which still, so far as it is free, associates them either with heaven or with hell.

Before the last judgment, the false heavens interposed themselves between the true heaven and the spirits of men, like dark and threatening clouds. At the first coming of the Lord, the hells had even begun to infest the angels and also every man coming into the world and going out of the world (@BE 57, @AE 806[2], Lord 33). A judgment removes those infernal clouds and restores the influx of heaven into the world of spirits.

It is therefore said, that after the judgment was accomplished, there was joy and also a light in the world of spirits such as had not been before. This may be explained by the fact that new centers of instruction were established, not only in the New Heaven but also in the world of spirits. The functions of the specific church were there reestablished as a means of propagating the light of truth to all nations in the spiritual world.

But it is also added: A similar light arose also with men in the world, from which they had new enlightenment (@LJCont 30).

What was this new light that arose among men? And what effects has it had in the world? It has already been observed that illustration or mental light arises by the insertion of a mans mind into a spiritual society. Understanding is not possible if we are in states of impatience or prejudice or in a negative mood, or if pride or self love closes our eyes. But it comes when we are introduced into a spiritual sphere. The new light after the last judgment came from the spheres of faith in the New Heaven.

Yet how is that light received on earth? To whom can it give spiritual enlightenment? The answer is that there is no reception of the light unless there are objects which reflect the light. These objects are in the Writings, and are called truths. As far as these truthsin their organic form as the doctrine of faithare known and loved, so far does the light cause spiritual enlightenment.

Yet there are many in the New Church who hopefully scan the Christian world and say, Lo here and Lo there, whenever any writer or orator expresses some thought that seems to harmonize with New church teachings; although that isolated truth may be interlarded with many falsities. They take it as a proof that the light of the new heaven is gradually permeating the former church and making it new. If they see some worthy charitable undertaking some indication of a better religious or racial tolerance, they point to it as a sign that the new age of the second advent is dawning.

But it is not so that we are to expect the New Church. The Lord derives and produces the New Church on earth through the New Heaven by means of a revelation of truths from His mouth, or from His Word, and by inspiration... (Coro. 18, 20). And the revelation referred to is the doctrine given to the New Church. It is through the Writings that the New Church is to be established in the light of the New Heaven.

Yet the Last Judgment has had many indirect results, and many after-maths in the natural world. Indeed, the two centuries that have almost elapsed since 1757 have witnessed more revolutionizing changes in mens manner of living and thinking and even changes on the surface of the globe than any other period of known history.

The spiritual judgment itself, as witnessed by Swedenborg, was swiftaccomplished within a year. It was not discernible on earth, and was accompanied by no startling events in the world. The work on the Last Judgment contains therefore this warning:

The state of the world hereafter will be altogether similar to what it has been heretofore, for the great change which has taken place in the spiritual world does not induce any change in the natural world as to the external form; so that after this there will be civil affairs as before, there will be peace-makings, treaties, and wars, as before, and other things that belong to societies in general and specifically... (@LJ 73).

That civil and political affairs have gone on as before, we can confirm after nearly two hundred years. Swedenborg did not expect any sudden reforms, or any quick establishment of a heaven on earth. He did not anticipate any essential change in human nature or any rapid growth of the New Church.

As to external appearance, he wrote, divided churches will exist as heretofore, their doctrines will be taught as heretofore; and the same religions as now will exist among the gentiles. But as to its internal, the state of the Church will be dissimilar: henceforth the man of the church will be in a more free state of thinking on matters of faith, thus on spiritual things relating to heaven, because spiritual freedom has been restored to him.... But man does not observe this change of state in himself because he does not reflect upon it, and because he knows nothing of spiritual freedom and of influx; nevertheless it is perceived in heaven, and also by man himself after his death (Ibid.).

Before the judgment, not any doctrine of the Church could be conveyed
... to men on the earth without being falsified. But after it, many can be led, in a freer and more spontaneous spirit, to discard falsities and to receive truths from the new revelation (Coro. 20). The angels told Swedenborg that they know not things to come, but they did know that the slavery and captivity in which the man of the Church was formerly, has been taken away, and that now, from restored freedom, he can better perceive interior truths, if he wills to perceive them, and thus be made more internal, if he so wills.... But they added, that still they have slender hope of the men of the Christian world... (@LJ 74).

It is of course clear that in the world of spirits this new freedom allows all novitiate spirits to progress towards heaven or towards hell without undue delays. But what it effects in the Christian world while the old churches, the Catholic and the Reformed, the Evangelical Lutheran and the Methodist, the Baptist and a hundred other denominations still maintain their external worship and defend their ancient falsities, is not so manifest. In the centuries since the judgment, however, there has been established, in America and in many other countries, a degree of religious liberty and a tolerance which were unheard of in Swedenborgs times. This liberty of worship and of thought and speech is by no means universal, and in some countries it has been recently restricted by the powers of the civil state while in others the Catholic Church or some other hierarchy prevents any rival religions from taking root.

In frequent instances, freedom of worship has obviously not been the generous fruit of Christian charity but was fought for by elements opposed to Christianityor at least opposed to the established Churches, which only grudgingly granted religious liberty to dissenters. The chief reasons why religious tolerance obtains are found in a growing indifference to religion, a distrust of the organized churches, and realizationas in Americathat unless we grant liberty to others we cannot claim it for ourselves. The recent wide syncretist movement among Protestant sects which now seek to join forces and so avoid expensive local competition, is rooted in an increasing aversion for doctrinal discipline and a consequent feeling that the mission of Christianity is largely social improvement rather than the salvation of the soul. And a similar substitution of secular progress for religious goals is noticeably commencing even in lands where pagan religions are dominant, as in China and India.

All over the worldwith conspicuous exceptionspeoples are waking to a new freedom which allows the individual more rights and imposes on him a greater personal responsibility, while at the same time he may be regimented into more fixed educational and economic patterns. Suppressed and backward races are chafing at their bonds, social, political, and religious. Yet how are men using their new freedom? Not only are there New heavens, but also new hells! Both are ready to pour in their influx so far as many freely invite it. Freedom is freedom for the evil as well as for the good, and the wicked use it for a more flagrant propaganda. of their crude philosophy that might is right and that there is no reckoning after death, no Divine law before which men need bow.

The world, since the second advent of the Lord, has been in the throws of a mighty judgment. On earth this proceeds slowly, with issues that seem obscure and confused. Indeed the conflict of this age seems not to be concerned at all with the New Church, which is only an oasis in the wilderness. The Divine truth of the Heavenly Doctrine is known to few, unobserved and ignored by the multitude. The world struggle today for dominion over mens minds seems to be not between the New Church and the old, but between the forces of religion, represented by various consummated churches, and the aggressive spirit of secular thinkinga spirit which has gradually evolved from humanism and deism to a frank materialistic atheism and which uses as a tool the immense armory of a steadily developing science.

Thus the falsities of religion are arranged against the falsities of the senses: each side using the persuasive powers of its own authorities; each side fighting not for true spiritual freedom but for its own ends, to gain prestige and honor, and the reward either of the world or of their own kind of their own kind of heaven.

And if we look further, we may realize that the battle lines are confusedcutting across these rival alliances. Within each side another struggle is going onbetween the love of the world and the love of dominion.

It is so that the Lord, by balancing and ordering the forces of evil and falsity, procures for the vast numbers of His Church Universalthe vast multitude of simple souls which no man can numbera freedom and a power that are implemented by natural good and by innate loves which the Lord uses to maintain the race: instincts of self preservation and the love of offspring and family and nation.

Yet within and beyond this apparent turmoil of humanity there works there almost unnoticed ferment of spiritual faith and charity which is represented in the Lords New Christian Church and in its Divine Revelationthe Heavenly Doctrine, the Writings; the one true faith which, because it springs from the mind of God, can meet the multi-form and shifting attacks of the hydra headed hells.

It is the New Jerusalem which now stands at the center of the spiritual world. Its doctrine is the touch stone of judgment for all spiritual states. All issues must eventually be judged by the truth of the internal sense of the Word. And although the New Church has remained among a few, the truths taught in the Writings have admittedly had a critical influence upon the worlds thought out of all proportion to the numerical importance of the organized New Church.

Truth can judge even when not received. The keen logic of the Writingsbroadcasted in an unending succession of educationshas been a major factor in arousing common sense against many of the dogmas of the old churchagainst concepts such as that of a blind faith, of a tri-personal God, of a vicarious atonement, of a merely literal understanding of the Bible, and of a bodily resurrection of the dead. Swedenborgs descriptions of the realities of the afterlife have found a far wider acceptance than supposed, not only among spiritualists who claim him as a Father of their movement, but among the clergy and laity of the established churches. But mostly, the truths of the Writings have been approved as a means to judge falsities, not as the way to the truth and the life, or as the Divine and authoritative law for a new age or for a New Church in which the souls of men can find a safe refuge from the hells.

---

The New Church is not to be established by persuasive miracles or rest its faith upon signs and wonders. Yet we cannot dismiss it as mere coincidence that since the last judgment new horizons of natural knowledge have opened and research has progressed with amazing spurts. Certainly this cannot be traced as a result either of Swedenborgs scientific achievements or of the new rational revelation given in the theological Writings. But we can hardly doubt that the conditions which resulted in the spiritual world from the last judgment are a direct cause of the increased effectiveness of the workings of mans natural minds.

From many indications, the spiritual judgment, which was so quickly accomplished in the other world, will eventually reach down even into the natural world. We are informed in the Apocalypse Explained (n. 641)
that the revelation of the spiritual sense was made in order that by means of it the good may become separated from the evil, and a New Church established, and this not only in the natural world where men are, but also in the spiritual world where spirits and angels are; for in both worlds there is a church, and revelation takes place in both, and thereby separation, as also the establishment of a New Church.

This judgment or separation can take place on earth only so far as, in the providence of the Lord, the impediments of space and time are relaxed in the natural world, and the minds of men can communicate more freely. The world of spirits is now freed from confusion, and its communications by influx are restored, welding it into a unified world, where freedom and protection is possible for all. A corresponding thing is occurring on earth. The discoveries and inventions of modern times haveoften against mens objectionsbroken down the barriers of space and time by improved communications. Stem, gas, and oil engines; chemical and electrical energy; steamships, trains, motors, airplanes; machine printing of newspapers and books; telegraph and telephone, radio and television; all these have, since the last judgment made possible a spread of knowledge and a contact of minds on earth which begins to approximate the conditions in the world of spirits.

But along with this we see the flaying tail of the Dragon, cast down as it is upon the earth. We are watching while the falsities of the past are losing their historic momentum. It may well be that Christendom has to become paganized before gentile states can arise which allow a reception of the New Church.

In many lands, the life and thought of the ordinary man has been revolutionized. We see humanity in a mental chaos, seething with issues of vast dimension. No longer does the choice of man affect only the immediate welfare of his family or nation. Many world problems are upon us too great for mens minds to settle, for they involve no simple choice between right and wrong, but of the future of races and civilizations, of the institution of the family and the homes, and the church. The industrialization and socialization of what once were domestic and personal uses seem to imperil freedom instead of assuring it.

Yet beyond these issues that we seeeven beyond the apparent justice of matters of war and peacethere lies a deeper, spiritual justice, which is conjoined to natural justice by means of a connection between things past and things future that are known only to the Lord. Even the wars men wage are decided not by prudence, but by Divine Providence, through a correspondence with spiritual conflicts that are fought out in the world of spirits (@DP 252, 251).

It is well to remember, therefore, that what we witness is the after-math of the last judgment. We are experiencing the convulsive, prolonged birth-pangs of a new world, which Providence destines to bein its turn, the womb in which the New Church will some day be nurtured. And over this world the Lord God Jesus Christ doth reign.
