= Essays on the Ten Commandments
By Hugo Lj. Odhner 
include::../template-attributes.adoc[]

Essays on the Ten Commandments + 
By Hugo Lj. Odhner +
General Church Publication Committee +
Bryn Athyn, Pa. +
1972


<<<

== Preface

This little volume is prepared for private reading or for use in public worship.

The TEN COMMANDMENTS, also called the DECALOGUE, are a summary of all things of religion (@TCR 286). They are explained in their natural and interior meanings in the Divinely inspired Writings of Emanuel Swedenborg (1688-1772) written for the use of the New Church which is meant by "the New Jerusalem." 

- In his last published work, "The True Christian Religion", a chapter (@TCR 282-331) is devoted to this subject.

- And in the posthumous work "The Apocalypse Explained", the Ten Commandments are dealt within a series of inserts - especially between paragraphs (@AE 948-1028).

- In the exegetical text "The Arcana Coelestia", their spiritual meaning is laid clear in the setting of chapter twenty of the book of Exodus (@AC 8860-8912).

- Further explanations are given in "The Doctrine of Life", (@DLife 53-91) and (@DLife 108ff),

- in "The Doctrine of the Sacred Scripture" (@DSS 67), + 
and in "The Divine Providence" (@DP 329 ff).

For the sake of completeness a copy of the two versions of the Commandments is appended on following pages.

And in order to facilitate the use of these Scripture passages in worship, a selection of lessons from the threefold Word is also provided.

Hugo Lj. Odhner + 
Bryn Athyn, Pennsylvania +
April 1971

<<<

=== The Ten Commandments from Exodus

And God spake all these words, saying:

I am the Lord thy God who brought thee out of the land of Egypt, out of the house of bondage.

Thou shalt have no other gods before My face. Thou shalt not make unto thee a graven image, or any likeness of anything that is in the heaven above, or that is in the earth beneath, or that is in the water under the earth; thou shalt not bow thyself down to them, nor serve them; for I the Lord thy God am a jealous God, visiting the iniquity of the fathers upon the children, unto the third and fourth generation of them that hate Me; and showing mercy unto a thousand generations of them that love Me and keep My commandments.

Thou shalt not take the name of the Lord thy God in vain; for the Lord will not hold him innocent that taketh His name in vain.

Remember the sabbath day to keep it holy. Six days shalt thou labor and do all thy work; but the seventh day is the sabbath of the Lord thy God; in it thou shalt not do any work, thou, nor thy son, nor thy daughter, thy manservant, nor thy maidservant, nor thy beast, nor thy stranger that is within thy gates; for in six days the Lord made heaven and earth, the sea, and all that is in them, and rested on the seventh day; wherefore the Lord blessed the sabbath day and hallowed it.

Honor thy father and thy mother that thy days may be long upon the land which the Lord thy God giveth thee.

Thou shalt not kill.

Thou shalt not commit adultery.

Thou shalt not steal.

Thou shalt not bear false witness against thy neighbor.

Thou shalt not covet thy neighbor's house.

Thou shalt not covet thy neighbor's wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor anything that is thy neighbor's.

Exodus 20:1-17

---

<<<

=== The Ten Commandments from Deuteronomy

Hear, O Israel, the statutes and judgments which I speak in your ears this day, that ye may learn them, and keep and do them.

I am the Lord thy God who brought thee out of the land of Egypt, out of the house of bondage.

Thou shalt have no other gods before My face. Thou shalt not make unto thee a graven image, or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth. Thou shalt not bow thyself down to them, nor serve them; for I the Lord thy God am a jealous God, visiting the iniquity of the fathers upon the children, unto the third and fourth generation of them that hate Me; and showing mercy unto a thousand generations of them that love Me and keep My commandments.

Thou shalt not take the name of the Lord thy God in vain, for the Lord will not hold him innocent that taketh His name in vain.

Keep the sabbath day to sanctify it, as the Lord thy God hath commanded thee. Six days shalt thou labor and do all thy work; but the seventh day is the sabbath of the Lord thy God; in it thou shalt not do any work, thou, nor thy son, nor thy daughter, nor thy manservant, nor thy maidservant, nor thine ox, nor thine ass, nor any of thy cattle, nor thy stranger that is within thy gates; that thy manservant and thy maidservant may rest as well as thou. And remember that thou wast a servant in the land of Egypt, and that the Lord thy God brought thee out thence by a mighty hand and by a stretched out arm; therefore the Lord thy God commanded thee to keep the sabbath day.

Honor thy father and thy mother, as the Lord thy God hath commanded thee; that thy days may be prolonged, and that it may go well with thee in the land which the Lord thy God giveth thee.

Thou shalt not kill.

Thou shalt not commit adultery.

Thou shalt not steal.

Thou shalt not bear false witness against thy neighbor.

Thou shalt not covet thy neighbor's wife.

Thou shalt not covet thy neighbor's house, his field, or his manservant, or his maidservant, his ox, or his ass, or anything that is thy neighbor's.

Deuteronomy 5:1,6-22

{empty}

---

{empty}

<<<

=== Selected Readings for Services 

Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, thou shalt love thy neighbor as thyself. On these two commandments hang all the law and the prophets. + 
Matthew 22:27-40

A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another. By this shall all men know that ye are my disciples, if ye have love one to another. + 
John 13:34,35


[cols="4"]
[%autowidth]
[frame=none]
[grid=none]
.Selected Readings for Services
|===
|1|Exodus 20:1-21|Matthew 12:30-45|@AC 8862
|2|Deuteronomy 5:1-22|Mark 3:20-35|@SE 1304
|3|Isaiah 55,56 |Luke 13:10-22|@AC 8885 (parts)
|4|Deuteronomy 32:1-20, 44- 46|Luke 2:39-52|@TCR 307,308 (parts)
|5|Genesis 9:1-17|John 15:1-17|@DSS 67
|6|Genesis 2:15-25|Matthew 19:1-15|@CL 204-205
|7|Joshua 7:16-26|John 10:1-18|@DLife 91-97
|8|Genesis 3:1-19|Matthew 26:59-75|@TCR 321-323
|9|Deuteronomy 6:1-15|Matthew 18:21-35|@TCR 400: 11-14
|10|Revelation 18:1-21|Matthew 18:1-20|@TCR 400:8-10
|===


<<<

== 1 The Law Against Graven Images

_Thou shalt have no other gods before my face. Thou shalt not make unto thee any graven image, or any likeness of anything that is in the heaven above, or that is in the earth beneath, or that is in the water under the earth: thou shalt not bow down thyself to them nor serve them..._ (Exodus 20:3-5)

In the ark of the covenant - the inmost shrine of Israel - there lay, face to face, two tables of stone. The first table contained the first three commandments which recounted the duties of man toward God and thus the conditions under which the Lord God could be present among men. On the second table were written the rest of the precepts, which related man's duties to his neighbor and thus indicated what the Lord, if present, could enable man to do in order to be conjoined with the Lord.

The first requirement, in order that the Lord may draw near to us so as to conjoin Himself with man, is given in the first precept: that we must have no other gods before His face, and must make no idols or images to worship.

The revelation that there was but One God came to the shepherd people of Israel when they had fled from the temple-filled cities of idolatrous Egypt. History testifies to this religious revolution as a most epoch-making event. For in those days the representative spiritual church of the Ancients had long been corrupted and the whole world was steeped in idolatrous worship of many gods and had confused the image with the God in gross superstition. It was hardly conceivable that anyone at that day could claim his god to be the only one - to be a jealous god who would permit no rival!

But the world changes. Who, at this day and in this civilization, would make idols to worship? or bow down to stone or wood with fear and reverence? Yet the commandment is not obsolete. Even to us in these latter days, the Lord must needs speak this warning against idolatry which is as fatal to the soul now as of yore. For human nature is always prone to take the symbol for the reality - to worship the image, and put its foremost faith in material things and natural forces; and to divide that love which should belong only to the One Divine among many finite and fallible human objects. This tendency is shown in the story of Judaism despite its proud adherence to the philosophy of a One God and its strict rejection of external images. It is shown in the gradual development within Christianity, of the idea of three separate Divine personalities within the One God, and in the introduction of saints and relics into Christian worship. It is shown in the spreading modern idea - the supreme blasphemy - that man is not created into the image of God, but that mankind has created its god or gods into the image of man! Nay, the same tendency is shown in the story of all our individual lives, in that we tend to idolize whatever reflects the image of our own desires.

---

In the obvious and literal sense, the first commandment teaches that no man, dead or alive - no spirit, no angel, no demon - must be worshipped, but only Jehovah, who is the Only God, known to the Israelites as the Creator and revealed on Mount Sinai as their Redeemer from the bondage of Egypt.

Vaguely, the Jews thought of their God as being in a human form, and speaking to their prophets through an angel. But they could comprehend only a God who, like themselves, was vengeful and jealous, fickle and arbitrary, and who was moved by the love of power and self-glory. They could therefore not penetrate to see the spirit which lay within the First Commandment.

To reveal the spiritual meaning of this remarkable precept, and thus make clear that God is Love and Wisdom itself, Jehovah descended into the world of human life in and as the Lord Jesus Christ, and thus revealed His Divine Humanity, so that men might know God. By His resurrection and glorification, all that was not Divine was put off and He was united with Jehovah in absolute identity of Person and Essence, even as the Body and Soul of the One God. The testimony to His sole Divinity was the simple message of all the apostles, who were not yet confused through sophistries and theological speculations, but who knew that in Christ "dwelleth all the fulness of the Godhead bodily," (Colossians 2:9), and who said of Him, "This is the true God, and eternal life. Little children, keep yourselves from idols." (1 John 5:20,21).

In man's external thought, which is the conscious thought of his natural mind, he can entertain false ideas concerning God, and also can think of many gods, or of God as merely the interior force or impersonal blind energy within nature, thus as an invisible God with whom there is no conjunction of love; yea, he can even deny that there is any God. But man's internal thought, which is the thought of his spiritual mind, is incapable of conceiving of God except as the Divine Human. Such is the angelic conception about the One God - since in the angelic mind the thought of time and space perishes, and the Divine Human, or God-Man, can thus be perceived without the limitations of gross earthly ideas.

Even the eyes of angels are unable to see God - the Divine Human - apart from finite accommodations. The Divine Man is visible before them through the finite appearances of their own minds, thus more fully or profoundly, according to their degree of wisdom. Yet by rational acknowledgments they enjoy a deeper sight - or insight - from which they see the Lord as infinite and eternal. To them, it would be a breach against the First Commandment to confuse anything finite and created with the Divine, or to worship what is but the garments of God as the Lord Himself!

And therefore we are taught that the celestial or inmost sense of the first precept is that the Lord is infinite and eternal, the First and the Last, omnipresent and omniscient and omnipotent: that He is Love and Wisdom in their very essence and origin; that His substance is infinite Love and His form is infinite and eternal Wisdom; thus that He is Life itself. It is so that we may understand that He is the source of all human qualities, and therefore is the Only Man whose gifts of life can alone make us human.

---

Man, despite his human soul, is born in captivity, in bondage to self-love, vanity and hereditary passions. We are held in the Egypt of spiritual indifference, preferring the indulgence in natural delights to the freedom which the Lord offers those who would be led by Him. It is frequently imagined that man can, by his own will-power and prudence, free himself from the bondage of his faults and evil habits. But the truth is that we cannot be liberated from our proprium, our self-consciousness, and self-importance, which are the centers of our lives, by any effort which originates in our old will. However we cultivate and refine our natural affections or polish our behavior, any self-discipline which originates in our old will would progress in circles back to our love of self; it is the Lord who alone can do the work of liberation, and His first condition is that we must assume Him, not ourselves, as the center of our lives; that we shall have no other gods before His face; that the evils which we flee from shall be shunned because they are evils against Him, not merely because they are inconvenient to us or make us appear ugly in the eyes of others.

It is thus the Lord who shall teach us what is good and what evil, what is true and what false. Our regeneration must commence in our understanding of His will and His ends, His ways and His means. For this cause He gives us His Word and His Commandments, and endows us with an understanding, a memory, an imagination, and a rational mind. And the power of a man to free himself from his evil proprium or from the bondage of his hereditary evils, depends on his not permitting the evil passions and delights of his old will to overtake and overpower his understanding, in which the Lord - through the truths of His Word - is seeking to establish and give to man a new and regenerate will.

In the Arcana Coelestia, the internal sense of the First Commandment is therefore stated to be, "that truths must not be thought of from any other source than the Lord" (@AC 8867). That this is the internal meaning and thus the universal idea within the precept against idolatry and polytheism, may not at once appear, unless we reflect on the fact that no 'truth' about anything is true unless it shows the relation of that thing to the Lord and to His purpose as it works itself out in the universe. If it blinds a man to the Lord's presence and purpose, it is not a truth that enlightens but a fallacy or appearance which misleads. Thus human learning, however factual, may lead men into increasing mental darkness. A truth must be a statement of the relation of a part to the whole. We recognize this when we dismiss some statement as a half-truth or as 'mere propaganda'. And the whole truth cannot be seen except from the Lord. Even the best knowledge of the laws of the universe is mere idolatry - worship of Nature - unless thought of as the laws of the Lord's wisdom and mercy. And this is true also of those truths of civil and moral and spiritual life which are contained in Divine Revelation. They become fallacies unless seen in the light in which the Lord presents them in His Word; fallacies if taken apart from the Divine purpose. Literal statements from the Word - such as the recital about the creation of nature's kingdoms in six days - can be turned into dangerous errors and stumbling blocks if treated merely as scientific laws apart from the spiritual message which they symbolically express. The revealed truth concerning the existence of another world can be profaned and degraded if regarded as a spur to human curiosity instead of as a means by which the Lord seeks to operate for man's redemption from the evils and false appearances of our corporeal life. To seek material confirmations of the presence of spirits by consulting mediums, and if convinced, to regard the spiritual world as a wonderful discovery of man's; or to rest one's faith in God and the soul on mere reasonings - on a 'natural theology' which does not credit a Divine revelation - all this is quite apart from any religious value. The convictions so formed are merely gods of the flesh, of whom the Lord says, "Thou shalt have no other gods before my face."

In the spiritual sense, "gods" mean truths, or falsities which are supposed to be truths. Every falsity is the perversion of a truth and often bears the external aspect of truth. And in the mind and on the lips of man there may be truths from the Word which are used by man's prudence for purposes quite other than those for which the Lord revealed them, and which are thus not thought of from the Lord. Of such truths the Writings say that they "are in themselves truths" but are then "not truths in their internal form." They are closed within. The Lord is not in them, nor do they lead to the Lord or bring the presence of heaven, for they have not the Lord's love of salvation in them (@AC 8868).

The most sublime truth becomes the merest idol if viewed apart from the Lord. The truth that God is One, if divorced from the idea of the Lord as a merciful Savior, becomes a philosophical quibble - a term devoid of any religious meaning. Any teaching of the Church becomes an empty, closed idea, an idol, a false, misleading god, if - stressed by human pride or taken to confirm some evil of life - it becomes dismembered from its organic connections, from its place and use in the structure of Divine Doctrine. If seen apart from its purpose as a means of Divine redemption, it becomes a thing of the memory only. This is indeed the reason why the Writings of the Church contain so many repetitions. Each new truth which we learn must be seen from the Lord, not from the passing states of our intellectual fancy. The truly pious reading of our Revelation and of the Word in its letter in a sphere of worship, whether public or private, directs our affections to the Lord and has the peculiar power of conjoining man to heaven and the Lord because truth is then seen not as man's wisdom but as the Lord's.

Man's self-intelligence and natural delight of confirming what is agreeable to his vanity, are indeed tools by which truths are hammered and fashioned into "graven images," or moulded by the flame of our cupidity into a "molten image." It is so that every false doctrine is raised up as a rival to the One God, and its adherents come to worship the spirit of evil and of deceit. But the Divine command continues: "Thou shalt not make unto thee ... any likeness of anything that is in the heavens above or that is in the earth beneath or that is in the waters under the earth; thou shalt not bow down thyself to them, nor serve them." To the Jews this was a severe but necessary restriction, ostracizing the plastic arts. But the purpose with this precept was to warn against deception, persuasion and hypocrisy, which are a magic and an idolatry that can survive as enemies of God long after primitive superstitions have lost all religious significance.

To "make a likeness" means to deceive others or, by excuses and reasonings deceive ourselves. To make a likeness of anything in the waters beneath means to deceive by things of science, or to throw doubt upon the laws of charity, by the fear of appearances or of material force. To make a likeness of the things on earth, means to deceive, and lead into evil, through hypocritical pretensions or through the lure of sensual delights or by the spell of insincere persuasion. And to make a likeness of what is in the heavens above, is to deceive and mislead by falsifications of the doctrine of spiritual truth.

The mind of man - ever centered and concerned in self - is prone to bow before such pretences. And that which comes to rule inmostly, is his god. That which man fears the most, is most afraid to lose, becomes his god. Civilized man does not worship gold or fame; but he bows down to these as mediate ends, thinking of self as the real god to be served. We worship the world, if - distrusting the Divine Providence - we submit to having the world's opinion or the world's allurements, rule us, rather than the laws of God. We worship self, and thus bow before the evil spirits of hell, if we allow the spirit of self to order our lives.

But truly, these interior idolatries lose their fair aspect in the other life, for then hypocrites will fashion the image of their fantasies in monstrous and depraved forms for others to behold. Led by their passion to counsel others to worship these gods which they insanely serve, they finally must bow down, as cringing time-servers, to whomsoever among them can make his will prevail.

In the heavens it is not so. For there the angels know that beside the Lord in His Divine Human there can be no other god. And that only the Lord God is worthy to be loved, and in men only what is from Him. None there can accept worship for himself or bow down to any human merit. But from this first law of heaven, the neighbor is loved according as he is a willing medium for the Divine uses which the Lord performs for the perfection of angelic happiness.

<<<

== 2 The Law Against Blasphemy

_Thou shalt not take the name of JEHOVAH thy God in vain; for the Lord will not hold him innocent, that taketh His name in vain._ (Exodus 20:7)

The Lord caused Israel to preface their law with three commandments which made the whole into a Divine law. The first of these stated that the Lord Jehovah alone is God, and required that He alone be worshipped. In the second, which bids us not to take His name in vain, we see an added requirement which must mark us if we would be more than merely natural, civil, and moral men, but also citizens in the spiritual kingdom of love and charity.

The doctrine of the New Church teaches us that "the signs of charity are all the things which pertain to worship" (@Char 8). The sign which indicates that one has charity is not - as is generally believed - "good works," but piety. Good works, helpfulness, altruism, generosity, are signs, not so much of charity as of civil loyalties, and may proceed from the love of worldly praise, honor, and power, or from the natural good of friendliness and inborn good nature. But the sign of true charity - the necessary mark of the spiritual man who acts not from self but from charity - is piety.

The broad meaning of the Second Commandment is, that man must be pious, must not be irreverent, must not take lightly his relation to the Lord, must not blaspheme or misuse the Lord's name which is "holy and reverend." In its literal form, this precept took such a hold upon Jewish minds that eventually a Jew did not even dare to pronounce the name Jehovah even while reading it in the Word. The same extreme reverence was shown to the Ark and the vessels of the Sanctuary. These were not touched except by ritual modes and by sanctified hands. The idea of holiness was that what was holy was set apart - held in fear; for contact with it meant a blessing only if such contact was obtained by prescribed rituals; otherwise a curse or calamity would follow.

In common with other nations of the decadent Ancient Church, the Jews were convinced of the power and holiness of certain names. The prophets, too, performed miracles in the sacred name of Jehovah. The Lord, when on earth, allowed His disciples to control demons and do works of healing in His name - thus proving its holiness. But neither the Israelites nor the disciples came to understand that this use of the name was not any benevolent magic, but a Divine application of a profound spiritual law - a law of the spiritual world, the world of human minds and spirits. For it was not the name only, but all the conditions and needs and states of mankind both on earth and in the heavens, which called forth the miracle. And although such miracles do not occur in the same manifest ways at this day, yet the power of the Lord's name is not lessened. He grants men whatsoever they pray "in His name," and "when two or three are gathered together in His name," He is in the midst of them. But let us reflect on the meaning of this 'name.' A name is that which makes a man known to us. It means his fame and reputed qualities, his influence among men, his power, his abilities to perform uses. When a spirit enters into eternal life, his earthly name and fame are forgotten, and a new name is given him, by which his real qualities are described in the spiritual language of ideas. And such a new naming is also of order, when a man enters into the Church on earth by the gate of Baptism - to signify the new quality which he then assumes.

The name of the Lord our God therefore, in a spiritual sense, represents His infinite, Divinely Human qualities. It means His Divine which proceeds from Him as Divine truth, as the light and heat of the spiritual Sun. It means everything of Divine revelation by which His qualities are made known; and thus it includes everything of His Word, in its letter as well as its spirit. It extends into the worship of the Church into which the Word enters, and to the whole Church and to the sphere of Divine Good which - from the Lord - pervades its worship and life.

All that is commanded by the Lord, and therefore done in His name and on His behalf, is a means of His holy presence. For by His 'name' is meant His Divine Order, His plan of salvation, His way of bringing His rule into the minds and hearts and personal lives of men and into the government and institutional uses of the Church. All good and all truth are of His name, and in them are vested His power and His holiness.

This inclusive meaning is given in the Arcana Coelestia, where the precept, "Thou shalt not take the name of the Lord in vain," is explained to mean, that we must not profane or blaspheme the truth and good of faith; we must not turn truth into falsity by avowing the truth yet living in evil; nor turn good into falsity, by deliberately living under holy pretences while yet not believing the truth (@AC 8882). For if so, the Lord cannot hold us guiltless.

---

The evil which is here described is the evil of profanation, the mingling of good and evil, the conjunction within one mind of heaven and hell. No evil - so the Doctrine reveals - can be more terrible than such a profaning of what is holy by what is evil. The ancients, even the primitive peoples whose fragmentary wisdom men scorn at this day, lived in a manner closer to the spiritual world than we moderns who live in a world where nothing is held sacred. And therefore - despite their ignorance of physical laws - they knew the truth about profanation and its direful punishments. They lived in fear of sinning against something that was holy, of offending the gods. And this led them into gross idolatries and superstitions, because they lost their original discernment of what holiness was.

But we, in the New Church, are given to know what is holy. We know that the Word is the holy ultimate of Divine order upon earth; that upon it the Lord has put His name, and that He dwells within His Word and is present in its sacred teachings to bend our affections heavenward and to strengthen our faith in Him. When the Pharisees had suggested that Jesus drove out evil spirits by the power of Beelzebub; and when they thus denied His Divine power - His Divine Spirit and Soul - the Lord replied by saying, "All manner of sin and blasphemy shall be forgiven unto men, but the blasphemy against the Spirit shall not be forgiven unto men. And whosoever speaketh a word against the Son of Man, it shall be forgiven him; but whosoever speaketh against the Holy Spirit, it shall not be forgiven him, neither in this age, nor in the age to come" (Matthew 12:31,32).

To "speak a word against the Son of Man" means for a man to deny some truth of doctrine while he still looks to the Word as the source of truth, believing that in it and from it are Divine truths. Necessarily, the manifold truths which the Church draws from its Revelations cannot be equally seen by all men or in all states. There must be freedom to judge whether such doctrines are Divine truths or merely formed from appearances on the surface of Revelation. And so long as truths are not yet implanted by faith into the conscience, or inscribed upon man's life, they come to man with their Divine character veiled, and are what is meant by the Son of Man. Hence the Lord said, "When the Son of Man cometh, shall He find faith on the earth?" (Luke 18:8). "The Foxes have holes, and the birds of the air have nests; but the Son of Man hath not where to lay His head" (Matthew 8:20). Such truth, whether it appear as a Savior or as a Judge, is not yet interiorly received, nor is its inmost connection with religious life recognized. Man is pardoned if he doubts or reasons against it, pardoned if he struggles against it, and resists the demands it makes upon his life. And indeed he may seek to blind himself against its Divine authority and to hide himself from the judgment which the truth might bring about within Him.

We cannot say that such states of obscurity, doubt, and rebellion, are guiltless; for they spring from the refractory will of man. But they can still be forgiven; they can yield and pass away, provided only that man will seek affirmatively for light in the Word.

Not so the sin against the Holy Spirit. This is a denial of the holiness, the Divinity, the inspiration of the Word; a denial which closes heaven to man. Or, it is a denial of the Divinity of the Lord Jesus Christ. It is a denial that the Spirit of God is in the Word, or is in the Lord's Human. And it is unforgivable to Christians; not because the Lord resents this sin more than any other, but because there is no hope for anyone who - in this world or the next - sees yet wittingly denies and rejects these means which the Lord extends for his salvation.

The celestial angels, above all others, have the perception of the utmost necessity of the acknowledgment of the Lord in His Divine Human as the only possible means of salvation. They see that a man's unwillingness to acknowledge God as the source of all human qualities, profanes the name of God and induces a brutal coldness into all the thoughts of his mind, which can then be stirred only by the fires of evil. The celestial sense of the Second Commandment therefore is, not to deny the Divinity of the Lord's Human. For with this denial angelic spheres depart from the interiors of man's mind.

---

Much may be read in the Writings concerning profanation. In its most direful and interior form - which the whole force of Divine Providence seeks to prevent - it is the deliberate mingling of evil affections and falsities of evil with the holy things of good and truth. Those who become such profaners are excluded not only from heaven but from hell, until their minds and spiritual bodies are reduced by a terrible process of vastation into an almost senseless and lifeless state - a living death. And this eventuates, not as a punishment, but because confirmed good and confirmed evil have produced a double yearning in the mind – a belief in truth and in phantasy at once. Such an unbearable state cannot be stamped out or dissolved except by a pulling asunder of the roots of a man's life, and, with this, a carrying away of as much of man's spiritual life as has been profaned (@AC 8882).

It is to prevent such interior profanation that "the Lord admits man interiorly into the truths of wisdom and into goods of love only so far as he can be kept in them to the end of his life" (@DP 232-233). It is because of this that guards are placed about interior truths such as are in the spiritual sense of the Word - and that the letter of the Word consists of parables and appearances. The first responsibility of the man of the Church is therefore to keep the Word holy. For all profanation - in its descending degrees - begins with something of contempt in the externals of our thought. The need of watchfulness lest something holy be degraded or desecrated, is indicated in the Lord's saying "that every idle word that men shall speak, they shall give account thereof in the day of judgment" (Matthew12:36).

It cannot be doubted that this is a warning against the vulgar habit of bursting out in impatient and condemnatory language which hurts the sensibilities of others - as well as against the employment of useless oaths in which the name of God is "taken in vain." But such "idle words" become of the greatest moment the more they are joined with a contempt of the Word and its purpose - which is human salvation - and so far as they spread, as today, into a depraved custom of using names and sayings from the Word as witticisms, some indecorous, some openly profane.

In the New Church there is no need for artificial solemnity, nor for morbid sadness, in the exercise and expression of our religious convictions. There should be no fear of taking the Lord's name upon our lips, no undue anxiety or embarrassment or timidity about introducing the things of the Church and of the Word into our social conversations. Religion belongs to all things of life. Nor should any excessive fear of profanation either prevent us from entering interiorly and rationally into the mysteries of faith, or discourage us from taking part in the worship of the Church "frequently every year receiving the sacrament of the Supper, and performing the other parts of worship according to the ordinances of the Church" (@NJHD 124). If there is sincerity, together with a desire to continue to resist evils, there is not only protection against profanation but also the promise of spiritual progress, and an interior joy in the worship of the Lord.

The Gospel of the Second Advent of the Lord is one of great joy. As long as the children of the bridechamber have the Bridegroom amongst them, they cannot fast. Humiliation before the Lord, reverence of His name, does not imply a condemnation of the wholesome human delights of mind and body, or an abstinence from lighthearted relaxation. Indeed, among the diversions of charity the Doctrine mentions "decorous wit" and harmless humor.

Yet in our whiles of recreation we largely live in our sensual degree; and - since the sensual is at best only in a process of being disciplined and purified - there are apt to be present in such states the play of many corporeal affections which would profane the name of the Lord and the things of the Church if such things are improperly introduced without adequate reflection. To use anything holy in flippant or "frivolous conversation," is therefore proscribed and forbidden to the New Churchman (@TCR 298). And this is done to prevent the sphere of the world's interior contempt for the holy things of the Word from infesting the Church. For habits of speech which may not be deeply profane to many in the world who lack the knowledge of what is holy, would with us become deeply hurtful.

The Writings speak of a law operating within the organic mind of man, called the law of associated ideas. When a name or expression from the Word is made an occasion for laughter or derision, such ideas with their pervert delights attach themselves to that name, and are recalled whenever this is read or called to mind, producing an interior presence of both heaven and hell. And in the other life man will then have lost the use of this holy ultimate as a means of inviting angelic aid (@SE 1304).

The habit of jesting about holy things becomes a wedge which pries open the mind, already swept and furnished by religion, for the entrance of a worse profanation. The name of the Lord is holy. The idea of the Lord, whenever it is suggested in the thought, must be paramount - never subjected to thoughts of trivial sort. When it is brought to bear (as it should) on everyday affairs, it must always dominate. Frivolity in religious matters is a tool of hell for undermining the sanctities of life.

There is no more wasting argument against any cause than laughter. This argument of scorn and derision is usually at war with charity, and is often profane - as when it was visited upon the Lord in the palace of the high priest. It is our part - be we young or old, unworthy disciples of the Lord's new truth - to realize that we cannot always laugh when the world laughs, cannot join in the clever cynicisms that are everywhere directed against the holiest things of life - against the sanctities of spiritual doctrine or against the sanctities of conjugial love; nor treat lightly the sanctity of friendship or imposed trust, even if it may be only a child who so trusts us.

There are many things in the life of every man which must be respected as sacred - sacred because they come from the Lord, and are basic to salvation - the means and conditions by which eternal life is acquired. Chief among these is the freedom of others - which is given from the Lord and is an intrinsic part of His order, a part of His wonderful name. For that which is not ours, belongs in reality to the Lord; and that which is ours only seems to be our own. This widening perception of all things of life as sacred to a Divine purpose, is that which can bring the true wisdom of innocence to men, and which will lead the Church to the fulfilment of its eternal prayer: "Hallowed be Thy name."

<<<

== 3 The Law Concerning The Sabbath

_Remember the Sabbath Day to keep it holy. Six days shalt thou labor and do all thy work; but the seventh day is the Sabbath of the Lord thy God; in it thou shalt not do any work, thou, nor thy son, nor thy daughter, nor thy manservant nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates; for in six days the Lord made heaven and earth, the sea and all that in them is, and rested on the seventh day; wherefore the Lord blessed the Sabbath Day, and hallowed it._ (Exodus 20:8-11)

Man is liable to forget. Throughout one's life, this is one of the most persistent of human weaknesses. A thing has to be impressed upon us many times, regularly, repeatedly, and in varied modes, before it becomes so familiar that we are no more in danger of forgetting it. Repetition is therefore one of the modes of education, whereby the child is trained to remember what may be considered to be the essential things of knowledge and life. And ritual aims to do the same for the man's religious life.

Yet it is easy to forget even what has been repeatedly impressed, if there is no living and active affection to assist and prompt the recollection. We are not so much in danger of forgetting that which we love the most, as that which we do not hold so dear or so necessary. And although people's unequal powers of recollecting come very largely as the gifts of heredity or the fruits of an early cultivation, it is true of all men that it is more natural for them to remember what gives them delight and what interests them the most. Unless we are morbidly inclined, we pass over that which is displeasing to us - we like to forget our whiles of tribulation - we seek to flee from our sorrows and from what seems irksome and irritating and difficult and dangerous. And if our situation seems too desperate, or our responsibilities too great, it is quite in the spirit of human nature, and of the times in which we live, to bury our heads in the sands of forgetfulness and think of something else, to dismiss the serious side of life in a whirl of gay abandon.

The farther mankind drifts away from the Lord and from heavenly spheres, the more difficult become repentance and regeneration, and the longer is the road back to the true religious life - the life of spiritual humility and spiritual honesty; and the more irksome seems the road to salvation - the duty of spiritual life. So, also, it becomes easier then to forget the conditions for the Lord's help, and to say, with so many at this day, "If there is a God and an after-life, we will leave Him to look after us there. If not, what then? Let us not worry; let us forget what we may be hereafter, and ensure that we get along well here on earth!"

This prevalent attitude arises from the fact that the natural man from himself does not love anything except corporeal and material things, or - what the Doctrine classes under the two heads: Self and the World. And what one does not love, one wants to forget. If we look back into the past, we see in every nation two opposing tendencies. One is the irrepressible need for religious comfort, the craving of the soul for some spiritual acknowledgment of God, and the afterlife, and of human duty; and the other is the desire of men to evade the conditions of salvation, and make the demands of religion easier - a desire which comes from the natural man which does not take any delight in spiritual things, and thus gradually wants to substitute some form of magic for religion - or else wants to do away with religion entirely.

The fact that the natural degree of man (with its evil heredity) is pervert as long as it remains the master of our life and we listen to it like Eve hearkened to the subtle serpent in the Garden, shows that it is not natural for us to remember the duties of religion. We are liable to forget, and therefore the Lord in His Word and in the Writings of the Church constantly reminds us of them. Therefore it is that the Lord has instituted His Church, furnished, as it is, with a priesthood whose sole duty it is to maintain and administer "what is Divine" among men, and present the requirements of faith and spiritual life. Therefore - lest we forget - the Third Commandment, which looks to a continual and periodical reminder of the means of salvation, begins with the words, "Remember the Sabbath Day to keep it holy."

In a more limited meaning, this precept from the Lord's mouth refers to the observance of that day of the week which in Christian countries is recognized as a day of rest and a religious holy-day. To the Jews it meant the seventh day, now called Saturday. From Friday sunset to Saturday sunset was the Jewish day of rest, called "Sabbath." But when the Jews, who had utterly departed from the spirit of the Sabbath, added to this by crucifying the Lord Himself on the very eve of the Sabbath, they, in the Lord's sight and in the view of Christians, did so profane the Sabbath that the day of the Lord's Resurrection, or Sunday, was assigned instead, and accepted by Christians as the Sabbath Day worthy to be kept holy, in remembrance of Him.

Sunday therefore became, symbolically, at once the first and the seventh day of the week, the Lord being the First and the Last. It became, the Doctrine shows - and should be observed as -- a day of Divine instruction, of rest from ordinary worldly occupations, of meditation upon salvation and eternal life, and of love toward God and the neighbor (@TCR 301).

The fact of the change has a deep symbolic meaning, in that the Lord, who is inmostly signified by the Sabbath, was made the last in the Ancient and Jewish Churches, but is the first, and thus the beginning, in the Christian Churches. His final glorification progressed during the Jewish Sabbath, and was completed on the Christian Sabbath. But apart from this, it is inessential whether one day or another be declared to be the Sabbath, as long as the day agreed upon on earth as the Sabbath be set apart as the Lord's day, the day of rest, and thus be kept holy. For the holiness does not pertain - as some Christian literalists still believe - to the weekly calendar, but to the sacred use of such a day to us.

We are not merely commanded to remember that the Sabbath Day, thus sanctified and appointed, is holy. But we are given the responsibility to keep it holy. It is holy, that is, it has a holy use and a holy significance, whether we remember it or forget about it; but we are to see to it that we act and think in accordance with its holiness. "The Sabbath is made for man" - for his use, for the sake of his betterment, his reformation, his regeneration into spiritual life. It is necessary to have a time when we can cut ourselves clean away from this world's compelling worries and from the thoughts of natural life, and give an opportunity for our spiritual minds to be set free - that is, when the spiritual states, that are present as we may hope inmostly in all that we do, may without social embarrassments or social interference - come out freely in the conscious externals of the natural mind, and come to rest there, without disturbance from materialistic thought. Providence has ordained that every seventh day should rightly be used for this purpose, in order that spiritual and celestial things may then be impressed upon the natural mind, and the reformation of man's natural mind be facilitated. And there have to be very grave reasons indeed before we could feel justified in changing this Divine order.

The literal observance of the Sabbath is an ultimate, direct command which must not be made "of none effect" by our prudence or our restless desire for worldly diversions and exhilarations. The Church must unite to defend the dignity of the Sabbath, and its use as a holy, orderly ultimate of spiritual life. The Son of Man, who is the Lord of the Sabbath, has a right to this day. And although exaggerated piety has sometimes made the Sabbath Day a burden - and thereby has defeated its purpose and made it unacceptable both to God and to man, yet its proper use must be zealously maintained as one of the gates and bulwarks of heaven among men.

It is true that the literal sense of the Word must not be taken alone; for the letter killeth and it is the spirit which maketh alive. But the spiritual life of man is built upon ultimates of order, ultimates in time and space. Charity is nothing without civil and domestic uses. Conjugial love perishes without the stable institution of marriage. Education must depend on objects: on books, orderly homes, schools. And so religion rests upon the fulcrum of the Sabbath Day.

If these ultimates are broken down; if, because we know that the Lord looks upon the spirit rather than the literal observance, and permits us to pull our sheep out of the pit even on a Sabbath Day; if, then, we begin - by attrition, by small degrees, on pleas of liberality - to break down the sanctity of the Lord's Day, by making rules out of exceptions; a generation will surely come, with us as in the world, to whom this day will mean no more "a day for instruction in Divine things, and thus also a day of rest from labors and of meditation on such things as are of salvation and eternal life, as also a day of love towards the neighbor" (@TCR 301).

In heaven the angels - although they too observe periodic days of rest and Divine instruction - are said to enjoy a perpetual Sabbath (and thus continually to "rest from their labors") because their natural minds are subjected to and correspond with their spiritual minds. In heaven, spiritual thoughts and affection are liberated, once and for all, from the restraints - the self-consciousness, the rebellion, the anxieties - of the natural man. This is what gives existence to angelic blessedness. Even on earth - the Writings say - those who are in a life of love and charity also desire to observe the Sabbath holily, for "nothing is sweeter to [such men] than to worship the Lord, and to glorify Him every day" (@AC 1798[3]). Piety thus is a sign of charity (@Char 8). The inward desire to worship Him is constantly present, and they welcome the opportunity to do so, fully and thus freely, and with both body and mind, when the Sabbath comes. Such truly remember the Sabbath Day to keep it holy.

When the Lord bids us to Remember, it behooves us to study what this injunction may mean! It is necessary for us to go to the Doctrines given for our spiritual welfare, and see what functions of mind are involved in the process.

First of all, there is no memory without learning. We must study the Word and the Doctrine to learn the things that pertain to our peace. Secondly, while our memory is formed from attentively receiving truths into our minds, these would only be stored there, apparently forgotten, useless and inactive, unless by an effort we take time to recollect them and bring them to mind. Only then can we be said to remember. But the evident purpose of the third precept is to prevent our ever forgetting. We must remember again and again perpetually - always remember. This is difficult - and with many it cannot be achieved except by a lifelong process. Children, however well-intentioned as to obeying, have the great weakness of forgetting if not constantly reminded. And the simple good in the "first" or "natural" heaven have also a similar difficulty. They obey - when they remember. Unless they are in the sphere of higher angels they cannot remember; because they are not animated by a spiritual love of their own, they have not a love of good and truth for the sake of good and truth without idea of merit and reward. The third precept aims for a higher state than such a bare salvation - aims to make men masters, not servants - aims to bring men out of the house of bondage and make them free. And thus it prescribes: Remember always.

To "remember" means therefore, to have something perpetually in the thought, so that it rules universally with man even when he is meditating on other things or is engaged in everyday affairs (@AC 8885) or in social diversions.

What has become insinuated into man's will, reigns universally in his thought, and makes up the inmost part of man. What man loves is also caught up frequently into manifest perception. Man ponders on what he loves. He brings it under the searchlight of his reflections. But what he dislikes gravitates from the center toward the circumference - to the sides, where it lies, as it were forgotten. Only such ideas as are associated with delight, and are tied up with man's affections, are recalled to mind!

Truly, how wonderfully is man made! For even in our ability to forget, there is a purpose - a blessing. Things false and evil, with the regenerating man, can thus be put away eventually, through disuse and aversion, even though they still remain indelibly preserved in the substance of his memory. And what is true and good - what is the Lord's with man - can then find room in man's mind, so that his whole spiritual body can thus "become light" with one whose eye is single.

Remember the Sabbath Day! Keep the Sabbath Day, and what it stands for, constantly in the thought; make it one with the love, the will; make it the Inmost of the mind! The Third Commandment goes on to suggest what the Sabbath Day signifies in the light of heaven, and what it should signify to men. It tells that the Lord made heaven and earth, the sea, and all their contents, in six days, and rested from His labors on the seventh; and thus that the seventh should be a day of rest unto the Lord, in which no labor may be done. It was as if this day was a day for reflective enjoyment, rather than for work; a day for the conjunction of the Lord with His finished creation. For the marriage of heaven and earth as symbolized by that early life of man in the paradise of Eden, the garden of worship and innocence, when creation was completed, and while heaven still dwelt on earth and mankind could still discern the Voice of Jehovah walking in the Garden in the cool of the day.

The Sabbath Day therefore, in the internal sense, signifies the Union of the Divine and the Human in the Lord's glorified Person; for this was the Rest, the End and Purpose, of the New Creation in Him; this was the result of the six days of combat and labor of temptation which He underwent on earth. It also signifies the Conjunction of the Lord's Divine Human with the angelic heaven, which that Redemption brought about, and the constant Presence of the Lord in heaven. And because of this, the Sabbath Day also signifies the Marriage of good and truth in man and angel, since good is from the Divine Itself and truth is from the Divine Human revealed to the Church. Wherefore the Lord is present in His Divine Human wherever men suffer good and truth, or charity and faith, to be wedded within them (@AC 10356, 8886). Rest and peace come from such conjunction.

To keep the Sabbath Day holy means to think holily and constantly about these three conjunctions; since "they are the very essentials of the Church," and since they would be profaned or violated if there should enter into the will of man (or into the inmosts of his thought) any sphere of idea or intention which is contrary to charity and faith, or contrary to the Lord's Divine Human.

This is what must be remembered, for without this idea there is no real holiness in our Sabbath observance. And it is therefore stated in the Writings, that this commandment and the next, which stand at the center of the Decalogue, do not begin like the rest with a "Thou shalt not...," but are put as a positive requirement of religious life, because, internally, on them all the rest depend! (@AE 965[2]).

It is not only Sunday observance which is here spoken of, but the positive need of acknowledging the Divinity of the Lord in His Human, and the conjunction of charity and faith; that is, of doing truth as well as believing it. And thus it also emphasizes man's need to ultimate his spiritual thoughts without profaning them or taking the Lord's name in vain. The New Churchman must see to it that the Sabbath Day is not only a time but a state, a state of internal peace and holy faith, which by the Lord's mercy is preserved in the inmosts of the regenerating man's mind. That state must be expressed in the natural mind. It must come forth into reflection, and whenever it does so come forth the labors and anxieties of temptation, doubt, and impatience must be quieted and put aside; our earthly prudence and conceit and disorderly imaginations must yield, and reverence and worship must fill our minds and prepare a place before the Lord.

This is indeed the manner of man's regeneration the way in which the natural and conscious mind is made receptive to the Lord. And such Sabbath-states of worship, instruction, meditation, and charity are sorely necessary, daily and continually, if we shall hope even to maintain the dominance of whatever of celestial love the Lord has implanted in our hearts as remains; and if we are ever to realize the yoke of the Lord as easy and His burden as light.

"Come unto Me," saith the Lord, "and I will give you rest ... unto your souls." The six days of labor and temptation must not engender permanent spheres which shall disturb the peace of our love. The intranquil states which rule before regeneration must gradually yield their sceptre. The restlessness and passion of a sensual world, and the prudence of a solicitous proprium, must not govern our souls, lest violence be perpetrated upon the celestial and spiritual states which are to become our eternal heritage - our eternity of Rest. For by unceasing creation the Lord blesses the Sabbath Day and hallows it. He secretly disposes all the interiors of man's new will or conscience into heavenly order, and gifts it with the influx of the good of love, giving it protection from the hells so that its peace can no longer be violated. And the heavenly promise reads, into this internal peace - which is meant in the celestial sense of the commandment - "will those come who are received into the New Church which the Lord is at this day instituting" (@TCR 303).

<<<

== 4 The Commandment with a Promise

_Honor thy father and thy mother: that thy days may be long upon the land which the Lord thy God giveth thee._ (Exodus 20:12)

"Children, obey your parents in the Lord; for this is right. 'Honor thy father and thy mother.' This is the first commandment which has a promise: 'that it may be well with thee and thou mayest live long on the earth.'" Such is the commentary upon the fourth precept, made by the writer of the Epistle to the Ephesians. It applies the commandment to children, who must be led to a love of what is just and right and good through the promise of rewards. It is right that children should obey and honor their parents; yea, and love them. It is morally right, because parenthood is imposed by the Lord, and is not always felt as a joy, but often as a burden involving continual sacrifices and adjustments; and at best, it is apt to demand pains and heartaches in payment for the bright memories which it bestows.

The blessing which is promised to children through honoring their parents (and also the teachers and masters to whom the parents entrust them) finds its first fulfillment in the happy results of a right education, which is the greatest heritage that anyone can receive. Honor commences in the humble virtues of obedience and courtesy, and it matures into mutual confidence and understanding. Those who respect duly instituted authority and appreciate the wisdom of the older generation, learn to have open and receptive minds, are able to absorb more fully the gifts of skill and learning, and will thus build their lives upon a broad basis of human experience which cannot be upset by the confusions of the day or seduced by shallow fashions. The advance of mankind - the forward movement of knowledge and of the arts of civilization - is secure and wholesome only when it is accompanied by a reverence for those enduring spiritual things which time cannot change.

As the youth ripens, the Fourth Commandment becomes translated into an affirmative attitude towards the laws and principles and institutions which the past has established. If childhood obedience was insincere, adult life may become embittered and rebellious against the order of society; a rebellion which, whether open or suppressed, would tend to destroy the progress and security of his life. It depends largely upon parents and teachers, upon their fitness and wisdom and God-given illustration in their functions, whether there shall be bred among us a generation of rebels and scoffers, a generation of sly cowards and hypocrites, or a generation of real men and women who are inspired with justice and endowed with true judgment and are able to look upon their elders with sincere honor and with a love which understands and approves what they have striven to do. The foundations of all government, all true citizenship, all social order, is thus laid in the home; and there also begins the concept of love to the neighbor which is the theme of the second table of the Decalogue. It is therefore spiritually right to honor our natural parents in so far as those parents bring to their offspring the gifts of heaven - the sphere of the conjugial life, the ideas of the spiritual faith, the sanctities of worship, and the first formulations of a concept of charity in a moral life. For whatever of good, of religion, or of human worth and wisdom, the child receives, albeit in fragmentary and distorted forms, comes first by the hands and lips of their elders.

These are ancient truths, which have always been more or less clearly perceived, and sometimes enforced with severity. And though the promise of earthly rewards is not guaranteed with us as it was with the Jews, as the fruit of obedience, yet the Lord grants natural benefits in proper abundance to the virtuous and the good, if they can be conducive to eternal happiness (@AC 8717[e]). And even natural law aids to bring it about that in a land where parental authority is honored, a people will achieve a deeper patriotism, a greater industry, longer periods of peace, and thus a more stable prosperity and a disciplined progress. Only a generation which venerates and appreciates the good of the past, can be assured of enjoying a fruitful life upon the land of their forebears.

To the Jews and to the Christians, the rewards mentioned in the precept had no distinct application beyond this mortal life. But in the Lord's Second Advent, He reveals the commandments anew, as universal truths which apply in all ages and to all states and degrees, and thus also to the life-conditions of the angels in the heavens. The angels, however, cannot be required to honor their father and mother according to the flesh. It is seldom that men after death are able to dwell together with their earthly kindred. The parents may even dwell among the wicked, in utmost dishonor, and beyond the power of any angel to revere them. This the Lord suggests when He taught that "if any man ... hate not his father and his mother" he cannot be a true disciple (Luke 14:26). Indeed, after death as even here on earth when spiritual issues and grave matters of religious conscience separate, so that the son is "set at variance against his father and the daughter against her mother" (Matthew 10:35) the relationships of the flesh are as it were dissolved. With the angels, they are transformed into purely spiritual kinships. To all those who aspire to think spiritually, the Fourth Commandment must especially point out our obligations within the spiritual framework which is centered and oriented around the Lord as Author of all life, and not about any individual or family, clan, or nation, or race, or human institution. In this sense, the commandment teaches adoration and love of God and loyalty and devotion to the Church.

For the Lord God is our heavenly Father. "Call no man your father upon the earth," is the teaching, "for one is your Father which is in heaven" (Matthew 23:9), "and all ye are brethren." "All ye" - angels and men, adults and offspring - "are brethren." The regenerated man is therefore called "a child of God"; an expression which, if rightly understood, involves the profound truth that man's whole being must be seen to be totally dependent on the Lord who is the eventual source of all his power and life, and this even in the least things of thinking and acting. Nor is it difficult to understand that the Church is our spiritual mother (see Matthew 12:46-50). Not only is the Church again and again described as the Wife or the Bride of the Lord - joined to Him in a holy union of spiritual love and service; but it is the Church which at Baptism receives us into her arms, and throughout childhood and youth feeds our spirits with proper food and clothes our minds with garments of knowledge, to give us spiritual strength for future battles and protection against the wintry climate of the world's life. In our adult age it is the Church which affords us a spiritual home, with comfort and refreshment; and after death, it is into this eternal home that we are to enter interiorly just so far as we have honored our Father and Mother.

By our father is thus to be understood the Lord Jesus Christ, our incarnate God and Savior, who has all power in heaven and in earth; that is, the Lord in His Divine Human. And by Mother is to be understood the Lord's Church, His Bride and Wife; also described as the "Communion of Saints" which is His Church spread over all the world (@TCR 307).

Now let us well understand the fact that a Church might claim to be a spiritual mother even if it be an effete and corrupt religiosity - even if her milk be a poison (@TCR 23[2]) - even if she fails to clothe her children, and has forsaken her Divine Husband for the glamour and flattery of the world and the gratifications of the flesh. "Contend with your mother," said the Lord to the Jews about their unfaithful church, "she is not My wife, neither am I her Husband" (Hosea 2:2, cf. vs. 5).

It is important to know from the Heavenly doctrine, that it is the New Jerusalem, Bride and Wife of the Lamb - "the New Church which the Lord is now instituting, ... and not the former" (or old Christian Church) which is to be the Wife of the Lord and the Mother of our spirits (@TCR 307). It is this New Church which is to be honored and loved as the neighbor in a higher degree even than the country. And if this New Church is honored and loved, if her God-given doctrines are treasured above life itself - above bodily comfort and personal vanity and ambition - and are seen to be good and true, seen to be the law of salvation, it follows of itself that one "loves all in the whole world who acknowledge the Lord and have faith in Him and charity toward the neighbor" (@TCR 416), and that one honors and loves all men according to the way in which they live up to the Divine commandments. And he who thus honors the Church does not love others merely for their person, nor because they are his associates in any particular group; but he loves the welfare and honors and supports the efforts of the Church societies far and near, thrills to every work well done for the Church as a whole, knowing that all this is for the good of the Kingdom of the Lord upon earth. Such a man will see in the scattered efforts of the isolated, struggling societies and individuals of the Church, the kernels of that great Communion of Saints which is internally one with the new heaven; and his love thus extends above to the angels of heaven and below to the uncorrupted remnants of simple and good men on this darkling earth of ours, who from gentile or Christian lands will someday pass into the spiritual world to be there instructed and received into the New Jerusalem and who, as his brethren and sisters, will honor this as their spiritual Mother.

It must be seen that the true love of the Lord as the Heavenly Father, the Provider and Giver of all good, is present in the love of the Kingdom of the Lord, and causes a true love of the neighbor. And the essential within our love of the Church is not a love of persons, but a love of the Truth of revelation. Our Father is thus the Divine Good, and our Mother is the Divine Truth. What could more universally claim our honor? Not only while we are children, but as adults, and if God pleases, as angels to eternity, the fourth precept will shine before us as a holy duty and an eternal condition for that Divine promise, "that thy days may be long upon the land which the Lord thy God giveth thee."

To Israel, this meant the Land of Canaan, ensured to them as a national home as long as they would remain faithful. To the individual Jew, it meant a long life on earth. To the New Churchman, it means eternal enjoyment of a place of use and delight in the Lord's Kingdom of Uses in heaven, a place of use already prepared for on earth, a place perhaps granted in some way here in the work of the organized church on earth, a humble place, in the active support of new uses, a small task perhaps, yet symbolic of the honor which we should render to our spiritual Mother, and of the faithfulness we have in the greater matters of "law, judgment, mercy and faith" (Matthew 23:23); a place prophetic of the land, the lot, the inheritance, which the Lord in His foresight will have selected for us.

---

In the spiritual world, certain wives, in the course of a discussion reported by Swedenborg, made a distinction between honor and love. You can never love where you do not honor, they said in effect, but you can honor where you do not love (@CL 331[2]).

This is indeed true. But it is not loveless honor that is meant in the commandment. In heaven such honor is refused and rejected. In heaven all love one another with a tender love. And when an angel loves, he also honors (@AC 8897). Here on earth a man may see good qualities in others, may recognize genuine virtues and truths in the acts and sayings of others, and yet be moved only with envy, or with that cold admiration which begrudges them a full recognition, but pays the tribute of honor outwardly while inwardly it cultivates suspicion and dislike.

To honor while withholding love may of course be a beginning of something more genuine. Indeed, admiration of what is noble and good and true in another is often the first conscious realization of a true affection; and that is a truer love which begins thus, than the love which arises from a blind personal fondness because of some natural relationship or with a view to selfish advantage and gratification, and which often ignores the real character or the spiritual and thus governing principles of the one who is loved. Real love is founded in honor, in what is honest; and in real honor there is love. What is refused in heaven is an empty honor - from such, for instance, as acclaim the truth of the Church yet inwardly dislike it and the duties it enjoins upon them. Such a state is called a state of cold faith, a faith without charity, or a state of "faith alone," and eventually - if not checked - it will lead away from the truth until there is no longer any honor for the true Father and Mother.

We cannot learn to honor what is good and true, and at the same time embrace and respect the evil and the false. Each of the Divine commandments has an opposite sense; or an application to evil conditions. And so we meet with a group of teachings in the Word like those already quoted. For the Lord said: "I am come to set a man at variance against his father, and the daughter against her mother, and the daughter-in-law against her mother-in-law, and a man's foes shall be they of his own household. He that loveth father or mother more than Me is not worthy of Me; and he that loveth son or daughter more than Me is not worthy of Me" (Matthew 10:35-37). "If any man come to Me and hate not his father and mother and wife and children and brethren and sisters, yea, and his own life also, he cannot be My disciple" (Luke 14:26). When a certain man wanted to follow Jesus but asked first to go and bury his father, the Lord said to him, "Let the dead bury their dead; but go thou and preach the kingdom of God" (Luke 9:60).

By such words the Lord rebuked those natural affections which set themselves against the true service to Father and Mother - against the allegiance to true principles. No compromise can be shown where the issue is a direct conflict between natural affections and spiritual truth. The household of the natural man is what delays man's spiritual regeneration, and thus delays the beginning of man's interior uses to his fellow men. The old states of the proprium must be shaken off - put aside. The call of old and selfish and worldly affections and delights must not be hearkened to. What is of unregenerate life - what is of old habit endeared to us - is apt to ensnare us permanently if we allow ourselves even so much as an affectionate last farewell, or if we, like Lot's wife, in the crises of our life's decisions look back upon states we must shun, We must flee - shun the evil, not linger in the sphere of its temptation, not bury it with a clamor of regrets and excuses and raise monuments to its memory, for all that makes its resurrection the easier - a resurrection and survival, not of the broken habit perhaps, but of the lingering inward lust thereof.

Old states must die in the cleansing of man's spirit, in the freeing of his mind from the bondage of self-centered childhood affections and the inclinations of hereditary evils which hide human misery under a restless search for social well being. And as it is with the individual, so it is with the Church. The old church must not ensnare the New in its web of natural affections; for the message of the Lord is, "Let the dead bury their dead"; "Come out of her, O My people, lest ye be partakers of her sins!" Seemingly cruel words, but having a meaning as merciful as Charity itself. Uncompromising words, but spoken for the salvation of souls, for the prevention of profanation, and for the preservation on earth of spiritual uses and spiritual truth. Hard sayings to the ears of the hesitant, yet needful as is the surgeon's knife and the flail of the thresher, and given lest men should give honor where none is due, while throwing dishonor upon the Father and the Mother of their souls - the Divine good and the Divine unchangeable truth.

In spirit with the interior sense of this commandment, "Honor thy father and thy mother," we may learn to shun the evils of our mortal inheritance and turn to our heavenly Father and Mother for the power to become truer representatives of their functions. For the New Churchman must never forget that he is but the guardian, the appointed trustee, in the work of rearing and caring for the young. The Lord has given this work to parents to do, according to the laws of Providence. The honor due to parents is not theirs to refuse. But the Church is alone the real mother; and it follows from our belief in the New Church as the Wife of the Lamb, that our children have been given to us in order that this Spiritual Mother may feed them, and that we should assist rather than make difficult the transfer of our children's affections to their Heavenly Parents. Only if we do that work wisely can we hope to retain a due measure of our children's affections not only on earth but to eternity, and thus be less unworthy of their honor and their love.

<<<

== 5 The Sanctity Of Life

_Thou shalt not kill._ (Exodus 20:13)

Since the Lord alone gives life, He has the supreme right to say, "Thou shalt not kill."

If we reflect - and we must reflect at times if we are to live aright - it will be seen that since the Lord is omnipotent, there is a sense in which His Commandments - which simply mean His Will - cannot be broken. Inmostly the whole of creation is obedient to God. And so in the case of this fifth precept of the Decalogue, it is true, in the final sense, that man cannot kill - cannot destroy life. Life goes on even if the vessels that receive life be broken. Life goes on in a new form; the power of life expresses itself merely in a different way.

The slaying of certain animals - which constituted a main part of the ritual worship of Israel, and which is to this day permissively used in the search for human food - and the punitive killing of criminals, were not forbidden in the Scriptures (Compare @TCR 32[3]; @AC 1002).

But the commandment "Thou shalt not kill" has a distinct and real application. The Hebrew term here used for 'kill' is 'ratzach', which is exclusively used to designate 'murder' - the destruction of the human form.

Man can destroy the forms of life - can in purpose and endeavor destroy those very forms which the Lord has created into His own image and likeness - can raise his hand to degrade and destroy the human form, which in itself is holy and intended for an immortally living temple of God - intended for the conscious reception of the Divine love and the Divine wisdom.

Man alone can know and love the Lord, and thus consciously receive His life. The human form is the purpose and end of creation, and thus it is this to which the Lord refers when He commands each one of us, "Thou shalt not kill." Thou shalt not take away human life. And since human life is not only the life of the body, but also the life of the natural mind, and the rational mind, and the spiritual mind; and since the mind in its three degrees continues on after death; we may see that the commandment is given, not only for the protection of civil society, not only for the safety of our earthly existence, but also for the needs of eternal life, so that even in heaven, yea, in hell also, does the law against killing hold good.

The civil law of every country forbids murder; and under this law there are also enactions against assault, brutality, and criminal carelessness or negligence, whereby the lives, health, or reasonable wellbeing of the neighbor might be endangered or injured. But the civil law, or civil society, for the sake of its own welfare, is also interested to prevent other injuries to human life. There are laws against libel - against any efforts to kill a man's reputation, to destroy his honor, or to bring evil upon his good name. The Heavenly Doctrine informs us clearly upon this point, stating that "fame and life with many go hand in hand" (@TCR 309). Honor and a good name are "the source of a man's life among his brethren," and without these he might just as well be dead, for he would be judged as an outcast, or live a living death. Before the angels, we are told, a person who "kills" the civil life and thus the civic use of another, "is held to be as guilty as if he had destroyed the bodily life of his brother" (@AE 1012[3]).

Men live in utter dependence on each other in all that has to do with their life in the great human family. Our bodily safety is entrusted to others - is dependant on their skill, their good-will, and their vigilance. Each time we cross a highway or partake of a meal , or enjoy any function of society, we rely on others. And in the sphere of civil life the same holds true: we are all the guardians of the reputation and good name of each other. Our words about our brother, our behavior towards him, may, unconsciously or deliberately, tear down that confidence which is the foundation and prop of every man's usefulness to society as a whole. Use does not exist in the abstract; it is vested in persons. And unless there is an affirmative sphere of support and confidence which guarantees to the man a real freedom, and thus illustration, in the performance of his use, public confidence will be undermined and the use will come to a standstill as far as that person is concerned. His civil use is gone, and sometimes unjustly and regrettably so; and with the use is removed his delight in life and his standing among men.

We may see, then, what a tremendous responsibility the privilege of life among our fellows places upon us. We are the guardians of the reputations of our fellow men; we are in that sense "our brother's keeper"; and whosoever shall say a contemptuous word to his brother shall be in danger of "the council," and even in danger of the "hell of fire" (Matthew 5:22). We are thus warned against negative and destructive criticisms, against useless discussions of men's demerits, except so far as is actually necessary to form the private moral and civic judgments upon which depend our choice of companions for ourselves and our children, and of associates in the uses of life (@SE 4347).

That it is of charity not to judge from the appearance, but to judge righteous judgment, is clear from the Lord's teachings. To appreciate the abilities and endowments and qualities of others is necessary in civil life, and there is even some urgency at times to feel something of contempt for those who are deficient in their functions or business. Such contempt may be mistaken; but even if it is, it may be forgiven, unless it is prompted from the love of self, and unless it leads to self-exaltation and conceit, as it so frequently does. Those who are in charity and self-humiliation may, in the other life, reverse these judgments if they find them wrong. But charity also causes a man to hesitate in making judgments in matters outside his own sphere of illustration, and to realize that where Providence has not clearly set him up as judge, the better rule is to heed the Lord's warning, "Judge not, that ye be not judged." The good name, the usefulness, the civic and social life and happiness of our neighbor are, in Providence, entrusted to us to hold in honor, and to preserve from damage of evil tongue and unconsidered word. To kill means to destroy, partly or wholly. The Jews, in their time, took the commandment to mean that he who killed another was liable to punishment in this world. But the Lord widened the idea. He showed that the anger of hatred is essential murder, and that one who, without cause, or rashly, is angry with his brother, and from confirmed anger acts contemptuously toward him, may expect that this anger will follow him when he becomes a spirit in the other world, and will lead to punishment there, which eventually will be represented by the "hell of fire," i.e., by a consuming hatred which destroys his own life and the possibilities of his eternal blessedness.

The Writings give ample evidence from the spiritual world that in all hatred of the neighbor, and thus in enmity and in anger, and in all evil love, there is the suppressed desire to destroy or kill. The fact that men are bound to each other by so many common needs while they live on earth has the effect of suppressing this desire to kill; but unless a conscience has been formed which can defeat this evil desire and remove the lust to rule and to destroy everything that opposes one's selfish delights, the lust to kill will show itself openly after death, and often as a spiritual insanity, a homicidal mania.

It is known that love brings presence in the other life. From this comes the felicity of heaven. But it is also true that hatred brings a sort of presence: a spirit who has harbored deep hatred of another is obsessed by the thought of his presence, and this in turn awakens the lust to kill. The inner endeavor to harm can no more be suppressed; intentions confirmed and proposed become actual deeds - yet only in phantasy, for the Lord protects His own. If two evil spirits seek to destroy each other, these - not being in the sphere of the Lord's protection - would actually both be in the phantastic combat. Good spirits may be persecuted for a time, but only in their first, unpurified, states.

ANGER is a general affection, which results from a combination of feelings - and this when man feels that there is resistance to his love, the love of his proprium and its delights. When man's love of the world is thwarted, or especially when his love of self is opposed by other men or by a combination of circumstances so that he is deprived of his delights, then there breaks forth as it were a sudden fire from his will into the understanding and, there it bursts into the flame which we call anger. This flame actually strives to consume the truths and goods of the understanding (@AC 9144[2]), making them of no effect, destroying the reason, and so far as it can, overriding prudence itself. The understanding - swamped with such sudden emotion -- cannot retain any real order in its thought. The influx of heavenly light, which is usual in a rational mind, is therefore closed off, and instead the thought is fed entirely from the senses. The fire of hatred fills the mind with falsities of evil, which are like smoke in the imagination, and produce a morbid, lurid light of phantasy which sees all things in "red" - i.e., in a false appearance.

It is well to know what the anger of hatred is, for it must be shunned and controlled and removed if man is ever to enjoy the light of heaven and live in the Lord's kingdom. For anger is from the love of self - from the intolerance which comes from the love of indulging one's desire to rule over others, or of having one's own way in spite of the opposing rights of others. This anger flames out against all who differ, or who limit the man's delight and do not favor him; and it breeds revenge and cruelty. To shun as murder everything of hatred and enmity, or internal envy and grudge, is to obey the spiritual-moral sense of the fifth precept.

It should be clearly seen, however, that the keeping of any law cannot be judged merely from the letter, or from appearance. Since the inward idea of the fifth precept is that human life must be preserved, the civil law prescribes the death of a murderer, and acknowledges the right of self-defense, and the moral right of an army to defend the lives of its civilian population. And on the spiritual plane there is a similar apparent exception. For there is what is called a righteous indignation, which appears, even with the angels, as if it were anger; yet it is but the zeal of love and charity, expressed as a rebuke against what is evil. It is love, kindled to protect itself against a violator; and while a regenerating man is immersed in his proprium during combats of temptation, he therefore becomes indignant against evil and falsity, thinks restlessly, and desires and prays impetuously. But afterwards he (perhaps in a moment) returns into his internal state - into the sphere of regenerate affections - and into a serene, cheerful, happy, and bright state (@AC 5725; @AE 693).

Evil is judged by its inner character - by its spiritual nature. The evil of murder seems to be hatred of the neighbor. But primarily, in its essence, it is hatred against spiritual laws of truth and order and justice and mercy and use. It is against truth and charity that the love of self hurls its forces of blind rebellion. It is against the kingdom and reign of the Lord God Jesus Christ, that the spirit of murder rages. And it spends its force against men because it cannot overthrow the laws of possibility - it cannot destroy God. It was this inner essence of hell and of the devil (the love of self), called "a murderer from the beginning," that had to be exposed when the Jews were led to crucify the Lord; and the same opposition of the spirit of hatred to the Divine Truths of the Lord's glorified Human (now revealed in the New Jerusalem as the Light thereof) is represented in John's vision of a Lamb as if slain standing on the throne of heaven (Revelation 5:6).

The Divine purpose, the Kingdom of the Lord, would be unrealized if the souls of men could be killed and destroyed by evils and by falsities. This would be murder in its fullest sense. The angels have no notion of bodily death; but they understand by murder anything that injures man's spiritual life (@AC 7089). Murder, in the ultimate and final sense, is to take away from a man the faculty of understanding truth and willing good; and the object of hell, and of all its crew, is thus to make man's repentance impossible. They do that by encouraging man's evils, insinuating their own evils and persuading the man that they are his - his forever. They do it by perverting truths into falsities which seem to show that there is no need to continue a life of self-examination and self-control and of shunning evil. They do it, finally, in the latter days of a Church, by appearing to take away from men their spiritual freedom.

This effort of hell is real murder. But it is achieved only with man's consent and desire. It may not appear to be murder when men here on earth inject scandals against some truth of religion, or some means of salvation - when they contrive to create aversion for the things of worship and instruction - and thus by subtle and apparently trivial methods turn men away from God, from religion, and from heaven. But this is the soul of all the hatred and anger and revenge of hell.

And therefore, in the Word of God, the signs of the end of the age when the judgment would come in the spiritual world, include great wars and much slaughter. The prophets and apostles of the Lord would be killed. In fact the Lord said to His disciples, "The time cometh when whosoever killeth you will think that he doeth God service" (John 16:2). When hatred rules, in a mind or in a world, falsity will be accepted and truth persecuted in the name of Religion.

"Prophets" and "apostles" stand for truths of doctrine, which the love of self will minimize, and alter, and finally pervert or reject. Even to the New Church, which is given to serve in the Lord's cause of preserving alive the perceptions of the truth of His teaching through these times of spiritual slaughter when the children of older states are rising against their parents and killing them, there will come temptations to give way to the loves of self and the world. And the spheres of these loves are at all times ready to discourage the worship of the Lord and the study of His revelation, and to obscure our understanding of the goods and truths of the Church, i.e., of its principles and its uses.

When such danger is felt to threaten, let us recall that the Lord alone is the Master of our lives. We, one and all, belong unto Him. From Him is the life that is ever more abundant. Into His hands may we commend our spirits, and need no more fear them that can only kill the body and after that have no more that they can do. For even the whole of hell is in reality impotent. It also must obey the Divine Omnipotence which dictates the law, "Thou shalt not kill." Falsity and evil cannot kill truth or good - cannot lead a soul into spiritual death except he himself so desires. The Lord God Jesus Christ rules, and against His Truth the power of hell shall not prevail.

<<<

== 6 The Law Against Adultery

_Thou shalt not commit adultery_ (Exodus 20:14)

In their outward form, the Ten Commandments are arranged in the order of their sanctity, and thus of their importance. Inwardly, they all cohere with each other; and in the inmost sense they describe man's covenant with the Lord. Still, the last six of the precepts, in which are specified certain acts which we are forbidden to do, have regard to man's duties to his neighbor rather than to his duty toward the Lord. In them it is definitely enjoined on us that we must not kill anyone, for this is to take away the life which the Lord gave him; we must not commit adultery, for adultery is nearly as effective in spoiling a life as is murder; we must not steal a man's possessions, for property-right is at the basis of man's life in society, and to deprive him of what is his is to endanger and diminish his life and to interfere with his uses; neither must we bear false witness, for lying undermines justice, deprives others of their good name, and thus in another way interferes with the life rightfully theirs.

These commandments are all intended to safeguard the neighbor's life. If society is not to perish, a man's body, his life, possessions, and reputation, must be held sacred by his fellows. This is the reason why every country - quite apart from any religious intentions, but for its own self-defense - protects its citizens by laws against homicide, laws regulating marriages, laws against theft, laws against injurious falsehoods.

The New Churchman, in the light of the Word and the Heavenly Doctrine, regards these laws as necessary. They protect earthly society; and society is necessary for usefulness. Society and its uses are provided by the Lord Himself as a means to serve His purpose of leading man to heavenly societies and heavenly uses, and of preparing him for such heavenly community life. For this reason earthly society and its laws must be loved, and upheld, and protected, and if possible made truly effective in becoming true means to spiritual ends, and thus in advancing the kingdom of the Lord in the hearts of men.

Yet earthly society will always reflect the state of the Church in the world. Crimes that obviously endanger the order of society, and impede the freedom of commerce and industry, and many other things which are treasured by the Love of the World can be met, and in some degree subdued, by the prudence of civil government. But when we examine the problems attending such a law as the sixth precept - "Thou shalt not commit adultery" - it becomes obvious that no civil power can effect anything of permanent value except so far as this effort is upheld by the state of religion among its citizens. And even where religion rules, it is relatively easier to follow the ideals of the Church and the dictates of its thought and doctrine, when these coincide with the current opinion of the world. Public crimes, which threaten society with immediate consequences, are generally publicly condemned. But personal evils - such as relate to the relation and mutual attitude of the sexes, and whose consequences are at first private and thus less apparent - are not so popularly condemned. Here, therefore, the battle is more severe. Man has to fight, in silence, an individual battle against his own heart - a battle where his conscience stands out against the laxities and compromises of public opinion, on the one hand, and against the hypocrisies of the Pharisees of today, on the other. This battle is the special battle of the New Church; and the Church will find her true distinctiveness, her reason for existence, and her road of progress, when she learns to discern and shun the evils which the world connives at.

It is constantly borne in upon those who read the Writings of the New Church, that we are living in the age of a consummated church; that the New Church represents only a small remnant, unable as yet to create any dominant state in the world, and that the world as a whole regards marriage as a merely worldly provision for the satisfaction of the normal instincts of man, for the propagation of the race, and for the rearing of the young. The true idea - that marriage is essentially meant as a progressive union of two souls and minds - is today absent from the world's serious thought; even though it may still linger in the daydreams of poets and lovers.

In the Christian World no true idea of conjugial love and of marriage prevails. The old Christian Church is in spiritual adultery; and there is no true marriage of good and truth in it (@AE 1008[2]). The perception of truth in religious matters has largely departed from present day Christianity, and its place has been usurped by false teachings, by a vast spiritual ignorance, and by a creeping agnosticism. And since it is the tendency of falsity to excuse evils and conjoin them to itself, there is scarcely present in the world any internal aversion to adultery, but only an external aversion, which is, in part, blind to the source and nature of adultery and its brood of kindred evils. For the essential character of marriage can be seen only by those who recognized and will that it shall last into eternity, not merely unto the death of the body.

To the New Church the promise has been given that truly conjugial love can and shall be restored. And if the New Church shall ever be truly and permanently established on earth, it must be by its treasuring of that promise. There is no use so great here on earth - no influence so wide, no work so effective - as that which two married partners perform when they live together in truly conjugial love. For the shunning of the love of adultery is the only means of breaking and modifying the evil heredity of the human race, and thus - in each generation - of laying an organic and actual foundation in human flesh and blood for the spiritual advance of mankind, and of handing on to the next generation the inclinations towards spiritual things which the parents - by their battles against evils - have confirmed (@CL 202-204).

We cannot here dwell on the uses of the marriage of conjugial love, on the regenerative effects of the conjugial life, on the educative value of a home which is built up around a love of the Lord, a conjugial love between parents, and thus a love of offspring. Nor can we more than refer to the felicity and delights which only truly conjugial love can give, and the protection against hell which such love guarantees (@AE 999). So important is the knowledge of these things to the New Church of the present and to the world of the future, that an entire volume of revealed doctrine is devoted to the virtual exposition of the Sixth Commandment, under the title of Conjugial Love. Without the inspiration of that God-given work, the New Church could not hope to survive through the temptations of the present world. Without the reverent reading of that work, no young man or woman is adequately equipped either to meet the problems which come to him and to her in the later years of adolescence, or to understand themselves truly, or to ensure for themselves the strength of a pure, clean, manhood or womanhood on which their future happiness will rest. And when they read, in the 49th paragraph of that work, (@CL 49), the glorious promise that "those who from early youth had loved, wished for, and asked of the Lord, a legitimate and lovely companionship with one, and who spurn and reject wandering lusts as an offense to their nostrils," will find, even here on earth, their real mate with whom they shall live in eternal and heavenly union - what ideal could have a more powerful effect on their lives than this Divine promise! and what could keep their ways ever lit up by a more real hope and a more tangible blessedness!

Surely it shall be a fact, and already is a fact, that "those who will be of the New Jerusalem" will shun especially all that savors of adultery, of the love of dominion, of deceit, as deadly evils which close heaven to man (@SE 6053). And the reason why adultery is first mentioned is because the love of adultery is the fundamental love of hell, and the form into which all evils tend, if not in this life, yet in the next; while conjugial love is the fundamental of all good loves - celestial, spiritual, and natural - and the form into which they tend, for the blessedness of men and angels.

This being so, we may see that the commandment, "Thou shalt not commit adultery," does not only forbid the breaking of the marriage vow. The actual infidelity of adultery is the end of a long road, and while comparatively few arrive at that end in this life and thus become guilty in act, yet untold multitudes travel on the road which leads there, and thus are guilty in intention and purpose. This was referred to by the Lord when He said, "Ye have heard that it was said by them of old time, Thou shalt not commit adultery: But I say unto you, that whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart" (Matthew 5:27,28).

The sin of adultery thus includes all obscenity, all impurity of act and speech, and all thought or insinuation which in any way degrades the holy estate of monogamous marriage, which the Lord Himself as Creator has intended and instituted for a seminary of heaven and for the fruition of human life, and as Redeemer has uplifted from the degradations of polygamy and placed before us as a spiritual and eternal means of blessedness and perfection.

The sixth commandment is by no means given only for the married, or only for the adult. To infants it should mean Innocence and Charity. To children it should mean Purity and (in their behavior toward the opposite sex) Courtesy and Obedience, Tenderness and Friendship and Chivalry. To the adolescent youth it must mean an open-minded confidence in his or her parents and thoughtful consideration of their guidance; it must mean responsible self-control in the face of unknown temptations, modesty, and mutual respect between the sexes, and a deepening reverence towards marriage; it must mean the cultivation of a wholesome idealism which leads to an aversion against what is immoral or unhealthy, and to an avoidance of evil companionship. To the young man and the young woman, the sixth commandment means especially the need for a religious ideal in their relations to those of the other sex, whether in their general social life or in their marriage. For only by regeneration can the Lord give them, as their own, the gift of conjugial love and the chaste love of the sex, and only by community of spiritual life can a true marriage be formed - an eternal union of two minds and hearts which are bent upon the same heavenly goal and are able to walk by the same road of spiritual instruction and obedience. Personal loyalty one to another is not sufficient to knit two souls together; there must be a common loyalty to the Truth which is higher than them both.

We may thus trace the growth of conjugial love from the primitive forms which contain it in childhood, which prophesy and prepare for its coming. But no genuine good is from man. Man is born merely corporeal, and by heredity he inclines to evil rather than to good, to hell rather than to heaven, to adultery rather than to true conjugial love. By nature man is a beast, an animal, and it is only by education, by moral and spiritual truths, that he is lifted up into the human state and degree. The love of the sex with man is natural, and thus not very different from that of animals. And it is carefully emphasized in the Heavenly Doctrine, that the "love of the sex" is not the origin of Conjugial Love. Truly human love comes only from the Lord; and it is from Him that it inflows when man is ready to receive it; and man is ready only if he looks to the Lord, shuns evils as sins, and, both in ideals and in practice, determines his love to one of the sex.

It is only by new truth - by spiritual verities about the nature and eternity of marriage - that conjugial love can be restored among men, restored to its proper position of regard, restored as a hope and an ideal, restored as an actual possibility and as a fact in natural life. Among the many protracted struggles which lie before the New Church is the effort to remove - from within its own borders - the veil of embarrassment, which the world's evils and man's self-consciousness have combined to spread around the ideals and the doctrine of true conjugial love. Conjugial love is the center, the focus, of all good loves. The finest and the most loyal and noble and selfless instincts of heaven enter into it. All good men seek for it. God created us for it. It does exist - even now in utmost purity. Yet the sphere of adultery and faithlessness and deceit and insane stupidity from hell is so strong in the world that when marriage is mentioned evil men and evil spirits insinuate the idea of what is unhappy and impure. The New Church must defend itself from this sphere of infestation, in whatever form it comes; for only by constant resistance to such spheres can the basis be laid for a sphere of Innocence within the Church, in which the marvelous and beautiful form of love truly conjugial can unfold itself and grow. 

Innocence means the state of being led willingly by the Lord. And the Lord leads the men of the New Church by the laws of His order, which are the truths of His Heavenly Doctrine. Only by obedience not half-hearted part-obedience, but full and eager consent, evidenced and supported by a research of the laws of Conjugial Love, a study of the Lord's conditions for granting true love - only by such unquestioning obedience is a sphere of innocence established in the church - a sphere from heaven, which, in its essence, is so powerful that the gates of hell shall not prevail against it and evil spirits will flee from it. In this atmosphere of loyalty to the Doctrine, the fulfillment shall come of the promise given, that those (only) will appropriate conjugial love to themselves who will be received by the Lord into the New Church which is the New Jerusalem (@CL 43).

What a great responsibility is thus laid upon every man and woman of the Church to maintain and keep unsullied the sphere of innocence within the communion of the Church - the sphere of a spiritual marriage of faith and charity, of willing obedience to our grand and lofty faith in this love which the Lord can give! It is by a life of faith that the Church becomes the Bride and Wife of the Lamb. From that celestial marriage, and from that alone, comes the marriage of love truly conjugial. It cannot come in any other way than by a faithful observance of the prescribed laws of heaven, which are now also revealed and accommodated to be the laws of the Church.

It is especially to woman that the maintenance of conjugial love is assigned. "Conjugial love depends on the love of the wife" (@DeConj 34). "In every woman conjugial love is implanted from creation" (@CL 409). "The conjugial sphere is received by the female sex"; through this it affects the male sex and "is transferred into the male sex"; and because, as we read, "conjugial love exists solely with the female sex" (@CL 223), it was said to Adam that "a man should cleave to his wife." In fact, the stability of society - which in the last analysis rests upon the institution of marriage and thus upon conjugial love - demands that the very nature of woman should incline to monogamy, to the marriage of one man and one woman. And so Providence has ordained. Woman is the guardian of conjugial love, and has therefore a most sacred role which only the most foolish of women dare trifle with or treat with levity or flippancy. It is hers to inspire conjugial love, and provide a safe future for the next generation.

It may be hers, too, to flaunt her charms, or to permit familiarity of touch - and touch is a sense which is sacred to conjugial love - to do this without the modesty which remembers that her powers, greater than she perhaps knows, are yet only entrusted to her by the Lord the Creator for His good purposes. She may thus destroy her use - may encourage the spheres of evil passion - and realize only too late the truth of the Biblical proverb which says, "Can one take fire in his bosom and one's clothes not be burned? Can one go upon hot coals and one's feet not be burned?" (Proverbs 6:27,28). Herein speaks the wisdom of all the ages. And despite what man may do, and the rational wisdom which he may have for her to love, the woman has the power to set the standards in moral life, and it is for the man to cleave to them, to adapt himself to her ideals to win her favor. This is and has been the immemorial basis of society and the foundation of the home.

The higher virtues of love to God and to fellow-men all cohere within conjugial love; and all have their opposites which cohere within adultery, and which indeed lead to abominable perversions in hell. The most obvious sin within adultery is of course the breaking of the sacred marriage promise, which initiated the conjugial life by an assurance of its continuance beyond the end of life. Without a looking to eternity, conjugial love and conjugial unity can never be achieved. In inward aspect adultery causes other bonds, other covenants, to be broken; heavenly covenants which, when broken, lead to separations far more terrible than that of two human beings from each other, or the breaking up of homes. For by adultery man separates himself from heaven, and from the Lord, and from the goods and truths of the Church. This separation, or rejection of spiritual things, is not a sudden thing. Indeed, the interior rejection of the truths of life often is what paves the way more and more for the loosening of outward bonds, until the conscience against doing evil has been destroyed.

The precept, "Thou shalt not commit adultery," therefore must stand guard before us against the terrible forces - living, insidious forces - of the spiritual world, which invade the minds of men seeking to relax the bonds of conscience and to dissolve the marriage-union between Truth and Obedience, between Wisdom and Love, between Faith and Charity. But the Lord Himself, as far as He is loved, is present within His commands. He is there to guard and to withstand the assaults of temptation. For without His constant presence the Church would be powerless against the subtle infestations of evil. He rules the genii and spirits of hell, and when He has fought the battle and redeemed His Bride at last, there shall be everlasting peace and internal blessedness of life in the New Jerusalem.

<<<

== 7 The Precept Against Theft

_Thou shalt not steal._ (Exodus 20:15)

With the congregation of men into communities and nations there necessarily arises the need for Law, a law which might specify what are to be considered as the orderly and as the disorderly relations among men. For whenever two or more persons come into contact, there may arise either cooperation or conflict between them. Order brings cooperation and freedom and true delight into a community. Disorder brings conflict, compulsions and undelightful fears and anxieties.

The idea underlying all community-life is that of mutual service. The simplest of human communities is that of husband and wife, in which each performs uses to the other and to the Lord's kingdom, each one performing special uses which by Divine providence are clearly assigned to him and to her. And just as each sex is organically and spiritually incapable of performing the uses peculiar to the other sex, so each individual in a community is able to fill some position that he has from preference chosen or for which he has been trained or prepared; and the greater the variety of uses, the greater the perfection of society, or in other words, the greater the specialization, the more perfect can the mutual service be.

It is upon the recognition that each man represents an individual use and thus must be equipped for that use, that the social principle of individual ownership and the right and responsibility of property-holding, rest. Each service a man performs to others - each responsibility which he assumes - makes him the object for service in return. And the return is meant to increase the man's ability and power to serve, and is thus meant to help him extend his usefulness or make it more proficient. The community or the society is itself the judge and valuator of anyone's usefulness. In ages of violence, the use of protection was regarded as the most vital; and so, in ancient times, the physically strong usually became the rulers - and also the greatest property-holders, the men of wealth. What a people values most, will determine what uses will be most richly rewarded, and thus what elements will rule. Seek where the wealth of a people is vested, and you shall find what the people love. Where the treasure is there will the heart be also.

And thus the general state of a people will itself determine the distribution of its wealth and property, whether this be wise or foolish, whether it be just or unjust. And nothing can make for a wise distribution except the knowledge of the degrees of uses and the proper subordination of uses among themselves. And this perception does not come except the people learn wisdom - learn to value that which is of the greatest and deepest use above what is trivial and accessory. We have dwelt upon these general truths because at this day the Divine precept, "Thou shalt not steal," is being universally challenged, and with it the right of individual ownership. It is complained that there is no justice in the distribution of wealth; yet this complaint is often not accompanied by the desire to curb the love of the world which, prodded by selfishness, has produced this state of things.

And while honesty is accepted in civilized business as "the best policy," there is really no interior and thus actual shunning of the evils of theft and dishonesty except among those who see these evils to be sins against God - God, whose providence is in all things and whose laws have "divided to the nations their inheritance" - among those who see that "the earth is the Lord's and the fulness thereof."

The Seventh Commandment, like the rest of the ten precepts, can be kept in appearance even when it is broken in spirit. It may appear to a man that he is really honest if he does not steal, rob or defraud, or act unjustly in his work or dishonestly to employees or creditors. Yet such a man may at the same time internally concede no right to his neighbors to possess what they enjoy, but would from envy deprive them of it provided he could do so by legal and approved means which would not reflect discredit upon him. Such a man may even on moral grounds be averse to any dishonest dealings, realizing that society needs laws and that if he and his are to benefit from the advantages of a peaceful and orderly society (which makes it possible for trade and industry to grow and thus for the love of the world to be satisfied), he must encourage the keeping of the law against thefts and surround it with esteem and respectability and even, through religion, exalt it as a Divine law! Yet that man may be utterly devoid of the spirit of the precept against theft. For to be willing to exalt a law into a precept of religion because this would be of assistance in protecting one's own possessions, is in itself a profane thing, a trading upon the name of religion, an action worthy of the spirits of Babylon in the other world who sought to make religion the stepping stone for their own ambitions. Yet this attitude, so evident in modern life, of patronizing religion and supporting the churches not because of any faith in their teachings, but because of the habits of obedience and submission and orderly life they help to cultivate among the simple, and because of the law-abiding citizens they generally produce - this attitude in itself is hypocritical.

None is purified from the evils of theft unless he shuns them from religion and for the sake of eternal life. For only so is man's mind opened to heaven, and it is through the presence of the spheres of heaven that evils of lust are removed from him. But there is also another reason: so long as it is denied that the Lord alone is the Master and rightful Possessor of all things of heaven and earth, it is impossible to see clearly that the "S.C." [so called](*) "rights" of holding property is not any mere invention of mankind, but that it is a right bestowed upon men by the Lord, for the sake of use, and that Providence is still the administrator. It would be true that if any man had invented that right, another man might lawfully challenge it. For man of himself has no rights, no inherent dignities; what we speak of as "human rights" are really rights pertaining to the uses and functions which we exercise or are learning to exercise. When thefts and misappropriations are shunned as sins against God, an acknowledgment is implied that it is not for man to say "I may" when the Lord commands "Thou shalt not steal"; for unless we so confess the Lord's right to command, we steal the Divine powers that are His.

(*) Editor's interpretation of "S.C."

Frequently it has been brought in as a matter of grave doubt whether a man can, at this day and as society is at present constituted, conduct himself and his business on the high moral level implied in the seventh precept and nonetheless succeed in his use and reap the fruit of his labor. The Lord has not indeed given any guarantee of worldly success along with His invitation to men to love Him and do His commandments. Rather did He say, "If ye were of this world, the world would love his own; but because ye are not of this world, but I have chosen you out of the world, therefore the world hateth you.... In the world ye shall have tribulation; but be of good cheer, I have overcome the world" (John 15:19; 16:33). Still, the tribulation here referred to is really spiritual more than natural. Spiritual opposition means temptation, and life in the world necessarily entails a constant watchfulness lest a love of the world ensnare our very souls through binding our affections to itself, strand by strand. Yet in externals the opposition is not so discernible. And worldly uses - by whatever men they are to be carried out, need for their growth a sphere of outward order and honesty, "just balances, just weights, a just ephah and a just hin."

To judge what is required for the keeping of the precept "Thou shalt not steal," it is necessary to consult the True Christian Religion, where we read as follows: "In the natural sense, by this commandment, is meant, literally, not to steal, rob, or act the pirate in times of peace; and in general, not to take away from anyone his goods secretly or under any pretext. It also extends to all impostures, illegitimate gains, usuries and exactions; and also to fraudulent practices in paying duties and taxes and in discharging debts" (@TCR 317). Workmen, it is further explained, offend against this commandment if they do dishonest work or are unfaithful to duty; merchants, if they misrepresent the quality of their goods or use false measures; officers, if they withhold the wages of their men; and judges, if they are influenced by friendship or by bribes to assist in legalizing frauds.

From this it may be seen how wide the range of theft is. And while it is a dangerous thing to burden the conscience with trivialities if this leads man to forget the main thing of the law, which is the cultivation of charity, of a love for others and a desire to further the welfare of the Lord's kingdom by the faithful performance of the use which is ours, the function or business for whose right performance we must stand directly responsible, yet it is safe to conclude that there are a myriad ways of stealing which do not so directly have to do with our neighbor's possessions.

We can steal by wasting the time of others, steal by a selfish attitude which decreases their advantages in life; we can steal other people's delight in their work or their personal happiness, by constant disapprovals, insinuations and faultfinding; we can steal or destroy a use by defamation or slander or unwarranted accusations. We can steal the dignity from a person's office or use by a distorted sense of humor; or we can ascribe to ourselves the honor which really belongs to our use. We can rob people of their freedom; divert to ourselves the praise which should be theirs; yea, we can squander the future of our children by depriving them of a right education; or gamble away the salvation of our immortal souls which yet belong to the Lord alone. The mention of this latter possibility leads us away from the natural and into the spiritual sense of this precept.

In a spiritual sense, stealing means to deprive others of the truths of their faith, which is done when false and heretical things are taught. Priests, who, for the sake of honor or gain teach what they know or might know to be contrary to the revealed doctrine, are the principal offenders in the matter of such guilt. The priesthood as an office has been entrusted with the grave responsibility of teaching doctrine from the Word and to confirm it according to their illustration, always with a view to lead men into the good of life. Such doctrine is to be taught by teaching ministers duly ordained and set apart, and this partly in order that responsibility for teaching sound doctrine may be fixed, and partly also that illustration with them may be constant through their constant devotion to that work. These provisions are necessary in order that the truths of faith may be preserved in their integrity, unchanged by the hand of man. To modify away or to alter the truth is "to take away from the people the means of their salvation." This is spiritual theft, and is signified in the Lord's saying, "He that entereth not in through the door into the sheepfold, but climbeth up some other way, is a thief and a robber" (John 10:1,10).

But this evil (of teaching falsities which shall eventually permit self-indulgence and thus lead to evil) is not only an alienation of the truths of faith from others; it is also a theft from the Lord Himself. For it means that man claims to himself the power to determine truth, and thus puts human conceit above the truths of Revelation; or else it means that man takes away the truth from the Lord's mouth and ascribes falsity to Him instead.

"Will a man rob God?" asked Malachi the prophet. And, speaking in the name of the Lord, he continued: "Yet ye have robbed Me ... in tithes and offerings." They were unwilling fittingly to support the worship of the Lord. This, according to the law, was really to rob God of His tenth part of the yield. The weekly offering in our worship at this day has also the same important significance of a constant, never-ending, never-absent willingness to acknowledge that all we have is from the Lord, and nothing from ourselves; that we need His help constantly, at all times. To withhold that acknowledgment would - even if from habit or for the sake of appearances, the significant act of bringing offerings was continued - be to rob God, to claim to ourselves and to our prudence or our merit what really was of His Mercy alone. If there were no such confessions in the hearts of the worshippers, the house of God would, among us as with the Jews, be turned into "a den of thieves." And this is true wherever there is an internal rejection of the Lord's help, when He is denied, when His providence is denied, or when men do not trust Him and His leading, but only trust themselves; and also when they think that they can be saved and inherit heaven because of their own merit or righteousness.

All the evils that have been mentioned and many others are involved and are thus interiorly contained within the evil of stealing. The very act of theft, be the stolen object ever so trivial, gives a basis in the natural mind for the influx of all the hells which are in the various evils that have been described. For this reason, and because of this internal connection, stealing leads to deceit and to lying and to all other evils. And while it is true that a man as long as he lives in the world still retains the capacity to repent if he wishes to exert this power; and while we can therefore not accept the proverb "Once a thief, always a thief", yet the Writings of the New Church stress the facility with which the habit of stealing may be confirmed. "When a man has of set purpose committed manifest thefts two or three times, he cannot afterwards desist from them" (i.e., as we suppose, without radical repentance); "for they continually inhere in his thought." "An evil enters into the will by detention in the thoughts" (@AC 6203-6204), and there is brought about an itch, a fever, to possess what others have. The thief "loves one stolen coin more than ten which have been given him" (@DP 296[4]).

The Doctrine thus points to the great need of mastering the evil of theft in early life while it is yet controllable; and they show that if a man shuns the cupidity of gaining wealth dishonestly he can tell himself in his heart's thought that such evil is sinful in the sight of God, and then, "after some brief combats," he will be withdrawn from that evil and led by the Lord into the opposite good, viz., into a love of honesty and an aversion for thefts (@AE 1167). He would then become gifted with charity, and he who is in the life of charity would rather give of his own to his neighbor than to take anything away from him (@AC 1798).

But, on the other hand, if the evil of theft is not arrested, it will "enter more deeply into man than any other evil; because it is conjoined with cunning and deceit, and cunning and deceit insinuate themselves even into the spiritual mind of man" (@DLife 81).

And when we come to consider what the actual effects of thefts are within the mind of the thief, we will realize that all evils and all falsities are spiritual thieves. The Lord, from our childhood on, bestows upon us the means of regeneration. These are goods and truths which affect a man especially in infancy and youth while the mind is yet docile and the proprium with its conceit does not as yet seriously resist. The general truths of religion are thus learnt in childhood and are stored up in the memory. But when man advances to rational age and begins to think for himself, he either affirms the truth that he had - which indicates that he is in good; or else - if he is moved by evil - he denies and rejects it.

If evil states begin to infringe upon man's early knowledge and affirmation of good and truth, the Lord removes these from the memory into the interiors of the natural mind, so that they will not be so accessible nor be liable to be profaned, but be reserved for later times of need when the conceits of adolescence have become somewhat broken up. States of evils may come, and yet man will be able to repent by virtue of those "remains." But if evil states become really aggressive, if evil lusts are given sway, if the mind dwells on evil desires; then these evils will infest and consume the remains of good and truth, or rather, pervert them and invert them, so that evils and falsities come to occupy the interiors which the Lord destined for His own abode. This is done especially where deceit is present. And it causes a spiritual theft, an invasion of the spirit of man, a burglary committed against the treasures of the kingdom of heaven before these have been so confirmed and appropriated by regeneration that "moth and rust" could not corrupt them nor "thieves break through and steal." The result is an alienation of the truths and goods of remains. All evil is therefore a theft by man's self-will and a usurpation by man of that holy place within the natural mind of man which the Lord had reserved for Himself, for His abode, His dwelling place with man. Only if a man acknowledges that place for the Lord's, can the Lord dwell with him and make him pure in heart. By prayer man must therefore open his mind to the Lord; and by repentance he must cleanse the inside of the cup and the platter of his life, that he may not become guilty of the folly of those who find delight in stolen fruit even though it turns into ashes in their mouths, and who glory when they have deceived others, only to find at last that they have cheated only themselves. From this lot may heaven protect us, and lead us early to accept the gift and guidance of His Holy Spirit.

<<<

== 8 False Witness

_Thou shalt not bear false witness against thy neighbor._ (Exodus 20:16)

The commandments of the Decalogue condemn all evils of act, of speech or of thought, and of intention or lust. Within murder, adultery, and theft, is comprised every evil act. Nor is there any perverse lust against which a warning is not given in the last group of precepts: "not to covet" the neighbor's house, or "not to covet" his wife or his possessions. The present commandment, "Thou shalt not bear false witness," which in its specific meaning forbids false accusation, or perjury and legal injustice, is also directed against all kindred evils of speech and thought, thus against lies and falsities of every kind.

The act of lying is more commonly observed among men than are the actual crimes of murder, adultery, and theft; and because it is so familiar it is not regarded as severely as are other evils. Also, a lie is generally an act of speech, and is therefore not so ultimate, not so complete a form of surrender to evil as is an act of the hands, like murder and violence. Nor can a man be so easily convicted of having issued a deliberate falsehood, since he can oft-times be deceived himself.

But the Writings show that the evil of lying is bound up with all other evils, in that it offers a confirmation of those evils. An evil, committed in the heat of passion, might be forgiven. The man may - when he enters into a more rational state - see it for what it is, see its infernal origin, acknowledge his fault, and strive to undo whatever injury is done, repenting humbly in his spirit. But if instead he should begin to hide the evil that he has done, covering it over with falsehoods before others, and stubbornly excusing himself before his own conscience - then the evil becomes really his own, and he becomes guilty in the sight of our Lord and the angels.

Man has a will and an understanding. The evil that he does from the will without consulting his understanding is not so deliberate - not performed "in cold blood" - as when he does it with the consent of his understanding. The conjunction of his evil will with the reasonings, the excuses, and the lies that hide this evil from the rebuke of his own better knowledge, is what finally condemns a man. And the more there is of such a hideous mock-marriage of falsity and evil within his mind, the more difficult becomes any future repentance from the evil so confirmed. For he is then bearing false witness about himself and about the evils which infest his spirit. He has made evil to appear good; has persuaded himself that it was orderly. And what a man has once and for all made himself believe to be allowable, that he continually commits in the secrecy of his own heart. He can in no way be led away from evil so confirmed, unless his eyes should be opened to the monstrous fact that he is living as "the witness of a lie." The evil of lying, which is committed in the understanding of man and thence in his speech, is therefore especially dangerous because it confirms and establishes his evils of intention or act. And because of this its terrible consequence, falsehood must be regarded as an interior evil to be guarded against continually, whatever forms it may take, lest it become habitual and irradicable; an evil which should fill us with aversion because it stands as a barrier between us and that salvation which can only come through repentance and the remission of sins.

Where there is innocence, there is no need for lies. In the sacred story about the infancy of our race it is said that before evil entered into the blessed Garden of Eden, Adam and his wife were both naked, and were not ashamed. Sin was brought into the world by the suggestion of a lie - by the deceit of the Serpent who said, "Yea, hath God said..?" And so, in the life of each child on earth, there comes at some time the consciousness of sin, and with it the desire to hide his fault behind excuses, and, as it were, to clothe himself with fig-leaves to defend his self-respect.

Soon, with the child, (especially if he has been taught to fear more than to love, and if no care has been taken to show that punishments are meant for his protection, and not as a revenge), soon there appears, suddenly, the first denial, the first lie, the first entrenchment of evil. Let no parent neglect to watch for this important change of state, that moment when the cohorts of evil - evils of heredity for which the child is not up to that time responsible - begin, in their invasion, to "dig themselves in," changing the tactics of infantile discipline from one of open warfare into the more drawn and discouraging battle against confirmed evils - evils into which the element of deceit has entered. Wise are the parents who can watchfully ward off this first success of evil and keep the battle in the open. Happy the children who may remain in their Eden without knowing such poison plants as deceit and lying. For deceit consumes the remains of good, eats out the very marrow of childhood, and makes it impossible for the child to walk the way of the celestial, even though he may yet - if the evil is repented of - become saved for a spiritual heaven, by regeneration.

And here - in childhood - it is that the battle against falsehood can be fought most successfully. Yet how universal is not the tragedy of parents who neglect their opportunities! How often do they not themselves resort to convenient lies to escape meeting the questions or states of their children? How often do they not make wild promises or empty threats without any intention of fulfilling them? or permit themselves and their children to exaggerate and boast and thus to distort the truth to the advantage of their own self-importance? This habit of disrespect for truth in trivial matters is bound to undermine the love of truth, which is the saving affection of human life - the fundament on which character is built. And the first intellectual layer of that substructure is the teaching concerning the dignity of the given word - the teaching that one's word is consecrated to truth, and must neither be insincerely given, nor lightly broken. What a shifting, treacherous foundation one's life must have if, from the very beginning, insincerity and guile undermine and weaken one's faith even in oneself - if the consciousness of being guilty of falsehood is inwardly fretting his mind. Inevitably there comes the need of constant dissemblance, and there develops an almost subconscious effort to rear a structure of other lies to cover up those first uttered, until man instinctively begins to believe in some of his own distortions of the truth.

It may appear from what has been said that the duties of parents are difficult. For they cannot always tell the whole truth to their children, nor answer all their clamorous questions in a full way. Yet there is always a right way to answer, and still to preserve the love of truth. This way the Lord Himself used when He spoke to the multitudes in parables. This way parents use when they tell the stories from the early Word about Creation, about Adam and Eve, the Flood, and the Tower of Babel; or when they stimulate the children's eager imaginations by legends and fairy-stories which represent truths in symbolic forms - forms which contain and correspond to internal truths. In that manner, also, are all the secrets of life gradually opened to the young, by answers which - while in themselves mere appearances of truth - yet contain and point to the real spiritual truth. Indeed it is so that we all - simple and wise - must learn to enter into interior truths of wisdom and judgment. They alone can know the real uses of things who have become prepared for using them. 
// this trailing piece appears incomplete:
//But to others in parables.

The obvious and direct meaning of the command, "Thou shalt not answer against thy neighbor the witness of a lie," is that a solemn and deliberate lie is a sin against God and man. So far as it is intentionally deceitful it is a sin, and so far also it is a falsity of evil. If it is unintentional - spoken from ignorance or misapprehension or fear - the falsehood may indeed be in itself a falsity of evil, and might lead others into evil, yet it will not be imputed to the speaker as a sin, but as a falsity of ignorance: "If ye were blind," the Lord said, "ye should have no sin; but now ye say, We see; therefore, your sin remaineth" (John 9:41).

The need is therefore urgent that even though we may regard a thing as likely to be true, we should not persuade others of it unless we are convinced of its truth and usefulness, lest we thereby injure the neighbor's faith in the Lord and the Word, or his faith in his fellow men. We must bear responsibility for what we say, since the honor or safety of others, and even the welfare of our country, may be endangered by our idle words. The Law of Israel therefore contained the commandment, "Thou shalt not go up and down as a talebearer among thy people" (Leviticus 19:16). This injunction, which, interiorly understood, directs us to protect the spiritual good of others, was, in the letter, aimed against the evil of gossip, the circulation of idle and irresponsible opinions about one's acquaintances and friends, such as are pleasant to the man's natural self-love to pass on, since this is a veiled way of belittling others in comparison to oneself - a way whereby small-minded people, with little claim to distinction on account of their own accomplishments, can bolster up their own self-esteem and importance by reflecting on the alleged doings and especially the faults of others.

Even in the Jewish Church the moral import of this commandment was seen. For how can any social effort be brought to fruition if the atmosphere of a community is poisoned by cynicism, suspicion, and mistrust, and if we are inclined to watch for the failings of others? How can frank friendship exist where there is mutual fear that the confidences of intimacy will be abused? Even though gossip be innocent with many - and born of friendly interest - yet it is often used as the highway of slander. It is well for us to reflect on the sentiment of the Apostle James, that the tongue is boastful, "poisonous," and, though little, is "unruly" and "hard to tame"; able to cause vast destruction, even as a small spark can set a world afire, so long as fuel is abundant (James 3). Only where no wood is, does the fire go out (Proverbs 26:20). Falsehood is stopped only when it meets disapproving ears, closed by a Christian charity, which - as Peter promised - "shall cover the multitude of sins" (1 Peter 4:8). "Charity," the Christians were taught by Paul, "suffereth long, and is kind;...thinketh not evil; rejoiceth not in iniquity" (1 Corinthians 13:4,7).

Yet it is a part of charity to give credit where credit is due; and to show a needful appreciation of a good cause by supporting it, and rewarding those who are instrumental in performing it. Beauty and strength and virtue and usefulness are indeed all worthy of praise. But praise - overstepping a subtle boundary - can become flattery. And this - equally with slander - can involve the bearing of false witness. Although it is on the surface the very opposite of slander, wrong flattery may come from a love of self, and stimulates the same love of self in others. Praise becomes flattery, not only when it is deliberately insincere, but also when it is given without a due consideration of the fact that all use and all beauty are from the Lord - and that all praise and honor are His alone.

Thus flattery may become a form of lying. It is the recognized means which deceitful spirits in the other world, as well as deceitful men in this, employ to gain influence over others. Evil spirits praise a man by their tongue, but despise him in their hearts, while they "spread a net for his feet" (Proverbs 29:5). In appearance they praise his virtues; in reality they seek to inflame his self-love, and blind him through his own vanity. Then they can lead him where they will, for he will soon lose the power to discriminate between truth and falsity.

Deceit and insincerity are the soul of every lie. And when a man has succeeded in clothing his deceit with plausibility and piety, he becomes a hypocrite, an actor, a dissembler, pretending to virtues he does not possess. It is a strange fact that hypocrisy can go on developing so secretly in a man that the man himself is not necessarily aware of it, and does not admit himself to be a hypocrite, but is self-deluded to the point of assuming that he is holier than others. This is so because his mind is so full of lying that he cannot and will not examine himself in the light of truth. The Lord therefore told some of the chief priests and elders among the Jews, that the publicans and harlots who repented at John's call "would go into the kingdom of God before them." "Cleanse first the inside of the cup and the platter," He told them, "that the outside of them may be clean also." To clean the inside means to remove deceit and lust, by self-examination and constant repentance.

---

"Every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved" (John 3:20). If we should enter into the spiritual meaning of the eighth precept, we should find that those words of the Lord are the very words of judgment upon the evil after death. Those whose deeds are evil will flee from the truth, will hate the truth, will prefer to live on as if the truth was merely a dream - an unreality. Thus they choose the life of phantasy - the life of hell - the life of their self-love.

In the spiritual world, even those who had loved natural truth on earth, and had perhaps championed high standards of honesty and sincerity in society, might yet be convicted as breakers of the precept "Thou shalt not answer against thy neighbor the witness of a lie". The "witness of a lie" means really a falsity of faith. And the "neighbor," in the spiritual sense, signifies good. By the whole is meant that we must not accuse good of being evil by advancing false doctrines, nor persuade that a truth is a falsity, or vice versa, from purpose, and thus knowingly. Atheism itself can advocate morality and claim to be sincere in its search for natural truth, while it stubbornly closes its eyes to every spiritual truth and every spiritual virtue. Yet heaven comes only from the Lord, and without Him no virtue is genuine. Without Him a virtue is but the conceited gesture of self-love and of inward contempt for the Lord's leading - contempt for the humility that is innocent, for the purity of heart that can see God, and for the poverty of spirit which shall inherit the kingdom of heaven. No lie is more terrible in its devastating effects than the lie of the fool who says in his heart that there is no God. None can do more evil than to spread such falsehoods, about the Lord, about heaven, and about spiritual things - even though this lie be accompanied by a love of natural truth, a love of delving profoundly in facts about material and even supernatural things, and though this poison be sweetened by the most persuasive exhibitions of natural "charity." All falsities of religion have been derived from the self-love of man; and the almost subconscious object in their being formulated and accepted has been to cover over and excuse the weakness and evil of man.

The most powerful influence which a man can exert here on earth is not by his words, but by the approval or disapproval which he shows toward the uses that look to the salvation of men. By one's very sphere or attitude, one either resists or assists those spheres of the hells which seek to establish in the world of human minds the LIE that one's own comfort, one's own natural interests, are more important than the duties of worship and the uses of the Church - or than the self-compulsions needed for regeneration and for a life of conscience and usefulness. The life of the love of self is a lie, a false witness, as surely as are false doctrines.

Yet the Lord, in His Coming, has broken the web of the false witnesses. Falsity can no longer rule in the world of spirits, nor in the Lord's Church on earth. The truth of regeneration has been revealed anew, and the Lord is seen as the Truth, the Way, and the Life. The truth of the Word of the Lord may be seen to be the way to rational life on earth and to everlasting happiness. And it remains for us humbly to pray for courage at each juncture of our lives to face the truth within ourselves, to acknowledge our state, to learn to break the spells of confirming self-delusion, and to shun our evils as sins. Then we shall be nearer heaven. For heaven with its peace can descend into human life only where the mouth may speak with unreserved frankness from a heart that is penitent, humble, sincere and fearless, having nothing to conceal.

<<<

== 9 The Love Of The World

_Thou shalt not covet thy neighbor's house._ (Exodus 20:17)

The Commandments of God were once written upon the hearts of men, and their contents were perceived in living warmth as an expression of love to God and to men. But the human heart now issues a challenge against the laws of God, which it has come to know only as forbidding precepts written on tables of stone.

Yet these precepts have ever been necessary to the well-being of society. They have been incorporated into the statutes of nations, as part of civic law. In the task of maintaining order among its citizens, every government has had to define certain acts as disorderly and forbidden, others as permissible, and some even as compulsory; and to punish those who contravene such laws.

In actual fact, however, justice demands that even the civil and criminal law should recognize the difference between deliberate law-breaking and unintentional, ignorant, or accidental crimes. The law of equity has been called in to modify the letter of the law by taking into consideration the motives and purposes of the transgressor.

It is in this way recognized quite universally, from a common perception, that it is in the motive, the ill-will, that the real crime lies. Yet few will reflect upon this most important truth. It is only too common to find that people consider it quite blameless to harbor hatred and bear grudges and wish evil to others, or to display an irreconcilable and unforgiving spirit, so that one does not actually do any physical harm to the neighbor; the thought - erroneous but common - being that evil will or evil intent will do him no harm. Thus the act alone is made a sin. And this persuasion is confirmed in unthinking minds by such false doctrines as are often taught in Christian lands to the effect that the Ten Commandments are not necessary for salvation, and - at any rate - can only be kept as moral laws (See @DLife 63). Regeneration - such false doctrines proclaim - is a matter of faith and of instant conversion; and God can in an instant wipe away man's sins as from a slate, no matter how full of evil desires the heart is, or how perverse the "old Adam," the natural man, may be.

New doctrines are therefore necessary for mankind's spiritual recovery; and being necessary they have also been furnished by the Lord in the new revelation to that New Church to which He now calls and invites all that have ears to hear. This new doctrine - which is the doctrine received among the angels - teaches that man can be regenerated only if he actually repents, not merely of the evils he has committed by word and deed, but of the evils that lie hidden in his spirit as lusts or evil desires. By repentance is meant acknowledgment of an evil, resistance to it, and discontinuance of it with prayer to the Lord for help. For when man in his natural thought resists and repents of evils, the Lord by Divine power will remove the lusts of evil from the internal man; which is done by His separating man's spirit or mind from the societies of evil spirits which inspire such lusts. The evil that man has longed for and lusted for before repentance indeed still remains organically with man as scars in his mind; but these evil forms become quiescent, and as it were dead, and the Lord - by an irresistible force - keeps the influx of hell away so that it cannot rouse the evil delights into activity.

This essential truth about repentance is taught in every revelation - even in the Law of God to the stiffnecked people of Israel. It there appears in the last two of the ten commandments, which both open with the words, "Thou shalt not covet." Preceding commandments had prohibited certain evil acts against God and against the neighbor; but the last two forbid even the desire for harming the neighbor, or the harboring of feelings of dissatisfaction with one's lot. In order to obey the Divine law and to be regenerated or born anew - not from the will of the flesh, nor from the will of man, but of God - man must receive a new heart and a new spirit, a new love, a new will which does not covet, is not envious, does not long for evil, and is not stirred by evil delights.

The people of Israel did not appreciate this law of regeneration, although even the letter of their Law taught it. Their Prophets however pointed to this internal reform as the very essential in the commandments, more important than burnt offerings and sacrifices. But the spirit of prophecy perished, and when the Lord came into the world, His first work was to restore the inner spirit of the law and religion of Israel, and to urge that - first of all - the inside of the cup and the platter of human life must be purified. In His sermon on the mount He showed that, while the letter of the Law given to them of old time was "Thou shalt not kill" nor "commit adultery," yet the anger of hatred, the lust of enmity, was really murder; the impure lustful desires of the heart were really adultery.

Thou shalt not covet. To covet is to long ardently for something, to yearn - yea, to burn with desire for it. Most frequently it is used, as here, in the sense of unlawful and inordinate desire. "Thou shalt not covet thy neighbor's house" means, "Thou shalt not be envious of thy neighbor, nor desire to be enriched at his expense, or wish for his downfall for the sake of thine own aggrandizement." It may be said to be a more internal form of the seventh commandment, "Thou shalt not steal", and as such it is aimed against the lusts of the love of the world, the love of possessing the goods of others.

But the spiritual meaning of the precept against coveting the neighbor's house has necessarily a wider scope. It does not refer to the merely material possessions which are bound to pass from him at death. Our "neighbor's house" signifies a man's good of charity, and also the internal rewards which rightly should bless such good as our neighbor represents, such use as he performs, such character as he possesses. These must be acknowledged as justly his. We must be content with whatever of mental peace the Lord has bestowed on us - content with the spiritual lot which is to be ours, and utterly trustful in the justice of Providence. We should gradually learn to strive for heaven, not as for a reward, but as for a kingdom of such uses as can only be performed in purity of heart. And because this commandment inculcates a new love, of uses rather than of rewards, of heaven rather than of the world, therefore the Heavenly Doctrine gives us to know that the inward contents of the precept against coveting the neighbor's house specifically is, that one must beware lest the evils springing from the love of the world become of one's will and thus come forth; thus lest they become loved, and, from a longing for them, retained, and so become appropriated to man as a part of his mental make-up, and finally, in course of time, become actual evils (@AE 1021[2]).

This teaching suggests that evils can exist in the mind without being actually man's own. And this is indeed possible. We know from the Doctrine that an infant newly born, despite its innocence, is but a mass of cupidities which are hereditary evils - evil tendencies, evil desires springing mostly from self-love (@DP 83[2]). We also know that because these evils of tendency are in the nature of the offspring from the parents and their forebears - and thus are not harbored there from any deliberate choice - the infant, should it die before maturity, would still be educated in heaven and its salvation would be assured. And we know that, even as with children, so adults are not, after death, punished for their hereditary evils which they received from their parents, but only for the actual evils which they appropriate to themselves from their own consent - consent exercised knowingly of their own free will.

Evils of heredity are seated organically in man's natural mind. And the organics of that plane of man are at birth so perverted that they do not receive heavenly influx, but only infernal. Indeed the whole tendency of man, from heredity, is to act against heaven and against others whenever these at all oppose man's self or hinder his own interests.

Man's native will - the proprial will, which from birth receives the influx of the hells - is so filled with corporeal and sensual passion that if it was let out into man's mind, the mind could not resist it, but would become insane and utterly ungovernable. In His mercy the Lord on this account provides that the native will should only gradually show itself, so that even man himself should not fully know the beast that is within his heart. The will has been "closed off" from man's understanding. Only as man grows up from childhood, and his understanding is filled with knowledge and is awakened by prudence and spiritual reason, one affection of the native will after another is permitted to show itself as a lust. The external heredity is first displayed, then the more internal traits. One by one, the tribes of evil may thus be combatted and driven from his inheritance; or else, one by one, they may conquer him, if he makes alliances with those evils instead of opposing them as sins against God.

And from without, that is, from the world, come constant allurements and temptations, stirring the thoughts and opening the mind to a new influx of some lust from the evil will; or, what is the same, from hell. The evil will of the hereditary proprium is but a dead thing, were it not for the fact that it is an organ moved and controlled from hell. Man cannot always avoid coming into contact with evil. He cannot prevent evil at times from entering his thoughts, and inviting the influx of hell. Indeed it is only so that he can become acquainted with the horror of evil - and come to realize its power - its tyranny, its merciless cruelty and ugliness. It is only so that evil can be recognized for what it is, and that man can learn to judge it, control it, and thus to govern himself; and, by shunning it, be born anew from the Lord, acquiring a new will. Evil is known by the state it induces in the mind.

The Lord was often censured by a certain class of hypocrites who insisted on a puritanical life and who suffered no ordinary people even to speak to them for fear of their pious states being contaminated. When they criticized our Lord for not observing religiously the hollow ceremony of dipping the fingers into water before each meal, He replied, "There is nothing from without a man that entering into him can defile him...because it entereth not into his heart but into the belly...." But "from within out of the heart of man, proceed evil thoughts, adulteries, fornications, murders, thefts, covetousness, wickedness, deceit, lasciviousness, an evil eye, blasphemy, pride, foolishness; all these evil things come from within, and defile a man" (Mark 7:15; 19-23).

The implications within these words become more evident when we know that the mind of man is the real man himself; that it is like a complete spiritual body with organs corresponding to those of the mortal body; and that in the mind, the thought corresponds to the mouth and the alimentary canal. Into the thought enters all the food for the spirit of man. There it is tasted, judged, and digested. Yet normally, only such food as is agreeable to the state of the body is absorbed by the heart's blood and made part of the structures of the bodily tissues; and only such thought as is received with some delight, and by man's free consent, is united with the will and thus made a part of man's spiritual being. Thoughts concerning evil, evil suggestions and imaginations, do not defile a man. Not, that is, so far as they come uninvited - come as spheres of temptation, as wandering spirits seeking rest, as spies seeking out the weakness of man's spiritual defenses. What defiles a man is the heart's consent to evil - the consent which makes the suggestion of evil welcome - the consent which opens the house of the human mind to the imaginations of vainglory and self-importance and to the fantasies which feed unlawful lusts, the consent which unlocks the flood-gates of the will of the proprium for the influx of cupidity.

And now the internal sense of the precept, "Thou shalt not covet thy neighbor's house," tells us that we must beware lest the evils which the love of the world prompts and suggests, become of the will, become no longer hereditary tendencies, but actual evils. Actual evils do not mean merely evils of obvious act. Rather do they mean evil personally sanctioned and appropriated, which transforms the imagination and the deeds of the body into a symbolism, in which the fulfilment of that evil lust is prophetically present in veiled ways, inhibited only by fear from going forth into acts openly rebellious against the laws of charity. We must beware, therefore, lest we consent to the thoughts which our hereditary inclinations would have us entertain as permanent guests.

For what is retained in the thought of man - what is kept active for long, what is not rejected but is accepted with some delight excused and held agreeable - that enters and forms his will. If it is good and true it forms the new regenerate will, but if evil it forms, in man's consciousness, an evil will which is at one with that old evil hereditary will which was, by the Lord's mercy, at first closed off for the sake of man's freedom. Man must beware against thus allowing the love of the world to stretch forth its lusts like tentacles from the old will into the understanding, and there confirming it by the thought. For out of the heart come the evils which defile a man.

But what are the lusts of the love of the world? We generally call them envies, or covetousness. The "love of the world" drives men on relentlessly in its desire for that elusive happiness which the sense of possession is supposed to ensure. It urges for wealth, for comfort, for luxury, for display. It delights in constant acquisition, yet it knows no lasting contentment, no real enjoyment. For the love of the world rules the man with whom it has found a home, and rules the age in which we live. This is what makes it a restless age - for there are no limits to the pursuit of wealth and comforts. As soon as one goal has been reached, envy again raises its eyes to the neighbor's house, and the heart is deprived of its delight in what is its own, and casts about to obtain something new.

Who can recount the indefinite varieties of lusts which proceed from the love of the world? In hell they range from the desire to take the goods of others by force, with the insatiable tortures of envy attending this desire; to the vanity of seeking to substitute the sophistication and conceit of much knowledge and of great intellectual acquisitions for the true wisdom of life which begins with the fear of God and results in lasting happiness.

But over the fevered world, fretful and suffering, there comes descending, to those who may see it, the cooling morning dews of Divine revelation. "Is not the life," it causes us to ask,"more than meat, and the body than raiment?" "Take no thought," it protests, "for your life, what ye shall eat... nor yet for your body, what ye shall put on! ...For your heavenly Father knoweth ye have need of all these things. But seek ye first the kingdom of God and His justice, and all these things shall be added unto you.... What is a man profited, if he shall gain the whole world, and lose his own soul? Take heed and beware of covetousness; for a man's life consisteth not in the abundance of the things which he possesseth" (Matthew 6:25,32,33; 16:26; Luke 12:15).

And in the words of John in his epistle there rings the conviction and peace of one who had followed his Master's precept: "Love not the world, neither the things that are in the world.... For all that is in the world, the lust of the flesh, and the lust of the eyes, and the pride of life, is not of the Father, but is of the world; and the world passeth away, and the lust thereof: but he that doeth the will of God abideth forever" (I John 2:15-17).

The lust of the world is not of the heavenly Father, but is in rebellion against Him. It involves a sin against Him - a denial of His mercy and continual watchful providence. It is really an envy against Him. It contains at bottom a fretting hatred against the Lord the Creator for not making a different universe - a world where we could always be supreme. The lust of worldliness is envy against the Lord's claim upon us for a place in our lives and in our minds and hearts - envy against Him as our supreme Neighbor. The human mind - which is so fearfully and wonderfully made, so curiously wrought - is the house of the Lord. It is built by the Lord as His abode - an abode in which our spirit is but a guest Let us pray that we may ever freely grant Him room, and not covet for ourselves our Neighbor's House.

<<<

== 10 The Love Of Self

_Thou shalt not covet thy neighbor's house; thou shalt not covet thy neighbor's wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor anything that is thy neighbor's._ (Exodus 20:17)

From the literal sense of the Word alone, it is not clearly seen why the verse of our text should be divided into two commandments, and named, as they are in the Writings of the New Church, as the Ninth and Tenth Precepts.(*)

(*) That there were ten commandments in the two tables of the Law given to Moses at Sinai, is clear. And the finality of the number ten is recognized; ten, the number of man's fingers, signifying what is complete. Yet there is no clear Biblical teaching as to how the Law was to be divided into ten precepts.

The consequence was that the traditional Christian division which was generally received up to the time of the Reformers of the 16th century, was changed by Calvin. So anxious was Calvin to emphasize that the Catholic use of images was against the Divine Law, that he separated the first commandment into two, and made a separate precept of the part of the commandment against polytheism and idolatry which says, "Thou shalt not make unto thee a graven image... ."

The English-speaking Protestants have therefore adjusted the numbering and joined the last two commandments (which both treat of envy or lust) into one; and they call it the Tenth - for otherwise there would have been eleven commandments. In the Writings the original numbering is maintained, except in the Apocalypse Explained where the numbering of the fifth and the seventh is reversed. - (HLO)

At first glance, there seems indeed but little difference between the law "not to covet the neighbor's house," and the further injunction "not to covet the neighbor's wife, servants, cattle, and chattels." Both prohibitions are warnings against envy and jealousy, and thus against the spirit of theft. Still, if we look more deeply, we may see that the first warning is against the possession of what is the neighbor's, and the second is against unlawfully ruling what is the neighbor's. One possesses a house, fields, and inanimate things, like wealth or property. But one does not, in the full sense, possess a wife, servants, or even cattle; but these may become subject to some degree of control or rule; and the possibility is here suggested that they may become alienated from the neighbor's control, and become obedient to one's own will. While the Ninth Commandment therefore warned against the envy which comes from a love of the world or the lust of possessing the goods of another, the Tenth Commandment in effect states that we must not will, or be eager, to rule over our neighbor to his detriment (@AE 1021[2]).

Much emphasis is laid in the Heavenly Doctrine upon the fact that all evils come from two roots or springs, and these are the evil Love of the World and the evil Love of Self. Even if man's life were ever so faultless; even if he - like the rich young man of the Gospel story - had conducted himself in entire obedience to the first eight commandments, as to his outward behavior; even if he, as Paul suggested (1 Corinthians 13), spake with the tongues of men and angels, understood all mysteries and all knowledge; even if he bestowed all his goods to feed the poor, and gave his heart's blood for some noble cause; yet would he not have kept the Law of God, yet would he be far from the Kingdom of Heaven, unless he had resisted, when alone with his heart's thoughts, the loves of the world and of self! For these loves are the roots of all evils, and in the shunning of them is found the essence of the whole Law.

Last of all come these two commands in the Decalogue. Last of all are the lusts of evil expelled or subdued. They remain after man has begun repenting of evil works, and indeed are removed only by the Lord Himself from the - internal of man's thought, while man is striving to cleanse the externals of his thought from lustfulness and envy and covetousness - and this only if man realizes that these lusts are unclean in the Lord's sight and are sinful against Him and can be removed only by supplicating Him continually for help (@DP 100 seq.).

The prohibition of harboring the lusts of the love of self is placed at the close of the Decalogue for the special reason that it discloses the very purpose - the end-in-view - of the Law, as well as laying bare the real character of evil.

The lust of the love of the world is an envy or desire for external things - which makes the mind more and more external, less and less concerned about internal things. It generally does not lead to such deep infractions against the neighbor's life, as does the love of self. Worldliness desires the neighbor's house. But the love of self tends to go further: it desires to control internal things - all things within the house! The end-in-view of evil is to rule, to control others, to make others into the slaves and tools of one's own pleasure, or at least to make others unable to oppose the gratification of one's whims or ambitions. In all evil desires, when they are examined, this love of rule will at last be seen as the final objective.

And the end-in-view of the Divine Law of the Decalogue is just the opposite to this: the Lord's Law aims to provide freedom - the true freedom of charity and mutual uses, the state of heavenly community life, in which all envy and desire to prevail over others is absent; where all are content with their lot and respect the freedom of each one's use, finding their delight rather in seeing others happy than in having their own way.

Here, in the last commandment, we therefore find brought into contrast the essence of good and that of evil; or, what is the same, true love and false love.

No word has been so much abused as the word LOVE; nor so much misunderstood. That misunderstanding strikes at the very roots of human happiness. Its tragic reflections are seen in the many disillusionments of life - friendships that fail, marriages that go to wreck, associations that are found to have no soul. But the wisdom of life - at this day - is at its low ebb. It is lost, and has to be learnt anew; because it is thought that "to love one's own in another" is love! And the heavenly teaching is therefore now given: that love is to feel the delight of another as delight in one's self (@DLW 47); or to be happy when others are happy. So often it is said that someone loves another when this other person pleases him - as that a man loves a maid when he likes her beauty and grace of mind and body, and enjoys her conversation, her cheerfulness and industry and modesty, so that he desires her for his own and feels utter undelight away from her. Such love does not seem evil; certainly it does not seem to divide. For he feels his joy in her! Yet there may be no love there - nothing but self-love. He might be utterly incapable of taking any delight in what he thinks might be delightful and good to her. He may care only about his own happiness; and his love, which at first may seem to conjoin them, will then eventually so divide them as to be turned to hatred at the first signs of opposition. For in self-love there burns interiorly only the desire to rule, to control, to turn all things and all men to its own use; while true love - which is love of others and service to others from love to the Lord and for the sake of cooperating with the Divine ends of creation - wishes not to compel, since there is no conjunction of love except in freedom.

The last of the commandments, in its internal sense, bids us beware of the evils of the love of self; and especially, since every man from birth is selfish and lustful, it warns us against permitting the love of self to become the ruling love in us. It begins to rule us if the lusts of that evil become confirmed in our mind - if we neglect to recognize them for what they are but instead permit them to be excused, condoned, and indulged, and taken to our heart.

The Writings describe certain danger-signs for which we must watch. The first is the habit of immersing one's thoughts in self, or into the proprium - reflecting on one's own power, wishing for ambitious things, regarding our own welfare as very important, disregarding others and feeling contempt for them, being unjust when one's own interests are at stake, and generally filling the imagination with evil delights, with sensual pleasures, and with enmity toward others. And the remedy is said to be to shun these thoughts of self and self-glory, and instead to think of others, of their rights, their wishes, their good.

These, like other evils, are not seen while they are active. When a man immerses his thought in the body, or in the allurements and appearances of the senses, he becomes blind to the difference between evil and good. The thought must therefore be trained to lift itself above self, to be elevated from the natural mind into the spiritual light of heaven which streams forth from the truths of Divine Revelation - from the Lord as the Spiritual Sun. This is the opening of the spiritual mind.

Yet we are given another important indication as to how we may avoid appropriating the lusts of evil loves when they come to our apprehension:

It appears that Swedenborg, already in the year 1749 (eight years before the Last Judgment), was observing how the spirit-world, increasingly congested with evil spirits, was becoming worse and worse, and how it turned all the influences of heaven into evil, instead of transmitting them unperverted to mankind on earth. Certain spirits then blamed their evils upon the general ruling state of evil, saying in effect, "How can we be good if the rest are evil?" and adding that since everything is from influx, men would not be in fault for the evil they do on earth. Swedenborg was then inspired to reply to their reasoning, that evils active in the world of spirits and thus inspired into men's minds were appropriated to men because men were persuaded that the evils were self-originated in themselves, and took full responsibility for them; and thus became guilty of them, whether they actually carried out the evil suggestions or merely consented to them in their minds. If, on the other hand, men would only believe, as the matter really is, that evils, lusts of concupiscence of every sort, do not originate from themselves but are inspired from hell, they would not become guilty of those evils; they would oppose them, shun them, refuse to harbor them; they would not identify them with their own desires, not take pride in them; but would cultivate aversion for them, and finally disown them utterly.

The lusts of the love of self - which, as one grows up, begin to crop out from our hereditary nature - are so various and so numerous that they can scarcely be catalogued. In general, they are all the longings and seethings of man's selfish heart. And the corresponding imaginations of the mind display their quality. They are turbulent affections; impatient, or cunningly patient, as the case may be; and they are all suggestively included in the tenth precept - "Thou shalt not covet thy neighbor's wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor anything that is thy neighbor's." That the love of self always seeks to transgress upon the rights of the neighbor, may not be so evident when we think of the many ways in which it seeks to fulfill its secret passions. Gluttony and drunkenness and dissipation may be the symptoms of disease. Yet they have a spiritual origin and serve as the ultimate and sensual outlets of the lusts of self-love, and tempt a man to ask, What harm is he doing anyone? or, Whom does it concern whether he abuses his body or not, should he so want? The answer to that question is far-reaching.

No evil can be done by a man, in secret or openly which has not the widest consequences, and which is not a definite transgression, both against the Lord and against the human society and race of which the transgressor is a member. "He that is not with Me is against Me," said the Lord, "and, he that gathereth not with Me, scattereth" (Luke 11:23). We cannot declare ourselves neutral in any fight between spiritual right and wrong. We cannot detach ourselves from the needs of those about us - from the duties that must be done - from the obligations of our position in life. And the reason why even those indulgences of self-love which do not so apparently interfere with the happiness of the neighbor must yet be regarded as destructive both naturally and spiritually, and thus as of immense negative influence - is seen from the statement of our Doctrine that "Man is not born for the sake of himself, but for the sake of others, that is, that he may not live for himself alone, but for others (@TCR 406).

The love of self displays its potency for evil in manifold ways. With the politician, the officer, or the ruler, it takes the form of a love of worldly dominion which drugs itself with a sense of power and self-importance, and is unsatisfied as long as its tyranny is opposed. Whether it persuades by the sword or by material wealth or by fear or ignorance or by an appeal to the gain and self-interest of other men, it imposes its own order under the pretext of expediency. It is contemptuous of weakness, pitiless and blind to human misery. It rushes on insanely, heedless that it leaves the world in ruins. It reckons with no borders, no treaties, no principles of equity. And its spirit is the same whether its domain is confined within four walls or extended over a continent, whether it exercises its control openly or by subtle and hidden methods, and whether it is successful or whether it must remain only as smoldering passion.

But the love of self is not content to rule the world. It seeks to enslave the minds of men, by falsities both natural and spiritual. In this form it pervades the fields of learning, and invades even the churches where it shows itself as a lust for power over souls.

Indeed, the love of self surpasses all other loves in its ability to adulterate goods and to falsify truths. Where the love of self prevails, there the spiritual truths of the church are endangered and liable to perversion. Whatever "self" does or thinks seems right in the eyes of self-love. We therefore find that "self" will even pervert the doctrines of religion and will impose a spurious conscience, so that it may rule not only by outward force but by subjecting men to inner restraints in the name of religion. This is the worst of all Loves of Dominion, and is profane. This is Babylon the Great, Mother of Abominations.

---

Yet in the heart of every man before regeneration there is a secret delight, a quickening of the pulse, at the thought of subjecting others to one's authority. And this unregenerate ambition takes the form of persuading others. To lead others to good by reason and by appealing to their love of truth, or to exercise the command that is a legitimate function of one's work or office - this does not violate the freedom of others or trespass upon their rights. But to persuade, and to lead a man by his sensual or evil affections, or by arousing merely natural emotions, is quite another. This is to "covet" the household of the neighbor's mind.

In the spiritual sense, a neighbor's "wife" represents his truth. His "manservant" and "maidservant" signify his affections of spiritual truth and good; "ox" and "ass" signify his affections of natural good and of natural truth. To desire to control these things in another is to take away his spiritual life (@AC 8912).

The spiritual household of another can be controlled and ruled over through various forms of persuasion. Fear, flattery, emotional stimulus, or other inducements, can be used by evil men and evil spirits to enslave the mind of another and to compel him to think as they insinuate. In the spiritual world there exudes from certain evil spirits a persuasive sphere which entirely takes away the power of thought and the understanding of truth, and induces a stupor in the mind (@AR 428). Such persuasion is seldom possible on earth; but still the love of dominion - even here - urges men continually to persuade others and to make them surrender their own free will, their own reason, their own initiative, and their own delight of being in free choice and in free cooperation with the Lord. To shun the lusts of the love of self means therefore that we should not begrudge the fullest freedom of thought and will to the neighbor, and do nothing which will cause him to surrender to us the rational life of his mind. It means that we should preserve in the neighbor that precious appearance that he lives as if from himself, for upon this all his delight of life and of use rests.

In such freedom alone can men fulfill the ends of creation and the purpose of love which is present within every one of the stern commandments of the two tables.

Unless this spiritual responsibility is assumed by the regenerating man, there cannot be a kingdom of God upon earth. For the Lord cannot reign where men seek to rule over each other's minds and spirits. Inmostly hidden in the evil of envy there frets the desire to displace the government of the Lord; to deny that He is Love Itself and Wisdom Itself, that the Word is holy and that through it He grants conjunction and peace and protection from hell, that He is our Father, and that the New Jerusalem which He is now establishing is our Mother. Such envy, in its inward, diabolical form, is rashly angry against the Lord; it adulterates the goods of the Word, and, through human distrust, steals the Divine power and sole merit, and finally banishes truth itself from the Church.

The evils of coveting are, therefore, sins against God. He who shuns them as such, as from himself, shuns inwardly all the evils mentioned in the Decalogue. And the celestial covenant which the ten precepts are given to protect, will then be inscribed upon his spirit, and stored there within the curtains of his mind, as in an Ark of gold. And God Himself shall dwell with him, and be his God. 
