= Essays on The Lord's Prayer
By Hugo Lj. Odhner   1972
include::../template-attributes.adoc[]

General Church Publication Committee + 
Bryn Athyn, Pa. + 
1972

////
CONTENTS

Preface + 
The Lord's Prayer according to Matthew 6:9-13; Luke 11:2-4 + 
1. The Meaning of Prayer + 
2. Our Father + 
3. Hallowed be Thy Name + 
4. Thy Kingdom Come + 
5. Thy Will be Done + 
6. Our Daily Bread + 
7. Forgiveness + 
8. Temptation + 
9. Deliverance + 
10. The Kingdom, Power, and the Glory
////

PREFACE

This little volume is prepared for private reading or for use in public worship.

The subject of the Lord's Prayer is not treated of consecutively in any one place in the Writings, but is often referred to in whole or in part, as is made clear in the Potts' Swedenborg Concordance under the heading "Lord's Prayer."

The outstanding importance of the Lord's prayer is shown in statements such as these: "There are more things in the contents of that prayer than the universal heaven is capable of comprehending" (@AC 6619).

"Prayer, regarded in itself, is speech with God. If a man prays from love and faith, and concerning heavenly and spiritual things only, then there arises in the prayer something like a revelation which shows itself in his affection as hope, consolation and something of internal joy" (@AC 2535).

And certain angels stated, "We in heaven read that prayer daily" (@TCR 113[6]).

For the sake of completeness a copy of the two versions of the Lord's Prayer is appended on following pages.

And in order to facilitate the use of these Scripture passages in worship, a selection of lessons from the threefold Word is also provided.

I am indebted to Lennart Alfelt for preparing the manuscript for the press.

Hugo Lj. Odhner Bryn Athyn, Pennsylvania April 1972

<<<

== The Lord's Prayer

Our Father, who art in the heavens, hallowed be Thy name. Thy kingdom come. Thy will be done, as in heaven so upon the earth. Give us this day our daily bread. And forgive us our debts, as we also forgive our debtors. And lead us not into temptation, but deliver us from evil. For Thine is the kingdom, and the power, and the glory, forever. Amen. (Matthew 6:9-13)

And it came to pass, that, as he was praying in a certain place, when he ceased, one of his disciples said unto him, Lord, teach us to pray, as John also taught his disciples. + 
And he said unto them, When ye pray, say, + 
Our Father who art in the heavens, Hallowed be thy name. Thy kingdom come. Thy will be done, as in heaven, so in earth.
Give us day by day our daily bread.
And forgive us our sins; for we also forgive every one that is indebted to us. And lead us not into temptation; but deliver us from evil. (Luke 11:1-4)

Selected Reading For Services

1 Luke 11:1 Psalms 102 Luke 11:1-13 @AE 815[10] (part) + 
2 Luke 11:2 Isaiah 64 Matthew 6:1-21 @AC 8705[4,5] (part) + 
3 Luke 11:2 Psalms 99:1-3 Mark 9:33-50 @DP 230,231 + 
4 Luke 11:2 Daniel 7:1-3,9-28 John 18:33-19:4 @AE 726[2] + 
5 Luke 11:2 Deuteronomy 11:18-29 Matthew 26:36-46 @AC 2447[2,3] + 
6 Matthew 6:11 Psalms 78:1-4,12-25 John 6:1-14 @AC 8478, 8480 (parts) + 
7 Matthew 6:12 Genesis 45:1-15 Matthew 18:21-35 @AC 3014[3,4] + 
8 Luke 11:4 Isaiah 45:1-19 Matthew 10:24-39 @AC 6324-6325 + 
9 Luke 11:4 Psalm 44 Matthew 11:11-30 @AE 1164 [2,3] + 
10 Matthew 6:13 Revelation 5 Matthew 6:1, 5-15 @AE 726[1]

<<<

== The Meaning Of Prayer

Lord, teach us to pray, as John also taught his disciples. Luke 11:1.

Deeply concealed within each human heart there is a fear of the unknown. When man is confronted by danger or death, or stands defenseless before the raging elements, the chill hands of fear grip him. His skill and prudence have proved of no avail, and he bows before the inevitable. He attempts no longer to oppose the wave or turn the path of the thunderbolt. But he prays - seeks to approach the wielder of those terrible powers which he cannot resist, the creator of the circumstances which seem to overwhelm him.

Prayer is in a manner, a natural law of all life, an instinctive act of self-preservation. In this man differs but little from the beast of the forest, wounded in the chase. Prayer is the clamoring of our heart for the necessities which alone will satisfy and protect our life's love. Each natural instinct within us, each appetite, each hunger, is voiced in its own language, whether in the infant's cry or in the carefully worded arguments of the adult.

There is no need for the Lord in His Word to command men to pray; for life bears in itself a spontaneous prayer. Yet it is to the Lord and to His teachings that the disciple must turn, that he may learn how to pray aright. For the prayers which pour forth unceasingly from the yearnings of our animal nature, are not the prayers which the Lord enjoins upon us. Our Father - who is in secret - knows that we have need of food and drink and clothing and safety. He feeds the fowls of the air and clothes the lilies of the field. What man must learn from the Lord is how to pray for those things which the selfish heart does not so ardently desire.

The beasts of the field do not need to learn to pray. They are led by their instinct into the fulness of their powers in a transient and brief existence. But man has been given dominion over all the lower creation. To him it is given to control his own life and destiny and to balance the various affections of his earthly nature so that they may serve to produce a variety of forms and uses, capable of lending perfection to eternal life. His office is spiritual rather than natural, and his truest and noblest achievements come by cultivation and free choice. He is made rational by self-discipline and thus becomes independent of the appetites of his mortal body. Every rational man feels within him a thirst for knowledge and truth, a hunger for something of justice and mercy; and for these he strives and labors and supplicates.

But all do not realize that the prayers of man's spirit must not be self-taught, but taught him by the Lord; that the prayer of our life must be Divinely sanctioned, if it is to be answered; that we must pray the Lord's own Prayer! But this He teaches to none other than those who approach Him and say with the disciple, "Lord, teach us to pray, even as John also taught his disciples."

At the time of the Lord's advent, the air of earth was ringing with prayers; prayers of grasping Jews and superstitious gentiles, prayers to national deities, to spirits of dead heroes and to living men, or to abominable idols whose worship required the blood of children and the dishonor of women. At Jerusalem, long petitions were offered by men whose piety was but a cloak for their lust of power; while the pagan temples were filled with incantations which threw a spell over the minds of the simple and bound them under the dark powers of hell.

And therefore the first instruction which the Lord gave had to be of a negative character. "When thou prayest," He said, "thou shalt not be as the hypocrites are; for they love to pray standing in the synagogues and in the corners of the streets that they may be seen of men. Verily I say unto you, they have their reward. But when ye pray, use not vain repetitions, as the heathen do; for they think that they shall be heard for their much speaking." (Matthew 6:5,7)

These things were said to remove the deep-seated evils and falsities which pervert the use of prayer into a ritual of self-approbation, a superficial lip-worship. And in His second advent, the Lord sounds anew these warnings against a pharisaism which tends to lead men into imaginary heavens. The Writings inveigh against hypocrisy so strongly that the people of the New Church have learned to turn away with repugnance from any externals of worship which seem to savor of what is not genuine; sometimes forgetting that the Lord does not only condemn the false external but also teaches concerning an external which is new and true - concerning the need of new garments for new states, of new bottles for new wine. Thus it is stated in the Heavenly Doctrine that genuine piety is both acceptable to the Lord, and valuable to man, and that it consists, in part, "in devoting much time to prayer, and in behaving with becoming humility during that time." (@NJHD 124,128).

It is well known in the Church that Charity (or love to the neighbor from a love to the Lord) has regard to looking to the Lord and shunning evils as sins, while acting from justice and with judgment, and doing the goods of use that belong to one's calling. The degree to which these inner determinations of mind are present or absent decide the quality of man's spirit. But his spirit cannot be formed except on the basis of the corresponding externals, for the decisions of his life while prompted by an inner rational freedom and a choice of internal attitudes are concerned with the selection of fitting thoughts and fitting acts. It is in these observable external that the quality of the internal man is manifested and finds its sincerest expression (@NJHD 173-183).

It is therefore of importance to note that while Charity itself is in the internal man, "all things of worship are externals of the body and externals of the mind" (@Char 173). In worship, mind and body are both employed to express that essence of all charity - that all good and all truth which man receives through others and does and speaks before others - is from the Lord alone. The mind falls therefore into a state of conscious humiliation, a mood of confession and tender gratitude, a desire to meditate and reflect on spiritual things, an aversion from the evils and the self-seeking which infest it. The Writings therefore point out that "to glorify God is not a use, but is a recreation" (@Dmin 4773). There is something of spiritual peace which allows the mind to assume an external state that conforms to the inmost affections and aspirations of the spirit. The externals of the mind which habitually cohere and make one with the externals of the body, thus fall into a form conducive to worship. And this is aided by the very postures and actions of the body in so far as these express the mood of the mind.

Prayer, whether silent or spoken, whether private or public, is one of these expressions of man's inner love and inner faith. Even though we may worship in public, seeking common illustration and common strength, our prayers are addressed to "our Father who seest in secret" -- as if we had entered our closet and shut the door on the world and the world's opinions. And this prayer should not be a merely emotional thing with us, but an act of rational faith. Neither should a false shame of piety - instilled by pride or by indifference - lead us into a spiritual cowardice.

When we kneel down to pray we seek an audience with God. Prayer - in itself considered - is speech with the Lord. It is not our lips that speak; it is our affections. If our affections cling to self and to worldly objectives, our prayer cannot rise above their level, whatever words we use. For the affections cry with a louder voice, confirming the sense of our words or annuling them, or even contorting them into an utterly different meaning. If man is in a life of charity his prayer will be before the Lord continually.

The Lord heareth prayer. He is present with every man; yet not with the evil in their evils. Therefore He has said, "Whatsoever ye shall ask in My name, believing, this shall ye receive." To ask "in His name" is to ask for that which is in accordance with His Divine order. A prayer which accords with the laws of Providence will be heard. This we are promised; nothing more. We cannot, by our urging, alter the laws of order or direct the wisdom of God. But so far as we learn these spiritual laws and learn to love them, so far we have learnt to pray. The fervent and effectual prayer comes forth when we so dispose our minds as to surrender our soul into the keeping of the Lord's government, that the pride born of our ignorance may be broken, and we can acknowledge in charity of thought that the Lord alone can and will reveal what is good for us and for others.

Truly the Lord answers every sincere prayer - even if it proceeds from ignorance or is tainted by human folly. But His answer is according to His own perfect wisdom, not according to our fragmentary knowledge and dull foresight. He cannot bring into realization our untamed imaginations. He cannot attend to man's impatient desire to be saved from the very effort of regeneration; cannot save us from the pain that comes with the birth-struggle of the new man that must be born within us. He seldom hearkens to the prayers of those who would be led out of temptation prematurely - for He will not act in favor of a supplicant and against the very end-in-view, which is salvation (@AC 8179). If He complied with the wishes of vain hearts, hatred and malice would rule where He now governs from justice and mercy, and the very substance of the earth would pass away into dissolution.

But upon prayers that spring from innocence and from wisdom, the Lord adds His blessing. "If from love and faith man prays for celestial and spiritual things, there is given to him something like a revelation - which is felt as hope, as consolation, or internal joy."
The doctrine likens this to a revelation. It is sensed as hope and inmost joy; but it contains more than man can sense. It is a revelation to man's spiritual mind for it effects a certain "opening of man's interior toward God," and thence an influx into the perception or thought which gives an inner sense of the essence of the subject of the prayer (@AC 2535). This assurance man can have if he "asks for nothing but that which contributes to the Lord's kingdom and to himself for salvation." For an angel of heaven it would be impossible to ask for anything else; and if he did, he could have no faith that he would receive it. (@AE 815[10])

When man thus prays, his mind grasps but the surface import of what he asks of the Lord. He begs forgiveness for his sins, appeals for guidance and protection, for strength to resist his evils; he implores for victory in temptations, and asks for gifts of enlightenment, intelligence, wisdom, charity. He supplicates for the speedy establishment of the Lord's kingdom. But to him who prays, all these things have only a vague and general meaning. How these petitions may be fulfilled is not clearly seen in his conscious thought. Yet as he prays there is a stirring of a profound affection in the hidden interiors of his mind. His spirit is affected from within with an ineffable vision of the heavenly modes whereby his prayer might be answered: ineffable things of beauty and truth which his conscious mind cannot as yet grasp, but which are prophetic of the regenerate life. And as he rises from his prayer, he feels a new strength, a greater resolve, a sense of future victory, as if the spiritual tasks ahead were after all less heavy than he had thought.

He does not know that his spirit - in the putting away of worldly thoughts - had actually drawn breath from heaven and had stood in the great audience-hall of his God and Lord, and had viewed life for the nonce in the new perspective of eternity. He does not know that the ideas within the words of his prayer had been unravelled in their fulness and depth of meaning by angelic minds - into a spiritual invocation of sublime significance, involving the arcana of the Lord's providence. But he feels their sphere of thoughts as a perception of consolation and joy.

The angels are in unceasing internal worship, even while in their various uses of their spiritual occupations. But internal worship alone is not sufficient for man on earth. "Man," the Arcana states, "ought not to be otherwise than in external worship also; for by external worship internal things are excited, and by means of external worship external things are kept in (a state of) holiness, so that internal things can flow in. And man, moreover, is thus imbued with knowledges and is prepared for receiving celestial things, and is also gifted - unawares - with states of holiness ... which ... are preserved to him by the Lord for the use of eternal life, for in the other life, all the states of his life return." (@AC 1618; @Char 173-183).

How great the need of man for these interludes of prayer, whereby our disordered minds may relapse for a while into a state of holiness - so that the springs of spiritual life might again be stirred into action - to inflow without danger of being defiled and distorted by the prudence and the pride of our worldly self which at other times claims possession of our thoughts! How great the need of prayer, if through this we may lay up for ourselves treasures in the kingdom of heaven! For where the treasure is, there will the heart be also.

Yet it is not we that can lay up that heavenly treasure, but the Lord, unbeknownst to us. And it is not the vain repetitions of the heathen, nor the prayers of our own fickle will, that can call forth the responses of heaven; but only those petitions which accord with the prayer of the kingdom, the Lord's prayer, the prayer taught by Him whose is the kingdom and the power and the glory, forever.

<<<

== Our Father

And He said unto them, When ye pray, say, Our Father who art in the heavens... Luke 11:2

All prayer is prophetic - looking into the future. As to the Lord's prayer, it is revealed that "from beginning to end ... (it has reference) to the time when God the Father will be worshipped in the Human Form," and that "this appears when this prayer is rightly explained" (@Inv 37). All that we ask therein will in mercy be fulfilled in the life of the New Church wherein the Lord is approached immediately. "Our Father who art in the heavens." Thus are we to address the Lord. We come to Him not only as to a Judge or a King, but we speak to Him as to a Father - the Father of us all. "Have we not all one Father? hath not one God created us?" (Malachi 2:10). "Thou art our Father," saith the prophet; "though Abraham be ignorant of us and Israel acknowledge us not, Thou, O Lord, art our Father, our Redeemer, Thy name is from everlasting" (Isaiah 63:16) It is not for justice only that we pray; but for mercy. In prayer, love cries out to love, as a child cries out for a father's comforting hand. "A Father of the fatherless, and a Judge of the widows, is God in the habitation of His holiness" (Psalms 68:5) We have no claim for justice. Our only claim is that of helplessness - the same claim to love as has the newborn babe upon the love and aid of his parents. In the endeavor to regenerate, our awakened spirit finds itself naked and in need, newborn into a world not yet comprehended. We are in need of all things - of strength, of shelter, of food; yet we know not what we need most. Our prayer is inarticulate. We can pray only for life - spiritual life, whatever that may mean. But it must be the cry of Innocence, of a sincerity that stems from those states of infantile love and trust which the Lord implanted as "remains" in our minds early in the spring of our life.

Who is this Father in the heavens? Alas for the darkness that rules in Christian lands! The heavenly Father is imagined as a God among gods - an invisible Deity among a triumvirate of Divine "Persons." The angels, on perceiving this folly, are sorrowful; for they know that a prayer addressed to such a god cannot be heard in heaven (@TCR 108). Those who are innocent in heart inmostly cherish no such idea of three Divinities. And in the other world the angels instruct newcomers that in addressing the Father who is in the heavens, they do not think of God the Father or of the invisible Divine, but of Him in His Divine Human, in which He is visible; thus of Him who by men is called Christ, but by angels is called "the Lord" (@TCR 113).

The angels know the Lord as the Father in the heavens. They have always known that God is one and indivisible; that He is by His very essence Human, and that man was created in His image. They knew that because Jehovah God was from eternity infinitely Human. He could and, in case of need, would descend to assume the ultimate human form of earth-born man and glorify this form by His presence and operation therein until that which was merely finite was put off. And when this took place at the Resurrection, they hailed Him their God and Father now made visible even before the natural minds of men in the glorified aspect and Person of Jesus Christ in whom now dwelleth the fulness of the Deity bodily, and who manifests the power and glory of the Infinite and makes this approachable as the goal of our worship.

This simple and fundamental truth, known to the angels, dawned but slowly upon the apostles themselves. When the Lord taught them to pray to the Heavenly Father, it did not seem to impress them that it was their Master who was to become the object and recipient of their prayer. His Divinity was at first so securely veiled that their attitude to Him could scarcely be characterized except as a holy fear, a loving reverence, and an awe of the impenetrable mystery that constantly covered His words and His acts, His powers and His Person. It was not until after the Resurrection that their eyes were opened, and that even Thomas, the doubter, worshipped Him as "his Lord and his God." Not until then had they understood the meaning of their Master's former teachings that He was the Way, the Truth, and the Life. "No man," He had said, "cometh unto the Father, but by Me." "I am the door of the sheepfold; he that climbeth in some other way is a thief and a robber." "No one has known the Father at any time nor seen His shape; the only-begotten Son.... He hath manifested Him." "If ye had known Me, ye should have known My Father also; and from henceforth ye know Him and have seen Him." "Have I been so long time with you and yet hast thou not known Me, Philip? he that hath seen Me hath seen the Father; and how sayest thou then, Shew us the Father?" "I and the Father are one."

This simple truth was the corner-stone of the Christian Church - a stone which (alas!) the builders rejected. From apostolic times heresies entered into the Church of Christ, by the confusing of the Lord's teachings with earthly philosophies and the sensual thinking of polytheistic paganism; until, at the time of the second advent of the Lord, Swedenborg was commissioned to reveal that there were "no other than false churches" left in the Christian world. The power of the prayer which the Lord taught men to say was annulled in the minds of Christians, so far as it was directed to a divided Godhead or to an invisible God (@TCR 108).

Yet - was there not a distinction made by the Lord Himself between Him and the Father? Did not Jesus, as the only-begotten Son of God, pray unto the Father, as if mediating between the Father and the human race, and thus interceding? This appearance however was unavoidable, since the human assumed by the Divine through birth in the world could appear no otherwise than as the Son of God; but it was also an intentional appearance without which men could not be introduced into the interior truth itself. For the Lord as the Son was the Divine Mediator and Intercessor.

But it is necessary to know that the Lord's office of mediation was performed in a different manner while He was in the world from the manner in which He now performs it. The apostolic teaching was that "God was in Christ reconciling the world unto Himself." (2 Corinthians 5:19) The Divine was in the Human of the Lord as the Soul in its body; was the Soul and Source of every word and work. "Believest thou not," the Lord asked Philip, "that I am in the Father and the Father in Me? The words that I speak unto you I speak not of Myself; but the Father that dwelleth in Me, He doeth the works." (John 14:10) Yet before its full glorification, the Human of the Lord was not identical with the Divine. It was rather the truth Divine that "came forth from God." And this distinction was conveyed by the relation of Father and Son, a natural symbolism which suggests a personal distinction when applied to men, but which in the case of the Lord could not be so interpreted, since the infinite God dwelt in Him as a Soul, and was separate in no other sense than as the soul of man is distinct from his self-conscious personality. The Lord's Human is therefore identified with the Divine Truth proceeding from the infinite Divine Good, which latter is called the Father, since with every man, the "soul" is derived from his father. The Human of the Lord was the Word becoming flesh, i.e., the embodiment or incarnation of the Divine laws of mercy and salvation.

The Divine Good - the infinite mercy, compassion, and love of God - cannot be received by men except as truth, or except by the life according to the Divine laws. In His incarnate life, the Lord reconciled the laws of the physical world with the laws of Divine Mercy - laws which are all Divine though they seem to men to conflict. He became the Divine Truth in Human form; and at last this Truth, in Him, became infinitely identical with the Divine Good.

This was the reconciliation. But before this union was completed, the Divine Truth mediated with the Divine Good as if the two were separate and apart. The Lord prayed to the Father as to another. He Prayed for His disciples. He prayed that the Father should send "another Comforter, even the Spirit of Truth," which should abide with them forever. But this was to be but another form of His presence: "I will not leave you comfortless," He added, "I will come to you." (John 14:18)

This prayer of the Lord's Human to the infinite Father was the intercession of Divine Truth with Divine Good. For Divine Good can be approached only through Divine Truth, and can inflow only into what is of Divine order, thus into Divine Truth. For this reason the Lord also said, "If ye shall ask anything in My name, I will do it..." He did not here say, "the Father will do it," for He and the Father are one.

The Holy Spirit was then not yet, for that Jesus was not yet glorified. But when the Spirit of Truth would come, "at that day," He promised, "ye shall know that I am in My Father..." "The time cometh when... I shall shew you plainly of the Father." "At that day ye shall ask in My name; and I say not unto you that I will pray the Father for you; for the Father himself loveth you because ye have loved Me..." There would be no need of intercession as by another. Divine Truth and Divine Good would be seen as One. The Lord would Himself be worshipped as the Heavenly Father.

Therefore it is nowhere enjoined in Scripture - neither in the apostolic writings - that Christians should pray the Father "for the sake" of the Son; nor is it ever said that God forgives the sins of believers "for Christ's sake." Such common Christian phrases stem from false doctrine perpetuated by erroneous translations. It is said in the Epistle that we should forgive one another "even as God in Christ hath forgiven..." (Ephesians 4:32) And the Lord did say, "Ask of the Father in My name" (John 15:16); for the name of the heavenly Father is Jesus Christ.

The name is that by which a man's quality is known. And the quality of God's mercy and compassion is revealed in the Divine Human. After His glorification, the Lord may be called Mediator only because no one can think of the Divine itself unless he has before him the idea of a Divine Man; and no one can be conjoined to God by love except by such an idea (@AC 8705). There can be no love for an invisible God; for such a nondescript Deity becomes confused with the interior powers of nature - with a blind and unfeeling mechanical force, or with a bleak and indeterminate infinity to which we can attach no living qualities, no mercy, no wisdom, no providence, no consideration for the needs of man. Even the devils in hell, who altogether deny the Divine Human, are sometimes not averse to hear of an invisible and unknowable God whom they call Creator. (@Ath 201)

The Father in heaven whom we worship, is the Lord in His Divine Human. He is the infinite Divine Love which appears to us through Divine Truth. Jesus Christ, glorified, is the name of our God, the name of the Father and the Son and the Holy Spirit. We do not worship the invisible "Father" -- the Divine Esse which was related to the "Son" as Soul is to Body. We are not to separate the Divine Trine, for the fulness of the Godhead dwells bodily in Jesus Christ. And it is He whom we invoke as our heavenly Father (@TCR 113[6]).

As our Father; not as my Father. There is no worship of God from a spirit of selfishness. What we desire for ourselves we pray that all men may receive so far as it may be a blessing for them.
// notable:
[_Scanner unable to insert word_], reads the prayer in Greek: "Father of us." Love to the Lord and love toward the neighbor are both fundamental to the kingdom of God, and from these two spring all the uses and delights of heaven.

"Our Father who art in the heavens." Even in thought we cannot ascend above the heavens. But in the heavens - in the inmost sphere to which human and angelic thought can rise - the Lord is present and meets with man. Each man seeks God in his own heavens - in the temple of his spirit. If the kingdom of heaven is within us, and we raise our thoughts above the realm of worldly things, our prayer may rise as fragrant incense. If not, it will turn back upon ourselves as the storm-driven smoke of our smouldering lusts. Such prayers as proceed from evil are also answered - by evoking their powerful echoes in the hells or in the imaginary heavens of our own making.

Every man thus prays to his Father in his heavens: opening his heart to the source of his life, to the influx of his ruling love whatever this may be. He prays either to the finite and futile god which he has himself set up in his own frail image, or to the true God who has revealed the Divine pattern of human life and who taught us to pray in His name, for the fulfilment of His will.

<<<

== Hallowed Be Thy Name

Our Father, who art in the heavens, hallowed be Thy name! Luke 17:2

The first petition which the Lord would have us bring before Him is that His name be hallowed. This is not the first thing that is in the heart of the unregenerate man to ask for. But neither is the Lord's Prayer like the prayer which man, untaught, would offer in his personal distress. The Lord's Prayer is the prayer of the spiritual man, and furnishes an ultimate whereby man may inscribe the order of heaven upon his thoughts and confirm it in his natural life; The Lord's Prayer is, therefore, fashioned in the image of heaven, and in the image of the spiritual mind which is seldom aroused with man in this world.

The Lord's Prayer, being patterned after the order of heavenly influx, commences with the idea of the Heavenly Father as the supreme Source of all good; and then the effects of His inflowing life are unfolded in their series: first the Lord's name, then His kingdom, then His will as done in heaven and on earth. Later our heavenly nourishment is mentioned, and at last the birth of forgiveness or charity, and the deliverance from temptation and evil.

We can ask for none of these things unless we first pray that the Lord's name be hallowed in our mind. The Lord cannot hold us guiltless if we take His name in vain.

In the Scripture much is said concerning the name of God. The Jews, to whom the ancient name of Jehovah was restored, knew not its meaning, but - like other peoples of antiquity - believed that in the secret name of a god or spirit there resided a power for miracle or conjury. And we may read with wonder about the times when the name of Jehovah caused water to turn into blood in the rivers of Egypt and to flow from a rock in the desert; when this holy name struck armies with disaster or caused the shadow on the sundial to move back. Those days, we are wont to say, are no more. Yet the name of Jehovah has lost none of its power, and is no whit less holy; although its omnipotence operates no more by mere "representatives"; for these have vanished before the reality itself - when the Lord was revealed in the flesh and took unto Himself all power in heaven and in earth - the power which had formerly lodged in representatives.

Yet He Himself bids us to "walk in His name" and to "ask of the Father in His name"; and speaks of "writing His new name" upon the redeemed of the New Jerusalem. He promises salvation to those who "believe in His name," and gave to His disciples the power of driving out demons and healing diseases in His name. And "into His name" were they to baptize all nations!

For He and the Father are one. The Divine Human of Jesus Christ is the "name" of our Heavenly Father - the name we are to hallow. Marvellous and holy is that name! For as the name of a man is a symbol of his personality, the convenient index and summary by which we refer to all his qualities; so the name of God is the sum of the Divine attributes, of all the qualities and powers of the Lord. The Divinely Human essence of God was manifested in Jesus Christ, which - after the incarnation and the glorification - became the name of the Father, the form and quality of the Divine love.

It is needful that we hold the image of His Divine Person before us, as He is made visible in the Gospels. For in the Divine character of His Person are revealed the spiritual and celestial virtues which are to be reflected in human life: compassion and zeal, love and selflessness, meekness and strength, justice and judgment, innocence and wisdom, patience and courage. Unless these virtues are seen as embodied in the one Lord whom we worship and whom we are to love with all our heart and all our soul and all our mind and all our strength, there is nothing spiritual in any of our uses and our prayers become empty and directed only to ourselves. For then our imagined goodness is thought of as a product of our own for which we demand homage and reward.

If our regenerate spirit is quickened into life, and we turn to our Heavenly Father with innocent, helpless hearts, asking His compassion, He will answer our prayer, as yet unformed, and do it by revealing His name. He comes before us as a Divine Man, as a Teacher offering us the protection of truth - a clothing for our naked spirit, lest the awakened spark of spiritual life be chilled and extinguished at its very birth.

Our Heavenly Father is not far away from His children, but is ever present by the sphere which proceeds from Him. All the true forms of finite human life are echoes of His life. He, too, is man, but Divine Man. He makes His "name" to dwell with men and in the finite world, being present and perceptible in His truth, His law, His order. And when this Divine law is represented in its own form - adapted as sacred story or prophetic command inspired as to every detail, and revealed as doctrine so as to be intellectually perceived by the minds of men - it is called the WORD of God. It is in the Word - the revealed Scripture of truth - that the Name of the Heavenly Father is ultimately manifested. We are to guard lest we take this His name in vain; we are to keep it holy.

If the Lord were now to appear to us as He did before the prophets, clothed in flaming light and majesty; if we should hear His mysterious voice as the peal of thunderbolts or see His power shown in manifest miracle, what could we do but to fall down in awe and add our whisper to the song of the cherubim, "Holy, holy, holy!" But we do not see Him thus. He comes no longer compellingly before the senses, but comes clothed in more subtle garb in realities, not representatives. In the laws of life, in the plain truths of revelation! We see Him only by glimpses within the confusing events of life, letting us sense a measure of His mercy or of His power of justice and judgment. We see Him revealed to our rational mind as we read of His provisions in the Word, and learn of His redemptions and His unceasing guardianship. Little by little His qualities, His purposes, are revealed, so far as our spiritual mind is opened and we learn to hallow His Name.

Inmostly, the Word is infinite and incomprehensible; for the Lord has a name written that no man knows but He Himself: "and His name is called the Word of God" (Revelation 19:12,13). Yet before angels and men He reveals that name in the spiritual sense of the Word so far as this name will not be taken in vain. He inscribes that name upon all things of the Church; it is breathed in every confession of faith and in every deed of spiritual charity. It is not difficult to stop our tongues from outward blasphemy, from denying the Lord or vilifying His Word. But the Lord is also present imperceptibly wherever men speak from innocence, or act from charity, or think from doctrine preached "in His name."
Wherever two or three are gathered in His name: whenever faith and charity are present, whether in intention or in act; there the Lord is in the midst of them. And to these states of discipleship the Lord says, "He that receiveth you receiveth Me." And should we, from stubborn self-will, blind ourselves to the presence of His name, and offend innocence and violate charity and injure faith, instead of taking in the stranger and clothing the naked and ministering to needy states; then the eternal Judge must say, "Inasmuch as ye did it not to one of the least of these, you did it not to Me." (Matthew 25:45)

But to hallow the Lord's Name, to acknowledge His Divine Human in His Word and in the situations of human life, there must be not only the appreciation of good and truth wherever found, but there must also be a constant judgment, a renunciation of evil and falsity. Nothing is holy unless it is separated from evil and the falsities of evil. Natural life commences with a separation. And similarly spiritual life begins by a self-renunciation, and continues by a winnowing away of what is evil, false, and unworthy! That which is born of the flesh must be separated from what is born of the Spirit. The holy must be protected from the profane. The new will born in men's understanding from the truths of doctrine is at first so closely surrounded by the lusts and obscurities of the natural affections that the spiritual man within must struggle for its independence by casting off by degrees whatever does not correspond.

Yet it is not for man to claim to himself the holy things of the new conscience, or to take merit for what he does or thinks in the Lord's name, by the Lord's instruction and the Lord's power. The new life of Conscience is indeed felt as man's own, as a new "proprium". Yet this new and angelic proprium is from the Lord, and only the consciousness of it, the sensation of it, is man. Man's consciousness has only been transferred, by his consent, from among the profane and disordered things of self and the flesh, into the midst of the celestial and spiritual things of the Lord's kingdom. The angels therefore perceive that it is the Divine - not they which makes Heaven; and that they are in the Lord when in the things that are of His order and withheld as by a mighty force from the evils of their nature. And hence also Paul, in his teaching, called the Church "the Body of Christ" "in whom we live, and are moved and have our being" (Acts 17:28).

"Hallowed be Thy name!" Holiness with men can dwell only in ignorance that is innocent (@AC 1557). This is true of the wisest angels who are not only constantly aware of the infinite extense of their ignorance, but who perceive that all that they do know is from the Lord. And with men, only the confession of their own spiritual ignorance and of the boundless wisdom of the Creator can lead them to a sense of the holiness of the infinite God and of the Word wherein He reveals His name. Our acknowledgment of the holiness of the Word rests upon our realization that in its form and structure, its words and expressions, there is to be found a meaning so inexhaustible, so perpetually new and profound, that human wisdom cannot vie with it. It pierces and enlightens the very depths of the human heart. We perceive the holiness of the Word in its literal sense because in its correspondential appearances, drawn from the things of nature, the genuine truths of heaven are held together in a connection and order which nothing but a Divine Mind could inspire and nothing but the Lord Himself could reveal. Yet this ultimate order, because it is the order of heaven, affects every innocent and pious man with a sense of holiness, because it was fashioned to image the order of heaven and has the power to conjoin man's mind with the angels (@AC 3438[e]; @AE 1088[4]).

Because of this order within the letter of the Scriptures, it is said that the holiness of the Word is in its fulness in the sense of the letter as this exists on our earth. For therein all Divine truth of the spiritual Word and the celestial Word of the heavens, finds its focal plane. In it are collated all the infinite forces of salvation. Nothing is missing. Upon this Word, the interior wisdom of the heavens rests as on a secure foundation. The Lord is here approaching man in His Human, but shrouded in mystery as in His holy temple. And the earth is silent before Him.

Sanctity belongs to truth in its ultimates, in its static form as Divine order and unchangeable law. When the angels are sometimes called "holy," this has reference to the fact that with them heavenly truths are received into their life; and the highest of the angels are they who even as to their sensual degree have become forms of truth, so their very bodies not only represent, but correspond to celestial truth. Yet this holiness is not from them, but from the Holy One of Israel who was glorified and made Divine even as to flesh and bones and became the First and the Last, the Alpha and the Omega.

To hallow His name we must therefore admit ourselves into the sphere of His holiness, and come before Him reverently to receive the truths which can imbue us with new motives and subjugate and order our rebellious affections, clarify our thoughts, and induce upon our outward lives a correspondence with internal things. It is especially stated that when man is performing acts of sincere piety, and his externals are humbled, internal things are excited and "he is gifted with states of holiness" which later serve him in the after-life. (@AC 1618)

Most men, from a common perception and an instinctive need, can at times feel something of a holy fear as of a near presence of God. The Jews felt this fear of His holiness, regarding their temple as the abode of Jehovah. But we must realize the omnipresence of the Lord. All sincere virtue, all Orderly joy; the innocent delight of the child hearing the stories of the Word at the family hearth, the states of the adults of the Church when some new truth dawns to spread its light over their life, or when the spirit of charity finds expression in a happy word or useful act, or friendship finds an echo in forgiveness, or when new understanding breaks the barriers of pride; or when love newfound blossoms out into the tender wisdom of the conjugial life: all these things are to be looked upon as sanctities, as holy to the Lord, as things accomplished in the name of the Heavenly Father.

All good things and true, even the lowest and the least in human life, are inscribed with the name of the Lord. Yet holiness does not pertain to man, nor to nature. Even the bread and wine of the sacramental Supper are not holy in themselves. The things of the Church are holy with us only so far as they can serve in our minds as the ultimate plane for the Lord's presence. And this they can do so far as we resist the polluting influence of evil, allowing the truth to reform our thoughts and purge our lives.

Therefore the Lord said, "He that overcometh, upon him will I ... write the name of My God, and the name of the city of My God, the New Jerusalem which cometh down out of heaven from My God, and...My new name" (Revelation 3:12). The "name" of God is Truth: this the Lord, in His Human, speaks of as "My God," -- His Truth, His Law. For His "new name," which is to be hallowed, is the law of human life that was glorified in Him and revealed in the holy structure of Divine Doctrine which is the New Jerusalem, where He is seen as the Divine Human, as Divine love in Human Form.

<<<

== THY KINGDOM COME

Thy kingdom come! Luke 12:2

The prayer which the Lord taught His disciples contains the essentials of all worship, all doctrine, all life. It is to be addressed to the Lord as the Divine Human, the Source and creative Origin of human life. Our first petition should be that we be moved to hallow His name that we be brought to acknowledge His Divine qualities as they are revealed in the Word and from this in the church, in its doctrine and in its states of innocence and spiritual charity. The second petition is that His kingdom may come.

It might seem that it would be unnecessary to pray for the coming of the Lord's kingdom. Indeed the inner truth which the Church acknowledges is that the Lord alone rules the universe of His own creation. The earth is the Lord's and the fulness thereof. The heavens are His. His order is impressed on all things, spiritual and natural. His laws are universal and unchangeable and cannot be defeated. This is the comfort and joy of all good men, and is expressed at the close of the Lord's Prayer by the phrase, "For Thine is the kingdom, and the power, and the glory, forever."

There is no need, then, for man to implore the Lord to rule His universe. But there is need for man to understand this government and to consent to it in his heart.

Our human idea of an omnipotent government savors of the notion of tyranny and compulsion. As we behold the unyielding structure of the natural world and the laws of space and time and motion which govern it, and the inevitable sequences of natural effects from material causes, we are tempted to think that all things and events therein are predetermined with mechanical precision. And from the Writings we learn that even the spiritual world has its laws, and that this spiritual creation - which has its source in the Heavenly Sun, with its proceeding atmospheres and with its visible ultimates - is also substantial and ruled by the laws of God which cannot he altered nor abolished, being founded in the eternal Divine truth. "To each and every thing in the worlds of nature and in the worlds above nature He alone gives life; and ... no angel, spirit, or man is able to move a hand or foot except from Him" (@AE 726[2]). If this be so, what is man but a slave of destiny? and what is our human existence but an illusion - a phantasmal dream not of our own making.

Yet such a thought is founded on a fabric of errors. For the structure of the two worlds with their unchanging laws is not what is meant by "the kingdom of God" for which we pray. These two worlds are and were created, and are everlastingly ordered by the Lord, not for His own sake, but for man's. They are but the foundations and the media for the production of a kingdom of immortal human life which can become the kingdom of the Lord.

It is necessary to reflect that God is Divine Love itself - love in its infinite purity. Love in its essence is such that it does not build up a world to manifest its unlimited power or to display its glory! Love can take no satisfaction in creating a domain where not only every atom yields unfailing mechanical obedience, but where every thought or feeling of man also would be predestined and controlled. So shallow an ambition is unworthy even of the nobler loves which man can feel within himself.

Only by knowing God can we come to understand the functions and purposes of His Creation. His Creation was designed to convey of His life that others might live - live as if of themselves and thus be capable of receiving the love which He offered, receiving it for themselves alone, or receiving it to transmit it to fellow beings and to share it with them

For this kind of reception of life, freedom is imperative and indispensable. Not freedom from the laws, whether of nature or of life, for they constitute the frame-work within which our finite existence is carried on. But the freedom to make use of these laws is within our limited scope and power. And these laws give ample room for choice and liberty. The force which carries the stone to the depths of the sea also causes the air to rise. The power that enables us to destroy can be used to save and deliver. These laws of the universe are not set up to predestine our human spirits, but to make our freedom possible. There can be no freedom, and therefore no love, except within the compass of an established order, ruled by a Creator of infinite wisdom and mercy.

Now life comes in many forms - even in lowly forms as in the kingdom of plant-life and in animal creation. Each form manifests a certain image of freedom, though limited by the order of its creation. Only in man does this freedom become rational and conscious of its destiny, taking on the power to decide its own degree of responsibility, and coming to understand the laws which limit it, and the Divine Source from which it springs. Not only can man ferret out the operations of nature, but he can perceive and intelligently grasp spiritual laws when these are revealed by his Maker.

By spiritual laws we mean here the truths which tell of the Lord's end in creation - tell of the purpose of human life, the reason for our existence. Spiritual law is the law of love, which enlightens man to see his duties and debts of charity and to respond with gratitude to the provisions of his Creator. Such law comes from the spiritual world, and when the mind of man becomes perceptive of this law and in freedom responds to its government and takes delight in its operations and modes, then the kingdom of the Lord begins to be established within him.

The Word, as explained in the Heavenly Doctrine, tells the story of this kingdom of God: how it came into being in the innocency of the celestial race signified by Adam; how it declined with these but was renewed with the men of spiritual genius signified by Noah; how it was preserved as a symbolic hope among the descendants of Abram, and, being threatened with extinction, was founded anew by the Lord incarnate; only to be again perverted and demolished by men, yet to be restored as an eternal kingdom by the descent of the New Jerusalem from God out of heaven.

The Gospel of the New Church is that the Lord Jesus Christ now reigneth, of whose kingdom there shall be no end (@TCR 791). For the laws of perpetual judgment have now been revealed, in the spiritual sense of the Word. This is the Divine promise. But still the kingdom can be established only in human minds and hearts; and we are therefore told that whoever learns about "the second coming of the Lord, and of the New Heaven and the New Church, and thus of the Lord's kingdom, ought to pray that it may come"; and that whoever thirsts for truths ought to pray the Lord for light, and that then "he who loves truth will receive them from the Lord without labor of his own" (@AR 956). The Word in its letter closes with this prayer: "The Spirit and the Bride say, Come! And let him that heareth say, Come. And let him that thirsteth come, and let him who willeth take the water of life freely."

The kingdom of God cometh not with observation. For it is within you. It is not imposed upon man by any omnipotent act of Deity or by Divine prophecy, or by any compelling decree, nor by the pressure of external circumstances. It can come only as the fruit of prayer a prayer not of the lips alone, but of the heart and the life; a prayer taught by the Lord.

But if the silent prayers of men's hearts proceed instead from self-will and are filled with the phantasies of sensual passions, filled with pride and the lust for gain and personal admiration, there arises another immortal kingdom within which is not the Lord's. It is a dominion which is named as that of "the Devil" and "Satan", the dominion of evil loves - of hell. The existence, the very possibility, of such a domain of evil is the proof of human freedom and of the essence of God's love which tolerates the abuse of the gifts of conscious life rather than denying them to all. If there is to be a kingdom of God - a heaven from the human race founded in human freedom - by which Divine Love may impart its life and the delight of life to finite individuals in numberless worlds and to ages of ages; then there must also be a law of permission which implies the possibility of immortal souls rebelling against the order of heavenly life and making their own "heavens" of ill-will and lust.

It is not to be thought that the hells are beyond or outside of the Lord's universal government. For the Lord rules most particularly the thoughts, intentions, and wills of all (@AE 726[2]). His laws of grace and permission determine and order the influxes of life, the faculties and modes of human thinking, the limits of man's power to abuse, so that evil can never lastingly injure any final good, but will ever lead to its own retribution. It is of doctrine that what guards and rules hell is the sphere of Divine Truth separated from the Divine Good (@AC 9534); for the evil do not receive Divine Good (@AC 4180). This sphere of Divine truth is also called the Lord's universal presence, or His external presence, which is perpetual with every man (@TCR 719, 774).

In appearance, this infernal kingdom defeats and denies the omnipotent Will of God, and glories in a presumed power of breaking the Divine laws, and even repeatedly destroying the external order which would bind it. For men on earth, evil seems to possess an undue power; and every crime and ugly passion, every breach against justice or decency, every abuse of privilege, every falsity that triumphs, seems to demonstrate that the Lord does not rule in human affairs. And when man turns to nature, with its apparently ruthless waste of life and the mute sufferings which attend the endless processes of birth and death, he finds difficulty in seeing therein any unanimous testimony to the omnipotent rule of a God of Love!

But man has set up a scale of values which look only to the delight and comfort of the moment. Having eaten from the tree of knowledge, he believes that he can recognize good from evil; not reflecting that the greatest gifts of life are often wrapped in repulsive garbs lest man should grasp for them before their proper use can be appreciated. The delight of living, with every creature, outweighs its sufferings. Death, which men so fear, is but a tool of new creation, and has its part to serve, both in propagation and in the fulfillment of the end - the realization of the final good. Evil, when its effort is spent and its judgment comes, has harmed only those who deliberately confirm the appearance that man lives from himself - that his life is self-derived and must look only to his own gain, power and dignity. And though at times the apparent power of evil threatens human liberty itself, it can achieve nothing except to arrest for a while the growth of the human spirit towards maturity and freedom.

At such times, more than ever, must we pray for the coming of the kingdom of our heavenly Father. For the portent of its approach is that truth, Divinely revealed, which breaks down the illusive power of evil in our minds. At the end of a Church, the Lord comes again as a King to bring about a new order. A king is the source and symbol of the laws of his realm. He typifies the law of truth in its acknowledged majesty and power, the law from which the order of the nation springs.

Order is the beginning of progress. If we consider the many sufferings which are the aftermaths of every state of unjust passion or of appetites that are not controlled; the disillusionments which impatience brings about; the confusion and disappointment that are the fruit of self-confidence and conceit; the indifference and lethargy which are spawned by misunderstandings and false beliefs; it must appear how urgent is the need of order in man's mind: order and subordination not only in our thoughts, but among our many affections and desires, our yearnings and instincts. And order comes only where there is truth, where principles rule, where there is a clear sight of the two worlds in which we live and a knowledge of ourselves and our relation to others and to our Maker.

It is such an order for which we daily pray when we say, "Thy kingdom come!" In our confusion, we petition for light, for the ordering of our minds by the influx of spiritual truth - into a regenerate pattern in which our distracted thoughts and our wayward affections might be purified and brought together to form a flowing stream of power for the performance of such uses as the Lord may indicate by the needs of others.

But the kingdom of God comes not by prayer alone. It must be sought.
"Seek ye first the kingdom of God and His justice, and all things shall be added unto you." It must be sought, not for recompense or profit, but for its justice. We must seek it seek the Divine truth from a love of the kingdom of spiritual uses which we may gradually come to see crystallizing before us as a city of light for all peoples and tongues, while we study the pages of the revealed Writings.

It is one of the marvels of heaven that the angels, who have the kingdom of heaven within them, are also surrounded with the external beauty and peace, the sincere friendships, the plenty, and often the wealth and splendor, which men first think of when they long for heaven. These things, the Lord promised, shall be added as free, undeserved gifts, to those who seek His justice, and whose hearts are not set to earthly values.

The Lord's kingdom must be within, in the realm of the loves that continually resist evil and falsity and form the interior motives which fashion our lives. Yet the kingdom will not come within us except so far as we, while on earth, seek to promote its establishment in the uses about us. Outside of us, it exists as the Specific Church (which guards and teaches the Heavenly Doctrine) and in a wider and vaguer sense the Church Universal. Our prayer would be futile if we fail to respond - each in our own way and according to our abilities - to the needs of the Church and to the call for understanding and mutual charity through which the government of the Lord may be established, as in heaven, so upon the earth.

<<<

== THY WILL BE DONE

Thy kingdom come, Thy will be done, as in heaven so upon the earth. Luke 11:2

The essential within all religion is to wish for the fulfillment of the will of God. In worshiping the Lord we mean to acknowledge that His power is over all, that His ways are just and true, and that the ends of His providence are eternally good.

We therefore bow our hearts before the Lord, conscious that the ways of man, if unguided by Him, will lead only toward evil and folly. We ask for strength to put our own will aside and to resist the alluring schemes and projects which our self-intelligence has formed. This may seem to a man like forsaking his delights and sacrificing his very life. But even though he resolved thus to surrender his own selfish will completely to the will of God, this cannot be accomplished by any sudden act or decision. For man can never be entirely severed from his own past; and any changes of state that he might undergo can be effected only by stages and degrees.

Indeed, the life which man feels within him as his own is not really his. Nor is it ever fully within his own control. Man is but a vessel into which life inflows - an instrument responsive to influences from many sources, some perceptible, some hidden. His emotions and feelings are borrowed from generations long passed on. His thoughts are largely reflections of the opinions of others, and are often adopted by an unconscious mimicry. His moods and motivations, even when they appear to be directly caused by outward circumstances, worldly situations, or bodily states, are reflexes from unseen hosts of spirits and angels. And whatever media are employed - spiritual and natural - the final source from which life inflows is the Lord, the infinite God. From Him it flows immediately into our inmost souls for the maintenance of the human form of our spirit and of our body; and it also inflows mediately through the spiritual world and through nature, which both serve as agencies in His all-provident government.

In its immediate influx, life is pure and unpervertible. But in its transmission through finite agencies, life is limited, refracted into many forms, determined towards different ends; and often - by a transflux through the hells and through the evil minds of men - it is perverted or misappropriated for ends that go counter to the will of God.

And it is this perversely determined life which man receives and feels as his own will - as selfish delight. For from heredity the very structure of man's natural mind has become disposed to invite only such influx as will enable him to indulge in sensual delights - in delights that enhance his self-importance and individual gain, in loves of self and of the world. Influx is always according to the form and state of the receiving vessel. And only so far as the vessels of our mind can be changed, only so far can the will of the flesh, the will of man, be surrendered, and a new will be formed which is in accord with the order and intent of the Creator. The promise is indeed given that "he that loseth his life shall find it." Man suffers no loss in doing the will of God, but gains a life more abundant.

Only the Lord can think and will from Himself. But our doctrine discloses that the essential human is "to think and will from God" (@DP 293). And this is possible to man because his thought and his will are not self-derived, but come by influx from others. His mind is formed not only from hereditary tendencies but from constant contact with others. Thereby he comes into a state of freedom and can compare truth with falsity and good with evil, and thus choose that life which he would have as his own choose to think and will from what is of Divine order, or else - from the loves and phantasies of self-love alone.

Thy will be done! These words were voiced by our Lord in His supreme temptation in Gethsemane, when He was about to relinquish the separate life of His assumed Human. His sacrifice no man can ever measure, for man is not required to surrender the appearances of finite self-life. Man, by patient endeavor, may Surmount and subdue the affections of his own native will; yet he is not asked to put off his finite nature, but merely to employ his God-given faculties for the furtherance of the Divine will in the limited sphere of his own life. The kingdom of God is to be established within the field of man's free cooperation.

The laws of the Divine providence therefore ordain that the will of God should be disclosed to men by Divine revelation, so that man may in freedom think and will as if from himself, yet from the Lord; for when he acts willingly from the Lord's teaching, he acts and wills from the Lord, and not from himself, yet as from himself (@TCR 506). Me acts and wills from freedom, in accordance with his reason as formed from the Lord's instruction and in accord with a perception of the Lord's will. Wherever a human race exists on the uncounted earths of the universe, the Lord's will is in some way revealed, and His order, which is the law of love and charity, the law of reformation and regeneration, is in some manner made clear, according to the needs of each human being and the genius of each race. On our globe this has been done by the inspired, written Word and by doctrine derived from it; a Word differently given to successive churches which have served to promote the kingdom of the Lord.

It is through the Church that the Divine truth concerning the Lord's will and purpose is being made known. For this reason, the Lord's Prayer voices our petition for salvation in this order: "Thy kingdom come, Thy will be done, as in heaven so upon the earth." The kingdom with its message of Truth, must come to show the will of God, that this may be done on earth as it is done in heaven: done by men, in obedience to the revealed Truth, and done in freedom according to the rational sight of that truth.

Much merely human sentiment has been read into the prayer, "Thy will be done." For men are wont to use this pious phrase as a sign of despair or as a passing acquiescence in conditions as they are, rather than as a rallying cry to more fervent labor in the Lord's vineyard, a call to do battle against the evils which infest us from within and without. In times of anguish and temptation, when the forces of evil seem triumphant, man must indeed become resigned to the fact that even the uninvited presence of evil and the crude necessities which obstruct progress and hamper our usefulness, are permissions of the Divine providence which mercifully prevents the worse dangers which it foresees. But let it not be thought that what is of the Divine permission is what is meant by the will of God which we pray may be done on earth as it is done in heaven. In states of temptation, doubt, and obscurity, man's perception of the will of God is blunted. He confuses what is merely of permission with that which is of the Divine will, and holds the Lord responsible for conditions which are of man's making - often pretending that God countenances or approves the violence and deceit of human ambition.

This is indicated in the Lord's words to the Pharisees: "Moses because of the hardness of your hearts suffered you to put away your wives. But from the beginning it was not so..." "What God hath joined together, let not man put asunder." (Matthew 19:6)

From the beginning it was not so. In heaven it is not so. Yet there is no contradiction between the law of human freedom (which necessarily involves the possibility and permission of evil) and the law of Divine government (@AC 2447). Both are laws of the Divine love. Both are the tools of mercy and compassion. Yet in human life, these laws of order can be separated from good - separated from the Will of God which they contain and then they are turned into rods of iron, into bonds wherein no mercy can be seen.

But our prayer is, "Thy will be done as in heaven, so upon the earth."
In heaven, the inmost end of creation is perceived. The wisdom of the angels consists in understanding the modes by which they can carry this end into effect. The end or purpose of creation is a society of immortal spirits in which all varieties of human values, all the celestial, spiritual, and natural loves by which human happiness is measured, are so wisely subordinated and ordered by a selfless love of uses that they come to constitute a united heaven of innocence and peace - a kingdom of human souls who can receive the gifts of life and respond to the love of their Maker.

Nothing less than this eternal heaven is worth striving for and praying for. Yet this heaven can never be formed unless the will of God be done on earth. For it is of human spirits, born on earth, that heaven must be constituted. The legends about the creation of a hierarchy of angels before the formation of mankind, are but a part of a Jewish-Christian mythology. It is within human beings only that angelic minds can be shaped. And the process of their formation is called a regeneration, a new birth; implying the birth of a new will within man's understanding, whereby the sensual will can be controlled and put aside and man be ruled by a conscience built up from rational truth and spiritual love.

Every man, if endowed with something of conscience from a faith in Divine truths, has within him a "heaven" as well as an "earth". His "earth" is his natural mind - his sensual nature that is kindred to the beasts. His "heaven" is his new will or conscience in which the will of God is obeyed. And the prayer of our every moment must be that this will of God (accepted in the idealism and faith of our inner spirit and reason) may be established also in the thoughts and imaginations of our natural mind and in our outer acts and words.

It is this descent of conscience into the natural realm, which is the chief subject of the Lord's Prayer. Obviously, this conscience cannot extend its rule over man's externals of thought and life, unless it first be truly formed and established; formed by genuine spiritual truths rather than merely moral sentiments; established through a rational faith in the Lord, moved by a love of truth and by charity towards the neighbor. For conscience is not horn with man. It is built by religious instruction. And it is clear and pure in proportion as that religious teaching is not contaminated by man-made dogmas or by one's personal phantasies and the conceits of self-intelligence.

But religious knowledge - however profound - is not conscience until it becomes activated into a motivation for man's life and usefulness in the world. It must become a living zeal for what is just and right, for what is fair and honorable, for what is good and true. It must seek to promote not only the bodily and temporal well-being of men, but the health of their minds and the safety of their souls and eternal spirits.

This can never take place except by active and persistent endeavor. It cannot take place without a devout searching for the truth about the kingdom and the will of the heavenly Father, truth from Divine revelation that can penetrate our superficial thoughts and lay bare within us the evils and the cherished falsities which prevent the rule of the Divine will. It cannot take place as long as man indulges in self-pity, or doubts that the Lord has equipped him with the freedom to choose and the power to repent and cooperate in the Lord's work.

The will of God must not be confused with the voice of supposed necessity by which men are lulled into fatalistic indifference as to the real purpose of life and as to the destinies of society. Such fatalism - with its inevitable attitude of self-pity - leads to spiritual lethargy, which relieves man of the sense of responsibility and dulls the voice of conscience. Necessitywhich flows from the force of circumstances and the cramping pressure of time and space - does not remove man's freedom but only indicates the alternatives of the choice before him as he strives to make his own will accord more closely with the will of God. (@AC 6487; @Dmin 4692).

But in the spiritual world (as also inmostly in the realm of human motives) such limitations of external circumstances do not shackle man's life. When death removes his spirit from the realm of space and time, the restraints of earthly things are swiftly loosened. The will becomes then a powerful and irresistible force, moulding the whole spirit in its image. What terrible powers we might have released here on earth if the powers of our will had been unlimited by time and unrestrained by worldly circumstances! A moment of anger might have killed our friend! a sudden lust for power or gain or pleasure might have committed us to inevitable destruction! It is because of the deterring bounds and bonds of necessity that earth-life gives opportunity for man gradually to form his ruling love in freedom and according to reason.

After death, this chosen love which rules man's will becomes free in its exercise and expression and guides the development of his intelligence and usefulness under the marvellous government of spiritual laws whereby all spirits are consociated according to their inner character. Our prayer must always he that the will of the Lord may increasingly be done on earth - that liberation from merely natural bonds may be granted only so far as this may be consistent with the freedom of the race, and so far as evil and its license will in time lessen. This is the hunger of every faithful heart: that the time may come when charity and worship, mutual love and the love of truth and use, and conjugial love with its innocence and peace, may find its abode as in heaven so upon earth.

<<<

== OUR DAILY BREAD

Give us this day our daily bread. Matthew 6:31

Nothing can be preserved except by perpetual creation, by continual renewal and growth. Hence there is nothing static or permanent, but all things are in a constant state of change and flux. Even matter itself is but a complex of intricate activities maintained by a spiritual influx. The tissues of man's body wear out and must be restored through the food brought by the blood and inhaled from the atmospheres. We die and are born again with every breath. Through our soul, creative life pours into the body to reform and heal. And as the mortal body is fed by earthly food, so the mind, the immortal spirit, is fed by the food of heaven.

All this comes to mind when we pray the heavenly Father to give us each day our daily bread. We ask not alone for bread or food, but for protection, preservation - for fresh air and shelter, for heat and clothing, for a place to work in and to rest in, a field of usefulness. We ask for the protection of civil law, for a measure of freedom and the enjoyment of social intercourse and the communion with other minds. We ask for health and knowledge, for appreciation and love. All the things that our hearts hunger for, are to us "our daily bread."

These blessings come to us on the wings of time - come either as free gifts or as the result of toil and struggle. The Lord leads men to uses by their longings and ambitions. But secretly as well as openly He directs our minds towards greater things than the passing needs of mortal life. "Labor not for the meat that perishes," He tells us, "but for that meat which endures unto eternal life." "Man shall not live by bread alone, but by every word that proceeds out of the mouth of God."

The body is indeed the temple of the spirit, and as such its claims must be respected. Man's opportunities for usefulness depend on his own state of physical and mental fitness. By his obtaining knowledge and training his talents are multiplied. But his foresight about self-development must be the servant of charity. He must not put his heart on riches, luxuries, or honors, but must value them only as tools by which he can perfect his spiritual and natural usefulness.

Normally, that which enters through the mouth does not defile a man; nor does the passing knowledge about evil cause any harm unless it stirs an unwholesome delight in his heart. But there are many things that glut or poison our minds, even as the pleasures of taste may seduce us to overindulgence and invite physical disorders. The knowledge we select to feed our imagination may not be the wholesome sustenance, which our spirit craves for its health and growth. Presentation of coarseness, brutality and impurity will blunt a child's tender perceptions. It will also confuse the adult's understanding by arousing sensual passions. To expose children to falsities about God is like depriving them of all spiritual milk (@TCR 23). Much of the mental food imbibed as delightful entertainment or offered as doctrine by the Scribes of our day contains suggestions which subtly pervert our ways of thinking, fascinate us with doubts based on appearances, fill us with intolerance, uncharitable suspicions, or unworthy fears, undermine our ideals and our faith in revealed truth, breed impatience and cynicism and stifle the zeal for spiritual uses. "Beware of the leaven of the Pharisees," saith the Lord. Woe to them that "strain at gnats but swallow camels," or who "give stones for bread and serpents for fishes," and make us believe that the thoughts of man are the water of life!

"But the Lord offers living water. He offers Himself as the "bread of life." He says, The words that I speak unto you, they are spirit and are life."

It is not the mere knowledge of His words that is meant by the bread of life. Knowledge is only the raw material from which spiritual food can be prepared. Unless a flame of affection warms the cold words of doctrine into a savory food that rekindles the energies of the spirit, the mind becomes easily satiated and sometimes nauseated with instruction.

The Word often speaks of the food of spiritual life. This is what is meant by the food which Noah had to store in the ark before the great Flood, and by the grain stored by Joseph in the cities of Egypt before the seven years of famine. From infancy the Lord provides it in abundance, as innocence and simple faith, as the seeds of all future happiness and understanding. He stores it so deeply within the mind that man cannot reach in and dissipate it. It comes to the surface only when man is in forgetfulness of self. It is locked up for emergencies which the Lord alone foresees; and released when man begins to feel a spiritual hunger which we know as a love of truth. Then it comes down as manna from heaven.

Man's spirit is organic, and is constantly growing and changing. Old states, when their function is completed, are cast into oblivion, and new states are formed by means of new truths and new affections, or by what man considers as truths and goods. There is no nation or people with whom something of spiritual knowledge is not provided. Without this, spiritual life languishes and regeneration is arrested at its start. The spirit of man cannot grow without the goods and truths of faith. It is out of goods and truths - civil, moral, and spiritual that the spiritual body, the immortal spirit, is formed. (@TCR 583)

To our natural thought, "good" and "truth" appear as unreal abstractions, not substantial enough to serve as spiritual food and drink! Yet it is our delights and affections, our perceptions and intuitions, which give essence to our life! The Lord thus told His disciples, "I have meat to eat which ye know not of... My meat is to do the will of Him that sent Me." And in the spiritual world, where there is nothing material, the delicacies which angels eat and which are seen on their tables as manifestly as material food on ours, consist of spiritual aliments only forms of knowledge, affection, intelligence, and wisdom, such as alone can nourish the mind. If only material things are regarded as real, we would be like certain strangers in the world of spirits who came to a laden table and yet saw no food! (LJ post. 338)

But those who "hunger and thirst after righteousness," shall surely be filled. They who long for a better understanding of the purposes and duties of life and for a purer heart, may see the sphere of charity reach out towards them from all sides, offering them refreshment of spirit. They discern the bread of heaven in the abundant truths of the Lord's Word. They see how the Lord prepares a table before them even in the valley of shadow, in the presence of their enemies, so that their cup runneth over. For wherever men live according to the truth and do His will, there charity and use are theirs for the seeking, with delight and food for the soul.

But man is slow to grasp these opportunities. We often spurn what lies before us, and look for other charity than that which is shown us. We then prefer the leaven of the Pharisees, seeing the shortcomings of our neighbor rather than his virtues. Or, we would have the whole before we can appreciate the part. We wish for instant fulfillment of heavenly happiness, leaving untasted the partial fulfillment which comes as a reward for uses done, and wishing a heaven on earth without walking the narrow way that leadeth unto life more abundant

But the Lord tells us to pray, not, "Give us bread!" but "Give us this day our daily bread." A wise father does not give a child his entire patrimony at once. Our heavenly Father grants us spiritual food in abundance, but only as much as we can receive and are able to use. We cannot ask Him for the bread of heaven only to lay it aside unused, or in order to hoard it and hide it. But we ask to be sustained in the tasks immediately ahead, ask for strength and illustration in the state we are commencing to enter, for a clearer perception of the spiritual uses involved in our earthly duties. For in the spiritual world there is no food given to the indolent or to the evil, except as a remuneration for work done. And angels, who are in the love of uses, receive food and other necessities freely, but always in correspondence with their functions. (@SE 6088, Love xii:3)

Neither men nor angels need to take any anxious thought about the morrow. The far-flung future is in the Lord's hands. He alone knows the eternal use to which His providence leads us as by a hidden current. But neither can we depend on past states of illustration or affection. Whatever gain was made in the past will indeed add firmness and momentum to the uses of today. Yet the ardor of Yesterday cannot be stored up, for it was an influx which we "cannot tell whence it cometh or wither it goeth." The riches of heaven cannot be wrapped up and taken along, any more than the manna, which Israel found fresh with each morning's dew, could be preserved over night; or any more than the meat of the sacrifices could be kept for the next day.

But the Lord provides food for the hungry. Hunger comes when the energy stored in the cells of the body has been used up converted into action. Spiritual hunger, which is a longing for good and truth, arises when man feels the need of spiritual renovation; and each new state must be initiated by a prayer for daily bread as an expression of such hunger. Then, if man has stored his understanding with the teachings of the Word, this knowledge is converted into food - digested by meditation and assimilated by rational judgment to strengthen the tissues of the new will.

It appears as if knowledge gave life and sustenance to the mind, even as it appears that material substances built the body. But it is really the soul which organizes the body; and it is really a spiritual influx from the Lord that organizes the truths from the Word into vessels receptive of life from heaven. These truths are not mere undigested knowledge such as lodges in the memory, but truths of life which go to form a new will that receives the good which truth invites.

This "good of truth" is doctrine which has been put into life, and this is what is meant by the manna which fell from heaven. But it is also told that the manna began to breed worms when more was taken than was eaten during the day. For whatever of spiritual truth that enters man interiorly beyond the capacity of his new will to receive and hold, would soon be profaned by overflowing into the sensual will of his old proprium (@AC 5145, 8480). It is therefore a law of Providence that the will - the heart of man's spirit - shall receive such spiritual food only in proportion as man repents of his evils and removes them from his conscious mind; and that one shall be admitted interiorly into the truths of wisdom and the goods of love only so far as he can be kept in them to the end of his life (@DP 232).

This providential guard against profanation is revealed so that man should not be deterred from his duty to seek daily for the knowledge which the Lord offers in His Word of Scripture and Doctrine, for the salvation of his soul. The nearer danger is that man finds it hard to leave the fleshpots of Egypt for the manna of the wilderness. But if he feels despondent when the sun waxes hot and the manna dissolves into mist, there are also quails from the sea which settle on the camp at evening tide. Every use performed by angels and men has its legitimate natural pleasure which, if held in its proper place, lends variety and perfection, rest and recreation, to their lives, by presenting the beauty, the glory and the magnificence of their uses in the natural settings of social and domestic enjoyments (@AC 8487).

But where there is no spiritual conscience to hold the love of pleasure in leash, men come to despise the manna of heaven. The lust after "quails" engenders a creeping plague of spiritual paralysis and stupor. Their lips may still pray for daily bread, but their minds are weighed down by the anxious cares for the morrow and they are consumed with envy for many things which are not necessary either for their uses or for their happiness (@HH 278).

In heaven it is not so. The angels do not care for the past nor think with concern about things to come. In this lies their happiness, that they live content in the present (@AC 2493). And this is one of the secrets of life. If we look for our duties and opportunities in the present, we shall find our delights there also. And the Lord, who is the First and Last, shall care for our tomorrows even as He gives us bread for today.

<<<

== FORGIVENESS

And forgive us our debts, as we also forgive our debtors. Matthew 6:12

The prayer which the Lord taught His disciples contains all the laws of the regenerate life. It breathes the spirit of charity - the love of Him who began His public teaching by saying, "Blessed are the merciful, for they shall obtain mercy," and ended His life on earth by saying of His persecutors, "Father, forgive them, for they know not what they do."

The Lord spoke His doctrine of charity and forgiveness to a race which knew no other law than that of retaliation - the law of "a tooth for a tooth, and an eye for an eye." We speaks still to a world which is tied up in endless chains of retaliation; a world which identifies justice with revenge; a world whose people are all prone to envies, hatreds, and bitter feuds, to carping fault finding and mutual intolerance, to self-seeking competition which is devoid of gratitude or mercy; a world where charity is mistaken for weakness, and weakness for charity.

Therefore we must pray for forgiveness. There is no escape from the vicious cycle of evil, no breaking away from the cruel logic of retaliation, no raising of the mind above the brute passions of the proprium, except by forgiveness. And man can begin to forgive only when he comes to acknowledge that he himself needs to be forgiven. Our prayer is then a confession of sins, a pleading for mercy; but it is also an acknowledgment that we cannot ask to be forgiven except so far as we also will forgive. It is a prayer for the power to repent, for the ability to respond to the Lord's influx of love which may endow us with charity towards our fellowmen.

It must be said, once and for all, that the Lord never ceases to forgive. The Divine love is beyond that human pride which is so often offended and seeks reprisals. Love only hungers to be received. It reckons not with the past, but continually excuses, intercedes, and abundantly pardons. When we ask the Lord to forgive the transgressions of the past, that prayer is immediately fulfilled, even before it is spoken.

Yet this Divine forgiveness a compassion which does not cease even towards the devils in hell - cannot always be effectively received by man. Therefore, in the language of appearances, we pray that we may forgive us in so far as we forgive our debtors - as if His wrath were more severe than ours. The appearance is that with the merciful He is merciful, with the pure He is pure, but that with the perverse He contendeth (Psalms 18:25-27). It is within the range of such appearances that human life is laid, for they are what condition our life and make it finite. We cannot see God as He is in His own essence, but we see Him and meet with Him as He comes to us in terms of human situations. Viewed from human life, the Lord appears as wise and loving only so far as our spirit apprehends the treasures of His wisdom and love. A stupid man sees no wisdom in the laws of creation, but sees only mistakes and haphazard events without purpose. An evil man feels no love in the dispensations of the Lord's providence, but only tyranny and antagonism and opposition.

This is the reason why man must pray, "Forgive us our debts, as we also forgive our debtors." We pray that our minds may be so changed by repentance and regeneration that we can receive a heavenly delight in willing well and doing good towards our neighbor. For the influx of life is limited to what the vessel can hold; and the effect of the influx is according to the character of the vessel - pure with the pure and perverse with the impure. Our desire must be to become purified from the spirit of revenge which defiles our proprium, so that the water of life may be poured into our minds as into a clean vessel, and that our "daily bread" -- the sustaining good and truth of heaven - may not breed evil things before the day of our life is done.

The wording of the prayer in Luke's gospel is, "Forgive us our sins."
Unless evils are shunned as sins against the Lord, they are only temporarily hidden. Genuine repentance is not begun merely from a personal love for others, but for the sake of something higher than all men that is, for the love of what is good and true, for the sake of the Divine law and the Divine end.

Only by such repentance can we plead for the Divine forgiveness. The Lord will then forgive, pardon. Repentance means the renunciation of delight in the evil which we shun. So far as evils are thus renounced because they are in themselves wrong - so far the opposite goods can be instilled by the Lord: thefts are displaced by honesty, laziness by industry, obscenity of thought or act by chastity, conceit by humility.

Simple as this truth is, it is often misunderstood. It is imagined that God forgives sinners by an act of immediate mercy - an acquittal that blots out iniquities in a moment. But such apparent mercy would mean doom for man! It would mean the forcible taking away of man's whole life - all his delights of love and will and thinking. Such a sudden change would mean his annihilation. Happily, the Lord leaves it for man to curb and disown his disorderly desires one by one - that as his evils are gradually removed they may also be forgiven and his delights gradually shift from evil into good.

Repentance is the road to charity. But charity is the goal. And to forgive others is the great Christian virtue - the sign of charity. "If thou bring thy gift to the altar ... first be reconciled to thy brother, and then come and offer thy gift." Yet such is the perversity of man's scruples that it may seem easier to offer peace-offerings to a God whom one cannot meet face to face than to do a simple act of restitution to a fellow-man against whom one has offended. It is easier to seek forgiveness of God than of man.

Repentance must first take the form of seeking to become worthy of forgiveness by other men. And only then can it lead to charity - which is to forgive others.

And in a world such as ours, we have all much to be forgiven and much to forgive. We are all bound up in the evils of heredity which differ but little among individuals. Our human contacts make inevitable a constant conflict of the "proprium" -- the proprium of men and of nations and classes. Each man thinks not so much of his own faults but searches for those of others. He justifies himself, but finds little excuse for others. He is anxious to pull out the speck from his brother's eye, but sees not to remove the beam out of his own.

The Lord hurled His "woes" upon the hypocrites while showing His compassion on the multitudes, the publicans and outcasts. It is told how He rebuked the self-appointed judges of a harlot; how, when His verdict, silently written in the earth, had sent them away ashamed, Me turned to the woman and said, "Woman, where are those thine accusers? Math no man condemned thee?" And when she replied, "No man, Lord", He said, "Neither do I condemn thee. Go, and sin no more."

These Divine words and acts often stir us but for a moment, after which they leave our minds complacent, smug, and self-satisfied. And when forgiveness is needed, we are slow to grant it; or grant it in words, but not in spirit. It is our human tendency to nurse the wrongs we may have suffered until they grow out of all proportion; to conjure up imaginary motives and suspicions; until at last we may come to live in a world of fanciful fears.

We may misread the intent of the Lord's words, "He that is without sin among you, let him first cast a stone at her," and turn this to mean that evil is so universal that it cannot be avoided and is no longer a sin! This is the false "broadmindedness" which springs from our own indifference. And it is not forgiveness of sin - but a partaking in the sin. Forgiveness does not mean approval of an evil. For what we hold allowable, and defend, that we do in our spirit and would do in act if opportunity offered.

But although the duty of forgiveness is often twisted into an excuse for evil, the duty still stands. Forgive the sinning brother - not seven times but seventy times seven! Forgive the man who sins - but condemn the evil itself. We must aid the man, but abhor and oppose the evil which we think he has. Love your enemies, pray for them that despitefully use you and persecute you. We cannot help a fellow-man to overcome his faults if we condemn him and withdraw from him that sympathetic encouragement to good which is the sustaining thing in the life of every human being. Yet we must guard against companionship with those who appear confirmed in the evils of life and in the falsities of such evil. We must indeed watch lest we hurt the souls of others by withdrawing our love from them when they need it the most when they are in states of temptation. But we must guard first of all the health of our own souls and our children's, lest we compromise with evil.

All true freedom is rooted in charity and truth. The intolerance which condemns first and inquires afterwards strikes at all that is most precious in human society. The hells center their efforts in exciting men's minds to hate and envy his neighbor's person, but to love and applaud his evils so far as they do no harm to themselves. The angels love man as a brother while they strive to bend his affections away from evil and to encourage him leading him in freedom according to the reason and faith that he has; even, if necessary, excusing and defending his evils and falsities so far as these can be bent toward what is good.

And the man who is in charity also is forgiving. He looks not for the evils of others but for their goods and truths, and inclines to put the best interpretation on their faults. He does not publish the errors of others unless this becomes imperative knowing that public accusation provokes a man to defend and confirm his evil. The man of charity allows for the fact that men's evils may be due to their being immersed in states of temptation; and may not be confirmed, but are excusable by ignorance, or by simplicity in which something of innocence may still abide.

Yet even the regenerate man cannot deny to society and the State the right to protect itself by punishing evil-doers. For as long as men actually identify themselves with an open evil, no one, even the most forgiving, can show them the charity that is in his heart without harming the uses of others, to whom we also stand in debt.

Thus we pray, "Forgive us our debts, as we also forgive our debtors."
We owe so much. Life, freedom, possessions, knowledge, happiness - nothing is from ourselves, all is a debt to God and to our neighbor. And there are those who are debtors to us; who depend on us for the means of happiness. Love makes us debtors unto one another. What love gives is forever a bond of mutual debts. The greater the debts, the stronger is the love. But love does not clamor for payment. It forgives the debt cancels it. Love says, "No, you owe me nothing, nothing in return." And if there is a response, none the less, love regards it as a new debt, for which it asks - and receives - forgiveness.

Thus the bonds of love multiply into a more and more complete reciprocal conjunction. And this can best be seen in the love called truly conjugial, which descends from the heaven of innocence. There the debts of the man to the woman and of the woman to the man balance into an eternal union, even as love and wisdom are balanced in their angelic minds.

But we find an image of this conjunction in the whole Divine economy of creation. There is no charity, no true friendship, no love of use, no field of duty, which does not create its debts, which dawn but gradually upon us. At times we may feel overwhelmed with duties we can never accomplish, with needs which we are unable to fill, with increasing obligations beyond our ability to repay and debts we cannot return. We do not all rise to an equal purity of love or to an equal understanding. And so we ask forgiveness, relying on the love which others are willing to extend, and - supremely - on the love of God. And love - being love - will understand and pardon.

Without such a frank trust in others, and such a mutual confession of constant failure, human life becomes a scene of morbid fears and repinings which would threaten our uses and our sanity. It must be taken for granted that in the performance of uses all have their limitations and all - men and angels - are debtors to each other. If men were conscious of this bond of indebtedness, how much easier it would be to approach the problems of the world's work. The Church is established as a more protected sphere where this law of love can be re-established, a more closely knit circle where loves and uses are spiritual and the Lord, not man, is acknowledged as their source. But the most perfect communion of all is found only in heaven, for there all regard themselves as debtors and servants.

The giving and the return seem at times unequal. But the Lord knows otherwise. For the internal reception of love is only according to the return. Only when we return love for love can we really receive love. Only as we forgive can we be forgiven.

<<<

== TEMPTATION

And lead us not into temptation. Luke 11:4

The prayer which the Lord taught His disciples to pray comprehends in a summary everything of spiritual life, more than even the heavens can ever come to understand. It contains every rightful human aspiration which men to all eternity can entertain. It is - like all the Old and New Testaments - written in the language of appearances. Yet its words are spirit and are life, full of hidden wisdom which only the humble heart can discern.

When we ask our heavenly Father, "Lead us not into temptation," it is an acknowledgment that nothing happens by chance, but that the Lord's governing hand is over all. He takes account of all things, and makes use even of evil conditions, when they arise, so as to turn their effects into an eventual good. The appearance therefore is that the evils which come upon us - not only the tragedies which result from man's wickedness and disobedience to the laws of God, but also the accidents and misfortunes, the famines and pestilences, for which men cannot be directly blamed, are punishments sent by God. So long as men are evil it is necessary that their first idea of God should be that We rules with unlimited power, rather than that He is all-forgiving and merciful. Thus the Lord appeared to the Jews to be angry and jealous; and He told them through Isaiah: "I am the Lord and there is none else. I form the light and create darkness, I make peace and create evil. I Jehovah do all these things." (Isaiah 45:6,7)

And now we pray, "Lead us not into temptation. "We know that the Lord, who is Love itself, would never lead us into situations of peril or temptation, and that He is not responsible for the evils which infest us. But we must also acknowledge that the permission of evil is a law of God a law of the greatest mercy, since it allows for human freedom. Evil is never the Divine Will, but human freedom is. Temptations are evils which come upon us from without, and seemingly without our seeking, yet with Divine permission. Temptation is a spiritual struggle, forced upon us by evil spirits. yet the Lord still controls and modifies, restrains and permits, according to His love and wisdom, and therefore we pray Him to protect us against the snares and cunning of the hells. For when we thus approach the Lord for help, the evil of the temptation may be turned into good.

It is man himself, who unwittingly invites temptations. The complex thing which we call the human "heart" presents many contradictions. It may surprise us with explosions of bestial cruelty and uncleanness which staggers our reason, or with generous impulses of which we did not think it capable. For man is only a vessel of life, an instrument responding to the inflowing moods of all manner of heavens and hells. He is a vessel composed of many faculties, degrees, and receptacles. His proprium is in itself wholly perverse and easily inflamed by evil spirits with vainglory and vengence, with sensuality, avarice, envy and lust for power. These evils are indeed tendencies of the heredity that lies slumbering in him until aroused and made his own. Yet over against these, man has also an understanding in which a conscience of truth can be built up from the precepts of the Word and its revealing doctrine.

And doctrine teaches that if man believed and acted from the truth that every good and every truth which is felt or acknowledged in his mind are really from the Lord through heaven, and that every evil and falsity that springs up as his own will and thought are in reality from the influx of hell, he would neither feel pride in the good and thus make it meritorious, nor would he appropriate the evil to himself and thus identify himself with it (@DP 320).

It is in order that this saving truth may be impressed upon man's mind that he is permitted to come into states of temptation - in which he feels the conflict of good and evil within him, and thus may recognize that he is neither good nor evil but a vessel receptive of their influx: that he is bonded to neither, but has the freedom to choose what he shall become.

Even when a spiritual conscience has been established as a new will or, as he feels, a "better self," within him, the old proprium is still active, unconsciously influencing his affections and thoughts, causing him to make light of his spiritual responsibilities and turning even the appearances of truth into excuses for his own misdeeds. It is this subtle revolt of the unregenerate natural man which gives occasion for what is called temptation the spiritual temptation referred to in the Lord's Prayer. For this prayer does not refer to the many hesitations, doubts, and tribulations which are caused by the disappointments, dilemmas, and fears of natural life. A man who is devoid of a spiritual conscience feels no struggle between the spiritual man and the natural. If he is harrowed by doubts these concern his self-advantage or reputation, and whatever he decides is from his natural proprium. The remorse he might feel when he realizes the unfortunate consequences of his crimes or vices is not a distress of conscience, but the result of fears and of the conflict of divergent natural affections.

The Writings indicate that in the Christian world today, few are permitted to undergo spiritual temptation; for in a consummated church spiritual truths are so transfused with various falsities that there could be no resistance. Yet it is true that in every religion men can be saved by living uprightly according to the teachings of their church. And if the ambitions of the world come to dominate them the Lord permits that their self-confidence be broken by misfortunes and sickness, and hardships of natural life, so that something of spiritual good may affect them. Such tribulations, however, are not spiritual temptations, but natural trials (@AC 762, 8164).

And since we cannot judge of our spiritual state, nor measure our inner strength or know the power of the hells, we must all pray, "Lord, lead us not into temptation." It would be presumptuous for us to invite temptation of any kind, natural or spiritual. We are not to seek contact and intimacy with evil. We are to shun evil and do good, do justly, love mercy, and walk humbly with our God. If we court temptation with pride in our supposed power to resist, we are defeated before we begin.

There are those who misunderstand even this simple truth, and who cloister themselves away from the world and spend their time in prayer and fasting. Such do not know that they cannot flee from their own proprium except by forgetting themselves in the sphere of uses to others. It is through the uses of our calling and the obligations of our domestic life that the Lord can best protect us from temptations which we are not equipped to meet. The idle hand and the idle mind are ever most receptive to the influx of evil spirits. Certainly we are to shun pleasures or companionships which we see doing us spiritual harm. Certainly we need to guard ourselves and our dependents from contacts with evils and falsities, which like the leaven of the Pharisees would poison and corrupt our thoughts. "Watch and pray," the Lord forewarns,
"lest ye enter into temptation; for the spirit indeed is willing, but the flesh is weak" (Matthew 26:41). Yet where our duties call us, the Lord will protect us. For there He leadeth in the paths of justice and will set a table before us in the presence of our enemies.

A regenerating man cannot shirk the temptations that come to him in the course of duty. If laid on our shoulders we cannot refuse the cross of temptation. "Whosoever will come after Me," the Lord said, "let him deny himself, take up his cross, and follow Me." "Think not that I am come to send peace on earth, but a sword..."

But spiritual courage does not do away with either fear or caution. A coward is of course controlled by his fears, while a brave man's fear is placed under the control of his reason. We are allowed to pray that we be excused from drinking the cup of bitterness; but if it is placed in our hands we must say with the Lord in Gethsemane, "Not my will, but Thine, be done." Temptation, or the contact with evil, is never the Lord's will. But the way which leads through temptations, is still the Lord's way.

Because man is infected with hereditary and actual evils, it is indeed necessary for him to undergo temptations in order that his rational mind may be subdued and become spiritual (@AE 654[62], 730:31). The lusts of the loves of self and the world can be broken only by means of temptations. Without victory in temptations man cannot be regenerated, nor can he enter into any new enlightenment (@AC 5036; @HH 194). Hence we are taught that the great multitudes of spirits who are in the good of life according to religions in which there are no genuine truths, undergo temptations in the other life; whereby their falsities are shaken off and truths implanted. And those who are let into such temptations, or vastations of falsity, are all saved. Even those who die as infants and are therefore educated in heaven, are admitted into a species of temptation as they grow up, by being brought into contact with spirits in the world of spirits (@AC 3407; @HH 342; @SE 3548).

Although it is inevitable that temptations must he endured, and must be faced when they confront us, men have no obligation to seek them out. Man has a simpler duty - to cultivate an aversion to his evils because they are against the Divine will and precept. It is on man's life of daily repentance that his salvation depends. His exercise of free choice, his recurrent resistance to the lure of some evil longing and his acts of self-compulsion to do what is just and right and learn what is true and good - all take place in the conscious externals of his thought, and are not what is meant by spiritual temptations. Yet they prepare man for victory.

The real battles of temptation are not fought by man. They are combats between evil spirits and angels for man's soul; and while they go on, man grasps scarcely a thousandth part of the battle, for he is then in so bewildered and obscure a state that he can only vaguely sense the spiritual issues that are at stake. He feels an inward anxiety because he is being let into the states of his evil proprium - into an unbearable consciousness of his faults and of the sins of his past. Evil spirits then suspend his power to think from his own faith and to will from his own love, that is, from his spiritual conscience. They intercept his communication with heaven, insinuate scandals against truths and goods, taunt him with hypocrisy, raise scruples of conscience about unimportant things to accuse him, and take away his delight in truths, insinuating doubts even about the Lord's presence and aid (@NJHD 196).

In this mood he is crushed in spirit, comes into deep despair and even bitterness. And this is aggravated if the temptation is accompanied by ill health, by a loss of honor, or by worldly failures. The keener a man's conscience is, or the greater his inward love for the spiritual things which are endangered, the more grievous is the temptation.

Yet the temptation must run its course. The Lord in His mercy overlooks man's indignations and remonstrances, but He cannot often attend to the desperate prayers of those who are in temptation (@AC 8179). Instead He is fighting man's battle in the spiritual world. There His angels draw forth the interior contents of the truths which the man still clings to but only superficially understands. And man, feeling himself forsaken, does not realize that the angels are using these truths of his own faith as weapons in this spiritual combat. For the interior ideas within those truths can meet and defeat the interior evils which the devils have sought to impute to the man - evils such as man never dreamt of but which were lying latent as logical implications within the external evils of which man had been guilty, or as hidden lusts within his unexplored heredity.

In states of temptation, man will not profit by relying merely on prayer or giving up his active life of use. Yet the temptation is not over until he comes to acknowledge that from his own power he cannot desist from evil or penetrate the subleties with which the hells obscure his mind. His pride of self must be broken, and he must see and confess that the battle is the Lord's (@NJHD 187-200).

And the Lord - in His second advent - has now uncovered and rendered impotent the designs by which evil spirits seek to beguile men's minds and extinguish what little sparks of spiritual love may still burn in human hearts. He has provided His church with an armory of faith against the hours of temptation.

For the time is coming when spiritual temptation will again and increasingly become the means of opening the channels of influx from heaven. During temptations, man, being in externals, perceives only the evil things which the spirits inject. But when the combat is past man enters undeserving - into the fruits of victory. His spirit is admitted among angels, and joy and consolation inflow and fill even his natural mind which is humbled and content. His cup of life runneth over. And of him who holds fast to the Lord during temptations, this promise is given: "Him that overcometh will I make a pillar in the temple of My God, and he shall go no more out; and I will write upon him the name of My God and the name of the city of My God, the New Jerusalem which cometh down out of heaven from My God: and My new name."

<<<

== DELIVERANCE

But deliver us from evil. Luke 11:4

Man's whole life is a struggle for deliverance from evil. He is born in unconscious bondage to evils of which he is made aware by degrees. No man can rise to any truly human qualities except by subordinating his selfish instincts and rebuking the thoughts which revolve about himself as a center. This is commonly recognized. Yet it is not generally acknowledged that of his own power man cannot defeat the love of self; nor is it realized that merely social motives can only sublimate that love into a subtle self-respect.

Therefore the Lord teaches us to pray for His help to deliver us from evil. Yet even when men pray to be delivered from evil, they mean - all to frequently - only the pains and dangers of natural life or the consequences of their own mistakes. They want to be protected against the disease and wants which are unpleasant to the flesh and that trouble the mind. The heart of man constantly yearns for worldly security; and the heavenly Father knoweth that we have need of these things. But what the Lord teaches us to pray for is shown by the context of the prayer: "Forgive us our debts ... and lead us not into temptation, but deliver us from evil." It is from the evils aroused in our own heart and spirit that we must ask to be delivered.

The Word tells of repeated deliverances of mankind from evil. Noah was delivered, by Divine instruction, from the Flood of Sin. Lot was delivered from the corrupt city of Sodom, the Israelites from Egypt and from other oppressor nations, and from the captivity in Babylon. At the Lord's first advent His followers were delivered from the yoke of the Pharisees. And by His second coming, the dominions of a spiritual Babylonia and of the Dragon of "Faith Alone" were overthrown in the spiritual world, in a new and final judgment.

But the Lord labors still, every moment, to deliver us in secret ways from the evils which we have invited. At times men recognize such Divine leading as special interventions of a merciful Providence. But they seldom reflect that the Lord's government is constant, and present in the most trivial events of every human life.

The aim of Providence is that men should be held in spiritual freedom. The word "deliver" is related to the word "liberty". Liberty, or free agency, sets mankind apart from brute creation and marks the way to spiritual progress. "Ye shall know the truth," the Lord said, "and the truth shall make you free" (John 8:32). Yet the spirit of man requires more than merely civil liberty, more than the cultivation of natural truth and learning such as men now boast of. It is an "arcanum" revealed to the New Church that the spirit of man, even while he lives on earth, is unconsciously also an inhabitant of the spiritual world and is present although not visible - among spirits and angels. The interiors of his mind are secretly affected by the angels of the three heavens. His sensual nature is moved and influenced by spirits and by devils. But his rational mind, whereby he determines his final character, is held in an equilibrium or balance between good and evil, in the world of spirits which is midway between heaven and hell.

It was to restore and maintain this balance in the world of spirits that the Lord came to earth and, by temptations subjugated the hells within Divine laws of permission, and ordered the heavens. For the same reason He made His second advent, by a revelation of the spiritual sense of His Word, by which He completed the basis on which human freedom could be assured henceforth.

By this last judgment, which was predicted by John on Patmos and actually witnessed by the Seer Swedenborg, the strongholds of evil spirits in the intermediate world of spirits were dislodged, and well disposed spirits who had fallen under the influence of the evil were released, instructed, and set free to find their heavens and enter into spiritual usefulness. On earth, the repercussions of that great spiritual liberation became observable as a remarkable growth of religious liberty, of freedom of thought, and as the dawn of a new age noted for increased communication and external progress among men. The New Church was established, as in heaven, so upon earth. And henceforth every spirit who enters the world of spirits through the gate of death is free to receive instruction in the way to heaven, and is delivered from the bondage of falsities and evils - unless he prefers their rule.

The redemption of mankind has been effected. Yet still we need to pray,
"Deliver us from evil"; or, as the Greek phrase may be rendered, "Draw us out of evil!"

Even though man's rational mind - under the laws of Providence - is free to determine his real character and choose his final destiny; yet his native, inherited will is immersed in hell. The perverted love of self is from birth engraven in the fibres of his sensual and corporeal mind, into which the hells pour their passions and cruelties, their lusts, enticements and delights. Man's reactions and feelings are not always rational, but may burst forth from hidden depths of unmastered emotions. His understanding may be free to progress in the pursuit of truth, and his good intentions may bear fruit in a life of usefulness; and yet the submerged self of pride and of brooding rebellion and bitterness may still remain, unamended within. And then, whenever the natural man acts apart from conscience, or apart from the spiritual, evil comes forth! comes forth in its naked ugliness, or comes forth rationalized by excuses or disguised by seemingly good works and adorned with the pleasant things of sensual beauty and corporeal pleasures.

Evil is sometimes thought of as sporadic and passing, like crimes of sudden temper or like infectious diseases which strike and vanish. Many regard evils as mere blemishes, or as errors due to ignorance or environment. But the evil from which we pray to be drawn out is none of these things, but is a love - a steady motivation and lingering purpose. It can be recognized by certain signs: by contempt for others; by a desire for revenge; by envies or by inordinate hankering for the goods of others or for the wealth of the world; by seeking to profit by fraud or dishonesty; by claiming merit for oneself and by ingratitude to others; by the wish to take away the inner freedom of others; by domination; by deceit and unscrupulous cunning; by morbid self-pity; and by an interior impatience with the spiritual truths that teach of man's duties to God and his obligations to the neighbor.

By these signs, which become all too plain if man explores himself, every one may be convinced that his need for deliverance is great. For even when man disowns an evil love, it remains with him. Salvation consists in man's withdrawal from evil, and his being held in good. And this can be done only by the power of the Lord.

Man can indeed shun an evil which becomes obvious to him. But no one evil exists alone. Evils are bound up with each other into a monstrous whole which the angels think of as a Grand Monster and which the Scriptures speak of as the Devil or Satan and symbolize as the ancient Serpent or Dragon. Taken together, all the hells are a parody and a bestial perversion of the human form of the Lord's kingdom. Every society of hell is the abode of some specific evila human virtue twisted out of shape. Yet every evil is entangled with other evils, and organized under the two ruling loves of hell - the love of self and the love of the world.

"Man, from his birth, is in the midst of infernal societies" (@AE 1163). It is his inborn love, inherited from forebears, that is there. When he later dilates his evil affections, he extends himself into these societies. From them he draws the delight of his life, as a babe sucks milk from its nurse's breast or a tree draws sap from its roots; and without this influx he would indeed wither away (@AE 1162). Thus it is clear that no man could of his own power disentangle himself from hell.

This is the reason why we must beseech the Lord, in prayer, to draw us out from the evil that holds us in its grip; and why we must renounce the old man so that the Lord may create a new man within us.

This new man or new will is born in the rational, which is formed above hell, in the sphere of the world of spirits, where man is free. By this rational understanding man can extend his thoughts and affections into all the vistas of the spiritual world, thus also into societies of heaven. With an infant, who cannot think from reason, the Lord mercifully closes off the evil will, although it yet acts as a conduit which adapts the inflowing life to his sensual man. And the infant is surrounded with impenetrable spheres of innocence, to prevent the excitation of the native will until the understanding is formed.

When man comes into the freedom of his own reason, his spirit walks freely through the many societies in the world of spirits, where heaven and hell meet. In his thought he can separate himself from his native will, and extend his life as from a central society where he abides. As he traverses the mental world, with invisible companions on all sides, he becomes attached as by elastic cords of sympathy with various spiritual associates. These attachments measure out and limit the space wherein he can move, still he feels in perfect freedom. Although bound, his mind walks free, as his chosen affections dictate. Yet in all his wanderings, "the Lord leads him as if by the hand, permitting, but withholding so far as man is willing to follow in freedom." Man's own affections tend to draw him into infernal societies, into dark, deceptive morasses of falsities and into pungent jungles of unworldly and angry emotions; but he can still be led forth by degrees if he looks to the Lord, who knows the road out of hell. If man knew these roads he might wish to lead himself and return to evil in the persuasion that he could always escape again (@AE 1174).

Man can never know the intricate pattern of life. Too great assurance never finds the way to heaven. But - the Doctrine tells -- "it is enough for man to learn truths from the Word, and by means of truths to learn what good is, and from truths and goods know what evils and falsities are, so that he may be affected by truths and goods and not be affected by falsities and evils..." (@AE 1174). Only when a man knows truths and loves them, can he see evils and falsities as something outside of himself, as something coming from hell even when they seem to well up from his own heart. Thus the Lord can "lead man in freedom ... in opposition to himself" (@DP 211).

The Lord delivers us from evil by bending our affections to love truths. From this love man can freely desire to shun the evils of his own heart. Under no circumstances can evils be removed from man unless he resists them as if from himself (@AE 1164). Yet in every case, the withdrawal of man from his evils is the work of the Lord alone. Man gives his consent by exercising self-compulsion. If this be lacking, or if it be relaxed, the evil remains, or returns. Man's part is simple, touching only the conscious surfaces of his mind. The Lord's part is infinitely complex involving the simultaneous government of all the societies of the heavens and the hells. Every man, yea, every angel also, would from his own proprium gravitate into the lowest hell, unless the Lord continually withdrew him and uplifted him. And this can be done only by gradual separations, such as we see pictured in the marvelous processes by which the interiors of the human body are constantly and secretly purified from harmful things, which in turn are made to serve for digestion and tempering. For the Lord tempers the states of spirits and men, permitting the evils of one to counteract the excesses of another, diverting their natural affections toward a lesser evil whenever they cannot be bent toward good.

Yet the Lord never expels evil by evil, but removes evil by good. This law men find it hard to comprehend. But it was revealed to Swedenborg while he was praying the Lord's Prayer (@SE 1878). In the Lord's sight, evil is as an utter nothing (@SE 3939). His kingdom is a kingdom of uses in which even the devils are unconsciously contributing to the ends of creation. For even they are drawn to perform uses - however vile and lowly; and this from necessity and from natural bent and for the sake of honor and gain (Love xvii). And while so occupied they too are in a sense delivered from evil.

It is by the good of uses that the Lord liberates man from self-centered thinking and leads him into the redeeming currents of the Divine providence. It is in the process of adjusting oneself to the manifold needs of others that new affections can be born and a wider point of view be established. Selfish ambitions lose their glamour; the raptures and vanities of yesteryear begin to seem absurd and hollow; the illusions of inexperience pass away, unmourned.

Yet this deliverance from the chains of the past, and the breaking, one by one, of the thousand cords that hold man dependent on the hells, are possible only by a persistent shunning of new evils as sins against God; new evils of a subtler kind which he discovers and resists while he seeks to merge his life into that of his family, his community, his profession, his country and his church. And all the while his regenerating spirit is being inserted into heavenly societies, by the sphere of which the interiors of his mind are touched with self-less delights, inspired by the vision of eternal uses, and stored with heavenly treasures - angelic societies to which he is attached by a common love of spiritual charity.

For where the treasure is, there shall the heart be also. Deliverance from evil means more than an empty freedom. It means new loyalties, new bonds of one's own choosing. It means a spiritual home, a place in our Father's house, wherein the Divinely taught prayer is fulfilled: a heaven of mercy and freedom where the Lord's truth rules and His will is done, as in heart so in life; where there is no lack, and sin is forgiven and temptation removed and the love of truth has made us free from the allurements of evil; a heaven which is His kingdom, established by His power for our salvation but to His eternal glory.

<<<

== THE KINGDOM, POWER AND THE GLORY

For Thine is the kingdom and the power and the glory, for ever. Amen. Matthew 6:13

The Divine end and purpose in creation is the formation of a heaven from the human race; a heaven wherein men may attain to final happiness by entering into the uses of the Lord's kingdom, having renounced their selfish striving after their own futile ends, acknowledging that all their power is from Him alone, and giving to Him alone the glory.

It is this kingdom for which men pray while addressing the Lord Jesus Christ as the Divine Human and as the heavenly Father and the origin of all good and all truth. Each petition in the Lord's Prayer when spiritually understood marks a further step by which this end can be fulfilled for the regenerating man and for the church.

Man's own end in life is the pursuit of happiness. This is what he instinctively strives for, each man in his own fashion and whatever be his ruling love. Yet it recurs continually that this happiness which he tastes for a moment melts away and eludes his grasp. The visions which we men create in our imagination often dissolve in the light of day. The kingdoms which we build up with centuries of toil and reasoned foresight may in time turn into tyranny or confusion. The joys and pleasures for which our hearts may hunger are often found too transient, or grow dull. For man can make nothing that is lasting and, still less, eternal. The heavens that he makes for himself are such as pass away. No human love however ardent, no prudence, no wisdom of man, can create happiness.

The truth is simple. The kingdom and the power and the glory are the Lord's. Just as physical and mechanical power is made available to men only so far as they take advantage of the pre-existent natural laws which they have discovered and formulated, so spiritual power is given to men and angels only so far as they follow the Divine laws of love and charity, of faith and use, which are impressed from creation upon every human soul and which are revealed to our minds in the Word of God and perceived in states of innocence by those who are poor in spirit.

When the Scribe of the Lord's Second Advent asked certain celestial angels how they had found a home in the inmost heaven, they replied that in their life in the world they had shunned filthy thoughts, frauds, revilings and hatreds, and thence come to love chastity, sincerity, justice and truth; but that they perceived that when evils had been put away and they acted as if from themselves from love of the neighbor, it was done not from themselves but from the Lord; on which account they had been raised up by the Lord after death into the third heaven (@AE 902[4]; @DLW 239).

The Lord alone can introduce man into heaven. Man can indeed make for himself imaginary heavens, or lead himself into the false heavens which evil men and evil spirits continually endeavor to construct to satisfy the sensual longings or please the selfish prides of men. But the angels know that the Divine of the Lord is what makes heaven. The kingdom of the Lord is therefore likened to a vast human form - a spiritual organism of uses and functions - which is in the image and likeness of God, and thus is a Grand Man. In its inmost aspect, this Grand Man is infinite and eternal and identical with the Divine proceeding from the Lord's Divine Human. So regarded, it is the Divine of Use, the infinite harmony of all the ends and purposes of Providence; an infinite composite which does not consist of persons but of the potential uses which the Lord foresees and seeks to provide uses through which mankind on the countless planets can come to partake in the joy of the Divine creation, world without end (Love xiii:3, 4, vi.: @AE 1115[5]). So viewed, the Grand Man of heaven is purely Divine, and is indeed the Body of the Lord, perfect and glorious in its Divine Humanity; in whom we are to abide as the branches abide in the Vine; and in whom we live and are moved and have our being.

So far as we willingly cooperate with the laws of Providence, our souls can be brought into uses of love and charity and find a place within that infinite heaven which is the Body of the Lord. By the finite uses men perform they can become instruments in the Lord's hands for Divine uses of which they are unaware, and thus be conjoined with the Lord. It is so that the angels also come to constitute a Grand Man which is the image of the Divine Man. In this heavenly Man the Lord is the life and Soul; for nothing of life is from man or angel. And nothing human can be of eternal use unless the Lord gives it a place in the pattern of His Divine uses wherein all things are reconciled. To Him alone belong the kingdom, the power and the glory. If we felt that it were not so: if we could not add our "Amen" to this confession; then the purpose of our prayer would go for nought; for we would then be persuaded that our own arm could save us and that our own mind could create a heaven for us.

"Thine is the kingdom!" It is the law which makes a kingdom. And the creative law of heaven is the Divine truth. And as the love and mercy of a kindly monarch are shown by his laws, so the Divine truth reveals the infinite love of the Lord. Love makes heaven by means of this truth. "By the Word of the Lord were the heavens made."

The Heavenly Doctrine discloses that as a first projection of the Lord's love towards creating a finite world, there came into being a spiritual Sun, as an origin of spiritual heat and spiritual light. From this Sun and through atmospheres going forth from it the Divine love radiates as Divine truth, to be received by angels and men in this accommodated form. As light, this proceeding truth enables the eves of the angels to perceive the spiritual objects around them. As heat, it inflows into their souls and gives them the faculty to will and understand. The angels of the "celestial" kingdom of heaven receive the Divine truth immediately into their hearts, or into their wills, and feel it as an influx of good. The angels of the Lord's "spiritual" kingdom receive the Divine truth into their understandings and are conscious of it as truth. With the celestial, the truth received into their hearts endows them with a power which nothing in the created universe can surpass. With the spiritual, the truth which makes them intelligent also environs their whole heaven with a glory and a magnificence beyond the dreams of mortal man. But all these angels, celestial and spiritual, confess with joy of heart that nothing of the power which they can exercise or of the glory with which they are encompassed is from themselves, but that both are to be ascribed to the proceeding Divine truth.

The power of the celestial angels is manifold. They serve as the media through which the Lord inflows with love into the lower heavens. Their moderating influence, though unobserved, permeates the heavens. Before their sphere the most arrogant infernal crew will cringe and flee. Their power of understanding anticipates the ordinary processes of reason and is therefore called "perception", by which they immediately judge of right and wrong and see a complex of truths in its universal perspective. Their power of enjoyment is so acute that they are capable of an intensity of happiness such as man cannot approximate. Yet should a celestial angel ever become conscious of these powers, his concern would only be to thank the Lord for being able to transfer to others what belongs to himself (@AE 79). For this is the root and secret of spiritual strength. Such power is given only to those who are in the highest form of charity and are able to love others more than themselves. This mutual love inflows from the Lord whenever the celestial heavens are allowed to draw nigh. It comes as a sphere loaned by heaven to men, and without it our race would perish. It is seen in the caress of a mother's hand and in the mutual touch of married partners. It is represented in certain human acts of great significance, such as the laying on of hands in baptism, ordination, and blessing. For touch carries with it something of the celestial power of transferring to another what is in oneself.

But these angels know that the power of mutual love is not from them. Long ere mankind was born and the celestial heavens peopled, the Lord poured out His sphere of mutual love and by it governed the wild beasts of the forest and plain, who blindly followed their mating calls and their herding instinct. The celestials know, as none better, that the power that moves the world is love, and that the source of love is the Lord alone, who - even after men refused and perverted His better gifts - persists to lead them by bending their natural affections to serve the heavens which they had spurned.

His is the kingdom and the power; but also the glory! Among the spiritual angels, the Divine truth is evidenced not so much by power as by a glory which makes the very air sparkle with brilliance. This same glory is seen in the palatial abodes of these angels and in their temples and gardens, their food and their garments. The inmost heaven has the beauty of natural simplicity, but in the spiritual heaven there is the ornate magnificence of art, always proportioned to the intelligence of the angels and the uses in which they excel. All things seem to laugh, to play, to live before their eyes. But to the angels these things of glory and honor are only the representative tokens of that glory which created the heavens. Their heaven is to them a world of Divine truths - truths under the appearance of grace and beauty. They do not think of these outward things, nor enjoy them for their own sakes, but see in each new flower and in the precious things of wealth and in the shifting harmonies of colors, sounds, and forms, an inward meaning, a message of spiritual significance which teaches them of the Divine things which flow into their minds and fill them with delights and which enable them to serve the neighbor with truer sympathy and deeper understanding. Eye hath not seen nor ear heard, the things which God hath prepared for them that love Him.

We are apt to think of heaven from externals, as another more perfect natural world. We need often to remind ourselves of the Lord's words,
"The kingdom of God is within you." It is a mental, spiritual world, wherein we dwell even now, amidst imagery which appears like that of nature; but which displays only the states which we choose to foster. If our minds are blind to the virtues of others, or insensible to the delights which come from a spiritual communion with others, or if we cannot be kindled by the inspiration of new truths, new perspectives of uses that may perfect society, then we will never be able to see how "the heavens are telling the glory of God" the palaces of heaven, its verdant gardens, and its springs of living water. But men and angels may partake of this glory and of the power of God so far as they are willing to shun the evils which obscure the truth. If man wills the good of another and wills to transfer to the other as much as possible of what is with himself, he will be given spiritual power, which he exerts as if it was his own. If he wills to turn his intelligence of truth into service to God and man, so far spiritual glory will shed its beneficent light of charity and friendship over his life along with the gains and honors of uses done.

The Lord is constantly leading man away from mere appearances and toward the inner realities. For man's road to heaven is devious, leading through many apparent heavens of illusion and phantasy. The kingdom for which he prays is not always the Lord's. The name he desires to hallow is not always that of the Divine Word. The bread for which he petitions is not always that for which his state is ready. He asks forgiveness while hatred and envy still smoulder in his breast. With his lips he prays to be excused from temptation although his wandering gaze is still seeking it out. He cries, "Deliver us from evil," yet is blind to his own faults.

Nevertheless, whenever man stumbles, the Lord seeks to raise him up, providing him with the revealed Word as a staff and a lamp; when man falters, the Lord gives him a new vision of paradise as if it were closely ahead shows him a glimpse of the glory and power of heaven. Yet, so long as a man looks upon this heaven as a regard to be earned by his own merit, he can see only the portals of the kingdom, the outskirts of paradise. He sees only the natural heaven, where salvation indeed awaits, but not angelic life in its power and glory. For to follow the Lord for the sake of reward brings with it the seeds of self-glorification and blindness, which detract from the contentment of angelic life; the contentment which springs from a knowledge of self and from a profound humiliation such as is expressed in the words that are added to the Lord's Prayer in the Gospel according to Matthew: "For Thine is the kingdom, and the power, and the glory."

Therefore the Lord does not cease leading man onward through the ultimate heaven into the spiritual and, if possible, into the celestial state itself. And this is the reason why the Lord has now come "in the clouds of heaven with power and great glory," revealing the spiritual and the celestial meanings hitherto concealed in the Holy Scripture: and has raised up His New Church, the New Jerusalem, the crystal city of Truth "having the glory of God." (Revelation 21:11)

Power and glory are from the Lord's proceeding sphere of Divine truth, creating, preserving, and rejuvenating all things. In the literal sense of the inspired Word this Divine truth takes a fixed and final form. The Lord is there present in the holy ultimates of His own order with the power of salvation; and the sacred words are full within the glory of the spiritual sense. The internals of the Word, in which the Lord stands forth before the angels in His glory as the Divine Human, are now disclosed through the Writings to man's rational sight. And so far as man receives the Lord's influx through his spiritual mind into the rational and through this into the ultimate truths of the Word, the power latent in the Word is released for his use, and the glory of the Lord will enlighten him and dispel the illusions of self-power that hide heaven from his view (@AE 726).

It is easy to acclaim the doctrine that all power and all glory are the Lord's alone. yet when we fall back into natural thought we think of our power and glory as our own. They who are wise will thank the Lord from their hearts that it is not so. For they know that if angels or men had a whit of power from themselves, the heavens would fall and hell would become a chaos and every man would perish on the earth. If the Lord's hands were withheld for a moment, every man would seek his own glory and the restraints upon evil would be unloosed. But the Lord is king of all the world. He orders the paths of our thought while we are unaware, lest we should cast away our precious gift of spiritual freedom He hides our enemies with the cloak of His providence lest we surrender without resisting. He instils His power into our nerves and tissues even though we clench our hands in sullen wrath against His heaven. And when we are near to despair over our iniquity and weakness, He throws the rays of His glory over our undeserving lives.

What can we do to acknowledge His mercies? For He is weary of vain oblations and asks not for burnt offerings. The heaven of heavens is His. What can we do but follow where He leads, to accept what He offers, and to worship Him in silence of heart. For His is the kingdom, and the power, and the glory, forever.
