= Externals of the New Church
A Series of Doctrinal Classes by the Rev. Hugo Lj. Odhner.
include::../template-attributes.adoc[]

////
Preface 0
I. Relation of Internals and Externals 2
II. External Uses 9

Uses of the Church 13
III. Order within the Priesthood 18

Organization of the Church 21
IV. External Worship 27
V. Public Worship 35
VI. Ritual and Representation 43
VII. Externals of the New Church 51

New Church Home 53
VIII. Externals of Life in Community and Church 59
////

PREFACE

In the twenty-third chapter of Matthew, the Lord rebukes the scribes and the Pharisees for omitting the weightier matters of the law of God while scrupulously observing the external forms of piety and paying tithes even of mint and anise and cummin. These ought ye to have done, He says, and not to leave the other undone. Cleanse first the inside of the cup and the platter, that the outside of them may be clean also.

The Lord here contrasts the internals of the church with its externals. Unless the internal things of religion - charity, faith, mercy and judgment are present within a church, it becomes like a whited sepulcher which is beautiful outwardly but within holds only death and decay.

Yet it is important to note that a spirit of charity and faith existing only as good intentions or as an intellectual consent, will inevitably wane and vanish unless expressed in living acts of faith and in progressive uses of charity. Repentance - which is the first of the church with manmust bring about a new life. Internals must build their own corresponding externals. And a new religion such as the Lord gave to the world created externals peculiar to the needs of Christian charity and Christian faith. For unless new wine be put into new, fresh wine-sacks, it cannot be preserved. (Matthew 9:17)

It is the same at this day. The New Church requires externals equal to its needs if its distinctive spirit is to survive. When the Lord prophesied of the New Jerusalem dispensation, Behold, I make all things new, it referred to a new state in the spiritual world - a new heaven - and a new Divine revelation of Doctrine. Newness does not come from external innovation - for there is nothing new under the sun - but from within - from a new spirit, from a new sphere of affection and thought, a new understanding, a new conviction and a new will. Newness also implies the rejection of that which is false and hypocritical and spiritually dead.

But granting this, nothing new can survive in the garbs of the old so far as these be false and perverted. The New Church must not be content with adopting the external customs, morals, rituals, and forms of the Old Church or of the pagan modern world, but must be inspired to maintain its own externals and increasingly come to a deeper perception of their meaning.

<<<

== I. THE RELATION OF INTERNALS AND EXTERNALS.

We could have no understanding of what a man is, unless we conceive him as a spirit clothed with a material body. Having discarded this material covering, the spirit or natural mind of man survives in the spiritual world and is then found to be a complete man - a soul clothed with a spiritual body. Indeed, it is an error to suppose that a soul can exist without a body. (@DLW 14[e])

And as the case is with the individual man, so is it with the Grand Man of human uses, which appear before the Lord as one. This greater form of man consists of heaven and the church, or - in other words - of the church in heaven and the church on earth. The doctrine states that there is a church in the heavens as well as on the earth, for there is the Word there also, and temples and preachings in them, and there are ministerial and priestly offices. (@AR 533) But the church cannot subsist in the heavens unless there is a church on earth in conjunction with it, because heaven where angels are and the church where men are act as a one, like the internal and the external with man; and the internal with man cannot subsist in its state unless an external is conjoined with it; for an internal without an external is like a house without a foundation, or like seed on top of the ground rather than in the soil.... It is therefore an absolute necessity that there should be a church somewhere on earth, where the word is and where by it the Lord is known. (Ibid.)

The New Church on earth is therefore likened to a body of which the New Heaven is the soul. This New Heaven, which was formed after the Last Judgment which came to a head in the spiritual world in the year 1757, was the internal of the church and was formed before the church on earth. As this new heaven increases, so far the New Jerusalem or the New Church comes down from that heaven. (@AR 486, @TCR 784) But this descent is possible only as the falsities of the former church are removed; and such eradication of falsities must first take place among the clergy.

Thus the church on earth is the external of the new heaven. But the church - as a spiritual communion regarded - also has its internal and its external. The internal of the church - its soul - is the good of charity which comes from the affection of the will, while the external of the church is a good of charity that comes not from affection but from obedience, thus not from the will of good but from doctrine. (@AC 5843)
Those people belong to the internal church who love to do truth for the sake of truth from a spiritual affection, so that they rejoice when they hear truths and think about a life according to them.

Those of the external church also rejoice when they hear truths, for they too love truth for truths sake, but from an external or natural affection, and they do not think about living according to the truths. (@AC 10683)

Again, the man of the internal church attributes to the lord all the good which he does and all the truth that he thinks, and makes internal worship of the Lord from charity the essential. The man of the external church also does what is good, but is ignorant that all his good and truth is from the Lord he has internal worship but feels that the holy observance of external rites must be a chief concern of conscience. And his conscience contains only a few tings, because he knows only few things from the internal sense of the word, while the man of the internal church has his conscience enriched with many things from the internal sense of the Word. (@AC 1098)

Those of the internal church are capable of being elevated into states of interior thought and affection by a withdrawal from things of sense and memory. (@AC 6183) they are led from good to truths whereas those of the external church are prompted to good by loyalty to doctrine, or from a sense of duty, without much delight. (@AC 7840) It should be added, that every regenerating man must first become a man of the external church. Even the man of the external church acts from internals, but only because the good of the internal church affects him by influx. (@AC 5841) With the man of the external church, exteriors are brought into compliance or correspondence with internal things. But the man of the internal church is elevated into interiors and can see exteriors from the interiors. (@AC 6454) Those of the external church are clearly in its externals and obscurely in its internals, while those of the internal church are clearly in its internals and obscurely in its externals. (@AC 8762)

We gather from these and other statements that the two classes of men cannot be distinguished by the amount of zeal that they show, nor by their relative learning or piety, nor by their good works; but by whether they act and think from a sense of duty or whether they act from an inner affection. The former are very many, but the latter are few. (@AC 6587)

Now both these classes of men join in the work of the church on earth. And in order that its uses may be performed the church is of necessity organized externally, as an institution with offices and administration. Thus there arises an external church, a visible body of the church. And this also has its internal and external aspects.

The internal of the organized church is constituted of those who have interiorly studied its doctrinal things, and have confirmed them from the Word. (@AR 398, cf. @AC 10028, @TCR 580) In an orderly church the priesthood should represent such an internal. Yet it must not be thought that doctrine is the internal of the church, but love and the faith derived from it - a faith which embraces all the doctrinal teaching of the church thus the doctrine that is from charity, for this is of life. (@AC 1798)

The external of the organized church is concerned with the administration of rituals and of many things pertaining to the stewardship of the church. (@AC 1795) These external uses are necessary instruments of the internal church, and in them the soul of the church is embodied. The internal clothes itself with things of the natural in order that it may be present therein and lead a life therein. But in order that the internal may thus have a foundation and a receptacle, the natural must necessarily be regenerated. (@AC 6275, 6299)

Externals thus have important and indispensable uses which no rational man can deny. But external things may and do also become a danger. A
man may become so absorbed in externals as to lose sight of the internal purpose or end which they are supposed to serve. He may be so enticed by food or bodily pleasure that he forgets, that food is for the sake of health and that pleasure is provided as a reward for uses. He becomes so fascinated by the machinery of the physical world that be does not reflect on the reason why he is placed on earth. At this day men are often most studious in the fields of their occupation or in abstruse things of science, yet when spiritual goads and truths are in question they feel the subject irksome and boring. (@AC 4096) The astounding progress of the world in science and invention since the Last Judgment has immersed society into such a feverish ambition to perfect external conditions that many thinkers complain that men are in danger of becoming mere robots who know not whither they are going; for while seeking to procure the knowledge to control nature they neglect to study the moral and spiritual truths that might build up a conscience by which they might learn to control themselves.

As the Writings state: At this day man cares not what is taking place interiorly in him, because external things occupy him. And internal things have no importance to one who is wholly occupied with external things, that is, in whom they are, the aims in life. (@AC 5224)

If we reflect on the history of mankind we can easily see that whenever a race or nation or church began to degenerate it was because it separated internals from externals and so immersed itself in externals. This takes place in proportion as evil increases with men. When a church comes to its end, or reaches its spiritual consummation, its externals indeed remain much the same as before but men are no longer affected by internal things until they no longer think about spiritual and eternal life except in obscurity and uncertainty. A church which is vastated is thus in externals without internals. We see striking instances of such externals empty of genuine spiritual meaning and purpose wherever hypocrisy exists. For the hypocrite uses external piety or pretended goodness for his personal self-aggrandizement or to mislead others; he may even at times persuade himself that he is such as his play-acting has made him appear, for he can put on good affection externally, and his evils are then quiescent - covered over by a seductive natural good.

In the ancient nations, where true internal worship once existed, there grew up elaborate ceremonials which at first were sincere representations of their love of God. They embellished their temples with images and symbols, selected out of their knowledge of the correspondence of natural things to spiritual equivalents. But in time their external worship turned into magical practices, since they lost their concern for internal things, and played upon the superstitious fears of the common people to obtain fame and authority for themselves. Something like this was repeated in the Church of Rome which multiplies masses and mummery to impress the laity and hold then in religious awe, yet has taken away from them the internal truths of the Word and perverted the goods of charity with meritorious works. That whole spiritual Babylon rests its power on holy externals without internals. Its tools are persuasion and fear.

All idolatry - signified in the Commandment by bowing to graven images - is external worship devoid of what is internal. And whenever we see that the internal is separated from an external we find a form of idolatry. The Jews, even when they most literally abstained from the cult of graven images, were yet idolaters at heart in that there was nothing truly spiritual in their external ceremonies and sacrifices, but only a representation and a prophecy of spiritual things - things which were contained in their Word as an internal sense but of which they were themselves utterly ignorant. They adhered to the ceremonial covenant chiefly because they thought that by this they would obtain long life, protection, national power and worldly rewards. (@AC 9391) It is the love of external things for their own sake, or for the sake of self and the world, that is the essence of idolatry.

It is this, also, that prompts men to believe in false religions which assure then of salvation without any interior repentance or any real regeneration of their spirit, or by faith alone without charity, or, perhaps, by ritual ceremonies or priestly interventions.

The Writings warn that no merely external good, whether inborn in man or cultivated during life, can possibly save his soul. It may indeed be serviceable in the reformation of the natural man, but it is not saving, nor can any one be reformed by any external means or any legislation of church or state. He cannot be compelled to believe and love the things of religion by miracles or signs, by conversations with the dead, by threats or punishments; nor can his reformation be accomplished in states of fear or misfortune, mental or physical disease, or in irrational states of emotional hysteria, or of persuasion induced by others. For such external states have no lasting effect, but only close off the internal of his thought. (@DP 129 seq., @AE 1150[3])

The dangers latent in externals when they are devoid of internals is seen from the fact that all evil and its falsity take their origin from the sensual, scientific, or natural degree when this degree begins to act against the spiritual and the rational. This is meant in Genesis when it is said that the serpent persuaded the woman to eat of the forbidden tree. Acting from one's sensual or from externals alone is therefore potentially evil. It is therefore shown in the Doctrine that evil originated when men began not only to prefer a lover good such as that of the pleasures of the flesh and the world - to higher goods, but to pervert this lower good by claiming it to be from themselves, and thus turning against Gods commands and closing their minds against the influx and presence of the heavens. (@CL 444) It was so that mans natural mind became perverted so that it is now by inheritance the abode of all evils and falsities (@AE 545[3], 763e) To act from the external, in rebellion against the rational and the spiritual, is thus evil; whereas to act from the natural in correspondence with the spiritual and the rational, is good. For then the spiritual inflows and gives a soul or internal to our acts.

Since externals of life are both a blessing and a danger, it is to be expected that there should be a wide discrepancy among men as to the employment of external forms and things that provide natural delights and power; and differences of opinion as to how far these should be cultivated or shunned. As long as are five on earth, we cannot escape material conditions or physical necessities, but must resort to continual adaptations of our spiritual aspirations to the limitations of the body and the world.

We must use natural means for expressing spiritual uses and spiritual loves. The whole problem of rife is not whether to employ externals but how to make these externals such that they correspond to our spiritual needs, and do not crowd the internal things of life out of focus and balance.

Before this is accomplished there seems to be a conflict between internals and externals, between the spirit and the flesh. What is merely instrumental and formal seems to be in rivalry with what is the essential. The work of individual regeneration is chiefly concerned in bringing about a correspondence of the natural man to the rational or internal man, and this in every particular. And it is by means of rational truths that the natural is brought into obedience, so that it acts not from itself, but as of itself from the rational. (@AC 3286)

Most of the externals of which man makes use in the world do not survive the death of the body. Even his memory of earthly things although it; is preserved intact is not ordinarily aroused in the other life. But the thing which is carried over as the determinant of his external character is the correspondence or agreement between his externals and his internals. This correspondence is what man works out in the world, in his natural life, in his uses and occupations and recreations, in his public activities and in the privacy of his own meditations. It is this correspondence that makes men genuine and sincere and of single mind.

Both angels and men need an external as well as an internal. But externals which do not agree with the internals and make one by correspondence, are dissipated in the other life. And internals with no basis in the external lie powerless and as it were lifeless. (@AE 441)
and with men, the internal (which means the conscience of faith and charity) seems to be estranged and to be austere and harsh if the externals of one's life do not conform.

But what is correspondence? Correspondence is the appearing of the internal in the external and its representation therein. When there is no correspondence, the internal is not represented within our natural activities or our natural thinking. (@AC 5423)

If man becomes an angel his natural - despite its defects and faults - is brought so far as is possible into a harmonious correspondence with his interiors. In so far as this takes place, the natural becomes as it were transparent so that the angelic shines through.

Yet this can never be completely effected, even as to any one detail of his thought, but only as to most general things. (@SE 2292, 2573, 2157-2159)

Man can be perfected in the other life, even to angelic wisdom, only on the basis of the concordance and correspondence between his natural and his interiors. Therefore the Arcana states: Blessed is the man who is in correspondence. (@AC 2994) But his interiors should be good. If the interiors are evil, then he goes to hell, and that, no matter how externally perfect his natural man appeared before men in the world. (@SE 5552)

The regeneration of man commences in his rational - as an end of good. To establish such an end or such a good purpose or motive is the object of mans reformation, and of the upbuilding of his understanding. But the main concern in the long process of regeneration is to allow the Lord to recreate one's natural mind and life, so that the rational can descend into the natural and prepare there new natural affections and natural delights through which the spiritual can be conjoined with the natural. This is effected by continual shunning of evils and its falsities, so that the natural is purified of evils and disorders, and thus - by temptations and other means prepared for conjunction.

It is not by shunning externals because they are externals, but by the choice of our externals and by their proper subordination and reduction into correspondence with the end of charity and intelligent faith, that man can become more and more regenerated and born anew. This is true of the individual man. But - as we hope to show in following classes it is also true in the Church.

Matthew 23:1-14, 23-26
Hymn 45, p. 467

30 September 1949

<<<

== II. EXTERNAL USES

The Writings stress the fact that man is not born for the sake of himself alone but for the sake of others, thus not only in order to be of use to himself, but to serve his fellow men, serve society, serve the country, the church and thus the Lord. He who does this, provides well for himself to eternity. (@TCR 406)

Man has been crested for uses. Love and wisdom, which are the essentials of his life, are nothing but ideal entities without use. (@AR 875[6]) Use is therefore the ultimate containant of love and wisdom, and may be called the external expression of the internals that make up mans spirit, Swedenborg records a prince of an angelic society as saying simply, Use is to discharge the works of our employment sincerely and industriously. (@CL 16.3) Even the uses of heaven take external forms.

But it is also shown that uses differ among themselves. Some are more comprehensive and universal than others, more far-reaching and thus more eminent. Thus it is said that the use of conjugial love is of paramount excellence because it involves the end of ends of creation, which is the propagation of the human race and thus of heaven. (@CL 68)
The propagation of the race is said to be the highest and ultimate (last) use of the Divine love through the Divine wisdom. (@CL 183) And note that this propagation is possible only in ultimates, or on earth! Uses are graded according to the loves that prompt them. Uses that spring from a heavenly love to God and the neighbor are called spiritual, while the uses springing from a love of the community and the state in which a man is and of his companions and fellow citizens is called moral uses; and a love of the world and its necessaries is productive of natural uses, while the love of self-preservation for the sake of the higher uses results in corporeal uses, also called domestic. (@CL 18, @TCR 394)

The forms which all these uses take are in a sense equally external. By uses, the angels even of the third heaven understand the uses and good works of ministry, administration and employment not only with priests and magistrates but with merchants and workmen; while good works not connected with their occupation are simply called benefactions or favors. (D. Love xiii) But so far do these angelic uses differ from those of men that their manual employments and the duties of their callings cannot be described in the words of human language. (D. Wis. vii.5)

And even on earth we can see that there are degrees of uses which differ as to their objectives. Some uses are for the sustenance of the body, some for the perfecting of the rational, some for receiving what is spiritual from the Lord. (@DLW 330) Some may thus be called internal uses, while others are relatively external. And between them there is bound to be rivalry, for all must be performed by means of the same body; all tax mans time and strength; each seeks to gain his full attention.

The Church is established and maintained for the performance of spiritual uses - which have in view the reception of what is spiritual from the Lord. But besides his share in these uses, a man of the Church, as long as he lives in the world, must also be concerned with the sustenance and protection of his body and providing for the physical welfare of those for whom he is responsible; and with the perfecting of his rational as well as with the education and training of his children, dependents, or charges. This is true of every person, whatever his use in society, be he priest or administrator, soldier, merchant or craftsman, servant or master, man or woman, wise or simple, poor or rich. It is each mans individual responsibility to balance the needs of the body with the requirements of mental health and with the demands of his spiritual conscience. This is. the human problem confronting every man, testing his judgment and forming his character. He must decide what amount of his energy he should devote to the particular field of his employment - wherein his charity towards the neighbor finds its primary use and how far he should engage in additional uses outside of his office or function, or indulge in recreations or domestic felicities.

The answers to these questions cannot be learned by looking up the references to Uses given in the Swedenborg Concordance. These references should be studied, indeed, by every New Churchman, since they throw a flood of heavenly light on the meaning of usefulness and the relation of uses to each other. But for the application of these principles to our different personal circumstances and for the evaluation of the many inclinations and abilities which prompt us to find our place in the social whole, there is needed a wisdom which we cannot learn in books but which ripens in the warmth of the love that are receive and cherish in our hearts.

The choice of a use or profession confronts every young man and nowadays many a young woman. In olden days youths were often almost predestined to adopt the trade or profession of their fathers, and maidens were usually either given into marriage or assigned as a useful dependent in the household. And so far as we can tell people were as happy then as now.

Today, youth has no such obvious indications of Providence. Both sexes are given a wider choice, after a far more elaborate education and a greater acquaintance with luxuries which they will not normally be able to duplicate when they start out for themselves. Here they are faced with the question - what field of use to enter. Should the choice be determined by their inborn leanings or cultivated tastes by their special affection, or by the talents which (they fancy) it is death to hide? Should they follow chiefly their ambition to procure wealth or power, influence or standing in the community? Should they seek the oath of learning - an opportunity to satisfy the craving for better understanding of this world or the next? Should they calmly wait to be pushed by necessity and accept what chance (or Providence) brings them with the least possible expenditure of thought or energy and earn enough to gain their daily bread, avoiding any responsibilities not forced upon them? Or should they consider only the most honored, reputed, and excellent of human occupations - not deigning to enter any use or business which is designed to cater to the bodily needs and comforts of men?

It is fortunate that such alternatives are usually qualified by the needs of society. And the needs of society, ranging from the spiritual needs of the church and of our own souls to the lowest and humblest tasks of necessity, are seen by each man - according to his insight and wisdom - as indications of the path in life which he is meant to pursue. And if he does not find that this path leads to the greatest wealth, the highest honors, or the most complete fulfillment of his natural. yearnings, he may yet find an inner contentment which surpasses the fleeting delights of wealth and station.

Thus it is taught in the Writings that while external uses differ in degree, some being more external as to form or as to objective, yet their real character depends on the internal motive of love and affection that direct them, and on the way in which they are bent to serve and minister to the higher ends of the Lord's providence - which are particularly represented by the uses and the life of the Church. The man of the Church lives in the world, yet is not of the world. The Lord said of His disciples, They are not of the world, even as I am not of the world. I pray not that thou shouldest take them out of the world, but that thou shouldest keep them from the evil.... (John 17:14, 15)

The man of the New Church generally lives and works among unbelievers in the world, yet if he is truly of the Church he is constantly on guard against the sphere of the worlds thoughts and affections. He regards the Church as his spiritual home, where he is sheltered from the storms of carnal passions and earthly anxieties.

But in order that this may be so, the Church must be surrounded by protective externals. Its internal sees must take external and visible form, not only in the lives of individuals but in an organized body composed of many and carrying on its functions from generation to generation.

The Arcana states that of necessity every church must be both internal and external. The internals of the Ancient Church and those of the Christian Church were exactly the same: for these internals were all the things of charity and the derivative faith. And the worship of the Lord from charity can never differ. But the externals differed widely. In the Ancient Church there were sacrifices, libations and similar representatives of Divine things. But in the Christian Church other symbolical things, such as the two sacraments, became externals from which the Lord was regarded, and sacrifices were abolished. (@AC 1083)
In the New Church which is the New Jerusalem there will also be temples and external worship, but not an external separate from the internal. (@AR 918)

The reason for an external church is that man is externals before he is led by means of externals to internals, and afterwards all the things of the internal man are terminated in corresponding externals. Unless there were external worship, he would know nothing whatever of what is holy. (@AC 1083)

USES OF THE CHURCH

The internal uses of the Church concern charity and its faith. The external uses of the Church have regard to Evangelization and Worship. (@AC 9924, 9925, 795) The symbolic forms of these two uses are Baptism and the Holy Supper. Evangelization, or the proclamation of the doctrine, has to do with the Lord's approach to man. Worship implies mans conjunction with the Lord.

Evangelization means the spreading of the Gospel, the evangel of the Lord's coming. and since the entire Word inmostly refers to the Lord, all of doctrine, all of instruction and education, is involved.

Worship is for the sake of conjunction with the Lord. True worship is more than formal, and proceeds from love and charity. Indeed, charity is called internal worship. Real worship of the Lord consists in performing uses. (@AC 7038) Since charity finds expression only through life and the uses of life, all the external forms and modes of charity are the externals of an internal worship - externals of the Church with men.

But in the life of the Church these tare inclusive uses Worship and Evangelization - cannot be separated. They merge and enter into all activities in some form or other, even as in the body of man the heart and the lungs cooperate to produce all vital motions. Where they are not present, there is nothing of the Church. Where life is not of doctrine or influenced and ordered by doctrine, the Church is in a swoon. Where worship or the uses of charity are injured, spiritual life is endangered.

For the Church is a living body, and its externals must correspond to its internals. The externals of the Church have very definite uses:
They protect the interiors from being profaned. They form a plane of continual judgment against evils and falsities. They introduce the child and the man more and more interiorly into the Church. They serve as ultimates which in various ways conjoin the Church with heaven. And finally, they express the soul of the Church, carry out its purposes, and perpetuate it from generation to generation.

The first urgent step in evangelization is the translating and publishing of the Writings. This was Swedenborg's own mode of evangelizing. It became also the first task of the New Church when organized. Some receivers of the Writings seriously maintained that the New Church should confine itself to this use that there was no necessity for any separate organization of the New Church except a publication society!

The very earliest New Churchmen recognized the need of separating from the former Christian Church, where this was legally possible. Beside the fact that New Churchmen could not in good conscience join in prayers directed to an invisible God whose favor was invoked for the sake of His Son, nor join in repeating the symbols of the false faith of the Old Church, nor feel any spiritual gain in listening to preaching by clergymen defending such falsities, it became obvious that to place the uses of the New Church in jeopardy under the ecclesiastical government and discipline of the bodies representing the consummated church would be destructive of all hope for promulgating the near doctrine and its life.

It was also seen from the Doctrine that a distinctive priesthood was a primary condition for establishing a New Church on earth. Even the practical reasons for this are reviewed in the Writings, which are given for the New Church. Thus we read:

Good may be instilled into another by any one in the land, but not truth except by those who are teaching ministers; if others do so, heresies spring up, the church is disturbed and torn to pieces. (@AC 6822)

Order cannot be maintained in the world without governors who are to observe all things that are done according to order and all things contrary to order. (@HD 312)

There are two things among men which ought to be in order: the things which are of heaven, and the things which are of the world. The things which are of heaven are called ecclesiastical, and those of the world are called civil. (@AC 10789)

Governors over .... ecclesiastical matters are called priests, and their office is called the priesthood. (@HD 314) Priests are governors for administering those things which belong to the Divine law and worship. (@AC 10799)

Swedenborg gives this teaching as an integral part of the Doctrine of Charity in the Arcana, and as part of the Heavenly Doctrine revealed to him out of heaven for the New Church. And in speaking of the common good of a society of men or of a country, the Doctrine further specifies that there must be ministries, that is, priestly offices, and that those in such ministries should provide that what is Divine shall be in the community, even as magistrates or judges must provide for justice, and both together for morality. (@Char 130-135)

It is clear that the priesthood, which is here placed first among the required functions in society and is said to be the first of the Church, i. e., the first necessity of a Church (@AE 229[4]), is to be a separate office or profession. For the Writings often speak of the training for the ministry, of the support of the ministry, and show that a clergyman is to be inaugurated by the promise of the Holy Spirit and the representation of its transfer by the laying on of hands. (Can., H. S., 4, @TCR 146, @DLW 220, @CL 396, @AC 878, 6292)

Answering to the priesthood as an office of the externally organized Church, we have in the internal of the Church a corresponding function, Charity takes the place of the priesthood. (@AE 229[4]) Charity, or spiritual love of the neighbor, finds its noblest form in the love of saving human souls, which is the Lord's love for the entire human race and is the specific love which leads to the formation of a priesthood. It is the internal love which inspires the Church and supports all its uses; and in these uses the priesthood takes the lead. Hence the tribe of Levi was the tribe from which the priesthood of the Israelites was drawn, For Levi means Conjunction and signifies Charity.

But although Charity takes the place of the priesthood in the individual man - as good leading to truth - this does not mean that there is no priesthood in heavenly societies. For a use which is universal must yet create its specific organs by which it may function normally and permanently and in a state of freedom. The blood must have heart and lungs as the organs of its use. It is revealed. that there is a priesthood also among the angels. Priests officiate at betrothals in heaven. None but appointed priests preach in the churches and teach doctrine from the Word there. (@HH 226) In the symbolic Nunc-Licet temple, shown to Swedenborg as a representation of the New Church, there was a pulpit which it is stated, signified the priesthood and preaching. (@TCR 508) And in his Diary, Swedenborg speaks of a class of spirits who had rejected the priestly office saying that the priesthood was universal, thus with all. These spirits advocated this view because they preached clandestinely, wishing secretly to subvert the doctrine of the church. (@SE 4904) It is of considerable interest to note that although Swedenborg himself was never ordained through any ecclesiastical authority but was a layman whom the Lord inspired to unveil the falsities taught by the official priesthood of the consummated Christian Churches, yet he never breathes a word against the priesthood as a Divinely ordained office.

The priestly office, although of prime importance among the external provisions for the establishment of the Church, may - like all other human functions - be abused and corrupted until it is no longer an arm of heaven but a tool, of hell. This takes place when the externals of the priestly use are separated from the internal love of the salvation of souls, and are instead conjoined with the evil love of exercising dominion or with self-intelligence or with the love of the world or of fame. This corruption of the clergy goes hand in hand with the decline of the Church: as the prophet Hosea said, like people, like priest (Hosea 4:9) or as Jeremiah wrote, The prophets prophesy falsely and the priests bear rule by their means, and my people, love to have it so. (Jeremiah 5:31)

If the priesthood becomes concerned only in the external progress of the Church - and does not devote itself to its internal needs, the flock is not fed and the wolf falls upon the fold. The external institution of the priesthood is therefore not primarily for the sake of protecting the organized church body, but for the protection of the inner purpose of that body the furtherance of a state of charity and illustration and the maintenance of such uses as will make for the increase of this charity and this illustration.

The use of a trained and ordained priesthood would to a large extent be frustrated if the priest in his work is compelled to engage in so much external administration or be involved in so many social obligations or routine duties that he is not free to study and meditate on the truths of Revelation by the teaching of which he is to lead to the good of life. It is also frustrated if his office has to be exercised under the pressure of worldly anxieties or under the dictation of lay authorities.

When the apostles were sent out to preach the kingdom of God, the Lord told them to provide neither gold nor silver nor copper in their purses, for the workman is worthy of his meat. But the priest must be more than a paid servant of men. He must be the servant of God. This is the reason why free will offerings made to the Lord in worship have been assigned as direct support to the priestly office, rather than used to defray the cost of the temporalities of the Church.

The material support of the priesthood is of no value, however, unless it represents spiritual and moral support also. It is not true that the priesthood should be loved as the neighbor in a higher degree, or that the priesthood should be loved and from it the Church; for a congregation built around the personality of a clergyman will soon be scattered.

It is the good and truth of the Church which should be loved, and for the sake of these the priesthood, which only serves and as it serves it is to be honored. (@TCR 415) No honor or merit attaches to the person, whose talents, knowledge, and powers are derived from heredity or training, and is thus due to the grace and providence of God. But the honor belongs to the office only, and is merely loosely attached to the person for the sake of the use. (@AC 10796) This is of course true of all men and of all offices and uses. The internal progress of the church into the perception of new truths and new uses can hardly be effected except through leaders who are advancing in states of regeneration and who are in consequent enlightenment. (@AC 10028[2], @DP 168, 169) Yet even a priest who is personally evil can have an external enlightenment from the doctrine of his Church as upheld by others, and can thus effectively teach and administer the sacraments to others so far as his interior evils do not break forth and cause disturbance and scandal. (@AC 4511[3], 3670:2, 10,309)

7 October 1949

<<<

== III. ORDER WITHIN THE PRIESTHOOD

In the talk last week it was shown that the uses of the external of the Church, or of the organized Church, had to do with Evangelization and Worship. The first requisite for carrying cut these uses was said to be a priesthood.

In ancient times the patriarch or father of the family was both king and priest of his clan. In the representative church the two offices were also sometimes united, as in the case of Melchizedek, king of Salem, to whom Abraham paid tithes. But later the royal function of civil government which represented the rule of Divine truth, was separated from the sacerdotal office, the priesthood, which represented the government of the Divine good. (@AC 6148) Since the church is no longer co-extensive with the state or the country, it is of course inevitable that the church should have its own government. But even if it were not inevitable for political reasons it is stilt necessary for the uses of the church to be organized and organization implies a government.

Even in heaven, where all things are spiritual, this distinction of functions occurs. Swedenborg, after having been shown the tragic insanities of certain devils who were possessed of a love of ruling from the love of self, met two angels. who were magnificently dressed. They had been sent to him to make clear that there was a heavenly love of ruling also, from a love not of self but of uses. One was a prince of an angelic society; the other was the high-priest, who served the church there by administering holy things for the uses of angelic souls. Both frankly sought obedience and dignity for the sake of being able to perform their uses more fully and to extend them more widely. (@CL 266, or @TCR 661) There is no suggestion that the priest was subservient to the prince or the prince to the priest. They were apparently in sincere friendship and harmony and in close consultation about the common good. Undoubtedly the field of use of one overlapped and dove-tailed into the province of the other. Yet there was no conflict or rivalry; only cooperation, like that of clergy and laity in a. well-ordered society.

As to the case on earth, it is stated beyond dispute that there are two classes of things which must be in order among men, and these are ecclesiastical or heavenly things, and civil or worldly things. Therefore, there must be both ecclesiastical and civil government.

The need for governors in the field of worldly affairs is not apt to be doubted. Men must be held in bonds by laws; by rewards, honors and profits for those who do good things, and by punishments even to loss of life - for those who do evil. Otherwise the human race would perish. (@HD 312)

Human society must be held in order by governors (prefects) skilled in the laws, arise, and God-fearing. And among themselves, those who constitute a government must be distinguished into subordinate groups, lest say one from caprice or ignorance should permit abuses and destructive evils. (@HD 315)

Priests are also governors in their ecclesiastical province, and are responsible for order in matters of Divine law and worship. They are of course not governors until accepted as such by the free action of the church; and the scope of their administration is thus limited to the uses entrusted to them. They certainly have no authority over the souls of men, for they do not know the internal states of others; nor have they any power of opening or shutting heaven or to grant forgiveness of sin. It is not their office to fix doctrine whether by vote of council or by episcopal pronouncement (@TCR 489), but to teach the doctrine of their church from the Word. They cannot compel anyone to believe the things of religion, and if any one differs from the priest, he is to be left in peace. But he who makes disturbances (turbas) is to be separated; for this also is of the order on account of which the priesthood [is established]. (@HD 316-319)

These functions belong to the priesthood. But the priesthood itself, like any other government, must operate by a distribution of authority and responsibility among many, and a grading of uses so that there is no interference or conflict of one with another. The doctrine notes that in order that anything may be perfect, there must be a Trine in just order, one under another, and a communication between. This is illustrated by the three heavens, by the three atmospheres existing in each world, by the relation of head, body, and extremities. In like manner in the Church there must be a mitered prelate, parish priest; and under them curates. (Coronis 17)

A similar trine existed in the Israelitish church, where Aaron was the first high-priest, his sons constituting the sacrificial priesthood, and the other Levites forming a body which carried on instruction and aided in more external services.

The Writings show that a kingdom, state or house must have its head or chief, and that order requires distinctions, and thus signs and titles of dignities, and rights of administration, which result in subordinations whereby they can act as a one. (@TCR 680) At a council of clergymen called together by the Lord in the spiritual world, the members clad in sacerdotal garments were placed on three rows of seats, the first row of seats being covered with silk draperies of purple color, the next with draperies of cerulean blue, and the third with white, suggesting three degrees of priests. (@TCR 188)

The detailed form of the priesthood is not laid down in the Writings, although there ape many suggestive teachings given. It is the uses themselves which must dictate the final form. And in general these uses are three: Evangelization and Worship have already been mentioned as the two uses of the Church. But for these uses to be carried out, there must be a third, namely, Government. But these functions - while they pertain to the priesthood as a whole - are best carried on where the government and supervision of the work of the whole church is centralized in a permanent official, a Bishop or supervisor. Beside this executive bishop, other men of the episcopal degree would also he entrusted with the authority to inaugurate men into the priesthood. Pastors would then preside over societies - forming a middle degree. And there would be other clergymen - Ministers of the first degree - who assist in teaching and other forms of evangelization. Yet between all three degrees there must be communication - for this is vital for the maintenance of cooperation, common progress, and growing illustration.

But it should be realized that the functions of the various degrees of the clergy cannot be fixed. Doctrine teaches us general principles, but future generations may see the application of these principles with greater clarity. It is against good judgment to legislate for the future. For experience also teaches. To forget principles and simply follow the voice of expediency would be fetal. But there is a time-honored proverb which tells us to remain firm in essentials while yielding in less important things: firm in essentials but agreeable to adopt new external modes accommodated to new conditions.

A body cannot grow if it does not possess a certain elasticity in its external structure. The functions of the various degrees of the priesthood may thus not be fixed with certainty as essential. At present, priests of the first degree are entitled to perform only the sacrament of Baptism, while the Holy Supper and Marriage belong to the higher degrees.

ORGANIZATION OF THE CHURCH

We have premised our comments on the Externals of the Church with a brief account of the Priesthood, because in a sense the church is organized with special reference to the uses of the priesthood. It is also recognized among us that just as Baptism into the New Church cannot afterwards be rescinded by any action of the Church, so the powers conferred by ordination by the laying on of hands are from the Lord alone, and not from any body of the Church, and can therefore not be taken away from him by any bishop, council, or church organization, or by any repudiation of his services. On the other hand, his ordination constitutes him a priest of the Lord's New Church - introducing him, we believe, into the spiritual society of his use, and acknowledging before men his fitness for priestly work: but it does not, necessarily make him a clergyman of the organized church-body.

There has never been (and probably there will never be) any external church-body which includes all those who have received the Writings of the Lord's second advent. It is therefore well to distinguish the various usages of the term the New Church.

The teaching is that the Lord's Church on earth is in itself universal and - though scattered throughout the world it is before the Lord as one man. In this universal Church are all who live in the good of charity according to their religiosity. (@HH 308, 328). Where these are, only the Lord knows, for they are in every race and religion. (@AC 7396[2]) It is the invisible kingdom of the Lord. And within this kingdom there must always be those with whom there is the Word and thus a knowledge of the Lord. These constitute, as it were, the vital organs of the Church Universal - the heart and the Lungs, by which the rest can be maintained in a spiritual communion with heaven. (@AC 9256, 9276e, 10500:20, @AE 313[3]) These are said to constitute the Lord's Church in special (@AC 10765, @AE 351, 252:2) or to use an adopted term - the Church Specific.

The New Church, considered as a new dispensation of Divine truth, was established after the last judgment to serve as a Church Specific, and thus takes over the functions of the former Christian Church. But when we so speak of the New Church, we mean only those who know the Lord in His second advent in the Heavenly Doctrine and who are in the good of charity according to this doctrine; for no others belong to the Church Universal and no others can participate in the uses of its heart and lungs.

The Lord's New Church is therefore a title which cannot be applied to any external organization of men, And the same is true of another expression which occurs in the Apocalypse Revealed. The seven churches are there said to signify the universal New Church, which is described as including all those in the Christian world who have religion and from whom the New Church can be formed and who will receive the Heavenly Doctrine in this life or the next.

But those who receive and openly profess the Heavenly Doctrine in this life and are associated in some way with an externally organized group or congregation for the worship of the Lord as the God of heaven and earth, are participants in the visible New Church; and this irrespective of their internal state, their age, or their formal membership status.

The visible New Church is thus composed of a number of church-bodies, groups, and missions which in varying degrees and ways are founded on the teachings of the Writings. Most of these bodies are composed of New Church societies which have joined for more general uses within a country or continent, or within a district using the same language. These organizations are usually formed as associations of individual societies or local churches which sent elected representatives to an annual meeting which selects its officers for the year and assigns all the work to standing committees. On such a plan operate the General Convention of the New Jerusalem on this continent, the General Conference of the New Church in England, the New Church in Australia, the Confederation of French-speaking societies, the Swiss Union of the New Church. AThe New Church Swedish Society in Stockholm and Gothenburg, as well as various national groups and missions loosely associated with the Conference or the Convention, which have each recognized geographical spheres of influence in order not to conflict in their church-extension work.

The Convention in this country and Canada has a further feature. The societies are joined into thirteen associations, like the Massachusetts Association, the Illinois Association, etc. And delegates of these associations are entitled to vote at the Convention.

The General Church of the New Jerusalem is organized on a different plan and from a different principle. It is formed not from delegates of societies, but from individual adult members baptized into the faith of the New Church. Its membership is irrespective of national or geographical limits.

It is presided over by a Bishop who is first nominated in and by the Council of the Clergy, and then elected by the Church as a whole as represented at a General Assembly.

The purpose underlying the existing form of government of the General Church is to encourage the closest possible cooperation between the priesthood and the laity, and to guarantee to each the freedom of their respective function in the Church.

The Council of the Clergy was formed before the General, Church came into being. Requesting the leadership of Bishop William Frederic Pendleton, it initiated the action by which the Academy movement was transformed into the General Church of the New Jerusalem. The Council of the Clergy is not an administrative body apart from ifs intra-mural affairs. It may of course make recommendations to the Bishop, the Executive Committee, or the General Assembly. It may also act together with the Executive Committee as a Joint Council. The Joint Council may act for the Church in necessary decisions in the interim ears when the General Assembly does not meet.

The priestly government of ecclesiastical affairs should provide not only for the freedom of the priesthood in its proper field but also for the freedom of the laity or of the Church as a whole. This is involved in teaching that no one can be compelled to believe. The government of the Church, like that of heaven, is not one of command and compulsion, but of influx. In heaven, such influx, which leaves others free, is a communication of thought with a desire that it should be done, and or, the part of the recipient there is then a perception of a need. (@AC 5732)

The administration of the Divine law and worship or of the things of heaven is the function of the clergy. But in the actual work of the Church there are uses corresponding to the civil administration in a country which is the function of magistrates. (@HD 319) It seems to follow that the civil or fiscal affairs of the Church should be administered by laymen. This is generally the case in the various societies. In the General Church as a whole, the use is served by an Executive Committee elected by the Church - or, actually, by a corporation which stands as the legal equivalent of the General Church. This is a lay body, although presided over by the Bishop. It handles all the funds of the General Church and in it is vested all the property of the ecclesiastical body. In this is actually fulfilled the principle that the tribe of Levi should have no inheritance in the land of Canaan.

In view of this division of functions, it is obvious that there is no power in either the clergy or the laity except so far as there is a free cooperation between them. Our order is one based on mutual confidence. It has no true parallels in the realm of political or civil government. Our government is the government not of prudence but of conscience. Its success depends on mutual understanding and a common aim.

With this in view, there has been from the first an emphasis on the need for Council and Assembly. The presiding Bishop is assisted in his decisions by consultations with a council of his own choice - a Consistory selected from the clergy. A Council of the whole clergy, over which he also presides, meets annually for mutual consultations on the spiritual and ecclesiastical welfare of the Church and its societies, and for mutual enlightenment on doctrinal questions and the forms of worship. On the other hand, the Bishop presides over the meetings of the Executive Committee, where he presents the needs of the church and the viewpoint of the priesthood as to many phases of the works, as well as affording a spiritual leadership from the enlightenment of his high office. The Executive Committee meetings also provide the Bishop with opportunities for lay counsel, for its members represent the Church as a whole and can present her needs as they are seen from the side of the laity.

This mutual counsel of the priesthood and the laity comes into special effect in the Joint Council which is held annually and whenever special need arises. To this Joint Council the Clergy and the Executive Committee both report their work and in it both discuss the affairs of the Church, its uses and their instrumental set-up and its administrative problems. The Joint Council not only makes recommendations but can take executive actions; for it represents the whole Church and is regarded as having emergency powers to act for the Church in the interim between General Assemblies. This provides for the continuity of the work of the Church. Should the Church at any time find itself deprived of its executive Bishop or an elected Assistant Bishop in his stead, it would be the Joint Council which must provide for the government of the Church pending the choice of a Bishop.

The choice of a Bishop is ingested in any General Assembly of members enrolled in the ecclesiastical body of the General Church of the New Jerusalem. The reason for giving such a power to the members who are able to attend an Assembly lay in the fact that all are members in the General Church before they become members of societies or parishes. The presumption is that it will be those vitally interested in the uses of the Church who will attend Assemblies.

Yet already in 1923, Bishop N. D. Pendleton pointed out that, if the Assembly is to maintain its prerogative of calling a presiding Bishop, it must eventually so adjust itself as to speak more nearly and equally the voice of the whole Church, instead of, as now, by a mass meeting in which there is a heavy local preponderance. (New Church Life, 1923, p. 597)

But the General Assembly is more than a body for transacting the necessary business affairs and major decisions of the Church. The interlinked organization of the priestly and lay uses of the Church is such that the work - both of the central uses and of the various societies - is carried on uninterrupted even if time elapses between Assemblies. This leaves the Assembly free to devote much of its time to more interior or universal uses to the consideration of the things of spiritual development and growth, to the progressively clearer understanding of our doctrine and to a re-consecration of our people to the purposes of the internal Church. Each Assembly - whether it is a General Assembly or a convocation within a specific district - is like a sacred feast when the tribes of Israel go up to Zion for the renewal of the covenant with the Lord. To such feasts all men of the Church come as equals and as brethren.

It has been shown that the external organization of the General Church is an order based on the mutual trust and co-operation of the clergy and the laity, and on a recognition of the need for freedom and autonomy within each field of use. Our ecclesiastical body does not even possess any binding constitution. Its order has grown up by living usage and precedent, with the understanding that it can be modified when our spiritual uses so demand, and experience and greater enlightenment so indicate. Our only constitution is the teaching of the Writings themselves.

This unique situation is illustrated also in the relation of the Academy of the New Church to the General Church. Even within the spheres of the English Conference and the American Convention there exist certain affiliated, but autonomous bodies publishing societies and missionary boards; and there are also some more independent associations, like the Swedenborg Society of London and the Swedenborg Scientific Association. But the Academy of the New Church stands in a peculiar relation to the General Church, because the latter depends upon the Academy for the performance of one of the most vital uses belonging to the Church, the use of promoting New Church education, preparing teachers, and educating young men for the ministry of the New Church.

It serves as the lungs of the Church, even as the ecclesiastical organization serves as its heart. Yet the Academy is an independent, self-perpetuating, and endowed corporation, which by its own action has placed its ecclesiastical affairs and the religious instruction given in its schools, under the supervision of the Bishop of the General Church, whom the directors of the academy have also chosen as President of the institution.

In our brief survey of what I understand to be the main features of the external organization of our Church, the effort has been to point out that the externals of the Church so far as government is concerned - are not intended to be rigorous and unyielding bonds which jealously guard prerogatives and stifle actions by technicalities or by regulations that bind future progress. Externals are always protective of internals but are meant to perpetuate these internals, not to smother them or cramp them. Order - based on such externals - is necessary for the protection of the freedom and growth of every use within the Church. But order is such as is the disposition and activity of the parts that make up the whole. Perfect order requires a voluntary and free subordination and coordination of uses, from a common love of the internal end, which is salvation, and a growing mutual perception of the means and instrumentalities which will cause all uses to converge towards this end.

Heavenly Doctrine 311-314
Hymn 12, v 1, 3. p. 492
Hymn 58, v 1, 2. p. 482

14 October 1949

<<<

== IV. EXTERNAL WORSHIP

In considering the character and use of the externals of the Church, we have given some attention to the need for externals and their relation to the internals which they must serve; and also to the need for a priesthood and an external organization of the Church. We have described what the Writings say about the functions of the priesthood among which is the use of governing ecclesiastical affairs. It. was shown that this government has in view the free and harmonious cooperation of laity and clergy in the uses of the Church.

The uses of the Church were said to relate to charity and faith, or to Worship and Evangelization. For charity and its life are the internal things which must be within Divine worship and which external worship is to call forth. And faith is the internal of all evangelization and instruction and the purpose of these is to lead to faith and establish it.

This evening we propose to present some generals which the Doctrine reveals about external worship and its use. By external worship is meant all forms of piety, both public and private.

With the consummation of a church and the decline of spiritual life, the worship of the Lord loses its internal soul, although the forms of worship may persist - preserved for the sake of the simple-hearted. That Christendom had arrived at such a point, Swedenborg confirmed from the state of the world of spirits before the judgment. And he wrote that there was no knowledge of the Lord or of Redemption or of the after-life, and that the sacraments were regarded as mere ceremonies; whence it followed that there was no religion, no church, no worship, no ministry. He added that no grain of truth remained which had not been perverted by being used to confirm some false doctrine, and that falsities therefore must be rooted out before truths are implanted. (Abom. Of Desol., A.)

No man can know the internal state of the Church except from Divine revelation. Yet there is a general recognition even in the world of the fact that much of the worship of the Churches is empty of internal sincerity. Beautiful externals, impressive pomp and ceremony, unctious behavior, emotional fervor and pietistic exhibitionism - these things do not make worship genuine. Overdone, they rather suggest a staging for hypocrisy, fear, and empty tradition.

Many people, therefore, shy at the very word piety. Especially in Protestant lands, a display of religious feeling becomes suspect. And the more unbelief spreads, the more embarrassing it becomes in the world to wear one's religion on one's sleeve. Even for very many good New Churchmen hardly a day passes that they do not bow - like Naaman of old - in the house of Rimmon. (I1 Kings 5:18).

One of the obvious advantages of a New Church circle, society, or community, is that it affords a freedom to the spirit - an environment where our faith and devotion can be expressed in correspondent words and acts and our ideals represented in a symbolism which foreshadows our hopes and future uses an environment which we must constantly seek to perfect and purify. This environment comes to us as a wonderful gift of the Lord's providence; yet we are responsible for its perpetuation and for maintaining its original purpose.

In the New Church, true worship can be restored; but only so far as those falsities and evils are rooted out which have perverted the worship in the former churches into an external devoid of a corresponding internal. The remedy is not found in abolishing external worship. John in his vision on the isle of Patmos indeed saw no temple in the New Jerusalem, for the Lord God almighty is the temple of it, and the Lamb. Yet, by this is not meant that there will be no temples in the New Church, but that in it there will not be an external separated from the internal, because the Lord Himself in His Divine Human from whom is all of the church, is alone approached, worshipped, and adored. (@AR 918)

The most essential thing in worship is the acknowledgment that the Lord is the Only God and that His Human is Divine, and that everything of faith and love proceeds from this. There must be the acknowledgment that man is but dust and ashes nothing but evil - and thus does not dare approach the Lord from himself, but from the faith and power given him by the Lord. Eternal life and happiness cannot be given to man by the Lord unless the man is in such humble worship. (@AC 7550) For the object of worship - in the Lord's sight - is not that He may obtain glory from men, but that man, through sincere humility, may be lifted out of his old proprium which is the love of self. (@AC 10203, 3994)

It is clear from this that worship from freedom is pleasing to the Lord but not worship that comes from being compelled by another. (@AC 9588, @DP 136, 137) Yet such freedom is born through self-compulsion, when the interior man from conscience resists the natural man. (@AC 1947, 1937)

Humility either before God or men is not natural to man after his first rational begins to insist on his dignity and human pride. In childhood man must be led to external worship by parents and teachers who appeal to innocence and obedience in the child. Worship from these states is acceptable to the Lord, and angels are present who translate the crude childish ideas into the delights of wisdom. Adolescence and youth are transition periods, in which the forms of worship and the habits of religious observances must be taken for granted as necessary ultimates, even though innocence is waning and self-compulsion cannot as yet be relied on to take its place.

The warning is given that if the loves of self and the world continue to control a man, his self-compulsion to a moral and religious life is not from any interior freedom but from prudence and self-interest. His worship then is not from any interior intention to shun what is evil, or from any endeavor to think apart from self. Craftiness and fraud are apt to fill his interiors instead. His piety is either from mere childhood habits or from a persuasion that such external acts somehow are a short cut to heaven which absolves one from the need of interior repentance; or it may spring from a mere social instinct (since there is little else to do when business stops on holy days), or from fear of being considered irreligious. (@AE 182) That such worldly ideas enter at times also into the minds of the well dispose and sincere is of course not to be denied: but with them there is the recognition that such reasons for observing the acts of devotion should not govern us since they spring from the proprium and that the real reason is that we desperately need every ministration which can strengthen our faith, bend our pride, and soften our hearts to receive the influence of heaven. This is indeed what the Writings teach. The Lord is chiefly worshipped in the performance of our uses. But frequenting a place of worship, hearing sermons, and saying prayers, are also necessary. For they teach what the life of charity should be and what is our relation to the Lord. (@AC 7038)

Similarly, when the Arcana explains that a man who is in love and charity is continually worshiping, and that heaven is thus a perpetual Sabbath, it is added: But man, while in the world, ought not to be otherwise than in external worship also. For by external worship internal things are excited, and by means of external worship external things are kept in holiness so that internal things can flow in. And besides, man is thus imbued with knowledges (cognitionibus.) and is prepared for receiving heavenly things; and is also gifted with states of holiness which he himself is not aware of.

These states of holiness are conserved for him by the Lord for the use of eternal life; for all his states of life return in the other life. (@AC 1618)

To hold that a person cannot be saved or can have no worship if he lives where there is no Church, no preaching, sacraments or priesthood, is to make formal worship essential; when yet the formal things of worship are but the form which internal worship takes. A man deprived of access to a church Amay yet worship the Lord from the internal, which is what sanctifies and vivifies the ceremonial or formal. But, the teaching continues, it does not follow from this that there ought not to be external worship. (@AC 1175, cf. @HH 222)

There are those who object that they can worship better in the solitude of Gods free nature - can discern His mercies more clearly in the forests and in the murmur of mountain brooks than between narrow cathedral walls. Indeed the people of the Golden Age did read the laws of the Lord in nature, which to them was an open book of correspondences - with sermons in stone and good in everything. But modern man can see nothing in nature which he has not already learnt from doctrine. The poetic mood - the feeling or mystery and awe-- that flows over his senses as he views a glorious sunset or stands spellbound on a mountain top must not be confused with religious sentiment. And one of natures unique phenomena - the rainbow bridging heaven to earth - was set aside by the Lord as a symbol to testify before the spiritual church that the call of nature by itself is not enough - but that mankind can now be saved only through a life according to revealed doctrine which must form and perfect the conscience and discipline our lives.

Here we must distinguish between the source of worship and the quality of worship. Worship itself is nothing but a certain activity coming forth from the celestial which is within. The celestial cannot exist without activity, and its first activity is worship. (@AC 1561[e]) This means that all worship - even the grossest worship of self springs forth from a love, an emotion. But the quality of the worship is from the goods and truths of doctrine; for worship is only an external act in which there must be internals that are of doctrine. Without these the worship is devoid of its essence, life, and soul.... (@AR 777) Good of love is the essential of worship, but good comes into existence and is formed through truths; and therefore all worship must be through truths, from good. (@AE 696[6])

It is of course clear that one's worship is such as are the thoughts and affections active in one's mind. The idea that man has of his God, and of himself in relation to God, necessarily directs and qualifies his worship. And this idea is formed from doctrine as this is interiorly received, and from his own state of repentance. Worship is acceptable so far as a man has - as of himself - subdued his proprium, has shunned evils as sins and rejected the falsities which his self-love favors. Worship is perfected insofar as there is a correspondence between the internal man and the external. So far at the external man - during worship - regards worldly ends while the internal man wants to regard the ends of the Lord's kingdom, the angels and spirits; with man perceive the disagreement more distinctly than at any other time. (@AC 1571) Even man himself is most keenly aware of the intrusion of worldly states, conceits and unworthy emotions while he is attempting to meditate on spiritual things and to compose his mind into a humble submission to the Lord's leading of his thoughts and this awareness is of use so far as he thereby comes to know the contrasting states within him. To man it appears as if he was of a divided mind. But the Lord regards him from the quality of the conjunction of goods and truths - or of will and understanding within him this quality tempers all the ideas of his thought so that the whole man is in all things of his worship. (@AC 10298)

Still, man cannot worship the Lord from what is from man, but from those goods and truths which are with him from the Lord. These holy truths and innocent affections the Lord can vivify and elevate to Himself, and along with them man is also raised into heavenly light and heat. (@AC 10299) And what disagrees is then rendered. quiescent so as not to appear. (@AC 1581) The external man becomes submissive, ordered, serviceable, and suffused with an influx from the internal things which are the Lord's. Indeed, so far as it is conjoined with the internal, its deformities are hidden and it puts on a certain beauty, for it is transparent from the charity within. (@AC 1598)

It is wrong to think that one can dispose oneself for influx by prayers and other externals of worship; for man disposes himself when he abstains from thinking and doing evils and thus leads himself as of himself - to a good life through truths from the Word. Then his prayers avail and are elevated into heaven even unto the Lord, being purified on the way. (@AE 182[4], 248e, 700:3) We are also taught that there can be no worship from an empty mind: but the more of genuine truths of faith that man has the fuller and more acceptable is the worship. (LJ post., 243)

It is clear from the cited teachings that the things of external worship which the Writings present as necessary in the New Church, are not externals of the body alone but externals of the mind: thus not only deliberate actions, gestures and words, but conscious intentions and thoughts.

In general, piety consists in thinking and speaking of the holy things of the Church with reverence, in devoting much time to prayer, and then behaving humbly: in frequenting temples listening to preaching with attention and devotion, receiving the sacrament frequently each year and performing other parts of worship according to the ordinances of the Church. (@HD 124) In connection with public worship, devout singing is mentioned, and also kneeling in prayer. Externals of worship include also home worship - prayer morning and evening, and. at dinners and suppers; conversation about religious faith and the life that leads to heaven instruction of children and servants, reading of the Word and of church-literature. (C 174)

But most of these acts can be of the body and the mouth and memory alone, and may be performed even by the impenitent, who may regard them as a concession to public opinion. The repentant man disposes his body in attitudes of humiliation and obedience; but he also seeks to reduce the externals of his mind into a state or mood which permits an affirmative reception of the goods and truths of heaven so that these are not profaned by worldly and selfish conceits and enticements. He averts his mind from irreverent or unclear suggestions, reflects upon his intentions and thoughts with an effort to shun evils by the Lord's help, and enters upon meditations about God and the eternal life. He may also be sensibly moved by certain affections and natural delights that seem to express in sensuous form the peace and freedom which are feebly echoed in the inward aspirations of his struggling spirit. (C 175)

Yet the Writings say in this connection that all things of worship are externals - externals of bodily life and externals of the mind. For it is the external or general state of the mind that is deliberately composed for worship, or ordered into an external state - a poise and attitude that represents what man acknowledges and inmostly desires, and that signifies man co-operation with the Lord through a voluntary subjugation and renunciation of rebellious and frivolous inclinations. Something of this self-discipline seems to man to be present in worship while the natural is not yet regenerated; and it is ultimately expressed by the bodily act of kneeling before the open Word.

This does not mean that there is any spiritual value in self-imposed discomforts or flagellations such as are resorted to by many misguided ascetics in their effort to overcome the flesh. For the consciousness of bodily suffering disturbs the externals of the mind (which cohere with the body and its states); and thus the purpose of worship is defeated.

In many Christian sects, piety is confused with morbid states of temptation and anguish which keep the thought centered upon one's self, and such sects often aim to evoke harrowing emotions of despair and self-pity and fear, which tend to sustain a temporary contrition but leave the permanent character untouched. In such cases, the real end of external worship is left unfulfilled. For states of worship are intended to instruct and upbuild a mans rational mind, to enlighten and warm it with spiritual light and beat, and to cause the natural man to be ordered and subservient to charity, rather than to stir up its self-centered emotions.

The internal of true worship is charity: which is described as looking to the Lord, shunning evils as sins, and doing the duties of one's calling faithfully. Our doctrine teaches us that unless man does these things, his internal man is evil and his of external acts of worship would appear before the angels as those of an actor waving a firebrand. (C 179, 180)

In the world it is generally thought that the works of charity are the signs that a man has a religious faith. But the Writings state exactly the reverse: Externals of worship are the signs of charity. (C 177)
Charity, being itself internal worship, in the internal man, leads to all the acts of worship that are performed in externals.

The works usually identified with charity appear the same even if an atheist performs them. The acts of piety can be imitated, to a point, by an evil man and a hypocrite. But piety distinguishes the confessing believer from the unbeliever. The very act of worshipping the Lord is a sign that the man in his life intends (or at least pretends) to act from charity or love of the neighbor.

There is no charity with those who do not worship God and seek to learn His will so far as they can. There is no love of the neighbor in any acts - however generous or heroic - which proceed from a mind that claims for itself the credit or merit of its own accomplishments or does them from pride in its own goodness.

This might dishearten us. For something of pride and meritoriousness is apt to attach itself to all that a man does, even if its first impulse originated from charity. There are many in the world who deny that it is possible to act except from self-interest: that self-less motives do not exist! Yet, what religion and worship aim to do is to render to the Lord the glory of His name - to renounce the pride and merit of our works, to confess that without His creation, His redemption, His providence, and His revealed teachings since most ancient times, there could have been no civilization, no human sense of moral responsibility, no development of mans higher nature, no charity that can love others apart from their services to ourselves.

In fewer words: the charity that makes the internal of worship is not from man but from the Lord. This acknowledgment is what leads to acts of worship, And those acts are therefore signs of that charity not infallible signs, for signs are only indications which can be misread. But genuine external worship appears to the angels as a standard-bearer with a banner held aloft. It is the banner of the Lord, raised by all who are of His Church and who confess Him openly before men.

Yet the externals of worship are not all public. There ought to be worship in the home - of which we may speak on a later occasion - and also worship by each individual in private. When thou prayest, retire into thy chamber, and when thou hast shut the door, pray to thy Father who is in secret.... (Matthew 6:6) In essence, all worship is private, and not for the sake of display. The Lord who seeth in secret is present differently with each man who bares his soul before Him.

Nevertheless there are reasons why men should at stated times gather together for a common and public worship, and why a communion or church or society - in its common uses and progressive states - should have an opportunity for common prayer and common enlightenment, on the basis of a common order of worship, which we call ritual.

I1 Kings 5:9-19
Hymn 63, v. 1, 2. p. 487
Hymn 39, P. 465

28 October 1949

<<<

== V. PUBLIC WORSHIP

Worship is in its essence individual and personal. It is not for the sake of displaying one's piety. The Lord rebuked the Pharisees who loved to pray standing in the street corners for to be seen by men. But He also said, Whosoever shall confess Me before men, him shall the Son of Man also confess before the angels of God. Where two or three are gathered together in My name, there am I in the midst of them.

The Writings state that the externals of worship are the signs of charity. This does not mean that man should worship publicly in order to show off his good works; for indeed good works are eventually recognized in any ease. But by worship man disowns any merit or credit for his good works: and it is this that makes such works goods of charity. Let your light so shine before men that they may see your good works and glorify your Father who is in the heavens: that is, that they may give credit to the Lord alone for the accomplishments of the Church.

It is by such public avowal that we can acknowledge before men that all good and all truth which lend grace and value to our lives come from the Lord - come by influx out of heaven and by instruction from the Divine Word of revelation; and at the same time we confirm before the church that realization to which we arrive in private worship and by solitary self-examination - that there is in us as persons nothing but evil, excepting that which may be with us from the Lord.

Worship that is compelled - from fear or threats - is naturally sad and lifeless. But genuine worship is free and clear and joyful. (@DP 137)
The Writings show that the angels do not consider external worship, or glorifying the Lord, to be a use, but a recreation. (@Dmin 4773, 4805) The contents and meaning of our worship is always derived from the charity which has been born in our everyday life of repentance and use to the neighbor and tested by struggles and temptations; and worship flows spontaneously from this inner source. The relation of worship to charity (which is the essential spiritual use) is thus like that of our natural recreations to the toil and strain of natural uses. And while man can indeed get along for weeks with all work and no diversions, it is apt to endanger his health and his usefulness. Similarly, spiritual health needs its recreation in external worship.

The sincere man of the church therefore looks forward with eagerness to periods of public worship. It is hard for a man to carry his convictions locked up as a secret of his own heart but he longs to unburden himself and share his faith and feeling with others, in an atmosphere of charity and understanding. Public worship provides such a release of inner tensions - an opportunity to feel the support of others and thus dissipate the sense of his own loneliness which pursues him as he passes through the states of spiritual life, whether these partake of thanksgiving or of temptation.

Thus the church-edifice comes to stand for him as a sanctuary from which the alien spheres of the world are to an extent excluded. It represents a place where his spirit may draw breath from heaven - for the renewal of that faith and that inner resolution which must carry bin onward. It seems to him as the house of God and a gate of heaven where the angels of God ascend and descend as upon the ladder of Jacob.

It is a common experience that where many act together, the individual loses much of his self-consciousness, and feels less important as an individual. His proprium becomes less proud, less sensitive of its prerogatives; finding its place in the larger group. This is the reason why regeneration is impossible except in the society of other men, and why charity itself consists in the faithful execution of the work of one's calling, or in uses in which we adapt ourselves to the needs of others and to the uses of the commonwealth or the church. And it is the same in public worship when we sing or prays or kneel or read together in choral action.

Thus it is said that novitiate spirits in the other life must be initiated into common gyres of various kinds in order to be prepared for heaven. Discordant things are first of all removed, and the first introduction into gyres has the object of simply enabling them to be together - in mutual accommodation; the second stage looks to the end that their thought and speech may agree, and that externals may agree with internals, and also that the thought may follow the speech; the third stage is aimed to cause them to be in mutual accord as to thoughts and affections; and the final object is to produce an accord of truths and goods. (@AC 5182, @SE 1030) These gyres are also referred to as choirs, in which many think and speak the same thing and act together and are led, as it were by one another, yet. really by the Lord: for no one in heaven desires to act from himself, or from proprium, still less be over the others and lead or dominate; even as in an orchestra or in choral singing or acting, each participant fits his own part into the whole without exaggerating his own importance. (@AC 3350)

It is remarkable that the formation of such gyres or choirs is the introductory ultimate for disclosing an ever more interior unanimity. The first object is to obtain a mutual accommodation, an external order in which many can be together without confusion or conflict. In the spiritual world this is achieved first of all by the separation of all spirits according to their religious or church affiliations or beliefs, so that Christians are separated from Jews or Moslems or pagans. This is the reason for such initiatory rites as circumcision and baptism, and why baptism causes one to be inserted among societies and congregations in the spiritual world according to the Christianity in him or about him. (@TCR 677 seq.) It is also the reason why spiritual freedom and progress can be best assured when a congregation or church starts out on the basis of a common mode of worship or recognized ritual. Where there is a distinctive quality of the Church, a common ritual becomes an ultimate for the cultivation and development of that spiritual quality. In the Ancient Church, there was a common charity which made the earth one and its lip one; but there was a multiplicity of rituals which distinguished the church into many distinct cults, which lived in tolerance and even harmony, since it was recognized that all cannot receive or cultivate the same kinds of good, nor have the same concept of the truth. The rituals constituted the externals of the church, and were of value so far as they had spiritual meaning far the worshipers,

Rituals are approved customs or modes of worship or of religious life; procedures that have grown up with time and been taken as representative of the inner contents of worship and doctrine. Such forms of worship are not ends in themselves, but are instrumental, serving as means to excite thoughts about spiritual and celestial things.

In speaking of ritual as representative we should note that in the most ancient times the forms of worship were not only representative, but correspondential. Correspondence is the appearance of what is internal in what is external and its representation there. (@AC 5423) With the celestial, all gestures and actions corresponded to their will and affections, as a spontaneous and natural expression. But with the man of the spiritual genius, there is a need to represent things which are not of mans love but which his understanding still sees as symbolic or expressive of what he ought to love. He kneels in prayer because he knows that he should feel utterly submissive, and he desires that this action may be prophetic of the time when there is nothing in him to resist this humiliation before the Lord. Ritual is therefore essentially prophetic - a prayer for spiritual life, for a new heart which is led by the Lord in innocence, and a new understanding which can grasp more fully things now known only superficially.

If man, as he is at this day, should do in worship only that which would come spontaneously to him; if he should say only that which he fully and rationally understands; if he should represent nothing but his own present states: then there could be hardly any use or value in external worship.

But if our worship is only representative, what becomes then of the principle that, externals should correspond to internals in order to be genuine? And if worship still is representative at this day, what then is meant when it is taught that the Lord abrogated representatives when Be instituted His church on earth?

The answer to the first question may be found in the fact that the representative externals of worship with the man of the spiritual church do correspond to his internal desire to subordinate his will to the Lord's and to reduce his life into an order which is not as yet spontaneous as with the celestial but which is still recognized as right and good and useful. If there is no such interior desire in man, his worship would be an empty external, or merely representative, merely imitative or habitual, or else hypocritical. It is sincerity and earnestness which make for correspondence.

As to the second question, the teaching is that the Lord abrogated the Jewish sacrifices, libations, and ceremonials, because since the Lord's advent man is not regarded in heaven from external things but from internals. The state of the spiritual world was changed, so that angels can no longer turn merely external representative rites or observances into corresponding ideas and affections unless man regards them from conscience or from a sincere internal. If any one is regarded from, externals it is because he is in simplicity, in which innocence and charity are concealed. (@AC 1003)

This is noted with special reference to the dietary laws of the Jews, who were forbidden to eat flesh with blood in it because this was represented before the angels as a mingling of holy things with profane. Yet now no one is condemned because of his eating such food, since his conscience permits it. Not that which entereth into the mouth defileth a man, but that ... which comes forth out of the heart. (@AC 1002, 1003)

Two representatives were retained by the Lord: baptism, which was instead of all the Jewish ceremonial washings, and the holy sipper, which was instead of the sacrificial feasts and libations. (@TCR 670, @AC 4904) Baptism was into the name of Jesus Christ, in whom is the trinity of the Father, Son, and Holy Spirit.

The Holy Supper was to be done in remembrance of Him. The sacraments were thus external representative rites, but not merely external, nor merely representative. Their power to conjoin with heaven depends on their internal contents - on the states they evoke. Both turn the mind of the Lord and to repentance of life. Both bring His teachings to mind baptism introducing into instruction, the holy supper introducing into the essential thing of worship, which is the acknowledgment that all charity, all good and all truth, are from the Lord and are the Lord's inflowing life with us.

All external worship, even in the New Church, is necessarily representative. Even our stated private devotions are - or should be accompanied by something of representative rites, as when we kneel in prayer or when we handle the copy of the Word or the Writings reverently in opening and closing it: although there is also a place for studying the Writings, in which case were would not hesitate to make annotations in the margins and using them as we would other books; and the same applies to the Word, when we might wisely use copies of the ordinary English Bible which has references and maps, and other aids. Under such conditions, ritual would be out of place.

Home-worship is accompanied with a form of procedure, or a ritual. But it is in public worship that the externals of worship come into greater perfection and thus into greater power. Such ritual is developed under priestly leadership and becomes more fully significant and representative of the internal things to which the church aspires.

Since all worship is from the Word it is natural that the ultimate forms of ritual, or the general outline of the order of service and much of its material, should be mostly derived from the literal sense of the Word, or from the Old and New Testaments, which are written in correspondences and representatives. The liturgical outline (or office)
is like a skeletal frame which givers a certain form, fixity, and order to the service, and prevents thoughtless innovations or capricious neglects which might in the long run tend to destroy the real purpose of the worship.

It is not possible here to speak further of the reasons why the literal sense is the main substance of the ritual of the church, except to point out that it is in this sense that the holiness and power of the internal senses find their receptacle and basis. It is the internal sense: and the doctrine that give illustration - and this is one purpose of the service; but the literal sense, with its correspondences and representatives, are the ultimate means of conjunction with heaven.

And the things of the literal sense accommodate infinite things of truth and good to all states both simple and wise, by presenting general truths which embrace the particulars that all perceive differently according to their understanding. Thus the church can be united by the literal sense and find in it a common ground of progress into interior things.

The order of service is only an outline or framework into which the minister fits the selections and the discourse that combine to give substance, variety, and rife to the service. The outline is so arranged that. parts may be omitted to simplify the service.

Just as the bone-system is gradually adapted in a growing body, so there has been a gradual growth in the development of the ritual of our church. The Liturgy prepared for the General Convention in 1876 but rejected by that body, was used by the early Academy and the General Church, until gradually modified and finally, in 1908, displaced by a new Liturgy prepared by Bishop W. F. Pendleton. But from about 1890 on, the practice of reading a third lesson, from the Writings, in addition to lessons from the Old and New Testaments, marked an effort towards a distinctively New-Church form of service. The new Liturgy of 1908
contained twelve office, but in a second edition only eight were offered. In the drastic revision of the Liturgy published in 1939 they were reduced to four, with two shorter offices added, together with a special service for the Holy Supper.

It might be supposed that the needs of a church-edifice of such dimension and dignity as the Bryn Athyn cathedral-church would encourage the development of a more ornate ritual. But actually, the Liturgy of 1908, when our local congregation worshiped in the Benade Hall chapel, offered a more complicated rubric than is at present employed. The services are now both shorter and simpler. On the other hand, the worship in the cathedral calls for a great many arrangements and features such as a vested choir, processionals, chancel-attendants, and ushers as well as provisions for a public-address system. These elements are accommodations to local circumstances, and while they involve no changes in the service they add to the externals of worship a certain perfection and beauty reminiscent of the call of the prophet Isaiah, Awake, awake, put on thy strength, O Zion; put on the beautiful garments, O Jerusalem, the holy city. (Isaiah 2:1) The glory of Lebanon shall come unto thee, the fir tree, the pine tree and the box together, to beautify the place of My sanctuary; and I will make the place of My feet honorable. (Isaiah 60:13)

The Arcana explains that this refers to the things of external worship. (@AC 2162)

Now it is to be understood that all the externals of worship are like garments which vary with needs and circumstances. There are no two persons who have exactly the same taste in dress or who are equally appreciative of ceremony or music, or equally sensitive to artistic grace. And so, in the adoption of forms of ritual by a church-body, we must expect that, all cannot feel alike. No one would deny that it is desirable to seek for beauty and perfection in our worship so long as the essentials of charity and faith are within - as an inner beauty. And while it would be unwise to urge for the externals of our own particular preference as essential, it is equally the part of wisdom and charity to accept with grace certain externals which seem significant and useful to others if not to us. It may also be that some customs and rites which tax our patience may contain a representation and a value which we sill later learn to treasure. To eliminate from the service everything which someone in the congregation believes unnecessary would make impossible any progress towards perfection. And since the ritual is based on the Word and hence partakes of holiness, we should take care not to wound the state of worship of our neighbors with flippant or impassioned criticism of the service. The form of our ritual as a whole and the contents of each service are arranged not by a majority vote of the congregation but by the priesthood. And each pastor relies not only on the illustration which he may have from the doctrine in seeking for the spiritual good of his people, but also on his estimate of the response of the laity as this appears from experience and from taking counsel. A ritual should not become a cause of dissension but should be the ultimate basis for a growing unity for the realization of the interior truths and goods which are represented in the rites performed.

All external worship is necessarily representative both of the charity that may be within and of the charity for which the worshiper is prayerfully striving and to which the church points. Public or congregational worship carries an even greater meaning for here, the individual merges his spiritual aspirations with those of others in the prayer that the kingdom of God may come. Thereby those of the Church become known to each other as laborers in the Lord's vineyard, willing to be led by the Lord's revealed truth. They accept in common certain ideals of faith and standards of charity, so that they can afterwards meet spiritually without self-consciousness - can converse about the issues of spiritual life, about the church and about heaven, and exchange perceptive illustration as to the common uses and responsibilities that confront them as members of the church.

They can meet not merely as persons. For when meeting others as persons, the proprium of each is apt to grate upon the other and judge the other impatiently by his ingrained faults or opposite temperament, and to give out sparks of contempt or envy whenever there are imagined affronts to his sensitive pride. These reactions are inevitable when men meet and judge each other merely as persons. The only way then to minimize conflict and dissension is to cultivate external decorum and watchful politeness. That is the way of the world; and it is necessary also in the church, as an ultimate of social order. But, the men of the church - because they are bonded in common worship - can meet also as human souls. Each can see the other as a spirit, a fellow traveler on the road to heaven, seeking the spiritual good of others; and can observe the proprium of another with the humbling confession that his own proprium is all so evil that if man be judged by this he is indeed unsalvable.

Thus the church becomes a communion of souls who, while still living and active in the worlds uses, are also lifted out of the sphere of the world and into the protection of heaven - which is promised in the benediction given in the church service.

Isaiah, 62:1-7
Matthew 26:6-13
Hymn 29, p, 450
Hymn 30, v. 1, 2, p. 451

11 November 1949

<<<

== VI. RITUAL AND REPRESENTATION

In our remarks last week it was pointed out that since the advent of the lord conjunction with heaven cannot any longer be effected through mere representative rites such as the Jews employed in their sacrifices and ceremonies which had lost their spiritual internal. Yet the law of correspondence and representation has not been abolished. And the New Church can enter into the real conjunctive use of the Christian sacraments and of the rites which belong to external worship, because now the spiritual sense of the Word is disclosed and the true purpose of representative acts of worship can be recognized. (@TCR 700)

In our age and civilization, we see strange contradictions gross superstition persisting side by side with scoffing skepticism; and other multitudes without a shepherd knowing not where they should turn for certitude or faith. The New Churchman educated to beware of irrational credulity - puts his trust in the Writings as a revelation which allows him to think rationally about spiritual things. He is wary of whatever savors of the superstitions of the past of magical salvation by ritual obedience or of undue reliance upon external forms. He is especially averse to hypocrisy or excessive pietism. But he is also apt to be a child of his age and environment. If brought up in Protestant lands he may react against elaborate ceremony, and he may easily overlook the fact that wisdom was not born yesterday; that external forms hallowed by time may have a power and a value which is not destroyed merely because men have perverted them to their evil ends. Abuse does not take away use.

This is particularly true in the matter of religious ritual. The Writings therefore instruct us about the law - the eternal spiritual law of correspondence and representation. The immense importance of this law may be seen from the fact that, in the eternal world of the after-life - which is also the world of the human mind - there is not a single phenomenon of sense or experience, not a single event, that does not obey the law of correspondences. Every thing seen and heard in the spiritual world is a representation of some inner spiritual state. And all influx of spiritual things into natural things is also according to correspondences. The soul and the mind represent themselves in the body of man through correspondences - making the body grow into a tool for the ends of the soul and making the mouth speak the thoughts of the mind.

It is quite strange that in the world this law of influx and correspondence - like many other spiritual laws of universal efficacy - is utterly unknown as such, and if mentioned would be classed as a mystical concept.

And yet men act according to it, now as from time immemorial. Whenever they wish to impress an idea or further a cause they resort naturally to the use of symbolism, realizing without reflecting on it that rational ideas have little permanent power unless confirmed by symbols and clothed in representative forms and procedures, and signified by tokens and emblems. This is evident in political or ideological movements, and is especially notable in the field of religion.

The fact is that while man is a rational being, the rational mind is but a part of his make-up, and a part which is slow to develop enough so as to become dominant. Most of his reactions are sensual - unthinking reflexes of habit and the need that confronts him from birth is to subordinate and reform the natural mind which is only a reflex or image of the world. It must be re-formed into a correspondence with heaven. The mental pictures derived from the world of the senses and organized into knowledge in our minds must be re-interpreted so as to become receptive of spiritual light. The ordinary things of life must become suggestive of spiritual truths and goods, so that they are stripped of evil connotations. Ultimates must be established in the natural mind which can receive art influx from heaven.

It is for this reason that Divine revelation is given us in two widely different forms - in naked truths of doctrine which illustrate and upbuild the rational mind; and in representative truths heavily veiled in symbols or natural correspondences, in which the infinite truth is fully contained. but only vaguely suggested. Even the Writings, in giving open rational truths of doctrine, therefore continually go back to the literal sense of the Word for symbolic confirmations, and add to this long relations concerning the spiritual world where everything appears in natural forms which correspond to spiritual states.

Let us not think, then, that the age of representatives has gone by and that the New Church is a purely rational movement which should disdain symbolic truth; nor that the letter of the Word is now meant only for children and the very simple.

It is obvious that a symbol does not lose its power because we know - or can learn its meaning. A flag on a shipmast an a far-off ocean means little and stirs slight feeling except curiosity, until we recognize it as the emblem of our own country. Yet the flag itself tells almost nothing about the country. It only creates a focus in the mind for an influx or concentration of all the things we ever knew or thought or felt about our country.

Our mind is flooded with a warm affection which sweeps away many hitter and cynical doubts and lifts us to realize the marvels of cooperation and organization which make the country a neighbor to be loved above the petty interests of self. And to each man, the flag of his homeland means a different thing according to his experience, his knowledge, his uses, his loves. But the symbol ties all these together into a whole - it produces a state confirmatory of mans character, a state by which all his past patriotic resolutions, decisions, and sporadic endeavors are renewed and are as it were again made his own. Indeed, this is the purpose in raising our country's flag.

Something similar is involved in the symbolic language employed in our worship, and in such representative acts as the opening and closing of the Ward on the altar. Almost the whole of the rubric of the service is taken from the Word in its Literal sense. Many prayers are full of correspondential imagery. The Lord's prayer speaks of our Father in heaven, of His name and kingdom, of our daily bread; all of which expressions are correspondences of spiritual things. So far as we learn the spiritual meaning, the doctrinal truth contained therein, so far the service takes on added value and power. But one reason why the service does not consist only of open doctrinal instruction is because it is meant not only for the intellect but for the will - thus representing a conjunction of the will and the understanding, or of love and faith. Love embraces more than what is seen by the understanding. It sees beyond what can be expressed in the precise terms of doctrine. It demands symbols, signs, correspondences.

For correspondences imply things known and things unknown things old and things new. When two partners wed, their plighted troth - symbolized by the wedding ring - is not an acceptance of each other in their present state merely, but for the unknown future, whatever may befall. Their conjunction is based on a mutual knowledge of their present state but looks also to the future discovery of new states of each others minds and hearts. So it is also when we embrace the Writings as a Divine revelation to mankind: our knowledge of their more general teachings so inspires our confidence and love that we accept the very books upon our shelves as a source of future light - so far as we shall advance in our reading and understanding of their teachings.

And especially is it true of the language of the literal sense of Scripture that we accept them as sacred vessels containing infinite truths of which we grasp only the mere surface with our understanding while we accept it all unseen - with our love. This is in spirit with the Lord's saying, Blessed are they that have not seen and yet have believed.

What is meant here is not a blind faith but a faith which begins by acknowledging the Divinity of the Lord and the holiness of the Word. (@AC 2568, 2094:2, 1936, 3365, 6047, 129, @SE 2545). For if this is done, there is a universal confirmation of everything in the Word even though it be not comprehended. (@AC 3388) This affirmative principle opens the mind to a progress into the interiors of truth (@AC 2568) and disperses the shades of fallacy. (@AC 1911)

It is because spiritual and interior truths rest on the truths of the literal sense, and because in the order of revelation truth couched in correspondential and representative symbols precede. more open truths, that the first past of our church-service consists almost entirely of citations and readings from the Old and New Testaments. The reading from the Writings then follows as a third lesson, in which doctrine is given which provides the key to the spiritual sense of the Word. This completes the preparation for the discourse of the day.

The church service therefore gives an epitome of mans spiritual development. It represents an ascent from obscurity to enlightenment - utilizing all the revelations given to mankind. It suggests the order of mans instruction from childhood. It also images mans reformation and regeneration, beginning with humiliation and repentance and proceeding to instruction in the particulars of doctrine.

Since this is so, and because man in the process of regeneration is not merely passive, as if waiting for influx, but cooperates with the Lord and thus has a reciprocal and reactive role, receiving the Lord's redemptive truth and saving good in freedom and with a sense of responsibility; therefore our service is not one in which the minister alone is active and the congregation sits silent and inert, as an audience at a performance. Such an attitude would befit a congregation which, like the Catholics, depended on priestly intervention for salvation, or, like the Calvinists, believed themselves to be like stocks and stones in spiritual things, deprived of free will. But in the New Church the individual is himself to serve the Lord in worship, by taking a responsive part. This is done throughout our service, by responsive prayers and singing, by alternate readings and by antiphonal chants.

Here it must be noted that the priest in the service has a twofold representation. The Arcana Coelestia shows that Moses had such a double representation. (@AC 7041-7047, 8645, 10571) When he came down from the mount with so shining a countenance that he had to put on a veil, he represented the Divine Law. When he pleaded for his people he represented the congregation. So with the minister.

In addressing the people, as he does when he reads from the Word or pronounces benedictions or blessings, he represents the Lord. He then faces the people; as he also does when giving the sermon, which he prefaces with the announcement. In the name of the Lord Jesus Christ, Father, Son and Holy Spirit.

But the priest also represents the people of the Church, as in leading the prayers or the creed, or in some of the sentences. He then faces to the altar - as he does also when he gives the ascription of glory to the Lord, after the sermon.

When the Psalter is read alternately by the minister and the people, or during the antiphon, and at certain other times, the priest usually faces halfway, since he is then a part of the congregation yet has a leading part. The Psalter has been read in alternate lines in the New Church at least since 1854; the reason being that this brings out the duality of the Hebrew construction which signifies the marriage of good and truth. This is easily seen from such a couplet as this:

Give me understanding and I will keep Thy law;

Yea, I will observe it with my whole heart. (Psalms 119:34)

The sermon is a distinctive feature in our service. Worship without instruction would be as incomplete as instruction without anything of worship. Each element may indeed be emphasized on different occasions. At doctrinal classes the element of worship is reduced to a minimum, or absent, as at informal doctrinal evenings, such as the Young Peoples Classes. The school has its worship introductory to instruction. But in our church-service both elements are usually balanced.

The New Church sermon is more than an address on morals or current social problems in the light of the Word and the doctrine of the church. So far as it rests on the opinion of the minister it is of little value. The sermon is undertaken in the name of the Lord - and must refer back to the Divinely revealed doctrine of the threefold Word for authority. The priesthood is charged to teach truth and thereby lead to the good of life. This is tantamount to an expounding of the internal sense of the Word; for the internal sense is the doctrine of love and charity and its faith. The sermon thus leads back to the internal which is within external worship - the internal worship which is involved in the life of repentance and the uses of charity by which preparation for external worship is made. It is this that leads to external worship, and of it external worship is a sign.

There may be great variety in the fern and character of the sermon. But the usual form is that of the exposition of a text from the literal sense of the Word, a presentation of the doctrine involved in the internal sense as revealed or suggested through the Writings. The emphasis may be upon the moral sense, but this should lead up to the spiritual sense. Laymen often comment if a sermon does not contain suggestions for the application of doctrine to life. But it must be remembered that the minister might interfere with the freedom of his congregation if he used the pulpit to decide how doctrine should be applied by others; except so far as the Writings themselves clearly show the application. He might indicate the life of doctrine by illustrations; and he might confirm doctrinal principles by reason and by accepted science as veil as by Scripture. But his concern must be to build up a conscience founded on rational faith, not on persuasion or dictate or fear.

The only emotion to which the clergyman can safely appeal, is therefore the rove of truth, the affection of seeing and doing the truth. The truth must be seen in its own light, and in the light of good, charity, use. Therefore the abstract doctrine must not be avoided. Doctrines such as those concerning the Lord and His glorification, or concerning creation and the laws of influx, etc., have a more universal import in building a rational conscience and thus influencing the whole mental life of man than specific teachings with more direct reference to practical life.

The object of the sermon therefore is to present the text or topic of the day in spiritual light, in a state of elevated thought from an affection of spiritual truth which is a one with a desire for the life of charity and which springs from love to the Lord. The congregation is meant to think along with the discourse as it progresses. Unless this is done, the purpose may not be fulfilled, for the balance of various truths - which is the particular task of the priest - may not be perceived. And many truths must be rightly combined to present a doctrine. Even so, where there is an affection of truth and an absence of impatient or critical moods, the wandering thought is usually brought back to perceive the essence of the doctrine presented.

The holiest act of worship is the Holy Supper. In services which center in the communion, there are preparatory readings from Scripture, and instruction is usually given from the Writings or else a short discourse may be given; but the service proceeds thereafter as a descent into the realm of the literal sense of the Word. The ordinary Sabbath service as it were traces the ascending recess of repentance and reformation to the point of the regeneration of the rational and the establishment of a spiritual conscience - and the concluding prayers are confirmatory of this state which looks to further progress. The. communion service pursues the representation further. It signifies the regeneration of the natural, which means a descent of the good and truth of the rational conscience into the ultimates of natural and sensual life, so that the natural of man shall actually correspond to the internal man and become conjoined with the regenerate rational. New natural affections and delights are born in the natural by this descent. This is signified by the Lord's words that if be that is bathed will submit to the Lord's washing his feet, he would be every whit clean. (John xiii)

In the Holy Supper, ritual reaches down to the lowest sensual ultimates. It appeals not only to sight and bearing, like the Word, but to taste and touch and smell. The Word is received and utilized by our conscious mind - the understanding. But in the Holy Supper is signified a more complete response and a more interior reception. The worshiper goes forward into the chancel and receives bread and wine which correspond to the Divine good and Divine truth, the appropriation of which shall introduce mans spirit into heaven or into the Divine Body of infinite human uses which the Lord alone orders and provides for the eternal good of all who are prepared to receive Him in His Divine Human.

By this act we acknowledge the Lord's part in the work of regeneration. Man receives food consciously, but the inner process of digestion are outside of the control of his conscious mind. It is so with spiritual food. Man accepts the truths of religious life in the form of doctrinal terms and symbols. We see only their external phase, their suitability to our superficial needs. Yet the Lord, operating in the hidden interiors of our minds, draws out, the inner essence and significance of these truths and causes them to build up our character by application to spiritual uses and needs which we are not aware of. This secret assimilation of spiritual food is the Lord's regenerative work. Even symbolic truths, the meaning of which we can only vaguely perceive, He translates before the angels of heaven into brilliant truths and warm affections by which we may become conjoined with heaven.

Even as food is purified and is carried to perform uses in body or brain which we cannot determine, so the Lord carries the inner truths (which our heart unconsciously distills out of our knowledge) as if on the stream of an omniscient Providence to repair and strengthen the fibers of the spirit. And in the Holy Supper, if mans state is repentant, these two processes, physical and spiritual, go hand in hand.

It was because of the power that resides in ultimates that the Lord assumed a human of flesh and blood in order to reach man in his low estate. And before His resurrection He instituted the Holy Supper as a giving of His flesh and blood in perpetual remembrance of Him, and that He might still be ultimately present with His faithful. For we are instructed that the Divine which proceeds from His Human can also be in ultimates, and so can preserve the heavens and save the human race. Thence is the omnipresence of His Human in the Holy Supper. (Ath. Cr. 177) And because there is the greatest power in correspondences the Word was written in mere correspondences so as to conjoin man with heaven. Thus the Word is the Lord in firsts and at the sane time in ultimates. Therefore the sacraments are instituted through correspondences, in which there is, therefore, Divine power. (Inv 59, 45)

Thus the Lord in the Holy Supper, as it were renews His Advent with men. He is present there with His whole Human and with the whole of His redemption. (@TCR 716, 717) It is a signing and a seal of the covenant of the Lord with man. It is the culmination of all external worship, because of its power to break down the resistance of the corporeal man and the inhibitions of the sensual mind. It lays a plane of other and holiness in the sensual degree, and thus prepares for the descent of that charity and faith which the Lord has previously prepared in mans conscience or in his rational man.

This is indeed that to which all ritual looks, and is the reason why public worship is. the foremost external of the church.

John 13:2-17
Chant 29, v 1, 2, p. 368
Chant 29, v 3, 4, p. 368

18 November 1949

<<<

== VII. DISTINCTIVE LIFE OF THE CHURCH

It is made clear in the Writings that the Church cannot exist without externals or worship and that the internals or worship consist in charity and its life. The real worship or the Lord thus has regard to the life of repentance and or use. This life of charity is expressed and confirmed in the acts or external worship.

Yet the life or charity itself has its external forms, apart from acts of worship. For charity is formed in the internal man while man is performing his offices and functions and carries out the duties of his work; and also whenever he comes into some relationship with other men outside or the use of his calling. Charity grows by a process of reaction with ultimate conditions in the world or the body and the senses. Charity, or love toward the neighbor or love of use, creates new habits in the body and new forms or acting, new social procedures, and a host or new uses by which this love can reach out towards its fulfillments.

Charity or love is always such as are the truths which qualify it (@AC 7759, 9154, 8772,) or the intelligence with which it is exercised. With New Churchmen, it takes on the distinctive quality or the doctrinal concepts or their faith. In the Jewish church it was required that every man wear in the hem or his garment a thread or hyacinthine color as a testimony of his religion. (@AE 576[4]) In the spiritual sense - which applies also to the New Church this signifies the celestial love or truth, which is the good of mutual love - the love or the uses or the community. (@AC 9912) The distinctiveness of the New Church is not to be a matter or dress or of outward customs, as much as a characteristic love and a manner of thinking and consequently a distinctive purpose in life. Yet this internal attitude gradually tends to make all the uses and externals of life distinctive. It causes the New Churchman to become especially averse to some of the most prevalent evils of the ago - namely, the love of adultery, the love of rule from self-love, and the evil or deceit. Swedenborg notes in his Memorabilia, These three things, especially, do those shun who will be or the New Jerusalem. (@SE 6053)

It is true that the ideal New Church community where the Heavenly Doctrine has in all things become a way of life as well as a faith and profession, is as yet far off - a thing only hoped for as an eventual goal. Yet it is - I think - permissible to observe that a New Church society is a blessed refuge from the more blatant aspects or the three evils just spoken of. It is a matter or encouragement that there is a general aversion among our people to things which carry with then the sphere or the love or adultery or anything that desecrates or breaks down the sanctity of marriage. The lewd levity which is so sadly taken for wit in the world does not often invade our social sphere; and if so, it finds little response and no approval.

For the New Church is jealous to cling to the promise that to it a love truly conjugial will be restored.

Similarly, the selfish love or rule is felt to be intolerable in the Church. Anything savoring of compulsion, undue persuasion, pressure or domination, or anyone overstepping his authority, would arouse suspicion and resentment; and New Churchmen are often so afraid of encroaching upon the freedom of others that they hesitate to act or speak even when their words or actions might be of use. We are distrustful of many methods of missionary work lest we by persuasion attract converts who really do not join us with a free mind. In our church affairs we wait for a general unanimity rather than override a minority; and we are warned not to legislate for the future, if this can be avoided. All this indicates that the Church is awake to the danger of abusing the powers we possess and is willing to respect the freedom or others.

As to deceit and hypocrisy, the Writings lay constantly before us the dark picture or the corner churches which perished because evil took on the guise or piety and faith. Rather than risking assuming a false pose, our people sometimes tend to a frank bluntness that disregards the proper courtesies and scoffs at ceremony and time-honored forms. Thus the effort to avoid one evil may sometimes lead to another extreme which is also undesirable and hurtful.

It may also be said to be typical or the New Churchman that he holds blasphemy to be execrable. Even in moments or provocation, impatience, and loss of self-control, he would at least refrain from taking the name of the Lord in vain. The confirmed New Churchman, knowing the real reason for the holiness or the Word; knowing the laws or influx and that the hells are constantly in the effort or capturing and perverting the ultimates or the Word in a mans mind; knowing that the sin or profanation is the most devastating and unforgivable of all evils; recoils with something or abhorrence and nausea to a wrongful or flippant use or the Lord's Word. It is painful to his conscience to see any or the sanctities or the Word, of the Church, or of marriage, profaned. And this is generally realized and respected with the Church.

In its attitude to death, a New Church community also displays certain distinctive traits, which ore surprising and sometimes shocking to strangers. It is usual in the world, from a sense of duty and as a sign or a warm heart, to aggravate the sorrow or parting, to harrow the feelings or those left behind, by a deliberate cultivation or melancholy and open despair and a morbid exhibition or the deed body. Instead or following this traditional pattern, our burial customs have tended to emphasize the marvelous entrance or the soul into an eternal life where its truest endeavors will find fulfillment, and the leading of a Divine providence which is over even the most particular events of every mans life. Such an attitude sometimes arouses amazement, and strangers exclaim, These people act as if there really is a life after this. There is or course a great difference between a vague hope in a future resurrection and a knowledge and assurance or a spiritual world, such as is given through the Writings.

THE NEW CHURCH HOME

We have given some instances of how the New Church, in its external life and social behavior, will manifest its interior distinctiveness of faith and love, its new sense or spiritual values which have been revealed in the Writings. We cannot point to these instances with any pride, but rather with a trembling hope that they may indicate that the fig-tree has put forth a tender branch to indicate the advent or an eventual summer.

It is not to be supposed that this increasing newness of life - which is implied in the Lord's saying, Behold, I make all things new - will always stand out conspicuously in utterly novel forms. Solomon is credited with the saying that there is nothing new under the sun. New things originate by taking old things and putting them together in a new way or using them for a new purpose. New Church educators must use the data of worldly science both old and recent, and New Church ritual will necessarily be built up or elements used in past ages. The New Churchman - throughout foreseeable times will doubtless perform secular uses which will closely resemble those performed by others in the world. He will be in the world, and will to a great degree be a partaker in the some hereditary evils as those in the world; yet he will not be of the world.

The difference the distinctive quality in the New Churchmans life will consist in a new and rational evaluation or all the elements which enter into his own make-up and the make-up of the world end society in which he dwells. His thought must be guided in accordance with the doctrine or discrete degrees which reveals the relative importance or corporeal, sensual, scientific, aesthetic, moral, rational, spiritual-natural, spiritual, and celestial uses. Each of these uses claims a share of his love and intelligence and supplies a portion or his delight. Every person is also faced with the necessity or dividing his time and strength prudently between many tasks and undertakings in order to fulfill his complex obligations. He has to devote some time to his own person, for necessary personal affairs, for repose, for nourishment, for reflection and thought and seeking information, and for exercise or recreation. He must set aside time for his home responsibilities, both practical and educational; and in the case of women, these duties are especially intricate and comprehensive. He must further perform the duties of his office or employment whether forensic or domestic, for these are the main field of his exercise of charity, and also the source of his support. He must find time to participate in the uses of the community and for taking an intelligent part (however modest) in civic and political affairs. He has to so arrange his life and that of his family that he and they can be freed from the excessive pressures and worries of the world, and - like Mary, the sister of Martha - sit at the Lord's feet to hear His Word.

For the family is not only a unit or the State or the community, but or the Church. He will therefore not think or the Church as of an outside organization which he can occasionally patronize or aid financially with credit to himself:

but as the soul or medium through which spiritual life inflows into his home and family in common with other homes and other families and individuals which all together compose the organs, members, and tissues or the body of the Church; thereby all are bound up in the bundle of life with the Lord our God. He will feel the support or the Church and its uses and a sharing in its activities as his responsibility: even as each tissue of the human body has something - a product, a hormone - to offer to the common blood stream as well as imparting stability to the frame; thus contributing to the health and temper or the whole on which every part depends.

It is no extravagance to say that a New Churchman, whose heart has kindled to the realization that the Lord has come again in the Writings and that the spiritual future of the entire world is pivoted upon the promulgation, preservation, and eventual establishment of the New Church, will devote his lire to these ends so far as the needs of the Church indicate. This does not call for his setting out to preach at street corners or for his suddenly giving all his wealth to the Church. It does not mean forsaking his family or neglecting his office or business. But it means a sufficiently difficult thing, that requires wisdom and judgment. It means so ordering his lire that the uses of the Church will not perish within his sphere of responsibility or within his community, and that the sphere of heaven will not be alienated from his family or dependents.

In the little work on Charity, there is an outline or the essential features or a perfect society in which the various uses would be justly balanced to display a complete human form. Worship, justice, morality, uprightness, wisdom, and industry would bind all functions and employments into a whole. (Charity 126-157) But such a commonwealth is as yet a Utopia not within our sight. It is as impossible for the little. groups at present composing the New Church to reform worldly society as to change the face of the earth where a rivalry and a conflict is going on between uses, between classes, between groups and between notions, and there is little to resist the constant gravitational pull towards dead externals, corporeal pleasures, and cynical and gross thinking.

But in our hoses, where the same elements are represented, we do have the opportunity to make a new beginning; to form societies in miniature where there can be shaped protective externals which correspond to true internals and prophetically reflect them. I doubt if - given the chance - we would have illustration enough to reform the world! But in his hone a man is free to seek the kind or life that may at least approximates and symbolize his ideals and his hearts desire. This is the reason why every young man and every maiden dreams or a home or their own.

It is therefore in its homes that the New Church finds its first ultimation. It is here, in the sphere of conjugial love and the love of offspring that accompanies it, that the married pair sets out to take responsibility for the future or the church and or the race - responsibility for a balanced life or use, satisfying the normal needs or body, of mind, and or soul.

All uses originated within the home and the family. Through specialization of talent and training many of the original functions of the family were gradually transferred elsewhere - to social agencies, factories, restaurants, shops, and public institutions such as churches, schools, libraries, hospitals, theaters and concert-halls-until in the present century this centrifugal tendency has made many forget that it still is the choice and responsibilities of the home to evaluate and balance these uses which even now find focus in the family. Every home has its individuality and has to meet widely varied individual needs. But we need to remind ourselves often that the home is more than a dormitory or a boarding-house or hotel! Neither must it become a tread-mill; nor a sentimental prison where everything is centered about one dominating personality; nor a place of morbid retirement from wholesome and needed social contacts. The home is dedicated to the realization of an ideal - to a spiritual as well as a natural goal: and ideals are never reached by succumbing to routines that have become meaningless, but they must be repeatedly revised and kept before us and labored for.

The externals of home-life-if characterized by courtesy, cheerful industry, orderliness, adaptability, and cleanliness are the ultimates and foundations of charity and reverence and the seminary of all the human virtues. Family life impresses upon us the fact that a solitary virtue such as insistence upon order or such as a blind obedience often becomes intolerable or stupid. A good external can be made a fetish; there must be a rational balance of all the moral virtues or none or then will be of good effect.

The uses or the home range from the lowest to the highest, from corporeal to celestial. But in relation to the wider uses of society and church, domestic uses, which are for one's self and one's own, are classed (in the True Christian Religion) among corporeal uses which belong to the love of self. And these uses are said to be good and orderly only when they serve, and are subordinated to, the higher uses of society and of heaven. Then they lend perfection to mans life; but when they are made the head of the rest, they pervert him. (@TCR 394, 395)

The true home is built upon conjugial love, and around this all domestic uses are ordered. Conjugial love is called the head of all other loves - holy and pure above them all. It is the fundamental of all good loves, because it descends from heavenly loves and contains the delights of every plane of the regenerate mind. Between the partners there is an interchange and conjunction of the inmost things of life and of perception. And in their married life all the inexpressible states of the Church with them descend into external form and into holy uses which look to the end of ends of creation, which is the procreation of human souls, and are therefore said to surpass all other human uses both in excellence and in blessedness. (@CL 68) Thus it is clear that these uses are not what is meant by domestic uses; but that they conjoin themselves with domestic uses and ennoble them.

Domestic uses are said to belong to the love of self. But we are taught that man cannot be in either health or position to perform useful works to the neighbor unless he first procures for himself the necessaries of life - food for his body and intelligence for his mind. (@TCR 406) This refers to uses which are principally of the home. If the house is made the end-in-view, its uses remain those of self-love. Such homes may seem quite pleasant, but they are spiritually barren.

The case is very different when the home is made to serve the uses of society; which is most signally done where the husband engages in some employment that is of benefit to the neighbor and where children are properly trained to become useful citizens. That kind of home may not excel in external peace or perfection, but it is vivified by a new soul and an inner purpose which transforms domestic uses from a dreary routine into a dignified ritual of deeper emotional meaning.

The home is then not isolated from the body of society, but acts like one of its organs, in unison with it. The parents and members of the family are not confined to domestic uses, but are complete human beings with broadened sympathies and wider interests.

To find a proper balance among the various uses, undertakings, and obligations or life is the chief problem in the search far happiness in the home. Yet this balance requires a common axis, a center or rotation. And while the married partners - the parents - may appear as the pivots about which the life or the family revolves, there is no safety in relying on a merely human foundation. We believe that in the New Church home the real center must be a love or the Lord in His Second Advent - which is symbolized in the family repository where a copy of the biblical Word is placed beside one or the books or the Writings. Here, then, is a source or authority for parents and children alike.

Where the dinner table is the only unifying feature and mealtimes the only occasion when the household gathers together, the New Church home lacks a distinctive, corresponding external - an ultimate in which internals find their power. The repository is a silent reminder that man shall not live by bread alone but by every word that proceedeth out of the mouth of God. Family prayers are needed not only when the maelstrom of external worry - in the rush of domestic or worldly concerns, like those of Martha who was cumbered with much serving; and also when there develops one of the familiar vicious circles of irritability and misunderstanding when the proprium of every one - both parents and children - becomes oversensitive, critical, and denunciatory, or seeks a victory through sulking or assumed martyrdom, or through the last word or the loudest voice! Or perhaps evades defeat by a dramatic exit! Such an impasse - which can happen in most New Church families - sometimes results in lasting tensions. These can often be gradually relieved by the cultivation of external courtesies, but they are not broken except by the realization of common spiritual aims. Regular family worship is needed to provide a respite from the fluster and haste of our daily program and to take us out of our proprium and allow an opportunity to the family to start anew - in mutual forgiveness and good will - towards the common goal.

And unless parents teach their children early to go to the Lord's Word daily for spiritual protection and strength, the time will soon pass when habits are easily formed. And in this hectic modern life it will be round increasingly difficult for them to initiate such orderly externals as they grow up, if their parents have not laid a foundation.

We must realize that, in this as in other things, man conquers his problems one by one by reducing difficult and complicated procedures to simple habits. Habits are indeed the rituals of personal life. They invite influx. They confirm our resolutions and our free strivings towards our ideals. They give power, save energy, and make life spontaneous and efficient.

If a regular, stated time be set aside - sanctified - for family-worship as it is fixed for a mealtime, the routine of other uses can be easily adjusted. And let us reflect that the Lord gives to the home not only our daily bread, our bodily strength, and our worldly wealth. He loans us also that strange and precious thing called time - time to live on earth, we know not how long. Is it not proper then that we bring him tithes not alone of money and labor, but of Time; a time to listen to His voice, and reflect on His mercies?

Readings: Luke 10:38-42

Hymn 47, p, 469

Anthem 5, p. 589

Delivered December 2, 1949 by Rev. Hugo Lj Odhner at Bryn Athyn, Pennsylvania (Published in Parents Teacher Journal, January 1950)

<<<

== VIII. EXTERNALS OF LIFE IN COMMUNITY AND CHURCH

In the life of the home are contained as in a replica all the uses of human society. This is acknowledged - to some extent - by common sense; but in the New Church it is made clear by the doctrine of the Grand Man, which shows that every society, large or small, is in the human form, The home or the family is itself a society in a small form, but also a part or unit of a larger community, commonwealth, or country. A
wise civil government recognizes this and offers protection to the family. The family draws its subsistence from the common good of society, but this common good comes into existence from the goods of use which the individuals of the family perform. In a well constituted commonwealth therefore, provision is made that no one shall be useless. (Charity 127, 128) Our doctrine also brings out the fact that it is primarily in the performance of the special uses of each individual that he becomes a form of charity. Society depends on each mans performing the use of his calling, office, or employment faithfully, sincerely and justly. But if he also looks to the Lord and shuns evils as sins he becomes a form of charity, that is, an external embodiment of love to the neighbor.

In the Doctrine of Charity many examples are given as to how men in widely different employments can become charities in form: priests, officials, soldiers, businessmen, workers, servants, etc. Women's uses are not there mentioned, but in the work on Conjugial Love it is shown that their typical offices which are usually performed within the home and partake more of affection than of cold intelligence - are the sphere in which their regeneration is effected. And it is also shown that by mutual aid the husband and the wife perform uses to society which neither could do alone. (@CL 175, 137)

The work of one's employment is the external of a mans use. The internal is the love of the good of the neighbor, or the love of uses. But life would become a chimera if a man, because he loves to be of use, would feel obligated to rush around frantically helping every one he sees, or scattering his efforts indiscriminately, doing good where he is not even wanted or more often to those who simply use him as a dupe. The world could then become one vast confusion. It is therefore provided - and it becomes more and more necessary as society grows complex - that each man should prepare and train himself for some useful work, work within his own range of talents, and make this his special contribution for the common good; and that he should channel his love of use, or charity, for the best performance of this work.

This does not imply that we should callously close our ears and hearts to the call of distress, or bury ourselves in our work to the exclusion of obvious obligations - domestic, civil, moral and spiritual. But it means that we should center our efforts around our life's work or around the duties which we have assumed as our employment. In that employment there is a protection not only against poverty and want but against the dissipation of our mind and talents. In such definite duties there is a leading of Providence. Our thoughts are concentrated on the needs of others, and removed from conceit and reflection upon self.

All the additional obligations of life are clustered around the duties of our calling, and are usually proportioned to these. Those in more eminent uses generally have a more varied range of public and social obligations, connected with their central field of work. But every citizen owes debts to his country, which be discharges cheerfully if be is in charity. He also owes debts to the Church, which he can honor by giving material as well as moral and spiritual support. (And the New Churchman has the added duty, to prevent the Church from becoming a mere tool in the hands of the State, as has happened in many countries.)

There are debts which are in the nature of contracts or solemn promises. Some are fixed by law - such as public taxes, levies, and fines; others are private debts, wages, etc. The stability of the economic structure and the maintenance of the exchange of commodities and services demand that such debts be settled; and he who has charity in his heart will fulfill such responsibilities with sincerity and benignity and to the best of his ability, and will use his prudence to avoid incurring debts which he will not be able to meet. (@TCR 430-432, Char 187.)

But we incur other obligations which are far more difficult to measure - debts which we scarcely realize. We acknowledge this in our daily prayerForgive us our debts, as we also forgive our debtors. From childhood to the grave we are continually put under obligations which we can never hope to repay - and for which no payment is asked. Many a gift would lose its point and meaning if it should bring with it a compulsion to repay in kind. For this would lead to competitive giving as if life was a perpetual Christmas. Especially would social obligations, like those of hospitality, mount up into an unbearable routine which left no room for normal living or usefulness. Those who live by the principle proverbially expressed as keeping up with the Joneses will eventually seem ridiculous in the eyes of others and imprudent in their own eyes.

The kindness and helpfulness that men show towards one another must therefore not be measured critically, but are to be extended and accepted as symbols of affection - even as a gift is not graciously received if it be judged by its material value. If so regarded, the natural obligations which men contract become the external foundation of the friendship and the trust that go to beautify life and that enrich the reservoir of mental peace to which all men must resort for new strength.

Every love brings with it obligations. This is so in the home and the family, in the reciprocal relations of parents, children, and servants. Various kinds. of love make us recognize our obligations in various directions. When once recognized, obligations are fulfilled from a sense of duty, from necessity, even if there is no particular feeling of good pleasure or choice in the matter.

But charity sometimes acts where there is no pressing obligation or sense of duty. Such acts the Writings call benefactions or favors - acts which a man does apart from his employment and at his own pleasure, in entire liberty, without necessity, and for specific assigned purposes. To help the needy, caring for widows and orphans, contributing funds or labor for hospitals or church buildings, special gifts to hospices, gymnasia, etc., are mentioned in the Writings as examples. Such donations, it is noted, are frequently matters of indifference. But if benefactions are not given with prudence or discrimination, but merely from a soft, heart, harm can be done and evil encouraged. Yet equal care must be exercised not to stifle the generous instincts of children in their innocent desire to help all who look needy. Benefactions are genuine spring spontaneously from charity so far as there is no feeling of merit attached to them.

It is often hard to tell where duty stops and acts of good-will begin. But the thing that makes all external forms of use, or of obligation or of generosity to be of charity, is that a man looks to the Lord, shuns evils as sine, and regards as the neighbor the good that is with others. This elevates charity to be more than a love of persons. It becomes a love of good and truth wherever found, and thus a love of the Lord. And this is meant in the parable when the Lord said to those on His right hand, Inasmuch as ye have done it unto one of the least of these My brethren, ye have done it unto Me. (Matthew 25:40)

In the life of a New Church society, all these externals are to be balanced by good judgment so that the essential uses do not become absorbed and dissipated in trivialities. The foremost uses of a society of the Church are worship and evangelization. The distinctive externals of worship have already been referred to. The church service contains evangelization as well as worship. The Word is read and instruction is given in spiritual things - especially by an exposition of the spiritual sense of the Word. But for the study of particulars of doctrine, doctrinal classes are also provided, adapted to general and specific needs. These classes are intended for the systematic development of the doctrinal understanding of the congregation that there may be a growth of a common perception of the aims of the Church both in reference to heaven and to the world.

To confine public doctrinal instruction merely to the simplest needs, those of young people and noviates or people who do not care to expend any effort to gain a deeper understanding, would fatally retard the progress of the Church and dam up the flow of zeal and illustration. Progress is possible only on the condition that there is a laity which is informed in various fields of doctrinal thought, and which, from private reading of the Writings, is inspired by the spiritual love of truth which is the test of New Churchmanship. (@AR 831, @AE 732)

Time was when we could isolate ourselves and our children from the influences of the world and our defense lay in a virile attack on the dogmas of the old church. But the increase in worldly learning and the confusing propaganda of every enthusiastic phantasy and cleverly disguised falsity and insidious evil which pour in upon us in floods of magazines as well as on screen and radio, stress the need of life - long adult education and the development of a New Church philosophy of life that can guide us through this maze of errors and temptations from childhood to old age.

One of the most striking features of our body of the New Church is our system of distinctive New Church education, the maintenance of which has become the most pressing obligation of charity in many societies. Education has bean adopted as the most practical form of evangelization, since the seed of truth is thereby sown in receptive soil, as yet not much infected with the falsities of the world.

But although the use of Education has developed a whole new field of externals belonging to the Church, the consideration of this subject must be deferred to some other occasion and perhaps referred to other speakers.

It is our trust that the extension of New Church education will cause the light of heaven to be shed upon all fields of thought and experience and will result in a higher learning and a greater power for the Church, and thus prepare for the day when it can minister to multitudes whose ears are now closed.

In the meantime the infant New Church is only among a few who are struggling to preserve the precious sanctities of the new revelation. The laborers are few, but immense spiritual harvests seem to lie ahead. We are faced with the temptation of undertaking what is beyond our power, or of evading necessary uses from a lack of courage or a too critical desire for immediate perfection. On the other hand there is a sense of security and solidarity in the existence of New Church societies with a common social and religious life.

What a New Church society can mean to us is sufficiently clear if we contemplate life without it. Except for a few temperamental recluses and a few who have retired for reasons of health, New Churchmen generally recognize the need for contacts with other adult minds in the sphere of our common faith, of our mutual amity, and of the uses and interests to which we are devoted. Our church uses require such association in committee work and consultations - or nothing would be accomplished. But it is a part of our doctrine that charity seeks also other types of social communion, whereby our hearts are gladdened and united, our minds stimulated, challenged, and diverted from the toil of our uses, our senses delighted and our bodies recreated.

The internal of charity must have externals in which it can rest as well as externals through which it can work, The affection of use tends to strain the mind and make it dull and listless unless it is relaxed by some variety. The mind chooses pleasures according to its interior state in the viscera of the body-pleasures correspondent to the minds operations. (@Char 191) For the subtle balance of one's moods are closely connected with the nervous system and the activities of various glands of internal secretion.

A mind inspired by a love of use will seek diversion in pleasures which correspond to something of charity and honesty. There are men who live with pleasure as the only end. These seek carnal and evil delights, voluptuous pleasures, intemperate and cruel, and become the slaves of their appetites, loving only food and drink, filthy talk and a lazy life.

The amusements of the evil also consist in seeing how far they dare go in indulging in an evil or in approving evil without taking the risk of committing it to the full; approaching it by hints and as it were with a leering innocence; and disguising it so as to trap the simple or the uninitiated, Such things feed and recreate their evil loves. But the diversions of charity renew the love of use, and the enjoyment of such pleasures is broken at the proper time by a longing to return to one's use - return, not incapacitated for work, but restored in body and spirit.

The Writings give instances of the kind of recreations which are proper externals of charity: social intercourse, conversations, walks and sight-seeing, theatricals of moral value or with plots in which the Divine providence shines forth; music, songs, decorous jesting; banquets and entertainments, games of chance or skill at home, dances at weddings and festive gatherings; exercise, sports, manual hobbies; and reading of pleasing historical or doctrinal books, and of newspapers.

Some of these diversions are private or centered in the home. They are needed to develop a mans personality and make the home a center of social charity, delightful for the young as well as for the old. It is of value that young and old be not always socially separated. In the hone sphere - and the sphere of conjugial partners - moral, and social ideals can be formed, and hospitality and gracious manners can be instilled. This is of course the reason for the principle of chaperonage.

But youth eventually is moved to explore social possibilities beyond the homes of the parents and their friends. In the formative years, before judgment has matured, the too adventurous search for social delights outside of the sphere of the Church, usually has results which are later regretted and which are sometimes emotional tragedies that cannot be undone. No iron hand can prevent this; although parental authority must continually moderate youths impatience by moral suasion. But it becomes an obligation of parents and of the Church to provide a New Church social life where the needed pleasures and diversions will contain the proper internals. And since for young people social life eventually looks toward the state of marriage, the soul of our social life must be an ardent longing for a conjugial life, and a shunning of the opposites as pleasures of insanity. It is this that makes distinctive New Church social life not merely the coming together of people nominally of the Church!

It is in his periods of recreation, when he has nothing to do but follow his own inclinations, that a man is most vulnerable to evil influences. In the sphere of one's uses and obligations there is a Divine protection;

and we need not avoid the normal associations which our uses call for, unless we are in the grip of the love of the world. We may, in an attitude of mutual tolerance, associate with others who are of different doctrine and religion, may learn and fairly appreciate their uses and virtues, but not become imbued with them or conjoin them with our own truth. (@AC 5117) Our conscience which is to guide our lives must be formed from our own faith. In passing, we may taste the grapes of our neighbors vineyard, but must not put any in our own vessel. (Deuteronomy 23:24) And while the ordinary courtesies of life must be extended to all, without any need to explore the interiors of their minds; while external friendships with those with whom we are in association and commerce are not hurtful; yet for our protection the doctrine also says, that every one may indeed be friendly to others, but still he should be most friendly to what is good! (@TCR 449, @AC 4804.)

Great injury may be done to one's spiritual life by friendships which are indulged merely for social reasons without caring whether one's friends are good or evil, provided they are agreeable. For evils can be inspired into the good but not goods into the evil. (@AC 4804, @TCR 448)
And when friendship becomes undiscriminating a blind infatuation - the love of the person easily becomes a conjunction with his evils. (Faith 21)

The warnings of the Writings against false friendships, against the formation of mutual-admiration societies or the setting up of pleasure or self-indulgence as the only desirable end in life, should suffice to prevent the social life of our Church from trespassing upon its more internal uses, when it is really to be the servant of these uses.

How social externals can assist spiritual uses is exemplified in our weekly suppers of charity, which free many families of domestic affairs so as to facilitate their attendance at the doctrinal class and the congregational singing practice. In the True Christian Religion, in the recital of what charity is and what are the benefactions of charity and the debts of charity, the various diversions of charity are not mentioned; but the statement is simply made: The recreations of charity are dinners, suppers, and parties. And it then explains that these are with those who are in mutual love from a similar faith. It speaks of the love feasts or agapes of the early Christians, how they had conversations at table about various things, domestic and civil, but especially about matters of the Church; and that the presence of a spiritual sphere of charity exhilarated their minds and softened the sound of every speech;

and thus brought heartfelt festivity into all their senses. There were also social meetings of charity among them, for they were a spiritual fraternity. In such companionship they found consolation for the adversities of the church, exultations for its increase, and also recreation of the mind after studies and labors. (@TCR 433, 434)

The social life of our society is therefore centered in our weekly suppers and occasional banquets and assemblies. But provision is also made for other diversions, within the sane sphere of charity, the sphere of the Church. The social needs of young and old, of the society and of the schools, have to be weighed carefully in any program of social events. But especial care must be shown - on the one hand, that the serious duties of life be not interfered with by an irresistible social whirl, and on the other, that our freedom as individuals and as parents be not made of none effect by the alluring externals of social life.

In a New Church community there is a marvelous opportunity for setting up standards generally agreed upon as common-sense safe-guards, especially for our children. The word standard does not imply a rule but an objective, a result of free consultation and free cooperation. There must be respect for the freedom of individuals and homes, respect for various interpretations of what the Writings teach about life and how these teachings might apply to one's circumstances.

One example of this is found in the matter of Sabbath observance, with the Jews the Sabbath was the principal representative in all their worship which they would profane if they as much as gathered a few sticks on the Sabbath day. Christians followed the Lord's teaching that good could be done and necessary tasks performed on that day. But later many Christians made it a day of almost continuous worship and Bible reading - as in one of the imaginary heavens shown to Swedenborg in the spiritual world. The people of the Academy movement reacted against such a surfeit of sad and dreary solemnity. What the Writings actually teach is that the Sabbath is no longer a merely external representative of the Lord's glorification and resurrection. When the Lord came..., they state, that day was made a day of instruction in Divine things, and thus also a day of rest from labors and of meditation in such things as belong to salvation and eternal lire, and also a day of love towards the neighbor. (@TCR 301)

This, now, is the direct meaning of the commandment, Remember the Sabbath day to keep it holy.

It is - for the mew Church a day of instruction and meditation, a day of rest from our ordinary labors, and also a day of love towards the neighbor. And charity does not, of course, rule out those diversions of charity in which the spirit and purpose of the day are still remembered. But it is left to each one of us to reflect what kinds of diversions are proper for us and our children - for whom externals are of such great importance without our making the commandment void of meaning; lest we follow the current of the worlds practices which are gradually converting Sunday into a secular holiday. Certainly there is no need to make Sunday a day of penance, a day to be disliked for barren intervals of tedium between our religious duties. Certainly the range of proper diversions is wide enough to include neighborly charity, and hospitality, and diversions which have some mental profit, without resorting to the more hilarious types of frolic or to entertainments that are better fitted for other occasions or to labors that intrude upon family peace.

A word in closing. In this series of classes various externals of the Church and of our common life were described and the endeavor was to show that the externals must come to correspond with the internals of the Church which are charity and its faith. The Lord has given the Word and the holy sacraments as essential and unchanging Divine ultimates for the presence among men. But only to the changing needs of man and their differing states of response, external forms and modes cannot be static, but will grow and alter with the progress or retrogression of the Church. In internals there must be firmness, for they are the eternal source of progress. As to externals there must be within the Church a large degree of freedom - plasticity in modes and procedures, in methods and instrumentalities, freedom in judgment and cooperation.

We have pointed out some of the reasons for the externals that characterize our Church; with the thought that as long as these reasons are recognized in the Church, the ultimate forms of government, of ritual, and of life will serve to conjoin the members of the Church rather than to prove matters of contention; and will be accepted as a common road to a common goal. The achievements are worth our efforts even if we find on reflecting that we have traveled only a few stumbling steps on this road. For it leads to the fulfillment of the promise that in the New Jerusalem there will be no empty, spurious externals, no external separated from its internal. (@AR 918)

Matthew 25:31-40
Hymn 24, p. 444
Anthem 7, p. 587

9 December 1949
