= Formative States Of The Human
By the Right Rev. Willard D. Pendleton
include::../template-attributes.adoc[]


Formative States Of The Human + 
By the Right Rev. Willard D. Pendleton

A series of five lectures + 
delivered to the EDUCATIONAL COUNCIL of the General Church, + 
August 1968.


Note teaching: [underline]#*Man is not born a man, but becomes a man*#

CL 156 (b) Acton + 
CL 152 (a) Alden + 
CL 152 (2) Standard + 
TCR 692 (6) (Same Memorable Relation)

<<<

== Lecture I - Genesis 11:27 - 12:6

Lesson: Genesis 11:27-32; 12:1-6; @AC 1407-1408.

Indeed, it is said in (@DLW 270): "Man is born an animal, but he becomes a "man.

This does not mean that at birth man is an animal, for he possesses a human soul; but it does mean that until the lungs are opened, that is, until the child takes his first breath, he is as the animal.

Unlike the animal, therefore, man possesses a potential that the animal does not possess. This potential is found in the child's capacity to become a man. For whereas the animal is a creature of instinct, man is a being who is endowed by his Creator with the ability to rise above his natural instincts and thus to become, spiritually speaking, a man. Note the teaching: All men whatsoever are born natural, but with the power of becoming ... spiritual or celestial (@AC 4592[3]; @AE 449b[3]).

When the Writings speak of the human, therefore, they have reference to the human mind. It is this which man puts on by means of birth into the world. For at birth man possesses both a soul and a body, but as yet no mind. For as yet the mind, that is, the plane of man's conscious existence is without form and void, and darkness,... [is] upon the ... [faces] of the deep (Genesis 1:2). Note here the use of the word 'form', for it is by means of knowledges derived by way of the senses that the human mind takes form.

Observe here that a knowledge of the doctrine of forms, as introduced into the philosophical works and fully developed in the Writings, is basic to the understanding of New Church education. For what are knowledges but forms; that is, forms in which, as in mirrors, truths may be seen.

In this connection note the following passages: Knowledges are imbibed by hearing, seeing, and reading, and are stored up in the external or natural memory. These knowledges serve the internal sight or understanding as a plane of objects that it may thence select and elicit such things as may promote wisdom (@AC 9723). Also: To rational wisdom pertain ... all the sciences into which youths are initiated in schools, by means of which they are afterwards initiated into intelligence... such as philosophy, astronomy, jurisprudence, politics, ethics, history, and many others, by which, as by doors, they enter into things rational, whereby rational wisdom is formed (@CL 163). Also: Knowledges are means, and as it were mirrors, in which an image of interior things shows itself; and in this image, as again in a mirror, are reflected and represented the truths and goods of faith (@AC 5201).

We will have more to say about knowledges as forms when we come to the consideration of the developmental states of the human which are directly dependent upon formal instruction. (Here note the use of the word 'formal'.)

It is important to observe that the central subject of this series in the Arcana Coelestia is the Lord. Chapter by chapter, and verse by verse, the Writings here treat of the Lord's birth and the successive states which He assumed through infancy, childhood and youth. These states apply to man only by way of analogy. It is to be understood, however, that in considering this series at this time our interest is focused upon man. It is not my intention to become involved in the subject of the Lord's glorification. What we are concerned with, therefore, is the application of these teachings to the educational process, that is, to the formative states of the human. For what is said here applies, with a difference, to man, the difference being that the Lord's soul, referred to in Scripture as the Father, was the Divine life itself; whereas the soul of man is a finite vessel receptive of life from the Lord. Having stated this difference, which has a fundamental bearing upon every state that the Lord assumed, we proceed to the consideration of man. In this connection we note that the same laws of mental growth and development apply.

By way of introduction to the educational implications of the Divine text, however, it may prove useful to consider briefly the historical setting in which the drama took place.

The central figure in the chapters under consideration is Abram (or Abraham). According to the Scriptural account he was the son of Terah, who dwelt in the land of Ur of the Chaldees.

[.text-center]
`--- image content not available ---`

////
Map: Ur

Babylon

Kingdom of Mari

Haran

Canaan

Fertile Crescent 2000 B. C.

[drawn map]

Chapter 11 (Ancient Word)

Begins with Tower of Babel (1-9)

Genealogy (Shem to Abram) (10-27)

Shem to Eber

(Eber--from which name of Hebrew nations was derived. ... Eber means passing over or, the passing over the worship and doctrine of the Ancient Church to the Israelitish Church. (C. T. Odhner, Correspondences of Canaan, and @AC 1343.

Heber--beginning of 2nd Ancient Church)

Eber (pass on to) Nahor

Terah

Abram--NahorHaran (died in Ur)

/ / /

Idolatry - Self World Pleasure (See @AC 1357)

/ / /

Isaac Bethuel /

/ / Lot Sensuous

Jacob Laban

and

Rebecca

Here, some interesting questions:

a) Haran - Abram's brother;

also name of city.

Same true of Nahor.

b) What was Terah doing in Ur?

Abram--Semite

Ur--Samarians

c) Ur--Highly sophisticated (Morley 1923)

Babylon in 600 B.C.

One story houses--mud or brick

Ur in 2000 B.C.

Two story houses

Villas--13 or 14 rooms

According to Werner Keller (Bible as History) Abram did not come out of Ur, but out of the Kingdom of Mari (Syria).

Excavations in 1933 220 rooms 10 acres

Palace

Your fathers dwelt on the other side of the flood in old time, even Terah, the father of Abraham (Joshua 24:2).

Terah and Abram were strangers in Ur.

Their real home was Padan-Aram.

Haran--Nahor = cities Padan-Aram = Plains of Aram

HaranAbram

NahorLaban

Records found in Mari speak of:

a) Benjamites (Semites)

b) Family names such as Serug, Nahor, Terah, Haran and other ancestors of Abram.
////


At all events, we read in the closing verses of the eleventh chapter of Genesis: And Terah took Abram his son, and Lot the Son of Haran his son's son, and Sarai his daughter-in-law, his son Abram's wife; and they went forth with them from Ur of the Chaldees to go into the land of Canaan; and they came unto Haran, and dwelt there. And the days of Terah were two hundred and five years; and Terah died in Haran (Genesis 11:31-32).

In the opening verses of the twelfth chapter where it is said in the Writings that true historicals begin, we read: Now the Lord had said unto Abram, Get thee out of thy country, and from thy kindred, and from thy father's house, unto a land that I will shew thee (Genesis 12:1).

It is said in the introduction to this chapter in the Arcana Coelestia:
The things related in this chapter concerning Abram represent the Lord's state from earliest childhood up to youth (@AC 1401). This chapter treats of:

a. The call of Abram.

b. His departure from Haran.

c. His entrance into the land of Canaan.

d. His progression from the north to the south.

e. His sojourn in Egypt.

While it is true that it is the Lord who is treated of here, these things also directly concern man. For the Lord cane into the world as man, and, as the Writings say, it was necessary, if He was to become man actually, that He should be conceived, carried in the womb, born, educated, acquire knowledges gradually, and thereby be introduced into intelligence and wisdom (@TCR 89). What we are concerned with in this chapter therefore are those states of life through which man passes from first infancy up to the time of youth. Five states are here described, those states which are represented by:

1. Haran

2. Shechem

3. The Oak Grove of Moreh

4. Bethel and Ai

5. Egypt

In carefully considering the contents of the chapter, it seems apparent that the first four states are descriptive of the progressive states of infancy, while the last state, namely, Egypt, has reference to those years of childhood which lie between infancy and youth.

Considering these states in their order we begin with the words, Jehovah said unto Abram, which is said to signify the first mental advertence, or animadversion, which means to turn the mind, to take heed or notice of, to perceive; that is, to be aware or conscious of
(@AC 1410).

Here an interesting question arises. Does this first mental advertence have reference to the first living sensation, that is, to the first breath of life, or does it refer to what Bishop De Charms, in the Growth of the Mind, describes as the dawn of consciousness? According to Bishop De Charms there is a difference between sensation and consciousness. As he aptly points out, we can receive sensations without being conscious of them (Growth of the Mind, p. 111). He holds, therefore, that during the first month of the child's life there are indeed active sensations, but they cannot be interpreted in terms of consciousness for there is as yet no fixed attention upon them (Growth of the Mind, p. 113). He says that during the first month the sensations pass through the brain in a constant stream, and are received, as it were, in sleep, without being specifically noticed. And this dream life must go on for some time before a focusing of attention is possible (Growth of the Mind, p. 113). What is involved here may be related to Abram's life in Haran prior to his call. It is a state of spiritual or mental obscurity. With the first conscious or meaningful sensation, however, a miracle takes place. For by virtue of this first mental adversion the way is opened whereby the child begins to form some idea of that which he experiences. Here, therefore, another question arises: is there a difference in the quality of the sensation which the child experiences as compared with the animal? Not only do we believe that there is a difference, but we hold that if this were not so, man would remain as the animal.

What is this difference? How do we account for it? Does the difference not lie in the quality of the delight or the affection which the child experiences? In both instances it is a purely sensual affection, but all influx is according to reception. To understand this, bear in mind the teaching of the Writings that it is the soul which perceives in the body; and as the human soul, which in essence is the affection of good and truth, (see @DP 34) differs from the soul of the animal, so that which is perceived by man differs in quality from that which is sensated by the animal. In other words, in even the most primitive affections of life there is something present with man that is not present with the animal. It is present in the quality of his affections.

Is not this directly involved in the words, "Get thee out of thy land"? For the Writings say that in the representative sense this means that He (the Lord) should recede from corporeal and worldly things (@AC 1411) as represented by Haran; that is, that He should recede from the delights and pleasures of the senses (@AC 1412) and advance into "the land I will cause thee to see"; that is, into the land of Canaan, by which is signified spiritual and celestial things, which are truths and goods (@AC 1413).

This teaching, as applied to man, has reference to the Divine endowment; that is, to that ability or capacity with which every man, as distinguished from the animal, is endowed by the Lord. By virtue of this, man is capable of receding from the life of the senses and of entering with delight into the life of the spirit. Were this not so, man would remain a creature of instinct.

What we are speaking of here is the affection of truth, that is, of man's ability to be affected by truth. This the animal does not possess. The animal can form no concept whatsoever of truth or of good. But the question arises, What of the infant? Certainly in the first year of his life the little child is utterly incapable of any abstract concept. How, then, do the words, Get thee out of thy land ... to the land that I will cause thee to see, apply to the child's first conscious perception? They apply because all perception is from love, in that it is love which perceives. What is perceived by the infant, I therefore, is not as yet perceived as a truth but as a sensual delight. But within this delight there is a latent affection which aspires to the understanding of the sensation. Hence the teaching of the Writings: The rational is not born, (as is supposed) of knowledges (scientiae et cognitiones), but of the affection of these knowledges, as may be seen from the ... fact that no one can ever become rational unless some delight or affection... aspires thereto (@AC 1895).

The desire to understand is with the child from birth. It is an affection of the human soul. The fact that it is not observable until the child has learned to talk and to ask the question, "Why?", does not mean that it is a later development. Were it not present with the child from birth he would not learn to talk for he would not have in himself any capacity to associate meaning with words.

We pass now from the dawn of consciousness to the second state of human development. For having left Haran, Abram came into the land of Canaan, even unto the place Shechem. Abram's entrance into the land of Canaan is said to signify the attainment of the celestial things of love (@AC 1438). It is said: The celestial things of love are the very essentials; and it is added, the rest come from them (ibid). What the Writings are speaking of here are all those primitive affections of early infancy with which man is endowed by the Lord. These loves, or affections, are good loves because they are innocent. What is more, they are said to remain with man unless they are destroyed in later life by deceit. Hence they are called remains.

There is no need at this time to dwell on the doctrine of remains; the subject is familiar to us. It is one of the basic concepts of New Church education, and certainly the most distinctive. I say 'the most distinctive' because there is nothing in modern educational psychology which is comparable to it. While it is true that modern psychology recognizes that the experiences of childhood have a profound effect upon later life, what is not recognized is that these states of infancy are ordered by the Lord and that they are His dwelling place with man. As Bishop N. D. Pendleton once said: "Life's treasures ever come out of the past, and the deeper the past, the greater the treasure. An especial sanctity pertains to the early store of life's impressions, and also a high degree of power. Childhood memories are man's Holy of Holies. The worst fate that can befall man is from the destruction of man's first-born affections (The Wells of Abraham: The Glorification; Chapter 1, p. 7). The first remains, or affections, however, are not subject to recall by the memory in that they belong to those years of which man has no recollection. Nevertheless, the Writings insist that these first states of love are the very essentials, and that those states of childhood which follow, come from them (@AC 1438). For it is said that from these states, as from their seed ... all things afterwards [are] made fruitful (ibid).

Hidden as they are from human introspection, what can be said about these primitive states of innocence? We know that they have their origin with man in the delights which the infant perceives in sensations, as is evident from the child's response to light, color, sound and touch. But what is the origin of the delight itself? According to the Writings, life inflows, and when it is experienced in, or as, a sensation, it is sensed by the child as a delight. Hence it is that all loves, affections and delights are with man from the Lord. Concerning this the Writings state: Man places life solely in what is sensuous and scientific ... when yet the case really is that the Lord inflows ... and without an influx of the Lord's life ... into the voluntary (that is, into man's affections) there would be no life with man (@AC 657). Also: Through the internal [man] from the Lord, comes all perception. From no other source does perception come, nor even sensation. ... The senses placed in the body are nothing but organs or instruments that are of service to ... man ... that ... [he] may be sensible of what is in the world; wherefore the internal flows into the external causing it to feel, to the end that ... [man] may thereby perceive and be perfected; but not the reverse (@AC 5779).

What is meant, therefore, by Abram coming to Shechem, is that state in which, as the Writings say, the celestial things of love become apparent (@AC 1439, 1440). The reference here, however, is not to perception from understanding, but to perception from love. Concerning this the Writings state: It is one thing to be in celestial things, and another to be in the knowledges of... [them] (@AC 1453). What is described here, therefore, is the quality of those first affections by means of which man is disposed to good. The good that is perceived, however, is felt, it is not seen, hence it can be described only as a disposition to good; that is, as a sensuous delight in which there is that which is good. In other words, within these primitive delights of life the essential human is potentially present as good, that is, as the good of remains; but it cannot take form, that is, it cannot become visible to the sight of the understanding until by way of instruction the way is opened whereby truth may be conjoined with good.


<<<

== Lecture II - Genesis 12

Lesson: Genesis 12:6-10.

We come now to the third state described in this chapter which is signified by the oak grove of Moreh, (Hebrew ELON=oak grove) which was in Shechem. Concerning this it is said in this chapter that by trees themselves are signified perceptions; by the trees of the garden of Eden eastward, inmost perceptions, or those of intellectual things; by the trees of the forest of Lebanon, interior perceptions, or those of rational things; but by the trees of an oak grove, exterior perceptions, or those of memory knowledges [scientifica], which belong to the external man (@AC 1443).

In this connection two basic teachings should be noted: First, that in coming to the oak grove of Moreh it is said that Jehovah appeared to Abram; and second, that this signifies that it was here, that is, in this state, that the Lord attained perception. So we read: As soon as Jehovah appeared to the Lord in His celestial things [Shechem] it is evident that He attained perception; all perception is from celestial things (@AC 1442). Hence it is that the oak grove Moreh signifies the Lord's first perception; for He was as yet a child, and His spiritual things were not more interior than this (@AC 1443).

So far we have been speaking of perception as an awareness of sensation. Here, however, as is evident from the text, perception has reference to the understanding of a thing. It is in this frame of reference that the Writings usually speak of perception, as for example, where it is said, The knowledge of a thing must come first, in order that there may be a perception of it (@AC 5649, 1802). In other words, we may feel, we may sense, we may experience a thing, and in so doing we are aware of it and affected by it. But if we are to understand, that is, if we are to perceive it in an intellectual sense, we must have some knowledge of it. Hence it is that in coming into the state signified by Shechem, the child attains to the celestial things of love, but while yet in Shechem; that is, while yet in a state or innocence, he comes, by way of instruction, to the oak grove of Moreh.

This cannot take place until the child has first learned to communicate by means of words. But somewhere in the child's third or fourth year he has acquired sufficient knowledges that he is ready to be introduced into the idea of God. Of this state it may be said that the Lord appears to him.

Of all of life's experiences there is none as significant as the child's first-formed idea of the Lord. While what is learned in later states infills and perfects our understanding of Him who is the source of all life, it does not supersede it. The child's first-formed concept of the Lord as a Divine Man involves the essential truth concerning Him. He, who in later life loses sight of this truth, is as a blind man who gropes in the darkness.

But if the first-formed idea of the Lord marks with the child the beginning of wisdom, it also marks the end of that celestial period of life in which the child is totally dependent upon his affections. With the idea of God also comes the child's first-formed concept of truth and the progressive development of a conscience within the understanding by which man must be led as he recedes from innocence of infancy. These developmental states in the formation of a conscience were considered by me in a series of lectures entitled Values and Objectives of New Church Education, given to this Council in 1964.

We come, then, to that period of life which is best described as early childhood. In general it includes the fourth, fifth and sixth years. So it was that Abram left Shechem and his encampment at the oak grove of Moreh, and journeying toward the south he came to a place having Bethel toward the sea, that is, on the west, and Ai on the east (@AC 1453).

This is the fourth state described in the chapter. By Bethel is signified the knowledge of celestial and spiritual things, and by Ai, the knowledge of worldly things (@AC 1453). We note that by having Bethel on the west is signified a state of obscurity in regard to goods and truths, and that by having Ai on the east is signified a state of clarity, or relative clarity, in regard to worldly things (@AC 1453). This is early childhood.

The little child is keenly aware of the world around him. To him it is a world of people, of objects, of endless activity, and vivid sensual impressions. As yet, however, he is only vaguely aware of what is involved in human relationships and the uses of all the things he surveys. The reason for this is that his world is as yet a sensual world, and he is not as yet capable of forming a rational idea of things. We can understand, therefore, why it is said that in regard to spiritual things he is as yet in obscurity. He knows from instruction that there is a God, that God is a Divine Man; but the child's idea of God is a natural idea, neither can it be anything else. He also knows that it is good to obey his parents and wrong to disobey; but as yet he does not know why. He does what is good to please his parents and also from fear of the punishment which follows when he does not obey. He is as yet incapable of doing good for the sake of good because he does not yet understand what good is. If, therefore, he is to come to know what good is, formal instruction is necessary. For it is only by way of truths that good can be made visible to the sight of the understanding. Hence it is said of this state that there was a famine in the land (Genesis 12:10). By a famine is signified scarcity of knowledges. That is why Abram was forced to leave the land of Canaan, and went down into Egypt to sojourn there, for to sojourn in Egypt, we are told, signifies instruction in knowledges from the Word (@AC 1459).

We all are familiar with the charge that is frequently leveled at the Academy and the General Church to the effect that the Writings have nothing to say about education apart from a few isolated passages concerning the instruction of children in heaven. Let me call your attention, therefore, to the closing statement in this chapter. It reads: These things, [that is, the things involved in this series of the Arcana] involve more arcana than man can ever believe. ... Besides the most profound arcana concerning the Lord, they also involve arcana concerning the instruction and regeneration of man ... not only concerning the instruction of the individual man, but also concerning that of the church in general. ... These things do not ... appear in the sense of the letter, for the reason that the historical narrative veils them over and obscures them; but they appear in the internal sense (@AC 1592[3]).

It is in the light of this statement that we consider the story of Abram's sojourn in Egypt. What is involved here is identified in the Writings as the fifth state in the progressive development of the human. It is the age in which formal instruction, or systematic learning properly begins. It would seem to include the seventh to the fourteenth year. If we are looking here for a blueprint of curricular offerings, or for a psychological interpretation of the states of childhood, we will be disappointed. These things must be derived from doctrine and perfected by experience. What we will find, however, is a clear statement of the purpose of instruction and the means by which it is to be achieved.

The purpose is that man may become a form of use, and the means is instruction from the Word.

What we seek, first of all, is a sound educational philosophy, i.e., one which conforms to the Divine purpose in creation. This is the subject of this portion of the twelfth chapter of Genesis.

Let me note here what I believe to be the key concept of the educational series of this section. Not only is this concept basic to the understanding of New Church education, but it is, to the best of my knowledge, the concept which sets New Church education apart from every educational theory hitherto devised. We read: All instruction is simply an opening of the ways (@AC 1495[2]).

It is the teaching of the Writings that man is a trinal creation, that he possesses a soul, a mind and a body, As distinguished from Christian theology, in which there is no clear distinction between the soul and the mind, the Writings teach that the soul (human internal) is from conception, and that it weaves for itself in the womb of the mother a physical body in which it may dwell. At birth, therefore, man has a soul and a body, but as yet no mind. It is the mind, therefore, which is formed and fashioned by the soul upon the anvil of nature; and it is to the mind that the Writings refer when they speak of man becoming man, and to the putting on of that which is human. This progressive development of the human mind is the humanizing or educational process. It is effected by means of knowledges which the child acquires by way of sensation, experience, instruction, abstraction and contemplation. This would not be possible, however, were it not for the fact that the soul, from birth, possesses all the wisdom to which the human mind can ever attain. Knowledge is not wisdom; it is but the form in which truths may be seen. Without knowledge, however, truths cannot be seen; hence the teaching that no one can perceive what he does not know (@AC 1802), in that the knowledge of a thing must always precede the perception of it (@AC 5649).

In other words, as knowledges are acquired, the soul inflows into the plane of the mind bringing with it perception, that is, understanding. For as the Writings insist, it is the soul which sees, but what is seen is seen on the plane of the mind.

What we are speaking of here is the doctrine of influx, the teaching that life, love, good and truth, affection and thought and even sensation inflow into man, and this by way of the soul. I could here cite many passages but we do not have the time. Let just one brief statement, which I believe I have already quoted, suffice. It is through the internal from the Lord [that] ... all perception [comes]. From no other source does perception come, nor even sensation. It appears as if sensation, as also perception, comes by influx from the external [world]; but this is a fallacy, for it is the internal which feels through [or by means of] the external (@AC 5779).

Returning, then, to our thesis that the soul of man is wise from birth, the purpose of instruction is that the way may be opened whereby what is with man from the Lord, namely, good and truth; may be seen and understood. That is why it is said in the chapter that the knowledges must be from the Word (@AC 1461). For, it is added, knowledges from the Word are such that they are open from the Lord Himself (ibid).

We must distinguish, therefore, between secular knowledges and knowledges from the Word. It is by means of secular knowledges that the natural rational is formed; that is to say, it is by means of worldly knowledges that the way is opened to the understanding of man's physical environment. This is the function of the sciences of our day. But unless worldly knowledges are disposed and ordered by knowledges from the Word, man cannot enter with understanding into the arcana of faith. By the arcana of faith I have reference to such subjects as the nature of God, the nature of man, the Divine purpose in creation, and the life of regeneration. Upon these knowledges, as a house upon its foundation, all spiritual understanding depends.

As New Church educators, therefore, our primary interest in the development of the curriculum is centered upon those knowledges from the Word whereby the mind of the child is progressively opened to the understanding of those moral, social and spiritual values which are essential to a life of use. For when applied to life, knowledges from the Word become values, and where values are lacking the curriculum is reduced to what the Writings refer to as empty memory-knowledges; (@AC
1542) that is, knowledges ... [in which] there is no truth; and also truths ... [in which] there is no good; (@AC 3079, 3068) or what is the same, knowledges in which there is nothing of genuine value. By this the Writings have reference to those knowledges which are learned without any perception of truth and good. In this connection I have been interested in reading several articles of late which speak of the value vacuum in modern education.

So it was that Abram went down into Egypt because there was a famine in the land; that is, a lack of knowledges from the Word. As noted, this state is descriptive of childhood at the time that formal education begins. The reason for this is clearly stated in the Writings where it is said that the memory knowledges (scientiae) of the Ancient Church flourished there more than anything else (@AC 1462).

We cannot begin to do justice to the educational implications of the content of this section of the chapter under consideration. In passing, however, we would refer your attention to the strange incident involving Abram's insistence that Sarai should present herself to the Egyptians as his sister rather than as his wife, According to the letter, he did this lest he be killed for her sake. To understand this story we must know that by Abram is here signified the celestial, that is, the good that was with the child from the Lord. This is the good of remains. By Sarai, Abram's wife, is signified the truth that is adjoined to this good, which is the child's perception of the truth of the Word. By the Egyptians are signified the child's love of learning. While this love is essential, there is nevertheless within it an inherent danger to the spiritual life of man, for this love, which is innate in man, is at first delightful to him, for no other end than for the sake of knowing (@AC 1480). But knowing is not an end, and when man learns merely for the sake of the delight which is to be found in learning he does violence to the celestial; that is, he destroys what is good in himself. Hence the further teaching: In childhood ... [knowledges] are acquired for no other end than ... [for the sake of knowing]. ... The memory knowledges acquired in childhood [however] ... are disposed by the Lord into order so as to serve for use; first, to give the ability to think [abstractly]; then that they may be of use by means of thought; and lastly that this may take effect, that is to say, that the very life may consist in use, and be a life of uses (@AC 1487). That is why time and again I have defined New Church education as education for use. I am convinced that this is the most comprehensive, the most meaningful, and the most practical definition possible. That also is why I believe that in the development of the curriculum, the criterion which must always be applied is that of use. Note well, that it is here - where the Writings are specifically treating of the first states of formal instruction - that it is the doctrine of which is emphasized. Observe here the teaching: Memory knowledges are ... the lowest and outermost things, in which are terminated in their order the things that are more interior ... [for this reason] they must be preeminently things of service. Every one may know for what such knowledges may be serviceable, if he reflects or inquires in himself for what use they are; and when he is thus reflecting upon their use, he can also apprehend the quality of the use. Every memory knowledge must be for the sake of some use, and this is its service (@AC 1486). Does this not apply to the curriculum?

Lest violence be done, therefore, that is, lest through the love of knowing, man comes to believe that the good which he does is attributable to his own intelligence, the Lord has provided that the truth of the Word, as represented by Sarai, is not at first seen for what it really is, that is, as the good of life taking form in the understanding. Hence it is presented as an intellectual truth rather than as a celestial truth, the difference being that what is presented to the understanding is delightful to the love of knowing, whereas that which is presented as good, apart from the understanding as to why it is good, is in time rejected. Concerning this the Writings state: Order itself is that the celestial by means of the spiritual, [that is, good by means of truth] introduces itself into the rational, and thus into the memory knowledge (in scientificum) and adapts this to itself; and unless this order is observed, there cannot possibly be any wisdom (@AC 1475). That is why the Word has been given. But it is only as the mind matures that man is capable of perceiving the true relationship which exists between truth and good; that is, that they are one, even as husband and wife. We can readily understand Pharaoh's indignation, therefore, when he upbraided Abram, saying, "What is this that thou hast done unto me? Why didst thou not tell me that she was thy wife?" (Genesis 12:18)


<<<

== Lecture III - Genesis 13

Lesson: Genesis 13.

Chapter thirteen of the Arcana Coelestia treats of Abram's return to the Land of Canaan and his separation from Lot. Note here that Lot was the son of Abram's brother Haran, who is said to signify idolatry from the love of pleasure (@AC 1357). Certainly the love of pleasure, which is a sensual love, is descriptive of the external aspects of childhood states.

As the twelfth chapter, which we have already considered, dealt with man's states of life from earliest childhood up to youth, it is obvious that this chapter directly concerns the first states of awakening adolescence. If in turning to this chapter, however, we expect to find a detailed analysis of the progressive states of adolescence we will again be disappointed. What is described here is man's separation from those sensuous things or pleasures which, it is said, captivate man in his childhood (@AC 1547).

This, from an educational point of view, is the theme of this chapter, and in reflecting upon it we are reminded that adolescence is an intermediate period in the life of man; that is, an age in which man temporarily stands between childhood and adult life. It is in many respects a difficult period because it involves a transition from the carefree life of childhood to the life of responsibility, or manhood.

This transition is not an easy one. We do not readily give up that which is delightful to us. The pleasures of childhood have a strong hold upon the affections; and while the adolescent aspires to the comparative freedom of adult life, he tends to resent the greater degree of self-discipline and self-control which the responsibilities that are proper its manhood require of him. The consequence of this is that the adolescent is prone to rebellion and states of resentment against authority. Certainly what we are witnessing among youth of today is ample evidence of this. It is these states of rebellion which are considered in the fourteenth chapter of the Arcana Coelestia where the battle of the four kings against five are treated of in the internal sense.

In this chapter (13th) we are concerned with Abram's separation from Lot; that is, with the rejection of those purely sensual delights which are characteristic of childhood in order that man may enter with understanding and new found delight into the responsibilities that are basic to a life of use. Concerning this the Writings state: There are two things with man which prevent ... [him from] becoming celestial,
[that is, which prevent him from entering into a life of use from love to the Lord and to the neighbor], one of which belongs to ... [the understanding and the other to the will]; that which belongs to the ...
[understanding] consists of the empty ... [scientifics] he learns in childhood and youth; and that which belongs to the will ... consists of pleasures from the cupidities which he favors. These are the hindrances that prevent him from being able to attain to celestial things (@AC 1542).

We have already spoken, in passing, of empty memory-knowledges or scientifics, and have taken as our definition, that which is said elsewhere in the Writings concerning empty vessels: to quote, that they are knowledges ... [in which] there is no truth, and also truths ... [in which] there is no good (@AC 3079, 3068).

Now how can you have a knowledge in which there is no truth, or a truth in which there is no good? What is meant, therefore, seems obvious. The reference is to a knowledge in which the truth is not seen, and a truth in which the good to which it testifies is not perceived. The reason that the truth is not seen, or the good or the use perceived, is because the man does not will, that is, he does not will to believe. Let us take, for example, the primary teaching of all Divine revelation: namely, that there is a God. This comes to man in the form of knowledge, but if he does not will to believe it, the truth is not seen. Let us assume, however, an intellectual acknowledgment on the part of man; but if the man does not will to be governed by the Lord, the good that is implicit in the truth is not perceived. Hence the knowledge, or the truth, is said to be empty, that is, devoid of any good purpose or significant application to life. It is true that elsewhere in the Writings, Swedenborg does speak of useful knowledges, and of those which are worthless in use. In speaking of the useful knowledges, Swedenborg proceeds to list all the known sciences of his day; but in speaking of the worthless sciences, he has reference to scholastic reasonings of his time which, he says, take away all reason, because they describe one plain matter, intelligible to almost any one, by means of ... scholastic terms, until no one understands it (@DMin 4578). This, however, is not what is a referred to by empty memory-knowledges in the Arcana series. Here we are concerned with knowledges of all kinds which are valued in themselves rather than on account of the use they are intended to serve, and thus become what the Writings refer to as hindrances in the life of regeneration.

When the mind of man is absorbed in worldly things and in the pursuit of knowledge for purely natural ends, the mind is, as it were, closed to the perception of spiritual things. This is characteristic not only of youth, but of many adults at this day. We are reminded here of the public school teacher who recently inquired concerning our curriculum and expressed the hope that we did not waste valuable time on the teaching of religion. What she failed to perceive is that religion is of life, and the life of use is, or should be, the primary concern of education. Lacking this, we are educating in a vacuum; that is, in what I have described as a value vacuum.

We come, then, to the second of the two things which is said to hinder man's regeneration. These things belong to the will, and are said to be the pleasures from the cupidities which ... [a man] favors. For the most part, in the Writings the term cupidities has reference to the bodily appetites and to purely external pleasures.

There is no need in this council to speak of the evil involved in the overindulgence of the appetites, or of the states of spiritual indifference which are the product of an excess of pleasures. The Writings speak firmly and directly of the use of the appetites and of the need for the recreation of both mind and body. But the hedonistic philosophy that pleasure is an end in itself is devastating persuasion. For the pursuit of pleasure for its own sake not only distracts the mind, but it also is subversive of use. In youth, and with those in whom adolescence is protracted into adult years, that is, before the man enters with a sense of evident delight into responsibilities, the love of pleasure becomes an obstruction which prevents or hinders the opening of the mind to the perception of use.

As teachers we all are painfully aware of the student who is capable of a good academic performance but is constantly diverted by the thought of those things which are pleasurable to him. While these things to which he gives his attention may be seemingly harmless, they nevertheless, and I quote, draw him away from goods, that is, from the goods which are of use. These distractions or sensuous things are represented by Lot, from whom Abram had to separate himself. Concerning this we read that by Lot is represented sensuous things, by which is meant the external man and its pleasures ... thus those things ...which are wont to captivate man in his childhood, and draw him away from goods. For as far as a man indulges the pleasures that originate from cupidities, he is drawn away from the celestial things that are of love and charity; because in those pleasures there is love from self and ... the world, with which celestial love [that is, the love of use] cannot agree (@AC 1547).

At the risk of some repetition I would here quote another passage which from an educational point of view is the key passage in this chapter. It reads: The external man receives its life principally from the internal man, that is, from the spirit or soul. Thence comes its very life in general; but this life cannot be received in its particulars, or distinctly ... unless its organic vessels are opened. ... These organic vessels ... are not opened except by means of the senses, especially those of hearing and sight. ... They are [therefore] opened with the senses as the media, by means of knowledges (scientifica et cognitiones), and also by means of pleasures and delights; those belonging to the understanding by means of knowledges, and those belonging to the will by means of pleasures and delights. From these things it may be seen that it must necessarily happen that such knowledges as cannot agree with spiritual truths will insinuate themselves into the external man; and that such pleasures and delights will insinuate themselves as cannot agree with celestial goods; as is the case with all those things which regard corporeal, worldly, and earthly things as ... ends. ... Wherefore, unless such things are first dispersed, the internal man cannot possibly agree with the external; so that before the internal man can agree with the external, such things must first be removed. That with the Lord these things were removed or separated, is represented and signified by the separation of Lot from Abram (@AC 1563). (Comment on Lots choice of the Jordan Valley)

Now what do the Writings mean when they say that cupidities and knowledges which do not agree with celestial things, that is, with remains of innocence, will necessarily insinuate themselves? Two things are involved here: first, man is born natural, and by heredity inclines to those delights which are implicit in the loves of self and the world; second, he instinctively seeks to justify the delights which he favors by means of reasonings from the appearance of self-life. Reasonings from the appearance of self-life are subtle and devious. This is the serpent in the garden of Eden. It manifests itself in the child's first lie, and unless it is seen for what it is, it will in time destroy every vestige of innocence. Of all the evils to which man is prone there are none as devastating as deceit. In childhood, reasonings from the appearance of self-life take form as persuasions which are conducive to the life of self; but as the mind matures it seeks out those reasoned arguments in which knowledges of many kinds are organized in such a way as to incur doubts concerning the reality of God, the credibility of the Word, and all matters of faith. We know these arguments. They are quite familiar to us. There is materialism, hedonism, existentialism, pragmatism, and a host of other highly developed persuasions which have their impact upon youth. We have only to look at the world around us to see their effect. The knowledges upon which these philosophies rest, however, are empty memory-knowledges and abstractions because they are devoid of any spiritual purpose and of any concept of what the Writings mean by use.

In the development of the curriculum, therefore, we must take cognizance of the philosophies of the day. The modern mind is no longer concerned with the doctrine of faith alone, or three persons in God, but with pragmatic solutions to problems and with existential interpretations of life. A living curriculum is a relevant curriculum, and it is my thesis that the Writings, although written in an age of theological controversy, are relevant, because when rightly understood they are directly addressed to those intellectual and emotional persuasions with which men are concerned at this day.

I regret that due to my commitment to the series in hand I cannot take the time to discuss with you the modernization of the curriculum; that is, of reorganizing the curriculum in such a way that current problems with which the student is confronted can be more effectively met. It is, however, largely a matter of illustration; that is, of using illustrations in the presentation of doctrine that the student will immediately recognize as relevant. This, more than anything else, will give vitality to efforts. Perhaps it could be the subject of another series at some future date.



<<<

== Lecture IV - Genesis 14

Lesson: Genesis 14.


We come now to the fourteenth chapter of the Arcana Coelestia. The subject treated of here is the Lord's temptations in His childhood. Concerning this the Writings say that no one can fight against evil and falsities ... until he has the full use of his understanding and judgment, which is the reason why man does not come into temptations until he has arrived at adult age (@AC 1661). In this, however, the Lord advanced more quickly than other men for the Divine was in Him, and as He was instructed in scientifics and knowledges He perceived from the Divine love the quality of that human affection of truth which He derived from the maternal human. Herein He perceived the quality of that delight which men find when they attribute what is good and true to self-intelligence and the nature of its attendant evils. In this He was tempted; that is to say, He was tempted to withdraw from the perception and from all thought concerning it, for it struck Him with horror (@AC 2222).

To understand this, and also what is involved in the chapter, we must first understand what the Writings mean by temptations. According to medieval Christian theology, temptations are tests or trials by which God determines man's faith in Him. This, however, is only the appearance, for God does not tempt man. It is evil which tempts man, and that which is evil cannot be predicated of God. Hence the Writings define temptations as an assault upon the love in which a man is (@AC 1690). When the love in which a man is, is assaulted, the man suffers, for love is the life of man, and when man is deprived of life, that is, when he experiences a deprivation of life or love he suffers a loss of delight, and he is afflicted. Let us think of temptations, therefore, as those afflictions of mind and spirit in which doubts are incurred concerning the end in view. Hence the Writings also define temptations as doubts. Indeed, the Writings state that if the end which is loved were not put in doubt, there would be no temptation (@AC 1620, 2334, 2338). When, therefore, man comes into states of despondency, and particularly into states of despair, he is in temptation.

We must distinguish carefully, however, between two kinds of temptations; that is, between natural and spiritual temptations. Natural temptations arise when the love of self is attacked, and all men, including children, are subject to natural temptations. But spiritual temptations can be predicated only of the regenerating man; that is, of him who to a lesser or greeter degree is in the love of use, the severity of the temptation being determined by the degree of the love (@AC 1620).

When the Writings say, therefore, that children cannot be tempted, they are speaking of spiritual temptations in which the love which is attacked is the love of use. But the child can be tempted by the thought of the loss of that which appears to him to be good; that is, by the thought of the loss of honor or reputation. Let us take, for example, the child who has lied. He has lied because he feared the punishment, but now he fears that his lie may become known. This produces mental anxieties and also induces a sense of the loss of self-respect. The child, therefore, may be said to be tempted. He is torn between his desire to protect self from condemnation by others and his love for that which he believes to be good, i.e., his respect for himself. Hence the Writings define natural temptations as anxieties arising from an assault an one's natural loves (@AC 847); and as respect for one's self has its origin in concern for self, it is a natural love; howbeit, with children and with those who have not confirmed themselves in a life of evil it is a means whereby man may be led by the Lord into a genuine concern for self, which is a concern for self as a form or instrumentality of use, Hence it is referred to elsewhere in the Writings as a mediate good (@AC 4145), but here it is referred to as an apparent good (@AC 1661).

To understand the contents of this chapter we must first understand what the Writings mean by apparent goods and truths. Concerning this the Writings say: Every man combats first of all from the goods and truths he has received through knowledges; and from them and by them he judges about evils and falsities, Every man also, when he first begins to combat, supposes that the goods and truths from which he combats are his own; that is, he attributes them to himself, and at the same time attributes to himself the power by which he resists. This also is permitted ... [because] the man cannot then know otherwise. Until a man has been regenerated, he cannot possibly know, as to be able to say that he knows, acknowledges, and believes, that nothing of good and truth is from himself, but that all good and truth are from the Lord. ... When a man is in such a state that he supposes good and truth to be from himself, and that the power of resisting is his own, then the goods and truths from which he combats against evils and falsities are not goods and truths, although they appear [to be] so; for there is what is his own in them, and he places self merit in victory, and glories as if it were he who had overcome the evil and falsity, when yet it is the Lord alone who combats and overcomes. That this is really the case, none can know but they who are being regenerated by means of temptations (@AC 1661).

From this it is evident that with children and youths, all goods and truths are apparent goods and truths. Such goods and truths, however, are proper to their state of life in that man cannot enter into the perception of genuine goods and truths until he has been instructed and enters, to quote, into "the full use of his understanding and judgment" (ibid). Prior to adult life, therefore, man resists evils and falsities from a moral and social conscience which, although the basis of, is not as yet, what the Writings refer to as a spiritual conscience. For he who acts from a spiritual conscience acts from the love of use, (See Values and Objectives of New Church Education, Willard D. Pendleton, pp. 28-35).

The evils of childhood are essentially states of disorder; that is, states in which the child seeks to do what is pleasing to self without regard for its effect upon others. For the most part these are sensual delights, and because they are sensual they are said to be the most general or the most universal kinds of evils and falsities (@AC 1663). Up to the time of youth, these evils are held in bonds by parents and teachers; also by the child's desire to please those whom he loves and upon whom he is dependent. There comes a time, however, when the child begins to resent the bonds that are restrictive of self, as is evident in the more critical attitude which he takes toward the judgment of parents and teachers, and in the sullen response which he tends to adopt when what is required is not pleasing to him. As every educator knows, there is nothing more defeating than this. When the child does what is required of him, but in such a way as to express his resentment, the best thing to do is [?to more?] him and await a change of state. The reason for this is that youth craves attention, and when it is withheld it usually serves as a corrective. Be this as it may, what we are concerned with here is the battle of the four kings against five, in the valley of Siddim. What is represented here is the inevitable struggle between Chedorlaomer and the kings that were with him; that is, between the apparent truths and goods of childhood and the hereditary evils and falsities that are signified by the five kings.

It is recorded that for twelve years these five kings served Chedorlaomer, and in the thirteenth year they rebelled (Genesis 14:6), Herein the Writings are describing the rebellion of youth which involves not only the desire to be free from parental authority, but also the freedom to determine for one's self what is good and evil. Certainly there are many manifestations of this at this day. Perhaps at no time in history has there ever been such a demand for freedom from restraint among youth as there is at the present time. This is a cause for deep concern, and while so far, within the church, we have been better able to cope with it than others, we are not free from its effects.

In this, however, we are far from defenseless. Our appeal to our children, particularly with our adolescents, is to a higher authority; that is, to the authority of the Writings. In so far as we have succeeded in inculcating in our children an affection for truth, we are in a strong position. While it is true that as yet this affection is a natural affection, it serves as the means whereby the adolescent may increasingly impose upon himself a respect for order, and thus restrain the evils to which he inclines. While it is true that the truths from which the adolescent disciplines himself are only apparent truths, in that he attributes to himself what he accomplishes with himself, it is spiritually sufficient to his state at this time. Yet it is to be noted that the four kings, having subdued the five kings, took Lot, by whom is represented the external or sensual man, and carried him away captive.

What is recorded here is of particular interest for it has reference to the state of the adolescent who, having come into order, attributes merit to self. While this is according to order, it nevertheless opens the way to a far more devastating evil, namely, the pride of self-intelligence, to which so many are prone at this day. When man attributes to himself the truth he perceives and the good which he does, he in time closes his mind to the Word. This is the spiritual issue in adult life, but it is in youth that it takes root.

(Historical note re: Lot's choice. See Warner Keller.)

Returning now to the spiritual sense, it is evident that what the Writings are treating of here is the delight by which the mind of man is captivated when he comes under the influence of reasonings from the appearance of self-life. While this delight has its origins in childhood, it is particularly persuasive in youth. As the child's ability to reason becomes more adept, and as the desire to be free from authority becomes more acute, the mind is increasingly captivated by the appearance that the good which he does is attributable to self. So it is that the external man, as represented by Lot, is, as it were, taken captive by Chedorlaomer and the kings which were with him, who represent so many apparent goods and truths. Were it not for Abram the Hebrew, that is, for 'the potential spiritual rational', there would be no way in which man could be delivered from the illusions of self-life which are inherent in apparent truths and goods.

I say, 'the potential spiritual rational', because it is not until Isaac is born that this rational may be said to exist; yet it is potentially present with man from birth. Were this not so, man would be as the animal; and its presence with man is here represented by Abram the Hebrew.

This is the only place in the Word where Abram is referred to as Abram the Hebrew. The reason for this is that by Hebrew is signified one who serves, and in this instance the reference is to the interior man; that is, to the rational which serves as a medium of communication between the internal and the external man, or between the soul and the natural mind (@AC 1702).

It is not until the promise of Ishmael is given, that the formative states of the rational are directly considered in this series. What is said concerning Ishmael, by whom is signified the natural rational, is descriptive of the later states of adolescence and of early manhood. But the power to think and to reason, the ability to abstract ideas out of sensations, manifests itself early in life. Were this not so, the child would not be educable. What is described here under Abram the Hebrew, therefore, is the awakening rational which, although not as yet dominant, nevertheless serves as the means whereby the way is opened to the perception of truth from the soul.

What we are concerned with here, therefore, is the function of the awakening rational in the early states of adolescence. Certainly to the child of this age, the appearance is that the truth which he perceives is attributable to his own understanding, and that the good which he does is meritorious. This is particularly observable in the delight which he finds in excelling others, and in the lift to his ego when comparisons with others are made that are favorable to self. Yet at this age the child is still under the influence of early remains, and in his opinion of self there is still something of innocence. Thus although self-willed and deeply immersed in what is pleasing to self, the thought, and particularly the affections of youth, can be temporarily redirected to the Lord, and thus be, as it were, rescued from complete absorption in self. That is what is represented by Lot's deliverance from the four kings who had carried him away captive.

We note with particular interest that this rescue was effected by means of the trained men that were born in ... [Abram's] house, some three hundred and eighteen men in all (Genesis 14:14). These men are said to signify those goods [and also truths] in the external man which can be conjoined with the interior man (@AC 1708). What these goods and truths are is evident. They are the goods and truths of a moral and social conscience. From their early childhood, we seek to instruct our children in knowledges from the Word in order that they may be able to distinguish between right and wrong, good and evil, in their relations with others. Thus we hopefully seek to establish in their minds a moral and a social conscience. These are those things which the Writings say belong to the external man, but which can be conjoined with the interior man, that is, with the rational. From reason, the adolescent, when under the influence of an adult, can see that moral decorum and a sense of responsibility to others is not only a matter of order, but also is desirable. While it is true that he vacillates, and when in states of self-insistence tends to reject what reason dictates, nevertheless under normal circumstances he can be appealed to. In this connection I must confess, however, that the conditions and circumstances in which many adolescents find themselves today are not normal. This is regrettable, and presents many problems.

What, then, shall we say about the temptations of childhood? In the first place we would observe that they are both real, and at times, acute. What is more, it is quite apparent from the definitions of temptation that are given in the Writings, that much more is involved than is generally supposed. For when the Writings define temptations as: + 
1) an attack upon the love in which one is, + 
2) as a doubt concerning the end in view, + 
we can perceive that what we are concerned with here are all those states of stress to which the child is subject in the process of becoming a man. These stresses are many, and in some instances, severe. What is more, they very greatly depending upon the disposition and the personal circumstances of the individual. Take for example, the child whose home life is torn by dissension, or the child who finds extreme difficulty in adjusting to the social life of the group. In each instance the child suffers, and his suffering is sensed as an attack upon the love in which the child is. Also, take for example, the child who encounters real difficulty in the learning process. In what is required of him in the classroom, he is constantly faced with a sense of defeat. We can readily understand why he wills to withdraw from what is painful to him. The fact is that he is suffering from doubts concerning his ability to achieve the end in view; and because of his doubts concerning himself, we find great difficulty in motivating the child. Every teacher has experienced this.

Much could be said concerning the stresses of childhood and of youth; that is, concerning the temptations involved. There is room here for the development of an educational psychology based upon the Writings -- a field which as yet has been scarcely touched.

Yet the question arises, as it inevitably does in this council, how do we carry over into the classroom situation, what has been said in this series of lectures? In regard to the temptations of childhood, let me say that what needs to be carried over into the classroom are understanding and patience. We are not merely instructors. We are, hopefully speaking, educators, that is, human instrumentalities who by virtue of the use which is entrusted to us may serve as a means whereby the way may be opened in which the child may be led to the understanding and perception of what is of genuine value in life. This requires not only a high degree of dedication to the ideals of New Church education, but also a sensitive awareness on the part of all of us of the states of the children for whom we as educators are responsible. While this may be a generalization, it is an important one, and one that is all too easily overlooked in the educational process.

Need for a stable environment, all too lacking today. School cannot substitute for the home, but it can support it.

As teachers we share a high degree of responsibility in providing a stable environment for our children. I have reference here, not only to our emotional reactions in our supervision of children, but to stability of purpose. This the Writings provide for us, in that they establish a standard of authority which looks to what is good and useful in life.



<<<

== Lecture V - Genesis 16

Lesson: Genesis 16.

We come now to the sixteenth chapter of Genesis. Our subject is the first rational. This, we are told, is conceived by the influx of the internal man into the affection of memory knowledges (scientiae) of the external [man] (@AC 1890); that is, of the influx of the soul into the delight which the child finds in learning.

The internal man = Abram.

The affection of memory knowledges = Hagar, the Egyptian handmaid.

The rational thence derived = Ishmael (See @AC 1890).

Now the key teaching here is that this first rational, or Ishmael, was of such a nature that it held intellectual truth, that is, Sarai, in low esteem. The actual statement in the Writings is: But as this affection, that is, the affection of the Ishmael rational, was of the external man, its nature was such that it held intellectual truth [as represented by Sarai] in low esteem (@AC 1891). We proceed from here.

In order to understand this, bear in mind that by Abram is signified the good or love of the soul, and by Sarai, his wife, is signified the truth or wisdom of the soul. This truth is referred to in the Writings as intellectual truth.

Immediately we are presented with a problem in semantics. When the term intellectual is used today we immediately associate it with what is rational. But the term intellectual truth as it is used in the Writings is carefully distinguished from rational truth. Intellectual truths are prior to, and superior to rational truths; even as the soul is prior to, and superior to the rational mind. By intellectual truths are meant those truths which are inherent in the soul from birth and are seen from love and affection, that is, from perception; whereas by rational truths are meant those truths which are acquired by means of knowledges and are seen from reason. By way of illustration note the familiar teaching that now it is permitted to enter intellectually into the mysteries of faith (@TCR 508). To enter intellectually is to enter with understanding, but a true understanding involves more than a rational grasp of doctrine. It also involves love and affection, that is, the perception from love that it is so. In this connection note the teaching found in @AC 1496. It reads: [Scientific] truth ... is one thing; rational truth is another, and intellectual truth is another; they succeed one another... [Scientific] truth is ... of ... knowledge; rational truth is... [scientific] truth confirmed by reason; intellectual truth is conjoined with an internal perception that it is so (@AC 1496). In order to understand what is involved in the spiritual sense of this chapter, therefore, we must note what is said in the letter. According to the letter of the Word, Sarai, Abram's wife, was barren; but we are told she had a handmaid, an Egyptian woman, whose name was Hagar. Now it came to pass that Sarai, in reflecting upon her barren condition, said unto Abram, Behold, I pray, Jehovah hath shut me up from bearing; go in, I pray, unto my handmaid; it may be that I
shall be built up by her (@AC 1899-1901; Genesis 16:2).

We are told that what is involved here is that intellectual truth which appertains to the inmost, [that is, the soul] is altogether barren, or like a childless mother, when as yet there is not any rational into which and through which it may inflow; for without the rational as a medium, intellectual truth cannot inflow with any truth into the exterior man, as may be seen from the case of little children, who can know nothing ... of [any] truth until they have been imbued with knowledges ... the more perfectly they are imbued with knowledges ... the ... more perfectly can intellectual truth, which appertains ... to good, be communicated (@AC 1901). This is what education is all about.

Simply stated, the teaching here is that truth, as is generally supposed, does not come from without, but from within. What comes from without are knowledges in which, as in mirrors, the truth may be seen. But if the truth is to be seen, the knowledges that are acquired must be ordered by the Word; that is, by knowledges from the Word. The reason for this is that knowledges from the Word open the way to the perception of good and truth; that is, to the perception of Him who in essence is good and truth (See @AC 1461).

What comes from without, therefore, is knowledge; but what comes from within is perception. In this connection note the teaching of the Writings concerning Sarai; that is, concerning what the Writings refer to as intellectual truth. We read: This intellectual truth, as represented by Sarai, is the spiritual itself which flows in ... by an internal way ... and it continually meets the knowledges that are insinuated by means of the things of sense, and are implanted in the memory. Man is not aware of this intellectual truth because it is too pure to be perceived by a general idea. It is like a kind of light that illuminates the mind, and confers the faculty of knowing, thinking, and understanding. [Thus] as the rational cannot come into existence except by means of the influx of the intellectual truth represented by Sarai, it stands related to this truth se a son (@AC 1901). What, then, do the Writings mean by intellectual truth? Do not the Writings here have reference, as stated, to the spiritual itself in man? Is it not this that gives to man the ability to perceive, to think and to understand? Is not this, therefore, that which is essentially human in man? Is it not to this innate wisdom of the soul that certain philosophers have reference when they speak of intuitive knowledge? It is an unfortunate term, in that knowledge cannot be predicated of the soul, but it is a recognition of a wisdom that is inherent in man. It was no less a philosopher than Immanuel Kant who argued that there is that in man which gives meaning and significance to the raw material of sensation, or to that which Plato had referred to as the rabble of the senses.

According to the Writings, however, the first or natural rational is not born of Sarai; that is, of the perception of good and of truth, but of Hagar the Egyptian who, as Sarai's handmaid, was subordinate to her. In other words, the first or natural rational, as distinguished from the spiritual or regenerate rational, as later represented by Isaac, is born of the affection of knowledges. It is this delight in learning which makes education possible in that it serves as the means whereby the first rational takes form. But this delight, as all the delights into which man is born, is centered in self, and therefore, spiritually speaking, is as yet natural, Hence it is said that this affection holds intellectual truth, as represented by Sarai, in low esteem (@AC 1891).

Whereas in the last chapter the Writings treated of those natural temptations which are descriptive of childhood, here they treat of the beginning of spiritual temptations. This takes place when man begins to perceive what is actually involved in a life of use as distinguished from a life of commitment to self. According to order, this should have its beginnings in late adolescence; that is, as the man passes from the relatively carefree life of youth into the responsibilities of adult life. But whether it comes early or late is not the point here. The point here is that if man is to become a regenerate man he must come to perceive the limitations of human reason, and place his confidence in that vision of use which is the testimony of the spiritual sense of the Word.

Let us have no illusions, therefore, as to why we have established New Church schools. It is in order that our children may be instructed in the Word and thus enter according to order into a life of use. We admit to no other purpose. What is primary here, therefore, is our own sense of dedication. This however cannot be communicated by means of closely reasoned arguments and by endless references to use. The classroom situation must be a vital situation, that is, one in which the student participates. In whatever we teach, therefore, let us seek out what is significant, that is, what has relation to life. By this I do not mean life as projected into some obscure future, but life as the child understands it. What is then presented becomes relevant, and it is in what is relevant that uses are seen and understood. What I am appealing for here is a vital and significant education. And what is more vital and significant than use itself? In so far as we can enable the child to see the relation of self to use, that is, in so far as we can enable the child to understand that self is intended to be an instrumentality of use, to that degree do we challenge the child, both intellectually and spiritually speaking. This is done by means of knowledges; that is, by means of knowledges of many kinds which, when ordered by knowledges from the Word, open the way to the perception of truth and of good.

But the question that arises here is, What are these intellectual truths which are the subject of this chapter? How are they to be described or defined? So far we have been speaking of intellectual truths as the light of the soul which illumines the mind, and which confers upon man the faculty of thinking, of knowing, and of understanding (@AC 1901). This applies to all men. But a faculty is one thing, and the proper exercise of that faculty is another. With man rests the choice; it is by means, and only by means of the proper exercise of this faculty, that man may be led to perceive intellectual truths; that is, that he may be led to perceive those truths to which this faculty looks. Hence we read in the Writings that it is an intellectual truth that all life is from the Lord; but the rational [when] first conceived does not apprehend this, and supposes that if it did not live from itself it would have no life. ... It is [also] an intellectual truth that all good and truth are from the Lord; but the rational [when] first conceived does not apprehend this because it has the feeling that they are ... from itself; and it also supposes that if good and truth were not from itself, it could have no thought of good and truth, and still less do anything good. ... It is [also] an intellectual truth that nothing but good is from the Lord, and not even the least of evil; and this too the rational [when] first conceived does not believe, but supposes that because the Lord governs everything, evil also is from Him. ... [Further], it is an intellectual truth that the celestial man [that is, the man who is in the love of use] has from the Lord a perception of good and truth; but the first rational either denies the existence of perception altogether, or supposes that if a man were to perceive from another, and not from himself, he would be as if inanimate, or devoid of life. In fact, the more the rational thinks from ... knowledges that originate from sensuous things and from philosophical reasonings, the less does it apprehend the foregoing, and all other intellectual truths. ... Hence it is that the learned believe less than others (@AC 1911).

From these illustrations that are given here it is apparent what intellectual truths are. They are the primary truths of faith; that is, those truths upon which all of Divine revelation rests. Does it not follow, therefore, that it is also an intellectual truth that there is a God, and that he is one (@TCR 9); that the purpose in creation is a heaven from the human race; and that the good of a thing is not in itself, but in the use which it serves? In other words, intellectual truths are truths which are inscribed upon the soul and are perceived by man as an internal dictate; that is, as a dictate that it is true because it is good (@TCR 9). Concerning this, we read in the Writings: [While it is true that] the truths ... [which] constitute belief flow in ... through ... hearing, [that is, by way of instruction,] and are thus implanted in the mind ... [which] is below the soul; but by means of such truths [that is, the knowledges of truth] man is simply made ready to receive influx from God through the soul; and such as this preparation is, such is the reception (@TCR 8).

The ultimate purpose of New Church education, therefore, is to enable man to enter with understanding into the perception of good; that is, into the perception and interior acknowledgment of Him who alone is good. But when applied to life, good takes form as use, and is in use. It is this which makes New Church education both meaningful and relevant. For he who thinks from use perceives what is true, and he who acts for the sake of use does what is good. What could be more relevant and meaningful than this?

Let us not be discouraged, therefore, if at times we do not perceive the application of doctrine to the educational situations in which we find ourselves. As previously stated, the Writings are not a blueprint. We will not find here a detailed description of the educational practices to be followed in the solution of our immediate problems. But what we will find is a clear and definitive statement of what education is all about, and an insight into those progressive states of human development which cannot be acquired from any other source. We hope that in this respect this series of lectures have been of some use.


