= Reflections on Some Popular Fallacies
A Series of Doctrinal Lectures, by the Rev. Hugo Lj. Odhner
include::../template-attributes.adoc[]

{empty}

== I. INTRODUCTION

In the Words for the New Church, the first publication issued by the Academy of the New Church, there is contained a comprehensive treatment of the state or the Christian world, as this is exposed in the Writings. The forceful presentation assisted in awakening many people to the realization that the New Church was not merely reform-sect within a reviving Christianity, but had as distinctive and militant a mission as did the Christian church in the time of the apostles. It was because of the realization that the Christian world was being vastated at an ever accelerating pace, that the Academy placed its main hope in a distinctive education by which a future generation might arise, that would be in great measure protected from the falsities of the Old Church and be able to see and appreciate the interior and distinctive truths of the Second Advent revelation.

The particular fallacy which this article, published in 1870, aimed to disperse, was the idea current in the General Convention that the Christian church was being reformed from within, and that its old organizations would revive and draw new breath, by an unconscious influx out of the new heaven established after the Last Judgment and that as Christian leaders came to see the falsities of the old creeds, they would or themselves, and without knowing of or accepting the doctrines of Swedenborg, arrive at the acknowledgments of the Lord as the sole Deity and of a life after death, such as the Writings describe, and a concept of the true nature of regeneration and a social realization of the idea of the Grand Man; thus becoming, unconsciously New Church.

This optimistic fallacy has barely survived on its very slim diet. For while the trend of educated thinking men, the Christian world has been one of discarding the more crude falsities of the old orthodoxy - such as a belief in three personalities in the God-head, in the vicarious atonement by the blood of Christ, in the resurrection of the body, and in the existence or a personal Devil is also clear that those whose minds are critical to these old dogmas are usually also negative to the inspiration of Scripture, the Deity of Jesus Christ, and the certainty of a hereafter, and doubtful of any possibility of ever finding practical assurance about religious truths.

In speaking or the tendencies in religions thinking, and the growth of non-belief, we must or course be aware that organized religion is not on the decrease in any statistical sense, in these United States. It is calculated that in the year 1800 less than 7% of the population, (then 5,308,483); were church-members. In 1878, 19% were members or a Church; and in 1930, by steady growth,--due to the persistent momentum of history - over 40%, or more than fifty million persons, 13 years of age or over, were attached to a church-body.

Nor would we find a lack of religious zealots among these; more than fifty millions. We would find many among the (20) millions of Catholics, (10) million Baptists, (8) million Methodists, to say a good word for the old faith. Over two and a half million Presbyterians would include many stubborn champions even for infant damnation. And innumerable smaller sects have arise in the fervent faith that more enthusiasm and unworldliness is needed for salvation; or else, like the Mormons, with devotion to a theocratic society, ruled by prophets.

The fact remains, however, that with the bulk of our countrymen,--and this holds true of the six hundred million Christians the world over - religion has taken a less and less important; place in the lives or man. The State has taken over a large amount of the work the churches used to do. Science has taken over most of the thinking. The mechanical means of doing things has captured the imagination. It is difficult to work up any excitement about doctrinal differences, for the matter of ones beliefs usually seems to be of no practical importance, when men so generally live with an eye, for this world only.

We therefore meet relatively few people who seem disturbed by the falsities which their churches officially sanction: for the preaching they hear is usually either emotional or else confined to the moral and civil plane. The churches, with notable exceptions, discourage doctrinal thinking, set a cause only of embarrassment to the clergy.

Does this mean that the old falsities have perished? that the influx of the new heaven is received more widely? that the old church is not so dangerous an influence as in the dogmatic days of generations ago? that we and our young people, moving about in the world, are not surrounded any longer by the deadly infesting spheres of fallacy which once sought to extinguish the spheres of spiritual truth?

Perhaps the answer to these questions is found when we read in the Writings concerning the origins of falsities. There are three origins for falsities. One is the doctrine of the church: false dogmas which have fastened themselves upon the traditional and accepted creeds of a church. The second origin of falsity lies in the appearances and fallacies of the senses. The Arcana lists many examples of such fallacy or merely natural sense: not only the long-accepted idea that the sun and stars revolve once a day about our earth; but ideas such as that there is only a single atmosphere; that trees and flowers grow and reproduce of their own power; that all things are ultimately composed of simple substances, or indivisible atoms; that all things are natural and that there is nothing beyond; that only the body lives, and life perishes with it; that man is an animal and cannot live after death any more than they can; that the soul - conceived of as something etherial - resides in the brain and thence regulates the body as if it were a machine; that there can be no light and heat, except that of nature. Similarly, it is from the fallacies of the senses, and thought thence, that man appears to live of himself, or from a life planted in him. From fallacies of sense, man can argue that adulteries perform the same purpose for the race as marriages. It is from fallacies of sense that men believe heaven to be a place, and its joy to consist in being greater than others; and that good works merit heavenly reward; or that man is saved by faith, apart from charity, thus that it is the faith, not the life, that survives after death! (@AC 5084).

Modern science has loosened the hold or some of these fallacies. But it has strengthened the strangle-hold of others upon mens spirits. And in this time or the end, foretold through Daniel, when many shall run to and fro, and knowledge shall be increased, the faith of the popular mind has been transferred from the grosser sense-deceptions of nature and from the literal appearances of the Bible, to the more subtle illusion, fostered by empirical science, that nothing is worthy of belief until it is sensually demonstrated. Not that science itself makes any official claim denying spiritual things - which belong to a field with which it has as yet claimed no acquaintance--; but by inference it has simply made people feel that nothing is true unless Science has set its seal thereto.

But there are three sources of falsities. The third is a life of lusts, cupidities of evil. This is indeed the inmost origin, and what flows thence comes from the will, the heart, the man himself. And those fatal falsities cannot be rooted out except by new life from the Lord (@AC 4729), or through regeneration. The confirmations of evil in the thoughts produce such falsities, which to the man appear as true; and real truths than seem to be false, for the light of heaven has been excluded from the mind.

Let us not imagine that ignorance, or traditional errors of doctrine, or fallacies of sense, were the causes of the consummation of the Christian Church! For the cause of such degeneracy was not a series of innocent mistakes, but the increasing prevalence of evil. It was so with all the Churches of the past:

In the beginning charity is fundamental with them: every one then loves another as a brother, and is affected by Good, not for his own sake but for the sake or the neighbor, the community, the kingdom of the Lord, and above all things for the Lords sake. But in process of time charity begins to wax cold and to become naught. Afterwards there arises hatred or one another; which, although it does not appear outwardly, because in civic society men are under laws and under external bonds of restraints, still is nourished inwardly. These outward bonds of restraint come from the love of self and the world; they are the love of honor and eminence, the love or gain and hence also of power, thus the love of reputation. Under these loves hatred against the neighbor conceals itself: which is such that men desire to have command over all, and to possess all things that are another's; and when these desires are opposed, they treasure in their hearts contempt for the neighbor, breathe revenge, take delight in his ruin, and even practice cruelties so far as they dare. Into things like these does the charity of the church at its end at fast decline, and it is said of it that there is no longer any faith, for where there is no charity there is no faith ... (@AC 2910).

Thus we learn that the Christian Church was indeed at its inception internal, for interior truths had been revealed by the Lord; but that church now is at its end, because now there is not only no charity, but there is hatred instead of charity; which hatred, though it does not appear outwardly, yet is within, and it breaks out ... whenever external bonds do not restrain (@AC 2910).

It does not appear to those in the church, that the church is such-nor that they cherish contempt and have aversion for spiritual things. For the bad as well as the good attend churches and are moved by something of holiness while there, and can talk about it. They also live among themselves in civil charity or friendship; ... but these things are only external forms by which one seduces another.... (@AC 3489).

The consummation, desolation, and end or the church was however openly revealed in the spiritual world, at the time of the Last Judgment. We can only refer here to the terrible descriptions - in Swedenborg's Spiritual Diary - of the state after death of those who came into the world of spirits from the Christian world: their state was worst; or all - one of hating the neighbor, hating the things or religion, and of being given to adulteries (@AC 1886, pref.).

Only in the spiritual world, where, hearts speak, and not mouths, can the interiors of men be seen. The quality of the Lords church on earth, cannot be seen by any man, so long as he lives in the world; still less, how the church in process of time has turned aside from good to evil (@LJ 41). We cannot judge merely by external signs, or by our trust in, or distrust or others. Nor can we judge the general and proper state of the church by the fact that remains or remains are always preserved, or some with whom the good and truth of faith remains, although they are few (@AC 530). Revelation from the Lord can alone open our eyes to the state of interior consummation which has engulfed Christendom. Though invisible in this world, this inundation appears in the other life like a black cloud encompassing Christians and separating them from heaven. The cloud consists of direful falsities from evil (@AC 4432).

Two things may be observed, in these teachings. The first is, that the cause of the destruction or religion lies in evils of life, or evil loves (See @TCR 751). The second is, that these evils engender falsities which are means of vastations, and which destroy the spiritual usefulness, and the specific functions, of the church.

If evils are the ultimate cause of the state of consummation, it might be thought that a removal or these evils should amend the state, and restore the church. But this hope is slight. The teaching is that when once the good and truth or the church are extinguished, ... falsities and evils are superadded; for falsities and evils grow continually in a church ones perverted and extinct (@AC 4503).

How this occurs is also suggested: Churches decrease and destroy themselves for numerous reasons: one is, that parents accumulate evils
... and so transcribe them by heredity unto their offspring ... which, unless they are reformed or regenerated, is continued into successive generations, and then always increases (@AC 2910). This is given in explanation of the fact that a new Church is rarely, if ever, raised up from the men of the former church, but from Gentiles - of some other race-who were in ignorance (Ibid).

The reason why hereditary evil. does not decrease, presumably is that regeneration cannot be effected without genuine truths. Something of reformation can indeed take place, with any individual, despite hereditary evils; for every man born has freedom and rationality and can repent or those evils that he can recognize in the light of what he takes to be true, and he can thus be saved. But in order that the quality of hereditary evils may be unearthed so as to be explored and resisted, and so the racial strain be ameliorated, the falsities which conceal and explain away those evils must be exposed and extirpated; and thus can be done only by new light of truth from the Lord, and from the Word - the same genuine or spiritual truth which produced the Last Judgment in the spiritual world! When the false appears as true, then the good which in itself is good, and is called spiritual good, no longer exists. The good which is then believed to be good is the merely natural good which a moral life produces (@TCR 754).

But here we face the question whether the Christian world of today - nearly two centuries after the Last Judgment - has not in fact done - or at least begun - the necessary work of exposing and rejecting the falsities that concealed the evils of our forebears. (The doctrines of Swedenborg, even if not accepted by the world, have had no little part in hastening this rejection of the old dogmas - in showing up their falsity in the pitiless light of reason.
 Yet we find - on further reflection - that the rejection of the creedal dogmas of the old churches was not a rejection or their falsity: it was rather a more complete acceptance of their underlying falsity which had been hiding under the mask of theological phrasings. The doctrine of three Divine persons in the Godhead, is in modern society often smiled upon because or the absurdity of the logic which tries to make three individuals into a One God: but it is rejected - in reality - because the idea of the Divine Human of the Lord is altogether destroyed in the Christian Churches Aespecially with the learned there; only something of it remaining with the simple (@AE 1097, 808; S. D. Index Dominus; Ath. Cr. 189, 198). Swedenborg lamented over this fact, which he knew from the spiritual world; but not until recently has it become freely admitted. The Athanasian Creed, which fastened the doctrine or a tri-personal Trinity upon the church, was actually a lesser falsity - adopted in defense against Arius who had denied the Divinity of the Lord. When now this false defense tumbled, Arius prevailed in the end.

But let us note other instances: When our contemporaries ridicule the old fallacy that the bodies of the dead would rise from their graves on the Last Day, this is not generally done because of any perception that man rises in a spiritual body immediately after death; but it is a new and bolder form of the sons falsity: viz., that life is impossible without a material body, and ceases at death. When the moderns tolerantly laugh at the idea of heaven as a place filled with joys-whether in the stars or on a new-born earth - they usually substitute the thought that the only heaven worth working for, is a heaven here on earth, a pleasant life or peace and of plenty: for-who knows of any other? When they learnedly disprove the fallacy that the Bible is literally the as to history or prophecy, it is not because they feel that within its symbolisms there is a spiritual sense; but rather do they carry further the aversion to the truth that this Holy Writ was inspired by the Spirit of God, or was anything beyond what the letter indicates. When they reject the fantastic doctrine about a salvation by faith alone through an atonement wrought by the merit of Christs blood shed on the cross, they do so not because they see that charity as well as faith are needed for salvation, but because they do not see the need of any redemptive work on the part of the Lord, but regard evil merely as an inevitable complication from an ill adjusted social system, and Christ merely as one of the great moral idealists of the world. And if they feel a revulsion to the various dogmas about a Predestination to hell and about infant damnation, there is often only a superficial opposition to the idea of a selfish, merciless, dictatorial Deity, and little perception or the need of human freedom as a means to repentance and spiritual life. For these same critics may coolly accept the idea that they are relieved or much moral responsibility by being predestined by the blind forces of nature and of circumstance. And if they should object to the insolence of the Pope at Rome in his claiming power over men as a vicar of God, it is not because of the usurpation of the authority which belongs to God, but because they believe that this power and influence should be divided more equally among men.

---

The falsities, then, that desolated the Christian Church, are thus still abroad: the same falsities, but now often stripped or their holy garbs, and clothed with a secular authority more suited to the age. In such forms, they infiltrate the thought of the world, and vary their voices to the pitch of every sect and class, striving, like Paul, to be all things unto all men. The dragon, with his ilk, has truly been cast down from heaven and now walks upon the earth to make war upon the woman and her seed (Revelation xii.).

All falsity proceeds - though by various ways - out or hell. Those which now affect the world proceed as spheres particularly from the hells of Christians (@TCR 618). And these spheres cannot be dissipated so long as there are men who willingly receive them in loves of self and the world, and thus turn them into falsities of evil, changing with every occasion. There is an inner unity within all falsities: in that they are all in interior opposition to the truths of the Word, and to the spiritual sense. Yet the strange thing is, that while truths are consistent among themselves, and make for mutual perfection and harmony, falsities go from opposite to opposite, and combat each other for supremacy. It is partly in this that the safety or the church lies.

Through the clear teachings of the Writings, and their keen analyzes of the falsities of the old church, the New Churchman is largely protected from these past errors; and his mind is filled with general truths which are the gateways to ever interior perceptions of food and of truth. But a mans mind consists of more than these generals or doctrine. His thought roams over many fields or experience about which the generals of doctrine seem to have nothing directly to say. And as the worlds interests and the focus of its problems move away from the realm of the old orthodoxy, the deceptive appearance may arise that the Doctrines or the New Church era largely concerned with dead issues! and that they do not protect us against the blinding influence of the fallacies of the modern world!

We must admit that we are in great measure parts of that world. In our veins there courses the same heredity, practically, as that of the old churches: as are of the same race and genius, and heredity is not changed except through many patient generations. When we think from our proprium, or native will, terrible falsities of evil can be formed, even if prudence disguises such falsities so as not to seem to conflict with the doctrine of our church, nor to support false dogmas which our rational judgment has already condemned. Thus the old falsities take on a form which evades the judgment of the Writings. We may thus observe, and may expect, that within the organized bodies of the New Church there arise parallels to almost every heresy which has infested the old Christian Church.

All New Church men acknowledge general truths of our Doctrine. But generals are only vessels, into which particulars gather continually. These particulars of thought are different with every man. So, for an instance, the general acknowledgment that man lives after death, may be filled with particulars, according to all the ideas which men entertain about the life of heaven and hell. In such a general acknowledgment there may enter not only truths, but fallacies: our individual notions of what we would like heaven to be; ideas colored by prejudice and temperamental preferences, by ambition and self-love, by love of glory and preeminence, or - by purer desires of worship and humility, or service and charity and its perceptions of use.

Fallacies and misconceptions may thus enter into the generals of truth; and, in time, may pervert such a general truth into a falsity, although the general statement or the truth may still be acknowledged.

A general truth is therefore able to fight only general evils. In order to resist interior temptations, we must enter into the particulars or our understanding of doctrine, and purify these particulars from fallacy.

If general truth is loved and lived, and thus conjoined with good, there is a leading by the Lord towards interior, or true particulars. Then man is willing that no other particulars shall enter than such as can adapt themselves to their own general truth. The general truth is held holy, as the ultimate of Divine Wisdom; an ultimate which must not be desecrated or profaned by such fallacies as may spring from the desire to evade a judgment upon our evils.

Living in the midst of a consummated church, the New Church is environed by subtle fallacies, which we imbibe as with every breath. This imposes on us the responsibility of a constant watchfulness. We must understand the world of specious thinking in which our minds move; fallacies which are accepted as practical premises in every paper or book or speech. Only so can we meet intelligently the problems which loom large in modern life.

To ferret out such fallacies is of course possible only so far as they become obvious to each one of us. This work makes a one with the life or regeneration and with the progress of the Church as a whole. We shall never be rid of fallacy. But there are always some fallacious modes of thought and deceptive underlying attitudes which can be generally recognized in every stage of society's development. We propose, in the following series or classes to consider some of these popular fallacies.

For, even though we select only a few samples of the contagious errors of the worlds thought, we believe that only by the constant effort so to do can we come to see the practical value and universal applicability of the distinctive doctrines of the New Church, no longer against the vanishing background or a past dogmatism, but in contrast to the current beliefs which we now face.

== II. THE FALLACIES OF NATURAL THEOLOGY.

In external appearance, we live in a geographical place, in the natural world. But our reel life, our consciousness, the life of our mind, is carried on in a sphere which is often quite independent of place and physical situation, and rises above the conditions of our immediate environment. It may become oblivious of poverty, hunger, and pain, and dwell amidst beauty and feel rich in the enchantment of friendship and truth. Or it may poison the atmosphere of the most luxurious palace with the dregs of suspicion and the bitterness of hate, and the walls of a temple may vanish before it and give p lace to the squalor of passion and the phantasies of self-glorification and conceit. For while our bodies move within the material bonds of physical routine, we ourselves are only superficially tied to its fixed circumstances. The mind as it were looks out into the natural world: but it is not living there. It dwells, and is moved, upon currents of thoughts; it is borne out upon these powerful currents, and by a process only vaguely perceived it seeks-by degrees-that sphere of thought wherein it feels delight and satisfaction. And when it finds a sphere in which some affection finds a correspondent environment, it begins forthwith to conform itself to that sphere of thought.

The natural-rational men prides himself on the independence of his thinking. He even makes ostentatious attempts, now and then, to go counter to what others think; fearing to become a mere conformist. And these attempts are the instinctive acts which prove to man himself that he is gifted with freedom to follow the decisions of his reason and determine the quality of his own life.

Yet the Writings tell us that no man thinks from himself, but from others (@AC 5511, 6470, 8343:2). This does not merely imply that he thinks according to the opinions or those men with whom he associates; for this is not fully the case-or the world would be mentally moribund and static. But it means that thought is not an individual matter. It has a social source-as a formulation of the love and faith, or of the passion and credulity, of any given age, nation, or community.

All the thought of the angels is effected by variations of the light of Divine truth which is perceived by them as coming from the Sun of heaven; and this is the origin also of the thought of man, although he is not aware of it (@AC 4742). This light is modified and refracted by spiritual media, and is reflected in spiritual objects-including all the knowledge of man. But no man can think except in accord with that sphere in which his spirit dwells, whether permanently or temporarily. And to enter a sphere of thought he must be led by something of affection.

It is of common observation that it is difficult to resist a sphere of thought. The worlds history may be traced as successive waves of common thinking, which-like mighty forces-drive events before them, and constitute the inner, moral and spiritual, story or our race. In the spiritual world, all these old spheres of thought are still active, some in heaven and some in the hells. At the end of each church, or dispensation, there have been formed, therefore, new heavens and-new hells; and this as a result of a final judgment upon the consummated church.

A consummated church is said to be vastated of truth, i. e. its former acknowledgments of spiritual truths are gradually forsaken and turned into denials. The falsities already dominant within its doctrine and its thought, come out into the open and present themselves in their real role as enemies of the church, directly attacking it from without as well as from within, by a denial of the truths behind which they had formerly operated.

We find such a state in the so-called Christian world of today. The vastation of truth in the world is but the result of what happened in the spiritual world at the time of the Last Judgment. There, the vastation was far more sudden. By this we do not mean that evil spirits from the Christian world suddenly lost all knowledge of the dogmas they knew in the world. This happens only to some. But even others, who retain the falsified doctrine which was ingrained in their minds while in the world, become eventually openly professors of three gods, and later, as their interiors open, they worship the Father only, and finally they may reject even the idea of an invisible God (T. 536:2). Moreover, the truth which all the hells unite in resisting, is the truth concerning the Divine Human. For this is the universal of all truth. It contains the very law of heaven. It is diametrically opposed to every falsity, to all evil. It is also the interior of all truths, and is therefore interiorly opposed by every falsity.

We therefore read: The hells are filled with the most bitter hatred against the Lord; not so against the Lord; not so against the Father, whom also some hells call the Creator of the universe, from the habit of speaking that was formed in the world, and this without hatred; but all the hells are against the Lord; they are not willing, nor able, to name Him, and to all of them it is most delightful to torment those who adore the Lord.... A sphere against the Lord is exhaled from all the hells, and a sphere for the Lord from all the heavens; hence there is an equilibrium (Ath. Cr. 201).

This explains what is said about one of the sphere in the spiritual world, which flow forth from modern Christiandom: this sphere comes from a quarter where the learned among the clergy and the erudite of the laity are. It enters into the ideas of Christians, and with many it takes away faith in the Divinity of the Lords Human; with many it weakens it, and with many it makes it seem foolish in that it brings in the idea of three gods and confuses the mind (T. 619).

Such a sphere of thought is intangibly present in the world today, even where it is not observed as an outright denial of the Lords Divinity. It is subtly implied in almost every work of fiction, every screen-play or drama, every text in science and history, every modern poem. It hides behind every impertinence in art and music. By things done and things not done, it manifests itself in the policies of governments and in the strategies of nations. It makes one with the conceit of human intelligence, the lust of power, and the greed of gain.

This sphere of denial operates in two ways. Where there is some falsity of religion drawn from the literal appearances of the world it insinuated itself so that it seems to evolve naturally from within it; so that the denial of the Truth about the lord seems now to many as a logical result from an effort to purify doctrine from false encumbrances and ancient superstitions. But where there is no such previous faith, the denial confirms itself directly by all the fallacies of what the Writings call sensual lumen, or the natural light of the senses.

We proposed, in these classes, to examine certain popular fallacies. In doing this we must recognize that the fallacies which each age uses to confirm its loves and its falsities of evil envelop men like a sweeping tide, against which the individual is powerless to fight, unless he can be lifted above this tide, and see it in its true relation to eternal things, and to universal laws. For the spirit of an age turns all appearances in its favor. It reinterprets all facts of experience to confirm its leading thesis or principle. It seizes upon the past and mirrors all its contentions in history.

And if, as in our present age, the gates of knowledge have been swinging open to reveal many new fields of factual truths, and so much wealth of science and discovery has been accumulated that only a giant mind could grasp even a part, a swiftly growing mass of knowledge which has not yet been finally ordered or understood; then there is exceptional opportunity for the spirit of the age to introduce its own interpretation of these virgin fields of research.

For in our age-within a few centuries-the scope of mans learning has rapidly altered. Men used to look to the past, to tradition, to the written Word, as to the main sources of truth. But now the earth is compassed and the eye looks into the depths of the stellar spaces, the secrets of a subatomic world are weighed, the intimacies of the cells within our bodies are watched, and the strata of the rocks divulge the mighty, patient forces which built the mountains over the ruins of extinct forms of life! And with this knowledge as a tool, men look now to the future-a future mastered by mans intelligence, which can construct, now, a mechanized, synthetic universe more to his liking then that which the past knew.

Such is the proud dream of our age-in which we all to some extent share. And it is only partly baffled by the ominous challenge of wars and the dangers of self-destruction, or by the dawning suspicion that with all that man knows, he knows himself least of all, and least of all as a spiritual being, who, after all, even now lives in a spiritual world in which machines and much knowledge are unable to help him!

It is while in the grip of this illusion that modern man looks back upon the Bible-that strangely unique product which was borne out of an otherwise despised race. But from the spirit of the age he does not see its real uniqueness-or that this is due to the fact that in it God speaks to man. He only sees that the Biblical books were written long ago-in ages when it was thought that the earth was flat and the stars its satellites, and when all things were explained by miracles. To modern minds it becomes almost impossible to attribute Divine truth-eternal value-to teaching which bears the imprint of such ignorance. And when it is said that god Himself descended upon this earth-this becomes the more incredible to those who consider this earth as but an infinitesimal point among the galaxies, and not as the center and fulcrum of the universe.

No sooner had science begun its march, in the century before Swedenborg, than there arose a movement which sought to evade these growing modern dilemmas. For conveniences sake, we shall call it Deism. The Deists acknowledged God as being a First Cause, an infinite and incomprehensible and invisible God who cannot reveal Himself to man. The denied that it was God who spoke-by His spirit or inspiration-in the Scripture. God stood, sublime and aloof, as a Creator who had left the universe to work out its own destinies. He could not make known His will. He could not reveal Himself by coming Himself in the flesh. The Scripture was but the record of mans effort to discover God, not of Gods effort toward self-revelation. Jesus Christ was indeed, some granted, foremost in the search for God, and had given his fellow-men better ideas concerning the qualities of God than had any teacher or sage before him; but even he was man.

As for us, the Deists said, (and after them the Rationalists), we should be satisfied with whatever knowledge of Religion and Theology we might arrive at by conclusions from the experiences of the senses and from reason.

---

Now let us point out that the Writings were given to the world as if in direct response to the growing menace of this fallacy, and in anticipation of the time when it would interiorly dominate-as it does today-the thought of the world. The Writings come as a Divine Revelation addressed to minds which are not confined in a universe centering on this globe, whether flat or round; which are no longer in the appearance that the earth was formed and furnished in six days; which do not regard research as sacrilege, nor external progress as mere worldliness. The Writings, from the first, accept the modern scientific perspective in all its essentials, and then proceed to show the fallacy of those who imagine that the opening of the horizon of natural knowledge should militate against the need of a Divine Revelation of spiritual truths, or make difficult the faith in a God who reveals Himself even in the flesh.

The Writings therefore speak of those who believe only in natural theology, or who insist that without the Word man would be able to know of the existence of God, and also of heaven and hell, and to have some knowledge about other things taught in the Word....

Swedenborg indeed takes up the issue on the rationalists own ground: he asks them to admit that mans will dominates his understanding, and that men does not wish to understand or believe anything but what favors his proprium: and indeed, cannot form any other idea unless there be some other source from which he may learn it. Thus man, of his own will, will engender no thought except what is of self and of the world; whatever is above, is thick darkness. When a man sees the sun, moon, and stars, and wonders whence their origin, could he think otherwise than that they exist of themselves; as even learned men, though they know of the Word, sometimes insist? (@SS 115). No. Natural reason by itself, seeing in sensual lumen, is incapable of any notion of the nature of God, of charity, of mercy, or conscience. But these ideas came by Divine revelation, were disseminated widely, from the primeval or Ancient Word, and survived with tradition, so that even gentile sages, such as Aristotle and Seneca, could confirm them by reason. But reason alone could not originate them.

And Swedenborg adds, that in the spiritual world he had been permitted to see people born on islands, rational in civil matters, but utterly ignorant concerning God. They appeared, there, at first like apes! But being born men, they were instructed and became spiritually alive.

Moreover, has not history shown that the tendency of mans will is rather to destroy belief in God and in heaven, than to confirm it. Merely natural light tends not even to the worship of sun or moon, but only to the adoration of self (@SS 116).

---

It is of interest to note, that those who are understood in the Apocalypse by the Dragon-who sought to devour the seed of the Woman-are those who wish to be wise concerning Divine things from Natural Theology, and, by resting in reasonings, bring all things to the negative (D. 4760). By this process is brought to center upon itself-until it relies on nothing else, and uses the fields of natural facts and the things of the literal sense of the Word, to confirm its own opinions.

It is this sphere-of the Dragon-that the New Church must meet, not only as it skulks within the dogmas of a dead church, or as it nakedly is abroad in the world, but also in the privacy of our own minds. From merely natural light nothing of the church can be really understood. It is a light which merely leads man to confirm what is pleasing to him, not to see what is true. In this way he can assume as a principle whatever he pleases, and can so impart to it the light of confirmation as to make it appear to be a truth from heaven although it be a falsity from hell (@AE 846).

This is inverted order. Yet in true order, there is a place for the light of nature, when the rational receives spiritual light (which is from the Lord through revelation) and transmits it to the natural. Therefore the prophet wrote, In that day there shall be a highway out of Egypt into Assyria, that Assyria may come into Egypt, and Egypt into Assyria, and the Egyptian may serve with Assyria; in that day Israel shall be a third to Egypt and to Assyria, a blessing in the midst of the land that Jehovah of hosts shall bless, saying, Blessed be Egypt My people, and Assyria the work of My hands, and Israel Mine inheritance (Isaiah 19:23-25). By this is meant that the time is to come when the rational can be opened by true knowledges, so that man may regard the scientifics of the natural man rationally, thus intelligently, and see in all the fields of knowledge the laws of a Divine purpose and leading (@AE 654[10]).

It is in and through the Writings, that the new highway of spiritual illustration is restored, and an entirely new orientation of all knowledge is possible. The Writings make clear that there could have been no progressive evolution of human reason, unless at each step this had been caused by a progressive Divine revelation of necessary spiritual truths, adapted exactly to the needs of mankind. So viewed, the scattered jig-saw puzzle of present-day factual knowledge will fall into line-in a general order in which these facts assume a new and beautiful meaning, which concords with the intelligent purpose of the Creator.

If we assume the attitude of natural theology, we may indeed be led-by self-reliant reasoning-to admit the existence of a God. But not the real God. The god of the rationalist is a god such as many of the hells also acknowledge; a god who cannot-will not-revealed himself, and never intervenes in his creation; a god who need not be feared because he is in no concern for mankind; a god who cannot be loved, because he treats his creatures as the result of an interesting experiment; a god who is not wise, because his laws, impressed on nature, are blind to the welfare of the individual and work impartially for justice or for injustice; a god, therefore, who has no visible features to love or adore, and whom it is quite indifferent whether he is acknowledged or not.

It is the insinuation of this idea of God that has caused the Christian world to be permeated with an unprecedented indifference to spiritual things, which allows a fuller license to natural ambition. For all religion is such as is the idea of God. The primary object of the Writings is therefore to restore a true conception of the essence of God, so that men may see the world in the light of the truth that the Creator is Love itself and Wisdom itself, and that His universal government of love and mercy concerns itself with every individual soul on all the untold earths. The idea of the Divine Human, God-Man, revolutionizes our concept of the universe, which in its greatests and its leasts is organized into the image of the Divine Human. It makes us see that the single events of the past and the present, the growth of the race and of the individual, the development of the civilization of the past, and of the knowledge of man, the fluctuating progress and retrogression in moral and spiritual ideas-as indicated in the Scriptures-are all dominated under one universal law, one evolving purpose, in which the Lord seeks to make Himself known to men in terms adapted to their own capacity to understand and to take responsibility for what they thus come to understand.

The revelation of the Lord to men is therefore always such that it comes through human, natural ideas. We are taught that there are two foundations of truth,-one from the Word, the other from the truths of nature (@SE 5709). And in the Most Ancient times, the Divine as it were spoke to men and this by means of the correspondences of nature, thus by the aid of sensual light. For Divine order was interiorly inscribed on them, and thus they recognized this order (of love) as mirrored in many things of nature, and in the gestures of the body. But when mans will become by heredity evil, nature became silent and did not yield its representative truth directly, and its order could be seen only from the Word, or doctrine.

(Lest a wrong idea be conceived of the Most Ancient people, it is however stated that what they perceived-as to the order of spiritual and celestial life in their spiritual mind, resided there only, and was never immersed into the natural mind, or retained in the external memory, as is done by the spiritual-natural man of today (@AE 617[15]). And therefore they judged not at all about spiritual things from their experience of natural things, for thus would be to eat of the tree of the knowledge of good and evil, and to claim themselves to be as gods, knowing good and evil, and to claim themselves to be as gods, knowing good and evil from themselves.)

The self-revelation of God to men must take form according to human ideas, and must be represented in terms of human life. The Lord, before the Advent, could represent His qualities, and make known His will through representative men-prophets and kings and priests-selecting out of the minds of these the symbolism which portrayed Divine judgments. Not all men could understand the cryptic Divine message, when so couched; each could perceive only what he was able to accept as a Divine command. In the Jewish Church, the Mosaic law and ritual were forged from elements already known to men; and when the Jews gained contact with the great civilizations of the East-especially Babylonia and Persia-where survivals of the doctrine of the Ancient Church persisted-the prophets of Israel began to speak in tones of a more lofty morality than before, and suggest a greater comprehension of the visual realities of the spiritual world on which they had before been silent.

Yet it is not the search of the human reason for God, still less the making of God in the image of man, that we see in this progress. But it is the Lord, making use of the best material of mans experience, to fashion the words wherein His Spirit could make itself heard.

And when, degree by degree, the human mind-especially among the Jews-had closed itself to the Spirit of God, and refused to admit any such revelation, the Lord could use nothing in mens minds whereby to reveal His love, to save and redeem. And there remained, on this earth, nothing for the Lord to do, except to reveal Himself through the materials of physical nature, and selecting a representative form from the womb of the virgin Mary.

If that road had been closed, the Divine would have been deprived of any way of self-revelation, or manifestation; and this planet, out off from spiritual light, would have become unredeemable, and no flesh could have been saved. But the body of man had not been fully in the power of mankind to pervert. Its order-of birth and growth-was still a means of expressing, though in ultimates, the way of Divine love, and God could make known His Divine Humanness in a more complete and universal manner than ever before. The glorification of the assumed Human of the Lord was the final response to the need of all mankind-on this earth and throughout the universe.

And here again, we must think in terms of universal laws which are little reflected upon in the world. In these universal laws are linked up the reasons for every event and every spiritual provision, and in them is given the light to dispel our obscurities, which are caused by the fallacy of thinking from a confusion of knowledge. We have time, here, to call attention to only a few:

There is the law that all Divine operation must pass through intermediates to ultimates, and there creates and operates.

There is the law that in ultimates reside the power and holiness of prior, or interior things, which are there exerted.

There is the law that all things should return from ultimates to their primes.

There is the law that in ultimates all intermediates are together, simultaneously; and that the Lord rules and disposes all intermediates from primes through ultimates.

The New Churchman is able to learn many other universal laws, from which to think; all indisputable, all aids to clear reason, yet coming with the seal of Divine authority: laws of influx, of conjunction, of symbolism or correspondence; laws of discrete degrees, of creation, and of regeneration; laws of judgment, of permission, of freedom, of Divine government. But besides this, the universe of the New Churchman opens into another world of facts, of spiritual observations, Divinely sanctioned, which enriches his knowledge, and widens the horizon of his mental perspective, immeasurably above the scope of the worlds vaunted research.

It is this vision of eternal truths, which display the ends of creation and the Divine means of their fulfillment in a heaven from the human race; it is this vision which must save us from the fallacy of merely natural theology, and lift us out of the dream of the age into the serene light of spiritual realities.

== III. FALLACIES CONCERNING PREDESTINATION, PRUDENCE, AND PROVIDENCE.

The first message which the twelve apostles proclaimed in the spiritual world as missionaries of the Lord in His Second Advent, was the gospel that the Lord Jesus Christ reigns (@TCR 791). This gospel is the all-inclusive message of the New Church. When a New Church is in the process of establishment, which is called the New Jerusalem, and when its doctrine is taught, the primary thing is to know and believe that the Lord is the only God, from whom is all safety (salus).... For without that faith no one comes into the New Church, neither does anyone receive anything from its doctrine; consequently, without this faith no one henceforth can be saved... (Ath. Cr. 213).

All the hells, in both worlds, labor henceforth to prevent the establishment of such a faith in the power of the Divine Human of the Lord and in His Divine government of human affairs; for there is no safety and no peace except so far as men place their trust in the Divine Providence.

It is on the lips of many, in times of danger or of solemnity, that the Divine Providence superintends and leads men and nations. But the meaning and power behind that pious sentiment varies according to the sphere of thought from which the words are uttered. At the consummation of an age, the church is deprived of all genuine knowledge concerning God, concerning His Omnipotence, concerning mans freedom of choice, and all other truths; until there is no religion, no church, no ministry; and the notion of predestination alone prevails interiorly in the minds of men whenever they come into the spheres emanating from the perverted doctrines of the churches (Abom. Desol., passim).

The roots of the thought of the Christian world in which we live, are tainted by the fact that for centuries our ancestors have mostly trusted in salvation by faith alone, a salvation out of pure mercy apart from mans cooperation in repentance. This falsity the Writings call the dragon, and also the fiery flying serpent in the church (@DP 340). It wore the mask of religious faith. For did the champions of that doctrine trust the Lord most fully? Did they not ascribe salvation to Him alone? Did they not say that only He could-out of His choice and selection-endow this man or that with faith, or grace to believe, man himself being like a stock and stone, devoid of any ability even to cooperate? And that all things of religion flowed out of that miraculously given faith which man suddenly was granted? What more perfect example of reliance on Providence? on a God who could immediately change a sinner into a saint, like an owl into a dove!

The human mind can indeed be inconsistent, can believe remarkable things. But it cannot for long refuse to elaborate upon its premises. It takes up a position, which attracts it because of some pleasant promise which seems implied; but then it begins to embroider upon it-to follow out is ramifications and logical inferences, and accepts these also-whether in self-defense or by choice.

The doctrine of faith alone was bad enough in itself. It was based on the idea of a vengeful God whose sense of justice was satisfied with the vicarious atonement offered in blood by His Son, whose merit was then miraculously transferred to a relative few men whom He gifted with the power to believe. Its direct inferences also were sufficiently shocking: It destroyed religion, in that it took away belief in human free will and the need for repentance of life, and induced on the believer a false sense of security. It made the Word, with its commandments, its call for a life of repentance and charity, of no effect. But its indirect inferences were still worse: for if God selected a few on whom He conferred saving grace, God must be alone responsible for the damnation of the rest! And if salvation was only an arbitrary act of an omnipotent God, who was also omniscient, and mans actions or mans will, had no part in it, then surely God fore-ordained to hell all who were not selected for heaven, including many infants and all gentiles and however well and piously they may have lived! From which monstrous concept it follows that from eternity God must have been both good and evil. And this would in turn mean that good and evil are equally Divine!

The dogma of such predestination to hell by an immutable Divine decree, destroyed not only the sense of mans freedom and spiritual responsibility, but also all conception of the meaning of Divine Providence. God became a majestic, pompous tyrant instead of a heavenly Father, an inexorable law devoid of mercy or appeal, impersonal, inhuman, like the unmotivated forces of nature. And, translated into the language of a scientific age, God became soon openly identified with the interior forces of nature.

It was not the dogma, but the sphere of thought involved in the dogma, that was so translated. The dogma prepared for the doubt about mans free will, the doubt which is implied in all the speculations of a materialistic age.

This is not the place to discuss the scientific theory of mechanistic determinism, by which naturalistic thinkers have sought to prove that human consciousness and so-called will are merely the by-products of changes in a physical universe which neither will nor consciousness are able to influence. But even while writing their theses on the subject, these thinkers must forget their denial of freedom and act as if they were wrong. For to all interests and for all practical purposes, the will-wherever it comes from-does influence the changes of nature; the hand and the pen move to the command of the mind. And it is on this primary evidence that the sense of human responsibility rests-a responsibility which can never be successful evaded by any philosophical argument, however logical they might seem. The man who denies his freedom is under an obligation to his fellows to prove that he is coerced. In a practical sense, to deny ones freedom is otherwise simply a subterfuge, an excuse for what he really wants to do or to think.

It is not merely misguided philosophers, therefore, who attempt to establish this alibi for responsibility, natural or spiritual. One of the favorite pastimes of human beings is to blame their omissions and their faults, their states of anger and their follies, on the crushing circumstances under which they live. Not that men have absolute freedom: but they live amidst limitations in order to recognize freedom when they sense it! In natural and civil affairs, their freedom is very much circumscribed. In moral matters, they are far more free than in external conduct. And in spiritual attitudes this freedom is especially protected, and man often boasts of being captain of his soul, even if he is captain of nothing else.

Freedom, especially internal freedom, is therefore a great reality. Without this freedom, on the part of man, there can be no religion, because religion means a reciprocal conjunction of the Lord and man, and this must be mutual, which is not effected by action and reaction-or by compulsion from the Lord-but by cooperations; for the Lord acts, and man receives the action from the Lord, and operates as from himself; yea, of himself, from the Lord (@TCR 371).

There are spheres of thought, originating out of modern Christendom, or rather from the new hells, which insinuate among men a spiritual lethargy, in respect to the means of salvation, and tend to divorce faith from charity, and prevent their conjunction (@TCR 619). These spheres invite everything which confirms a man in the feeling that he is a prey to forces against which there is no use fighting forces which predestine him to think and act and even to will. It induces a fatalism which leads to spiritual inaction. It takes very many forms; but always it feeds upon the fallacy that; man is not free and therefore not responsible.

In ancient times - indeed towards the end of the ancient church - such fatalism invaded the Orient, and from this it made lasting inroads into occidental countries, tending everywhere to a gradual decadence or civilizations. Such oriental fatalism encouraged all manner of credulity and superstition, which have their survivals even in the new world today. No newsstand is without its several samples of astrological magazines and ready-made horoscopes which purport to lay down the verdict of the stars and their favorable or unfavorable influences, which predestine the course of our lives. There are palmists who read the future in hands or in cards, and are patronized by millions of otherwise sane and responsible people, who yet have become persuaded that the future is thus predestined. The fear of fate is wider than men will admit: and reliance on luck is too often substituted for the use of reason. That men will not sit down at table with twelve others, nor walk under a ladder, and that they shudder when a black cat crosses their path, are also indications that the belief in a merciful Providence has become warped by the insidious notion of Predestination.

Among the cultured, the falsity that God predestined men to hell was succeeded by the pervading scientific attitude or mechanistic determinism already referred to. This attitude - which usually excludes God from His universe quite effectually - has indeed spurred modern progress in many fields; because it looks to an improvement in external conditions, in education and social legislation, for the cause or happiness, regarding these as the material environment which predestines a mans mental states. Diverted towards such a social effort-laudable in itself, because of the truth that the natural mind of man does indeed take form according to the natural environment - this type of predestination loses its initial direction and engenders contradictory fallacies of various broods, which are affecting us today in vital ways.

One such fallacy is that the regeneration of society must precede, or can precede, the regeneration of the individual: that; the evils of the individual are due to the state of society; that the individual therefore has a right to demand from society more than society can demand of him; that the individual can fold his hands as if in fatalistic resignation until society gives him what he wants, instead or trying by his own free initiative to do what; he can, and so by degrees gain a greater freedom.

The other fallacy which the theory or social determinism begets, is quite contradictory. For in the effort to shape the material conditions so that they shalt in turn cause greater happiness to the natural minds of men, men come to realize the importance and effectiveness of their own prudence.

The Writings make clear that those who trust in their own prudence can not even begin to have any idea of how the Lord sees all things and knows ... and provides all things from eternity and has particular and individual care of all things. For they attribute to themselves all things which turn out; auspiciously ... and the rest they put down to fortune or chance, and few to Divine Providence; thus they attribute the things that happen to dead causes, and not to the living cause (@AC 8717).

Fortune is picturesquely described as a fickle goddess, smiling at men one moment, turning her back on them the next. Luck is sometimes pictured, like Justice, blind-folded; but because it disregards all merit, is indifferent to consequences. Within these portrayals lies the real idea - that; luck, chance, fate is a blind force, dead causes, the force of unguided circumstance that apart from the prudence of man himself, there is no intelligent, merciful purpose, no guiding motive which organizes the scattered moments and events of life into a whole, even like the living soul orders and connects the separate sensations of our body into a connected, meaningful whole.

Whether a man - denying such a guiding Providence - attributes what happens to an impersonal fate or ill luck or chance; or whether he - more learnedly - credits what happens - even in his mind - to the inevitable complex or physical changes which with cold mathematical precision weave unending chains of consequences in nature and thus in society: it is much the same. The inner fallacy is the same, that of a predestination which tends to remove human responsibility, loosen the bonds of internal restraint, and confirm man against the acknowledgment that there is in creation, any real purpose, or any Divine end in which he must, in some way, collaborate. Yet the same fallacy and the same denials enter when man - while conscious of being a free agent - begins to glory in his own prudence.

Freedom, and the use of prudence and rational decision and will are inextricably conjoined. Without the faculties of freedom and rationality, man would not be man, and there could be no conjunction between the Lord and man; and religion would be an empty phrase without these acknowledgments. Yet it appears to many that mans freedom is a contradiction to the Lords omnipotence and to the Divine Providence. It is felt that; there may be, indeed, a Divine government, in general; but that, if man be free as to choice, then this realm or human will and human prudence must be a realm into which the Lord does not enter a realm outside of the Divine government! Or perchance, it is argued, the government of God is universal both in nature and in man, but that particulars adjust themselves by chance, or in man, by free choice!

The Writings dismiss these vagaries by the rational doctrine that nothing can be universal unless it includes and enters into all particulars and singulars and therefore the Divine Providence is in the minutest particulars of nature, and in the minutest particulars of human prudence, and that it is from these facts that it is universal (@DP 201). In other words, the prudence or man is but a tool of the Divine Providence for effecting the end of creation, which is the conjunction of the Lord with man.

The prudence of man is thus only as it were a part or the framework of Providence, and as such it belongs to the Lord. The persistent fallacy is, however, that it is not the Lords, but is mans own.

This fallacy is rounded on a constant appearance, according to which man must act in order that he may be free: for he cannot be free apart from this finite appearance. Reception, of life is nothing else than mans acting as if this prudence or intelligence of life was his to use as his own. The angels so act. They shun evils as if from themselves, and do goods with prudence, intelligence, and wisdom (@AE 837[9]). They acknowledge that this prudence is only a loan from the Lords wisdom, and that it is to be used for the Lords purposes; that it is not theirs; that in no sense can it be regarded as diminishing the Divine omnipotence: that if man should misuse his prudence for an evil end, it would actually defeat no end or Divine Providence which looks only to free conjunction of man with Himself and can still act even through the evil for that ultimate end.

The Writings, in every way, stress the need of man to use the gifts of freedom, of rationality, of prudence, which are the pounds which the Lord entrusts to man: If you want to be led by the Divine Providence, we read, use prudence as a servant and minister who faithfully dispenses the goods of his lord (@DP 210[2]). Prudence is also specifically mentioned among the moral virtues (@CL 164); and we are enjoined to use prudence, or discrimination, in all benefactions of charity (@TCR 425) and in our public offices and our private life. For our prudence and judgment are the signs of our responsibility to our fellow-men and to our God. And it is not to be thought that such prudence can be exercised unless men place some confidence in their own judgment. A man continually in doubt; cannot; make decisions, nor can he perform uses. The angels, then whom none are more humble, speak from clear illustration and act with conviction in their proper fields of use. But the Doctrines call that prudence a prudence not ones own, because such do not persuade themselves that intelligence and wisdom are from man, and from interior thought they see in themselves that one cannot be wise or do good from oneself (@DP 311).

But relative to the Divine Providence the blunt statement is made, that mans own prudence is nothing, that not a grain of will or of prudence that is his own in possible in any man (@DP 191. ff., 293), for if so neither heaven or hell could continue to exist. And in explanation it is shown that the thoughts of man are but the surface ramifications of affections - and that the Lord collects the affections or the entire human race into one form, which is the human form (@DP 201), and governs then as a whole.

Yet in no whit does this interfere with mans freedom! The freedom that comes from mans prudence can be used only to fill in the design which the Lords Providence already has foreseen and provided for. Yet they design is not finite, but infinite.

Men are apt to think of this design or Providence from the picture which they have or nature, in which one thing occasions another in a chain of fixed necessities. The Writings record Swedenborg's conversations with angels and spirits about this viewpoint (@AC 6479-8494, S. D. min. 4692). Certain spirits, knowing that the Lord leads men by apparent necessities (D. 2628), had the idea of a pre-ordained fate or absolute necessity, by which the whole life of man is a necessity; and that the Lord was bound by necessity. But since this idea of the Divine partakes or the human idea of finite necessities, attention was called to the fact that man has freedom, and he who acts from freedom of choice is net under necessity. The very idea or a choice implies this! There converge many circumstances (or contingencies, happenings) which can bear man to either opposite. For example: if a man wishes to place some pebbles on the ground, he is not obliged by necessity to put them in any foreordained order, but acts from freedom. The moments of a mans life are like those pebbles. The Lord foresees the form in which man, from freedom, wills to arrange his life. And the Lord then sees whether this fills up the interstice, sees what is lacking, and where, and likewise always what the consequences are, even after hundreds of years. All the things which are from the Lord are most essential but they do not follow in order from necessity, but in application to the freedom or man (@AC 6427).

Thus the Lord foresees with an unceasing accommodation how man as it were leads himself (@DP 202[e]). Every change and variation of the state of the human mind produces some change and variation in the series of things that follow, and this progressively to eternity (Ibid). But the drift of all these consequences of human states, freely determined, would go far wide of the goal or creation, if the Lord did not lead the states or human minds every least moment (Ibid). And this leading is secret, and does not interfere with human prudence or choice, but is accommodated to mans free agency. For everything that man sees, does, or thinks, the Lord does infinite things. In superficial appearance, the history of the race and the life of each man is determined by human decisions. If it were not so, man might just as well not exist, for he would have no sense of accomplishment, so incentive either to will or to think! still less to work or take any responsibility. But the Lord acts, to correct human mistakes, through unforeseeable things. He acts through heaven, mediately, and immediately from Himself, not only into the will and thought of man himself, both with and without mans consent, but also at the same time into many things which befall him (@AC 6480). These contingent things, these providential circumstances, are the means by which the Lord, from infinite resources, supplies the links between the moments of human decision! by which He fills in the interstices which man has not thought of!

It is no use for the doubter to try to fathom these contingencies of the Lords providence, or even to recognize them: for as the smallest grain of dust will blind the eye, so the scruples which pride of intelligence begets will prevent the acknowledgment and sight of Providence. Yet is it not a fact, that even our sensations are so general, so vague, so simple, that a glance of the eye takes in only one, or two objects, and a hazy notion or all else. The image of the object seen is but a single item or an order which the Lord through angels and spirits connects up by associated ideas and emotions, in accommodation to mans previous states but with ramifications which the Lord alone regulates with infinite foresight.

And nature itself, and its seemingly inflexible order is used by Providence to fill in these contingent circumstances. Man is led into that place in natures routine which corresponds to the needs of his freedom and salvation. What man call fortune and chance, apparent accident or fortuitous coincidence, is Providence acting in the ultimates of order. It obeys the same law by which the Lord makes His sun rise on the evil and on the good and sends rain on the just and on the unjust. Unless, in ultimates, there was such a sphere of uncomputables, of uncertainty, as would baffle all research: a field of inconstant relations, such as in a lottery or game or chance, where the uncertainties are beyond calculation and are only governed by a periodic limitation of probabilities;-unless there was such a sphere, which pervades all life and surrounds us with uncertainties, human freedom would not be assured; nor would Divine government be possible.

The things or mans choice, things that are within the range and limited focus of his attention, thus become the vessels for all the indeterminate and unforeseen goods which exist constantly from the Lord (@SE 3366-72), and by which He leads man towards the eternal place within the Grand Man or heaven which accords with his freedom. Even apparent misfortunes minister to this Divine end, in spite or the fact that accidents and unforeseen misfortunes are produced by spheres from evil spirits who act - without mans knowledge - to destroy him by all accessible means, which often appear like mere chance (@AC 6493, S. D. min. 4784). But nothing of evil is permitted unless it is foreseen that it can be continually bent to good by the provident disposing of the Lord (@AC 6489, @SE 1088; @AC 5155).

The Heavenly Doctrine is that the life of every man is foreseen by the Lord, as to length and manner of life (@SE 5002). How greatly that man errs who believes that the Lord has not foreseen and does not see the smallest particulars connected with man.... For each smallest moment of mans life has in it a series or consequences extending to eternity and as the Lord foresaw from eternity what would be mans quality, and what it would be to eternity, it is evident that His providence ... governs and bends the man to such a quality; and this by a continual moderating of his freedom (@AC 3854).

In every choice made by man, in every exertion of his prudence, in every act or his limited judgment, there he concealed the most hideous possibilities or disaster. But the Lord acts for the good of the whole race as well as for the good or the individual. He rectifies mans errors by moderating his freedom; and also by balancing one mans error against that of another. And we are assured that they who trust in the Lord, continually receive good from Him; for whatever befalls them, whether it appears as prosperity or adversity, is still good, since it conduces as a means to their eternal happiness. But they who trust in themselves and in their own prudence ape continually drawing evil upon themselves; whatever befalls them, however it may seem as success and delight, is poisoned by anxiety for the morrow and turns to their eternal detriment, although the Lord at all times presses to bend it into a lesser evil for them and others (@AC 8480).

There is no room, in our Doctrine, for any hope that faith in Providence will by itself, or even by prayer and fasting, ensure mans temporal prosperity, as we believed among the Jews. The sons of this world are more prudent than the sons of light! The wicked perform uses equally with the good, and are apt to have more ardor and energy, less scruples in gaining their ends. Especially so, we read, in wars, because the evil man is more crafty and shrewd in contriving devices; because a good man is prudent and zealous only in defending, and rarely is prudent and zealous to any extent in attacking; for while it is allowable for anyone to defend his country ... it is not allowable to become an enemy without a cause (@DP 252[2]).

All that is promised, therefore, is that the Lord provides for the good, who receive His mercy, in time, such things as conduce to the happiness of their eternal life, riches and honors to whom they are not hurtful, and no riches and honors to whom they would be hurtful. Nevertheless to these latter He gives in time, in the place of honors and riches, to be joyful with a few things, and to be more content than the rich and the honored (@AC 8717[e]).

---

There is no acknowledgment with man of a Divine providence, except from a deep sense or the actual presence or God in all the things of life: a sincere and single hearted faith that the Lord Jesus Christ reigns in His Divine Human, from whom is all safety. Such a faith and trust is fortified in the New Church by a knowledge of the laws of Divine providence. The operations of Providence are not to be known, and the future is sealed to secure our freedom. But our reason is given to see that God is Order; and it may therefore be enlightened to cooperate with that Order by learning its spiritual laws.

By this effort to see and obey the laws by which Providence leads and rules, me can be protected from the sphere or fallacies which emanate out of the dogmas of Predestination, old or now, which create a universe empty of soul. Whether they take the form of a denial of human freedom directly; or whether they raise the spectre of Fate or Fortune or blind elemental Nature as the tyrant of our souls; or whether they set up human prudence as joint partner with the whirling atoms in predestining man; yet there is but one saving perception which can restore sanity and re-establish religion: And that is the perception that the inmost Soul and governing Form within all things, guiding all events to their eventual fulfillment, is the Divine Human, infinite Love and Wisdom, in Whom we live and move and have our being.

== IV. THE FALLACY OF UNIVERSAL SALVATION.

Out of the confusion of modern life we hear the call of many persuasive voices which seek to dissuade us from feeling the reality of evil or sin. These voices - some bold, some cautious - proceed alike from the chairs or learning and from the pulpits of sectarians, as from marts of trade and from halls of pleasure. They ask in varying intonations, What is evil? Is anyone really responsible for sin? What other hell is needed, beside, our present pains and discomforts?

These skeptical questions are indirect, contorted echoes of the age-old dogma of Predestination, which like the mythical hydra, grows a new head for each that is cut off. For the persistent fallacy within the dogma is that man is not free. And from that assumption it would follow, that the evil he does is not the fault or man.

A man who rejects the religious falsity that God should predestine anyone to eternal condemnation, might get be attracted by the idea that an omnipotent God would instead arrange, for a universal salvation, and permit no soul to be lost, however much steeped in evil. When he so argues, from the light of his own intelligence, and setting aside, at the time, the testimony of Divine Revelation, he is not able to reflect that such a provision would also be an utter negation of human freedom and choice. For he is then thinking from a natural affection which seeks, above all, to avoid spiritual responsibility so as to be free to do as it pleases.

Man is usually not aware, at such times, that his wish-thought is not prompted by innocence and good-will. It would be lovely, says the Universalist, if there were no hell! good for all! a perfect consummation of the end of creation! a complete answer to any doubts about the mercy of the Lord! But wait, says the Christian Scientist, would it not; mean more than that? If God, by an act or omnipotence, could take away the possibility or the results or evil, why could He not equally prevent; evil itself, prevent any evil from occurring? And if so, perhaps what we judge to be evil is not such, but all, even now and here, is good, and its evil aspects, of war, of crime and disease, are only an illusion born in our immature and earth-bound minds? Abstain from thinking that; anything is wrong, and presto!--all evil vanishes!

It is not only the universalists and the various sects of mental healing that can argue themselves into these imaginary heavens. The fundamental illusion comes from what the Writings call mans natural good! For this natural good, which every mans flesh is heir to, and which is sometimes brought to the fore through misfortunes and diseases, or physical weakness and dependence on others, makes man kindred to the gentle animals, and urges him to think from impulse and confirm whatever pleasant fancy that may at the moment please the natural man, or help to dismiss his anxieties, or soothe his doubts about his own virtues. Man continually gravitates into this mind or natural good, which is keen to see what is good for the natural, i.e., delightful to the natural men. It takes the form of generous impulse, of courage, or gaiety, of friendship, of pity, or of other virtues; but within, it always centers in self. It discourses self-exploration. It is superficial and fickle, unreliable. It turns away from the discipline of reason, and is carried away by persuasions like chaff in the wind (@AC 6208), being as easily led by evil as by good, provided the evil be presented as good (@AC 5092, 7761, 8002, 8772). It is also called good from proprium (E. 458:8), and it is unable to serve as a plane for the influx or heaven. It is not to be, confused with conscience.

From the nature of this natural good we may see that it lacks judgment. It is instructed by truth, and therefore cannot recognize evil; nor can it recognize what is genuinely, or spiritually good! From natural good one is apt to be blind to the faults of ones children, partial to ones family, biased against ones rivals; it lays one open to be imposed upon; it leads to credulity and self-deception, and to a misplaced optimism. And in the joy of conscious self-expression it forgets to enquire as to the wisdom of ones act or speech. It may often try to outdo charity itself in generosity!

Yes. Natural good can as easily join hands with atheism as with religion! It can reel quite indignant about the narrow-mindedness of the church and the uncomfortable coldness of rational common sense. It is also averse to the love or spiritual truth, because it prefers to judge doctrine by its own feelings and states. Therefore natural good leads a man into spiritual darkness, and into a moral twilight where good and evil seem to blend into a vague, colorless sameness.

(Parenthetically: It is on such natural good that theater-audiences and magazine readers love to feast. Mental food is there provided, salted with sale that has lost its saltiness! Impulsive sentimentality there receives its undeserved laurels! Courage without judgment is vicariously enjoyed! Wishful thinking beers unreal fruit! Criminals are turned into heroes by a sudden act of sacrifice! Good and evil become so indistinguishable that everyone feels the better for it! For here humanity is weltering in its own imagination - each man enjoying by proxy what he cannot experience in person!)

It is this natural good - which is so abundant in all of us - that stands ready to respond to the subtle fallacies which hide the interior spheres of the hells. And they always lead, indirectly, towards a denial or any essential difference between food and evil, or to the doubt or the existence or any permanent evil, or of any eternal truth! It is like the serpent whispering to Eve, Ye shall be as gods, knowing good and evil. Is it not man, who, by eating of the fruit or experience, determines what is good and what is evil? does not what is good in one age become evil to the next?

If this denial that evil is really opposite to good, could be established in mens thoughts, the victory or the serpent would be complete; and there would be that profane marriage of heaven with hell, of which William Blake wrote! To save us from that, hell is permitted by the Lord to show its ugly features, not alone in disease and death, but through crime and war, through obvious sin and falsity. Yet evil is not exposed - in its eternal opposition to God - in any of these temporary events. It was necessary, when men began to eat of the tree of knowledge of good and evil, for the Lord Himself to reveal this eternal opposition and to teach in the written Word what was against His Will, what was permanently contrary to His merciful purposes by which His creatures might enjoy His gifts of eternal happiness. He warned men against evil by forbidding certain symbolic acts which, if not shunned, would defeat His plan for their happiness. And when mankind still persisted in their evils, insisting on determining for themselves what evil was, He revealed, by His own mouth, the consequences or sin. Even in the New Testament, however, He spoke in symbols, and described heaven and hell by parables and human similes. Hell He depicted as a place or darkness wild disappointment, a lake of unquenchable fire, where the wicked would undergo eternal chastisement.

Christians have usually taken this quite literally. Modern Catholic textbooks brand as rashness any suggestion that the fire of hell is figuratively used(*1), and insist that hell (and also purgatory, a thing of their own invention) is in a place. Among Protestants, such orthodoxy is more rare, although the preaching of hell-fire is still the common vogue of evangelists in terrifying their hearers into contrition. The Writings of course make clear that hell is a state rather than a place, and that whatever the appearance - its fire is actually the loves of self and the world, its darkness is due solely to the falsities which lead to willful ignorance. And it was left for a New Churchman to point out(*2) that the eternal punishment of the wicked, in the Greek text, meant rather discipline than torture, since the word used is [scanner unable to insert word] which suggests pruning, checking, tempering, correcting: which, of course, must be an eternal process in the hells; whereas punishments are not everlasting.

(*1) See God and Creation, by T. B. Chetwood, S. J., Benziger Bros., New York, 1928.

(*2) C. J. N. Manby, The Eternal Duration of Hell, Toronto, 1901, page 62.

---

The aversion or men to recognize the nature or evil has led thinkers in every age to seek for some way of evading the truth that it can persist permanently. In the ancient Orient; such a way was found in the doctrine or Nirvana; according to which all creation, after an epoch, returns into its infinite source - leaving no trace, like a flame that has been blown out. Another Oriental phantasy,--or much influence even on Western peoples - is the doctrine of Transfiguration of Souls, in which the period of mans choice is extended over many life-times, mans spirit being reincarnated, either as a higher or lower form of life, and re-born, as a king or a pauper, as a man or as a beast, until ha attains the Nirvana of blessed extinction; unless the world is dissolved eer then.

A counterpart of the same idea is found among sects such as Jehovah's Witnesses, who believe that at; the impending Last Judgment, the wicked, whether dead or living, will be annihilated, leaving the newborn earth to be enjoyed by living and reincarnated saints alone. But this simple solution of the worlds troubles did not generally find favor in the Christian Church, although there were many prominent Church Fathers who believed in the eventual redemption or conversion of the hells. Among them were Clement of Alexandria, Origen, Jerome, and others, and later John Scotus Erigena. And in Swedenborg's life-time, Lavater, who wrote to Swedenborg, and Franz-Stilling, who wrote about him, also defended Universalism; as also William Law, the mystic. Later a Universalist church was founded, in 1770, in America, on the creed that all must pay their debts to God, but that a harmony of all souls with God will eventually ensue. As an organized movement this church is negligible; but their doctrine has greatly permeated the thought of our contemporaries, as if by a silent capillary attraction. For natural good stands ever ready to solve unpleasant problems by closing its eyes to the essential issues. And the essential issues are, first, what has the Lord revealed? and second, Can man have spiritual freedom if he is prevented from making his choice permanent?

The modern Christendom about us is more and more veering away from dogmas. It has found a formulae for evading the force of the Gospel teachings. The idea of hell lingers in the theological schools, but the rear of a personal Devil is very rare and the clergy have to reduce their flocks into very unsound emotional states before hell-fire has any meaning for them. The real underpinnings of religious motive are weakened by the influence of a popularized version of evolutionary teachings which present man as basically good, evil as a superficial disease due to the infection of the environment, and civilization as the healer, not religion. Give man what he wants, feed him and clothe him and amuse him, and he will become good - that is the general philosophy.

---

The demoralizing influence of the persuasion that the hells are eventually redeemed has even penetrated into the organized New Church. About the middle of last century, there appeared the figure of Thomas Lake Harris, who by an apparent reception or the Writings, gained a number of leading New Churchmen as converts to his amazing form of spiritistic celestialism, claiming to divulge - in inspired doggerel verse - the celestial sense of the Word. And among his teachings was the redemption of the hells! A number of years later, Dr. W. H. Holcombe, the author of several popular New Church works, became a prey to a similar influence, and a pretender to a celestial status, from the point of view of which he felt free to make good the supposed omissions of Swedenborg. He claimed that evil spirits could descend and corporeally obsess men who were fully regenerated,-like a Mr. G. W. Christy-and that, by living in their organism, the sensual spirits would have a new chance for repentance; and this until all the hells were redeemed.

But even in more recent times the idea was revised. In 1898 to 1901, Mr. Albert Bjorck (who later retracted and for a number of years was affiliated with the General Church) carried on an admittedly able defense of the idea that a change of will can take place also with the devils in hell. Swedenborg's testimony to the opposite effect he dismissed by his claim that the law, by which such a change of state is possible with the devils, is a new law which came into operation only after the Second Advent had occurred!(*)

(*) Manby, op. cit., page 17.

---

That we should find those within the New Church who will defend the non-eternity or the hells is surprising; not because it is not quite natural that we should wish that evil would eventually cease; not because there is not with all of us that natural good which tends to escape from accepting realities; not because-with New Churchmen-the problem of combining the idea of Divine Omnipotence with the permission of evil looms any less difficult when we are in states of merely natural thought; but because the Writings are so perfectly clear in their teaching that if any spirit from his free will desires sincerely to repent and leave hell, he is given every assistance by the Lord. There is no question at all about the freedom or those who desire to come out of hell, for the whole endeavor of Divine Providence is working in their behalf. But the question is whether a spirit shall have the freedom to remain in hell, remain in his evil loves and in their delights, if he chooses this course despite all the inevitable disadvantages which his choice implies.

It is easy for a man here on earth to say that he would prefer even annihilation to a life in hell. But no devil desires annihilation. We loves his own life - even more than any angel does. He treasures it above any angelic blessedness. The notion that any devil desires to leave his evil loves - or to leave hell except for the purpose of extending his power over others and to deceive credulous spirits - is a pure assumption, which could be confirmed only by Divine Revelation. And Divine Revelation denies that it is ever so.

Reason might put in a word here also. For if the choice of man, the freedom to choose and cultivate and confirm a ruling love, is not to lead man into the eternal fruition of such a choice and preference, but - after death-would be again reduced to a thing of no value, and be played upon by undesired circumstances and thus be cheated of its conclusion and fulfillment, with the certainty that whatever he decides, he would be pressed back nonetheless - into one direction only - viz., to a subservience to the Lords dictate: what feeling could man have but that his freedom is but a brief vanishing flash, like a match which flares up and then flickers out forever?

On the other hand, if there was no provision against a change of love with the devils, could there be any such safeguard for the angels? Could not they as easily degenerate, and fall into infernal loves, reducing the spiritual world into an uncertain, disordered chaos of beings who had no aim, no reason for living, no settled personality or permanent qualities?

But enough or such speculations! It is because human freedom is the most real thing in creation that the Lord protects its final choice and enables man to preserve what it has chosen. It is because or Gods great love for the freedom which makes man the image of God, that it in provided that no ones life can be changed after death, because it is organized according to his love and consequent works; and ... that a change of organization is possible only in the material world, and is utterly impossible in the spiritual body, after the former has been cast away (@CL 524[3]).

All. who come into the spiritual world are distinguished as to their quality of life by this test, that those who can be saved can resist evils as of themselves, while the rest cannot do so (@AE 1165, 971:3) The inmost of the Divine providence respecting heaven is to lead each salvable soul to his own situation in the Grand Man of heavenly uses, and this is accomplished by means of his affection of good and truth which corresponds to that place and use. The Lord continually withdraws man from the deepest hell-whither he tends. But if he cannot be withdrawn in freedom he is prepared for his own place in opposition to heaven, that is, for his own position in hell, so that his power for evil shall be counterbalanced by a corresponding heavenly influence. This, we are told, is the inmost of the Divine providence respecting hell (@DP 68, 69).

---

The conception that evil is the fruit of a deliberate choice, is a ruling love in actual organic relation to all other evil loves, and that all evils are thus the pervert opposites of a grand organization of good loves which display in actual uses the eternal fulfillment of the Divine ends of creation,--that is utterly foreign and incomprehensible to the thought of modern man! Not that evils, selfishness, crime, cannot be recognized. Common perception persists, aided by many remnants of religious teaching. let us not think that there are not multitudes of good people who cherish the general truths of the Word and obey the commandments there given. But the vision, even of these, is confused by the seductive call of natural good. Natural good looks at acts, not motives. It doss not see that an evil love can express itself even through moral virtues, through friendship and modesty and temperance and courtesy. It takes these things at their face-value, and is ready to believe that if one or two of these virtues are shown, the act must be genuine. It has no appreciation of the fact that unless the evils of the heart are uncovered and resisted, goods are not goods of charity. Natural good cannot recognize its own superficiality, and is satisfied with poor results.

The Writings certainly do not encourage us to judge of mans spiritual states or to go about suspecting their motives! But the Writings teach quite definitely that an evil is not shunned except from the Lord, or except it be seen as a sin against God. This is what natural good forgets. It does not see evil as a sin against God, but as an uncomfortable complication in the relations of men. Therefore the world balks at the idea of hell. There are no devils, no villains of deepest dye, nowadays. No black and white, only shades of grey. The noblest love is traced to some ignoble jungle instinct, the coarsest brutality to an inferiority complex acquired in childhood. How then can one speak of good and evil! They have both lost their inner meaning. And the chief virtue of a man of liberal education is to give the devil his due. And while-if a Christian emphatically condemns some evil-he would be criticized for his harshness, as the Lord for His hard sayings; yet if that Christian exercises tolerance and forgiveness towards an evil doer, it would very likely be mistaken (by natural good) for indifference to the evil done. And from that same natural good, men find much to admire in the worst or their fellows, and find it almost impossible to believe that an atheist, because he engages in philanthropy from professed self-interest or animal good nature, should not thereby have atoned for all his blasphemies and for the spiritual harm that he has callously done to the innocent minds of others, for the peace and comfort of which he has robbed them.

No. The world finds it hard to believe in hell, or in the permanent nature of evil. But the Doctrine of the New Church restores the knowledge of what evil is. The Writings even list the acknowledgment that there is a hell, among the essentials of religion.

Evil being a perversion, it cannot be known except from good. Good discloses evil (@AE 239[3]). Evil is that which is contrary to the love to the Lord and love towards the neighbor. The love of self and of the world are not originally, or in themselves evil; but by themselves,--separated from spiritual loves - they are evil: they are evil when they dominate over, and destroy or harm, these loves of heaven by which happiness and wisdom can alone be established among men (@TCR 394, 403-405). For then, the love of self comes into opposition to all the ends of creation.

Swedenborg, while conversing with two angels who had been brought up in heaven and were at a loss to understand how anything evil could exist, took care to explain that while good proceeds by degrees to a greater good or to a lesser good, and while evil similarly progresses to a greater or lesser evil, yet there is no relation or progression of good to evil, but that in every respect they were opposites. When the least of good becomes nothing, there springs up, on the other side, evil (@CL 444[3]). Evil, conjoined with its falsity, is therefore said to be a nothing; yet regarded in itself it is not nothing, although it is nothing of good (@DP 11, 19, @CL 444[3]).

The Word describes the beginning of evil and sin as the eating by Eve and Adam of the forbidden fruit. For evil is a turning away from God and from His order wherein all things are subordinated to love and charity. And the all-inclusive falsity through which evil operates is the confirmed belief that one knows good and evil and becomes wise from oneself and not from God (@CL 444[4]). In all evil there is therefore hidden an anger against the Lord and against the holy things of the church through which the Lord speaks and acts (@AE 693[4]). From these things it is clear that evil is not an act but a spirit, a perverse love centered in self, an attitude or utter opposition to good.

When this spirit of rebellious self-love was formed with men, hell came into existence, simply by perversion of true and good things into uses not in accord with a good end. Evil has no power except by truths and appearances of good. If it acts by manifest lies or falsehoods, it is impotent to do any harm to the good, but is as it were laughed out of court. It then meets its judgment, its penalty, which is merely that its power to seduce the good is taken away and it must go elsewhere, seek a sphere where pretense and falsity are tolerated. So it is that the evil flock together to form hells, where the evil of one can find delight and power through the phantasies that rule in another.

While man still so desires, he is free to repent or evil and become reformed. No man is taken away from this opportunity by death, for the Lord foresees all possibilities or repentance. After death, however, he is led by his confirmed ruling love, and if this is evil, he is vastated of goods and truths. The law of Providence is that good and evil, truth and falsity, must not be, mingled, but that good should be united to its own truth and evil to its own falsity. From the evil spirit, therefore, is taken away the truth which he had adjoined to his evil.

Yet there is with every devil or hell certain human graces left! Even a devil was once a tender, innocent babe, a docile child. And therefore remains of good and of truth were stored at the depths of his mind, as borrowed states reserved for whatever use the Lord might find for them. The definite teaching is that the good and truth which are not adjoined to evils and falsities, are not vastated. The remains, with the evil, are reserved by the Lord and withdrawn beyond mans reach, and are used - in the other life to temper and modify the states of the spirit; and this in order to maintain something of the power to think and will, that there may be something human still left, and thus a communication with heaven! (@AC 1906, 7556, 7560). And note this sentence of Doctrine: There is indeed a communication with heaven of the evil, even of those who are in hell, but; no conjunction by good and truth; for as soon as good and truth flow down from heaven and come into hell, they are turned into evil and falsity, whence the conjunction is at once broken. Such is the communication (@AC 7560).

We gather from this that while an evil spirit is his own form of evil and falsity, yet; not only has he always a human soul, still unperverted, but also his external man is tempered and modified by remains which cannot enter his consciousness without being perverted, but which can unconsciously modify his life. Therefore the devils retain the use of their reason to differing extents; and evil spirits, like evil men, may have aversions for certain types of crime, drawing the line at one while rushing into another without restraint!

Yet another law of mercy is that when good and evil with a devil have been profanely mixed, both are removed from his consciousness, often by agelong sufferings, in order that the spirit may not utterly pariah in the eternal tortures of a conflict of opposite delights.

Let us not think that, despite these attempts by which the Lord ameliorates the lot or the evil, the evil are in such delights of their own that whether one chooses heaven or hell is of no moment! Hell is not a place or eternal torment. But neither is it a state or eternal delight. The very nature of their delights is to avoid the laws of order and the necessities of labor and justice. To do this, they retreat into a phantasy which cannot be maintained; or they inflict harm on others, to whose retaliation they are then suggested. And they are soon forced - in order to rebuild their phantasies upon some basis of truth - to labor under others, in return for shelter and food for their souls.

Punishments for excessive evil-doing bring the devils into new hells, described as hells within the hells. By the torture of these penalties, which are administered by other devils, but moderated by laws, the offenders are cowed until they - from fear - consent to use self-compulsion and abstain from carrying their evils beyond a limit. Then they are taken out of these hells of punishment and returned to the hell of their ordinary routine life.

The devils rebel against their restriction, against the enforced labor which they are required to perform. Yet they are willing to undergo all this rather than give up the delights of their life's love. Even their punishments are permitted for their own good, and their our amendment. They cannot indeed be amended as to interiors, but only as to exteriors (@AC 6977). But so far as they are, by fears of consequences, brought into an external order, they have also the advantages which civil order brings; they can, in a fashion, perform spiritual uses or a vile sort, and thus become for the time a superficial part of the Grand Man of uses, and are so far lifted out of that state which is called hell, the state or their interiors, to which they return again when their uses stop (@AC 696).

This picture of hell is not so very different from the states of life of corporeal and sensual men on earth: a life with its own peculiar delights, purchased at a price of the happiness of their neighbors and at the constant risk of retaliation; but a life which is preferred by choice, and cannot be ameliorated except on the surface. The doctrine that devils desire that life and wish its continuance, is not revealed in order thee men might thus tremble and repent from fear of hell and its eternal fire. The fear or hell has its functions, and does indeed remove evils temporarily, but it does not implant goods of love and charity. What man does from such fear does not remain for long (@AE 1133, 193:5, @DP 139[4]). With those who are in the good of faith there is no rear or hell and of damnation, but there is a holy fear, which is an aversion to doing and thinking anything against the Lord and against the neighbor, or against the good of love and the truth of faith (@AC 2826).

But the doctrine about hell is revealed that we might see evils, know their source and origin, and thus be enabled to shun them in ourselves.
