= Saul, David and Solomon - The parable of three kings
By Hugo Lj. Odhner
include::../template-attributes.adoc[]


////
The book actually uses Ahimelech five times (for Abimelech)
NCBS search can't find it
////

General Church Publication Committee + 
Bryn Athyn, Pennsylvania + 
1967

Copyright 1967 by + 
The General Church of the New Jerusalem + 
Printed 1967, 500 copies + 
Printed 1975, 500 copies +  
// added per my copy

Printed in United States of America + 
George H. Buchanan Company + 
Philadelphia



". . . For the letter killeth but the spirit maketh alive." + 
2 Corinthians 3:6 

== The Reluctant Kingmaker

In the sacred history which is comprised in the Old Testament certain periods are given special emphasis. The four generations of Hebrew patriarchs - Abram, Isaac, Jacob and Joseph - occupy most of the book of Genesis. The story of Moses and the exodus from Egypt, followed by the conquest of Canaan, is the subject of four other books. The brief period of United Israel under the three notable kings, Saul, David, and Solomon, is the next detailed account. The story of the two prophets Elijah and Elisha covers a great many chapters in the two books of Kings. And finally the books of Jeremiah, Daniel, and other prophets give many incidents from the time of the Babylonish captivity.

The inspired Writings of Emanuel Swedenborg give a detailed exposition of only two of the books of the Old Testament - namely, Genesis and Exodus, the spiritual sense of which is fully unfolded in the Arcana Coelestia. Besides this, they give meager outlines of the spiritual sense of the Prophets and the Psalms. Yet there are sufficient teachings given, scattered in these Writings, to enable us to confirm that all the events of the Biblical drama internally treat of the progressive states of the Lord's glorification and of man's regeneration; indeed, that the Old Testament contains a continuous internal sense which reflects and contains the spiritual teachings of the Lord in His second advent.

It is predicted of the New Church that "every Divine truth in the sense of the letter of the Word is, with the men of that church, translucent from the Divine truth in the spiritual sense." This is signified when it is said that the walls of the New Jerusalem were of jasper, shining like crystal. "The Word in the sense of the letter is of such a nature that the more a man is enlightened by the influx of the light of heaven, so much the more does he see truths in their connection and thence in their form; and the more he so sees them, so much the more is his rational mind opened interiorly, for the rational is the very receptacle of the light of heaven." (@AR 911, cf 897).

The present little volume aims to present some highlights in the story of the three kings of United Israel; for in a sense their reign marks the culmination of Israel's hopes and the nearest fulfilment of Jehovah's promise of a homeland for Abraham's seed. It is a very human story, this striving of the twelve tribes for a country of their own; a story which reminds us of the pioneering efforts of many immigrant peoples who have fled from oppression. And in a larger aspect, does not every man long for the freedom, peace, and power of an inheritance of his own - for a field of uses of his own or for the fulfilment of the promise implied in his inherited talents? The spiritually minded man sees this promised land more clearly, as an opening of new opportunities for selfless cooperation with others in uses which look to the establishment of the kingdom of God, both on earth and eternally in heaven - uses which promote charity and spiritual enlightenment and are inspired by, and centered in, an ever more pure and perfect worship of the Lord and in a realization of His leading. All such human aspirations - civil, moral, and spiritual - find their parallel in the events which led up to the establishment of Israel in its promised land. Whatever men find to be worth striving for as a means to a life more abundant, can be reached only by the way which Israel had to tread.

Progress begins with a vision of this goal. There must be a Moses to reveal it and hold it before our eyes. But there must also be a realization of the bonds that bind us, and the courage to shake them off. We must leave the merely worldly climate of Egypt. We must commit ourselves to the hardships of the wilderness - to a sacrifice of less important things, to the discipline and training which the Lord called "the strait gate" and "the narrow way." We must accept new laws and order our lives for survival, and fight for each new stage of the way.

The fight seems often as one against outward conditions, external enemies. But on closer examination it is realized to be a fight against ourselves, a struggle for self-control, for mastery over the impulses of one's lower self; a fight against our inward foes.

This held true even with the Israelites, who could not advance into their inheritance until, after forty years, a new generation, trained in warfare, had been raised up. The conquest of Canaan under Joshua was never a complete conquest, however. The tribes settled down in their scattered districts, but usually they could only maintain themselves in the mountains and highlands, while their enemies held - or by turns controlled - most of the fertile valleys and the shores of the western sea. The only strength of Israel lay in their possession of a common shrine - the tabernacle at Shiloh in the center of the land. For there the scattered tribes gathered to consult together and learn the will of God. When, through disloyalty, they had fallen into idolatry and intermarriage with their pagan neighbors, their strength departed. Foreign nations or nearby nomadic tribes then invaded and began to oppress them. But in such times of crisis, common leaders were raised up by the Lord, to lead the repentant people to throw off their alien yoke.

In this period of perhaps several centuries, known as the period of the Judges, the solidarity of Israel was maintained against terrific odds. While the worship of Jehovah was continued at Shiloh, there was no central government and the Mosaic laws were largely neglected and forgotten. And the sacred chronicle repeatedly complains that "in those days there was no king in Israel but every one did what was right in his own eyes." It was an era of political and moral confusion. We see this in the pathetic story of Jephthah, who sacrificed his own daughter in fulfilment of a rash promise to Jehovah. We see it in the strange story of Samson, who used his God-given strength with playful abandon, but whose moral weaknesses blinded him to deceptions. We see it in the tale of Micah whose idols were stolen by the Danites. We see it, intensified, in the terrible moral degradation which caused Israel in horror almost to annihilate the tribe of Benjamin.

---

One of the last of the Judges was Eli, a good but weak man, who also was priest at Shiloh. But his two sons, who were in charge of the sacrifices, were evil and utterly corrupt; and the Lord sent a man of God charging the father with honoring his sons above the Lord, when he only mildly rebuked them for their abuses. The Lord therefore raised up Samuel to succeed him.

Samuel was one of the most admirable characters in the Old Testament. His mother Hannah had "lent him to the Lord" while yet a child. He is the first Scriptural character who was the product of a religious education. He was brought to Eli as soon as he was weaned, and was trained to help Eli in the tabernacle. It is said that "the Word of the Lord was precious" - that is, rare or unusual - "in those days; there was no open vision." Yet while he still was a child, Samuel was called to be a prophet of the Lord, or a "seer", and it is plain also that he became one of the inspired writers of Scripture. (I Samuel 10:25)

It is of interest to note that during the period of the Judges the Lord sometimes sent His "messenger" - or an angel - to exhort the people to repentance or to strengthen some leader. Mention is also made of "a man of God" rebuking them for their sins and thus acting as a prophet. Yet it remained for Samuel to establish the prophetic office on a more stable basis. He instituted the first prophetic school, a training-place for a company which became known as "the sons of the prophets."

The "sons of the prophets" were specifically trained in religious songs and the use of psalteries, pipes, and harps, tabrets and cymbals. Some may have been given instruction in the law and in writing. But besides this, they seemed to have been seized at times with religious enthusiasm, dancing and casting themselves in the dust, interpreting the message of God in dramatic form, acting as if obsessed with the Divine Spirit even as to their body. Several instances are shown of the hypnotic effect of such choral actions upon the beholders who thus also were seized with the prophetic impulse, and caught up in the vortex of inspiration.

In the last days of Eli the priest, an event occurred which shook the foundation of Israel. The two evil sons of the aged priest allowed the ark of the covenant to be brought out from Shiloh into the field where Israel was battling with the Philistines. It was an act of superstitious faith - whereby the people's lack of courage and discipline was to be made up for by a scheme to compel the Lord to work a miracle. The outcome was that the sacred ark fell into the hands of the Philistines and the sons of Eli were among those killed in the battle. And hearing of the disaster, Eli's heart was broken, and he fell dead from his seat.

Here came Samuel's opportunity to rally the people from their crushing defeat, rebuild their faith by a call to prayer and repentance. The Philistines were eventually pressed back, with the Lord's help, so that, for twenty years, they "came no more into the coasts of Israel."
"And Samuel judged Israel all the days of his life." The Philistines voluntarily returned the sacred ark, which had brought them only misfortunes; and it was lodged for twenty years in a small town in the Judean foothills, within territory recovered from the Philistines. But it does not appear that Kirjath-jearim, the place of the ark in this period, was the only place of sacrifice, as Shiloh had been. For Samuel went yearly on circuits to Beth-el(*) and Gilgal and Mizpeh, and returning to his house at Ramah, sacrificing and performing his office as a judge.

(*) Possibly Beth-el, "the House of God", was a title then bestowed on Kirjath-jearim.

He also appointed other judges, among them his two sons whom he set over Beer-sheba. But his sons - to his sorrow - did not walk in his ways, but took bribes and perverted judgment. Fearing that Samuel's sons would succeed him, the people therefore came to Samuel and pleaded that he should appoint a king over Israel, a king such as other nations had, a king to rule by decree and lead them in battle.

This was a revolutionary request! So far Israel had been a theocracy - its leaders had risen spontaneously when a crisis made it necessary. No judge had ruled the whole of Israel, each tribe had its own patriarchal government; and if uncertainties arose the leaders could go to the high priest at Shiloh and be guided by him when he consulted the Lord by means of the "urim and thummim" on the sacred breastplate, or go to a seer or "man of God." But after the death of Eli, the priesthood was in disrepute and the ark was no longer in Shiloh. The sons of Samuel were not acceptable leaders. And the Philistines were a constant menace.

Samuel was much disturbed by this demand for a king. However, the Lord said to him that the people were not really rejecting Samuel, but rejecting the Lord's more direct government. He told Samuel to give in to their request, but to tell them frankly what kind of a king they would have to expect: a king who would compel their goodliest young men to run before his chariots and serve as soldiers and as harvesters of his fields and as workmen to produce his weapons; and who would draft their daughters to be cooks and confectioners; a king who would confiscate the best of their property and take their asses for his own work and demand as taxes a tenth of their sheep and of the fruit of their labors.

But the people still insisted that they wanted a king, and be like all the nations.

---

Soon after this, some asses, belonging to Kish, a prominent Benjamite, strayed away; and he sent his son Saul to look for them. Saul and his servant went far and wide, but saw no sign of the asses. Finally, as they were well nigh exhausted, they thought to ask Samuel the seer, who was in a nearby town getting ready for a sacrifice. And Samuel, to whom the Lord revealed that this choice young man, taller than any in Israel, was to be the future king, embarrassed Saul by placing him in the chief seat at the feast. And the next day Samuel took him aside and anointed his head with oil and revealed to him his royal destiny. Saul was shown by various signs that Samuel spoke the truth. Saul was a bashful man, far from self-reliant. But it happened, as Samuel foretold, that he met a company of prophets, and the Spirit of God descended on him also, and "gave him another heart" so that he was "turned into another man." And he prophesied among the prophets. And the on-lookers exclaimed, "What has happened to the son of Kish? Is Saul also among the prophets?"

Presently Samuel called the people together and cast a lot to determine who was to become king. And the Lord's choice fell on Saul, who had modestly hidden himself among the supplies. All hailed him, with the cry, "Let the king live" - or, as we would say, "Long live the king!"
Yet Samuel impressed on the people that they had done a great wickedness in asking for a king.

And Samuel had soon reason to be discontented with the new king, who was apt to trespass on Samuel's prerogatives and - in his anxiety for the Lord's protection against the approaching Philistines - took upon himself to sacrifice in Samuel's absence and, again, to disobey the command to utterly destroy Agag, the king of the Amalekites, and annihilate both people and cattle. When Saul spared Agag as a captive and let the Israelites save the choice animals for a sacrificial feast, Samuel rebuked Saul, saying, "Has the Lord as great delight in burnt offerings and sacrifices, as in obeying the voice of the Lord? Behold, to obey is better than sacrifice, and to hearken than the fat of rams."

Saul made excuses, but Samuel declared that the Lord had rejected him. As the seer turned away Saul laid hold of Samuel's cloak, which rent. And Samuel exclaimed, "The Lord has rent the kingdom of Israel from thee this day, and has given it to a neighbor of thine, one better than thou!"

---

One who reads this story cannot help having a good deal of sympathy for Saul. For he was placed over the kingdom under almost insurmountable difficulties. He became king in name only, and only a small band of men "whose hearts God had touched" followed him home to Gibeah, his home town. And there were many who were privately contemptuous of the upstart king. But it was not long before he proved his worth. When the Ammonites beleaguered an outlying city, he commanded all Israel to come to the rescue on pain of death. And the victory which followed established Saul's authority.

But soon the Philistines again began to encroach. Saul then had only six hundred men. And except for Saul and Jonathan his son, they had no regular weapons, neither sword nor spear. For so primitive was their condition, that there was no smith in all Israel, but the people were obliged to go down to the Philistines in the valleys to sharpen their axes and farm implements; and iron tools were still scarce in those days.

The Philistines had many garrisons throughout the country. It was Jonathan who on his own initiative challenged this situation, saying,
"There is no restraint to the Lord to save by many or by few." So he and his armorbearer climbed up a steep cliff and challenged an amused garrison of Philistines, who exclaimed, "Look, the Hebrews have come forth out of their holes." Yet after Jonathan had slain twenty of the enemy the whole garrison resorted to flight. And at this Saul's men took heart, and many Hebrews who had served with the Philistines took Israel's side, and soon the whole countryside was cleared of Philistines who turned in rout towards their coastal cities. Saul now consolidated his gains, and with the help of his uncle Abner, who became the captain of his host, he soon controlled the hinterland even down to the southern deserts. But it was when he thus defeated the Amalekites in the south that he was disowned by Samuel for disobedience. And never again did Samuel see Saul.

---

It was said that every man, in some fashion, seeks to inherit the land of promise which is latent in the talents with which he is born. As he grows up, he is led on by ideals of life which differ with his age. And since all children - if they are to make something of themselves - must become civil and moral, and acquire the virtues distinctive of their age, it is these virtues which stand out as the leading factors in the formation of their minds.

At first these ideals - in childhood - are not unified or constant. Like the various judges of Israel, they rise to meet some crisis and are then soon replaced by other interests. Like the judges, such as Jephthah and Samson, they are confused with false loyalties and led to many errors, many childish tragedies. Scattered bits of instruction may lead to the formation of a spurious conscience which mistakes some popular persuasion for the voice of God. Progress towards any unity of mind, any integrated character, is impossible unless there develops a universal quality which can give a general guidance.

And in our story, this quality is described in the character of Samuel. It is Obedience.

The name Samuel can be translated "God hears," or "One who hearkens to God." In general it means Obedience. And Samuel, from childhood, was lent to the Lord, and, brought up in the service of the tabernacle, heard the voice of God as a child. He put aside his own fears and preferences, to obey the Lord. "Behold," he said, "to obey is better than sacrifice, and to hearken than the fat of rams!" He had a quality of innocence and forthrightness, a simple loyalty to the literal commands of God which is reminiscent of the best qualities of childhood.

Yet the time comes when such obedience is not enough to rule the devious ambitions which rise in the growing mind, and to meet the states which rebel and the worldly falsities which invade the understanding. This is particularly true when the states of childish trust in prayer and worship are apparently disappointed and the ark of the covenant is stolen away from the inmost center of the mind. The reliance on childish love for parents becomes weakened and the tender celestial remains of infancy fail to move the mind as formerly. The child becomes disillusioned about his childhood dreams and feels insecure when he realizes how he has been moved by one passing ideal after another and found them all full of error. The mind comes into a sophisticated state. It is tired of "judges." It wants a king! a truth that is unassailable, permanent; whose authority cannot be challenged; a ruling principle that shall dissolve all disputes, discover all wrongs, reconcile all contradictions, banish all doubts!

So it is with every normal child. And in our spiritual life, in the process of spiritual growth, it is the same. Our first enthusiasms that lead us to battle with some of our evils and cause us to do good works with a pleasing sense of merit but without much judgment, are soon found to savor of a spurious conscience, and we find that we must revise our principles from time to time. This again is like Israel's state in the days of the Judges. It is followed by the discovery of evils which hide even in the sanctuary of our faith - like the unfaithful sons of Eli who gambled away the ark of the covenant. And it is then that the only salvation lies in a new humility - a simple obedience like that of Samuel, a new repentance which marks a new spiritual childhood where innocence can be re-established.

The Writings would call such a state as is signified by Samuel, a "celestial natural" state, such as is present with children and the simple. Indeed, we may discern in all the Hebrew heroes from the period of the Judges representations of those states of religious immaturity which achieve something of reformation but fall back into disorders and mental confusion; states in which glimpses of truths about faith and charity are seen in the borrowed light of tradition, but in which the impatient passions of the natural man continue to break forth to obliterate this temporary illustration.

Samuel stands for the highest attainment of this loyalty to the traditions and doctrines of the church; a simple obedience which begins to hear the voice of God as a call to inner repentance. But simple obedience cannot forever rule the states of doubt and fear which clamor for recognition in the mind. Tradition is not enough. Truth must be invested with a greater authority, as chosen and anointed of the Lord; as a king vested with permanent powers and able to fight against assailing falsities.

Such authoritative truth cannot come from tradition, but must be seen in the Word itself. And the kings of Israel, beginning with Saul, represent such Divine truth as this is seen operating in the mind of man. In the literal sense of the Word, these kings are described as human personalities, wherein good is as it were mingled with evil, strength offset by weakness, wisdom accompanied by folly. In a proximate sense, each king represented the Divine truth as seen in a fallible human state, not as it is in itself. But in the more interior view of the angels, the evils mentioned in the Word disappear, for the angels see only the Divine purpose and the Divine law within the literal sense. Acts which appear cruel and shocking - such as the massacre of enemy populations and the polygamy practiced by Israel's kings - come to represent, in the spiritual sense, the highest justice and the greatest mercies, for they describe complete deliverance from the hells and the Lord's love for the universal church.

And the rivalry of Samuel and Saul similarly represents the fluctuations in man's concept as to what kind of truth should rule him for the best progress in spiritual life. Samuel, on the Lord's command, anointed Saul. True tradition, a true doctrine of the church, points, from a sense of duty, to the authority of the Word and helps to prepare the way for men to turn to the Word. Yet the Lord - and Samuel - regarded the demand for a king as a decline, as if it was a revolt against the government of the Lord. For in a sense, the rule of the judges was in form a superior kind of government - like that of the celestial kingdom of heaven - a government by truth seen from good. Hence it is said that one must enter into the kingdom of heaven as a child. The child accepts truth from a love of parents and masters, from the affections active at the time. But when innocence departs, the emerging evils of the proprium must be restrained and its falsities put away by sterner methods, by the facing of truth as such, seen in its own light. (@AC 8770). From the sphere of the celestial kingdom man departs into the custody of the spiritual kingdom of heaven. And the truth man first accepts is that of the natural sense of the Word; which in general is described by Saul.

== David Against Goliath

It is stated in the Writings in connection with the affairs of nations, that "in heaven there is a spiritual justice to a cause and in the world a natural justice, and that these two are conjoined by means of a connection between things past and things future, which are known to the Lord alone." (@DP 252) It therefore happens that the just cause is not always victorious in the world. Yet what happens occurs from the spiritual necessities of the case, for the ultimate best and the eternal good of all. In the Word many wars are described. The natural causes of these wars were rooted in spiritual causes - in intricate spiritual conditions in the world of spirits, where other, spiritual, issues were being fought out. The states of the minds of the people on earth, and the spiritual associations which they had with spirits of different kinds, caused them also to represent certain spiritual causes.

This is the case even now, among the various kingdoms and nations in Christendom. It is not known - and it would not profit us to know for sure - what particular nations now have the same representation as did the Philistines or Moabites or Syrians or Chaldeans with which Israel fought at one time or another. "Yet there are those that do answer to them." (@DP 251) "What the quality of the Church is on earth and what the evils are into which it falls and for which it is punished by wars, cannot at all be seen in the natural world." It is now revealed, however, what the nations mentioned in the Word represented. And it is also revealed that "when the sons of Israel, who represented the Church, departed from their commandments and statutes," they were attacked or oppressed by some nation which represented the particular evil into which they had fallen.

For this reason it is well for us to recognize the various evils and persuasions to which Israel was vulnerable. For they are the same ills that infest our spiritual life. And the circumstances under which we are liable to such infestations are clearly described in the story of Israel in human terms such as the revealed doctrine itself cannot employ except when seen refracted against the background of the literal sense of the story.

---

One nation which comes to the fore as Israel's main enemy in the time of Saul, Israel's first king, is Philistia. When the twelve tribes, after the initial victories under Joshua, settled in the land, they could only hold the strategic highlands. Under the Judges, the main roads from Egypt along the sea towards Syria were usually patrolled by Philistine mercenaries in Egyptian pay, troops often equipped with horses and chariots and weapons of iron. But in the hill country there were only occasional garrisons of Philistines with which the Hebrews could more easily cope.

In a spiritual sense, the Philistines - who were mainly seafarers and fishermen but also cattle men whose herds grazed on the fertile plains along the sea, down to the borders of Egypt - represent "the science of cognitions." This expression means the organized science of religious knowledge, which in itself is a necessary function in any living church. It is not enough to read the Word and know its teachings about faith and charity, but the church must organize these knowledges in systematic form, contrasting the truths of the church with the falsities of other beliefs.

Since the Philistines represent such a study of human knowledge about Divine things, it is mentioned in the Word that both Abraham and Isaac sojourned in the land of Philistia when their own pasture lands dried up. (@AC 2726, 3365, 3463) It is even stated that the Ancient Church at one time extended to this land which then was occupied by a different people and then signified the science of the interior things of faith. (@AC 9340) But gradually the religion of Philistia became perverted.(*)
And we find that they adopted the worship of Dag-on, whose image was represented as half man, half fish. (@DSS 23, @AE 700[22], 817: 10)

(*) Modern research indicates that the Philistines were a part of the "Sea Peoples" who settled on the Palestinian shore regions in the twelfth century B. C. after an abortive attempt to invade Egypt. But the Bible uses the name "Philistines" also for a people who seemingly were migrants from Egypt and who befriended Abram and Isaac. (Genesis 10, 21, 26)

In a decadent church, the study of faith is readily turned into an intellectual curiosity and a detached interest in other religions, with a patronizing and outwardly sympathetic view of their possible utility. The Philistines had considerable respect for the God of Israel and for the ark which they captured in battle and prudently returned when its powers became embarrassing; an attitude reminiscent of that of Quakers and of modern university professors who give extensive courses on the history of religions without committing themselves to any definite faith in any. Yet it is also possible that the study of the doctrine of faith will be used as a means of evading the obligations of charity - and that pride in one's own religion may breed contempt for others who are less equipped with the means of spiritual progress.

And this latter attitude of spiritual conceit - the reliance on faith alone with little thought of charity and tolerance - is exemplified in our story when the Philistines came up into the valley of Elah and sent their champion to challenge the forces of Israel whom Saul had gathered to oppose the invasion. This champion was a giant of more than six cubits - perhaps about ten feet tall. He was armored like a Greek, with helmet of brass, coat of mail, and shield, and with brazen greaves on his legs. He carried a spear of the size of a weaver's beam, with iron tip. And when he cried out his words of defiance, Saul and all Israel were dismayed. They felt that the Lord was no longer with them.

And in a sense this was true. The prophet Samuel had made it clear that "the Lord had repented that He had made Saul king over Israel." For Saul had not completely or literally followed the Lord's commands. He was still king. But it was made plain that his sons would never inherit the throne.

Although he was a shy and modest youth when chosen, the power of kingship had gone to Saul's head. He was given to headstrong decisions, impulsive actions. Yet he was a true representative of his people. He was the kind of man they could accept - tall, handsome, impressive, a real king in appearance.

The spiritual state which is here described is one in which the man of the church has come to mistrust tradition and has turned in something of impatience to the authority of the Word in its literal teachings as the source of strength and leadership, hoping that it will confirm his views; and hoping also for a definite end to mental confusion and what he senses as a spiritual stagnation. And this results in some initial victories. Saul - when true to his office - evidently represents the Divine truth in the literal sense of the Word; not as it is in itself, but as man sees such truth in that state. And in that state man is concerned with truth largely with a view to his intellectual satisfaction. What appeals to him is the beauty and logic of the truth. He may read about repentance, about charity and worship, about heaven and hell; but his inclination is to apply this new authoritative information in an argumentative, combative way - applying the yard-stick of truth to measure others, rather than himself. He sees only the surface of the truth. The Divine truth is ever perfect - infinite in its scope, all powerful to redeem. But man often sees it shrouded in conflicting appearances, and defends his own misconceptions, thinking that he is doing God service. Even when he reads expositions of its spiritual sense in the Writings, the real spirit of heavenly affections, the message of charity and love, may not deeply touch him.

In such a state man has no weapons with which to fight the Philistine - to resist the temptation of sinking into a reliance on "faith alone."
Too late, he recognizes how vulnerable he is, how his self-confidence has left him powerless.

---

Now we must retrace our steps, in telling the story. For there are still elements of hope in Israel. Not indeed in the camp of Saul. But Samuel - still obedient to the Lord - is preparing for the future. He goes down to Bethlehem with a horn of sacred oil. The little town of Jesse is frightened, for Samuel is known to be out of favor at the court. He is asked, "Comest thou peaceably?" And he answers that he has come to do a sacrifice. He did not come to foment rebellion or disturb the allegiance of the Bethlehemites. But secretly he takes Jesse apart and asks him to have his seven sons pass before him. Eliab, the eldest, impressed him. But the Lord told him, "Man looketh on the outward appearance, but the Lord looketh on the heart." Finally, when none was chosen, the youngest, David, was called in from the field where he kept the sheep. He was beautiful in countenance, ruddy, and strong. And at the Lord's bidding, Samuel anointed him amidst his brethren. "And the Spirit of the Lord came upon David from that day forward."

The anointing was a sign before the heavens, a rite which invited the influx of the heavens and testified to a gradual transfer of representation from Saul to David. It was not a rebellious act, but an act of succession. David, in all respects, remained, like his family, loyally subject to Saul, never lifting up his hand against the Lord's anointed. But it is interesting to note, that while Saul had been anointed when he, bewildered, was looking for his father's straying asses, David was anointed as he came in from watching his father's sheep.

David's usefulness to Saul was soon evidenced. For an evil spirit began to trouble Saul, and his servants had heard that David was a cunning player of the harp. So David was sent for and became Saul's armorbearer, and when Saul turned morose and moody, David played before him until the evil spirit departed from him.

Apparently David returned to his sheep, and Saul forgot all about him. We may well think of David, watching his flocks, with his harp and shepherd staff beside him, on the very hill slopes where, a thousand years later, other shepherds heard an angelic choir announce the birth of the Savior; think of him meditating, seeping in the simple beauty of the everlasting mountains laden with their legends; noting the hart timidly approaching the water brooks, seeing the sun, going forth rejoicing as a bridegroom from the chamber of the clouds; think of him sometimes cowering, hearing Jehovah's voice in the thunderstorm and feeling forsaken and lonely. We may also think of him defending his sheep against bear or mountain lion. For David, all was translated into music and poesy and inspired words which flowed from a heart unspoiled into cadences which untold generations have treasured as a precious heritage, unsurpassed.

Three elder sons of Jesse, in the meantime, had followed Saul to battle. And after some weeks Jesse sent David to the camp with fresh provisions for them - including ten cheeses for their captain - and to see how they fared. And - the father charged - he was to be sure to bring back a receipt! So David arrived at the battle lines where Goliath, for forty successive days, had hurled his challenge morning and night. "If any one be able to fight with me and kill me, then we will he your servants. But if I . . . kill him, then ye shall be our servants. . . ." David left his provisions with the supply keeper and looked up his brethren. To his brethren's annoyance, he hung around listening to the camp gossip. Saul, it appeared, had promised tax-free wealth and his own daughter in marriage to the man that killed Goliath.

And David, having seen the giant, went around the camp saving, "Who is this uncircumcised Philistine that he should defy the armies of the living God!" This finally came to Saul's ears, and David - having been sent for - offered to fight the Philistine. He explained that he had already, with the Lord's help, killed a lion and a bear single handed, and why not this Philistine? (@AE 781[12]) Something about the young man's spirit impressed Saul. And Saul armed David with his own armor and helmet and sword. But David put them off - for he was not used to heavy, unwieldy weapons. Instead he chose five smooth stones out of the brook, put them in his shepherd's bag, took his sling in hand and approached the cursing Philistine. "Thou comest against me with a sword and shield," David cried, "but I come to thee in the name of the Lord of hosts, the God of the armies of Israel, whom thou hast defied!" And with this David slung a stone straight at Goliath, so that it sank into his forehead and the champion fell dead upon his face.

Then the Philistines, dismayed, broke rank and fled before a victorious Israel. David took Goliath's sword, cut off his head and took his armor. And Saul, astounded, asked David whose son he was. And David replied, "The son of thy servant Jesse the Bethlehemite."

---

Many have no doubt noticed that the story of David seems like the original of many a nursery tale in which the lonely shepherd boy cuts off the head of the giant, reaps great riches, marries the princess and inherits the kingdom. But the story of David bears all the marks of history, and is told with a detail of local color which only archeologists can appreciate to the full. It even retains some of those apparent inconsistencies which a fictional account characteristically avoids.(*)

(*) Compare I Samuel 16:21f, 17:58.

Yet David's story is more than history - it is part of the Divine Word. It is, in all its details, pregnant with an internal meaning, meant for the illustration of men now and in the unending future. When examined in the light of the Writings, we find it to be a Divine drama of the development of the church and of the opening of the human mind. It reveals the secret of all spiritual victories.

The outstanding fact in the literal story is that Saul, although king in name and a warrior of repute, could win no victory over the Philistines until David entered upon the battle scene. For this we find a historical parallel in the Christian Church. For the Writings point out that when nearing its decline and consummation, the Christian Church, unfaithful to its charge, was turned into a spiritual "Philistia." (@AE 1029[18], 817:8, F 49) By this is meant that the Protestant world, where the Word was still being read, turned to the falsity of "faith alone"-the attitude in which doctrine may be studied much but life little, and the religious motive is separated from practical life and it is held that there is no need to shun evils except for ethical reasons of self-respect, but that man is saved by faith alone.

Against this false doctrine, the simple good among Christians had no defense. The Word, understood as it was only in its literal form, was full of obscurities and contradictions. The learned Philistine occupied the pulpit and the professor's chair and allowed no spiritual smiths to forge any weapons to be used in revolt. The church indeed acknowledged as its king the authority of the Bible literally understood. But because genuine doctrine was no longer available in Christendom, only a few general truths could be marshalled to oppose the tenets of "faith alone." The Divine truth of the natural sense of the Word was indeed, like Saul, king in Israel, but its power could not be exerted.

This was the reason why the spiritual freedom of the church could not be restored except through the revelation by the Lord of the spiritual sense of the Word and the giving of the doctrine of genuine truth; thus by a new revelation of spiritual truth by the Lord in His second advent. The Writings of Swedenborg - in our historical parallel - stand as a David which restores the saving power of the literal sense of the Scripture by slaying the Goliath of "faith alone." But it is also true that every man of the New Church is, spiritually speaking, a subject of King Saul before he can receive the interior doctrines of the Writings. Whether he is brought up as a Christian in ignorance of the Writings, or whether he as a child was educated within the New Church, it is of order that he should first come into the sphere of the literal sense of Scripture; and it is inevitable that he should be confused and retarded by its obscurities. Yet the Divine truth in its veiled form, as legend, history, commandment, prophecy and biography, must first be accepted as the anointed king, as the Saul who must lead in our battles.

David - the internal truth - finds its place of leadership in our lives by slow degrees. And its first mission is to restore the power to the literal sense of the Word. This is done by the humbling of that state of intellectual pride - of spiritual self-satisfaction - which is portrayed by Goliath, the giant of Gath.

Let us note that David, when he steps into the scene, did not seem to be weighed down by the problems which disheartened Saul. He came with a fresh viewpoint, a new, naive perspective. He was not concerned with the strength of the enemy, with armaments and numbers. And it is generally true - not only in mathematics but in life - that our dilemmas can usually not be solved until we transpose our problems into different terms. David had seen the hand of Omnipotence in wind and flood before which the giants of earth were puny and weak. He had seen a tiny spark kindle into a vast wildfire. He had seen tiny raindrops wearing away the hills. He had caught a lion by the beard and rescued his lamb out of its jaws. He knew that the battle was the Lord's. And were not the people of Israel like the sheep he loved - in need of a defender? David, in the Word, represents the Lord as to Divine truth. This representation adhered to him from the time of his being anointed. But in particular, he represents spiritual Divine truth, or the truth of the spiritual sense of the Word, the inner spirit of Divine revelation which teaches truth from good, as a shepherd feeds his flock.

The words of the Lord "are spirit and they are life." They have a power to lead men to truth and to the good of life whenever men are willing to see the spirit in which they are spoken. And even in simple states, men can see the life of charity as the real intent of their teachings, even if this is opposed by all the creeds of Christendom and even if the dogma stressing faith alone looms before them as a giant with a spear like a weaver's beam! A giant equipped, from the arsenals of a consummated church, with truths subtly perverted by intricate reasonings, with sharpened phrases of Scripture and with shields of tradition; and even if behind it stand the ordered cohorts of clever confirmations, row by row.

Spiritual truth - the truth men come to see in times of spiritual need and in the light of charity, love, and use - does not meet confirmation by confirmation or array one set of apparent truths to counter another, one passage of the literal sense against another! For this - in such a case - is a futile procedure. Our spiritual David instead places the simplicity of the truth against the elaborate complexities of error. He only gathers "five smooth stones from the brook."

Note that these stones were not taken from a desert or from a wall or from a stagnant pool, but from a brook. The selected stones signified truths not of the memory alone, not merely from tradition nor from a persuasive faith; but truths perceived in the Word when this is looked to as a source of living intelligence and inspiration - homely truths of common sense rounded out by experience and frequent usage; polished and cleansed by uncounted waves of Divine instruction; truths which belong to the wisdom of a good life, and are collected into the shepherd's bag which we may identify as a personal concept of charity.

Such truth is not mere sentimentality. It is militant, powerful against falsities of evil, penetrating to the very head and principle of falsity; more effective than a whole artillery of theological learning based on a literalistic and pedantic interpretation of the Word. And it cannot be reached by the sword of the Philistine.

And against such truth the enemy cannot stay to fight, but the battle resolves itself into headlong, disorderly flight and pursuit. The ancient practice of battle by chosen champions was derived from a law of the spiritual world where societies in heaven and in hell act through subject spirits into whom each society centers its influx. When an evil subject spirit is judged in the world of spirits and sent back to his associates, the hell which he represented is also punished and for a season deprived of power to act.

It is said that David took Goliath's own sword and cut off the head of the giant, and stripped his armor and put this in his tent for future use. For the armament of falsity is truth taken from the Word, and can therefore be reclaimed for better use. But the head of Goliath had to be cut off - for it represented the carefully guarded love of self, with its persuasion of godlike immunity to error.

---

One more incident throws light on the representation of David. For it is said that when Saul had talked with David, "the soul of Jonathan was knit with the soul of David, and Jonathan loved him as his own soul."
So great was Jonathan's devotion to David, who was considerably younger, that the two entered a solemn covenant of friendship. Jonathan took off his robe and garments and gave them to David together with his sword and bow and girdle. The two became inseparable friends while David was kept at the court of Saul. It is easy to see why the young prince should become so fond of David, whom he could well regard as an equal in courage, one worthy of love. Indeed, David, whose name means "Beloved," seems to have inspired both love and hero-worship. Jonathan, in the isolation which his royal station brought with it, was in need of a friend. His father was a moody man with a dangerous temper whose consciousness of weakness made him suspicious and touchy about his dignity, and was not the kind of father to invite confidences. The relations of Jonathan and his father had been strained ever since Saul had nearly put his son to death for inadvertently disobeying one of his thoughtless orders. (I Sam. 14)

But there were deeper reasons why it is said that Jonathan loved David "as his own soul." For David represents the Divine truth of the internal sense of the Word, and this is the very soul of what Jonathan represents. Saul stands for the literal sense of the Word, especially as to the obscurities and veiled truths therein which often confuse the natural mind; but Jonathan, the valiant hero of Israel, stands for that genuine truth which plainly shines out nakedly from the letter as the very essence of the Biblical teaching. Such genuine truths are compared in the Writings to the naked hands and face of a man who is otherwise robed in dark garments. It is these naked truths of salvation seen in the literal sense of the Word which at times can lead even the simple to victory over their spiritual enemies. And the simple good also prevent such open truths from being condemned; even as it was the people who rescued Jonathan from being put to death by his father for unknowingly disobeying his command. (I Sam. 14) This genuine or naked truth of the letter is indeed the form in which the spiritual sense - the essential doctrine of heaven - shines through, like the soul of man manifests itself in the face. Therefore David was, in the representative sense, as Jonathan's very soul. And for this reason it is also told that Jonathan stripped himself of the robe that was on him, and his other garments, and gave them to David!

David had refused to wear the armor of Saul; he tested it but put it off, for he could not use it in his kind of battle. But he did not refuse Jonathan's armor. The spiritual sense and its truths of love and charity receive both power and sanctity by assuming the garments which the plain, clear passages of Scripture provide for its expression. When the Writings of the Second Advent were written and the internal sense was disclosed, its doctrine was amply confirmed from genuine truths gathered from the Biblical Word. David assumed the garments and weapons of Jonathan, and was thus prepared to be acknowledged, even by Jonathan himself, as the real heir - the future king of the land. (@AE 395[5], 7)

And it is by this mode of exposition, which the Writings exemplify, that each new truth is crowned and confirmed within the church. Each spiritual truth from the revealed doctrine must be arrayed in the robes of Jonathan, confirmed by the open teachings of the literal sense of the Word, lest there be a question as to its right to legitimate succession. By Jonathan's loving consent, and eventually by Saul's own recognition, David was to become king of Israel.

== David's Flight

The Heavenly Doctrine reveals that a man cannot enter into interior or spiritual uses until he has been tested by states of temptation and anxiety. There is of course a parallel to this in every human achievement. Nothing of importance is ever accomplished without its cost in hardship, training and labor, and in mental turmoil and moments of despair.

In the Word, this is brought out with special emphasis in the story of David. And in an inmost sense the life of the Lord on earth is therein described, especially as to the temptations which the Lord suffered. These temptations are also the subject of the internal sense of the many psalms in which David pours out the anguish of his heart. But in an applied sense, the story of David inwardly describes the spiritual development of the human mind while it is being regenerated by the Lord and while its spiritual degree is being opened through a desire to perform spiritual uses of charity.

The early life of David was not especially marked by tribulations. From a shepherd boy he was - after Samuel had anointed him - briefly taken into royal favor as a minstrel at the court. Later he came into prominence as the slayer of Goliath, and lived at court as a bosom friend of Jonathan and an attendant upon king Saul. "Saul set him over the men of war" - the royal bodyguard. He was accepted in the sight of all the people and all Saul's servants. And when the army again returned victorious under his leadership, new honors were heaped upon him by the women of the towns they passed through. For these met king Saul with music and dance and as they sang they used the refrain, "Saul hath slain his thousands, and David his ten thousands!"

Then Saul's jealousy was aroused; and the next day "the evil spirit from God came upon Saul and he prophesied in the midst of the house."
And as David played his harp before him, Saul cast his javelin at him so that it stuck in the wall. David was not harmed. But the more prudently David behaved the more Saul was afraid of him, realizing now that the Lord was with David. So the king used subtlety. He married off his older daughter, Merab, after promising her to David. But he offered David the younger daughter, Michal, if he would kill a hundred Philistines. For Saul thought that surely David would perish in the attempt.

Now Michal had fallen in love with the young hero, and David fulfilled the king's conditions with eagerness. The two were married, and David's popularity rose even higher.

Saul's decision that David should be slain became an obsession. Although Jonathan made his father swear not to order his death, Saul again tried to pierce him to the wall as he was playing. And when David fled to his home, Saul sent messengers to slay him in the morning. Michal found this out and persuaded her husband to flee. She let him down through a window and laid an image - presumably an idol ("teraphim") - in the bed, and padded it with goat's hair and covered it with a cloth. To the messengers she pretended that he was sick. But Saul commanded that he be brought - bed and all; and the ruse was discovered. Michal excused herself to Saul, saying that David had threatened her. Thus David was plunged into a crucible of temptations which were to test him for more than physical prowess. He was to be tested for loyalty, patience, prudence, and endurance. He was to taste the bitterness of persecution, and of the loss of home, of wife, of friends, and of possessions.

Yet David was protected as by an invisible shield of love. In this we may see something of his spiritual representation, as it applies to man's regeneration. For he represents that spiritual truth which springs from the desire to learn the secrets of genuine charity, the love to see and to serve the real good of the neighbor and of the community. Spiritual truth is more than the mere knowledge of the doctrine of charity. It is the perception which only a love of the doctrine can give. It is based in a profound trust in the Lord.

Saul also represents truth, indeed truth which is vested with Divine authority and is acknowledged as "king" in a way that the truth called "David" is not, in the state of mind here described. The truth called "Saul" is truth such as man sees when the Word is viewed superficially, and recognized by various natural affections as confirming one's faith. In its literal sense, the Scripture contains much that is pleasing to the natural man. The letter seems to say that good works ought to be done that one may have recompense in heaven. It seems to say that the men of the Church are a chosen people, specially favored. It seems to show that God can be angry, can repent, can send evil as if in revenge. It seems to show that God can be swayed by prayers or promises. It seems to show that one must give to any one who asks, without discrimination, and that one must not resist the evil, nor judge anyone. All such teachings find a responsive chord in man's heart if they flatter his self-respect or his opinions, or if they mark out an easy escape from responsibility. He takes them as his authority and justification. Yet in other moods, he might find, in the letter of Scripture, the very opposite teachings: at least, they appear opposite, although actually they are complementary and often explanatory. And because they are not really opposite, and because they are truths in the form of human appearances, the church is warned that "in so far as they are from the literal sense of the Word" such doctrinal things are not to be denied, but explained in the light of doctrine which is formed by a comparison of passages. (@AC 3436, 9025, 7233:3) And it is made plain that "the sense of the letter, understood in simplicity, does no harm to any spiritual truth which is in heaven." (@AE 914[3])

But the concepts men form from the sense of the letter of the Word can be perverted and misused, if, instead of being understood in simplicity, the literal teachings are made the excuse for evil; and then the appearances of the letter rise up in the mind as if suspicious and jealous of the spiritual perceptions which interpret and seem to nullify the faith in these appearances and suggest that eventually a more interior concept of truth will take their place.

It is important that we recognize that in the course of a man's regeneration there arises in his mind much distress due to an unavoidable rivalry between two concepts of the truth. One is a natural concept, the other is a spiritual concept. Both are derived from Divine revelation. And this rivalry between truth and truth is what makes the very essence of those spiritual temptations which are inevitable before man as he is constituted today can be made spiritual.

It should here be understood that men can be reformed and saved without undergoing that kind of temptation. Those who are in the good of obedience, and those who are reformed by combats against obvious evils and falsities, and confirm something of religious faith without investigation, may gain a place in the entrance-courts of the kingdom of heaven without such spiritual temptations. (@AC 8974-8977) But for the establishment within man of a conscience of spiritual truth, a love of seeing and doing the things which the doctrine of charity teaches, there must precede certain apparent conflicts such as are described in the Word by the relations of Saul and David.

There is no effort made in the sacred text to disguise the faults, the narrowness and rankling envy of Saul. Despite these faults of Saul, David invested him with an almost superstitious sanctity, that of "the Lord's anointed." For quite aside from Saul's personal degeneracy, he was still king. Spiritually, he represented "truth Divine defending the church" and particularly the natural truth Divine in the literal sense as this is received within the church. David therefore never threatened the office of Saul, even as spiritual truth never acts against natural truth, but serves to inspire it.

But as was shown, natural truths from a literal view of the Word can be turned into an excuse for evil. (For instance, the description of God as angry and as giving cruel commands can be used as justification for man's cruelties.) This is represented when it is said that "an evil spirit" came upon Saul. Then David was brought to the court and played on his harp, "and Saul was refreshed and was well and the evil spirit departed from him." That harmonious music has a soothing effect even on the evil spirits which attend a man, is indicated repeatedly in the Spiritual Diary (1996 ff., 2090, 2108, 2231, 2403). But with Saul, it was not the music by itself which had this result, but the fact that David's harp signified "confession of the Divine Human from spiritual truths" (@AR 276) or from the spiritual affection of truth, which is charity. (@AE 323[12]) The reading of the literal sense in the light of heaven which is invited by such affection, restores the genuine sense and purpose of the text and removes the misapprehensions and falsities which distort it into a confirmation of evil. And it is therefore added that Saul, in the beginning, loved David greatly. But the evils of man's proprium are not easily removed or softened by the sense of harmony that is aroused when spiritual affections inflow. The evils return with greater force when the understanding of the natural man feels that his opinions and his vanity are slighted. He then impatiently sees the truths about charity and forbearance as obstacles in his path, and is filled with anger at the glaring fact that spiritual progress is impossible unless he views truths as a means of charity and love. He is unwilling to sacrifice the prestige of his former conceptions of duty, and is averse to enter upon a deeper repentance. And so, even as Saul sought to slay David with a javelin, man in desperation seeks to kill his higher and more tender perception - the perception that truth must be interpreted from charity.

The state here described is not one of confirmed evil, but of temptation. Not only are there a Saul and a David within our mind, but also a Jonathan and a Michal, who seek to protect their beloved David. Jonathan, whose love for David exceeded that of man for woman, yea, who loved him as his own soul, represents those clear and genuine truths of doctrine which shine out from the literal sense of the Word, and as it were mediate between the letter of the Word and the spiritual sense. And Michal, the younger daughter of Saul, stands for a genuine affection of truth, albeit an affection of natural origin.

It might be surprising that Michal, representing a natural affection, should become married to David who represents spiritual truth. Yet it is told us that this is the manner and mode of the heavenly marriage of good and truth within the mind. The good affection which is born from a sincere acceptance of the commandments of God in their natural sense is open to receive and cherish the spiritual truths that belong to the spiritual sense. This natural affection is in turn exalted and elevated by this conjunction, and is made spiritual. (Cf @AC 3952) Michal becomes the bride of David. And with wifely prudence she conceals his flight - letting the living David down through a window while she presents his would-be executioners with his lifeless image!

David escapes. He was actually beyond the power of Saul to hurt. For the inner essence of truth - the spirit of the truth, with its implication of charity and wise patience - escapes the comprehension of the natural man, and survives even the misinterpretations and falsities which man's evil moods marshal against it.

David escapes, offering no opposition. The perception of interior or spiritual truth does not oppose the literal truth. It does not urge to be received. It has unending patience, it awaits its time. It can do nothing unless freely accepted in the mind. Indeed, it must mature and develop its strength in secret, in the inner depths of the mind, and he formed at last into a spiritual conscience, a spiritual degree within the rational mind, before it can assert its rule over the natural man and supercede the more external conscience represented by the house of Saul.

In a sense this is true of the spiritual truths of the Word revealed as doctrine for the New Church. Such spiritual truths cannot at once supercede the natural concepts of the Christian world - concepts derived from a literal understanding of Scripture, concepts often turned as hostile arguments against the spiritual teachings of the Writings. The dragon of "faith alone," with its chilling breath, waits to devour the Heavenly Doctrine, which is therefore caught up to God in heaven, while the church is forced to flee to a secret place in the wilderness, where it will remain among a few, for a time and times and half a time. (Revelation 12) The concepts of spiritual charity cannot come into their own except by slow degrees and after many temptations. They will apparently retire - withdraw before the pressures of worldly states. They must mature in patience, and in this patience, wisdom is born.

And as with the church as a whole, so with the individual who is being regenerated. But in order to see the story of David in its application to the regenerating man, it is necessary first to review some of the teachings about the degrees of the human mind.

---

The Writings reveal that man's mind contains many levels - like the stories of a house, each with its hidden corners, its secret chambers and unconscious furnishings. First we have the Memory, the lowest degree, which we continually use in our conscious thinking, but which also contains a wealth of "forgotten" things. Then there is the Imagination, wherein we re-combine our remembered knowledge into a living imagery which pleases our shifting affections and interests, and which serves as the workshop of our arts and skills. And above this there is the Rational, the proper realm of reflective thought which - working by laws beyond our scrutiny - is occupied in analyzing and sifting our experience and our mental states and in freely choosing and formulating the abstract principles which shall rule over our lives and determine our dominant character.

Even in the light of natural experience and introspection, men can come to acknowledge these three levels of the mind - the Memory, the Imagination, and the Rational. For they belong to the natural mind which we consciously use in this world. But the Writings reveal that there are certain more interior levels or degrees within the mind which the world knows nothing of. They are described as degrees within or above the Rational.

It is in the Rational that a man's spiritual character is determined, and his rational therefore takes on new qualities when he is being reformed and regenerated. In it is formed, first of all, a conscience of what is just and right, based on the truths he accepts from the literal sense of the Word, from the general teachings of the church, and from the moral truths of society around him. From this conscience the quality of obedience to truths is gradually imposed on man's natural rational, and it becomes a plane into which the good spirits of the lowest or natural heaven can inflow with various delights.

The interiors of the Rational are, however, not opened except through the spiritual truths of the internal sense of the Word, and by the new love of uses which the Writings variously describe as "love to the neighbor from love to the Lord," or "charity," or "spiritual love," or as the "spiritual affection of truth." Spiritual truths can of course be known to any one, in the form of revealed statements in the Writings. But a conscience of spiritual truth is built up only when there is forgetfulness of self. It is built up within the Rational as it were in secret, as a new will, a new motivation on which man scarcely reflects. "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh or whither it goeth; so is every one that is born of the spirit." (John 3:8) The kingdom of God - the spiritual degree of the mind - is like seed which springs up, "man knoweth not how." (Mark 4:27)

We are therefore told that a regenerating man is not conscious, not aware, of the opening of the spiritual mind, the spiritual rational, within him. (@DLW 252) And we are also instructed that when the evils and falsities of the natural mind muster up natural conceptions of truth into their service, and the state of the natural rational is shaken by evil spheres, then "the spiritual mind contracts itself" - draws back - "as a fibril of the body does at the touch of a sharp point." (@AE 739[3])

---

It is this retreat of the tender and sensitive perceptions of spiritual charity before the aggressions of a disorderly world, that is described by David's flight from Saul. Such perceptions withdraw into the depths of the mind - beyond thought and reflection, into the realm of other "remains" of more infantile or childish good which in a sphere of innocence are also preserved, as it were awaiting a future opportunity when the mind has fought out its more external issues and has returned into a less callous state, when love and enlightenment can perhaps come into their own.

And where, then, should David flee, if not to Samuel, his spiritual father, who dwelt in Ramah with a company of prophets. For Samuel had himself withdrawn from the political life of the kingdom, although still exercising a deep religious influence. It may have occurred to David that he also would do well to give up the cares and perils of a public career which he had never really sought, and "devote himself with his musical and poetical gifts to the prophetical office."(*)

(*) Cited from A. P. Stanley, The Jewish Church, New York 1871, vol. 2, page 65.

But Saul gave him no choice. He sent his agents up to take David. Yet now there intervened one of those strange happenings which could only take place in an oriental or primitive society. The messengers of Saul, when they saw the company of prophets prophesying, Samuel at their head, were themselves seized with prophetic rapture. This happened with three successive groups of Saul's guards. And when, in anger, Saul himself arrived, the Spirit of God came upon him also, and he stripped himself and lay down naked for a day and a night! Perhaps we shall never understand exactly what was meant by this kind of "prophesying" to which Saul was especially prone. Undoubtedly it was a form of bodily obsession by spirits who compelled their subjects to act out in a symbolic drama a prediction of the future or a representation of some spiritual state. In Saul's case, he was compelled to strip off his royal garments, to signify that his royal powers, to which he was clinging jealously long after his usefulness had passed, were to be taken from him. His humiliation was complete - and the proverb ran the rounds in Israel, "Is Saul also among the prophets?"

But in his spiritual representation as truth from the literal sense of the Word, Saul could not refuse to testify of the spiritual truth Divine which is its inner message, and strip off those garments of appearances which seem at times to oppose the Spirit which compelled its writing.

David, who represented the truth which man acquires from a spiritual affection by the opening of the spiritual degree of his conscience, was truly inviolate. For such truth finds sanctuary in the holy places of the mind where evil cannot penetrate. "He that dwelleth in the secret place of the Most High shall abide under the shadow of Omnipotence," wrote David in his psalter. "In time of trouble shall he hide me in His pavilion, in the secret of His tabernacle shall He hide me." Of those that fear the Lord he wrote: "Thou shalt hide them in the secret of Thy presence from the pride of man. Thou shalt keep them secretly in a pavilion from the strife of tongues." (Psalms 91:1, 27:5, 31:20) The conscious thought of man, with the clamor of worldly states such as affect the natural rational, cannot invade the interiors of the rational mind - the lodging place of remains, the spiritual degree of the mind. Neither can man measure the discretely interior good and truth, the spiritual love and wisdom, which are stored up in his spiritual mind. All this is hidden "from the pride of man."

---

But it was not intended that the remains of good and truth, and the truths of spiritual conscience, should have no influx into the natural mind. And we therefore read that David secretly sought out Jonathan, as an intermediary, to determine Saul's intentions. For strange to say, the king in his heart had a love and respect for David which his obsessive jealousy and violent spells of madness at times drowned out. Like many oriental despots, he expected obedience even from those whom he had openly marked for death. And we find that for the feast of the new moon, Saul reserved a place at his table for David, beside Jonathan and Abner. Knowing no doubt that Jonathan had seen David, he marked with displeasure that David's place was empty two days in succession although he was in the neighborhood. When Jonathan makes excuses for David, Saul accuses his son: "I know that thou hast chosen the son of Jesse to thine own confusion ... As long as he lives ... thou shalt not be established, nor thy kingdom ..." And when Jonathan refuses to betray David, the king casts a javelin at him.

Then Jonathan, by the strange, symbolic method of shooting an arrow beyond the lad who attended to his weapons, signals David that the king has decided on his death. It is because of Jonathan's representation as the genuine truth of doctrine, that he is so often associated with the mention of a bow and arrows. (Cf. 2 Samuel 1:22) Jonathan and David then say a tearful farewell, Jonathan having made a covenant of friendship with the house of David, whom he recognized as Saul's successor. And so David starts upon his life as a hunted outlaw - to hide in the mountains. His adventures describe the further temptations by which the regenerating man must gain in strength and wisdom. For at length David must conquer Saul by a power mightier than the sword - overcome the very heart of the soul-sick king by the power of loyalty, of forgiveness, of generous and self-effacing charity.

== David As Outlaw

The life of a political refugee has always been difficult. This is well illustrated in the history of David while he was evading his persecutor, King Saul.

When Jonathan had at last convinced David that Saul would not relent, it was not possible for David to seek refuge with Samuel. Instead, alone and without plans, he looked for sanctuary at Nob, where the tabernacle of Israel stood at this time. It seems to have been a small village situated, on the Mount of Olives. Some eighty-five priests "wearing the linen ephod" lived there, under the charge of Ahimelech. David had neither food nor weapons and was faint and famished. He pretended to be on a secret errand for the king; but Ahimelech was surprised that he had arrived without a retinue, although David made out that his young men were stationed at some distance.

David asked for five loaves of bread - as many as the Lord later had to bless and feed a multitude of five thousand. But Ahimelech the priest had only hallowed bread, which had just been taken from the altar of shewbreads to be replaced by fresh. David persuaded the priest to give this to him, arguing that his young men had clean - and as it were holy
- vessels to keep it in.(*) He also asked if the priest could furnish him with a spear or sword, for he had left in such a hurry. Ahimelech had none, except the sword of Goliath of Gath, which was kept there as a holy relic. David exclaimed, "There is none like that! Give it to me!"

(*) The shewbread was meant only for the priests. But David pleaded an emergency. Even so the Lord (Matthew 12:4) defended David's action-to show that a spiritual conscience is not bound blindly by external regulations, which indeed must give way before spiritual necessities.

He then set out over the mountains, and sought service with Achish, the king of the Philistine city of Gath. But when recognized as the slayer of Goliath, the Philistines distrusted him, even though they knew that his own land had disowned him. David was afraid, and to save his life he began to act as if insane, scratching on the doors with his fingers and drooling into his beard; until Achish sent him away as a madman. David's stratagem was successful, because primitive peoples usually feel that a madman, like a prophet, was under the special protection of the gods.

Already, David's family at Bethlehem were feeling insecure because of Saul's anger against David. David therefore decided to use a cavern not far from Bethlehem - the cave of Adullam - as a refuge for his clan. Not only his brothers, but probably also his nephews, Amasa, and the sons of Zeruiah (Abishai and Joab), joined him, but gradually there were gathered into his band about four hundred men - men out of favor with Saul, debtors and distressed or discontented men whose only recourse was to live outside the law. At least one Hittite, and probably other foreign exiles, joined the band. For the time being he sent his parents to be under the protection of the king of Moab. And after a time a prophet named Gad, later called "David's seer," warned him to depart further into the land of Judah. For Doeg, an Edomite servant of Saul, had reported David's visit to the tabernacle at Nob, and Saul in his despotic rage called the innocent priests to his court and, listening to no reason, massacred them all for having assisted David. The town of Nob was raided and all, women and children and even cattle and sheep, were put to the sword. Only one young priest, Abiathar, escaped to David with the terrible news.

Abiathar arrived with an ephod in his hand. This was a special blessing; for through the priestly ephod it was customary to "enquire of God." How this inquiry was conducted is uncertain. But in the case of the ephod of the high priest, the method is given. For this ephod had a golden breastplate, set with precious stones engraved with the names - or initials - of the twelve tribes. And the high priest received answers from God by watching how the lights flashed in the various stones. The Writings show that the truths of the Word in its ultimates similarly give answers to the inquiring soul who consults them from an affection of the heart. (@AC 3862, 9905).

By means of the ephod, David was encouraged to go to the rescue of the small town of Keilah which the Philistines had raided; and when he had restored the stolen cattle he abode there for a time. But the ephod also revealed that Saul was on the way to take him and that he must not trust the people of Keilah to help him. And so David and his band of six hundred roamed from one mountain stronghold to another. Once, in a wood in the Judean wilderness, Jonathan came to meet him, renewing their covenant and saying enthusiastically. "Thou shalt be king over Israel and I shall be next unto thee."

At another time, Saul took three thousand men intending to catch David's band "upon the rocks of the wild goats." There Saul laid down to sleep in a cavern, not knowing that David and his men were in a side-shaft of the cave. The outlaws urged David to do away with his enemy, thus delivered into his hands. But David stayed his men and was content to steal in and cut off the hem of Saul's robe. Even this act smote his conscience. And as Saul was leaving, David called to him, "My lord the king!" and bowed his face to the earth. He proclaimed his innocence and displayed the piece of robe to prove that his hand would never be lifted against his king.

Saul was overcome with remorse. "Is this thy voice, my son David?"
Weeping, he continued, "Thou art more just than I. For thou hast rewarded me good, where I have rewarded thee evil ... And now behold, I know well that thou shalt surely be king ... Swear now therefore unto me that thou wilt not cut off my seed after me..."

David swore, and thus they parted, David returning to his stronghold at Engedi. There is no other instance in the Old Testament, except that of Joseph's forgiving his brethren, of the celestial law which the Lord announced in the sermon on the Mount: "Resist not the evil." "Love your enemies ... do good to them that hate you." The reason is that David represents the truths of charity which build a spiritual conscience; build it during states of spiritual temptation when the natural man, fortified by misunderstandings and prejudices from the sense of the letter of the Word, alienates itself and hardens its heart against the truth of charity.

It is well that the New Church reader of the Word, as he reads, in the books of Samuel and in many of the Psalms, of David's life as a fugitive, should at the same time think of the inner meaning, with the general acknowledgment that it is his own temptations and struggles of spirit, his own problems of spiritual life, that are here spoken of. When a man's natural feelings, his unruly moods of envy or retaliation, lust or covetousness, love of worldly mastery or wounded vanity, are upon him, the things of spiritual charity and perception are banished and starved. The ordinary consolations of an orderly pious life are denied him. He feels homeless and alone. His spiritual perceptions hunger for hallowed bread even if he is not in an orderly state to receive it. Like David, a staggering fugitive, pleading for the shewbread, man's spirit prays for an inner sustenance of good intentions which his natural man - in its present state - would not allow.

And knowing not where to turn, the "David" within man seeks refuge in simple states not of the church - only to be dismissed as a madman, like David at Gath. For, as the epistle reads, "the natural man receiveth not the things of the spirit of God; for they are foolishness unto him; neither can he know them, for they are spiritually discerned." (I Corinthians 2:14).

It is significant that one of David's strongholds was the cave of Adullam - a name which means "the justice of the people." It was here that those in distress gathered about him, in a refuge of a higher justice which human laws would not recognize. What is this justice, but that which judges not of acts but of intentions, judges not from the letter of the law but from the spirit of charity; and which is capable of forgiveness, watching for opportunities to show mercy and compassion?

And David found opportunity to show Saul his real intentions. The spiritual mind strives to overcome the resistance of the natural man not by compulsion but by kindness - by the power of sincerity and love. And the natural mind, kept in turmoil by its conflicting emotions and the contradictory appearances which confront it, can be reduced into correspondence with the spiritual only when it has become wearied with the hardships imposed by its own illusive ambitions. At times, the things of this world lose their importance, and the natural mind falls as it were "asleep," like Saul in the cave at Engedi, in the wilderness of Judah near the Dead Sea - the same wilderness where the Lord was tempted forty days and nights. When the natural man becomes less assertive, the spiritual mind can inflow and cut off for its own use certain ultimate truths, truths from the Word prophetic of the fact that eventually all truths of man's natural understanding shall be at the disposal of spiritual faith! David cuts off a hem of Saul's royal robe. Yet the spiritual leaves the natural free, free to fight on against the external foes which it also can recognize.

And is this not what the doctrine states? "The spiritual mind acts into the natural mind from above or within, and removes the things which there react, and adapts to itself those things which act in harmony with itself; so that the excessive reaction (or opposition) is successively removed." (@DLW 263).

---

But although David, by his gestures of generosity, seemed to have moved Saul to tears of contrition, he knew Saul too well to rely on his fickle promises. Samuel had died. David and his outlaws moved into the south, still within the district of his own clan - Judah. It would be a mistake to think that outlaws, in those days, were criminals or robbers. Rather may we think of David's band as similar to Robin Hood's forest fighters who controlled a district as benevolent guardians against the marauders or robbers which were a constant menace in such desperate times; or as frontier police who in exchange for their services received and sometimes demanded a tribute from the farmers whom they protected.

So we find David sending word to Nabal, a wealthy rancher in nearby Carmel, politely suggesting that Nabal could spare something of his produce for services rendered. It was just at sheep-shearing time, and
- as they put it - they "came in a good day." But Nabal - whose name literally means "fool" - was a churlish, greedy man with such a temper that even his own people could scarcely talk to him. He not only refused to give anything to David's messenger but broke out into vilest abuse, calling David a runaway slave. Hearing this, David said nothing, but armed four hundred men.

But Nabal's servants became offended and anxious and told what had happened to Abigail, Nabal's intelligent and beautiful wife. The servants testified that David's men had been a wall unto them night and day and that they had never lost a sheep or anything else while David's men were in the district. So Abigail hurriedly loaded large supplies upon asses - bread and wine, meat and corn, raisins and figs - and was just in time to meet David and his men as they approached. She fell on her face before David and took the blame upon herself, intimating that her husband was always acting foolishly, anyhow, and that she herself had not known of David's messengers. She spoke so eloquently that David's wrath was turned utterly away and he received her offerings, blessing her for withholding him from shedding blood.

So she returned to her home. Nabal was holding a feast in his house, like the feast of a king. He was drunken. But in the morning she told him how she had averted David's wrath. And his heart turned to stone with fright and he died of the stroke ten days later. Soon thereafter David paid a visit to her, and with an extraordinary humility she consented to be his wife. He also married another woman. But Saul had given Michal, David's first wife, to another man.

The spiritual meaning of this story may seem obscure. Yet it seems to describe the activities of man's spiritual conscience in the field of the natural man. The spiritual man protects those things in the mind which, like true spiritual shepherds, teach truths and lead to the good of life. The season of shearing the sheep means the time when these states should yield their true use - and pay their tribute to the spiritual ends in life. For unless the good in the natural man acknowledges its indebtedness to spiritual truth it becomes inspired by the love of self - becomes, like Nabal, churlish and greedy and self-indulgent, and insolent to the interior truths signified by David. Indeed, the thought that springs from such merely natural good is spiritually dead - paralyzed with its own fears. It is falsity that denies everything spiritual.

But the prudent Abigail represents an affection which cannot be conjoined with the falsity of self love, but which longs to offer the best that natural life can produce for the service of spiritual ends of charity and love. And such affection can be uplifted by spiritual truth into a marriage.

Let us note that there are many such natural affections which are conjoined with the truths of a spiritual conscience. The polygamic habits of the Israelites are often used in the Word as symbols of these continual conjunctions of thoughts and affections which in their combined effect make a marriage of will and understanding in the spiritual mind.

---

As David had anticipated, Saul again took an army of chosen men to corner David's band. And again, David crept up into the midst of the camp of Saul and stole Saul's spear and water cruse, while a deep sleep from the Lord had fallen on the whole camp. David restrained Abishai, his sole companion, from harming the king, saying that his time would come when the Lord decided. Then David called down from a high hill nearby, chiding Abner, the king's captain, for not better protecting his master. To Saul he cried out, "What have I done? ... For the king of Israel is come but to seek out a flea, as when one hunts a partridge in the mountains." Then said Saul, "I have sinned. Return, my son David: for I will no more do thee harm, because my soul was precious in thine eyes this day: behold, I have played the fool, and have erred exceedingly." Thus Saul was finally disarmed by David's charity; after which David returned the king's spear - to be used for more profitable battles.

---

But in a troubled mind, dominated by natural thoughts, there is as yet no real welcome, no inheritance or home, for spiritual perceptions of truth. This, in an eminent sense, was true of the Lord who said, "Foxes have holes and the birds of the heavens have nests, but the Son of Man hath not where to lay His head." And note how many of David's psalms breathe this nostalgic longing for safety and rest, for a safe lodging.

Yet it is the Lord's own provision that the spiritual mind shall be formed as an unconscious plane - deeply within the mind; so that it rests only lightly on natural ideas and comes into the range of our consciousness only through the interior natural which is our memory of abstractions and of rational or doctrinal ideas. (@AC 5094, @SE 3258, 3265, @AC 6226) And we are even told that spirits who correspond to this inner realm of the memory "wander about in bands" - even as did the followers of David. (@AC 2491)

It is also revealed - in a remarkable passage - that it is in the interiors of this interior natural that those things are held which are called spiritual. "And the spiritual things in it are those which are from the light of heaven, from which light are illuminated the things that are from the light of the world and are properly called natural. In the spiritual things there are stored up truths adjoined to good."
These are indeed the things that are signified by "David" in our story. But the passage continues: "The spiritual things there are what corresponds to the angelic societies that are of the Second Heaven, with which man communicates by remains." Should we be surprised then that David was allowed to eat the hallowed shewbread from the Holy Place of the tabernacle, a part which corresponds to the Second Heaven? (I Sam. 21) And the teaching goes on:
"This is the heaven which is opened when man is regenerated, but is closed when he does not suffer himself to be regenerated: for remains, or truths and goods stored up in the interiors, are nothing else than correspondences with the societies of that heaven." (@AC 5344)

The spiritual mind is opened primarily by man's abstaining from doing evils because they are contrary to the Divine commandments. But the formation of the spiritual mind, or of the conscience of spiritual truth, is said to take place when genuine truths from the Word are drawn from the memory and purified by the Lord, thus separated from falsities. These genuine truths are then elevated by the Lord in a wonderful manner and in the process they become spiritual, and are not any more in a natural form but in a spiritual form, such as those in the spiritual sense of the Word, and are disposed into a heavenly order. (@AE 790)

Usually people have the belief that there is no "thought" except conscious thought - that is, that the only thought possible to man is that succession of ideas of which a man is aware in his imagination. Some indeed admit that there can be "imageless" or abstruse thinking. And there are many psychologists who maintain that there is a "subconscious intellection" by which men can solve difficult problems in their dreams or in hypnotic sleep. But the Writings are far more definite. They teach repeatedly that there is thinking going on in man of which he knows nothing! And with the regenerating man, this thinking goes on in the spiritual degree of his mind. "So long as man is living in the world, he is wholly ignorant of what he thinks in the spiritual mind; he knows only what he thinks in the natural from that mind." (@AE 790[8], 625) For when a truth is elevated into the spiritual mind, it as it were "vanishes from his external memory" - that is, from his consciousness -
"and passes into the internal one," and then it becomes spontaneous and as if innate. (@AC 3108, 9918) While "the truths of faith in the natural come to manifest perception ... it is not so with those which are thought in the internal man." For "spiritual ideas cannot be comprehended in the natural, since they are intellectual ideas which are without such objects as are in the material world; nevertheless, those spiritual ideas (which are proper to the internal man) do flow into natural ideas ... and produce and make them; which is effected by correspondences ..." (@AC 10237, cf 4104:2) And this communication by correspondences "is perceived in the understanding only by this, that truths are seen in light, and ... in the will only by this, that uses are performed from affection." (@DLW 252)

---

It is this manifestation of the evasive and inexpressible perceptions of spiritual truth by an influx into the natural mind, that is signified by David occasionally emerging from his hiding places and meeting with Jonathan, Saul, and others. So also, the strange fact that David and his men now settled in the city of Gath, among the Philistines, and his pretense of warring against Israel when he actually went on a raid against the Amalekites whom he utterly destroyed so that no human being was left to tell the tale. The spiritual sense here describes how spiritual truth -- in certain states
- seems to take the side of falsity when its real purpose and effect are to eradicate certain evils which spring from falsities.

The state here described is one of spiritual confusion. Achish, the king of Gath gathered an army against Saul, who was afraid because, when he enquired of the Lord, "the Lord answered him not, neither by dreams, nor by Urim, nor by prophets."

Saul had himself put away all wizards out of the land. Yet in his desperation on the eve of an unavoidable battle - he now hunted up a woman who had a familiar spirit, and went to her in disguise, by night. To her he said, "Divine unto me by the familiar spirit, and bring me up whom I shall name." Finally the woman complied, and was told to bring up Samuel; for he wanted to have the counsel of Samuel, dead, though he had not heeded the voice of the prophet when he was alive.

The woman, when she saw Samuel, cried out, realizing that her visitor was Saul. The king asked her to describe what she saw, and she replied,
"I saw gods ascending out of the earth." She saw an old man, covered with a mantle. And as Saul cast himself to the earth, he heard the voice of the prophet: "Why has thou disquieted me, to bring me up?"

As a living prophet, Samuel represented the Word. But the dead letter - when approached through unlawful modes - can only prophesy death. The letter, apart from the spirit, killeth. (2 Corinthians 3:6) Samuel could only predict that Israel would be defeated. "Tomorrow thou and thy sons will be with me."

The Philistines, in the meantime, had wisely objected to David's participation in their war against Saul, although king Achish still trusted David as he would "an angel of God." So David turned back, just in time to find that Ziklag, the city which king Achish had given David for a present, had been sacked and burned by Amalekite raiders who had also carried off the women and children, including both David's wives. By an Egyptian servant who was found nearly famished in the desert, David was directed in his pursuit and caught the raiding party feasting, and so after a bloody battle recovered the abducted families, the stolen cattle, and all the rich loot from many towns of Philistia and Judah. Even those of David's men who had guarded the supplies were given an even share of the spoil. And not only so. But David sent presents of the spoil to all the elders of Judah, and to all places where he and his men had been wont to haunt.

But a more tragic story was enacted on Mount Gilboa. For there the Philistines defeated Israel and slew Jonathan and two other of Saul's sons. And Saul was sorely wounded by the archers and when his armorbearer refused to give him a death blow he fell on his own sword. The army of Saul was cut to pieces, and the Israelites fled from all the towns round about. On the morrow the Philistines cut off Saul's head and nailed his body to the city wall of Bethshan. But some valiant men took down his body and buried him and his sons in Jabesh of Gilead.

The death of Saul signified the end of man's reliance on the appearances which he finds in the literal sense of the Word to bolster the courage of his fickle proprium, apparent truths turned to flatter or comfort his self-esteem. Such appearances have been seized upon by Christians to excuse the claims of papacy to power over the souls of men, to justify the cruelties of the Inquisition, and to inculcate the fallacy that man is saved by human merits. And in the Reformation, which reacted against this error, other appearances from the literal sense were seized upon. Charity was renounced as a factor in salvation, and the Christian Church became vulnerable and succumbed to the Philistine falsity of "salvation by faith alone."

And as Reformed Christendom degenerated, and the Word became a closed book which no longer yielded the answers to the problems of spiritual life - the power and authority of its literal sense perished, in the minds of men, like Saul, by his own hand. And soon the genuine truths shining out from the Scriptures became extinct in the Christian world, even as Jonathan, the sworn friend of David, perished on Mount Gilboa.

The house of Saul was doomed to extinction. But the genuine truth which the Divine Word contains was indeed restored, in a new and spiritual form. It was restored not through human illustration but by a new Divine revelation which disclosed the spiritual sense of the Scriptures. The fall of Saul paved the way for the crowning of David. And in the supreme sense, David therefore represents the Divine Human of the Lord, revealed at His second advent, coming with the authority and power of Divine truth in all its forms, to restore the kingdom of the Lord.

== David Becomes King

In the inmost sense of the Word, David represents the Lord who was to come on earth to subjugate the hells and to glorify His Human, and thus found the kingdom of God among men. The Lord Himself confirmed this prophetic function of David when He opened the Scriptures to His disciples and showed them that in His life had been fulfilled all the things which were written concerning Him, "in the law of Moses, and in the Prophets and in the Psalms" - the Psalms of David. (Luke 24:44) The period of David's life when he was fleeing before Saul and persecuted as an outlaw, especially describes, in correspondential language and word-pictures, the many temptations which the Lord sustained throughout His abode on earth.

Yet we should understand that the Lord's state which on earth was not represented only by David, but by all the characters mentioned - Saul and Samuel, Jonathan and Joab, - all the other persons who play a good or an evil role in the Divine drama of Israel. For the Lord, in His very Person, had assumed the human heredities, the tendencies and infirmities, of the whole Jewish race. The representative story of Israel depicts how these hereditary human elements transmitted through Mary the mother were ordered and overcome by the Divine Soul from Jehovah God which labored to express its infinite potentialities within Him. Even David did not always represent something entirely Divine. So far as he acted as the Lord's anointed, so far He represented the Divine Human. But when David departed from the Lord's commandments, he reflected the evils and the falsities which lurked as slumbering tendencies within His assumed human, the infirm human from Mary. The evils, the cruelties and intrigues, the lusts and hatreds and envies and violent crimes, which the Word in its letter so frankly describes, are the evils and falsities which the Lord discovered when examining His human heredity; and naturally they were the very evils which had been committed in the course of Israel's history and which had been described in the Word.

---

But it is not proposed that we follow David's story, as it mirrors the course of the Lord's glorification. Instead let us remind ourselves that in the process of man's regeneration, and in the development of the Church, there are successive states which develop much like the life of Israel under the first three kings. As was noted in a previous chapter, there is even a historical parallel ready at hand. For King Saul represents the literal sense of the Scripture, such as it was understood in the declining ages of the Christian Church, when spiritual truths - the truths of the internal sense of the Word, thus the truths of charity - were outlawed by the official creeds and had to exist precariously as fugitives, like David when fleeing before Saul. But in the Heavenly Doctrine revealed after the last judgment, David has become king. Spiritual truth has come into its own, and is ready to claim its authority in the Church.

---

The Second Book of Samuel opens with a strange episode of retribution. David had come back to his ravaged town of Ziklag after recovering rich booty from the Amalekite marauders. And a man came to him out of Saul's scattered army and gave him Saul's crown and armlet, boasting that he had, at Saul's request, given the wounded king his deathblow. This man, who confessed that he was an Amalekite who had happened to pass over the battlefield on Mount Gilboa, expected to be rewarded for his tidings. Instead, David, ignorant that the Amalekite was lying (since Saul took his own life), ordered the man to be slain for daring "to stretch forth his hand to destroy the Lord's anointed." (@AC 8607, 8593f)

The Writings reveal that the Amalekites - jackals of the desert who never left Israel in peace - represent evil genii who attack men's spirits in their weakest moments, by suggesting persuasive falsities which accord with interior evils of which man is not aware. But David was not open to the subtle temptation of rejoicing over the death of Saul. He ordered that the Amalekite be slain. Then he rent his clothes and fasted and mourned for Saul and Jonathan and for the Lord's people slain on Mount Gilboa.

And in his lament he taught Israel some phrases from the Song of the Bow, which was written in the ancient Book of Jasher: "How are the mighty fallen, and the weapons of war perished!" There is no trace of recrimination in his elegy. So far as David was concerned, Saul's faults had been wiped out by his heroic death.

"The beauty of Israel is slain upon thy high places: how are the mighty fallen! ... Ye mountains of Gilboa, let no dew or rain be upon you, nor fields of offerings, for there the shield of the mighty is vilely cast away, the shield of Saul as though not anointed ... The bow of Jonathan turned not back, and the sword of Saul returned not empty. Saul and Jonathan were lovely and pleasant in their lives, and in their death they were not divided: They were swifter than eagles, they were stronger than lions ... I am distressed for thee, my brother Jonathan:... thy love to me was wonderful, passing the love of women. How are the mighty fallen, and the weapons of war perished!"

To the listening angels, this was the testimony of the spiritual sense of the Word to the virtue and power of the sense of the letter of the Word, and to the doctrine of genuine truth which can be drawn from it. The spirit of the Word feels no rivalry from its letter. Nor does the letter perish, even when it is understood in a spiritual sense. The death of Saul was a resurrection - and the representation he had carried was now added and transferred to David, to be carried on by him.

Therefore we find that the men of Judah now came and brought David to Hebron and anointed him king over the house of Judah, his own tribe. In the course of man's regeneration, the time comes when spiritual truth, perceived in the depths of the mind, kindles within him the beginnings of a new will born in the understanding as a confession of the Lord. This is a spiritual love - a love of uses for the sake of charity - a love which actually opens the spiritual degree of the mind and by degrees forms and infils it, so that it may become a power, a motive power in the whole mind, to reorder the natural mind for new uses and fill it with new affections; for it is so that man's natural mind also can be born again.

Yet the natural mind is full of complex states. Even our religious life is far from pure. Although we may have a sincere acknowledgment of the Heavenly Doctrine as the ruling authority in our thought, we sometimes show this allegiance in the strangest ways. For our proprium sometimes curries favor with our forming conscience - like the Amalekite, who brought Saul's crown to David. Our natural affections, which contain so much of self-love and corporeal delights, act on the principle that the end justifies evil means, and begin to enforce the dictates of our conscience by wrong methods, by violence. And our affections also war against each other, not for the sake of spiritual justice but to dominate one over the other. For as long as there are sensual affections left active in our mind, evil spirits can stir up continual dissenting states and deceitful lusts and impulses.

Nor does our first confession of the Lord - our crowning of the Heavenly Doctrine with Divine authority - at once convert our whole understanding to its service! Therefore it is told that although David sent messengers to some of Saul's supporters to gain their confidence, yet Abner - Saul's uncle and the captain of Saul's host - instead proclaimed Saul's remaining son as king over Israel. The name of this man was Ishbosheth, which literally means "a man of shame"! Despite this strange name, he ruled for two years over Gilead and Benjamin, Ephraim and the northern tribes. When Abner and his men met Joab, David's captain, at a pool near the border of Judah, Abner suggested that the young men should "play together" -that is, in individual matched combats. This ended by twelve of each side killing each other. But this game of war then resolved itself into a general battle in which Abner and the men of Israel were beaten and fled. The warriors of Judah pursued, and Asahel, Joab's brother, persisted in following Abner until Abner smote him dead.

Thus it was that an undeclared war developed between the house of Saul and the house of David. Gradually David's party became stronger. And when Abner was rebuked by Ishbosheth for taking one of Saul's concubines, Abner in his anger sent word to David that he was ready to hand Israel over to David. In accepting this offer, David's only condition was that Ishbosheth return Michal, David's first wife, whom Saul had later married to another. And the helpless Ishbosheth sent and took her from her second husband, who followed weeping behind her. The humiliation of Saul's house was complete.

Abner, having advised the transfer of Israel's allegiance, then visited David at Hebron with twenty men, and was received with honor and was ready to be sent away in peace. But Joab, hearing of this, and thirsting for revenge against Abner who had killed his brother Asahel, took Abner aside to speak to him in the gate at Hebron, and murdered him there in cold blood.

David was horror-stricken, but by lauding Abner and blaming Joab alone, he made it plain to Israel that he as king had had no part in the slaying. And it was also understood that the king - in those times - could hardly interfere in a private feud, especially when it concerned so powerful a man as Joab.

Saul's house - Ishbosheth, and Abner his captain - all represent the natural understanding, which is slow to accept the rule of spiritual truth, because it thinks in terms of this world, and adheres to ideas of space and time and person. But spiritual thought, such as was represented by David, has no intention to destroy natural thought which is useful in its own field of natural uses and in the relation of man to man in the community. Nor does a spiritual conscience act violently. It destroys only evils. It does not kill rebellious or immature thoughts. It conquers by love and inflows as a higher motivation, leading gently, and strengthening those affections and. ideas in the understanding which are willing to perceive a deeper meaning in life.

David had dealt lightly with Saul's house. Others were more revengeful. Thinking that they were pleasing David, two Gibeonites assassinated Ishbosheth and brought his head to David at Hebron. In horror, David ordered the misguided partisans slain. For a spiritual conscience cannot condone those natural affections which would use evil means to promote the cause of the Church.

Eventually the elders of all the tribes came to David and anointed him king of all Israel. His power was now complete. And one of his first acts was to capture Jerusalem from the Jebusites. He raised a fort on Mt. Zion, and around it an important city was soon formed on its northern slopes. To him and his people, it was "beautiful in situation, the joy of the whole earth," with its towers and bulwarks. In a sense, it was the first strategically located city of Israel which could hold out against real attack. And Hiram, king of Tyre, sent expert masons and carpenters to David and supplied cedar wood for a real palace. David also acquired a harem of many wives and had very many sons and daughters.

But the safety of Jerusalem was not assured at once. For the Philistines came up twice to be defeated in the valley of Rephaim. This place was close to Bethlehem, David's home town. And while he and his men were besieged in his old stronghold, the cave of Adullam, David spoke longingly in reminiscence, wishing that he could drink once again of the water of the well by the city gate of Bethlehem. Three of his warriors then broke through the ranks of the Philistine host, and at the risk of their lives brought him a cruse of that water. David was so touched by this testimony of their love that he refused to drink it, but poured it out as an offering to the Lord. (II Samuel 5:18 ff, 23:13 ff)

The conscience of spiritual truth - or of charity - is slow to develop. Yet even with those who are ignorant of the doctrine of heaven, but who read the Scripture from an affection of charity, the goods and truths of the spiritual sense - which are as yet like fugitives from the natural man - are unconsciously inscribed interiorly upon their will and understanding, albeit they cannot articulate the thoughts that move within their spirit. Such must wait until after death to recognize the genuine truths of spiritual doctrine.

But it was not the Lord's will that the progress of men into the light of the internal sense of the Word should be delayed until after they have died! By His second advent the Lord has revealed the doctrine of heaven which shall make possible the establishment and ordering of a spiritual conscience with men, and shall "make all things new." And this Heavenly Doctrine, as it descends into men's minds, is represented in the Apocalypse as a "new Jerusalem." Indeed, the Jerusalem of David, like Hebron, his first capital, represents "the Lord's spiritual church," with especial reference to its doctrine. (@AC 2901[e], 2909, 2981)

In this city David now dwelt in a house of cedar - even as the conscience of the New Church man finds its home in rational good formed by spiritual cognitions. Yet King David was not content. For the ark of the covenant, with its precious tables of the Divine Law, had for nearly a century been without a home. It had been brought fearfully from hamlet to hamlet, as if it were still a fugitive, exiled from the holy place within its proper Tabernacle. David first "heard of it in Ephratah," i.e. Bethlehem; he found it, now, "in the fields of the forest," in Kirjath-jearim, "the city of the woods." (Psalms 132, II Sam. 6) And he had "no rest unto his eyelids" until it was brought up and placed in the Tabernacle pitched upon Mount Zion.

The ark with its tablets written by God signified the essential Word, which is the spiritual sense. This was lost, well-nigh forgotten, as if in a city deep in a forest. In His second advent, the Lord brought back this Divine content of the Word and as it were replaced it in its proper Tabernacle, which is the literal sense of the Word, wherein it can serve as the medium of conjunction between the Lord and the Church. Hence the man of the New Church, like David, can say: "I will not come into the tabernacle of my house, nor go up into my bed; I will not give sleep to mine eyes, nor slumber to mine eyelids, until I find a place for the Lord, an habitation for the mighty one of Jacob. Arise, O Lord, into Thy rest. Thou and the ark of Thy strength!" (Psalms 132)

The ark was brought up to Jerusalem in three stages, which represented "the progress of the Church with man, from its ultimate to its inmost," as from one heaven to the next, even to the inmost. (@AE 700[25]-32). The first stage was when the ark was placed on a new ox-cart and brought from the house of Abinadab in Kirjath-jearim, while David and thirty thousand of his men and all the people played instruments in festal procession. This represented a state when the acknowledgment of the Divine truth with man is somewhat precariously founded only on a doctrine of natural truth from natural good, as on tradition and on fickle natural states. It is therefore told that Uzzah, the son of Abinadab, walking beside the shaking cart, put out his hand to steady the ark, and on touching it, fell dead.

This ended the journey. David was afraid to go on. The ark was instead placed in the house of Obed-edom, a Gittite. This abode represented the spiritual, who receive the Divine truth in the good of charity and are thereby blessed. And after three months David decided it would be safe to bring the ark up to Zion. But now it was not on an ox-cart, but was carried by the priests. And every six paces the jubilant procession stopped to sacrifice an ox and a fatling; and David danced with all his might before Jehovah, girt only in a linen ephod. Amid shouts and the sound of a trumpet the ark was brought into its place within the tabernacle. This last stage represented an ascent into the inmost of the Church, or into the third heaven, where the Divine truth is guarded by the good of love to the Lord. (@AE 700[25]-32)

The spiritual Word is accommodated to the three heavens as it descends from the Lord by inspiration. But in its reception by men there must be an ascent from a natural understanding into a spiritual and celestial perception of its truth. By slow stages, man's mind, during regeneration, is elevated into the light of the heavens and their higher loves, elevated to perceive the interior aspects of the Word. It may at first appear to man as if, in a certain sense, he was discovering this higher truth, and, from his proprium, assisting the Word, or steadying the ark of the covenant. Yet the truth is already in the Word - in infinite measure.

And it is in acknowledgment of that fact that the ark must be brought into its holy Tabernacle. How bleak and purposeless the Tabernacle without the golden ark in its sanctuary! How futile the letter of Scripture unless we knew it as the abode of the Spirit of truth, the Divine meaning, the spiritual sense! And how deprived of its intended use was the ark, while standing forgotten in a distant hamlet, unprotected and with none to attend it! - The Writings therefore say, that the ark of Israel "could not be called holy, and a sanctuary, until ... covered by curtains and veils" - as in the Tabernacle. "So would it be with the Divine truths in the heavens, unless they were enclosed in natural truths, like the truths of the sense of the letter of our Word." (@AE 1088[3])

For the conjunctive power of the spiritual sense is exercised through the Word in the sense of its letter; and it is from and through the sense of the letter that there is communication with the heavens, and conjunction. (@AE 1066[4]) It is this conjunction of angels and men that was represented by the worship centered in Jerusalem, the city of David, the spiritual center of the whole earth.

The sacred drama, in which the royal prophet led the ark up to Zion, was in a way a culmination of his conviction that "the earth is the Lord's and the fulness thereof." We can imagine that David felt some doubts who of all this people were worthy to ascend into the hill of the Lord and stand in the place of His holiness. And he answers, "He that hath clean hands and a pure heart . . ." And the people burst out in a chorus of joy: "Lift up your heads, O ye gates, and be ye lifted up, ye doors of an age! For the king of glory shall come in!" (Psalms 15, 24)

David, having offered many sacrifices to the Lord, distributed lavish gifts of food and flagons of wine to all the people. And having blessed the people, he returns to bless his household. But Michal, the proud daughter of Saul, taunted him sarcastically for demeaning his royal station by publicly dancing in the view of his maid servants. David then retorted that it had been before the Lord who after all had chosen him instead of Michal's father to rule Israel. And as for the maid servants, of them would he be had in honor, while Michal would be widowed in her husband's house. Therefore Michal had no children to the end of her life.

The contrast between the dignified etiquette of the daughter of Saul and the simple ecstasy of David's joy, marks the difference between a love of truth that is sophisticated and self-conscious, because it is rooted in natural affections and judges by the worldly standards of caste or fashion, and a spiritual love of truth which is forgetful of self. A spiritual conscience cannot be propagated through the natural light which brings learning from the glory of pride. Such pride is thenceforth childless, like Michal, unworthy to propagate the truths of a spiritual conscience.

---

Historically speaking, David's glory and power were ever increasing. He subdued the Philistines decisively. He made Moab his tributary. He conquered Syria up to the Euphrates and destroyed a thousand chariots, reserving a hundred chariots for his triumphal return to Jerusalem, with golden shields and vessels of precious metal which he dedicated for the use of the Tabernacle. He put garrisons throughout Edom, and when his good will ambassadors were disgraced and sent back half naked by the Ammonites, David defeated them and their allies and added their country to his domain.

Thus in one generation, Israel had risen from a primitive and scattered lot of tribes into the stature and repute of an empire, with important allies and - for the time - a modern army. David had now an impregnable capital city, a tabernacle where Jehovah was worshipped with elaborate rites and festal music of David's own directing. His court and government were organized like that of other oriental despots - his sons being treated as princes and his nephews and old supporters heading the army. His bodyguard, the Cherethites and Pelethites, were foreign mercenaries.

And David now bethought himself of his vow to Jonathan. He inquired of Ziba, a former servant of Saul and found that when Saul and Jonathan had fallen in Mount Gilboa, a nurse maid had fled with Jonathan's five year old son, Mephibosheth, and that in her haste she had stumbled so that he fell and became lame in his feet. David now sent for Mephibosheth and restored to him all Saul's land, under the stewardship of a man named Ziba. And Mephibosheth dwelt in Jerusalem from that time on, and ate at the royal table as one of the king's sons.

---

David's empire was the actual fulfilment of the Lord's promise to Abram, "Unto thy seed have I given this land, from the river of Egypt unto the great river, the river Euphrates." (Genesis 15:18) In order to understand what this territory represents, it should be kept in mind that all the ancient nations and peoples had their spiritual functions, based on their religion, their history, and unique character. All were needed as component parts of the picture of the spiritual environment of the Church or the contents of the human mind. In the relation of Israel to the Canaanite or Amorite or Hittite tribes which it displaced or absorbed, and to the neighboring peoples, Moab, Ammon, Edom, as well as Syria and Egypt, we see a description also of the various kinds of spirits which inflow into man's hereditary nature and influence the Church in its various states.

The kingdom of David represented the central region of the mind which had come under the control of a spiritual conscience. But around it we still find the Egypt of the knowledge of the memory, the Syria of cognitions or religious knowledge, the Babylonia of the imagination, and the Assyria of worldly reasoning; which all will exert their influence on the spiritual Israel of the Church.

== The Fruits Of David's Sin

It is in the nature of man to err, to sin; and the Lord, from Divine mercy, continually forgives. Yet sin has its consequences which even the Lord cannot annul. He who sows the wind will reap the whirlwind. Sin leaves its marks upon the sinner even after repentance; and in its train lies ruin for others also. Each sin hatches a brood of other evils seemingly unconnected yet interiorly bound up into a chain of events which follow the inescapable logic of retribution.

The latter half of David's reign illustrates this law. For David falls into the grievous sins of adultery and murder. The reverent reader of the Scripture to whom David had stood as a model of charity and piety and nobility, is shocked to find that his hero has feet of common clay. The New Church man, although knowing that the faults in David's personal character do not prevent his representing the spiritual conscience of man and, in the prophetic sense, even the Lord Himself in the flesh, may still be at a loss to understand how the heinous crimes and cruelties of David and his family could find a place in this lofty representation. For we cannot belittle David's sins, which are related in the Hebrew record with characteristic candor.

At the time of year when kings go forth to battle, King David sent Joab and his army to finish the war against Ammon; but he himself stayed behind in Jerusalem. And one evening as he was walking on the roof of his palace, he saw a beautiful woman bathing in a nearby garden. And finding that it was Bathsheba, wife of Uriah the Hittite who was away in the wars, he had her brought to the house. And later the woman sent word to him that she was with child. David, hoping to cover up his trespass, sent for the husband on a pretext and tried to make him drunk, but Uriah returned to the army without seeing his wife. And David then ordered Joab to place Uriah in the forefront of the battle so that he would be killed.

Uriah, whose self-restraint and high sense of discipline and duty were thus rewarded with death, was a Hittite. The Hittites were among the better of the inhabitants of Canaan, a "well disposed nation." (@AC 2913)

After Bathsheba had completed her mourning for her husband, she became David's wife. "But the thing that David had done displeased the Lord."

And the Lord sent Nathan the prophet unto David. And Nathan told the well-remembered parable of the rich man who had abundant flocks, but who, when entertaining a traveller, took the ewe-lamb of a poor man and killed it and dressed it for his guest; although the ewe-lamb was the poor man's only possession, which grew up as his children's pet and was unto him as a daughter. On hearing this, the king's official sense of justice was kindled, and he cried out, "As the Lord liveth, the man that bath done this shall surely die, and restore the lamb fourfold . .
. because he had no pity!" And Nathan said, "Thou art the man!" The Lord "put away" David's sin. But the child that was born to David and Bathsheba would die; and the sword would never depart from his house. The Lord would raise up evil against David out of his own house, and his wives would be dishonored before all Israel.

David confessed that he had sinned. And when the child became sick he lay fasting on the earth for seven days, praying to avert the death of the child. His agony of penitence is pictured in the fifty-first psalm, where he pleads with the Lord to create in him a clean heart and to renew a firmer spirit within him.

The child died. In time Bathsheba gave him another son, who was named Solomon and also Jedidiah ("beloved of Jehovah").

But David's heart was not cleansed. For when at last Joab had captured the city of Rabbah in Ammon, David was not satisfied with the golden crown and the other spoil of Ammon, but put the inhabitants to death with unmentionable tortures.

It was a peculiar quality of the Israelites that they could abase themselves utterly before the Lord with deep confession of their sins and be in a holy external during their worship. yet cherish within the lusts of enmity and revenge, avarice and contempt for others. The psalms of David, if read only as to their literal implications, show not only these contradictory features, but also the self-righteousness of David who again and again avers that he has kept all the precepts. It is also evident that there could be no love truly conjugial where the love was divided among many wives and concubines, and no concept of the eternity of marriage existed. Yet there was a powerful love of tribe and family, and of offspring, especially of the sons who were to perpetuate and defend the tribe.

David had many sons. And it was one of his weaknesses that he could not bear to disappoint them or inflict pain on them, even when they should have been corrected and punished. He loved them, not according to their virtues, but because they were of his own flesh. This, as well as the fact that they had different mothers, became the cause of dissension and domestic tragedy.

Thus it came about that his son Absalom treacherously slew Amnon, a half-brother, for violating Tamar, Absalom's sister, and then brutally casting her off. King David became heart-broken at an incorrect report that Absalom had slain all his brethren. Absalom then fled to his mother's father, the king of Geshur, in Syria. But David longed to have him back - willing to pardon. And after three years Joab, seeing David's longing for his son, secured permission to bring him back. Indeed Joab copied Nathan's method, of using a parable, getting a wise woman to ask the king's counsel about how to save her son who had slain his brother. So Absalom came back to Jerusalem, but was not permitted to see David's face. Then - after two years - Absalom set Joab's field afire, and so forced Joab to secure him an audience and full reconciliation.

All now seemed well. But Absalom was ambitious, and harbored a hidden contempt for his father. He began to use flattery and intrigue, sitting at the gate of the palace and showing interest in the cause of any one from the provinces who came to the king's court with a petition, asking them where they came from and insinuating that it was too bad that the king was so busy; if he were judge he would have time for seeing that they received justice. He behaved most democratically, shaking people's hands and kissing them, in the manner of a clever politician. And so he "stole the hearts of the men of Israel."

Absalom was a charming man, none so praised for his beauty. "From the sole of his foot to the crown of his head there was no blemish in him." His hair was long and heavy, and when he polled his hair at the year's end it weighed two hundred shekels!

Forty years had passed since David was anointed. Absalom, on a pretext, gained royal permission to go to Hebron in fulfilment of a vow. He took with him two hundred men who were quite innocent of his real purpose. But now he sent his agents all over Israel and gathered his conspirators together, and sounded the trumpet for a rebellion.

The conspiracy was so strong that the king had to flee with his loyalists and six hundred of his household troops from Jerusalem, leaving only his ten concubines to keep his palace. Amidst the lamentations of the populace they passed over the brook Kidron, headed for the wilderness. The priests Zadok and Abiathar and the Levites took with them the ark of God. But David ordered them to go back with the ark, and await his further orders. And Hushai, David's friend, was ordered to get into Absalom's confidence in order to subvert his schemes.

And as David went up Mount Olivet, barefoot and weeping, with covered head, Ziba, the servant of Mephibosheth, Jonathan's lame son, passed him to go up to Jerusalem, and added to David's sorrow by falsely pretending that Mephibosheth was now plotting to be restored to Saul's throne! Shimei, a man of Saul's family, went along by the wayside, cursing David, pelting him with stones and mud; but David told his soldiers to let the man alone; it was as nothing to one whose own son wished to kill him; it was only another affliction sent by the Lord.

When Absalom came to Jerusalem, he invaded David's harem and set out to disgrace his father in every way. And if Hushai had not defeated better counsel, David's little army would have been wiped out before it crossed Jordan into Gilead. But in Mahanaim in Gilead, David was given supplies for his people and began to organize an army under Joab, Abishai, and Ittai the Gittite. His men convinced him that he must not go out with his army. And when finally the decisive battle was near, he asked his captains, "Deal gently for my sake with the young man Absalom!"

Yet when the battle was joined it was a scattered combat in the oak forest of Gilead, in which "the wood devoured more people than the sword". Absalom was riding on a mule, and his head - with its beautiful hair - was caught in the gnarled branches of an oak and he was left hanging "between heaven and earth"! Joab, told of this, took three darts and thrust them through the rebel leader's heart. Then Joab blew the trumpet to hold back his people from pursuing the fleeing Israelites; and Absalom was buried in a pit under a pile of stones.

The news of victory came to David. But his only question was, "Is the young man Absalom safe?" And the answer was, "May all the enemies of my lord the king ... be as that young man is!" Inconsolable, and weeping, David sought his chamber, moaning, "O my son Absalom, my son, my son Absalom! Would God I had died for thee, O Absalom, my son, my son!"

The people walked about shamefaced, despite the victory. It was only when Joab had upbraided the king with loving his enemies and hating his friends, that he arose to sit in the gate.

And now there came a strange reversal in the feelings of the nation. There was much strife and discussion, but there was growing realization of David's greatness. The tribes of Israel - the northern tribes - were first to bring his restoration about, but later Judah came to conduct him in triumph over Jordan. The king not only declared a general amnesty and reconciliation, but he deposed Joab and --- as an act of confidence - chose Amasa, Absalom's captain, as chief of his army. He forgave Shimei, who had cursed him on his flight. He restored half the property of Mephibosheth who had been falsely accused.

But despite these gestures of friendship to Israel, they were jealous because the tribe of Judah had first brought the king back to Jerusalem. Sheba, a Benjamite, raised Israel into revolt. Amasa, the new general, assembled the men of Judah, but was tardy, and so Abishai, Joab's brother, was first to take the field. Joab caught up with Amasa and treacherously murdered him. And then the two brothers pursued after Sheba, and besieged him in a town in Naphtali. Joab was about to destroy the town, when a wise woman found out that what the attackers really wanted was Sheba. Then the town's people threw Sheba's head over the wall, and Joab - now again the head of Israel's hosts - returned to the king at Jerusalem.

---

Why are such evils given prominence in the Word of the Lord, which is the most precious inheritance of mankind, and the window through which heaven is to shine? Why must even David, the beloved, the hero and the poet, interpreter of some of the heart's deepest emotions and most sublime hopes, be portrayed as besmirched with the grossest vice and shown up as weak and sinful?

The answer lies in the doctrine that "in the internal sense of the Word the Lord's whole life is described such as it was in the world, even as to the perceptions and the thoughts . . . and how by successive steps He put off the human and put on the Divine." (@AC 2523) And the story of David, from the time of his first trespass to the time when he returned from exile, abased in his own sight, acquainted with the grief that was born of irreparable sin, is but a segment of the story of how the Lord put off His mortal inheritance. It is against the background of his experience of human frailty and suffering, that we must see David, if in him we shall recognize the prophetic type and representative of the Christ that was to come! - of the Lord in His assumed human, born as the Son of God but also as the son of David, and hailed in scorn as "king of the Jews!" - of the Lord, born of woman, carrying the iniquities of us all in the inheritance of borrowed flesh!

Who accuseth Him of sin-this "Lamb of God" which carried the sins of the world only that He might take them away? Although His assumed flesh was charged with the propensities of all the hells and the inclinations of all the kings of Judah, not the least of such perversity entered the will of the Lord in His Human, or into His own purpose. But to subjugate and order the hells, the Lord had to become increasingly aware of the nature of His maternal heredity, and in the course of the growth of His own proper mind, He unceasingly studied the consequences which would result if the connate lusts of man should but for a moment rule.

The Lord, different from all men, had a perfect "perceptive sensation and knowledge" of all things that were taking place in the world of spirits and in the heavens. (@AC 1791, 1786) He could therefore scrutinize the tendencies of fallen man and measure the forces of evil and probe their origins and their paths of influx from the spiritual world, observing how they approached man in enticing disguises and gradually unfolded their destructive nature. And this Divine study cannot be conceived as an abstract process. For it plunged the Lord's human consciousness into the very midst of the hells, making the Lord's external mind the burning focal point and arena wherein the evils of all past generations were reenacted in grimmest realism, as their inner challenge and their deepest potentialities were revealed. It cast the Lord's mind into a state of temptation and suffering, keen beyond compare.

The power of the hells does not consist in evil alone - or in the inborn lusts of the flesh; but in their seizing upon the ideas which man regards as true and perverting these truths to excuse and thus to confirm evil. In the Jewish Church, the truths thus perverted were from the Hebrew Word itself, Divinely inspired holy truths containing the very laws of heaven but mostly veiled in the symbolism of correspondential language. But even those truths of the letter of Scripture which were least veiled - such as the ten commandments - had in the Jewish Church been distorted and abused.

The profane conjunction of evil with simple, external truth is in reality a form of spiritual adultery, which brings with it internal perversions, spiritual violence, spiritual death, spiritual rebellion. And it was the propensity of the human inherited from Mary the mother to such evils, that the Lord, from His Divine insight, discovered as a tendency innate in His assumed flesh. He saw that so far as any truths entered His mind the inherited human from Mary would seize upon them to pervert them. And this danger, Divinely foreseen, was pictured before His mind as the internal meaning within the sacred narrative concerning David's weakness and fall. For David - at this point - represents the Lord in His assumed human, and thus as to the maternal heredity. Therefore David, in the fifty-first psalm, cries out in his despair,
"Behold, I was shapen in iniquity, and in sin did my mother warm me."

The supreme contents of the narrative describing David's sin thus involves what the Lord saw within the maternal inheritance which He bore; and it involves a stage in the glorification of His Human through temptations, the temptations to which truth Divine was subjected. All the hells concentrated to induce the idea that the Lord was Himself identical with His assumed Human and responsible for its potential evils and the falsities these evils could engender; or, obversely, that the Divine was responsible for the evils of mankind permitted by virtue of man's freedom. The hells sought to immerse the Lord's human mind into the despair that because such was the heredity of man, there could be no redemption, no salvation for our race.

And from Divine truth, if separated, the race stood indeed condemned. Yet from the union of Divine truth with Divine good, there came consolation, forgiveness after repentance, and thus a restoration through mercy. And this is pictured in the sense of the letter when it is shown how David, though repentant, had to bear the consequences of his grievous sins and see the degeneracy and rebellion of his offspring and the secession of his people, yet, mellowed by sufferings, was forgiven of God and restored to his kingdom. By the searching light of Divine truth the evil gnawing at the heart of the world could be exposed and clearly seen as evil. Its disguises torn away, it would be pressed to work for its own defeat. Then the Divine truth could show the way to the Divine love. And by the union of Divine truth and Divine love, the Human of the Lord would be glorified and revealed as the Divine Human.

---

The Divine foresight involved in the story of David extends also to show the means and stages by which the Lord can open the spiritual degree of a regenerating man's mind, by the affection of truth for its own sake. In the first stage of such spiritual rebirth, man's state resembles that of David, innocent and fearless, who could not rest until the ark of God was restored in its tent on Mount Zion, and who danced for joy as it was brought into Jerusalem. But it is told in the Writings, that "the good of truth cannot for long remain pure" with the man of the spiritual church. For it is modified and - in the natural mind - sullied by enjoyments which spring from the desires of the proprium. (@AC 8487)

These impure delights rise up into the rational, and defile and confuse its perception, so that man's conscience is covered over by what is spurious from the natural man. The David of spiritual good no longer rules - in such states. But another David, subject to the alluring desires of the senses, takes its place; a David who no longer leads his people in the war against evil.

All evil is some form or consequence of spiritual adultery. Even as natural adultery means any trespass done from a loathing for the true state of marriage, so spiritual adultery springs from an aversion to the marriage of good with truth, and seeks to avoid the consistent life of religious duty. It is a disorder within the relations of one's affections and perceptions. It allows self-indulgence and lust to take the place of conscience; it secretly permits the simple truth to be killed off, and turns the affection for such truth into a harlot: even as David caused Uriah, the simple, loyal soldier, to be slain, and his wife seduced.

Spiritual adultery, when described in abstract terms, does not appear as abhorrent as natural adultery. The reason is that it is present in the proprium of every man. Indeed it is told that man is born into the love of spiritual adultery. (@AE 984[3]) Yet it is discovered only when man's spiritual conscience has become awakened - as if by a prophet's voice, the voice of Nathan, when David, repenting, is restored and granted a new heart and a firm spirit. It is then seen as to its true nature; for it leads inevitably to spiritual murder, to self-deception and shame, to the death of the spiritual children of the mind, to unspeakable mental cruelties, to profane, unlawful relations among a man's thoughts and affections. And eventually its consequences are seen to result in a spiritual rebellion, in which the spirit of the Word of God is reviled and the rule of the conscience of spiritual truth is overthrown.

Some such chain of spiritual disasters comes from every unholy connection between evil affections and false ideas. From such spiritual adultery the evils with man become actual and thus also handed on to posterity as hereditary inclinations. The prevalence of such spiritual adultery is the cause why there is no longer much internal resistance to natural adultery in the Christian world.

There is something final and irrevocable about natural adultery. It closes heaven to man. But spiritual adultery, which is within the mind, can, in many of its forms, be amended. (De Conj. 93) The trespass of David, callously committed, seems unforgivable. Yet in the Biblical account David is said to have been forgiven by the Lord; the reason being that in the spiritual sense, his sin represented a spiritual adultery, or a perversion of an affection of simple truth through the seduction of a strong and prevalent concupiscence. It signified a state which repentance could cure. There are many perversions in the mind which man has not discovered, and so cannot shun. And there are children of our brain - born out of due time - which of mercy die, despite our misguided entreaties.

And Bathsheba was reclaimed from adultery into honorable marriage, to become the mother of Solomon the wise.

---

Where a spiritual adultery has possessed the mind, and the vigilance of conscience is relaxed, a brood of evils follows. The incest of Amnon signifies a state where there is an acknowledgment of charity without any shunning of the evils of life. Even a merely moral standard is outraged by such spiritual hypocrisy. It is condemned by purely ethical standards, such as are now so prevalent in the world. Many ethical movements exalt the moral precepts in the Bible, both the second table of the Decalogue and the moral teachings of Christ. But they voice utter contempt for the idea that the Word is holy because it has an internal sense inspired from God.

Thus Absalom killed Amnon, even as modern ethics contemptuously condemn the hypocritical phases of religious life. But Absalom goes further, plotting to obtain the kingdom.

Sneaking spiritually, we see all around us this rebellion of Absalom. The effort is being made to create a religion for this world alone - a religion which takes the literal sense of the Bible not as inspired of God but as the beautiful literary record of man's increasing intuitions
- a history of moral perceptions, a literary masterpiece, which, when stripped of its superstitious trappings, its talk of miracles and an after-life, can be of value to our more enlightened age in constructing a more pleasant - though less permanent - paradise than God could ever invent!

This new Absalom is but another, more subtle form of treating the Word as a letter - having no spiritual sense within it, but only moral implications. Taken thus by itself, "the letter is rebellious as was Absalom the son of David." (@SE 2658)

The merely ethical interpretation of Scripture becomes a seductive system of thought. Like Absalom, it has a sensual beauty and a persuasive appeal. In effect, it presents before us a revised form of Bible, - which in the eyes of modern man - "has no blemish" from the sole of the foot even to the crown of its head; for every thing repulsive to the delicate ear or liable to offend our prejudices or strain our scientifically trained faith, is simply eliminated as antiquated and of no value. And how the crowds, partly "from simplicity," are drawn to such a faith! It promises a panacea - justice for all - without disturbing the spiritual inertia of the unregenerate. It does not tax our minds with self-examination. It flatters the natural good in every man who seeks a superficial success founded on self-respect.

But it disrupts all spiritual progress, destroys all eternal values. It flauntingly unleashes sinister evils in the name of a new freedom. The standards by which it judges are frankly worldly and ostensibly supported by statistical evidence. Many of the leaders of Israel flocked to Absalom's standard.

The remarkable thing in the history of the rebellion was that David fled at once to the wilderness and to Gilead. And when, reluctantly, he prepared his own hosts to do battle, he charged his captains, "Deal gently with the young man Absalom for my sake."

For David, mourning for Absalom, represented the spiritual sense of the Word, the Doctrine which is fearful lest all faith in the literal truths of the Word should perish among men. Even false principles, when from the Word, can be bent by the Lord into truths; "wherefore the sense of the letter ought not to be broken" For in the literal sense the Divine truth dwells in the beauty of holiness. (@SE 2694f)

The three darts which are thrust through Absalom's heart "while he was yet alive in the midst of the oak," shall not come from the legitimate source of the New Church. The modern rationalists that have caught the fancy of the churches are headed towards a destruction of all faith in the Bible. It is their own untamed reasonings that run away with them, like Absalom's mule in the wood; and they are left hanging "between heaven and earth," their beautiful perceptions entangled in the sensual appearances of the Bible and the contradictions of the "higher critics;" as Absalom was caught with his elegant locks ensnared in the gnarled oak branches. But the death blows were given by Joab.

Every worthy cause has its Joabs who defend it merely for the brutal joy of battle and are untouched by its spirit; servants who are permitted to fight error with callous guile and do evil in the cause of good, until they finally overreach the limits of their authority. (@AC 9014[5], 9828:7) And at this time David was in Joab's hands, unable even to rebuke his captain for what was deliberate disobedience. But all he could do was to cover his face and mourn, "O my son Absalom, 0 Absalom, my son, my son!"

== David's Latter Years

In the view of heaven, the whole history of Israel is seen entirely in a spiritual sense which describes the succession of the states of spiritual life with man; and inmostly in a supreme sense which records the successive states of the glorification of the Lord's Human. So utterly different is the internal sense of the Word from the sense of its letter that the angels perceive no mention of persons or places or natural events; and as their minds are uplifted to see the Divine contents of the Word as it emerges from its letter, natural ideas fall away and with them the thought of the evils and perversions that are so prominent in the literal story.

The Writings reveal that the internal senses - one within the other - are seen by the angels in a beautiful series, unbroken and orderly, always reflecting the progressive states of angelic uses - organized as if in the human form. (@AC 1871-1876) This continuity of the internal sense persists even where the literal sense seems to be broken and as it were incoherent, without any discernible order. The last portion of the Second Book of Samuel describes detached incidents from the life of David after Joab had murdered Amasa his rival, suppressed the rebellion of Sheba, and regained his position as captain over the host of Israel. First is described a famine, then a war with the sons of a Philistine giant, then follows a lengthy song of deliverance known to us also as the eighteenth Psalm. After this is adjoined what is called "The last words of David." Then comes a description of some heroic deeds by the three foremost warriors of David and by two others, with a list of other "mighty men," thirty-seven in all. And finally the book closes with the narrative of how David "numbered the people," an act which brought a pestilence upon the land.

The Writings give only scanty indications of the continuity of the spiritual sense of these scattered records. But the whole of David's life is a representation of the Lord's states of temptation, by which He overcame the hells. As applied to the states of man's regeneration, the story treats of the opening and furnishing of the spiritual degree of man's mind, and the awakening of the elusive states of spiritual perceptions; eventually, after many temptations, these come to rule in the mind as truths of doctrine, which are then confirmed by the sense of the letter of the Scripture and seen therein. Thereby the Holy Scripture becomes a tabernacle into which the ark itself is placed and which is thus restored as the medium of conjunction between the Lord and man.

David was a man of war, and his life represents the combats of temptation. His sins and weaknesses, so frankly depicted, represent hidden states of evil which a man's spiritual conscience discovers in himself, as tendencies or even intentions; states which are forgiven him when he recognizes their nature and turns away from them with aversion. David is occasionally pictured in the Word as an evil-doer, an adulterer and murderer. For it is so that the regenerating man appears to himself when he regards what his proprium actually is in itself. Some of the other evils of David represent what is good. The massacre of his enemies with infants, women, and sometimes the cattle, means a man's condemnation and utter obliteration of certain of his own evils, both lusts and falsities, from his active life. And it is to be noticed that some of these enemies, although utterly destroyed, seemingly turn up - a few chapters later - as formidable as ever! even like the evils which, man thinks, will no more tempt him. It is also true that some of David's weaknesses, in the spiritual sense, signify virtues. His love of many women is used to symbolize the many affections which are aroused by spiritual truth. His incomprehensible weakness for his wayward son, the rebel Absalom, signifies the Lord's Divine yearning for the preservation of faith in the literal sense of the Word, and the spiritual man's similar reluctance to pit his perception of spiritual truths against natural truths, even when these are wrongly used and advanced from a conceit of self-intelligence which is contemptuous of an interior understanding.

---

With this in view - that the evils described in the letter are those evils which a spiritual conscience discovers during self-examination - we proceed to consider one more dread event.

A three-year famine came upon the land. And by enquiring of Jehovah it was found that it had come "because of Saul and his bloody house" - because he had broken faith with the Gibeonites, with whom Joshua had made a solemn compact that they should not be slain but be treated as tributaries, as hewers of wood and drawers of water for the tabernacle. Saul had slain some of them and David now let the Gibeonites fix the penalty. Their decision was a strange and awful one; resting their case on the law of retaliation, they demanded not lands, but claimed the lives of seven of Saul's descendants. The five sons of Michal by her second marriage, and two sons of Rizpah and Saul, - men who perhaps had been involved in the massacre - were delivered to be hanged. And Rizpah, day and night for the entire summer, sat beneath the gallows to protect the bodies from vultures and beasts. The sordid story is relieved at last by David's ordering the bones of Saul and of Jonathan and of the seven who were hanged to be gathered and buried in the sepulchre of their fathers in Benjamin. And then the drought was broken and the land blessed by rain.

It is clear that the famine came as a result of an evil as yet undiscovered. That one evil leads to another is not a secret doctrine. But there are hidden evils fretting in our hearts which never come to view in act or word, yet simmer unjudged and spread their dark moods over our spirit until they finally cut off the influx of heaven from our conscious mind and reveal their effects as a spiritual famine - a failure of the goods and truths, and especially of the knowledge that we need for the daily nourishment of spiritual life and thought. In this case, the evil, never actually recorded in the sacred record, was committed by Saul, yet its aftermath came in the days of David. Evils which date back to our childhood states when our conscience was based on merely literal understandings of what was right and wrong and before our passions were under intelligent control, can remain brooding, unconsidered and unjudged, in the undercurrents of the mind, until the memory of these sins of our youth begins to come back to haunt us. And when the evil, with its results, is rationally recognized, and seen in its perspective, it is no time for self-accusation. But the responsibility must be traced to "the house of Saul" - to the errors of the past. It might be thought that the reader of the Word might be saved the hideous scene of Rizpah watching beneath the gallows. But the fact is that Rizpah, Saul's concubine and later Abner's (and her name means "a live coal") represents that smouldering ember of natural yearning which survives even after our evils and falsities are judged. And it is that natural affection, mother of many errors, which is permitted to guard lest the memory of natural truths - however perverse the use to which they were put - should ever perish from our minds.

And indeed, this loyalty was rewarded when David gathered the bones of Saul and Jonathan and those that were hanged, and respectfully placed them in their family sepulchre. Truth is in itself sacred, even if used amiss. Even as a man's body is to be laid reverently aside in the earth whence it came, the bones intact, as a representation of perpetual remembrance; so truth, even when its essence is fled, persists as knowledge in the memory.

---

But David represented a living truth, a leading state in the mind. And therefore the next segment of his story is about a final war with the Philistines in which he again encountered one of "the sons of the giant," and, waxing faint, was nearly killed. He was rescued by Abishai; and they made him swear to into battle no more, "that thou quench not the lamp of Israel!" In all, four sons of the giant of Gath were slain by David's men in that war.

David was the lamp of Israel. His uses - recognized by his people - were superior to that of fighting men. And as if to emphasize this the sacred text at this point includes one of his psalms - substantially the same as the eighteenth, which is therefore found twice in the Word. That it was David who was mainly responsible for the embellishment of the ritual of the tabernacle with songs, antiphonals and even sacred dances as well as with orchestral music, seems clear, not only from the account of his life but from the headings, of many of his psalms, which show that he prepared them to be sung with instrumental accompaniments. (@AR 279, @AE 323, 326:2, 13) And these various instruments have a correspondence to the delights of the distinct celestial or spiritual affections which predominate in the internal sense of the psalm. (@AC 8337[e])

The eighteenth Psalm is David's song of deliverance from his enemies and from Saul. (Note that he never calls Saul his enemy.) The internal sense describes the Lord's temptations while in the world, the power by which Jehovah delivered Him, the justice of Jehovah who enlightened Him and gave Him strength for victory. But David thought that he was writing the song about himself, for - as the Arcana states - he "was in the love of himself and his descendants." (@AC 2842[4], @SE 2621) Even considered in the natural sense, his poetry was highly symbolic, in the style of the ancients: "Jehovah is my rock and my fortress, and my deliverer . . . my shield, the horn of my salvation, my high tower . .
. The cords of hell encompassed me, the snares of death prevented me .
. . In my distress I called upon Jehovah . . . Then the earth shook and trembled . . . There went smoke out of His nostrils . . . He bowed the heavens and came down . . . He rode upon a cherub . . . He sent out arrows and scattered them . . . He drew me out of great waters. Jehovah rewarded me according to my justice; according to the cleanness of my hands hath he recompensed me . . . For I have kept the ways of the Lord
. . . I have kept myself from mine iniquity . . . "With the pure Thou art pure, but with the perverse Thou contendest."

These things wrote David about himself, not knowing that it was a prophetic picture of the Messiah to come. That he, nonetheless, was seized by the spirit of prophecy and wrote only what God inspired, is clear from the next chapter, which begins:
"And these are the last words of David. David the son of Jesse said, and the man raised up on high, the anointed of the God of Jacob, and the sweet singer of Israel, said: The Spirit of Jehovah spake by me, and His word was in my tongue. The God of Israel said, the Rock of Israel spake to me..."

The inspired message then follows. It contrasted the qualities of a true king with those who are lawless and worthless. "He that ruleth over men must be just, ruling in the fear of God, and be as the light of the morning at sunrise, a morning without clouds; as the tender grass out of the earth sparkling after rain . . ." But those "of Belial" would be as thorns which cannot be touched except by iron tools and must be burned with fire.

---

Then follows a list of the "thirty-seven" mighty men of David. (2 Samuel 23:8) The deeds of Adino, Eleazar, and Shammah are recounted, as well as those of the next mightiest, Abishai and Benaiah; and thirty-one others are named, making thirty-six. But Joab is conspicuous by his absence from the list; neither is Abner mentioned. For both these men - although chiefs over armies - failed to live up to the measure of a hero. One was a murderer, another a rebel. The "mighty men" in David's list represented the "truths from good" which fight for the establishment of a spiritual conscience, and this cannot be done from a natural love, but by convictions that spring from spiritual charity. The truths which can fight evil and falsity are truths also which have acquired strength and skill in the arena of man's conscious thought. Such truths - the real heroes of Israel - find their training ground and their battlefield in the natural mind. The Writings plainly show - as has been pointed out in preceding chapters - that the spiritual mind is furnished or "formed" from those things from the Word which are in man's memory. But in order to enter the spiritual mind, such truths are "elevated" and purified and take on a spiritual form no longer bound to ideas of space and person and time; and such thoughts as man thinks in the spiritual mind are inexpressible, so that he is not really aware of them while on earth except as a vague affection and a new motivation and a delight in uses for others. David represents, particularly, such imperceptible truths which are being stored in the spiritual mind. (@AE 625, @DLW 252)

Yet the battles of life are fought out on earth, and spiritual issues are constantly involved in the practical problems which occupy so much of our natural thoughts. And therefore David needed an army of chosen mighty men, inspired by unswerving loyalty to him. For these would represent "the things which are in the natural mind from the spiritual," the things by which the spiritual mind, once established within, can form the natural mind in its image, so as to correspond to it and serve it.(*)

(*) This doctrine is elaborated in @AE 790.

What are these agents of the spiritual mind by which it can enforce its rule, except truths - rational truths, moral truths, and natural or civil truths? They are the mighty men of David: truths which "come under the view and into the perception of man," and which enter into his responsible thinking and - willing. For, for every thought there is an answering affection and longing, a good of use.

---

The kingdom of David now seemed secured for his lifetime and for his descendants after him, according to the Lord's promise. Yet Israel, it appears, had not yet fully atoned for her many sins. We read that the Lord's anger was kindled against her and that He moved David to say, "Go, number Israel and Judah!"

It is part of human nature to feel insecure unless one can rely on external strength and physical power. It is not enough - man feels - to be right, one must also be strong to defend the right. The Lord alluded to this prudence with seeming approval when He said, "What king, going to war against another king, sitteth not down first and consulteth whether he be able with ten thousand to meet him that cometh against him with twenty thousand? Or else . . . sendeth an embassy and desireth conditions of peace." One must count the cost beforehand. But, the Lord made clear, the cost of discipleship was to forsake all that one has. (Luke 14:31-33) Here we seem to meet up with a spiritual paradox. We are to number our spiritual resources, yet forsake all that we have.

This same paradox appears in David's numbering of the people. For apparently even Joab remonstrates with David that it was an unwise thing to do. And when it was done - and when Joab had gone through the land from Dan and Tyre in the north to Beersheba in the south - and it had been found that there were in Israel eight hundred thousand valiant men that drew the sword and in Judah five hundred thousand, David's heart smote him and he confessed that he had sinned.

The story, in its literal sense, does not make clear wherein his iniquity lay. For there were provisions in the Mosaic law for taking such a census. Perhaps it was the spirit in which David undertook the numbering that was wrong? Perhaps he wanted to test whether he could raise armies large enough to conquer further territories which had not been included in the land which Jehovah had promised to Abram's seed? Perhaps it was to bolster his own pride that he wanted to know the potential strength of his domain, so as to compare his empire with those of Egypt and Assyria?

But let us note that the law in Israel was that its rulers should not take the sum of the children of Israel after their number unless at the same time every man who was counted, be he rich or poor, gave a ransom for his soul - a half shekel as an atonement for his soul - to be used for the service of the tabernacle of the congregation; and this, lest there be a plague among the people. (Exodus 30:11-16)

Properly conducted, a census was useful and permissible. It is of need at times to take stock not only of our man power, but of the material wealth on which the uses assigned to us in the providence of the Lord, ultimately depend. Even the uses of heaven are perfected by the constant addition of new angels. And new spirits are welcomed joyfully if they are prepared and anxious to contribute to the work and enlightenment of a society. Similarly it is proper for men to rejoice in the growth of the church, so far as this numerical increase can make possible new ways of extending its usefulness, propagating its faith, and perfecting its life.

Uses are from the Lord alone. He provides the means and He points out the end. He instructs us in the Word as to their relative importance, inspires a love for them and gives men the power to carry them out. To Him alone is the glory. But they are performed by men, as if of themselves; and a man feels that they depend on him. In fact, he is loath to ascribe all the merit to the Lord. Has he not suffered and toiled, and freely labored to gain skill and judgment? (Matthew 20:12)
His spiritual conscience does indeed urge him to acknowledge that all good is from the Lord. But his natural man feels that it is his own doing! And he reflects on his available wealth and marshaled man power with pride and concern. In his pride, he concludes that there must after all be some superior quality in him and his. He begins to judge the states of others, their abilities and conditions. If he cannot find fuel for his pride in greater accomplishments, he can at least boast about his greater handicaps.

What the natural man fails to see is that what he can achieve as of his own power and choice, is not the real use! It is so even with the uses of the Church. Men can establish societies and institutions, publish books, solicit new adherents, maintain a priesthood which provides for teaching and leading. But the real - and only - use of the Church is a Divine use performed solely by the Lord who opens men's hearts to the Divine Word and awakens the life of charity. (@DP 172[6]) This is not done by men, but by the Holy Spirit which passes through the heavens and the Church and through men to men; and when and how this use is effected, no man knows for certain. (Canons HS iv) No man can number the souls that are saved, or count the states of good or truth which the Lord arouses through human hands or human voices.

---

It is this acknowledgment, this feeling, that is meant by the small half-shekel which poor and rich could equally afford as a gift to the Lord's work - a gift which saved them from the plague which a "numbering of the people" would otherwise surely bring. It is in this spirit that every regenerating man is at times "moved" by the Lord to give thought to his state, to examine himself to see what evils must be combated and what uses he is able to undertake. We ask the Lord "so to teach us to number our days that we may apply our hearts unto wisdom."
(Psalms 90:12) To "number our days" means to order and dispose the states of our life. (@AC 10217) But even with the wisest man there are limits to his knowledge of the states of his own mind. His field of responsibility and cooperation with the Lord is staked out by the things which his natural thought can perceive. For man has an external of thought of which he is fully aware and in which he exercises his choice. But of his internal of thought, the thought of his spirit, he knows nothing. Yet the law is given that so far as man explores and shuns evils in the external of his thought because such evils are sins against God, so far the Lord will remove the lusts of evil from the internals of his thought and open his spiritual mind and store it with heavenly treasures - and give him a heart of wisdom. (@DP 120, @DLW 252)

In order to enable man to cleanse and govern the external of his thought, it is provided that man should be able to elevate his thought above his selfish desires so as to perceive and recognize spiritual truths. From his inborn rational faculty even an unregenerate man can come to know and acknowledge truths about heaven and the Lord and be able to teach them and as it were have a love for them from a natural affection of learning or of fame. The rational, when so elevated, may appear as a spiritual or a celestial rational! Yet when man's own self-love, his proprium, becomes active, he ascribes such truths to himself and reflects on how clever he is to know them.

It is notable that even Joab recognized the folly in David's fixed desire to number the people. For Joab represents a state of understanding from merely natural loves of preeminence and fame. Even a hypocrite can know from plain doctrine that it is wrong to claim to know the interior states of the Church, or to discern what truths in his internal of thought are conjoined with goods. Spiritual truth is not conjoined with good until man has paid his half-shekel as an acknowledgment that all truth from good must be attributed to the Lord alone. When truth is thus conjoined with good it is lifted out of the sphere of man's natural mind and beyond his power of calculation. Wherefore we are told that man cannot judge of the state of his internal: "he is unable to know whether he has charity," and if he has it, he "does not reflect upon it." (SD min. 4547)

Our uses in this life would be impossible if we were constantly aware of our own spiritual states or imagined that we could judge as to the interior motives of others. Nor can the internal quality of the Lord's Church on earth be seen by any man as long as he lives in the world. (@LJ 41, @CL 523) The consummation of the former Christian Church will therefore "not be at all recognized on earth, though fully recognized in the heavens." (5 Mem. 15) It had to be disclosed by a Divine revelation.

For the needs of human society, it is sufficient to make civil, moral, and rational judgments. The Lord alone can know, and thus order and dispose the truths and goods of faith and love in the internal of man's thought, or within the spiritual mind. Therefore the law about numbering Israel is strangely inserted immediately following the command to make an altar on which incense was to be burned when Aaron lighted the lamps in the holy place of the tabernacle: for the holy place signified the spiritual degree of the mind. (Exodus 30)

To think of spiritual states of truth from good as the product of his own efforts, is to invite a spiritual pestilence. When David's heart smote him, and he recognized his sin, the prophet Gad, David's seer, offered him the choice of three punishments, a seven year famine, a defeat in war, or a three day pestilence. And David said, "I am in a great strait. Let us fall now into the hand of the Lord, for His mercies are great; and let us not fall into the hand of man."

David's words point to the law that as soon as man "acknowledges and believes [in his heart] that goods flow in from the Lord and not from himself, and that evils are from hell, then goods affect him and evils do not adhere to him." But, in Israel, the pestilence could not be averted and seventy thousand perished - a scourge that signified the vastation and consumption of goods and truths received from infancy. (@AC 10219)

It is important that we know - in our efforts to obtain a heart of wisdom - that this is the retribution awaiting us if we count our virtues and claim merit far spiritual truths and goods which we imagine we have. The story of David tells what the regenerating man sees as his penalty, if he claims such merit. But it also tells how the avenging angel of the Lord was commanded by the Lord to stay his hand when the pestilence neared Jerusalem, and how Gad told David to rear an altar on the threshing floor of Araunah the Jebusite, who seemingly had ruled Jerusalem before David had conquered it.

The Jebusites were long tolerated in their ancient city of Jebus or Jerusalem because they signified a form of idolatry in which there was something of truth. (@AC 6860) And in every man's mind there is a threshing floor where he may break up the husks of fallacy to procure the truth of good - the kernel of charity that truth is meant to produce.

But here we find now a contest of virtues. For David wished to buy the threshing-floor, to rear the altar. But Araunah offered not only the place but oxen for the sacrifice and the precious threshing flails and the yokes of the oxen for wood. "All these Araunah, a king, gave unto the king, saying, `Jehovah thy God accept thee.'" In this act of generosity the spiritual meaning shines through. For the things in the mind that are worthy to be rendered up to the Lord in worship are not to be thought of as great sacrifices, or as procured through our labors or to be valued by human standards. David failed to see the graciousness in Araunah's offer. He insisted on paying - and set the price at fifty shekels. He would not offer burnt offerings unto Jehovah his God of that which cost him nothing!

And though we might more easily see the inner truth in Araunah's royal gesture, David's purchase signified an appropriation and confirmation of the same truth. For his sacrifice of the oxen meant the acknowledgment that natural good - the good of use which man consciously performs when obedient to his spiritual duties - is really not his, but comes from the Lord. If, in the external of our thought, we shun our evils and cooperate with the Lord, dedicating to Him the skill and labor which appear as a product and purchase of our own, the Lord will care for the spiritual states which He can alone multiply and number and dispose in the secret courts of our spirit.

== Solomon Succeeds David

King David had grown old. His active life had taken its toll of his body, and as he neared the age of seventy his vital heat failed him even though he was covered with clothes. And his servants found a special nurse for him, Abishag, a beautiful virgin from Shunem, who cherished him and lay in his bosom to warm him. But the king knew her not.

This incident is told to show that David was too stricken to attend to affairs of state. For the sake of the spiritual sense, the emphasis lies on his lack of warmth. David represents the spiritual truth which rules in the spiritual mind - truth of the Word taken up from a man's memory by being transposed into a spiritual form, as spiritual ideas of which man is not aware, yet which enrich his spiritual conscience. But a man can see spiritual and even celestial truths in rational form; for every one is equipped to know and understand such truth if he only allows his thought to be elevated into spiritual light, apart from the prejudices of his proprium. Still, unless his will is at the same time raised into spiritual heat, his thought sinks back into merely natural light. (@DLW 258) A spiritual conscience is therefore powerless and incapable of ruling in man when there is no love for spiritual truth; as happens when the natural man plots a rebellion against the uses of charity. Then David is cold. For no amount of truths can make the spirit warm. And Abishag was called in, to represent an unattached and virginal affection which can for a time cherish, serve, and maintain spiritual life without itself being raised up to enjoy it.

---

Every man, as he grows old, becomes concerned about the future of his family and of the forensic uses which he must leave for other hands to carry on. As death approaches, life can be seen as to its whole drift, and essentials stand out in important relief, while other things sink back as insignificant. For man's ruling love is then settled, and its wisdom - such as it may be - has been harvested. He can discern past errors without passionately flying to their defense; he can more clearly see the principles which made his uses real. His last words, when fully attested, have a certain binding force upon his posterity - as a "last will and testament" which directs to a conclusion the work he had begun, and shifts its responsibility to younger shoulders.

The "last words" of David (cited in our last chapter) therefore prescribe that "he that ruleth over men must be just, ruling in the fear of God." (2 Samuel 23:3) David does not here name which of his sons would succeed him. But when he added, "he shall be as the light of morning when the sun ariseth, a morning without clouds, as the tender grass springing forth from the earth sparkling after rain" - he seemed to suggest the name of Solomon, which means "peace." And among his intimates it was known that Solomon was the king's choice. Yet Adonijah, an older son who had been born in Hebron, did not wait for his father's commands, but conferred with Joab and with Abiathar the priest (a descendant of Eli), and prepared chariots and horsemen and fifty men to run before him. And saying, "I will be king!" he invited the king's sons and the men of Judah to a feast in his house below Jerusalem. But Solomon, and Nathan the prophet, and Benaiah and his troop of mighty men who were David's bodyguard, he called not.

Now David was very fond of Adonijah, and had never scolded him or denied him anything. Adonijah was also a very handsome man, like Absalom before him. His attempted coup d'etat had apparently much the same spiritual significance as the abortive rebellion of Absalom - a rebellion of a state in the natural mind, an evil state based on a perversion of the sense of the letter of the Word. But Adonijah's rival was not David, but Solomon. Adonijah's prime intent was to prevent Solomon from ruling Israel.

The sacred text goes on to tell how this plot was frustrated. Nathan the prophet showed Bathsheba, the mother of Solomon, that only quick action could save their lives. Bathsheba then went to the king's sick bed, told him what had occurred, and reminded him of his promise that Solomon would inherit his throne. Nathan came in also, reinforcing her petition. And David, rallying his strength, called Zadok the priest and Nathan the prophet and Benaiah the captain of the "mighty men," and ordered them to let Solomon ride on the king's mule down to the brook Gihon in the valley below Mount Zion, and there anoint him, blowing the trumpet to proclaim him, with the shout, "God save king Solomon!" And the people who had streamed out of Jerusalem after him, piped with pipes and made enough noise to make the earth shake with the sound. Then all the guests of Adonijah, having just made an end of eating, were startled to find that their plot was nipped in the bud; and they fled in all directions, and Adonijah took refuge in the tabernacle, holding on to the horns of the altar until Solomon sent for him and put him on probation as long as wickedness should not again be found in him.

Shortly afterwards David was on his death bed. His charge to Solomon was to walk according to the law of Moses. But he also told Solomon to even the scores with Joab, who, while he had not gone with Absalom, yet had joined Adonijah's rebellion and had also murdered two worthy men; and with Shimei, who had cursed David; but to show kindness to the house of Barzillai who had befriended David in a time of need. Then "David slept with his fathers and was buried in the city of David."

---

Solomon carried out his father's last commands. His patience with Adonijah came to an end when Adonijah persuaded Bathsheba to ask Solomon to allow him to marry Abishag, David's virgin widow. Solomon considered this an impudent request, equivalent to asking for the kingdom. For it appears that an oriental despot inherited not only the throne, but his predecessor's harem. (Cp. 2 Samuel 12:8) Thus Solomon found occasion to put Adonijah to death. Abiathar was thrust out of his priestly office - the last of Eli's line. Joab - in accordance with the law of Moses - was slain even as he held on to the horns of the altar which he refused to leave. (Exodus 21:14) Shimei was killed for disobeying Solomon's command not to leave the city.

And so the kingdom was established in the hand of Solomon. It is plain that the bloody acts of retribution which marked the opening of his reign - and which find far more terrible parallels in the history of most monarchs of that time - in the spiritual sense represented the aftermaths of the judgment which had been signified by the wars and tribulations of David's lifetime; a judgment by which the natural man became subservient to the spiritual and by which hypocritical states as well as openly rebellious affections were removed from the life of the mind. For Solomon himself had the reputation of a man of peace - as his name indicated. And his spiritual role in the story of Israel is clearly shown in the description of his reign.

Solomon, like David, represented the spiritual mind which is opened, although man is unaware of it, during regeneration. But Solomon obviously represents an even higher degree of that mind, or that which is spoken of as the celestial or the interior rational. It is opened especially by "a love of the Lord from the Lord," a love of celestial uses. It is opened when a man has an aversion for evils. It follows, that with such a man not only is the rational regenerated, but also the lower natural. And we are told in the doctrine that few at this day are regenerated as to the sensual degree of the natural. (@AC 9726, 7442:4, @SE 4629 1/2) With the celestial man there is however a conjunction of the spiritual degree with the lowest natural. (@AC 1434) And in Solomon's reign this is represented even by the first thing told of him
- that he made affinity with Pharaoh, king of Egypt, and took his daughter to wife. (@AE 654[29], 33) For Egypt signifies the knowledges of truth and good, and indeed all scientifics about natural things and their causes. (@AC 5223[2], 5213e)

Solomon "loved the Lord," But he sacrificed and burnt incense in various "high places." And one of these places was at Gibeon. There he offered a thousand burnt offerings. And there the Lord appeared to him in a dream, and asked him what he wished for. Solomon humbly said that he was like a little child. He needed an understanding heart to judge the Lord's people. And God commended him for not having asked for long life or riches or revenge on his enemies. "Behold, . . . I have given you a wise and understanding heart ... I have also given you what you have not asked - both riches and honor . . ." And Solomon woke up - and behold, it was just a dream! But he arose, and came to Jerusalem and offered up burnt offerings there, before the ark.

His wisdom soon proved itself. When two women both claimed to be the mother of a child, he commanded that the child be divided by the sword; whereat the true mother was revealed by her willingness to give up the child.

His power grew. He appointed eleven princes (or cabinet members) and twelve provincial governors. "Judah and Israel were as many as the sand of the seashore . . . eating and drinking and making merry." At last it was a happy land! "Judah and Israel dwelt safely, every man under his vine and under his fig tree, from Dan even to Beersheba, all the days of Solomon." From the river of Egypt to the Euphrates, the kings of the border states brought him tribute. The daily rations of his court were huge, including thirty oxen and a hundred sheep "beside harts and roebucks and fallow deer and fatted fowl." And there were forty thousand stalls of horses for his chariots and twelve thousand horsemen! His wisdom excelled the wisdom of all the sons of the east and all the wisdom of Egypt! His fame was in all nations round about. He spake three thousand proverbs, and his songs were a thousand and five. He spake of trees, from the cedar of Lebanon to the hyssop that springs out of the wall; he spake of beasts and fowls and creeping things and fishes. (Cp. @AC 5223) And there came of all people to hear the wisdom of Solomon, from all the kings of the earth who had heard of his wisdom.

But much of the fame of Solomon is connected with his building a magnificent temple of Jehovah. This was done in fulfilment of his father's ardent desire to build such a house of God. David had not been permitted to do so, because he had been constantly involved in struggles with external enemies and with the foes of his own household. Now his son Solomon sent to Hiram, king of Tyre, who had ever been a lover of David, and agreed to supply Hiram with wheat and oil if Hiram would bring down timber of cedar and fir from Lebanon, shipping it on floats down the coast to Judah. Solomon's plan was not confined to the temple, for he needed also to build a "house of the forest of Lebanon" as a palace, and Millo, another house, for Pharaoh's daughter, and besides this he wanted to rebuild the wall of Jerusalem and reconstruct a great number of cities and rear up fortified store cities.

For these enterprises Solomon raised a levy of thirty thousand men who worked in shifts of ten thousand in the forest on Mount Lebanon, with another seventy thousand to carry and eighty thousand to hew. Solomon's builders and Hiram's artisans hewed costly stones and cut the timber to fit the plans.

Solomon had reigned for four years, when he began his seven year task of erecting the temple. Four hundred and eighty years had passed since Israel, a rabble of nomads, fled from Egypt. And twice four hundred and eighty years were to go by until the coming of the Lord.(*)

(*) We find ourselves in ancient times - at least a century before Homer sang, and two centuries before the legendary founding of Rome!

Solomon built his temple carefully and reverently, of stone made ready before it was brought thither so that neither hammer nor ax nor tool of iron was heard in the house while it was being erected. For Jehovah had promised that here He would dwell among the sons of Israel.

The house was sixty cubits (c. 90 feet) long and 20 cubits wide and 30 cubits high. There were windows of narrow lights, and a porch before it. Against the walls were additional chambers, in three stories all around the house, each story 5 cubits high. The floors and walls and ceiling were of cedar, the doors and posts of olive wood, part of the floor being additionally covered with planking of fir. No stone was visible within. All was cedar, carved with knops and flowers, and overlaid with gold. Two great "cherubim," of olive wood, each ten cubits high, were overlaid with gold and set in the sanctuary (or oracle), and the doors to this room were carved with cherubim and palm trees and open flowers.

Solomon's own house, "The House of the Forest of Lebanon," was larger, but its timbers were not overlaid with gold. Its foundation was of great stones sawed with saws, stones of eight and ten cubits each. The house had forty-five pillars of cedar, in three rows, and windows on both sides, and a pillared porch where Solomon had his judgment throne
- a throne of ivory, overlaid with gold, and with six steps guarded by twelve lions.

To do the brass work for the court of the temple Solomon imported a craftsman from Tyre, Hiram, whose mother was from Naphtali. He cast two great pillars with ornate chapiters of molten bronze, and a molten "sea" or basin, ten cubits wide and resting on twelve oxen; and also ten bases and ten lavers and pots and shovels. And Solomon also provided for the holy place a new altar of incense and censers and a table for the shewbread, and candlesticks, five on each side; all of gold.

And when these things were ready, the older furnishings of the tabernacle were put among the treasures of the temple. And Solomon assembled all the elders, tribal chiefs and heads of families in Jerusalem to bring the ark out of its tent on Mount Zion into its new abode. Now "there was nothing in the ark save the two tables of stone which Moses put there at Horeb." Solemnly the priests carried the ark, amid continual burnt offerings, and placed it beneath the wings of the cherubim, leaving the ark itself unseen in the darkness of the most holy, but with its staves protruding into the holy. place. And it came to pass that a cloud of the Lord's glory filled the house so that the priests could not remain to minister.

Then Solomon spake: "Jehovah said that He would dwell in the thick darkness." He turned his face to the congregation and blessed them and began his address of dedication. And then he spread his hands to heaven before the altar and prayed the prayer that forever placed him among the wise on earth: "Jehovah God of Israel: There is no god like Thee in heaven above or on earth beneath, who keepest covenant and mercy with Thy servants who walk before Thee with all their heart . . . Behold, the heaven and heaven of heavens cannot contain Thee; how much less this house that I have banded? ... Yet have respect unto the prayer of Thy servant . . . that Thine eves may be open towards the place of which Thou bast said. My name shall be there.... Hear Thou in heaven Thy dwelling place, and when Thou hearest, forgive!"

And when his long prayer was finished Solomon blessed the congregation and said, "The Lord our God be with us, as He was with our fathers; let Him not leave us or forsake us: that He may incline our hearts unto Him to walk in all His ways . . . that all the people of the earth may know that Jehovah is God and none else."

So Solomon dedicated the temple and the court and offered burnt offerings, and the feast that he gave to all the people lasted fourteen days.

---

Whence came all the wealth which Solomon thus poured out in public works and for private magnificence? The text tells of Pharaoh taking a city from the Canaanites and presenting it to his daughter; of Hiram king of Tyre supplying Solomon with gold, in ample return for some twenty small border cities. It tells of Solomon levying a tribute on the remnants of the Canaanitish tribes still living in the land. It also shows that Hiram supplied experienced sailors for a navy that Solomon built to trade in the Red Sea, and which brought gold from Ophir as well as precious stones and woods. But this was apart from what he received from trade and taxes and tributes and the revenue from the traffic lanes which he controlled between Africa and Asia. And when the queen of Sheba visited him to test his wisdom, she brought immense presents of gold and spices and jewels. It was no wonder that all king Solomon's cups and platters and utensils and even the shields and targets that hung in his hall were of solid gold; "none were of silver: it was nothing accounted of in the days of Solomon!"

---

This is the picture of the mind that has been opened even to the celestial degree and has been integrated so that the internal man is conjoined with the natural. The celestial is characterized by love to the Lord. This is represented by Solomon's building the temple and by the gold that abounded in his kingdom; also by the peace that prevailed in his reign, and the humility and wisdom with which he was endowed.

Solomon's kingdom clearly represents the state of the regenerate man - as well as the Church triumphant. In a still more sublime sense, this greatest of the kings of Israel is a type or a prophetic representative of the Lord in His glorified Human, as to His presence both in the celestial kingdom of heaven and in the spiritual kingdom of heaven. For as the Lord by His struggles of temptation fought against the hells and subdued them, so David's life was one of combat, resulting in a final victory. David at last defeated his external and domestic enemies, and at the end of his life Judah and Israel were for the first time united securely together, so that Solomon could rule over both. But Solomon stands for the Lord in His state of glorification. (@AE 654[29], @DP 245) For the Lord's glorification was finally effected when the Divine truth in His Human Divine was united with the Divine good, or the Divine Spiritual with the Divine Celestial; and by this final union, the Doctrine tells us, the spiritual kingdom and the celestial kingdom of heaven were conjoined. (@AC 3969[9])

The regenerate state of man is also pictured in the glorious reign of Solomon. The three houses which Solomon erected have their counterparts in the mind of the man of the Church. (@AE 654[33]) There is a spiritual mind, signified by the temple with its sanctuary, its holy place, and its courts - the celestial, spiritual, and spiritual-natural degrees from which man's final motives are inspired. There is a rational mind, signified by the "House of the Forest of Lebanon" where Solomon conducted the government and pronounced his judgments. And there is man's lower natural, the part of the mind where he collects the knowledge and experience by which love and wisdom are confirmed, - which was signified by Millo, the palace of Pharaoh's daughter. When the mind is so built and ordered that all these degrees and levels work in conjunction, because no evils disturb their harmony, a wealth of uses can bring increasing delight and the things of the world become the means by which the wisdom of heaven comes to its fruition.

---

David, for all his greatness, never measured up to Solomon. In David we see the manner by which spiritual truth is gradually established as a conscience which leads to the uprooting of hidden lusts of evil and of deceptive falsities. Yet this conscience - with the spiritual man - is, so far as man can discern it, only an imperfect refraction of the rays of the Divine glory in the clouds, even though it is truly the token of an everlasting covenant with the Lord. Therefore David, in his "last words," also meekly confesses: "Although my house be not so with God, yet hath He made me an everlasting covenant, ordered in all things, and sure; for this is my salvation, and all my desire, although He make it not to grow."

But through such a confession - which marks the summit of its illustration - the spiritual conscience can surrender its authority to a higher wisdom of life, springing from a celestial love of the Lord. An inmost conscience, or perception, which is celestial and interiorly rational, is then established, by which evils are judged at first approach, by sheer aversion. According to the literal story, David, having abdicated in favor of his chosen son, dies. But in a spiritual sense he is raised again, in a new form, as Solomon.

---

As is well known, David was a prophetic type of the Lord who was to come on earth. But the Word contains interiorly series within series of meanings, like wheels within wheels. Thus it is well to note that David and Solomon also represent the Lord in His second advent. For (as has previously been shown) King Saul represented the literal sense of the Word, specifically as understood in the Christian Church; and his life story shows how the authority placed in the letter of the Word was misused in the Church so that it could not defend itself against the falsity of "faith alone," signified by the Philistines. The spiritual sense of the Word, like the ark of the covenant, had already been lost and neglected. It was David, signifying the Lord in His second advent, who brought back the ark and replaced it in its tabernacle. The spiritual sense was restored and the Divinity of the Word again demonstrated by the publication of the Arcana Coelestia, in the years 1749 to 1756.

The statement is however made, that before the crucial year 1757 much of the communication between heaven and mankind had been cut off by the presence of evil spirits in the upper ranges of the world of spirits.
"Revelations for the New Church" could therefore not be made before a last judgment had purified the world of spirits. (@LJCont 12, LJ post. 134, @AE 1217) The Arcana indeed prepared the way for this last judgment, by disclosing the spiritual sense of the Word and thus displaying the interior evils of spirits and men. Yet the reception of this Divinely revealed spiritual truth was not possible before the last judgment. (@AC 32, 2121, 2123, 2242:3) In the Arcana Coelestia we find many anticipations of the coming judgment and many predictions of a New Church to come. In it, the spiritual sense of the Word is, like the ark of the covenant, recovered, recognized and returned into its holy tabernacle. Within its expositions, or appended thereto, are contained the doctrines of heaven - truths in full unity with the Doctrine of the New Church later published. Still this Doctrine is not yet given in categorical organized form addressed "for the New Church." The ark of the new covenant - in the Arcana - dwelt as yet within curtains, in its holy tabernacle; but the temple had not yet been built.

The tabernacle and the temple were both the abode of the same sacred ark. But it is noted in the Apocalypse Explained that "the tent of meeting was a more holy representative of the Lord, of heaven, and of the church, than the temple." (@AE 700[33]) And similarly, that Divine truths such as are of the spiritual sense are called holy only when they are in their ultimate in the sense of the letter. (@AE 1088[2])

The life of David as a king, with its wars and civil commotions, together with the final retribution that overcame his enemies after his death, displays significant parallels to that last judgment which was being precipitated in the period during which the Arcana Coelestia was published; a judgment by which order was restored in the spiritual world.

And who can fail to see the likeness between the temple of Solomon and that holy city, New Jerusalem, which in the book of Revelation is described as descending from God out of heaven, and which signifies the Doctrine of the New Heaven and the New Church. The temple of Solomon with its adjacent palaces represented the organized doctrine "for the New Church" - written and published as a rationally consistent system of teachings immediately after the last judgment of 1757, in volume after volume, - Heaven and Hell, The Last Judgment, The New Jerusalem and its Heavenly Doctrine, The Doctrines of The Lord, The Word, Life, and Faith, and many others, culminating in the True Christian Religion.

All the vessels of the tabernacle were brought into the new temple. All the truths of the Arcana Coelestia are found as intrinsic parts of the Doctrines later published. David was not himself permitted to rear the temple; but he had gathered treasure and material to be used in the project. (1 Chron. 22) It was for Solomon to add to this and build the temple and dedicate it for the use of the church.

And as Solomon excelled the wisdom of the east and the wisdom of Egypt, so do the Writings rest spiritual revelation upon natural truth, both symbolic and factual. The temple was made of cedar of Lebanon, which signifies rational truth - that truth which interprets human experience in the light of heaven. And the foundations of the temple - its stones and timber - though hewn beforehand as if by Divine foresight, were fitted together so that neither hammer nor ax or any tool of iron was heard in the process of building. For in the Writings are imbedded the truths of all the ages - the truths of ancient perception restored, the forgotten doctrines of the Ancient Word, the symbolic commands of the Mosaic law, and the surviving highlights of Christian faith; even as the New Jerusalem stands on twelve foundations garnished with precious stones - the open truths of former revelations.

And this universal aspect of the Writings and of the New Church is reflected in Solomon's relations with all the countries round about. Israel became the center of commerce, the focus of wealth and wisdom. And we are instructed that the angels are as it were blind to the decadence of Solomon in his later days when he took seven hundred princesses for wives and three hundred concubines and set up shrines to all their gods; for in these extravagant trespasses the angels only perceive a symbol of the Lord's universal mercy and love toward the well-disposed in every religion, who live in mutual charity according to their lights, and who constitute in His sight one universal church and are joined with invisible bonds into a human form of uses - a Grand Man in which those serve as the heart and the lungs who have the Word of God and thus can know and worship the Lord in spirit and in truth. Hence we read:

"Because the Lord, after the glorification of His Human, had power over heaven and earth (as He Himself says in Matthew 28:18), so Solomon His representative appeared in glory and magnificence and possessed wisdom above all the kings of the earth, and also built the temple. Furthermore, Solomon permitted and set up the worship of many nations, by which are represented various religions in the world. Similar things are meant by his wives, seven hundred in number, and by his concubines who numbered three hundred (I Kings 11:3). For a "wife" in the Word signifies a church, and a "concubine" a religion . . . " (@DP 245)

---

Let us not think that Saul or David or Solomon or any other man could maintain a life good enough to give a picture of the Lord's Divine perfection. But the Word has many levels, and what appears in its literal sense has also its Divine intent - not only to reveal the weakness and failure of man, the depths of evil which we seldom recognize in ourselves, but also to manifest the infinite mercy of the Lord.

That the three kings of United Israel each had the seeds of greatness, it would be ungenerous to deny. The pious man reads their story with sympathy, knowing that all greatness and virtue can represent and prophesy something Divine.

But when the prophecy is fulfilled, the representation fades and shrinks back into its human dimensions. And so, when we see the glory and the scope of the New Jerusalem and feel the presence of the wisdom of God in the Divine Doctrine in which the Lord again dwells with men, we see a glory that is not from man and know that One greater than Solomon is here.
