= Sermons on the Ten Commandments (vol 1)
By Alfred Acton    1914-1918
include::../template-attributes.adoc[]

ALFRED ACTON + 
Written for the New Church + 
Soldiers of the Great War + 
1914-1918

Vol. I  + 
Bryn Athyn, Pennsylvania
----
THE FAITH OF THE NEW CHURCH

There is One God, and the Lord, the Saviour, Jesus Christ, is that God.

The Sacred Scripture is the Word of God.

Man is saved by shunning evils as sins against God.

The Lord has made His Second Coming by revealing the internal sense of the Word in the Writings of Emmanuel Swedenborg.

On this revelation is to be established the New Church signified in the Revelation by the New Jerusalem descending from God out of heaven.
----
Published by + 
THE ACADEMY BOOK ROOM, + 
W.H. ALDEN, Manager, + 
Bryn Athyn, Pa.

<<<

== I. LOVE TO THE LORD. 

Deuteronomy 6:1-15; Mark 12:28-40; @HH 2,6.

And thou shalt love the Lord thy God with all thine heart and with all thy soul and with all thy might. (Deuteronomy 6:5).

These words occur after the giving of the laws and statutes to the children of Israel, and they are as it were a summary of all those laws. Hear, O Israel, the Lord our God is one God, and thou shalt love the Lord thy God. This is the first commandment, the universal commandment, the first thing in the regenerate life - to acknowledge God, and, with Christians, his means to acknowledge the Lord Jesus Christ.

What is this acknowledgment of the Lord? and why is it so important? Acknowledgment of the Lord is essentially the acknowledgment of a Master; the acknowledgment of One whose will is to be obeyed; whose law is to be the rule of life. Every man acknowledges some God; even the devils of hell acknowledge a God and also actually worship him. But the important thing is, who is the God that is acknowledged,whether it is the Lord who gives the commandments obedience to which leads to the happiness of heaven and of human society; or whether it is the acknowledgment of some evil end as the rule and guide of life. The evil do acknowledge a god, but their god is the guiding principle of their life; it is that which they love above everything else; it is that which really dominates all their thoughts and actions. Sometimes this god is the love of self; sometimes it is the love of the world or of pleasure, -- but whatever it is, this god is the ruler of their life. In the spiritual world, devils who have acknowledged such evil god on earth do the same in the societies of hell. But there their god is personified as one of themselves (or it may be even themselves) who is the most powerful and commanding exponent of the evil love which is their delight.

You will see from important it is to acknowledge God; how important it is for one at the beginning of life to determine that he will acknowledge the Lord. This determination will enter into and color the whole of his life, -- color it for eternity. Such acknowledgment means that with his mind he looks to the Lord and resolves that the commandments of the Lord shall be the rule of his life; resolves that when his own loves and desires go against the commandments go against what the Lord teaches, then that he will obey the Lord and not his own desires; and that he will pray to the Lord for help to do this work.

It is well for every young person, and of course the old also, to have the importance of this acknowledgment in active thought; to, as it were, say to themselves, I acknowledge the Lord; I will read His Word; His law shall be the rule of my conduct, private and public. Such an acknowledgment is an ultimate in which there is power; an ultimate which can rest in the memory as something to which one can ever look in times of trial and doubt and difficulties, and in looking, can remember that the Lord is his God and that that he must be a faithful servant.

To acknowledge the Lord is for the Christian the first of religion. The words which me have taken for the text teach us how this acknowledgment is to be a real acknowledgment. Three words are used to describe the acknowledgment. We are to love the Lord with all the HEART, all the SOUL, and all the MIGHT. If we understand what is meant by these three expressions we shall understand the nature of genuine acknowledgment of the Lord.

The HEART, as is known to everyone, means the love. All our love is to be in the acknowledgment of the Lord, that is, we are to love to acknowledge Him; we are not to have any other ruling love than the desire to obey Him. ALL the heart must be in the acknowledgment. Now man has a great many loves. He has the love of eating and drinking; the love of ease; the love of study; the love of fame; the love of doing kindness; the love of duty; the love of country, and so forth, all these loves are from his heart, and all of them must acknowledge the Lord; that is to say, all these loves must acknowledge that they are in order, that they are good for us, only when they are under the rule of the Lord. The practical lesson here given is that when from love we desire to do a thing, -- or desire to enact it in our imagination,then we shall cease to do it if we know that it is contrary to the Lord's Word. When we do this, then that love which we thus subdue, that desire which springs from the love, is made to acknowledge the Lord. This is what is meant by loving the Lord will ALL the heart.

By the soul is meant in the Hebrew, spirit or breath: and because the spirit or breath proceeds from the lungs and is the means of expressing thoughts by means of speech, it therefore signifies the understanding from which all thought comes. We are to love the Lord with all our understanding; with all our thoughts. What this means is clear, namely, that we are not to allow our thoughts to go against the Lord; not to blaspheme His name with our lips. It means that me are to think straight concerning the Lord and concerning the Word, and not to allow our thoughts to he twisted and warped by evil desires. It means in a word that we are openly and plainly to say in our thought and to confirm with our understanding that the Lord is the only God.

The last of the three phrases is With all thy MIGHT, or strength. This is the last and also the ultimate in which are contained the two that precede. It therefore refers to the deed. All strength or might is from interiors, but it does not become strength until it has actually come into the deed of the body. We are to work from acknowledgment of the Lord, and work means actual doing. We do not love the Lord with all our heart or love; me do not love Him with all our soul, unless se also love Him also with all our might, that is in our actual life. All three are important, but not one of them can exist without the other.

What is this ultimate? It consists in all the things which are actually done by a man. Going to church; reading the Word; thinking at times about the state of one's life, about the road on which one is travelling; shunning evils as they come up in the daily life, -- all these are meant by with all thy might, for these deeds show the strength of the heart, and soul, in them the heart and soul enter into their power.

There are some who live a good life in externals and yet do not acknowledge God. But with such men there is not the strength to resist evils always; there is no deep and abiding principle; when evil seems to them to be for their advantage, there is nothing in them from which they will shun it; and still less will they shun evils in their imagination. But if a man acknowledges the Lord with heart and soul and strength, he will have One before his eyes who will guide him in all circumstances, and guide him to shun evils as sins; -- not only the actual evils of the body, but also and still more the evils of the intention.

And therefore when the Lord came on earth he repeated this commandment, and he called it the first or great commandment.

And Jesus said The first of all the commandments is, Hear O Israel, the Lord our God is one God; and thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength. This is the first commandment. And the second is like. There is none other commandment greater than these.

== II. LOVE TO THE NEIGHBOR. 

Deuteronomy 6:1-18; Mark 12:28-43; @HH 18.

And the second is like, namely, this, Thou shalt love thy neighbor as thyself. There is none other commandment greater than these. (Mark 12:31).

In giving the two great commandments the Lord cites from the Law and the Prophets, and sums up, as it were, the whole of their teaching; for He says, On these two commandments hang all the law and the prophets, (Matthew 22:40), and by the law and the prophets is meant the whole Word as it had been given to the Israelitish church.

The commandment respecting love to the Lord is cited from Deuteronomy 6:4-5; and the commandment concerning love to the neighbor, from Leviticus 19:18, Thou shalt not avenge nor bear any grudge against the children of thy people, but thou shalt love thy neighbor as thyself; I am the Lord.

It will be seen therefore that in giving the two great commandments the Lord was not giving something that had been unknown before. And yet there is a great difference between those laws as understood by the Jews and as taught by the Lord. With the Jews the command to love the Lord thy God was understood as meaning to be faithful to Him above other gods; to observe the rites and ceremonies laid down by the Law, to obey Him in all the civil and moral laws that had been laid down for the government of the people. The Jews were not strictly a monotheistic people. They did indeed worship only one God, but they did not believe that He was in truth the only God. They believed that there were other gods, called by them the gods of the nations; and that these were also truly gods; but that their God was the most powerful of the gods. Hence they called Him God of gods. This is the reason why, when they were in adversity or in great prosperity, they so often deserted the worship of the Lord and took up the worship of the other Gods. Therefore in the New Testament the commandment is repeated, and the Lord adds that This is the first and great commandment; moreover, He directed the thought to the Lord in His human now revealed before their eyes, as the God who is to be loved with all the heart and soul and strength. And this involves the loving of His words as given in the New Testament.

The commandment to love the neighbor was also given to the Israelitish Church; but as will be seen from the passage in Leviticus where it is given, it is stated apparently in an incidental way; and, while attentive reading will show that all the teachings of the Old Testament involve the command to love the neighbor, it will also show that the Jews more and more understood this commandment as being a command to observe strictly the justice of the civil law in their dealings with the neighbor. Therefore, in the New Testament, the Lord repeats this command, and lie adds, None other commandment is greater than these two.

The two great laws had indeed been given to the Israelites but they had buried them by their traditions, that is, they had lost the real truth of the Laws by their false understanding of them. Therefore the Lord in His appearing to men on earth repeated these two as the great laws of the Christian life.

We have already considered the first law, to love the Lord; it now remains to consider the second, which is love to the neighbor.

Two things are evident. I. That love to the Lord is one thing and love to the neighbor another. 2. That these two loves cannot be separated, i.e., that neither can exist without the other. Love to the Lord is, externally, faithfulness to Him by the reading of His Word, the attendance at worship, prayer to him in private, and obedience to His commandments. Internally it is to keep as sacred in the mind and heart all thought of the Lord; to keep as supreme in the thought when one is by himself, the idea that His commandments are the law of life. Inmostly it means that the mind is to be directed to the worship of the Lord Jesus Christ as the creator of the universe.

Love to the neighbor is involved in obedience to the Lord; for throughout the Word runs the universal teaching that we are to consider the good of the neighbor and not our own selfish interests, and that we do this if we obey the commandments. The two laws ire therefore bound together as one. On the one hand, we must love the Lord; on the other if we obey His Word we love the neighbor.

The leading idea here is that there can be no love of the neighbor unless there is love to the Lord, and this is the idea we would impress in the present address, leaving to the future the consideration of who is the neighbor.

Anyone, from common perception, may know what loving the neighbor is, namely, that it consists in doing good to him, in helping him when in distress, in not injuring him either in body or in name, etc. But, what is not known to all, is that even the evil can love the neighbor in this way, and that only those who love God, and, with Christians only those who love the Lord, can truly love the neighbor.

There is a certain natural good implanted hereditarily in some men, and acquired by nearly all who have been brought up to be good citizens. From this good, whether hereditary or acquired, they are not indisposed to help others. It is this good that makes us feel pity at the sight of distress; that gives us at times a feeling of generosity and magnanimity; that makes us sometimes even deny ourselves. Yet all this can be done by the evil, that is, by those who do not shun evils as sins against God. Anyone of you may know this if he will only reflect on his own life. How often have we felt pity, and yet the next moment harbored evil lusts in our imagination? how often have we felt the generous impulses of friendship, and yet practiced deceit in hiding from others our wrong deeds? It is true that these generous feelings, this pity, is apt to diminish as men grow old and their heart becomes more selfish and hardened. But the essential point is that there is a difference between love to the neighbor which springs from obedience to the Lord, and love to the neighbor which springs from any other source; and also that love to the neighbor may exist, or rather may appear to be with a man, even when interiorly he delights in evil.

The love to the neighbor that is not from love to the Lord, comes to a man either naturally, or by training, or by imitation; it is the path of least resistance. But the love of the neighbor that comes from love to the Lord always has its origin in combat against one's own evil and selfish loves. Easy come, easy go is true in spiritual things as well as in natural. That which we do with little effort counts as little; but that which we do with effort and labor becomes very precious to us. To truly love the neighbor is to act with him from justice; to be willing to excuse him; to be unwilling to injure him; and to do this because you will and desire and pray to be obedient to the Lord. Let me give one or two illustrations. He who refrains from swearing and in the refraining thinks that he should not injure others by leading them into this habit, shows love to the neighbor. So also he who in a school shuns disobedience to its laws, and shuns also deceit, and this because he fears to injure the school and those who are engaged in its work; also he who in his dealings with this fellow men shuns dishonesty, because he fears to injure others, shuns lascivious thought and conduct because he fears to injure the chastity of women, or to destroy the sweetness of conjugial love. All these acts are of love to the neighbor.

Your neighbor is your fellow student, your teachers, your parents and guardians, your country, and your fellow members of the Church; and to all these you who will show love, that is, the sincere desire to do good to them and not to do evil to them, only so far as you love the Lord, read His Word, and pray to Him for help to obey it.

== III. WHO IS THE NEIGHBOR? 

Leviticus 19:13-18; Luke 10:25-37; @HH 15-16.

And thou shalt love thy neighbor as thyself. (Mark 12:31).

In the former discourse on these words we spoke of the general, teaching involved in these words; we now propose to enquire who is the neighbor that is to be loved. This question was asked of the Lord by a Jewish lawyer to whom the Lord had just given the law as to love to the neighbor. This law had already been given to the Jews by Moses: Thou shalt not bear any grudge against the children of thy people but thou shalt love thy neighbor as thyself. (Leviticus 19:18). But the children of Israel, in order to justify their merciless and often cruel conduct to the stranger, interpreted the neighbor in this commandment to mean the same as the children of thy people, i.e., to be strictly confined to their fellow Israelites. So this lawyer, willing to justify himself, said unto Jesus, And who is my neighbor? Having the idea of neighbor as being merely the orthodox Jews he supposed that the Lord would answer the question in no other way; and he was conscious that his conduct to his fellow orthodox Jews could not be questioned. He therefore asked the question with confidence that the answer would justify him as one who kept the two great commandments.

In answer to this question the Lord told the parable of the man who fell among thieves. It is not necessary to here repeat the parable as you all know it well. But I will can your attention to the closing words in which the Lord asked a question. Which now of these three thinkest thou, was neighbor to him that fell among thieves? And the lawyer said, He that showed mercy on him. Then said Jesus unto him, Go, and do thou likewise. (Luke 10:36-37).

It will be noted that the question, and, in fact, the whole parable is contrary in its spirit to the modern conception of who is the neighbor. The modern conception is that all who are in distress are your neighbor if you are able to help them. But this is quite evidently not the Lord's teaching in the parable. Had this been the teaching the parable would have treated, not of the attitude of three men to one in distress; but of one man and his attitude to various men including one in distress. And the final question would have been, not which of the three men whose attitude was described, is the neighbor; but which of the various men was the neighbor to the one whose attitude to them hall been described.

But the Lord's question was so put that it could receive only one answer. Which was neighbor to him that fell among thieves? The Samaritan, of course. But note that according to the modern conception it is the one who had fallen among thieves, that is the neighbor; for the prevailing thought in the Christian world is that one who is in distress and whom you are able to help, -- that such a one is the neighbor. The Lord however so put His question that the only conceivable answer was the true one, namely, that the neighbor is the one who does good.

Here is a new conception of what is meant by the neighbor. The one who does good, that is who loves the Lord and from love obeys the commandments. This is the neighbor, who is meant in the command, Thou shalt love thy neighbor as thyself.

To love the neighbor according to the modern conception of neighbor is not a difficult thing. For this purpose society has organized charities, and it is well known that there is far less chance of deceit when help is given through good societies than when one undertakes to give to the poor oneself. And if we understand by the neighbor the one who lives near us, or who is near us by ties of relationship, it will readily be seen that to love such a neighbor does not involve anything of the spiritual life. A man might love his neighbor in this sense from a thousand and one different motives. In fact, this conception of the neighbor involves the common saying, charity begins at home, -- a saying which is usually filled with the spirit of utter selfishness; a saying which involves that oneself is the nearest neighbor who is to be loved. And this is indeed the idea, though perhaps not the conscious idea, of all who are in evil, i.e., who do not shun evils as sins against God. They love themselves above all things; their own pleasures and satisfactions more than the commandments of God or the laws of men; and if they obey the latter and train themselves to do so until it has become a habit, they do this from fear of the law or from hope of reward from the world. They never obey the commandments of God; for these can be obeyed only when they are obeyed in the spirit. To such men, themselves are the nearest and dearest neighbor; and nest come their friends and relatives; then their city, state, and country; then the church; and lastly heaven and the Lord. Such men have the spirit of jingoism which will boast of their country and uphold whatever it does whether right or wrong, -- and yet who love themselves more than their country. Such men will perhaps boast of their church and its doctrines and worship; will be filled with the spirit of enthusiasm at its name; and yet love themselves more than the Church; nor do they willingly give up anything. for the sake of the church. Such men may proclaim belief in the Lord, and may even themselves think that they love the Lord; but they do not give up any evil of thought, intention, and imagination because of His commandments. No! themselves and their loves are the principal neighbor; just as, to the children of Israel, their fellow Israelites were the only neighbors whom they were commanded to love.

It was against this falsity that the Lord spoke in answer to the question asked by the Jewish lawyer who wished thereby to justify himself. And in the answer the Lord teaches that the neighbor is not the man in distress but the man who is in good, in charity, and this from an upright and sincere heart. It is such a man then whom the Lord meant when He said, Thou shalt love thy neighbor as thyself.

Now if you will reflect you will see that it was not the Samaritan as a man that is meant, but the Samaritan as to his goodness, i.e., as to his obedience to the commandments of religion. Abstractly therefore the neighbor is not the man, but it is that good, truth, and mercy that comes from the Lord. And if you reflect a little more deeply you will see that this involves that it is the Lord who is the neighbor in the highest sense. Indeed it is plain to be seen that the Lord Himself is the good Samaritan. He came to the world which was as a man fallen into the hands of the wicked leaders and priests of the Jewish Church who had robbed him of all his goods; and the Jewish religion represented by the Pharisee and the Levite who passed by, was of no avail,indeed, had not the will,to help. But the Lord came and restored to man the truth of the Word which had been taken away; and after His resurrection He left the Church in charge of the Apostles,innkeepers, as it were, who were to care for the man who had been robbed but who now was restored to health, until such time as the Samaritan should come again, that is, until the second Advent.

It is plain that the Lord is the neighbor; and if we follow up this thought we shall arrive at a conception of the neighbor entirely contrary to that which was described as of the evil man. The Lord is the first neighbor; He is to be loved and obeyed above all things. Then comes heaven and the church; we are to love the church because there the Lord is preached and the doctrine of truth; and this love to the church involves the willingness to die for the church, i.e.. to kill, put away, everything that is destructive of the church and its growth among men. Then comes the country. this we are to love more than ourselves, and be willing to die for it and above all be willing to be good and upright citizens, and unwilling to injure the country by lawlessness. Then comes one's State and city, associates and friends and relatives; and finally, and in the last place, oneself. Self is in the last place because regeneration consists in making oneself the servant to the Lord and obedient to His laws which are the laws of religion; and the Lord is in the first place because regeneration consists in laying down the life of evil because it is against His commandments. Ye are my friends, (says the Lord), if ye do whatsoever I command you. (John 15:14).

== IV. THE TEN COMMANDMENTS. 

Psalms 33; Revelation 22:1-7; @TCR 33; or @HH 117-118.

And God spake all these words saying.

As we have examined the two great commandments on which hang all the Law and the Prophets, I propose now to enter upon an exposition of the ten commandments. In these commandments, we are told, and the matter is in itself evident enough, are contained all the laws of life; and, having considered the two great universal laws of life, -- love to God and love to the neighbor, -- we may now consider the application of these universals to the great laws of the Decalogue.

In the Hebrew the first of the words which we have taken as text is, And spake; and the word spake is simply the verbal form of the Hebrew for word. Very literally the text might be translated, And worded God all these words, saying.

Word, then. is the leading idea, because the first expressed. And here we note that Word is the leading idea, that is, is the first idea expressed, in both testaments. In Genesis the leading idea is creation by speech: And God said, Let there be are the words that precede the creation of each day. In Matthew the leading idea is the delivery of the book of the generation of Jesus Christ, and by the book is meant the Old Testament or prophetic Word, so called because it prophesies the coming of a Messiah or Saviour. It is this Book of the generation of Jesus Christ that is first spoken of, because the New Testament is the record of that Book or Word made flesh. The burden of the whole testament is the Divinity of the Lord and the exhortation to receive Him; the teaching that He is the only God of heaven and earth. It is true that there are passages that seem to suggest two Gods; but it is also most patently true that, taking the New Testament as a whole, reading it with the view of receiving its universal message, one cannot justly do other than affirm that its one great teaching is that the Lord alone is to be loved, obeyed, and worshipped. And therefore the testament commences with the Book of the Generation of Him who is and was the Lord. This is openly taught in the opening words of John: In the beginning was the Word, and the Word was with God and the Word was God.... All things were made by Him and without Him was not anything made that was made.

The leading idea of both Testaments then is creation by the Word of God. This is referred to in the saying of David, By the Word of the Lord the heavens were made, and by the spirit of his mouth the host of them. (Psalms 33).

In the opening verse of Genesis the leading idea is the creation of a world on which man call dwell to whom the Lord can give the blessings of His love. But the opening verse of Matthew, and still more plainly the opening verse of John, introduces to the new or spiritual creation made by the Lord in his coming in the flesh. He was to create a new heaven and a new earth, by which is meant a new Society of angels in the spiritual world, and a new Church on earth. Matthew and John first tell of the former creation, and then proceed to present to view Him who in the beginning was the Word whereby all things were created, and who now is come in the flesh that he might create a new spiritual world or kingdom wherein the heat and light of the spiritual sun would produce a new and spiritual paradise, -- would build up a new mind with new thoughts and affections:

This was the work of the Lord when He came on earth. The churches before the advent had worshipped an invisible God, who nevertheless had been represented to them by correspondential images; and hence the churches of that time were called representative churches. But when the church had sunk to so low a level that none could be found to keep, and teach, and interpret the Word which God had revealed through his angels through whom he had spoken with when there was none to understand, and danger threatened that all knowledge of God would be lost from the earth, -- then the Lord came, in order that He might build up and create anew, it were, the mind of man, and establish on firm foundation the knowledges and acknowledgment of God, -- for on this faith and acknowledgment rest all interior thoughts and affections, even as the new heaven rests on the new earth. By this means a new Church was formed which served on earth as a new and more firm foundation for the continued growth and enlightenment of heaven. For heaven rests on the Church even as the mind rests on the body; neither is independent of the other; both come into fuller and more complete life only by means of the other. Therefore, angels and spirits still are associated with men on earth; and, therefore, also when the Lord had made His Advent in the flesh, and thus established a church which should worship Him as the visible God of heaven and earth, the prophecy of Isaiah was fulfilled which says, And the light of the moon shall be as the light of the sun, and the light of the sun shall be as the light of seven days, when the Lord healeth the breach of His people. By the sun is meant Heaven, and by the moon the church.

And because the Lord by coming on earth and teaching the Divine truth from His own mouth, thus created a new heaven and a new earth, therefore in glory of Him was sung the song of the elders in the spiritual world, Worthy art thou, O Lord, to receive glory and honor and power; because thou hast created all things, and by Thy will they ARE and WERE created. (Revelation 4:11).

We have dwelt at this length on creation as being effected by the Word, because this is the leading idea of the words that introduce the Decalogue. It can he shown, if time permitted, that the actual creation of the world was effected by the breath or spirit proceeding from the Lord the creator, or, to put it in a way more easily understood, by the proceeding as living atmosphere, from the Spiritual Sun. But for our present purpose it is sufficient that it be seen that the mind is formed or created only by Words. A word. however, does not mean an atmospheric motion; a word is a thing, THE thing indeed, -- the real and spiritual thing which the writer expresses in printed words, the orator in the spoken word, the painter in the words of his brush, the musician in the words of his harmonies. A word is the thing, the spiritual thing, which, as a matter of fact, is usually conveyed to us by the spoken or written word.

And a word is a thing because it creates, that is, it forms the mind of man.

Every influence that comes to the mind, forms and frames it; and as it is formed, so it receives or rejects life from the Lord. Every image we receive through the senses actually changes the state of the mind. If we sensate something, a word, a feeling, or any other thing, and find the sensation; delightful, we strive to repent the change of state induced by that sensation; and if we do this often it becomes a habit and a veritable part of our very own mind. Happy are we if the mind is thus created and formed by the Word of the Lord.

The Decalogue contains the ten Words which comprise in general form, all the Words or Things that go to build up the spiritual life; and we are happy if we heed those opening words, And God spake; that, -- even as, when He spake in the beginning of time, worlds were formed by His speech, and on them the kingdoms of nature and man, -- so His Word in us shall create, first the dry earth of mere obedience, but an earth potent for the coming life; and then the beauties of new ideas, new thoughts, perceptions, delights, which shall beautify and people that earth and be blessed. It is by the commandments, and obedience to them as the Laws of God, and by this alone, that the prayer can be fulfilled, Create in me a new heart, O Lord, and renew a right spirit within me.

== V. THE LORD. 

Exodus 2:1-14; Luke 6:41-49; @TCR 23; or @HH 530.

I am the LORD thy God who brought thee out of the land of Egypt, out of the house of bondage. (Exodus 20:2)

In the natural sense these words were specifically addressed to the Israelites, and were to remind them that the God who spoke the commandments that follow is the same God who had delivered them from slavery and oppression. The Israelites were an ignorant people, and, as their future history shows, were easily led off into the worship of other gods. Few if any of them had any idea of the One God except as being the most mighty of the Gods; and, therefore, they called Him the God of gods. The commandment, therefore, was given them that they might know that it was the great God who gave these laws and who must be obeyed. It was for the same reason that the commandments were given with so many miracles and with such impressive preparation of the people.

As a fact, the laws given in the ten commandments were known to all nations in some general form. What nation did not and does not know that one must worship God? must reverence the things connected with that worship? must not kill, commit adultery, steal, lie? The Israelites also must have known these things. Indeed as to one of these laws we have direct evidence of their knowing it, in the fact that when Moses reproved one of the Hebrews, the man angrily threatened to report to the authorities the fact that Moses had killed one of the Egyptians. (Exodus 2:14) But they knew them, not as the commandments of their God but as the laws of the Egyptians; and they were now revealed to them with wonderful miracles, that they might learn that these laws were the laws of their God and the laws of their religion. Had they obeyed them as such their lot would have been prosperous in the land of Canaan. But they proved to be continually rebellious and disobedient, and the consequence was that they were taken captive by the Babylonians, and never again attained to their former freedom.

This is the great lesson of the giving of the commandments, -- that they reveal to us that the laws which rule in civil and moral life in Egypt, as it were, must also be observed as the laws of religion. The laws of moral and civil life are derived from the Decalogue; but they are enforced either by law, or by the conventions of society. And they are enforced because men see that no society would be possible without their observance. Hence we have governors, laws, and police. And hence also every child is brought up to know that the laws of the Decalogue must be obeyed; and this even though he had never heard of the Decalogue. Moreover, self-interest, training, the fear of censure, or even punishment by the world, all tend to keep a man in the observance of these laws. Honesty is the best policy well illustrates the matter; for it is indeed true that to keep the commandments is the best policy in a world whose laws are based on those commandments. And so it is that most men do observe those laws, or profess to observe them, so far as their actions and speech before the world are concerned.

But just as with the Israelites the laws that had been known to them in Egypt were repeated from Mount Sinai in order that they might know that these laws were also the Laws of the God who had led them from Egypt, and that they must observe them as His laws if they would come into the promised land; so is it at the beginning of regeneration with every man.

Every one has learned the morel and civil life, so far at any rate as concerns the sight of the world. The great average of men do not kill, or steal, or lie, or commit adultery; and even if some of these evils are more common than others, it is still acknowledged that they are against the interests of society, and, at any rate, they are done more or less surreptitiously.

Therefore it is, that the young man and woman at the beginning of life has been trained more or less to an observance of the moral law. But the beginning of religion, the beginning of the Church comes when this law is revealed to him as the law of God. And so the first thing of this revelation is. And GOD spake all these words,---by which, as we have already seen, is meant that the truths that are to reform the mind and as it were create it anew, must be truths from God.

Following this. the commandments open with the declaration of who the God who speaketh is. It is Jehovah thy God who brought thee out of the land of Egypt, out of the house of bondage.

By Jehovah thy God is meant the Lord Jesus Christ. He is called Jehovah as to the Divine good which is the cause of the creation of the universe; and He is called god as the Divine truth which was the Word by which all things were created. That this Divine Good and Truth is the Lord our Saviour, is plain from a mere reading of the Old and new Testaments. The great universal lesson running through them is that Jehovah would descend upon the earth to become the Saviour, and that the coming of the Lord Jesus Christ is the fulfillment of this prophecy. I will note only that great law given in Deuteronomy, Thou shalt love Jehovah thy God,a law which the Lord repeats and changes the word Jehovah to Lord,and this because Jehovah was then in the flesh present as Emmanuel God with us.

The first law of regeneration then is to acknowledge the commandments, the laws into the doing of which we have been more or less trained, -- to acknowledge these as the commandments of the Lord, -- and, according to the latter words of the text, -- of the Lord who is the Deliverer or Saviour.

In the Hebrew language the tenses of the verb are extremely weak; that is to say, a verb in any given tense might equally well be translated in any other tense. The origin of this peculiarity lies in the nature of those celestial people of earliest times with whom Hebrew was first spoken; for because they were in correspondences, a verb to them represented the operation of the Divine Truth, and this they knew is the same in the past and the present and the future. To the Israelites the Go who spoke from Sinai had performed the deliverance from Egypt, and they were commanded to obey him in order that this work of leading them into the promised land might be completed.

To deliver from Egypt is to deliver from being immersed merely in the things and interests of the world and the flesh. The flesh pots of Egypt has become a common expression, but it is not known that by Egypt in the Word is signified the sciences and knowledges of the natural man, i.e., sciences concerning natural things, and the affections of such sciences.

By the house of bondage is meant the state of mind in which man is a mere slave. A house in the Word always represents the human mind. Thus we read, Except the Lord build the house they labor in vain that build it. (Psalms 127:1) Again, we have the parable of the man who built his house on a rock or on sand. The house of bondage, therefore, means the mind where man is not free but a slave; and since the human mind in itself cannot be made a slave by others, -- for no one can prevent another from thinking, and also doing in his mind whatsoever he pleases - it is evident that the house of bondage is a mind which is ruled by evil affections, or by mere appetites, lusts, and concupiscences. Such a mind is not free, but is a slave to its passions.

Now at the very beginning of the regenerate life the young man or woman must listen to the commandments of the Lord Jesus Christ; and he must acknowledge the Lord as the One who has delivered Him from Egypt and bondage; i.e., who not only has given him the faculty of understanding and choosing, but also Revelation whereby he has learned concerning spiritual things, and thus been prevented from entirely immersing his mind in mere worldly matters. In its application to you whom I now address the words mean acknowledgment that the Lord has so guided your life that you have learned that there are treasures other than the riches of Egypt; and that He has led you by various ways, internal and external, to arrive at your present state in life's journey; not the slave of the evil passions which you know are within, delivered from this bondage, which at times you have been, -- delivered by His Word, so that you are now free men, -- free to undertake the journey to the promised land, -- the journey that leads through temptations to heaven.

But the words of the text involve not only that the Lord has delivered, but that continually he delivers, and will deliver. The verb has no tense, and so our acknowledgment of the Lord must have no tense. Our Lord Jesus Christ is to be acknowledged not only as the God who has so delivered us in the past that we are now free and prepared to start on life's journey, but also as the God who will deliver all those who from confidence obey Him. This is what is meant by Faith in the Lord. To have confidence that obedience to His Word. To have confidence that obedience to His Word will bring genuine happiness and genuine freedom He that hath my commandments and keepeth them, he it is that loveth Me. (John 14:21).

== VI. OTHER GODS. 

Matthew 24:36-51; Isaiah 63:1-9; @HH 236.

Thou shalt have no other gods before me. (Exodus 20:3).

The Israelites who heard these words, and their descendants who followed them, understood by these words do other than that they were not to worship the gods of the nations. They did not, however, understand by this, that there were no other true gods, and that Jehovah alone ruled the universe; but they thought there was no God so powerful as Jehovah. It was because of this that they so often fell into idolatry, i.e., as often as they doubted concerning the power of their God. In a word, the Israelites, for the most part, took these words of the text to refer merely to the external duties of religion, such as sacrifices and offerings, etc. Few, if any, had a realization of what worshiping the Lord is; and this because they were for the most part so ignorant and sensual that few of them lifted up their thoughts to the contemplation of spiritual things. They had the opportunity, -- for Moses was constantly teaching them; but for the most part they preferred to remain in purely external matters. Hence their idea of worship was a merely external one, namely, that it consisted solely in performing the rites and ceremonies enjoined. And so the commandment came to them as a command to sacrifice to no other god than the one who had brought them out of the land of Egypt; and because there was no perception of a spiritual command within these words, therefore, they so often fell away from obedience.

The words before us do, in fact, mean what the Israelites thus understood, but they mean a great deal more. In the external or literal sense they mean that one is not to worship any other than the true that he is not to put other gods in His place. But who is the true God? To Christians the true and only God in the Lord Jesus Christ; to the heathen the true God is the supreme God of their heathen religion. In both cases there is to be no other God or gods; men are not to be worshipped, that is to say, the fear of the power or scorn of men is not to be set up as the criterion and guide of conduct. Saints are not to be worshipped, nor any pope; for it is not a saint or a pope who can deliver from hell, but the Lord alone who has delivered us from the house of bondage.

Thus far in our consideration of the commandments we have seen that they open with the words, God spake, by which is meant that the words proceeding from the mouth of God, -- which words are all summed up in the ten commandments,are to be received as the truths of religion, that they may enter into and form or create a new mind. The commandments proper then open with the words, I am the Lord thy God.

The first word is, I, by which is meant the One and Only; and this idea of the one and only God is the universal principle that runs through all the ten words; for what is first uttered in a series is the universal thought or principle that rules throughout the series. The universal here is that the one God is to be worshiped. And let me here say that the Writings teach us, and human reason can easily confirm the teaching, that there is, a universal influx into the soul of every man, which gives him as it were an internal dictate, so that when he hears of God he spontaneously call think of but one God.

After this universal teaching that I, the one God, is to be worshiped, the Law then teaches who is the one God. I am JEHOVAH THY GOD. By Jehovah is meant the Infinite and invisible Divine Esse. This is manifest from the fact that the word Jehovah is made up entirely from the verb to be; and from the further fact that the Israelites never dared to otter this name - and this from correspondence, since the Infinite cannot be seen or comprehended by man such as it is in itself. It is then the One and Infinite God that is to be worshiped.

But how are we to know the Infinite. This also is told in the opening of the commandments. It is involved in the words, Thy God who brought thee forth, etc. It is not the invisible Divine Esse that can be the direct object of Mans worship, but it is that Infinite manifesting itself; it is THY God who brought thee forth. To the Israelites and their followers the manifestation of Jehovah was ever made through an angel. This is clear from the Word. See, for instance, Exodus, chapter 3: And the ANGEL OF THE LORD appeared unto Moses in a flame of fire.... And the LORD saw that Moses turned aside. That Thy God here refers to the manifestation of the Infinite and Divine Esse, which manifestation, to the Israelites, was effected by means of angels who were seized with the Lord's presence and spoke when thus inspired by Him, is further manifest from the following words, Who brought thee forth from the land of Egypt; for it was the Lord leading and guiding by means of the angel of God who actually led the Israelites out of Egypt. And the angel of God which went before the camp of Israel, (to lead them), removed and went behind them ... and came between the camp of the Egyptians and the camp of Israel, namely, to give darkness to the one and light to the other.

It is then the angel of the Lord who is meant by thy God. As I have said, before the Lord's coming, this angel means the prophets and angels whom the Lord inspired with His presence and by whom His infinite Divine truth was thus able to come to the comprehension of man. But in time this was no longer possible. For Divine Truth revealed in this way can be presented only in correspondences, and when the knowledge of those was lost, the words of the angel of the Lord became little comprehended except as to their obvious meanings. There were no angels, there were no prophets, who could so receive the Divine truth as to transmit it in plain rational language to men; and even if there had been, the men would not have been able to comprehend it. This is what is meant by the words, And I looked and there was none to help, and I wondered that there was none to uphold. And that the Lord then Himself came upon earth, in order that He might take to Himself a human, -- human lips, and a human mind,whereby the Infinite Divine might come to man to instruct him and to thus be his saviour,all this is taught by the words that immediately follow.

Therefore, mine own arm brought salvation unto me, and my fury it upheld me. (Isaiah 60:5). It is then the Lord in His Divine Human, who is now the Deliverer,the Lord whose Divine teaching is given in the New Testament: the Lord who has spoken in His Second coming in the Writings of Swedenborg, those many things which were promised to the apostles but which they could not bear while He was yet with them. (John 16:12); it is the Lord Jesus Christ who is our God, and he it is who is, the Deliverer from Egypt and the house of bondage. He it is who is Jehovah whose words are to form our mind into the form of heaven. That He is the One and only God who is one with the Father or Divine Esse, and that he is to be worshiped as the deliverer from evil,this is the universal teaching that runs through the ten commandments.

Following come the words of the text, whose meaning must appear evident: Thou shalt not have other gods, i.e., the universal ruling principle is not to be hindered; since by Thy God is meant the Divine Human, or the Divine Truth revealed by the Divine Human, it follows that by other gods is meant falses; or rather truths looked at, not from the Lord but from self; for falses are nothing but truths so regarded, i.e., regarded not from the fear of the Lord and the will to serve Him, but from the love of self. When truths are regarded from this state, they become falses because the man secretly or openly turns and bends them to favor his own evils; or, if he cannot do this. he so bends and twists them that finally lie comes to deny them. Self-examination will show every sincere examiner that this is the case, -- namely, that when the truths of the Word are contemplated from any other love than love to serve the Lord, they become bent to more or less favor and excuse our evils.

This is what is meant by having other gods before Me, or, as the original words are, before my faces. By the faces of God is meant His Divine Love and mercy, which shines forth from His face, that is, from the face of the Divine human, and manifests itself in His revealed Word. We are not to set other gods before this face, i.e., between ourselves and the Mercy and Love of God; for if we do this we look at all things not in the light of the faces of God, but in the darkness induced by selfish loves; and these continually turn the mind away from God. On the other hand, in all things, in all our thoughts, we are to keep before our mind the thought that the Lord alone is to be worshiped, that He is revealed in His Word, and that He is there the Deliverer. May the Lord made His face to shine upon you and be gracious unto you.

== VII. GRAVEN IMAGES. 

Matthew 6:1-15; Exodus 3:1-15: @HH 254-255

Thou shalt not make to thee a graven image and any likeness of anything that is in the heavens above, or that is in the earth beneath, or that is in the waters that are under the earth. (Exodus 20:4).

In these words the Israelites were given the direct command that images were to have no place in their worship. And the command was made most specific, namely, that there were to be no images of the things in heaven, such as the sun, moon, or stars; or of the things on earth, such as men or animals; or of the things in the water, such as fishes of various kinds. Images of one or another of the above kinds had been in common use in the ancient church, and were well known to the various nations of Canaan and surrounding countries.

In the Ancient Church worship was carried on by means of representatives. That is to say, they represented the spiritual things of the thought by means of images of various kinds, so that such images might serve them as means of thinking of spiritual things. The reason why this kind of worship then prevailed was because the Lord Himself appeared to them in the representation of an angel. He could not appear to them as He was in Himself, for the finite can never grasp the Infinite. In order to appear it was necessary that the Lord take upon Himself a human accommodated to reception; that is, a human by which the Divine Truth uttered by the mouth of God might be presented clothed in ideas comprehensible to man, and finally in a language that could be understood. And inasmuch as the Lord had not yet come in the flesh, this accommodation could be effected only by means of the Lord taking possession of an angel, -- seizing possession of him, in the same or similar way as hypnotic subjects are seized; so that the angel no longer knew other than that he was in truth the Lord; and yet he was not speaking from himself but from the Lord.

But through this angel the Lord's words were clothed in natural ideas and images taken from the angels mind, which could be transmitted to men; and when men's spiritual eyes were opened so that they saw and heard the angel of the Lord thus seized, the spiritual speech of the angel to them was at once translated into the words of their own language; -- just in the same way as, when a foreigner of whose language I may be ignorant, manages to convey by gesture or otherwise some idea to me, that idea in me at once clothes itself with the words of my language. Tills is the nature of revelation as given to the Israelitish Church, and also as given to the preceding Ancient Church. And this is the reason why we so often read of the revelation being given by the Angel of the Lord who yet always speaks of himself as the Lord.

Now because the Lord appealed to the Ancient Church only by representatives therefore all the things of their worship were representative. They were a representative church. The revelations that they received through angels were clothed in language, and in ideas which corresponded to the Divine message contained within. And in order that the Divine Truth might be unveiled, it was necessary that men study and learn the science of correspondences, -- the science, namely, that teaches how the things of the spiritual world are effigied and represented by corresponding things in the natural world. Indeed there was then no other way in which men could learn concerning Divine and spiritual things. Hence the science of correspondences was with them the principal of all sciences; and hence also, whenever they wished to express spiritual things, it was necessary for them to do so by means of correspondences. For this reason they were in the habit of representing various attributes of the Lord by various images, so that when they looked upon the image their thought might be thus directed to that thing in the Lord which was represented thereby. In course of time, however, the knowledge of correspondences was turned into magic, and afterwards, being divorced from genuine religion, it declined and was almost entirely forgotten, -- though some remnants of it seem to have remained with the early Greeks of Hesiods and Homers time. But the images still remained, and then began the worship of these images themselves. Thus idolatry arose.

There is much evidence both in the Lord and also in the investigations carried out by modern researches in ancient ruins that idolatry was rife in the cultivated world of ancient times. The sun in heaven was worshiped; they also had Astarte, the moon goddess. Heroes on earth, and also animals were worshiped. Images of fishes and combined fishes and men, as Dagon, were worshiped.

Moreover, it is evident from the Word that the Israelites, were especially prone to idolatry. They were an ignorant people, and easily carried away by anything that appealed to the senses. Therefore, they were given the most strict command that they were not, like their fathers in the Ancient Church, to make images of any kind. At the same time their desire for externals was or ought to have been satisfied by the many and wonderful miracles they witnessed, and also by the sacrifices and rituals laid down for them.

Such is the natural or historical meaning of the words we are considering. The Israelites were on no account to make anything whatever in the nature of an image of God; but they were to write the law of God in their heart, and thus God Himself was to be in their heart.

The same general lesson is contained in the spiritual sense of the words before us; in fact, the spiritual sense of Scripture is nothing else than an unfolding of the genuine spirit that must enter into the observance of the literal sense. By a graven image in the spiritual sense is meant a thing graven by the hands, and thus the result of human intelligence and power; and this being a likeness of the things in heaven above, etc., involves that this graven thing is made to look like the work of God but is not really such

Since a graven image means one sculptured by the hands it signifies doctrine, and here a doctrine made up by self-intelligence; as opposed to a molten image, which, since it is made by fire, signifies evils. And by the graven image being a likeness of the works of God, is meant doctrine made up by the human proprium which indeed appears as though it were the work of God. and which yet is only the concoction of self-intelligence.

It is said that there must be no such images either of the things in Heaven, or of those on earth, or of those under the earth, by which words is evidently meant three degrees in the things that come to man from God. These three degrees are the revelation of God to the three degrees of the human mind.

Every human mind is in three degrees. In the highest degree reside spiritual things, that is, thoughts and affections for God and religion, and, in general, the things of religion and the spiritual life, as distinguished from mere life of the body in the world. In the second degree reside all those thoughts and affections that concerned the direction of the moral and civil life; in one sense animals are also in this degree, but there is this difference, namely, that while animals can be only one kind of animal and can live according to the rational laws of their own love only, which laws are their instincts, man can be any kind of an animal; thus he can have the wisdom of the serpent, the cunning of the fox, the cruelty of the leopard. the skill of the beaver, etc. He has this faculty from this middle degree which receives influx from the inmost degree, and which by means of that influx is able to see and judge concerning the things that come in through the senses.

The third degree of life is the memory which is the general storehouse wherein are laid up the things that are to be of use in the rational and spiritual life. The characteristic of this last degree is the collection of scientifics or knowledges concerning any or every kind of subject.

The command in the law is now evident, namely, that man is not to make up from his own intelligence, any theological or spiritual doctrines, which look as if they were Divine, and which yet are not so but are the works of human proprium and conceit, and are destructive to the spiritual life. Such doctrines are the doctrine of faith alone, of Predestination, of denial of the Lord, etc.

Neither must man make up for himself moral laws and ethics, so-called, that are not based on the acknowledgment of God. These may indeed look like the laws of religion, and yet they not only are not like, but on the other hand, they are deadly to the real spiritual life. Of such nature are the modern ethics and morals which lack the soul of religion.

Finally, neither must we make up a science which springs from human intelligence and which appears as if it were the work of God, and yet which denies God. Such is modern science, which despite the apparent order of its facts is utterly repudiative of the existence of God. and especially of humble obedience to His commandments.

To be genuine in our worship, to be sincere, to be humble, -- this is the lesson of the text. To be content humbly to worship the Lord and to obey His commandments from a simple heart, and not to erect in our minds images which seem like the things of religion, but which deny Him from whom alone the life of religion comes, -- this is the lesson of the text, and also the lesson that every man must learn if he will be a true worshiper of the Lord and not a hypocrite and deceiver.

== VIII. HEREDITY. 

Ezekiel 33:7-20; Mark 8:1-21; @HH 545; or @CL 202-4.

For I the Lord thy God am a jealous god visiting the iniquity of the fathers upon the sons unto the third and fourth generation of them that hate Me, and showing mercy until the thousandth generation of them that love me and keep my commandments. (Exodus 20:5-6).

These words give the reason offered to the children of Israel why they should not worship other Gods, namely, because the Lord their God is a jealous God and will surely punish them if they are false to His worship; the mode of the punishment is also stated, namely, that the children to the third or fourth generation will be punished. This does not mean that children are to be punished for what their fathers have done, for this would be against justice. This is plainly. stated in Deuteronomy, one of the books written by Moses who also wrote Exodus. We read: The fathers shall not be put to death for the children, neither shall the children be put to death for the fathers; every man shall be put to death for his own sin. (Deuteronomy 25:16).

Here it is plainly told that every one is to suffer the consequences of his own sins, and that no one will be made to suffer the punishment of another's sins. What then is meant by visiting the iniquity of the fathers upon the sons? To the Israelites the meaning was clear, namely, that if they did not remain faithful to the worship of the Lord they would not be able to enter the land promised to them until three or four generations. This indeed is what actually happened. For because of the many sins of the children of Israel while they were in the desert, not one of that generation was permitted to enter the land of Canaan. While no one is punished for the sins of another, still no one can commit a sin without doing injury to another. One who tells a lie or deceives in other ways does harm to those whom he deceives, for he is helping to destroy their trust not only in himself but also in others. One cannot steal, nor commit adultery or other net against the holiness of chastity without doing harm to others. Anyone who does evil, necessarily does harm to others; the law of order demands this. Yet he himself is the only one to suffer the actual punishment. The others appear to suffer punishment, but this is only the appearance. If they look to the Lord and shun evils as sins they do not suffer any punishment. If, for instance, a son should commit crime and thus bring grief to his parents, it call readily be seen that though the parents suffer grief yet if they trust in the Lord and shun evils, that grief instead of being a punishment may be a means of strengthening their faith. So it was with the children of Israel. The privilege of enjoying the Land in peace was not theirs, because of the sins of their fathers in the wilderness and afterwards; and yet because this was a lesson continually before their eyes, it might have served them as a means to be more obedient to the Lord.

It will be noticed that the iniquity of the fathers is visited upon the sons only to the third or fourth generation, while the rewards of the good will reflect on the sons to the thousandth generation. This is because of the Lord's mercy. Thus, although the children of Israel sinned in the wilderness, yet the Lord punished only the one generation. The reason is because the Lord is always in the effort to lead man to heavenly happiness, and this whatever evil he has done. This is the reason why, however evil one has been, or whatever evil he has done if only he sincerely prays to the Lord and persists in shunning evils as they come up in his daily life, he will feel within him the delight of an upright life.

This is expressed in the words, To those that love me and keep my commandments. Notice that the test of love is keeping the commandments. If a man shows his love to the Lord by keeping his commandments then the Lord will bless him and also his children will be blessed,though whether they will receive that blessing and make it their own depends on whether they keep in the steps of their father.

This natural sense of the words as understood by the children of Israel, is not unlike the spiritual sense. Every one who does evil thereby shapes his mind into the form and habit of loving that evil; and if he persists in thinking of it and taking delight in it, this evil brings forth other evils and other evil and filthy thoughts. When a man does evil, that evil, like a father, gives birth to other evils. Thus if one does something against the low, it leads to lying in order not to be found out; if one commits seduction it often leads to cruel desertion and even to murder, although the seducer had never thought he would ever be guilty of either of these crimes. No man can commit an evil without its leaving its stamp and form on his mind, and because this form is a form of a living mind, it is always trying to be active so as to make the other forms of the mind, -- the forms and habits of the mind that have been learned in childhood, to make these forms also like itself, i.e., to destroy good forms and habits, and bring evil one's which it itself has brought forth, to take their place. This is the third and fourth generation that follows every evil, and which is the punishment of that evil. But while evil is thus always in the effort to increase itself and bring forth other evils, yet the Lord's mercy is so great that He is in the constant effort to prevent man from falling further into evil. Anyone can see in himself that if he commits one evil it leads to two or three others at least; but he can also see that so many are the means that the Lord uses to remind him that he is doing evil and to bring him to repent if he will, that he can always shun the evil and become one of those who love the Lord and keep His commandments.

As it is with the offspring of a man's mind, i.e., with his thoughts and affections, so it is also with the offspring of his body. No man can do evil without it so impressing, actually impressing itself upon his mind and also on the finest parts of nature that go to make up the lowest part of his mind, that it is passed on to his offspring. We know that this is the case with diseases. Witness, for instance, the dreadful evils that have been handed down to children by fathers who have lived a loose sexual life. They thereby contract gonorrhea, and syphilis, and they communicate this to their wives and pass it on to their children. This is the reason of much of the hereditary weakness that exists to-day. And it would be well for every one to think of this, so that if he has any honorableness it may serve to check him when he thinks what misery he is storing up for others. And if children inherit the bodily diseases of their parents, they must also inherit the diseases or evils of the mind. Indeed, we know this to be the case. But we know also that no one can plead this as an excuse for his evils; for every one is free to shun evils as sins if he wishes to; and every one has the rationality to understand what evils are sins; everyone, moreover, has learned about these evils, so as to recognize them. Let no man plead that he had a bad heredity. It is useless to do this as it would be for a bad son to plead the good life of his father. No! Every man must be responsible for himself. Yet no man can do evil without its having an effect on his offspring. This is the reason why with evils committed generation after generation they have now grown so strong that they have well-nigh destroyed all interest in religion. This is because the sons instead of shunning the evils to which they felt an appetite, went on doing them and thus passed them on to their offspring still stronger than they had received them.

And what is true of evil is also true of good; but with this difference, that if a man does good the Lord is with him and where the Lord is, there is peace and blessing and increase. Anyone who has shunned evils and then has come into some peace of mind in consequence, will understand this; for instead of the dread and weariness that follow after the doing of evil, there is peace and happiness and exhilaration, and this is felt even in the body. This is the blessing to the thousandth generation of them that love the Lord and keep His commandments.

But there is also another view of this, namely that from those who shun evils as sins are born offspring who derive from their parents something of the inclination to the love of spiritual things. This, in fact, is the hope of the New Church. It seems sometimes as if it were almost impossible to awaken any interest in spiritual things; to get others to take an interest in reading the Word or the Writings; even to take an interest in these ourselves. Nor will this condition ever improve unless men actually love the Lord by keeping His commandments. It is to such men that we shall look for the renewal of the worlds life; and not only to the men themselves, but also to their offspring, born with something of an inclination to spiritual things, and during their childhood surrounded with things to encourage this inclination. And if they will persist and cultivate this inclination and make it their very own, the Lord will bless them a thousand fold, -- both them and their children, -- the children of their mind which are their thoughts and affections, and also the children of their body. This is the essential of a happy home in which are born children whose earliest years are surrounded with evidences and remembrances that there is a spiritual life and that this life is the end and goal of life on earth. To those who keep the Lord's commandments, the Lord will bring blessing and thousand fold increase.

== IX. PROFANATION. 

Exodus 32:19-35; Matthew 12:30-45; @TCR 297; or @HH 562.

Thou shalt not take the name of the LORD thy God in vain, for the LORD will not hold him innocent that taketh His name in vain. (Exodus 20:7).

Literally translated, these words would read, Thou shalt not take or bring the Lord's name into nothingness, that is into deeds of worthlessness or works of vanity. The words were understood by the Israelites as being a command that they should not bring the name of their God or the thing belonging to His worship, into the worship of idols, -- for the worship of idols was a work of vanity, of nothingness, of emptiness. This is shown in Deuteronomy where we read: The children of Israel did secretly things that were not right against the Lord; ... for they served idols, whereof the Lord had said unto them, Ye shall not do this thing. Notwithstanding, they would not hear ... and they rejected his statutes and his covenant and they FOLLOWED VANITY and became empty and went after the heathen that were round about them (2 Kings 17:9-15), and again in Jeremiah. My people hath forgotten Me, they have burned incense to vanity (Jeremiah 18:15).

The Israelites were not only forbidden to worship other Gods, but in this command they were forbidden even to mingle the name of their God with anything connected with the serving of other gods. And yet, even while the commandment was being given, even though just a few days before the people had witnessed the wonderful deliverance from the Egyptians and the Red Sea, -- yet despite these things Aaron easily led the people to make a golden calf and worship it. Nor was this the whole extent of the peoples fault, for they listened obediently when Aaron brought the name of their God into this idolatrous worship. After he had fashioned the golden calf the people said, These be thy Gods, O
Israel, which brought thee up out of the land of Egypt; and after this Aaron made a proclamation, To-morrow is a feast day to the LORD, and thus brought the Lord's name into vanity or in vain.

It is said that the Lord will not hold him innocent that doeth this, by which is clearly meant that there can be no excuse for this mingling of the holy name of God with the profane worship of idols; there can be no excuse, and so no escape from the punishment. For they had been distinctly commanded to worship no other god than He who brought them out of the land of Egypt; they had witnessed His wonders; they had sung their praises to Him. If then they turned to idolatry there could be no excusing them; they had learned the holy name of God and His power and had mingled it with the things of vain worship. That there actually was no excuse, is shown also by the event in the case of the worship of the golden calf; for the punishment was not severe, being the slaughter of over three thousand men.

Interiorly the Israelites had little if any concept of as a spiritual god. Their god was a tribal god. He was their God, and his name was holy, not because of any real reverence they owed to that name and to him whose name it is, but simply as the name of one who was most powerful in the executing of vengeance against all who disobeyed him. Hence it was not long before the commandments began to be interpreted as a forbidding to the people of the use of the name Jehovah and from this has grown up the custom which has survived to our day, that the Jews will on no account utter the name Jehovah. Whenever this name occurs in the Hebrew Bible, they indeed write and print it, but when reading they always read Adonai.

But though thus particular as to using the name of Jehovah with their lips, and though thus ingenious in spinning out the meaning of the Law so that it became among them a vain tradition, yet they paid little attention to the weightier matters of the law, that is, to justice and mercy. Punctilious as to uttering the name Jehovah, they were not punctilious as to making use of the things of His worship for the sake of their own profit, and for the exploitation of the people. They would not utter the name Jehovah, but they had no hesitation to turning His house into a den of thieves, where they sold pigeons, and exchanged the common coins for holy shekels, -- and all at an exorbitant price.

It is ever thus; fur those who place most emphasis on externals are invariably extremely anxious after the morals of other people; they are extremely keen-sighted in seeing where others fail; and extremely ready and even eager to speak of these failures; but they pay little attention to the real things of religion which concern, not the appearance before men but the appearance which we are by ourselves in our closets where the Lord, alone can see. This is the reason, or one of the reasons, why we sometimes read of men who have been most punctilious in the observance of religious duties, and also most ready to blame others, and who, when put in the way of temptation, or when restraints have been removed, suddenly rush headlong into the very evils they have denounced.

It will be seen from what we have thus far said, that the general lesson of this command is, that man shall not mingle the things of religion with things that are vain and empty. What is meant by things that are empty? A thing is empty when nothing can be taken from it; and the works or doings of man are empty when no use to others comes from them, and especially when they breathe destruction of others. It is not possible for any of man's deeds to be empty, i.e., to be empty of motive, purpose, life. Every act that he does has within it either good or evil; and if it has not good within it, and by this I mean the good of an active purpose to resist evil, then it has evil within it. This is well expressed in the homely proverb, The devil always has some work for idle hands to do. So that a thing or deed that is empty is a deed that is devoid of good, and, therefore, is full of evil.

Of such a quality are all the deeds of man that are not done under the spirit of shunning evils as sins against God. Men are usually content to let themselves drift through life so far as any reflection on the state of their spirit is concerned. That is, they are content to remain in the external sphere of conduct in which they have been brought up, or, if this is not satisfactory to their prospects, they strive to better themselves, to improve their manners, graces, etc. But they rarely reflect on the inner world where are enacted their interior motives, and where the evils of the will hide themselves under a garment of good and moral conduct which we are so accustomed to wear, that we hardly reflect upon it as possibly not being our true garment or character. And yet our hereditary evils and inclinations, -- those evils which sought outlet during childhood in many little ways, foolish and childish, such as pouting and sulking, saying, I wont play with you any more, etc., -- ways that, as we grew older, we grow ashamed of, -- these evils are still within; they are only covered over by a garment that has been borrowed from the world. The garment has its use in covering the nakedness of man, i.e., in covering his evils; but this use is for the purpose of putting him in a free state so that he can gradually shun his evils.

There is no such thing as natural spiritual good. All spiritual good must come by effort. Unless effort be made to shun evils as sins against God, those evils still remain within, and the man is an empty man, that is, empty of good; his mind is filled with vanities, that is, with things that, while of great value to himself because they administer to his own pleasures, are not productive of spiritual good to others.

It is into this emptiness that we are not to bring the name of God. We are not to mingle the worship of the Lord with a life of evil; we are not to have the name of God on the lips but the name of vanity in the heart. Those who do this are in a serious position, for they are in danger of profanation. If they have confirmed themselves in their religion, it has become so set into the very fibre of their being that it perhaps can never be wholly extirpated; and if they still indulge in a life of evil, that is, if they do not shun evils as sins, they mingle in their mind states of evil loves with states of the apparently sincere acknowledgment of truth. This is profanation, and sometimes it can never be cured. The profaned truth, and the affections that have been connected with it, sometimes call never be separated to eternity, and the lot of the man is then severe indeed; for he can be neither in heaven nor in hell, for each would reproach him; and so he remains in a sort of comatose condition, forever unable to think good because it condemns him, and unable to do evil because his truth condemns him. You can get some idea of this state if you will reflect on how firmly you believe in the doctrine of the New Church, and would stick up for it by all manner of argument, and yet, -- how easy it is for you to pay little attention to the practical confirmation of that doctrine by the life of religion.

It is this punishment of profanation that is meant by the words, He will not hold him innocent that taketh His name in vain.

I have said nothing about the evil of swearing; and this partly from lack of time, but more especially because I know the lesson of the text in this respect is quite obvious to you. In the Christian world there is so little interior acknowledgment of God-Man that it is little wonder that His name is daily profaned. But for one who does acknowledge the Lord, to use His name in vain and empty speech is the mingling of the holy with the profane.

If there is love for the Lord in the heart; if there is the desire to obey Him and not to serve other gods, it is then that His name is hallowed, and that there is a just fear to bring it into aught that is vain or evil. But if there is not love to the Lord, mere abstaining from swearing is of little use except to preserve external order. Thou shalt not take the name of the Lord thy God in vain.

== X. HALLOWING THE LORDS NAME. 

Matthew 5:33-48; Psalms 119:9-16; @HH 292-293.

Remember the Sabbath day to hallow it. (Exodus 20:8).

In the preceding commandment we are commanded not to take the name of the Lord in vain, by which is meant that we are not to bring the Lord's name, that is, the profession and worship of Him and the reading and acknowledgment of His word, -- we are not to bring these into a heart that is vain or empty of the will and effort to apply the commandments to the life. A man who truly honors and worships the Lord, verily holds His Word, the reading of that Word, the public and private worship of Him, and prayer to Him for help in the struggles against the evils of the heart, -- verily holds these as the sacred things of his life. As to whether we do this is a question that each man must ask Himself. He may know, however, that if he makes it a point to read the Word daily and to pray to the Lord, and if he persists in doing this, even when the desire for rest and pleasure tempt him to let it go; if moreover, as sometimes, when tempted to actually do an evil, or wallow in the delight of it in his imagination, he resists that evil, saying to himself that it is a sin against God and an injury to the neighbor; if a man does this at times, then he may feel assured that he is in the path of regeneration. But the struggle must be constant.

Now if one thus honor the Lord's name in his heart, he cannot but regard it as sacred on the lips. To utter the name of God, or any of the names by which He is known, -- to utter his name in vain, frivolous or unbecoming speech is the external representation of the slate that indeed uses the name of God and the things belonging to the worship of Him, but that cherishes all manner of evil; that has no love of religion; a state which, as Swedenborg tells us, is seen in the other world to be a state of hatred against the Lord. If we would be genuine New Church men therefore, it behooves us to be on our guard against the profane use of the Lord's name.

But more than the actual name of the Lord is involved. The command includes also all speech that is peculiarly associated with the worship of the Lord, or with the life after death; it includes also becoming respect for the things used in worship, especially respect for the Word; and lastly it includes the speech of the Word itself.

In all these respects the young man of the present day, as in past generations in the so-called Christian world, must be on his guard. It is remarkable that, while in all heathen nations the name of their god and the things connected with His worship are held in awe, in the so-called Christian World where is the light of the Gospel, there is the utmost profanity in the use of the Lord's name, in the light treatment of the things of worship, and in joking from the Word of the Lord. No wonder Swedenborg speaks of the mass of the Christian world as being Christian gentiles. They are indeed heathen, and many of them are actually ignorant of even the first principles of religion. These, however, are usually the utterly ignorant, and with these doubtless the taking of the Lord's name in vain is pardoned if only they live in some uprightness.

But a vast number of those who thus profane the Lord's name, who have no hesitation in using lightly the words of the Scriptures, are men who have some pretensions to Christianity; and with than the matter is no light one.

Spirits are associated with men, and everything that a man does, immediately brings to him spirits who are in loves corresponding to the deed. This is the reason why, if we look at an evil scene, as, for instance, a lascivious picture, or indecent things on the stage, or if we read something that brings such a picture to the mind, we immediately feel a rush of impure fire which is experienced by us as delight,but it is the delight of hell, and it comes from the evil spirits who then gather around us like birds of prey around a rotting carcass. For where the carcass is there will the eagles be gathered together. (Matthew 24:28).

It is similar with swearing; it cannot bring the presence of spirits who hallow the Lord's name; that is quite plain. But what is not so plain is that it does bring the presence of spirits who are in hatred of the Lord; nevertheless this is a fact that is now revealed to us, and we can readily see its truth.

In the Christian world where swearing and the other habits that are opposed to this commandment are so common, it is sometimes very hard for the young man to resist, especially if he has not learned to shun such speech in his career years. He hears so much of it that it is apt to slip from his lips without previous thought. This is due, not only to the prevalence of this speech, but also, and especially to the fact that he has not schooled himself, or has not been schooled, to purity of speech in his earlier years. And I might here and, that any young man who realizes this will have it before his thought in his treatment of those younger than himself. The young men of our church ought to be as elder brothers to those younger than themselves; and their influence ought all to be in the direction of implanting good external habits of speech and deed.

As I have said, many find it difficult to avoid swearing. Probably they could avoid it if they really tried; but that is a question for themselves. I would suggest to such, -- as an easier way to obey the commandment in spirit, -- that they make up their minds that never shall the name of the Lord pass their lips except in the sphere of worship and religious thought. Whatever else they may say, they can at any rate do this. Moreover, if they cannot avoid listening to, and even being amused at stories from the Word, they can at any rate make up their mind never under any circumstances to repeat such stories. But I would earnestly warn my young friends against even giving ear to light stories and jokes based on the Word. Such stories stick to the mind, and come up even in worship, and are then the ultimate for the approach of evil spirits, at a time when the effort is to bring the mind into a state of worship.

If a young man will make up his mind to observe these rules, and to do this because he wishes to obey the Lord's commandment, and if he persists in keeping to this mind, and, when he fails, prays humbly to the Lord that he may be strengthened to conquer when temptation again comes, -- and if at some times he does actually conquer, then he is in the way of regeneration.

But we cannot of ourselves do this; we must pray to the Lord; we must actually pray to Him, -- and by actually I mean in genuine thought and intention, and also in actual worship.

This is the reason why the next commandment is Remember the Sabbath Day to hallow it. And it is the external and general meaning of this commandment that I would here emphasize. We cannot hope to walk along the path of regeneration, unless we worship the Lord. The reason is obvious, for there, is, nothing in us that would prompt us to lead a new life in the heart. There is much that prompts us to reform our external conduct; but there is nothing whatever in ourselves that prompts us to shun evils in heart and thought and intention. We can do this only when we acknowledge the Lord and learn from Him.

Worship, therefore, is necessary to regeneration. The real worship is the actual obedience to the Lord in daily life. But this is not possible without learning from the Lord in His Word; nor is this possible without the reading of the Word; nor is this possible without something of external worship. This shows the importance of always observing some actual external worship. We need it in order to preserve us in the interior worship of the Lord; for otherwise it would be easy, and indeed inevitable, for us to become more and more careless about the things of religion as applied to our daily life.

It was for this purpose that the Sabbath was established; and the whole Christian world is based externally on the giving of every man an opportunity of resting more or less on that day. It is the one day of the week which the Lord asks of us. He has given us six days in which our minds are mainly concerned in merely worldly things, and He asks us to devote one day to thought about the spiritual and eternal things of life. The same would apply to daily prayers; nearly all the day we are engaged in thoughts of worldly things, and it is little enough to any a prayer for help when going to rest, and - still better, at the commencement of the day. Indeed, we need these external helps, and should, therefore, cultivate in ourselves the habit of reading from the Word, prayer, and worship. I can imagine no circumstances under which it would be impossible for a man to do these duties, at any rate most of the time. He will do them if he really wishes to be regenerated. And when he is doing them, if he does them sincerely his very doing is his prayer to the Lord to help him to a life of good.

I do not mean that on Sundays the thought is to be kept all the time on religious things; that would be unnatural. Nor do I mean that on other days one is not to think of religious things; that would be ridiculous. I simply mean that once a day there should be prayer to the Lord and reading of his word if possible, end that, at all events, there should be some sort of more formal worship, reading, and prayer, on Sunday. This is the real prayer to the Lord for help that we may not take His name in vain. If we really desire to do this, then, in order to receive help we shall also Remember the Sabbath day to keep it holy.

== XI. THE SABBATH. 

Isaiah 5:6; Luke 6:1-11; @HH 500-501.

Remember the Sabbath day to keep it holy. (Exodus 20:8)

In my last discourse on these words I dwelt particularly on the reason why they immediately follow the command not to take the Lord's name in vain, namely, because no one can truly honor the Lord's name in his heart, and thus on his lips, unless he worships the Lord; and worship of the heart, involves and indeed requires external worship, both private and public; and I emphasized the importance of daily prayer and reading from the Word.

I now propose to enter more into the spiritual sense of the above words. This sense indeed rests on the natural sense, as you will see; for in general the spiritual sense teaches that the Lord Himself must be held as holy, and this cannot be done without the open worship of Him whenever that is possible, and the reading of His Word.

The Sabbath signifies the Lord in His glorified Human, that is, the Lord as He is revealed in the pages of the New Testament and as He is now revealed in the Writings of the New Church. The reason for this signification is because the Sabbath is the seventh day which, in the Jewish Church, constituted the last day of the week and involved in itself all the preceding days. For this again there is a still deeper reason. The Lord created the heavens and the earth in six days, and on the seventh day God ended His work which He had made; and He rested on the seventh day. And God blessed the seventh day and sanctified it, because that in it He had rested from all His work which God created and made (Genesis 2:2-3). In the external sense the work from which God rested is the creation of the world and its kingdoms; but in the spiritual sense this work is the salvation of man; for this is the end, and the only end for which creation was. Now this work of salvation could not be effected except by the revelation of God in Human Form, for otherwise no man could see him, and still less worship and obey Him. This revelation in human form was, prior to the advent, made by means of on angel who was called the angel of the Lord; but when, owing to the gross ignorance that had grown from the evils of the human race, this manifestation was no longer sufficient to enlighten mankind, then the Lord came on earth and manifested Himself in His own Human which He glorified, so that The father was in Him and He in the Father, and he who saw Him saw the Father. Thus the Sabbath properly signifies the Lord in His glorified Human. For the glorification His Human, and thus His full revelation of Himself to man for man's salvation,this is the End for which creation was,the end of the six days, as it were, the end which is the Lord Himself, and in which is the Lord. This is the reason why the Lord said of Himself, that the Son of man is Lord also of the Sabbath.

Before the Lord's advent into the world, all revelation and all worship in the various churches was a prophecy and a representative of the Lord's coming. This is plainly stated in the Word where we read, All the law and the prophets prophesied until John the Baptist, Matt 11, 13. Thus the days before the Advent, or the Church and its worship before the Advent, all looked to the Advent of the Lord as their end and conclusion; this is signified by the six days of creation ending on the seventh day on which God rested from all the work that He had done. It was for this reason that, before the advent, the Sabbath was the last day of the week. But after the Lord's advent the Sabbath was made the Lord's day (Revelation 1:10), and became the first day of the week (Luke 24:1). For the Christian Church did not like the former, look to the fulfillment of prophecy, but it commenced with that fulfillment; that is to say, the Lord in His Divine Human, who is the Sabbath, was the First and the Founder of that church.

And since the Sabbath signifies the Lord, it therefore signifies heaven, for the Lord's presence with man makes heaven with him. And moreover, it signifies also the marriage of good and truth, for it is only when there is this marriage with man that the Lord in His Human can be present with him, and establish heaven with him.

By reason of these significations of the Sabbath, the Israelites were most strictly commanded not to profane the Sabbath by doing any work therein, and this even under the penalty of death. Every one that defileth the Sabbath hall surely be put to death; for whosoever doeth any work therein, that soul shall be cut off from among his people (Exodus 31:14). For when the Israelites were in their Sabbath, the angels and spirits who were with them in that state, perceived the glorification of the Lord's Human, and if any profaned this day, it would be presented to spirits as the rejection of the Lord's Human. Indeed, it is for this reason, that the Sabbath was given to the Israelites as a sign between Me and you, throughout your generations, that ye may know that I am the Lord that doth sanctify you (Exodus 31:13). It was because the day was such a sign, that its observance was held to be one of the holiest requirements in the Israelitish Church.

We are commanded to remember the Sabbath. In the external sense, this means to keep it in mind, not to forget to observe it. But in the internal sense, to remember, means to hold implanted in the heart. A man remembers what he loves, and this, because what a man loves is universally present with him, even when he is thinking of other things. Anyone can see this for himself if only he reflects how easily he can be led to think and talk about what he really loves, whatever he may be doing. What a man loves is in his internal will and thought, and it remains there whatever the external thought and the body may be engaged in doing; it is his End, to which all the things of his life look. It is for this reason that Remember means to have present in the interior will, or, to have universally present; not present in the mind as are knowledges, or as are the sciences, or experience, etc., for all these are sometimes present in the thought and sometimes not; but to have present in the thought and will in such way that they are always present and thus always remembered.

The purpose for which we are to remember the Sabbath is to hallow it. To hallow or sanctify means to make holy, not to profane. In what way do we make a thing holy? Externally we signify the holiness of a thing, for instance, the Word, by treating it with devout and humble attitude and by placing it in a peculiar place which we approach with holiness. Now transfer all this to the action of the heart and you will see what hallowing the Sabbath signifies ill the internal sense, namely, being unwilling to cherish ally thought that profanes the Lord in His Divine Human. No one can really profane the Lord; but a man can be in the will to do this, and if he is in this will he profanes that which represents the Lord with him, that is to say, the knowledges which he has from the Word. These rest in the mind, and if a man does not remember the Sabbath to hallow it, these knowledges become mingled with evil lusts and false imaginations.

How can we thus remember the Lord, or the Sabbath which signifies the Lord, to hallow Him? We cannot do this of ourselves, that is, we cannot make ourselves love the Lord's things and turn sway from our own when these latter oppose; but we can commence by externally remembering that We are New Church men; that we have been instructed in the Word and the Heavenly Doctrine. And if we remember this when we are tempted, and because of the remembrance, turn away from evil, then the Lord will be present with us, and gradually reform our will, so that we shall find it easier and easier to remember; and finally this remembrance will be that true remembrance which is universally present in the mind. In a word let our remembrance be the universal presence in will and thought of a determination to obey the Lord, -- for this is the hallowing of His Sabbath.

Blessed is the man that keepeth the Sabbath from polluting it, and keepeth his hand from doing any evil (Isaiah 60:2).

== XII. THE USE OF THE SABBATH. 

Matthew 12:1-63; Isaiah 1:20; @TCR 301-303; or @HH 221-222.

Six days shalt though labor and do all thy work, but the seventh day is the Sabbath of the LORD thy god; in it thou shalt not do any work, thou, nor thy son, nor thy daughter, thy manservant nor thy maidservant, nor the cattle nor thy stranger that is within thy gates. (Exodus 20:9-10).

In the words preceding this text the Israelites were commanded to remember the Sabbath; the words that we are now to consider give the fruits that were to result from that remembering, namely, that no work should be done on the Sabbath. This is the reason why they were to remember the day, in order that they might do all their work on the six preceding days so that when the Sabbath came they would be prepared to devote themselves to the duties of worship. It does not appear that the Israelites had any special services for the Sabbath; it was to be for them mainly a day of absolute rest from labor. They were not even to light their fires on that day, nor to gather manna for their food. Doubtless in practical life many interpretations grew up as regards this commandment; indeed this is quite evidently the case towards the end of the Jewish dispensation, as the Lord intimates when He accuses the Jews of making the law of no account by reason of their traditions. A case is mentioned by the Lord where an evidently just interpretation had been made, namely, where a man's ass or ox had fallen into a pit on the Sabbath, it was held to be lawful for him to work to rescue it. As an illustration of the vain traditions we might instance the learned opinions given by the rabbis pro and con in regard to whether it is a breach of the commandment to eat an egg laid on the Sabbath; some maintained that since the work of making the egg had been accomplished on the preceding day, therefore it was lawful to cat an egg laid on the Sabbath; but not an egg laid on the day following the Sabbath, since the work of making that had been done on the Sabbath. Others held that the external work of laying the egg was the work forbidden, and that therefore it was unlawful to eat an egg laid on the Sabbath. By such vain traditions did the church cover over the Word, neither using it themselves nor allowing it to be used by others.

But we need concern ourselves but little with the Israelitish observance of the Sabbath; for the law respecting the Sabbath was plainly modified by the Lord when He was on earth. The Sabbath (said the Lord) was made for man and not man for the Sabbath, -- and in these words he not only rebuked the Jews, but also laid down a new understanding of the fourth commandment, showing that it was lawful to do all manner of merciful and necessary works on the Sabbath. This the Lord states positively; but nowhere does He teach as to whether or not man is to refrain from other than necessary or merciful work on that day. The burden of His teaching is that we are to be more careful as to the cleanness of the heart, as to the real worship of the Lord, than as to a rigid observance of a feast day. And, indeed, this is openly taught in the Old Testament.

//an example of what can be done with quotations
 "Bring no more vain oblations; incense is an abomination unto me; the new moons and Sabbaths, the calling of assemblies, I cannot away with it; it is iniquity, even the solemn meeting; your new moons and your appointed feasts My soul hateth; they are a trouble unto Me; I am weary to bear them.... Your hands are full of blood. Wash you, make you clean; put away the evil of your doings from before Mine eyes; cease to do evil." (Isaiah 1:13-16).

Is there any different interpretation as to the observance of the Sabbath given in the Writings of the New Church? I think not. The teaching of the Writings as to the external observance of this is practically the same as that given by the Lord on earth, except that what is plainly implied in the Lord's teaching is openly stated in the Writings. In a passage in the Arcana there is found a list of the Israelitish laws under three headings, namely: Those which were still obligatory on the Christian: those which have been altogether abolished; and those which may or may not be observed, according as the man chooses. The commandment as to the Sabbath is put under this last head. It is clear, therefore, that man is free to do work on the Sabbath day, if it is agreeable to his conscience so to do. The New Church addresses itself to the internal or heart of man and not his actions; for it leaves to the man himself to decide from his own conscience as to his actions. The teaching of the church therefore as to the Sabbath is that the commandment is really obeyed when man worships the Lord at heart; when this is done there will be a genuine desire to set apart some time in the week for the external worship. Indeed, the Sabbath is to be remembered all the time, and so there should be a Sabbath on every day, just as there is a Sabbath of every week; this daily Sabbath is represented by daily prayer and reading of the Word.

Should wee do work on the Sabbath? If, for instance, we have complied with the duty of attending public or private worship, is it then right to devote ourselves to worldly occupations? The question cannot be answered by a simple affirmation or negation, but we may offer some suggestions to guide the judgment, that each may answer for himself and in accordance with his own circumstances.

In the present state of civilization it is manifestly impossible to refrain from all work on the Sabbath; nevertheless, our modern economy is such that for the great mass of men the Sabbath is a day of rest from the daily toil. The labors of the world have to do with the provision for the needs of the bodily life; they have to do, for the most part, with objects having in view man's life in the world or preparation therefore. The essential use of Sunday is that it gives us rest from these concerns and reminds us that we live for the other world and not only for this. It is very easy for us to forget this; or rather, to keep it in the memory as a well-known truth, but to neglect its obvious lesson. It is, therefore, good and necessary that we should have one day set apart every week on which the mind can free itself from purely worldly concerns, and enter into a state of worship.

This entering on a new state is represented by the good and common practice of having Sunday clothes; for clothes signify state, and the best clothes being kept for Sunday represents a new and better state. I say that this is a good practice; it is of course rarely thought of in the way I have mentioned, and yet it is a fact; new clothes do assist in the putting on of a new state. However, the mere fact of putting on new clothes for Sunday, is of littler account comparatively. The thing is to put on, or enter into a new state, that is, a state which is related to the end for which man is created on earth.

To enter upon a new state, -- this is the end of the institution of the Sabbath, and it is in order that we may the better do this, that we should so far as possible lay aside on the Sabbath all that work that associates itself with our everyday life. Thus it is wise not to leave studies to be done on the Sabbath. I know that sometimes this is unavoidable, but at any rate we can have it in mind to avoid it as far as possible. We should try as far as possible to remove from ourselves on the Sabbath all that savors of everyday and compulsory labor.

We may note here that nowhere, either in the Old Testament or in the New, is there any command not to play on the Sabbath. This interpretation is purely man-made. The command not to work, that is, to remove oneself from the labor and toil that concentrates the mind on worldly objects. The day is a day on which we shall call to mind our spiritual duties, in order that these may be confirmed with us and, so may enter into and influence the work of the coming week. The first duties of the day therefore are the duties of worship, and the second duties are the duties of the love of the neighbor. The day is to be a day of Divine worship and of the exercise of charity towards the neighbor, -- this latter including the recreations of charity. It is for each one to decide for himself what recreations best serve to preserve in him the Sabbath as a day of rest from worldly ends. With older persons it is usually the recreation of conversation, especially about things of the church; and also the reading of more serious matters with the younger people it consists frequently in taking walks and entering into the unrestrained delights of friendship, -- indeed, with both it is a day when the bonds of friendship in the Church are greatly strengthened; with children it is a day on which they feel free to amuse themselves without restraint. But with all, there is this one thing in common, namely, that they are free from the compulsions of the daily task, free to express themselves according to the desires. There can be no reasonable objection to amusements on the Sabbath, if such amusements promote friendship between those who are spiritually brethren; but we may add, that charity demands that such amusements shall not be so engaged in as to obtrude themselves upon others whose conscience is opposed to them. The essential thing is to keep the day free for the worship of the Lord and for the exercise of charity to the neighbor and the entry into the delights of that charity; and I would say that one of the best external ways to do this is to try as far as possible to finish all the duties of the week before Sunday.

One word more I should like to add. The six days of labor in the world represent the combats against evils, and the seventh day represents heaven which is the end and crown of these combats. We are to do all our work of combat on the six days, that is, while me are in the world, for the seventh day is the Sabbath of the Lord. There is no reformation after death, no temptation, no combat against evil; but man then enters into the rest which he has earned by the labors of the day. Blessed are the dead who die in the Lord; they shall rest from their labors, for their works do follow with them.

== XIII. CREATION IN SIX DAYS (1). 

Genesis 1:1-19; Mark 4:1-20; @HH 284-6; @TCR 392.

In it thou shalt not do any work, thou, nor thy son nor thy daughter, thy manservant nor thy maidservant, nor thy cattle nor thy stranger that is within thy gates. For in six days the LORD made heaven and earth, the se and all that is in them, and rested on the seventh day; wherefore the LORD blessed the Sabbath day and hallowed it. (Exodus 20:10-11).

In these words we are given the reason why the Sabbath is to be hallowed, namely, because in six days the Lord made the heavens and the earth and the sea, and rested on the seventh day. Clearly this refers to the early part of Genesis where the work of creation is set forth as a work of six days. It is as though the whole of that chapter were brought in here as a reason for this commandment. Let us then briefly examine this chapter in Genesis.

It must first be premised that by day is not meant a day; for as the Psalmist says, A thousand years in the sight are but as yesterday when it is passed, and as a watch in the night. (Psalms 90:4). What is meant by days in the history of creation is not meant by days in the history of creation is not days, but stages in the work of creation. Thus when the earth was first separated from the sun as a ball of globe of finite substances, those substances were at first without form; that is to say, they had not been formed into any forms of uses, such as trees and animals, etc., they were then as yet unformed material from which the forms of uses were to be made up - or fashioned - the chaos of the ancients. Now, that the earth or primitive globe might be brought from this condition of chaos to that ordered state portrayed in the garden of Eden, filled with the forms of uses, various stages were required; that is to say, one thing must be accomplished before another, dependent on it, can be done; just as the saw mill or quarry man must finish his work before the burden or the sculptor can accomplish his. It is these stages that are meant by the days of creation.

It is true that the first chapter of Genesis actually describes the creation of the world, but it describes it, not in the language of science (for there was no natural science at that time), but in the language of those in whose days the account of creation was written, that is, in the language of types or correspondences. We do not propose to dwell on this matter, further than to observe the general law of creation, that the dry land had to emerge from the waters before the vegetable kingdom could be formed; that the first of that kingdom is the lowest grasses - lichens - and that these are necessary that by their death they may furnish something of the humus or ground to bring forth higher vegetables; that the higher herbs must also be first created before trees, in order that by their death and decay a richer humus or ground might be formed, enriched with new chemical particles; that when the vegetable kingdom is in existence, then for the first time do the seasons exist and are manifested forth in that kingdom which is meant by the creation of the sun and moon; that the animal kingdom cannot be formed until after the vegetable, since it depends on the latter for its subsistence; that the first forms of the animal kingdom were the lowest of creeping and flying things, that is, the lowest of the insect kingdom, such as those ephemera that comprise their whole life in a few hours, wherein, perhaps, they live in water or slime alone, or wherein they also rise into the air like butterflies to enter as it were for a brief space into their heaven; that thus creation of animals went on from the lesser to the greater, until at last Man was created as the crown of the work, and for whose formation the quintessence of all the dust of the earth was required.

But the Word is concerned primarily not with the mode of creation, but with the regeneration of man. In fact the regeneration of man and the creation of the world must correspond to each other. For the creation is nothing but the proceeding of the Divine Love and Wisdom to the fulfillment of the End of creation, which is a heaven from the human race; and the laws by which it proceeds when operating on matter for the certain of the three kingdoms of nature must be the same as the laws by which it operates on the human mind to form therein the kingdom of heaven that is within you, or the celestial paradise. The first chapter of Genesis is therefore not only a description of creation, but also a description of the way in which man is born again or regenerated.

At the beginning of regeneration his mind is in darkness as to spiritual things; as a child he lives in the world and for the world, nor does he occupy himself with spiritual things except that he does the things of the church and religion because brought up to do so by his parents. Then about the age of sixteen or seventeen comes a time when he begins to realize that he is responsible for himself; that he must obey the truths of the church, not because his parents say so, but because they are the Lord's commands. This is what is meant by the creation of light; for this thinking concerning what has been learned from parents and teachers, and thinking about the necessity of obeying the commandments because God has commanded them, is the beginning of spiritual light, in which the young person begins to see that there are such things as spiritual things, spiritual treasures which are more to be preferred than worldly treasurers. This is the first stage of regeneration, and the fruit of it is that light is separated from darkness, that is to say, that the young person begins to discriminate between truth that inspires to duty, and false suggestions and persuasions that ever soothe to the doing of evil.

The next stage, or the second day of creation or regeneration is the separation of the sky with its watery clouds from the waters on the earth, by which is meant the separation and discrimination between spiritual and natural truths, a separation between the dictates of moral and civil and social precepts, and spiritual truth. Spiritual truths concern always our relations to God the Lord, and they always involve the thought and desire of the heart and intention; civil and moral truths concern our life in the world, and involve our external conduct. Early in regeneration we must learn to discriminate between them in order that our conduct may be subservient to principles of religion; that is, in order that spiritual truth may be above and natural truth below. When we have the light of truth, we can do this, but only by effort; and if we do not make this effort we shall find that merely natural principles, which have as their end success in the world without regard to the spiritual state - that merely natural principles are above and spiritual principles below. This is the second stage of regeneration.

By these means man forms for himself, or rather the Lord establishes with him a solid body of principles on which he can stand firm; it is these that are meant by the dry ground; and it is to such ground that Luther referred when he exclaimed before the council that wished to condemn him to death, Hier stande Ich, Ich kann nicht anders (Here I stand, I can do no otherwise). When this ground is established, then the man can begin the performance of spiritual uses; that is, of uses which he performs in his spirit. Any one can perform uses in the body, whether from a good or bad motive; but only the good can perform spiritual uses. From each man there proceeds a sphere of his love; when a man is in evil thoughts and desires and gives way to them so far as to imagine them and delight in the imagination then there proceeds from him a sphere of evil which, whenever it touches the minds of other men, strives to perform evil uses to them by inspiring similar evil delights in them - just as the odors of poisonous plants strive to injure the life of those who inhale them. But the sphere of a spiritually good man is like the lovely odor of a good and useful plant, which strives to give life and delight. It is the sphere of a man that makes the spiritual uses that he performs. True, he does not see these uses, but he does, or can if he wants to, see himself doing these evil things in his imagination; and he may know that if he persists in them he is willing evil uses to the neighbor, and that his sphere is actually doing such evil uses or striving to do them. To bring forth spiritual uses, signified by the vegetable kingdom, is the work of the third day.

And as in our explanation we have now reached the middle of the week of regeneration, it would be well to pause here. But let us briefly sum up in this one sentiment:

 The first part of the labor of the six days whereby the Lord attains the End of His Love which is the salvation of man, consists in the establishment in man of spiritual principles which bring light; that in all the circumstances of his life he must stand firmly on these principles, and shun what opposes or would twist them; that in this way he will be a servant in the Lord's hands for the production of spiritual uses which do their work in ways unknown to him, and at the same time will enter into the life of active and useful work in the world. Through His commandments the Lord will make him wiser than his enemies, the persuasions of evil; for those commandments are ever with those who fear Him. (Psalms 119:98).

== XIV. CREATION IN SIX DAYS (2). 

Kings 18:17-40; John 13:1-17; @TCR 535 or @HH 528-529.

In it thou shalt not do any work, thou nor thy son nor thy daughter, thy manservant nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates. For in six days the LORD made heaven and earth, the sea and all that is in them, and rested on the seventh day; therefore, the LORD blessed the seventh day and hallowed it. (Exodus 20:10-11).

In our last address on this commandment we observed that in these words is given the reason why the seventh day was to be hallowed, namely, because the work of creation was done in six days and God rested on the seventh day; and that it is as if the whole of the chapter in Genesis which describes creation were included in this commandment. We therefore proceeded to give a general view of that chapter in its internal sense. It was shown that by the creation of light on the first day is meant the commencement of spiritual thought which comes to the young man or woman at the beginning of regeneration that by the separation of the clouds from the water which was the work of the second day, is meant the discrimination between what is spiritual and what is worldly in the motives that inspire the conduct; and that by the appearance of the dry ground and the creation thereon of the vegetable kingdom is meant that when the principles of spiritual truth are established with the regenerating man, then he begins to have some firm foundation for the growth of a spiritual life, and then on the basis of this foundation he begins to perform spiritual uses, which are not the uses done with the body, but which may and should be within such uses. These uses are what are meant by the various things of the vegetable kingdom. At this point we stopped our consideration of the work of creation; and at this point, therefore, we shall now resume it.

The work of the fourth day, the creation of sun, moon, and stars, has been a puzzle to commentators of the Word; while to scoffers it has always furnished a cheap way for ridicule. And yet these latter, had they been somewhat humble and not conceited, might have reflected that it is just possible that the early men who could write such an account as is given in the early chapters of Genesis, might have known that light comes from the sun, moon, and stars; and that possibly when they wrote on the fourth, what they really meant was something else than the stupid error with which modern conceit charges them. In the natural sense we may as well assume that these early writers knew that the sun was the source of light, for indeed they say, that it was created to give light upon the earth, and that therefore they meant to convey some special meaning when they wrote that the sun was created after light. In the natural sense this meaning seems to be that while, before the creation of the vegetable kingdom there was the light of the sun, yet this light was a cold light, that is, a light after the vegetable kingdom was formed the light and heat of the sun begins to be manifested in the seasons with all their charms. However this may be, there can be no doubt as to the spiritual sense.

The Lord who is the Sun of Life, is indeed the only source of light; it is from Him that the light comes whereby man first begins to see spiritual things, and thus to see the entrance to the path of regeneration. But in the beginning of regeneration this light is a cold light; it is of the conscience rather than of the desire. When, however, the man has used his conscience to shun evils and do uses, then there is born in his mind the fruits of the seed sown in his understanding; these fruits are what is meant by the vegetable kingdom, and are uses done by the spirit of the man. Now, when man comes to this state of really obeying the truth because it is of his conscience to do so, and when, consequently, he shuns as sin everything that is opposed to this truth, then the internal man is opened with him.

Every one has an inmost or soul in which the Lord inmostly dwells with him. But at first man lives only in his external or natural mind which is aroused and stimulated by the senses. His soul is as it were shut up, and life flows from it into the natural mind only as it were through chinks and crannies - sufficient to give him freedom and rationality. But when man begins to think about spiritual things and to hold them as sacred, then the natural mind comes into such a state that it turns to the soul or interior mind, and, as it were, opens itself to receive life from the internal mind or soul where the Lord dwells with man. This opening is what is meant by the sun, moon, and stars being created after the vegetable kingdoms.

When man comes into this state he begins to see the Lord from himself and no longer merely from the truths of the church; and he begins to fed in himself the warmth of heavenly love, which is the Sun; and the light of truth, which is the moon; and the additional light which all the sciences give to the truth of religion, which are the stars. Prior to this state man had seen the truth in the light of others; after he has performed the uses of life from obedience to the truth of the Word, he begins to see it in its own light; for his mind begins to be opened, and then the light of the Spiritual Sun which shines into the soul or internal mind, begins to shine also into the natural mind, and there to illumine the truths that have been learned (the moon),.and to illumine also the sciences that have been stored in the memory (the stars.)

It is after this that the animal kingdom can be created; for the animal kingdom signifies, not uses, but the affections from which uses are performed. Animals are indeed nothing but living, acting affections; and in the spiritual world this is easily proved; for there, when an angel or spirit is in any active affection than at once certain animals or birds are seen around him. The animals that were created on the fifth day were fishes and birds, and by fishes are signified the affections of knowledges, that is, the affection for the knowledges that have been learned from the letter of the Word - for the Word is the great sea wherein live fishes - and by birds are meant the affections for spiritual truths - for these like birds ascend into the heavens. It is when the internal man is opened that man begins to feel the warmth of the spiritual sun which shines there; and the first effect of this warmth is the growth of affections - affections of truth, so that the regenerating man begins to feel in himself something of the real love of truth for itself.

After this comes the work of the sixth day, when the mammals, or the higher animals of the earth were created. By these animals are meant, not affections of truths, but affections of good; for these animals are engaged in actually performing uses upon the earth, and they therefore signify the love of uses which is the same thing as the love of good. It is after the internal man has been opened, and the light of the spiritual sun received, to make the ground of man's mind fruitfulit is after this that there begins to be created in him the affection of truth; and then if he continues in this, there will also appear in increasing perfection, the affection of good itself, that is to say, the love of good, not because the Word so commands, or conscience so dictates, but because it is loved for its own sake. Very few men arrive at this stage of regeneration; most men go only to the first or second stage. But it is possible for everyone who knows these things to do them; and so it is possible, for those who are of the new Church to reach this sixth stage of regeneration. The close of this stage is the creation of man who is the crown of the animal kingdom, and in his creation is represented that by regeneration man becomes the image and likeness of God.

We must again refer to another address the more particular application of this exposition of the story of creation to the particular text with which we are now concerned, the text namely about hallowing the Sabbath. But we would close with this thought. The Lord created man into his image and likeness; that is, He gave man to be in appearance as it were a self-existent being. But this image of God is at first only a natural image; the body appears to live from itself and the mind to think from itself. In later years the man is to decide whether he - the mind that is forming - will become an image of God or a slave of the devil. The carrying out of this decision is the labor of the six days of creation, that is, regeneration. The very fact that you know of the possibilities of regeneration, the very fact that you are now reading concerning these things in the sphere of worship - this very fact alone sufficiently indicates that each one of you can if he wills, become an image of God as to his internal man - an image which appears most to live from itself and in freedom, because it acknowledges that it lives from God and the laws of His heavenly kingdom. If ye know these things, happy are ye if ye do them.

== XV. SABBATH REST. 

Ezekiel 33:1-20; Revelation 20:6-15; @DP 310.

In it thou shalt not do any work, thou nor thy son nor thy daughter, thy manservant nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates. For in six days the LORD made heaven and earth, the sea and all that is in them, and rested on the seventh day; therefore, the LORD blessed the seventh day and hallowed it. (Exodus 20:10-11).

In the last two discourses I dwelt on the latter part of these words, namely the reference to the reasons why the Sabbath was to be hallowed; and I showed that in these latter words of the text is involved the whole story of creation or regeneration as given in the first chapter of Genesis. The story, however, not only describes the course of man's regeneration, but more particularly it describes the steps by which the men of the most ancient church were raised up from being almost animals to men of heavenly perception; the story of creation is the story of the various stages by which the first church on earth grew from its infancy to its prime. It is by these same steps that men now are to be regenerated in order that they may enter into the rest of the Sabbath day.

By the Sabbath here is meant the regenerate state itself, or the state of conjunction with the Lord, or heaven itself. This is evident from the fact that it is described as a day of rest, and there can be no rest until temptations have been endured and conquered in. Rest is frequently used in the Word as meaning death and the life of heaven; as in Job, Why died I not from the womb? For now should I have lain still and been quiet; then had I been at rest (Job 3:11-13), and again the same prophet, There the wicked cease from troubling and there the weary be at rest (Job 5:17). By the weary here is meant those who have been wearied in the combats against evils, for they are spoken of as opposite to the wicked. Rest is evidently used for heaven also in the following passages, Thus saith the LORD, Stand ye in the ways and see, and ask for the old paths, where is the good way, and walk therein, and ye shall find rest for your souls (Jeremiah 6:10). Come unto Me all ye that labor and are heavy laden and I will give you rest (Matthew 11:28). It is a people that do err in their heart, unto whom I swear in My wrath that they should not enter into My rest (Psalms 95:10-11).Blessed are the dead who die in the Lord; they shall rest from their labors, for their works do follow with them (Revelation 14:13).

It was in this sense of rest as meaning heaven, that this command was understood by the Apostle Paul in his preaching to the Hebrews, where he says, There remaineth a rest to the people of God; for he that is entered into his rest, hath ceased from his own works, as God did from His. Let us labor therefore to enter into that rest lest any man fall according to this example of unbelief. For the Word of God is quick and powerful and sharper than any two-edged sword, and is a discerner of the thoughts and intents of the heart (Hebrews 4:9-12).

Our ideas are at once elevated from the natural ideas of rest for the material body, or rest from the cares and worries or the world, to the idea of spiritual rest, which is deliverance from evil, and which when attained is indeed heaven with man. The work of creation was for the end of giving man this rest; and because this is the End of the Divine Love therefore it is said that when the work of creation was finished God rested; that is to say, when the regeneration of man is accomplished the End of the Divine Love is with that man accomplished and as it were rests or abides with him. It is this rest that is meant by peace where the Lord says, These things I have spoken unto you that ye might have peace. In the world ye shall have tribulation; but be of good cheer, I have overcome the world (John 16:33).

This rest, or peace, as plainly said in the last quotation from the Word, can be obtained only by struggling against evil. There is and can be no rest so long as evil rules in the heart. Every man can see this on the slightest reflection. How can there be rest if one's neighbors are not honest, are not willing to help one? and if this is so plainly the case in natural things, how much more must it be the case in spiritual things? Moreover a an perceives in himself the unrest of evil; that it gives him no peace; that there is in evil an ever present desire which wearies when it is attained, or else grows to greater demands.

This rest, or peace, as plainly said in the last quotation form the Word, can be obtained only by struggling against evil. There is and can be no rest so long as evil rules in the heart. Every man can see this on the slightest reflection. How can there be rest if one's neighbors are not honest, are not willing to help one? and if this is so plainly the case in natural things, how much more must it be the case in spiritual things? Moreover a man perceives in himself the unrest of evil; that it gives him no peace; that there is in evil an ever present desire which wearies when it is attained, or else grows to greater demands.

Rest, reset, of mind, which is peace, can be found only after the labor of temptation. The rest is to be fully realized in heaven, which is meant by the Sabbath day; but first come the six days of labor, that is, the days or states that introduce to eternal life. On these six days we must do all our work; not a part of it. We cannot say, O well, Ill find it easier to shun this or that evil tomorrow, or next year, or in the other life. The work must be done now, while we have the six days of labor before us; and if it s not done now there will be no rest, no heavenly state after death. It is because no the state of hell is the lot of those who do not do all their work in the six days of labor, that the desecration of the Sabbath day by working thereon was punished in the Israelitish Church by the extreme penalty of death. There is no regeneration after death; man then will remain to all eternity of the character which he has formed on earth; he will grow in perfection, in wisdom, in happiness, but all his growth will be along the lines of character he himself has laid down during his life and earth. There is no changing this. Where the tree falls there shall it lie; as the man lives so shall he die.

Men have argued as against this, that to determine a man's character merely from a few years spent on earth would be unjust. But such men do not take into account the very elementaries of the science of the human mind. The mind, the will, is actually an organic form, it is a form, just as much as the hand is a form. And this form is actually shaped and hardened as it were, or confirmed, by man while he is in the world, and has a material body - just as much as the hand is shaped to being apt for certain motions and actions according as the owner of the hand practices with it. Now man begins the forming of his real will, his real mind, his spirit that will live after death - man begins forming this about the time of puberty. He then begins to think for himself; to reflect on his aims, and objects; to have some desire for a useful life; for a life of pure marriage with the one of his choice. All this has some commencement at the time of puberty. And in the years that follow, the man undergoes trials that assail these desires and ideals. Most men soon learn to give them up for the sake of what they call getting on in the world. But whether they persevere or give up, the fact remains that they are actually building up their mind, the mind that is their very selves. And as this building goes on it becomes more and more difficult to change its lines. A change may, however, be made at any time so long as a man is living in this world; but as the man grows older he becomes more and more confirmed so that it is almost certain that he will not change his character.

Now if this is the case with the few years in which we live from young manhood to adult life,the years that are the formative years,how shall we expect that it would be different if man were to live a thousand years? or how are we to expect that man call change his character after death

But here another reason comes in. Man cannot change his character after death because he then no longer has a material body; he no longer has a tired ultimate plane, where the habits, and loves which he has striven to cultivate, call be changed. Reflect a moment, and you will see that though evil desires are in the will, yet we are able to actually direct the eyes to the Word, we are able to move the hands to the Word, and take and read it. We can do this by virtue of the fact that we have a fixed ultimate body, which will do whatever the spirit bids it, and this quite independent of the state of the spirit. If we did not have such a body, it would never be possible for us to reform our mind; for we should have to speak and do whatever was in the love and thought; thus there could never be any change. But since we have a body independent, as it were, of the spirit, we call thereby receive the things of heaven, pay attention to them, hearken to the Lord and obey Him. If, and as, we do this, the forms of heaven are actually impressed on the mind; and if we keep on doing it, keep on forcing ourselves to do our duty, these forms impressed on the mind will become more and more confirmed until at last they become our new character, our new mind, the regenerated or reborn mind which is born not of blood nor of the will of the flesh, nor of the will of man, but of God (John 1:13). But in the other world man's body makes one with his spirit; it cannot act differently from the thoughts and loves of the spirit; a spirit must say what he thinks, and must do, or try to do, what he wills; he has no material body behind which to hide and, consequently, no body by means of which he can change his character if he will.

Regeneration is possible only in this world. It is here we actually form our spiritual body, and as we form it so shall it remain, a thing of beauty or a thing of ugliness, -- a child of God, or a child of the Devil.

The six days of earthly life are given us, and to us is given the command that in those days we shall do all our labor, nor leave any of it to be done on the seventh day. This commandment is given from the Divine love, for only by obeying it can we realize the End of creation; only by obeying it can we have the Sabbath day wherein God rests after doing upon us the work of regeneration or spiritual creation. This is the work that lies before us, the work of the six days, that we may enter into the Sabbath of the Lord our God.

== XVI. THE FORMING OF THE MIND. 

Psalms 144; John 9:1-7; @HH 278.

In it thou shalt not do any work, thou, nor thy son nor thy daughter, thy manservant nor thy maidservant, nor thy cattle nor thy sojourner, nor thy stranger that is within thy gages. (Exodus 20:10).

In previous sermons on these words we have shown that all man's work of regeneration is to be done during the six days which represent his life on earth, and this, in order that he may enter into conjunction with the Lord; conjunction with the Lord is what is meant by rest, for when man is conjoined with the Lord the Lord rests or abides with him, according to the words of John, Abide in me and I in you (John 15:4). When man abides in the Lord and the Lord abides with him, then he is in peace and in the happiness of heaven, which is the happiness of love to the Lord and charity towards the neighbor.

I also showed that man's mind is, as it were, a house which is to built up in this world by the six days of labor, and that if this house is built by the Lord it becomes a habitation of the Lord, and when the work is finished by death, the man will enter into that house as his eternal abode, where he shall rest from his labors.

The particular words before us now, describe the state of peace or rest that follows the days of labor; for they declare that after the six days no one in the house is to labor, and the clear implication is that all in the house will, on the Sabbath, enter into the rest or reward of their labors. The subject, therefore, is the state of heavenly blessedness with the regenerate man. In particular it describes that state as it will be after death; but in a more general sense it describes that state as it is even on earth with those who shun evils as sins against God. The difference, however, is that in heaven the state is not interrupted by the trials and labors of temptation, the Sabbath is an eternal one of delight in the performance of uses; but on earth the pence of heaven is often interrupted by the labors of new trials and temptations, -- the Sabbath comes, indeed, but it gives place to another and another week of labor.

This state of peace and rest is described as being given to the whole household that is, to all the things of the mind which is man's house. Thou refers to the whole man, for in a single word it comprises the head of the household and the whole household as represented by that head. The words that follow, and which describe the various things in the house to whom the rest shall be given, refer to the various things in the human mind. For the peace of heaven, as is here declared in the internal sense, is a peace not only of the internal man, but also of the external man; in fact, of all the things that pertain to the human mind.

The son and daughter represent the things of the internal man, the servants the things in the external man, the cattle the external affections, and the sojourner the external knowledge which resides in the outer courts of the natural mind. These significations are apparent at first sight, but if we examine them more in detail we shall see more clearly how it is that the life of regeneration brings peace and rest. Let us then enquire what is meant by the internal man and what by the external.

At birth every man has merely the faculty of mind. He does not have a mind of his own. His mind is yet to be formed. Now the formation of the mind is possible with him because he has from the human soul, that is, from the inmost region of his life where the Lord alone dwells, the faculty of nationality and liberty. No animal has this faculty, because no animal has this inmost region which is the Lord's dwelling place. This inmost region, which is called the human internal, cannot be injured by man; it is the same in the evil as in the good; and this is the reason why even the devils of hell have still the faculties of rationality and liberty, and, though they do not use these faculties in order to shun what is evil, they still use them sufficiently to guide them in at last coming into some sort of order, like the order of a prison house, and this because from their faculties they are able to realize that otherwise they will suffer punishment.

The faculty then of becoming human is therefore inborn in every man. It is because of this faculty that man is born into ignorance. Animals are born into the knowledges necessary to their lives, because they have no choice; what they are born, that they remain while they live. But man has a choice; he is born a faculty in order that he may choose for himself what he will become. An animal is born one kind of an animal, and that he remains; he is born with knowledges, and to those knowledges he is confined. But man is born without knowledges in order that he may acquire all manner of knowledges; man can become any sort of an animal, -- a human animal with heavenly love and wisdom, and with knowledges of many kinds; or a beastly animal, a fox, a serpent, a toad, a tiger; but if he becomes one of these, then he is worse than even the evil animals, because he might have been a human man. Indeed, it is a matter of common perception that the evil man is worse, more savage, cruel, and relentless than any animal.

The mind is first formed by means of the senses. Objects of the world enter in, through the senses of sight and hearing especially, in a way not unlike that in which the modifications of the ether affect a photographic plate. But there is this difference, that on a photographic plate there is a mere impression oil the sensitive surface; the plate is dead; but the human mind is living and hence when an impression comes to it from the outer world, that impression becomes a sensation. We sensate the things that come to us through sight and hearing; and, what is wonderful, from our inborn faculties, we sensate these things as good or as evil, as pleasant and delightful, or as unpleasant and painful. This is a matter of common experience. It is as with our sensation of taste. When we taste something for the first time we heaven inborn perception as to whether or not it is pleasant to us; if it is pleasant we want to repeat the sensation; if it is unpleasant we want to avoid that food in future. But there is this to be added, namely, we have what no animal has, a superior perception, or a superior sensation, whereby we call decide whether the food we taste is healthy for us. We may put a food on our tongue and find it tastes very nice, and yet we may decide that it is not good for us; that is, to the tongue and the external mind, it tastes agreeable, and we wish to take it again; but to the rational mind, which is better instructed, this pleasant taste is seen to be deceptive; it is seen that what seems so pleasant is really unhealthy, and so, the rational mind decides that the tongue shall not have this food any more.

Now it is the same with the food of the mind, as with the food of the body. Many things come to our experience. It may be that we have indulged in a certain line of conduct; we have, perhaps, been disobedient to those in authority; or indulged in evil passions, or in the satisfaction of wicked lusts; or in hatred and revenge; and in all these we have found a delight. It is delightful to the natural mind to indulge it; whatever satisfies its desires; and because the natural mind is formed only by the things of the world and by worldly experience; it perceives delight or pleasure only in things that have the world, and life in the world, as an end and object.

But we find that we have also another mind, a mind, namely, which can look down on the pleasures of the natural mind and condemn them. We may, for instance, have given way to some evil pleasure, or to the indulgence of impure passion, if not in deed yet in imagination; when doing this, we naturally experience pleasure and wish to repeat the experience; but, at the same time, we have a perception that this pleasure is evil, that what seems to the natural mind to be so delightful is really deadly poison to our real life. This thought comes from the internal mind.

The beginning of the internal mind is formed in infancy when we are in the innocence of ignorance. In our childhood days we have stored up with us good states of love to the Lord and charity to parents and friends. These are only external, but yet they are the beginning of heaven with man. You can readily see this if you will reflect how often it is that thought concerning your childhood days and your states then, has been the center, as it were, from which you have been strengthened to live a life of religion.

We have two minds therefore, -- a spiritual and a natural. The spiritual is strengthened by reading of the Word and the life of religion; it is formed first in infancy, when it is tender and delicate, it increases in firmness as we read and obey the Lord. The external mind is formed from the pleasures of the world. And between the two minds there is a conflict; for the one sees that to be good which the other perceives to be evil. This combat is the labor of temptation. and the end of it is that one mind or the other will prevail.

Time will not allow me to pursue the matter further now, further than to say, that the labor of temptation which we are to engage in while on this earth, consists in making the natural or external mind obedient to the spiritual or internal mind; in saying to the natural mind, I know you would like to do this or that, but I forbid it because it is a sill against God and is destructive of the spiritual life.

If the natural man is not made obedient, then the labor of the six days is not done. There is no rest for that man, his desires are never satisfied; and in the other life also they are never satisfied; and yet they never can be satisfied, because they are against. the laws of heaven. Such a man is, therefore, compelled to obey the laws of heaven; compelled to restrain himself from doing the very things in which he has placed the greatest delight. His delight, his life, is evil, and he is forced to give it up, except in imagination; instead of the rest of the Sabbath lie is put to death because he did not do all his work on the six days of labor; for spiritual death consists in the deprivation of the delights of life.

But if the spiritual mind prevails in the combat, then there is pence with that man, -- peace in his spiritual mind; peace in his natural mind, which now obeys the laws of God and feels the delight of the obedience; and peace also in the very affections of even his body and senses, and order in the knowledges which are stored in his mind. This is the peace of rest of the whole man and of all who are with him that is described in the words of the text. It is the peace of heaven; eternal peace, a peace for which we must fight and which we can obtain only by fighting; and to attain this peace and its heavenly delights is the end for which we are born on earth.

== XVII. THE HOUSEHOLD OF THE MIND. 

Haggai 1:1-11; Matthew 10:24-39; @CL 120-121.

In it thou shalt not do any work, thou, nor thy son nor thy daughter, thy manservant nor thy maidservant, nor thy cattle nor thy stranger that is within thy gates. (Exodus 20:10).

In the last discourse on these words I dwelt on their signification as being the human mind and all things therein; and I spoke more particularly on the internal and external mind and their formation. Both minds must be formed after birth; the external mind is that mind which is formed from and by the things, sensations, and delights, that flow in through the senses. Thus this mind is an image of the world; all its thoughts and imaginations and aspirations, concern things in the world, the securing of ends and purposes in the world, and the enjoyment of delights in the world. This mind may therefore be called a little world or microcosm.

The internal mind, on the other hand, is formed by influx from the spiritual world, or, rather, from heaven; but the means of its formation, that is to say, the means that enable the influx from heaven to be received, are the senses. Heaven, and by heaven I mean the sphere of love and charity that proceeds from all the inhabitants of heaven, -- a sphere which proceeds from them because the Lord dwells with them, and which, in fact, is the Divine Sphere proceeding and operating through them, the sphere, namely, of the love of the salvation of man, -- Heaven (I repeat) is in the constant effort to inflow with man, to be present with him, to be received by him so that it can communicate to him its own happiness. But heaven cannot be received unless there is a vessel that shall be fitted to receive. It is as with the sphere or odor that proceeds from a flower; this sphere is, as it were, in the constant effort, to enter into man and give him its delights; but it cannot do so unless man has a nose and nostrils, and directs this organ to receive the odor.

The vessel that receives the spheres of heaven is formed solely by truths from the Word; for these truths, by their very nature turn the mind away from the Word and its objects as the sole objects of our love and thought, and direct the mind to the consideration of the spiritual world, -- to the consideration of duties that belong to another sphere than this earth. When man reads the Word, -- and I include also the Writings of the New Church, and in a most general sense, all works that direct the thought to spiritual things, -- when man reads the Word his mind is directed upwards to the Lord; he thinks of duties to the Lord and to his neighbor entirely separate from whether he will externally profit by the performance of such duties. He thinks of what is right and wrong in the sight of God, and not of what will best prosper him in his earthly life. This thought, this contemplation, forms a vessel that is turned upwards to the Lord, that is to say, it forms the mind itself into such a vessel; and when the mind is so formed heaven at once flows in, or is received; and the influx of heaven gives to the man a perception of delight in the thought of the things of heaven, -- a delight that is weak at first, but that grows stronger as lie perseveres in the life of heaven. This constitutes the internal mind.

Both minds, the internal and the external, can exist together, -- the external as an image of the world, and the internal as all image of heaven; the external as the scene or theater in which are portrayed in imagination, the hopes and loves and aspirations as regards things of the world, and the internal in which are portrayed in internal imaginations, the hopes and loves and aspirations as regards the things of heaven. But you will at once see, that before these two minds can adjust themselves so as to work together, there must be a conflict. Heaven inflows into the internal mind, and hell into the external; for the spirits of hell are men who in the world have loved only the things of the flesh and the world, and, therefore, their spheres and presence is at once felt by man as soon as the external mind is opened to the world; and their constant effort is to hold man in the delights of the external mind. There must then be a conflict between the two minds as to which will prevail; the conflict is in reality a conflict between heaven and hell as to which shall gain possession of the man; but it is felt by the man as a conflict between his internal mind and his external. This conflict is what the Lord refers to when he says, The disciple is not above his master nor the servant above his lord; It Is enough for the disciple that he be as his master and the servant as his lord. (Matthew 10:21-25). By the master and lord is meant the internal man, and by the disciple and servant the external man. If the internal man becomes the master then the external man comes into peace and happiness and wisdom like his master, but if the external man becomes the master then the internal man is suppressed, that is to say, it is shut up from heaven and open only to the world, and so, it also becomes like its master.

Now in this conflict, as to the mastery between the internal arid external man, or mind, both minds have their work or labor which must be accomplished during the six days of life on earth. The whole household must work, for it is the whole household that is meant by the word thou in the text, -- a word which, indeed, means the master of the house, but which involves the whole household as being under the orders and directions of the master. And the text then specifies what are the things in this house or man, that must work; the son and daughter, the servants, man and maid, the cattle and the stranger.

The son and daughter are the spiritual truths, and the spiritual affections that are in the internal mind, and that, like the son and daughter of the house, dwell in the choicest rooms. A man represents truth, because he is a form of the love of acquiring truths, but a woman represents affections because she is a form of the love of truths acquired, -- the love of listening to truths and receiving them.

By the son and daughter doing their work is therefore meant, that these spiritual truths which we have in our mind, and the spiritual affections, affections of the church, of the Word, of worship, of duty, must all do their work in subduing the loves of the external man; must, like son and daughter, direct the servants of the house so that they shall be good and useful servants, and not rebellious. This work is done when we direct the likes and the deeds of the external mind according to the spiritual truths and the spiritual affections that have been stored up in the internal mind.

These likes, and these deeds, are what are meant by the servants, man and maid; the manservant being the thoughts of the external man, such as worldly ambition, thoughts of worldly reputation and success; and the maidservant being affections for such things. These thoughts and these affections are good and useful if they work as servants and not as the rulers of the house of the mind. They must, indeed, do their work on the six days, but their work consists in listening to and obeying the voice of the son and daughter, the principles and affections of the internal man.

So likewise the cattle. By the cattle are meant the corporeal affections, that is to say, affections of the body and the senses. This signification owes its origin to the fact that all animals are living affections of the external mind, that is, living natural affections; but since the affections of the natural mind are signified by maidservant, therefore the cattle signify the most external affections, or those of the body and senses. The stranger who is not in the house, but only within the gate, that is, in the outer court of the house, signifies those things which have not yet been received into the mind itself, but are only at the entrance. Such things are the things in the memory. Now the cattle must labor for the uses of the household, that is, the corporeal affections must labor to avoid ruling over the household, must labor to be useful cattle; and the stranger must also do this work, lest he bring injury to the house into whose courts he has been received. The work of the stranger consists in the proper ordering of the various knowledges that are in the mind, so that those knowledges shall serve the mind, and not, like treacherous strangers, destroy the house that has received them. That is to say, we must hold the knowledges in our memory merely as servants to be useful to enriching the house that it may become a temple of God, and not allow those knowledges to lead us to the denial of God and the neglect of the spiritual life.

These, then, are the labors of the household, labors that are all to be done on the six days of labor. And if those labors are done, then on the Sabbath that house will enter into rest; and it will be a household united and not divided; a household in which the servant will be as his master, that is, in the freedom and delight of heaven; a household that is one, and is united in the praise and worship of the Lord. That our mind may become such a household, which shall be as a temple in which the Lord is worshiped,that is the labor of our life on earth.
