= Ten Blessings
By Rev. Michael Gladish in two sermons
include::../template-attributes.adoc[]

////
source: https://www.swedenborgstudy.com/sermons/mirror-newchurch.org/TenBlessingsPart1.htm and ...Part2.htm ... concatenated

meta-data from html source:
<meta name="dc.creator" content="bruce">
<meta name="dc.title" content="Microsoft Word - kl_sermon_TenBlessingsPart1.doc">
<meta name="dc.date" content="2004-12-17T21:07:52Z">
<meta name="dc.date.modified" content="2004-12-17T21:07:52Z">
<meta name="generator" content="Microsoft FrontPage 6.0">

////


== Part One
////
                      Ten Blessings, Part 1 of 2
                    "Blessed are those Who Mourn."

                   A sermon by Rev. Michael Gladish
////
....
 "Blessed are the poor in spirit...
 "Blessed are those who mourn...
 "Blessed are the meek...
 "Blessed are those who hunger and thirst for righteousness...
 "Blessed are those who are persecuted for righteousness' sake...
 (Matthew 5:3-6, 10)
....

When we think of blessings we do not usually think of sadness,
difficulty or want. We usually think of happiness, peace and plenty.
Indeed the word, blessing, means happiness and suggests that we have
everything we need.

Why, then, does the Lord seem to say the opposite? You know,
practically all of human psychology today is dedicated to the principle
that we should not be poor in spirit. They say we should be rich in
spirit, meaning self-confident, with healthy self-esteem and even
self-love. They say we need to know how to be self-assertive, to know
what we want and to feel good about "going for it." They say we can't
possibly love others or be happy in society unless we feel good about
ourselves first - WHICH IN A VERY IMPORTANT WAY IS TRUE (see D.P. #53).

But then why does the Lord plainly say that the people who are poor in
spirit are blessed - not "will be blessed" but are blessed? Why does He
say that the kingdom of heaven is theirs - not "will be theirs," but is
theirs? How can we be blessed even while we are "poor in spirit?"

We can ask the same questions of the teaching about those who mourn,
those who are meek, those who hunger and thirst for righteousness, and
of course, most of all, those who are persecuted for righteousness'
sake. Really, how can you be happy when you are being persecuted!

The answer of course rests in the fuller, deeper meaning of the Lord's
words. To be poor in spirit does not mean to be self-deprecating or to
have no self-esteem. It is simply a state of self-awareness and self
acknowledgment: in effect it is a state of knowing how little we know
in relation to how much there is to know. This isn't a sad state, it's
an exciting state, full of hope and promise, full of the anticipation
of learning and growing, and, among other things, never being bored
because we know that the Lord always has more and more marvelous things
to show and teach us - forever!

The word, spirit, in the Lord's teaching specifically refers to the
understanding. It is the same as the word for wind or breath, which of
course has to do with "inspiration" [breathing in]. On the spiritual
level we are "inspired" when we get a new insight or idea, when we
suddenly understand something that has perhaps eluded us in the past.
We are then filled with anticipation and delight. But what if we are
already "rich in spirit?" What if we think we know all that we need to
know in any given area? Will we be open to new ideas? Will we be
receptive? This is exactly the situation the Lord referred to when He
said, "It is easier for a camel to go through the eye of a needle than
for a rich man to enter the kingdom of God." There is nothing wrong
with natural wealth, that was not the point. The Lord was stressing
intellectual humility.

And He said of those who have this quality, "theirs is the kingdom of
heaven." Note the present tense. The word, kingdom, obviously, refers
to the realm of a king, and the king governs by means of laws. So in
the spiritual sense a king represents the truths (or falsities) by
which we live in society. And his kingdom is the whole realm of life
and thought based on those principles. Therefore we possess the
"kingdom of heaven" as we acknowledge our need and willingness to learn
what the Lord teaches us in His Word. It is not a promise, it is a
fact.

The second blessing the Lord mentioned is for those who mourn. Again,
it seems like a contradiction: how can you be sad and happy at the same
time? Because it seems impossible many have supposed that the Lord was
simply talking about delayed gratification: mourn now, be happy later.
Suffer now, get your blessing later. From this perspective it might
seem like we're supposed to be miserable in this world, or that there's
something wrong with us if we enjoy our life in the world. But this is
not what the passage says. Those who mourn are blessed, and, what's
more, "they will be comforted."

Now, mourning is grieving, usually over some loss. It wells up from
deep within and so has more to do with feelings than with thoughts. It,
too, is a state of awareness, a real awareness and acknowledgment of
what we will or want but often can't have. In fact it is the
acknowledgment of our self-will. And since we never have everything we
want for ourselves it is obvious that when we get in touch with these
feelings we are going to be sad.

Psychologists of course are right when they say we have to get in touch
with our feelings. And they are right when they say we shouldn't
suppress or deny these feelings. If we're bitter and resentful the
first step in healing is to admit it, and really acknowledge it, then
we can face it and with the Lord's help do something about it. But if
we have a conscience based on an understanding of the truth we will
realize as part of this process not only that we can't ever have
everything we want but furthermore that this would not be right, or
good for us. And so our grief, our mourning can take on the additional
quality of sadness that we do want what we shouldn't have.

OK, so where is the blessing in this? The blessing is that this
acknowledgment heightens our awareness of the Lord's love and mercy. In
fact without it there can be no awareness of the Lord's love and mercy
and thus by definition no blessing, all of which comes from Him. We
read, "Those who give no thought to the evils in themselves, that is,
who do not examine themselves and afterwards refrain from evils, cannot
but be ignorant of what evil is and then love it from its delight. For
he who does not know evil loves it, and he who neglects to think about
it is continually in it" (DP 101:2). You cannot be blessed when you are
unaware of the evil in your life.

On the other hand, when you are aware of it - and feel grief on account
of it - not only can you begin to appreciate His mercy in that He
continues to love you and care for you in spite of these evils, you
also put yourself in the position of being willing to receive His help.
This is where the promise of comfort comes in. Do you remember the
teaching in John about the Holy Spirit, where the Lord called this "the
Comforter" and promised to send it to them after He Himself had gone
away from them (John 14:16; 16:7)? In the New King James translation
this is called "the Helper," and the same word used as a verb means "to
help." That word is Paraclete or in its verb form paracalleo, meaning
to call alongside. This is the word now used for "comfort" in the
phrase, "they shall be comforted." Literally, they shall be helped. The
Lord will walk by their side.

Briefly stated, then, this is the second of the ten blessings: Happy
are those who acknowledge their evils, for they shall get help! And
they'll get it because they want it, for there is no lack of help
offered by the Lord at any time in our lives; it's just that most of
the time we resist it because we don't think we need it. "Blessed are
those who mourn."

The third blessing that the Lord promised is for the meek. Now meekness
is not necessarily a problem for us, but the truth is that we often
think of the term in a derisive sense representing weakness or even
cowardice, as in the sentence, "He stood by meekly as his friend was
attacked." But if we think that this is what the Lord meant in His
teaching about blessing we could not be much farther from the truth.
First of all the word here translated "meek" really means "gentle" and
suggests a spiritual softness that is to be associated with patience
and kindness, not at all with weakness or tolerance of evil. It is
indeed the weak who tolerate evil, but the truly meek, those who are
truly kind, will not tolerate evil, especially in their own lives, and
so they labour constantly and courageously to act from charity in all
that they do, shunning evils as sins against the Lord and doing what is
right and good because it is right and good.

The teaching that the meek will inherit the earth is, by the way, a
direct quotation from the Old Testament (Psalm 37:11, for example),
where the Hebrew version of the word, meek, means exactly the same
thing with, perhaps, the added notion of humility and willingness to
suffer if necessary rather than inflict suffering on others. Of course
the Lord Himself gave the supreme example of this quality when He
permitted the crucifixion - not because He couldn't prevent it but
because He knew that it was necessary for the process of His
glorification to be completed. So we can follow in His steps, not so
much resisting the evils that are outside of us in others, but
resisting and indeed aggressively fighting against the evils that we
find in ourselves: evils of jealousy, greed, hatred, lust and the love
of domineering, to name just a few examples.

The Lord plainly says that when we do this we are blessed. The blessing
is in the doing. But as with those who mourn there is an additional
promise, "for they shall inherit the earth." Those of us who are
familiar with the study of correspondences know that "the earth" does
not mean the planet in a worldly sense, but our world, the world of our
own experience, the world of our minds. And surely we can all see that
when we exercise the disciplines of genuine charity we do take control
of our spiritual lives, we do inherit the "promised land" of love and
wisdom from the Lord.

Before we go on to the fourth blessing (and we will only review 5
today, leaving the other 5 for the next sermon), let's just notice that
the first three form a beautiful trilogy. The first relates to the
understanding, as we recognize our need to learn and receive the spirit
of truth. The second relates to the will, as we recognize the evils in
our hearts and take advantage of the Lord's help in overcoming them.
The third now relates to the way we behave, in that we act from
charity, not from weakness but with gentleness and kindness toward
others as we fight against the evils of our own lives.

The fourth blessing that the Lord promised was for those who hunger and
thirst for righteousness, for, He said, "they shall be filled." Hunger
relates to food and thirst to drink. Again, they are both cravings and
they relate to an awareness or acknowledgment of need.

Now the food that nourishes our spirits is the goodness of love; the
drink is the knowledge of truth. And if we're hungry and thirsty we are
aware of our need for these essential things. But the teaching
specifically stresses the hunger and thirst for righteousness, which
like meekness has to do with the way we live. A curious thing in the
Scriptures, incidentally, is that the word, righteousness, probably
should be translated "justice." "Righteousness" conveys a heavy sense
of doing what is strictly right, strictly according to the truth, but
that isn't what the Lord meant in His teaching about blessing. Rather
He was referring to those who long for the goodness of life, that is, a
life in which decisions are made on the basis of what is good for
people, not just on the basis of truth, which would be truth separated
from good.

This teaching therefore follows in order after the one about meekness.
For if meekness has to do with the quality of one's own life, the
longing for justice has to do with life in general - not only that we
should be treated well by others, but that others should be treated
well, too. When you look at the evil and the falsity and the hurt in
your community you naturally long for justice. And when you feel the
lack of integrity in your spiritual community your longing goes even
deeper.

But those who hunger and thirst for justice are blessed. Like those who
mourn they are blessed in the recognition of what is good. They are
fortunate to know about it and they are happy to have the longing for
it. True, the lack of it makes them sad, but the blessing isn't in the
lack, it's in the longing. "Blessed are those who hunger and thirst for
justice, for they shall be filled." Sooner or later, one way or
another, their longing will be satisfied. For whether they are given
the truth in this world or not, whether they are shown what is
genuinely good in this world or not, if they long for it they will
receive it as soon as it can be provided - which in many cases happens
after death in the spiritual world. And that is no shame, for the
purpose of life in this world - which is so short - is to prepare for
life in the next - which lasts forever.

To complete our series today we are going to skip the next 3 in the
sermon on the mount and go directly to the 8th, where we read about
those who are persecuted for justice's sake. Though not in order - and
the order is important - this fits the series as one of the apparent
contradictions in the Word: how can anyone be blessed if he is being
persecuted?

The answer, like the answer to the other questions we have raised, lies
in understanding the teaching on a deeper level. Remember, the
persecution is not for just any reason, it is on account of justice,
"for justice's sake." This means the person is being attacked for
taking a stand in favour of justice. It reminds me of the apostle,
John, who described himself at the beginning of the book of Revelation
as "your brother and companion in tribulation," and who said he was "on
the island that is called Pat mos for the Word of God and for the
testimony of Jesus Christ." This does not mean that he went there to
preach. No one was there! He was banished to the island because of his
preaching. He was being persecuted for justice's sake.

Now remember, you can't get to heaven unless you know the truth, or at
the very least love what is good so that you can learn the truth in
time. But those who are in evil and falsity hate the truth, and they
hate what is genuinely good. So when they see or feel it they attack
it. This is especially true of evil spirits who as a result of their
confirmed states have no inhibitions about their evils or their desire
to attack the good. And because they are spirits, in a sense there is
no escaping them. Wherever there is good they will attack and persecute
it, just as they did the Lord Himself.

What does this mean for us? Look at the positive side: if we had no
sense of justice we couldn't be attacked "for justice's sake." But if
we are so attacked and persecuted it is a sign that we have this
quality and that it is working within us. The fact that we are caught
up in temptations does not mean that we are worse than other people, it
means that we have a good, working con science, and in this conscience
we are blessed! We know what is right. We actually have the kingdom of
heaven within us. So again, the kingdom is not promised at some future
time, we read simply, it is theirs. All we have to do is maintain the
effort to hold on to it.

We will review this last teaching and the others about persecution next
month along with the three beautiful blessings about the merciful, the
pure in heart and the peacemakers. For now, and in conclusion, let us
do what we can to remember, integrate and reflect on the fact that all
these blessings relate to internal, spiritual states, and that all of
the ones we have reviewed today relate especially to states of
acknowledgment or self-awareness. "The kingdom of God," Jesus said in
Luke, "does not come with observation; nor will they say, 'See here!'
or 'See there!' For behold, the kingdom of God is within you" (Luke
17:20-21).

Bad things happen. And there are bad things within each of us. But when
we see them and acknowledge them we are taking the first steps toward
genuine happiness and peace, indeed toward the spiritual wealth and
prosperity that is the blessing of heaven. The beatitudes were the very
first systematic teachings of the Lord in His ministry. In a sense they
contain all things that follow. Not only do they tell us what to do
first (in acknowledging our needs), they assure us of the Lord's active
presence in that work so that we can feel His love and wisdom as we do
it. And finally, of course, they promise even more fulfillment in the
future as with the Lord's help we sustain our efforts and discover the
profound reality of inner peace, "the peace of God that surpasses all
understanding" (Phil 4:7), "peace that flows as a river from the
eternal Source alone" 
//(hymn 126).

Amen.

Lessons: Matthew 5:1-12 @Psalm 37:1-11; @DP 53

== Part Two
////
                      Ten Blessings, Part 1 of 2
                    "Blessed are those Who Mourn."

                   A sermon by Rev. Michael Gladish
////

....
  "Blessed are the poor in spirit...
  "Blessed are those who mourn...
  "Blessed are the meek...
  "Blessed are those who hunger and thirst for righteousness...
  "Blessed are those who are persecuted for righteousness' sake...
  (Matthew 5:3-6, 10)
....

When we think of blessings we do not usually think of sadness,
difficulty or want. We usually think of happiness, peace and plenty.
Indeed the word, blessing, means happiness and suggests that we have
everything we need.

Why, then, does the Lord seem to say the opposite? You know,
practically all of human psychology today is dedicated to the principle
that we should not be poor in spirit. They say we should be rich in
spirit, meaning self-confident, with healthy self-esteem and even
self-love. They say we need to know how to be self-assertive, to know
what we want and to feel good about "going for it." They say we can't
possibly love others or be happy in society unless we feel good about
ourselves first - WHICH IN A VERY IMPORTANT WAY IS TRUE (see D.P. #53).

But then why does the Lord plainly say that the people who are poor in
spirit are blessed - not "will be blessed" but are blessed? Why does He
say that the kingdom of heaven is theirs - not "will be theirs," but is
theirs? How can we be blessed even while we are "poor in spirit?"

We can ask the same questions of the teaching about those who mourn,
those who are meek, those who hunger and thirst for righteousness, and
of course, most of all, those who are persecuted for righteousness'
sake. Really, how can you be happy when you are being persecuted!

The answer of course rests in the fuller, deeper meaning of the Lord's
words. To be poor in spirit does not mean to be self-deprecating or to
have no self-esteem. It is simply a state of self-awareness and self
acknowledgment: in effect it is a state of knowing how little we know
in relation to how much there is to know. This isn't a sad state, it's
an exciting state, full of hope and promise, full of the anticipation
of learning and growing, and, among other things, never being bored
because we know that the Lord always has more and more marvelous things
to show and teach us - forever!

The word, spirit, in the Lord's teaching specifically refers to the
understanding. It is the same as the word for wind or breath, which of
course has to do with "inspiration" [breathing in]. On the spiritual
level we are "inspired" when we get a new insight or idea, when we
suddenly understand something that has perhaps eluded us in the past.
We are then filled with anticipation and delight. But what if we are
already "rich in spirit?" What if we think we know all that we need to
know in any given area? Will we be open to new ideas? Will we be
receptive? This is exactly the situation the Lord referred to when He
said, "It is easier for a camel to go through the eye of a needle than
for a rich man to enter the kingdom of God." There is nothing wrong
with natural wealth, that was not the point. The Lord was stressing
intellectual humility.

And He said of those who have this quality, "theirs is the kingdom of
heaven." Note the present tense. The word, kingdom, obviously, refers
to the realm of a king, and the king governs by means of laws. So in
the spiritual sense a king represents the truths (or falsities) by
which we live in society. And his kingdom is the whole realm of life
and thought based on those principles. Therefore we possess the
"kingdom of heaven" as we acknowledge our need and willingness to learn
what the Lord teaches us in His Word. It is not a promise, it is a
fact.

The second blessing the Lord mentioned is for those who mourn. Again,
it seems like a contradiction: how can you be sad and happy at the same
time? Because it seems impossible many have supposed that the Lord was
simply talking about delayed gratification: mourn now, be happy later.
Suffer now, get your blessing later. From this perspective it might
seem like we're supposed to be miserable in this world, or that there's
something wrong with us if we enjoy our life in the world. But this is
not what the passage says. Those who mourn are blessed, and, what's
more, "they will be comforted."

Now, mourning is grieving, usually over some loss. It wells up from
deep within and so has more to do with feelings than with thoughts. It,
too, is a state of awareness, a real awareness and acknowledgment of
what we will or want but often can't have. In fact it is the
acknowledgment of our self-will. And since we never have everything we
want for ourselves it is obvious that when we get in touch with these
feelings we are going to be sad.

Psychologists of course are right when they say we have to get in touch
with our feelings. And they are right when they say we shouldn't
suppress or deny these feelings. If we're bitter and resentful the
first step in healing is to admit it, and really acknowledge it, then
we can face it and with the Lord's help do something about it. But if
we have a conscience based on an understanding of the truth we will
realize as part of this process not only that we can't ever have
everything we want but furthermore that this would not be right, or
good for us. And so our grief, our mourning can take on the additional
quality of sadness that we do want what we shouldn't have.

OK, so where is the blessing in this? The blessing is that this
acknowledgment heightens our awareness of the Lord's love and mercy. In
fact without it there can be no awareness of the Lord's love and mercy
and thus by definition no blessing, all of which comes from Him. We
read, "Those who give no thought to the evils in themselves, that is,
who do not examine themselves and afterwards refrain from evils, cannot
but be ignorant of what evil is and then love it from its delight. For
he who does not know evil loves it, and he who neglects to think about
it is continually in it" (DP 101:2). You cannot be blessed when you are
unaware of the evil in your life.

On the other hand, when you are aware of it - and feel grief on account
of it - not only can you begin to appreciate His mercy in that He
continues to love you and care for you in spite of these evils, you
also put yourself in the position of being willing to receive His help.
This is where the promise of comfort comes in. Do you remember the
teaching in John about the Holy Spirit, where the Lord called this "the
Comforter" and promised to send it to them after He Himself had gone
away from them (John 14:16; 16:7)? In the New King James translation
this is called "the Helper," and the same word used as a verb means "to
help." That word is Paraclete or in its verb form paracalleo, meaning
to call alongside. This is the word now used for "comfort" in the
phrase, "they shall be comforted." Literally, they shall be helped. The
Lord will walk by their side.

Briefly stated, then, this is the second of the ten blessings: Happy
are those who acknowledge their evils, for they shall get help! And
they'll get it because they want it, for there is no lack of help
offered by the Lord at any time in our lives; it's just that most of
the time we resist it because we don't think we need it. "Blessed are
those who mourn."

The third blessing that the Lord promised is for the meek. Now meekness
is not necessarily a problem for us, but the truth is that we often
think of the term in a derisive sense representing weakness or even
cowardice, as in the sentence, "He stood by meekly as his friend was
attacked." But if we think that this is what the Lord meant in His
teaching about blessing we could not be much farther from the truth.
First of all the word here translated "meek" really means "gentle" and
suggests a spiritual softness that is to be associated with patience
and kindness, not at all with weakness or tolerance of evil. It is
indeed the weak who tolerate evil, but the truly meek, those who are
truly kind, will not tolerate evil, especially in their own lives, and
so they labour constantly and courageously to act from charity in all
that they do, shunning evils as sins against the Lord and doing what is
right and good because it is right and good.

The teaching that the meek will inherit the earth is, by the way, a
direct quotation from the Old Testament (Psalm 37:11, for example),
where the Hebrew version of the word, meek, means exactly the same
thing with, perhaps, the added notion of humility and willingness to
suffer if necessary rather than inflict suffering on others. Of course
the Lord Himself gave the supreme example of this quality when He
permitted the crucifixion - not because He couldn't prevent it but
because He knew that it was necessary for the process of His
glorification to be completed. So we can follow in His steps, not so
much resisting the evils that are outside of us in others, but
resisting and indeed aggressively fighting against the evils that we
find in ourselves: evils of jealousy, greed, hatred, lust and the love
of domineering, to name just a few examples.

The Lord plainly says that when we do this we are blessed. The blessing
is in the doing. But as with those who mourn there is an additional
promise, "for they shall inherit the earth." Those of us who are
familiar with the study of correspondences know that "the earth" does
not mean the planet in a worldly sense, but our world, the world of our
own experience, the world of our minds. And surely we can all see that
when we exercise the disciplines of genuine charity we do take control
of our spiritual lives, we do inherit the "promised land" of love and
wisdom from the Lord.

Before we go on to the fourth blessing (and we will only review 5
today, leaving the other 5 for the next sermon), let's just notice that
the first three form a beautiful trilogy. The first relates to the
understanding, as we recognize our need to learn and receive the spirit
of truth. The second relates to the will, as we recognize the evils in
our hearts and take advantage of the Lord's help in overcoming them.
The third now relates to the way we behave, in that we act from
charity, not from weakness but with gentleness and kindness toward
others as we fight against the evils of our own lives.

The fourth blessing that the Lord promised was for those who hunger and
thirst for righteousness, for, He said, "they shall be filled." Hunger
relates to food and thirst to drink. Again, they are both cravings and
they relate to an awareness or acknowledgment of need.

Now the food that nourishes our spirits is the goodness of love; the
drink is the knowledge of truth. And if we're hungry and thirsty we are
aware of our need for these essential things. But the teaching
specifically stresses the hunger and thirst for righteousness, which
like meekness has to do with the way we live. A curious thing in the
Scriptures, incidentally, is that the word, righteousness, probably
should be translated "justice." "Righteousness" conveys a heavy sense
of doing what is strictly right, strictly according to the truth, but
that isn't what the Lord meant in His teaching about blessing. Rather
He was referring to those who long for the goodness of life, that is, a
life in which decisions are made on the basis of what is good for
people, not just on the basis of truth, which would be truth separated
from good.

This teaching therefore follows in order after the one about meekness.
For if meekness has to do with the quality of one's own life, the
longing for justice has to do with life in general - not only that we
should be treated well by others, but that others should be treated
well, too. When you look at the evil and the falsity and the hurt in
your community you naturally long for justice. And when you feel the
lack of integrity in your spiritual community your longing goes even
deeper.

But those who hunger and thirst for justice are blessed. Like those who
mourn they are blessed in the recognition of what is good. They are
fortunate to know about it and they are happy to have the longing for
it. True, the lack of it makes them sad, but the blessing isn't in the
lack, it's in the longing. "Blessed are those who hunger and thirst for
justice, for they shall be filled." Sooner or later, one way or
another, their longing will be satisfied. For whether they are given
the truth in this world or not, whether they are shown what is
genuinely good in this world or not, if they long for it they will
receive it as soon as it can be provided - which in many cases happens
after death in the spiritual world. And that is no shame, for the
purpose of life in this world - which is so short - is to prepare for
life in the next - which lasts forever.

To complete our series today we are going to skip the next 3 in the
sermon on the mount and go directly to the 8th, where we read about
those who are persecuted for justice's sake. Though not in order - and
the order is important - this fits the series as one of the apparent
contradictions in the Word: how can anyone be blessed if he is being
persecuted?

The answer, like the answer to the other questions we have raised, lies
in understanding the teaching on a deeper level. Remember, the
persecution is not for just any reason, it is on account of justice,
"for justice's sake." This means the person is being attacked for
taking a stand in favour of justice. It reminds me of the apostle,
John, who described himself at the beginning of the book of Revelation
as "your brother and companion in tribulation," and who said he was "on
the island that is called Pat mos for the Word of God and for the
testimony of Jesus Christ." This does not mean that he went there to
preach. No one was there! He was banished to the island because of his
preaching. He was being persecuted for justice's sake.

Now remember, you can't get to heaven unless you know the truth, or at
the very least love what is good so that you can learn the truth in
time. But those who are in evil and falsity hate the truth, and they
hate what is genuinely good. So when they see or feel it they attack
it. This is especially true of evil spirits who as a result of their
confirmed states have no inhibitions about their evils or their desire
to attack the good. And because they are spirits, in a sense there is
no escaping them. Wherever there is good they will attack and persecute
it, just as they did the Lord Himself.

What does this mean for us? Look at the positive side: if we had no
sense of justice we couldn't be attacked "for justice's sake." But if
we are so attacked and persecuted it is a sign that we have this
quality and that it is working within us. The fact that we are caught
up in temptations does not mean that we are worse than other people, it
means that we have a good, working con science, and in this conscience
we are blessed! We know what is right. We actually have the kingdom of
heaven within us. So again, the kingdom is not promised at some future
time, we read simply, it is theirs. All we have to do is maintain the
effort to hold on to it.

We will review this last teaching and the others about persecution next
month along with the three beautiful blessings about the merciful, the
pure in heart and the peacemakers. For now, and in conclusion, let us
do what we can to remember, integrate and reflect on the fact that all
these blessings relate to internal, spiritual states, and that all of
the ones we have reviewed today relate especially to states of
acknowledgment or self-awareness. "The kingdom of God," Jesus said in
Luke, "does not come with observation; nor will they say, 'See here!'
or 'See there!' For behold, the kingdom of God is within you" (Luke
17:20-21).

Bad things happen. And there are bad things within each of us. But when
we see them and acknowledge them we are taking the first steps toward
genuine happiness and peace, indeed toward the spiritual wealth and
prosperity that is the blessing of heaven. The beatitudes were the very
first systematic teachings of the Lord in His ministry. In a sense they
contain all things that follow. Not only do they tell us what to do
first (in acknowledging our needs), they assure us of the Lord's active
presence in that work so that we can feel His love and wisdom as we do
it. And finally, of course, they promise even more fulfillment in the
future as with the Lord's help we sustain our efforts and discover the
profound reality of inner peace, "the peace of God that surpasses all
understanding" (Phil 4:7), "peace that flows as a river from the
eternal Source alone"
//(hymn 126).

Amen.

Lessons: Matthew 5:1-12; Psalm 37:1-11; @DP 53


