= Ten Blessings By Rev. Michael Gladish in two sermons include::../template-attributes.adoc[]

////
source: https://www.swedenborgstudy.com/sermons/mirror-newchurch.org/TenBlessingsPart1.htm and ...Part2.htm ... concatenated

meta-data from html source:
<meta name="dc.creator" content="bruce">
<meta name="dc.title" content="Microsoft Word - kl_sermon_TenBlessingsPart1.doc">
<meta name="dc.date" content="2004-12-17T21:07:52Z">
<meta name="dc.date.modified" content="2004-12-17T21:07:52Z">
<meta name="generator" content="Microsoft FrontPage 6.0">

////


== Part One
////
 Ten Blessings, Part 1 of 2
  "Blessed are those Who Mourn."

 A sermon by Rev. Michael Gladish
////
....
 "Blessed are the poor in spirit...
 "Blessed are those who mourn...
 "Blessed are the meek...
 "Blessed are those who hunger and thirst for righteousness...
 "Blessed are those who are persecuted for righteousness' sake...
 (Matthew 5:3-6, 10)
....

=== 1
When we think of blessings we do not usually think of sadness, difficulty or want. We usually think of happiness, peace and plenty. Indeed the word, blessing, means happiness and suggests that we have everything we need.

Why, then, does the Lord seem to say the opposite? You know, practically all of human psychology today is dedicated to the principle that we should not be poor in spirit. They say we should be rich in spirit, meaning self-confident, with healthy self-esteem and even self-love. They say we need to know how to be self-assertive, to know what we want and to feel good about "going for it." They say we can't possibly love others or be happy in society unless we feel good about ourselves first - WHICH IN A VERY IMPORTANT WAY IS TRUE (see @DP 53).

But then why does the Lord plainly say that the people who are poor in spirit are blessed - not "will be blessed" but are blessed? Why does He say that the kingdom of heaven is theirs - not "will be theirs," but is theirs? How can we be blessed even while we are "poor in spirit?"

We can ask the same questions of the teaching about those who mourn, those who are meek, those who hunger and thirst for righteousness, and of course, most of all, those who are persecuted for righteousness' sake. Really, how can you be happy when you are being persecuted!

The answer of course rests in the fuller, deeper meaning of the Lord's words. To be poor in spirit does not mean to be self-deprecating or to have no self-esteem. It is simply a state of self-awareness and self acknowledgment: in effect it is a state of knowing how little we know in relation to how much there is to know. This isn't a sad state, it's an exciting state, full of hope and promise, full of the anticipation of learning and growing, and, among other things, never being bored because we know that the Lord always has more and more marvelous things to show and teach us - forever!

The word, spirit, in the Lord's teaching specifically refers to the understanding. It is the same as the word for wind or breath, which of course has to do with "inspiration" [breathing in]. On the spiritual level we are "inspired" when we get a new insight or idea, when we suddenly understand something that has perhaps eluded us in the past. We are then filled with anticipation and delight. But what if we are already "rich in spirit?" What if we think we know all that we need to know in any given area? Will we be open to new ideas? Will we be receptive? This is exactly the situation the Lord referred to when He said, "It is easier for a camel to go through the eye of a needle than for a rich man to enter the kingdom of God." There is nothing wrong with natural wealth, that was not the point. The Lord was stressing intellectual humility.

And He said of those who have this quality, "theirs is the kingdom of heaven." Note the present tense. The word, kingdom, obviously, refers to the realm of a king, and the king governs by means of laws. So in the spiritual sense a king represents the truths (or falsities) by which we live in society. And his kingdom is the whole realm of life and thought based on those principles. Therefore we possess the "kingdom of heaven" as we acknowledge our need and willingness to learn what the Lord teaches us in His Word. It is not a promise, it is a fact.

=== 2
The second blessing the Lord mentioned is for those who mourn. Again, it seems like a contradiction: how can you be sad and happy at the same time? Because it seems impossible many have supposed that the Lord was simply talking about delayed gratification: mourn now, be happy later. Suffer now, get your blessing later. From this perspective it might seem like we're supposed to be miserable in this world, or that there's something wrong with us if we enjoy our life in the world. But this is not what the passage says. Those who mourn are blessed, and, what's more, "they will be comforted."

Now, mourning is grieving, usually over some loss. It wells up from deep within and so has more to do with feelings than with thoughts. It, too, is a state of awareness, a real awareness and acknowledgment of what we will or want but often can't have. In fact it is the acknowledgment of our self-will. And since we never have everything we want for ourselves it is obvious that when we get in touch with these feelings we are going to be sad.

Psychologists of course are right when they say we have to get in touch with our feelings. And they are right when they say we shouldn't suppress or deny these feelings. If we're bitter and resentful the first step in healing is to admit it, and really acknowledge it, then we can face it and with the Lord's help do something about it. But if we have a conscience based on an understanding of the truth we will realize as part of this process not only that we can't ever have everything we want but furthermore that this would not be right, or good for us. And so our grief, our mourning can take on the additional quality of sadness that we do want what we shouldn't have.

OK, so where is the blessing in this? The blessing is that this acknowledgment heightens our awareness of the Lord's love and mercy. In fact without it there can be no awareness of the Lord's love and mercy and thus by definition no blessing, all of which comes from Him. We read, "Those who give no thought to the evils in themselves, that is, who do not examine themselves and afterwards refrain from evils, cannot but be ignorant of what evil is and then love it from its delight. For he who does not know evil loves it, and he who neglects to think about it is continually in it" (DP 101:2). You cannot be blessed when you are unaware of the evil in your life.

On the other hand, when you are aware of it - and feel grief on account of it - not only can you begin to appreciate His mercy in that He continues to love you and care for you in spite of these evils, you also put yourself in the position of being willing to receive His help. This is where the promise of comfort comes in. Do you remember the teaching in John about the Holy Spirit, where the Lord called this "the Comforter" and promised to send it to them after He Himself had gone away from them (John 14:16; 16:7)? In the New King James translation this is called "the Helper," and the same word used as a verb means "to help." That word is Paraclete or in its verb form paracalleo, meaning to call alongside. This is the word now used for "comfort" in the phrase, "they shall be comforted." Literally, they shall be helped. The Lord will walk by their side.

Briefly stated, then, this is the second of the ten blessings: Happy are those who acknowledge their evils, for they shall get help! And they'll get it because they want it, for there is no lack of help offered by the Lord at any time in our lives; it's just that most of the time we resist it because we don't think we need it. "Blessed are those who mourn."

=== 3
The third blessing that the Lord promised is for the meek. Now meekness is not necessarily a problem for us, but the truth is that we often think of the term in a derisive sense representing weakness or even cowardice, as in the sentence, "He stood by meekly as his friend was attacked." But if we think that this is what the Lord meant in His teaching about blessing we could not be much farther from the truth. First of all the word here translated "meek" really means "gentle" and suggests a spiritual softness that is to be associated with patience and kindness, not at all with weakness or tolerance of evil. It is indeed the weak who tolerate evil, but the truly meek, those who are truly kind, will not tolerate evil, especially in their own lives, and so they labour constantly and courageously to act from charity in all that they do, shunning evils as sins against the Lord and doing what is right and good because it is right and good.

The teaching that the meek will inherit the earth is, by the way, a direct quotation from the Old Testament (Psalm 37:11, for example), where the Hebrew version of the word, meek, means exactly the same thing with, perhaps, the added notion of humility and willingness to suffer if necessary rather than inflict suffering on others. Of course the Lord Himself gave the supreme example of this quality when He permitted the crucifixion - not because He couldn't prevent it but because He knew that it was necessary for the process of His glorification to be completed. So we can follow in His steps, not so much resisting the evils that are outside of us in others, but resisting and indeed aggressively fighting against the evils that we find in ourselves: evils of jealousy, greed, hatred, lust and the love of domineering, to name just a few examples.

The Lord plainly says that when we do this we are blessed. The blessing is in the doing. But as with those who mourn there is an additional promise, "for they shall inherit the earth." Those of us who are familiar with the study of correspondences know that "the earth" does not mean the planet in a worldly sense, but our world, the world of our own experience, the world of our minds. And surely we can all see that when we exercise the disciplines of genuine charity we do take control of our spiritual lives, we do inherit the "promised land" of love and wisdom from the Lord.

Before we go on to the fourth blessing (and we will only review 5 today, leaving the other 5 for the next sermon), let's just notice that the first three form a beautiful trilogy. The first relates to the understanding, as we recognize our need to learn and receive the spirit of truth. The second relates to the will, as we recognize the evils in our hearts and take advantage of the Lord's help in overcoming them. The third now relates to the way we behave, in that we act from charity, not from weakness but with gentleness and kindness toward others as we fight against the evils of our own lives.

=== 4
The fourth blessing that the Lord promised was for those who hunger and thirst for righteousness, for, He said, "they shall be filled." Hunger relates to food and thirst to drink. Again, they are both cravings and they relate to an awareness or acknowledgment of need.

Now the food that nourishes our spirits is the goodness of love; the drink is the knowledge of truth. And if we're hungry and thirsty we are aware of our need for these essential things. But the teaching specifically stresses the hunger and thirst for righteousness, which like meekness has to do with the way we live. A curious thing in the Scriptures, incidentally, is that the word, righteousness, probably should be translated "justice." "Righteousness" conveys a heavy sense of doing what is strictly right, strictly according to the truth, but that isn't what the Lord meant in His teaching about blessing. Rather He was referring to those who long for the goodness of life, that is, a life in which decisions are made on the basis of what is good for people, not just on the basis of truth, which would be truth separated from good.

This teaching therefore follows in order after the one about meekness. For if meekness has to do with the quality of one's own life, the longing for justice has to do with life in general - not only that we should be treated well by others, but that others should be treated well, too. When you look at the evil and the falsity and the hurt in your community you naturally long for justice. And when you feel the lack of integrity in your spiritual community your longing goes even deeper.

But those who hunger and thirst for justice are blessed. Like those who mourn they are blessed in the recognition of what is good. They are fortunate to know about it and they are happy to have the longing for it. True, the lack of it makes them sad, but the blessing isn't in the lack, it's in the longing. "Blessed are those who hunger and thirst for justice, for they shall be filled." Sooner or later, one way or another, their longing will be satisfied. For whether they are given the truth in this world or not, whether they are shown what is genuinely good in this world or not, if they long for it they will receive it as soon as it can be provided - which in many cases happens after death in the spiritual world. And that is no shame, for the purpose of life in this world - which is so short - is to prepare for life in the next - which lasts forever.

=== 8!
To complete our series today we are going to skip the next 3 in the sermon on the mount and go directly to the 8th, where we read about those who are persecuted for justice's sake. Though not in order - and the order is important - this fits the series as one of the apparent contradictions in the Word: how can anyone be blessed if he is being persecuted?

The answer, like the answer to the other questions we have raised, lies in understanding the teaching on a deeper level. Remember, the persecution is not for just any reason, it is on account of justice, "for justice's sake." This means the person is being attacked for taking a stand in favour of justice. It reminds me of the apostle, John, who described himself at the beginning of the book of Revelation as "your brother and companion in tribulation," and who said he was "on the island that is called Pat mos for the Word of God and for the testimony of Jesus Christ." This does not mean that he went there to preach. No one was there! He was banished to the island because of his preaching. He was being persecuted for justice's sake.

Now remember, you can't get to heaven unless you know the truth, or at the very least love what is good so that you can learn the truth in time. But those who are in evil and falsity hate the truth, and they hate what is genuinely good. So when they see or feel it they attack it. This is especially true of evil spirits who as a result of their confirmed states have no inhibitions about their evils or their desire to attack the good. And because they are spirits, in a sense there is no escaping them. Wherever there is good they will attack and persecute it, just as they did the Lord Himself.

What does this mean for us? Look at the positive side: if we had no sense of justice we couldn't be attacked "for justice's sake." But if we are so attacked and persecuted it is a sign that we have this quality and that it is working within us. The fact that we are caught up in temptations does not mean that we are worse than other people, it means that we have a good, working con science, and in this conscience we are blessed! We know what is right. We actually have the kingdom of heaven within us. So again, the kingdom is not promised at some future time, we read simply, it is theirs. All we have to do is maintain the effort to hold on to it.

We will review this last teaching and the others about persecution next month along with the three beautiful blessings about the merciful, the pure in heart and the peacemakers. For now, and in conclusion, let us do what we can to remember, integrate and reflect on the fact that all these blessings relate to internal, spiritual states, and that all of the ones we have reviewed today relate especially to states of acknowledgment or self-awareness. "The kingdom of God," Jesus said in Luke, "does not come with observation; nor will they say, 'See here!' or 'See there!' For behold, the kingdom of God is within you" (Luke 17:20-21).

Bad things happen. And there are bad things within each of us. But when we see them and acknowledge them we are taking the first steps toward genuine happiness and peace, indeed toward the spiritual wealth and prosperity that is the blessing of heaven. The beatitudes were the very first systematic teachings of the Lord in His ministry. In a sense they contain all things that follow. Not only do they tell us what to do first (in acknowledging our needs), they assure us of the Lord's active presence in that work so that we can feel His love and wisdom as we do it. And finally, of course, they promise even more fulfillment in the future as with the Lord's help we sustain our efforts and discover the profound reality of inner peace, "the peace of God that surpasses all understanding" (Phil 4:7), "peace that flows as a river from the eternal Source alone" 
//(hymn 126).

Amen.

Lessons: Matthew 5:1-12 @Psalm 37:1-11; @DP 53

== Part Two
////
 Ten Blessings, Part 2 of 2
 "Blessed are the Pure in Heart."

 A sermon by Rev. Michael Gladish
////
....
  "Blessed are the merciful...
  "Blessed are the pure in heart...
  "Blessed are the peacemakers...
  "Blessed are you when they revile and persecute you...
  "Rejoice and be exceedingly glad, for great is your reward in
  heaven..."  (Matthew 5:7-12)
....

Today we continue a review of the ten blessings, or beatitudes, from the gospel of Matthew that we began last month. For those who missed the first part, printed copies are available.

So far we have reviewed 5 of the blessings, the first four and the eighth, all of which present a rather negative appearance in the literal sense and yet inwardly or spiritually speaking help us to understand the Lord's incredible presence with us in our states of innocence and humility. Now we are ready to review the three blessings that appear beautifully positive even in the literal sense, and then continue with the last two, which are again challenging. Remember, we have already spoken about those in general "who are persecuted for righteousness' sake." Today we consider the more personal conclusion, "Blessed are YOU when they revile and persecute YOU... Rejoice... for great is YOUR reward in heaven."

=== 5
When the Lord blessed the merciful and the pure in heart, or rather, when He said that they ARE blessed, as so often happens, He was referring to an Old Testament teaching, in this case one that we see reflected in our lesson from Psalm 18, where David wrote of the Lord,

  "With the merciful You will show Yourself merciful;
  "With a blameless man You will show Yourself blameless;
  "With the pure You will show Yourself pure;
  "And with the devious You will show Yourself shrewd.
  "For You will save the humble people, but will bring down haughty
  looks" (vv 25-27; see also 2 Samuel 22:26-28)

In fact, all of the ten blessings are reiterations of Old Testament teachings. As the Lord said, "Do not think that I came to destroy the Law or the Prophets. I did not come to destroy but to fulfill" (Matt. 5:17). So in this first part of the sermon on the mount - His first recorded formal teaching - He states the laws of order, and in the parts that follow He explains them and gives examples of what they really mean. For instance, what is it to be truly merciful? Jesus said, "You have heard that it was said, 'You shall love your neighbour and hate your enemy.' But I say to you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who spitefully use you and persecute you, that you may be the sons of your Father in heaven..." (Matt. 5:43-45). So He showed that mercy involves an inner disposition of kindness toward all people, no matter how they may be disposed toward us.

Again, "Blessed are the pure in heart:" Jesus said, "You have heard that is was said to those of old, 'You shall not commit adultery.' But I say to you that whoever looks at a woman to lust for her has already committed adultery with her in his heart" (Matt. 5:27-28). So He taught that it is not enough to love and honour the commandments in outward life, it is also necessary to love and honour them in will, desire, and intention.

The word, mercy, in Scripture, means compassion, and involves the feeling of pity for those who are in any sort of misery or need (AC 3063, 5042, 6180, 9219, etc.). In particular it is said to be "love grieving" (AC 5480), since it is a form of love, and love turns to grief on account of those who suffer, whether the suffering is self-inflicted or imposed by others, whether it is natural or spiritual (as in the case of those who are in spiritual temptations).

The Writings say that the whole government of the Lord's Divine Providence is nothing but mercy because it is devoted entirely to lifting people out of their miserable selfish and worldly lives into the joys of heavenly life (see DP 337), and this is work that He must do with every one of us. It follows, then, that if we share His love we will also share His mercy, and make every effort to co-operate with this work - in ourselves and in others. So we will feel His mercy operating in ourselves. We will feel pity, we will feel compassion; we will feel sorry for those in need.

But wait. How can we be blessed in such feelings of sadness? Isn't this just like the question we raised last month about the poor in spirit, those who mourn, those who hunger and thirst, and those who are persecuted? Isn't it painful to be aware of other people's misery and distress? Think of anyone you love - wife, husband, son or daughter, a parent, brother, neighbour, friend: if you see that person hurt or sad, sick or disabled, confused, bitter, angry or abused, of course you are going to feel mercy towards that person. But the Lord said, "Blessed are the merciful...." Where, we may ask, is our blessing in this grief?

Well, first of all, when we reach out to others who are in need, either in heart or in deed, we feel a sense of real use and purpose. We feel a sort of "call" from the Lord that signals His presence within us and even possibly suggests a role for us. It makes us feel important, needed, or at the very least that we have something we could share. Sure, the cynic would say it makes us feel superior, and if we have an arrogant or conceited attitude that might be true. But if we have a humble and sincere attitude it just makes us feel good, and feeling good is feeling blessed.

Then again, remember that the Lord's Providence is nothing but pure mercy towards all of us. It is not His fault if we do not receive it. But if we open our hearts to others, His love flows in, and fills us with a sense of blessing.

Finally, suppose we act on our feelings of mercy. With the Lord's help the people for whom we feel compassion will benefit and receive a blessing. The old man will smile or laugh; the confused or bitter friend will get some new insight and feel better; the sick or disabled will enjoy something she couldn't have done on her own; the abused or miserable person will feel understood. Since love carries with it the joy of making others happy, this too will be a blessing.

Now before we go on, let's just note that in the first four beatitudes everything is focused on our awareness of our own needs. As we acknowledge these needs and pray to the Lord for help He gives us the wisdom and encouragement we need to be fulfilled. So we are blessed. Then we are prepared to receive the next three blessings, which all relate to an attitude that goes beyond ourselves in the strength of what we have from the Lord to share.

=== 6
So it is with mercy. And so it is with the blessing for the pure in heart. We know the heart corresponds to the will or love, but what is purity of heart? Where does love get its quality?

The answer of course is that it gets its quality from truth. To purify something is to wash or cleanse it, or in some cases to refine it so that it does not contain extraneous or contaminating elements. To have a pure heart, therefore, is to be sincere, to love without pretense or hypocrisy, and especially to love what is true, or to put it another way, to let the truth guide us in love.

In order to appreciate the blessing in this we have only to consider what it's like NOT having a pure heart, that is, being conflicted in our motives and intentions, not knowing which way to go or even how we really feel about things. We want to serve the Lord and the neighbour but we also want to please ourselves, and so we vacillate from one attitude or feeling to another and from one course of action to another. Now we're happy and content, an hour later we're upset or angry; one day the world looks rosy, the next day it's a mess. And we can get ourselves into some real messy situations making decisions from good motives one day, not so good another.

But for the person who has a pure heart, that is, a whole heart and singleness of purpose in following the Lord, life is free of stress like that and relatively simple. It's not easy; no one ever said it would be easy, but it's more straightforward. Such a person loves the truth because it is the truth, and so receives the truth more easily than others, and understands it. Therefore the Lord says, "Blessed are the pure in heart, for they shall see God." To "see God" is to understand how He works; it is to "see" His truth.

Now notice that in blessing the merciful the Lord promised happiness to those in real charity or love for others. In blessing the pure in heart He promised understanding to those who love the truth and try sincerely to live according to it. In the third blessing of that series - the seventh blessing overall - He promises happiness to the peacemakers, and peacemakers are those who work to combine their love and wisdom together in the uses of life so that there can be spiritual rest.

The Writings have a great deal to say about peace, as does the Word of the Old and New Testaments. But the essential truth in all the teaching is that peace comes to those who do what the Lord teaches. "'There is no peace, says my God,' 'for the wicked'" (Isa. 57:21). Therefore to "make peace" is to make this effort: to combine the forces of love and wisdom as we receive them from the Lord to do what is right in our external lives.

For the one who really cares about others, who seeks to understand the truth that he may actually help others, the achievement of this goal is a blessing in itself. So the Lord said, "Blessed are the peacemakers." For they enjoy this work and take great delight in any contribution they can make toward establishing the order of heaven on earth. But beyond this they are also called "sons of God" because they are "born again" through life according to His truth, and they feel His closeness the way children feel the closeness of a loving father.

Let's review. So far, from the beginning, and this time in order, we have discussed the blessings for the poor in spirit, those who mourn, those who are meek, those who hunger and thirst for righteousness (or justice), the merciful, the pure in heart, and the peacemakers. The sequence is beautiful - and important! The first four in the series address our attitudes about ourselves, the next three in general our attitudes toward others.

=== 8!

Now we return to the final blessing we discussed last month, the 8th blessing, on those who are persecuted for righteousness' (or justice's) sake. As we noted, the kingdom of heaven is theirs because it rests in the good and truth they have and in the effort they make to live according to it. They are persecuted because evil hates good and fights against it everywhere, but they are saved from any spiritual harm from evil because the Lord is with them, in them, fighting for them to maintain the order of heaven. It is hard to believe at first that we could be blessed in a state of temptation (which is spiritual persecution), but the Writings tell us that the Lord is actually closer to us at such times than at any other times, defending us, protecting us, preserving our freedom.

So in the last two blessings the Lord takes up this all-important point and drives it home in a terrific climax. In a sense the series is already complete - in the abstract: Blessed are those who recognize and acknowledge their needs. Blessed are those who love and care for others. Blessed are those who love the truth and love sincerely to be guided by it. Blessed are those who work to apply that good and truth together in the uses of life. Blessed are those who are persecuted, for they have something precious from the Lord to be attacked. But the Lord is with them, and He will protect them. So what does He say next?

"Blessed are YOU when they revile and persecute YOU, and say all manner of evil against YOU -falsely - for My sake." This is the ninth blessing. Think of it. The most bitter Psalms in the Old Testament are the ones where David complains about the lies and slanders of his enemies against him. We know how difficult it is to be accused and condemned for things we have done wrong; how much more difficult is it to face the lies and deceptions of those who wrongly accuse! And yet this is TYPICAL of the evil spirits who are with us every day. They insinuate their own evil thoughts and intentions into our minds and then turn right around and blame us for them! How wrong! How cruel! And how vital therefore it is for us to know that the Lord is still with us, fighting for us, helping us maintain our equilibrium.

Notice the phrasing in this blessing, by the way: "Blessed are you when they revile and persecute you...." That is the key. They may do it but they cannot do it unless the Lord is with you to provide the balance. Nor would they care otherwise, for it really is the Lord's own good and truth that they attack in you. So the blessing is real; without it we would simply dive headlong into hell. But because we have it, though it may be an unconscious thing, we can grow in our enjoyment of it day by day. We are blessed when the hells attack; the hells attack us when we're blessed.

=== 10

And so we come to the tenth blessing. Some don't even see it as a blessing because the literal word isn't there. But remember, blessing is happiness. The Lord has now described all the qualities that provide for real happiness; He has also urged us to recognize these spiritual qualities in anyone who may suffer outwardly on account of them. Finally, He has addressed each one of us directly, anticipating His words in John as He predicted His own crucifixion: "Peace I leave with you, My peace I give to you; not as the world gives do I give to you. Let not your heart be troubled, neither let it be afraid" (14:27). So you are blessed when they revile and persecute you..." Again, "In the world you will have tribulation, but be of good cheer, I have overcome the world" (16:33).

Now the Lord concludes with a tremendous personal exhortation in the imperative voice: (YOU, don't just be happy,) "Rejoice and be exceedingly glad, for great is your reward in heaven, for so they persecuted the prophets who were before you."

What possible comparison is there between worldly and eternal blessings! How poor and simple and ultimately disappointing are the joys of selfishness compared to the delights of knowing the Lord and doing what He says! And this is heaven: knowing the Lord, seeing how He works, being confident in His providence, feeling His love and acknowledging His presence from day to day as we relate all the things that we experience in this world to His eternal plan. Of course we are not in heaven every day; we are a mixed bag of good and evil as long as we live on this earth. But we can have heaven in us any day that we choose, for it is not "out there" somewhere far away and difficult to get to, it is here, now, in the thoughts and feelings that one famous preacher once called the "be happy attitudes."

Persecution may come, indeed we know it will come, "for so they persecuted the prophets who were before you." Prophets represent prophetic truths, teachings we need to know in order to find our way to heaven. These truths WILL be challenged, as they always have been. But like Elisha, surrounded as he was with horses and chariots of fire (2 Kings 6), as long as we remain confident and true to His Word we are never left alone. The Lord's love and mercy are all around us; His wisdom and the understanding of His Word protect us. He will address the challenge.

So "Rejoice, and be exceedingly glad!" This is what it's all about: eternal values, unchanging principles, the delights of real love, real wisdom and real fulfilling usefulness to others. This is the experience of heaven, and the reward, the blessing of it is great indeed.

Amen.

Lessons: Matthew 5:1-12, Psalm 18:1-17, Arcana Coelestia 8403

