= Visible God
By Erik Sandstrom
include::../template-attributes.adoc[]

// good shape, but would appreciate verification against an original
// see comments herein for particular locations
// also, punctuation is a crap-shoot.
// Nice reading. You can enjoy this ;-}

Published by the Rev. E. Sandstrom, B. TH.

THIS BOOKLET
is intended as an introduction to the study of the doctrine concerning the Lord Jesus Christ, the one God of heaven and earth, as given in the TRUE CHRISTIAN RELIGION chapters I-III. Special attention has been given to those two chapters that treat of the Lord after His advent into the world and of His works after His resurrection.

A first edition of The Visible God was published in December 1961 in 150 stencilled copies. These copies have now been sold and distributed, mainly in England. Having consulted the Pastors Council of Michael Church, London. I have decided to print a second edition.

References used in the booklet to the Theological Writings of Emanuel Swedenborg, with abbreviations, are as follows

TCR True Christian Religion + 
AC Arcana Coelestia + 
DLW Divine Love and Wisdom + 
Life The Doctrine of Life + 
AE Apocalypse Explained + 
AR Apocalypse Revealed + 
HH Heaven and Hell

As I am now about to relinquish my pastorate of Michael Church for other duties in the New Church I would like to dedicate this second edition to all Members and Friends of that Society. I do so with warm affection and lasting gratitude for eight most happy years spent among them.

London, August, 1963. E. SANDSTROM.

<<<

== GOD THE CREATOR

THE opening chapters of the last of the published works of the Writings, "_The True Christian Religion_", set forth our God. This is of order, for as the Lord said, I am the Door (John 10:9). No truth can be understood for what it is, unless the Lord is seen in it. Truths are not isolated one from another. They are all in a universal context. Only man-made speculations are like the grains of sand. The truths of the spirit and of the world are all cemented together, as into a rock; and wise is he who builds his house upon a rock (Matthew 7:24). It is the Divine infilling presence of the Lord that causes all truths to testify with one accord to Him. He is the entrance to the whole body of truth; and He is, by infilling, that body.

The Lord is a Trine. First there is within Him the Infinite Divine Itself. Then there is the Embodiment of this Infinite Divine namely the Human, the ultimate or natural of which He put on in the world. Finally there is the creative and providing power that goes forth from His Divine out of His Human. This is the Trine which is called in the Gospels: Father, Son, and Holy Spirit. It is clear that this Trine is the Divine Soul, the Divine Body, and the Divine Operation.

By means of the Lord's two advents into the world He has made Himself visible as to all the aspects of this Trine. Not that any man can see the Divine Itself, the Lord's Soul, as it is in itself; but he can see it as it shines forth in the Divine Human. He that hath seen Me hath seen the Father (John 14:9).--The time cometh ... that I shall shew you plainly of the Father (John 16:25). Therefore we see not only the Human, but also the Divine in the Human. The two are one in God Man; and it is that oneness that is meant by the Divine Human. The operation that goes forth is the work that this God Man, the Lord God Jesus Christ, does.

// something looks amiss in the following sentence 
In the following study our main attention is on the chapters dealing with the Lord as Redeemer and the Lord that is to say, the Lord as revealed in the world. Yet we cannot properly understand these chapters, if we do not know who it was that came into the world. We must therefore have a concept of the Lord's Divine Itself.

The Infinite as such is beyond man's ken. We can only speak of it in negative terms: not-finite. But we can know about it. First of all we can know that it exists, and that it is very Life. From that Infinite the finite, thus creation, was derived. 
// punctuation problem here?:
It could as Holy Spirit: not be otherwise. God could not have created out of nothing; nor could He have used for His material already existing finite substances, for there were none. He could only create out of substances emitted from Himself. To create is to finite the things going forth from the Infinite.

That Infinite, the Origin of all, is therefore Being itself. God alone exists in Himself, and has no origin. Frequently the Latin word _Esse_ is used to represent this inmost Divine self-existing Life. This is the Lord as He is in Himself.

But His Life itself has a form, a forth-standing. This is what is called His _Existere_. The _Esse_ and _Existere_ of God constitute verimost Reality. The universe and all things in it are an image of it, a mirror of it. That is reality in the created sense. But nothing that is created has the least life from itself, nor could it exist for moment, unless it lived from and was sustained by Infinite Life.

Certain Divine qualities reveal themselves in and by means of creation. They are qualities of infinite love and wisdom. We see love and wisdom in the fact of creation: for only love would be prompted to create; only love would give: and love can give only in a wise way. We also see love and wisdom in the fact of the Word: for the Word reveals the Lord, tells of His will and His end of creation, and thus provides that there may be conjunction. And finally we see love and wisdom in the fact of the angelic heaven: for it is in heaven the supreme gift of God is bestowed upon man - namely eternal happiness. It is a gift of love, provided by means of the laws of wisdom. (See @TCR 43)

The Lord's Divine love and wisdom are together recognized as His Divine Essence. _Esse_ and _Existere_ are terms expressive of Life itself. Essence describes the quality, or nature of Life. Thus Life is seen to be Love and Wisdom. Operating as such, Life manifests its omnipotence, its omniscience, and its omnipresence. It is Love that is omnipotent by means of Wisdom; Love that perceives all things as present in its Wisdom: and Love together with Wisdom that infills all things, and leads and rules all things.

This was ever so. Infinite Love and Wisdom do not change or develop. Perfection cannot advance beyond perfection. Changes belong only to creation - and to the Divine mode of revealing Himself in creation. Change belongs also to that mode, because change belongs to man and revelation is ever accommodated to man. The modes of revelation change. Only he who is revealed changeth not.

Now, the Lord's advents into the world were modes of His revealing Himself. In His first advent He took on Flesh, so that He might show Himself among men, and work among them. And in His second advent He caused all that He accomplished while in the Flesh to be described and explained, in order that the glory wherewith He glorified His Human might shine forth. He ever had infinite glory and power. But it is now that that glory and power have been revealed in fullness.

This leads us on to the chapter on the Lord as Redeemer, which speaks of His coming in the Flesh: and the chapter on Him as Holy Spirit. which tells of His works by means of the Flesh: His works as God-with-us.

<<<

== THE LORD THE REDEEMER

The essential burden of the opening chapters in "_The True Christian Religion_" is the revealing of the Visible God.

The whole work, whose title page declares that it contains The Universal Theology of the New Church is in fact designed for the setting forth of that one supreme doctrine. As worded in (@TCR 108):  *_The principal object of this work is to show that the Divine Trinity is united in the Lord_* -- that is to say, in the Lord Incarnate, the Lord in the Flesh; thus the Lord as standing forth to view in the world. The phrase itself, however, The Visible God, is not introduced until the closing chapter of the work, where we read: This New Church is the crown of all the Churches which have hitherto been on the earth, because it will worship one visible God, in whom is the invisible God, as the soul is in the body (@TCR 787). Every chapter should be read with this doctrine in view, in fact every page of the Writings should be so read: for it is the paramount doctrine, the doctrine that unites all other doctrines into one scope, or under one head, so as to make of all the countless individual doctrines one Universal Theology.

=== The Omnipresence of the Supreme Doctrine

The omnipresence of the doctrine concerning the Visible God in the work, "_The True Christian Religion_", also becomes manifest on a closer examination of the very structure of that work itself. It is, of course, built up according to Divine order. We find first, in the opening three chapters, the doctrine of the Lord itself. Next we have the Word and its summary, the Decalogue, the Word being the medium of conjunction between the Lord and His children. Afterwards there is the response with men, presented in the chapters on Faith and Charity and Good Works. These things, mentioned so far, make as it were a completed series, a whole by itself; for they present God, His mode of conjunction, and the conjunction itself. But then the particulars involved are opened up step by step. The nature of man's response comes first, namely in the chapters dealing with Free Agency, Repentance, and Reformation and Regeneration. This having been explained, there follows a description of how the Lord inflows with His good and truth as and when the mind of man has been prepared for reception; and this is shown in the chapters on Imputation and on the Two Sacraments. These chapters may be said to describe the process itself whereby conjunction between the Visible God and man is effected, and also the conditions for the process to commence. And finally there is the summing up chapter, dealing with the end of that age which has not worshipped the one visible God, and with the crowning age to come which is to be such because it will worship one visible God, in whom is the invisible God, as the soul in the body.

=== The Divine and the Human

We have seen that the opening chapter of "_The True Christian Religion_" deals with the Divine Itself, thus with the Invisible God who is in the Visible God as the soul is in its body. Also with the handiwork issuing forth from this Divine Itself, namely Creation. This initial presentation of the Divine - its _Esse_ and _Existere_ as well as its Essence of Love and Wisdom - is necessary, so that it might be known not only that our God is infinite and eternal in Himself. but also and particularly who it was who assumed the Human and came into the world. Accordingly we find the following opening words in the chapter, The Lord the Redeemer. 

 "In the previous chapter we treated of God the Creator and also of creation: but in this chapter we shall treat of the Lord the Redeemer and also of redemption: and in the following chapter we shall treat of the Holy Spirit and also of the Divine operation. By the Lord the Redeemer we mean Jehovah in the Human; for it will be shown in the following pages that Jehovah Himself descended and assumed the Human in order to effect our redemption" (@TCR 81).

The relationship between the opening chapter and the two that follow after it, is therefore that the first chapter describes the Divine of the Lord's Human - and indeed of necessity in abstract terms - whereas the succeeding chapters present to the reader the Human assumed by that Divine, and the Operation of that Human from the Divine within it. In this manner it is possible for the reader to combine the doctrines and form for himself a true concept of the Divine Human.

That concept is not just a matter of knowledge. Anyone can remember certain teachings, and can also say within himself: "This sounds right, I accept this." But that is not enough. The doctrine must become a living vision before the understanding itself, so that it is possible for the man to think from the doctrine, and also to act from it. No man can work in co-operation with that which he does not understand - unless of course we mean blind co-operation. Knowledge alone belongs to the external man, and it is altogether possible for it to be kept there without the internal being touched. It is the internal man that understands and loves. If therefore the Divine Human is to be God-with-us it must be God with the internal man in us. In his internal, man must see the Lord before himself constantly, even as the angels perpetually see the Sun of heaven before their eyes. If that be so, then the words the Divine Human become infinitely more than just an interesting phrase. They become a summary expression of the faith of the heart itself. And the external knowledges become infilled with the vision of the internal man.

In one of the Memorable Relations adjoined to our chapter an experiment in the spiritual world is recounted. Certain newcomers, called together, were asked if they could say, "Divine Human", and it was found that not one of the clergy present was able to do so, but some of the laymen were able. This being found, some selected passages from the Word were read to them, showing that all the things that belonged to the Divine Itself, or the Father, also belonged to His Human, called the Son. Then we read on:

 "They were requested to bear in mind that, according to these passages, Christ is God of heaven and earth in respect of His Divine and of His Human, and so to utter the words "Divine Human"; but still they could not, and they said that, although from these passages they had in their understanding a certain idea of it, there was no acknowledgment, and therefore they were unable to pronounce the words" (@TCR 111[4]).

It is further told that neither could they speak the name "Jesus", although they were able to say both "Christ" and "God the Father". The reason for this, as given, was that they had prayed to God the Father for the sake of the Son, and not to the Saviour Himself; and Jesus means Saviour (@TCR 111[3]).

All of this is quite revealing, especially if we keep in mind that they were asked to speak from their thought concerning the Human of the Lord (@TCR 111[4]). That thought belonged to their internal man, and it had had no enlightenment. It had understood nothing whatever concerning the true nature of the Lord, and consequently nothing whatever of the Christian Gospel. And let no man think within himself that their inability to understand was due merely to an intellectual shortcoming, or to improper instruction, for in this as in all similar regards these words are true: 

 "Every one that doeth evil hateth the light, lest his deeds should be reproved. But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God" (John 3:20, 21).

Therefore let every man who would live spiritually apply his mind to the doctrine of the Divine Human, the Visible God, seeking to make his thoughts and affections into images of this Divine Human after its likeness, and thus also causing himself to speak and act from that doctrine. Otherwise the interior thought will not be able to speak out the words, "Divine Human", or to declare their meaning. The emphasis on all this is in the following statement:

 "Hereafter no Christian can enter heaven unless he believes on the Lord God the Saviour" (@TCR 107).

By contrast the case of the Rev. John Clowes may be recounted. John Clowes, Church of England Rector of St. Johns, Manchester, was one of the earliest receivers of the Doctrines of the New Church. While continuing in his rectorate for no less than sixty-two years, and never leaving the Church of England, he was a most zealous translator of the Writings and preacher of the new truths. It was about 1773 "_The True Christian Religion_" fell into his hands (only about two years after its publication), and the Rev. Samuel Noble tells of his conversion. The account is preserved in Tafel's Documents Concerning Swedenborg, vol. II. pp. 1167-68, from which we quote:

Mr. Clowes being on a visit to [an intimate friend, the late Richard Houghton, Esq.] was asked by him whether he had seen Swedenborg's Latin work then recently published, entitled Vera Christiana Religio ("_The True Christian Religion_"): and on Mr. Clowes replying in the negative, he exacted a promise from him that he would procure it. On returning home, Mr. Clowes did procure it accordingly; but when he had got it, being much engaged, he felt no desire to peruse it: and it lay many months upon the table in his library without his looking into it. When he was one day about to set out to spend some time at the house of a friend who lived at some distance in the country, in passing out of his study to mount his horse, he threw open the book which had so long lain untouched upon the table; when his eye caught the words Divinum Humanum (Divine Humanity). He merely thought it an odd sort of phrase -- read no further -- and rode off to his friends. He awoke next morning with a most brilliant appearance before his eyes, surpassing the light of the sun: and in the midst of the glory were the words Divinum Humanum. He did not then recollect having ever seen these words before: he thought the whole an illusion -- rubbed his eyes, got up, and made every effort to get rid of it; but in vain. Wherever he went, or whatever he did, all day, the glorious appearance was still before him; though he spoke of it to no one. He retired to rest at night, and fell asleep.

When he awoke the morning following the words "_Divinum Humanum_", encircled by a blaze of light still more glorious than before, immediately hashed upon his sight. He then recollected that those were the words which he had seen in the book on his table at home. He got up, made an apology to his friend, and took an abrupt leave; and in his own words, no lover ever galloped off to see his mistress with half the eagerness that he galloped home to read about Divinum Humanum. He speedily perused the whole book.

And here Noble quotes Mr. Clowes testimony, the first sentence of which is as follows: "The delight produced in my mind by the first perusal of the work entitled Vera Christiana Religio, no language could fully express."

==== Are the Teachings Concerning the Lord Ethereal?

Frequently the various doctrines in the Writings concerning the Lord are regarded as unreal and purely ethereal things. It is believed that these teachings have no immediate relationship to life. We want to know what to do, and what not to do, it is said. The attitude seems to be that the things related of the Lord concern only Himself, as if we would say: Good and well, these things took place in the Lord. He subjugated the hells and glorified His Human; and thereby He re-ordered the heavens; and instituted a new Church on earth. I will be glad to believe that this was so. But that is missing the point. For the point is not just that it happened, but that it happened before men. It could not have taken place at all, unless it took place visibly; that is to say, the entire purpose of redemption would have come to nothing, if the Lord had accomplished the works of redemption purely in secret, only to tell subsequently that He had done them. It is not just that the Lord achieved glory that matters (He had infinite majesty from eternity!) but that we beheld His glory, the glory as of the Only-begotten of the Father, full of grace and truth (John 1:14).

Without this understanding of the Glorifcation there is again but the dead knowledge, the indifferent acceptance. It does not touch the heart. It does not move the spirit of man into regeneration. Or to refer again to the passage concerning the crown of Churches. The New Church will become such a crown, not just because the Lord has made Himself visible, but because the Church worships Him as He thus stands forth to view.

The reason why the whole point is often missed, is the failure to appreciate that the object itself of the Lord's glorification was the restoration of human freedom. That, therefore, is also the essence of redemption. But there can be no freedom unless there is choice, and there is no choice where only one way of life - the way of the Prince of the world - is known. So the Lord came to reveal the way of the Prince of peace. That gave knowledge of the truth to men. That gave them choice. Hence His words: "Ye shall know the truth, and the truth shall make you free." And further: "If the Son therefore shall make you free, ye shall be free indeed" (John 8:32, 36). For this reason the Lord Himself never saw His glorification as an object in itself. He had the salvation of the human race in view, and consequently His conjunction - reciprocal conjunction - with man. That is why we read:

 "In the union of Himself with the Father the Lord had in view the conjunction of Himself with the human race, and He had this at heart because it was His love; for all conjunction is effected by means of love, love being conjunction itself ... [The conjunction of Himself with the human race] was His end, and was His love, which was such that the salvation of the human race, as beheld in the union of Himself with His Father, was to Him the inmost joy" (@AC 2034[2,3]).

=== Redemption and Salvation

Now, redemption was not salvation; but redemption was a prerequisite for salvation. Redemption, as just said, is restoration of freedom. But salvation is the proper use of that freedom, once given. It follows that redemption is as it were a collective act, removing from all men the fetters of spiritual slavery. Redemption is like the exodus from Egypt, but salvation is like the entrance into Canaan. In the meantime there is freedom of choice. It is possible to return in heart into Egypt. Is not this the word that we did tell thee in Egypt, saying, "Let us alone, that we may serve the Egyptians? For it had been better for us to serve the Egyptians, than that we should die in the wilderness" (Exodus 14:12).

There is a similar distinction, in idea, between the Lord as Redeemer and the Lord as the Holy Spirit. To receive the gift of redemption is to know, understand, and acknowledge the Lord in His glorified Human. This gives man choice, in that it makes it possible for him to follow the Lord. But the reception of the operation of the Lord's Spirit is the actual following. It is the actual reception of the regenerating Divine good in the will and the reforming Divine truth in the understanding. Hence redemption is for the individual, a potentiality; but salvation an actuality. Or again, as Redeemer, the Lord prepares the ground for His work as operating Spirit; and as operating Spirit He completes the work. It follows as a corollary that the Lord is the Redeemer of all; and that He ought to be both Redeemer and Saviour of each.

=== The Advent and Order

In order to safeguard all this, the Lord, in "bowing the heavens and coming down" (Psalms 18:9), must come according to His own order (@TCR 89-91). A sudden appearance before the world in the majesty of His Divine would have forfeited the purpose of restoring freedom. The Jews, as is well known, expected Him to come that way; and had He done so they would have accepted Him with joy - but without the least change of heart. In fact they would have had no chance whatever of a change of heart, for the Lord would have appealed to nothing but their proprial desires.

Therefore He came in such a way as to make His very own teaching and His very own acts constitute His claim of being in truth the Son of God. Nothing was to compel belief. Not even His miracles compelled belief, in the absolute sense, for they could be explained away - and were explained away by the leaders of the Jewish Church. They did serve a purpose lower than the truly rational appeal which was to come only in His Second Advent but that lower appeal was not for the purpose of compelling the unwilling, but to prove to those who had willing hearts that His claim of Divinity was founded on the truth. Hence He said:
"Believe Me that I am in the Father, and the Father in Me: or else believe Me for the very works sake" (John 14:11). His works themselves became the ultimate authority of His teaching.

His coming according to His own order involves infinitely more than any man can fathom. It involves, of course, the fullness of that order itself. But the outline of it is revealed, and angels and men may be perfected in their understanding of the particulars to eternity. What we know is that the Lord as Creator had caused His creation to issue forth out of His hands as it were in layer upon layer, one being derived from the other, until the outmost layer - that of matter - was formed. These are the discrete degrees in the terms of the Writings. And we know that He descended through these degrees, taking them on as veilings as He came, and this lest angels or men should be consumed by His presence.
// "We the soul the infinite soul" looks odd.
We know also that with regard to the birth of an ordinary man, We the soul the finite soul, is conveyed by means of a human father, and that the Divine life flows into that soul; but that in this one case that Divine life entered into the virgin without the human medium, enkindling life in the waiting ovum by its immediate presence. and the more effectively so, since there was no imperfect covering to limit the force of life itself descending.

We know further that He caused Himself to grow up like other men. He was an infant as an infant, a boy as a boy, as we read: But with this sole difference, that He passed through those progressive states sooner, more fully, and more perfectly than others (@TCR 89). In this way He not only caused Himself to reach out from His own Human for the Divine truth and the Divine food, thus in His Human altogether as of Himself: but in addition the caused the truth He took to Himself and the good that He made His own to stand forth to men little by little. For as He gained, so He gave. It goes without saying, that He gained more than any man or angel could ever receive from Him; but so great was nevertheless His love, that He constantly wished to give, if only it were possible, all whatsoever that He gained for Himself. The point however is that He never gave before His own Human had taken to itself the things He might give. In this again His glorification and the redemption of the world were one and the same act.

=== The Acts of Glorification and Redemption were the same

Let me illustrate this by one single example, and we take the example from an incidence in His public ministry. "Is it lawful to give tribute unto Caesar, or not?" was the snaring and hypocritical question put before Him in the presence of the people. (Luke 20:26) Now, this was an ultimate expression of temptations injected into His Human by the hells. The sly chief priests and scribes were but the earthly spokesmen of their masters in hell. Thus He fought within Himself against the hells, but simultaneously He fought in the ultimate, before men, so that not only did He conquer in temptation, but also men were able to witness - indeed only in some small measure, but witness nevertheless, His victory. "Shew Me a penny [or the tribute money]" (Matthew 22:19), He demanded. And then His question: "Whose image and superscription hath it?" And when they timidly answered, "Caesar's", knowing full well that the coin was Caesars royal property, He put forward a Divine truth which is to stand for all ages, directing human behaviour: "Render therefore unto Caesar the things which be Caesars, and unto God the things which be Gods" (Luke 20:19-26). -- Who can fail to see that this was not only a Divine victory in temptation, but also at the same time a showing forth of that victory? That not only was the Lord in the process of glorifying His Human, but also that we beheld His glory? His glorification was the redemption.

More in particular, however, the work of redemption consisted of three major acts. By the same token His glorification accomplished three major results. The first was the subjugation of the hells. Why were the hells subjugated as the result of His glorification? Because they lost their power with men, in the measure that the Lord won over followers of His own. Apart from the free-will following after Him, He had all power in heaven, on earth, and in hell already. In His inmost Divine He was ever omnipotent. But He had not come to crush by violence, or to snatch away His disciples by arbitrary acts of power. He desired to reveal, patiently and gently, that His Human itself had Divine power - power, not over human beings deprived of their free will, but over their very freedom. He only desired to govern by consent. And that is how the sword of His own mouth wrought victory for Him; for it was the truth that He taught that constantly made free; and it was those liberated who came of their own choice from the dead to the One living, and who walked from an old age into one that was new.

The second act was the orderly arrangement of the heavens. This also was accomplished by the Lord's glorification, and in the measure in which He could show forth His glory. For whatever happens on earth has immediate repercussions in the spiritual world, and vice versa. The Lord was in the spiritual world too. He taught there, as He taught here. He Himself said: "No man hath ascended up to heaven, but He that came down from heaven, even the Son of Man which is in heaven" (John 3:13). Consequently there was a judgment in the world of spirits, that is to say, a separation of the evil from the good; and this, simply because the truth made it impossible for those who were evil to deceive any longer by feigned acts of piety and the like. That was the judgment: that the good saw the truth, and were able to withdraw from the influence of the evil. Now, out of those liberated a new heaven was formed and at the same time the higher heavens, which had been disturbed in their integrity because of the shaking and splitting foundations, were restored to their peace. In fact, their sun shone with sevenfold splendour then, as it did again for a similar reason at the second advent.

And the third act of redemption was preparation for a new spiritual Church on earth. That Church, of course, at the first advent, was the first Christian Church. It was built on the Word then given, the Word which was at first the Lord Himself in the Flesh, and afterwards the inspired written testimony of His acts and His doctrines. Thus it was then, as ever, formed out of the free-will acceptance of the truth. This is precisely as in the parable of the house on the rock. The Lord said: "Therefore whosoever heareth these sayings of Mine, and doeth them, I will liken him unto a wise man, which built his house upon a rock, and the rain descended, and the floods came, and the winds blew, and beat upon that house: and it fell not; for it was founded upon a rock" (Matthew 7:24, 25).

=== The Lord's Divine Natural

// pretty complex sentence:
There are many more things, but only the chapter itself with its two sections - The Lord the Redeemer, and Redemption, and including all the Memorable Relations appended to illustrate by living experience the doctrinals of the chapter - only that chapter itself can do justice to the subject.

Suffice it, however, to point at one or two more landmarks of doctrine. We are taught that the Lord, by His acts of redemption, became Righteousness; and we may now see that this also involves that the Righteousness which was in Him from conception, and which also became His in His Human, shone forth as a beacon to those who began to worship Him in their hearts. He gained it, and He revealed it. -- Further, that His Righteousness was not won just by the Passion of the Cross, nor that He won it because He died; but that it was made His own by means of constant victories in temptation, of which the Cross was the last. Consequently, He became Righteousness, not by once dying but by rising again and again after every temptation, and finally and in fullness after the Cross, because that was His last and conclusive victory. Also, that as He fought and conquered, so He emptied out all heredity He had derived from the mother, and in its place put on His Divine. This is what is referred to in the teachings concerning the Lord's alternate states of exinanition and glorification (@TCR 104-06); or as the doctrine is frequently given: 

 "the Lord put off the human from the mother, and put on the Human from the Father. (Exinanition means emptying out.) In this we see the wonder of the truth, that not only was the Lord conceived of the Father, but by glorification He became born of the Father as well" (@AC 2628, 2798:2 et al.).

// this merits verification against an original
But above all we would point to the teaching that what the Lord took on by His incarnation was the Divine Natural; and that it was in this that redemption was wrought. This the Lord did not have before the Incarnation (@DLW 233, 234; @TCR 109) for prior to His coming into the world He had acted only through the celestial heaven (@AC 6371-72). It is in the Natural He became the Last, the Omega, and the Ending, as He had ever been the First, the Alpha, and the Beginning. Consequently it is in the Natural Divine He is God with us - God present in the ultimates of order, and speaking to men through their very natural ears, and showing Himself as it were by means of their very natural eyes - for so He appears to us when we read the Gospels; and so He speaks to us when we read any form of Divine Revelation. And this is the interior reason, as it is called, why the Lord while in the world put on the Divine Natural: namely, that from it He might enlighten not only the internal spiritual man, but also the external natural man (@TCR 109). It is thus that He has become the Visible God.

In His first advent He put on and glorified His Human. Men saw, but dimly. In His second advent He revealed in fullness what He had glorified. That new Revelation too, like former Revelations, is couched in earthly language: but it is addressed to the rational mind. It is revelation indeed, for it is a full revealing of the things that previous forms of the Word contained under cover. The whole mind of man is invited to see God: the external mind, in which are the knowledges, and the internal mind, in which is the rational. And if both of these are not enlightened at the same time, the man remains as it were in the shadow of darkness; but if both are so enlightened he is, as it were, in the light of day (@TCR 109).

This is what is new in the New Church. It is new, because what the former Christian Church might have seen at least in a small measure, it failed to see. A Church was established which saw Divine truths, or rather which could see them, in light (@TCR 109). The Christian Church, as it is in itself, is now just beginning. The former Church was Christian in name only, but not in reality and essence. (@TCR 668)
Christianity itself is now first beginning to dawn, and a New Church, which is meant by the New Jerusalem in the Revelation, is now being established by the Lord, in which God the Father, Son, and Holy Spirit are acknowledged as one, because in one Person (@TCR 700).

Glorified, and revealed. With greater cause than before is it now possible to say: We beheld His glory. That is why the Church, suffering itself to become an image of the Visible God after His likeness, comes forth out of His hands as the Crown of Churches.

<<<

== THE HOLY SPIRIT

We have noted that it was as the Visible God that the Lord became Redeemer. All the acts of redemption were done by Him as He stood forth to view; and the three great acts of redemption were the following: The subjugation and re-ordering of the hells; the restoration of order in the heavens and the institution of a new heaven, and the establishment of a new church (at that time the First Christian Church) on earth. Another way of saying that the acts of redemption were done by the Visible God is to point out that these acts were accomplished by means of the setting forth of the Lord's glory. The glory of His Soul was in Him from conception; but by means of His combats and victories in the world He took that glory into His Body also, His Human also; for His Body and His Natural Mind, conceived of the Father and born of the virgin mother, expelled in combat all that was from the mother, and so became by victories born of the Father as well as conceived of Him. Let me give special emphasis to this point by repeating it, but in the words of the Writings themselves: "The Lord's Divine Human was not only conceived, but was also born of Jehovah" (@AC 2628; 2649:2; 2798). And as He glorified His Human, so He revealed it. As He gained, so He gave. It was necessary that His glorification should take place visibly, for else there could have been no active response, no co-operation, on the part of man. Men could not see all His glory. Not even the angels are able to do this: and yet John was inspired to write: "We beheld His glory" (John 1:14). And the glory that men saw was the glory of the truth He taught, and the glory of the infinite good of love shown in His acts. These were the things that made men free: for by these means the order and the way of the Prince of Peace were set at variance with the order and the way of the Prince of the world.

So men could choose. This is what lost hell its power among men, which led to its total subjugation; this is what provided a new basis for influx from heaven through the world of spirits, causing the great judgment there, and the consequent liberation of the good and the formation of a new heaven from them; and this is what gave the impetus to the gathering together of a feeble beginning of a new Church on earth. The words and acts of the Son of Man accomplished these things. The Word incarnate, showing forth both its truth and its good, did them. And as the Lord in the world had commenced His work of redemption and salvation, so He continued it afterwards by means of the Spirit of truth operating in and through the New Testament, which bare record of Him, and in and through the re-opened Old Testament likewise.

=== The Spirit of Truth

The Spirit of truth is the Holy Spirit. It is clear from this connection between the Lord's work while on earth and His work afterwards that His operation as Holy Spirit must be visible also. We did not complete our study of the Visible God in our former chapter. That study must now continue - in fact, it should never be completed, even as the work of the Holy Spirit never is.

The essential point with reference to the Holy Spirit is that it is the Lord's operation by means of the Word, consequently by means of teachings that enter into man through his physical senses. Not that the Holy Spirit is the literal statements themselves of ultimate, written, Divine Revelation, but that it is the Spirit of what is there said. Even so the Lord taught, saying: "The words that I speak unto you are Spirit and are Life" (John 6:63). That is to say: His words have within them the outgoing Divine truth, which in turn carries within it the Divine good which is Life. That Spirit and Life are what express themselves, or speak, in the words of Revelation. They are themselves without language, and are not translatable into other language. Not even the angelic language, in which the Word in heaven is written, can be said to be the Spirit itself and the Life itself that go forth from the Lord and as it were speak through that language too. The Spirit is Divine light, and the Life is the Life within the Light. "The Word was with God, and the Word was God ... In it was Life; and the Life was the Light of men" (John 1:1,4). So when the Lord promised His disciples the Spirit of truth, whom He also called the Holy Spirit and the Comforter, He spoke of the Divine light in which is life - the light proceeding from Him by means of the Sun of heaven, and the heat within that light. The Writings say openly that that light is Divine truth, and that heat Divine good.

This then shows in what manner the Lord remained with His disciples after His resurrection, and in what manner He remains with all men and angels in His kingdom to all eternity. He would continue to speak to His followers, and to work His works among them - no longer by means of the body born of Mary, but by means of the Revelations of His Divine Human which were given, one at His first Advent and the other at His second. He does not require a body born from a virgin in order to speak to men. He did, for a short while, require it, in order that it might be revealed that He is with men in ultimates, and that He is God-Man. Yet even while He spoke in that body, the Divine truth that healed and saved did not consist of the Aramaic words that His Human employed, but of the light itself that was conveyed by means of those words. He chose His words as vehicles of light and life, as all Divine Revelation is ever a vehicle of these things alone. So also the body itself that was born of Mary was not His own Human, nor was it the Son of God. He expelled what was from Mary, and put on the Divine. His Human - as already observed was born of the Father within Him, not of Mary. So therefore, if the words were spoken by lips from Mary, yet they were inspirited and infilled with His Divine life by the outgoing Divine Human that made use of the words.

=== The Lord's Presence with Man

The amazing point that evolves from these observations is that He is with men after His resurrection essentially in the same manner as before His resurrection. Note again that His maternal human was not His presence with men. It was a tool and an agent only; but it was His Divine Human that shone forth by means of it that was His real presence with men - That alone was Immanuel, God-with-us.

For this reason He spoke of His presence with the disciples after His resurrection simply as a continuation of His sojourn with them in the Flesh. The mode was to be different. That is why He refers to His new presence as another Comforter (implying that He had been their Comforter in the Flesh also). Indeed the mode of His presence after the completion of His work in the Flesh was to be superior to that used by Him before that work was fulfilled. Did He not say: "It is expedient for you that I go away; for if I go not away, the Comforter will not come unto you; but if I depart, I will send Him unto you" (John 16:7)? The body from Mary was in the long run a hindrance for His Divine work. It could not but call some attention to His maternal human. Thus obscuring the vision of the Divine Human itself which made use of the maternal human only so that it might have lips to speak with and hands to act through. That is why it was expedient for Him to go away from that maternal human. Or as He taught the same lesson in other words and at another time: "The hour is come that the Son of Man should be glorified. Verily, verily I say unto you, Except a corn of wheat fall into the ground and die, it abideth alone; but if it die, it bringeth forth much fruit" (John 12:23, 24).

But though the mode was different, yet the gift itself - the Divine work itself - was the same. In each case - before, as after the resurrection - the Divine truth and the Divine good were revealed. He did not suffer any of His words or any of His acts to rise up from the maternal human. He spoke and acted only as He conquered, only as the maternal human was overcome and put oft. Everyone knows that He was not fully glorified until the end of His life in the world. But this did not make His acts and words prior to that time any less Divine; for again - as He glorified, so He revealed, or so He spoke and acted. But the vision of the glorified Human was obscured by that which was not as yet glorified. What He did was ever perfect - but the scope of men's vision, men's response, was circumscribed. Only when the grave was seen empty were all limitations broken. Only then was Thomas able to stammer, for himself and the rest, in awe and wonderment: "My Lord and my God" (John 20:28). He - they - had not known this before, not understood. Afterwards they recalled, and understood as it were in retrospect - but at the time their eyes had clung to the son of Mary.

// thus, or this?
Their eyes had clung to the son of Mary ... Yet not only thus. They had seen too that the Spirit of God Himself worked through this great Master from Nazareth. Peter confessed, saying: "Thou hast the words of eternal life" (John 6:68). Both aspects of their experience were true: they saw, and they did not see. They were stirred within their hearts, but confused by the testimony of their senses. Hence the same Peter who in an exalted state made the confession just cited was able later on to take Him aside and rebuke and contradict Him, saying: "Be it far from Thee, Lord; this shall not be unto Thee" (Matthew 16:22) -- as if the Lord did not at all possess the words of eternal life, but was fallible and could be mistaken.

But when He was fully glorified, then He could show Himself immediately in His Divine Human Body, and no longer surrounded by the infirm human body from the mother. Then the disciples saw with the eyes of their spirits alone, and not at the same time with the eyes of their material bodies. Then they saw truly. And then it was that He could be with them - the same Lord as before, but now without any of His former shackles - more fully their Comforter than before, and so like as it were another Comforter. Hence it was then that He breathed on the disciples and said: "Receive ye the Holy Spirit" (John 20:22).

=== The Holy Spirit Proceeds from the Lord's Human

As the disciples had seen His Divine Human before, so - only more fully - were they to see Him operating from that Human as the Holy Spirit. They were not only to see their Lord as a pictorial image in their memory. They were to see Him as they had ever seen Him: at work - see Him going along before them as they followed - see Him teach and cure and bless. This is to see the Holy Spirit the Comforter. The promise was: "He shall abide with you for ever; even the Spirit of truth; whom the world cannot receive, because it seeth Him not, neither knoweth Him; but ye know Him; for He dwelleth within you, and shall be in you. I will not leave you comfortless: I will come to you" (John 14:16-18).

This concept of the Holy Spirit is vastly different; in fact diametrically opposed to that held by the Church that has fallen. There the thought seems to be from space. It is assumed that the invisible Father, sitting somewhere in heaven on His throne and taking counsel with His Son, who by mystifications has likewise been made invisible, sends out an invisible secret messenger from that throne to the soul of man, touching and sanctifying that soul and pronouncing it saved. We can see the folly, the artificiality and lifelessness of such a concept. Yet the ideas of the Old Church linger on. New Church people too tend to think of the Holy Spirit as descending from above, as through space, to light upon the mind of man, working there the works of salvation altogether in secret. New Churchmen know that the Holy Spirit is not another God, but that He, or it, is the operation of the Lord. They know too that the Father and the Son, from whom the Spirit goes forth, are one in the Person of the Lord Jesus Christ. Consequently they have accustomed themselves to thinking of the Divine Trinity as being in the Lord alone, even as His infinite Soul, His Divine Human Embodiment, and the activity in teaching and working from that Human Embodiment. This is good and well. But I suggest we are inclined to thinking from terms; that we are too much dependent on our memory for the right way of speaking and thinking; thus that we know about the Holy Spirit, but that we have perhaps not really seen Him as we should. We ought to see Him: not once and for all, but once and thenceforth in ever greater clarity and power to eternity.

This is, I suggest, the burden of the chapter in "_The True Christian Religion_" which is at present under review. If so, it is of course also the burden of all the teachings in the Writings concerning this most holy subject.

==== The Holy Spirit and Human Co-operation

Let me emphasize again, as before, that the purpose of the Lord revealing Himself visibly is that men may be made free. They have the proprium with its inclinations to evil of all kinds; and they are not able to choose anything else if they do not know anything else. They see the world and its pleasures. They must see the Lord also, and the happiness that is from Him. And if they are free, then are they able to co-operate with the God of their own choosing, the Lord of their hearts who is at the same time the Lord of Life itself. Thus they are able to respond, and to be in the Lord even as He is in them. And it is this free-will response that spells happiness; they have themselves chosen it, and they love it.

In view of this it will surprise no one that all the acts predicated of the Holy Spirit are such as result from the co-operation of the Lord and man; none of them is accomplished by the Lord without man, thus without his consent and active participation. These are the works of the Divine Virtue and Operation signified by the Holy Spirit as enumerated in our Chapter: In general, reformation and regeneration; and following upon these, renewal, vivification, sanctification and justification; and following upon these again, purification from evils and remission of sins; and finally salvation ... [and] with the clergy, in particular, enlightenment and instruction (@TCR 142, 146).

Let us review these works in brief outline. Reformation consists of the inbuilding of truths in the understanding, so that man may think not from the testimony of his senses but from truths which are above the senses, thus interpreting the things of the world in the light of things of heaven.

Regeneration is the creation of a new will within that understanding, and it is formed as man suffers himself to obey the truths he sees in his understanding; for when he bows himself in obedience, then his proprial affections find no outflow; they are as it were suffocated and closed up; and instead the affections of conscience are opened up and released; and it is from these affections flowing down into the reformed understanding that his new will is made. In this wise there is renewal of our understanding according to the words: "Renew a right spirit within me"; also new life to the will, and through it to the whole mind, in fulfilment of the following: "Create in me a clean heart, O God" (Psalms 51:10).

// another difficult sentence to assemble
Sanctification results, because in the degree that those things are accomplished - in that degree the Divine truth with the Divine good within enters the mind and dwells with man, and this is the truth that is called holy (sanctus), and which is therefore said to sanctify. It need not be specially mentioned that this is the presence and dwelling with man of the Holy Spirit.

Justification, or - what is the same - making righteous, is applied to created man, although the Lord alone is Righteousness, and every man and angel of himself is nothing but evil; and this on account of the fact that the will of man, having suffered itself to be created anew, receives into itself an eternal influx of the Divine Righteousness. Man is neither holy nor righteous; but he - that is, his understanding and will - are sanctified by the influx of divine truth, and justified by the flow of Divine good, and by the willing reception of these. We may therefore say that renewal and vivification refer to the process of making the new understanding and the new will; but sanctification and justification to influx into these things in the degree that they have been made new. The first two speak of the Lord labouring with man in the six days of creation: the latter two of His resting with man on the Sabbath day -- resting, that is to say, in the relaxed love of use, full of ardent longing and eager application

//scan/OCR struggled through some of this
The final aspects of the work of the Holy Spirit, purification from evils, remission of sins, and salvation, are there to remind us that purification from evils comes, not before the reception of God (the good of conscience), but after its reception and after this good has been employed (by means of its truths) in combat against their opposite numbers in the state of temptation. The same applies to the removal of falsities by means of truths. It is true, of course, that things good and true from the Lord are not received in such a way as to be confirmed, until after combat, but it is also true that they must exist in the internal man, in the region of conscience, before there can be any battle. By their being condemned is meant that they are received in the external man also: and that of course involves the full reception by the whole man; but they must exist in the internal beforehand. Let no man think that he can be delivered from his evil affections and false concepts by anything else than good affections he himself has known beforehand and by truths he himself has recognized and acknowledged beforehand. Else he could have no part in the battle. He would be swayed in the struggle as a reed in the wind. But now he is called upon to fight as from himself: and he can do this, because the good he knows gives strength to his arm, and his truth gives a sword into his hand. This matter, however, is made more real by the following from the Doctrine of Life:

 "As evil and good are two opposites, precisely as hell and heaven are, or as the devil and the Lord are, it follows that if man shuns an evil as sin, he comes into the good that is opposite to the evil ... [and] that the latter is removed by the former" (@DLife 70, 71).

The ensuing state of remission of sins is the resulting state. Remission is nothing else than the blessed state that descends into the mind after the disturbing and quarrelsome evils there have been removed. The prayer, "Lead us not into temptation, but deliver us from evil", has been said.

This is salvation. It is salvation, because salvation is not just getting away from something evil and dangerous. It is the replacement of evil and danger with what is opposite to these things: with good and its peace. Salvation is the same as regeneration, and regeneration is the same as heaven, and heaven is the same as eternal happiness in the kingdom of uses.

=== The Operation of the Holy Spirit with the Clergy

//this paragraph is too long
Now in addition to these works of the Holy Spirit there are said to be, in particular, enlightenment and instruction with the clergy. Here I would suggest two points; first that every man can have enlightenment, and that everyone, according to his station, is able to instruct others in the truth; but that nevertheless these qualities are bestowed upon the clergy in a particular way; and second, that enlightenment and instruction are given in a purely mystical way, thus never without a man's active search for both enlightenment and ability to instruct. Hence our chapter adds after stating that the first Divine works relate to both clergy and laity, that these things are received by those who are in the Lord, and who have the Lord in them (@TCR 146); and with regard to the things ascribed in particular to the clergy, that there is not only the zeal that is from the Lord, hut also a zeal of apparently the same nature which nevertheless is derived from mere falsities and the worship - perhaps the secret and tacit worship - of nature (ibid). True and humble and active reciprocation is ever involved. Else the result could not be ascribed to the Holy Spirit, for the Divine works that are done totally in secret by the Lord, thus without man's active response, are not said to be works of His Holy Spirit. They are the fruits of His immediate influx through the soul - that is to say, the fruits of exactly the same Divine light and life -  for there is but one Divine - but of that influx coming to man in an invisible and not at the same time visible way. We mention this in passing, for this is not the place to compare this purely secret influx with the influx that is called the Holy Spirit; only let it be said that the former influx bestows upon man his faculties themselves, the faculties of freedom and rationality; even as it also bestows all the secret powers of the body, whereby organs and glands function without our conscious control. The influx that is called the Holy Spirit, however, is not through the soul. But through the angelic heaven upon the mind, as it were from the side - namely from the spiritual environment of that mind; and this as received in the truths lifted up into the mind from the pages of Revelation. Not that the sphere of angels is employed by the Lord to pass on things from them to man, but to pass on things of His own by means of them. The sphere is theirs, but the light and heat of heaven accommodated by their sphere is the Lord's alone. It is this light and heat that is the real influx; and it is the light and heat, or the spirit and the life, of the words of Revelation.

This is how it is possible for man as it were to reach out for the Lord's Holy Spirit; and this is how the clergy receive enlightenment and instruction as of themselves - as is the case with anything that comes from the Holy Spirit.

The reason why the clergy have these things in particular - that is, in a particular way - is because their office itself, or their function itself, employs their minds in a particular way. And as their minds are turned and respond, so they receive. Influx with them, as with all and for ever, is according to reception.

=== The Holy Spirit is the Divine Power

Finally, two points. First that power is attributed to the Lord as the Holy Spirit. This is in keeping with the universal doctrine in the Writings that power belongs to truth from good, or good by means of truth (@AE 205, 209[4], 376[22], et al). This, let us note, is not just an academic truth. It means that even as all Divine truth is from Divine good, so the power of the Divine truth is seen and received by man precisely in so far as he sees and perceives the good that is in the truth. Truth without good does not affect the mind, or warm the mind. It does not influence the man's life. It does not cause him to change his manner of thinking, and still less his pattern of behaviour. Truth without good has no meaning. It is like a picture we do not understand, a person we meet and talk to but do not get to know. But let a man see the good to which the truth would lead, and still more the love in the name of which it speaks, and the man has been won over. He has seen the point! He takes note! For the first time he understands! Now he is affected, influenced, and he will always remember. We never forget what we have once truly understood; words and formulas may be forgotten, but not the idea itself that we once saw. It is thus that the truth comes to a man with power.

This brings to mind the teaching that the Word does not make the Church, but the understanding of it; and the Church is such as is the understanding of the Word with those who are in the Church (@TCR 243). It is not as though this passage simply wanted to say that it is not enough to have the Word on the book shelf, but that it must be read and talked about too. The warning is to those who do read it, quote from it, and talk about it; for they are the ones who may mistake an external knowledge for a real understanding. Truth such as it is itself; is not just a formula.

Truth is both the form in which it comes to view and the contents of that form. And what is contained is good. This means that truth is not understood, unless the good of it is also perceived. Truth and good make one. They can be separated only in idea, but not in reality and in life. Do we not read concerning the Divine Truth itself, the Word, that "in it was life; and the life was the light of men" (John 1:4)? So, then, to understand a truth is to understand the life of it. That is why the Church is such as is the understanding of the Word with those who are in the Church.

Knowledge alone belongs to the external mind, and is stored away only in the external, or ordinary, memory. But the understanding is a faculty of the interior mind (in which, if it is well with man, the true rational is formed); and what engages the understanding is stored away in the interior memory. The exterior memory is illusive and erosive. But the interior memory is one with man's character. Nothing is ever lost from it. His views, beliefs, and affections themselves are preserved there. In fact, his interior memory is his book of life according to which he is judged in the life hereafter. And the dead were judged out of those things which were written in the books, according to their works (Revelation 20:12; see @AC 9841[3]; @HH 463). The Lord's own Book of Life is the Word (because in it all His thoughts and affections, thus His infinite wisdom and mercy, are written). 
//internal 'name' ??
Man is said to have his name written in this Divine Book, if the quality of his mind (which is his internal name) has been derived out of it and formed by it. (See Revelation 13:8, 20:15. @AR 874). Such is the case with him; if he has truly understood the Word, so that he has been affected by it, and so has learned to think, will, and act from it, that is to say, if the Word has come to him with its power - its creative power. "All things were made by the Word, and without it was not any thing made that was made" (John 1:3).

That power of the Word does not belong to its mere letter, therefore not a mere knowledge of the letter. "It is the Spirit that quickeneth; the Flesh profiteth nothing: the words that I speak unto you are Spirit and are Life" (John 6:63). What is that Spirit and Life of the Word except the Holy Spirit? Is not the Spirit of Truth another name for the Holy Spirit? (See John 14:16,17,26). Thus it is that the Holy Spirit is the Lord, the Visible God, the Son of Man, speaking out of His Word with power and great glory (Matthew 24:30) -- speaking, that is to say, to those who understand something of the Spirit of the Word, especially as revealed in His second coming. That is His "coming in the clouds of heaven" (Matthew 24:30); His coming in the dark sayings and proverbs of old. For He promised: "The time cometh, when shall no more speak unto you in proverbs, but I shall shew you plainly of the Father" (John 16:25). Yet then too it is by no means sufficient to remember the lucid words. They too, like anything read or heard, can be stored away in the external memory only. Again it is necessary to be awake to the Spirit and Life of Divine Doctrine: to respond not only to the truth-form of Revelation, but to sense also the affection of Divine good therein. Otherwise the real rational with man is not touched; doctrine is not written in man's book of life: the profound explanations are not truly understood; and the creative power of the Spirit and Life of the words of the Son of Man, speaking in His second coming, is not shed upon the man. Power belongs to truth from good.

=== Of Himself from the Father

The second point relates to the following statement in our chapter: "The Lord operates of Himself from the Father", and not the reverse (@TCR 153[3]).--The reverse would be that God the Father operates the virtues [attributed to the Holy Spirit] of Himself through the Son (see the same number). That such is not the case our passage confirms as follows: "No man hath seen God at any time; the only begotten Son, who is in the bosom of the Father, He hath declared Him" (John 1:18); and in another place: "Ye have not heard the voice of the Father at any time. nor seen His shape" (John 5:37). From these things it therefore follows that God the Father operates in the Son, and into the Son. but not through the Son, but that the Lord operates of Himself from the Father; for He says: "All things of the Father are Mine" (John 16:15); that "the Father hath given all things into the hand of the Son" (John 3:35); and also that "As the Father hath life in Himself, so hath he given to the Son to have life in Himself" (John 5:26); as also "The words that I speak are spirit and life" (John 6:63; @TCR 153).

Apparently the above teaching has mystified many. It means simply that the Holy Spirit, or the Lord's operation, goes forth from Him as visible (thus from the Lord in His Human), and not from Him as Invisible (or the Lord in His Divine called the Father). The Lord is not visible as to His infinite Soul itself. It is with reference to this it is said: "There shall no man see Me, and live" (Exodus 33:20). In other words, the inmost Divine cannot be understood or comprehended by either man or angel. What is finite cannot grasp the infinite. But the Infinite willed to communicate itself to men, wherefore "He bowed the heavens and came down" (Psalms 18:9). He who was the Word itself, the infinite Truth in the Beginning, became Flesh, and it was only thus that we beheld His glory (John 1:14). It is by means of taking on finite coverings that our God becomes visible and comprehensible to us.

Throughout the Writings the name The Lord means nothing but the Lord God as known by means of His advents. It is this that makes the whole doctrine concerning the Lord so powerful. We are not taught concerning One who is not near, but concerning God-with-us: Immanuel. (Cf. @AC 14).

Once this is seen, the passage just quoted becomes not only clear, but full of inexhaustible meaning. It is then recognized that the Holy Spirit can operate with man only when man sees Him, and so agrees to respond and work with Him. Why! is it not said that man himself is to open his door, outside which the Lord, the visible God, stands knocking? (Revelation 3:20). It is seen too that the Holy Spirit is the Lord as it were reasoning with man, and this with infinite compassion and tender love. "Come now, and let us reason together, saith the Lord" (Isaiah 1:18). The truth is gently revealing to him the power of love. There is no pressure, no force; only omnipotent, holy presence. Nor is the man led blindly, or against his will. He is only invited to co-operate in freedom according to enlightened reason.

<<<

== THE AS-OF-ONESELF

The foregoing spells the as-of-oneself. That phrase is unique to the Writings - but it means everything! It means, to wit, that whereas man can do nothing whatever of or from himself, yet he can understand, will, and do all things within the scope of creation, if he knows how to do this from the Lord. "All things are possible to him that believeth" (Mark 9:23). Particularly is it possible for man to reach out for the gift of salvation: for he can examine himself in the light of Revelation - thus as of himself; and he can repent of his ways and of his prejudices: can think from the Word and act from the Word, and so lead a new life; and he can fight the battle of spiritual temptation by wielding the sword of truth against his internal foes, the foes of his own household (Matthew 10:36) all as of himself.

As stated in the Faith of the New Heaven and the New Church man is to acknowledge that the Lord God the Saviour Jesus Christ is the one God, and that there is no other saving faith than faith in Him; that evil must not be done because it is of the devil; and that good is to be done because it is of God; and that these things ought to be done by man as of himself; but that he should believe that they are from the Lord with him and through him (@TCR 3).

That man thus acts from the Lord with him is clear; but that the Lord thereby acts through him must be specially understood. The Lord so acts only in one sense. Reflect on the good act of man! What does it do? What does it accomplish? An act of the hand - a word of the lips.... There is some physical effect, of course. But what of the effect on the other persons spirit? That is, what of the effect that endureth? There a man can accomplish nothing whatever, save in the sense that the Divine Spirit which prompted our act or our word, may also operate in the person who is the object of our act or word. What came from us served as an agent. The Lord allowed man to have a share in the kingdom of uses: His kingdom. Not that He cannot operate upon our fellow without our agency; but that He gives us to have a share for our sake, for it is only thus that our spirit can live in Him. "As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in Me" (John 15:4). It was the Spirit, operating with our fellow, that gave the new understanding, that kindled the warm affection, that gave the blessing. We did not do that. We only passed on the vehicle - the act, the spoken word - in which the Divine could be. As the doctrine has it: The Holy, which is meant by the Holy Spirit, is not transferred from man to man, but from the Lord through man to man (Canons of the New Church, The Holy Spirit IV:5 (@CanonsNC 36[5])).

If we have understood this properly, then we have seen that there is nothing Divine inherent in our act itself. or our word; just as there is nothing Divine inherent in us, or as part of us. The Holy Spirit, that is, the Divine Proceeding, never becomes man's, but it is constantly the Lord's with him (Canons, H. Sp. IV:3 (@CAnonsNC 36[3])). It is only that whatever is done or said from the Lord, has the Lord within it. It is in fact in no other way that He is God-with-us: God-with-the-man.

Keeping in mind, then, that what we do or say never is or becomes Divine, we can understand why it is that the Writings insist that in another sense the Lord does not act through man. Thus it is not as though our act was the Lord's act. What we do is too limited, too pitiful, to compare even the most remotely with the Lord's own acts, namely those of the Holy Spirit.

Thus consider the following: When the Word is present in any degree of fullness in the internal of a man, he then speaks and acts of himself from the Word, and not the Word through him (@TCR 154). This teaching is given to illustrate the point that the Lord acts of Himself from the Father, and not the reverse; and it thus gives a direct link between the doctrine of the Holy Spirit and the doctrine of the as-of-oneself.

Of himself from the Word - that precisely is what the as-of-oneself means. But not the Word through him! That is to say: Man is called upon to draw for himself freely from the storehouse of infinite power latent in all that the Lord has revealed, and is in no way subjected to an overruling influence regardless of his consent. And how this is indeed the Lord Himself and man working together - the Lord operating out of Himself from the Father who is His Soul, and the man responding as if of himself - is still further shown as we read on in the same passage:

 "It is the same with the Lord, because He Himself is the Word; that is, the Divine truth and the Divine good therein. The Lord acts of Himself, or from the Word, in and upon man, but not through him, because a man in freedom acts and speaks from the Lord, when he does so from the Word" (@TCR 154[5]).

All of this establishes, once again, the truth that the Lord operates as the Holy Spirit only in and out of His Word; only as the Spirit and Life which is in all that proceedeth out of His mouth. That is how the Holy Spirit becomes visible. That is how a man may meet and work with his God - the Lord operating in and upon man, giving enlightenment, enkindling affections; and the man speaking and acting of himself from that which has been so awakened by his Lord and his Master. This is speaking and acting, not from, yet as from oneself - in perfect freedom and in agreement with one's reason.

=== The Scope of the As-of-self

We said that all things within the scope of creation are open to the as-of-oneself. But let the Writings themselves clarify this point:

 "It is to be noted that although the Lord works all things, and man nothing from self, yet His will is that man should work as if from self in all that comes to his perception. For without man's co-operation as if from self there can be no reception of good and truth, thus no implantation or regeneration. For to will is the Lord's gift to man; and because the appearance to man is that this is from self, He gives him to will as if from self." (@AE 911[17]).

It will be seen, then, how it is that

 "the New Christian Church is to be the crown of all the Churches that have hitherto been in the world, because it will worship one visible God, in whom is the invisible God as the soul is in the body" (@TCR 787).

The first Christian Church did not do that. It fell away. Instead of preaching obedience to the Commandments, it set up for itself an atonement that was vicarious. Instead of opening up the understanding - and the heart - of all, by showing the mercy of the Lord the Saviour in calling upon man to act in his own freedom and in agreement with his own reason, yet from the truth that makes [man] free and gives light, it gave the dogma of faith as alone saving; faith in the memory, faith from the Hand Book of the Church, incomprehensible faith, blind faith, external persuasive traditional faith, dead faith - a faith destroying the Church, destroying the spirit of man.

Well then may these words again be applied to a Church that has passed away: "Ye made the commandments of God of none effect by your tradition" (Matthew 15:6); and well may these other words again turn to a Church that is new: "Henceforth I call you not servants; for the servant knoweth not what his Lord doeth; but I have called you friends; for all things that I have heard of my Father I have made known unto you" (John 15:15).

At this day He as it were repeats those words, for even as in His first advent He revealed from the Father - from the Divine within Him - all that they could then receive, so He looked to His second advent, saying: "I have yet many things to say unto you, but yet cannot bear them now. The time cometh when I shall shew you plainly of the Father" (John 16:12, 25); which means revealing His Divine in full glory. That is why that saying takes on a renewed meaning by virtue of the giving of the Revelation of the Second Coming - All things that I have heard of my Father I have made known unto you. In His Human He speaks again from His Divine.

=== The Visible God and the As-of-oneself

"I have called you friends." -- His friends know their Lord. They see Him, worship Him, follow Him. He is the Lord God Jesus Christ, standing forth in His glorified Divine Human in the internal sense of the Word now laid open. He speaks out of the Word, which is glorified with Him, and out of the Word He acts in man and upon him. The Old and New Testaments have been made new, because they have been opened. They speak in the language of the Writings. The whole three-fold Word, as we now have it, yields nothing but the Heavenly Doctrine - the Doctrine as known to angels, only clothed for us in a language taken from the earth. It was the Son of man - the Lord as the Word - who was glorified; and it is the Son of Man who reveals His glory. They shall see the Son of Man coming upon the clouds of heaven with power and great glory (Matthew 24:30).

The truths of the Heavenly Doctrine are all truths from good; Divine, eternal truths from Divine, infinite good. The truths act in and upon the understanding. They shine forth - the man being willing - from the Divine statements of Doctrine. And the good within the truths, accommodated by means of a Divine transflux through the heavens, thus through angelic spheres, acts at the same time in and upon the affections of the will. Earthly language, angelic spheres: these are the finite coverings, through which and out of which the Divinely Human One, the Lord of the kingdom and upon the understanding.

In and upon the thoughts of man; in and upon his affections. "My thoughts are not your thoughts, neither are your ways my ways, saith the Lord. For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts higher than your thoughts" (Isaiah 55:8, 9). He calls upon man to produce his own thoughts, to give flow and direction to his own affections and then to do his own acts and speak his own words. But all are to be from the Lord with him. Then the acts of man and his spoken words will bear the testimony of the Lord to the neighbour; and as a man's words and acts awaken thoughts and affections with the neighbour, so the Lord acts in and upon the neighbour. It is in that sense the Lord acts through a man; thus not because the words and acts of man are the Lord's acts and words, but because by virtue of Divine merciful presence they are from the Lord.

It is very clear then, that there could be no as-of-oneself, if the Lord had not made Himself visible. "Ye in Me, My words in you" (John 15:7). Was there, therefore, no such thing as the as-of-oneself before the Lord came into the world? The answer is that the Lord has always been visible in some measure. (That is, capable of being seen). But before His coming in the Flesh He could not have been seen in the natural. Instead there could only be a representation of Him in the natural. Thus He was envisioned but vaguely, obscurely, as behind a curtain; as the Ark of the Covenant was envisioned only by virtue of the protrusion of the carrying staves into the veil that separated the holy of holies from the holy place in the Tabernacle. The point is that men have always been able to form some idea of God. Otherwise they could not have been free. They would have had no as-of-self.

But before His coming into the world they could not see Him rationally. For the rational, though turning heavenward, is seated in the natural mind. In their internal mind they had a general awareness of God; in the external, or natural, mind they learned by experience the laws of nature. But what of the link between the two? What of the true rational, that has its form from the natural and its essence from the spiritual? There was no other link, save a fragile one. In the natural, from the spiritual, there was but the representation, but the effigy, but the remote reminder.

//'hill' can't be correct
Now the veil has been rent in twain (Matthew 27:51). It began when the Lord glorified His natural Human, and the [line-through]#hill# invitation to see was given when He revealed what He had glorified. Hence John in Patmos could testify: "And the temple of God was opened in heaven, and there was seen in His temple the Ark of His Covenant" (Revelation 11:19).

Accordingly we are taught: 

 "The Lord before His coming into the world was indeed present with the men of the Church, but mediately through angels who represented Him, but since His coming He is present with the men of the Church immediately for in the world He put on also the Natural Divine, in which, He is present with men. The glorification of the Lord is the glorification of His Human which He assumed in the world, and the glorified Human of the Lord is the Natural Divine.... Hence the angels know that the Lord alone, in the whole spiritual world, is fully Man.... The Lord Himself, indeed, appeared among the Ancients ... but because He was then only represented, which was done by means of angels, therefore all the things of the Church with them were made representative; but after He came into the world those representations vanished: the interior reason of which was that the Lord, in the world, put on also the Natural Divine, and from this He illustrates not only the internal spiritual man, but also the external natural; which two, unless they are at the same time illustrated, man is as it were in the shade: but while both are at the same time illustrated, he is as it were in the day." (@TCR 109).

"The dayspring from on high hath visited us...." (Luke 1:78). That is how a new day breaks for the New Christian Church, which is to be Christian in essence and reality and not only in name (@TCR 668, 700). To it the Lord speaks, saying: "I am the bright and morning Star" (Revelation 22:16). To it He is visible as the Omega, the End, the Last; and not only remotely as the Alpha, the Beginning, the First. Because He is visible in His Natural Divine Human, therefore He is visible in fullness. He is God-with-us as never before. He is God with the as-of-self of man.

THE END
