= Creation
Doctrinal Essays By Hugo Lj. Odhner
include::../../template-attributes.adoc[]

////
Abbreviations, and Footnotes, could use some cleanup/integration
and there are some 'list' issues
////

Creation from H. Lj. Odhner,

Creation. Doctrinal Essays. 

Bryn Athyn: Academy Publication Committee, 1964

---
~~~

== God and Creation

“In the beginning God created the heavens and the earth.” - Genesis 1:1

"The first thing of the Church is the knowledge that there is a God and that He is to be worshipped. His first quality to be known is that He has created the universe and that the created universe subsists from Him."[1]

The first instruction given in the Divine Word is, "In the beginning God created the heavens and the earth." This is the primary truth about God's quality, because in it everything else is involved. If this truth is sincerely received, all other truths will flow from it. Without it, all spiritual truth perishes. It is the first among the canons of the New Church, the first subject treated of in the True Christian Religion. It is necessary that we should know the Lord as the Creator of the world - of the heavens and of the earth - before we can learn to know Him as Creator of the new world of regenerate life which He is endeavoring to create within us....

As the Creator, the Lord comes to us in the years of tender infancy. The child is surrounded with gifts for which he has not labored. He is faced with the marvels of growth, of production. He finds his little world expanding into ever wider horizons. And there is within him the stirring seed of a rational mind, which asks, `Where did this thing come from? and that? Who made these things?'

Happy is the child who receives the true answer: ‘The Lord made them!' For this truth is immanent in the wonder of the child; this truth is the real, but unperceived source of the question! It prompted the awe in the child's mind. And the answer therefore leaves the mind of the little one at peace, with a sense of fulfillment and assurance. The soul's own prompting has been satisfied.

The truth that God has created all things, is the first fact of spiritual education. It connects all things of sense observation with the idea of the Lord, and thus keeps an avenue of influx open from the Lord into all the knowledges of the mind. It makes worship of Him full of meaning. It fits into the scheme of the infant's life, because to him love is that upon which he depends at all times, and love is the source of all good things, the maker and provider of everything of life. Love is what creates his world around him, and now he learns what the final source of these things is. He has a name for it - God. God created him and - everything! It does not matter how. The fact is enough.

The question ‘How?' comes later. And when it comes, the Word in its literal sense gives a sufficient answer to the child: "God said, Let there be light. And there was light ... And God said, Let the earth bring forth the tender herb ... And it was so ..." The means and the modes are not important. The child strikes through, with the unspoilt logic of its nature, into the essentials, the power of the creative Word, the spoken will of God. And there is, in simplicity, in the child-like heart, something which loves magic, which loves to know that there are powers which exceed any understanding. If we ever, through much learning, lose that sense of the magic of things, we lose the essence of wisdom.

The creation story of Genesis conveys the essential truths about the mode of creation, by the use of symbolic pictures and in phrases of profound significance. Indeed, it conveys all the truth that can ever be known, for it contains the infinite truth in an ultimate form which reflects that truth to us so far as we are prepared to see it, but no further. It does not express these truths except in the barest generals, but it involves them all, as in a whole.

The origin of the Genesis account of the creation of the world in six days, lies in the remotest antiquity. Distorted and incomplete echoes of the same story are found in the mythological lore of many ancient nations. Even up to modern times Jews and Christians have insisted that the account is literally true; and Swedenborg, in his early treatises, also defended it against the scoffing of modern science, by explaining that while creation could not have occurred in so short a time, or in such exact order, yet the sacred text contains a true description of the progressive stages of the creative process as viewed from the earth and as couched in pictorial language, with the understanding that the ‘days' were in actuality epochs of uncertain duration.[1a]

The Arcana Coelestia nonetheless asks us to ponder on the particulars of the Genesis description, and to conclude "that the creation of the universe is not there meant!" Such particulars "may be known from common sense not to have been so," and can hardly be acknowledged to be possible "by any one who thinks interiorly."[2] The Writings do not deny that certain general truths about Creation are found in these early chapters of Genesis - nor do they claim that the idea of stages in the formation of the earth and its kingdoms is erroneous. But it is pointed out that the purpose of the Genesis story is a spiritual one - that it is "a history so framed as to contain within it heavenly and Divine things, and this according to the received manner in the ancient churches," since the custom of writing in symbolic and allegorical style about the things of the church was common amongst the people of antiquity.

Actually, or in a spiritual sense, the six days of creation describe the establishment of the Most Ancient Church. And since the spiritual stages by which this was done involved the states through which man passes in his reformation and regeneration, until the paradise of his mind is fully prepared and populated, these states also are described as a "creation" wrought by God when, out of the chaos and vastness of ignorance and cupidity, He labors to order man's mind.

Yet the child, and those who are in simple ignorance, cannot grasp what the Writings evolve out of the story of the six days; cannot as yet understand what is meant by the various details of spiritual creation. And for such, the Mosaic account is to be held believable and true - as it indeed is in all that matters. It is a holy ultimate for something far more vital than physical science. As the child's comprehension grows, explanations can be inserted which fill in the physical truths. The picture given is elastic, but the solemn words of the sacred text remain fixed in the mind, ready - not to be broken - but, when the time comes, to be seen as full of a truth far more marvelous than had been before imagined.

Thus gently, the two creations are distinguished one from the other, to be studied separately. Yet it will be seen that, although in point of view, and in use, they differ, yet each study casts an enriching light upon the other. Inwardly, the two creations have the same purpose, the same end; and have principles in common, laws which are universal in both. In each there is something which corresponds to something in the other. The same God creates both the universe and the regenerate mind of each human soul.

* * * * *

It is for this reason that the New Church has been given not only a doctrine concerning Regeneration, but a doctrine concerning the Creation of the universe. The child lives in a world of representations - and representative truth is sufficient for him. But when he enters the real and actual world, he needs to know it as it is. He needs to distinguish the natural from the spiritual, and must learn the nature and origin of each. His reason becomes active and he inquires into the relations of things, their connection and order, the modes of their actions, their forms and composition, their functions, their origins, how and why they came to be.

The maturing mind is not satisfied with blind faith. It must see how and why; it clamors for the experiences of seeing for itself. The reflecting youth accepts the facts that there is this great arena of natural and physical things around him, and that there is also an inner world of realities - spiritual things, of which he is also partly conscious, because they enter into his own imagination and thought. It is quite normal that his Reason should wish to survey all the possibilities as to the origins of these two worlds, before he can feel sure of his own place in the universe. And with the penetrating teachings of the Writings as a cicerone, he can fearlessly embark on such a voyage of exploration. They guide him safely through seas of absurdities into calm waters and into the rich harbors of faith.

The first assurance which the Writings give is that creation did occur. "It cannot be thought by anyone that the universe is from eternity, or that it is from nothing; and hence it cannot be denied that it was created, and by Some One ..."[3] "It cannot be thought!" Yet there are those who deny creation; who point to the much amended "law" that matter - or rather mass, or rather the energy of which mass is the measure - is indestructible, and thence conclude that neither could it be created. There are also ancient religions which are founded on the assumption that while God was eternal, Matter also was eternal - both co-existing, as a positive and a negative force, the respective origins of a dualism of good and evil; or, that God was not a Creator, but a Former, a Potter who shaped the co-eternal clay into a universe; or else, that matter existed from eternity as an undistinguished chaos of many mixed elements, which - for some reason -
were then separated and joined with their affinities to form the world, and this either from a latent force of their own, or from the prompting of a Divine Spirit.

But these are ideas - not completed thoughts. They evade the call of Reason which demands a cause for every effect. Imagination is not thought. The refusal to follow out the demands of the rational, and instead stop in the middle of a process of thought, is not thinking.

The Natural sees only from effects. The Rational looks for causes.[4] And because this is instinct in the rational mind, the common sense of men (i.e., the spontaneous intuition of the rational mind) has led men to acknowledge that the world must have its cause in an infinite Source.

Still there are those who stick in the idea that this creative source of all the things of space and time which we discern about us and which compose us, may be Nature; that is to say, that the particular things we know of are merely the changes of form which are assumed by the basic substance of Nature, and that that substance is eternal, or from eternity. But this still involves that a finite substance could be from eternity. It supposes that an infinity of space and an infinity of time can be predicated of Nature or of the finite. For eternity is an infinity, as regards time. Yet - the thought is impossible! For space and time, and even their spiritual equivalent, which is finite state, are the antitheses of infinity. Therefore we read in the Writings: "God from eternity can be thought about, but in no wise Nature from eternity; consequently the creation of the universe by God can be thought about, but in no wise creation from Nature.[5] "The world was created by God, not in time, but times were introduced by God with creation ..."[6] "In the sight of God, there were no spaces or times before creation, but after it."[7]

If our thoughts are to be led by the Writings, we must be willing to accept the conditions which the Writings require. Sensual thinking - from mere appearances and from merely material realities - cannot reach where the Writings would have us follow. "Creation itself," they tell us, "cannot be brought within one's grasp unless space and time are removed from the thought."[8]
"The eye beholds the universe, and the mind ... concludes in the first place that it was created, and then wonders who created it. The mind that thinks from the eye comes to the conclusion that it was created by Nature; but the mind that does not think from the eye concludes that it is from God. The mind that takes a middle course, thinks that it is from a Being of which it has no idea, for it perceives that not anything is from nothing; but such a mind falls into Nature, because about the Infinite it has an idea of space, and concerning eternity it has an idea of time; these are interior-natural [men] ; while those who simply think of Nature as a creatrix, are external-natural. But those who, from religion, simply think of God that He is the Creator of the universe, are external spiritual men; while those who from religion think wisely of God as Creator of the universe, are interior spiritual men ..."[9]

Those think wisely who realize that nothing of nature can be eternal, since space and time - by division into parts - are what take away infinity and eternity. Wise thought is thought which is not only rational, but interiorly rational. Such thought do angels and spirits have.[10]

In an early treatise on "The Infinite as the Final Cause of Creation," Swedenborg demonstrated that by analytical thought a man must necessarily arrive at the conclusion that the finite world owed its existence and thus its origin to the Infinite. But he also admitted that this was as far as the mere logic of the natural mind could carry one. The quality of this Infinite, he pointed out, could not be known without the aid of Revelation. It was not a mere Infinite of space or of matter; but an Infinite which must be grasped by thought purified of space, time, and material concepts. If these be removed from our ideas, the Writings show, the Infinite from which all things are created, can be seen as to its quality, which is the love and wisdom which the Divine revelations ascribe to God: the quality which is meant when God is called God-Man, the Divine Human.

At one extremity of the spiritual world, Swedenborg records, there sometimes appear two statues in monstrous human form - with their great jaws open. Spirits who - from ideas of space and time - think vain and foolish things concerning God from eternity seem to themselves to be devoured by those cavernous mouths. It is the representation of their own fantasies - the recoil of a reason threatened to be drawn into the impossible idea of infinite time![11]

For no idea of God the Creator or of His omnipresence and eternity can be had by any delirium about what God might have been doing before creation. In His sight there is no time, but all things are infinitely present. For Him there is no "before," or "after." We can only come to apprehend the Divine Infinite through the knowledge of His essence, which is Love itself and Wisdom itself. These have no time, are not in space. They are Life in its origin, Being, Reality itself. These terms convey but little to the mind if life is not measured in terms of love and wisdom. Yet in that volume of the Writings which treats especially of Creation, and which is called "Angelic Wisdom concerning the Divine Love and the Divine Wisdom," we are challenged with the following words: "Sum up all things you know and submit them to the intuition of your mind, and in some elevation of spirit search for what is the universal of all things, and you cannot conclude otherwise than that it is Love and Wisdom."[12] But the work goes further, and shows that the Divine love and the Divine wisdom are not a mere term or a something abstracted from a substance of which they are predicated, but that they are Substance itself, and Form itself, the only substance which is in and of itself.

It is God as Substance - infinite and absolute - that is the final Cause of creation, and thus the source of all created things. The Divine love and the Divine substance are identical, and are God-Man.

Now, in this idea of the Creator as God-Man, we find the child's belief, that the Lord made all things, restored. Not the belief that God, as a great Person of magical powers, walked about the universe and, by a command, fashioned one thing after another. But the concept of God-Man as the infinite Love and absolute Substance whence we derive all ideas of the human form; the concept of God-Man as the center and origin of all human things - the infinite prototype in whose limited, finite image and likeness man was to be formed.

The idea of creation would be impossible to us, if the infinite Source were pictured as a blank abstraction devoid of qualities and powers: it would then be like a vacuum - a purely negative concept. But Love alone can create; and Love gives of its own. It creates out of Its own Substance and lends of Its own qualities, although these can be but finitely reflected in Its creations. Therefore the Writings state that the Lord is called the Infinite not only because He is Esse and Existere in itself, but also because in Him are infinite things - or "infinities" - which we may see to be One, but which we can also distinguish. We are warned against speaking of these as "infinitely many" - for this partakes of limitations and parts. But we may not deny to God anything which in finite measure composes the frame of man - whose form is the image of God.[13] Thus the Eye of the Lord is upon them that fear Him; the Finger of God works wonders; His Feet stand in our holy places; His Voice reveals His secrets to the prophets. Each thing with Him is infinite; and all are One in His undivided perfection. "In God-Man infinite things are distinctly one."[14] In His infinite uses He regards only infinite and eternal ends.

God is Love. This is the reason for creation. The essence of love is to love others, not self. There is something called ‘love,' which loves only that which pleases one; as when one feels joy in another, but does not feel the joy of the other as joy in oneself. This is called ‘love,' but it is only self-love, and will eventually turn to hatred unless the other submits.[15] There can be no reciprocation in such love.

The Divine Love is not such. The Divine looks to others outside of itself, desires to be one with them, and to make them happy by the gifts which He bestows.[16] Here there is no desire to rule, but to give. The Infinite cannot give to itself, cannot love itself. Nor does Divine Love rest after creating inanimate nature, which cannot feel its happiness. Not until mankind was created - in the image of God and after His likeness - it is said, on the seventh day of creation, that God "rested" from all His work. All that had preceded was a preparation: the Divine Love is not received except in freedom: which is what makes man an image of God.

Yet there is nothing Divine in man, nothing of the essence of love in itself, or of the Infinite.[17]
God's love must create others whose reciprocal love it can love; others, with whose free finite response it can conjoin itself. It cannot love itself in others.

Here, then, we see the reason of creation, and also the reason why nothing created can be Divine.[18]

But how can this be? How can the Infinite, out of its own Substance, form the finite such that it has nothing of the Divine in itself?

For note, that the finite has, in its esse or being, "nothing of God which is God." "That which is created in God from God is not continuous from Him."[19] It is still in the Divine, and the Divine is in it, since the Divine, being infinite, has no limits, and cannot be limited or excluded by the finite which it has produced. And the Divine is - even after creation - the only Substance in se. But there is a distinct break, a discrete step, between Infinite Substance and created things. Is it possible for man to conceive of this process? Is it allowable to reflect how it might have occurred?

Certainly we are not forbidden to try. Yet the responsibility is ours if we do so without removing from our minds those ideas of space and of time, of person and of matter, which lead the thought to a continuum of matter instead of to the Infinite of Divine Love.

* * * * *

The baffling problem of conceiving of the first creation, or "finition," by which God emitted of His substance to form the primitives of the universe, and at the same time avoiding the concept that what was thus produced from the Divine was Divine still, is called, in the Writings, a "Gordian knot.[20] Yet it is not such a knot except from the introduction of natural ideas from space and time; which leads to the idea of a Divine matter shaped into finite corpuscles in such a way that the mind is inclined to say that the created thing also is Divine. This is Pantheism. It is the endeavor to derive spatial substances directly from God's infinite substance, that is confusing. The angels use spiritual thought about creation; and by spiritual ideas it is clearly seen that what comes from God by creation or is produced by Him has nothing of the Divine in it, and is in no wise infinite. They see this - not by having any pictorial idea of the process of first finition - but from the necessities of the case. They see that thus alone could the Divine Love give of its own to others outside of itself.

In his philosophical treatise on "The Infinite," Swedenborg addressed himself to this problem of first finitions. In his Principia, to which this work was an adjunct, he had suggested that all nature, all material things, were but compositions and derivations of a type of primitive "simples" or first entities, which he described as vortex-like motions, or infinitesimal dynamic points; focal points of a conatus or endeavor by which the Creator can form the beginnings of nature. Except for these, there was nothing substantial in the entirety of nature. After assuming such primal entities, one could, he said, proceed by analogy and rational analysis, to account for all other substances, investigate their forms, and speculate on their motion and modes. But - he now writes - "All modes, and analogues of modes (and of such it is that analysis is formed), begin in the simple or primitive of nature, and not in the Infinite, in and from Whom nothing can be said to exist, or issue, immediately, by any mode which is intelligible to us in any geometrical, analogical, rational, or philosophical sense whatsoever."[21]

If this means anything, it means that the mode by which the first entity of geometrical and mechanical nature was formed out of its eventual source in the Infinite, is not to be explained by either geometry or natural rational arguments, or any kind of mechanical concepts.

When writing this, Swedenborg had not yet been introduced into the knowledge of the mediating world of causes which is the source of the creative "conatus." But a growing spiritual understanding of the media by which the Lord formed the first entity of nature, came to him as he was led by the Lord, through enlightenment from the Word and finally by his introduction into the spiritual world, to see that everything in the natural world has its cause in the spiritual. He then confessed that he had long meditated about creation, but in vain; but that after being admitted into the spiritual world he "perceived that it would be vain to conclude anything about the creation of the universe, unless it were first known that there are two worlds ..."[22] Certain general teachings are indeed prefatory: "In every thing created, the greatest as well as the least, there are three [things], end, cause, and effect ... In what is greatest, that is, in the universe, these three exist in the following order: in the Sun which is the first proceeding of Divine love and Divine wisdom, is the end of all things; in the spiritual world are the causes of all things; in the natural world are the effects of all things."[23] "Jehovah God, through the Sun in the midst of which He is, created the spiritual world; and through this, mediately, He created the natural world ."[24] "The origin and maintenance of spiritual things is from a Sun which is pure love ... but the origin and maintenance of natural things is from a sun which is pure fire. That the latter is from the former, and both from God, follows of itself, as the posterior follows from the prior, and the prior from the First."[25] "All things that exist in the world of nature, atmospheric, aqueous, or earthy, as to every particle thereof, are effects produced by the spiritual as a cause ..."26 "The natural draws its origin from the spiritual, and in its existence is nothing other than congeries congregated out of spiritual things."[27]

This conception of an intermediation by the spiritual world in the process of the creation of nature by God, does not (of itself) take away the problem of how to conceive of the first finition by which "God first finited His Infinity through substances emitted from Himself, from which stood forth His nearest compass, which makes the Sun of the spiritual world."[28] Neither does it explain how this spiritual world, by a process of further finition, gave origin to the substances of nature, which are of time and space, and thus in essence totally different. But it does show the order of creation, the complex character of the process. It demonstrates the true nature of the world, as a clothing of the substantial realities of the spiritual that wells forth from the bosom of the Divine Love.

* * * * *

The chapter on Creation in the True Christian Religion therefore lists some prerequisite knowledges:

"No one can obtain for himself a just idea concerning the creation of the universe, unless some universal knowledges, previously acquired, put the understanding into a state of perception; which knowledges are the following:

I. That there are two worlds, the spiritual world in which angels and spirits are, and the natural world, in which men are.

II. That in each world there is a sun, and that the Sun of the spiritual world is pure love from Jehovah God who is in the midst of it; and that from that Sun proceed heat and light; and that the heat thence proceeding is in its essence love, and that the light thence proceeding in its essence is wisdom, and that those two affect the will and understanding of man, the heat his will, and the light his understanding; but that the sun of the natural world is pure fire, and that therefore the heat thence is dead, as in like manner the light; and that they serve for clothing and support for spiritual heat and light, that they may pass to man.

III. Then, that those two things which proceed from the Sun of the spiritual world, and thence all the things that exist there by means of them, are substantial, and are called spiritual; and that the two similar things which proceed from the sun of the natural world, and thence all the things which exist here by means of them, are material, and are called natural.

IV. That in each world there are three degrees, which are called degrees of altitude, and thence three regions, according to which the three angelic heavens are arranged, and according to which human minds are arranged, which thus correspond to the three angelic heavens; and that other things are arranged in like manner, both here and there.

V. That there is a correspondence between those things which are in the spiritual world and those things which are in the natural world.

VI. That there is an order into which all and everything in both worlds was created.

VII. That an idea concerning these things ought first of all to be obtained; and unless this be done, the human mind, from mere ignorance concerning them, may easily fall into the idea of the creation of the universe by nature, and say only from the authority of the church, that nature was created by God; but because it knows not how, if it inquires into it more interiorly, it falls headlong into naturalism, which denies God."[29]



---
~~~

== The Spiritual Sun

“By the Word of the Lord were the heavens made, and all the host of them by the breath of His mouth. - Psalm 33:6

In our introductory essay the central teaching was brought out that God created the universe out of His own substance which is Love itself. It was however shown that the process of formation by which matter arose out of its eventual source in the Infinite was not a process which could be perceived by any mechanical modes, nor by any spatial ideas of geometry or by any material rational concepts; but was a complex process, involving the intermediation of spiritual causes, which can be understood only when the spiritual light of Divine Revelation is shed into our thoughts. It was then shown from the Writings that all things of the natural world are only effects produced by the Spiritual as a cause. The spiritual world is thus to be regarded as a world of causes, and spiritual substance as prior to natural substance.

The creation of the universe consequently involves a spiritual creation as well as a natural one; and in the Writings accounts are given of such a spiritual creation. One of these accounts leads up to this statement

"All these things are from a spiritual, and none from a natural origin. A spiritual origin is life from the Lord. To correspond to these [spiritual] things are created all the things which appear in the natural world, where similar things therefore exist, with the difference that these, [although] they are likewise from a spiritual origin, are simultaneously from a natural origin. A natural origin is added, that they may be at the same time material, and thence fixed, to the end that the human race may be procreated, which could not occur except in ultimates where there is fullness; and so that there might - from the human race as a seminary - exist inhabitants of the spiritual world, who are the angels: this is the first and last end of creation.

"But a complete idea of creation, or of the existence of all things in their order from Life which is the Lord, cannot be given, on account of arcane (secret) things, which are known in heaven and which indeed [have been] communicated to me; but because they are full of such things as are deeply hidden (recondite) in the sciences, they cannot be described except by volumes, and scarcely then so as to be understood."[30]

The suggestion is here conveyed to us that there are angelic truths about creation which in the present state of man's knowledge can scarcely be intelligibly revealed. Nevertheless, the following sentences are appended as the sum and substance of these matters

"The Sun of heaven, in which is the Lord, is the common center of the universe; all things of the universe are peripheries, and peripheries even to the ultimate. These He rules from Himself alone, as one continuous thing, but the mediates from the ultimates. He also perpetually animates and activates these things, as easily as a man, from understanding and will, animates and activates his own body. Influx takes place into uses and from these into their forms."[31]

This statement is amplified in the paragraphs which conclude the manuscript, and stand under the title "The Angelic Idea concerning the Creation of the Universe by the Lord"

"... God is the center, and He is Man. Unless God be Man, creation would not have been possible. The Lord from eternity is that God ... The Lord from eternity, or God, created the universe and all things therein through His Divine proceeding; and because the Divine proceeding is also Life itself, all things are created from Life and through Life: and the proximate Divine proceeding is what before the angels appears as a Sun. This Sun appears before their eyes as fiery and flaming, ... because the Divine, proceeding, is the Divine love and the Divine wisdom, the appearance of which is such from afar ..."

The angels, whose idea Swedenborg here records, also said that "from that Sun as a great center, there proceed circles, one after another and one from the other even to the last, where there is an end of them (ubi finis illorum) and they subsist at rest; and that these circles - of which one is from another and one after the other, appearing as extended far and wide - are spiritual atmospheres, which are full of the heat and light from their Sun, and through which [this Sun] propagates itself even to the ultimate circle; and that in the ultimate, by means of those atmospheres and afterwards by means of natural atmospheres which are from the sun of the world, there takes place the creation of the earth and of all things on it which are of use; which creation is afterwards continued through generations from seeds, in wombs or in eggs... ."

Such is the general idea which the angels have about creation; an idea which contains some of those arcana which they disclosed to Swedenborg. And since it is the spiritual Sun which is here spoken of as the source and center of creation, it is to the teachings about that Sun that we shall next turn.

* * * * *

The spiritual Sun is presented in the Writings under two aspects. On the one hand we are taught that the Lord is the Sun of heaven, to which all the angels turn as to the source of their life, and this whether they see this Sun as a blazing orb, or in relatively less brilliant aspect, as a moon, or simply as light.

Yet all the angels know that the Lord is not a Sun; even though His Divine effulgence so appears, as if localized in their sky. They do not need the warning of the Writings, "Let everyone beware lest he think that the Sun of the spiritual world is God Himself. God Himself is Man."[32]
They worship Him as the Divine Human, and see Him as such when He manifests Himself to them. They know indeed that "as to His Person, the Lord is constantly encompassed with the

Sun."[33] But their ideas are not of space. However they turn their bodies, the Lord is ever present before them. They know that the spiritual Sun is omnipresent in all creation.

But the angels are also aware of the second aspect under which the Sun of heaven is spoken of in the Writings, namely, as a substance which is not God, but is the first substance of creation, nay, the one substance out of which all created things, spiritual as well as natural, are inmostly composed.

The spiritual Sun is therefore said to be "the first of creation."[34] "God," we read, "first finited His infinity by means of substances emitted from Himself, from which there came into existence His proximate compass, which makes the Sun of the spiritual world." "All posterior things" - i.e., all things of later creation - "are receptacles of prior things, and ... so in order of the primitives of which the Sun of the angelic heaven consists ..."[35]

There is therefore a universal substance which is directly derived from the Divine substance, or from the Infinite. It is presumption to attempt to define its qualities, unless we adhere closely to the very words of our Revelation. Yet these words are meant to be understood. The qualities of the first created substance are so elusively perfect that the spiritual Sun is sometimes not distinguished in thought from the Divine which acts through it.

Thus it is written: "That Sun is not the Lord, but is a proceeding from His Divine love and Divine wisdom. It is called a proceeding because that Sun is produced out of Divine love and Divine wisdom which are in themselves substance and form, and the Divine proceeds through it.'"

When angels think of their Sun they think of the heat and light which proceed through it, not of the finite substance which composes it. And this heat and this light are the Divine accommodated to reception and perception; or, what is the same, they are the Divine proceeding. We can have no idea whatsoever of the Divine in its proceeding, unless we hold in our thought the idea of something not Divine, something finite, into which the Divine proceeds
!37 Not that the finite "proceeds" from the Lord, but that the Lord's infinite life proceeds into and through the finite!

How, then, did the finite arise, if it did not "proceed" from the original Infinite? The question is important. The answer is fundamental to our religion, and determines our whole attitude to God.

For the Writings show that what "proceeds" from God is God. If the universe proceeds from God, the universe would be God! The love and wisdom of God which inflow into creation, are God, are the Lord present with men. The Word, or the Divine truth proceeding by revelation, is the Lord Himself with men. In other words, the Divine Proceeding is the Lord present with His creation. And nothing can be said to be Divine with men except what is of the Divine proceeding.

The word ‘proceed,' however, simply means ‘come forth'; and. thus the Writings when at times they speak in the language of appearances, say of finite things, that they proceed from the Lord. But strictly, ‘proceed' means to go forth while remaining the same. Hence a definite doctrine is laid down: "The finite cannot proceed from the infinite to say that it can ... is a contradiction: yet the finite can be produced by the infinite; but this is not ‘proceeding' but ‘creating.'[38] This is a universal law in the light of which everything else said in the Writings must be viewed, if we are to understand it. It is the philosophical truth, involved in the first commandment: 'Thou shalt have no other gods...' Nothing finite is Divine, or God. Nor is there anything infinite except the Lord.

The finite arose by being produced or created. And the only cause of this ‘production' was the Divine. But the Divine must proceed in order to create!

In order that we may understand this, we are allowed to distinguish between the Divine as Love and the Divine as Truth. Truth is the same as the law or the mode by which Love operates and the form by which it expresses itself. Love creates by means of truth, by proceeding as truth, or law. The Divine order or wisdom which is the essential law maintaining the universe, is therefore the Divine Logos - the Word which "was in the beginning with God, and which was God, and which made all things" (John i.1). And when the Psalmist says, "By the Word of the Lord were the heavens made: and all the host of them by the breath of His mouth," the meaning is the same as when the Writings state: "The Divine truth, proceeding from the Divine good, is the very Reality and the very essential itself in the universe; which makes and creates ..."[39] It is "the unique substantial, the derivations being nothing else but the successive forms thence resulting!" (AC 7004). From the truth proceeding from the Divine "are all the essences of things in both worlds, the spiritual and the natural";[40] it may even be said that the Divine truth proceeding "was afterwards formed successively into spheres" or descending atmospheres.[41]

The Divine truth standing forth and proceeding, is thus called, in the Apocalypse, "The Amen, the faithful and true witness, the beginning of the creation of God" (iii. 14). It is the beginning, i.e., the principle or law of creating. It gives substantiality to finite things. But it is not itself finite.

"God ... finited all things by means of (per) His Sun, in the midst of which He is, which consists out of (ex) the Divine Essence that goes forth from Him as a sphere. There and thence is the first of finition ..."[42]

The spiritual Sun is, then, the very focus of creation, the first finiting of infinity. Yet the Infinite is deprived of nothing, loses nothing in the process, does not - except in appearance - impose limits upon itself. The human mind is itself too limited to understand this. We are warned to think not naturally but spiritually - in spiritual terms of life, love, wisdom - about the matter. Yet illustrations are given, as parallels which enable us to think in correspondent ideas about creation.

The things which constitute the Sun of heaven "are from the Lord, but are not the Lord ... They are not life in itself, but are deprived of life in itself."[43] They go forth as "a sphere" from the Lord: but the comparison here is with the spheres of angels and men. For from every man and angel go forth substances set free and separated from their bodies, even as all natural objects also have their exhalations - as waves of effluvia. Thus it is said of every angel, that from everything of his spiritual body there go forth such spheres which closely environ him and are moved continually in rhythm with the motions of his heart and his lungs: and that these spheres convey these activities to the atmosphere and proclaim and convey his quality; for this is a spiritual sphere, not a material one.[44] In the angel, these substances were forms of his life; but when they become spheres, they are devoid of his life, yet are concordant with it.[45] This suggests that the angel no longer controls the action of such spheres, and that they are now subject to changes from other influences. This comparison is called an arcanum which men cannot express by merely natural ideas. For men inevitably think of space in connection with the life of the angels. The spheres of the angels, however, are non-material,[46] and thus are only apparently "in space." The things which constitute the spiritual Sun are said to be "devoid of life in itself." Only the Infinite has life in itself. But this does not mean that the things of this Sun are dead, like the things of nature. Instead we learn that "all that comes forth from the spiritual Sun is living and spiritual."[47] They are living, but their life is not in se, not their own; but comes from the Lord.

Throughout the Writings there is contrast between the living Sun and the dead sun. The natural sun is said to be "pure fire," "entirely dead," yea, "death itself." It is "material," has "nothing whatever of life in it."[48] Its essence is "elementary fire," its activity is mere "dead" motion -
motion in space and time. Its forces are "dead forces."[49] The same is true of all the things of nature which spring from it. But the spiritual Sun is "alive." And since this cannot mean that its substances are infinite, it must mean that they are - not forms of motion - but forms of life, finite receptacles of life. This is true of all spiritual things, all things of the entire spiritual world; for all receive their essence from the Sun of heaven. "The angelic idea ... is that the Divine life is inwardly in the fire of the Sun of the spiritual world, but outwardly in the fire of the sun of the natural world. "[50]

Whether our comprehension of this quality of the "living Sun" be clear or vague, depends less on close definitions than on the reality we ascribe to spiritual things, as they are in themselves. This reality, we conceive, has nothing to do with spatial existence. For as the Divine is not in space, and is the same in greatests and leasts, so "this is true also of that Sun which is ... the one only substance of creation."[51] It is because "this only substance ... is not in space, that it is all in all, and is in the greatest and least things of the created universe."[52]

The substances of the spiritual Sun are not in space. Its presence "is not in the extense of space and time."[53] And the same is said of the whole spiritual world: "Because spaces and times cannot be predicated of love and wisdom, but states instead ... [therefore] the expanse around the Sun of the angelic heaven is not an extense, but still is in the extense of the natural sun, and is with living creatures there according to reception; and the reception is according to forms and states."[54] "The extension of space is not predicable of spiritual things, which are derivations of the spiritual Sun."[55]

Thus the "things" or "primitives," of which the Sun of heaven consists, are presented in a unique light. They cannot be described by any natural terms - unless by a distant comparison. They are spiritual things; and we cannot think of spiritual things in terms of space. They do not belong to a universe of mechanics. They belong rather to a world of incipient endeavors, living potentialities such as the mind of man is made of : a world of substantial spiritual force which is the seed and beginning of every possible variety.[56]

The thought of space moves men easily to think of the world as made up of simple elements, which, like building-blocks, are all alike; and from the differing combinations of which the various forms and patterns of nature would arise. But certain teachings in the Writings discourage this idea:

"Many admit that there is an only substance which is the first substance and source of all things; but ... they believe it to be so simple that nothing is simpler; so that it may be compared to a point with no dimension; and that from an infinite number of such the forms of dimension came into existence.[57] This, however, is a fallacy originating in the idea of space; for the idea of space makes the least to appear such. But the truth is that the simpler and purer a thing is, the more and fuller it is. It is for this reason that the more deeply an object is examined, the more wonderful, perfect, and beautiful are the things seen in it; and thus, that the most wonderful, perfect, and beautiful of all are in the first substance. This is true, because the first substance is from the spiritual Sun, ... and as this substance is not in space, it is the all in all, and is in the greatest and the least things of the created universe. Since that Sun is the first and only substance from which all things are, it follows that infinitely more things are in that substance than can appear in the substances that spring from it, which are called substantiate and, at length, material ..."[58]

* * * * *

It is interesting to note, that even in his scientific period, Swedenborg went counter to current ideas, in that he derived the ultimate things of the world not from more and more simple constituents, but from elements more and more complex and perfect. He indeed describes the first substances as "simples," even "the pure simples"; but in idea they were far from simple. Even in the Principica, he speaks of the first elements as having the form of a tremendously complex gyre. And in later developing his so-called "Doctrine of Forms," he shows that the origin of all forms was the Infinite Form; and this begot the Spiritual Form, and this in turn was the origin of the first natural form, which was described as a sort of perpetual vortex of perfect adaptability and perfection, containing in it the power and potentiality to form the lower and more imperfect and limited natural forms - the vortical, the spiral, the spherical, and, lastly, the inert angular form. (Fibre, 261-273) Afterwards, when Swedenborg had been introduced into communion with angels and spirits, he was led by the Lord Himself into the perception of forms

"entirely transcending all geometrical forms," yea, "forms almost entirely void of limits," but which nonetheless were still "within nature," and were thus "without life." And he commented:
"Consequently as long as the mind detains itself or is detained in such forms, it still is without life; but the things that are within or above them, are living from the Lord, but still organic
(because in themselves they have nothing of life, even as the forms within nature). Wherefore no one, by any sort of abstractions, can have any conception of the forms which are within the natural: as I now perceive ... being forced to confess that within the most subtle forms of nature there are spiritual forms which are altogether inconceivable."[59]

Such spiritual forms are those substances that constitute the entire spiritual world and especially the spiritual Sun whose perfections and potentialities for use are beyond any imagination. Thus we read, that "there are infinite things in God Man, and thence indefinite things in the spiritual Sun ... These things indefinite stand forth as in an image in the created universe ... Thence is the variety of all things" in both worlds! Diversity springs from infinity![60]

Spiritual things are not "infinite." The spiritual, such as it is in itself, cannot be grasped by any natural ideas or images. Thus we are told that the soul - whether of a man or an animal - is a spiritual substance, and because of this it "has not extension, but impletion" - and can therefore reproduce itself without loss.[61] But this does not mean that it is infinite! Each soul is finite. Other spiritual things - like human states - are also finite.[62] The love and the wisdom of the angels are finite and have no power to comprehend the infinite, and bear no finite ratio to the love and wisdom of the Lord![63] And although the Divine, in its holy proceeding, contains infinite goods and truths, yet truths and goods, with angels and men, are only capable of being multiplied and increased indefinitely; "indefinite" meaning what cannot be defined and comprehended by number. Yet the "indefinite" is finite in respect to the infinite.[64] As in the Lord everything is infinite, so in heaven everything is "indefinite."[65]

The spiritual Sun is the source of all finite powers and varieties. In this one ground substance of creation are comprehended all these indefinite varieties, as potencies; yet there they seem as if they were one, or undistinguished. In lower creation these varieties are made apparent, and thus it seems and can be said, that variety arises and increases toward ultimates - or that variety arises, not from the influx, but from reception.

As a matter of fact, as creation proceeds, the one universal substance is formed by discrete steps into more and more limited, or more and more finite, substances. It loses something of its perfection, in each lower degree; becomes more general, more gross, more inert; its potentialities become less universal, its range narrowed down, its uses more confined and specific. In the lower degrees its changes of state and its adaptability become less capable of variation.[66] The image of the Divine and infinite is obscured with each step. So confined, the one universal substance has indeed - in ultimates - taken on a marvelous variety of forms unperceived beforehand. For no two things in the created world are alike! Yet all this variety is but a remote image of the powers of that original substance. For thousands of thousands of things in the spiritual world there corresponds only some single thing in the natural![67]

The varieties within man's mind - the states of his mind - are incomparably greater than those of his body. For the unlocking and releasing of the varied powers of life tied up in the substance of the Sun of heaven, it is necessary that man climb back on the ladder of life - upwards towards the Source of life! By creation, the Lord as it were lowers that ladder of degrees toward man -
yea, a different ladder for every man! But by regeneration, the Lord suffers man to climb the ladder, to enjoy the increasing varieties of heavenly life.[67a]



---
~~~

== Successive Spheres of  the Spiritual Sun

"Bless the Lord, O my soul ... Who coverest Thyself with light as with a garment; Who stretchest out the heavens like a curtain!" - Psalm 104:1,2

In the preceding essay certain teachings were cited to show that the first of creation was the production out of the Divine Substance of the primary spiritual substance which is universal in everything finite, whether spiritual or natural; and which is called the spiritual Sun, because it is a medium by which the Lord proceeds into His creation, and this proceeding is sensed by angels as heat and light are perceived by our physical senses.

The spiritual Sun - as a universal substance out of which everything finite is formed - contains all potencies and varieties which can ever come into existence to eternity in both worlds. Yet in that Sun these "indefinite" things are as it were undistinguished, or unrevealed. It is not a most simple substance, but a substance most multiple, perfect, and full, and of indefinite adaptability or universal quality. It is beyond the limitations of space and quantity. Being spiritual, it is called "living," yet it has no life in itself, but lives from the Life which is God.

This suggestion was carried further in the comparing of the spiritual Sun, as to its created substance, with the spheres from men and angels, spheres which are deprived of the proper life of the man. Even as the spheres of the bodies of the angels still convey the activities of their life's love, so the spiritual Sun is at once a beginning of creation and a mode of Divine proceeding and of the revealing of the very life of God.

But no matter how perfect in potentialities the spiritual Sun might be, it does not by itself fulfill the ends of Divine Love. The purpose of creation is that the Divine may give of its life to others so that they may receive its gifts of love and wisdom. And such a purpose requires the creation of vessels receptive of life and responsive to it. Such vessels cannot be formed immediately, but are formed "from substances and matters" created by the Lord. It is the office of the first or universal substance of creation to serve as a source for all other finite things. It is a source for all varieties, for substances of all kinds of quality and all degrees of power.[68]

To produce such distinct varieties of substance, the first substance must assume limitations. The substance of the spiritual Sun must generate from itself lower substances in which specific properties are separately manifested, and which are thus able to serve more specific and defined uses.

Even the angels have a very vague idea about the substances of the spiritual Sun and its nearest derivatives. But it is revealed in the Writings that they clearly see this Sun before them, yet perceive its heat and its light - which in the Sun are one - as two distinct things, as qualities which affect them as it were separately. Moreover, they see their Sun encompassed with several radiant girdles or belts of flame which they know to be successive envelopments which temper and moderate the Divine fire to accommodate it for the heavens.

These radiant belts are not merely appearances. They are substances appearing. But their relation to the Sun as the prime substance of creation is not conclusively shown in the Writings. They are described as "devolutions of the infinite" or, elsewhere, as "infinite circumvolutions" which successively diminish the fire of the spiritual Sun.[69] One passage informs us that there are "many radiant circles, which are envelopments (involucra) one after another," to temper the Divine love;[70] another speaks of only one solar circle, in this case seen around the aspect of the Lord as Man;[71] which seems to identify the Sun itself - or its "primitive" substances - with these belts of flame.[72]

In the Arcana we find the teaching that "the truth which proceeds immediately from the Lord, being from the infinite Divine itself, cannot possibly be received by any living substance which is finite, thus not by any angel;" and that "therefore the Lord created successives by which as media the Divine truth which immediately proceeds can be communicated." "But," it is explained, "the first in succession from this (primum ex hoc successivum) is more full of the Divine than can as yet be received by any living substance which is finite, thus by any angel; and therefore the Lord created another successive through which the Divine truth that proceeds immediately might as to some part be receivable this successive is the truth Divine which is in heaven; the first two are above the heavens, and are as it were radiant girdles of flame which encompass the Sun which is the Lord ..."[73]

This makes clear that, although there may appear many circles or belts about the heavenly Sun, yet there are two degrees of finite substance which are above the heavens. We gather - from the somewhat difficult language of the passage - that it is the third successive which carries the Divine truth down into heaven - to the heaven nearest the Lord. That this third successive is the same as the highest or first of the spiritual atmospheres seems borne out by other teachings.[74]

* * * * *

It is of interest to note that the knowledge of a spiritual Sun is not new in the Writings. Among the ancients, God was pictured as haloed by the solar circle. Pythagoras, who was trained in the temples of Egypt and Babylonia and redirected into Greek thought some of the mental currents of the older Orient, is said to have taught his adepts that our sun was only a faint reflection of the "central fire" around which all things moved .76 And in the Old Testament, the coming of the Lord is referred to as the rising of the Sun of justice with healing in His wings (Mal. iv. 2).

In the Economy o f the Animal Kingdom, Swedenborg, though as yet not initiated into the spiritual world, wrote far better than he at that time could have realized, when he penned the following paragraph:

"To know the manner in which ... life and wisdom flow in, is infinitely above the sphere of the human mind; there is no analysis and no abstraction that can reach so high for whatever is in God, and whatever law God acts by, is God. The only representation we can have of it is by way of comparison with light. For as the sun is the fountain of light and the distinctions thereof in its universe, so the Deity is the Sun of life and of all wisdom. As the sun of the world flows, in one only manner, and without unition, into the subjects and objects of its universe, so also does the Sun of life and of wisdom. As the sun of the world flows in by mediating auras, so the Sun of life and wisdom flows in by the mediation of His Spirit ... One sun is within nature, the other is above it; the one is physical, the other is purely moral; and the one falls under the philosophy of the mind, while the other lies withdrawn among the sacred mysteries of theology; between which two there are boundaries that it is impossible for human faculties' to transcend ... "[76]

Swedenborg here speaks of the Moral Sun and notes that by its action life and wisdom are conveyed to man by the mediation of the Spirit of God. He also notes, in comment, that therefore the Scriptures liken the Holy Spirit to the purest aura.[77] Later, in the Theological Writings, this comparison is confirmed. But here a further distinction is made. The heat and light of the spiritual Sun are indeed specifically called the Divine Truth, which is the Spirit of God; for these, essentially, are God's love and wisdom, and thus infinite. But together with the auras of that Sun, which are spiritual, they (the heat and the light) are called "the Divine Proceeding. "[78] We cannot think of the Divine proceeding as heat and light apart from atmospheres; i.e., spiritual atmospheres. The Lord manifests Himself as to love by heat, as to wisdom by light, and as to use by the atmosphere.[79]

These two - the infinite Divine, which proceeds, and the finite, but spiritual, atmosphere which is the instrument by which the Lord operates - cannot be divorced in thought; and we may therefore speak as if they were one in act. Yet neither must they be confused: for one is infinite, the other is created.

In action and appearance they are a one. Therefore the Arcana, in speaking of the gold with which the portable ark and altar of the Tabernacle were overlaid, states that this gold signifies the sphere of Divine truth conjoined to Divine good which encompasses heaven in ultimates, and thus encloses heaven on all sides, and - like an atmosphere - operates around an angel and contains him with its benign spiritual pressure.[80] This Divine sphere prevents, in heaven, the irruption of evils. Indeed, it extends even into the hells and interiorly rules and mitigates evil. But in the externals of hell it is not operative, but is turned into a sphere of Divine truth separated from Divine good.[81]

It is notable that this sphere acts, like the atmosphere of our world, from without - and even in the ultimates or bounds of heaven. But it is specified that in the world boundaries refer to spaces, but in heaven to "goods conjoined with truths."[82] In the world, the pressure of the atmosphere is exerted upon a man's material body; but in heaven the Divine sphere maintains the spirit, the character, so that whatever marriage of good with truth has been effected within him, should never perish or dissolve. This is involved when it is said that angels are in the Lord and He in them and that "in Him we live, and move, and have our being."

It is, then, a spiritual sphere, like a universal spiritual atmosphere, in which heaven is founded, even as the physical universe is ordered and preserved by the force of gravitation: And further, we are told, it is through this same Divine sphere that "heaven came into existence, and was created," and through it is preserved: for "preservation is perpetual creation."[83]

Proceeding and creating are distinct in idea. Yet "what proceeds [from the Divine], this produces."[84] Therefore the Divine Proceeding was "formed successively into spheres, of which the last (ultima) is the atmosphere of the natural world."[85]

What, then, preceded? What spheres were formed before this "last"? The answer is given.

From the spiritual Sun proceeded spiritual atmospheres, "one from another."[86] The sphere of the Divine truth, or the radiation of the Sun of heaven, created them, each one by means of the preceding; created them as "successives," and as the substance in which the angelic heavens were to be founded. "One thing was formed from another, and thence were made degrees."[87]
Swedenborg thus states before the angels: "When I was in enlightenment, I perceived, that by means of the light and heat of your world, spiritual atmospheres, which in themselves are substantial, were created one from another; and because there were three, and thence three degrees of them, three heavens were made ..."[88]

The same concept is borne out by the "angelic idea of the creation of the universe" already referred to

"The Divine proceeding that is nearest to the Lord appears before the angels as a Sun.... From that Sun ...proceed circles, one after another and one from another, even to the last where their end subsists at rest. And these circles, which are one from another and one after another, appearing as extended far and wide - are spiritual atmospheres through which the light and heat propagates itself to the last [circle] ; and in this last circle, by means of those atmospheres and afterwards by means of natural atmospheres which are from the sun of the world, the creation of the earth was accomplished and of all things upon it which are of use... . These angels (who knew that the universe, so created, was a continuous work from the Creator even to ultimates; and because it was a continuous work which depended, is moved and ruled, linked together as a one from the Lord who is the common Center) said that the Prime proceeding is continued even to ultimates through discrete degrees, just as an end is continued through causes into effects ... and that the continuation is not only in, but also around, from the Prime and thence from all prior things into all things posterior even to the postreme ..."

To these profound angelic observations - which are here quoted only in part - is added a postscript on the last page of the manuscript

"By means of that heat and that light [from the spiritual Sun] all things in the spiritual world and all things in the natural world have been created. ... There are three degrees of that light and heat to the ultimates of the spiritual world and afterwards three degrees to the ultimates of the natural world ..."[89]

It is a firm principle in the Writings - a universal of thought - that no angels were created from the beginning, or before the natural world; no angelic hierarchy such as we read of in the Christian mythology depicted by Milton in his "Paradise Lost"! There are no angels or spirits who were not born men on some earth.

Nonetheless the doctrine is reiterated that successive spiritual atmospheres of three distinct degrees of perfection, were created "one from another" so as to become the ground or original substance for as many heavens!

Not only so. But these three spiritual auras are represented as the real cause and formative internal for the three natural atmospheres which are to follow: the latter are only clothings of the spiritual atmospheres, to carry their efficient power down into nature itself and thus complete there the ends of creation.[90]

Later we shall discuss the sequence of the processes of creation - the relation of natural creation to spiritual creation, especially as relates to time. But for the present, let us note that the formation of the series of three spiritual atmospheres or degrees, from the Sun of heaven, was effected by a process of discrete conformations, one degree from another; effected without stop until the third was reached, and effected "without nature" and thus "apart from the forces which serve as substitutes and aids from the light and heat from the sun of the world."[91]

That such successive formation of a series of discrete degrees is possible in a spiritual world and in a substantial essence which by its very origin and character is not in space and time, is beyond the imagination of the natural mind to picture. Yet doctrine and reason combine in leading us to acknowledge that spiritual things have finite relations which correspond to natural relations of space and time, and that spiritual things can therefore be said to combine and form degrees. Such spiritual compositions can be described, and are described in the Writings, as analogous to their corresponding natural entities.

Thus we read of the auras and atmospheres, which "emanate" from the Lord as a Sun: "These auras ... which are spiritual ... when active in general exhibit heat, but when modified singly (singillatim) exhibit light," i.e., heat which in its essence is love, and light which in its essence is wisdom 82 "The atmospheres ... are ... similar in both worlds, ... with the difference that those in the spiritual world are spiritual and those in the natural world are natural ... The spiritual atmospheres are discrete substances or least forms, originating from the Sun; and because they receive the Sun singly, its fire, divided among so many substances and forms, and as it were enveloped (involutus) by them, and by these envelopments tempered, becomes heat, adapted at last to the love of angels ... and spirits ..."[93]

Here the inner and unseen constitution of the spiritual auras is described. Not any "appearance" which spirits and angels see, but the spiritual things themselves are named and described. Naturally we ask ourselves, How can a spiritual substance - which by definition has not extension, but only "impletion"[94] - be divided into entities and parts?

But when we consider our own experience with the spiritual things within our minds, do we not find that our, states, our thoughts, our affections, are complex organizations and orderings of multiform spiritual elements? Do not a great many separate intentions combine and concentrate into some one more general purpose? And this despite the fact that the whole plane of the mind and the spirit, contrasted with our physical world, seems like a continuous and non-spatial something without parts or physical dimensions.

When the Writings describe spiritual substances as being finite forms, and the spiritual auras as composed of discreted forms, they describe those elements out of which our spirit, our soul, our spiritual states, our affections and our thoughts, are constructed! Unless there was a substance the inconceivably subtle modifications of which made possible the varieties of the mental life of man, there could be no thought, no consciousness, no mind at all.

This is implied when it is stated that thought is a modification of the spiritual substances of the mind, and does not come from the physical substances which also are associated with the natural mind as it operates in the body." "The spirit of man ... also is created from finite things ... The finite things from which it is, are spiritual substances which are in the spiritual world ..."[96]

It is clearly taught that the whole spiritual world around an angel is not a place but a state. The things seen there and felt there are appearances or manifestations, not of physical things or of the conditions of space and time, but of spiritual states, or of forms of love and wisdom.

In the spiritual world, these indescribable variations of states of love and wisdom, charity and faith, are seen and touched by a spirit or angel. But such states are not unoriginated. They do not simply happen! They could not exist unless the Lord was continually giving life to the angels, but life modified in a created and finite medium in which those finite changes or states could occur. Therefore we read that "all these things are from a spiritual, and none from a natural origin. A spiritual origin is life from the Lord."[97] And Swedenborg further testifies: "In the other life, everything that is there is - not as some suppose, empty and void - but is the substantial itself, which is the origin of all the substantial things in nature; a living substantial is there, or a most pure ethereal: this is formed by the Lord into such marvelous things that they can scarcely be described; it is enough that I have seen them, and this often. I have been there!"[98]

The spiritual atmospheres are contrasted with the natural ethers: for the natural are dead, but the spiritual "are in themselves active" and "have life in them."[99]

These spiritual atmospheres were "created for the transmission even to the angels of light and heat ... accommodated to the life of both their minds and their bodies, in order that from the light they might receive intelligence, and also see, and, according to correspondence might also breathe . ... and in order that they might receive love from the heat, and have sensation, and that also, according to correspondence, their hearts might beat ..."[100]

But the immediate use of these atmospheres - before there were any angels - was to serve as a means of further creation. One atmosphere came from another and one after another. There were steps and stages in the creation. It occurred by discrete degrees, or by the formation of successives.[101]

Only by conceiving of these spiritual auras as having finite constituents, can we conceive of this process; for it is a process of composition, in which the first degree (or original substance), by a congregation or concentration of its units, takes on a new and less perfect form, to serve a more general use.

A common illustration of discrete degrees is the muscle, which is composed of small fascicles and these of still finer fibrils. An even clearer example is found in the three natural atmospheres: the aura, the ether, and the air. And if we resort to modern instances, the relations of the molecule to its component atoms, and of these to their constituent electrons, protons, etc., might carry out the same idea of discrete planes of composition. In his cosmological treatises, Swedenborg shows various methods by which the lower atmospheres might have been compounded from higher elements.

The distinctness of discrete degrees is indicated when it is stated that "no quality of the air can be elevated to any quality of the ether, and no quality of this to any quality of the aura; and yet elevation of perfections to infinity exists in each of them" on their own plane.[102] In some series of degrees of a common origin, there is greater divergence of quality than in others. So the relation of the spiritual to the natural - or of thought to speech, of affection to gesture - are used as an instance of the difference, but at the same time the harmonic correspondence, between two discrete degrees.

In the spiritual world, discrete degrees are displayed more openly than here on earth. The different heavens are each founded in a different discrete degree;[103] and they sometimes appear, on this account, as one above the other, and thus without any discernible mode of contact. And the statement is even made that the angels of the three heavens dwell respectively in the "regions" of the three spiritual atmospheres: the celestial aura, the spiritual ether, and the spiritual-natural air.[104]

Such a statement would have no meaning unless we realized that these atmospheres were spiritual in essence and function. The "celestial aura" is that created veiling of the Divine love and wisdom which enables the Lord to communicate celestial love with its practical wisdom of innocence. This is received by the highest angels consciously in their interior rational mind; but with other angels it is the origin of their power to will and think spiritually. The "spiritual ether" serves to bring the angels of the middle heaven the love called charity and the rich gifts of spiritual intelligence, because their exterior rational degree is open to receive them; but with all the angels, and all spirits, it empowers spiritual sight! And lastly, the "spiritual-natural air" is formed to give the angels of the ultimate heaven the blessings of faith and obedience because their life is conducted in the interior natural degree; which is the only spiritual plane on which they can be responsive; but at the same time, the same spiritual "air" enables all spirits and angels, high and lowly, to enjoy spiritual hearing and spiritual breathing![105]

Angels, as well as men, live on solid ground. They think, they see, they hear and breathe. They also eat and drink, and enjoy the fruits of the soil. But it is a spiritual soil - a land of spiritual origin, which is "life from the Lord"![106] Nor is it so impossible to transpose the full and complete range of human life into spiritual terms. Some time we will have to do so. We might do well to make the attempt by degrees so far as we are able!

The three atmospheres from the spiritual Sun are not insubstantial abstractions. They are media of creation, substantial and discrete degrees which in their descent become more general, more defined or finited as to potential variations and uses. The lowest spiritual atmosphere does not have the same conatus nor the universality which the highest possessed. It conveys a more general, a less intense, less keen, less intelligent life! It cannot impart the highest, most universal purposes or desires. Yet it is still spiritual and "alive"!

But here we must note that creation - in every series - always proceeds towards its ultimates. And we read that it is so with the atmospheres in both worlds. These atmospheres are distinguished among themselves according to discrete degrees or "degrees of height." But in their progress to lower things they "decrease according to degrees of breadth," i.e., they become gradually and imperceptibly less active and "more compressed and inert, and finally in ultimates so compressed and inert that they are no longer atmospheres but substances at rest ..." The consequence is the formation of "substances at rest," quiescent substances; which, because they originate in the three atmospheres, are also of three degrees.[107] This could only occur - we believe - if each atmosphere so decreased and formed a corresponding degree of quiescent substance.

This process takes place, so we read, in both worlds. But in the natural world, the terminations or endings of the various atmospheres are fixed and inactive matters; a process very well illustrated in Swedenborg's Principia, and especially in his "Lesser Principia." On the contrary, spiritual atmospheres do not so terminate in "fixed matters," but in "substances at rest," of three degrees; and the suggestive statement is made in this connection, that "the Spiritual ... is living in intermediates but is not living in its ultimates. In ultimates the Spiritual retains no more of life than is sufficient to produce a likeness of what is living."[108] This is said with reference to plants which - in correspondence to angelic states - germinate and spring up upon the lands of the spiritual world. "The lands there," we are informed, "are spiritual from their origin": and are "the ultimates" of the forces of acting, creating, and forming, which inhere in everything spiritual.[109]

But our spiritual universe, so far as we have followed its creation, is as yet but in process - unrelated to another element which enters into the work of the Creator, namely, the production of the natural world. Before nature and mankind came into being the world of spiritual causes can only be imagined 'as empty of inhabitants, barren of uses; but full of potentialities, rich in provisions, complete in its range of degrees from the Infinite through the spheres of the spiritual Sun and down to the ultimates of its own series. What the function of those ultimates might be, in the further progress of creation, will be the subject of our next essay.

---
~~~

== The Sequence of Creation

 “Before the mountains were brought forth or ever Thou hadst formed the earth and the world, even from everlasting to everlasting, Thou art God.”  - Psalm 90:2

The end of creation is not fulfilled by the formation of the spiritual atmospheres or even by the formation, in the termination of those atmospheres, of spiritual ultimates. For all these spiritual substances, while they indeed among themselves are discreted into degrees and are therefore in mutual relations of end, cause, and effect, yet taken together they are nothing but an intermediate world of causes - the "substantial" out of which can eventually be created all the glories of the heavens.

The Writings warn us of the impossibility of picturing to our imagination - which feeds on space-time imagery - this realm of purely spiritual causes. Our reason - if somewhat enlightened - can see that such a realm of spiritual causes is necessary, as a prior world. But our reason is also ready to confirm the doctrinal statement which immediately follows one of the accounts of the creation of the successive spiritual atmospheres and the three heavens: "But, because this spiritual universe cannot exist without a natural universe in which it might act out (ageret) its effects and uses, that at once then (simul tunc) the sun out of which all natural things proceed, was created, and through this, similarly, by means of light and heat, three atmospheres ..."[110]

The spiritual universe "could not exist" unless a natural universe was also created. To 'exist' means to stand forth. It could indeed be, but not exist. Its powers could not be manifested or unfolded, its blessings not imparted, its varieties not revealed, unless nature was formed. The teaching is frequent that an interior degree, or a prior one, can exist and subsist without the exterior degrees, but not the exterior without the prior.[111] If this were not the case, the Writings show, man's spirit would perish when the body dies; nor could it be said that in the spiritual world there are not only all the things that are on earth, and in human minds here, but also untold more things which human eyes have never seen.[112]

Nature was not necessary for the bare existence or 'being' of the realm of spiritual substance! But nature was necessary to carry the spiritual into effect. Nature was created, we learn, that creation might be carried to a completion;[113] that it might subsist in ultimates and be fixed; that its uses might continually persist and endure, which is effected by generations;[115] in other words, that the Spiritual might be terminated in effect by being clothed with correspondent forms which might serve for uses [116] Hence the two worlds are mutually interdependent.

In the places where the Writings describe creation, the accounts usually give a full description of the successive degrees of the spiritual atmospheres before mentioning the beginning of natural creation; as though the spiritual universe was first completed in all its degrees before the natural universe was begun. In a certain sense this must be true; otherwise it would be difficult to account for certain expressions used. Yet if we so interpret the teaching, we must bear in mind that creation in the spiritual world - in the beginning as now - is effected without reference to time, i.e., instantaneously; and also that in the inmost degree of spiritual substance is implied all derivative degrees. Perhaps it is in this sense that we must take the unique statement, in The Divine Love and Wisdom, that "the creation of the universe and of all things thereof cannot be said to have been wrought from space to space, nor from time to time, thus progressively or successively, but from eternity and from infinity";[117] suggesting that all things were to God complete before they began! Swedenborg adds, "I am aware that these things transcend the ideas of thoughts which are in natural light ..."

But whatever we may say of spiritual substances, we must take account of the fact that their quality is such that they are not by themselves permanent as to form, or constant.[118] "Unless the Spiritual flow into and terminate in the natural, and rest therein, it is like a prior without a posterior, consequently like an efficient cause without an effect, and like an active without a passive - which would be like a bird flying in the air perpetually without any resting place on the earth."[119]

Here we are reminded of the principle that "in everything created, greatest as well as least, there are ... an end, a cause, and an effect. "[120] When we take creation as a whole, the "end" is in the spiritual Sun; the causes, or means, are in the spiritual world; the effects, finally, are in the natural world. Yet end, cause, and effect, as a trine of degrees, are necessarily also in every created thing, in every detail of both worlds. This means that within the spiritual world there can be spiritual effects of spiritual causes. For there are "spiritual ultimates" which are - in that world - the effects of spiritual causes. But what must also hold true is, that everything spiritual tends to form, not only its own ultimate, but also a corresponding ultimate into which it may inflow and operate as into a fixed and permanent form; and such a correspondent fixed ultimate can exist only in nature.

It is not difficult to recognize the general truth that there is a complete correspondence between the spiritual and the natural worlds. Everything in nature is so formed that it corresponds or answers exactly to something spiritual. We might safely go further, and say that there was a correspondence in the processes by which the two worlds were and are formed. Therefore the two worlds - as to degrees and in appearance - are confusingly alike. Of course the essence and the internal aspect of the spiritual world, which does not possess space and time as properties, are totally different from the internal aspect and essence of the physical universe. The laws of each world therefore seem different - and the sequence of similar phenomena in each world tells the story of different sets of events; even as the sequences of mental states do not obey the laws of nature. But nevertheless they correspond, and the same processes are active in both, even the creative process.

It cannot be said of the natural universe that its creation took place apart from time; except, of course, in the sight of God. "Times were introduced by God with creation," and indeed with the creation of the natural world, where spaces and times are more than appearances [121]

In connection with the formation of nature, sequence and process therefore take on a more comprehensible and familiar meaning. When we read in the True Christian Religion that "then the sun from which all natural things proceed, was created, and, through this similarly, by the means of light and heat, three atmospheres encompassing the former [i.e., the spiritual atmospheres], as the shell does the kernel or the bark of the tree the wood; and finally, through these, the terraqueous globe ... where men, beasts, fishes, trees, shrubs, and herbs were formed out of earths which consist of soils, rock, and minerals," - we can see certain very definite stages and periods in this complex process of formation.[122]

Yet we can also see some very clear confirmations of the truth that "all things which come forth in nature ... are correspondences. For ... the natural world ... comes forth and subsists from the spiritual world, and both from the Divine." "Everything which comes forth and subsists in nature by Divine order, is a correspondent."[123] We see, for instance, that as the spiritual Sun is the first of spiritual creation, and the source and only substance of its world, so the natural sun is the first, the origin, and beginning, of nature, from which, in due process, atmospheres are formed in a threefold order, again corresponding with the prior spiritual creation. That the expanse of the solar system is derived from the center (or from the sun) and not the reverse, is confirmed by the fact that the planets depend for their subsistence on the sun, and by the principle that "subsistence is perpetual existence."[124]

There is definite teaching that this sun of our world "is created by the Lord through the living Sun"[125] and is "from it,"[126] and that the fire of nature's sun "is from no other source than from the fire of the spiritual Sun ."[127]

"The actuality of the natural sun is not from itself, but from a living force proceeding from the Sun of the spiritual world." Indeed, if that living force should be withdrawn, the natural sun would collapse or perish ![128]

This does not imply that the sun of our world is not physical through and through, yea, dead and material, an ocean of pure fire from which everything of life has been utterly withdrawn! a nuclear furnace of purely physical or chemical activity. It is "death itself. "[129] Even its heat and light are entirely dead, and so are the atmospheres around it.[130] Indeed, the worship of this sun would be the most degrading of all cults ![131] That the sun has within it inconceivable stores of energy does not at all contradict the fact that from this their origin, all things natural are material and dead; or that the natural sun has no creative power whatsoever, for its chief attribute is inertia. But it does mean that the spiritual Sun utilizes the natural sun and its dead, motiveless energy, as an agent for its own living conatus.[132] It means that thereby our sun - and, of course, every other parent star - comes to correspond, in the physical world, to the spiritual Sun, and receives a specific influx which sustains its energy directly from the Sun of heaven - or, if you please, from the one original substance of finite creation! For influx is according to corresponding uses, and into them.

This same correspondence is observable in the relation of the natural atmospheres to the prior spiritual atmospheres. And since these two kinds of atmospheres correspond, those of nature become receptive to an influx from the spiritual, and also serve as "clothings" or - in a sense -
embodiments of the spiritual atmospheres. The spiritual become as it were a "soul" to the corresponding natural. For "each and all things which are in the natural world" - however inanimate - "may be said to have a soul, which is the beginning (principium)," cause, or original source of the thing.""

The relating of the spiritual atmosphere as a "soul" to the natural auras does, however, not militate against other statements, which are to the effect that the natural are entirely dead and that "there is nothing interiorly in them from the Sun of the spiritual world"; for we learn that they are only "encompassed" or "girt about by what is spiritual,"[134] or that the spiritual simply is adjoined to, or accompanies, the natural.[135] So also is it said of the fire of our sun, that the Divine life is "outwardly in it," while of the fire of the spiritual Sun it is said that the Divine life is "inwardly in it."[136] Therefore the function of natural heat and light is nothing more than to "open and dispose the things of nature so that they may receive influx from the spiritual world."[137]

We shall return later to consider the fuller meaning of these teachings. Here we cite them only to show that although nature's sun is dead and its atmospheres are equally lifeless, yet the spiritual Sun has a particular relation to the natural sun, and the spiritual atmospheres stand in a similar special relationship to their natural counterparts. There are few clear teachings from which we can conclude their relations. All spiritual things are indeed the "causes" of natural things. But as to the mode or order in which natural creation resulted from these causes, only scant direct instruction is given.

Under such circumstances, it may be permissible to resort to something of theorizing, so long as the theories are borne out by general principles. The most relevant theory is simply that all spiritual things advance - or, rather, progress - toward their least of activity, by continuous decrease, until they are changed into "substances at rest" or "ultimates." The same happens to each atmosphere of the natural world. Since there are three atmospheres in each world, the terminal substances are also of three degrees in each world; which would hardly be the case unless each atmosphere in turn produced its own "ultimate." But let the Writings speak for themselves.

"The atmospheres, which are three in each world, the spiritual and the natural, close in their ultimates in substances and matters such as are in lands."

It has been shown in Part Three (n. 173-176) that there are three atmospheres in each world, the spiritual and the natural, which are distinguished inter se according to degrees of height and which, in their progress towards lower things, decrease according to degrees of breadth. And because atmospheres decrease towards lower things, it follows that they become continuously more compressed and inert, and finally in ultimates become so compressed and inert as to be no longer atmospheres but substances at rest, and in the natural world fixed such as are in lands and are called matters. As such is the origin of substances and matters, it follows, first, that these substances and matters are also of three degrees; secondly, that they are held in mutual connection by surrounding atmospheres; thirdly, that they are accommodated for producing all uses in their forms."[138]

If we may here invoke the principle that "all creation is effected in ultimates," or that "all Divine operation extends to ultimates, and therein creates and operates,"[139] it may be seen that no new discrete degree can be derived until the prior degree, by continuous decrease, becomes a plane or ultimate from or in which a new creative action may commence. On such a premise we assume that the substance of the spiritual Sun formed such a plane of relative inactivity, before the first spiritual atmosphere could be formed; and that that first atmosphere likewise in its ultimate formed the plane for the creation of the second, and so on until the ultimates of each degree had been formed. This principle is variously expressed in the Writings:

"All order proceeds from primes to ultimates ; and the ultimates become the primes of some following order; moreover, all things of the middle order are the ultimates of the prior, and the primes of the following order ..."[140] "Divine influx is from primes into ultimates, and through the connection with ultimates, into mediates."[141]

Ultimates, of course, mean the last things created and the lowest, and therefore refer principally, and usually, to the material world, and indeed to the lowest and grossest parts of that world. Still, every series has its 'last' or its ultimate. We speak of the "ultimate or first heaven," of the "ultimate spiritual atmosphere," of the ultimates of the Lord, or the "ultimate Divine." And of the spiritual world we read that the "idea of state" which the angels have, as well as "the derivative idea of the appearance of space and time, is not possible except in the ultimates of creation there, and from them. The ultimates of creation there are the lands upon which the angels dwell ..."[142] All things in both worlds have been created by means of the heat and light of the spiritual Sun which progress by three degrees "to the ultimates of the spiritual world" and afterwards by three degrees "to the ultimates of the natural world. "[143] "As there is nothing which has not its ultimate, where it ceases and subsists, so also the Spiritual ..."[144]

We conclude then, that there are spiritual substances at rest, which are terminations of every degree and series of spiritual things. But let us here note the principle that the ultimates of one order can become the primes (or firsts) of another order. It is in this sense, that it is said quite definitely that the spiritual or "substantial" is the beginnings (initia) of material things"[145] and that "the substantial is the primitive of the material."[146] "The natural draws its origin from the spiritual, and in its existence it is nothing other than congeries congregated out of spiritual things."[147] There is nothing in nature which is spiritual.[148] Yet it may be said of nature that "its essence out of which it comes forth (existit) is the spiritual ..."[149]

From this it would seem to follow that natural creation is a by-product of spiritual creation; or that the ultimates of the spiritual realm, by a new creative direction, become the substantial cause and thus the "primitives" of a lower type of substance which is called matter, and which is not spiritual, because not at all living.

If this is difficult to understand, we may derive some comfort from the fact that we are assured that, aside from a few statements which describe this process, "the origin of earths from the spiritual Sun through the atmospheres as media" can be expressed only through spiritual ideas, and these "do not fall into any expressions of natural speech," wherefore "it is enough" if it to some extent be "perceived naturally!"[150]

Speaking naturally, and thus in terms of time, we can see that the substance of the natural sun might be formed from the spiritual Sun - in the sense that the first material substance, the inmost of nature, was created as a final and fixed ultimate in space and time for the substance of the spiritual Sun. The sun of the world - it would thus seem - is the first and only substance of nature – and all other material things are derivations thence.

Similarly, the lower things of nature - the three natural atmospheres and their fixed terminations - are the by-products in time and space of the successive spiritual atmospheres and their ultimates. We shall leave it to others to question whether the lower spiritual degrees might have been created only after the prior natural degrees had been formed. Such an order - which introduces definite periods into spiritual creation - is suggested by the language of the "Angelic Idea," in which it is said that the spiritual spheres were formed one after another: since time was properly introduced only with the beginnings of the natural world, this expression suggests that the natural world already had commenced. But to us, this question seems unimportant.

The real difficulty, however, lies in conceiving how spatial, physical matter can possibly originate from some substance beyond space and time. Yet even in his early treatise on "The Infinite,"
Swedenborg recognizes that this must be so. "For extended entities must originate and subsist ultimately from non-extended ..." (Wilkinson's translation, p.10). And later Swedenborg exclaimed before the angels: "What is matter, unless a congregation of substances?"[151]

It is possible that future scientific research into the nature of matter may show that - while it is itself spatial - it is yet of a non-spatial origin. Space and time, and the quantitative properties which attend them, are very real in their own sphere. But the substances which are the inner realities that sustain nature in its greatests and leasts, have nought to do with space and time as such. Space and time - the deadness that is added to the spiritual in nature - "does not make reality (reale), but diminishes it."[152]

On the other hand, the Doctrine warns us against thinking that matter is made up of what philosophers have called "simple substances" which if divided would fall into nothing; that is, "a substance so simple that it is not a form from lesser forms; and that out of that substance, by massings, there exist ... composites, and finally substances called matters."[153]

Spiritual substances are not "simple" in that sense, but are highly composite. For perfection increases towards interiors. "Those who terminate the ideas of their thought in the atoms of Epicurus, the monads of Leibnitz, or the simple substances of Wolff, close up their understandings as with a bolt, so that they cannot even think from reason concerning spiritual influx ... "[154] Such ideas cause spiritual substance to be regarded as "merely a subtle natural substance." It leads to the notion that the original substance of creation was so simple that it "can be likened to a point of no dimension and that from infinite such [points] the forms of dimension arose."[155]

This is a fallacy originating from the idea of space. The constant truth is that "the simpler and purer a thing is, the more [eminent] and the fuller it is."[156] The most perfect, beautiful, complex, and marvelous forms are found in the interior constituents of things.[157] Among the idle fancies about creation which enter the mind if one does not realize that God is the first substance and form, is that the substances and forms of creation originate "from points, then from geometrical lines, which, because they are of no predication, thus are in themselves not anything."[158]

The appearance is as if Swedenborg here repudiated the theory which he had published in his Principia ten years before his enlightenment. But let us note that what he rejected was the concept of indivisible "mathematical points" which have no form, no qualities, and no content, but are - in fact - nothing.

The more physical matter is examined, the more elusive is the substance of it. Once it was thought that the world of nature was made up of uniform indestructible units; later these units were conceived as multiform - as elements; a further revision allowed that the units or atoms also were composites; still later research found it easier to view matter as virtually bundles of energy, in a most complex organization.

In his scientific works, Swedenborg already recognized this nature of matter. He spoke of the elements of the world as forms of motion - and showed how the laws of mechanical motion demanded degrees and series of such forms. He saw that the more gross and inert matters of the earth were but compositions of more active and perfect forms. And the inmost constituent form of such energic motion - the first form of motion from which all the rest came - he called the "first natural point."

It is to be noted that he did not ascribe to the whole of nature anything really substantial of its own. Nature's so called "substances" were only forms of motion. In conceiving how this could come about he had the same difficulty as we do. "Still," he writes, "it follows from reason and experiment, that motion is the only medium by which anything new can be produced. Motion itself, which is merely a quality and a mode, and nothing substantial, may yet exhibit something substantial ..." (Princ., I., ii, 24).

Swedenborg's "first natural point" was thus a symbol, only a symbolic name for the beginning and the vanishing point of material qualities. Yet it is important to note that this was no merely geometrical concept. On this account he abandoned the expression 'first natural point' after publishing the Principia in 1734. He defined his point not only as the beginning of motion - thus giving it a dynamic quality; but also as a focus or concentration point of what he termed conatus!

'Conatus' means endeavor; which belongs not to motion, or matter, or space or time, but to the world of life. Conatus is a spiritual thing. The Writings state, "Endeavors result from living forces, and produce in objects acting forces."[159]

"Motion is nothing but continual endeavor; for when endeavor ceases, motion ceases; and therefore there is nothing essential in motion except endeavor."[160] "Endeavor produces act and motion."[161]

We are also aware that the spiritual, when it appears in the natural world - as for instance in the body of man, or in the growing plant appears only as an "endeavor" which produces action and growth. Hence the definition is given, that "that which is from the spiritual world in natural things,
... is an endeavor, on the cessation of which action or motion ceases... . This endeavor ... in action or motion is the spiritual in the natural: for to think and will is spiritual, and to act and be moved is natural. "[162] "The conatus is from influx; from the conatus is force; and from the force there is effect."[163]

All the indefinite effects in nature are thus the results of the endeavors or the conatus that are the inmost essence of each thing therein. Heat and light, by their action, have the effect of "actuating the conatus" which by creation is continually inflowing into each earthly thing. "This conatus ... is from the spiritual acting in them and into them."[164]

Conatus is spiritual. It is the potentialities of spiritual things coming into focus and expression. In the human body, a simple action is prompted by the confluence and congregation of untold mental endeavors and states, both conscious and unconscious. These concentrations of many ideas into a focus is shown in speaking or in writing.

The spiritual world, in its whole range, is a world of conatus. It is the influx of that world which causes all action and motion in the world of nature, all organic life, and all the speech and act with men, thus all changes. But there are conatus of many degrees.[165] In the creation of matter, the potentialities of the various degrees of this spiritual realm were not at first segregated or specific, but that world acted from its ultimates where spiritual forces had as it were interlocked in a neutralized state of relative passivity, and where each spiritual series acted in general. And "in generals," or in ultimates, the conatus of the spiritual is not a conatus to what is living; not a conatus to release its inward spiritual potentialities and varieties as is done in organic forms or in the human mind; but a conatus which is merely a general prompting to motion - motion without specified "motive" or distinct, evident purpose. It is a conatus which in comparison might be regarded as non-living. "Motion is nothing else than continuous conatus; for when endeavor (conatus) ceases, motion ceases; and therefore there is nothing essential in motion except endeavor.... Endeavor in man is will, and motion in him is action; they are so called in man because in him endeavor and motion are living."[166]  Thus the Doctrine makes clear that not all endeavors are properly called "living." For there are endeavors of "life's ultimate forces."[167] The atmospheres become in ultimates such forces, from which dead matter is formed and maintained; in order that from matter there may eventually be fashioned the clothings for life's more interior forces, so that the inflowing life may - in the form of uses - return to its origin.



---
~~~

== The Expanse of Nature

"He maketh His sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust." - Matthew 5:45

The Writings teach that the two worlds, the spiritual and the natural, "as to external face are altogether similar ... but as to internal face altogether dissimilar"; indeed, so altogether distinct from each other, that "they can in no manner be together ... and have nothing in common with each other; yet are so created that they communicate, yea, are conjoined, by correspondences."[168] And "because these two worlds are so distinct, it is necessary that there should be two suns, one from which all spiritual things are, and one from which all natural things are."[169]

In so speaking, the Writings use our solar system as a pattern. There is only one spiritual Sun, for its substance is universal in creation and apart from the concept of space. But there are innumerable stars - each a natural sun, each a potential origin and center of a planetary system of its own. What the Doctrine stresses is the contrast.

One sun is living, the other dead. The dead sun itself is created by the Lord through the living Sun. The dead sun was created to the end that in ultimates all things may be fixed, static, and constant; "thus and no otherwise is creation founded. "[170]

It is particularly noted in the same doctrinal context, that "everything was created through the living Sun, and nothing through the dead sun." "What is living disposes what is dead in submission to itself, and forms it for uses, which are its ends; but not the reverse."[171]

What we see in the progress of natural creation is thus how the forces of creation - which are wholly spiritual - form nature as a tool for uses, thus for spiritual ends. There is no room for chance or accident in such a universe.

Owing to this fact, our point of view as New Churchmen must differ widely from that of secular science. For natural science is in the effort to analyze the actual motions of the dead forces of nature, predicting natural effects, and putting this knowledge to use. It has the function of describing the modes in which nature acts, and is not concerned with the spiritual causes and spiritual ends which give to nature its reason for existing. It is therefore often the fashion today to ignore those ends; to accept the physical world as a vast and unfathomable conundrum, which simply grows larger as the horizons of knowledge widen: to look upon it as an incredible yet actual work of blind and clumsy forces and relentless laws of motiveless energy which weave the infinitesimally small electrons as well as governing the inconceivable immensities of galaxies and island universes millions of light-years away.

Under such a concept, the formation of our own little solar system was but an accident among errant masses of matter. The competing theories of the formation of suns and planets need not here concern us. The Writings themselves say scarcely anything about the formation of the sun and its system. But the principle stands out that in each solar system the sun was formed first. A confirmer in the other world once suggested to Swedenborg and an angel guide, that "before the sun, there may have been something, and this everywhere in the expanse, and that this flowed together of itself into order, thus into a center." Swedenborg and the angel then addressed him from indignant zeal, and said, "Friend, you are beside yourself! ... What is more indicative of insanity than to say that the center is from the expanse? By your center, we understand the sun, and by your expanse, we understand the universe; and thus that the universe would have existed without a sun. Does not the sun make nature and all its properties, which depend solely upon the light and heat proceeding from the sun through the atmospheres?
... Are not the atmospheres and all things which are upon the earth, like surfaces, and the sun as their center?" Their argument was, in brief, that subsistence is perpetual existence. Since all things now clearly subsist from the sun, it would follow that they existed from the sun. Otherwise the prior would come from the posterior, which is contrary to order and to the laws of nature, and to common sense. And, they added, was it by chance that the expanse flowed together into such wonderful order? as if nature could exist from nature? And their final word was that the sun of the world existed from the spiritual Sun (which was the center of an expanse of life, called the spiritual world), and that from the natural sun there existed the expanse of space, called the natural world.[172]

Every sun, or star, thus became a vice-regent of the spiritual Sun, which is universal, and became the mother of the earths or planets of its system, and of their satellites. Again, the Writings themselves give only slight instruction as to the mode in which atmospheres and planets were formed. The fullest statement is the following, from the Apocalypse Explained:

"From the sun of our world, auras and atmospheres proceed as from their fountain; these are called ethers and airs; whence, nearest (proxime) around it, is the pure ether, and, further away from it, ether less pure, and finally airs; but these and those (viz., the less pure ethers and the airs) are around the earths."[173]

That these atmospheres constitute three discrete degrees, is also clearly taught.[174] The pure ether or "aura" is universal, but it alone immediately surrounds the sun.[175] The "ethers less pure" are centered around the earths, and are therefore said to be farther away. The three are also distinguished as ‘aura,' ‘ether,' and ‘air.'

* * * * *

Atmospheres alone cannot constitute the expanse of nature in which the uses of life are to become clothed. In order to express all spiritual potentialities, the natural world must fully correspond to the spiritual as to all its degrees, both discrete and continuous. And the final likeness between the spiritual and the natural worlds is confirmed by the statement that "there are, in each, atmospheres, waters, and lands, which are the generals through which and from which all and singular things exist with infinite variety."[176]

Atmospheres, waters, and lands, are "generals." The tangible substances of our world exist in either of three conditions, in gaseous form, or as liquids, or as solids. Thus water vapor can be condensed as liquid water and finally as solid ice. And it might be the same with the ether and the aura! Yet more than this seems to be implied in the statement. Atmospheres are called "active forces," waters are called "mediate forces," and lands are called "passive forces." In both worlds, these are the generals of creation.[177] But it is notable, that the atmospheres are said to be of three distinct grades, or of three discrete degrees. "It is a fallacy of merely natural sense
... that there is only one single atmosphere ... and that there is a vacuum where it ceases."[178]

This is as yet unknown in the world. The only atmosphere within the certainties of science is the air - a mixture of gases surrounding the globe. That the air is relatively an "active force," is of course easily seen, from the fearful velocities of the wind, and the sound effects of its vibration and its varying pressure. Some scientists are inclined to believe in the existence of an "ether,"
but are unable to define its properties and therefore often regard it as merely something of a symbol of one's aversion to conceive of radiations in empty space! Also within the projects of science are studies of the magnetic fields of force which belt the earth.

But in defining atmospheres as "active forces," the Writings lift our minds into the realization that there are forces in nature which operate in discretely differing fashions, and yet cannot be divorced from substances. Thus we read

"The three natural atmospheres, originating from the sun of the world, are: the purer ether, which is universal, and from which is all gravity; the middle ether, which makes a vortex about the planets, in which also is light, in which are the satellites, and from which comes magnetism; and the ultimate ether, which is the air."[179]

Each of these three represents forces which act in a discretely different way; so that "no quality of the air can be elevated to any quality of the ether, nor any of this to any quality of the aura; and yet an elevation of perfections to infinity is possible in each."[180] The force of gravity is unique in its universality, and in the fact that no object or mass or substance in our universe seems to be opaque to its penetrating influence. Light and magnetism are classed together; and their close relationship seems indicated by the fact that recent tabulations of the types of "radiation" show that so-called "wireless waves," heat radiations, the spectrum of visible light, ultra-violet radiation, X-rays, -y-rays, and possibly some ‘cosmic' rays, are all parts of a continuous series of varying "wave-lengths." It is also true that matter, of some sort or another, stops all such rays. It is equally true that, as a class, they are utterly different from sound-waves in the air.

We also note that in recent physics all these natural forces are assigned their functions in the actual constitution of matter. Matter is not given any greater reality than light; even light has inertia and is apparently affected by gravitational influences; and often light is simply regarded as energy propagated through space! This is interesting to us here, even if we should be extremely skeptical about what science sometimes cautiously proclaims and her disciples loudly dogmatize. For the Writings - without shadow of doubt - state that atmospheres (yes, in each world), in their progression towards ultimates, decrease in activity and are converted into "substances at rest, and, in the natural world fixed, such as are in lands (terris) and are called matters."[181]

It cannot be thought that the Writings were intended as a text book in physics. Yet it is one of the primary teachings of this revelation that there is a correspondence between the two worlds. Swedenborg could-from his Divinely granted knowledge of the heavens-see many of the things "deeply hidden in the sciences" which his day and age could not have known, nor yet ours. He had also been led by a singular Providence, since youth up, to study natural truths for the sake of the end that he might see principles of order in both worlds, see, not only the surfaces, but the underlying essences, of these two worlds.

We take it, then, that while we cannot obtain more than a very general and somewhat imaginative idea of what the Writings mean by "the atmospheres," yet, profoundly involved in such descriptions, rationally interpreted, we may, in each age, come upon new truths which shall bring us nearer to a real concept of the work of God the Creator, and of His laws-laws which correspond in both worlds.

* * * * *

When the atmospheres of our world are called "active forces," this does not mean that they are "living" forces. For they have their origin and source in a sun which is "pure fire" and thus utterly dead and material. The natural atmospheres therefore are "dead forces," and "forces not living, "[182] although they are "active,"[183] when contrasted with waters and lands.

The Writings explain this as follows: "There is a spiritual world; and that world is prior, interior, and superior to the natural world; consequently everything in the spiritual world is a cause, and everything in the natural world is an effect. Even in the natural world one thing exists from another in a progression, but this is done through causes from the spiritual world, for where the cause of the effect is, there also is the cause of the efficient effect; for every effect becomes an efficient cause in order even to the last where the force subsists as an effector; but this is done continually from the spiritual, in which alone that force is. This, therefore, is what is meant by
[the statement that] nothing in nature exists except from the spiritual and by means of it."[184]

This implies that although natural things are all of them mere effects of spiritual causes; yet effects among themselves can portray relations of cause and effect. One natural thing is derived from another, in endless progressions. Some natural things are more active, and are then called "efficient effects" because they seem to be effective causes of other natural things.

"In nature there are two mediate causes by means of which every effect, that is, every production and formation there, is accomplished. These mediate causes are light and heat.[185]
Light modifies substances and the heat moves them, each from the presence of the sun in them. The presence of the sun that is manifested as light causes an activity of the forces or substances of every particle according to the form that it has from creation. This is modification. The presence of the sun which is perceived as heat expands the particles and produces the acting and effecting forces according to their form, by actuating the conatus that they have from creation. This conatus, which becomes by means of heat the acting force even in the minutest forms of nature, is from the spiritual acting in them and into them."[186]

From such teachings it is clear that nature progresses by causes and effects toward the creation of planets and the formation of their ultimate constituents.

The atmospheres are composed one from another,[187] and it is through the natural atmospheres that the terraqueous globe was formed.[188] This leaves us to enquire as to the manner of this formation. The Writings - as we have seen - hint at the process. But in his scientific works Swedenborg had developed a general principle which accords with these hints. The sun, he shows, surrounded itself with atmospheres, the single particles of which had a shell-like exterior within which the fiery particles of the solar substance were active; and when the volume of these atmospheric particles had reached a certain limit, the pressure was so intense that at the margin of the sun the atmospheric units broke down, their active internal being as it were pressed out and the passive exterior being pressed together into a relatively solid unit which no longer was atmospheric in nature, but was a grosser, passive substance at rest; which was thus available for new formations, some parts being employed in the building of a lower type of atmospheric particles, other parts becoming matter such as formed the kernel of the earth. The process, in somewhat varying ways, is repeated, until matters of several other degrees have been compounded by means of the atmospheres around the planets, which atmospheres are also subject to similar compression.

In the published Principia, which was an Introduction to his trilogy on the "Subterranean or Mineral Kingdom," Swedenborg also gives a theory of the formation of the planets. A modified form of the same general theory is given in the "Worship and Love of God," the last of his philosophical works. In essential outline the theory simply is that the sun was first created as a center of most active finites of fiery units of highest type, then put forth an atmosphere, which in turn by pressure condensed into a passive matter encrusting the sun. It was such matter which became the source of the core of the planets: for due to the revolution of the sun around its axis, this heavy matter was gathered as a belt around its equator and finally broke up into various masses which were - by centrifugal force - hurled out into the solar vortex, as planets and satellites. These various planetary masses also exuded their atmospheres. First, a far-reaching sphere, the ether, in which the satellites also are included. Second, an ultimate atmosphere, called air, which closely hugs the surface of the earth. The inference is that the terrestrial atmospheres also by compressions gave rise to matters which added themselves to the earth.

In the "Lesser Principia,"[189] a variant method of creation had been suggested. A first atmosphere is formed from the sun, and by compression of its parts a first matter, which is promptly used up in the formation of a second atmosphere, or ether. This ether forms itself into whirling volumes, which travel out into space, each ether volume destined to be formed into a planet with a definite and balanced orbit around the sun. Towards the center of such a volume or such a tellurian vortex, the ether particles become compressed into a second type of passive matter, which in turn is used up in the formation of a third atmosphere, the air. The air as it increases in volume, becomes also compressed toward its center, and forms there a third type of matter, which Swedenborg identifies with water. Afterwards this globe of solid water at its center generates, by the intense pressure, various solid substances, such as now compose the earth.

* * * * *

We have cited these theories from the early works of Swedenborg without claiming any critical knowledge of the technical, physical, mathematical and astronomical problems involved; but merely in the hope that they might suggest some clue to a better approach to some of the principles of creation.

Similarly, the early history of the globe - on which scientists are not agreed - is pictured by Swedenborg in several early works; and especially in his "Worship and Love of God," where his descriptions are given in a semi-poetic, semi-scientific vein which brings up many principles later reiterated in the Writings. Such a study of the progress of physical creation "does not properly enter" into a theological system.[190] Yet it gives us a suggestive background such as must have been in Swedenborg's own mind when he later received Divine instruction in the spiritual laws of influx which rule all the operations of nature.

Swedenborg thus portrays the globe as it was traveling in widening orbits from the sun, as a naked planet, veiled from the sun's rays by the ether and the air. Over its central core lay the primeval ocean. By compression in the boiling depths of this abyss there were formed various "salts," and from these, by combinations of the interpenetrating ether and the water and the fragments of salts and the minerals of the core, a storehouse of chemical substances. Many of these floated up to form a dense crust of richest variety over the original ocean - a scarless plane perforated only by warm rivers, bathed by a dewy mist, and fathered by the air and wind.

But as it neared its destined orbit its years grew longer and its native heat decreased; yet a perpetual spring ruled in this perfect infancy of the earth.

We shall not here describe the details of the progressions of creation as they are recounted in the Worship and Love of God. Let it suffice to say that when all conditions were ripe, the surface of the earth, like an egg, contained all the wealth of prior nature, and waited only for the advent of life. The earth - i.e., the mineral kingdom-was as it were full of tiny eggs, charged with the powers latent in the atmospheres and in the minerals themselves; eggs which needed only the fertilizing spirit before developing or unfolding into forms of life. And it is said, that "these seeds or beginnings lay ... one folded up in another, namely, the vegetable kingdom within the mineral kingdom which was to be the matrix, and the animal kingdom in the vegetable kingdom which was to serve as its nurse and nourisher ..."[191]

The account goes on to show that it was the three types of nature's atmospheres - the aura, the ether, and the air - which, in the reverse order, were the tools for mediating life to the vegetable forms - flowers, shrubs, and trees - which now turned the barren earth into a paradisal grove.[192] Rich loam covered the ground like a soft couch, leaves sheltered it from the sun's heat. And nature was ready for another step.

For - in this romance of creation - instead of merely producing its own kind, the plants of every species became pregnant with corresponding species of animal life. At first the lesser herbs, from their seedpods, transmuted into ovaries or wombs, brought forth insects and humble reptiles. At a later period the birds were hatched from nobler plants; and finally, from viviparous forests, whose sap by Providence was richer, were born mammals of every kind.

A miracle, you may say? Yet not so complete a resort to miracle as was the orthodox idea of Christians in Swedenborg's day-the idea that God disregarded all means, all methods, in His creative acts, and simply called each thing into existence by the mere command from His mouth

The principle which draws our attention, however, is involved in one of the footnotes to this story. The account itself is obviously written in a somewhat playful mood, and is embellished by fancy and symbolism. But in the footnotes we find the sober philosopher. The philosopher distinguished carefully the origin and nature of the plant kingdom from that of the animal kingdom. The form of plants is natural, and the medium of their formation is the natural atmospheres. But the animal kingdom has the form of life, and the forces which mediate its life are spiritual. Thus he wrote:

"From the very series of productions, it may be evident whence came the souls of brutes, which are said to have been ingenerated in the seeds of the vegetable kingdom; for as the seeds of plants arose from the conjunction of the active powers of nature with the inert powers of the earth, through the medium of the radiation of the sun of the world, so these seeds, which are animated, arose from that form or spiritual essence which is spiritual and living, infused into the forms or active powers of nature, through the medium of the radiation of the Sun of life."[193]

The Writings give no teaching about the emergence of the animal kingdom from the womb of the vegetable world. Yet observe how the distinction between these two kingdoms as made in the Worship and Love of God approximates the revealed doctrine which we find in the Apocalypse Explained.

"There are two general forms, the spiritual and the natural; the spiritual is such as belongs to animals, and the natural is such as belongs to plants. This is why all things of nature, except the sun, the moon, and the atmospheres, constitute three kingdoms, the animal, the vegetable, and the mineral; and the mineral kingdom is simply a storehouse, in which are contained and from which are taken those things which compose the forms of the other kingdoms ...

"The forms of the animal kingdom, which are called, in a single word, animals, are all according to the flow of spiritual substances and forces; and, from the conatus that is in these, this flow tends to the human form, and to each and all things of it from head to heel; thus it tends in general to produce the organs of sense and the organs of motion, also the organs of nutrition and the organs of prolification. For this reason the entire heaven is in such a form, and all angels and spirits are such a form, and men on earth are in such a form, and all beasts, birds, and fishes, for all have like organs. This animal form derives its conatus to such things from the First from whom all things are, who is God, because He is Man. This conatus and consequent determination of all spiritual forces can be given and exist from no other source, for it is given in things greatest and in things least, in first things and in things last, in the spiritual world and therefrom in the natural world; but with a difference of perfection according to degrees.

"But the other form, which is the natural form, and which is the form of all plants, has its origin in the conatus and consequent flow of natural forces, which are atmospheres and are called ethers; and in these this conatus is present from a determination of spiritual forces, which is into the animal form, and from a continual operation of spiritual forces into natural forces which are ethers, and through these into the materials of the earth, of which plants are composed. That its origin is such is clear from what has been said above, that a certain semblance of the animal form is evident in them. That all things of nature strive after that form, and that the ethers have impressed upon them, and so implanted in them, an effort to produce that form, is evident from many things ..."[194]

But the end of creation is not the formation of the earth, or the rearing of a paradise, or even the raising up of animated forms of life. The inmost endeavor which is involved and hidden in all created forms, dead or alive, is the end of use, use to man. It is for the sake of man that every degree was formed, every step and process effected. For in man, and in him only, can uses return into spiritual life. Only in him and through him, can nature give thanks to its Creator.



---
~~~

== The Creation of Organic Forms

"And the earth brought forth grass, the herb yielding seed after his kind, and the tree yielding fruit whose seed was in itself, after his kind…" - Genesis 1:12

We have attempted to outline the teachings about the creation of the spiritual world as a prior world of causes, and of the natural world as a posterior world of effects; each arising from its own sun whence atmospheres issued in a series of three discrete degrees; and each, through these atmospheres, forming its own threefold ultimates. It was also suggested that the stages of elemental natural creation were always the correspondent result of the successive steps of spiritual creation.

Yet we must understand that these two distinct creations operated together, the spiritual within the natural, for one common purpose. The end of creation was that the spiritual might express itself and form itself in and by the natural. Although utterly distinct in themselves, the spiritual and the natural were to be conjoined in the accomplishment of uses.

The end of creation is use. And the final use or the eventual end of creation, is the formation of a heaven from the human race - an eternal heaven in which the infinite ends of the Divine love which were from the beginning involved in the things of spiritual creation, might again be evolved, and thus sensed and consciously received by finite human minds, as Divine blessings.

Creation is therefore looking to man as its plane of fulfillment. Yet man had to be created last, as the basis of all that preceded.[195] In man was to be collated everything of Divine order, from firsts to ultimates : "into his inmost were collated those things of that order which are primary; and into his ultimates those which are ultimate." He was to be an epitome of creation, a focus of all its forces, a replica of the world and also of heaven; yea, an image of God. Everything created was to prepare for his formation. The final use of every created thing was to be a use to the human race.[196]

To imagine the creation of mankind on a barren globe is indeed impossible. The earth must be prepared for man. And this was done by the appearance of the vegetative and animal kingdoms, which prepare the globe for man and serve him for a source of nourishment and protection, and this for the mind as well as for the body.

Whence came these first forms of uses - vegetation and animal life? That they came from a spiritual cause, is of course certain: for that which is dead cannot be the cause of that which is living. Matter, which is so inert and dead, is of course not entirely inactive, and even a grain of sand has its inner activity and its exhalation or sphere.[197] Yet the only conatus present from creation in a material particle, is an endeavor to motion - a conatus which maintains the particle as a unit. Matter has no creative power within it - it is a form of inertia, it tends to entropy. It contains only a "non-living conatus," which is "the conatus of life's ultimate forces."[198] It is motive-less, purposeless, and thus blind and general. Each unit of matter such as exists on the earth is therefore in itself opposed to change, and mostly tends to remain such as it is, unless acted upon by outer forces.

Clearly, then, material substance, from its own proper conatus, cannot become changed into living substance. Changes are, however, promoted from a different source: for the heat from the natural sun expands the material units and "actuates the conatus that they have from creation";[199] and thus, even in the minutest forms of nature, there arise acting forces which cause matters to combine and recombine in different ways, producing a variety of composite substances and chemical combinations, acting and interacting, but tending as a whole into a balanced state, or into an equilibrium of forces.[200] Yet even from the most vast production of complicated chemical substances, no development of life can possibly arise, nor any forms of living uses be created.

Life comes only by influx from the spiritual world, and this is mediated by the spiritual atmospheres. The spiritual is not in space, nor is it confined by the natural; but it is present within and around the natural, in all its degrees. Yet it can act by influx only according to correspondences; or, what is the same, it can inflow only according to reception.[201]

There is only one Life - the Divine and Infinite God. But this One Life, in order to animate the universe, is transmitted through spiritual media which are the substances and forces of the spiritual world. Through the spiritual Sun and its atmospheres and substantial degrees, this one infinite Life finites and directs its infinite purposes into special ends of use, into definite endeavors, into finite and specific qualities. The whole spiritual world, in its range of degrees, contains these endeavors toward uses in substantial potency. It is a world of conatus, in ordered variety; and thus contains the causes of all natural creations and formations. It is the source of the formative substance or "soul" of every organic thing in nature.

The most general effect of life, mediated by the lowest spiritual, would be merely a conatus to motion, such as is the formative principle of matter. But in order that life - sensitive and endowed with something of freedom, and with an aspiration towards growth - might be manifested in nature, as it is in the vegetative kingdom, the spiritual must act from a higher conatus than a mere endeavor to motion!

The Spiritual, present in the natural, is always manifested only as conatus, whether in the intelligent speech and act of a man, or in the instinct of an animal, or in the vegetative effort of a seed in the earth. But we must recognize that there are degrees of all things, and thus also of this conatus.[202] Each degree of conatus has a distinct source in the spiritual world of causes. And, moreover, the higher conatus inflows into, and dominates the lower, and sometimes overrules and displaces it. This is a universal law of life, both spiritual and natural.[203]

Thus a conatus to motion, such as is the origin of material substance, can be the focus of living forces from the spiritual world which can begin to direct that conatus and determine that motion towards a use. When this is first done, the first point of life begins on the young earth, the first living seed is produced, the first plane is formed into which the Spiritual can inflow to reveal some of its manifold powers.[204]

Thus it can be said that in the mineral kingdom - in the soils of the earth - there lie concealed, and as it were involved, the ends and beginnings of all uses which spring from life. These ends are the conatus to perform uses;[205] use is the spiritual soul from which they come and which now assumes a clothing, by associating material substances to itself in order to use the physical energy tied up in these matters for productions of organized and growing forms of ever increasing complexity and perfection. This is the first conatus visible in vegetation. Inwardly in this there is again present a conatus to perform uses for the animal kingdom, to serve it for food; and this also causes plants to take on a certain semblance to the animal form.[206] But inmostly in the vegetative soul there is a conatus to be of use to mankind.[207]

As we understand the teachings of the Writings, it is only when matters are acted upon by a source of energy outside of themselves, such as heat or radiation, that they can come into a state in which an influx of life can occur to change the quality of their conatus. Yet it is strongly stressed that the heat of nature merely gives the opportunity for the forces of spiritual heat, conveyed through spiritual substances, to exert a guidance and direction over nature. And we are warned not to think "that God implanted in nature from the beginning a power to produce such things" as animals or plants, for "no power is implanted in nature."[208] But it is "an unceasing influx out of the spiritual into the natural world" which effects such creations. Form, or the "image of creation," is spiritual.[209] Nature contributes nothing to the forms of uses, but is merely led by the spiritual to "infill" that form with matters to render it permanent and fixed.[210]
For spiritual substances are not in themselves constant, since they are apart from time.[211]
Therefore there is within everything spiritual a conatus to clothe itself with a body out of homogeneous or corresponding things on earth.[212]

This was illustrated to a learned man, Sir Hans Sloane, in the other life, in Swedenborg's presence. Sir Hans was permitted to handle and examine a bird in the spiritual world - a bird which was a spiritual creation corresponding to some affection in the mind of an angel; and which vanished in his hand when the affection ceased. The experience caused the savant to admit that nature contributed nothing to the image and form of creation: "If that bird," he exclaimed, "were to be infilled in its minutest parts with corresponding matters, and thus be fixed, it would be a lasting bird!"[213] No sudden materialization is here meant or expected. But in the normal procreative process, the male seed of a bird contains the codepattern which conveys the spiritual form of the species to the ovum where it is clothed or infilled with "corresponding matter" to fashion an individual bird which can reproduce its kind on earth.

When it is said that "within everything spiritual there is a conatus to clothe itself with a body,"
this also implies that the spiritual, in its greatests and its leasts, its primes and its ultimates, contains not only an active force and a creative force, but a formative force.[214] This formative or plastic force operates in ultimates - especially mediated by the atmospheres, both spiritual and natural[215] - affecting the substances and imbuing them with the power of impregnating seeds and guiding their growth.[216] This formative force thus gathers the substances of nature into a complex form imbued with a living purpose of use. It builds the inanimate things of nature into fibers and cells, and orders these into connected structures of organic life.

* * * * *

The forms of uses are brought forth by the Lord out of ultimates.[217] But uses themselves are spiritual. Uses - we are therefore assured - existed before the organic forms through which these uses are brought forth.[218] Nothing is formed unless there is a need for it - a use. And unless something spiritual existed which had a need to be clothed in natural forms, no organic life would have been formed.

But the Writings show that there are many degrees of what is spiritual, and that the formative force lodges "in each degree thereof, but with a difference of perfection."[219] It is therefore explained that "the souls of beasts are not spiritual in the same degree in which the souls of men are spiritual."[220]

That there are three degrees of spiritual substances and forces, is generally taught, and is testified to by the fact that there are three spiritual atmospheres and three heavens. But we are also taught that besides these three degrees "there are also as many degrees of things spiritual below the heavens, that is, in nature; which are lower degrees of things spiritual ..." This is illustrated by the fact that man's mind, while he lives on earth, grows up in a physical environment, and this natural mind, which is of course a spiritual and living thing, is of three degrees - rational, intermediate, and sensual; or, rational, imaginative, and sensual.[221] Man therefore enjoys natural affections; and indeed, his natural mind, as distinguished from the spiritual mind, is composed or organized of natural as well as of spiritual substances.[222]
Thought is from the spiritual substances, yet is conducted in his earthly brain, organized of natural substances.[223]

That there is such a set of lower spiritual degrees operating in the body is also consistent with the teaching that there are, properly speaking, six spiritual atmospheres: "three above the sun of the world, and three below it"; "the three below the sun ... closely accompany the three natural atmospheres, and enable a man in the world to think and to feel."[224]

It is important to note that the formative force is present not only in heaven, but also in the lower degrees of the Spiritual, which operate into nature. For the souls of animals and of plants are distinguished from the souls of men, in that the human soul is formed from all the spiritual degrees, while those of animals are formed of the lower spiritual degrees only.[225] On this account animals all represent natural affections, and thus picture forth the various inclinations of human nature and parody the possibilities of human types, with their passions and fears and instincts.

In the spiritual world, the exterior or natural affections of spirits and angels are therefore continually imaged, by the formative and plastic power that lies inherent in such affections, as animal forms as real as those on earth, but not permanent except as long as the affection is active. And the same affections can be represented in equally evanescent creations of plant-life which instantaneously germinates from the ultimates of heaven "which are the lands there."[226]

Thus the things which appear in the other life are the correspondential forms of the states of what angels and spirits receive from the Divine. It was very different in the first creation of plants and animals in the natural world. These were not created to represent the states either of spirits or men: for man was not yet in existence. Yet they were created from the same spiritual degrees and formative origins! origins in the spiritual world, in those degrees of it whereby it extended itself into the natural world. They originated as the first formations from the spiritual-natural; from ends latent in the spiritual. These ends were the Lord's ends, determined, in the spiritual-natural degrees, into endeavors toward more specific uses. Hence it is stated: "The affections of His love are infinite, and the perceptions of His wisdom are infinite; and of these, all and every thing that appears upon the earth are correspondences ... Such correspondences of His love and wisdom are in the whole natural world, ... but in ... the spiritual world there are similar correspondences with those who receive affections and perceptions from God."[227]

* * * * *

Creation - to the view of puny man - seems like a work of infinite patience. If we look at the record of the unhurried process of developing forms of life as it is impressed in the rocks of the globe, we must see that the stages of creation are counted not in days, but in millions of years. Yet we also observe a certain order - an ascent from lowly and imperfect forms of life by the addition of the more perfect. This ascending order is indicated even in the Mosaic account of creation. But in the Writings it is described as an ascent of uses, a progress looking always to Man, through whom creation might as it were meet its Creator and be conjoined to Him.[228]

The whole creative act may be seen to contain two phases, a descent and an ascent. The first substance of creation was finited more and more by descending into lower forms, or lower discrete degrees, where its action was generalized; and in nature the final imprisonment of the active forces of creation occurred in fixed matter, which is in itself dead. But the ascent began when forms of life were created. The fact that the commencing plant life and animal life represented very complicated structures, organic orders as it were freed from some of dead nature's forces, might make it appear as if the ascent lay in the perfecting of the forms which material substances assumed. But the truth is that the ascent lay, not in the physical constructions - for matter remains matter even if it is compounded - but in the uses which could be served through these perfected organisms. Such uses are indeed obvious in retrospect. The earth's energies are released for our use through the plants and animals of the past and the present; the ground has been stored with oils and coal; the air has been charged with gases proper for our purpose of life. Inmostly, every use of the lower kingdoms of life, as of the earth itself, prepares for the eternal uses attained through mankind.[229]

In the descending series or process of creation, perfection by degrees decreased. In the spiritual Sun, considered as the first and original substance of which all other finite things are composed, "there are infinitely more things," more potential varieties, and more "innumerable"
perfections, "than can appear in the substances that spring from it, which are called substantiates (or composites), and at length material."[230] The image of the Divine "becomes less and less apparent" in the successive formations.

But the reverse occurs in the progressive steps of organic creations. The lowest forms of vegetable and animal life manifest only a few general functions of life, and invite the influx only of the most external spiritual endeavors, which can be received in the kind of matters which are at hand. But when these simpler organisms have, by their living activity, and their cell-products, produced more complex organic chemicals in their little laboratories, then higher forms of life, with more complex organs and specialized uses, can be formed, and receive an influx of more varied spiritual endeavors, which guide their life as the soul guides a slumbering body.

We shall not here enter into the question as to the steps whereby the plant kingdom developed into its full perfection, and how the animal kingdom achieved its wide diversity of genera and species. Both these kingdoms "have the same origin, and thus the same soul," which is spiritual-natural affection.[231] Being from that spiritual which is operating within nature, these souls are not immortal, but "the influx passes through their organic forms out into the world, and there terminates and vanishes and never returns"; and because the spiritual - which cannot die -
is not appropriated, "the recipient forms ... cannot but be dissipated" and return to nature.[232]
There is indeed an image of immortality in their faculty to generate and reproduce their species. But the only lasting immortality lies in their uses - to mankind.

Here we may remark on the fact that while plants and animals have the same spiritual origin, the difference between them is due to "the forms into which the influx passes." Thus, in the spiritual world, the same natural affection, when it inflows into "intermediates," produces animals, but if it inflows into "ultimates," which are the lands there, it produces plants.[233] In the natural world, it is the same; but plants are subject more directly to the flow of atmospheric forces, and thus assume the form which the Writings name "the natural form," while animals retain "the spiritual form," from the conatus and flow of spiritual substances.[234]

If nature cannot as yet supply the materials for the formation of higher forms of life, only lowly orders of plants and animals can be created. Life acts into nature "according to induced changes of form."[235] Influx is according to reception. But this does not mean that nature acts upon life, or that the external accidental mutations of nature determine the development of life. For there are no purely accidental happenings in a universe created by God. The courses of the atoms and the clustering of stars, obey laws which to human eyes are indifferent to consequences, but which are, nonetheless, the tools of the Divine hand - governing from below as well as blessing from above.

And indeed, the matters are not what determine the quality of the life which shall inflow to form them into a bodily vessel. But it is the spiritual - the soul - which, by influx, selects the materials which are proper for its use, proper to clothe its particular purpose, express its specific varieties of endeavor.[236]

Such as this soul is, in degree and quality, such is the body, in essence and potentiality: yet how much of the potentialities of the soul is expressed through the body, depends on many qualifying factors, and also on the physical environment of the body, and its chemistry of nourishment.

The "soul" of vegetation and animal life is spiritual-natural affection. As the ages go on, the generations of organic species have enriched the earth more and more with varieties of natural substances, the by-products of life, which allow an increasingly greater variety of species to be formed; and thus are revealed the vast variety of the uses of natural affection, or, what is the same, the potential uses of natural and bodily life. Therefore we find animals of different degrees of perfection, but also intermediate types merging one into another, of inexhaustible variety, and always held in a biological balance which leaves room for these varieties to exist and for many species to survive.

Yet the lower kingdoms only represent the natural affection, instinct, or "appetite" which is their soul. Beasts are not able to understand their affections from which they act, as if in freedom yet without reason, nor to govern these affections, or to analyze them, or reverse them. They cannot reject the order of their life, and thus are not free to appropriate it as their own.[237]
Instead, when animals die, "the recipient forms of their life cannot but be dissipated; for with them the influx passes through their organic forms even into the world, and there terminates and vanishes and never returns."[238] In other words, the end of creation - which is that the spiritual might form itself in the natural - could not be accomplished through animals.

Neither animals nor plants can pervert the order into which they are born. Evil came with the hells, thus with men.[239] But the natural affections of evil spirits can and have become the pervert medium by which the earth may bring forth animals or plants which are obstacles to the uses of man, and thus hurtful and evil.[240]

It is strange that the reason why man could thus introduce evil even into the lower kingdoms is because he is created in the image and likeness of God - and because his soul, different from that of the beasts, is from the higher spiritual degrees.



---
~~~

== Human Beings - The End of Creation

"And God created man in His own image, in the image of God created He him; male and female created He them." - Genesis 1:27

"The end of the creation of the universe is people, in order that from people there may be an angelic heaven."[241] For so there may be "an eternal conjunction of the Creator with the created universe," which is not possible without subjects which are recipients of the Divine, so that they can - as of themselves - reciprocate His love.[242] All things created by the Lord are uses only "in that order, degree, and respect in which they look to man, and through man to the Lord."[243] All things "have been created for the use, for the benefit, and for the delight of men, some things more directly, some more remotely." And in serving people, they are of service to life itself, which is the Lord.[244]

When creation had proceeded from inmosts to ultimates, and the terraqueous globe had been endowed with vegetation and animal life, people were therefore created last of all, "and into them were collated all things of Divine order from firsts to lasts."[245] Their internal was a heaven in least form, and their external a world in least form, or a microcosm.[246] All the degrees of creation, spiritual and natural, contributed to their formation. They were created a recipient of all the three degrees of the natural world and of all the three degrees of the spiritual world.[247] From first creation, therefore, people contained within their make-up every substantial degree of created things, from that of the spiritual Sun to that of lowest matter. In their bodies were represented the uses of all things; the mineral deposits were effigied in their bone-structures, the vegetative functions in their hair and cell-growth, the animal passions in their natural constitution. In their rational mind, the degrees of all the heavens were present as planes of possible development.

In this they were different from the animals, in whose bodies not even all the natural degrees are substantially represented and whose souls derive their origin only from the "ultimate spiritual degree."[248]

This fundamental inner difference is important to note, in view of the fact that as to their body people may be called "animal," and as such may be classed as belonging on the "highest" peak of the animal kingdom.[249] In a sense, " For the human being is born an animal, but becomes human, "[250] which no brute animal can ever become. And the root of the difference lies in the person’s soul which is present in the paternal seed. It is the soul which determines the powers, the faculties, for progress and development.[251] The soul gives "essence."[252] And thus -
whatever superficial likeness there may be between the life of people and beasts - the whole of a person is such as his or her sou1.[253] "The soul clothes itself with a body as a person garbs themselves with raiment."[254] "It as it were creates or effigies a body in the image of itself ... and is consequently the all in the body."[255] "Everything of the body is produced from the soul, thus to a resemblance of it."[256] Indeed, "a person begins from the soul which is the very essence of the seed and thus not only initiates, but also produces in their order the things of the body."[257] The soul in the seed continually "aspires" to the human form, from the conatus of its own substance."' It is generally known that sex is determined by the male sperm and that every cell of a male body is male in its actual structure, while every cell of woman is female. "The material form that is added and superinduced in the world, is not a human form from itself," but from the soul, or spiritual. And it is added to the spiritual "so that a person might do uses in the natural world, and also draw to themselves out of the purer substances of the world a certain fixed containant of spiritual things, and thus continue and perpetuate life."[259]

Before we inquire into the creation of people, it is well to have a somewhat fuller idea of a person’s soul. Little, if anything, is known of the soul except what is taught in the Writings. "People have become so external as to be unwilling to acknowledge anything except the natural
... It has become distasteful to them to elevate their thought above the natural to something spiritual separate from the natural; therefore, in accord with their natural love and its delights, they can think of the spiritual only as of a purer natural ... Yea, the merely natural man cannot think of anything separate from the natural; any such thing to him is nothing."[260] Some of the learned thus "believe that the soul is a particle or drop of ether, some that it is a ball or spark of heat and light, some that it is some entity which hides itself in the brain. But whichever to them is the soul, they indeed call it spiritual, yet by spiritual they understand a purer natural ... wherefore they remain within the sphere of nature, and in it ascend and descend ..."[261]

Over against these fallacies we have the doctrine of the Writings that the soul - using the term in a general sense - is a vessel receptive of life, and is the same as the spirit or the mind, which is the after-death person. It also is finite, created from "the spiritual substances which are in the spiritual world."[262] It is "the inmost person," and is therefore "fully and perfectly the human form,"[263] as indeed is seen in the spiritual world. It is not only the inmost of the head, but is in the whole and in every part of the body, and indeed intimately adjoined to every fibril.[264]

The soul is thus to be regarded as a "spiritual substance which has not extension."[265] And as so defined it embraces all that is spiritual in people. As such it can propagate itself in the seed, retaining all the conatus of the spiritual, all the confirmed qualities of the mind of the father.[266]
"The entire soul forms itself, and clothes itself, and becomes seed."[265]

In this wider sense, the "soul" embraces the three degrees of the spiritual world, present as to quality and conatus. Therefore we read that "in every person from their birth there are three degrees of height ... one above or within the other"; and also, that "there are in people a natural, a spiritual, and a celestial will and understanding, in potency from birth, and in actuality when they are opened."[267] We take this to mean that the substantial basis - the spiritual substances - of these degrees are involved and present from the first in the soul: as a basis for developing a natural mind, a spiritual mind, and a celestial mind,[268] all for the conscious use of man in this life and in the spiritual world; the natural mind in this life, the others after death.

Yet when human beings - as a soul - enters the other life, they possess not only these three mental degrees; but, as a spirit, they are complete people, and have a body, albeit a spiritual one, a mind, which answers for all purposes to the natural mind they consciously used on earth, and an inmost which "lacks a name" since it is beyond their ken or control.[269] This unconscious inmost - the first vessel by which they receive life, and which is the abiding place of the Lord with them[270] - is sometimes separated in idea from the mind, and is then, by itself, called "the soul." The inmost, or soul, is thus distinguished as "a superior spiritual substance"
which "receives influx immediately from God"; while the mind, because it is "a lower spiritual substance," receives influx from God mediately through the spiritual world.[271] Of the supreme soul it is said that it belongs to the Lord alone. "The very heaven that is nearest the Lord is composed of these human internals; but this is above even the inmost angelic heaven."[272]

It is this "inmost" of the spirit which makes people human, and makes their minds different from the beasts; so that people can enjoy a spiritual mind which can receive celestial and spiritual things from the Lord; and so can have - as a gift from the Lord - the faculties of rationality and spiritual freedom. And because of it human beings are also enabled - in their natural mind - to think analytically and look into their own natural affections and rule them. For people are "given dominion over the fish of the sea and over the fowl of the air and over every living thing that moveth upon the earth" - i.e., their own earth, the natural mind; and this in order that they may "multiply and replenish the earth and subdue it." By doing this they becomes human.

* * * * *

The spiritual cause and formative principle in the creation of people upon earth, was the soul, a soul embracing all the spiritual degrees. Yet the soul does not create, but the Lord alone creates both soul and body.

A body, formed dust of the ground, is also necessary. A person or angel cannot be created immediately into the spiritual world, but must be born on an earth. The reasons are many, but the chief reason is that spiritual substances are not in themselves constant, but vanish when their active cause ceases: "it would have been similar with the angels if they had been created there" - that is, in the spiritual world.[273] Therefore the earth had to be formed, and furnished from the lower kingdoms with the matters from which the body of human beings could be built, before the "first person" could be created. The body was to be the means by which the human soul could act in the various degrees of the material universe. The soul borrows, from nature, the matters whereby to express and infill its own form. And nature - in whole and in every part -
was created such that it might perform this use. It is therefore no contradiction to say that a person’s body is created to conform to the natural world, or, in particular, that the senses of a person’s body are formed "in correspondence to the elements" of nature; since the atmospheres are such as they are, to the end that they should form the senses.[274] The ear is formed to the nature of the air and its modifications of sound, the eye to the modifications of the ether of light; and the interior organics of the brain are formed to the highest ether, which enables the natural mind to develop.[275] Nor could anything of the body be held together except by the pressure of these atmospheres; the higher atmospheres hold the inmosts of the body in their forms.[276]

Yet this is not sufficient. The atmospheres do not have any power to create a human body; although it is "an essential of atmosphere" to promote the clothing of form.[277] The form itself of the body must have its cause; and while this may be said to be the soul, yet the soul is a vessel not only acting from the life of God within, but also formed by its unison with spiritual forces external to itself. We therefore find the teaching that "the human body is entirely formed from the Greatest Human."[278]

This is explained to mean that peoples’ bodies, and every organ, tissue, and function of them, correspond to the Greatest Human of the heavens, and could neither subsist nor operate except by continual influxes of life from the Lord mediately by the Greatest Human and its various provinces.[279] For all human uses represented in the heavens must as it were modify the form of the human body, and contribute to its perfect balance.[280] Thus the body of man must be formed, and "exist," "from something general or universal, thus from the Greatest Human."[281]

But granting that the body of man is thus formed and sustained by influxes through that "Greatest Body" of the angelic heavens, and that it is the endeavors of that universal body of uses that express themselves - when power and occasion are offered - into the active forces that build the body of each person; how then could the first person have come into being, before there was such a Greatest Human? Swedenborg confides that this tender scruple occurred to him. He was given an answer by a "spiritual idea." This was, that the Lord is the final source of all those endeavors which arise in the single things of the Greatest Human: the human race was of Him from the beginning, wherefore He has all care for them. "The first person, and those born at first, have not been led by any other than the Lord alone." And it was explained, that "human beings, as to all their degrees, existed before his nativity as after it."[282] All of human life thus was involved in the spiritual degrees, from the beginning.

* * * * *

The actual mode of human beings’ creation is not taught in the Writings. And indeed, it seems unwise to explore with too irreverent a curiosity into all the secrets of the Lord's workshop. Man was formed, dust of the ground, and into his nostrils the Lord God breathed the breath of lives, and man became a living soul. The letter of Genesis thus conveys the picture of an instantaneous creation by a Divine fiat. But before his final call, Swedenborg, in his prose-poem The Worship and Love of God, suggests that the Lord's omnipotence is in no way impugned by the possibility that He might have used means and methods in creating the kingdoms of organic life.[283] The vegetable kingdom might thus have been the means of gathering the rich products of the soil that were needed for the creation of animals, and the first of each animal species might have been born as the first-fruit of a corresponding plant. And if so - since peoples’ bodies are of similar nature as that of an animal - could not the first Adam and Eve have been born as the fruit of a "tree of life," in a literal sense?[284]

The Writings seem nowhere to sustain this picture. Yet there are universal truths which suggest that man is indeed the crowning fruit of a "tree of life" - not necessarily vegetable nor indeed animal - but a genetic tree which was human from the start and which developed during untold ages from a human seed and a human soul, to form eventually a body which could cradle a mind conscious of God as its Maker and able to assume the responsibilities of immortality. Whether the doctrinal concept of the "preadamite" ancestor of man should be extended into the concept of such an evolving form is in the realm of speculation. Yet howsoever mankind arose, it must have had its own history, long or short, even as every individual child has a hidden fetal development from conception to birth. The laws of this first creation could not be contradictory to the laws revealed concerning the gestation and birth of every person.

Certain things said in the doctrine seem however to indicate the general state of those human beings who are first referred to in the story of the spiritual development of mankind, as recorded in the book of Creation. The idea that Adam and his wife were the first individual people - and were created perfect, is rejected in the Writings. ‘Adam' was not an individual but the personification of a most ancient primitive church of celestial type. And there were "Preadamites," whose spiritual development is what is described in the internal historical sense of the ‘six days' of creation. These people at first "lived like wild animals (ferae) but at length became spiritual."[285] Their mind, as it was at first, is described as an earth, void and empty, shrouded in thick darkness, an abyss of waters over which hovered the spirit of God's mercy. The creation which followed was a spiritual creation, a gradual awakening of people’s faculties, a revelation of some of the countless possibilities and powers for use and delight that are hidden in the soul and in the substances of his spiritual degrees, from their origin in the spiritual Sun! It was a creation of spiritual things which people accept freely from the Lord and which contain interior possibilities, ever fresh, of which they never dreamt. Only by the aid of sensation and knowledge coming through nature, could human beings ever become aware of these spiritual things. Even after death, when the senses of the natural body have been closed and removed, and the natural memory with its concepts of space and time has been laid to sleep, a person still has his mental life - their reception of wisdom and love from the Lord - based, directly or indirectly, on the material ideas of living people, which are indeed the common basis for all the heavens;286 although only spiritual ideas are entertained by the angels.

Another phase of this same truth - that the spiritual takes form in the natural - is also important.

The general teaching is that "man is born spiritual as to the soul, and is clothed with a natural which constitutes his material body; wherefore, when this is put off, his soul, clothed with a spiritual body, comes into a world where all things are spiritual." "The spiritual body is to be formed in the material body, and is formed through the truths and goods which flow in from the spiritual world and are received by man inwardly in such things of him as are from the natural world, which are called civil and moral."[287]

Everyone therefore "has their soul from the life of the body formed by themselves";[288] which means, of course, that a person’s natural mind is so formed. The order of his or her ruling love, as they have formed it, is indelibly inscribed in all the twists and connections of their corporeal memory; and this - in turn - is held unchangeable by the inmost or purest things of nature, which are organized as a fixed containant called a "limbus," or "medium."[289]

What is seen in the spiritual world as an angel or spirit, is the spiritual body, which is in the actual form of the ruling love. This body, and within it the mind, is the spiritual as he formed it within the natural. It is the character of a person, the spirit, organized - as you note[290] - not from anything physical, but through truths and goods which had inflowed from the spiritual world with his consent. It is indeed a spiritual creation, but permanent as to all essentials, because formed in the natural and having "a relativity (relativum) to those things which are in nature, and also a correspondence to them."[291]

The spiritual body is permanent, and a form of the ruling love. From examining the body of a spirit, exploring angels can reconstruct his past life![292] Yet a spirit or an angel undergoes changes of state; some flow from the development of their own love; others arise when they determines their mind to uses of various kinds and degrees; still others are occasioned by contacts with other spirits, or with people with whom these spirits are associated.[293] These changes of state are principally those of thoughts and affections, and pertain to his mind. But every spiritual thing is in the conatus to act, to create, to form! And as the substance of the other world is spiritual, all effects there are spiritual: each new state of mind is a new manifestation of the Lord's creative power out of the living substance of that world, and a new realization on the part of an angel or spirit of spiritual productions. This is the sole origin of the productions or creations which occur around the angels, and angels well know that nothing about them is material, but that everything is an expression or mirror-image of a human state! and this as a new creation from the human and living substance of that world.

* * * * *

Concerning such spiritual creations - houses as well as paradises - Swedenborg testifies:

"Like other men, I wondered that such things exist in the other world, since it is contrary to the
[common] conception of the life of spirits... . Everything which exists in the other life is not, as some suppose, empty and void, but is the substantial itself which is the origin of all the substantial things in nature; a living substantial is there, or a purest ethereal. This is formed by the Lord into such things as are so marvelous that they can hardly be described. It is enough that I have seen them, and frequently; I have been there; I have spoken with [the angels]; and they have said that those things are real while the things on earth are comparatively dead things, which they disdain. 1749, June 2."[294]

As shown above, the Writings repeatedly testify that "as to internal face" (or as to essence) the two worlds are altogether dissimilar.[295] The phenomena in each are the same, but they follow different laws. Thus "it should be known that in external appearance the spiritual world is exactly similar to the natural world. Lands appear there, and mountains, hills, valleys, plains, fields, lakes, rivers, springs of water - just as in the natural world; thus all things belonging to the mineral kingdom. There appear also paradises, gardens, groves, woods, and in them trees and shrubs of every kind with fruits and seeds; as well as plants, flowers, herbs, and grasses; thus all things of the vegetable kingdom. There appear animals, birds, and fishes of every kind; thus all things which are of the animal kingdom. Human beings are there as angels or spirits. This is premised that it may be known that the whole of the spiritual world is altogether similar to the whole of the natural world, with this sole difference that the things which are there are not fixed and set as those in the natural world, because in the spiritual world nothing is natural but everything is spiritual.

"That the whole of that world represents human beings in an image can be clearly manifest from this, that all the things just mentioned ... appear to the life and have existence about an angel and about angelic societies as if produced or created from them: they remain around them and do not recede. That they are as if produced or created from them is shown from this that when the angel goes away or when a society moves elsewhere, they no longer appear; as also, when other angels come to their place, that the appearance of all things about them is altered. In the parks the trees and fruits are changed, in the flower gardens the flowers and seeds, in the fields the herbs and grasses, and even the kinds of animals and birds are changed. Such things have existence and are so changed because all these things have come into existence according to the affections and thence the thoughts of the angels; for they are correspondences. And because things which correspond make one with that to which they correspond, they are a representative image of it. This image is not seen when all these things are viewed in respect to their forms, but they are seen when they are viewed as to their uses. It was given me to see that the angels, when their eyes were opened by the Lord, and they saw these things from the correspondence of the uses, recognized and saw themselves in them."[296]

We are given direct instruction as to the production of objective creations in the other life. The immaterial sphere which wells forth spontaneously from the life's love of an angel is directed by his interior memory, which is his conscious and rational plane of life.[297] This sphere calls forth the appearances corresponding to its state.[298] Indeed, a spirit's sphere is even said to be changed into the representative creation outside of him. Yet the sphere by itself could not effect this. For the common spiritual ultimates - or the lands on which all the spirits of his society live -
are needed as the womb out of which the representatives arise. "Nothing of the vegetation of that world comes from seed sown but only from seed created" - for it is produced from the ultimates there instantaneously, and of course without the assistance of nature.[299]

Before there were any angels to populate the heavens, the spiritual world was complete as to all substances and degrees. It had a spiritual Sun and three atmospheres as well as the substantial spiritual ultimates of each of these atmospheres. Potentially, these atmospheres (by which the Divine of use is represented) contained all the unborn uses and unseen creations which the angels of the unending future were to participate in consciously and experience objectively.

But the creative power of the Lord could not produce any spiritual objects, except by the spheres of spirits and angels. For the visible spiritual world is a world of reception. None of its original substances or progressive degrees, from the spiritual Sun down to its ultimate, can be thought of as fixed or constant, since, being spiritual, they are beyond the concept of time. The human mind - even while picturing them in natural fashion - must admit them to be the perpetual outflow of the Divine love and wisdom in accommodated finite forms. Only by reception in the minds of human beings can they reveal themselves to spiritual sight, or be apprehended as to their quality, or become constant forms of uses. Only through reception in terms of the ultimate order of the natural creation can there be formed states which are constant relative to each other - states which enable our spirits to live eternally upon secure spiritual foundations which are more real than those we leave behind at death. The spiritual creations which surround the angels reveal more and more the countless varieties and unending propagations of which the spiritual, proceeding from the Lord, is capable.

But the Lord alone is infinite. He alone sees in the heavens, in the Greatest Human of spiritual uses, an infinite end. His glorified Human is the pattern of an infinite heaven.[300] For every angelic use is but a tiny bit of the pattern, and every representative creation of heaven is but a partial unfolding of His purpose. Yet in His view the end of His creation stands forth as "an infinite and eternal creation.[301]

It is through human beings that uses ascend, through discrete degrees, and return to God. Yet, "No man hath ascended up to heaven, but He that came down from heaven, even the Son of Man who is in heaven" (John 3:13). Only in the Lord, who assumed flesh for our salvation, could the inmost and infinite end in creation as it were ascend back to the infinite source. In the Lord incarnate the infinite meaning and use of all creation, natural and spiritual, was realized and embodied. His Divine, which makes heaven, is now revealed in His glorified Human as the infinite Soul of all the forms of created life. In the threefold Word of Law, Gospel, and Doctrine His qualities of provident wisdom and mercy are revealed and accommodated to each degree of the human mind, so that we may, in every state, be able to see His features and His laws in the universe which He has made, and by conjunction with Him, allow the end of creation to be fulfilled in human life.



---
~~~

== Abbreviations

All the paragraphs in Swedenborg's Writings are numbered.  The typical citation of the Writings, then, consists of the initials, from the list below, indicating the title, followed by the paragraph number.  Thus, for instance, AC 771 refers to Arcana Coelestia, paragraph 771.

AC - Arcana Coelestia (1749-1756)
AE - Apocalypse Explained AR - Apocalypse Revealed (1766)
Ath. - Athanasian Creed BE - Brief Exposition (1769)
Can. - Canons Char. - Doctrine of Charity CL - Conjugial Love (1768)
CLJ - Continuation of The Last Judgment (1763)
Conv. Ang. - Conversations with Angels Coro. - Coronis to TCR De Conj. - On Marriage (posth.)
De Ver. - The Word from Experience DLW - Divine Love and Wisdom (1763)
Docu. - Tafel's "Documents"
DP - Divine Providence (1764)
Ecc. Hist. - Ecclestiastical History of the New Church EU - Earths -in the Universe (1758)
F - Doctrine of Faith (1763)
5 Mem. - Five Memorable Relations HD - New Jerusalem and Its Heavenly Doctrine (1758)
HH - Heaven and Hell (1758)
ISB - Intercourse of Soul and Body (1769)
Inv. - Invitation to the New Church LJ - The Last Judgment (1758)
LJ post. - Last Judgment and the Spiritual World (posth.)
Life - Doctrine of Life (1763)
Lord - Doctrine of the Lord (1763)
Love - On the Divine Love SD - The Spiritual Diary SD min. - The Spiritual Diary Minor SS - Doctrine of the Sacred Scripture (1763)
TCR - The True Christian Religion (1771)
WE - The Word Explained (Adversaria)

WH - Concerning the "White Horse" (1758)
Wis. - On the Divine Wisdom



---
~~~

== Footnotes

1 AC 6879

1a. Many statements to this effect may be found in "The History of Creation according to Moses," in "The Word Explained," nos. 1-27, and in certain early tracts such as "The Motion and Position of the Earth and the Planets."

2 AC 8891

3 Div. Wis. xii. 2

4 AC 3533e

5 DP 51, 48, AE 1130:3, 1131:2, TCR 29, 27 6TCR 31 8DLW 155 7TCR 30

6 TCR 31

7 TCR 30

8 DLW 155

9 Div. Wis. xii

10 DP 51

11 TCR 31, CL 328, AC 3404:2, SD 3476, 3457, 3482, DLW 156, AE 23

12 DLW 28

13 DLW 18

14 DLW 17

16 TCR 43

15 DLW 47

17 DLW 49

18 DLW 52, 53

19 DLW 283, 55

20 DLW 283

21 "The Infinite and the Final Cause of Creation," Part One, concluding sentences. Wilkinson's translation (1847), pages 88-89.

22 TCR 76

23 DLW 154

24 Canons, God, iv. 7

25 ISB 9

26 AE 1207:3

27 TCR 280:8

28 TCR 33

29 TCR 75

30 Div. Wis. xii. e

31 Ibid.

32 DLW 97, EU 40

33 AE 121, AR 938, 465

34 DLW 152

35 TCR 33:2, DP 5, 6

36 DLW 291

37 Compare AE 726:4

38 DP 219

39 AC 5272

40 AC 8200e

41 Ath. Cr. 191

42 TCR 29

43 DLW 294

44 DLW 290ff, AC 10130:2

45 DLW 294

46 AC 10130:2

47 Canons, God, iv

48 CLJ 38, DLW 89f, 164, 353e, AC 5079e, 5084:2, CL 415:3, 6, AE 1208:2, etc.

49 DLW 158, 175, AE 1209:3

50 DLW 157

51 DLW 300

52 DP 6

53 Div. Wis. xii. 3:2

54 TCR 35:11

55 ISB 5

56 DLW 155, 300:2, DP 6, AC 6232:3, SD 1713f

57 Compare TCR 20, LJ post. 263

58 DP 6

59 SD 3484

60 DLW 155, 300

61 CL 220

62 AR 31, DLW 53, SD min. 4609

63 Div. Wis. xii. 4:2

64 AC 6232

65 AC 1590e

66 DP 6

67 AC 6232:3

67a AC 3702|

68 DLW 155, DP

69 Ath. Cr. 190, Div. Love, iii.

70 AE 412:16; compare HH 120

71 AC 7173

72 TCR 365:2

73 AC 7270

74 Compare AC 8443

75 Schure, Pythagoras, London 1923, page 101; Ang. Id

76 2 Econ. 251, WLG 25 note.

77 Ibid. 260. Note that this is a comparison or "correspondence," and does not identify the Spirit of God with the "celestial aura" of nature, which the Economy described as "inanimate." (Ibid. 199.)

78 AE 726:ii.

79 DLW 299

80 AC 9498f

81 AC 9534

82 AC 9499

83 AC 9502

84 AE 726:ii

85 Ath. Cr. 191

86 TCR 76

87 TCR 33

88 TCR 76

89 For the full text, see the Standard Edition of "Apocalypse Explained," vol. vi, pp. 473-475.

90 TCR 76; compare LJ post. 313. The latter passage explains that the spiritual atmospheres, "properly speaking, are not three but six - three above the sun of the world and three below it. The three below the sun of the world follow the natural atmospheres constantly (jugiter) and enable a man in the world to think and feel.

91 AE 1211:4, TCR 33, 76

92 AE 726:ii

93 DLW 174

94 CL 220

95 DLW 257, DP 319, 279

96 TCR 470

97 Div. Wis. xii. 5

98 SD 4293

99 Coro. 17:2, LJ post. 313, DLW 175

100 Div. Wis. xii. 5

101 Ang. Idea of Creation.

102 TCR 32:8

103 TCR 76

104 Coro. 17:2

105 DLW 176

106 Div. Wis. xii. 5:2

107 DLW 302

108 AE 1212:2

109 AE 1211

110 TCR 76

111 AC 6055f, 5114:3, 5146:2, 6326, 3691

112 LJ post. 322

113 AE 1196:2

114 LJ 9, DLW 167, AE 1218:2, 3

115 AE 1207:4

116 DLW 315, etc.

117 DLW 156

118 Div. Wis. viii. 3

119 Coro . 19

120 DLW 154

121 TCR 31, 29

122 TCR 76

123 HH 106, 107

124 TCR 35:8

125 DLW 164

126 ISB 9

127 CL 380:12

128 DLW 157

129 DLW 89, 90, 164, CL 415:3, AC 5084:2

130 DLW 158, 175, 353e, AE 1209:3

131 DLW 157

132 CL 235:2, TCR 75, 44:2, AE 1206e, Div. Wis. xii. 1, DLW 93e, 166, 153;5 Mem. 17

133 SD 2757

134 DLW 158, 175, CL 320

135 LJ post. 313

136 DLW 157

137 AE 1209e

138 DLW 302

139 Div. Wis. viii. 2

140 CL 311:2

141 Div. Wis. viii. 2

142 AE 1219:5

143 Fragment from Codex 13, translated in Standard Edition of AE, vol. VI, p. 475.

144 AE 1210e

145 TCR 280:8, CL 320, 328

146 TCR 79

147 CL 320

148 DLW 83, 84, 353, 90

149 AE 1206:2

150 DLW 306

151 TCR 280:8

152 AE 1218e

153 DLW 229, compare AC 5084:4, LJ post. 263

154 ISB 17:2

157 CL 329

155 DP 6

158 TCR 20

156 DP 6

159 SD 2070

160 AC 8911

161 AC 3748e

162 AC 5173

163 AC 5116:2

164 AE 1206e

165 DLW 310

166 AC 8911

167 AC 8911. DLW 311. (Compare the Latin text and context.) DLW 218f, Coro. 30e, AE

1209:4, cp. WE 989

168 DLW 163, cp. 83

169 DLW 164

170 DLW 164, 165

171 DLW 166

172 TCR 35

173 AE 726, ii

174 TCR 32:8, 76, Coro. 17:2, LJ post. 312f, ISB 16:3, DLW 176, 191, 302; AE 726, ii; cp. SD 222, 418. In DLW 174 the atmospheres are described as "discreted substances and least forms" which singly receive the sun's heat and temper it.

175 Coro. 17:2

176 DLW 173

177 DLW 178

178 AC 5084:3. Compare DLW 81, 82, LJ post. 265

179 LJ post. 312

180 TCR 32:8

181 DLW 302

182 AE 1207:3, 1209:4

183 DLW 178

184 AE 1206:3. The relation of the natural atmospheres to the spiritual may be seen from DLW 175, TCR 76:3, LJ post. 313. Cp. CL 235.

185 Light and heat are said to be "uncreate," since they are only the activities or states of various receptive media such as atmospheres or other substances. See TCR 472, 40

186 AE 1206:4

187 DLW 184

188 TCR 76

189 Written about 1729, but never published by the author.

190 TCR 75e

191 WLG 15

192 WLG 22, note o

193 WLG 25, author's footnote.

194 AE 1208

195 LJ 9

196 DLW 310, 330

197 DLW 172

198 DLW 311

199 AE 1206e, DP 12. Compare the statement that earthly things "are not changed except according to the laws of natural order." (LJ post. 313.)

200 AE 1146:5

201 TCR 35:8, DLW 88, 341

202 DLW 310

203 This makes regeneration possible, in that natural affections can be dominated by a spiritual and rational end, and eventually be altered in quality.

204 DLW 312

205 DLW 65

206 DLW 61, 62, AE 1208:5

207 DLW 310

208 DLW 340

209 AC 5173e, DLW 315, 344

210 DLW 340, 344

211 Div. Wis. viii. 3

212 DLW 343

213 DLW 344

214 AE 1210, 1209

215 Ath. Cr. 26, 178

216 TCR 470, 499, DLW 310

217 DLW 310

218 AC 4223, 4926

219 AE 1210

220 AE 1201

221 AE 1210

222 DLW 270

223 DLW 257

224 LJ post. 313

225 DLW 346

226 AE 1210-1212

227 TCR 78

228 Div. Love, viii

229 Div. Love, viii, DLW 327

230 DP 6

231 AE 1212

232 AC 5114e

233 Confer AE 1212

234 AE 1208

235 DLW 166

236 Div. Wis. ii. 4

237 Div. Wis. iii. 4:3

238 AC 5114:5. Animal or plant souls are perpetuated as a species through the germ-plasm. But no surviving individual "limbus" is formed and retained, as with man. The life in their inmosts, which are natural, "relapses into nature." (See Div. Wis. viii. 2, 3, 4, 5.)

239 TCR 78

240 DLW 345, 339, 343

241 AC 9441

242 DLW 170

243 DLW 327

244 Div. Wis. xiii. 4

245 LJ 9

246 AC 6057, TCR 71

247 DLW 66

248 DLW 65, 66, 346

249 DLW 65. The term "animal" was sometimes used by Swedenborg to denote a being with a soul (anima). Thus his studies in human physiology and psychology which he undertook in search of the soul's operations in the body, were entitled "The Animal Kingdom," more properly translated as "The Soul's Kingdom."

250 DLW 270

251 Compare WE 643, 919

252 AC 5689e

253 AC 10076

254 ISB 12

255 AC 4727

256 AC 10125:2

257 TCR 166

258 WE 1457, AC 3633, DLW 388, 432

259 DLW 388

260 DLW 374

261 TCR 695

262 TCR 470, 103 263CL 315:11

264 Inv. 13, 48, CL 178, Div. Wis. vii. 2, 4

265 CL 220

266 CL 172

267 DLW 236, 239; compare 67, 245

268 DLW 239, 432

269 SD 4627:3, cp. 5548

270 HH 39, 435, LJ 25:5, 6

271 ISB 8

272 AC 1999:3, 4

273 Div. Wis. viii. 3

274 SD 4083-4086, 4066, AC 4523, 3628275 AC 6013, 6057, 3702:2; cp. DLW 17

276 SD 4063, etc.

277 Ath. Cr. 26, 178

278 SD 3148, 1708ff

279 SD 4064, 4065

280 SD 1708ff

281 SD 3972

282 SD 2591

283 He defends this idea in his manuscript on "The History of Creation as given by Moses," written in October the same year, 1745. (See Hist. Cr. 14, 21.)

284 WLG 29-38

285 AC 286, cp. SD 3390, TCR 466

286 LJ 9, SD 5187, 5607ff

287 TCR 583

288 SD 2794

289 TCR 103, DLW 257, Div. Wis. viii. 5, DP 220:2, 3

290 TCR 583

291 Div. Wis. viii. 4

292 HH 463

293 SD 5092

294 SD 4293

295 DLW 163

296 DLW 321, 322

297 AC 10130:2, 2489

298 AE 65, 342:10

299 AE 1211

300 SD 4845

301 DP 202, 203

