= The Story of Creation in Genesis
Pitcairn
include::../../template-attributes.adoc[]

The Story of Creation in Genesis 

By Theodore Pitcairn 

 
 
 
From: A SERIES OF LECTURES  
by Rev. Theodore Pitcairn 

Published by 
Nova Domini Ecclesia Quae Est Nova Hierosolyma  
The Lord's New Church Which Is Nova Hierosolyma 
Bryn Athyn, Pennsylvania  


---
~~~

== The First Day 

The understanding of truth by the enlightenment of the human mind. The creation of the World 
of mind and its relation to the world of matter. 

Every study which one undertakes involves not only new ideas, but also new words, in a sense 
a new vocabulary appropriate to the subject. Therefore, if we are to enter more profoundly into 
the things of religion, we, of necessity, have to master new ideas, and acquire an appropriate 
usage of words, which to a degree departs in meaning from the same words as used in 
common speech. In regard to the subject which we will consider, the difficulties of 
understanding it are not so great as is the case in many technical subjects which the man of 
medium intelligence readily masters if he is interested in the subject. But when it comes to 
religion many expect to arrive at essential things without the kind of effort that they would put 
into the study of some other subject. Yet everything worthwhile requires effort; apart from effort 
a subject soon grows flat and stale. The kingdom of God is not for the mentally lazy. 

The reason that few are willing to spend the energy required in acquiring a knowledge of religion 
that they would readily spend on other subjects is that their love is weak. While the things of this 
world grip their interest, the things of eternal life do not grip them sufficiently, wherefore on 
encountering the first difficulty, they give up. 

One seeking truth wishes a calm presentation, and not a highly emotional or oratorical 
presentation which deprives the mind of the quietness of mood necessary for an unbiased 
judgment. Religious talks often arouse the emotions to such an extent that one can not see 
whether what is said is true or not. 

The object of these lectures is not to persuade, but to present certain things for your calm 
consideration. 

In this country most persons believe in a God, that is, they are theists and  not atheists; but 
generally speaking, the idea of God is decidedly vague, and there  are many shades of opinion 
varying from those who hold to the strict traditions of  our grandparents to the scientist who finds 
an unknown force or intelligence behind  the natural phenomena with which he deals and which 
he calls God. 

Even in the churches the idea of God with the great majority has become somewhat vague. 
There are few who accept the Bible in the same way as our forefathers did. 

Our idea and thence thought of God may be based on three types of approach to the subject: 

 
 
 
 
 
 
 
 
 
● First, the approach through a written revelation: with the Christians through what is 

called the Bible. This is sometimes called the historical approach. 

● Second, the approach through the objective world. This approach may be divided into 

two kinds: the approach of the scientist who as it were sees God behind the order of the 
universe, or as the active force within the atom; and the approach of the artistically 
inclined who see God behind the harmony of creation. 

● Third, the approach through the subjective world of mind. These feel the presence of 

God as inspiration from within, as the source of love and wisdom. 

With those who believe in God there is generally some thing of all these methods of approach 
and each has its place; but in the world such as it is at this day, the scientific approach tends to 
dominate and take a place of importance beyond its due. 

The reason for this is that men have fallen into an intensive pursuit of material ends. They have 
been overcome by an all-pervading desire to satisfy first their material wants at the expense of 
all else. This pursuit has concentrated the thought on science as the means to this goal with the 
result that the thought of God has become largely a scientific idea of God. 

Science with the exception of psychology deals with the objective world, and even psychology is 
based largely on objective experiments, which can be scientifically demonstrated on the plane 
of physical sensation. 

To form our ideas according to the objective world, the world around us, is the easiest course, 
the course requiring the least reflection. 

A child, if it were not pointed out to him, would have considerable knowledge of his surroundings 
before he realized that he had an eye that sees; and when he knows he has an eye he still 
cannot see his own eye. After growing older a child has a far more extensive knowledge of his 
environment before he comes to realize that he has a mind which is the means of his being 
conscious of the world; and even when he grows up, it is hard for him to realize that the actual 
consciousness of the world around us is within us and not as it appears outside of us, for we 
appear to see a tree at a distance and are not aware that the sensation is in the eye. 

The tendency is to carry something of this childish attitude over into adult life, with the result that 
the world of material things around us seems to us more real than the world of mind. 

It also appears as if the mind were formed and received its activity from the sensations which 
come to it from the outer world; but that this is a fallacy can be seen from the fact that a more 
internal activity cannot be caused by a lower type of activity. This may be seen illustrated by the 
following example: 

● If a soft iron bar is held in a north and south direction and hammered while so held, it 
becomes magnetized, that is, it becomes a magnet. The reason for this is that all iron 
consists of magnetic particles. These particles are normally facing in every direction, so 

 
 
 
 
 
 
 
that they neutralize each other; but when the bar is hammered, the earth's magnetic field 
brings these particles into alignment with the result that the bar becomes what is called 
magnetized. The appearance is that the hammering gave to the bar its magnetic force, 
but the truth is that the hammering merely permitted the magnetic particles so to arrange 
themselves that their force becomes evident to us. 

● Another illustration is the electric generator. The turning of the wheels appears to be the 
source of the electricity, whereas in reality the turning of the wheels so arranges the 
electrical particles in which the electrical force resides, that the force may be felt and 
used. 

The same is true of the mind. The sensations from the outer world impinging upon the brain do 
not cause mental activity such as thoughts, affections, things of love and wisdom, but 
sensations are the means of the things of the mind so arranging themselves that we become 
conscious of our mind. The case is analogous to the hammer on the iron bar, where the 
hammering was not the cause of the magnet, but merely the means of the magnetic force, 
intrinsically present in the particles of the iron, manifesting its activity as magnetic force. 

The highest form of activity we know is mental activity, the activity of affection, thought, love and 
wisdom, things of which we are subjectively conscious, if we reflect upon them. 

It is obvious that the most appropriate thought concerning God is thought which primarily is 
based on the highest activity we can become aware of, that is, the activity of the human things 
of love and wisdom, and secondarily on the creation of the objective world of matter with its 
various forms of activity. In a word, that the primary thought of God be a Divinely Human idea, 
and not primarily a scientific non-human idea; that we think of God as Divine Love and Wisdom 
and, being such, that he is primarily the origin of mind, and thence of the material world; and 
that we view the world of matter as the means by which the world of mind manifests itself. 

All people have viewed God as being in a human form. This concept was first brought into 
question by one of the ancient Greek philosophers, who said that if cows were able to portray 
their gods, they would portray them as cows, etc. This line of thought led to the disparagement 
of what is called the anthropomorphic idea of God, the idea of God in the form of man. In the 
Genesis account of creation it is said that God created man in His image and likeness; and if we 
see that man is primarily man from the form of his mind, and only secondarily from the form of 
his body, and see the body as a manifestation of the soul on a lower plane, we can see that the 
idea of God as a Divine Man is the highest concept possible to man, and the only one which is 
truly appropriate. God is indeed infinitely more than man, but it is only by means of a Divine 
Human idea, that we can have any appropriate idea of Him, and thus be conjoined to Him by 
love. 

We indeed do not think of God as being spatial, as being a spatial figure seated somewhere in 
the universe, but if we see Him as Divine Love and Wisdom, and see the body as a 
representative or manifestation of the soul, we can visualize God as a Divine Man. 

 
 
 
 
 
If we can see this, it no longer appears strange that man is described as being created in the 
image and likeness of God. Nor does it appear so strange that the Logos, the Word, the Divine 
Truth, which was in the beginning, should be made flesh and dwell among us; and we behold 
His Glory as described in the first chapter of the Gospel of John, where also it is said, that He 
was the light of the world which lighteth every man that cometh into the world. 

Was not this light the same light of which we read in the first chapter of Genesis, where the first 
day of creation is described: "And God said, Let there be light, and there was light, and God saw 
the light that it was good"? 

The first chapter of Genesis appears to treat of the creation of the physical universe, the world 
of the physical creation, the objective world. This in the wisdom of God was so provided in order 
that children, and all peoples who are in a childish state, may think of God as the Creator of the 
wonderful world in which we live. For to a child, and to all who are in a childish state, this is the 
only world which has any reality to them. 

Yet the Word of God is also for the wise, for the adult who realizes that the world of mind is just 
as real and more essential than the world of matter, and that the primary creation is the creation 
of the world of mind. 

That the seven days of creation, essentially, are not a literal description of the creation of the 
physical universe, is evident from the fact that light is described as being created on the first 
day, while the sun, moon and stars are said to be created on the fourth day. 

That there is a light of the mind in which men see truth, as well as a light of the body in which 
men see physical objects, is a matter of common thought and speech, as well as of common 
expression in the Bible or in the Word of God. We have an instinctive feeling that this form of 
expression is not a mere simile, but that there is a correspondence between the seeing of the 
eye, and the seeing of the mind, and that the light of the mind is as real a light as the light of the 
sun. 

Concerning the first day of creation we read: "And darkness was upon the faces of the deep and 
the spirit of God moved upon the faces of the waters. And God said, Let there be light." Genesis 
1:2. Anyone who is willing can feel that the darkness here spoken of is the darkness of the man 
who is in doubt and obscurity, who is searching for the light of truth, but cannot find it, and 
therefore feels himself as in a deep, or in an abyss of ignorance, and that the spirit of Cod is the 
mercy of God, the mercy of our Lord, leading him into the light of truth. 

The spirit of God is said to move. The word in the Hebrew also means to brood. As a hen 
broods over her eggs, the spirit of God moves or broods over the waters. 

That waters mean truths is evident from the words of our Lord in the New Testament, but of this 
we will treat more fully in our next lecture. Here the faces of the waters are the knowledges of 

 
 
 
 
 
 
 
 
the truths of religion we learnt in our childhood, but which appear obscure and dark when we 
become adult and find that none can satisfactorily explain to us the things we have been taught. 
It is the Lord's mercy moving and brooding upon these knowledges of truth that brings to man 
the first light, which brings him to the first day of the re-creation of his spirit, the first light that 
God really is, that God is the All in all of life. 

The Bible commences with the words: "In the beginning God created the heaven and the earth." 
Are we to think here merely of the sky, or where the word "heaven" occurs, are we to think of 
what our Lord called "the kingdom of heaven within you"? Does "the beginning" merely refer to 
some ancient time, or does it mean the beginning of man's awakening when a vision of the 
kingdom of God is granted to him? 

As "heaven" stands for the "kingdom of heaven within you", so earth stands for the kingdom of 
earth in man, for the earthly things of the mind, earthly thoughts and affections. 

If the Bible is the Word of God, it cannot treat, as to its spirit, of any thing but the things of the 
spirit. 

What importance would many things written in the Bible have if they did not have hidden within 
them the things of the spirit? 

We read "the letter killeth, the spirit giveth life".

---
~~~

== The Second Day 

The distinction between inner and outer thought. Inspiration. Truth and how it purifies the mind. 

In the preceding lecture we considered some of the things involved in the first day of creation. It 
was shown that the seven days of creation, which apparently treat of the creation of the material 
world, as to their spirit treat of how the Lord God, the Logos, the Word of God, or the Divine 
Truth, creates the living spirit or the new mind in man. It was also shown that the word "creation" 
when used in the Word of God, as to its spirit always treats of the creation of the things of the 
spirit, as in the fifty-first Psalm, where we read: "Create in me a clean heart, O God; and renew 
a right spirit within me." Verse 10. 

It was shown that all true and appropriate thought of God was a thought of Him as being Divine 
Love and Divine Wisdom, thus as a Divine Man, and that man was thus to be created in His 
image; also that God, being Divine Good and Divine Truth, descended on earth as the Logos, 
the Divine Truth, and became flesh, as described in the first chapter of John. 

The first day treats of man being a "void" or "emptiness", a "deep" or an "abyss". As long as 
man pays all his attention to and directs his interests towards material ends, to the satisfaction 
of his material wants and pleasures, as to his spirit he is void and empty, and he is in darkness 
as to the things of the spirit; in fact, he is a "deep" or "abyss" of ignorance in relation to all things 
above the plane of material existence. The spirit of God moving upon the face of the waters is 
the Lord's mercy, reviving the things of religion which the man has been taught in his childhood. 

Children in states of innocence are delighted when taught about God, about heaven. Things like 
Christmas, the hearing the story of the birth of the Lord, make a deep impression on them. 
When a child grows up, such things recede into the background, and man centers his attention 
on gaining the things of the world. Still these childhood memories and impressions remain, and 
can be revived. It is these remains of things from a man's childhood which are the waters over 
which the spirit of God moves or broods. 

If the spirit of God touches these things, a man begins to come into light, into the light that God 
is, that He is the All in all things of life. It is the dawning of this light which creates in man the 
things of the first day of his spiritual creation, the beginning of the "creation of a new heart and a 
new spirit". 

In the first chapter of Genesis we are told that on the second day God made an expanse 
(translated at times firmament) in the midst of the waters, which was to distinguish between the 
waters below the expanse and the waters which were above the expanse and that God called 
the expanse heaven. 

 
 
 
 
 
 
 
If we think of the natural universe, this description has little meaning. Possibly one might think of 
the waters above as being the clouds and the waters below as being the seas, but to make this 
kind of distinction before the creation of the sun and moon, which were said to be created on the 
fourth day, is impossible. 

It follows that what is described as taking place on what is called the second day of creation has 
a hidden meaning, for as it stands it appears to have little sense. 

The subject of the second day of creation is the waters. That the Lord Jesus Christ used water 
as a symbol or representative of something of the spirit is self-evident, for we read that Jesus 
said: "He that believeth on me, as the Scripture bath said, out of his belly shall flow rivers of 
living water." John 7:38. 

The "Scriptures" here referred to are such places as the following: "With joy shall ye draw water 
out of the well of salvation." Is. 12:3. "They have forsaken the Lord, the fountain of living 
waters." Jer. 17:13. "Living waters shall go forth from Jerusalem." Zech. 14:8. 

There are many other places in both the New and the Old Testaments where it is self-evident 
that waters stand for something of the spirit. Therefore water and washing was chosen as a 
representative of purification, and is used in the sacrament of baptism. 

The meaning of water is most clearly evident in the fourth chapter of John, where we read: 
"Jesus answered and said unto her, If thou knewest the gift of God, and who it is that saith unto 
thee, Give me to drink; thou wouldst have asked of Him, and He would have given thee living 
waters. Whosoever drinketh of this water shall thirst again; but whosoever drinketh of the waters 
that I shall give him shall never thirst; but the waters that I shall give him shall be in him a well of 
water springing up into everlasting life. The woman saith unto Him, 'Sir, give me this water that I 
thirst not, neither come hither to draw." John 4:10-15 

If we are not like the woman of Samaria, but are willing to acknowledge the ancient symbolism 
or representation of water, we can find an intelligent and important meaning in the distinction 
made between the waters and the waters on the second day of creation. 

Waters stand for and represent truth. There are two things necessary for the sustenance of the 
life of the body: food and drink; and there are two things necessary for the sustenance of the life 
of the spirit: truth and good, or, what is the same, wisdom and love, for all living truth is of 
wisdom, and all living good is of love. 

If a man is willing to believe, truths, like a river, will flow out of his inner man: "Rivers of living 
water out of his belly." 

 
 
 
 
 
 
 
 
 
 
The subject of the second day of creation is therefore the distinction that is made between truths 
of a higher order, and truths of a lower order: waters above and below the expanse. 

That such a distinction can be made is evident from the distinction between concrete thought 
and abstract thought. Concrete thought is all thought which is based on the physical senses of 
hearing, sight, touch, etc. Abstract thought is all thought which is based on man's awareness of 
his conscious mind, awareness of his thoughts, feelings, affections, understanding, etc. Abstract 
truths therefore have to do with man's mental world, the world which he knows by reflecting on 
the operations of the mind. Of this world he is aware, not through the physical senses, but 
directly. Concrete thought, on the other hand, deals with the physical world of his environment. 

Another general distinction between truths closely related to the above is the distinction 
between scientific thought or the facts of science, and religions thought with its truths. 

A more profound distinction, however, may be made, which is the essential subject of our 
consideration of what is involved in this day of creation. A man may have been taught 
knowledges about religion, about God, etc., from his youth, and yet these knowledges may be 
largely a matter of memory, of knowing them from having been taught, and may not be a matter 
of inspiration, of insight, of understanding them in a living way. 

When a man has merely learned the things of religion in the same way as he has learned other 
subjects, they are together with his knowledges of other subjects in his outer mind. This is why it 
is first said: "Let there be an expanse or firmament in the midst of the waters and let it 
distinguish between the waters in the waters." In this state distinction is made between the 
truths of religion and other truths, but all on the same plane, with the same faculties of the mind. 
In the verse following, however, it is said: "God made a distinction between the waters which 
were under the expanse, and the waters which were above the expanse." That is, it is seen that 
a man has higher faculties of the mind, an inner life, and lower faculties of the mind, which have 
to do with his outer life, and that the living things of religion have to do with the inner or higher 
faculties of the mind, and that the living truths, called the waters above the expanse, are in 
these higher faculties. 

Therefore it immediately follows, "and God called the expanse heaven". 

The "heaven" here spoken of is "the kingdom of heaven", which the Lord says is "within you". All 
spiritual insight, all genuine inspiration, all living spiritual truths, are in this kingdom of heaven 
within man. These are the waters above the expanse, whereas truths which have only been 
learned, and are knowledges in the memory, are the waters under the expanse. 

With most persons the things of religion remain with other knowledges in the lower mind. In fact, 
most persons are unaware of any higher faculty of the mind in which insight, inspiration, the 
living truths of the spirit, have their seat or reside; and as long as one's interest is directed 
mainly to the things of the world, to its pleasures and satisfactions, one remains unconscious of 

 
 
 
 
 
 
 
the higher faculties of the mind. It is only when the pursuit of material ends is weakened that 
such faculties begin to open up. 

We read, therefore, in the Writings of Swedenborg: "At the present day this state (the second 
day) seldom exists without temptations, misfortune or sorrow, by which the things of the body 
and the world, that is such as are proper to man, are brought into quiescence (or quietness) and 
as it were die. Thus the things which belong to the external man are separated from those which 
belong to the internal man." Arcana Coelestia No. 8. 

At the end of each day it is said that the evening and the morning were the first day, second 
day, etc. Whereas at the end of the first day it is said: "And God called the light day and the 
darkness he called night." Every man whose mind is opened to God and to the things of the 
spirit, finds himself at times in the morning of the things of the spirit, when he sees that God is, 
and that all that is good and true with him is from God. Such happy states are followed by ones 
of obscurity and darkness; doubts arise and one falls into the things of self and self-interest. If 
one has cared for higher things, this condition of mind brings sadness and one raises one's 
eyes to a new dawn. Thus life consists of days, each with its morning and evening. 

In the morning one is raised into the things of the light of the spirit, the things of God. In the 
evening one sinks into one's own selfish thoughts and feelings, and the things of the spirit grow 
dim. 

As the subject of the second day of creation is the waters and the distinction made between the 
waters, we will here continue the consideration of what is meant by water in the Bible or Word of 
God. 

The first miracle our Lord Jesus Christ did was the miracle of turning water into wine. The water 
was placed in "pots of stone after the manner of the cleansing of the Jews". Water and washing, 
as is self-evident, stood for the purification or cleansing of the spirit. A man by living according 
to the truth is purified from evil. 

The water stood for truths which had been learned, truths in the memory, truths of the letter. 
These truths are turned in man into living truths of the spirit represented by wine. When a man 
comes to perceive from the Lord the living spirit of the Word of God, when he sees the teaching 
of the Word of God in application to the things of his soul, far above the natural appearances of 
the Bible, above the things of history, time, place and person, sees things universally as treating 
of the kingdom of God within, then the truths which he has learned are turned from water into 
wine. 

The meaning of the waters below the expanse or firmament and the waters above the expanse 
which were called heaven, in the second day of creation, is very similar to the meaning of the 
water and wine of the first miracle of the Lord, where the wine has a similar signification to the 
waters above the expanse which were called heaven. The waters above the expanse and the 

 
 
 
 
 
 
 
wine both stand for the spirit of living truth in contrast to the water below, or the waters in the 
pots, which stand for truths in the memory, or truths understood naturally, or as to their letter. 

We find this same contrast again in the words of John the Baptist: "I baptize you with water unto 
repentance, but He that cometh after me shall baptize you with the Holy Spirit and fire." Matt. 
3:11. Here John the Baptist stands for the letter of the Word, the first understanding of the Bible 
or Word of God, calling a man to repentance, whereas the Lord stands for the spirit of the Word, 
giving inspiration, and a spiritual understanding of the Word, represented by the Baptism of the 
Holy Spirit; and fire stands for the fire of love, the spiritual love of God and the neighbor. 

The Lord said to Nicodemus, "I say unto thee, except man be born of water and of the spirit, he 
cannot enter into the kingdom of God." John 3:5. 

To be born of water signifies to come into a new life based upon the Word of God, a life of 
obedience to the commandments of the Lord. But as at first the commandments are understood 
as to their letter, an external obedience is given to them. In this state a man regards his acts as 
being of primary importance, but does not take heed to the motives, the spirit behind the acts. 
This is being born of water, also to be baptized with water; but to be born of the spirit requires 
far more; to be born of the spirit involves understanding the spirit of the Lord's commands. To 
fulfill the spirit, one must not only change one's life as to its appearances before the eyes of 
men, but one must search one's motives, one's intentions, thoughts and feelings, for these must 
also be born again of God. The purification of water is the purification of the outward life. The 
purification of the spirit is the purification of one's inmost life, a life which few see: the 
purification of the feelings and thoughts one has in secret. 

The sad condition of the world, with its sorrows, its evils, its hatreds, is the result of man's not 
suffering God to make an expanse, a firmament, which divides the waters below from the waters 
above the expanse, the waters above being the kingdom of God in the inner or in the internal 
man, where the spirit of truth has its abode or dwelling place: truth which is not only a matter of 
knowledge, but which is living. Purifying truth changes the life, not only the life which is seen by 
man, but the life of one's inmost love and intention.

---
~~~

== The Third Day 

The seeds of truth and their growth. 

On the first day of the new creation of the heart and the spirit, God gives to man the light of 
truth: "God said, Let there be light, and there was light." This first light of the spirit is given to 
man by the spirit of God moving upon the faces of the waters. In our first lecture it was shown 
that by the faces of the waters were signified the things of religion which one imbibed in one's 
childhood, memories and affections about our Lord which impressed our childish minds, and 
which are now revived by the "Spirit of God", with the result that man receives the first light of 
truth. 

On the second day the subject is the dividing between the waters, and the expanse between the 
waters below and the waters above; the expanse or firmament being called heaven. In our last 
lecture it was shown that the waters signify the truths of God, that the waters below the expanse 
signify these truths in our memory, whereas the waters above the expanse signify the truths of 
the spirit: truths which belong to what our Lord called "the kingdom of heaven within you". 

Turning now to the third day which is the subject of the present lecture, we read: "And God said, 
Let the waters under the heavens be gathered together into one place and let the dry appear: 
and it was so. And God called the dry, land."  
(We use a more literal translation than that of the King James version of the Bible.) 

In the first two days or states of a man's new creation or rebirth, the mind is directed towards the 
truths of religion; he comes into light, he sees the things of the spirit as all-important. In these 
states he is delighted with the vision of the love and wisdom of God. These things must not 
remain things of the understanding, things of sight or vision merely, but must affect man's life. 
There must be good ground, a solid foundation on which the things of the spirit, things of 
spiritual life, can rest and from which the life can grow. Wherefore God said, "Let the dry appear 
and God called the dry, land." 

Waters, in the Word of God, as was shown in our last lecture, stand for or signify truths. These 
flow through the mind. But if man remains absorbed in truths and does not look to the ground of 
life, he is like a world with nothing but sea and sky. 

He has no resting place. He must have land, looking towards the Paradise of God. He must 
have something firm, a determination, a fixed direction to his life, and now to a new life; for a 
vision of God without a fixed determination to make one's life new, a determination to lead a 
Godly life, a life of love to God and love to the neighbor, is of no use. We often see religious 
people who are all sky and sea but no land, who have no ground in which things can take root 

 
 
 
 
 
 
 
and grow. Such are carried away by an abstract vision, but have nothing concrete. Such are all 
who do not order their natural life, who have not an ordered life in relation to the world in which 
they live, upon which the things of the spirit can rest. 

When a man has a determination to lead a new life, to lead a daily life of service to God and the 
neighbor, he has the beginning of good ground in which seeds can grow, and which in time will 
bear fruit, in a rich and noble life. Wherefore the description of the second day continues: "And 
God said, Let the land bring forth the tender herb, the herb seeding seed, and the fruit tree 
bearing fruit whose seed was in itself, after its kind and God saw that it was good." 

It was well known that by seed is meant the Word of God; for the Lord in explaining the parable 
of the Sower who went forth to sow, said in so many words, "The seed is the Word of God," 
Luke 8:11, and "He that soweth the good seed is the Son of Man." Math. 13:37. 

In the Arcana Coelestia, written by Emanuel Swedenborg, we read: "When the 'land' or man has 
thus been prepared to receive celestial seeds from the Lord, and to produce something of what 
is good and true, then the Lord first causes some tender thing to spring forth, which is called the 
tender herb; then something more useful which again bears seed in itself, and which is called 
the herb seeding seed, and at length something good which becomes fruitful, and which is 
called the tree bearing fruit whose seed is in itself." Arcana Coelestia No. 29. 

Because mankind reflects so little on the spiritual growths which take place in the mind, and 
does not see what is their nature, it is difficult to illustrate the difference between these three 
kinds of things which grow in man in the third day of his spiritual creation. The point, however, 
which is clear, is that if man will let the Lord implant the seeds of truth in good ground, they have 
the power of growing into a Paradise of wisdom and of multiplying immensely, just as plants and 
trees multiply by means of their seeds. Therefore seed is so frequently mentioned in the 
description of the third day. 

Here it is to be noted that the herbs and trees here spoken of are to be distinguished from the 
tree of life, and fruit trees which are spoken of as being in the Garden of Eden on the seventh 
day, after birds, animals and man had been created. 

On this third day of creation, according to the description given, there was as yet no sun or 
moon, no fish, birds, or animals, and no man. Thus this day signifies a state of life in man in 
which the things of life with man are not as yet truly animate, that is, there is nothing truly 
moving or living with animate life. Concerning this we read in the Writings of Swedenborg: "The 
man who is being regenerated is at first of such a quality that he supposes the good which he 
does and the truth which he speaks to be from himself, so that whoever supposes them to be 
from himself has not as yet the life of true faith; which nevertheless he can afterwards receive, 
for he can not as yet believe that they are from the Lord. This state is here represented by 
things inanimate and the succeeding one of the life of faith by animate things." Arcana Coelestia 
No. 29. 

 
 
 
 
 
 
This is "a state of repentance, in which a man, from his internal man, speaks piously and 
devoutly, and brings forth goods, like the works of charity, but which nevertheless are inanimate 
because he thinks they are from himself. These goods are called the tender grass, the herb 
seeding seed and afterwards the tree bearing fruit." Arcana Coelestia No. 9. 

Every man may know, since the fact is self-evident, that all life is from God, and that man is not 
the origin of the life which is in him. God is love, and it is the nature of all love, and especially of 
the Divine Love, to give of Itself to others, to give them gifts. The greatest gift of God to man is 
life. God cannot, however, give to man Life Itself, for to give this to man would be to make man 
God. But He does give to man life in such a way that man feels life in himself as if it were his 
own. If man did not feel life in himself as if it were his own life, he would not be a man. This is 
the supreme gift of God to man. But God is the only source of life. He must continually give life 
to man. He gives it like the talent which the Lord gave to his servants to use; but the servant, 
though he was to use and as it were administer his Lord's talents, was to give account and to 
acknowledge that it belonged to his Lord. 

So it is with life. God gives to man life and all the things of life, as if they were man's own. Man 
must administer these things like a good and faithful servant, but he should acknowledge that 
they are our Lord's and only as it were loaned to him. He must not steal them by claiming them 
for his own. 

And yet the things of man's life, the truths which man thinks and speaks, the good things which 
one loves and does, appear so much his own, that at first he can not realize that they are the 
workings of God in him, for man in this state has not advanced far enough to realize, in any full 
sense, the presence of God and how He works the good things which man loves and does, and 
the true things which man thinks and speaks. God in this third day or third state of regeneration 
does not hold man guilty for this kind of theft of His gifts. Nevertheless, the good things man 
does and the true things man says remain as it were inanimate; they do not fully live. For it is 
only when all things of man's mind and of man's life are filled with the spirit and the presence of 
the Lord in such a way that man actually feels that God alone is the source of life and all things 
of life, that man's acts, his works and his speech become living or animate. 

We will now turn to a consideration of some of the things which the Lord said about the seed. In 
explanation of the parable concernin3the sower, He said: "When any one heareth the Word of 
the kingdom and understandeth it not, then cometh the wicked one and catcheth away that 
which was sown in his heart. This is he which receiveth seed by the wayside. But he that 
receiveth seed into the good ground is he that heareth the Word and understandeth it, which 
also beareth fruit and bringeth forth." Math. 13:19, 23. 

The emphasis here is on the understanding of the Word, the understanding of truth, and thence 
willing and doing it. Many think that it is not necessary to understand the Word and doubt that it 
can be truly understood, thinking it is sufficient to have faith. Yet if one does not understand a 

 
 
 
 
 
 
thing, how can he know whether it is true or not, or if one does not understand the Word of God, 
what use is it, and how can one apply it to his life? Because the Word of God, which is called 
the Bible, has not been understood, many have lost interest in it; others have come to doubt it. If 
religion does not include the understanding of the Word, it remains merely an emotional religion, 
and as such is unstable. Man particularly wishes to understand that which he believes. Because 
the Word is not generally understood, and it is often thought that it cannot be understood, 
women predominate in the churches, and men often turn away, and the churches direct 
themselves largely to a merely emotional appeal. 

Of those who hear but do not understand, it is said that the birds came and devoured up the 
seeds. In the lecture on the fifth day of creation, which treats of the creation of birds, we will 
show that birds signify the enlightened rational mind, or the inspiration brought by rational 
understanding of the things of the spirit; but here the devouring birds have the opposite 
signification, namely, mere reasoning, reasoning from fallacies and false appearances. If one 
does not understand the Word of God, one may be led astray by all manner of false reasoning. 

The parable next treats of seed in stony places which sprang up, but on account of the lack of 
earth were parched by the sun. Such the Lord said, "is he that heareth the Word, and anon with 
joy receiveth it, yet hath he no root in himself and dureth for awhile; for when tribulation or 
persecution ariseth because of the Word, by and by he is offended." Math. 13:20,21. 

If one accepts the Word of God "in spirit and in truth", one finds oneself opposed to the sham 
society which to large extent surrounds him. Such a one is averse to popular conceptions. He 
sees the mockery of what is often mistaken for culture and civilization. He makes for himself 
enemies of those who persecute him for showing up the mockeries that have such a strong 
popular appeal. If he has not sufficient depth of ground to withstand the tide of popular opinion 
with its false standards of approval and condemnation, he gets carried away, and the seeds of 
truth which sprang up with joy wither away. 

Concerning the third type of reception we read: "He that receives seed among thorns is he that 
heareth the Word, and the care of this world and the deceitfulness of riches choke the Word and 
he becometh unfruitful." Math. 13:22. 

Now it is known that with some wealth proves a snare, and that all who put their heart primarily 
in the riches of this world are carried away. But it is also known that the poor are often 
discontented with their lot and bitter against God or society. Those who are primarily meant by 
the poor are those who in "The Ten Blessings" are called "poor in spirit" and by the rich are 
meant the rich in spirit, that is, those rich in the things of heaven. 

We read in the Revelation of John that the "Son of Man" says, "Buy of me gold that thou mayest 
be rich." Rev. 6:15. 

 
 
 
 
 
 
 
But in the parable of the sower as in other places the riches are those which "choke the Word". 
What are the spiritual riches which "choke the Word"? Spiritual riches are knowledges of 
religion, knowledges from the Word of God, theological learning. There are many to whom such 
knowledge, such learning, proves a snare. This applies to all who are proud of their theological 
learning, proud or vain of their knowledge of religion, proud of the amount of study they have 
given to the Bible; all such see only the letter and not the spirit of the Word of God. They indeed 
have a wealth of spiritual knowledge or learning, but it is useless wealth, wealth gathered for 
their own satisfaction and pride; such people proud of their own understanding tend to bring all 
religion into disrepute before the eyes of the superficial. 

On the other hand, those who are poor in spirit are those who are humble, those who know that 
what they understand is hardly anything compared to the immense treasure within the Word of 
God; those who know that what they do understand is from the mercy of God and not their own 
cleverness. 

The parable of the sower ends with the words: "But that on the good ground are they, which in 
an honest and good heart, having heard the Word, keep it and bring forth fruit with patience." 
Luke 8:15. 

Here it is shown that the good ground is an honest and good heart, a humble obedience and 
keeping of the Word, with patience and endurance. 

Can not any one who is willing see that the land and ground which was created on the third day 
is the same ground that the Lord said was "an honest and good heart", and that the seeds 
planted on that day are the seeds of truth, or the Word of God, which can bear fruit only in such 
ground? In the so-called Christian world how often the Word is not received in "ground" which is 
"an honest and good heart", but is received on shallow ground — shallow lives. This is why the 
world is what it is.

---
~~~

== The Fourth Day 

The source of life, love and faith. 

We read concerning the fourth day of creation: "And God said, Let there be luminaries in the 
expanse of the heavens, to distinguish between the day and the night; and let them be for signs 
and for seasons and for days and for years; and let them be for luminaries in the expanse of the 
heavens, to give light upon the land; and it was so. And God made two great luminaries, the 
greater luminary to rule by day, and the lesser luminary to rule by night, and the stars. And God 
set them in the expanse of the heavens to give light upon the land." 

In our lecture on the first day of creation, we showed what was meant by "God said, Let there be 
light and there was light." Namely, that in the first day or state when a man is being born or 
created anew, he is given the light of truth; he is given as it were a vision of God. He sees the 
Word of God in light, whereas before he was in the greatest obscurity and doubt. That that light 
stands for the light of the mind, the light of the spirit in which he sees the truth of God, needs 
little demonstration. That light stands for truth is an obvious teaching of the Bible, and is a 
matter of common speech. Besides which anyone can feel within himself that at times he may 
be brought into the light of truth which dissipates ignorance just as the light of day dissipates the 
darkness of night. But the first light into which a man comes in matters of religion, is a general 
and relatively obscure and diffused light. Nor does he see the source of this light. 

That the seven days of creation do not treat of the physical creation is here self-evident. For if 
we regard the physical world it is obvious that light could not be created on the first day, since 
the sun and moon were not created until the fourth; but if we see that creation refers to the 
creation of the new heart and the new spirit spoken of in the Prophets, we can see that a man 
must first come into a general light of truth, and later come to see the source of truth. 

As there are two physical things, heat and light, which make life on earth possible, so there are 
two things which make the life of the spirit possible, namely, the good of love and the truth of 
wisdom. That light stands for the light of truth we have already shown; that heat stands for the 
warmth of love is also self-evident and is also a matter of common speech. For we say a man 
has a warm heart, he showed a warmth of affection, he received us warmly, a warm friend, etc. 

As the sun in the sky is the source of heat and light, so God is the source of all the warmth of 
the spirit, that is of all love, and of all light of the spirit, that is of all truth. Wherefore it is said in a 
Psalm of David: "For Jehovah God is a Sun and a shield." Ps. 84:11. Here it is said of Jehovah 
God that He is a Sun, because He is the source of all warmth of the spirit or love with ma; and 
of all the light of the spirit, the light of truth with man. 

 
 
 
 
 
 
 
Not only is Jehovah God called a sun in the Psalms, but it is said of the Lord Jesus Christ when 
He was transfigured on the mountain before the three disciples, that "His face did shine as the 
sun and His raiment was white as the light." Mat 17:2. And John saw in vision the "Son of Man", 
"And His countenance was as the sun shining in his strength." Rev. 1:16. 

We thus find in the Bible or Word of God that Jehovah God is called the sun, and also that the 
Lord Jesus Christ, the Son of Man, shone as the Sun in His strength. 

The Lord when asked where the kingdom of heaven was, replied that the kingdom of heaven is 
within you. If the kingdom of heaven has been established in a man's mind and heart, Jehovah 
God is in that kingdom as a sun, the source of all the warmth of love and of all the light of truth. 
But the Lord Jesus Christ, the Son of Man, is also the "sun shining in his strength". 

The reason why both Jehovah God and the Son of Man are the sun, the source of the spiritual 
heat and light of man's spirit, is that they are one. As the Lord said: "I and my Father are one," 
John 10:30, "He that seeth Me seeth the Father:' John 12:45, "I am in the Father and the Father 
in Me," John 14:10. 

As the Lord God our Saviour Jesus Christ is the Sun of the kingdom of heaven within us, the 
source of all our love and faith, He also appears in the Sun of heaven before the eyes of the 
angels. Wherefore we read in the work Heaven and Hell by Emanuel Swedenborg "In heaven 
the Lord is seen as a sun, for the reason that He is Divine Love, from which are all spiritual 
things, and by means of the sun of the world all natural things have their existence. That love is 
what shines as a sun. That the Lord is actually seen in heaven as a sun I have not only been 
told by angels, but it has occasionally been granted me to see it." Heaven and Hell No. 117. 

Those who have truly felt the Lord's love and seen the truth of His Word may know that He is 
the Sun of life, the source of all love and truth. The Sun not only stands for the Lord's love, but 
also for love from Him in man, thus for that love to God and the neighbor which though it 
appears as if it were ours, really is from the dwelling of the Lord in us, and we in the Lord; for 
the Lord said: "Abide in Me and I in you. As the branch cannot bear fruit of itself except it abide 
in the vine, no more can ye except ye abide in Me." John 15:4. 

Therefore in the Revelation of John it is said that the woman, who stands for the true Church, 
"the bride of the Lamb', was "clothed with the Sun, and the moon under her feet". Rev. 12:1. For 
from the Church when it is truly Christian, love goes forth as the fire of the sun. 

On the fourth day of Creation two luminaries were created— the sun and the moon. The moon 
gives forth light by reflecting the light of the sun, but it does not give forth heat. As the sun 
stands for love in the kingdom of heaven, so the moon stands for faith. Faith without love is like 
the moon, which indeed gives a light in the night, but apart from the sun there is no warmth. 
When a church trusts in faith apart from love, it is in the cold light of the moon. But if there is no 
love, there is really no moon, for the moon cannot give light apart from the sun. Faith which is 

 
 
 
 
 
 
 
truly faith is nothing but the reflection of the love of God. Faith which is truly faith is always one 
with love to God and to the neighbor; wherefore the verb in the Hebrew where it is said, "Let 
there be luminaries" is in the singular number. This does not appear in the English, but the 
sense can be conveyed if it is said "there is to be luminaries" instead of "there are to be 
luminaries", for love and faith are one—faith without love being nothing. All spiritual death is due 
to separating love from faith or faith from love. Faith separated from love is cold, formal, hard, 
mere dogmatism. Love separated from an enlightened faith in what is true, is sentimental, 
obscure, mere emotionalism. 

The Sun stands for God as Divine Love and Wisdom, and also stands for the Son of man, our 
Lord Jesus Christ, from whom we are enkindled with love to God and the neighbor, and from 
whom we are enlightened in the light of truth. As the sun is spoken of in these two relationships, 
we must consider further what is the relation of the verse which says: "The Lord Jehovah is a 
Sun," Ps. 84:11, and the verse which says: "The countenance of the Son of man was as the sun 
shining in his strength." Rev. 1:16. 

We read in Isaiah: "The light of the moon shall be as the light of the sun, and the light of the sun 
shall be sevenfold, as the light of seven days, in the day that the Lord bindeth up the breach of 
His people and healeth their wounds." Is. 30:26. 

This is a prophecy concerning the Lord's coming. If man will receive the Lord in his heart, his 
faith will become like burning love, and his love will become sevenfold, like the light of seven 
days. 

Until God is seen as a Divine Man, that is as Divine Love and Wisdom, a fullness of love is not 
possible. This is the reason why the Lord God descended on earth and took on a human nature 
which He glorified. That it was God Himself who was born on earth is taught in the first chapter 
of John: "In the beginning was the Word, and the Word was with God and God was the Word. 
(*) And the Word (God who was the Word) was made flesh and dwelt among us, and we beheld 
His glory." John 1, 1:14. 

(*) A mistranslation occurs in the King James Version where it is said "the Word was God". 

That the Lord was Jehovah God Himself, descended on earth, is taught in many places in the 
Old Testament: "Jehovah bowed the heavens and came down," Ps. 18:9, "it shall be said in that 
day, Lo, this is our God; we have waited for Him that He may save us; This is Jehovah; we have 
waited for Him; we will rejoice and be glad in His salvation." Is. 25:9. 

We will not here stop to quote the many passages in the Prophets which say that there is but 
one God, that the Lord Jehovah is the only Saviour and Redeemer and there is none beside 
Him. Here is the center of the Christian Religion. Both the Old and the New Testaments teach 
most clearly that the Lord God Jesus Christ is God the Saviour. 

 
 
 
 
 
 
 
 
If Christians deny this teaching of the Bible, they take away the essence of Christianity. If they 
reduce the Lord Jesus Christ to a man by denying His full Divinity, they make of the Christian 
Religion a moral code, and deny its essential religious teaching, that God became flesh to dwell 
with man in order that we might see the Divine Glory and be able to love, to see and to worship 
a visible God. No one can truly love and be conjoined with an invisible God. 

Still it is with the greatest difficulty that those of the present day can believe in God incarnate, 
the Word, that is the Divine Truth made flesh. Yet why should this be? God is either Divine Love 
and Divine Wisdom, or He is nothing that we can grasp. To think of God merely as an infinite 
force is to think of Him materialistically. The only other possibility is to think of God as being of a 
totally incomprehensible nature, thus as an unknown and unknowable God. Why should such a 
God have created man? Can we love such an unknowable God? Either God created man from 
love according to wisdom, or He created man for a totally unknown reason. Why should God 
create man if man cannot know and love God in return? On the other hand if God created man 
from love and according to wisdom, it must have been in order that He might be known and 
conjoined to man by love. If this is true, what is more reasonable than that He should have 
assumed flesh and blood in order that He might be seen, known and loved by mankind? 

If we will believe the Gospel, we can see that our Lord was "God with us", and that the Father 
and Son are one, for God cannot be divided. The Lord did indeed assume a nature from Mary, a 
human body, but He glorified Himself, putting off all human limitations. This is the meaning of 
the description of the Lord's transfiguration where His "face did shine as the Sun and His 
raiment was white as the light". To see the Lord thus in His Glory is to see Him as one with 
"Jehovah God" who is a "Sun and a shield". 

This is the great question:—Is the Lord Jesus Christ the Sun of man's life, the source of spiritual 
heat and light, that is the source of love and wisdom, or is he a man? To believe that He is the 
"Sun shining in its strength" is to be truly a Christian; to believe he is merely a great moral 
teacher is not to be a Christian. 

Concerning the fourth day of creation we read in the work of Emanuel Swedenborg, the Arcana 
Coelestia: "Man receives life from the Lord by faith, first by faith in the memory, next by faith in 
the understanding, and lastly by faith in the heart which is the faith of love or saving faith." 
Arcana Coelestia No. 30. 

When a man loves the Lord Jesus Christ as the Sun in the kingdom of heaven within him, when 
he sees Him as the Sun shining in its strength, and his heart and his mind are filled with this 
vision, the sun is said to be created and man is in the fourth day of his spiritual creation. The 
paragraph of the Arcana Coelestia continues: "For this reason (on the fourth day) love and faith 
thence derived are first treated of, and are called 'luminaries'; love being 'the greater luminary 
which rules by day', and faith from love 'the lesser luminary which rules by night'. Love and faith 
in the internal man are like heat and light in the outer bodily man? for which reason the former 

 
 
 
 
 
are represented by the latter, a great luminary in his will and a lesser one in his understanding." 
Arcana Coelestia No. 30. 

When love of the Lord fills men's hearts, they are in day, in the light of love, but at times the love 
fades and they come into evening, into obscurity. They may remember the light of love which 
they had felt in the day and this memory of the things which they bad felt and believed is as it 
were a moon in the nights of their life, sustaining them until they come to another dawn. Thus 
the greater luminary of love rules in man in states of daylight and the lesser luminary rules in the 
states of night or obscurity. The two luminaries are said to be "for seasons and for days and for 
years". For when a man is in the warmth of love to the Lord and to the neighbor, he is in as it 
were a springtime of spiritual life. When this state passes and he is in coolness, he enters a 
state of autumn or winter. Thus does every man pass through seasons and days of his spiritual 
life. 

By the sun is signified love, by the moon faith, and by the stars the knowledges of faith, for 
every knowledge of God and His kingdom is a point of light in the mind, and all man's 
knowledges make as it were a starry firmament in its beauty, provided they are real knowledges, 
and not mere dry theological speculations. 

If we can but feel and see this meaning of the sun, the moon and the stars, we can understand 
why it is so often said in connection with both the First Coming of the Lord and also in relation to 
His Second Coming that "The sun shall be darkened and the moon shall not shine, and the 
stars shall fall upon the earth." Namely, that the love of God and the neighbor will no longer be 
the warmth of men's loves, then that faith is obscured, and the stars of heaven, the knowledges 
of God and His kingdom, will give place to the knowledges of merely earthly things. 

When love to God grows cold, when love to the neighbor no longer rules in man's heart, when 
faith becomes weak and obscure, the knowledges of such things no longer fill the firmament of 
man's heaven, the Lord must come to save men; otherwise they would spiritually die in the 
coldness and darkness of denial and ignorance. 

The Lord comes to establish the city or kingdom of God, of which it is said that it "hath no need 
of the sun, neither of the moon to shine in it; for the Glory of God did lighten it, and the Lamb is 
the light thereof." Rev. 21:23. A similar passage is found in Isaiah: "The sun shall be no more 
thy light by day; neither for brightness shall the moon give light unto thee; but Jehovah shall be 
unto thee an everlasting light, and thy God, thy Glory. The sun shall no more go down; neither 
shall the moon withdraw itself, for Jehovah shall be thine everlasting light." Is. 60:19, 20. This is 
said of the coming of Jehovah God in the Word, the Word which is God become flesh; as is said 
in John: "He is the light of the World." When the Lord dwells in the inmost of man's heart and 
spirit, and man sees His glory, then the Lord sets luminaries in the expanse of man's heaven, to 
give light on the earth, that is to give light as to man's earthly life,—how he is to live. A man who 
has this sun and moon in his inner or rather inmost man, and walks on earth in the light of it is in 
the fourth day of his spiritual creation.

---
~~~

== The Fifth Day 

How knowledges become living. 

"And God said, Let the waters cause to creep forth the creeping thing and let the birds fly above 
the land in the expanse of the heavens." Gen. 1:20. 

In the last lecture we treated of the creation of the sun, moon and stars, and today we will 
consider the meaning of the creation of the fish and the birds. 

Genesis commences with the words: "In the beginning God created the heavens and the earth." 
On the second day God was said to have divided between the waters above which He called 
heaven and the waters below which were called seas. The third day treats of the grass and the 
trees on the earth, the fourth day of the sun, moon and stars in the heavens, and the remaining 
days treat again of things created in the seas and on the earth. 

In this series of lectures we have shown that the sky or heavens represent or stand for the 
"kingdom of heaven within you", and the earth and sea stand for the outer man, the man in 
relation to the world around him. In the Writings of Swedenborg what the Lord called the 
"kingdom of heaven within you", is called the internal man, and the outer man, earth, is called 
the external man. 

It is known by every one that a man has a mind and a body. It is also known that a man has two 
kinds of thought, abstract and concrete: abstract thought, consisting of thought about things of 
the mind, such as love, wisdom, affections, thoughts, will, understanding, etc., and concrete 
thought dealing with physical objects. 

But the distinction between the internal man represented by heaven, and the external man 
represented by earth, is still a different distinction. Few know the difference between this inner 
and outer, or rather internal and external man, because few know what the Lord meant by the 
"kingdom of heaven within you". The reason that few know what this internal man, this "kingdom 
of heaven within you" is, is that men's minds are so much directed to the outer world, to 
accomplishing their purposes in regard to the outer world, in gaining a living, in perfecting 
machines, in satisfying their material wants, that they seldom turn their minds to what is higher. 
Even if they go to church on Sunday, the service is not an essential thing of their lives in which 
they center their love and thought. They let the minister do the work, if he really does any work; 
and even in the churches men's minds are largely centered on things of this world and the 
kingdom of heaven is largely forgotten. 

 
 
 
 
 
 
 
 
Therefore if one reads in the Arcana Coelestia of Swedenborg where he treats concerning the 
creation of heaven: "the next thing therefore a man observes in the course of regeneration is 
that he begins to know that there is an internal man, or that the things of the internal man are 
goods and truths, which are of the Lord alone," the reading of such a sentence in this day and 
age means nothing to the average man and woman, for the reason that they have not turned 
their minds inward and therefore have never observed the things of the internal man, the things 
of the kingdom of heaven. This inner or internal mind is therefore a blank as far as they are 
concerned. Now it is in the internal mind in the heavens within one that the sun and moon are 
created. 

In our last lecture it was shown that the Lord God our Saviour Jesus Christ dwells in man in His 
inner kingdom of heaven, if and when a man has had a new heart and a new spirit created 
within him. It was also shown that of the Lord Jesus Christ, the Son of Man, it was said that "His 
countenance was as the sun shining in his strength," Rev. 1:16, for the reason that from Him go 
forth love and wisdom, giving man spiritual life in the same way as heat and light go forth from 
the sun of the world and make natural life possible. 

It was also shown that when a man advances to the fourth day or state of his spiritual life, his 
mind is opened, and he feels and sees that all his love to the Lord and his love to the neighbor, 
all his wisdom of life, is from the Lord who is their source, and has His dwelling place in the Sun 
of life, in the kingdom of heaven within him. 

When a man has such a perception of the presence of the Lord God, such a perception of the 
presence of His love and wisdom within us, he begins to really live, for before such an 
experience a man can scarcely be said to live; wherefore the things created on the following day 
are living, animate things, fish and birds. 

When man's internal mind is opened, that mind where the love of God and the wisdom of God 
reign, he begins to live also a different natural life, a different life in relation to his work, his 
family, his friends, a different life as to what he cares to understand, as to what he wishes or 
wills. 

The first things created below the heavens after the creation of the sun and moon are said to be 
"the moving creatures having life that the waters brought forth",—that is fish. 

When treating of the second day, it was shown that by the seas and the waters which were 
called seas, were meant the truths of the Word of God in the memory or external man. A man 
may love the Word of God as a thing which he has been taught in his childhood, he may love 
the things he remembers- the things that he reads, and hears, but there may he nothing truly 
living or animate in his knowledges. He may not have a living understanding. If, on the other 
hand, man is given a vision of the Sun of heaven in which the Lord dwells, if he feels that all 
love and wisdom come from Him, warming the heart and enlightening the spirit, then there begin 

 
 
 
 
 
 
to be living, animate things in his understanding of the Word of God or the Bible that were not 
there before. These living things are called fish. These are living knowledges. 

There are dead knowledges of religion and living knowledges. Dead knowledges are not of 
inspiration, of enlightenment or insight, but are merely things that have been learnt. Especially 
are knowledges dead when there is not a great love that animates them. Living knowledges are 
all knowledges which a man takes great delight in, not merely to know them but on account of 
their service to God and man. 

On account of this signification of fish, fish are so often spoken of in the New Testament, where 
we are told of the miracle of the feeding of a great multitude with a few small fishes, of the 
miraculous draught of fish. Also it is told us that the Lord chose chiefly fishermen for His 
Apostles to whom He said He would make them fishers of men. If we are willing to believe that 
the Bible is the Word of God, we will acknowledge that such things are not of mere chance but 
of Divine Providence, and involve deep secrets, hidden reasons, things of profound wisdom. 

We will therefore consider a few of the things involved, first in regard to the feeding of the five 
thousand: 

The disciples had a few loaves of bread and a few small fishes in the wilderness, with which the 
Lord commanded them to feed the multitude. The Lord called Himself "the bread of life" which 
had come down from heaven, because bread stands for the Lord's love of the salvation of the 
human race and the reception of the Good of His love in the heart of man. Therefore bread is 
given in the Sacrament of the Holy Supper, and the Lord called it His body; for the body of our 
Lord after His resurrection from the dead, the body of our Lord seen in glory, is nothing but the 
Divine Love in human form, the Divine Love appearing in the form of a man. The few loaves of 
bread therefore means that with the disciples there was a little of the Divine Good, a little of the 
Divine Love; the fishes stood for the living knowledges of the kingdom of God. Of these also 
they had few. It therefore appeared as if they could not feed the great multitude in the 
wilderness, the wilderness signifying a state in which there is little that is spiritually alive, a state 
such as we see around us where most persons are alive in regard to the things of this world, but 
for the most part dead in regard to the things of the kingdom of God. The miracle is that if one 
has even a very little of the love of good, a very little of the living knowledge of religion, these 
things can be immensely increased and multiplied by the Lord, so that they amply feed the spirit 
of man. 

If man opens himself to the presence of the Lord, the few living knowledges that he has from the 
Word of God and which he loves and according to which he lives can be miraculously increased 
by the presence of the Lord. 

Another miracle was the miracle of the draught of fishes. The disciples after the resurrection of 
the Lord had fished all night, the night of ignorance, and had caught nothing. In the morning the 

 
 
 
 
 
 
Lord appeared and told them to cast their net on the right side of the boat, and the net was filled 
with great fishes. 

The right and left, the right hand and the left hand, are frequently spoken of in the Word of God 
and stand for the good of love and the truth of wisdom. Man's mind has as it were two halves to 
it, the intellectual and the voluntary, or what is the same, the will of doing good from a genuine 
love of God and the neighbor, and an understanding of truth, a genuine wisdom of life. These 
two halves of the mind are represented by the right and left sides of the body. Wherefore 
casting the net on the right side of the ship signifies acting from love. If a man will but act from 
the love of God and the neighbor, his living knowledge of the Word will be immensely increased. 

At this time mention will be made of but one other passage in the New Testament in which a fish 
is mentioned. The Lord said: "If a man's son asks for a fish, will he give him a serpent?" Matt. 
7:10. A serpent which is said "to go on its belly" stands for those knowledges Which are closest 
to the earth: that is, the knowledges of science, of experiment, of material objects and the laws 
governing them. Youth with its natural ideals asks for knowledges of the spirit, things which will 
inspire it, feed it, but the schools for the most part reply by feeding them only serpents, merely 
scientific knowledges. It is this tragedy of feeding our sons serpents instead of fish which has 
brought about the tragic state of the world which we see about us, where hardly any food for the 
spirit, living knowledges of the spirit, are to be found. 

It was once asked Swedenborg why the Lord had chosen him, a layman, to manifest to him the 
internal sense of the Scriptures and not a clergyman or theologian; to which Swedenborg 
replied that the Lord had chosen fishermen and not priests or scribes to be His Apostles; that 
he, Swedenborg, also had been a natural fisherman, that is, he had been one who had 
investigated the wonders of nature as showing forth the wisdom and handiwork of God as 
manifested in the laws of nature, and had been called to show forth the laws of the kingdom of 
God as they lay hidden in the Word of God. 

Swedenborg up until his fifty-fifth year had been a scientist and philosopher known throughout 
Europe. We will not stop here to speak of his remarkable writings in relation to philosophy and 
science, only noting that the spirit that ran throughout his scientific works was one of showing 
the wonders and the wisdom of God in nature and in the created natural universe. 

He said: "A fisherman in the Word denotes a man who investigates and teaches natural truths, 
and afterwards spiritual truths in a rational manner." Intercourse of the Soul and the Body. No. 
20. 

On the fifth day of creation first the fish were created, then the birds of the heavens. Fish stand 
for or signify living knowledges in the external or outer thought; birds of the heavens signify 
truths in the inner or internal thought, things of the inspired rational mind, the thoughts of the 
spirit which as it were ascend into heaven towards God. 

 
 
 
 
 
 
 
That living thoughts as it were fly in the inner or interior mind of man, thoughts which rise as it 
were towards heaven, can be felt by one who raises his mind towards God in His heaven. Birds 
are therefore frequently spoken of in the Word of God. That birds do not stand for material birds 
is evident from what is said in the Psalms: "Yea, the sparrow bath found an house and the 
swallow a nest for herself, even thine altars, O Lord of hosts, my King and my God." Ps. 84:3. 

But it is especially evident that birds stand for thoughts of the spirit, yea for the Holy Spirit Itself, 
in the description of John the Baptist's baptism of the Lord where we are told of "the spirit of 
God descending like a dove and lighting upon him". Matt. 3: 16. 

If man comes to the fourth state or day of creation, the Lord dwells in as it were the Sun in the 
kingdom of heaven within man, and man perceives and feels that the Lord is the source of all 
his love and wisdom, and then living knowledges, represented by fish, begin to live in his mind, 
especially in the things of the Word of God which are in man's memory. What he has learned 
begins to be full of animate or living things like fish, and the thoughts of his spirit ascend like 
birds into the heavens.

---
~~~

== The Sixth Day 

The Image and Likeness of God. 

In our last two lectures it was shown that by the sky or heaven in the Word of God is meant 
what the Lord called "the kingdom of heaven within you", that is, the inner or internal man or 
mind, and that the Lord is as it were in the sun of life in this internal man, being the source of the 
warmth of love and the enlightenment of truth. When this kingdom of heaven is open within man 
and he perceives the presence of the Lord God there, man's thoughts are changed. He comes 
into living knowledges of the Word of God, represented by the creation of fish, and his thoughts, 
represented by birds, ascend as it were towards God in heaven. Thus in the fifth day or state 
man turns his thoughts towards God, so that he thinks of the presence of God in all things of his 
life. He no longer regards himself in the first place, but thinks how he can do the will of God. He 
begins to see how all things of the Word of God are truths which guide him in his daily life. 

As was shown in the last lecture, the mind of man consists of two parts, the one part being the 
voluntary, the will of doing what is good or right, the voluntary or will side of the mind to which 
belong also the affections or feelings. The other half of the mind is the intellect to which belong 
the understanding of truth, thoughts, knowledge and memory. 

After establishing the kingdom of God within man, the first thing that takes place is that man's 
knowledge of the Word becomes living and his thoughts ascend towards God, that is, his 
intellect or his thoughts turn towards God. This is what was represented by the creation of fish 
and birds. On the sixth day the animals or beasts were created. The beasts stand for the 
affections or feelings of love. Thoughts, no matter how inspired, how lofty, or noble, are of little 
use if they are not followed by good feelings. An animal is led to do what it does from its 
affections, its feelings, which it instinctively follows. An animal, therefore, in the Word stands for 
affections or feelings. Men are therefore in the Word of God often called by the names of 
different animals, such as sheep, cattle or goats, or if evil, wolves and foxes. Because of this 
correspondence, it is often said in common speech that a man is a fox, a snake, a tiger, a pig, 
according to the nature of the affection which animates his life. 

On account of this correspondence the Lord Jesus Christ was called the Lamb of God, to signify 
the Divine Innocence of love; and He was called "the Lion of the Tribe of Judah" to signify His 
omnipotence, His infinite power. 

We have said that animals stand for affections or feelings. An affection is the result of 
something affecting us, moving us. We are affected by a thing according to our love. One who 
loves music is affected by it; one who does not, is not affected by it. If one loves another deeply, 
one is profoundly affected by his presence, particularly after a separation. If one loves truth, one 

 
 
 
 
 
 
is affected, moved, by hearing it. If one loves what is good, one is affected by seeing it. If one 
sees another make a great sacrifice, a sacrifice of that which he holds dear, for the sake of 
another, it affects one. A man who loves what is good is profoundly affected with delight at 
seeing good conquer, and is deeply grieved at seeing evil increase, and the affection is 
according to the strength of the love. 

Now there are many who are moved by great and noble deeds, especially when done at a great 
sacrifice. Such things affect us and make up our nobler affections or feelings. But the affection 
is always according to the love. If a man's love is for temporal things, he will be affected by 
temporal things. If he loves eternal things, he will be affected by eternal things. From all the 
lectures that have gone before in this series it may be seen that the animals which are said to 
be created on the sixth day of creation signify the affection of eternal things, things of the spirit. 
The saddest thing about the present day is that so few are affected by eternal things, things of 
the spirit. For the most part men are affected by temporal things. 

Generally speaking if a man loses his position, his reputation, his friends, his wealth, he 
becomes depressed and sunk in grief, maybe he is even brought to despair. But if a man feels 
himself losing his ideals, his faith, the purity of his purpose, he is not so much distressed. 

Parents are apt to be more greatly grieved at the death of their children, than they would be at 
the loss of ideals on the part of their children. If men cared for the kingdom of God, the passing 
of one's children from this world to the world to come would cause far less grief than if their 
children turned their minds solely to merely material pursuits and gains and away from higher 
ideals. 

When a calamity like war strikes in fury, many are affected by the great suffering. But there are 
few who are deeply affected by the far greater tragedy of this age: the youth of the world 
brought up without spiritual ideals, with no concept of anything beyond the things of this world, a 
youth which is largely aimless except in the pursuit of material ends, or a youth perverted by the 
false idea of a materialistic patriotism. 

In the world today we see part of the human race inspired by a cruel materialistic patriotism, 
while the other part mostly do not care about the welfare of the world, provided they do not have 
to endanger their own useless and selfish lives, with their possessions and pleasures. How few 
would sacrifice anything for the "treasure in heaven". A treasure in heaven is all the things of a 
genuine love of God and the neighbor, all things of a deep wisdom of life with the great joy and 
delight of such a life. 

If a man has passed through all the days, all the states described so far, he finally becomes an 
image and likeness of God. A man is not a man from his body but from his mind. A man's body 
is not unlike the body of an animal, but as to his mind he can become an image and likeness of 
God, viewing things Divine, living in things Divine. Thus is to be truly man in fullness. 

 
 
 
 
 
 
 
It is said in the Arcana Coelestia by Swedenborg that the wise men in the Most Ancient Church, 
the Church that was called Adam, "called no one 'man' but the Lord Himself, and the things 
which were in Him; neither did they call themselves 'men', but only those things in themselves, 
as all the good of love and all the truth of faith, which they perceived they had from the Lord. 
These they said were 'of man', because they were of the Lord." Arcana Coelestia No. 49. 

To become a man is to receive what is of the Lord in the heart and in spirit, in fullness, in such 
fullness that man as to his love, as to his wisdom, and as to his life is an image and likeness of 
God. 

This state is rare. It is therefore written in the Arcana Coelestia: "Those who are being 
regenerated do not all arrive at this state. The greatest part at this day attain only to the first 
state, some only to the second, others to the third, fourth or fifth, few the sixth and scarcely 
anyone to the seventh." Arcana Coelestia No. 13. 

It is therefore said of the world when it turns from God and from the kingdom of heaven to the 
things of earth: "I beheld and lo there was no man, and all the birds of the heavens were fled." 
Jeremiah 4:25. 

It is evident that unless man is born again as to his mind, he is not an image and likeness of 
God; that an evil man is not such an image and likeness is evident. But even with the good, for 
one of them to become an image and likeness in any full sense is very rare. Because this is so 
rare, it is difficult to describe what such a man is like, for apart from the experience of meeting 
and speaking with such a one, a description conveys little idea. 

If we really understand what is meant by man in the image and likeness of God, a man who is 
truly a man in the image and likeness of God, a man who is truly a man in the sense of the word 
in the description of the sixth day of creation, that is, one who is filled with the spirit of God, we 
may see for ourselves as did the prophet Jeremiah: "I beheld and lo there was no man." 

A man is distinguished from animals primarily in this, that he can raise his mind above the things 
of earth, that he can receive the Divine Love and Wisdom of God, that he can be conjoined to 
God by love, that his love, his thought, and his whole life can be directed to Divine and eternal 
ends. One whose mind and life is not so directed is little above the animals. He is not a "man" in 
the true sense of the word. 

We read concerning the sixth day of creation in the Arcana Coelestia by Emanuel Swedenborg: 
"The sixth state is when from faith and thence from love, he speaks what is true and does what 
is good; the things which he then brings forth are called the living soul and the beast, and as he 
then begins to act at once and together from both faith and love, he becomes a spiritual man, 
who is called an image. His spiritual life is delighted and sustained by such things as belong to 
the knowledges of faith, and to works of charity which are called his food; and his natural life is 
delighted and sustained by those things which belong to his body and the senses; thence a 

 
 
 
 
 
 
 
combat arises, until love gains the dominion and he becomes a celestial ('or heavenly) man." 
Arcana Coelestia No. 12. 

What is in the above quotation called a combat involves the greatest and most bitter struggle. It 
involves the giving up of the love of the things of this world in so far as they are not of service to 
the establishing of the kingdom of God in the hearts of men. It involves giving up all things which 
are not filled with the spirit of God. 

This great change in the heart does not necessarily involve a change in a man's life as it 
appears before men, but it involves a tremendous change in a man's life as it appears in the 
sight of God. Men have to continue their work in this world, but the whole purpose behind their 
life is changed. To change the life as it appears before men is not so difficult. The great difficulty 
is to change the heart and life as it appears before God, to remove self, self-advantage from the 
center of one's life, to the circumference, and to have the center of one's life filled with the spirit 
of the Lord God. 

We stand today at one of the great crises of human history. Not since the Germanic hordes 
overran the Roman Empire, while a civilization tumbled, has such a catastrophe appeared to 
threaten civilization. Men stand confused and bewildered, and wonder what it is all about. If 
men's minds turn to God, they wonder and often doubt the wisdom of the Divine Providence. 

The Lord in His Divine Providence works for eternal ends, ends which we often can not see. 
When a civilization becomes too materialistic, when men's minds concentrate on the things of 
this world and the kingdom of God is not in the hearts and lives of mankind, civilizations tumble 
and fall, sometimes they have been entirely wiped out, and a new beginning is made usually 
with different peoples. 

Has our civilization become so materialistic, so rotten, that it is worse than useless, in the sight 
of God and the sight of heaven? This we as yet do not know. We do, however, know the words 
of God: "I will not destroy the city for the ten's sake." Gen. 8:32. Ten in the Word of God stands 
for remaining things. As long as there are some spiritually living things, some remains of 
whole-hearted love, wisdom, and life of religion, not merely formal religion, but religion from the 
very soul, so long a civilization is preserved. 

As to the danger that threatens civilization, we can do little in the sight of men. What we are 
called to do is to enter into the warfare against the materialism and greed that is in our own 
hearts. To be willing to lay down our life for the sake of the Lord, to lay down that life which we 
have loved, for the sake of the new life which the Lord has promised us. To do so we must be 
heroes. 

Many who would like to be heroes for the sake of praise and honor of men, are not heroes in 
fighting against the vanity, the pride, the greed that is in their own hearts. To be a conqueror of 
evil in the world, one must fight and conquer the passions of one's own heart. Most so-called 

 
 
 
 
 
 
 
reforms are mere vanity. Men start out to right the wrongs of the world without having heroically 
combated the vanities of their own soul. The result is that most reforms are superficial, not real, 
nor lasting. 

It is easy to rally men to the support of superficial reforms of all sorts, but to call men to the 
reform, the rebirth of the inmost springs of their own lives, falls for the most part on deaf ears. 
This is why the Writings of Swedenborg have received so little attention in the world generally. 
They do not appeal to those loving what is showy; they do not flatter men; they call for a 
purification of the heart in the presence of God, in the inner chamber of the mind, and as such 
they do not appeal to the shallow, the superficial, to those seeking the easy road; in a word they 
do not appeal to the masses of mankind. To follow these Writings involves therefore turning 
away from the popular trend. One who does this appears strange to his friends and associates. 
He finds himself lonely in the world. If one has not something of the heroic in his nature, he will 
not be impressed by the genuine things of religion. It is easy to be a hero in the sight of men by 
fighting for what all men praise. The real hero is one who stands alone and fights for what is true 
in his own soul, in the sight of God, and having conquered, is willing to fight for what is 
unpopular, even when it brings upon him derision or mockery, the despising of the many. 

The life of the true man, the man in the image and likeness of God, is a life which is an inner 
image and likeness of the life of the Lord while on earth. He was in the Prophets called a hero 
and mighty man, and we are heroes in so far as we receive His spirit within us. His heroism was 
not the heroism of the world. His heroism was in condemning what was evil and false, what was 
hypocritical, even though it led to His death and resurrection. 

Though a man must fight as a hero, he must know that he does so solely from the power of the 
Lord God and not from any power of his own. He therefore ascribes the victory to the Lord. 

The Lord's love was the Divine Love of the salvation of the human race, not a love of the 
salvation of the human race by changing its external institutions, but a salvation which consisted 
in changing the heart of man. Insofar as one is in the Lord and the Lord in him, so far a man 
also is in the love of the salvation of the human race, not only a temporal and external salvation, 
but an internal salvation by the change of the heart and spirit. A man must at times fight against 
the external evils of the world, but this by itself is only a temporary stop-gap. If the evils of the 
heart and spirit are not overcome, there is no permanent salvation.

---
~~~

== The Seventh Day 

Rest after combat. 

"And on the seventh day God finished His work which He had made; and He rested from all His 
work which he had made." Gen. 2:2. 

The six days of the spiritual creation of man are called days of labor, that is, days of combat. 
These days are followed by a day of rest, of peace. As we said in our last lecture scarcely 
anyone arrives at this state of life. It is therefore difficult to illustrate its nature. We can only get 
some idea from analogous states of peace and rest that follow combat. After a great war when 
the victory has been won and peace comes, what a great joy fills the heart! So it is with a man. 
After fighting and overcoming in the spiritual warfare against what is evil and false, the rest and 
peace bring with them a great joy that fills the heart. 

Man must fight against the evil and false things of his own heart and having overcome, fight 
against what is evil and false in his surroundings. By overcoming what is selfish in one's own 
heart, by fighting against pride, vanity, greed, one comes into a genuine love of God and the 
neighbor, into a true and noble life. 

In this spiritual warfare a man must not hang down his hands. He must be faithful unto death. 
He must fight as if from himself, but he must know, acknowledge and believe that he fights 
against the powers of evil from the Lord God and not from any power of his own. 

Much is said in the Writings of Swedenborg about the "as of itself", or the "as if of one's self". 
This is indeed one of the most unique and important teachings in the Writings of Swedenborg 
and is the only possible explanation of the old controversy between Catholics and Protestants. 

The Protestants said that the Catholics made the works of man meritorious, that the Lord alone 
saved man, and that we can not save ourselves by our own power by doing works of charity, 
which would be meritorious. The Writings of Swedenborg agree with the Protestant Churches in 
saying that man can not merit heaven by works of charity, but they disagree with the Protestant 
dogma of salvation by faith alone, apart from works of charity. The Writings of Swedenborg 
teach that a man must not hang down his hands and leave all to God, but that he must act as if 
of himself. He must fight against evil and do good entirely as if he did it from himself, but he 
must at the same time acknowledge that in so far as what he does is genuine, he acts from the 
Lord, from His Divine power and not from himself. 

We read in the Gospels: "There is none good but one, that is God; but if thou wilt enter into life 
keep the Commandments." Matt. 19:17. If there is only one who is good, namely God, how can 

 
 
 
 
 
 
 
 
man who is not good keep the Commandments? Or why should the Lord command man to 
keep the Commandments if he can not do so? The only possible explanation of this is that man 
can receive the power and will of the Lord in his heart and act from this, thus act from God, 
although acting as if of himself. 

It is evident that if man hung down his hands and did nothing but say he had faith, he would 
become as it were dead or act like an automaton. He would not be a man whom God could love 
and who could love God. A man's life consists in his loving, thinking and acting as if of himself. 
Take this away and nothing of human life is left. God to all appearances leaves it to man to act 
from himself. This is the supreme gift of God to man. But man may know that he acts from the 
power of God. 

Man can use the gifts of God and at the same time acknowledge and believe that they are the 
gifts of God, or he may claim or as it were steal these gifts which God continually gives to man; 
he can claim them to himself and abuse them. God gives to man the power to use these gifts as 
of himself or to abuse them, that is, God gives to man free choice. This is represented by the 
two trees in the Garden of Eden, the tree of life and the tree of the knowledge of good and evil. 

A man from the Word of God may know that all that is good, all that is true is of God, and from 
the presence of God, but he does not feel this. He feels that life and all things of life are his own. 
It is of the mercy of God that he should so feel, for apart from this he would not feel the joy of 
life. 

In the first six days of creation a man indeed knows that all that is good and all that is true is 
from God, but because he does not feel this, he does not entirely believe it, believe it to his very 
bones. He has to fight so hard that he does not often reflect on the presence of God; but if he 
arrives at the seventh day, he comes to actually feel this. He perceives and feels that what he 
does is done from the power of God within him, and feeling the presence of God, he comes into 
rest, into peace. 

Let us illustrate this by an example: A musician if he is to become a real musician must work 
and struggle. He must master the technique of music. He must acquire a mastery of his subject. 
After having done this he may receive an inspiration. He may come to realize, to feel that all that 
is valuable in music comes from inspiration. Yet he would never have received the inspiration 
unless he had first gone through the labor and hard work required. On looking back he may also 
see that an inspired love gave him the will and energy to master the difficulties so that the time 
came that inspiration had full play. 

It is the same on the seventh day of man's spiritual creation. On looking back man can see how 
the Lord has guided him, led him, given him courage, given him strength and the will to persist, 
in a word has labored for him in a way that man was not aware of at the time, and could not 
have been aware of. It is obvious that if a man hangs down his hands and does nothing but say 

 
 
 
 
 
 
he believes, the victory will not be won. To hang down one's hands would be to refuse the gift of 
God, to hide one's talent in a napkin. 

If a man refuses the gifts of God, if man does not accept the powers which God gives him, God 
will not force these upon him. But while man must labor and struggle to overcome his faults, to 
overcome what is evil and false, and to do what is good and true, at the end he acknowledges 
that these struggles and labors are really the work of God, although they appear to be his own. 

In the Writings of Swedenborg the man who has reached the seventh state or day is called 
celestial or heavenly. We read: 

"When the spiritual man becomes celestial or heavenly, he is called 'the work of God', because 
the Lord alone has fought for him, and has created, formed and made him; and therefore it is 
here said, 'God finished His work on the seventh day', and twice that God 'rested on the seventh 
day'". Arcana Coelestia No. 88. 

If a man has fought, labored, and struggled to order his life, changed his life so that it has 
become a life in the image and likeness of God, and has finally come to the feeling and 
perception that this labor and struggle is from the presence and power of the Lord in him, he 
comes into the fullness of life and freedom; but he could never come into this fullness of life 
unless he had struggled as if of himself. This may again be compared to a musician, who having 
by struggle overcome and mastered the difficulties of his calling, receives inspiration, hears 
music in his soul and gives it free expression. He then is in the freedom and joy of the music, 
which he feels is inspired into him. If he had not struggled and labored as if of himself, he could 
never have felt this joy. 

There are three words frequently used in the Writings of Swedenborg which it is necessary to 
explain, namely, "spiritual", "celestial", and "perception". 

By spiritual is meant the spirit of truth; a man who lives in the spirit of truth is called spiritual. 
Such a man does not regard the letter only but the spirit of truth and he lets this spirit guide all 
things of his life. A man comes into the full spirit of truth, that is he becomes fully a spiritual man, 
on the sixth day of creation. 

On the seventh day he is said to become a "celestial" or heavenly man. The celestial man is one 
who is in the fullness of Divine Love, a fullness of love to God and the neighbor. This celestial or 
heavenly love is a dwelling in the mercy of God. It is a love which looks to the Lord God and 
from looking to the Lord God looks to what is eternal in the things of life. It looks to the salvation 
of the human race, a salvation from Divine Love. When a man is filled with such a love, he is at 
rest or at peace. Things that are merely temporal, things of the world, no longer trouble or 
distress him, do not disturb his mind, for he lives in the Divine Love which looks to the eternal 
salvation of the human race, a salvation which consists in turning the heart to God. The love for 
such a salvation is so great that time is of little importance; the difficulties, the sorrows of life are 

 
 
 
 
 
 
 
overshadowed by the living presence of the love of God, which he perceives working towards 
eternal ends in ways that other men can not see or feel. 

Concerning the seventh day of creation we read: "A dead man (spiritually) when in combat 
almost always yields, and when not in combat, evils and falsities have dominion over him, and 
he is a slave. His bonds are external, such as the fear of the law, of the loss of reputation, of 
wealth, of gain, and of the reputation which he values for their sake. The spiritual man is in 
combat, but is always victorious; the bonds by which he is restrained are internal, and are called 
bonds of conscience. The celestial or heavenly man is not in combat, and when assaulted by 
evils and falsities, he despises them, and is therefore called a conqueror. He is apparently 
restrained by no bonds, but is free. His bonds, which are not apparent, are perceptions of the 
good and the true." Arcana Coelestia No. 81. 

Here we have described the three kinds of men, first the spiritually dead, who is guided in his 
life by merely material ends, the desire for wealth, power, friendship, praise, anything which 
flatters his vanity. Nothing pleases such a one but that which gives him self-satisfaction. He may 
indeed appear to be a good citizen, and perhaps a good churchman, but he appears this 
because he loves to act and speak in such a way that men will speak highly of him and say 
what a fine man he is. Thus no matter how generous and kindly he may appear, he is animated 
by vanity and egotism. Such a man the Lord said is a slave, for he is carried here and there by 
vain emotions, by impulses over which he has no control. 

The spiritual man is of an entirely different nature. The spiritual man has principles of truth, and 
a conscience which guides him and by which he guides his life. He is not carried here and there 
by passions, feelings, disordered emotions like a vile slave. He has within himself a mastery, 
because he has something higher by which he is master of himself. He has a firmness and 
strength and does not let himself be carried away by blind emotions and impulses, nor does he 
let himself be swayed by mass reactions, by popular trends, by blind impulses; in a word, he is a 
man. 

The spiritual man is indeed at times in temptations. He holds the mastery over his disordered 
emotions, his inordinate impulses, by a force of character. He severely disciplines the things of 
his own life. Thus he is victorious. 

The celestial or heavenly man, the man of the seventh day of spiritual creation is different. He is 
one who has already conquered in the things of life and is free. He is one who is no longer 
troubled by selfishness, vanity, pride, the desire of the things of this world; for having 
conquered, he is so filled with the Divine Love of God and of mankind, that this love is as it were 
the whole of his life, his only joy. He is so filled with this love that he can not think of acting from 
any other motive. He is thus a sabbath of rest. He is in the peace of God. His only bonds are 
perceptions of what is good and true. To perceive in this sense is to feel what is good and true 
from the presence of God, and not only to feel but to feel with the greatest delight and joy. 

 
 
 
 
 
 
There are indeed few who arrive at this seventh state of regeneration, so few that we have to 
form our conceptions of such a man from an idea of what a man would be like if filled with the 
love and spirit of God, rather than from experience. The Divine Providence, the Divine Love of 
the Lord looks to the time when on earth such men will not be so exceedingly rare. 

In these lectures we have treated of the seven days of creation. Only a few things of the 
profound secrets involved have been presented. For the Word of God contains an infinite depth 
of wisdom. 

Of the relatively few things here presented, a real and living understanding can be had only to 
the extent that they are applied to life. A man who has not gone through some of the profound 
experiences described in these days of creation can have only a superficial knowledge. All 
profound knowledge is based on a living experience. 

In so far as we are led through these days of creation by our Lord and Saviour, so far the 
wonder of their meaning will open up to us. 

 
 
 
